### PR TITLE
[serve] skip failure test on windows

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

Skip `test_replica_actor_died` on windows.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
are we skipping the right tests; the test failures are https://github.com/ray-project/ray/issues/46032 and https://github.com/ray-project/ray/issues/46027

**Comment by zcin** [comment]
yes, this test skips the failing test in `test_failure.py`. `test_controller_crashes` actually runs a series of tests with a feature flag set, one of which is also `test_failure.py`, which is why `test_controller_crashes` is showing up as failing.

**Review by can-anyscale — APPROVED** [review]

**Comment by can-anyscale** [comment]
would love some review from @GeneDer and @edoakes

**Review by GeneDer — APPROVED** [review]
:shipit:

**Review by edoakes — APPROVED** [review]

**Pull request merged**
