### PR TITLE
Tune transfer buffer size

### PR DESCRIPTION
**Pull request by pcmoritz**
This PR is supposed to address one problem that we have seen while testing Ray's data plane, namely that data transfers are not using the full network bandwidth. This PR addresses the problem by resizing the transfer buffer size. The new value has been determined by running the following test on EC2: Two m5.4xlarge nodes were started, `iperf` gave the following measurement for the network speed between them:
```
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 0.9 sec  1.00 GBytes  9.71 Gbits/sec
```

For different values of the `buf_size`, I put an object into the object store by using a driver on one node via 
```
In [4]: import numpy as np

In [5]: a = (255 * np.random.random(100 * 1000 * 1000)).astype(np.uint8)

In [6]: x = ray.put(a)

In [7]: x.id()
Out[7]: b'\x83\xfd:\x97\x1a\xa5\xff7t\xff(\n\xe0\x1e\xa6\xa5\xbe>\xd7\xe2'
```
and then getting it from  a driver on the second node, via
```
In [6]: x = ray.local_scheduler.ObjectID(b'\x83\xfd:\x97\x1a\xa5\xff7t\xff(\n\xe0\x1e\xa6\xa5\xbe>\xd7\xe2')

In [7]: %time ray.get(x)
```

The results are as follows (the buffer size is multiples of the pagesize which is 4KB):

```
4 * 1024 * 1024: 8.3 Gbit/s (for 100MB and 1GB objects)

400 * 1024: 9.1 Gbit/s (for 100MB) , 9.4 Gbit/s (for 1GB)

40 * 1024: 8.3 Gbit/s (for 100MB and 1GB objects)

4 * 1024: 6.9 Gbit/s (for 100MB)
```
So a buffer size attains close to the maximum measured by iperf.

cc @robertnishihara @elibol @atumanov @ericl

### CODE REVIEW

**Comment by robertnishihara** [comment]
#1325

**Comment by robertnishihara** [comment]
@invictusjs It would be good to also get your thoughts on this (or whether it could cause problems). Basically, when transferring an object from plasma manager A to plasma manager B (on two separate machines), the objects are sent over the network in chunks of `buf_size_` bytes. Relevant lines are https://github.com/ray-project/ray/blob/4a2d62e7efce3a38dabf1b08a868c6086f38811e/src/plasma/plasma_manager.cc#L546-L550.

So, we're currently calling `write` on pieces of size 4KB at a time. This PR is changing that number (potentially to 400KB).

@elibol Didn't you experiment with a benchmark in C where you call `write` in a loop and `read` on the other end. Did varying the chunk size from 4KB to 400KB cause any performance change? If not, any idea why it would make a difference in this setting?

**Potential problems.** It seems like this could make the call to `write` more likely to fail, since there may have to be more space in various buffers. The benchmarks done in this PR are in the case with no contention and only one object being transferred.

**Comment by robertnishihara** [comment]
@yaroslavvb FYI

**Comment by ericl** [comment]
It seems weird that throughout can degrade with large enough buffer sizes, do you have an idea why?

I wonder if the following experiment makes sense: keep the 4k batch size, but write and read N chunks at a time (synchronously) instead of 1. This should tell us whether it is the size of the write call that matters or whether it is the event loop that is affecting performance.

**Comment by robertnishihara** [comment]
@elibol you did that experiment, right? Can you share the code?

**Comment by robertnishihara** [comment]
I just tried the changes from this PR and timed the transfer of a single large object. `iperf` achieves **11.1Gbit/s**.

100MB achieves **5.8Gbit/s**
1GB achieves **8.5Gbit/s**
10GB achieves **9.3Gbit/s**

Unfortunately the performance for 100MB and smaller is not great (10MB is only **3.6Gbit/s** and 1MB is **2.21Gbit/s**).

**Comment by elibol** [comment]
Yes, I think it's strange that throughput degrades as buffer size increases. In some experiments I ran, bigger object sizes triggered the "double transmission" bug (a retry was triggered). This **may** be why we're seeing slower times for larger buffer sizes.

@pcmoritz just out of curiosity, did you happen to record transmission times for 4096?

Here is the c code I used to run c socket tests, w/ results: https://github.com/ucbrise/dsgd_proto/tree/master/experiments/c_socket

**Comment by yaroslavvb** [comment]
PS, older versions of GRPC library have similar problem where throughput degrades). Discussion in https://github.com/tensorflow/tensorflow/issues/6116 . I think the problem was that large message ended up triggering several "grow the buffer" commands which copied some bytes more times than necessary

**Comment by pcmoritz** [comment]
@elibol Yeah, the results for 4096 is the last entry in the table

**Comment by elibol** [comment]
iperf (transferring over 10 seconds): **11.1Gbits/s**

Averaging over 100 iterations, I get two different sets of results depending on whether I `ray.wait` after each iteration, or if I let all iterations run through and `ray.wait` on the last result.

### wait on final iteration
* 100MB achieves **10.4Gbps**
* 1GB achieves **10Gbps**

### wait per iteration
* 100MB achieves **5.9Gbps**
* 1GB achieves **8Gbps**

I think this explains the difference in results.

Regardless of waiting, I am seeing `400 * 1024` perform competitively against `4 * 1024` for small object sizes (from 10bytes to 1mbyte):
small_objects

Code: https://gist.github.com/elibol/9e1b54ee833a80d2ff54f17841a40a2a

**Comment by ericl** [comment]
From the timestamp logs it looks like large chunk transfers exhibit several hundred ms pauses on the receiving end _between transfers_, which slows down the transfer. In all cases there are also 1us delays between each each chunk read/write, which is 20-30% overhead in the event loop when using small chunks. I think these event loop delays alone can explain the overhead -- small chunks have lots of 1us delays, and large chunks cause large delays.

I would look into why the event loop is behaving this way; probably it can be debugged with more prints or something. Particularly the 1us delays between write ops, that's quite suspicious. Maybe there's some mis-configuration of the event loop to sleep 1us?

**Comment by robertnishihara** [comment]
@elibol @pcmoritz since we just released 0.3.1, now would probably be a good time to get this merged. @elibol what do you think the best bufsize is? If I understand correctly, we've done all of our benchmarking in the setting with a single large object. Can we do some testing first to verify that performance doesn't get hurt in other settings (e.g., small objects, many objects, etc). Do you think there are any workloads where this will perform worse than the current bufsize?

My current understanding is that the reason there is a benefit to using a larger bufsize is that it involves fewer passes through the event loop when transferring an object. The event loop is a bit slow because it involves getting the current time or something like that in each pass through. Is this correct?

**Comment by elibol** [comment]
@robertnishihara I think what @pcmoritz is proposing with this PR is stable based on the testing I've done thus far. I agree that more thorough testing needs to be done with different workloads and different operating systems. Assuming the branch is stable, performance ought to be compared against `master`. I don't expect this buffer size to perform worse than the existing buffer size for small object sizes on Linux systems (see my comment from 12/21/17).

I think your current understanding of why there is an improvement with bigger buffer sizes is correct. Additionally, based on unidirectional object transmission tests done on the threaded plasma manager branch, buffer size seems to have an impact on performance independent of event loop overhead.

**Comment by robertnishihara** [comment]
Right, I'm more concerned about the setting with many large objects as well as many small objects and many clients. Can you think of any scenarios where this might be worse?

**Review by elibol — APPROVED** [review]
Based on testing and offline discussions about various workload scenarios, we've concluded that this branch is okay to merge.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
