### PR TITLE
[core][state] Task Backend - reduce lock contention on debug stats / metric recording on counters. 

### LINKED ISSUE #32202: [core/tune] Performance regression in tune_scalability_bookkeeping_overhead
Bisection revealed that the offending commit is either https://github.com/ray-project/ray/commit/d74e4c42ebd03d8ce274a84591043bd004c7b522 or https://github.com/ray-project/ray/commit/b2c5e63bf7df2b105dbdcaeb558c682c9103712f.

d74e4c42ebd03d8ce274a84591043bd004c7b522 Started failing: https://buildkite.com/ray-project/release-tests-branch/builds/1349#_

But 47bb652de59e0fc7fde26262b48918cdd7ffa64c passed: https://buildkite.com/ray-project/release-tests-branch/builds/1348#018614a4-c26b-48cb-8f95-b9afaef8aa9f

The test starts 10k trials and measured time until completion. It should finish below 600 seconds but started taking ~1000 second after the offending commit.

### PR DESCRIPTION
**Pull request by rickyyx**
Signed-off-by: rickyyx <rickyx@anyscale.com>

## Why are these changes needed?
When `GcsTaskManager` is busy processing task events, it is not supposed to slow down the GCS. However, we previously have mutexes protecting some of the counter states. So the main io service/thread will get blocked when trying to acquire locks to print debug states + record metrics + add telemetry data. 

```
Global stats: 196276 total (5 active)
Queueing time: mean = 5.255 ms, max = 4.545 s, min = -0.000 s, total = 1031.389 s
Execution time:  mean = 295.864 us, total = 58.071 s
Event stats:
....
        GCSServer.deadline_timer.debug_state_dump - 85 total (1 active), CPU time: mean = 521.750 ms, total = 44.349 s
        GCSServer.deadline_timer.debug_state_event_stats_print - 15 total (1 active, 1 running), CPU time: mean = 404.255 ms, total = 6.064 s
....

```
This PR 
1. introduced a thread-safe wrapper on `CounterMap`, such that modifying and reading various debug counters will have minimal lock contentions. Also merged the count by task type for telemetry into the counter map. This way, we will not need to acquire locks at various places. 
2. With access to counters thread-safe now, we could also remove the mutex locks on the `GcsTaskManagerStorage` since it's now thread-safe (only accessed from its dedicated io thread)

    

## Related issue number

Closes https://github.com/ray-project/ray/issues/32202

## Checks
https://buildkite.com/ray-project/release-tests-pr/builds/27896#_

image

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
Can we get this reviewed and merged ASAP? This is on the critical path for a release test run and handoff to product.

**Comment by rickyyx** [comment]
Fixing the tsan test.

**Comment by rickyyx** [comment]
Together with changes from https://github.com/ray-project/ray/pull/32251 it is still rather slow on the `stress_test_many_tasks` test if I increased the buffer size to 1M and keep the batch size as 10k. 

Trying a batch size of 1k to see if it helps.

**Review by rkooo567 — APPROVED** [review]
I think this looks good now, but for the maintainability perspective, I think we should make the whole class thread-safe (IMO partially thread-safe class like this is the worst for maintainability). E.g., if someone touches states within `Stop`, `OnJobFinished`, or the storage class, it can cause random issues that are difficult to debug. 

So let's merge it first and make another PR to make the whole class thread-safe.

**Comment by rkooo567** [comment]
ping me when tests pass

**Comment by rickyyx** [comment]
I guess making the whole class thread-safe is not hard. I could add a bunch of mutexes there.

**Pull request merged**
