### PR TITLE
[Tests] Skip autoscaler tests on Windows

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* Since we do not support most of autoscaler on windows, we can just skip those tests to:
  a) decrease test time 
  b) remove a bunch of tests marked as `pytest.mark.skipif(sys.platform == "win32")`

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ijrsvt** [comment]
@ericl @richardliaw 
What are your thoughts on this?

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Seems like a sensible cleanup!

**Comment by AmeerHajAli** [comment]
@ijrsvt , what is the status of this?

**Comment by ijrsvt** [comment]
@AmeerHajAli wanted to re-run a test

**Pull request merged**
