### PR TITLE
[ci] skip uploading logs on non-postmerge pipeline

### PR DESCRIPTION
**Pull request by aslonnie**
so that the tests can run on premerge when not triggered by PR.

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
test run: https://buildkite.com/ray-project/premerge/builds/2642

**Comment by aslonnie** [comment]
new test run: https://buildkite.com/ray-project/premerge/builds/2648

**Comment by aslonnie** [comment]
finally merge-able after 3 attempts..

**Pull request merged**
