### PR TITLE
[WIP] Implement Ape-X distributed prioritization

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

This implements https://openreview.net/forum?id=H1Dy---0Z for testing. The main ideas from Ape-X are:
- Worker-side prioritization: rather than take new samples as max priority, prioritize them in workers. This scales experience gathering.
- Per-worker exploration: Rather than choosing a single exploration schedule, assign each worker a different exploration value ranging from `0.4` to `~0.0`.

WIP: evaluation on pong. This implementation probably doesn't scale to very high sample throughputs, but we should probably be able to see some gains on a couple dozen workers.

### CODE REVIEW

**Comment by richardliaw** [comment]
I took a look at the Ape-X paper just now; why do we need multiple environments on each evaluator?Wouldn't this work if we added a global replay buffer actor and made the optimizer into the learner?

**Comment by ericl** [comment]
I wouldn't read too much into this PR for now, that was just an experiment.

**Comment by richardliaw** [comment]
```yaml
cluster_name: apex
min_workers: 0
max_workers: 0
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
    type: aws
    region: us-east-1
    availability_zone: us-east-1c
auth:
    ssh_user: ubuntu
head_node:
    InstanceType: p3.2xlarge
    ImageId: ami-e07e779a
worker_nodes:
    InstanceType: m4.16xlarge
    ImageId: ami-e07e779a
    InstanceMarketOptions:
        MarketType: spot
file_mounts: {
    # "/tmp/apex_sha": "/home/eric/Desktop/ray-private/.git/refs/heads/apex",
}
setup_commands:
    - pkill -9 python || true
    - test -e ray || git clone https://github.com/ericl/ray.git
    - cd ray && git stash; git fetch && git checkout e2c31b2f81ee
    - sudo apt-get update && while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done && sudo apt-get -y upgrade
    - source activate tensorflow_p27 && sudo apt-get install -y cmake pkg-config build-essential autoconf curl libtool unzip python # we install python here because python2 is required to build the webui
    - source activate tensorflow_p27 && conda uninstall -y libgcc gcc && pip install cython && cd ray/python && pip install -e .
head_setup_commands:
    - pip install boto3==1.4.8  # 1.4.8 adds InstanceMarketOptions
worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - ray start --head --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - ray stop
    - ray start --redis-address=$RAY_HEAD_IP:6379

**Comment by richardliaw** [comment]
credit solution to this thread -`https://discuss.pytorch.org/t/failed-when-trying-to-install-pytorch-from-source/8603`

**Comment by ericl** [comment]
Closing this in favor of https://github.com/ray-project/ray/pull/1604

**Pull request closed without merging**
