### PR TITLE
Update ray.serve.deployment overloaded signature

### PR DESCRIPTION
**Pull request by willfrey**
`mypy` complains about the overloaded definition for `ray.serve.deployment(...)` not accepting the `route_prefix` parameter. This should fix that.

I've opted to use `...` instead of a default value for the overloaded signature as per [the suggestion in the `mypy` documentation.](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Hi @willfrey thank you for your contribution! Looks like the default value still matter here as it failed a relevant test:
```
"/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/python/ray/dashboard/test_snapshot.runfiles/com_github_ray_project_ray/python/ray/dashboard/modules/snapshot/tests/test_snapshot.py", line 12, in <module>
--
  | from ray import serve
  | File "/ray/python/ray/serve/__init__.py", line 2, in <module>
  | from ray.serve.api import (start, get_replica_context, shutdown, ingress,
  | File "/ray/python/ray/serve/api.py", line 958, in <module>
  | _graceful_shutdown_timeout_s: Optional[float] = None
  | File "/opt/miniconda/lib/python3.6/typing.py", line 682, in inner
  | return func(*args, **kwds)
  | File "/opt/miniconda/lib/python3.6/typing.py", line 845, in __getitem__
  | arg = _type_check(arg, "Optional[t] requires a single type.")
  | File "/opt/miniconda/lib/python3.6/typing.py", line 374, in _type_check
  | raise TypeError(msg + " Got %.100r." % (arg,))
  | TypeError: Optional[t] requires a single type. Got (<class 'str'>, <enum 'DEFAULT'>).
```

**Comment by willfrey** [comment]
Hi @simon-mo—weird, `@overload`-decorated signatures shouldn't impact runtime behavior.

I changed the default from `...` to `DEFAULT.VALUE` for the signature. Hopefully that makes the test pass!

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Fix tests

**Pull request merged**
