### PR TITLE
Update arrow to latest master

### PR DESCRIPTION
**Pull request by pcmoritz**
This includes the following changes:

Serialization fix for Python 2 integers: https://github.com/apache/arrow/pull/2055
Plasma performance improvements: https://github.com/apache/arrow/pull/2056, https://github.com/apache/arrow/pull/2015, https://github.com/apache/arrow/pull/2022
PyTorch 0.4 Tensor serialization fix: https://github.com/apache/arrow/pull/2033

### CODE REVIEW

**Comment by robertnishihara** [comment]
Looks like there are compilation errors on Mac

```
[ 44%] [32mBuilding CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_directory.cc.o[0m

[1m/Users/travis/build/robertnishihara/ray-private-travis/src/ray/object_manager/object_store_notification_manager.cc:19:60: [0m[0;1;31merror: [0m[1m'kDeprecatedPlasmaDefaultReleaseDelay' is deprecated: PLASMA_DEFAULT_RELEASE_DELAY is deprecated [-Werror,-Wdeprecated-declarations][0m

      store_client_.Connect(store_socket_name.c_str(), "", PLASMA_DEFAULT_RELEASE_DELAY));

[0;1;32m                                                           ^

[0m[1m/Users/travis/build/robertnishihara/ray-private-travis/thirdparty/pkg/arrow/cpp/build/cpp-install/include/plasma/client.h:39:46: [0m[0;1;30mnote: [0mexpanded from macro 'PLASMA_DEFAULT_RELEASE_DELAY'[0m

#define PLASMA_DEFAULT_RELEASE_DELAY plasma::kDeprecatedPlasmaDefaultReleaseDelay

[0;1;32m                                             ^

[0m[1m/Users/travis/build/robertnishihara/ray-private-travis/thirdparty/pkg/arrow/cpp/build/cpp-install/include/plasma/client.h:38:19: [0m[0;1;30mnote: [0m'kDeprecatedPlasmaDefaultReleaseDelay' has been explicitly marked deprecated here[0m

constexpr int64_t kDeprecatedPlasmaDefaultReleaseDelay = 64;

[0;1;32m                  ^

[0m1 error generated.
```

**Comment by robertnishihara** [comment]
Also, this looks related (it happened a couple times on private travis).

```
======================================================================
FAIL: testLocalSchedulerFailed (__main__.ComponentFailureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/component_failures_test.py", line 200, in testLocalSchedulerFailed
    True)
  File "test/component_failures_test.py", line 182, in check_components_alive
    self.assertTrue(component.poll() is None)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 9 tests in 62.892s

FAILED (failures=1)
```

**Comment by robertnishihara** [comment]
There's still a linting error

```
ObjectStoreNotificationManager::ObjectStoreNotificationManager(
     boost::asio::io_service &io_service, const std::string &store_socket_name)
     : store_client_(), socket_(io_service) {
-  ARROW_CHECK_OK(
-      store_client_.Connect(store_socket_name.c_str(), "", plasma::kPlasmaDefaultReleaseDelay));
+  ARROW_CHECK_OK(store_client_.Connect(store_socket_name.c_str(), "",
+                                       plasma::kPlasmaDefaultReleaseDelay));
```

**Comment by robertnishihara** [comment]
Unfortunately this is still happening on Linux

```
======================================================================
FAIL: testLocalSchedulerFailed (__main__.ComponentFailureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/component_failures_test.py", line 200, in testLocalSchedulerFailed
    True)
  File "test/component_failures_test.py", line 182, in check_components_alive
    self.assertTrue(component.poll() is None)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 9 tests in 62.430s

FAILED (failures=1)
```

**Comment by pcmoritz** [comment]
The test failure is caused by this segfault I think:

```
Program received signal SIGSEGV, Segmentation fault.
std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >::unique_ptr(std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >&&) (
    __u=<optimized out>, this=0x800000000) at /usr/include/c++/5/bits/unique_ptr.h:464
464	      : _M_t(__u.release(), std::forward<deleter_type>(__u.get_deleter())) { }
(gdb) bt
#0  std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >::unique_ptr(std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >&&) (
    __u=<optimized out>, this=0x800000000) at /usr/include/c++/5/bits/unique_ptr.h:464
#1  __gnu_cxx::new_allocator<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > >::construct<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >, std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > >(std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >*, std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >&&) (__p=0x800000000, this=0x2636cc0) at /usr/include/c++/5/ext/new_allocator.h:120
#2  std::allocator_traits<std::allocator<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > > >::construct<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >, std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > >(std::allocator<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > >&, std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >*, std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >&&) (
    __p=0x800000000, __a=...) at /usr/include/c++/5/bits/alloc_traits.h:530
#3  std::deque<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >, std::allocator<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > > >::emplace_back<std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> > >(std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >&&) (
    this=0x2636cc0) at /usr/include/c++/5/bits/deque.tcc:155
#4  plasma::PlasmaStore::push_notification (this=this@entry=0x2631d60, object_info=object_info@entry=0x2638f78)
    at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:633
#5  0x000000000041124f in plasma::PlasmaStore::seal_object (this=this@entry=0x2631d60, object_id=..., 
    digest=digest@entry=0x7ffc5d1d39a0 "\001\253,\271cT", <incomplete sequence \352>) at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:439
#6  0x0000000000411a34 in plasma::PlasmaStore::process_message (this=0x2631d60, client=<optimized out>) at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:727
#7  0x0000000000413979 in plasma::PlasmaStore::<lambda(int)>::operator() (events=<optimized out>, __closure=<optimized out>)
    at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:524
#8  std::_Function_handler<void(int), plasma::PlasmaStore::connect_client(int)::<lambda(int)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/ubuntu/ray/python/ray/core/src/plasma/plasma_store, CU 0x0, DIE 0x82032>) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/5/functional:1871
#9  0x00000000004181da in std::function<void (int)>::operator()(int) const (__args#0=1, this=<optimized out>) at /usr/include/c++/5/functional:2267
#10 plasma::EventLoop::FileEventCallback (loop=<optimized out>, fd=<optimized out>, context=<optimized out>, events=<optimized out>)
    at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/events.cc:28
#11 0x0000000000433eb0 in aeProcessEvents (eventLoop=eventLoop@entry=0x2624cc0, flags=flags@entry=3)
    at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/thirdparty/ae/ae.c:412
#12 0x00000000004342cb in aeMain (eventLoop=0x2624cc0) at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/thirdparty/ae/ae.c:455
#13 0x0000000000418388 in plasma::EventLoop::Start (this=<optimized out>) at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/events.cc:69
#14 0x000000000040d2a5 in plasma::PlasmaStoreRunner::Start (use_one_memory_mapped_file=false, hugepages_enabled=false, directory="P;\035]", system_memory=<optimized out>, 
    socket_name=0x7ffc5d1d51d4 "/tmp/plasma_store66283217", this=0x2624c20) at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:785
#15 plasma::start_server (socket_name=socket_name@entry=0x7ffc5d1d51d4 "/tmp/plasma_store66283217", system_memory=<optimized out>, plasma_directory="/dev/shm", 
    hugepages_enabled=hugepages_enabled@entry=false, use_one_memory_mapped_file=use_one_memory_mapped_file@entry=false)
    at /home/ubuntu/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:820

```

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by richardliaw** [comment]
@pcmoritz tests look like they're passing?

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
