### PR TITLE
[Data] Restructure the user-provided optimizer rules file

### PR DESCRIPTION
**Pull request by c21**
## Why are these changes needed?

Restructure the user-provided optimizer rules into separate file to allow users to override them easily.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scottjlee — APPROVED** [review]

**Review by raulchen — APPROVED** [review]

**Comment by c21** [comment]
cc @zhe-thoughts for review. Tests are okay now.

**Review by aslonnie — APPROVED** [review]

**Comment by c21** [comment]
Waiting for CI tests now.

**Review by scottjlee — APPROVED** [review]

**Comment by c21** [comment]
Hi @zhe-thoughts - could you help review? This is to fix the release blocker. Ready to be merged.

**Review by zhe-thoughts — APPROVED** [review]
Yes this is release blocker

**Pull request merged**
