### PR TITLE
[Jobs] Return websocket response for tail_logs instead of None

### LINKED ISSUE #29632: [Dashboard] [Jobs] Jobs API request causes exception in metrics middleware
### What happened + What you expected to happen

Upon a (successful) job submit REST API call, an error appears in `dashboard.log` (see repro below).  There are no obvious symptoms, but it might be indicative of a bug in the dashboard metrics middleware, or the Job Head server might be returning the wrong kind of response.

### Versions / Dependencies

Master (Oct 24, 2022), Python 3.8, macOS

### Reproduction script

`ray start --head`

`ray job submit -- echo hello`

In `dashboard.log`:

```
2022-10-24 16:40:04,010	INFO web_log.py:206 -- 127.0.0.1 [24/Oct/2022:23:40:03 +0000] 'POST /api/jobs/ HTTP/1.1' 200 244 bytes 53028 us '-' 'python-requests/2.25.1'
2022-10-24 16:40:04,014	INFO web_log.py:206 -- 127.0.0.1 [24/Oct/2022:23:40:04 +0000] 'GET /api/version HTTP/1.1' 200 238 bytes 377 us '-' 'python-requests/2.25.1'
2022-10-24 16:40:06,023	ERROR web_protocol.py:405 -- Error handling request
Traceback (most recent call last):
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/archit/ray/python/ray/dashboard/http_server_head.py", line 122, in metrics_middleware
    status_tag = f"{floor(response.status / 100)}xx"
AttributeError: 'NoneType' object has no attribute 'status'
2022-10-24 16:40:06,030	INFO web_log.py:206 -- 127.0.0.1 [24/Oct/2022:23:40:06 +0000] 'GET /api/jobs/raysubmit_aC2SjbGKieq1dqcZ HTTP/1.1' 200 464 bytes 1604 us '-' 'python-requests/2.25.1'
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
The `tail_logs` REST API wasn't returning a Response object, causing an exception to be raised in the metrics middleware processing (see issue).  This PR returns the websocket response to fix this.

## Related issue number
Closes https://github.com/ray-project/ray/issues/29632

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Any suggestions on how to write a test to catch this kind of error in general?  It didn't have any symptoms besides the error log in `dashboard.log`.  One idea is to scan through `dashboard.log` for errors, but then the test could spuriously fail if there are other unrelated errors.

**Comment by rkooo567** [comment]
Maybe we can record all uncaught exceptions in memory and add some sanity check at the end of all tests? WE did similar things for the spilling test (we have leak_validation check at the end of every test)

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
more drasatic way is to add crashing dashboard on all uncaught exceptions and turn that on only for testing

**Comment by rkooo567** [comment]
The failuire seems related

**Comment by architkulkarni** [comment]
Tests passed a couple times, the `test_sdk` flakiness is unrelated and being fixed separately.
Doc failure unrelated

**Pull request merged**
