### PR TITLE
[Java] Add dependency reduced pom file to gitignore.

### PR DESCRIPTION
**Pull request by jovany-wang**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by chaokunyang — APPROVED** [review]
LGTM

**Comment by chaokunyang** [comment]
I'm not sure whether disabling dependency reduced pom file will make the released jar may still have guava/protobuf dependencies? @jovany-wang

**Comment by chaokunyang** [comment]
Please check it before merging this PR

**Comment by jovany-wang** [comment]
@chaokunyang @kfstorm 
I updated this PR to add it to gitignore file instead of preventing auto-gen it.

I believe @chaokunyang your concern is right.

**Pull request merged**
