### PR TITLE
[dashboard] Fix dashboard stack trace error when sudo is not found

### LINKED ISSUE #44242: [Dashboard] can not see stack trace error when sudo is not found
### What happened + What you expected to happen

When Ray runs on k8s with the images that does not install "sudo" and runs as non-root in containers, the "Stack Trace (Driver)" of the dashboard goes wrong and returns "`sudo` FileNotFound". In fact, py-spy can be used even if `sudo` is not installed. 
The code previous forget to handle the case `where the sudo` FileNotFound exception is thrown and directly returns it to the user. This PR fixes this issue, treat sudo not found as "cannot do passwordless sudo"

### Versions / Dependencies

2.9.0

### Reproduction script

None

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by owen3m**
## Why are these changes needed?
When Ray runs on k8s with the images that does not install "sudo" and runs as non-root in containers, the "Stack Trace (Driver)" of the dashboard goes wrong and returns "`sudo` FileNotFound". In fact, py-spy can be used even if `sudo` is not installed. 
The code previous forget to handle the case `where the sudo` FileNotFound exception is thrown and directly returns it to the user. This PR fixes this issue, treat sudo not found as "cannot do passwordless sudo"

## Related issue number
Closes https://github.com/ray-project/ray/issues/44242

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by anyscalesam** [comment]
@alanwguo this looks like dashboard code; do you mind taking a look?

**Review by alanwguo — APPROVED** [review]
@rkooo567 , can you review as well and merge if it looks good to you.

**Comment by JoshKarpel** [comment]
Closes #44904 as a dupe

**Comment by rkooo567** [comment]
let me take a look at the PR very soon

**Comment by anyscalesam** [comment]
@rkooo567 you'll merge?

**Pull request merged**
