### PR TITLE
[pick] [train] Add documentation for using metadata argument to save preprocessors #38701

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Pick https://github.com/ray-project/ray/pull/38701 to branch-2.7.

### CODE REVIEW

**Review by matthewdeng — APPROVED** [review]

**Comment by ericl** [comment]
```

File "<doctest data-loading-preprocessing.rst[6]>", line 43, in <module>
  | AttributeError: 'StandardScaler' object has no attribute 'serialize'
```

@matthewdeng I think you need to pick your PR first

**Comment by matthewdeng** [comment]
Ah that's right - can I take this PR over and do this sequentially? There are quite a few picks for Train, I can coordinate picking them all in order of when they were merged to master.

**Comment by ericl** [comment]
Sounds great!

**Review by zhe-thoughts — APPROVED** [review]

**Review by zhe-thoughts — APPROVED** [review]
Clean docs change

**Comment by matthewdeng** [comment]
Picked in https://github.com/ray-project/ray/pull/39105

**Pull request closed without merging**
