### PR TITLE
[Serve] [Docs] Clarify that the Serve config only supports remote URIs

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

The Serve config only supports remote URIs within its `runtime_env` for safety purposes. However, this behavior is poorly documented and only guarded by a pydantic validator with an unclear error message.

This change documents the remote URI requirements and clarifies the error message.

Behavior when you run the following config with an invalid `runtime_env`:

```yaml
import_path: fruit:graph

runtime_env: {
  "working_dir": "src"
}
```

1. Without the change:

```console
% serve run config.yaml
...
pydantic.error_wrappers.ValidationError: 1 validation error for ServeApplicationSchema
runtime_env
  Invalid protocol for runtime_env URI src. Supported protocols: ['GCS', 'CONDA', 'PIP', 'HTTPS', 'S3', 'GS', 'FILE']. Original error: '' is not a valid Protocol (type=value_error)
```

2. With the change:

```console
% serve run config.yaml
...
pydantic.error_wrappers.ValidationError: 1 validation error for ServeApplicationSchema
runtime_env
  runtime_envs in the Serve config support only remote URIs in working_dir and py_modules. Got error when parsing URI: Invalid protocol for runtime_env URI "src". Supported protocols: ['GCS', 'CONDA', 'PIP', 'HTTPS', 'S3', 'GS', 'FILE']. Original error: '' is not a valid Protocol (type=value_error)
```

## Related issue number

N/A

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - This change relies on existing tests.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Thank you!

**Review by sihanwang41 — APPROVED** [review]

**Comment by shrekris-anyscale** [comment]
Link to updated docs: https://anyscale-ray--34212.com.readthedocs.build/en/34212/serve/production-guide/config.html

**Comment by shrekris-anyscale** [comment]
The test failures are unrelated:

* `data:test_execution_optimizer` (CI failures: [1](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c71-f273-4e00-8047-a48d7655538e/1892-3164), [2](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c71-f276-4a61-8f7d-996de5b48116/1856-2885), [3](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c71-f279-4f9b-abc3-4663cb1deffd/1854-2882), [4](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c71-f27d-49fe-9b1b-aadf802231ed/1850-2878)) is failing on `master`:

Screen Shot 2023-04-10 at 5 11 19 PM

* [`learning_tests_stateless_cartpole_r2d2`](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c71-f230-4ac6-b0de-20c11d466eaa/1682-1829) is flaky on `master`:

Screen Shot 2023-04-10 at 5 13 50 PM

* [`test_task_events_2`](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c78-d71b-4246-9d4d-00910250145b/1412-2186) is flaky on `master`:

Screen Shot 2023-04-10 at 5 16 10 PM

* [`test_object_store_metrics`](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c71-f436-4906-8a01-9e3a8b6b1bc5/871-1674) is flaky on `master`

Screen Shot 2023-04-10 at 5 17 05 PM

* [`linkcheck`](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c7b-0c29-4a49-8583-7dd317ad3e04/6-4587) is failing on `master`:

Screen Shot 2023-04-10 at 5 18 30 PM

* [`Documentation`](https://buildkite.com/ray-project/oss-ci-build-pr/builds/17941#01876c78-d728-4723-950e-defc74bf30ac/1670-2069) is failing on `master`:

Screen Shot 2023-04-10 at 5 19 24 PM

**Comment by shrekris-anyscale** [comment]
@edoakes @architkulkarni this change is ready to merge.

**Pull request merged**
