### PR TITLE
[WIP] Try running in valgrind

### PR DESCRIPTION
**Pull request by pcmoritz**
after https://github.com/ray-project/ray/pull/3597 and maybe https://github.com/ray-project/ray/pull/3594 and https://github.com/ray-project/ray/pull/3592 the raylet might be valgrind clean

### CODE REVIEW

**Comment by robertnishihara** [comment]
```
$ python -m pytest -v --durations=10 test/actor_test.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-4.0.2, py-1.7.0, pluggy-0.8.0 -- /home/travis/miniconda/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/ray-project/ray, inifile:
plugins: timeout-1.3.3
collected 62 items                                                             
test/actor_test.py::test_actor_init_error_propagated /home/travis/.travis/job_stages: line 104: 16900 Aborted                 (core dumped) python -m pytest -v --durations=10 test/actor_test.py
The command "python -m pytest -v --durations=10 test/actor_test.py" exited with 134.
```

I think we need a specialized valgrind test in order to actually get out the valgrind errors.

**Comment by atumanov** [comment]
why is this closed, are we not doing valgrind or it's superseded by another PR (as per your comment above)?

**Comment by robertnishihara** [comment]
Ah we're definitely doing it! I closed it since I thought it was abandoned due to staleness, but I might be wrong about that.

**Comment by robertnishihara** [comment]
I actually intended to prioritize it for this week.

**Comment by robertnishihara** [comment]
I have a PR with this working in https://github.com/ray-project/ray/pull/3701.

**Comment by robertnishihara** [comment]
Replaced by #3811.

**Pull request closed without merging**
