### PR TITLE
[Client][Proxy] Refactor RayClient Proxy to not use additional Threads.

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* Removes hard-to-understand and unnecessary 'queue-filler-threads'.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by AmeerHajAli — COMMENTED** [review]
Is this tested somehow?

**Comment by ijrsvt** [comment]
@AmeerHajAli It is tested by the existing RayClient-Proxy tests. This is really just shuffling the internal implementation.

**Review by AmeerHajAli — APPROVED** [review]

**Comment by ijrsvt** [comment]
Failures unrelated (just a flaky Tune test).

**Comment by ijrsvt** [comment]
> Should this be cherry-picked to ray 1.4?

It is not necessary to be cherry picked for `1.4.0`.

**Pull request merged**
