### PR TITLE
[Core] Add cached memory to unsued memory in Linux/BSD

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

Cached memory should also be considered as unused memory.

When I start ray cluster in a machine that has low available mem but high buff/cache memory, a rayOutOfMemoryError is raised.

```
2020-08-10 16:26:03,954 ERROR worker.py:1085 -- Possible unhandled error from worker: ray::JobWorker.__init__() (pid=42130, ip=11.166.237.22)
  File "python/ray/_raylet.pyx", line 435, in ray._raylet.execute_task
  File "/home/admin/ray/python/ray/memory_monitor.py", line 128, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node corgiunit-eu95-5.rz00b.stable.alipay.net is used (15.59 / 16.0 GB). 
```

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            16G        5.9G        980M        3.6G        9.1G        980M
Swap:            0B          0B          0B
```

This PR has been merged but reverted because it breaks master, see <https://github.com/ray-project/ray/pull/10064>. 

And this time I fixed the problem mentioned in the reverting PR.
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by lixin-wei** [comment]
@rkooo567 Sorry for breaking the master because of my mistake. Thanks a lot for figuring it out. This time I checked `cached` attr before adding it to unused memory. could you please review this PR?

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@lixin-wei Thanks for creating a PR again :) !

**Comment by rkooo567** [comment]
Seems like test still fails with an error that `has_attr ` doesn't exist.

**Comment by lixin-wei** [comment]
> Seems like test still fails with an error that `has_attr ` doesn't exist.

fixed.

**Comment by rkooo567** [comment]
Lint failure

**Comment by virtualluke** [comment]
This will be great addition, I see this a lot.

**Comment by lixin-wei** [comment]
> Lint failure

fixed, seems I installed a wrong version of flake8

**Pull request merged**
