### PR TITLE
Reduced memory requirements in `python/ray/tests/test_reference_counting_2.py`

### PR DESCRIPTION
**Pull request by czgdp1807**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mattip** [comment]
Failures summary (non related to the changes in the PR):
run | platform | test | cause
---|---|---|---
ray-builders-pr | not relevant | summary | fails whenever a test run fails
small-and-client | public.ecr.aws/b4p2j5t6/dind:latest docker | in test_client_proxy.py | (1) test_delay_in_rewriting_environment caused RuntimeError: Proxy failed to Connect to backend
| | | | (2) test_proxy_manager_lifecycle caused RuntimeError: Unable to succeed in selecting a random port
| | | | (3) test_proxy_manager_lifecycle caused RuntimeError: Unable to succeed in selecting a random port
brain rllib learning cont actions tf2 eager tracing | bk_runner_env_pr: b3d7b7d09737e9c423da1737048f722afb32d8fa-ml docker| learning_tests_pendulum_cql | there is lots of output. I think this fails 3 times with a warning `WARNING services.py:1880 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 2684239872 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=4.46gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.`
potable water workflow and dataset tests python-3 | public.ecr.aws/b4p2j5t6/dind:latest docker | test_serialization.py | (0) same warning as above, then gets `"examples/comparisons/argo/retry_workflow.py", line 11, in flaky_step raise ValueError("oops")`
| | | | (1) setup of test_embedded_objectrefs fails to find an object when creating an error message, so the true error is not reported
| | | | (2) setup of test_embedded_objectrefs fails to find an object when creating an error message, so the true error is not reported
| | | | (3) setup of test_embedded_objectrefs fails to find an object when creating an error message, so the true error is not reported

**Comment by pcmoritz** [comment]
Hmm, I'm not very comfortable lowering the memory limits in the test cases here, I think they are an important part of the tests. Do you know why the tests can't pass currently with the higher limits? Do we need to bump some infra limit, e.g. instance size or docker container limits? cc @simon-mo

**Comment by czgdp1807** [comment]
I see. Let me try the same tests with higher hardware in order to verify the hypothesis that tests fail due to higher memory consumption.

**Comment by czgdp1807** [comment]
> Let me try the same tests with higher hardware in order to verify the hypothesis that tests fail due to higher memory consumption.

With 8 CPUs and 16 GB RAM all the tests pass in `test_reference_counting_2` passes.

**Comment by pcmoritz** [comment]
@simon-mo Is it feasible/a good idea to run the machines on a larger instance?

**Comment by simon-mo** [comment]
👋 currently the machine is m5.xlarge instance, which has 4 cores, 16G memory. however, we did set shared memory size to just 2.5g, 
```
"shm-size": "2.5gb",
```

how much should I bump it to?

**Comment by czgdp1807** [comment]
N.B. - On my machine with 4 CPUs and 8 GB RAM, the same tests here fail consistently. However, with 8 CPUs and 16 GB RAM, the same tests here pass.

**Comment by pcmoritz** [comment]
Why don't we bump it to 8 CPUs, 32 GB memory then?

**Comment by simon-mo** [comment]
Let me clarify. I think the host has enough memory. But the issue was shared memory was too small. Should we bump the shared memory side up?

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by mattip** [comment]
> however, we did set shared memory size to just 2.5g,
> `"shm-size": "2.5gb",`

@simon-mo I am confused. How does that work on windows? As far as I can tell windows only uses [`mmap`](https://docs.microsoft.com/en-us/windows/win32/memory/creating-named-shared-memory) on top of the filesystem, and has no shm-specific mounted filesystem.

**Comment by mattip** [comment]
@czgdp1807 is this the same failure mode from #21983?

**Comment by czgdp1807** [comment]
The output of `ray.init` is a `RayContext` object which has address and commit information. I am a bit confused on how copying address and commit information from 16 GB to 8 GB machine would be helpful in providing data to resolve this issue. @wuisawesome

**Comment by wuisawesome** [comment]
ah @czgdp1807 I think this recently changed. Can you run `ray.cluster_resources()["object_store_memory"]` and explicitely set that when you do `ray.init(object_store_memory=...)` on the larger machine?

**Comment by czgdp1807** [comment]
I took the output of `ray.cluster_resources()["object_store_memory"]` from 8 GB machine and applied to 16 GB. See diff below. Executed the tests and all were passing on 16 GB.

```diff
diff --git a/python/ray/tests/test_reference_counting_2.py b/python/ray/tests/test_reference_counting_2.py
index 549b4e482..840b0d188 100644
--- a/python/ray/tests/test_reference_counting_2.py
+++ b/python/ray/tests/test_reference_counting_2.py
@@ -29,7 +29,7 @@ def one_worker_100MiB(request):
         "automatic_object_spilling_enabled": False,
     }
     yield ray.init(
-        num_cpus=1, object_store_memory=100 * 1024 * 1024, _system_config=config
+        num_cpus=1, object_store_memory=1765178572.0, _system_config=config
     )
     ray.shutdown()
 
@@ -53,7 +53,6 @@ def _fill_object_store_and_get(obj, succeed=True, object_MiB=20, num_objects=5):
 
 # Test that an object containing object refs within it pins the inner IDs
 # recursively and for submitted tasks.
-@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
 @pytest.mark.parametrize(
     "use_ray_put,failure", [(False, False), (False, True), (True, False), (True, True)]
 )
@@ -107,7 +106,6 @@ def test_recursively_nest_ids(one_worker_100MiB, use_ray_put, failure):
 
 # Test that serialized ObjectRefs returned from remote tasks are pinned until
 # they go out of scope on the caller side.
-@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
 @pytest.mark.parametrize(
     "use_ray_put,failure", [(False, False), (False, True), (True, False), (True, True)]
 )
@@ -251,7 +249,6 @@ def test_recursively_pass_returned_object_ref(one_worker_100MiB, use_ray_put, fa
 # returns the same ObjectRef by calling ray.get() on its submitted task and
 # returning the result. The reference should still exist while the driver has a
 # reference to the final task's ObjectRef.
-@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
 @pytest.mark.parametrize(
     "use_ray_put,failure", [(False, False), (False, True), (True, False), (True, True)]
 )
@@ -353,7 +350,7 @@ def test_object_unpin(ray_start_cluster):
     cluster = ray_start_cluster
     head_node = cluster.add_node(
         num_cpus=0,
-        object_store_memory=100 * 1024 * 1024,
+        object_store_memory=1765178572.0,
         _system_config={"num_heartbeats_timeout": 10, "subscriber_timeout_ms": 100},
     )
     ray.init(address=cluster.address)
@@ -364,7 +361,7 @@ def test_object_unpin(ray_start_cluster):
             cluster.add_node(
                 num_cpus=1,
                 resources={f"node_{i}": 1},
-                object_store_memory=100 * 1024 * 1024,
+                object_store_memory=1765178572.0,
             )
         )
     cluster.wait_for_nodes()
@@ -456,7 +453,7 @@ def test_object_unpin_stress(ray_start_cluster):
     nodes = []
     cluster = ray_start_cluster
     cluster.add_node(
-        num_cpus=1, resources={"head": 1}, object_store_memory=1000 * 1024 * 1024
+        num_cpus=1, resources={"head": 1}, object_store_memory=1765178572.0
     )
     ray.init(address=cluster.address)
 
@@ -466,7 +463,7 @@ def test_object_unpin_stress(ray_start_cluster):
             cluster.add_node(
                 num_cpus=1,
                 resources={f"node_{i}": 1},
-                object_store_memory=1000 * 1024 * 1024,
+                object_store_memory=1765178572.0,
             )
         )
     cluster.wait_for_nodes()
@@ -552,7 +549,7 @@ def test_inlined_nested_refs(ray_start_cluster, inline_args):
     if not inline_args:
         config["max_direct_call_object_size"] = 0
     cluster.add_node(
-        num_cpus=2, object_store_memory=100 * 1024 * 1024, _system_config=config
+        num_cpus=2, object_store_memory=1765178572.0, _system_config=config
     )
     ray.init(address=cluster.address)
 
@@ -592,7 +589,7 @@ def test_return_nested_ids(shutdown_only, inline_args):
         config["max_direct_call_object_size"] = 100 * 1024 * 1024
     else:
         config["max_direct_call_object_size"] = 0
-    ray.init(object_store_memory=100 * 1024 * 1024, _system_config=config)
+    ray.init(object_store_memory=1765178572.0, _system_config=config)
 
     class Nested:
         def __init__(self, blocks):
@@ -622,9 +619,8 @@ def test_return_nested_ids(shutdown_only, inline_args):
     ray.get(test.remote())
 
 
-@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
 def test_actor_constructor_borrowed_refs(shutdown_only):
-    ray.init(object_store_memory=100 * 1024 * 1024)
+    ray.init(object_store_memory=1765178572.0)
 
     @ray.remote
     class Borrower:
@@ -644,9 +640,8 @@ def test_actor_constructor_borrowed_refs(shutdown_only):
         time.sleep(1)
 
 
-@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
 def test_deep_nested_refs(shutdown_only):
-    ray.init(object_store_memory=100 * 1024 * 1024)
+    ray.init(object_store_memory=1765178572.0)
 
     @ray.remote
     def f(x):
@@ -663,9 +658,8 @@ def test_deep_nested_refs(shutdown_only):
         r = ray.get(r)
 
 
-@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
 def test_forward_nested_ref(shutdown_only):
-    ray.init(object_store_memory=100 * 1024 * 1024)
+    ray.init(object_store_memory=1765178572.0)
 
     @ray.remote
     def nested_ref():
```

**Comment by wuisawesome** [comment]
hmmmm actually this is strange. i didn't realize the object store memories were already hardcoded. Now i'm wondering how you ended up with different object store memory than the hardcoded value...

**Pull request closed without merging**
