### PR TITLE
Docs update for Ray ecosystem -- Apache Airflow integration

### LINKED ISSUE #32699: [Ray Workflow] example of time-series dependent tasks (w/ different resolution)
### Description

First of all - this page of API comparisons is awesome: https://docs.ray.io/en/latest/workflows/comparison.html.

However, 
- it seems to be missing the time-wise dependency element in there. For example, here https://docs.ray.io/en/latest/workflows/comparison.html#airflow-api-comparison, where is the `start_date=days_ago(2)` equiv. for Ray workflow?
- would it be possible to add some more complex examples that are even closer to real-life workflows, like workflow that has tasks w/ time-series dependencies of different resolution? For example, every day some tasks run every 5 minutes, but they depend on past 5 days of some other tasks etc.

### Use case

_No response_

### LINKED ISSUE #32827: [docs] Airflow Integration example
### Description

Can we add Airflow to Ray's ecosystem? The Ray airflow provider is not updated for two years and has multiple issues

### Use case

Airflow should work as an Orchestrator for the ray cluster.

### PR DESCRIPTION
**Pull request by venkatajagannath**
## Why are these changes needed?

astro-provider-ray is python package that helps users orchestrate Ray jobs from Airflow DAGs. The new provider follows Airflow best practices to monitor current Ray jobs and get real time logs.

## Related issue number

Closes #32827
Closes #32699 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Comment by venkatajagannath** [comment]
@can-anyscale looks like merging is restricted to authorized users. Is there anything else pending on my end?

**Comment by can-anyscale** [comment]
enabled merge, thankks

**Comment by venkatajagannath** [comment]
@can-anyscale The docs on the Ray ecosystem page seem to get updated on the master and the 2.35.0 branches.

But, the latest version of the docs do not reflect the new tile. Can you please review if there is a bug in the PR?


Screenshot 2024-09-03 at 2 46 12 PM

**Comment by can-anyscale** [comment]
@venkatajagannath thanks for reporting; we missed a step during the release of ray 2.35.0; I fixed it now but it'll probably take an hour for the site to update latest

**Pull request merged**
