### PR TITLE
[RLlib] Fix flakey 100-policies LRU cache test.

### PR DESCRIPTION
**Pull request by sven1977**
Signed-off-by: sven1977 <svenmika1977@gmail.com>

Fix flakey 100-policies LRU cache test.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by kouroshHakha — APPROVED** [review]
LGTM, Can you actually for the sake of safety run the failing learning tests at least 3 times before we merge?

**Comment by kouroshHakha** [comment]
Run 1 passes.

**Comment by kouroshHakha** [comment]
@sven if you open up the test logs it still seems to be flakey. Is there any other config that makes this more stable and reliable?

**Comment by sven1977** [comment]
Thanks for checking. Yes, I'll restart these tests several times now to make sure they are more stable now. Might be I have to further relax the passing criteria a bit.

**Pull request merged**
