### PR TITLE
[tune/core] Better Resource Handling

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
 - [x] Reorder notification of resource release
 - [x] Tune - subscribe to resource release in `trial.stop` 
 - [x] Verify this works for
    - [x] mac py3
    - [ ] mac py2
    - [ ] linux py3
    - [x] linux py2

## Related issue number
#1065 

This is currently rebased off of #1541 .

### CODE REVIEW

**Comment by robertnishihara** [comment]
I wouldn't expect this to fix the latest issue in #1065. Does it? I would expect it to make the issue very slightly less common.

**Comment by richardliaw** [comment]
@robertnishihara not yet - the idea is that when trials are stopped, at the application level, I'll wait for Redis (the Redis) to update the actor field with `removed = True`, upon which the application can resume and start the next trial.

I'm trying to implement that right now (not yet pushed); thoughts welcome.

**Review by ericl — APPROVED** [review]
This is kind of terrible but I don't see a better solution for now.

**Comment by robertnishihara** [comment]
I'm hoping this will be fixed by #1668 and so won't be necessary.

**Comment by richardliaw** [comment]
Yeah I would wait for #1668 instead of merging this - after all, it doesn't actually entirely resolve the issue #1065.

**Comment by richardliaw** [comment]
Closing this for #1668

**Pull request closed without merging**
