### PR TITLE
[rllib] bug fix for rllib pettingzoo pistonball_v4 example

### PR DESCRIPTION
**Pull request by mguarin0**
## Why are these changes needed?

bug fix for rllib pettingzoo pistonball_v4 example. code was not running without this fix.

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
Hey @mguarin0 thanks for the patch! What was the behavior you were seeing before this fix? Would you be able to add a test case to `test_pettingzoo_env.py` with this behavior?

**Comment by mguarin0** [comment]
@amogkam @sven1977 this build failure does not seem to be related to my code. Is there something I should do in order to make sure these steps pass?

**Comment by amogkam** [comment]
Yes you’re right they are unrelated, so nothing you need to fix here. Will leave to @sven1977 or @richardliaw to give final review.

**Comment by mguarin0** [comment]
@sven1977 or @richardliaw do these changes look ok?

**Comment by richardliaw** [comment]
FYI @jkterry1

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Test failures look unrelated, merging -- thanks for the fix @mguarin0 !

**Pull request merged**
