### PR TITLE
[dask-on-ray] Fix Dask-on-Ray examples in docs

### LINKED ISSUE #14460: Dask on Ray documentation example doesn't run.
In the documentation page for Dask on Ray https://docs.ray.io/en/master/dask-on-ray.html, running the example

```python
import ray
from ray.util.dask import ray_dask_get
import dask.array as da
import dask.dataframe as dd
import numpy as np
import pandas as pd
import time

# Start Ray.
# Tip: If you're connecting to an existing cluster, use ray.init(address="auto").
ray.init()

d_arr = da.from_array(np.random.randint(0, 1000, size=(256, 256)))

# The Dask scheduler submits the underlying task graph to Ray.
d_arr.mean().compute(scheduler=ray_dask_get)

# Set the scheduler to ray_dask_get in your config so you don't have to specify it on
# each compute call.
dask.config.set(scheduler=ray_dask_get)

df = dd.from_pandas(pd.DataFrame(
    np.random.randint(0, 100, size=(1024, 2)),
    columns=["age", "grade"]))
df.groupby(["age"]).mean().compute()
```

fails with 
```
NameError                                 Traceback (most recent call last)
<ipython-input-1-5e88893d52b2> in <module>
     18 # Set the scheduler to ray_dask_get in your config so you don't have to specify it on
     19 # each compute call.
---> 20 dask.config.set(scheduler=ray_dask_get)
     21 
     22 df = dd.from_pandas(pd.DataFrame(

NameError: name 'dask' is not defined
```

If I fix that error, the next error I get is

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-9a278e9b1850> in <module>
     23 df = dd.from_pandas(pd.DataFrame(
     24     np.random.randint(0, 100, size=(1024, 2)),
---> 25     columns=["age", "grade"]))
     26 df.groupby(["age"]).mean().compute()

~/opt/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/io.py in from_pandas(data, npartitions, chunksize, sort, name)
    199 
    200     if (npartitions is None) == (chunksize is None):
--> 201         raise ValueError("Exactly one of npartitions and chunksize must be specified.")
    202 
    203     nrows = len(data)

ValueError: Exactly one of npartitions and chunksize must be specified.
```

@clarkzinzow

### PR DESCRIPTION
**Pull request by clarkzinzow**
Fixes buggy Dask-on-Ray examples in docs that didn't run. cc @robertnishihara 

## Related issue number

Closes #14460 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @richardliaw is there any way to run this code in the CI?

**Comment by richardliaw** [comment]
@clarkzinzow @rkooo567 take a look at how Tune docs run their tutorial code in CI - should be a good starting point!

**Comment by rkooo567** [comment]
@clarkzinzow can you make it run in the CI following richard's suggestion?

**Comment by clarkzinzow** [comment]
@rkooo567 can do! I've done this many, many times before in Sphinx, should be a quick update tomorrow.

**Pull request merged**
