### PR TITLE
Update hiredis and remove Windows patches

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Updates hiredis to a later version that includes patches for Windows, then removes our own patches.

## Related issue number

#9176

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by mehrdadn** [comment]
I believe the CI errors are unrelated, but I'm not 100% sure; it's a little difficult for me to tell. Here are some other builds that produce similar errors, though:

- https://travis-ci.com/github/ray-project/ray/jobs/359508769
- https://travis-ci.com/github/ray-project/ray/jobs/359417807
- https://travis-ci.com/github/ray-project/ray/jobs/359488842
- https://travis-ci.com/github/ray-project/ray/jobs/358047421

**Review by simon-mo — APPROVED** [review]
LGTM. Error shouldn't be related.

**Comment by simon-mo** [comment]
Out of curiosity, why is `ssl.c` excluded in the build target?

**Comment by mehrdadn** [comment]
@simon-mo It introduces an OpenSSL dependency that wasn't there before and getting it working is painful (I haven't figured it how).

**Pull request merged**
