### PR TITLE
[Core] [runtime env] Don't delete working_dir from runtime env

### LINKED ISSUE #16411: [runtime_env] Don't delete working dir in runtime env.
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by architkulkarni**
## Related issue number
Based off of https://github.com/ray-project/ray/pull/16378

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
cc @iycheng I would be grateful if you could take a look and let me know if this makes sense.  My understanding is that currently (before this PR), `"RAY_RUNTIME_ENV_FILES"` was never set and never used, because the field `working_dir` is never present in the runtime env dict (it gets deleted before the dict is created.).  Since we don't support working_dir per-task and per-actor, I deleted the part of worker.py that reads this env var. https://github.com/ray-project/ray/pull/16475/files#diff-e125e536c0f84a61d00bb9d0c7613c0984892ef3e89ac565605d40f93d7a68e2L1282-L1286.  If I didn't delete this, it would try to interpret the value of `"RAY_RUNTIME_ENV_FILES"` (which is a path) as a URI, which would cause an error.

I also tried to delete https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env.py#L165-L170, but it caused Ray Client to hang for some reason, which gave me some trouble.  It seems that if I leave the block in it fixes the hanging, but I don't really understand why.

**Comment by iycheng** [comment]
I think `RAY_RUNTIME_ENV_FILES` is a temporary solution to pass uris around.

But this won't merge with job config which means https://github.com/ray-project/ray/issues/16481 still won't work.

**Comment by iycheng** [comment]
This one is more like give the GCS some way to fetch the working dir.

**Comment by architkulkarni** [comment]
The PR to merge the actor/task runtime env with the job_config has been merged https://github.com/ray-project/ray/pull/16378 , does that address this?

Regarding `RAY_RUNTIME_ENV_FILES` I'm still confused, because I don't see how it could ever be set.  Here is the block of code where it's set in master https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env.py#L165-L170, but I don't think this was ever called, because working_dir was removed from the dict before these lines ran.

**Comment by architkulkarni** [comment]
With the current PR, my understanding is that we're passing the field "working_dir" in the runtime env dict just so it can be read and displayed externally.  But the actual mechanism of working_dir for tasks and actors is just to get the URIs from the job_config (https://github.com/ray-project/ray/pull/16475/files#diff-e125e536c0f84a61d00bb9d0c7613c0984892ef3e89ac565605d40f93d7a68e2R1282).

**Comment by architkulkarni** [comment]
`test_experimental_package_github` failed with this PR so I must be misunderstanding this codepath. https://buildkite.com/ray-project/ray-builders-pr/builds/7337#30496bea-c82a-4d8e-abe7-67c95e80fc34/6-9348

**Comment by architkulkarni** [comment]
I see, RAY_RUNTIME_ENV_FILES is used for the experimental package loading.  Let me take a closer look

**Review by edoakes — APPROVED** [review]

**Pull request merged**
