### PR TITLE
[docs] update-theme

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

need to test on mobile.
on web it looks great.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
FYI @amogkam @matthewdeng @xwjiang2010 since you guys expressed interest in developing more understanding of docs system

**Comment by maxpumperla** [comment]
@richardliaw the updated theme has replaced the confusing "<--" arrow to hide the left nav with a hamburger (good choice). Can we remove the custom CSS that was hiding the arrow?

**Comment by maxpumperla** [comment]
Screenshot 2022-06-08 at 23 14 36

also, the search box doesn't quite work now, should be an easy fix.

**Comment by richardliaw** [comment]
hmm i tried toggling the z-index for the algolia feature but it doesn't seem to work well. 

i think maybe it's because the new theme is a bit more stringent in how they have constructed the sidebar?

cc @simon-mo for more help here

**Comment by simon-mo** [comment]
My knowledge is very very limited here... can @sumanthratna help?

**Comment by sumanthratna** [comment]
to keep the autocomplete results within the sidebar, we can set `min-width: 0` on `#algolia-autocomplete-listbox-0`: 

Screen Shot 2022-06-08 at 20 59 16

but I'm not immediately sure how to remove the horizontal scroll on the sidebar and let the autocomplete results bleed over the main page content—will look into it

**Comment by richardliaw** [comment]
Yeah, def preferable to let it overflow. Let me know what you find! Maybe you need some way of having it break out of its container

**Comment by sumanthratna** [comment]
udpate: if we set `position: fixed` on `#algolia-autocomplete-listbox-0 > .ds-dataset-1` then it works I think
Screen Shot 2022-06-08 at 21 15 43

**Comment by maxpumperla** [comment]
@richardliaw @sumanthratna great, just make sure to have a media query for mobile devices (you can look up what we have already in custom.css). We don't want to overflow on mobile, but rather reduce the width there.

**Pull request closed without merging**
