### PR TITLE
[Docker] Start building `ray-ml` CPU Docker image again

### PR DESCRIPTION
**Pull request by amogkam**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — APPROVED** [review]
Looks good, and build seems to succeed. Thanks!

**Comment by amogkam** [comment]
FYI @javi-redondo @alanwguo @richardliaw

**Review by ijrsvt — APPROVED** [review]
@amogkam this looks good

Looks like `ray-ml:nightly` is still the same as `ray-ml:nightly-gpu` (this is the intended behavior right)!!
```
build-docker-images.py --py-versions py36 --device-types cpu cu101 cu102 --build-type BUILDKITE --build-base: 

These tags will be created for ray-ml:  defaultdict(<class 'list'>, {'nightly-py36-cpu': ['nightly-py36-cpu', 'ec7760-py36-cpu']})
```

and
```
build-docker-images.py --py-versions py36 --device-types cu110 cu111 cu112 --build-type BUILDKITE --build-base:

These tags will be created for ray-ml:  defaultdict(<class 'list'>, {'nightly-py36-cu112': ['nightly-py36-cu112', 'nightly-py36-gpu', 'nightly-py36', 'nightly-py36-gpu', 'ec7760-py36-cu112', 'ec7760-py36-gpu', 'ec7760-py36', 'ec7760-py36-gpu']})
```

Also holds for py37 & py38!

**Comment by amogkam** [comment]
@ijrsvt yes this was the intention!

**Pull request merged**
