### PR TITLE
[serve] Don't halt main control loop due to exceptions in snapshot logic

### PR DESCRIPTION
**Pull request by edoakes**
## Related issue number

Closes. https://github.com/ray-project/ray/issues/19712

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — COMMENTED** [review]
This is a behavior change:
- before: when `self.autoscale()` is consistently failing, `http_state.update()`, `deployment_state_manager.update()` can still run
- after: former failure in the loop will disable later update actions.

instead, just catch snapshot call and log that instead?

**Comment by architkulkarni** [comment]
Agree with Simon, otherwise looks good to me

**Comment by edoakes** [comment]
Oh, great catch @simon-mo, that is problematic. Let me fix this.

**Comment by edoakes** [comment]
@simon-mo updated.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
