### PR TITLE
[Autoscaler][minor] Improve shutdown handler, add retries to KubeRay config fetch

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

- Uses a Monitor attribute in the shutdown handler instead of an args attribute. Necessary because some integrations (including KubeRay) instantiate the Monitor directly rather than running `python Monitor.py` with arguments.
- Adds HTTP retries to Ray CR fetch. Necessary for robustness because Ray CR fetch exceptions are not currently handled during autoscaler initialization.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
Will add unit tests if reviewers find this reasonable.

**Review by Jeffwan — APPROVED** [review]
lgtm

**Comment by DmitriGekhtman** [comment]
TODO: Unit test.

**Review by wuisawesome — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
Test failures unrelated.

**Pull request merged**
