### PR TITLE
[Core] Remove cuda support in plasma store

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

They are never used in Ray (even without any build support). This reduces our tech debt, because after so many changes plasma store is already strictly incompatible with the upstream.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by suquark** [comment]
CI errors come from upstream.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Do you mind deleting the external storage too if you have time?

**Comment by rkooo567** [comment]
(I can do later too)

**Comment by suquark** [comment]
let me delete external storage in another PR

**Comment by suquark** [comment]
The PR for external store: https://github.com/ray-project/ray/pull/13080

**Pull request merged**
