### PR TITLE
Remove crashing assert in actor creation for old scheduler

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Try removing a bad assert to help debug https://github.com/ray-project/ray/issues/11239

This is an assert in old scheduler code tripped by GCS actor creation, which should be removed soon with the new scheduler.

### CODE REVIEW

**Comment by ericl** [comment]
@stephanie-wang @rkooo567 I'm not entirely sure why this is happening, but it seems like a possible race condition with updates to actor_registry_, and harmless enough to ignore. I'd like to merge so we can try it out with this patch in latest wheels.

**Comment by stephanie-wang** [comment]
Hmm looking at the code, it seems like this would just fail the assertion check at the next step of removing the tasks from the scheduling queue.

**Comment by stephanie-wang** [comment]
Oh never mind, I think I was mistaken about that. But it still seems a bit fishy...can we confirm that the ID does actually correspond to an actor?

**Comment by ericl** [comment]
I'm actually a bit confused what exactly we are tracking here, is it the task for the actor constructor? It seems we expect that to be in a special state (not WAITING), but I can't seem to find such a state.

In any case, can we merge this to unblock the experiment?

**Comment by stephanie-wang** [comment]
> I'm actually a bit confused what exactly we are tracking here, is it the task for the actor constructor? It seems we expect that to be in a special state (not WAITING), but I can't seem to find such a state.
> 
> In any case, can we merge this to unblock the experiment?

I don't really remember the details now, but I think maybe this is the actor constructor task and it's not in any of the scheduling queues.

Yeah, I'll approve it. But can you change it to log a message with the object ID if the check fails? That way at least we can maybe figure out what's going on when testing it.

**Review by stephanie-wang — APPROVED** [review]
Can you change to log a warning?

**Comment by ericl** [comment]
Done

**Pull request merged**
