### PR TITLE
[docs] Fix args + kwargs instead of docstrings

### LINKED ISSUE #13066: [Docs] Package reference not showing parameters.
### What is the problem?

The Ray docs package reference is now showing `ray.init(*args, **kwargs)` instead of the full list of parameters. Links between master and the last release below. 

This shouldn't necessarily block the 1.2.0 release, but we shouldn't update the latest/stable docs until we fix this. 

Master: https://docs.ray.io/en/master/package-ref.html

Latest: https://docs.ray.io/en/latest/package-ref.html 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by sumanthratna**
CC @wuisawesome @richardliaw 

I'm just guessing; I have no idea if this will fix the issue

## Related issue number

closes #13066

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
Thanks! Where you able to verify this/do you mind attaching a screenshot of the fixed docs page? (There's a Makefile in the `/docs` folder of the repo which should generate the html version of the docs).

**Comment by sumanthratna** [comment]
> Thanks! Where you able to verify this/do you mind attaching a screenshot of the fixed docs page? 

No, unfortunately :// I don't have local docs builds set up because pip takes forever to resolve dependencies. I'll let you know if I figure it out, though

( and by the way, I canceled most CI tests so that lint and docs are prioritized; I'll re-start other tests after those runs finish)

**Comment by richardliaw** [comment]
Works for me!

**Review by richardliaw — APPROVED** [review]
Thanks for the fast fix!

**Pull request merged**
