### PR TITLE
[Doc] Fix dependency conflict

### PR DESCRIPTION
**Pull request by evalaiyc98**
## Why are these changes needed?
Resolving dependency conflicts is crucial for ensuring the stability, safety, and while also making codebase highly maintainable.
I've addressed this issuse with a minimal fix to resolve the dependency conflict. 

However, please note that there might be a need for subsequent version upgrade for other packages.

## Related issue number
#39962 

## Checks
- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
Using manual testing, I set up a Conda environment and followed the [document](https://docs.ray.io/en/master/ray-contribute/development.html#installing-additional-dependencies-for-development).
I verified that all packages were installed with the expected version and ensured there were no dependency conflicts.

   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by aslonnie** [comment]
the images do not build now. see buildkite/premerge.

**Comment by evalaiyc98** [comment]
Still working on this. Try to find out why fail.

**Comment by can-anyscale** [comment]
I put up something similar in case you want to have a look https://github.com/ray-project/ray/pull/40345. The main thing here is that the python/requirements_compiled.txt is actually auto-generated code so you cannot modify by hand.

CI produced a copy of this file so you can just download and replace in your local copy: https://buildkite.com/ray-project/premerge/builds/8578#018b33c7-f576-46a5-ac50-1f15bf5d88cd

**Review by aslonnie — COMMENTED** [review]
(just to get this off my review queue for now; feel free to request for review when it is ready.)

**Pull request closed without merging**
