### PR TITLE
[Cherrypick][Serve][Doc] Add object detection example (#33760)

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

cherry-pick: #33760

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sihanwang41** [comment]
^^ @zhe-thoughts @clarng

**Comment by clarng** [comment]
Can we add some notes for why this needs cherry pick?

**Comment by sihanwang41** [comment]
> Can we add some notes for why this needs cherry pick?

this is a doc change and show serve examples (AIR wish list). @richardliaw

**Review by zhe-thoughts — APPROVED** [review]

**Comment by sihanwang41** [comment]
tests failures are not related.

**Comment by jjyao** [comment]
I'll merge after releasing to pypi.

**Review by zhe-thoughts — APPROVED** [review]

**Pull request merged**
