### PR TITLE
[tune] Modify stop criteria in hyperopt example

### PR DESCRIPTION
**Pull request by stvreumi**
Modify `training_iteraion` to `timesteps_total` because only `timesteps_total` is inside the reporter.

### CODE REVIEW

**Comment by richardliaw** [comment]
`training_iteration` is actually auto-filled, but `timesteps_total` works here too and is probably more clear for the example.

**Review by richardliaw — APPROVED** [review]

**Comment by stvreumi** [comment]
Is the auto-filled parameter also output in the logs? I find that there's also `training_iteration` the logs in the ray output.
I have search the docs about whether there is any info about `training_iteration`, but there's no results.
I think maybe you can create a brief description about which auto-filled parameter we can use and what meaning it is. That will help me a lot.
Thank you.

**Comment by richardliaw** [comment]
Hi, can you create a new issue for that so I can track this? 

Thanks!

**Comment by richardliaw** [comment]
OK, opened an issue to do this.

**Pull request merged**
