### PR TITLE
Revert "[RLlib] Auto-framework, retire `use_pytorch` in favor of `fra…

### PR DESCRIPTION
**Pull request by ericl**
…mework=...` (#8520)"

This reverts commit 2746fc04762b437e53c29017b0a9b011c2212726.

This breaks travis with
```
E                         File "/home/travis/build/ray-project/ray/python/ray/rllib/utils/framework.py", line 32, in get_auto_framework
E                           "framework='auto' (default value) is not allowed if both "
E                       ValueError: framework='auto' (default value) is not allowed if both TensorFlow AND PyTorch are installed! Instead, use framework='tf|tfe|torch' explicitly.

```

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Can't merge this yet. Breaking LINT:
```
++++python -m flake8 --inline-quotes '"' --no-avoid-escape --exclude=python/ray/core/generated/,streaming/python/generated,doc/source/conf.py,python/ray/cloudpickle/,python/ray/thirdparty_files --ignore=C408,E121,E123,E126,E226,E24,E704,W503,W504,W605
./rllib/contrib/bandits/examples/tune_LinUCB_train_recommendation.py:11:1: F401 'ray.rllib.contrib.bandits.agents.LinUCBTrainer' imported but unused
```

**Comment by simon-mo** [comment]
@sven1977 can you take a look? Lint failed and `//rllib:tests/test_attention_net_learning ` failed

https://travis-ci.com/github/ray-project/ray/jobs/341117595

**Comment by sven1977** [comment]
Please do not merge! Another PR fixes all failing tune tests with a single added line:
https://github.com/ray-project/ray/pull/8672

**Comment by rkooo567** [comment]
This will address the issue. https://github.com/ray-project/ray/pull/8672

**Pull request closed without merging**
