### PR TITLE
[Doc] Remove unused "help wanted" tag from doc

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
The doc links to a tag which has 0 issues: https://github.com/ray-project/ray/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

This PR removes the link.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by maxpumperla** [comment]
@architkulkarni even if this one is unused, don't we have a replacement? looks beginner friendly this way

**Comment by architkulkarni** [comment]
> @architkulkarni even if this one is unused, don't we have a replacement? looks beginner friendly this way

I think the existing tag good-first-issue should cover it.

**Review by angelinalg — APPROVED** [review]
LGTM

**Comment by angelinalg** [comment]
@architkulkarni Thank you for updating, docs!!

**Comment by architkulkarni** [comment]
Tests unrelated, this PR just deletes a link from the doc.

**Pull request merged**
