### PR TITLE
[metrics] Lower the metric recording interval to 10s and fix description

### PR DESCRIPTION
**Pull request by ericl**
Signed-off-by: Eric Liang <ekhliang@gmail.com>

## Why are these changes needed?

Lower the metrics recording interval from workers; 30s is too long and you can easily miss changes that lead to e.g., OOM events. Also fixes the description of the object store memory in the dashboard.

### CODE REVIEW

**Comment by rkooo567** [comment]
Running the agent stress test that. caused memory leak before. https://buildkite.com/ray-project/release-tests-pr/builds/20629#01845905-70f5-41c3-aed6-3f94f63a45c7

I prefer to merge it after we fix the root cause (which I am planning to finish mid next week), but if this test passes with this, I am okay to merge

**Comment by ericl** [comment]
Seems like it passed, shall we merge then?

**Comment by rkooo567** [comment]
Hmm actually it didn't seem to run

**Comment by rkooo567** [comment]
Screen Shot 2022-11-09 at 6 42 48 PM

the workload only ran 7 seconds... let me see if it is same in the master (this is supposed to long running)

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
