### PR TITLE
[Docker] Remove Kubectl

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
Ray no longer needs `kubectl`. It was used for the old "kubernetes cluster launcher." KubeRay does not require that Kubectl is installed to run.
~Kubernetes moved to a new location to host packages https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/~
~The old package locations did not support newer versions of kubectl :(~

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by aslonnie — COMMENTED** [review]
where do we need kubectl today?

**Comment by ijrsvt** [comment]
Oh, good point @aslonnie. @kevin85421 , do we need Kubectl in the Ray containers still?

**Review by aslonnie — APPROVED** [review]
update PR title and description?

**Comment by ijrsvt** [comment]
Done!
Best,
Ian
Security @ Anyscale

**Comment by aslonnie** [comment]
merged, but some of the k8s chaos tests are failing?

https://buildkite.com/ray-project/oss-ci-build-pr/builds/35832#018a84be-42b6-4393-9a71-c9d6b633fde4/7582-7618 

not sure if I made a mistake or not..

**Pull request merged**
