### PR TITLE
[Core] Suppress gRPC server alerting on too many keep-alive pings 

### LINKED ISSUE #25367: [core] gRPC error ENHANCE_YOUR_CALM
### What happened + What you expected to happen

During 1TB nightly tests (name dataset_shuffle*), I see error messages like this:
```
(map pid=516, ip=172.31.64.223) E0526 12:32:19.203322360     675 chttp2_transport.cc:1103]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
```
This could mean we're not setting some config parameters correctly/inefficiently in gRPC.

### Versions / Dependencies

2.0dev

### Reproduction script

dataset_shuffle_* nightly tests. Seems like it's shown up in other workloads too.

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
```
(map pid=516, ip=172.31.64.223) E0526 12:32:19.203322360     675 chttp2_transport.cc:1103]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". See [this](https://github.com/ray-project/ray/issues/25367#issuecomment-1189421372) for more details. 
```
We currently see this in many of the large nightly tests. 

### Root Cause
The root cause (with pretty high confidence level) has been some misconfigs between gRPC server/clients. Essentially the client is pinging the server too frequently for keep-alive heartbeats. 

### Mitigation
This PR is merely a mitigation step. I will keep looking into the exact client/server pair later, but probably don't have bandwidth for now largely because the test iteration takes quite a while and verbose logging with gRPC and ray backend have not revealed much useful info. This only kicks in at the end of a long running map phase, and verbose logging doesn't tell me which client is sending the pings. 

## Related issue number
Closes #25367 

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Manual runs 
   - [X] Release tests multiple ones

### CODE REVIEW

**Comment by rickyyx** [comment]
So I tried a few different values for the number of bad pings  (GRPC_ARG_HTTP2_MAX_PING_STRIKES ) our gRPC server allows. And I ran those `dataset_shuffle_..._1tb_...` releases. 
- [2, default](https://buildkite.com/ray-project/release-tests-pr/builds/13687#01828e87-0494-4031-b738-e3e87ea1e9ec): still seeing the too many pings errors in the test log 
- [4](https://buildkite.com/ray-project/release-tests-pr/builds/13662): No more
- [8](https://buildkite.com/ray-project/release-tests-pr/builds/13664): No more
- [16](https://buildkite.com/ray-project/release-tests-pr/builds/13665): No more

I guess we could go with 4 for now - and will revisit this later when we do a more thorough review on the gRPC configs.

**Review by scv119 — APPROVED** [review]
LGTM

**Comment by rickyyx** [comment]
Chatted with @rkooo567 offline just now - will do some more experimentation on this to understand the root cause. We have some hypothesis here: 
- The Python GCS client on each worker is sending too many pings to the GCS server when the connection is idle (could happen when phase changes during a shuffle?) 
- The server asks the client to GOAWAY and thus the logging on the gcs client at each worker. 


We will try the belowing: 
1. Remove Python GCS client keep-alive (we are not doing that in the C++ client anyway), and the GCS server is doing keepalive to the client every 10secs. And see if this goes away or breaks anything. 
2. Setting the `GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS` to 1min might be a better solution than setting the `GRPC_ARG_HTTP2_MAX_PING_STRIKES` since it still allows the python GCS client to detect connection failure early (1min rather than the other grpc or system config) 

There is still much we don't know for sure and we will revisit this later on.

**Comment by rkooo567** [comment]
@iycheng @scv119 ^ I think @rickyyx and I have a pretty good hypothesis and understanding of the gRPC keepalive behavior (and when it is needed). We will experiment a bit and share the knowledge soon. For this particular issue, we think the current solution is probably pretty safe, but there could be a better solution, and we need some experimentation to verify this. (match GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS and keepalive_time_ms). 

Regardless, I think it's safe to merge this PR (but let's just wait until Ricky finishes his experimentation). The potential downside is the keepalive from client to server could be increased at the large scale, but we suspect the impact is minimal.

**Comment by scv119** [comment]
@rkooo567 to merge once the experiment is done.

**Comment by rickyyx** [comment]
**Experiment updates**
Ran 4 dataset_shuffle releases (which had the GOAWAY messages showing up) on 2 changes:
1. Remove the keepalive checking from the gcs client
2. Change GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS to match with gcs client keepalive interval. 

See the release tests results/logs here:
- no gcs client keepalive, [tests](https://buildkite.com/ray-project/release-tests-pr/builds/14011#_)
- 1min GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS, [tests](https://buildkite.com/ray-project/release-tests-pr/builds/14012#0182a49b-f53b-4aed-8be0-361e541d0b05)

**Root cause**
Both changes suppress the GOAWAY messages successfully, so the root cause is likely the GCS client sending too frequent keepalive pings (no direct proof as observability in terms of which client/server raises the GOAWAY from gRPC isn't great) 


**Fix**
I think it will make sense to change `GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS` to match the GCS client keepalive:
- so that GCS client could detect dead server connections as quickly as 1 min. 
- grpc servers might get more pings from keepalive (every 1min) but this extra work should be fine given the server is doing keepalive check every 10sec. 

@rkooo567 for merging if this SG
cc @scv119

**Comment by rkooo567** [comment]
Awesome. So our theory was correct!

**Comment by rkooo567** [comment]
Let's follow up on the additional configuration update from Ray in general after 2.0 is released.

**Pull request merged**
