### PR TITLE
[Core] Fix bug to support S3 pre-signed url for .whl file

### PR DESCRIPTION
**Pull request by yantzu**
## Why are these changes needed?
We meet error if we use a pre-signed S3 .whl file url as runtime env py-modules. 
It turns out that it is a bug of Ray, current Ray doesn't support any .whl file url that has params, query or fragment part. Because ray will change the file name to a non-standard one then pip install will fail.
This PR is to fix the issue.

## Related issue number

None

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by yantzu** [comment]
@rynewang @dentiny could you help to review this pr

**Review by dentiny — APPROVED** [review]
Apology for the delay. Thanks for the fix! LGTM

**Comment by dentiny** [comment]
@jjyao for approval and merge.

**Comment by yantzu** [comment]
Hi @jjyao ,the original build test failed, so I updated code to trigger another build, unluckily it still failed, but the failure should not related to this code changes, could you please take a look?

**Comment by yantzu** [comment]
Hi, @jjyao the tests failed on different part each time,see 
https://buildkite.com/ray-project/premerge/builds/32072
https://buildkite.com/ray-project/premerge/builds/32034

**Pull request merged**
