### PR TITLE
[ci/bazel][1] bazelize some unit-tests

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?
Bazelize some of the tests I created. Without this it does not run on CI at all.

## Checks
- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests

### CODE REVIEW

**Review by krfricke — APPROVED** [review]
Thanks! We do have a script somewhere that checks if all test_ files are tracked in Bazel scripts (for the regular CI) - maybe we can activate that for the release package as well?

**Comment by aslonnie** [comment]
ugh... why is this merged..

**Comment by aslonnie** [comment]
for context, was trying to get https://github.com/ray-project/ray/pull/34689 merged first.

**Comment by can-anyscale** [comment]
There were some communications of not merge on the [ci/bazel][2] PRs but not this. My bad, should have move it to draft

**Comment by aslonnie** [comment]
it was not on "MergeReady" state (which is why I left it unreviewed)..

anyways, I can resolve the conflict. all good.

**Pull request merged**
