### PR TITLE
Deflake `serve:test_runtime_env` by splitting into two files

### LINKED ISSUE #23374: [serve][flaky test] serve:test_runtime_env is increasingly flaky on master
Screen Shot 2022-03-21 at 10 20 59 AM

Sample failure:
https://buildkite.com/ray-project/ray-builders-branch/builds/6653#c0b0bf8a-30d7-4701-af2a-af08b57f12ab/6-8392

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
- Also removes the unnecessary "post-wheel-build" tag, which is only used for conda tests.

## Related issue number
Closes https://github.com/ray-project/ray/issues/23374

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by shrekris-anyscale — APPROVED** [review]

**Review by edoakes — APPROVED** [review]
Thanks :)

**Comment by stephanie-wang** [comment]
FYI: This test is still flaky on OSX.

**Comment by simon-mo** [comment]
I'm going to put back the post-wheel-build flag to disable it on OSX.

**Comment by simon-mo** [comment]
PR https://github.com/ray-project/ray/pull/23436

**Pull request merged**
