### PR TITLE
Revert "Revert "[autoscaler] Utilization score plugin""

### PR DESCRIPTION
**Pull request by wuisawesome**
Reverts ray-project/ray#29266

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
How's the CI looking?

**Comment by wuisawesome** [comment]
I believe the 3.10 minimal install failure is the broken `test_dashboard` in the flakey test tracker. @DmitriGekhtman do you mind checking and confirming?

**Comment by DmitriGekhtman** [comment]
> I believe the 3.10 minimal install failure is the broken `test_dashboard` in the flakey test tracker. @DmitriGekhtman do you mind checking and confirming?

That appears to check out.

**Review by DmitriGekhtman — APPROVED** [review]
Seems we're good here.

**Pull request merged**
