### PR TITLE
[New scheduler] Deflake test heartbeat 

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

The heartbeat test was relying on the order of entries in the `resource_load_by_shape` field, but these were coming from a map. Simple fix is to just compare without worrying about the order. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
cc @stephanie-wang @ericl

**Comment by rkooo567** [comment]
Hmm this failure only happened at Windows build though? I am not sure how this will be related to only Windows failure? But let me approve it first anyway. Let's see the build result.

**Review by rkooo567 — APPROVED** [review]

**Comment by wuisawesome** [comment]
I believe this is just coincidental because the iteration order over the map is consistent on linux, and consistent but different on windows. 

I won't say that confidently in case the test doesn't pass though :p

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Please resolve issues in the CI (but it at least resolves the Windows issue!)

**Comment by wuisawesome** [comment]
remaining tests failures seem unrelated

**Comment by rkooo567** [comment]
https://travis-ci.com/github/ray-project/ray/jobs/406407223

This failure looks like it is related to this PR. (build failure from cluster_task_manager tests)

**Comment by rkooo567** [comment]
CAn you merge the latest master? There are lots of serve failures which must've been resolved in the master branch.

**Pull request merged**
