### PR TITLE
Revert "[RLlib] Issue 14533: `tf.enable_eager_execution()` must be ca…

### PR DESCRIPTION
**Pull request by rkooo567**
…lled at beginning. (#14737)"

This reverts commit 3e389d58121f2e41d706dbf67e3f1fe3518dfe84.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @ericl Let's wait to see if this actually fixes the `noise_parameter..` test

**Comment by rkooo567** [comment]
@amogkam can you check if this commit was included in  1.3 release?

**Comment by amogkam** [comment]
Yes I had picked the commit that is being reverted into the release since it was actually a release blocker  cc @sven1977.

**Review by edoakes — APPROVED** [review]

**Comment by rkooo567** [comment]
@amogkam I think this needs to be picked.

**Pull request merged**
