### PR TITLE
[Datasets][test] Change batch_size to 128 for inference nightly test

### LINKED ISSUE #29166: [release][CI] inference
### What happened + What you expected to happen

build failure - https://buildkite.com/ray-project/release-tests-branch/builds/1095#0183af7e-9945-4d77-b105-30694a258d3a

cluster - https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_8RfP4VztAY9MAENHQcZTTGdq?command-history-section=command_history

```
RuntimeError: CUDA out of memory. Tried to allocate 6.10 GiB (GPU 0; 14.56 GiB total capacity; 1.19 GiB already allocated; 500.50 MiB free; 1.20 GiB reserved in total by PyTorch)
```

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by c21**
Signed-off-by: Cheng Su <scnju13@gmail.com>

## Why are these changes needed?

This is to fix nightly test failure in https://github.com/ray-project/ray/issues/29166 . After https://github.com/ray-project/ray/pull/28648/, blocks will be bundled together to achieve default 4096 batch_size, which is too large in this case causing OOM.

Reduced batch_size to 128 here. Verified nightly test passed here - https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_btqa2UkEB4NPDd8eAxqgCDXN/ses_DzJsL3MVZ2fYkx8HB8KVWF6M?command-history-section=head_start_up_log .

```
Read: 100%|████████████████████████████████████████████████████████████| 1000/1000 [00:21<00:00, 46.23it/s]
Map: 100%|████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 690.51it/s]
Preprocessing...
Map: 100%|█████████████████████████████████████████████████████████████| 1000/1000 [01:04<00:00, 15.55it/s]
Inferring...
Map Progress (1 actors 1 pending): 100%|█████████████████████████████████| 334/334 [04:25<00:00,  1.26it/s]
Download time 34.213884115219116
Preprocess time 64.35004234313965
Infer time 265.69081687927246
total time 364.2547433376312
```
## Related issue number

Closes https://github.com/ray-project/ray/issues/29166
## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]

**Review by jiaodong — APPROVED** [review]

**Review by jianoaix — APPROVED** [review]

**Comment by jianoaix** [comment]
Do we know if the images are particularly large in this test?

**Comment by c21** [comment]
> Do we know if the images are particularly large in this test?

No I don't think they are large on-disk (https://s3.console.aws.amazon.com/s3/buckets/anyscale-data?prefix=small-images/&region=us-west-2). But when reading into memory, it seems their size inflated quite much.

**Review by richardliaw — APPROVED** [review]

**Review by clarkzinzow — APPROVED** [review]
LGTM!

**Comment by c21** [comment]
Thanks guys for review. Ready to merge.

**Comment by rickyyx** [comment]
Please open a cherry-pick.

**Comment by c21** [comment]
@rickyyx - yeah will do today.

**Pull request merged**
