### PR TITLE
[Serve][Core] Fix serve_long_running memory leak by fixing GCS pubsub asyncio task leak (#29187)

### PR DESCRIPTION
**Pull request by architkulkarni**
Cherry-picks #29187 to the release branch.

Context from that PR is reproduced below:

Debugged with @simon-mo and @scv119 . The Serve long running test was failing due to a memory leak in dashboard.py. The root cause was in the GCS pubsub code, with the _close: asyncio.Event object adding millions of waits every few minutes without the waits ever being killed, causing the _close._waiters queue to grow without bound. The root cause is when awaiting with FIRST_COMPLETED, the caller is responsible for killing the unfinished task.

This PR:

Fixes the memory leak by canceling the close task if it wasn't done. (Contributed by @simon-mo) This PR also adds some side improvements to the release test:

Use lower-memory instances so that memory leaks aren't hidden by the instances having a lot of available memory Gracefully handle the case where the wrk fails, which previously caused the release test output to be overwritten in a tight loop, which led to a hard-to-interpret errors being surfaced to the release test infrastructure Use different ports for the dashboard agents on the multiple cluster_utils virtual nodes to prevent port conflict

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
The relevant release test has been kicked off here: https://buildkite.com/ray-project/release-tests-pr/builds/17856#0183c842-ebbc-4e90-bdde-5b6ae7e305d0

@simon-mo @scv119 Could you please approve this PR? It needs two approvals.

**Comment by architkulkarni** [comment]
@c21 @rickyyx I can't run the release test due to this error:
`ray_release.exception.RayWheelsTimeoutError: Time out when waiting for URL to be available: https://ray-ci-artifact-pr-public.s3.amazonaws.com/11c2a6bcf8541a5a82ca67ec6fd271bc873087ed/tmp/artifacts/.whl/ray-2.1.0-rc0-cp37-cp37m-manylinux2014_x86_64.whl`

However, the buildkite build shows the wheels have indeed been built, at:
`https://ray-ci-artifact-pr-public.s3.amazonaws.com/11c2a6bcf8541a5a82ca67ec6fd271bc873087ed/tmp/artifacts/.whl/ray-2.1.0rc0-cp37-cp37m-manylinux2014_x86_64.whl`

There is a difference here; in the first URL there's a hyphen `-` after `2.1.0`, but in the second one, there is no hyphen.

This is also causing the runtime env `conda` tests in "Post-wheel tests" to fail with `Pip subprocess error:\nWARNING: Requirement \'/ray/.whl/ray-2.1.0-rc0-cp37-cp37m-manylinux2014_x86_64.whl\' looks like a filename, but the file does not exist`.

Can you look into this and perhaps double check the release branch commit that changes the version number to see if that's affecting it? (You should be able to compare it to previous releases, these tests pass in previous releases)

**Comment by architkulkarni** [comment]
It might be that we're using 2.1.0.rc0, when we're supposed to use 2.1.0rc0

**Comment by c21** [comment]
@architkulkarni - we renamed the version here https://github.com/ray-project/ray/commit/5e5fc3b8ca67e519dfd3660978bd5ff0786b7a0e in branch `releases/2.1.0`. Could you rebase and retry? Thanks.

**Comment by rickyyx** [comment]
Or a quicker walkaround would be provide the wheel url directly when creating the release run build: https://ray-ci-artifact-pr-public.s3.amazonaws.com/11c2a6bcf8541a5a82ca67ec6fd271bc873087ed/tmp/artifacts/.whl/ray-2.1.0rc0-cp37-cp37m-manylinux2014_x86_64.whl

Sorry about this.

**Comment by architkulkarni** [comment]
Ah thanks, good idea about the workaround, let me try that

**Review by sihanwang41 — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Review by scv119 — APPROVED** [review]

**Comment by rickyyx** [comment]
Lol that multiple accepts. 

THis has been running for 3hrs. Should I be able to merge this? @architkulkarni

**Comment by rickyyx** [comment]
The CI errors look weird though. @architkulkarni can you rebase and trigger another one see if those go away? I think the release test is good in terms of test signals.

**Comment by rickyyx** [comment]
Test looks unrelated to me.

**Pull request merged**
