### PR TITLE
[Cluster launcher] Install latest Ray by default instead of nightly

### LINKED ISSUE #34991: [AWS VM Cluster Launcher] AWS Cluster launcher installs nightly Ray by default
### What happened + What you expected to happen

At the moment, the AWS VM Cluster launcher is installing nightly Ray, instead of the latest released version by default. This is pretty bad because nightly Ray versions didn't go through the release process yet so they are not sufficiently tested.

See https://github.com/ray-project/ray/blob/4f754040764353b3e555327ef19c6778d4fe317b/python/ray/autoscaler/aws/defaults.yaml#L127

Theoretically this should be "latest" but in practice it is an unreleased version (you can see this by e.g. downloading the wheel and looking at the __commit__ field in __init__.py, which at the time of writing is `f34cfcdd2d004a5b97a8c674023eecebed3567ce`.

### Versions / Dependencies

Ray 2.4

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
In the default cluster launcher configs, previously the setup commands would install the *nightly* version of Ray if Ray was not already installed. This PR changes it to the latest stable Ray version instead.

This wouldn't happen often in practice because users are likely to use a docker image with Ray preinstalled.  However, the "minimal" example YAMLs in the docs don't specify a Docker image, so people running them would end up with the nightly Ray version, which might be unstable.

## Related issue number

Closes #34991 
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
Hmmm I feel like this is actually the behavior we want in master? 

I feel like when we cut release branches that's when the default should change.

**Comment by architkulkarni** [comment]
So the proposal in that case would be to add a step to the Ray release process to switch out these lines in all the `default.yaml` files?

**Comment by architkulkarni** [comment]
Tentatively, I think having the default always be to install "latest" makes more sense.  As Ray becomes more stable and the release cadence improves, we expect fewer and fewer people to be on the nightly. Most people trying out `example-minimal` will be on the latest anyway, so they'll expect latest to be on their cluster.

**Comment by wuisawesome** [comment]
> Most people ...

Yeah I agree that the behavior for most people should be latest, but they will be using a release wheel, and I think that's where the release version should be set. 

Pretty much, I think cluster launcher only works with the corresponding ray version, I don't think we want to inadvertently change this into a matrix, or inadvertently change what we nightly test.

> So the proposal in that case would be to add a step to the Ray release process to switch out these lines in all the default.yaml files?

Yup, exactly. (Really this step should be to done by a script)

**Comment by wuisawesome** [comment]
@can-anyscale do you have any suggestions about how we should solve this problem? let me know if you need any context about this problem.

**Comment by can-anyscale** [comment]
I discussed offline with @wuisawesome and comes to an understanding that either pinning to latest are nightly are both not sounds; but pinning to latest (what this PR is doing) is more dangerous. Generally, the version of ray to pin has to be later than the version of the default.yaml file. We can somewhat guarantee that ray is backward compatible with an old version yaml, but no way can guarantee forward compatible (which is not a thing).

The sound way here is to make sure the installed ray and the default yaml is on the same commit, which is do-able, but make code maintenance more challenging.

**Review by wuisawesome — CHANGES_REQUESTED** [review]
Based on the discussion, I'll block this PR for now. The concrete reason is that this will break if we add a new `ray start --head` flag, but the more important high level point is that we should think more carefully about the behavior we want here.

**Comment by architkulkarni** [comment]
Makes sense.  So then, for that reason, should we change `image: "rayproject/ray-ml:latest-gpu"` to `image: "rayproject/ray-ml:nightly-gpu", etc., on all the other YAMLs like `example-full.yaml`?

**Comment by wuisawesome** [comment]
I think it would actually mean that it should point to the specific version the wheel was built with. E.g. a wheel built today should always point to the docker image/wheel built today, even if you run `ray up` next week if that makes sense. 

This is particularly important for released versions of ray.

**Pull request closed without merging**
