### PR TITLE
[rllib] Moved clip_action into policy_graph; Clip actions in compute_single_action

### PR DESCRIPTION
**Pull request by SieversLeon**
Implemented clipping for actions in _compute_single_action_, follow-up to #4413.

### CODE REVIEW

**Comment by Jimpachnet** [comment]
Also, what is the general reason behind clipping not being directly embedded in the graph?

**Review by ericl — APPROVED** [review]
Looks solid, thanks!

**Comment by ericl** [comment]
Looks like the linter is failing: https://travis-ci.com/ray-project/ray/jobs/186998035

you can run scripts/format.sh to fix

**Comment by ericl** [comment]
Test failure looks unrelated.

**Pull request merged**
