### PR TITLE
[cli][ray] update ray cli message

### PR DESCRIPTION
**Pull request by oliverhu**
## Why are these changes needed?
The instructions from `ray start --head` has a typo:

```
> ray start --head
Local node IP: 192.168.86.36
2020-09-15 21:36:33,184	INFO services.py:1164 -- View the Ray dashboard at http://192.168.86.36:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.86.36:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', redis_password='5241590000000000') <<------ THIS LINE -----
```

It should be:
```
    ray.init(address='auto', _redis_password='5241590000000000') 
```

Also updated a similar typo in doc.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Comment by ericl** [comment]
cc @barakmich we should also hotfix this into 1.0

**Comment by wuisawesome** [comment]
Can we just not include the `redis-password` arg at all? we default to that default passsword, and if we're calling it hidden, it probably just shouldn't show.

**Comment by oliverhu** [comment]
@wuisawesome  that would be an incompatible user experience. I'd rather resolve that in a separate PR.

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Actually @oliverhu looks like tests are failing: https://travis-ci.com/github/ray-project/ray/jobs/385408309#L1359-L1363

Can you fix this test_cli by adjusting output?

**Comment by oliverhu** [comment]
updated! I didn't see this error when I ran pytest locally tho, guess some configuration was not properly set locally.

**Pull request merged**
