### PR TITLE
[RLlib] Added TransformerXL and "stabilized for RL" variant, GTrXL

### LINKED ISSUE #6030: [rllib] Add examples for attention network models
For example, the Numpad / memory maze experiments in https://arxiv.org/pdf/1910.06764.pdf

cc @gehring

### PR DESCRIPTION
**Pull request by gehring**
## Why are these changes needed?
Adds attention layers that can be used in custom models.

To do:
- [x] ~Supervised learning example~
- [ ] RL example

## Related issue number
Closes #6030

### CODE REVIEW

**Comment by eugenevinitsky** [comment]
The learning rate of the ADAM optimizer in the example should be decreased to 1e-3. It's a little too high and subsequently unstable.

**Comment by gehring** [comment]
@eugenevinitsky Thanks for catching that! I'm thinking of making these example into reusable tests so I haven't thoroughly tested them just yet. I'm hoping to have this wrapped up and polished over the weekend.

**Comment by eugenevinitsky** [comment]
Cool! Let me know if you catch anything, I'm also playing around with this example and I'll let you know if I spot anything on my end.

**Review by ericl — COMMENTED** [review]
@michaelzhiluo

**Review by sven1977 — APPROVED** [review]
LGTM

**Pull request merged**
