### PR TITLE
Unskipped tests for Windows

### PR DESCRIPTION
**Pull request by czgdp1807**
## Why are these changes needed?

This set of tests passes without issues on Windows for me, so unskipping them here.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@czgdp1807 It looks like `//python/ray/tests:test_list_actors` is consistently timing out on the CI :)

**Comment by czgdp1807** [comment]
> It looks like `//python/ray/tests:test_list_actors` is consistently timing out on the CI :)

I see. The unskipped tests individually pass but together with other tests in that file take more than the allowed time limit.

**Comment by czgdp1807** [comment]
The unskipped tests consume 40 - 50% of the total time of the test file. May be we should simply split `test_list_actors.py`?

**Comment by pcmoritz** [comment]
That sounds good, but before you do that, can you compare the timing with linux? Maybe there is something very slow here on Windows that we should optimize :)

**Comment by czgdp1807** [comment]
I can look into this, no worries.

**Comment by czgdp1807** [comment]
@mattip shared some data from Linux.

The two tests above take 17.1s and the whole file takes 43.04s. So, these tests consume 40% on Linux as well.

**Data**

> "1 passed in 6.65s" and "1 passed in 10.45s" respectively. /proc/cpuinfo says "AMD Ryzen 9 3900X 12-Core Processor"

```
4.00s call     ray/tests/test_list_actors.py::test_list_named_actors_namespace
3.85s teardown ray/tests/test_list_actors.py::test_list_named_actors_basic
3.75s teardown ray/tests/test_list_actors.py::test_list_named_actors_basic_local_mode[ray_start_regular0]
3.50s teardown ray/tests/test_list_actors.py::test_list_named_actors_namespace
3.26s teardown ray/tests/test_list_actors.py::test_list_named_actors_detached
3.22s teardown ray/tests/test_list_actors.py::test_list_named_actors_ray_kill
2.85s teardown ray/tests/test_list_actors.py::test_list_named_actors_restarting_actor
2.67s setup    ray/tests/test_list_actors.py::test_list_named_actors_restarting_actor
2.66s setup    ray/tests/test_list_actors.py::test_list_named_actors_ray_kill
2.64s setup    ray/tests/test_list_actors.py::test_list_named_actors_basic
2.63s setup    ray/tests/test_list_actors.py::test_list_named_actors_detached
2.60s setup    ray/tests/test_list_actors.py::test_list_named_actors_namespace
2.59s setup    ray/tests/test_list_actors.py::test_list_named_actors_basic_local_mode[ray_start_regular0]
1.91s call     ray/tests/test_list_actors.py::test_list_named_actors_detached
0.87s call     ray/tests/test_list_actors.py::test_list_named_actors_restarting_actor
0.01s call     ray/tests/test_list_actors.py::test_list_named_actors_basic
0.01s call     ray/tests/test_list_actors.py::test_list_named_actors_ray_kill
0.01s call     ray/tests/test_list_actors.py::test_list_named_actors_basic_local_mode[ray_start_regular0]
============================================== 6 passed in 43.04s ==
:100:
1
```

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by czgdp1807** [comment]
Please let me know if splitting `test_list_actors.py` is a go ahead. Note the comments - https://github.com/ray-project/ray/pull/21702#issuecomment-1023530419 and https://github.com/ray-project/ray/pull/21702#issuecomment-1017815366 of this PR.

**Comment by pcmoritz** [comment]
Yes, splitting sounds good to me!

**Review by pcmoritz — APPROVED** [review]
Let's wait for CI, one of the tests timed out so I took it out again.

**Pull request merged**
