### PR TITLE
ignore java/**/bin

### PR DESCRIPTION
**Pull request by ConeyLiu**
## What do these changes do?

ignore java/**/bin

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by raulchen** [comment]
which particular directories do you want to ignore? I don't see any `bin` directories under `java`

**Comment by raulchen** [comment]
Interesting, building python wheels shouldn't generate files in Java dir. Can you list the dirty files?

**Comment by ConeyLiu** [comment]
I will try to regenerate it. It happens when I build wheels and cancel it in the middle.

**Comment by ConeyLiu** [comment]
Hi @raulchen, this should be caused by vscode java plugin bug. The bug is here: https://github.com/redhat-developer/vscode-java/issues/634. Not sure this patch should be merged.

**Comment by raulchen** [comment]
> Hi @raulchen, this should be caused by vscode java plugin bug. The bug is here: [redhat-developer/vscode-java#634](https://github.com/redhat-developer/vscode-java/issues/634). Not sure this patch should be merged.

I see, thanks. Since this bug is not specific to ray, I think you can add the ignore item to your local config file (`~/.config/git/ignore`) until the bug is fixed.

**Comment by ConeyLiu** [comment]
OK, thanks a lot. Close this.

**Pull request closed without merging**
