### PR TITLE
add nightly test for oom

### PR DESCRIPTION
**Pull request by clarng**
Signed-off-by: Clarence Ng <clarence@anyscale.com>

## Why are these changes needed?

Add release test for oom for regression

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x[ Release tests
   - [ ] This PR is not tested :(

Passing test:
https://buildkite.com/ray-project/release-tests-pr/builds/19178#018412fc-58ed-450b-8771-588d0eb098fb

OOM counter:
https://ec2-7c1kalm-4f7k881-0000-cust-mon.ray.aws-us-west-2-admin.anyscale-test-production.com/grafana/explore?orgId=1&left=%5B%221666766586487%22,%221666766929959%22,%22Cortex%22,%7B%22exemplar%22:true,%22expr%22:%22ray_memory_manager_worker_eviction_total%22,%22requestId%22:%22Q-8ee824a2-46c7-4598-8b77-fb578fa1b9fe-0A%22%7D%5D

### CODE REVIEW

**Comment by scv119** [comment]
let's kick off one successful runs before merging?

**Comment by clarng** [comment]
Any idea how to do it? I don't see it builds a wheel 

And looking at other's PR there's no CI even? https://github.com/ray-project/ray/pull/27533

**Comment by clarng** [comment]
> let's kick off one successful runs before merging?

Any idea how to do it? I don't see it builds a wheel 

And looking at other's PR there's no CI even? https://github.com/ray-project/ray/pull/27533

**Comment by scv119** [comment]
https://www.notion.so/anyscale-hq/How-to-run-release-tests-from-your-laptop-e0257748db8e456683909d975da43ecd

**Review by scv119 — APPROVED** [review]

**Pull request merged**
