### PR TITLE
Fix or remove unnecessary `action_env` settings in `.bazelrc`

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

`PATH` is easy to be changed in a terminal session. Different `$PATH` values lead to miss of bazel cache. e.g. `pip install python -e` and `bazel build //:all` don't share cache because Python modifies `PATH`.

`LC_ALL`, `LANG`, and python-related environment variables are only used by C++ worker tests, which invokes the `ray start` command when running tests with `bazel test`. Java worker is not affected because we don't use `bazel test` to run Java tests. So these env variables should stay `test_env`, not `action_env`.

This PR can greatly improve the cache hit rate of Bazel build and test.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kfstorm** [comment]
These `action_env`s are originally introduced in #4458 and #9682.

**Review by clarkzinzow — APPROVED** [review]
Awesome, this should be a huge cache hit improvement! LGTM if the C++ worker tests pass.

**Review by SongGuyang — APPROVED** [review]
LGTM!

**Comment by kfstorm** [comment]
CI results look promising.

It seems that Cython build fails on Windows. Any idea?

```
(07:22:06) ERROR: BUILD.bazel:2294:12: Executing genrule //:python/ray/streaming/_streaming.pyx_cython_translation failed: (Exit 127): bash.exe failed: error executing command
--
  | cd C:/tmp/4lhdprva/execroot/com_github_ray_project_ray
  | SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0
  | C:/msys64/usr/bin/bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; PYTHONHASHSEED=0 external/cython/cython.py --cplus python/ray/streaming/_streaming.pyx --output-file bazel-out/x64_windows-opt/bin/python/ray/streaming/_streaming.cpp
  | Execution platform: @local_config_platform//:host
  | /usr/bin/env: 'python': No such file or directory
```

The other failure is `test_task_level_gc[python_object-pip-ray_start_cluster1] `. Not sure if it's related.

```
for i, value in enumerate(values):
--
  | if isinstance(value, RayError):
  | if isinstance(value, ray.exceptions.ObjectLostError):
  | worker.core_worker.dump_object_store_memory_usage()
  | if isinstance(value, RayTaskError):
  | >                       raise value.as_instanceof_cause()
  | E                       ray.exceptions.RayTaskError(ModuleNotFoundError): ray::f() (pid=8583, ip=172.18.0.3)
  | E                         File "/ray/python/ray/tests/test_runtime_env_conda_and_pip_3.py", line 84, in f
  | E                           import pip_install_test  # noqa: F401
  | E                       ModuleNotFoundError: No module named 'pip_install_test'
```

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
Anyone familiar with bazel on Windows? Help appreciated.

**Pull request merged**
