### PR TITLE
Fix raylet::MockWorker::GetProcess crashes

### PR DESCRIPTION
**Pull request by fyrestone**
## Why are these changes needed?

- Fix `raylet::MockWorker::GetProcess` crashes

## Related issue number

https://github.com/ray-project/ray/pull/13435

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]

**Comment by amogkam** [comment]
@fyrestone do you have commit authorization? If not, pinging @rkooo567- can you please merge once `cluster_task_manager_test` passes. Thanks!

**Review by WangTaoTheTonic — APPROVED** [review]
The failed test passed in my laptop, so LGTM

**Comment by amogkam** [comment]
Awesome- @WangTaoTheTonic can you merge please?

**Comment by fyrestone** [comment]
> @fyrestone do you have commit authorization? If not, pinging @rkooo567- can you please merge once `cluster_task_manager_test` passes. Thanks!

Sorry, I don't have the commit authorization.

**Review by raulchen — APPROVED** [review]

**Pull request merged**
