### PR TITLE
[release test] fix horovod release test.

### PR DESCRIPTION
**Pull request by xwjiang2010**
## Why are these changes needed?

horovod_user_test_master is failing with recent horovod release[[link](https://buildkite.com/ray-project/periodic-ci/builds/2960#61dabda8-eea0-4b7b-93bf-9e341926d3fd)]. 
Error message is saying:
```
AttributeError: Can't get attribute '_ExecutorDriver' on <module 'horovod.ray.runner' from '/home/ray/anaconda3/lib/python3.7/site-packages/horovod/ray/runner.py'>
```
The horovod test is set up in such a way that it has the "driver" (a.k.a. client) part (which is the code that runs in a buildkite agent) and the "cluster" (a.k.a. server) part (which runs in Anyscale cluster). Driver's dependency is specified by `release/ml_user_tests/horovod/driver_setup_master.sh` while cluster's dependency is specified by `release/horovod_tests/app_config_master.yaml`.

The two communicate via Anyscale client. 
The above error message is complaining that while client's horovod version has _ExecutorDriver in runner.py, the server's horovod doesn't. This is due to the version mismatch of the above two files. This PR brings the two horovod dependency to both point to horovod master. 

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [X] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — CHANGES_REQUESTED** [review]
It needs to be pinned in the cluster env for the relevant nightly test right? Not added as a new dependency here.

**Review by amogkam — APPROVED** [review]
LGTM! Let's merge if the test passes

**Comment by matthewdeng** [comment]
Can you add to the description what the failure is and why this change fixes it?

**Comment by xwjiang2010** [comment]
release test: https://buildkite.com/ray-project/periodic-ci/builds/2963

**Comment by xwjiang2010** [comment]
> Can you add to the description what the failure is and why this change fixes it?

Updated the PR description.

**Comment by xwjiang2010** [comment]
ah, made a mistake in the last run. Updated run: https://buildkite.com/ray-project/periodic-ci/builds/2967

**Pull request merged**
