### PR TITLE
[Core] [runtime env] Print message on driver when installing conda or pip

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
This is incremental progress towards https://github.com/ray-project/ray/issues/16299.  In improves the user experience when using Ray Client with runtime envs that have "pip" or "conda" specified.  Prior to this PR, it would look like `ray.connect()` is hanging while the environment is installing.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Probably should be logger.info because nothing went wrong? Not sure

**Comment by architkulkarni** [comment]
I tried with logger.info, but it doesn't get printed in that case. Or should I set the logging level to INFO, like `logger.setLevel(logging.INFO)`?  The only potential downside might be that other INFO logs from this file will now also get printed, but I don't see any other INFO logs currently so maybe it's okay.

**Comment by edoakes** [comment]
@architkulkarni looks like there are some relevant failures in CI here:
https://buildkite.com/ray-project/ray-builders-pr/builds/7339#c68eb44f-ddd2-4467-b0b4-8902528c74d4/136-1128

**Comment by edoakes** [comment]
Leaving it at warning level SGTM let's not mess with the default log level

**Comment by edoakes** [comment]
Windows failed seemingly spuriously. Re-running.

**Comment by architkulkarni** [comment]
Only failure is test_job_timestamps in test_job, which is known flaky and looks unrelated.  According to flaky-tests.ray.io, it is only flaky on Mac OS, but it looks like this Buildkite failure is coming from Linux, which is odd.

test_basic_client_mode was also flaky in this run https://buildkite.com/ray-project/ray-builders-pr/builds/7405#ef557f50-6ad8-4ccc-8c01-3af3a8f3c20c/116-506 , but a lot of other client_mode tests are failing right now so it's unclear if it's related to this PR.

**Comment by edoakes** [comment]
@architkulkarni I retried the build in question, let's see what happens

**Comment by architkulkarni** [comment]
test_job failure is unrelated, see https://github.com/ray-project/ray/pull/16545#event-4911320082.

Still a bit concerned about the test_basic_client_mode flakiness.  It failed 1 out of 2 times in the most recent run, as well as the run before.

**Comment by architkulkarni** [comment]
> @architkulkarni I retried the build in question, let's see what happens

Sounds good.  I expect test_job to fail again since the buildkite tests aren't run against the result of merging with master.  I'm interested to see if test_basic_client_mode fails 1/2 times again.

**Pull request merged**
