### PR TITLE
[serve] Unpin `fastapi` version

### LINKED ISSUE #42711: [Serve] Fastapi 0.109.0 is breaking the Serve proxy
### What happened + What you expected to happen

pip install fastapi==0.109.0.

run

```
import ray
import requests
from fastapi import FastAPI
from ray import serve

app = FastAPI()


@serve.deployment
@serve.ingress(app)
class MyFastAPIDeployment:
    @app.get("/")
    def root(self):
        return "Hello, world!"


serve.run(MyFastAPIDeployment.bind(), route_prefix="/hello")
resp = requests.get("http://localhost:8000/hello")
# Got 404 response
assert resp.json() == "Hello, world!"
```

Upstream issue: https://github.com/tiangolo/fastapi/discussions/10948

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

FastAPI has fixed the broken `starlette` interaction in `0.109.2`: https://fastapi.tiangolo.com/release-notes/#01092

Starlette handling of `root_path` has changed in `0.33.0`: https://github.com/encode/starlette/pull/2352. Prior to this, it was incorrectly stripping the `root_path` from the `path` field (which we need to mirror). Added compatibility logic to handle both of these.

## Related issue number

Closes https://github.com/ray-project/ray/issues/42711

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by GeneDer — APPROVED** [review]
:shipit:

**Comment by aslonnie** [comment]
I am updating your branch to rerun the premerge tests. the test failure of `test_update_task` seems unrelated to the "min install" failures.

**Comment by edoakes** [comment]
> I am updating your branch to rerun the premerge tests. the test failure of `test_update_task` seems unrelated to the "min install" failures.

Thank you!!!

**Review by richardliaw — APPROVED** [review]

**Comment by aslonnie** [comment]
looks like all tests passed; should be good to merge.

I will continue investigating the min install thing

**Pull request merged**
