### PR TITLE
Remove outdated Java doc and run demo code in CI

### PR DESCRIPTION
**Pull request by raulchen**
## Why are these changes needed?

These docs are out-dated. The new docs reside on https://docs.ray.io/en/master/

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]
I'm ok with deleting these if you want, but perhaps we could also update some of them? 

Serve, Rllib and Tune all run example programs in their test suite to make sure the examples are up to date.

**Comment by kfstorm** [comment]
Maybe we can keep the tutorial files? We can even run them in CI as @wuisawesome suggested.

**Comment by raulchen** [comment]
The code is up-to-date, as we will compile them in CI. But I think the tutorial examples are not very useful. Because they are redundant with the demo code for the documentation, e.g., https://github.com/ray-project/ray/blob/master/java/test/src/main/java/io/ray/docdemo/WalkthroughDemo.java

**Comment by kfstorm** [comment]
> The code is up-to-date, as we will compile them in CI. But I think the tutorial examples are not very useful. Because they are redundant with the demo code for the documentation, e.g., [https://github.com/ray-project/ray/blob/master/java/test/src/main/java/io/ray/docdemo/WalkthroughDemo.java](https://github.com/ray-project/ray/blob/master/java/test/src/main/java/io/ray/docdemo/WalkthroughDemo.java?rgh-link-date=2020-09-10T04%3A27%3A00Z)

OK. But can we run the demo code in CI?

**Comment by raulchen** [comment]
@kfstorm good point. added that.

**Review by kfstorm — APPROVED** [review]

**Pull request merged**
