### PR TITLE
Cherry pick pin gym dependency

### LINKED ISSUE #23530: [Bug] Wrong gym version on ray-ml:1.11.0 docker images
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib, Ray Clusters

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

Relates to the python issues in #23286 #23062.

**What happened:**
We have a k8s deployment running and we noticed the gym version bug using RLLib on the `ray-ml:1.11.0` docker images.
 
**Expected behaviour:**
Rebuild docker images for 1.11

**Resolution**
The `-ml` images use `requirements_rllib.txt, which seems to have been fixed with commit https://github.com/ray-project/ray/commit/04feea4afe01805aee49d4b2df1e9d4cd67fd72e but images have not been rebuilt.

**Workaround**
The resolution of downgrading the gym version would require a rebuild, which we chose not to.
For now, we have reverted to 1.10 images, which come with `gym` version `0.21.0`.

### Versions / Dependencies

We use the `rayproject/ray-ml:1.11.0-py38` for ray head/workers and `rayproject/ray:1.11.0` for the operator (latter likely less relevant here).

### Reproduction script

Execute following on a `rayproject/ray-ml:1.11.0-py38` worker:
```
import ray

ray.init("ray://.....")

@ray.remote
def get_gym_version():
    import gym as local_gym
    return local_gym.__version__

print(ray.get(get_gym_version.remote()))
ray.shutdown()
```
This returns `0.23.0` on the 1.11 images, which is not supported as per issues mentioned above.
Alternatively, I assume when you docker pull, you can also find the relevant gym version conflict in the image.

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Cherry-picking dependency pins for gym.

## Related issue number

Closes #23530 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Seems there is a problem with requirements_train.txt - I'll look into this tomorrow morning

**Comment by architkulkarni** [comment]
CI `privileged-test` and `post-wheel-test` were failing on the 1.11.0 branch as well and the decision was made to ignore them, so we'll ignore them for 1.11.1 as well.

Cherry picks need TL approval, @richardliaw or @matthewdeng could you please approve this PR?  (Sorry if I missed someone)

**Comment by architkulkarni** [comment]
//python/ray/workflow:tests/test_virtual_actor_2 is failing consistently on this PR, but it's passing on the last few commits of the `1.11.0` branch and the `1.11.1` branch.  Could it be related to this PR?  It recently started failing on master, but not sure how that could affect this PR.  @iycheng any idea about this?

**Comment by architkulkarni** [comment]
> //python/ray/workflow:tests/test_virtual_actor_2 is failing consistently on this PR, but it's passing on the last few commits of the `1.11.0` branch and the `1.11.1` branch. Could it be related to this PR? It recently started failing on master, but not sure how that could affect this PR. @iycheng any idea about this?

@clarkzinzow can you help diagnose this?  Is this safe to merge or do we need some kind of fix?

**Review by richardliaw — APPROVED** [review]

**Comment by clarkzinzow** [comment]
After looking at the tests and Workflows code, and comparing with the diff, I'm not sure how this PR could cause these tests to start timing out... These tests have also started being [flakey in master](https://flakey-tests.ray.io/), so it might be related to CI infra instead of the diff.

@iycheng Could you take a look at this? I don't think that I have enough context around Workflows to debug this in a timely manner.

**Review by matthewdeng — APPROVED** [review]

**Comment by architkulkarni** [comment]
I'm going to merge this so we can start the release tests.  If we determine later (before the final release) that this PR caused the test failure, we can revert it, but I think it's really unlikely.

**Comment by clarkzinzow** [comment]
@architkulkarni If you're talking about the Workflows `test_virtual_actor_2` tests, those are flaky on master as well, so I wouldn't worry about it.

**Pull request merged**
