### PR TITLE
[Job submission] Single runtime env definition for ray core and job submission

### LINKED ISSUE #15616: Use a single RuntimeEnv definition across Ray core and job submission

### PR DESCRIPTION
**Pull request by fyrestone**
## Why are these changes needed?

We use `pydantic` to define the RuntimeEnv to validate the post data of submit job RESTful API. This PR is to make ray core and job submission share one same RuntimeEnv definition.

## Related issue number

Closes https://github.com/ray-project/ray/issues/15616

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Thanks for this PR--I spoke with @edoakes and unfortunately I don't think we'll be able to merge this, because it requires adding `pydantic` as a dependency to Ray Core and we are trying to limit the dependencies.

**Comment by fyrestone** [comment]
> Thanks for this PR--I spoke with @edoakes and unfortunately I don't think we'll be able to merge this, because it requires adding `pydantic` as a dependency to Ray Core and we are trying to limit the dependencies.

But, dashboard requires the `pydantic`. @edoakes How to solve this issue: https://github.com/ray-project/ray/issues/15616?

If we use `attrs` to validate the data, then `aiohttp` requires `attrs`, ray do not requires more dependencies. We have discussed this problem here: https://github.com/ray-project/ray/pull/15103#discussion_r629648875

**Comment by edoakes** [comment]
@fyrestone sorry for the confusion here, this is somewhat tricky. We're trying to make a very minimal/slim distribution of Ray that includes as few dependencies as possible (and won't include the dashboard). For that purpose we should avoid depending on either attrs or pydantic here. The runtime_env should be simple enough that we can just write the validation by hand, what do you think?

**Comment by fyrestone** [comment]
> @fyrestone sorry for the confusion here, this is somewhat tricky. We're trying to make a very minimal/slim distribution of Ray that includes as few dependencies as possible (and won't include the dashboard). For that purpose we should avoid depending on either attrs or pydantic here. The runtime_env should be simple enough that we can just write the validation by hand, what do you think?

Then the `filelock` dependency is the first one to be reimplemented. It is simple and has few stars.

I prefer to use mature libraries. The issue #15616 can be closed because ray does not include the dashboard by default, and we don't have to make ray core and dashboard share the same RuntimeEnv definition.

**Comment by raulchen** [comment]
I agree that we should minimize ray's dependency size. But I think data validation is such a common requirement that it'd be worth it to use a mature third-party lib. For example, we may use this lib to check the arguments of other Ray APIs as well. 

Also, I guess the size of pydantic or attrs should be very small (@fyrestone could you confirm?). Maybe we should start with getting rid of other dependencies first? E.g., ray is depending on both requests and aiohttp, maybe we should remove one of them?

**Comment by fyrestone** [comment]
> I agree that we should minimize ray's dependency size. But I think data validation is such a common requirement that it'd be worth it to use a mature third-party lib. For example, we may use this lib to check the arguments of other Ray APIs as well.
> 
> Also, I guess the size of pydantic or attrs should be very small (@fyrestone could you confirm?). Maybe we should start with getting rid of other dependencies first? E.g., ray is depending on both requests and aiohttp, maybe we should remove one of them?

It's a good idea to validate the arguments of Ray APIs. The size and dependencies of `attrs` and `pydantic`:
- attrs - used by aiohttp, jsonschema, pytest (about 57 KB, no denpendencies)
- pydantic - 2~13 MB, requires typing-extensions

The `attrs` is lighter than `pydantic`, but have fewer stars 3.5k vs 6.4k

**Comment by edoakes** [comment]
@raulchen the plan is to move those dependencies into a separate ray[dashboard] or ray[monitoring] soon (this quarter)

@fyrestone I'm not sure your point about closing https://github.com/ray-project/ray/issues/15616 -- we should still use the same RuntimeEnv definition, it can be defined in ray[core] and also used in ray[dashboard]. I would personally prefer not to introduce a dependency here given that that the validation we need to do is quite simple. I'm fine with using pydantic/attrs in the dashboard given that it'll be split out from the minimal distribution.

cc @richardliaw @pcmoritz who are spearheading the effort to reduce the size of the default distribution. Thoughts?

**Comment by fyrestone** [comment]
> @raulchen the plan is to move those dependencies into a separate ray[dashboard] or ray[monitoring] soon (this quarter)
> 
> @fyrestone I'm not sure your point about closing #15616 -- we should still use the same RuntimeEnv definition, it can be defined in ray[core] and also used in ray[dashboard]. I would personally prefer not to introduce a dependency here given that that the validation we need to do is quite simple. I'm fine with using pydantic/attrs in the dashboard given that it'll be split out from the minimal distribution.
> 
> cc @richardliaw @pcmoritz who are spearheading the effort to reduce the size of the default distribution. Thoughts?

So, can we keep two definitions until the RuntimeEnv defined in ray[core] provides similar validations to the RuntimeEnv defined by pydantic in ray[dashboard]?

**Comment by edoakes** [comment]
@fyrestone after the discussion offline, let's go ahead with using `attrs` for validation. Let's scope it to just the dashboard for now and we can decide if we want to also use the same `attrs` dependency in the core runtime_env definition later.

**Comment by fyrestone** [comment]
> @fyrestone after the discussion offline, let's go ahead with using `attrs` for validation. Let's scope it to just the dashboard for now and we can decide if we want to also use the same `attrs` dependency in the core runtime_env definition later.

Thanks. Can I close this PR and create a new one for changing `pydantic` to `attrs` in the dashboard?

**Comment by edoakes** [comment]
@fyrestone sounds good to me!

**Pull request closed without merging**
