### PR TITLE
[Core] Increase sleep time to reduce flakiness for test_actor_cancel

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

When I merged the previous PR, I used 1 second sleep by mistake. Longer sleep will make it more reliable

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]
Is there a way to not use sleep?

**Comment by rkooo567** [comment]
@jjyao Maybe signal actor. But I think long sleep will do the same job anyway.

**Comment by jjyao** [comment]
> But I think long sleep will do the same job anyway.

If signal actor works then I think it's strictly better than sleep. (not blocking this PR).

**Comment by rkooo567** [comment]
Actually for the context of this test, there's not much difference. It doesn't depend on sleep timing. Infinite sleep is basically same as signal actor.

**Pull request merged**
