### PR TITLE
[docs] Add `get_actor` as top level API

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* This is under the top level ray import and should be considered a 'public API as such'.

* Change to the index:
Screen Shot 2021-04-23 at 8 10 52 AM
* Added description:
Screen Shot 2021-04-23 at 8 11 19 AM

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by AmeerHajAli** [comment]
TIL, I thought get_actor works with any named actor (not necessarily a lifetime="detached" one)

**Review by AmeerHajAli — APPROVED** [review]

**Comment by AmeerHajAli** [comment]
@ijrsvt I think the description might be incorrect, it seems like it is possible to name an actor without making it detached, no?

**Review by AmeerHajAli — APPROVED** [review]

**Comment by AmeerHajAli** [comment]
@ijrsvt , this is good to merge.

**Comment by AmeerHajAli** [comment]
@ijrsvt , this should be ok to merge right?

**Comment by ijrsvt** [comment]
@AmeerHajAli  I wanted to wait for @pcmoritz approval

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
Thanks for doing this, looks great!

**Pull request merged**
