### PR TITLE
[Object Spilling] Name IO workers properly.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

IO workers are named as ray::IDLE. This can confuse users that there are some idle workers that are never be scheduled.

This PR fixes the issue by naming the process `ray::object_spilling_workers`. I am open for a new name suggestion if you don't like the name.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
It's a bit long and will show truncated in top. How about Ray::IOWorker?

**Comment by rkooo567** [comment]
That was the initial name, but I thought IOWorker was a bit confusing without any context.  What about SpillWorker?

**Comment by ericl** [comment]
I think it's fine, spill worker is kinda weird.

**Comment by rkooo567** [comment]
Got it lol. I will go with IO worker

**Review by stephanie-wang — APPROVED** [review]

**Pull request merged**
