### PR TITLE
Revert "[core][state] Push down filtering to GCS for listing/getting task from state api"

### PR DESCRIPTION
**Pull request by cadedaniel**
Reverts ray-project/ray#34433

Screen Shot 2023-05-08 at 2 10 15 PM

### CODE REVIEW

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
whoops, no file change?

**Comment by cadedaniel** [comment]
>whoops, no file change?


I used github UI to revert... let me look

**Comment by cadedaniel** [comment]
This was already reverted.

Why are our tests not running?

https://github.com/ray-project/ray/pull/35107

**Comment by cadedaniel** [comment]
I guess something else broke the tests before this was reverted

**Pull request closed without merging**
