### PR TITLE
[Data] Store serialized ParquetFileFragment in _ParquetDatasourceReader 

### PR DESCRIPTION
**Pull request by c21**
## Why are these changes needed?

Found regression in release test - https://github.com/ray-project/ray/issues/38790, where Parquet metdata fetching become slow. I suspect this is related to the ParquetFileFragment serialization triggered inside _ParquetDatasourceReader. So trying out this fix to see if release test gets fixed.

## Related issue number

https://github.com/ray-project/ray/issues/38790

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by c21** [comment]
Rerun the release test, and verified the time dropped to be same as before:

```
[INFO 2023-08-23 22:17:30,577] log.py: 41  Observed the following results:
  |  
  | metadata_load_time = 37.145771741867065
  | success = 1
```

**Review by raulchen — APPROVED** [review]

**Review by amogkam — APPROVED** [review]

**Review by scottjlee — APPROVED** [review]

**Comment by c21** [comment]
This PR is bugfix to resolve data release test blocker - https://github.com/ray-project/ray/issues/38790 . cc @zhe-thoughts for review.

**Review by zhe-thoughts — APPROVED** [review]
This qualifies as a release blocker. 

@c21 I'll trust you to give me a green light when CI looks good. Then I will merge

**Comment by c21** [comment]
@zhe-thoughts - yes, I checked the CI and the failure tests are not related.

**Pull request merged**
