### PR TITLE
Update TuneCallback for Pytorch-Lightning 1.6+

### LINKED ISSUE #27487: [Tune: Python] Pytorch-lightning deprecated hooks in TuneReportCallback
### What happened + What you expected to happen

1. Getting a ton of warnings from pytorch-lightning about deprecation of certain hooks.
2. Expect no warnings.
3. The `TuneCallback` has old hooks such as [`keyboard_interrupt`](https://github.com/ray-project/ray/blob/master/python/ray/tune/integration/pytorch_lightning.py#L165) which have been deprecated.
The most list of the deprecated hooks and their new versions (In pl v1.6+) are:
- `on_keyboard_interrupt` -> `on_exception`
- `on_init_start` -> just deprecated no new version
- `on_init_end` -> just deprecated no new version
- `on_batch_start` -> `on_train_batch_start`
- `on_batch_end` -> `on_train_batch_end`
- `on_epoch_end` -> `on_<train/validation/test>_epoch_end`
- `on_epoch_start` -> `on_<train/validation/test>_epoch_start`

### Versions / Dependencies

ray-tune                  1.12.1 
pytorch-lightning         1.6.5
python                    3.9.13 
(installed using mamba)
OS: Ubuntu 18.04.4 LTS (Bionic Beaver)

### Reproduction script

```python
from pytorch_lightning import Trainer, LightningModule
from torch import rand
from torch.nn import Linear
from torch.nn.functional import mse_loss
from torch.optim import Adam
from torch.utils.data import DataLoader, TensorDataset
from ray.tune.integration.pytorch_lightning import TuneReportCallback


class Model(LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = Linear(20, 4)

    def forward(self, x):
        return self.l1(x)

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = mse_loss(self(x), y)
        return loss

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=0.02)


trainer = Trainer(callbacks=[TuneReportCallback()], fast_dev_run=True)
model = Model()
dataset = TensorDataset(rand((16, 20)), rand(16))
train_loader = DataLoader(dataset, batch_size=4)
trainer.fit(model, train_loader)
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by davzaman**
## Why are these changes needed?

Getting a ton of warnings from pytorch-lightning about deprecation of certain hooks. The TuneCallback has old hooks such as [keyboard_interrupt](https://github.com/ray-project/ray/blob/master/python/ray/tune/integration/pytorch_lightning.py#L165) which have been deprecated. I updated the callback to the new hooks and updated the integration tests.

The deprecated hooks and their new versions (In pl v1.6+) are:
- `on_keyboard_interrupt` -> `on_exception`
- `on_init_start` -> just deprecated no new version
- `on_init_end` -> just deprecated no new version
- `on_batch_start` -> `on_train_batch_start`
- `on_batch_end` -> `on_train_batch_end`
- `on_epoch_end` -> `on_<train/validation/test>_epoch_end`
- `on_epoch_start` -> `on_<train/validation/test>_epoch_start`

## Related issue number

Closes #27487

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/

I spent a few hours trying to wrangle my environment. Unfortunately I'm on windows using WSL and have an old version of Debian for some reason which only supports gcc-6 (not even close to gcc-9 which is required for building the project so I can run the tests). Given this roadblock and the fact that the fixes were minimal and simple I decided to push out the changes.

- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]
Thanks a bunch for opening this PR! Let's wait for tests to pass and I'd be happy to help merge!

**Comment by davzaman** [comment]
I think I may have caused a mess trying to go back and sign-off my commits, let me see how I can fix all these extra commits.

**Comment by davzaman** [comment]
I have 0 idea how this got forced to merge? I was trying to clean up my commit, I am so sorry. Please let me know how I can fix this! 

The contributing docs on the documentation site do not mention signoffs by the way!

**Comment by richardliaw** [comment]
Hmm, seems like you merged into your own master? It definitely didn't affect the ray project master so don't worry :)

**Comment by davzaman** [comment]
Would it be possible to delete this PR and try again? I cleaned up the commit so it should not fail the bot signoff check.

**Comment by richardliaw** [comment]
yep, think you don't need to do anything here.

**Pull request merged**
