### PR TITLE
[rllib] Write magic methods for SampleBatch/PartialRollout

### PR DESCRIPTION
**Pull request by alok**
## What do these changes do?

Everybody loves that sweet sweet (syntactic) sugar.

Since we typically care about the `.data` attribute, but may not want to just
subclass `dict` (I assume), we can use `dict`'s already implemented magic methods
to clean up syntax. These let us just treat rollouts more or less as dicts.

## Related issue number

Replacement for PR #2002. Simply branched from current master and applied last
PR, but without any formatting changes.

### CODE REVIEW

**Comment by richardliaw** [comment]
jenkins retest this please

**Review by richardliaw — APPROVED** [review]
lgtm

**Review by ericl — APPROVED** [review]

**Comment by robertnishihara** [comment]
This is probably mergeable now, right?

**Comment by alok** [comment]
I'm using it in a few other local branches and it works fine. It passes the tests it modified anyway.

**Comment by richardliaw** [comment]
Thanks! merged.

**Pull request merged**
