### PR TITLE
[RLlib] Rename example to match the new RemoteBaseEnv name

### PR DESCRIPTION
**Pull request by gjoliver**
## Why are these changes needed?

So users don't see remote_vector_env in our example script.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [*] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by avnishn** [comment]
This looks to be similar to a community PR from yesterday:

https://github.com/ray-project/ray/pull/20750

**Comment by carlogrisetti** [comment]
Yup, it's basically the same. This also changes the test name

**Comment by carlogrisetti** [comment]
Yeah, same :)
Was popping up way too often when trying to debug another issue.

**Review by sven1977 — APPROVED** [review]
Thanks for the fix @gjoliver !

**Pull request merged**
