### PR TITLE
Pin Redis version to < 4.0.0

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?

This pin is needed to fix `test_output` on master, which broke when 4.0.0 was released. 

It may also fix the windows build (unsure). 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
Dups Kai's fix.

**Comment by simon-mo** [comment]
> Dups Kai's fix.

@ericl this is is intended for testing windows breakage, which is a separate issue.

**Review by richardliaw — APPROVED** [review]

**Comment by wuisawesome** [comment]
We actually need to merge this short term to fix `test_output`

**Comment by richardliaw** [comment]
Hiredis doesn't have M1-mac precompiled wheels, so we pin-down the redis version to avoid breaking m1.

**Comment by simon-mo** [comment]
@pcmoritz this doesn't solve windows breakge https://github.com/ray-project/ray/runs/4228283679?check_suite_focus=true#step:8:1555

**Pull request merged**
