### PR TITLE
[Streaming] Fault Tolerance Implementation

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

This is the last part of [ray streaming implementation plan](https://github.com/ray-project/ray/issues/6184)

You can read this proposal for detailed design:  <https://docs.google.com/document/d/1NKjGr7fi-45cEzWA-N_wJ5CoUgaJfnsW9YeWsSg1shY>

This change has been merged before in https://github.com/ray-project/ray/pull/10008 but reverted since it breaks Windows build(see https://github.com/ray-project/ray/pull/10582). This PR fixes the problem and submit it again.

## Related issue number

<https://github.com/ray-project/ray/issues/6184>

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by lixin-wei** [comment]
@raulchen could you help me to merge this PR?

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Can you check why this fails? https://travis-ci.com/github/ray-project/ray/jobs/381385867

**Comment by raulchen** [comment]
@rkooo567 That doesn't look like related

**Comment by lixin-wei** [comment]
@rkooo567 I didn't change any code related to this CI item. This CI item also failed in master with the same output, see <https://github.com/ray-project/ray/runs/1074794136>.

**Pull request merged**
