### PR TITLE
Revert "Enable Ray client server by default"

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#13350

### CODE REVIEW

**Comment by ericl** [comment]
Reverting this didn't fix the test for me locally--- perhaps it's unrelated?

**Comment by amogkam** [comment]
@ericl hmm might not be related then. It seemed like it was this one because the commits starting from this one have been failing https://travis-ci.com/github/ray-project/ray/builds.

I'll file an issue for this and assign it to the core team.

**Comment by amogkam** [comment]
FYI @ericl this has been failing consistently since this PR- see https://flakey-tests.ray.io/

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Interesting it's fixed on travis

**Pull request merged**
