### PR TITLE
Roll forward to run train_small in client mode.

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?

Releaser now has basic support to install Ray with version matching that in cluster env (https://github.com/ray-project/releaser/commit/bbd4f2d1d57edee3db22cd153d83f0485d653ea8), and other dependencies from cluster env (app config). This has been verified by running from laptop.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by AmeerHajAli — COMMENTED** [review]
LGTM. I will refer to @krfricke .

**Comment by mwtian** [comment]
This is verified to work with releaser on buildkite: https://buildkite.com/ray-project/periodic-ci/builds/335

**Comment by AmeerHajAli** [comment]
@krfricke can you please advise on next steps?

**Review by AmeerHajAli — APPROVED** [review]
LGTM. @krfricke , is this ok to merge?

**Review by krfricke — APPROVED** [review]

**Pull request merged**
