### PR TITLE
[serve] Remove JSON ser/de logic from DAG building

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Originally, we planned to export the full DAG nodes into the Serve config file so we made them JSON serializable. That is no longer the API, which is now quite stable, so removing the JSON serialization code as it adds quite a lot of complexity.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@shrekris-anyscale you're probably best person to review this.

All I did was delete the json ser/de code and use `cloudpickle` instead.

**Review by shrekris-anyscale — APPROVED** [review]
Nice, thanks for deleting all that code! The changes so far look good. Couple questions–

1. Could you also fix the typo (`dummpy` -> `dummy`) in [this line](https://github.com/ray-project/ray/blob/b56aab4535d914acda19b4d764ff79c1c25fb686/python/ray/serve/deployment.py#L269) while you're at it?
2. Should we `pickle` deployments [when we `bind` them](https://github.com/ray-project/ray/blob/b56aab4535d914acda19b4d764ff79c1c25fb686/python/ray/serve/deployment.py#L270) instead of schematizing them? I believe we're schematizing them right now to make the nodes json-serializable.

**Comment by edoakes** [comment]
@shrekris-anyscale good catch - fixed the typo.

That sounds like a good further simplification. Do you want to take a stab at it if/when you have time?

**Comment by shrekris-anyscale** [comment]
> That sounds like a good further simplification. Do you want to take a stab at it if/when you have time?

Yeah, I can take it when I get more time.

**Pull request merged**
