### PR TITLE
[Doc] Make front page images non clickable

### LINKED ISSUE #32737: [Doc] Front page big buttons link to images instead of docs pages
### Description

Screenshot 2023-02-22 at 10 44 42 AM
On the front page of the docs, the first thing I clicked was the image "Getting started", which is a large clickable area.

I expected it to take me to a Getting Started doc page. Instead, it takes me to a page with just that image on it:

Screenshot 2023-02-22 at 10 45 53 AM

This seems nitpicky but I think this will be the first click for a lot of users so it's worth optimizing the experience here. We don't want their first impression to be that something is broken or they made a mistake. Might be enough to just not make it clickable.

### Link

_No response_

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
A Sphinx issue automatically makes images clickable whenever they're scaled (see https://stackoverflow.com/questions/40096251/disable-click-behavior-for-images). Clicking takes you to a full size version of the image.

On the front page of the docs, there are four prominent images that look like buttons. The user would expect clicking them to take you to a docs page, but instead it just takes you to the image. (See the linked issue for details)  

Since there's no single docs page corresponding to each of these four images, in this PR we opt to make these images non clickable.

## Related issue number

Closes https://github.com/ray-project/ray/issues/32737
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by angelinalg** [comment]
Thank you for finding and fixing that, @architkulkarni!

Going to assign this to someone in the codeowner group who has more context than me for a review of the code.

**Comment by architkulkarni** [comment]
Doc build looks good, non clickable as desired https://ray--32738.org.readthedocs.build/en/32738/

**Comment by architkulkarni** [comment]
@maxpumperla Could you please review this when you get a chance?

**Review by maxpumperla — APPROVED** [review]
thanks!

**Pull request merged**
