### PR TITLE
[Streaming Generator] Streaming generator wait prototype

### PR DESCRIPTION
**Pull request by rkooo567**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
Question, do we handle fetch_local with the wait here as well?

**Comment by rkooo567** [comment]
@ericl I am reimplementing this feature now actually. After that, it should work with fetch_loca=True.

This branch doesn't work with it (it is same as always fetch_local=False). This branch has other flaws that are pretty critical, so please use the branch just to prototype the integration with the new API!

**Comment by rkooo567** [comment]
@ericl @amogkam the implementation that will work with local_fetch will be available by tomorrow. Sorry for the delay (I was an oncall last week)!

**Comment by rkooo567** [comment]
Actually I think this branch will work https://github.com/ray-project/ray/pull/36071. 

Note that this is not compatible with ray.get yet (I believe it is not a requirement for ray data)

**Pull request closed without merging**
