### PR TITLE
[Data] should set num_returns in ray.wait inside ray data progress bar

### LINKED ISSUE #46674: [Data] Execution of repartition stuck at `ray.wait`
### What happened + What you expected to happen

Ray data driver uses 100% cpu inside the following stack while reparititioning large dataset.

```python
Thread 221304 (idle): "StreamingExecutor-8c9ed384e1f943f4bc2277102326887ca"
    absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashSetPolicy<ray::ObjectID>, absl::lts_20230125::hash_internal::Hash<ray::ObjectID>, std::equal_to<ray::ObjectID>, std::allocator<ray::ObjectID> >::prepare_insert (/usr/local/lib/python3.9/dist-packages/ray/_raylet.so)
    absl::lts_20230125::container_internal::raw_hash_set<absl::lts_20230125::container_internal::FlatHashSetPolicy<ray::ObjectID>, absl::lts_20230125::hash_internal::Hash<ray::ObjectID>, std::equal_to<ray::ObjectID>, std::allocator<ray::ObjectID> >::EmplaceDecomposable::operator()<ray::ObjectID,ray::ObjectID const&> (/usr/local/lib/python3.9/dist-packages/ray/_raylet.so)
    ray:core:CoreWorker::Wait (/usr/local/lib/python3.9/dist-packages/ray/_raylet.so)
    wait (/usr/local/lib/python3.9/dist-packages/ray/_raylet.so)
    wait (/usr/local/lib/python3.9/dist-packages/ray/_private/worker.py:2927
    wrapper (/usr/local/lib/python3.9/dist-packages/ray/_private/client_mode_hook.py:103)
    auto_init_wrapper (/usr/local/lib/python3.9/dist-packages/ray/_private/auto_init_hook.py:21
    fetch_until_complete (/usr/local/lib/python3.9/dist-packagges/ray/data/_internal/progress_bar.py:101
    execute (/usr/local/lib/python3.9/dist-packages/ray/data/_internal/planneer/exchange/split_repartition_task_scheduler.py:93
    split_repartition_fn (/usr/local/lib/python3.9/dist-packages/ray/data/_internal/planner/repartition.py:78
    all_inputs_done (/usr/local/lib/python3.9/dist-packages/ray/dat:a/_internal/execution/operators/base_physical_operator.py:93
    update_operator_states (/usr/local/lib/python3.9/dist-packages/ray/data/_internal/execution/streaming_executor_state.py:498
    _scheduling_loop_step (/usr/local/lib/python3.9/dist-packages/ray/data/_internal/execution/streaming_executor.py:336
    run (/usr/local/lib/python3.9/dist-packages/ray/data/_internal/execution/streaming_executor.py:237
    _bootstrap_inner (/usr/lib/python3.9/threading.py:954)
    _bootstrap (/usr/lib/python3.9/threading.py:912)
    clone (/lib/x86_64-linux-gnu/libc-2.31.so)
```

After digging into source code, ray data's progress bar does not set `num_returns` for `ray.wait`, and thus it returns only one block once a time.
https://github.com/ray-project/ray/blob/d2add3bcf488b285dd495e83ca157f86eec92881/python/ray/data/_internal/progress_bar.py#L98

### Versions / Dependencies

Ray 2.10

### Reproduction script

```python
ds = ray.data.range(10000000, override_num_blocks=5000)
ds = ds.repartition(200000)
ds.materialize()
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by tespent**
## Why are these changes needed?

Fixes #46674 

## Related issue number

Closes #46674 

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X] This PR is not tested :(

### CODE REVIEW

**Comment by raulchen** [comment]
I agree that the default `num_returns=1` is too small and can significant overheads. But on the other hand, I'm also concerned that if we simply wait for all remaining objects, it can also regress small-scaled latency-sensitive workloads. 
A better mid-ground solution would be make the `num_returns` proportional to the remaining. But I'm not sure what is the best value. We need to do some tests with different percentages on the release tests. cc @scottjlee

**Comment by scottjlee** [comment]
I ran release tests comparing master vs. the changes in this PR. Here are the results:

```
| Test Name                                      | Runtime (Master) | Runtime (PR) | % Difference |
|------------------------------------------------|------------------|--------------|--------------|
| torch_batch_inference_1_gpu_10gb_parquet       | 65.91            | 73.49        | 11.49%       |
| stable_diffusion_benchmark                     | 1166.5           | 1308.18      | 12.15%       |
| read_parquet_train_16_gpu                      | 125.4            | 116.5        | -7.10%       |
| read_images_train_1_gpu_5_cpu                  | 900.3            | 899.7        | -0.07%       |
| iter_tensor_batches_benchmark_multi_node       | 76.4             | 83.4         | 9.16%        |
| dataset_shuffle_random_shuffle_1tb             | 560.8            | 450.5        | -19.67%      |
```

so it looks like larger workloads are negatively impacted. @raulchen

**Comment by tespent** [comment]
I think tasks like inference with a 10gb dataset might be too small to expose the issue behind this change, thus causing performance degradation. In our jobs, an repartition from ~5,000 to ~20,000 blocks on a 360 nodes cluster takes about 1 hour without this change but only about 10min after that. A larger value of num_returns is desirable for such case.

Although it looks ugly and requires many efforts to choose a better magic number, perhaps we can use piecewise function to mitigate impact on smaller datasets? for example: (50 and 4000 blocks are the turning points for the below function)
```
num_returns=int(max(1, 0.5*len(remaining)-100, 0.8*len(remaining)-1300))
```

**Review by scottjlee — APPROVED** [review]
Discussed with @raulchen offline, we concluded that it's fine to use `len(remaining)` as num_returns here, since it is used in the context of AllToAllOperators and not the overall streaming executor. The streaming executor main usage in `process_completed_tasks()` has a separate loop and timeout: https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/execution/streaming_executor_state.py#L402-L407

**Review by raulchen — APPROVED** [review]

**Pull request merged**
