### PR TITLE
[CI] Buildkite PR Environment for Simple Tests

### PR DESCRIPTION
**Pull request by simon-mo**
Before reviewing, I would encouraging you to scroll down and click the buildkite links to view the builds.

This PR adds Ray Core tests to our new buildkite CI environment. Most of the changes are small fixes to get the build environment working. The important files are:
- .buildkite/Dockerfile: all builds will happen inside this docker container. The CI system will first build the docker container as specified by the Dockerfile, then run tests.
- .buildkite/pipeline.yml: This pipeline file list builds to run inside the docker container. 

Most of the actual infrastructure code, as well as the real pipeline yaml is in https://github.com/ray-project/buildkite-ci-stack

Additionally, we are just sharing the pool of resources for both master build and pull request at this stage. This is fine because we are not using the pipeline to perform asset uploading at all. 

Lastly, two followup work will come soon:
1. Add EKS for K8s operator testing
2. Modularize terraform infra so dev, pr, and branch builds are separated.

### CODE REVIEW

**Review by ijrsvt — COMMENTED** [review]
Not for this PR--but is the plan to make `ci/travis` something mroe general like `ci`?

**Review by ijrsvt — COMMENTED** [review]
One other question, I was wondering why the docker image isn't an 'artifact' of the first step.
Furthermore, how many ECR images will this generate? One per execution?

**Comment by simon-mo** [comment]
Correct, once per execution. I will apply lifecycle rule to auto delete images less than X days for ECR repo.

**Comment by ijrsvt** [comment]
> Correct, once per execution. I will apply lifecycle rule to auto delete images less than X days for ECR repo.

Sounds Good, I do know that ECR costs an add up over time, so I think a removal policy (either time based or  only keep the last "X" images) would be important. ([I didn't realize that ECR offer these amazing lifecycle rules](https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html)).

**Review by thomasdesr — APPROVED** [review]

**Pull request merged**
