### PR TITLE
Revert "[docs] add build skips"

### PR DESCRIPTION
**Pull request by maxpumperla**
Reverts ray-project/ray#33668. Master builds still don't work on rtd https://readthedocs.com/projects/anyscale-ray/builds/1396030/ complaining about configuration issues. This is the only recent build I'm aware of that changed the build config in any way, so I'm suspecting this is the issue.

### CODE REVIEW

**Comment by maxpumperla** [comment]
@clarng @krfricke @richardliaw this one seems to finally pass on readthedocs.

**Comment by clarng** [comment]
> @clarng @krfricke @richardliaw this one seems to finally pass on readthedocs.

sg let's wait for CI to pass

**Review by richardliaw — APPROVED** [review]

**Comment by clarng** [comment]
@maxpumperla can we cherry pick this to release branch?

@zhe-thoughts  for approval

**Comment by zhe-thoughts** [comment]
Approved

**Comment by clarng** [comment]
Can we cherrypick this to 2.4.0?

cc @zhe-thoughts  for approval

**Comment by zhe-thoughts** [comment]
Approved for picking

**Pull request merged**
