### PR TITLE
Support calling positional arguments by keyword (fix #998)

### LINKED ISSUE #998: Calling a remote function with a keyword argument fails
Not sure if this is a bug or a missing feature:
```
import ray

@ray.remote
def f(a):
    return a+1
    
ray.init()

f.remote(1)
f.remote(a=1)
```
 The last line produces this error message when using ray 0.2.0:

> Exception: The name 'a' is not a valid keyword argument for the function 'f'

### PR DESCRIPTION
**Pull request by AdamGleave**
## What do these changes do?

Python positional arguments can also be called via their keyword, with Python allowing the caller to choose between these two styles. (Exception: some built-in and C-bound functions only support positional arguments.) Ray only supported calling keyword arguments when they had a default value, a surprising semantic for Python users. 

This PR adds support keyword arguments in all common cases. It also adds unit tests to verify Ray accepts the keyword arguments, and rejects invalid uses.

There are a few unusual cases it does not support (but will warn the user of):
  
  * We do not handle arguments that can only be specified by keyword; this happens when keyword arguments are defined after ```*``` or ```*args```. Ideally we'd support this too -- I've intentionally written code like def f(*, kwd1, kwd2) to force callers to use keyword arguments. This doesn't seem difficult conceptually, but requires changing the return type of extend_args to be args, kwargs rather than just. This impacts a number of call sites I do not understand fully, so I decided not to touch this.
  * We do not support **kwargs (an existing limitation in Ray).

## Related issue number

Addresses #998 (apart from the caveats described above).

### CODE REVIEW

**Comment by AdamGleave** [comment]
I also note that funcsigs has a function Signature.bind that does exactly what extend_args is built to do, and should handle all the weird edge cases for us. I didn't make this change as there is some Cython-related magic going on in get_signature_params that I think might break this. Could someone who understands the related code better comment?

**Comment by robertnishihara** [comment]
Thanks @AdamGleave, this looks really great!

I think you're right that we need to switch to having `extend_args` return `args` and `kwargs`. The only challenge here is that we will need a slightly different way of encoding that in our C++ "TaskSpecification" object.

Could you quickly run something like

```python
import ray
import cProfile

ray.init()

@ray.remote
def f(a, b, c, x=1, y=2, z=3):
    pass

ray.get(f.remote(1, 2, 3))

cProfile.run('for _ in range(10000): f.remote(1, 2, 3)')
```

before and after this change and see if the amount of time spent in `extend_args` changes much? It doesn't look like it should.

@danielsuo implemented support for Cython in #1193.

**Comment by robertnishihara** [comment]
Ok, sounds good.

I'm seeing the following test failure from `python test/runtest.py APITest.testVariableNumberOfArgs`

```
======================================================================
FAIL: testVariableNumberOfArgs (__main__.APITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/runtest.py", line 607, in testVariableNumberOfArgs
    self.assertTrue(test_functions.varargs_and_kwargs_exception_thrown)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 3.626s

FAILED (failures=1)
```

Looks like that test needs to be updated.

Also, can you run

```
yapf --style=pep8 -i python/ray/signature.py
```

and commit the resulting change to that file? We have some fairly strict linting checks.

**Comment by AdamGleave** [comment]
I've updated signature.py to conform to code style. yapf made some awkward line breaks so I manually split out some of the deeply nested booleans to make the structure clearer.

Apologies for not catching that failing test. I think Ray should accept functions of that form (```*args``` after a keyword argument), it is valid Python albeit dubious coding style, so I have removed that test. If there is a reason for us forbidding this case then I can add a check in signature.py to forbid this.

**Comment by robertnishihara** [comment]
Ok thanks! Yeah, we should support functions of that form. The only reason for the test was that they didn't work before this PR I think.

**Comment by robertnishihara** [comment]
I had to push a small change, I think our versions of yapf may differ. Anyway, will merge soon. Thanks again!

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
Thanks again, this is a huge help!

**Pull request merged**
