### PR TITLE
[RLlib] Fix broken test_distributions.py (test_categorical)

### PR DESCRIPTION
**Pull request by sven1977**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
FYI @sven1977 looks like the test is still failing here

**Comment by sven1977** [comment]
yeah, still trying things out. It's not reproducible on my Mac.
I am getting a warning, though:
```
/Users/sven/opt/anaconda3/envs/ray/lib/python3.7/site-packages/tensorflow_probability/python/experimental/substrates/jax/internal/dtype_util.py:111: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return np.issubdtype(np.dtype(dtype), np.float)
```

Trying float64 now ...

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@sven1977 looks good, you probably want to re-enable the test in the `BUILD` file though (I disabled in a previous PR to avoid it failing on master).

**Comment by sven1977** [comment]
Cool, will re-enable the test (the JAX part will still be disabled, then).

**Pull request merged**
