### PR TITLE
[serve] Fix passing deprecated `loop` param to `asyncio.Event`

### LINKED ISSUE #43597: CI test linux://python/ray/serve/tests:test_autoscaling_metrics_on_handle is flaky
CI test **linux://python/ray/serve/tests:test_autoscaling_metrics_on_handle** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3208#018df753-0f7f-41cd-9e5e-331b151c6ed4
	- https://buildkite.com/ray-project/postmerge/builds/3193#018df676-8882-4341-8a62-b93b7de7790a
	- https://buildkite.com/ray-project/postmerge/builds/3183#018df59a-1fa1-428a-a4e5-4e71a29878d6
	- https://buildkite.com/ray-project/postmerge/builds/3179#018df487-83aa-42a0-bdd2-12284ccbafb7
	- https://buildkite.com/ray-project/postmerge/builds/3171#018df22b-2936-401f-80be-9e8e85e345ae

DataCaseName-linux://python/ray/serve/tests:test_autoscaling_metrics_on_handle-END
Managed by OSS Test Policy

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Deprecated in Python 3.11, so those tests are failing. I've refactored a bit to not pass the loop around unnecessarily too.

## Related issue number

Closes https://github.com/ray-project/ray/issues/43597

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zcin** [comment]
@edoakes I think I remember seeing an error about trying to use an `asyncio.Event` object from a different event loop/thread before, which is why I changed it to `asyncio.Event(loop=event_loop)`. I think since the `Router`, and therefore `RouterMetricsManager` and `MetricsPusher`, is initialized in the main thread, while the asyncio.Event needs to be used in the special router event loop?

**Comment by edoakes** [comment]
> @edoakes I think I remember seeing an error about trying to use an `asyncio.Event` object from a different event loop/thread before, which is why I changed it to `asyncio.Event(loop=event_loop)`. I think since the `Router`, and therefore `RouterMetricsManager` and `MetricsPusher`, is initialized in the main thread, while the asyncio.Event needs to be used in the special router event loop?

Oh... if this is the case then we need to lazily initialize it. Let me update.

**Review by zcin — APPROVED** [review]
Thanks!

**Review by GeneDer — APPROVED** [review]
LGTM!

**Pull request merged**
