### PR TITLE
[rllib] Add merge_trainer_config arguments to trainer template

### LINKED ISSUE #17151: [rllib] SAC custom model config error
### What is the problem?

RLLib algorithms that don't have the standard model configuration for custom models have key errors when merging with the common config.

For example in SAC, the Q model has the following default configuration:
```
    "Q_model": {
        "fcnet_hiddens": [256, 256],
        "fcnet_activation": "relu",
        "post_fcnet_hiddens": [],
        "post_fcnet_activation": None,
        "custom_model": None,  # Use this to define custom Q-model(s).
        "custom_model_config": {},
    },
```

Whenever anything is added to `custom_model_config` you will get the following error (using the reproduction script):
```
(pid=183)   File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
(pid=183)   File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
(pid=183)     return method(__ray_actor, *args, **kwargs)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
(pid=183)     Trainer.__init__(self, config, env, logger_creator)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 584, in __init__
(pid=183)     super().__init__(config, logger_creator)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
(pid=183)     self.setup(copy.deepcopy(self.config))
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 693, in setup
(pid=183)     config)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1340, in merge_trainer_configs
(pid=183)     cls._override_all_subkeys_if_type_changes)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/utils/util.py", line 278, in deep_update
(pid=183)     deep_update(original[k], value, new_keys_allowed)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/utils/util.py", line 278, in deep_update
(pid=183)     deep_update(original[k], value, new_keys_allowed)
(pid=183)   File "/home/julius/miniconda3/envs/ray/lib/python3.7/site-packages/ray/tune/utils/util.py", line 264, in deep_update
(pid=183)     raise Exception("Unknown config parameter `{}` ".format(k))
(pid=183) Exception: Unknown config parameter `test`
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
rllib train --run SAC --env CartPole-v0 --config='{"Q_model":{"custom_model_config":{"test":""}}}'
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

@richardliaw I am working on a fix for this, just putting this issue out now to document it.

### PR DESCRIPTION
**Pull request by juliusfrost**
## Why are these changes needed?

Adds configuration merge settings ([`merge_trainer_config`](https://github.com/ray-project/ray/blob/93c16346bf46c2b1d163ece4d32827e50ed581a6/rllib/agents/trainer.py#L1321)) to trainer template so users have more flexibility to define custom configs.
Also fixes the SAC related issue with `custom_model_config` in #17151

## Related issue number

Fixes #17151

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by juliusfrost** [comment]
@richardliaw

**Comment by richardliaw** [comment]
nice! bumping to sven and michael, who have more context here (about sac, trainer configs)

**Comment by juliusfrost** [comment]
Hi @sven1977 @michaelzhiluo this PR is ready and I would greatly appreciate your review!

**Review by sven1977 — APPROVED** [review]
Looks good. Thanks for the enhancement @juliusfrost !

**Comment by juliusfrost** [comment]
@sven1977 Thank you so much for the review! @richardliaw Would appreciate it if you could merge it for me :)

**Pull request merged**
