### PR TITLE
[autoscaler] Should use internal IP for ssh

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

As reported on the dev list, the external ip is not always accessible from the head node.

@richardliaw

### CODE REVIEW

**Comment by ericl** [comment]
Ah, there is an issue where you need to use the external_ip for the initial SSH.

**Comment by ericl** [comment]
Tested and this seems to work

**Review by robertnishihara — APPROVED** [review]

**Comment by richardliaw** [comment]
Test failures look unrelated.

**Comment by npyoung** [comment]
Just tried the latest build and it seems to work, thanks! I did notice that
my EC2 instances no longer get named and the ray:etc tags don't get
assigned. Not sure if that's specific to this build, something that changed
since ray 0.3.1, or another issue entirely.

**Comment by ericl** [comment]
Oh, the tag name change is due to a recent PR to support the GCP labeling
scheme as well. I guess on unintentional side effect is it breaks AWS
names. I'll see if that can be fixed.

**Pull request merged**
