### PR TITLE
[Hotfix] Fix the failure of C++ tests

### LINKED ISSUE #27237: [CI][runtime env] osx://cpp:test_python_call_cpp is failing on master/release branch
### What happened + What you expected to happen

image

@SongGuyang please unbreak it now.

### Versions / Dependencies

latest ray.

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by SongGuyang**
Signed-off-by: 久龙 <guyang.sgy@antfin.com>

Fix the issue https://github.com/ray-project/ray/issues/27237

### CODE REVIEW

**Comment by scv119** [comment]
@architkulkarni can you take a look at the runtime env related code?

**Comment by scv119** [comment]
@SongGuyang is it ready to merge? also can you help me understand the impact of release rc0 without this fix?

**Comment by SongGuyang** [comment]
@scv119 The test has passed in my mac after this PR. But I can't varify it in CI now. I think we can merge it and release rc0 first. But If we don't pick this PR, the basic cpp tests will fail after the users install the rc wheel.

**Review by architkulkarni — APPROVED** [review]
Runtime env code LGTM

**Pull request merged**
