### PR TITLE
[Data] Deprecate `Preprocessor`

### PR DESCRIPTION
**Pull request by bveeramani**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Superskyyy** [comment]
Hi, what is the background of removing the preprocessors?

**Comment by Superskyyy** [comment]
We are supposed to deprecate all predictors after this change right?

**Comment by bveeramani** [comment]
Hey @Superskyyy, we haven't finalized a decision on what we want to do with preprocessors yet

**Comment by bveeramani** [comment]
Will re-open this PR if we end up pursuing deprecation

**Pull request closed without merging**
