### PR TITLE
wrap models with DistributionalQModel when running DQN

### LINKED ISSUE #6091: DQN does not allow custom models
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8.0.dev6
- **Python version**: 3.7.5
- **Exact command to reproduce**:

The following code tries to set built-in VisionNetwork from TF as custom model and it errors out as described below. However, the code succeeds if custom model was not set in which case exact same VisionNetwork gets selected automatically by [_get_v2_model](https://github.com/ray-project/ray/blob/master/rllib/models/catalog.py#L517). The cause of this issue is explained below however I'm not sure about the fix.

```
import ray
from ray.rllib.agents.dqn import DQNTrainer
from ray.rllib.models import ModelCatalog
from ray.rllib.models.tf.visionnet_v2 import VisionNetwork

ModelCatalog.register_custom_model("my_model", VisionNetwork)

config = {'model': {
            "custom_model": "my_model",
            "custom_options": {},  # extra options to pass to your model
        }}
ray.init()

agent = DQNTrainer(config=config, env="BreakoutNoFrameskip-v4")
```

### Describe the problem
Current code in master is not allowing the use of custom models in DQN. When trying to use custom model (either for TF or PyTorch),  error is thrown indicating that model has not been subclassed from `DistributionalQModel`. This happens even when custom model is set to simply `ray.rllib.models.tf.visionnet_v2.VisionNetwork`.

Error message:
```
'The given model must subclass', <class 'ray.rllib.agents.dqn.distributional_q_model.DistributionalQModel'>)
```

### Source code / logs
Cause of this issue is [this check](https://github.com/ray-project/ray/blob/master/rllib/models/catalog.py#L262). Notice that this check is only done if custom_model is set. Apparently built-in models don't subclass `DistributionalQModel` either however as this check is not applied to built-in models they work fine.

### PR DESCRIPTION
**Pull request by AmeerHajAli**
## Why are these changes needed?
Prevents circular dependency of custom models when running DQN - #6091.
I also added a test that checks internal custom models for DQN and makes sure it does not accidentally break for other policies. PR after code review of PR #6254.

## Related issue number
Closes #6091

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by AmeerHajAli** [comment]
jenkins, retest this please

**Comment by AmeerHajAli** [comment]
I reran the same test locally and it passes. :/

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
Merged, thanks!

**Pull request merged**
