### PR TITLE
[ci] add dockerignore file

### PR DESCRIPTION
**Pull request by aslonnie**
do not include stuff that is not required for testing

### CODE REVIEW

**Comment by aslonnie** [comment]
running all tests here:

https://buildkite.com/ray-project/premerge/builds/16753

**Comment by aslonnie** [comment]
if this works, will cut the size of the build context in half

we can probably remove much more if we have an explicit declaration of the closure of source files required by ray.

**Comment by can-anyscale** [comment]
If it passes it works!

**Review by can-anyscale — APPROVED** [review]

**Pull request merged**
