### PR TITLE
[data] input files can be out of order

### PR DESCRIPTION
**Pull request by aslonnie**
so use a set for the test.

### CODE REVIEW

**Comment by aslonnie** [comment]
// hail to all the code owners of this test file..

**Comment by aslonnie** [comment]
example failure on premerge: https://buildkite.com/ray-project/premerge/builds/11778#018bd19d-d1bf-41ce-88da-fa8d4171b7b9/6-364

**Comment by aslonnie** [comment]
https://github.com/ray-project/ray/blob/master/python/ray/data/dataset.py#L2677

I am a bit surprised this can return files names that are not sorted..

**Comment by aslonnie** [comment]
````
>>> list(set(['1', '2', '3']))
['2', '3', '1']
````

probably based on hash key / iteration order..

**Comment by aslonnie** [comment]
and because `Time complexity: O(num input files)` , sorting in the implementation seems to be forbidden.

**Comment by aslonnie** [comment]
maybe the `set()` in the `input_files()` should just be used for dedup, so the order of the file names can be preserved as much as possible?

suggestions?

**Comment by bveeramani** [comment]
@aslonnie this is already fixed by https://github.com/ray-project/ray/pull/41171

**Pull request closed without merging**
