### PR TITLE
[Ray release infra] Script to compare perf metrics between releases

### PR DESCRIPTION
**Pull request by cadedaniel**
```
$ ./compare_perf_metrics -h
usage: compare_perf_metrics [-h] old_dir_name new_dir_name

Automate the process of calculating relative change in perf_metrics. This makes catching regressions much easier.

positional arguments:
  old_dir_name  The name of the directory containing the last release performance logs, e.g. 2.2.0
  new_dir_name  The name of the directory containing the new release performance logs, e.g. 2.3.0

optional arguments:
  -h, --help    show this help message and exit
```

Example output:
```
$ ./compare_perf_metrics 2.2.0 2.3.0 | sort -nr -k2
REGRESSION 63.52%: 1_n_async_actor_calls_async (THROUGHPUT) regresses from 10613.303070856366 to 3871.8303546442353 (63.52%) in 2.3.0/microbenchmark.json
REGRESSION 60.78%: 1_n_actor_calls_async (THROUGHPUT) regresses from 11646.429573331836 to 4567.333584384749 (60.78%) in 2.3.0/microbenchmark.json
REGRESSION 50.51%: 1000000_queued_time (LATENCY) regresses from 186.92522427999995 to 281.346150999 (50.51%) in 2.3.0/scalability/single_node.json
REGRESSION 34.67%: 107374182400_large_object_time (LATENCY) regresses from 255.3529769390001 to 343.87277882600006 (34.67%) in 2.3.0/scalability/single_node.json
REGRESSION 32.12%: n_n_actor_calls_async (THROUGHPUT) regresses from 35151.93038362862 to 23861.853635616822 (32.12%) in 2.3.0/microbenchmark.json
REGRESSION 31.20%: single_client_tasks_and_get_batch (THROUGHPUT) regresses from 11.24301668594478 to 7.734729483220359 (31.20%) in 2.3.0/microbenchmark.json
REGRESSION 24.10%: multi_client_tasks_async (THROUGHPUT) regresses from 32133.367075183483 to 24388.235673741856 (24.10%) in 2.3.0/microbenchmark.json
REGRESSION 21.08%: single_client_tasks_sync (THROUGHPUT) regresses from 1294.2667282228672 to 1021.4266276252367 (21.08%) in 2.3.0/microbenchmark.json
REGRESSION 18.55%: n_n_async_actor_calls_async (THROUGHPUT) regresses from 28665.946308284096 to 23349.39968007501 (18.55%) in 2.3.0/microbenchmark.json
REGRESSION 17.62%: 1_1_actor_calls_concurrent (THROUGHPUT) regresses from 4668.012480386666 to 3845.4307017030883 (17.62%) in 2.3.0/microbenchmark.json
REGRESSION 15.97%: multi_client_put_gigabytes (THROUGHPUT) regresses from 38.43419037441269 to 32.297592597613566 (15.97%) in 2.3.0/microbenchmark.json
REGRESSION 13.13%: 1_1_actor_calls_sync (THROUGHPUT) regresses from 2181.5451120926223 to 1895.1826839650737 (13.13%) in 2.3.0/microbenchmark.json
REGRESSION 10.32%: n_n_actor_calls_with_arg_async (THROUGHPUT) regresses from 2831.4666955768935 to 2539.392384949167 (10.32%) in 2.3.0/microbenchmark.json
REGRESSION 10.19%: single_client_tasks_async (THROUGHPUT) regresses from 10904.790007336374 to 9793.42578856184 (10.19%) in 2.3.0/microbenchmark.json
REGRESSION 9.93%: avg_pg_create_time_ms (LATENCY) regresses from 0.8335708558568591 to 0.916350372372258 (9.93%) in 2.3.0/stress_tests/stress_test_placement_group.json
REGRESSION 9.53%: 10000_get_time (LATENCY) regresses from 26.32780160499999 to 28.83745290899998 (9.53%) in 2.3.0/scalability/single_node.json
REGRESSION 8.07%: single_client_get_calls_Plasma_Store (THROUGHPUT) regresses from 5877.43374153343 to 5403.340357166397 (8.07%) in 2.3.0/microbenchmark.json
REGRESSION 7.01%: 1_1_async_actor_calls_sync (THROUGHPUT) regresses from 1479.0342425173185 to 1375.3347579969973 (7.01%) in 2.3.0/microbenchmark.json
REGRESSION 5.47%: single_client_put_calls_Plasma_Store (THROUGHPUT) regresses from 5893.086020155377 to 5570.884598806502 (5.47%) in 2.3.0/microbenchmark.json
REGRESSION 5.41%: 1_1_async_actor_calls_with_args_async (THROUGHPUT) regresses from 2087.8113920074993 to 1974.7614718203085 (5.41%) in 2.3.0/microbenchmark.json
REGRESSION 5.34%: avg_pg_remove_time_ms (LATENCY) regresses from 0.847586638137635 to 0.8928828003007966 (5.34%) in 2.3.0/stress_tests/stress_test_placement_group.json
REGRESSION 3.79%: placement_group_create/removal (THROUGHPUT) regresses from 1016.2011272594634 to 977.68192525157 (3.79%) in 2.3.0/microbenchmark.json
REGRESSION 2.59%: time_to_broadcast_1073741824_bytes_to_50_nodes (LATENCY) regresses from 91.34722920899992 to 93.7165343910001 (2.59%) in 2.3.0/scalability/object_store.json
REGRESSION 1.97%: 3000_returns_time (LATENCY) regresses from 6.100632732999998 to 6.2210802160000185 (1.97%) in 2.3.0/scalability/single_node.json
REGRESSION 1.92%: single_client_get_object_containing_10k_refs (THROUGHPUT) regresses from 12.380926011280408 to 12.143379797210303 (1.92%) in 2.3.0/microbenchmark.json
REGRESSION 0.49%: client__put_gigabytes (THROUGHPUT) regresses from 0.04628119129452739 to 0.046054468206325194 (0.49%) in 2.3.0/microbenchmark.json
2.3.0 does not have stress_tests/stress_test_many_tasks.json
2.2.0/microbenchmark.json does not have single_client_wait_1k_refs
2.2.0/benchmarks/many_tasks.json does not have used_cpus_by_deadline
2.2.0/benchmarks/many_tasks.json does not have dashboard_p99_latency_ms
2.2.0/benchmarks/many_tasks.json does not have dashboard_p95_latency_ms
2.2.0/benchmarks/many_tasks.json does not have dashboard_p50_latency_ms
2.2.0/benchmarks/many_pgs.json does not have dashboard_p99_latency_ms
2.2.0/benchmarks/many_pgs.json does not have dashboard_p95_latency_ms
2.2.0/benchmarks/many_pgs.json does not have dashboard_p50_latency_ms
2.2.0/benchmarks/many_nodes.json does not have used_cpus_by_deadline
2.2.0/benchmarks/many_nodes.json does not have dashboard_p99_latency_ms
2.2.0/benchmarks/many_nodes.json does not have dashboard_p95_latency_ms
2.2.0/benchmarks/many_nodes.json does not have dashboard_p50_latency_ms
2.2.0/benchmarks/many_actors.json does not have dashboard_p99_latency_ms
2.2.0/benchmarks/many_actors.json does not have dashboard_p95_latency_ms
2.2.0/benchmarks/many_actors.json does not have dashboard_p50_latency_ms
```

### CODE REVIEW

**Review by rickyyx — APPROVED** [review]
Nice!! 

could we make the output a bit less verbose? 
e.g. or something else 
```
some_metric: 10 -> 1 (-90%) [THROUGHPUT]
```
?

**Review by krfricke — COMMENTED** [review]
Nice! Does this replace https://github.com/ray-project/ray/blob/master/release/util/microbenchmark_analysis.py ?

**Comment by cadedaniel** [comment]
> Nice!!
>
> could we make the output a bit less verbose?
> e.g. or something else

> > some_metric: 10 -> 1 (-90%) [THROUGHPUT]
>
> ?

Is there a specific usage that would be made easier with a different output format? Open to change but this one is readable without headers and easy to sort by regression magnitude

> Nice! Does this replace https://github.com/ray-project/ray/blob/master/release/util/microbenchmark_analysis.py ?

Op didn't know about that. It supersedes in terms of functionality (since it supports perf_metrics in any of the benchmarks). Is that one a part of any automation or an existing process? I also don't mind having both tools...

**Comment by krfricke** [comment]
I don't think we actively use that script at the moment. Instead we rely on the dashboard to track metrics over time.

I'd say if the functionality of your script supersedes the old script, let's bin it. cc @rkooo567 to confirm this is fine.

**Comment by rkooo567** [comment]
I'd love to have a new script lol. I didn't know that script still exists (I wrote it when we release 0.85 lol)

**Comment by rkooo567** [comment]
can we update this to the release doc?

**Comment by rkooo567** [comment]
We can potentially report this data to the nightly dashboard and display too.

**Review by rkooo567 — APPROVED** [review]

**Comment by cadedaniel** [comment]
> can we update this to the release doc?

done https://www.notion.so/anyscale-hq/How-to-release-Ray-go-release-ray-28e4a2347577471288bbd7d64001fa88#fbc6c8ab7f3f4bfdb3f8a06c69c7a786

> We can potentially report this data to the nightly dashboard and display too.

agree!

**Pull request merged**
