### PR TITLE
[WIP][Core] limit log for gcs_server.out

### LINKED ISSUE #45678: [Core] gcs_server.out becomes too big
### What happened + What you expected to happen

We run a few Ray serve applications. After a few days, we found that our node will run out of disk space and cause all our Ray applications to go down. Upon further digging, it is the file `gcs_sever.out` file growing too big. I checked the source code. Looks like only `gcs_sever.err` is under log monitor but not for gcs_server.out`. 

[https://github.com/ray-project/ray/blob/d4fc01c584935ba4ebe4290a7ed8470f1fa82b74/python/ray/_private/log_monitor.py#L237](https://github.com/ray-project/ray/blob/d4fc01c584935ba4ebe4290a7ed8470f1fa82b74/python/ray/_private/log_monitor.py#L237)

I am very curious why. Is there any way to limit the max size of `gcs_server.out`? I appreciate your help!

### Versions / Dependencies

2.22.0

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by Bye-legumes**
## Why are these changes needed?

close https://github.com/ray-project/ray/issues/45678

## Related issue number

https://github.com/ray-project/ray/issues/45678
## Checks

- [√] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [√] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [√] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by frank-berlin** [comment]
How we get missing approval?

**Comment by Superskyyy** [comment]
> How we get missing approval?
@frank-berlin 
AFAIK this PR is not going to fix the problem (it's much more complicated than this), can you help confirm @Bye-legumes ?

**Comment by Bye-legumes** [comment]
> How we get missing approval?

HI, it's much complicate and you can refer to this PR https://github.com/ray-project/ray/pull/26121

**Comment by Bye-legumes** [comment]
close

**Pull request closed without merging**
