### PR TITLE
Revert "Revert "[Dashboard][event] Basic event module""

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#17068

### CODE REVIEW

**Comment by fyrestone** [comment]
@WangTaoTheTonic hi, i am not sure if this build fail is related to your PR: https://github.com/ray-project/ray/pull/16773

```
java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:5: error: package redis.clients.jedis does not exist
--
  | import redis.clients.jedis.Jedis;
  | ^
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:6: error: package redis.clients.jedis does not exist
  | import redis.clients.jedis.JedisPool;
  | ^
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:7: error: package redis.clients.jedis does not exist
  | import redis.clients.jedis.JedisPoolConfig;
  | ^
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:14: error: cannot find symbol
  | private JedisPool jedisPool;
  | ^
  | symbol:   class JedisPool
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:27: error: cannot find symbol
  | JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
  | ^
  | symbol:   class JedisPoolConfig
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:27: error: cannot find symbol
  | JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
  | ^
  | symbol:   class JedisPoolConfig
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:32: error: cannot find symbol
  | new JedisPool(jedisPoolConfig, ipAndPort[0], Integer.parseInt(ipAndPort[1]), 30000);
  | ^
  | symbol:   class JedisPool
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:35: error: cannot find symbol
  | new JedisPool(
  | ^
  | symbol:   class JedisPool
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:41: error: cannot find symbol
  | try (Jedis jedis = jedisPool.getResource()) {
  | ^
  | symbol:   class Jedis
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:52: error: cannot find symbol
  | try (Jedis jedis = jedisPool.getResource()) {
  | ^
  | symbol:   class Jedis
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:58: error: cannot find symbol
  | try (Jedis jedis = jedisPool.getResource()) {
  | ^
  | symbol:   class Jedis
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:72: error: cannot find symbol
  | try (Jedis jedis = jedisPool.getResource()) {
  | ^
  | symbol:   class Jedis
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:83: error: cannot find symbol
  | try (Jedis jedis = jedisPool.getResource()) {
  | ^
  | symbol:   class Jedis
  | location: class RedisClient
  | java/runtime/src/main/java/io/ray/runtime/gcs/RedisClient.java:89: error: cannot find symbol
  | try (Jedis jedis = jedisPool.getResource()) {
  | ^
  | symbol:   class Jedis
  | location: class RedisClient
  | Target //java:ray_java_pkg failed to build
```

The CI log: https://buildkite.com/ray-project/ray-builders-pr/builds/9094#60b52c76-0392-4a6f-afb0-96d809c96808

**Comment by WangTaoTheTonic** [comment]
`RedisClient.java` has been removed in master branch yesterday. I'm not sure why `post wheel test` still uses it. Guess the double-revert contains some information before yesterday.
Maybe we can retry this and file a new pull request with fresh new change if retry fails.

**Comment by fyrestone** [comment]
> `RedisClient.java` has been removed in master branch yesterday. I'm not sure why `post wheel test` still uses it. Guess the double-revert contains some information before yesterday.
> Maybe we can retry this and file a new pull request with fresh new change if retry fails.

This PR does not contain the `RedisClient.java`: https://github.com/ray-project/ray/tree/revert-17068-revert-16985-improve_test_events/java/runtime/src/main/java/io/ray/runtime/gcs

**Comment by fyrestone** [comment]
Just merged the latest master to trigger CI again.

**Review by fyrestone — APPROVED** [review]

**Pull request merged**
