### PR TITLE
[C++ Worker]Fix abi issue

### PR DESCRIPTION
**Pull request by qicosmos**
## Why are these changes needed?

Solve the problem: c++ worker's wheel package generated by ci can not run on linux, will throw std::bad_alloc.
Reason: Some dependent so built by ci is not compatible with user's compile environment because of ABI issue.
So add a compile option to solve the ABI problem.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

**Comment by mwtian** [comment]
I think downgrading Ray's ABI might not be a good idea. And I wonder how the flag can work with `-std=c++14` or newer C++ standards. Can you give more details about the environment with this problem, e.g. Linux version, gcc compiler version?

It seems recompiling libraries with GCC version >= 5.1 or building Ray in a private branch with the flag, can solve the issue better.

**Comment by qicosmos** [comment]
> I think downgrading Ray's ABI might not be a good idea. And I wonder how the flag can work with `-std=c++14` or newer C++ standards. Can you give more details about the environment with this problem, e.g. Linux version, gcc compiler version?
> 
> It seems recompiling libraries with GCC version >= 5.1 or building Ray in a private branch with the flag, can solve the issue better.

More details: http://litaotju.github.io/c++/2019/02/24/Why-we-need-D_GLIBCXX_USE_CXX11_ABI=0

GCC5 reimplement std::string and std::list, but some ray core dependent libraries compiled by gcc 4.x, so in gcc5 above version should use D_GLIBCXX_USE_CXX11_ABI to tell the compiler to keep old ABI, otherwise there will be ABI problems.

**Comment by iycheng** [comment]
@qicosmos I agree with @mwtian
My question here: could you tell more details about why downgrade the ABI? For example, which library did you notice is using the old ABI? Should we upgrade them instead of downgrade the ABI? We should try to use the latest ABI instead of degrading it.

**Comment by mwtian** [comment]
Hi @qicosmos, I'm also still not sure why this setting has to be the default for Ray wheels. This flag is not forward compatible with default ABI generated by newer GCC toolchains. Tensorflow and pytorch indeed build wheels with this option, but I believe it is more for backward compatibility with user's custom ops / extensions. In their instructions to build from source, this flag is not the default. Pytorch also offers C++11 ABI versions of libtorch. 

Unlike tensorflow & pytorch, Ray does not have any ABI dependents yet. Most Ray users right now would by default have compilers newer than GCC 5, e.g. from Ubuntu 16.04, 18.04 or 20.04. If Ray starts to have other use cases of C++ worker, either users have to (re-)compile their libraries with this flag which can be inconvenient, or Ray needs to provide a wheel with GCC C++11 ABI which has some cost on the Ray team. cc @pcmoritz @ericl who can have more insights.

**Comment by mwtian** [comment]
Just realized we are building a separate wheel for C++ API, to be released in Ray 1.7. If this build option just applies to the C++ API wheel and the ABI version is in the wheel name, it could be a better option.

**Comment by pcmoritz** [comment]
Ah, this is indeed a good question! Technically we have to go with whatever the `manylinux2014` standard that we use mandates (for our wheels). I can't find anything about it in the standard (neither in https://www.python.org/dev/peps/pep-0599/ nor https://github.com/pypa/manylinux), but the pytorch folks seem to believe that it should have `_GLIBCXX_USE_CXX11_ABI=0` (see https://github.com/pytorch/pytorch/issues/51039, specifically https://github.com/pytorch/pytorch/issues/51039#issuecomment-768970620). I think TensorFlow also uses that setting, see https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/tools/dockerfiles/tests/build-cpu.sh#L35. Unfortunately if I see this correctly, Arrow is not using this flag any more (https://github.com/apache/arrow/pull/3458). I'll sync back with the Arrow developers and see how they interpret manylinux2014.

Ideally we would use the new ABI because it has some improvements (the most important being std::list::size() is O(1) in the new and O(n) in the old ABI, so if we switch to the old ABI we need to look at the code to make sure we are not using std::list::size()). If it causes incompatibilities we have to look closer at what problems it causes and which python packages it causes incompatibilities with. I hope we can at least get pytorch, TensorFlow, Ray and Arrow to agree on a common setting for the flag :)

**Comment by pcmoritz** [comment]
Posted a thread in https://lists.apache.org/list.html?dev@arrow.apache.org

**Comment by pcmoritz** [comment]
Arrow devs suggested to ask this on the Python discussion forum which I did here: https://discuss.python.org/t/how-to-set-glibcxx-use-cxx11-abi-for-manylinux2014-and-manylinux2010-wheels/10551

**Comment by qicosmos** [comment]
> Ah, this is indeed a good question! Technically we have to go with whatever the `manylinux2014` standard that we use mandates (for our wheels). I can't find anything about it in the standard (neither in https://www.python.org/dev/peps/pep-0599/ nor https://github.com/pypa/manylinux), but the pytorch folks seem to believe that it should have `_GLIBCXX_USE_CXX11_ABI=0` (see [pytorch/pytorch#51039](https://github.com/pytorch/pytorch/issues/51039), specifically [pytorch/pytorch#51039 (comment)](https://github.com/pytorch/pytorch/issues/51039#issuecomment-768970620)). I think TensorFlow also uses that setting, see https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/tools/dockerfiles/tests/build-cpu.sh#L35. Unfortunately if I see this correctly, Arrow is not using this flag any more ([apache/arrow#3458](https://github.com/apache/arrow/pull/3458)). I'll sync back with the Arrow developers and see how they interpret manylinux2014.
> 
> Ideally we would use the new ABI because it has some improvements (the most important being std::list::size() is O(1) in the new and O(n) in the old ABI, so if we switch to the old ABI we need to look at the code to make sure we are not using std::list::size()). If it causes incompatibilities we have to look closer at what problems it causes and which python packages it causes incompatibilities with. I hope we can at least get pytorch, TensorFlow, Ray and Arrow to agree on a common setting for the flag :)

Also std::string is a problem, actually i tested a wheel package generated by ci, includes libray_api.so used by c++ worker template project, however when i tested it on my linux machine, found the std::string ABI problem leads an exception.

**Comment by qicosmos** [comment]
I added the ABI options only in c++ worker project to solve the ABI problem at the begging, but the c++ worker example ci failed, at last added the ABI option into .bazelrc, and resolved all problems.

**Comment by pcmoritz** [comment]
I think the most important decision here is what we do for the python wheel (for everything that gets dynamically linked into the python interpreter) because that might have implications on how compatible we are with other Python libraries and then on the C++ worker we have more flexibility, we just need to make sure that there is no mixture within the shared library for the C++ worker and we should be good.

**Comment by pcmoritz** [comment]
Digging into this a little more, I noticed that we are currently not producing manylinux2014 compatible wheels, I filed an issue here: https://github.com/ray-project/ray/issues/18506

This came up because according to the discussion in https://discuss.python.org/t/how-to-set-glibcxx-use-cxx11-abi-for-manylinux2014-and-manylinux2010-wheels/10551, if we used devtoolset-7 to produce our wheels, the `_GLIBCXX_USE_CXX11_ABI=0` would be automatically be forced (see https://bugzilla.redhat.com/show_bug.cgi?id=1546704), in which case we would be fine to not set the flag. However I think we are using devtoolset-8:  https://github.com/ray-project/ray/blob/4971e1394115a7a4c80f2e5b17c23df946883c4b/python/build-wheel-manylinux2014.sh#L30

My recommendation here is to enforce the manylinux2014 standard for our wheels, not set the `_GLIBCXX_USE_CXX11_ABI=0` by default and set it in the ray-cpp wheel if needed (or have two versions of that wheel if really needed).

**Comment by mwtian** [comment]
Thanks Phillip @pcmoritz for the detailed information and advice! Good point about Ray interoperating with Python interpreter and other wheels. I wonder if making the wheels conforming now would break some users, but it shouldn't be a big issue. 

@qicosmos I think we can try to process as follow: we can make Ray build conform to `manylinux2014` (again), and you can try to see if building the example project with `_GLIBCXX_USE_CXX11_ABI=0` would work. If not (less likely), the flag can be added to the `ray-cpp` wheel build process in `setup.py`. What do you think?

**Comment by qicosmos** [comment]
@pcmoritz Thanks for your advice.
@mwtian Do you mean replace the devtoolset-8-libasan-devel.x86_64 with devtoolset-7-libasan-devel.x86_64 in build-wheel-manylinux2014.sh and remove the ABI flag?

**Comment by mwtian** [comment]
We might be able to remove `devtoolset-8-libasan-devel.x86_64`, since we will be building separate asan wheels with clang toolchain instead. cc @rkooo567 @scv119 Then if everything works we can remove the ABI flag.

**Comment by scv119** [comment]
yup! That's the hope. I think we are blocked by the wheel containers

**Comment by qicosmos** [comment]
> We might be able to remove `devtoolset-8-libasan-devel.x86_64`, since we will be building separate asan wheels with clang toolchain instead. cc @rkooo567 @scv119 Then if everything works we can remove the ABI flag.

Okay, i will create a new pr to have a try.

**Comment by qicosmos** [comment]
The new pr is here:https://github.com/ray-project/ray/pull/18538

If the ci passed the problem will be solved:)

**Comment by qicosmos** [comment]
CI failed!https://buildkite.com/ray-project/ray-builders-pr/builds/13552#785d6039-8f01-4dc0-8327-0593e7bce8aa

**Comment by mwtian** [comment]
> CI failed!https://buildkite.com/ray-project/ray-builders-pr/builds/13552#785d6039-8f01-4dc0-8327-0593e7bce8aa

Very unfortunate. I guess there are other reasons why Ray wheels are incompatible with `_GLIBCXX_USE_CXX11_ABI=0`

**Comment by qicosmos** [comment]
@mwtian I have another idea: Remove the ABI flag and keep it in c++ worker template example projects, remove the ci test of c++ worker example to make sure ci passed.
In this way the ci can pass and the c++ user can use the wheel package.What do you think?

**Pull request merged**
