### PR TITLE
Worker <> GPU Mapping Information in Dashboard

### PR DESCRIPTION
**Pull request by mfitton**
## Why are these changes needed?
Instead of having average utilization of GPUs for each node, this PR adds entries for each GPU's utilization independently.
In addition, this PR adds information about to which GPU each worker is assigned. 

This enables a workflow where, for example, a user sees that one of their GPUs is underutilized, then looks to see which worker is attached to that GPU, allowing them to link the underutilization to a specific worker, then to an actor or task.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by mfitton** [comment]
@edoakes it's ready for review. Just getting a screenshot on a big cluster.

**Review by edoakes — COMMENTED** [review]
Looks reasonable to me, please ping when you have a screenshot

**Comment by mfitton** [comment]
image (1)
There is a weird instance of one of the slots being undefined, leading to rendering a ? mark there instead of a number. I thought that perhaps this only happens for partial GPU assignments, but that doesn't seem to be the case exactly, because here each worker is assigned 2 GPUs and only one is showing up with an undefined slot. I'll need to dig into the backend further to see why exactly this is getting passed in empty.

**Comment by mfitton** [comment]
Also @richardliaw here's the PR corresponding to our slack chat.

**Comment by richardliaw** [comment]
@mfitton post the snapshot of most recent version when you get the chance?

**Comment by mfitton** [comment]
@richardliaw here's a screenshot after the latest changes. I did this on a smaller cluster than previously because the big machines are pretty expensive, and I'd like to keep this running for a demo tomorrow afternoon.

image

**Comment by mfitton** [comment]
I added a bit of a dirty trick to fix "?" bug in some scenarios. The API really is passing through an entry with no slot, which is just bizarre, but it appears to always correspond to the first GPU, except in the case where there is a partial allocation, in which case we truly don't know which GPU a worker is pinned to.

**Comment by mfitton** [comment]
@richardliaw would you mind posting your approval here if you think this is good to go?
@edoakes could you please review this when you get the chance?

**Comment by richardliaw** [comment]
what does `[0]: 1` mean?

**Comment by mfitton** [comment]
GPU in slot 0 is fully assigned to that worker is what the [0]: 1 means.

**Review by richardliaw — APPROVED** [review]

**Review by edoakes — APPROVED** [review]
LGTM. I think the `[0]: 1` representation isn't very obvious to users but I can't think of anything better off the top of my head. We should continue to iterate on this but this is a big improvement over what we currently have!

**Pull request merged**
