### PR TITLE
Unpin setproctitle, fixes #37727

### LINKED ISSUE #37727: Make setproctitle pin consistent; loosen it?
Currently setproctitle is [pinned](https://github.com/ray-project/ray/blob/ray-2.6.1/python/setup.py#L549) to _exactly_ 1.2.2 in setup.py, however in other places it's already set to 1.3.2. Can you please at least clarify the dependency (and ideally, make it looser, e.g. `>=1.2.2,<1.4`).

### PR DESCRIPTION
**Pull request by timkpaine**
## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mattip** [comment]
@richardliaw this is needed for ray + python 3.11 on conda-forge. Could we get some eyes on it?

**Comment by richardliaw** [comment]
could you merge master back in?

**Comment by mattip** [comment]
master was merged back in, there are still a number of failing CI jobs. Is that normal?

**Comment by mattip** [comment]
Once again this is out of date with master.

**Comment by mattip** [comment]
FWIW, the conda-forge 2.7.1 release incorporates this PR, which enables python3.11 packaging.

**Comment by mattip** [comment]
Merging with master is an ongoing process. Until this can get some review it probably is not worth the effort. FWIW, this is working well on conda-forge, where it has already been adopted. Is there a reason _not_ to do this?

**Comment by anyscalesam** [comment]
@mattip is this specific to conda-forge only and not pip?

**Comment by mattip** [comment]
The version 1.2.2 in setup.py has wheels for python<3.10. `pip install` works currently by installing from source, which requires compiling the c-extension on each install. It would be much cleaner to merge this PR and use wheels.

**Comment by mattip** [comment]
I rebased the PR off master to make this mergable.

**Comment by timkpaine** [comment]
Thanks @mattip!

**Comment by anyscalesam** [comment]
this part of the stack sort of in no mans land; doesn't map directly to any eng team.... @aslonnie @can-anyscale thoughts on merging this?

**Review by can-anyscale — APPROVED** [review]
accept to unblock, i think the change is safe;

if the code owners do not accept in the next few days I can help merge it

**Comment by timkpaine** [comment]
rebased on latest master just to make sure its still ok

**Comment by anyscalesam** [comment]
@can-anyscale please just merge it

**Comment by can-anyscale** [comment]
yes, merging, sorry for the delay

**Comment by can-anyscale** [comment]
Could be breaking this test https://github.com/orgs/anyscale/projects/76/views/1?pane=issue&itemId=64249695 and is blocking the release. I'll revert if confirmed in https://github.com/ray-project/ray/pull/45539. Thankks.

**Comment by mattip** [comment]
I don't have access to that project page. What test is failing? Why isn't it failing in the CI here?

**Comment by can-anyscale** [comment]
@mattip ah yes sorry, it is this issue https://github.com/ray-project/ray/issues/45537

it's a macos test darwin://python/ray/tests:test_job so it doesn't run on CI

**Comment by timkpaine** [comment]
I'll leave it to the (very well funded) anyscale team to ensure this eventually makes it in

**Comment by mattip** [comment]
The problem is here https://github.com/ray-project/ray/blob/c94140a3a4b8ae9c0e6f1965d6285161189f9851/python/ray/tests/test_job.py#L291

At this point `list2cmdline(commands)` is 
```
'python /var/folders/4r/67pc2qss79q97y_7jpftm8tw0000gn/T/tmpei8y07tm --flag'
```

and `job["Entrypoint"]` is
```
'"/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python \
/var/folders/4r/67pc2qss79q97y_7jpftm8tw0000gn/T/tmpei8y07tm --fla" "" LC_PAPER=en_AU.UTF-8'
```

The long name for python has something to do with me running the tests in a virtual environment, I have a fix to allow tests to run locally, but that is not the problem.
Note `--flag` is missing a `g`. This somehow has something to do with `setproctitle`: the older version does not cut off the `g`.

**Comment by mattip** [comment]
This is probable https://github.com/dvarrazzo/py-setproctitle/issues/118, which is still open.

**Pull request merged**
