### PR TITLE
Fix a few f-strings missing the `f`

### LINKED ISSUE #24143: Missing `f` prefix on f-strings
Some strings looks like they're meant to be f-strings but are missing the `f` prefix meaning variable interpolation won't happen.

https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/python/ray/data/dataset.py#L638
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/python/ray/_private/log_monitor.py#L128
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/python/ray/tune/trial.py#L397
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/python/ray/tune/ray_trial_executor.py#L487
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/python/ray/serve/api.py#L179
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/rllib/utils/pre_checks/env.py#L266
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/rllib/utils/pre_checks/env.py#L283
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/rllib/policy/sample_batch.py#L658
https://github.com/ray-project/ray/blob/30ab5458a7e4ba2351d5e1beef8c8797b5946493/rllib/evaluation/sampler.py#L748

I found this issue automatically. I'm a bot. Beep Boop 🦊. See other issues I found in your repo [here](https://codereview.doctor/ray-project/ray)

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Thanks [code-review-doctor](https://github.com/code-review-doctor)!

Closes https://github.com/ray-project/ray/issues/24143

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]
Could we add to our lint check?

**Review by ericl — APPROVED** [review]

**Review by krfricke — APPROVED** [review]
Thanks!

**Comment by edoakes** [comment]
Still missing codeowner approval... maybe @sven1977?

**Review by sven1977 — APPROVED** [review]
LGTM :) Thanks for the fixes.

**Pull request merged**
