### PR TITLE
[RLlib] Fix cov matrix bug bandits

### PR DESCRIPTION
**Pull request by kouroshHakha**
## Why are these changes needed?
To fix the revert. #29846

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kouroshHakha** [comment]
let's see if this one fixes the issue. @gjoliver

**Comment by kouroshHakha** [comment]
@gjoliver The CI machines are extremely slow. The test_bandit takes 3 min on my laptop to run, on CI it takes 700 seconds.

**Comment by gjoliver** [comment]
> @gjoliver The CI machines are extremely slow. The test_bandit takes 3 min on my laptop to run, on CI it takes 700 seconds.

did we mark it exclusive?? I found that for almost all tests the require a ray cluster, we should mark them exclusive.

**Comment by kouroshHakha** [comment]
> > @gjoliver The CI machines are extremely slow. The test_bandit takes 3 min on my laptop to run, on CI it takes 700 seconds.
> 
> did we mark it exclusive?? I found that for almost all tests the require a ray cluster, we should mark them exclusive.

This should not need a cluster. It's just extremely slow for some unknown reason.

**Review by gjoliver — APPROVED** [review]

**Comment by gjoliver** [comment]
test failures are known.

**Pull request merged**
