### PR TITLE
[CI][nightly test] Fix infra error

### PR DESCRIPTION
**Pull request by scv119**
we have few infra failures (https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_pPGPzPaxUSLR3du5fmuBXpkn,   https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_NZJRifHzB61Xt1Ydty2tKwQA, https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_6eH4GjWt6ANgFXKZU5bAMPjn
) 
suggests r5dn.16xlarge  is not supported in Availability Zone us-west-2d. 
we explicitly choose us-west-2a, us-west-2b, us-west-2c instead.

### CODE REVIEW

**Comment by scv119** [comment]
it could be a transient failure as some of our tests are actually not specifying region.

**Review by rkooo567 — APPROVED** [review]
When saying not supported, does that mean we have 0 provision, or is it temporary?

**Comment by scv119** [comment]
```
Cluster startup Failed. Error: botocore.exceptions.ClientError: An error occurred (Unsupported) when calling the RunInstances operation: Your requested instance type (r5dn.16xlarge) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.
```

the error message itself could be misleading.

**Comment by scv119** [comment]
> chenshen@Chens-MacBook-Pro-16-inch-2019:~/Documents/source/ray(fix-infra-error)$ aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=r5dn.16xlarge --region us-west-2 --output table
> --------------------------------------------------------
> |             DescribeInstanceTypeOfferings            |
> +------------------------------------------------------+
> ||                InstanceTypeOfferings               ||
> |+---------------+--------------+---------------------+|
> || InstanceType  |  Location    |    LocationType     ||
> |+---------------+--------------+---------------------+|
> ||  r5dn.16xlarge|  us-west-2b  |  availability-zone  ||
> ||  r5dn.16xlarge|  us-west-2a  |  availability-zone  ||
> ||  r5dn.16xlarge|  us-west-2c  |  availability-zone  ||
> |+---------------+--------------+---------------------+|

**Comment by scv119** [comment]
It's clear AWS has some outages that we don't have r5dn.16xlarge in us-west-2a as well. we should revisit it if it doesn't resolve.

**Pull request closed without merging**
