### PR TITLE
Fix Pydantic 1 version check

### LINKED ISSUE #42413: Pydantic 1.8.1 is resolved to Pydantic 2 in pydantic_compat
### What happened + What you expected to happen

If Pydantic version is forced to be prior 1.9.0, the version check resolves it to Pydantic 2.0 due to missing __version__ attribute in Pydantic.

See: https://github.com/ray-project/ray/pull/38418

### Versions / Dependencies

Ray > 2.8.0, Pydantic 1.8.1 or older.

### Reproduction script

Install pydantic==1.8.1 and Ray.  Run `ray` command and pydantic_compat.py throws exception:

```
  File "/usr/src/app/.venv/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/scripts/scripts.py", line 2466, in <module>
    from ray.util.state.state_cli import (
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/util/state/__init__.py", line 1, in <module>
    from ray.util.state.api import (
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/util/state/api.py", line 17, in <module>
    from ray.util.state.common import (
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/util/state/common.py", line 25, in <module>
    from ray.dashboard.modules.job.pydantic_models import JobDetails
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
    from ray._private.pydantic_compat import BaseModel, Field, PYDANTIC_INSTALLED
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/_private/pydantic_compat.py", line 100, in <module>
    monkeypatch_pydantic_2_for_cloudpickle()
  File "/usr/src/app/.venv/lib/python3.9/site-packages/ray/_private/pydantic_compat.py", line 58, in monkeypatch_pydantic_2_for_cloudpickle
    pydantic._internal._model_construction.SchemaSerializer = (
AttributeError: module 'pydantic' has no attribute '_internal
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by jrosti**
## Why are these changes needed?

Pydantic versions prior to 1.9.0 are interpreted as Pydantic 2 due to missing version attribute in pydantic. It triggers an exception in any ray command:

```
AttributeError: module 'pydantic' has no attribute '_internal'
```

## Related issue number

[Closes #42413" -->](https://github.com/ray-project/ray/issues/42413)

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Thanks for the fix.

A few CI tests failed but it looks likely unrelated. Let me try running them again.

**Comment by jrosti** [comment]
> Thanks for the fix.
> 
> A few CI tests failed but it looks likely unrelated. Let me try running them again.

Yes, likely those are unrelated, but tests are however somehow connected to Pydantic. Let me know if I can help in testing.

**Comment by edoakes** [comment]
I re-ran a few times and it appears the test failures seem to be caused by this change. It appears to be related to the code in the Ray dashboard that handles when pydantic is/isn't installed in the environment: https://buildkite.com/ray-project/premerge/builds/16713#018d18ce-bb5e-4ce7-8e2f-2f7f09ab25f8/197-1121

**Comment by jrosti** [comment]
> I re-ran a few times and it appears the test failures seem to be caused by this change. It appears to be related to the code in the Ray dashboard that handles when pydantic is/isn't installed in the environment: https://buildkite.com/ray-project/premerge/builds/16713#018d18ce-bb5e-4ce7-8e2f-2f7f09ab25f8/197-1121

Thanks. I need to set up local compilation environment to see why it fails. I'll come back with my findings.

**Comment by edoakes** [comment]
@jrosti we want to get this fix into a patch release so I did some local testing to try to fix the test. It ended up being a bit of a rabbit hole. Opened a new PR with my changes to get the test to pass: https://github.com/ray-project/ray/pull/42704

Not 100% sure if it works yet, will let CI run.

**Comment by edoakes** [comment]
Other PR is merged, closing this one. Thanks a lot for the fix & making my life easy @jrosti :) sorry the tests were pretty confusing here...

**Pull request closed without merging**
