### PR TITLE
Revert "Revert "Revert "[Datasets] [Tensor Story - 1/2] Automatically provide tensor views to UDFs and infer tensor blocks for pure-tensor datasets."""

### PR DESCRIPTION
**Pull request by mwtian**
Reverts ray-project/ray#25031

It looks to be still somewhat flaky:
image

### CODE REVIEW

**Comment by mwtian** [comment]
Gentle ping @scv119

**Review by scv119 — APPROVED** [review]

**Comment by jianoaix** [comment]
The original PR was cherrypicked into 1.13 release. Does this revert means it should be reverted from 1.13?

**Comment by jianoaix** [comment]
@zhe-thoughts @clarkzinzow

**Comment by zhe-thoughts** [comment]
We decided to cherry-pick because this is new functionality and has low risk of breaking existing things. @ericl could you chime in here? Thanks

**Comment by zhe-thoughts** [comment]
@ericl and myself are looking at the test that became flaky because of the commit. Will confirm soon about whether to block 1.13.0 release on this

**Comment by zhe-thoughts** [comment]
@mwtian : the image is not very clear. Which test became flaky?

And thanks for the catch

**Comment by ericl** [comment]
```
=================================== FAILURES ===================================
_______________________ test_memory_release_lazy_shuffle _______________________
 
shutdown_only = None
 
    def test_memory_release_lazy_shuffle(shutdown_only):
        # TODO(ekl) why is this flaky? Due to eviction delay?
```

Seems it was this test. Given that this test was already flaky due to unknown Python gc reasons (per the comment), I don't think this will be a problem in practice.

**Comment by clarkzinzow** [comment]
Agreed with @ericl on this, although I think that we should follow up on improving the garbage collection story here and then capturing that desired state in non-flaky tests.

**Pull request merged**
