### PR TITLE
[all_tests] fix `test_dashboard_module_no_warnings` to only run in RAY_DEFAULT

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Should help with #29298 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rickyyx — APPROVED** [review]
Any thoughts on the root cause for the failures? 

<div><br/>via <a href="https://giphy.com/gifs/shaun-the-sheep-movie-not-my-gif-2016-oscar-nominations-tIeCLkB8geYtW">GIPHY</a></div>

**Comment by alanwguo** [comment]
The test is to check if optional imports causes any issues. These optional imports are supposed to cause issues in minimal install because those packages aren't installed in minimal install.

**Comment by rickyyx** [comment]
> The test is to check if optional imports causes any issues. These optional imports are supposed to cause issues in minimal install because those packages aren't installed in minimal install.

I see - so by right it should also work in non-default installs then?

**Comment by alanwguo** [comment]
> > The test is to check if optional imports causes any issues. These optional imports are supposed to cause issues in minimal install because those packages aren't installed in minimal install.
> 
> I see - so by right it should also work in non-default installs then?

yeah. I think it works for everything except minimal installs. Will update the logic

**Comment by rkooo567** [comment]
It makse sense, but how did it pass tests before? Seems like the test was added 10 days ago

**Comment by rickyyx** [comment]
Could we merge this if tests are okay? Unfortunately - I am not sure how to trigger the python 3.10 minimal test on this...

**Comment by alanwguo** [comment]
@rkooo567 @scv119 @rickyyx can one of you guys merge this? I think this is good to go.

**Comment by rickyyx** [comment]
There is discussion going on here: https://anyscaleteam.slack.com/archives/C011RJWAV08/p1665532419205369, which sounds like root cause for me.

**Comment by rkooo567** [comment]
@alanwguo I am actually hesitant to just merge it. It seems like this test passes in 3.9. Maybe we should at least understand the root cause? My concern is the root cause of this can affect other parts that we didn't expect

**Comment by rkooo567** [comment]
and also this test didn't run minimal python 3.10 test. Can we trigger that?

**Comment by rickyyx** [comment]
> and also this PR didn't run minimal python 3.10 test. Can we trigger that?

I thought adding `all_tests` will trigger it - but apparently I am not doing things correctly. cc @krfricke

**Pull request closed without merging**
