### PR TITLE
[CI] Use GCC 9 in GPU docker

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
GCC 9 has more complete support for C++ 17, e.g. `<filesystem>` header.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
cc @qicosmos

**Comment by scv119** [comment]
cc @simon-mo

**Review by scv119 — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]
Did we already apply the same change to the non gpu? Looks great!

**Comment by mwtian** [comment]
For non-GPU non-wheels build, I believe CI uses the default gcc compiler in Ubuntu 20.04, which is also version GCC 9. I can make that explicit in another PR.
For wheels build, I'm not sure which compiler is being used ... The image to build manylinux wheels should contain GCC 7.4 but Ray is likely using a newer version.

**Comment by simon-mo** [comment]
Make sense!

**Pull request merged**
