### PR TITLE
[xgb] re-enable xgboost_ray tests

### PR DESCRIPTION
**Pull request by amogkam**
With the pip release, we can re-enable xgboost_ray tests again.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — CHANGES_REQUESTED** [review]
Nice! Can we pin `xgboost_ray` to 0.0.2 in `requirements_upstream.txt`?

**Comment by amogkam** [comment]
Oh I didn't realize we made a new release -- just updated to 0.0.2!

**Review by krfricke — APPROVED** [review]
Thanks!

**Comment by amogkam** [comment]
@krfricke can you merge this please

**Pull request merged**
