### PR TITLE
[Windows] Fix py-spy command for dashboard

### LINKED ISSUE #33193: [Dashboard] Stack trace for worker process in ray dashboard don't work on Windows
### What happened + What you expected to happen

Tested stack trace with @pcmoritz on a Windows PC. It doesn't work but @pcmoritz has a fix for that. We should also make sure it works on WSL.

cc: @rkooo567 

IMG_2462

### Versions / Dependencies

Ray 2.3

### Reproduction script

windows env

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

Fixes https://github.com/ray-project/ray/issues/33193

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@rkooo567 Can you check if the sudo code path is still working on linux? :)

**Review by rkooo567 — APPROVED** [review]
will merge after verifying if it still works

**Comment by pcmoritz** [comment]
@rkooo567 Let me merge this first (I'm checking with @zhe-thoughts) to make sure this lands in 2.4 and I'll update the CI as a follow up (that can happen after the release branch is cut and when master is unfrozen again).

**Review by zhe-thoughts — APPROVED** [review]
Approved for merging into master (looks low risk)

**Comment by rkooo567** [comment]
sgtm. I can make a follow up PR actually.

**Pull request merged**
