### PR TITLE
[core] ray.init defaults to an existing Ray instance if there is one

### LINKED ISSUE #26329: [core] Improve usability for `ray.init` when there is an existing cluster
### Description

Two usability issues that I noticed:

1. `ray.init()` will always try to start a new standalone instance and will not warn you if there is an existing Ray instance on the same node. I think this is counter-intuitive to most newcomers and is a gotcha if you're trying to scale up from local development to a cluster.
2. When `ray.init()` is called implicitly (e.g., on the first `f.remote()` call), it will also default to the above behavior.

We can fix both by changing the default to `address="auto"`.

### Use case

_No response_

### PR DESCRIPTION
**Pull request by stephanie-wang**
Signed-off-by: Stephanie Wang <swang@cs.berkeley.edu>

## Why are these changes needed?

ray.init() will currently start a new Ray instance even if one is already existing, which is very confusing if you are a new user trying to go from local development to a cluster. This PR changes it so that, when no address is specified, we first try to find an existing Ray cluster that was created through `ray start`. If none is found, we will start a new one.

This makes two changes to the ray.init() resolution order:
1. When `ray start` is called, the started cluster address was already written to a file called `/tmp/ray/ray_current_cluster`. For ray.init() and ray.init(address="auto"), we will first check this local file for an existing cluster address. The file is deleted on `ray stop`. If the file is empty, autodetect any running cluster (legacy behavior) if address="auto", or we will start a new local Ray instance if address=None.
2. When ray.init(address="local") is called, we will create a new local Ray instance, even if one is already existing. This behavior seems to be necessary mainly for `ray.client` use cases.

This also surfaces the logs about which Ray instance we are connecting to. Previously these were hidden because we didn't set up the log until after connecting to Ray. So now Ray will log one of the following messages during ray.init:
```
(Connecting to existing Ray cluster at address: <IP>...)
...connection...
(Started a local Ray cluster.| Connected to Ray Cluster.)( View the dashboard at <URL>)
```

Note that this changes the dashboard URL to be printed with `ray.init()` instead of when the dashboard is first started.

## Related issue number

Closes #26329.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
IMO, it's a bit sketchy to run the existing autodetect logic by default, since it's effectively grepping ps aux output. The two issues I see are:
1. It's possible for there to be a false positive.
2. If a cluster died, then it wouldn't autodetect it correctly (false negative).

How about the following instead?
- `ray start` writes the created $RAY_ADDRESS to `/tmp/ray/default_ray_address`
- we check `/tmp/ray/default_ray_address` if $RAY_ADDRESS isn't defined
- `ray stop` deletes $RAY_ADDRESS

**Comment by stephanie-wang** [comment]
> IMO, it's a bit sketchy to run the existing autodetect logic by default, since it's effectively grepping ps aux output. The two issues I see are:
> 
>     1. It's possible for there to be a false positive.
> 
>     2. If a cluster died, then it wouldn't autodetect it correctly (false negative).
> 
> 
> How about the following instead?
> 
>     * `ray start` writes the created $RAY_ADDRESS to `/tmp/ray/default_ray_address`
> 
>     * we check `/tmp/ray/default_ray_address` if $RAY_ADDRESS isn't defined
> 
>     * `ray stop` deletes $RAY_ADDRESS

If there are these issues, then shouldn't we just fix autodetect to use the default_ray_address? It doesn't seem great to have all these different ways of finding which Ray address to connect to.

Also, this seems like it will work to fix (2) since we can throw an error if RAY_ADDRESS is unreachable. But it could also cause problems if Ray crashes (so no one calls `ray stop`), and then we later want to call ray.init() to start a new local instance. The alternative is to just log a louder warning if there is no instance found, which isn't much different from the current implementation.

**Comment by stephanie-wang** [comment]
Hmm okay, that sounds good. So let me update this PR to also update the autodetect implementation.

**Review by ericl — COMMENTED** [review]
Just tried this out again. I think this will be a big improvement. A couple more usability suggestions on the log messages:

1. When starting a new cluster, we now print two lines instead of one, but the second address is not really useful for local clusters. How about we combine them?
``` 
>>> ray.init()
View the Ray dashboard at http://127.0.0.1:8265
Started a new local Ray instance at address: 192.168.5.130:61720
```

For example:
`Started a new Ray cluster with dashboard at: http://127.0.0.1:8265`

2. Should we have a period or "..." at the end of the connecting message? Like

`Connecting to existing Ray cluster at address: 192.168.5.130:6379.`, or
`Connecting to existing Ray cluster at address: 192.168.5.130:6379...`.

The current log message seems a little abrupt.

**Comment by ericl** [comment]
Btw, do we need to update any docs?

**Comment by stephanie-wang** [comment]
> Just tried this out again. I think this will be a big improvement. A couple more usability suggestions on the log messages:
> 
>     1. When starting a new cluster, we now print two lines instead of one, but the second address is not really useful for local clusters. How about we combine them?
> 
> 
> ```
> >>> ray.init()
> View the Ray dashboard at http://127.0.0.1:8265
> Started a new local Ray instance at address: 192.168.5.130:61720

Ah I see, I actually don't get the first message because I don't have the dashboard built. But yeah, I'll remove the new log message.

> ```
> 
> For example: `Started a new Ray cluster with dashboard at: http://127.0.0.1:8265`
> 
>     2. Should we have a period or "..." at the end of the connecting message? Like
> 
> 
> `Connecting to existing Ray cluster at address: 192.168.5.130:6379.`, or `Connecting to existing Ray cluster at address: 192.168.5.130:6379...`.
> 
> The current log message seems a little abrupt.

Good idea!

> Btw, do we need to update any docs?

Hmm let me check.

**Comment by stephanie-wang** [comment]
The new behavior is documented in the ray.init() python docstring / API reference.

Otherwise, I actually removed most of the docs around ray.init() since users hopefully shouldn't ever have to change it now.

**Comment by ericl** [comment]
I like the new message. One thing that would be nice to fix is the case of connecting to an existing cluster. Is it possible to print that we're connecting to an existing cluster before trying to connect? Otherwise you get this if the raylet is dead, with no hint that the issue is from an existing cluster.

```
>>> ray.init()
[2022-07-20 12:12:19,252 W 153982 153982] global_state_accessor.cc:390: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
[2022-07-20 12:12:20,254 W 153982 153982] global_state_accessor.cc:390: Some processes that the driver needs to connect to have not registered with GCS, so retrying. Have you run 'ray start' on this node?
```

**Review by ericl — APPROVED** [review]
LGTM! Should we also hide the GCS address in the local cluster case? I feel like that's not really needed and may confuse new users.

**Comment by DmitriGekhtman** [comment]
This is great.

- It would probably be good to document the API change loudly somewhere if we haven't already. I might have heard we're planning a Ray 2.0.0 guide?

- I think some implementation details were decided in the comment thread. Could you mind update the PR description with those details?

**Comment by ericl** [comment]
Btw, if I run `ray status` I get `AttributeError: 'NoneType' object has no attribute 'encode'`. Could be related to failing tests.

**Comment by architkulkarni** [comment]
You asked about Ray Client -- I'm not an expert, off the top of my head I know the Ray client server calls `ray.init()` internally: https://github.com/ray-project/ray/blob/1949f359014b8be69709110772a54fc2f0c1cab8/python/ray/util/client/server/server.py 

But it should be fine.  In this PR, the only scenario where the behavior is different is when there's a Ray cluster currently running and `ray.init()` is called without an address.  But I think the Ray Client server must always be calling `ray.init()` with an explicit address.  (When using Ray Client, the assumption is that a cluster is already running; Ray Client never starts a remote Ray cluster, so I don't see why the client server would ever call `ray.init()` without an address.)

@ckw017 I believe you know more about Ray Client, let me know if anything sounds off or if you see any potential issues.

**Comment by ckw017** [comment]
> > 2. I think there might be some issues in ray client, but I don't really understand how it works well enough to fix them. Possibly we need to update some of the tests. @architkulkarni ?
> 
> I'm not an expert, off the top of my head I know the Ray client server calls `ray.init()` internally: https://github.com/ray-project/ray/blob/1949f359014b8be69709110772a54fc2f0c1cab8/python/ray/util/client/server/server.py
> 
> But it should be fine. In this PR, the only scenario where the behavior is different is when there's a Ray cluster currently running and `ray.init()` is called without an address. But I think the Ray Client server must always be calling `ray.init()` with an explicit address. (When using Ray Client, the assumption is that a cluster is already running; Ray Client never starts a remote Ray cluster, so I don't see why the client server would ever call `ray.init()` without an address.)
> 
> @ckw017 I believe you know more about Ray Client, let me know if anything sounds off or if you see any potential issues.

That sounds correct, the client server should init drivers with the address passed in here: https://github.com/ray-project/ray/blob/39cb1e5/python/ray/_private/node.py#L1059

**Review by fishbone — APPROVED** [review]
LGTM for the workflow part.

**Review by ericl — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Review by DmitriGekhtman — APPROVED** [review]
Thanks, this is great.

**Comment by pcmoritz** [comment]
Thanks for making this change, this is great!

@stephanie-wang @scv119  Can we make sure to mention this change in behavior in the Ray 2.0 release notes?

**Pull request merged**
