### PR TITLE
Unskipped tests in `test_actor.py`

### PR DESCRIPTION
**Pull request by czgdp1807**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
We should also try https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile with the suffix argument here before merging this :)

**Comment by pcmoritz** [comment]
Any updates on this?

**Comment by czgdp1807** [comment]
Will be doing the same as in https://github.com/ray-project/ray/pull/21484/files

Reason here - https://github.com/ray-project/ray/pull/21484#discussion_r783350617

Let me know if that's okay.

**Comment by pcmoritz** [comment]
Ok yeah, that sounds good!

**Comment by czgdp1807** [comment]
Cool. I will do it by evening today. I am first verifying https://github.com/ray-project/ray/pull/21525#issuecomment-1011959933. Then I will switch to completing this PR.

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
