### PR TITLE
[doc][api] remove deprecated api

### PR DESCRIPTION
**Pull request by can-anyscale**
Remove `set_progress_bar` (https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/progress_bar.py#L24) from doc since it is a deprecated API (https://github.com/ray-project/ray/pull/43575). It is also an internal function.

Test:
- CI

### CODE REVIEW

**Comment by bveeramani** [comment]
Just summarizing what we discussed offline -- this API is currently "soft deprecated," meaning it's labeled as `Deprecated` and raises a warning. Before we remove this from the code, let's "hard deprecate" it (make it raise an error rather than a warning).

**Comment by can-anyscale** [comment]
@angelinalg sorry i'm still confused about when we will remove the @deprecated api in the doc; there are hundreds of @deprecated api in our code, so if we go with @deprecated api also need to be in the doc that will be a lot of additions

**Comment by bveeramani** [comment]
For Data, there are 9 deprecated APIs. We can remove 5 of them. 3 of them we plan to never remove and keep deprecated for backwards-compatibility reasons. The remaining API os `set_progress_bars`, which should be hard deprecated.

Looks like most of the deprecated API in the rest of the codebase are in RLlib. I'm not sure what deprecation policy RLlib adheres to.

**Comment by bveeramani** [comment]
Here's a PR to remove all of the eligible deprecated Data APIs: https://github.com/ray-project/ray/pull/45850

**Comment by can-anyscale** [comment]
thanks @bveeramani, noted, let's close this and i'll follow up with another PR so we can specify a concrete date under the @deprecation annotation

**Pull request closed without merging**
