### PR TITLE
Bump Starlette version

### PR DESCRIPTION
**Pull request by sihanwang41**
Signed-off-by: Sihan Wang <sihanwang41@gmail.com>

## Why are these changes needed?

latest fastapi requires starlette 0.20.4 https://github.com/tiangolo/fastapi/blob/0.85.0/pyproject.toml#L41, remove the pin to let the pip decide version to use

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
will merge after unit test passing

**Comment by simon-mo** [comment]
```
================================== FAILURES ===================================
_________________________ test_fastapi_shutdown_hook __________________________

serve_instance = <ray.serve._private.client.ServeControllerClient object at 0x00000234F4BFBF40>

    def test_fastapi_shutdown_hook(serve_instance):
        # https://github.com/ray-project/ray/issues/18349
        shutdown_signal = SignalActor.remote()
        del_signal = SignalActor.remote()
    
        app = FastAPI()
    
        @app.on_event("shutdown")
        def call_signal():
            shutdown_signal.send.remote()
    
        @serve.deployment
        @serve.ingress(app)
        class A:
            def __del__(self):
                del_signal.send.remote()
    
        A.deploy()
        A.delete()
>       ray.get(shutdown_signal.wait.remote(), timeout=20)

\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_eyuo35ns\runfiles\com_github_ray_project_ray\python\ray\serve\tests\test_fastapi.py:568: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\install\ray\python\ray\_private\client_mode_hook.py:105: in wrapper
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

object_refs = [ObjectRef(7c418a8774dba87425d34a56dae76098c743e56c0100000001000000)]

    @PublicAPI
    @client_mode_hook(auto_init=True)
    def get(
        object_refs: Union[ray.ObjectRef, Sequence[ray.ObjectRef]],
        *,
        timeout: Optional[float] = None,
    ) -> Union[Any, List[Any]]:
        """Get a remote object or a list of remote objects from the object store.
    
        This method blocks until the object corresponding to the object ref is
        available in the local object store. If this object is not in the local
        object store, it will be shipped from an object store that has it (once the
        object has been created). If object_refs is a list, then the objects
        corresponding to each object in the list will be returned.
    
        Ordering for an input list of object refs is preserved for each object
        returned. That is, if an object ref to A precedes an object ref to B in the
        input list, then A will precede B in the returned list.
    
        This method will issue a warning if it's running inside async context,
        you can use ``await object_ref`` instead of ``ray.get(object_ref)``. For
        a list of object refs, you can use ``await asyncio.gather(*object_refs)``.
    
        Args:
            object_refs: Object ref of the object to get or a list of object refs
                to get.
            timeout (Optional[float]): The maximum amount of time in seconds to
                wait before returning.
    
        Returns:
            A Python object or a list of Python objects.
    
        Raises:
            GetTimeoutError: A GetTimeoutError is raised if a timeout is set and
                the get takes longer than timeout to return.
            Exception: An exception is raised if the task that created the object
                or that created one of the objects raised an exception.
        """
        worker = global_worker
        worker.check_connected()
    
        if hasattr(worker, "core_worker") and worker.core_worker.current_actor_is_asyncio():
            global blocking_get_inside_async_warned
            if not blocking_get_inside_async_warned:
                logger.warning(
                    "Using blocking ray.get inside async actor. "
                    "This blocks the event loop. Please use `await` "
                    "on object ref with asyncio.gather if you want to "
                    "yield execution to the event loop instead."
                )
                blocking_get_inside_async_warned = True
    
        with profiling.profile("ray.get"):
            is_individual_id = isinstance(object_refs, ray.ObjectRef)
            if is_individual_id:
                object_refs = [object_refs]
    
            if not isinstance(object_refs, list):
                raise ValueError(
                    "'object_refs' must either be an ObjectRef or a list of ObjectRefs."
                )
    
            # TODO(ujvl): Consider how to allow user to retrieve the ready objects.
            values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
            for i, value in enumerate(values):
                if isinstance(value, RayError):
                    if isinstance(value, ray.exceptions.ObjectLostError):
                        worker.core_worker.dump_object_store_memory_usage()
                    if isinstance(value, RayTaskError):
                        raise value.as_instanceof_cause()
                    else:
>                       raise value
E                       ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
E                       	class_name: SignalActor
E                       	actor_id: 25d34a56dae76098c743e56c01000000
E                       	pid: 7332
E                       	namespace: default_test_namespace
E                       	ip: 127.0.0.1
E                       The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 10054. An existing connection was forcibly closed by the remote host. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

c:\install\ray\python\ray\_private\worker.py:2289: RayActorError
============================== warnings summary ===============================
..\..\..\..\..\..\..\..\Miniconda3\lib\site-packages\_pytest\config\__init__.py:1126
  C:\Miniconda3\lib\site-packages\_pytest\config\__init__.py:1126: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: anyio
    self._mark_plugins_for_rewrite(hook)

::test_class_based_view
::test_fastapi_init_lifespan_should_not_shutdown
  c:\install\ray\python\ray\serve\_private\router.py:89: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self.config_updated_event = asyncio.Event(loop=event_loop)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED ::test_fastapi_shutdown_hook - ray.exceptions.RayActorError: The actor...
============ 1 failed, 18 passed, 3 warnings in 215.07s (0:03:35) =============
```


Windows failed. can we skip this test on windows for now

**Review by simon-mo — COMMENTED** [review]
skip fastapi test on windows

**Comment by c21** [comment]
Can it be merged? What's the remaing work here?

**Pull request merged**
