### PR TITLE
[remove/hide StringIdMap 1/n] use std::string instead of int64_t for node ids

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

This is the first PR that tries to deprecate `StringIdMap` from scheduling logic. In this PR specifically, we remove node_id from the StringIdMap, instead we just use string directly,

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Could you run nightly tests to make sure perf is ok?

**Comment by scv119** [comment]
well the placement group tests timed out due to scheduling slow down :(

**Comment by jjyao** [comment]
Which placement group test? Seems we proves that it's not a premature optimization? Maybe add a comment saying why this optimization is needed.

**Comment by scv119** [comment]
Looks the root cause is that our scheduling policy did a lot of manipulation of the node_ids, i.e. copying, sorting, etc. This slows down a lot when we migrate from int64_t to 28 bytes of strings for node_id.

**Comment by rkooo567** [comment]
So it does mean we need this optimization? Maybe we should go to the direction to hide the conversion?

**Pull request closed without merging**
