### PR TITLE
Revert "[RLlib] Enable Bandits to work in batches mode(s) (vector envs + multiple workers + train_batch_sizes > 1)."

### PR DESCRIPTION
**Pull request by fishbone**
Reverts ray-project/ray#22465
It breaks test_output.

### CODE REVIEW

**Comment by iycheng** [comment]
It seems to break test_output. I'll let the CI run to verify this.

**Comment by gjoliver** [comment]
> It seems to break test_output. I'll let the CI run to verify this.

you may want to kick the test again. it failed with some weird http error.
I also looked at the error, it's unlikely this PR would cause that. the format of the error message seemed to change.

**Comment by iycheng** [comment]
@gjoliver I also feel it in this way. That's why I'm waiting for the CI to show the results before merging blindly.

**Comment by iycheng** [comment]
it also failed. close this pr

**Pull request closed without merging**
