### PR TITLE
[CherryPick][Serve] Recover PENDING_INITIALIZATION status actor (#33890)

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

cherrypick: #33890

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sihanwang41** [comment]
^^ @zhe-thoughts @clarng

**Comment by clarng** [comment]
Can we add some notes for why this needs cherry pick?

**Comment by sihanwang41** [comment]
This is the fix we observe from release tests.  https://github.com/ray-project/ray/issues/33868#issuecomment-1492253408
it is to fix ray serve recovering for pending actors.  the release tests issue should be closed after two pr landed, yet it is closed with the first pr landed...

**Review by zhe-thoughts — APPROVED** [review]

**Comment by clarng** [comment]
> This is the fix we observe from release tests. [#33868 (comment)](https://github.com/ray-project/ray/issues/33868#issuecomment-1492253408) it is to fix ray serve recovering for pending actors. the release tests issue should be closed after two pr landed, yet it is closed with the first pr landed...

Got it , can we kick off the release test that this fixes to verify it is working in the branch?

**Comment by sihanwang41** [comment]
@clarng https://buildkite.com/ray-project/release-tests-pr/builds/34556#0187714e-fc2c-4133-a051-bba8b7e93a03 succeed

**Pull request merged**
