### PR TITLE
[Doc] Update main docs page

### LINKED ISSUE #42068: [Docs] Update the homepage
### Description

Update the homepage of ray docs as per the new design - 
Light mode - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=129%3A1083&mode=design&t=pNlPOuLgqsCOAl2z-1
Dark mode - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=19%3A466&mode=design&t=pNlPOuLgqsCOAl2z-1

(Let's set a max width of the whole container so that it doesn't look odd on really big screen sizes)

cc: @angelinalg 

### Link

_No response_

### LINKED ISSUE #44227: [Doc] [Polish] Front page video box looks awkwardly stretched
### Description

Full screen, the front page video looks weirdly long horizontally. When it plays, there's big black boxes on the side.
Screenshot 2024-03-21 at 2 00 45 PM
Screenshot 2024-03-21 at 2 01 24 PM

Full screen, Chrome, Macbook Pro M1

### Link

https://docs.ray.io/

### LINKED ISSUE #44228: [Doc] [Polish] Front page icons appear blurry and off-center
### Description

Examples:
Screenshot 2024-03-21 at 2 08 54 PM
Screenshot 2024-03-21 at 2 07 56 PM
The blurriness is slight, but apparent on a high DPI display.

### Link

http://docs.ray.io

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR updates the homepage to match new designs.

## Related issue number

- Closes #42068 
- Closes #44228
- Closes #44227

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simran-2797** [comment]
Looks much better! Thanks! 
A few small nits: 
 
Screenshot 2024-03-27 at 7 41 46 AM
1. In this section, can we increase the spacing between "An open source framework....." and the 3 cards "get started, install and example gallery" and make it 2 rem? 
2. Can we increase the font-weight of "an open source framework..." to 400?


Screenshot 2024-03-27 at 7 48 50 AM
1. These titles, Ray libraries, ray core should be centered wrt to their icons. Currently they are aligned at the top. 
2. The spacing between the content and learn more should remain the same: 1rem. 

Looks good otherwise. Thanks a lot!!!

**Comment by simran-2797** [comment]
I have another request. Just to add a little bit more brightness on the page, can we do this? - 
Screenshot 2024-03-27 at 7 53 23 AM

The change here is adding the colored boxes behind the icons in the 3 cards - getting started, install and example gallery. 
We will keep the icons same as they are today, just add the bg. This is a nice to have, not a super urgent requirement. 
cc: @angelinalg

**Comment by angelinalg** [comment]
Really nice improvements! Some nits:

1. The links to the `Learn more about xx` and `Examples` links seem to all be broken. Could we run link check or test out all links on the page?
2. Should we capitalize `Ray Example Gallery` in the top rightmost button? Not sure. It's capitalized in the side nav and top nav.
3. The divider line between `Learn more about xx` and `Examples` doesn't show up clearly in dark mode.
5. CSAT widget in dark mode, I can't see what I'm typing in the feedback box. The input text needs more contrast.
4. Last section, `Getting involved`, please lower case `support` in `Get support`, to be consistent.
5. CSAT widget in dark mode, I can't see what I'm typing in the feedback box. The input text needs more contrast.
6. `Ask questions on the forum` vs `to the forum`.
7. Capitalize `Python` in top sentence.
8. The top sentence doesn't make sense with the title `Welcome to Ray docs`. Shall we just keep it `Welcome to Ray`?
9. Since we're sentence casing all of our titles, let's do the same for the workloads: Batch inference, Hyperparameter tuning, Model training, Model serving, Reinforcement learning.

**Comment by angelinalg** [comment]
I just realized that I can make suggestions for the copy editing comments I made.

**Review by angelinalg — APPROVED** [review]

**Pull request merged**
