### PR TITLE
Added dtype safeguards to the 'required_model_output_shape()' methods…

### PR DESCRIPTION
**Pull request by simonsays1980**
… that cast from np.float32 to np.int32.

## Why are these changes needed?

Running RLlib's algorithms with an action space that contains float values results in a `TypeError` later on in the `forward()` method of the `RecurrentNetwork`. 

I also opt for using generally `np.prod` instead of `np.product` as the latter gets [deprecated](https://github.com/numpy/numpy/pull/10653). 

## Related issue number

#23489 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simonsays1980** [comment]
@gjoliver This might probably also be an issue in case of using `framework=torch`.

**Comment by simonsays1980** [comment]
@gjoliver Can you approve this?

**Review by gjoliver — APPROVED** [review]

**Comment by gjoliver** [comment]
please help with the torch side as well. thanks man.
I will ping @sven1977 to merge this.

**Comment by sven1977** [comment]
Hey @simonsays1980 , thanks for this PR. I have one question, though. What if the action shape is quite large, e.g. (4, 128), such that the product (512) would exceed the int8 limits? Wouldn't that lead to an int overflow and result in the wrong values being returned?
```
import numpy as np
np.prod([2, 256], dtype=np.int8)
>>> 0
```

**Comment by simonsays1980** [comment]
> Hey @simonsays1980 , thanks for this PR. I have one question, though. What if the action shape is quite large, e.g. (4, 128), such that the product (512) would exceed the int8 limits? Wouldn't that lead to an int overflow and result in the wrong values being returned?
> 
> ```
> import numpy as np
> np.prod([2, 256], dtype=np.int8)
> >>> 0
> ```

Well, good point @sven1977 :D I think to be on the save side `int32` then would be a good foundation. I could still imagine dimensions of around `32,000` so `int16` might be dangerous as well. 

I change the PR and will also add similar changes for the `torch` action distributions (@gjoliver ).

**Comment by simonsays1980** [comment]
> Hey @simonsays1980 , thanks for this PR. I have one question, though. What if the action shape is quite large, e.g. (4, 128), such that the product (512) would exceed the int8 limits? Wouldn't that lead to an int overflow and result in the wrong values being returned?
> 
> ```
> import numpy as np
> np.prod([2, 256], dtype=np.int8)
> >>> 0
> ```

Fixed in the new PR together with torch.

**Comment by simonsays1980** [comment]
> Awesome, thanks for the quick fix. Will merge right after tests pass ...

I will notify the user on the discussion board

**Comment by simonsays1980** [comment]
We can now close the issue

**Pull request merged**
