### PR TITLE
Added tensorlib 'numpy' to 'restore_original_dimensions()' such that …

### PR DESCRIPTION
**Pull request by simonsays1980**
## Why are these changes needed?

Trying to work on the `obs_batch` in `compute_actions()` can be cumbersome, if the observation space is complex. In the latter case the original structure helps to access the elements less error-proned. 
If one uses only `numpy` arrays one wants also to work on with `numpy` arrays, however `restore_original_dimensions()` accepts only `torch` or `tensorflow` as frameworks and then returns corresponding tensors. This PR should give the user more flexibility when restoring the original dimensions of the `obs_batch` by also using `numpy` arrays. 

In addition, when trying to convert the tensor output from `restore_original_dimensions()` with `framework="tf"`, I encountered a large performance loss because a TensorFlow session had to be used each time when calling `eval()`. 

## Related issue number

[issue #7896](https://github.com/ray-project/ray/issues/7896)

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@sven1977 Do you want to have a look?

**Review by sven1977 — APPROVED** [review]
Looks great! Thanks @simonsays1980 , let's merge :)

**Comment by sven1977** [comment]
Waiting for tests to pass after updating from master ...

**Comment by simonsays1980** [comment]
@sven1977 Thanks for merging this - helps to me to get rid of some extra code in my project :)

**Pull request merged**
