### PR TITLE
[wingman -> rllib] Removed remote evaluators assert

### PR DESCRIPTION
**Pull request by bjg2**
Not forcing remote evaluators not to be zero in the optimizer, as it makes sense for them to be 0 during the rollout. But for some reason, logger.warning is not written in the console (I don't know how rllib logging is working).

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Sounds good!

**Comment by ericl** [comment]
Hmm warn should definitely work. Does a print() show up?

**Comment by bjg2** [comment]
> Hmm warn should definitely work. Does a print() show up?

My blunder, had a wrong condition in if. :/ Fixed now.

**Comment by ericl** [comment]
Shortened the message to satisfy the linter line Iimit

**Pull request merged**
