### PR TITLE
The function get_node_ip_address while catch an exception and return …

### PR DESCRIPTION
**Pull request by adoda**
…'127.0.0.1',

when we forbid the external network. Instead of we can get ip address from hostname.

## What do these changes do?

The function get_node_ip_address while catch an exception and return '127.0.0.1' when we forbid the external network. Instead of we can get ip address from hostname.

## Related issue number

https://github.com/ray-project/ray/issues/2721

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
Can we catch a more specific exception here?

**Comment by robertnishihara** [comment]
This gives me hostnames like

```python
>>> socket.getfqdn(socket.gethostname())
'ip-172-31-44-155.us-west-1.compute.internal'
```

Have you verified that Ray works when this code path gets hit?

If we aren't connected to the network, what's wrong with `127.0.0.1`?

**Comment by adoda** [comment]
@robertnishihara 
When call the function:
```
get_node_ip_address(address="8.8.8.8:53")  
```
will catch an exception:
```
[Errno 101] Network is unreachable"
```
We forbid the external network for security in our cluster, but the internal networks is working.

**Comment by robertnishihara** [comment]
jenkins, retest this please

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
