### PR TITLE
[serve] Add atomic delete

### LINKED ISSUE #23053: Application delete should happen concurrently
The deploy steps deploy everything at once. but delete is sequential

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

Serve users delete deployments in two ways: individually with `delete()` or all at once with `serve.shutdown()`.

This change enables users to delete a specified deployment group atomically with `delete_deployments()`. This provides fine-grained control over which deployments to delete and allows a single request to delete multiple deployments. It also modifies the Serve CLI's `run` command to issue atomic delete requests.

## Related issue number

Closes #23053.

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
     - New unit tests are added to `test_api.py`.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
api.py is turning into a bit of a grab-bag of random functions -- is it possible to move this somewhere else instead?

**Comment by shrekris-anyscale** [comment]
> api.py is turning into a bit of a grab-bag of random functions -- is it possible to move this somewhere else instead?

That's a good point, but I'm not quite sure where to move it. Since it uses `internal_get_global_client()`, `api.py` seems like a good fit. Alternatively, we could remove `delete_deployments()` and move its body into `run()` in the Serve CLI. Thoughts?

**Comment by edoakes** [comment]
Just moving it into .run() sounds find to me actually, assuming it doesn't hurt testability.

**Comment by shrekris-anyscale** [comment]
I moved the body to `run()`.

**Comment by simon-mo** [comment]
Can you update the deletion path in `conftest.py` as well

**Pull request merged**
