### PR TITLE
[docs] Remove `requirements-rtd.txt`

### PR DESCRIPTION
**Pull request by matthewdeng**
## Why are these changes needed?

I don't think this is actually needed. Removing it to clean up extra files.

## Related issue number

n/a

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by maxpumperla — APPROVED** [review]
always left it in, as I wasn't sure if there were other systems using it. but lgtm

**Comment by matthewdeng** [comment]
@maxpumperla yeah I was curious too... 

I saw in `readthedocs` builds ([example](https://readthedocs.com/projects/anyscale-ray/builds/1369954/)) we use `requirements-doc.txt`:

```bash
python -m pip install --exists-action=w --no-cache-dir -r doc/requirements-doc.txt
```

I'm assuming as long as long as [the run associated with this PR](https://readthedocs.com/projects/anyscale-ray/builds/1369876/) passes, we should probably be fine? I'd be quite surprised if there are other systems building our docs 😄

**Comment by maxpumperla** [comment]
@matthewdeng yeah, exactly. completely agree

**Comment by matthewdeng** [comment]
Failures unrelated, [build](https://readthedocs.com/projects/anyscale-ray/builds/1440396/) job succeeds.

**Comment by richardliaw** [comment]
FYI, the reason why we had this was so that we would actually be able to properly reproduce the exact same build environment locally. The rtd.txt was the base set of packages offered by readthedocs.

I've tried updating the base readthedocs to no avail a couple years ago, so instead forced the local env to be the same.

Now if that's no longer an issue, that's great to hear.

**Pull request merged**
