### PR TITLE
[ci/hotfix] Fix CI with raydp-nightly install

### PR DESCRIPTION
**Pull request by krfricke**
We install `raydp-nightly` in data processing tests. This currently requires `ray < 1.13.0` which will uninstall our candidate wheel and install ray 1.12.1, crashing CI (see https://github.com/oap-project/raydp/pull/252/files).

We should probably depend on the latest raydp release and not the nightly version cc @clarkzinzow 

This PR installs `raydp-nightly` without dependencies in the meantime.

Signed-off-by: Kai Fricke <kai@anyscale.com>

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ArturNiederfahrenhorst — APPROVED** [review]

**Review by xwjiang2010 — APPROVED** [review]
Thanks Kai!

**Review by Yard1 — APPROVED** [review]

**Review by clarkzinzow — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Comment by krfricke** [comment]
@clarkzinzow I'd actually like to not merge this PR - we can use dependabot to track the `raydp-nightly` releases. Would that be ok for you? Note that this won't resolve the issue with the current raydp-master, for that raydp would have to remove their ray constraint.

The best solution would be to update raydp-nightly so that it is compatible with Ray 1.13.0 and current master.

**Comment by clarkzinzow** [comment]
@krfricke that sounds good to me!

**Comment by krfricke** [comment]
Closing for now

**Pull request closed without merging**
