### PR TITLE
[Doc] Bump sphinx-click to avoid building protocol buffers for Ray CLI

### LINKED ISSUE #43404: [Doc] Update sphinx-click build dependency to allow mocking out of protobuf
### Description

#43189 Added `protobuf` as a dependency; without adding this dependency, the docs for the Ray CLI can't be built because that PR included an import statement in the Ray CLI that pulled in some protobuf-defined objects. Since `sphinx-click<5.1.0` didn't support mocking imports, this adding an explicit dependency was necessary.

Additionally, some space-indented lines were added for the `html` target in the docs makefile, breaking it.

To fix these issues:
- Upgrade `sphinx-click`: `sphinx-click==5.1.0` is out and _does_ support mocking out modules
- Remove the extra RTD build steps related to getting bazel and building protobuf
- Fix the makefile to make the `html` target work again

Currently, this issue is blocking building documentation locally.

### Link

_No response_

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

[A recent change](https://github.com/ray-project/ray/pull/43189) imported some objects from a protobuf-generated module into the Ray CLI. Previously we never needed to build the protobuf-generated module for doc builds, but this change necessitated doing so.

Normally we'd just mock out the generated module, but the sphinx plugin we are using to document the CLI (`sphinx-click`) didn't support mocking out modules as of `5.0.1`. However a [recent change](https://github.com/click-contrib/sphinx-click/pull/129) added support for mocking imports. With the release of `5.1.0`, we can take advantage of this to avoid the need to include external dependencies for building the CLI docs.

Happily, the recent update to `sphinx-click` reuses the `autodoc_mock_imports` configuration setting from `conf.py` to know what modules to mock out so no configuration change is needed :smiley: 

## Changes

- Avoid installing bazel and building the protocol buffers during the RTD build
- Remove `watchfiles` and `protobuf` from the list of doc build dependencies; neither is needed anymore
- Remove protobuf invocation in the `html` target of the docs Makefile. These lines were space-indented, which isn't valid `make` syntax. So removing these lines making local builds possible again.

## Related issue number

Closes https://github.com/ray-project/ray/issues/43404.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by aslonnie — COMMENTED** [review]
@jjyao any opinions on mocking?

**Review by aslonnie — COMMENTED** [review]
I feel that it is better to use and test the real thing rather than mocking.

**Comment by peytondmurray** [comment]
> I feel that it is better to use and test the real thing rather than mocking.

Testing and using the Ray CLI is a separate concern. This PR affects how documentation is built, not how code is used or tested. We do not need to be able to _run_ the CLI to build the CLI docs, and therefore we do not need the Ray CLI dependencies. We're just reading some docstrings and generating HTML from them - we really _shouldn't_ be installing all the heavy ML/AI/distributed computing dependencies needed to actually run Ray to do that.

I'm happy to talk more about this if there are still some doubts about this; for context, [we are already doing this for every other Ray dependency](https://github.com/ray-project/ray/blob/bca48a386e989726ff090d47d0b4d839b87fbc3c/doc/requirements-doc.txt#L38C1-L39C80).

**Comment by peytondmurray** [comment]
Note: build failures will be fixed when https://github.com/ray-project/ray/pull/43438 is merged.

**Review by jjyao — APPROVED** [review]
LGTM!

**Review by aslonnie — APPROVED** [review]

**Comment by jjyao** [comment]
doc build test failed.

**Comment by peytondmurray** [comment]
> doc build test failed.

Yep as mentioned, should be solved by https://github.com/ray-project/ray/pull/43438. I'll rebase onto latest master, which should fix the issue.

**Review by angelinalg — APPROVED** [review]
Thank you for keeping the docs ecosystem healthy!

**Pull request merged**
