### PR TITLE
[GCS]refactor the GCS Client Task Interface

### PR DESCRIPTION
**Pull request by micafan**
Refactoring the GCS Client Task Interface .
Only expose Ray-specific semantics (e.g., AsyncSubscribe, AsyncUpdate, etc), and hide the implementation details about the backed storage.

Create this PR because the old PR #5515  which is merged and reverted (reverted because UT failed and the wrong CHECK in code).

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by ericl** [comment]
It's a bit unfortunate we have to add interfaces for the task table, which is only used in a very minimal way at this point but is quite complex. Would it be bad to leave it out? Once we enable the new scheduler it will be completely unused.

**Comment by micafan** [comment]
> It's a bit unfortunate we have to add interfaces for the task table, which is only used in a very minimal way at this point but is quite complex. Would it be bad to leave it out? Once we enable the new scheduler it will be completely unused.

How about add the new interface to TaskInfoAccessor too by then? I think expose TaskTable is not safe,  some people might use it instead of TaskInfoAccessor.

**Comment by ericl** [comment]
It doesn't matter, as the code is deprecated and will be removed as soon as the new scheduler is ready.

How about we freeze changes to the task lineage and lease management until it is removed?

**Comment by raulchen** [comment]
Hi @ericl, we'd like to merge this PR first to unblock other work on GCS Service. 
The changes to table table and lineage cache are pretty straightforward. We simply wrap old `task_table` code with new `TaskInfoAccessor` interface. 
When we enable the new scheduler, it should be very easy to remove the task table.
Also, this PR refactors code about the new gcs client as well. 
Please let us know if you still have concerns. Thanks.

**Review by raulchen — APPROVED** [review]

**Comment by raulchen** [comment]
BTW, for the short term, I think we still need task table to store actor creation task spec.

**Comment by micafan** [comment]
@ericl Could you take a look at the auto scaling test failed issue [6582](https://github.com/ray-project/ray/issues/6582) .

**Comment by raulchen** [comment]
Test failure should be irrelevant.

**Pull request merged**
