### PR TITLE
[Core] [CI] [Flaky] Split test_client.py to keep from hitting test timeout

### PR DESCRIPTION
**Pull request by clarkzinzow**
`//python/ray/tests:test_client` has been flaky recently due to bumping against the 300s timeout; even on successful runs, the test runs in just under the 300s timeout. This PR splits `test_client.py` into two test modules, `test_client_1.py` and `test_client_2.py`.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
can we split the test to test_client_1 and test_client_2? so when a test case fail by timing out it wouldn't take so long to caught it.

**Review by mwtian — APPROVED** [review]
Simon's suggestion is good too.

**Review by simon-mo — APPROVED** [review]

**Comment by clarkzinzow** [comment]
>can we split the test to test_client_1 and test_client_2? so when a test case fail by timing out it wouldn't take so long to caught it.

Ah so split the `test_client.py` module into two modules? Yeah I can do that. I was hoping to get this PR in with just edits through the GitHub UI, but I'll stop being lazy. 😛

**Review by mwtian — APPROVED** [review]

**Comment by clarkzinzow** [comment]
I haven't been able to reproduce this `test_client_2` failure locally, very strange. Will need to dig into this some more.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by simon-mo** [comment]
@clarkzinzow still working on this? Maybe close for stale?

**Comment by clarkzinzow** [comment]
@simon-mo We can close this. This was fixed in master as a driveby on another PR by bumping the timeout to "large", which is a worse solution than splitting the test, but coming back to debug and fix PR is very low priority for me.

**Pull request closed without merging**
