### PR TITLE
[CI] hotfix mac wheels build issues.

### PR DESCRIPTION
**Pull request by scv119**
Try to fix follow issue:
_pytest.pathlib.ImportPathMismatchError: ('ray.tests.conftest', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ray/tests/conftest.py', PosixPath('/Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-0cce6cf77c1456efa-1/ray-project/oss-ci-build-branch/python/ray/tests/conftest.py'))

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
What's the root cause?

**Comment by scv119** [comment]
most likely some dependency version upgrade.

**Comment by cadedaniel** [comment]
I think the issue is actually related to the fact that we're installing dependencies for the wrong python version. But could be wrong. Cc @krfricke, do you have any insight here?

**Comment by krfricke** [comment]
https://buildkite.com/ray-project/oss-ci-build-pr/builds/4432#01844fb9-6733-430c-abf5-c3fb20c65370/129-196

```


Failed to dry run py_dep_analysis.py
--
SyntaxError: invalid syntax
```

Seems like this setting prevents some installs (maybe we are executing with python 2?)

**Comment by cadedaniel** [comment]
> Failed to dry run py_dep_analysis.py

I created https://github.com/ray-project/ray/issues/30062 to fix the silent failure

**Comment by clarng** [comment]
tweaked to reference python3 directly to see if it fixes

**Comment by clarng** [comment]
after fixing it to python3 now its complaining about bazel 
https://buildkite.com/ray-project/oss-ci-build-pr/builds/4517#0184549d-2471-4bb4-811d-9732fb6fd925

**Comment by scv119** [comment]
failed runs: https://buildkite.com/ray-project/oss-ci-build-branch/builds/961#01845396-cefa-4f3e-b83b-e5d4f8322f7d/8460-8490
+ /Library/Frameworks/Python.framework/Versions/3.6/bin/pip3.6 uninstall -y ray
WARNING: Skipping ray as it is not installed.
+ /Library/Frameworks/Python.framework/Versions/3.6/bin/pip3.6 install -q /Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-0ae04fafa8ff32cbf-1/ray-project/oss-ci-build-branch/ci/build/../../.whl/ray-3.0.0.dev0-cp36-cp36m-macosx_10_15_intel.whl
...
+ /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-0ae04fafa8ff32cbf-1/ray-project/oss-ci-build-branch/ci/build/../../python/ray/tests/test_microbenchmarks.py
ImportError while loading conftest '/Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-0ae04fafa8ff32cbf-1/ray-project/oss-ci-build-branch/python/ray/tests/conftest.py'.
_pytest.pathlib.ImportPathMismatchError: ('ray.tests.conftest', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ray/tests/conftest.py', PosixPath('/Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-0ae04fafa8ff32cbf-1/ray-project/oss-ci-build-branch/python/ray/tests/conftest.py'))
successful runs: https://buildkite.com/ray-project/oss-ci-build-branch/builds/899#01843c63-2ec3-495b-a82d-d1607113940c
+ PYTHON_WHEEL=/Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-04d45c291282fe372-1/ray-project/oss-ci-build-branch/ci/build/../../.whl/ray-3.0.0.dev0-cp36-cp36m-macosx_10_15_intel.whl
+ /Library/Frameworks/Python.framework/Versions/3.6/bin/pip3.6 uninstall -y ray
Found existing installation: ray 3.0.0.dev0
Uninstalling ray-3.0.0.dev0:
  Successfully uninstalled ray-3.0.0.dev0
+ /Library/Frameworks/Python.framework/Versions/3.6/bin/pip3.6 install -q /Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-04d45c291282fe372-1/ray-project/oss-ci-build-branch/ci/build/../../.whl/ray-3.0.0.dev0-cp36-cp36m-macosx_10_15_intel.whl
...
+ /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/ec2-user/.buildkite-agent/builds/bk-mac1-branch-queue-i-04d45c291282fe372-1/ray-project/oss-ci-build-branch/ci/build/../../python/ray/tests/test_microbenchmarks.py
============================= test session starts ==============================
```

**Comment by scv119** [comment]
so the new fix is to override the PYTHONPATH for `pip uninstall`

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
it's hotfixed by #30090

**Pull request closed without merging**
