### PR TITLE
Revert "[Core] Fix ServerCall Leaking (#17863)"

### PR DESCRIPTION
**Pull request by scv119**
This reverts commit 4f6b50dc467ff2d2c3564ea8d757d3567fcaade8. 

TSAN failure: https://buildkite.com/ray-project/ray-builders-branch/builds/3291#07352601-19f2-440e-ac5e-9a01bea1dd82

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by scv119** [comment]
@lixin-wei there could be false positive in TSAN  test, but please take a look and maybe back out the tests

**Comment by simon-mo** [comment]
@lixin-wei I think this also happened because we added TSAN tests while your PR branch was still on older commits, so TSAN didn't run. Can you make sure to re-revert and merge master for it?

**Comment by simon-mo** [comment]
I merged it to hotfix master breakage

**Comment by scv119** [comment]
Thank you @simon-mo!

**Pull request merged**
