### PR TITLE
Remove unused ci/performance_tests

### PR DESCRIPTION
**Pull request by edoakes**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by HuangLED** [comment]
oops. New to ray project,  I have been following this script to understand flows, especially how to set up a local cluster.  

Mind if I ask, if this one is deprecated, would you pls point me the next most relevant e2e script?

 Much appreciated, Edward.

**Comment by edoakes** [comment]
@HuangLED this is not actually a good example for how to set up a cluster, it's using a test utility we have to set up a "virtual" cluster that allows you to test multi-node behavior on a single machine.

On a single machine, you just need to call `ray.init()` in your script. For multi-node, see the docs:
https://docs.ray.io/en/latest/cluster/index.html

**Comment by HuangLED** [comment]
Thanks Edwards! :-) 

B/c what I was looking for is exactly "local cluster". Are you suggesting there is a difference between "local cluster" versus "virtual cluster"? 

By having one cluster on local, I assume it would be "virtual" already, and each node takes one process. 

Motivation wise, yeah, I didn't want to setup multiple machines for a cluster yet. For now just want try out something end-2-end, using multi-processes.

**Comment by edoakes** [comment]
I see! In that case, `cluster_utils` is what you want. Here is a directory with a bunch of examples that use `cluster_utils` to simulate a cluster:
https://github.com/ray-project/ray/tree/master/release/long_running_tests/workloads

**Pull request merged**
