### PR TITLE
[docs] Fix readthedocs rendering

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?
documentation doesn't seem to be built properly (see memory management page).

This introduces a build environment more similar to what's on Readthedocs by adding their requirements.txt env.

We do a hack where we override their sphinx installation - it is not clear if it'll work on their end, but theoretically it should help us render more items on the docs.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by simon-mo** [comment]
Do you have a successful build with this on another rtd project? e.g. I have a rtd project pointing to my fork https://simon-ray.readthedocs.io/en/latest/

**Comment by richardliaw** [comment]
ah good suggestion, trying it out.

**Comment by richardliaw** [comment]
yep lgtm @simon-mo https://rllib.readthedocs.io/en/latest/index.html

**Review by simon-mo — APPROVED** [review]
lgtm

**Pull request merged**
