### PR TITLE
fix cli --help

### PR DESCRIPTION
**Pull request by Ox0400**
## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by Ox0400** [comment]
```
root@gpu63:/var/work# python /usr/local/lib/python3.10/site-packages/ray/dashboard/dashboard.py --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ray/dashboard/dashboard.py", line 197, in <module>
    args = parser.parse_args()
  File "/usr/local/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.10/argparse.py", line 2079, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/lib/python3.10/argparse.py", line 2019, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/lib/python3.10/argparse.py", line 1943, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.10/argparse.py", line 1106, in __call__
    parser.print_help()
  File "/usr/local/lib/python3.10/argparse.py", line 2567, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/local/lib/python3.10/argparse.py", line 2551, in format_help
    return formatter.format_help()
  File "/usr/local/lib/python3.10/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/usr/local/lib/python3.10/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.10/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.10/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.10/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.10/argparse.py", line 540, in _format_action
    help_text = self._expand_help(action)
  File "/usr/local/lib/python3.10/argparse.py", line 637, in _expand_help
    return self._get_help_string(action) % params
KeyError: 'asctime'
```

**Comment by Ox0400** [comment]
```
python /usr/local/lib/python3.10/site-packages/ray/dashboard/dashboard.py --help
usage: dashboard.py [-h] --host HOST --port PORT [--port-retries PORT_RETRIES] --gcs-address GCS_ADDRESS [--grpc-port GRPC_PORT] --node-ip-address NODE_IP_ADDRESS
                    [--logging-level {debug,info,warning,error,critical}] [--logging-format LOGGING_FORMAT] [--logging-filename LOGGING_FILENAME] [--logging-rotate-bytes LOGGING_ROTATE_BYTES]
                    [--logging-rotate-backup-count LOGGING_ROTATE_BACKUP_COUNT] --log-dir LOG_DIR --temp-dir TEMP_DIR --session-dir SESSION_DIR [--minimal] [--modules-to-load MODULES_TO_LOAD]
                    [--disable-frontend]

Ray dashboard.

options:
  -h, --help            show this help message and exit
  --host HOST           The host to use for the HTTP server.
  --port PORT           The port to use for the HTTP server.
  --port-retries PORT_RETRIES
                        The retry times to select a valid port.
  --gcs-address GCS_ADDRESS
                        The address (ip:port) of GCS.
  --grpc-port GRPC_PORT
                        The port for the dashboard to listen for gRPC on.
  --node-ip-address NODE_IP_ADDRESS
                        The IP address of the node where this is running.
  --logging-level {debug,info,warning,error,critical}
                        The logging level threshold, choices=['debug', 'info', 'warning', 'error', 'critical'], default='info'
  --logging-format LOGGING_FORMAT
                        The logging format. default='"%(asctime)s\t%(levelname)s %(filename)s:%(lineno)s -- %(message)s"'
  --logging-filename LOGGING_FILENAME
                        Specify the name of log file, log to stdout if set empty, default is "dashboard.log"
  --logging-rotate-bytes LOGGING_ROTATE_BYTES
                        Specify the max bytes for rotating log file, default is 536870912 bytes.
  --logging-rotate-backup-count LOGGING_ROTATE_BACKUP_COUNT
                        Specify the backup count of rotated log file, default is 5.
  --log-dir LOG_DIR     Specify the path of log directory.
  --temp-dir TEMP_DIR   Specify the path of the temporary directory use by Ray process.
  --session-dir SESSION_DIR
                        Specify the path of the session directory of the cluster.
  --minimal             Minimal dashboard only contains a subset of features that don't require additional dependencies installed when ray is installed by `pip install ray[default]`.
  --modules-to-load MODULES_TO_LOAD
                        Specify the list of module names in [module_1],[module_2] format.E.g., JobHead,StateHead... If nothing is specified, all modules are loaded.
  --disable-frontend    If configured, frontend html is not served from the server.
```

**Comment by jjyao** [comment]
Hi @Ox0400 Thanks for the contribution!

Could you update the PR description to describe what's the issue you are trying to fix?

**Review by rickyyx — APPROVED** [review]
Thanks!

**Pull request merged**
