### PR TITLE
Task duration distribution plot.

### PR DESCRIPTION
**Pull request by alanarenda**

### CODE REVIEW

**Comment by ericl** [comment]
I just tried this out and had a couple comments:

- Looks like this is missing an `import numpy as np` in that cell.
- What does it mean for end time to be 0? Should it be -1, Infinity, or the max task end time instead?
- The '%' thing is kind of confusing. Would it work to just have the start time, end time, and maybe a slider for setting the start and end times?
- Same thing for num tasks, especially why it's negative. I would consider removing these boxes to simplify the UI here.

Also this was there before but on Ubuntu you need this change to avoid crashing:

```
diff --git a/python/ray/experimental/state.py b/python/ray/experimental/state.py
index 5222269..c79ff8b 100644
--- a/python/ray/experimental/state.py
+++ b/python/ray/experimental/state.py
@@ -431,7 +431,7 @@ class GlobalState(object):
                         **params)
 
             for (event, score) in event_list:
-                event_dict = json.loads(event)
+                event_dict = json.loads(event.decode("utf-8"))
                 task_id = ""
                 for event in event_dict:
```

**Comment by robertnishihara** [comment]
Responding to one of @ericl's comments, we can probably use `.decode("ascii)`, although maybe in that case we should also encode it using "ascii" before storing it.

**Comment by robertnishihara** [comment]
When running this (Anaconda Python 3.6, Mac), I was seeing the following error.

```python
 BokehJS successfully loaded.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-4553694f6d02> in <module>()
     55     get_sliders(task_completion_time_update)
     56 
---> 57 task_completion_time_distribution()

<ipython-input-6-4553694f6d02> in task_completion_time_distribution()
     53         push_notebook(handle=handle)
     54 
---> 55     get_sliders(task_completion_time_update)
     56 
     57 task_completion_time_distribution()

<ipython-input-4-c84c078fe495> in get_sliders(update)
    192 
    193     # Initializes the sliders
--> 194     update_wrapper(INIT_EVENT)
    195 
    196     # Display sliders and search boxes

<ipython-input-4-c84c078fe495> in update_wrapper(event)
    181                     raise ValueError('Value "{}" is not a legal breakdown value'.format(breakdown_opt.value))
    182 
--> 183                 update(smallest, largest, num_tasks, tasks)
    184 
    185     # Get updated values from a slider or text box, and update the rest of

<ipython-input-6-4553694f6d02> in task_completion_time_update(abs_earliest, abs_latest, abs_num_tasks, tasks)
     34             distr.append(data["store_outputs_end"] - data["get_arguments_start"])
     35 
---> 36         top, bin_edges = np.histogram(distr, bins='auto')
     37         left = bin_edges[:-1]
     38         right = bin_edges[1:]

~/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py in histogram(a, bins, range, normed, weights, density)
    253     else:
    254         bins = asarray(bins)
--> 255         if (np.diff(bins) < 0).any():
    256             raise AttributeError(
    257                 'bins must increase monotonically.')

~/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py in diff(a, n, axis)
   1166     slice1 = [slice(None)]*nd
   1167     slice2 = [slice(None)]*nd
-> 1168     slice1[axis] = slice(1, None)
   1169     slice2[axis] = slice(None, -1)
   1170     slice1 = tuple(slice1)

IndexError: list assignment index out of range
```

I had Bokeh version `0.12.4` (I think). Upgrading with `pip install bokeh -U` solved the problem. However, then I downgraded back to `0.12.4` and the problem did not reappear.

**Comment by robertnishihara** [comment]
@ericl do you have an example that causes it to crash? If so, we should add it to the tests.

**Pull request merged**
