### PR TITLE
[rllib] Pull out shared models for evolution strategies and policy gradient.

### PR DESCRIPTION
**Pull request by ericl**
This lets evolution strategies and policy gradient share common action distribution classes and neural network models. As a side-effect, now evolution strategies can support non-mujoco environments and those with discrete action spaces (e.g. CartPole-v0). It still doesn't support Atari, but that should work once we implement shared preprocessors.

I tested evolution strategies with CartPole-v0 and Pendulum-v0, and it seems to learn on par with previous models. Haven't tried anything larger. Policy gradient also still runs (perf should be unchanged).

TODO: figure out why Humanoid learning performance seems to have regressed.

Next prs: shared preprocessors, porting more algorithms to using the shared models.

cc @pcmoritz @robertnishihara

### CODE REVIEW

**Comment by robertnishihara** [comment]
I don't remember the evolution strategies learning with CartPole or Pendulum. Humanoid is the one we benchmarked the most.

**Comment by ericl** [comment]
I can try out Humanoid, do you have an idea on how long it would take to train on a laptop?

**Comment by ericl** [comment]
ES is now achieving parity with master. I had to change the network architecture and action distribution to be basically identical to master (2x256 tanh hidden, output torques with stdev=0).

```
----------------------------------
| EpRewMean           | 1.04e+03 |
| EpRewStd            | 569      |
| EpLenMean           | 227      |
| Norm                | 1.42e+03 |
| GradNorm            | 13.5     |
| UpdateRatio         | 0.0246   |
| EpisodesThisIter    | 1e+03    |
| EpisodesSoFar       | 2e+05    |
| TimestepsThisIter   | 2.27e+05 |
| TimestepsSoFar      | 2.46e+07 |
| ObCount             | 2.14e+03 |
| TimeElapsedThisIter | 24.4     |
| TimeElapsed         | 1.89e+03 |
----------------------------------
```

**Comment by robertnishihara** [comment]
Nice job with this PR!

This PR "introduces" the following problem, right? (To be clear, I'm not worried about this problem, but I want to record it so we know where to look if it arises in the future.)

Because the shared model uses `tf.contrib.slim`, which creates some sort of Dask thread pool, if we try to create 500 actors on a single machine (e.g., an x1.32large), e.g., we run

```
python ray/python/ray/rllib/evolution_strategies/example.py --env-name=Humanoid-v1 --num-workers=500
```

then the actor creation will fail with an error saying that it couldn't create a thread (or something like that), and potentially produce a trace like the following.

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1182, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/home/ubuntu/ray/python/ray/rllib/evolution_strategies/__init__.py", line 1, in <module>
    from ray.rllib.evolution_strategies.evolution_strategies import (
  File "/home/ubuntu/ray/python/ray/rllib/evolution_strategies/evolution_strategies.py", line 18, in <module>
    from ray.rllib.evolution_strategies import policies
  File "/home/ubuntu/ray/python/ray/rllib/evolution_strategies/policies.py", line 17, in <module>
    from ray.rllib.models import ModelCatalog
  File "/home/ubuntu/ray/python/ray/rllib/models/__init__.py", line 1, in <module>
    from ray.rllib.models.catalog import ModelCatalog
  File "/home/ubuntu/ray/python/ray/rllib/models/catalog.py", line 8, in <module>
    from ray.rllib.models.fcnet import FullyConnectedNetwork
  File "/home/ubuntu/ray/python/ray/rllib/models/fcnet.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/dask/delayed.py", line 14, in <module>
    from . import threaded
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/dask/threaded.py", line 16, in <module>
    default_pool = ThreadPool()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/pool.py", line 749, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/home/ubuntu/anaconda3/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1182, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/home/ubuntu/ray/python/ray/rllib/evolution_strategies/__init__.py", line 1, in <module>
    from ray.rllib.evolution_strategies.evolution_strategies import (
  File "/home/ubuntu/ray/python/ray/rllib/evolution_strategies/evolution_strategies.py", line 18, in <module>
    from ray.rllib.evolution_strategies import policies
  File "/home/ubuntu/ray/python/ray/rllib/evolution_strategies/policies.py", line 17, in <module>
    from ray.rllib.models import ModelCatalog
  File "/home/ubuntu/ray/python/ray/rllib/models/__init__.py", line 1, in <module>
    from ray.rllib.models.catalog import ModelCatalog
  File "/home/ubuntu/ray/python/ray/rllib/models/catalog.py", line 8, in <module>
    from ray.rllib.models.fcnet import FullyConnectedNetwork
  File "/home/ubuntu/ray/python/ray/rllib/models/fcnet.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/dask/delayed.py", line 14, in <module>
    from . import threaded
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/dask/threaded.py", line 16, in <module>
    default_pool = ThreadPool()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/pool.py", line 749, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/home/ubuntu/anaconda3/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
```

**Comment by ericl** [comment]
Yeah, it seems to, though I am not clear why. Both the nproc ulimit and /proc/sys/kernel/pid_max seem to be comfortably high.

I ended up setting num workers = 50, which worked fine in combination with https://github.com/ray-project/ray/pull/740

**Pull request merged**
