### PR TITLE
[runtime env] dedup pip installs

### LINKED ISSUE #38312: [Job] Something may have gone wrong while installing the runtime_env `pip` packages
### What happened + What you expected to happen
**Bug**
I have two machines with IP 192.168.1.100 (Machine A) and another machines with IP 192.168.1.76 (Machine B). I have setup a ray cluster with Machine A as head node and making Machine B as worker node. 
On Machine A, I attempt to submit a training job to the cluster but the following error occured. 
```
ValueError: Local directory /tmp/ray/session_2023-08-07_09-42-41_348346_2128188/runtime_resources/pip/be761d619fdc1882001721f8dcc62801c604c6f1 for URI pip://be761d619fdc1882001721f8dcc62801c604c6f1 does not exist on the cluster. Something may have gone wrong while installing the runtime_env pip packages.
```
(Log from **runtime_env_setup-04000000.log**)
```
Installing collected packages: torch
Attempting uninstall: torch
Found existing installation: torch 2.0.1
Uninstalling torch-2.0.1:
Successfully uninstalled torch-2.0.1
Successfully installed torch-2.0.1+cu117

2023-08-09 14:25:24,471 INFO pip.py:187 – Skip pip check.
2023-08-09 14:25:24,472 INFO utils.py:76 – Run cmd[4] [‘/tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52/virtualenv/bin/python’, ‘-c’, ‘\nimport ray\nwith open(r"/tmp/check_ray_version_tempfiler__nav46/ray_version.txt", “wt”) as f:\n f.write(ray.version)\n f.write(" ")\n f.write(ray.path[0])\n ‘]
2023-08-09 14:25:25,128 INFO utils.py:99 – No output for cmd[4]
2023-08-09 14:25:25,129 INFO pip.py:236 – try to write ray version information in: /tmp/check_ray_version_tempfiler__nav46/ray_version.txt
2023-08-09 14:25:25,861 INFO uri_cache.py:84 – Added URI pip://a920087bf3b915e51b6880562fe260b5332a3d52 with size 7539223515
2023-08-09 14:25:25,862 INFO pip.py:293 – Cloning virtualenv /home/jackson/Next_Word_Autocomplete/autocomplete_ray to /tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52/virtualenv
2023-08-09 14:25:25,862 INFO utils.py:76 – Run cmd[5] [’/home/jackson/Next_Word_Autocomplete/autocomplete_ray/bin/python’, ‘/home/jackson/Next_Word_Autocomplete/autocomplete_ray/lib/python3.8/site-packages/ray/_private/runtime_env/_clonevirtualenv.py’, ‘/home/jackson/Next_Word_Autocomplete/autocomplete_ray’, ‘/tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52/virtualenv’]
2023-08-09 14:25:25,947 INFO utils.py:97 – Output of cmd[5]: Usage: _clonevirtualenv.py [options] /path/to/existing/venv /path/to/cloned/venv

_clonevirtualenv.py: error: dest dir ‘/tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52/virtualenv’ exists

2023-08-09 14:25:25,948 INFO pip.py:416 – Delete incomplete virtualenv: /tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52
2023-08-09 14:25:28,351 ERROR pip.py:418 – Failed to install pip packages.
Traceback (most recent call last):
File “/home/jackson/Next_Word_Autocomplete/autocomplete_ray/lib/python3.8/site-packages/ray/_private/runtime_env/pip.py”, line 388, in _run
await self._create_or_get_virtualenv(path, exec_cwd, logger)
File “/home/jackson/Next_Word_Autocomplete/autocomplete_ray/lib/python3.8/site-packages/ray/_private/runtime_env/pip.py”, line 330, in _create_or_get_virtualenv
await check_output_cmd(create_venv_cmd, logger=logger, cwd=cwd, env=env)
File “/home/jackson/Next_Word_Autocomplete/autocomplete_ray/lib/python3.8/site-packages/ray/_private/runtime_env/utils.py”, line 101, in check_output_cmd
raise SubprocessCalledProcessError(
ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[5] failed with the following details.
Command ‘[’/home/jackson/Next_Word_Autocomplete/autocomplete_ray/bin/python’, ‘/home/jackson/Next_Word_Autocomplete/autocomplete_ray/lib/python3.8/site-packages/ray/_private/runtime_env/_clonevirtualenv.py’, ‘/home/jackson/Next_Word_Autocomplete/autocomplete_ray’, ‘/tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52/virtualenv’]’ returned non-zero exit status 2.
Last 50 lines of stdout:
Usage: _clonevirtualenv.py [options] /path/to/existing/venv /path/to/cloned/venv

_clonevirtualenv.py: error: dest dir '/tmp/ray/session_2023-08-09_13-53-16_429892_3649853/runtime_resources/pip/a920087bf3b915e51b6880562fe260b5332a3d52/virtualenv' exists
```
**Note** I have tried both Ray-Client and Python SDK but it show same error. The same scripts work if I only run a single node.

### Versions / Dependencies

ray==2.6.1
python==3.8.15

### Reproduction script

entrypoint.py
```
from ray.job_submission import JobSubmissionClient

# If using a remote cluster, replace 127.0.0.1 with the head node's IP address.
client = JobSubmissionClient("http://192.168.1.100:8265")

        
job_id = client.submit_job(
    # Entrypoint shell command to execute
    entrypoint="python example.py",
    runtime_env={"working_dir":"./",
                 "pip":"/home/jackson/Next_Word_Autocomplete/word-autocomplete/requirements.txt",
                 "env_vars": {
                              "NCCL_DEBUG":"INFO",
                              "TORCH_CPP_LOG_LEVEL":"INFO",
                              "TORCH_DISTRIBUTED_DEBUG":"INFO"
                              }}
)
print(job_id)
```
example.py:
```
from ray.train.torch import TorchTrainer
from ray.air import ScalingConfig


def train_func(config: dict):
    # Call this function at the beginning of your training script or Ray task/actor
    print("Done!")

trainer = TorchTrainer(
    train_loop_per_worker=train_func,
    train_loop_config={"lr": 1e-3, "batch_size": 64, "epochs": 4},
    scaling_config=ScalingConfig(num_workers=1, 
                                 use_gpu=True,
                                 resources_per_worker={"CPU":20,
                                                      "GPU":1},
                                 placement_strategy="SPREAD"),
)
result = trainer.fit()
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by rynewang**
If you have 2 concurrent pip installs, e.g. from 2 different runtime envs who have the same pip requirements; and your ray is in a virtualenv, you will hit the problem that ray tries to pip install to an existing virtualenv dir, which is complained by virtualenv-clone.

This PR records already-installed pip URIs and if a new request comes, early returns OK (with number of bytes).

Fixes https://github.com/ray-project/ray/issues/38312.

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
Thanks for debugging and figuring out the issue! Just a couple of questions:

- Do we need to worry about the case where the pip uri was previously deleted by `PupPlugin.delete_uri` during runtime env garbage collection? 
- Is it feasible to add a test case for this situation? I think we have some virtualenv-related tests already.

**Comment by rynewang** [comment]
> Do we need to worry about the case where the pip uri was previously deleted by PupPlugin.delete_uri during runtime env garbage collection?

In `delete_uri` I removed the record (line 471) so it'd be fine. If there are concurrent create and delete cases it'd be tricky but we are having data races on the `del self._create_locks[uri]` as well so at least this is not adding more races.

> Is it feasible to add a test case for this situation? I think we have some virtualenv-related tests already.

Sure! Would you mind providing a example test file I can reference?

**Review by architkulkarni — COMMENTED** [review]
Makes sense! 

I found some virtualenv-related tests in https://github.com/ray-project/ray/blob/master/python/ray/tests/test_runtime_env_conda_and_pip_4.py and some concurrent install / GC tests in https://github.com/ray-project/ray/blob/master/python/ray/tests/test_runtime_env_conda_and_pip_3.py

**Comment by rynewang** [comment]
Thanks! Moved the multi pip test to virtualenv tests.

**Review by architkulkarni — APPROVED** [review]
I think we should remove `test_multiple_pip_installs` from the original file, because it looks like in the new file it'll be tested once with virtualenv and once without virtualenv.  Is this right?

**Review by architkulkarni — APPROVED** [review]

**Comment by architkulkarni** [comment]
Test failures:
- Windows test_actor_bounded_threads unrelated
- tune test_client unrelated
- tune test_cluster_searcher unrelated
- test_memory_pressure unrelated
- doctest unrelated
- test_client_builder unrelated
- test_out_of_disk_space unrelated

**Pull request merged**
