### PR TITLE
[core] Streaming generator task waits for all object report acks before finishing the task

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Cherry-pick #44079, fixes for #43914 and #43978.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
@stephanie-wang we are pretty late into the release cycle. How critical is it tp idc this one into 2.10?

**Comment by stephanie-wang** [comment]
> @stephanie-wang we are pretty late into the release cycle. How critical is it tp idc this one into 2.10?

We need it for Ray Data recovery. If we don't cherry-pick, I think we need to do a minor release at the very least. @c21 @raulchen can weigh in too.

**Comment by zhe-thoughts** [comment]
@c21 @raulchen Is this in scope for Data GA? If so we should pick (even at the cost of delaying the release)

**Comment by c21** [comment]
> Is this in scope for Data GA? If so we should pick (even at the cost of delaying the release)

Yes, let's cherry pick the PR.

**Comment by raulchen** [comment]
yes, it's a critical stability fix

**Review by zhe-thoughts — APPROVED** [review]
@khluu Let's pick but be careful about possible issues (e.g. release test failures)

**Pull request merged**
