### PR TITLE
[Data] Backwards compatibility for Preprocessor that have been fit in older versions

### PR DESCRIPTION
**Pull request by amogkam**
This is a cherry pick of #39173

Per user ask, support transforming with Preprocessors that have been fit in an older version of Ray.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]
This is a concrete user ask; qualifies for picking

**Review by c21 — APPROVED** [review]

**Comment by GeneDer** [comment]
@amogkam Can you get https://github.com/ray-project/ray/pull/39173 merged into master first?

**Comment by GeneDer** [comment]
Also, how risky is this change without a unit test?

**Comment by amogkam** [comment]
yes will get #39173 merged once CI finishes

**Review by bveeramani — APPROVED** [review]

**Comment by amogkam** [comment]
Original is merged @GeneDer

**Pull request merged**
