### PR TITLE
[Serve] [Docs] Correct tags for scheduling task metrics

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

The scheduling task metrics introduced in #38199 have an `actor_id` tag. However, the tag is listed as `actor_name` in the docs.

This change corrects the tag in the docs.

Link to the updated docs: https://anyscale-ray--39549.com.readthedocs.build/en/39549/serve/monitoring.html#built-in-ray-serve-metrics

## Related issue number

N/A

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - This is a pure docs change.

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
@shrekris-anyscale can we mark these metrics as some kind of developer API btw? They are pretty likely to change as we evolve the routing code

**Review by edoakes — APPROVED** [review]

**Comment by shrekris-anyscale** [comment]
> @shrekris-anyscale can we mark these metrics as some kind of developer API btw? They are pretty likely to change as we evolve the routing code

Yeah, good idea. I added a footnote marking them as `developer metrics`.

**Comment by shrekris-anyscale** [comment]
I reformatted the footnotes, so they show up line-by-line:

Screen Shot 2023-09-12 at 9 37 58 AM

**Comment by shrekris-anyscale** [comment]
@edoakes This change is ready to merge.

**Pull request merged**
