### PR TITLE
[Streaming] try to trigger mock transfer tests ci

### PR DESCRIPTION
**Pull request by ashione**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by ashione** [comment]
@edoakes @rkooo567 

**Comment by ashione** [comment]
@raulchen @jovany-wang @zhijunfu please help us to review this PR.
We remove this ci suppress_output and display all streaming bazel test logs on console.

**Comment by edoakes** [comment]
LGTM, but can you also try running the streaming test repeatedly to make sure it isn't flaky?

**Comment by ashione** [comment]
> LGTM, but can you also try running the streaming test repeatedly to make sure it isn't flaky? You can just put it in a loop in the bash commands in CI.

I have no idea about why this test pass in command line but failed with ci_suppress_output.
By the way, I run 1000+ times in local machine(macos and linux os) and all tests pass.

**Comment by ashione** [comment]
@edoakes @jovany-wang @zhijunfu Could you help me to retry this travis CI? I notice that failure is unrelated with this PR.

**Review by jovany-wang — APPROVED** [review]

**Comment by edoakes** [comment]
@ashione I re-ran the build.

Btw, I meant run it repeatedly in CI - push a temporary commit that runs it in a loop in CI, verify that it passes consistently, then revert that commit and merge. Often CI is more resource constrained/contended so things will fail there more often.

**Comment by ashione** [comment]
> @ashione I re-ran the build.
> 
> Btw, I meant run it repeatedly in CI - push a temporary commit that runs it in a loop in CI, verify that it passes consistently, then revert that commit and merge. Often CI is more resource constrained/contended so things will fail there more often.

Well,  got it and I will add `--runs_per_test=100` for this case.

**Comment by ashione** [comment]
> @ashione I re-ran the build.
> 
> Btw, I meant run it repeatedly in CI - push a temporary commit that runs it in a loop in CI, verify that it passes consistently, then revert that commit and merge. Often CI is more resource constrained/contended so things will fail there more often.

All repeated test cases pass but timeout，then the final state is `failed`.
Perhaps travis ci machine is too tiny flavor to run so many times. I'll revert this temporary commit.

**Review by jovany-wang — APPROVED** [review]

**Pull request merged**
