### PR TITLE
[train] fix Train/Tune integration on Client

### LINKED ISSUE #20348: [release][nightly][pg] tune_cifar_pytorch_pbt_example does not work on nightly (Placement group error)
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

I ran with ray 1.8 it works, when I run with commit c0aeb4a2368ca9c53f055522eebd65bcfd457b07 I get the following error:
```
(run pid=864) ray::TrainTrainable.train_buffered() (pid=253, ip=10.0.24.128, repr=<ray.train.trainer.TrainTrainable object at 0x7efea85879d0>)
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 262, in run
(run pid=864)     self._entrypoint()
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
(run pid=864)     self._status_reporter.get_checkpoint())
(run pid=864)   File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
(run pid=864)   File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/train/trainer.py", line 761, in tune_function
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/train/trainer.py", line 162, in __init__
(run pid=864)     max_retries=max_retries)
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 524, in remote
(run pid=864)     runtime_env=new_runtime_env)
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 747, in _remote
(run pid=864)     placement_group=placement_group)
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 452, in configure_placement_group_based_on_context
(run pid=864)     placement_resources, task_or_actor_repr)
(run pid=864)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 370, in _validate_resource_shape
(run pid=864)     raise ValueError(f"Cannot schedule {task_or_actor_repr} with "
(run pid=864) ValueError: Cannot schedule BackendExecutor with the placement group because the resource request {'node:10.0.24.128': 0.01, 'CPU': 0} cannot fit into any bundles for the placement group, [{'CPU': 1.0}, {'node:10.0.16.137': 0.01}, {'CPU': 1.0}, {'CPU': 1.0}].
```

### Versions / Dependencies

python 3.7, ray c0aeb4a2368ca9c53f055522eebd65bcfd457b07 (nightly)

### Reproduction script

`RAY_ADDRESS=anyscale://ga-demo-aws python tune_cifar_pytorch_pbt_example.py`

The cluster env:
Screen Shot 2021-11-14 at 4 11 06 PM

### Anything else

@richardliaw , can you please help with this one?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by matthewdeng**
## Why are these changes needed?

Follow-up to https://github.com/ray-project/ray/pull/20123.

Train uses `force_on_current_node` to support Ray Client by ensuring that the `BackendExecutor` is scheduled on the head node. 

~With Tune integration, this causes some scheduling issues because the `PlacementGroupFactory` constructed for Tune will try to place the `BackendExecutor` on Tune's head node, and not the node the Trial is assigned to.~

~To solve this, we only call `force_on_current_node` if Train is not in a Tune session. This will cause the implementation between Train and Train+Tune to diverge slightly. **Note:** I'm not sure what the strategy is for scheduling a 0 resource Actor in a placement group is - if it schedules to the first bundle (with the `Trainer`) then the resulting behavior is the same.~

`force_on_current_node` is unnecessary to begin with since the scheduling algorithm should place the 0 CPU `BackendExecutor` on the head node. This PR removes the `force_on_current_node` logic. 

## Related issue number

Closes #20348

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by AmeerHajAli** [comment]
Thanks Matt, did you test it with https://docs.ray.io/en/latest/train/examples/tune_cifar_pytorch_pbt_example.html and --use-gpu?

**Comment by AmeerHajAli** [comment]
cc @richardliaw

**Comment by matthewdeng** [comment]
@AmeerHajAli I've verified this functionality by running the following script:
```
RAY_ADDRESS="ray://<head_node>:10001" python tune_cifar_pytorch_pbt_example.py --use-gpu
```

Example logs:
```
(run pid=6179) == Status ==
(run pid=6179) Current time: 2021-11-15 04:33:48 (running for 00:14:51.33)
(run pid=6179) Memory usage on this node: 1.8/61.4 GiB
(run pid=6179) PopulationBasedTraining: 4 checkpoints, 3 perturbs
(run pid=6179) Resources requested: 6.0/80 CPUs, 4.0/4 GPUs, 0.0/378.16 GiB heap, 0.0/161.84 GiB objects (0.0/2.0 accelerator_type:M60)
(run pid=6179) Result logdir: /home/ubuntu/ray_results/tune_function_2021-11-15_04-18-57
(run pid=6179) Number of trials: 4/4 (1 PAUSED, 1 PENDING, 2 RUNNING)
(run pid=6179) +---------------------------+----------+-----------------+-------+--------+------------------+------+-----------+
(run pid=6179) | Trial name                | status   | loc             |    lr |   iter |   total time (s) |   ts |      loss |
(run pid=6179) |---------------------------+----------+-----------------+-------+--------+------------------+------+-----------|
(run pid=6179) | tune_function_26b2c_00000 | RUNNING  | 10.0.1.181:5721 | 0.008 |      2 |          208.023 |    0 | nan       |
(run pid=6179) | tune_function_26b2c_00001 | RUNNING  | 10.0.1.7:7253   | 0.01  |      1 |          288.46  |    0 |   1.42851 |
(run pid=6179) | tune_function_26b2c_00003 | PAUSED   | 10.0.1.7:6992   | 0.01  |      3 |          240.629 |    0 | nan       |
(run pid=6179) | tune_function_26b2c_00002 | PENDING  | 10.0.1.7:6704   | 0.1   |      3 |          258.734 |    0 | nan       |
(run pid=6179) +---------------------------+----------+-----------------+-------+--------+------------------+------+-----------+
```

**Comment by AmeerHajAli** [comment]
Yes, I verified this works. Can we please add a test that would fail before this PR and pass after?

**Comment by matthewdeng** [comment]
@AmeerHajAli it's a bit nuanced... I'm not sure how to create a node with a different IP address and add it to a `cluster_utils.Cluster` for CI testing. Can you point me in the right direction here?

I tried the following:
```
    cluster = Cluster()
    cluster.add_node(num_cpus=1)
    cluster.add_node(num_cpus=3, num_gpus=2, node_ip_address="127.0.0.2")
    ray.init(address=cluster.address)
```
`ray.cluster_resources()` looks correct:
```
{'memory': 73406552884.0, 'CPU': 4.0, 'object_store_memory': 314572800.0, 'node:127.0.0.1': 1.0, 'node:127.0.0.2': 1.0, 'GPU': 2.0}
```

But the second node doesn't seem to be recognized by the Autoscaler:
```
======== Autoscaler status: 2021-11-14 21:57:42.869947 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_37a118623af8af21628c06d5acd81640ecb2e0127cf5787289f06227
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/1.0 CPU
 0.00/32.389 GiB memory
 0.00/0.146 GiB object_store_memory

Demands:
 (no resource demands)
```

**Comment by AmeerHajAli** [comment]
A great question to @ericl or @DmitriGekhtman or @sasha-s

**Comment by ericl** [comment]
Why are we using force on current node at all? Ray client shouldn't need anything like that to work.

**Comment by matthewdeng** [comment]
@ericl for Train it's primarily an optimization to better support fault tolerance (this Actor would be scheduled on a non-preemptible head node). A standard setup could look like a CPU-only head node for this Actor and GPU worker nodes for the distributed training workers. While it's not a hard requirement to make Ray Client work, I think it does help from a usability perspective.

For Tune I believe it's a little more baked into the design because the Actor which is wrapped in `force_on_current_node` writes checkpoints to disk (for now), and the user would access these checkpoints by `ray attach`ing onto the head node.

**Comment by ericl** [comment]
As a safer optimization, why not instead create the Backend executor with
zero CPUs then? It will be pretty much guaranteed to be placed on the head
then. In the future we can support colocation placement hints.

The PR seems like it is working around a hack with another hack. We
shouldn't be using the resource in the first place...

**Comment by matthewdeng** [comment]
Gotcha, I wasn't sure if the scheduling algorithm prioritizes the head node, but in that case this does seem to be superfluous. I'll remove the `force_on_current_node` logic from Train.

FYI @amogkam

**Comment by amogkam** [comment]
Hey @ericl, scheduling with `num_cpus=0` doesn't guarantee placement on the current node right? The `force_on_current_node` method that we have uses `ray.get_runtime_context()` which makes this guarantee that the actor will be placed on the node containing the client server (i.e. the head node).

This is the same mechanism that's used by Tune, xgboost-ray, and Serve.

We had previously raised an issue https://github.com/ray-project/ray/issues/15930, and the `force_on_current` node was the recommendation that was made.

**Review by amogkam — CHANGES_REQUESTED** [review]
@matthewdeng could we switch back to using `force_on_current` node and then disable this for tune? We can also make an issue to add a test once we have multi-node CI.

**Comment by ericl** [comment]
It almost always does. I really don't think we should force placement in
general. It causes fault tolerance issues and prevents users from using
these libraries in tasks and actors (i.e., breaks composition).

Please don't use force placement in Ray libraries.

**Review by amogkam — APPROVED** [review]

**Pull request merged**
