### PR TITLE
[Datasets] Avoid `torch.as_tensor()` memory leak in `ds.to_torch()`

### LINKED ISSUE #29034: [AIR] Potential GRAM memory leak in pandas batch conversion
### What happened + What you expected to happen

See https://github.com/ray-project/ray/pull/28917

With batch size of ~1024, 646KB for each image, we have roughly ~0.6GB per batch. During BatchPredictor's allocated memory profiling, we also see ~0.6 GRAM memory leak between each predicted batch on the same GPU device.

Screen Shot 2022-10-03 at 10 01 38 PM

We're very, very likely not releasing batch data correctly in pandas conversion path. This symptom is discovered during BatchPredictor benchmarking, but very likely not just limited to predictor, more about general AIR data conversion.

### Versions / Dependencies

master

### Reproduction script

See PR attached for reproduction.

https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/air_tests/air_benchmarks/workloads/gpu_batch_prediction.py

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### LINKED ISSUE #30629: RAM memory leak with Dataset Pipeline
### What happened + What you expected to happen

1. The bug:
while executing the script below, the RAM keeps growing until it reaches capacity and the worker has to restart training from a checkpoint.  The Object Store memory remains constant.

2. Expected behavior:
we expected the RAM to be somehow constant as we experienced while using the nightly build.

3. Useful information:
A contributor at Ray gave us a fix for tensor creation that sped up our training by 4.5X.
This fix was given to us in a nightly release(see below)  a couple of days after talking with him/her on Slack.
(it was the best customer experience we've had so far with an open source library, thanks!).

### Versions / Dependencies

We don't have an issue executing the script with the nightly build below:
https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

We have an issue with Ray 2.1.0 though.

### Reproduction script

```
import ray
import ray.train
import ray.train.torch
import ray.data
from ray.data.extensions import TensorArray

import time
import torch
import numpy as np
import pandas as pd


def get_preprocessed_sample(data):
    return pd.DataFrame(
        {
            'X': TensorArray([np.random.randint(256, size=(3, 35, 224, 224), dtype='uint8')] * len(data)),
            'y': TensorArray([55] * len(data))
        }
    )


if __name__ == '__main__':
    n_samples = 400000
    parallelism = int(n_samples / 3) # 3 samples per block
    num_vcpu_per_worker = 12
    epochs = 50
    batch_size = 32
    num_workers = 1


    ray.init(address='localhost:6379')
    # ray.init()
    # waiting for cluster nodes to come up.
    while len(ray.nodes()) < num_workers:
        print(f"waiting for nodes to start up: {len(ray.nodes())}/{num_workers}")
        time.sleep(5)


    data_pipeline = ray.data \
        .range(n_samples, parallelism=parallelism) \
        .window(blocks_per_window=int(num_vcpu_per_worker)) \
        .repeat(epochs) \
        .map_batches(lambda x: get_preprocessed_sample(x), batch_size=None) \
        .random_shuffle_each_window()

    dataset_iterator = data_pipeline.iter_epochs()

    for epoch in range(epochs):
        dataset = next(dataset_iterator)
        torch_dataset = dataset.to_torch(
            label_column='y',
            feature_columns=['X'],
            label_column_dtype=torch.long,
            feature_column_dtypes=torch.float16,
            batch_size=batch_size,
        )
        for batch_id, (X, y) in enumerate(torch_dataset):
            print('{} samples processed'.format((batch_id + 1) * 32))
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by clarkzinzow**
`torch.as_tensor()` leaks memory when its type check fails; this PR avoids this memory leak by no longer doing a try-except fallback on `torch.as_tensor()`, instead eagerly checking for a type that Torch can't handle in its tensor conversion.

## Fixes

Closes #30629, closes https://github.com/ray-project/ray/issues/29034

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jianoaix — COMMENTED** [review]
Can we add a test like the repro to cover this?

**Comment by Yard1** [comment]
Is `np.object_` the only dtype that cannot be converted?

**Comment by clarkzinzow** [comment]
@jianoaix Any suggestions on how to test? We could factor out RLlib's testing utility for detecting memory leaks, but this could turn into a pretty big change, and since this is low priority, this PR will probably languish for a while: https://github.com/ray-project/ray/blob/47f8faa0f2389e6995b3cda6834adbbdac71316e/rllib/utils/debug/memory.py#L202-L356

@Yard1 It's the only one that we care about AFAIK; stacking should fail for all other unsupported types, so propagating the error more eagerly for all others should be fine.

**Comment by Yard1** [comment]
Ok, that sounds good to me!

**Comment by jianoaix** [comment]
> @jianoaix Any suggestions on how to test? We could factor out RLlib's testing utility for detecting memory leaks, but this could turn into a pretty big change, and since this is low priority, this PR will probably languish for a while:
> 
> https://github.com/ray-project/ray/blob/47f8faa0f2389e6995b3cda6834adbbdac71316e/rllib/utils/debug/memory.py#L202-L356
> 

That seems a nice test to have. For now could we run that leaky script for N secs (or iterations) and check process memory is not increasing by X%?

**Comment by clarkzinzow** [comment]
@jianoaix I added a memory leak test, confirmed locally that this fails without the change and passes with it.

**Comment by clarkzinzow** [comment]
cc @sven1977 @gjoliver @avnishn @kouroshHakha, I pulled the `_test_some_code_for_memory_leaks` memory checking utility from RLlib out into `ray.util.debug` so it can be used by other libraries, lmk if any aspect of this change is not agreeable!

**Comment by clarkzinzow** [comment]
@jianoaix @c21 Ping for data team review.

@sven1977 @gjoliver @avnishn @kouroshHakha Ping for RL team review, since this PR pulls out the memory leak testing utility into `ray.util.debug`.

**Review by jianoaix — APPROVED** [review]

**Review by c21 — APPROVED** [review]

**Review by avnishn — APPROVED** [review]
It looks like in this change you've moved part of the RLlib memory check utility and not modified it. Thats totally fine w me.

**Pull request merged**
