### PR TITLE
Fix a cxx compiler warning.

### PR DESCRIPTION
**Pull request by ghost**
Minor fix for https://github.com/ray-project/ray/issues/621.

### CODE REVIEW

**Comment by pcmoritz** [comment]
ok to test

**Comment by pcmoritz** [comment]
Thanks, this looks good! I'll merge it if you also fix plasma_error_status in plasma_common.cc; it needs to return a Status::OK() in the default clause.

**Comment by pcmoritz** [comment]
Can you also create a PR for arrow? I made a JIRA for it here: https://issues.apache.org/jira/browse/ARROW-1256

Sorry for the inconvenience, we are in the transition period for https://github.com/ray-project/ray/pull/692 right now, but it should soon be resolved and then we won't have two parallel codebases any more.

**Comment by robertnishihara** [comment]
This has been fixed in a separate PR.

**Pull request closed without merging**
