### PR TITLE
[Linkcheck; RLlib] Fix linkcheck (had removed PG algo from RLlib).

### PR DESCRIPTION
**Pull request by sven1977**
Fix linkcheck (had removed PG algo from RLlib).

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sven1977** [comment]
The `random_agent` link had already been removed in a PR we merged earlier today.

**Review by edoakes — APPROVED** [review]
Thanks for fixing quickly Sven!

**Comment by edoakes** [comment]
I think there's another in `rllib-dev` that needs to get fixed:

```
[2024-03-15T15:17:58Z] (rllib/rllib-concepts: line   13) broken    https://github.com/ray-project/ray/blob/master/rllib/algorithms/pg/pg_tf_policy.py - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/rllib/algorithms/pg/pg_tf_policy.py
--
  | [2024-03-15T15:17:58Z] ( rllib/rllib-dev: line   71) broken    https://github.com/ray-project/ray/tree/master/rllib/algorithms/random_agent/random_agent.py - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/tree/master/rllib/algorithms/random_agent/random_agent.py
```

**Comment by sven1977** [comment]
The `random_agent` one had already been removed in an earlier PR merged today. Could you pull again?

**Comment by sven1977** [comment]
yup, link check is green now.

**Comment by edoakes** [comment]
Nice!

**Review by matthewdeng — APPROVED** [review]

**Pull request merged**
