### PR TITLE
[Metric] AssertError when ray is not initialized

### PR DESCRIPTION
**Pull request by rkooo567**
## Related issue number

https://github.com/ray-project/ray/issues/13378

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
```
/Users/travis/build/ray-project/ray/python/ray/util/metrics.py:27: AssertionError
_______________________ test_custom_metrics_default_tags _______________________
metric_mock = <MagicMock id='4656867984'>
    def test_custom_metrics_default_tags(metric_mock):
        histogram = Histogram(
            "hist", description="hist", boundaries=[1.0, 2.0],
>           tag_keys=("a", "b")).set_default_tags({
                "b": "b"
            })
/Users/travis/build/ray-project/ray/python/ray/tests/test_metrics_agent.py:239: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/travis/build/ray-project/ray/python/ray/util/metrics.py:142: in __init__
    super().__init__(name, description, tag_keys)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <ray.util.metrics.Histogram object at 0x1158ea4e0>, name = 'hist'
description = 'hist', tag_keys = ('a', 'b')
    def __init__(self,
                 name: str,
                 description: str = "",
                 tag_keys: Optional[Tuple[str]] = None):
        assert ray.is_initialized(), (
>           "Ray metric APIs cannot be used when ray is not initialized.")
E       AssertionError: Ray metric APIs cannot be used when ray is not initialized.
/Users/travis/build/ray-project/ray/python/ray/util/metrics.py:27: AssertionError
________________________ test_custom_metrics_edge_cases ________________________
metric_mock = <MagicMock id='4657305080'>
    def test_custom_metrics_edge_cases(metric_mock):
        # None or empty boundaries are not allowed.
        with pytest.raises(ValueError):
>           Histogram("hist")
/Users/travis/build/ray-project/ray/python/ray/tests/test_metrics_agent.py:261: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/travis/build/ray-project/ray/python/ray/util/metrics.py:142: in __init__
    super().__init__(name, description, tag_keys)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <ray.util.metrics.Histogram object at 0x1158aa978>, name = 'hist'
description = '', tag_keys = None
    def __init__(self,
                 name: str,
                 description: str = "",
                 tag_keys: Optional[Tuple[str]] = None):
        assert ray.is_initialized(), (
>           "Ray metric APIs cannot be used when ray is not initialized.")
E       AssertionError: Ray metric APIs cannot be used when ray is not initialized.
/Users/travis/build/ray-project/ray/python/ray/util/metrics.py:27: AssertionError
```

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by simon-mo** [comment]
stale?

**Comment by simon-mo** [comment]
Closing due to stale PR, please feel free to re-open

**Pull request closed without merging**
