### PR TITLE
Updated outstanding_callbacks to unordered_map

### PR DESCRIPTION
**Pull request by pschafhalter**
- Converted `outstanding_callbacks` from UT hash table to `std::unordered_map`
- More progress on #404

### CODE REVIEW

**Comment by robertnishihara** [comment]
@pschafhalter The tests seem to be failing. Any idea what's going on here?

**Comment by pschafhalter** [comment]
Looks like `destroy_timer_callback()` modifies `outstanding_callbacks` which creates issues with the iterator in `destroy_oustanding_callbacks()`. Strangely, this wasn't throwing any errors while testing locally. I'll push an update that fixes the issue.

**Comment by robertnishihara** [comment]
There's a valgrind error that looks potentially related.

It's possible that it could be fixed by #1125, though I'm not sure.

**Comment by robertnishihara** [comment]
Once #1125 is merged, let's rebase on top of that, and I think that should fix the valgrind problem.

**Comment by pschafhalter** [comment]
Sounds good, I'll keep an eye out.

**Comment by robertnishihara** [comment]
@pschafhalter This can be rebased now.

**Comment by pschafhalter** [comment]
@robertnishihara great, I rebased. Hopefully, the valgrind error is fixed.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
