### PR TITLE
[ray] make version file a separate file

### PR DESCRIPTION
**Pull request by aslonnie**
so that:

- update does not change other stuff in `__init__.py`
- `_version.py` is independently runnable and can print version info.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by aslonnie** [comment]
@can-anyscale could you review?

**Comment by can-anyscale** [comment]
totally

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
still need an approval from @ray-project/ray-docs

**Review by angelinalg — APPROVED** [review]
stamp

**Pull request merged**
