### PR TITLE
Improve errors raised by ds.groupby() of unsupported key type

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This raises errors early in the driver instead of in the workers. Btw @jjyao we should probably fix our error retry policy to not retry non-IO errors, is there a way to do that today? Perhaps we can raise a fatal type of error for non-IO errors in our tasks.

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by jjyao** [comment]
@ericl I remember when we initially discussed the implementation of `retry_exceptions`. We started it with a bool type and expected that in the future we will support a list of exception types as well.

The current semantics of bool type is that if it's true, all exceptions are retried, but I think we can change the semantics to be only retrying IOError and subclasses. Alternatively, if we don't want to change the semantics of bool type, we can support list of exceptions and do `retry_exceptions=[IOError]` by default in dataset.

**Comment by clarkzinzow** [comment]
@jjyao If it's not much extra effort, I'd vote for adding support for a list of retryable exceptions. Any complications around having Python objects (classes) in task options? Should be able to serialize them as pickle bytes, store those bytes opaquely in the task spec, and eventually deserialize them for the retrying logic during task execution, right?

**Review by clarkzinzow — APPROVED** [review]
LGTM, nice!

**Comment by ericl** [comment]
TODO: also improve errors for aggregate()

**Comment by ericl** [comment]
Will follow-up with a PR cleaning up errors for aggregate() and sort() as well.

**Review by scv119 — APPROVED** [review]

**Pull request merged**
