### PR TITLE
Serve [DOC] Minor nit fix on usage and syntax

### PR DESCRIPTION
**Pull request by dmatrix**
Signed-off-by: Jules S.Damji <jules@anyscale.com>

## Why are these changes needed?

A minor nit to fix usage and syntax. No major changes, but small changes help readability. 

## Checks

- [ x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by dmatrix** [comment]
@bveeramani Strange that after your suggested update to black, it requests form 14 reviewers ... :-)

**Comment by edoakes** [comment]
@dmatrix you accidentally checked in some files under `streaming/`, otherwise LGTM -- thanks for the fixes!

**Comment by edoakes** [comment]
Please ping me when you removed those files

**Comment by dmatrix** [comment]
@edoakes Am a bit confused. I removed the files, but why does git think I have added these files when I haven't touched them? This new Black code formatting seems to get me spinning on my toes... :) Those files were merged already in a conflict.

Screen Shot 2022-01-31 at 6 17 24 PM

**Comment by dmatrix** [comment]
My branch is a bit messed up. I'll close this PR and start a new one, along with another tutorial I have to add.

**Comment by edoakes** [comment]
Sorry about that @dmatrix, bad timing w/ linter change.. things should be stable now

**Pull request closed without merging**
