### PR TITLE
Update git-clang-format to support Python 3.

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
Update git-clang-format to support Python3 and modify it to support our case.

### CODE REVIEW

**Comment by raulchen** [comment]
It'd be nicer to document the modifications. So it's easier to update this script in the future.

**Comment by robertnishihara** [comment]
Thanks for doing this! @guoyuhong did you directly take the upstream version from https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format? It seems a little different.

**Comment by robertnishihara** [comment]
Closing it was an accident.

**Comment by guoyuhong** [comment]
@robertnishihara It looks there are some whitespace diffs. I have added them back.

**Comment by guoyuhong** [comment]
@raulchen Yes, good idea.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
