### PR TITLE
[release-automation] Separate steps into groups

### PR DESCRIPTION
**Pull request by khluu**
- Apparently the block step blocks all the steps after it (unless the step specifies `depends_on`). This happens for mac sanity check step since it has no dependency: https://buildkite.com/ray-project/release-automation/builds/470/dag
- This separates each platform sanity check to separate groups so they don't block each other
- Also separate upload wheels step into its own group to allow more flexibility (upload to PyPI & TestPyPI doesn't have to be in the same build)
- Fix typo `forge-arm64` -> `forge_arm64`

### CODE REVIEW

**Comment by khluu** [comment]
I tested with this build and was able to see each of the group start "waiting for agent" right after unblocking without waiting for other steps: https://buildkite.com/ray-project/release-automation/builds/476#_

**Comment by aslonnie** [comment]
isn't it easier to just add the `depends_on` for steps? rather than breaking it down into pieces?

**Review by aslonnie — COMMENTED** [review]
isn't it easier to just add the depends_on for steps? rather than breaking it down into pieces?

like each group now only contains 1 or 2 command steps.

**Comment by khluu** [comment]
> isn't it easier to just add the depends_on for steps? rather than breaking it down into pieces?

for example, mac sanity checks don't really have any `depends_on`. I tried having it depends on the block step but that didn't really work.

**Comment by aslonnie** [comment]
> I tried having it depends on the block step but that didn't really work.

why? that is how it supposed to work?

**Review by aslonnie — COMMENTED** [review]
I don't really understand why using `depends_on` key does not work here..

**Comment by khluu** [comment]
@aslonnie  You can take a look at this commit: https://github.com/ray-project/ray/commit/30fdfe8c5fe4252ee304e64d2e6002189310077e which I set mac sanity check step to depend on its block step. The block step does depend on the step before it though: https://buildkite.com/ray-project/release-automation/builds/474/dag When I unblocked the step, the mac sanity check steps didn't even run or wait for agent ...

**Comment by aslonnie** [comment]
> When I unblocked the step, the mac sanity check steps didn't even run or wait for agent .. they were just stuck there

you need to add an empty `depends_on` for the wait/block step too. otherwise, a wait/block step depends on all steps before it.

**Review by aslonnie — COMMENTED** [review]
like this:

https://github.com/ray-project/ray/pull/45425

**Pull request closed without merging**
