### PR TITLE
Improve performance of ray log

### PR DESCRIPTION
**Pull request by qicosmos**
## Why are these changes needed?

Improve performance of RayLog: 50%-200% faster.
I did such improvements:
- generate log prefix at compile-time, eliminate runtime overhead.
- use custom stack allocator to avoid heap allocation.
- add a flag to control whether flush log every time,  in some scenarios don't need to flush every time, spdlog will do asnc flush.
- remove inheritance of RayLog(because of historical reasons we have to keep spdlog and glog at the same time before, actually we have removed glog, so no need use inheritance now).

Some test results on my linux machine([Perf Test](https://github.com/ray-project/ray/blob/2261e008212df2d1b8b051a00f0773f764685e7a/src/ray/util/logging_test.cc#L215)):
1. flush every time(rounds 100000):
```
new ray log: 179573868 ns
old ray log: 270365270 ns
50% faster.
```

2. don't flush every time(rounds 100000):
```
new ray log: 69729456 ns
old ray log: 146571339 ns
210% faster.
```

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests

### CODE REVIEW

**Comment by rkooo567** [comment]
this is awesome! I will review the PR soon. cc @iycheng

**Comment by rkooo567** [comment]
Btw why did you copy things from `https://github.com/tomazos/fixed_string/blob/master/fixed_string.h` and `https://howardhinnant.github.io/short_alloc.h`? Is there a adoption criteria here? (and also is there any other alternative in existing library)?

**Review by fishbone — CHANGES_REQUESTED** [review]
I feel really not comfortable to vendor so many codes just for log optimization. Can we do a better job here to reduce the dependence? This is really hard to maintain.
Btw, could you provide some metrics about e2e gain for this one, I feel that metrics is more important to ray.

**Comment by scv119** [comment]
I did some basic benchmark over RAY_LOG [using this code](https://github.com/ray-project/ray/blob/master/src/ray/util/logging_test.cc#L199). 

So the throughput before and after is 133511 lines/second vs 161290 lines/second, which is around 20% throughput improvement. 

I also counted the average lines of [INFO]/[DEBUG] log generated on a e2e test cluster, which is around 10 lines/s for INFO logs and 100 lines/s for DEBUG logs.

From the above numbers I think the string/stack allocation shouldn't give us much improvement.

**Comment by iycheng** [comment]
> > I did some basic benchmark over RAY_LOG [using this code](https://github.com/ray-project/ray/blob/master/src/ray/util/logging_test.cc#L199).
> > So the throughput before and after is 133511 lines/second vs 161290 lines/second, which is around 20% throughput improvement.
> > I also counted the average lines of [INFO]/[DEBUG] log generated on an e2e test cluster, which is around 10 lines/s for INFO logs and 100 lines/s for DEBUG logs.
> > From the above numbers I think the fixed-string/stack allocation shouldn't give us much improvement.
> 
> Because default flush log every time, if you set the flag as false: RayLog::EnableAlwaysFlush(false); You will get the 2x faster result.
> 
> I tested on mac and linux, on my linux new raylog is 50% faster, on mac new raylog is about 31% faster.
> 
> I can provide an entire test code.

From my memory, for logging, we should always use async logging by default for most cases. Should the right thing here be done is to use async logging? (https://github.com/gabime/spdlog#asynchronous-logging)

**Pull request closed without merging**
