### PR TITLE
Fix missing overrides

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Cannot compile on Windows due to `-Werror,-Winconsistent-missing-overrides`.  
And the macros should provide a way to add specifiers regardless.

## Related issue number

#631, #6637

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]

**Comment by zhijunfu** [comment]
@edoakes Thanks for fixing this!

**Comment by mehrdadn** [comment]
@zhijunfu Did you mean to tag someone else? 😄

**Comment by edoakes** [comment]
Haha. Probably because I requested his review :) thanks @mehrdadn

**Comment by zhijunfu** [comment]
@mehrdadn sorry, I somehow got this wrong... Thank you for fixing this! :)

**Comment by zhijunfu** [comment]
> Haha. Probably because I requested his review :) thanks @mehrdadn

Yes I guess this gave me the impression:)

**Pull request merged**
