### PR TITLE
increase container memory and shm to 20G

### PR DESCRIPTION
**Pull request by shaneknapp**
## What do these changes do?

increase memory allocated to docker containers running on jenkins.

### CODE REVIEW

**Comment by robertnishihara** [comment]
This looks good to me.

**Comment by shaneknapp** [comment]
test this please

**Review by atumanov — APPROVED** [review]
LGTM

**Comment by robertnishihara** [comment]
@shaneknapp was the Jenkins build hanging? Our Jenkins tests have gotten a bit flaky recently, so test failures are probably not caused by this PR.

**Comment by shaneknapp** [comment]
@robertnishihara -- no, i manually killed that build so that i could start testing my new commit immediately.

@atumanov and i hope that this change will de-flake the builds by allocating more memory to the docker containers.

**Comment by pcmoritz** [comment]
This is amazing 🥇

**Comment by robertnishihara** [comment]
Wow, nice!

**Comment by atumanov** [comment]
continuation of this saga shall continue shortly , but this is a good first step ;)

**Comment by shaneknapp** [comment]
@atumanov yep, heh...  i'm curious as to whether your master build will pass now.

**Pull request merged**
