### PR TITLE
Make the time series metrics in dashboard auto-refresh

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Before, the grafana embeds would show a static time range and the page had to be manually refreshed to see the latest data.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Nice. How often does it refresh?

**Review by rkooo567 — APPROVED** [review]
Can we call it "last 5 minutes"? I think that's more clear + aligns with Grafana. Not a blocker to merge the PR though

Screen Shot 2022-10-07 at 11 05 20 AM

Screen Shot 2022-10-07 at 11 06 47 AM

**Comment by rkooo567** [comment]
Btw, also not a blocker, but we also need to have a refresh button as well? It looks like I still need to to ctrl + R to refresh (and then the interval is reset when I do that)

**Comment by alanwguo** [comment]
> Nice. How often does it refresh?

15 seconds.

**Comment by rkooo567** [comment]
No reason to wait for Windows build.

**Pull request merged**
