### PR TITLE
Fix py-spy error message for OSX

### PR DESCRIPTION
**Pull request by alanwguo**
## Related issue number
The previous instructions only worked on linux.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
running mac tests

**Comment by rkooo567** [comment]
@alanwguo can you run test_http_job_server locally? Looks like this failed in both mac & linux, but I don't see the failure from the master

**Comment by alanwguo** [comment]
> @alanwguo can you run test_http_job_server locally? Looks like this failed in both mac & linux, but I don't see the failure from the master

It's failing locally for me but I don't think this can be related to my PR. I only change an error message string in my PR.

**Comment by alanwguo** [comment]
ready to merge! No need to cherry-pick this, right?

**Comment by rkooo567** [comment]
yeah. cc @zhe-thoughts can we merge this PR? It is a simple error message fix.

**Review by zhe-thoughts — APPROVED** [review]
Yes this is low risk enough. Approved for merging into master

**Pull request merged**
