### PR TITLE
Revert "Revert "[client] Fix ray client object ref releasing in wrong context.""

### PR DESCRIPTION
**Pull request by fishbone**
Reverts ray-project/ray#22090

### CODE REVIEW

**Comment by iycheng** [comment]
From cython documentation:

> The counterpart to the __cinit__() method is the __dealloc__() method, which should perform the inverse of the __cinit__() method. Any C data that you explicitly allocated (e.g. via malloc) in your __cinit__() method should be freed in your __dealloc__() method.
> 
> You need to be careful what you do in a __dealloc__() method. By the time your __dealloc__() method is called, the object may already have been partially destroyed and may not be in a valid state as far as Python is concerned, so you should avoid invoking any Python operations which might touch the object. In particular, don’t call any other methods of the object or do anything which might cause the object to be resurrected. It’s best if you stick to just deallocating C data.
> 
> You don’t need to worry about deallocating Python attributes of your object, because that will be done for you by Cython after your __dealloc__() method returns.
> 
> When subclassing extension types, be aware that the __dealloc__() method of the superclass will always be called, even if it is overridden. This is in contrast to typical Python behavior where superclass methods will not be executed unless they are explicitly called by the subclass.
> 

It seems like we are not supposed to do any python call in `__dealloc__` and in cython < 3.0, `__del__` is not supported right now.

I'm changing the weakref things back to `try-except` for now. Hope it can work ..... at least when I check the buildkite log in the previous PR for this change it seems ok.

Besides, we actually have other places doing this, for example: https://github.com/ray-project/ray/blob/f064306de9c4b2fcc6056905bdbdb7e6e7802b6c/python/ray/includes/object_ref.pxi#L57-L70

I actually tried a lot to make it work, but it seems super hard. For example, make it as a wrapper class and have `__del__` defined in py-class. Unfortunately, none of them is working.

**Comment by iycheng** [comment]
I've run the following tests on buildkite for 2-3 times and no flaky for them. It seems working.
`linux://python/ray/tests:test_basic_5_client_mode` (GCS HA)
`windows://python/ray/tests:test_actor_client_mode`

**Review by ericl — APPROVED** [review]

**Review by mwtian — APPROVED** [review]

**Comment by iycheng** [comment]
It seems test_actor_client_mode has been flaky for a while on other platforms but somehow on windows, it's just failed less.

https://buildkite.com/ray-project/ray-builders-branch/builds/5741#beef7744-1632-4bbc-a812-302624df202e

**Comment by iycheng** [comment]
given that windows test has been flaky on other platform for a while and it's not that flaky after this fix, I'll merge this and monitor it for a while.

**Pull request merged**
