### PR TITLE
[docs] [serve] Deployment as a service on k8s docs

### PR DESCRIPTION
**Pull request by edoakes**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by bllchmbrs — APPROVED** [review]

**Comment by anabranch** [comment]
LGTM

**Comment by simon-mo** [comment]
Can you fix the indentation to use spaces consistently? Otherwise there are red bars in the diff.

**Comment by edoakes** [comment]
@simon-mo weird, not sure why that happened. Will try to fix.

**Comment by simon-mo** [comment]
When I'm trying it out I'm confused. Is this dependent on #8659? Because for now there isn't a way to configure services in example-full.yaml. If #8659 is merged, do I still need to add the ports according the the doc?

**Comment by edoakes** [comment]
@simon-mo sorry, I totally forgot to mention that it's dependent on that PR as well. Let's wait for that to get merged for you to try it out.

**Comment by simon-mo** [comment]
It worked! I tried it on an ubuntu microk8s and it worked. I have to `pip install requests` because it's not required by ray[serve] but that's pretty straightforward to fix and out of scope for current PR.

**Comment by simon-mo** [comment]
Re-running LINT before merging...

**Pull request merged**
