### PR TITLE
[Core] Add Running Count to instrumented_io_context

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

I add a running count to instrumented_io_context in this PR.

This is very helpful when debugging with blocked IO services.

Before:
```
Global stats: 887 total (1 active)
Queueing time: mean = 113.537 ms, max = 25.225 s, min = 4.301 us, total = 100.707 s
Execution time:  mean = 496.666 us, total = 440.543 ms
Handler stats:
        NodeResourceInfoGcsService.GetResources.reply_callback - 583 total (0 active), CPU time: mean = 45.699 us, total = 26.642 ms
        UNKNOWN - 161 total (0 active), CPU time: mean = 7.145 us, total = 1.150 ms
        RedisCallbackManager.DispatchCallback - 102 total (0 active), CPU time: mean = 213.547 us, total = 21.782 ms
        HeartbeatInfoGcsService.ReportHeartbeat.reply_callback - 22 total (1 active), CPU time: mean = 10.835 ms, total = 238.377 ms
```

After:
```
Global stats: 5 total (2 active)
Queueing time: mean = 9.250 us, max = 24.803 us, min = 8.519 us, total = 46.248 us
Execution time:  mean = 6.676 ms, total = 33.380 ms
Handler stats:
        UNKNOWN - 2 total (0 active), CPU time: mean = 42.078 us, total = 84.156 us
        NodeInfoGcsService.GetInternalConfig.reply_callback - 1 total (0 active), CPU time: mean = 33.296 ms, total = 33.296 ms
        FrozenNodeGcsService.GetAllFrozenNodes.reply_callback - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
        [1 RUNNING] NodeInfoGcsService.RegisterNode.reply_callback - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
```

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
I've thinking `(1 active)` means it is running. What are the differences here?

**Comment by lixin-wei** [comment]
> I've thinking `(1 active)` means it is running. What are the differences here?

No, `(1 active)` means there is totally 1 handler in the IO service, including running and pending.

**Comment by rkooo567** [comment]
Maybe considering to change the format this way?

```
        [1 RUNNING] NodeInfoGcsService.RegisterNode.reply_callback - 1 total (1 active), CPU time: mean = 0.000 s, total = 0.000 s
-> 
NodeInfoGcsService.RegisterNode.reply_callback - 1 total (1 active, 1 running), CPU time: mean = 0.000 s, total = 0.000 s
```

**Comment by lixin-wei** [comment]
@rkooo567 Yeah, this format is better. I've committed it, please have a look :)

**Review by rkooo567 — APPROVED** [review]
LGTM

**Comment by rkooo567** [comment]
Retrying rllib test. @clarkzinzow it'll be great if you can give us final pass

**Comment by rkooo567** [comment]
cc @lixin-wei can you handle the merge conflict? I will merge once that's done!

**Comment by lixin-wei** [comment]
@rkooo567 done :)

**Comment by lixin-wei** [comment]
BTW, I've looked quickly through this [PR](https://github.com/ray-project/ray/pull/17578) who was in conflict with my PR.

I think it's better not to use macros. It's hard to read and debug.

**Comment by lixin-wei** [comment]
never mind :) conflict fixed.

**Comment by rkooo567** [comment]
Let me merge it when it is ready...

**Review by ericl — APPROVED** [review]

**Pull request merged**
