### PR TITLE
[Cherrypick] triton doc

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

cherrypick https://github.com/ray-project/ray/pull/41923

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sihanwang41** [comment]
@akshay-anyscale

**Comment by edoakes** [comment]
2.9.1 is already released, no?

**Comment by akshay-anyscale** [comment]
Yes, this is to cherry-pick the docs onto the release branch since we want to put out a blog

**Review by edoakes — APPROVED** [review]

**Comment by sihanwang41** [comment]
@architkulkarni and @zhe-thoughts ^^ as Akashay mentioned we want to have the doc change into the release version for blog. is it okay for now to merge? Or we have to wait till the next release

**Comment by architkulkarni** [comment]
We can merge it. It should show up within an hour

**Pull request merged**
