### PR TITLE
[DATA] Enable `RAY_DATA_ENABLE_TENSOR_EXTENSION_CASTING` environment variable

### PR DESCRIPTION
**Pull request by jaidisido**
## Why are these changes needed?

Casting ndarray columns to tensor extension columns cannot be set via an os environment variable

## Related issue number

See https://github.com/aws/aws-sdk-pandas/issues/2358

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by denadai2** [comment]
is there a news about this PR?

**Review by scottjlee — APPROVED** [review]

**Comment by scottjlee** [comment]
the PR LGTM, but since it is pretty old, it looks like @jaidisido will need to resolve merge conflicts and merge in latest master. Or @denadai2 if you want to pick it up / create a new PR with the same changes, would be happy to help shepherd it

**Comment by jaidisido** [comment]
Given how small the change is, I recommend just a new PR. Happy to create one tomorrow unless you get to it before me @denadai2

**Comment by denadai2** [comment]
> Casting ndarray columns to tensor extension columns cannot be set via an os environment variable

#46344 done

**Comment by jaidisido** [comment]
Closing in favour of #46344

**Pull request closed without merging**
