### PR TITLE
Improve the default grafana time-series config for Ray metrics

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This improves both the default Ray grafana / dashboard metrics config:
- Add new logical scheduler metrics
- Improve stacking and display of hardware utilization metrics

graphs

### CODE REVIEW

**Comment by rkooo567** [comment]
For resources metrics, what do you think about making "USED" takes up the bottom part of the graph? (That feels more aligned with how current tasks graph work when tasks exists, the graph goes up).

**Comment by ericl** [comment]
Yeah, maybe the dotted line is the way to go.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Approved to move fast before the branch cut (it's okay the comment is addressed in a follow up for me)

**Review by rickyyx — APPROVED** [review]
The task state chart looks a bit weird - seems it's half stacked and half line charted? 

<div><br/>via <a href="https://giphy.com/gifs/share-very-discover-10uEX5kfeodYgo">GIPHY</a></div>

**Comment by ericl** [comment]
Yeah, I reverted the task chart to be a normal stacked chart. I'll have to revisit this once we land the dead worker metric cleanup, so that we keep the max number of finished tasks over time, but that should be an easy change.

**Pull request merged**
