### PR TITLE
[AIR] [Release] Reduce batch size for batch prediction benchmarks

### LINKED ISSUE #29163: [release][CI] air_benchmark_torch_batch_prediction_gpu_1x1_20gb
### What happened + What you expected to happen

Build failure - https://buildkite.com/ray-project/release-tests-branch/builds/1095#0183af7e-97cf-46ad-a06d-fb6cf8b4e73a

Cluster - https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_jJvecMVZZ12NDKwb1B5bZQ6w

```
RuntimeError: CUDA out of memory. Tried to allocate 12.19 GiB (GPU 0; 7.44 GiB total capacity; 2.33 GiB already allocated; 4.39 GiB free; 2.35 GiB reserved in total by PyTorch)
```

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by amogkam**
Signed-off-by: Amog Kamsetty <amogkamsetty@yahoo.com>

Now that we have block coalescing enabled, we need to use a smaller batch size than 4096 so that the batch can fit in GRAM.

Closes https://github.com/ray-project/ray/issues/29163

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jiaodong — APPROVED** [review]

**Comment by rickyyx** [comment]
Should we cherry pick this one instead?

**Comment by amogkam** [comment]
Yes we should cherry pick @rickyyx, but am waiting for the test to pass before merging

**Comment by rickyyx** [comment]
> Yes we should cherry pick @rickyyx, but am waiting for the test to pass before merging

Gotcha!

**Comment by amogkam** [comment]
@rickyyx can you approve and merge please https://github.com/ray-project/ray/pull/29331

**Pull request merged**
