### PR TITLE
[Overview] Add Recent Serve Applications Card and Refactor the Overview Page 

### PR DESCRIPTION
**Pull request by chaowanggg**
Expected Results:

1. Create a Recent Serve Applications card: We have a Serve page with a table containing information about the Application name, Import Path, and Status. We will create a card based on this information and the styles of the Recent Jobs Card.

image

2. Reorder the cards according to the following picture:

image_720

- Move the Node Count card to a separate row. The Node Count card is already in the Overview Page.
- Copy the Ray Status cards to the Overview Page. The Ray Status cards are currently on the Job Detail page.

3. Create a row for the Accordion named "Autoscaler" based on the picture above. This row will control the visibility of the second row of cards (Node Count, Node Status, and Resource Status).

- By default, the Autoscaler row will be folded and show nothing.
- When clicked, it will expand and show the three cards.
- Double-clicking will fold it again and show nothing.

4. [Code Quality] Abstract a common card for reuse in the Recent Serve Applications and Recent Jobs Cards.

5. API change for getting another field import path

Title changed in Job Detail page
image

Add Import path as metadata in Serve Detail page
image

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by alanwguo** [comment]
> 1. Create a Recent Serve Applications card: We have a Serve page with a table containing information about the Application name, Route prefix, and Status. We will create a card based on this information and the styles of the Recent Jobs Card.

For 1, instead of route_prefix, It seems like we should show the import path. I'm not sure if that's easily accessible from the API right now. @zcin, is this something we can put as a field in the serve_applications API? I'm not sure if it'll always exist. 

@chaowanggg , if we do add this field to the API, can you also show this field in the serve page as one of the columns and add it to the metadata for the serve application detail page?

> 3. Create a row for the Accordion named "Autoscaler" based on the picture above. This row will control the visibility of the second row of cards (Node Count, Node Status, and Resource Status).
By default, the Autoscaler row will be folded and show nothing.
When clicked, it will expand and show the three cards.
Double-clicking will fold it again and show nothing.

This sounds good except by default, it should be expanded and not folded.

**Comment by zcin** [comment]
> For 1, instead of route_prefix, It seems like we should show the import path. I'm not sure if that's easily accessible from the API right now. @zcin, is this something we can put as a field in the serve_applications API? I'm not sure if it'll always exist.

Import path is available in the current serve rest api, in the field `deployed_app_config`. The value of this field should always contain the `import_path` for the application.

Will "recent serve applications" be information that's cached in the frontend? We currently don't store info on deleted applications.

**Comment by alanwguo** [comment]
Instead of "recent serve applications" we should just call it "Serve applications"

**Comment by chaowanggg** [comment]
@alanwguo Could we use route_perfix(/test1 in the picture below) as the path to show if import_path is empty? 

image

import_path will be returned from applications -> deployed_app_config -> import_path and there is a possibility that deployed_app_config is null.

cc @zcin

**Comment by alanwguo** [comment]
> @alanwguo Could we use route_perfix(/test1 in the picture below) as the path to show if import_path is empty?
> 
> image
> 
> import_path will be returned from applications -> deployed_app_config -> import_path and there is a possibility that deployed_app_config is null.
> 
> cc @zcin

@zcin says in a previous comment that it can't be null. Is that not the latest thinking?

**Comment by chaowanggg** [comment]
> 

No, I found the deployed_app_config is null when running the sample example provided from Ray docs.

Here is the full response when running the [sample example](https://docs.ray.io/en/latest/serve/index.html#quickstart)

/*
{
    "": {
        "name": "",
        "route_prefix": "/test",
        "docs_path": null,
        "status": "RUNNING",
        "message": "",
        "last_deployed_time_s": 1682029771.0748637,
        "deployed_app_config": null,
        "deployments": {
            "MyModelDeployment": {
                "name": "MyModelDeployment",
                "status": "HEALTHY",
                "message": "",
                "deployment_config": {
                    "name": "MyModelDeployment",
                    "num_replicas": 1,
                    "max_concurrent_queries": 100,
                    "user_config": null,
                    "autoscaling_config": null,
                    "graceful_shutdown_wait_loop_s": 2,
                    "graceful_shutdown_timeout_s": 20,
                    "health_check_period_s": 10,
                    "health_check_timeout_s": 30,
                    "ray_actor_options": {
                        "runtime_env": {},
                        "num_cpus": 1
                    },
                    "is_driver_deployment": false
                },
                "replicas": [
                    {
                        "replica_id": "MyModelDeployment#oJRaQg",
                        "state": "RUNNING",
                        "pid": 364224,
                        "actor_name": "SERVE_REPLICA::MyModelDeployment#oJRaQg",
                        "actor_id": "b8c9082697cd69c16109eeb804000000",
                        "node_id": "3434841e491012452165c643fea4919d80d078554059d3e008d51713",
                        "node_ip": "172.31.5.171",
                        "start_time_s": 1682029903.403788
                    }
                ]
            }
        }
    }
}

*/

**Comment by zcin** [comment]
Yes my bad I forgot about applications deployed through the Python API. If deployed through python API we currently don't store info on the import path anywhere.

**Comment by chaowanggg** [comment]
> > @alanwguo Could we use route_perfix(/test1 in the picture below) as the path to show if import_path is empty?
> > image
> > import_path will be returned from applications -> deployed_app_config -> import_path and there is a possibility that deployed_app_config is null.
> > cc @zcin
> 
> @zcin says in a previous comment that it can't be null. Is that not the latest thinking?
Thanks @zcin


cc @alanwguo I will also provide a default display when deployed_app_config is null to fix the existing PR

**Comment by alanwguo** [comment]
Okay, showing route_prefix seems like a reasonable work-around.

**Comment by alanwguo** [comment]
Can we also put import path as a metadata item in the Serve application detail page since we show it prominently in the Serve Applications card.

**Comment by chaowanggg** [comment]
> Can we also put import path as a metadata item in the Serve application detail page since we show it prominently in the Serve Applications card?

Sounds good. I will do it

Is this your expected result? 

image

The url for the above picture is http://localhost:4001/#/serve/applications/default

**Comment by chaowanggg** [comment]
Sure, I will do it in this PR

Is this your expected result? The url of the below picture is http://localhost:4001/#/serve/applications/default

image

**Comment by scottsun94** [comment]
Can we use `-` instead if people submit them via python api? My concern is that it's confusing to sometimes see `import_path` and sometimes `route_prefix`?

**Comment by scottsun94** [comment]
Do we want to include the `import_path` in the serve app table?
Screen Shot 2023-05-02 at 1 54 43 PM

**Comment by chaowanggg** [comment]
Discussed offline with @scottsun94

1. Show import_path in ServeCard
2. When import_path is empty, show "-" as default display

> Do we want to include the `import_path` in the serve app table? Screen Shot 2023-05-02 at 1 54 43 PM

**Comment by chaowanggg** [comment]
> import_path

How about show it in metadata section?

image

**Comment by chaowanggg** [comment]
> Do we want to include the `import_path` in the serve app table? Screen Shot 2023-05-02 at 1 54 43 PM


How about show it in metadata section?

image

**Comment by scottsun94** [comment]
> > Do we want to include the `import_path` in the serve app table? Screen Shot 2023-05-02 at 1 54 43 PM
> 
> How about show it in metadata section?
> 
> image

SG

**Pull request closed without merging**
