### PR TITLE
[Event] Add some error level events

### LINKED ISSUE #16249: [Dashboard][event] Basic event points.
- Some event points to expose exception, crash message, and `RAY_CHECK` failed.
- Event point will generate event logs.
- The event points will be located in C++、Java and Python.

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
- Add some event points to expose the events of process exited or killed.

- worker failure
image
- driver failure
image
- agent exit
image
- node removed
image

- issue https://github.com/ray-project/ray/issues/16249

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/18118#issuecomment-907405799 and failing cpp tests

**Comment by SongGuyang** [comment]
> I think if we only do that for custom field, that’s fine? We shouldn’t include default labels in ray log though

Can I implement this in an independent PR after current PR merged?

**Comment by rkooo567** [comment]
That's fine. Let's just make sure things are not slipped. So we need to

- Turn on by default
- Use RAY_LOG within RAY_EVENT instead of duplicating them (only with custom fields)
- Allow to set severity (WARNING by default)

**Comment by rkooo567** [comment]
Maybe although the WARNING is by default, we still probably want to emit INFO level logs (but not events)

**Comment by SongGuyang** [comment]
@rkooo567 Thanks. So, can we merge current PR and https://github.com/ray-project/ray/pull/18112 one by one today?

**Comment by rkooo567** [comment]
Yeah I will merge this once the test passes first. For the other one, I’d like to run release tests before merging it (and we should merge the latest master there after we merge this pr)

**Comment by rkooo567** [comment]
Okay. Let's go to turning this on by default..

**Pull request merged**
