### PR TITLE
[ci/release] Terminate clusters on job cancellation

### LINKED ISSUE #25400: [ci/release] Clusters should terminate when jobs are canceled
### Description

Currently hitting "Cancel" on Buildkite will send an interrupt which is not caught. Thus, started clusters remain running on Anyscale. Instead we should terminate them before stopping the script.

### Use case

_No response_

### PR DESCRIPTION
**Pull request by krfricke**
Signed-off-by: Kai Fricke <kai@anyscale.com>

## Why are these changes needed?

When a job is canceled on buildkite, the cluster is currently not terminated. This can lead to leaked clusters, especially for long running test. This PR adds functionality to detect SIGTERM issued from buildkite on cancellation to terminate a cluster.

## Related issue number

Closes #25400

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Does not work at the moment...

**Comment by krfricke** [comment]
The problem seems to be with the buildkite docker plugin, which does not propagate the termination signal...

**Comment by rkooo567** [comment]
please remove a tag when it is ready

**Comment by krfricke** [comment]
Keep open...

**Comment by krfricke** [comment]
Keep open

**Comment by krfricke** [comment]
Still relevant, keep open

**Comment by Yard1** [comment]
@krfricke I made my changes. It appears that we need to increase the grace period on buildkite agents in order for the request to be sent completely.

**Comment by krfricke** [comment]
@Yard1 can you merge the latest changes into this PR? I'll update the grace period to 15 seconds later.

**Review by krfricke — COMMENTED** [review]
Awesome! Would stamp if I could

**Review by Yard1 — APPROVED** [review]

**Pull request merged**
