### PR TITLE
[Data] Allow automatic handling of string features as byte features during TFRecord serialization

### PR DESCRIPTION
**Pull request by EdwardCuiPeacock**
[Sorry, previous PR was kind of messed up...]

## Why are these changes needed?

I am attempting to use `ray.data.write_tfrecords` to convert my features into TFRecords. Since some of my features are string features, the following error is thrown:

```
ValueError: Value is of type string, which we cannot convert to a supported tf.train.Feature storage type (bytes, float, or int).
```

Naturally, TFRecords serializes string features as bytes feature automatically (as typically done in Tensorflow and Tensorflow-extended (TFX); see for example: https://github.com/tensorflow/tfx/blob/fd070288ffa5dcb28204810d2bed261c7e1df201/tfx/components/example_gen/csv_example_gen/executor.py#L67). Making the TFRecord writer automatically treat strings as bytes would help serialize string features correctly, avoiding the hassle of creating additional map functions to convert string features into bytes.

When reading TFRecords, however, we should still keep the bytes features as bytes, as the program does not necessarily know a byte object represents a string. In [this example](https://www.tensorflow.org/tutorials/load_data/tfrecord#tftrainexample) provided by Tensorflow, tensors are serialized into bytes and stored in tfrecords, using `tf.io.serialize_tensor`.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
Thanks for the contribution @EdwardCuiPeacock! Do you think you can add a small test for this in `test_tfrecords.py`? We can add a case for string in `test_read_tfrecords`

Also cc @scottjlee for review

**Comment by EdwardCuiPeacock** [comment]
Hi, @amogkam . I added the new unit tests. To install the test_requirement.txt though, I had to change `numba` from version 0.56.4 to 0.57.1 temporarily, since 0.56.4 does not have a Python 3.11 wheel built (maybe we should upgrade that at some point). But all tests in `test_tfrecords.py` should be passing now.

**Review by scottjlee — APPROVED** [review]
Thanks for adding this feature!

**Comment by amogkam** [comment]
Thanks for the contribution @EdwardCuiPeacock! It's been merged.

**Pull request merged**
