### PR TITLE
[nightly] Put many nodes actor test back

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
There are two issues fixed in this PR:
- make sure wait for session count alive node
- upgrade the machine to match what's tested in oss ray.

## Related issue number
https://github.com/ray-project/ray/issues/19084

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
I'll post test result

**Review by rkooo567 — APPROVED** [review]
Mostly minor questions!

**Comment by iycheng** [comment]
Btw, this is not the end of the issue (https://github.com/ray-project/ray/issues/19084)
Since I'm working on GCS HA Broadcasting, I'll continue investigating this.

**Comment by iycheng** [comment]
Two issues created:
https://github.com/ray-project/ray/issues/19370
https://github.com/ray-project/ray/issues/19369

**Pull request merged**
