### PR TITLE
[k8s][Bug] Bump memory requests in Helm chart

### LINKED ISSUE #23322: [k8s][Bug] Healthchecks don't catch ray-operator failing to start head
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Monitoring & Debugging

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

Booted a simple ray cluster in a kOps k8s cluster (v1.22) using the Ray helm chart in namespace `ray`.

Got a `GCS has started but no raylets have registered yet.` error when trying to `ray.init(address="ray://ray-ray-head.ray.svc.cluster.local:10001")`

Viewed `ray-operator` logs by bashing into the pod, found it was repeatedly silently failing to run `kubectl -n ray exec -it ray-ray-head-type-wfdp6 -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"GPU":0,"memory":375809638}'"'"';ulimit -n 65536; ray start --head --port=6379 --no-monitor --dashboard-host 0.0.0.0)'`

When I manually ran that command, I got a verbose error and [the fix](https://github.com/ray-project/ray/pull/22799/commits/3252af5aa505ec1a55955a4b6453d611fddeeaec) became clear: the default 512Mi memory request is too small

This was a quite obscure error to debug for me (had to manually run the command to get the error message out), it would be cool if a readinessProbe/livenessProbe fails in k8s.

### Versions / Dependencies

Ray v1.11.0

### Reproduction script

#22799 and the yaml in https://github.com/ray-project/kuberay/issues/200

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ddelange**
## Why are these changes needed?

`ray-operator` remains healthy although it is unable to create `head`. This error is swallowed (had to manually bash into the pod and re-run to get this traceback):
```pytb
(base) ray@ray-operator-b4cdbf848-fcmmk:~$ kubectl -n aa-ray exec -it aa-ray-ray-head-type-wfdp6 -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_OVERRIDE_RESOURCES='"'"'{"CPU":1,"GPU":0,"memory":375809638}'"'"';ulimit -n 65536; ray start --head --port=6379 --no-monitor --dashboard-host 0.0.0.0)'
Local node IP: 100.114.232.202
2022-03-17 04:33:35,018 ERROR services.py:1421 -- Failed to start the dashboard: Failed to bind to 0.0.0.0:8265 because it's already occupied. You can use `ray start --dashboard-port ...` or `ray.init(dashboard_port=...)` to select a different port.
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1958, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 622, in start
    ray_params, head=True, shutdown_at_exit=block, spawn_reaper=block)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 274, in __init__
    self.start_ray_processes()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 1117, in start_ray_processes
    huge_pages=self._ray_params.huge_pages
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 1945, in determine_plasma_store_config
    ray_constants.OBJECT_STORE_MINIMUM_MEMORY_BYTES))
ValueError: Attempting to cap object store memory usage at 52442726 bytes, but the minimum allowed is 78643200 bytes.
command terminated with exit code 1
```

## Related issue number

Closes #23322 (only hotfix)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ddelange** [comment]
wonder why [`test_helm`](https://github.com/ray-project/ray/blob/7f1bacc7dc9caf6d0ec042e39499bbf1d9a7d065/python/ray/tests/kubernetes_e2e/test_helm.py#L15) didn't fail btw.. 🤔

**Comment by ddelange** [comment]
CI [raises](https://buildkite.com/ray-project/ray-builders-pr/builds/28245#96b6e7bd-eb27-4fb5-a0be-fd645d0c66d5/2211-3274) an error on Mac:

```pytb
>>> from tensorflow_probability.python.bijectors.glow import Glow
...
AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'
```

Which I can't reproduce on my own Mac with the exact same version pins as from the pip install logs of CI. Keras 2.6.0 is fine... Consensus on this error seems to be a re-install, so I'm attempting to trigger a cache refresh of Mac CI.

**Comment by ddelange** [comment]
@amogkam could you re-run the one test that only fails on Windows?

**Comment by amogkam** [comment]
The tests all look good- will defer to @DmitriGekhtman for review!

**Comment by DmitriGekhtman** [comment]
So, funny thing, I saw OOM errors while running tests and increased the memory limits in this PR https://github.com/ray-project/ray/pull/23540/files

Thanks for the fix and apologies for our delay in getting to the review.

For what it's worth, I think I read somewhere (perhaps in the Helm docs themselves) that it's bad form to provide defaults for resource requests and limits -- users should consider the needs of their application and set those themselves.

So perhaps the best move would be to remove the memory default entirely.

**Comment by ddelange** [comment]
> For what it's worth, I think I read somewhere (perhaps in the Helm docs themselves) that it's bad form to provide defaults for resource requests and limits -- users should consider the needs of their application and set those themselves.

Probably from the [output](https://github.com/twuni/docker-registry.helm/blob/f1583238750b54247c32b3d7cc1e6b72c0dbdc8c/values.yaml#L55) of `helm create` :)

**Pull request closed without merging**
