### PR TITLE
Fix redis crash when duplicate messages are appended to log.

### PR DESCRIPTION
**Pull request by pcmoritz**
## Related issue number

https://github.com/ray-project/ray/issues/3287

### CODE REVIEW

**Comment by robertnishihara** [comment]
I'm having a hard time understanding what this PR does. Of course, the ideal thing is to use a LIST instead of a ZSET, but I'm guessing that's still not supported by Redis Modules.

If we have to work with ZSETs, the natural thing to do seems to be to log a scary warning and drop the extra message (it is a duplicate after all...).

Here you're creating a new key, which is the old key concatenated with the index that failed to write, correct? Just to keep it around for debugging purposes?

I feel like this could trigger some problems with the pubsub stuff because the subscribers may try to parse the key as an ID and it may have the wrong length or something like that.

**Comment by pcmoritz** [comment]
The pubsub still uses the old key; the new key is just to (a) make sure the log is the right length after the append and (b) the message is kept around for debugging purposes.

**Comment by robertnishihara** [comment]
I see, could you add a test that hits this code path?

I think it should be doable if you do something like what is done in 

```python
import ray

ray.init(num_cpus=0)

driver_id = ray.ray_constants.NIL_JOB_ID.id()
error_data = ray.gcs_utils.construct_error_message(driver_id, "test", "message", 0)

# Push the same message to the GCS twice (they are the same because we
# do not include a timestamp).

r = ray.worker.global_worker.redis_client

r.execute_command(
    "RAY.TABLE_APPEND", ray.gcs_utils.TablePrefix.ERROR_INFO,
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)

r.execute_command(
    "RAY.TABLE_APPEND", ray.gcs_utils.TablePrefix.ERROR_INFO,
    ray.gcs_utils.TablePubsub.ERROR_INFO, driver_id, error_data)

while True:
    errors = ray.error_info()
    if len(errors) == 2 and all("message" in error["message"] for error in errors):
        break
```

or something like that..

The `while` statement needs to be double checked..

**Review by robertnishihara — CHANGES_REQUESTED** [review]
See comment.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
