### PR TITLE
Run merge builds on forks

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Runs merge builds on forks.  
Specifically, adds a **new** `(merge build)` job whose behavior differs in the following manner:

- On forked repositories:  
  Runs `git pull` (which is roughly `git fetch && git merge`) to merge in the latest `master`.  
  If this step fails, the entire job fails, as this indicates a merge would be unsuccessful.

- On the main repository:  
  Bypasses the rest of the workflow and prints a message containing the URL of the fork builds.  
  Then the job immediately succeeds.

Existing jobs remain unaffected.

**Possible future bug:**

This doesn't update environment variables like `GITHUB_SHA` or the GitHub event file on the filesystem, which may affect CI steps (like linters) that inspect diffs.  
Currently, we don't have these on GitHub Actions, so this isn't an issue.
However, this should be kept in mind if we add such steps later on.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by robertnishihara** [comment]
@mehrdadn can you provide more documentation for this? I'm not really sure what this is doing.

**Comment by mehrdadn** [comment]
@robertnishihara I added some explanations, let me know if anything is confusing.

**Comment by simon-mo** [comment]
Can you say more on what problem is it PR solving?

**Comment by mehrdadn** [comment]
@simon-mo It's useful when GitHub Actions on the main repo stops working (or gets clogged). It lets people refer to the fork's merge build to tell whether a merge is likely to be successful.

**Comment by simon-mo** [comment]
Cool. So to clarify: Travis already perform merge build but GHA doesn't. And this is adding a build to GHA to merge master? If that's the case, why don't we merge master in all GHA build?

**Comment by simon-mo** [comment]
Additionally, how does this interact with new ci remote watcher/canceller we just merged?

**Comment by mehrdadn** [comment]
@simon-mo GHA and Travis both perform merge builds when processing pull requests, but not pushes. But the runners for the main repo can get clogged or break down like they did the past 1-2 days, when the forks can keep on running. This performs a merge build on forks too.

You don't want to make *all* pushes perform merge builds because people need to be able to test their changes in isolation, or they'll get unrelated errors that might prevent the job from running. Merging only makes sense when they believe their code is ready to merge.

This should work just fine with the watcher we just merged. I don't see any potential for interference.

**Comment by simon-mo** [comment]
Closing as this might not be widely applicable and warrant a separate CI job. We might want to reconsider re-open this PR if CI get clogged.

**Pull request closed without merging**
