### PR TITLE
[RLLib] (P1 regression) Fixing view requirements in compute actions

### LINKED ISSUE #14385: [RLlib] `Policy.compute_actions_from_input_dict` does not properly track accessed fields for the Policy's view-requirements.
`Policy.compute_actions_from_input_dict` does not properly track accessed fields for the Policy's view-requirements.

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

To reproduce:
```
import torch
import numpy as np

from ray.rllib.agents.ppo import PPOTorchPolicy, PPOTrainer
from ray.rllib.policy.sample_batch import SampleBatch
from ray.rllib.utils.torch_ops import convert_to_non_torch_type, \
    convert_to_torch_tensor


class MixIn:
    def compute_actions_from_input_dict(self, input_dict, explore=None, timestep=None, episodes=None, **kwargs):

        #if not self.config['env_config'].get('invalid_action_masking', False):
        #    raise RuntimeError('invalid_action_masking must be set to True in env_config to use this mixin')

        infos = input_dict[SampleBatch.INFOS]

        explore = explore if explore is not None else self.config["explore"]
        timestep = timestep if timestep is not None else self.global_timestep

        with torch.no_grad():
            # Pass lazy (torch) tensor dict to Model as `input_dict`.
            input_dict = self._lazy_tensor_dict(input_dict)
            # Pack internal state inputs into (separate) list.
            state_batches = [
                input_dict[k] for k in input_dict.keys() if "state_in" in k[:8]
            ]
            # Calculate RNN sequence lengths.
            seq_lens = np.array([1] * len(input_dict["obs"])) \
                if state_batches else None

            # Call the exploration before_compute_actions hook.
            self.exploration.before_compute_actions(
                explore=explore, timestep=timestep)

            dist_inputs, state_out = self.model(input_dict, state_batches,
                                                seq_lens)
            # Extract the tree from the info batch
            batch_size = input_dict["obs"].shape[0]
            return convert_to_non_torch_type((
                torch.zeros((batch_size,), dtype=torch.int32),
                state_out,
                {
                    "vf_preds": torch.zeros((batch_size, ), dtype=torch.float32),
                    "action_dist_inputs": dist_inputs,
                    "action_logp": torch.ones((batch_size,), dtype=torch.float32)
                }
            ))


import ray
ray.init(local_mode=True)

MyPolicy = PPOTorchPolicy.with_updates(mixins=[MixIn])
MyTrainer = PPOTrainer.with_updates(default_policy=MyPolicy, get_policy_class=lambda c: MyPolicy)

trainer = MyTrainer(env="CartPole-v0", config={
    "framework": "torch",
    "num_workers": 0,
})

for _ in range(20):
    print(trainer.train())
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by Bam4d**
## Why are these changes needed?

@sven1977 This is a regression of a previous bug I raised. Griddly needs this to work!

The view requirments for inference do not just include the model's view requirements. 

`get_inference_input_dict` needs to return the input dict with all of the view requirements for the *whole policy* rather than just the model, otherwise all the `used_for_compute_actions` get ignored.

## Related issue number

This bug is a regression of this fix

Regression from this fix: #14386
Closes #14385 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by duburcqa** [comment]
@sven1977 Do you think this can be merged before releasing 1.4.0 ?

**Comment by Bam4d** [comment]
> @sven1977 Do you think this can be merged before releasing 1.4.0 ?

The previous fix (which then broke) wasn't merged in 1.3.0, I'd really like to be able to tell griddly users to download a stable release rather than the unstable wheels to get anything to work.

**Comment by Bam4d** [comment]
@sven1977 @duburcqa Super bummed this didn't make it into 1.4.0. Whats the hold-up with it? Is there anything I can do to get this through?

**Comment by duburcqa** [comment]
I agree with, it is quite a pity and very annoying bug. It tools me way too long to understand why my code was not working, and there is no clean way to get around it apart from patch ray.rllib.

**Comment by sven1977** [comment]
Hey @Bam4d , @duburcqa , I'm really sorry for the hold-up. However, please be aware that we have limited resources to get these fixes done. Also, if you have noticed, your PR has some failing test cases, which someone has to look into (and debug) before we can merge this! If all tests were pass, we could have merged this some time ago.

**Comment by sven1977** [comment]
Ok, I looked into this again. Thanks for the fix - again :)
The problem is that some policies in RLlib (e.g. QMIX) are based right off the base `Policy` class, so they "miss" the code, where we unify the policy's and the model's view requirements. I think this could be fixed by doing this here:

```
        # vv Do merge here if not already done.  vv
        view_reqs = policy.model.view_requirements if \
            getattr(policy, "model", None) else policy.view_requirements

        input_dict = {}
        for view_col, view_req in view_reqs.items():
```

**Comment by sven1977** [comment]
All failing tests passing locally now, just waiting for CI ...

**Review by sven1977 — APPROVED** [review]
Thanks for raising this issue and for the suggested fix @Bam4d .
Had to make 2 small adjustments for this to also work with legacy algos (e.g. QMIX). Looks all good now.

**Comment by duburcqa** [comment]
@sven1977 Amazing ! Thank you for fixing and merging this PR :+1:

**Pull request merged**
