### PR TITLE
Fix race condition in asyncRedisContext

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

We were seeing some issues in the core worker where redis callbacks were being called after they had been deleted (see issue below).

Verified that this fixes the issue by running the GCS actor state tests repeatedly, which previously reproduced the issue 100% of the time.

## Related issue number

#6169

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]

**Comment by micafan** [comment]
Thanks for fix this.
But it might cause deadlock if gcs request is executed inside the read callback, right?

**Comment by micafan** [comment]
Thanks for the fix.
But it might cause deadlock if a gcs request is executed inside the read callback, right?
Actually I already fix it in this [PR](https://github.com/ray-project/ray/pull/5946/files). Please try it.

**Comment by micafan** [comment]
Let me explain how the deadlock happen:

**Comment by micafan** [comment]
Let me explain how the deadlock happen.
We lock when executing  `redisAsyncHandleRead`, the lock here is the first lock.
In `redisAsyncHandleRead`, the callback which  registered by user may be executed, and if user submit any `redis command` via `GCS Client` in the callback, it will lock again!

**Comment by micafan** [comment]
Although we can use read mutex and write mutex to avoid the deadlock. But it's better to avoid the read lock at all (e.g.: use boost dispatch).

**Comment by micafan** [comment]
Recursive locks are not recommended because it sacrifices performance and difficult to debug.

**Comment by edoakes** [comment]
Yes, agreed - this was more of an experiment. I took at a look at your PR and it seems to work but it adds some performance overhead to post to the event loop for every call and is also a bit weird to leave `redis_async_context.cc` only partially thread-safe.

Another option is to lock the mutex where I have it and then unlock it before we perform the callback. Are there any clear issues with that (aside from it being a bit ugly)?

**Comment by edoakes** [comment]
Actually, we took a look at this and it gets pretty hairy. How about we go with your PR's solution to serialize reads and writes on the event loop and then also remove the logic in `redis_async_context.cc` that attempts to make it thread safe? We need to include this fix in the upcoming release so let me know if you'd like me to take over the other PR. Moving the discussion there.

**Pull request closed without merging**
