### PR TITLE
[core][state] do not prepend task_id for non list tasks CLI usage

### PR DESCRIPTION
**Pull request by ProjectsByJackHe**
## Why are these changes needed?

In a previous PR: https://github.com/ray-project/ray/pull/32353, we added a feature where "task id" gets put at the top when running "ray list" commands. 

The code that does the prepending works for list, but it shouldn't be used for "get" commands. In fact, that causes a runtime error. This is a fix to address the sloppy PR (from me) before haha. 

The added unit test should now catch a case in ray_get() when we introduce runtime errors due to bad input parsing. 
Screen Shot 2023-03-19 at 9 56 43 PM

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rickyyx — APPROVED** [review]
What's the error? Do you have a test that could manually (or better as unit testing) surface it?

**Comment by rickyyx** [comment]
I see - so I think it's because we didn't test CLI output that thoroughly in the unit testing. 

Yeah, if it's not too hard, I think you could follow some of the CLI testing in `test_state_api.py` which should already have test cases covered the CLI usage.

**Comment by ProjectsByJackHe** [comment]
> I see - so I think it's because we didn't test CLI output that thoroughly in the unit testing.
> 
> Yeah, if it's not too hard, I think you could follow some of the CLI testing in `test_state_api.py` which should already have test cases covered the CLI usage.

Thanks for letting me know! I will learn about this, and improve with future PRs

**Comment by rickyyx** [comment]
@ProjectsByJackHe Do you plan to add test in this PR? Or maybe add some manual testing that this works with 1 task/multiple tasks results?

**Comment by ProjectsByJackHe** [comment]
> @ProjectsByJackHe Do you plan to add test in this PR? Or maybe add some manual testing that this works with 1 task/multiple tasks results?

unit test added!

**Review by rickyyx — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/schittscreek/">Schitt&#x27;s Creek</a> on <a href="https://giphy.com/gifs/schittscreek-schitts-creek-607-fVtcfEXWQJQUbsF1sH">GIPHY</a></div>

**Comment by rickyyx** [comment]
Waiting for test signals.

**Comment by ProjectsByJackHe** [comment]
Closing this PR cause I messed up playing around with Git, and this PR is so out of date passing the Github unit tests are a major hurdle. New PR opened here: https://github.com/ray-project/ray/pull/33501

**Pull request closed without merging**
