### PR TITLE
Re-enabling tests from test_basic

### PR DESCRIPTION
**Pull request by czgdp1807**
## Related issue number

#https://github.com/ray-project/ray/issues/19177

Quoting https://github.com/ray-project/ray/issues/19177#issuecomment-943261339 here,

The following tests fail when not skipped,

```python
=================================== short test summary info ====================================
FAILED python\ray\tests\test_basic.py::test_user_setup_function - subprocess.CalledProcessErro...
FAILED python\ray\tests\test_basic.py::test_disable_cuda_devices - subprocess.CalledProcessErr...
FAILED python\ray\tests\test_basic.py::test_wait_timing - assert (1634209333.6099107 - 1634209...

Results (395.22s):
      36 passed
       3 failed
         - ray\tests/test_basic.py:197 test_user_setup_function
         - ray\tests/test_basic.py:220 test_disable_cuda_devices
         - ray\tests/test_basic.py:265 test_wait_timing
```

```python
=================================== short test summary info ====================================
FAILED python\ray\tests\test_basic_3.py::test_fair_queueing - AssertionError: 23

Results (198.33s):
       1 failed
         - ray\tests/test_basic_3.py:169 test_fair_queueing
```

The following test passed when not skipped. Opening a PR to verify that.

```python
def test_oversized_function(ray_start_shared_local_modes)
```

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by czgdp1807** [comment]
It seems like on Github actions CI, `test_oversized_function` fails due to memory error.

```bash
    def test_oversized_function(ray_start_shared_local_modes):
1225
>       bar = np.zeros(100 * 1024 * 1024)
1226
E       numpy.core._exceptions._ArrayMemoryError: Unable to allocate 800. MiB for an array with shape (104857600,) and data type float64
```

This doesn't happen locally on my Windows system. Is there any upper cap on the memory in Github actions CI?

**Comment by czgdp1807** [comment]
Regarding, `test_wait_timing`, I observed that to measure elapsed time we use `time.time()` (see below). What was the reason to choose and time.time() and not the alternatives listed below.

```python
start = time.time()
ready, not_ready = ray.wait([future], timeout=0.2)
assert 0.2 < time.time() - start < 0.3
```

The variations in the output of `time.time` are very high and hence `test_wait_timing` becomes flaky because sometimes the execution time is between 0.2 and 0.3 and sometimes don't. The alternatives,

1. `time.perf_counter` gives stable results (~0.39) with some minor variations from third decimal place onwards on Windows.
2. `timeit.Timer.repeat` gives interesting results. When `timeit.Timer(functools.partial(ray.wait, [future], timeour=0.2)).repeat(1, 1)` is called then it also gives `~0.39` with some minor variations. However, when `timeit.Timer(functools.partial(ray.wait, [future], timeour=0.2)).repeat(2, 1)` is called then the second entry in its output is `~0.2` almost matching the `timeout=0.2`. 

The higher values of time on Windows might be due to the overhead posed by the OS. Are we interested in investigating that part or the concern is the flaky behaviour?

**Comment by scv119** [comment]
@czgdp1807 thanks for identify those issues. I'd suggest you to

1. try to reduce the memory allocation size if possible for first issue; 
2. and loosen the time for the second test on windows

**Comment by czgdp1807** [comment]
Hi. Any thoughts on whether we should keep using `time.time()` or one of the alternatives I suggested above? IMO, `timer.Time.repeat` is a good one but let me know what you think.

**Review by scv119 — APPROVED** [review]
Thanks for fixing the tests!

**Pull request merged**
