### PR TITLE
Fix parquet missing error and improve arrow commit id changing

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
1. Find the root cause of "not finding parquet package" ([Issue1953](https://github.com/ray-project/ray/issues/1953)). There are missing Macros in calling `setup.py build`. We need to add `PARQUET_HOME=$TP_DIR/pkg/arrow/cpp/build/cpp-install   PYARROW_WITH_PARQUET=1` as the same as `setup.py build_ext`. Otherwise, sometimes, CMAK prints "Found the Parquet library: parquet" instead of the right message "Found the Parquet library: XXXX/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib/libparquet.dylib" and then CMAKE raises an error of not finding parquet package. @songqing  and @robertnishihara 's [solution](https://github.com/ray-project/ray/pull/2241) is to clean and re-clone the packages, which is very slow. Now, it is not necessary to clean the packages. 

2. Update the logic to better handle the case when we update the commit id the thirdparty packages by packing them into a function and call the function when the commit id changed. (Get ready for later Arrow updates.)

## Related issue number

[Issue-1953](https://github.com/ray-project/ray/issues/1953)
[PR-2241](https://github.com/ray-project/ray/pull/2241)

### CODE REVIEW

**Comment by guoyuhong** [comment]
Hi @robertnishihara , it looks like that recent PRs all had the valgrind test failure. Maybe this error was introduced by previous error?

**Comment by guoyuhong** [comment]
@robertnishihara Hi Robert, please help to review.

**Comment by robertnishihara** [comment]
Thanks @guoyuhong! Can you clarify what the root problem was? I still don't quite understand it.

**Comment by guoyuhong** [comment]
Here is the way to repro this failure:
1. build with `pip install -e python --verbose` successfully. 
2. run `rm -rf  thirdparty/../python/ray/pyarrow_files/pyarrow` the same as the building condition in build_arrow.sh. Then the failure will happen. 

I think I was missing something previously, but this time I found it. 

When the first time this script is building Arrow, it cannot find parquet so it will build it, which is fine. However, when the second time this script is building Arrow, it detects that the parquet package exists but it cannot find the correct path. The cache was in `$TP_DIR/build/arrow/python/build/temp.macosx-10.7-x86_64-3.6/CMakeCache.txt` (or the folder name is `temp.linux-x86_64-3.6` in Linux). I removed this file every time the rebuilding condition is satisfies. In this case, we don't need to re-clone Package Arrow & Parquet and Parquet won't be rebuild, either. This will save a lot of building time.

The rest part of this change is trying to make the third-party package updating smooth. In previous code, when we update the version of Arrow, Arrow won't be really rebuilt because the building condition is not satisfied (`$TP_DIR/../python/ray/pyarrow_files/pyarrow` exists.). This change will check the commit id to see whether we need to rebuild.

**Comment by guoyuhong** [comment]
1. @pcmoritz Your patch way will cause the building failure for Java if we build "Java" later than "Python". So put one line of `git checkout cpp/src/arrow/memory_pool.cc` and one line of comment. Please also checkout whether my conflict resolving is correct or not?
2. @robertnishihara Is there any further concern?

**Comment by pcmoritz** [comment]
jenkins retest this please

**Comment by pcmoritz** [comment]
jenkins retest this please

**Review by pcmoritz — APPROVED** [review]

**Comment by guoyuhong** [comment]
Thanks, @pcmoritz !

**Pull request merged**
