### PR TITLE
Revert "[nightly] Deflaky nightly test many_nodes_actor_test (#18582)"

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
This reverts commit fc6a739e4b2743e732dbfdf3303345a0664631ff.

Seems to break K8s support (specifically, dashboard url can't be read from redis for some reason).
See https://github.com/ray-project/ray/issues/18932

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:57:
--
  | /opt/llvm/bin/../include/c++/v1/memory:1274:7: error: field type 'ray::MockRayletClientInterface' is an abstract class
  | _Tp __value_;
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:1314:35: note: in instantiation of template class 'std::__compressed_pair_elem<ray::MockRayletClientInterface, 1, false>' requested here
  | private __compressed_pair_elem<_T2, 1> {
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:2661:26: note: in instantiation of template class 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface>' requested here
  | struct _ALIGNAS_TYPE(_CompressedPair) _Storage {
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:2684:19: note: in instantiation of member class 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::_Storage' requested here
  | static_assert(_LIBCPP_ALIGNOF(_Storage) == _LIBCPP_ALIGNOF(_CompressedPair), "");
  | ^
  | /opt/llvm/bin/../include/c++/v1/__config:444:31: note: expanded from macro '_LIBCPP_ALIGNOF'
  | # define _LIBCPP_ALIGNOF(_Tp) alignof(_Tp)
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3380:55: note: in instantiation of template class 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>' requested here
  | ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3389:19: note: in instantiation of function template specialization 'std::allocate_shared<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>, void>' requested here
  | return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
  | ^
  | src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:43:26: note: in instantiation of function template specialization 'std::make_shared<ray::MockRayletClientInterface, void>' requested here
  | raylet_client = std::make_shared<MockRayletClientInterface>();
  | ^
  | bazel-out/k8-opt/bin/_virtual_includes/grpc_common_lib/ray/raylet_client/raylet_client.h:71:16: note: unimplemented pure virtual method 'RequestWorkerLease' in 'MockRayletClientInterface'
  | virtual void RequestWorkerLease(
  | ^
  | In file included from src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:16:
  | In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:57:
  | /opt/llvm/bin/../include/c++/v1/memory:2622:37: error: allocating an object of abstract class type 'ray::MockRayletClientInterface'
  | ::new ((void*)__get_elem()) _Tp(_VSTD::forward<_Args>(__args)...);
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3380:55: note: in instantiation of function template specialization 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::__shared_ptr_emplace<>' requested here
  | ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3389:19: note: in instantiation of function template specialization 'std::allocate_shared<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>, void>' requested here
  | return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
  | ^
  | src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:43:26: note: in instantiation of function template specialization 'std::make_shared<ray::MockRayletClientInterface, void>' requested here
  | raylet_client = std::make_shared<MockRayletClientInterface>();
  | ^
  | In file included from src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:16:
  | In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:57:
  | /opt/llvm/bin/../include/c++/v1/memory:1375:12: error: static_cast from 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface> *' to 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface>::_Base1 *' (aka '__compressed_pair_elem<std::allocator<ray::MockRayletClientInterface>, 0> *'), which are not related by inheritance, is not allowed
  | return static_cast<_Base1*>(__pair);
  | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | /opt/llvm/bin/../include/c++/v1/memory:2672:74: note: in instantiation of member function 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface>::__get_first_base' requested here
  | typename _CompressedPair::_Base1* __first = _CompressedPair::__get_first_base(__as_pair);
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:2665:27: note: in instantiation of member function 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::_Storage::__get_alloc' requested here
  | ::new ((void*)__get_alloc()) _Alloc(_VSTD::move(__a));
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:2615:11: note: in instantiation of member function 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::_Storage::_Storage' requested here
  | : __storage_(_VSTD::move(__a))
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3380:55: note: in instantiation of function template specialization 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::__shared_ptr_emplace<>' requested here
  | ::new ((void*)_VSTD::addressof(*__guard.__get())) _ControlBlock(__a, _VSTD::forward<_Args>(__args)...);
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3389:19: note: in instantiation of function template specialization 'std::allocate_shared<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>, void>' requested here
  | return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
  | ^
  | src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:43:26: note: in instantiation of function template specialization 'std::make_shared<ray::MockRayletClientInterface, void>' requested here
  | raylet_client = std::make_shared<MockRayletClientInterface>();
  | ^
  | In file included from src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:16:
  | In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:57:
  | /opt/llvm/bin/../include/c++/v1/memory:1379:12: error: static_cast from 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface> *' to 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface>::_Base2 *' (aka '__compressed_pair_elem<ray::MockRayletClientInterface, 1> *'), which are not related by inheritance, is not allowed
  | return static_cast<_Base2*>(__pair);
  | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | /opt/llvm/bin/../include/c++/v1/memory:2678:75: note: in instantiation of member function 'std::__compressed_pair<std::allocator<ray::MockRayletClientInterface>, ray::MockRayletClientInterface>::__get_second_base' requested here
  | typename _CompressedPair::_Base2* __second = _CompressedPair::__get_second_base(__as_pair);
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:2630:53: note: in instantiation of member function 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::_Storage::__get_elem' requested here
  | _Tp* __get_elem() _NOEXCEPT { return __storage_.__get_elem(); }
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3382:76: note: in instantiation of member function 'std::__shared_ptr_emplace<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>>::__get_elem' requested here
  | return shared_ptr<_Tp>::__create_with_control_block((*__control_block).__get_elem(), _VSTD::addressof(*__control_block));
  | ^
  | /opt/llvm/bin/../include/c++/v1/memory:3389:19: note: in instantiation of function template specialization 'std::allocate_shared<ray::MockRayletClientInterface, std::allocator<ray::MockRayletClientInterface>, void>' requested here
  | return _VSTD::allocate_shared<_Tp>(allocator<_Tp>(), _VSTD::forward<_Args>(__args)...);
  | ^
  | src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc:43:26: note: in instantiation of function template specialization 'std::make_shared<ray::MockRayletClientInterface, void>' requested here
  | raylet_client = std::make_shared<MockRayletClientInterface>();
  | ^

**Comment by DmitriGekhtman** [comment]
> In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:57

Uhh, will try rebasing...

**Comment by jjyao** [comment]
Hmm, seems some code failed to compile.

**Comment by DmitriGekhtman** [comment]
> Hmm, seems some code failed to compile.

Will take a quick look and then ask for help when I'm out of my depth :)

**Comment by iycheng** [comment]
Related to this: https://github.com/ray-project/ray/pull/18957
and also https://github.com/ray-project/ray/pull/18961

**Comment by DmitriGekhtman** [comment]
> Related to this: #18957 and also #18961

@iycheng will it be possible to merge this revert after one of #18957, #18961 is merged?

**Comment by DmitriGekhtman** [comment]
Looks like specifically it's test code that's failing to compile.

**Comment by DmitriGekhtman** [comment]
@iycheng Can I leave this in your hands?

**Comment by iycheng** [comment]
Sure, let me fix this.

**Comment by iycheng** [comment]
```




::test_placement_group_remove_stress[2] 2021-09-29 04:45:45,137	INFO services.py:1252 -- View the Ray dashboard at http://127.0.0.1:8265
  | 2021-09-29 04:45:47,038	INFO worker.py:824 -- Connecting to existing Ray cluster at address: 172.18.0.3:6379
  | -- Test timed out at 2021-09-29 04:46:29 UTC --
  | *** SIGTERM received at time=1632890789 on cpu 2 ***
  | PC: @     0x7f8e883e87b1  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
  | @     0x7f8e883ed3c0  (unknown)  (unknown)
  | @ ... and at least 1 more frames
  | [2021-09-29 04:46:29,020 E 13642 13642] logging.cc:314: *** SIGTERM received at time=1632890789 on cpu 2 ***
  | [2021-09-29 04:46:29,020 E 13642 13642] logging.cc:314: PC: @     0x7f8e883e87b1  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
  | [2021-09-29 04:46:29,021 E 13642 13642] logging.cc:314:     @     0x7f8e883ed3c0  (unknown)  (unknown)
  | [2021-09-29 04:46:29,021 E 13642 13642] logging.cc:314:     @ ... and at least 1 more frames
 

<br class="Apple-interchange-newline">
```

Hmmm, pg failed... @rkooo567  did you see this before?

**Comment by rkooo567** [comment]
Yeah this seems to be occasionally timing out. I am thinking to make test longer now

**Comment by iycheng** [comment]
It looks like retry makes it work.

**Comment by iycheng** [comment]
I move it to large test

**Pull request merged**
