### PR TITLE
[Doc] CLI Reference Documentation Revamp 

### LINKED ISSUE #27351: [State Observability Alpha] Logically group CLI commands  from the documentation
### Description

Currently, Ray CLI commands are not logically grouped in a documentation which can confuse users (e.g., when to use `ray memory` vs `ray start`). 

### Link

_No response_

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Take out the CLI reference from the core API subsection. It follows the same CLI reference pattern as other library (e.g., Serve has Serve CLI under Serve API section).

This is the new structure

Screen Shot 2022-08-17 at 5 43 08 PM

## Related issue number

Closes https://github.com/ray-project/ray/issues/27351

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by DmitriGekhtman — APPROVED** [review]
Seems like a reasonable rearrangement.
Stamping for cluster docs codeowner approval.

**Comment by DmitriGekhtman** [comment]
Seems reasonable.

I'd suggested also linking 
`Programmatic Cluster Scaling `
into the "API references" for clusters/vms and clusters/kubernetes

clusters/kubernetes/api_references
Could be split as
`RayCluster CR configuration` (for the existing current content of that section) and
`Programmatic Cluster Scaling` (linking to the correct page)

If you prefer, I can make this change in a follow-up to this PR.

**Comment by DmitriGekhtman** [comment]
@cadedaniel do you have thoughts on clusters api ref structure?

**Comment by rkooo567** [comment]
@DmitriGekhtman that'd be great. I tried something at first and reverted it back for the cluster part because I wasn't sure if that was the right choice. I think it'd be better if you can follow up

**Review by DmitriGekhtman — APPROVED** [review]
Sign-off for clusters. We can refine that part in a follow-up.

**Review by richardliaw — APPROVED** [review]

**Comment by cadedaniel** [comment]
Good idea, thanks for improving this!

One minor detail: I think `cluster/package-overview` and `cluster/cli` should go into a new directory, perhaps named `cluster/reference`. The cluster docs revamp cleaned up the `cluster` directory significantly, we may as well keep things organized.

**Comment by rkooo567** [comment]
@cadedaniel I can create a follow up PR for that movement.

**Comment by DmitriGekhtman** [comment]
> I'd suggested also linking
> Programmatic Cluster Scaling
> into the "API references" for both clusters/vms and clusters/kubernetes

Oh, actually I see "programmatic cluster scaling" is under clusters / application guide, which is fine too.
Given that we also already mention ray.autoscaler.sdk.request_resources in every guide on autoscaling, we should be fine on that item.

**Pull request merged**
