### PR TITLE
Revert "Revert "[runtime_env] Add support of exclusion (#15241)" (#15303)" with fixing

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Revert the reverted pr back and add fixing for the test.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
cc @edoakes

**Comment by rkooo567** [comment]
Second windows build running now...

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Please do not merge it until I do (I am re-running windows build to verify it works). ETA is tomorrow

**Comment by rkooo567** [comment]
Third trial now..

**Comment by iycheng** [comment]
> Third trial now..

Thanks @rkooo567 !

**Comment by rkooo567** [comment]
All test succeeds. The windows tests passed 3 times in a row, meaning it is stable now.

**Pull request merged**
