### PR TITLE
[serve] Shutdown http proxy state (cherry-pick)

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

Cherry pick https://github.com/ray-project/ray/pull/35395 and https://github.com/ray-project/ray/pull/35439

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]
Approved for picking into 2.5.0

**Comment by cadedaniel** [comment]
this breaks lint https://github.com/ray-project/ray/issues/35454

**Comment by cadedaniel** [comment]
> remove print statement from the cherry pick.

also it's a bad idea to modify cherry picks.. makes it really hard to debug failures on the release branch. we should cherry pick only the commit from master, no modifications!

cc @ArturNiederfahrenhorst @can-anyscale

**Review by cadedaniel — CHANGES_REQUESTED** [review]
> this breaks lint https://github.com/ray-project/ray/issues/35454
> > remove print statement from the cherry pick.
> 
> also it's a bad idea to modify cherry picks.. makes it really hard to debug failures on the release branch. we should cherry pick only the commit from master, no modifications!
> 
> cc @ArturNiederfahrenhorst @can-anyscale

**Comment by zcin** [comment]
CI is fixed, and all commits on this PR are now cherry-picked from master.

**Review by cadedaniel — APPROVED** [review]
LGTM. test_multiprocessing_client_mode is failing but also on master.

**Review by zhe-thoughts — APPROVED** [review]

**Pull request merged**
