### PR TITLE
[minor] Refactor to expose RedisContext::PingPort

### PR DESCRIPTION
**Pull request by dHannasch**
This builds on https://github.com/ray-project/ray/pull/12016 and can flex to accommodate any changes to https://github.com/ray-project/ray/pull/12016, so worry about https://github.com/ray-project/ray/pull/12016 first. This will look much simpler with https://github.com/ray-project/ray/pull/12016 subtracted out. More importantly, https://github.com/ray-project/ray/pull/12016 is just *moving* the logic to a separate function without alteration, while this is *changing* the logic (very slightly), so subtracting out https://github.com/ray-project/ray/pull/12016 allows actually seeing what's being changed.

## Why are these changes needed?

This adds a callable function to quickly check whether a port is reachable. By itself this doesn't change any behavior; the function isn't actually called anywhere.

The only change to behavior is to check whether the RedisContext** is null. Obviously that *should* never happen when Connecting normally, so there are any number of legitimate answers to the question "What should we do if that pointer is null?"

The answer given here is "Treat it as a dry run" and the PingPort function gives context as to why: we can use the actual connection code to check a couple of ports in sequence.
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hey @dHannasch Thanks again for all the PRs to make this path clean and clear! But can you actually tell me which order I should review all these PRs? It seems like each of the PRs is on top of the others, so it is kind of hard to review right now.

**Comment by dHannasch** [comment]
> which order I should review all these PRs? It seems like each of the PRs is on top of the others, so it is kind of hard to review right now.

Like it says above, this one is built on https://github.com/ray-project/ray/pull/12016, so https://github.com/ray-project/ray/pull/12016 would be the best place to start. https://github.com/ray-project/ray/pull/12026 is the third in the chain, built atop this one, like it says.  Everything should be independent unless noted.

**Comment by richardliaw** [comment]
merge master now that 12016 merged?

**Comment by dHannasch** [comment]
> merge master now that 12016 merged?

Done. You can see the actual diffs now.

As you can see, this doesn't actually change the output at all (https://github.com/ray-project/ray/pull/12110 does that).

**Comment by richardliaw** [comment]
Great! I am personally not familiar with this part of the code, @rkooo567 can you take a look?

**Comment by rkooo567** [comment]
Thanks for the PR again! I am a little confused about this sentence `The answer given here is "Treat it as a dry run" and the PingPort function gives context as to why: we can use the actual connection code to check a couple of ports in sequence.`.

Why don't we implement this in this PR? The end state of this PR is just adding a method that is not used right?

**Comment by dHannasch** [comment]
> Thanks for the PR again! I am a little confused about this sentence `The answer given here is "Treat it as a dry run" and the PingPort function gives context as to why: we can use the actual connection code to check a couple of ports in sequence.`.
> 
> Why don't we implement this in this PR? The current end state of this PR is just adding a method that is not used right?

That's actually changing behavior, so I put that in https://github.com/ray-project/ray/pull/12026. https://github.com/ray-project/ray/pull/12026 should be easier to review when it's clear at a glance that it's really only making one change to call a single function once. https://github.com/ray-project/ray/pull/12026 is a bit thornier since it's actually adding more packet traffic that wasn't there before, even in the non-error case. (https://github.com/ray-project/ray/pull/12026 could be altered to remove that, but only by making much more extensive changes to the control flow.)

Plus, I didn't know whether you might want changes to *this* PR, whether you'd come back with "Actually, if this pointer is null then this function should X", something that would be easier to sort out if this PR wasn't commingled with https://github.com/ray-project/ray/pull/12026.

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
I'm merging this PR because it looks safe, blocks other usability PRs, and we've been sitting on it for a while without response. @dHannasch in a later PR, can you add a test for pingport?

**Pull request merged**
