### PR TITLE
[WIP] Auto-generate options methods documentation

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Added documentation for remote_function.options and ActorClass.options, which was missing before

## Related issue number

https://github.com/ray-project/ray/issues/6699

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @edoakes 

We pair programmed yesterday. It turned out there are 2 tricky issues.

1. It was a little unclear how we should document duck-typed chained methods. We just decided to expose `RemoteFunction.options` and `ActorClass.options`. I think it looks pretty clear that they are `options` methods for remote function & actor, but let us know if you think we should use a different way.

2. I think we should re-write `options` docstrings. It is currently written in a way it exposes all implementation details as well as does not contain any useful parameter information. Do you have any suggestion who to ask to write this docstring? (I can try if you don't come up with a good person).

**Comment by edoakes** [comment]
@rkooo567 sounds good, thanks for the details. (1) sounds good and agree the docstrings need to be re-written. Could you take a stab at it and I'll help review to make sure it's up to date? The main issue seems to be actually separating out the arguments instead of just passing them in as `**options`.

**Comment by rkooo567** [comment]
Why did we close this? What’s the next step for it?

**Comment by edoakes** [comment]
IIRC the next step is for you to take a stab at writing the docstrings @rkooo567 :)

**Comment by rkooo567** [comment]
Ah, that’s right. Can we keep it open? I will work on it at night or the beg of next sprint.

**Comment by rkooo567** [comment]
Replaced by https://github.com/ray-project/ray/pull/10830

**Pull request closed without merging**
