### PR TITLE
[2.3][Datasets] Update all documentation for Ray Data w/ lazy execution

### PR DESCRIPTION
**Pull request by c21**
## Why are these changes needed?

This PR is a combination of cherry-pick 4 PRs:
https://github.com/ray-project/ray/pull/31989
https://github.com/ray-project/ray/pull/32394
https://github.com/ray-project/ray/pull/32387
https://github.com/ray-project/ray/pull/32390

to update all Ray Data documentation after lazy execution is enabled by default.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
Should we wait and include https://github.com/ray-project/ray/pull/32390 as well?

**Comment by c21** [comment]
@cadedaniel - I can make all stuff in the same PR. No strong preference, if that's easy for review.

**Comment by cadedaniel** [comment]
> @cadedaniel - I can make all stuff in the same PR. No strong preference, if that's easy for review.

That would be better, thx

**Comment by c21** [comment]
This PR itself does not depend on https://github.com/ray-project/ray/pull/32390 .

**Comment by c21** [comment]
Ok cool, I will wait https://github.com/ray-project/ray/pull/32390 merged, and update here.

**Comment by c21** [comment]
Just included https://github.com/ray-project/ray/pull/32390 in this PR.

**Comment by cadedaniel** [comment]
Great cc @zhe-thoughts for review. I will look in a minute.

**Review by jianoaix — APPROVED** [review]

**Review by clarkzinzow — APPROVED** [review]

**Review by zhe-thoughts — APPROVED** [review]
Approved for picking

**Comment by cadedaniel** [comment]
Thanks team!

**Pull request merged**
