### PR TITLE
[Kubernetes][Doc] State intent to remove legacy Ray Operator

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
Signed-off-by: Dmitri Gekhtman <dmitri.m.gekhtman@gmail.com>

## Why are these changes needed?

This PR documents the intent to remove the legacy Ray operator in Ray 2.2.0.

Here's the timeline of our posture:

- In Ray 2.0.0, we documented KubeRay as the preferred deployment method and stated the intent to deprecate
the legacy operator in the future.
- In the Ray 2.1.0 release, we state that it is still possible to use the operator but give an explicit end-of-life at Ray 2.2.0.
- In the Ray 2.2.0, we remove the operator code and documentation. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
This would be good to merge before the Ray 2.1.0 branch cut.

**Comment by pcmoritz** [comment]
Ok, I'm supportive of this, but be aware that this deprecation + release cycle is pretty quick for an infra component like the Ray Operator. If we get push back about this from our users, we should push it out 1-2 more Ray releases.

**Review by pcmoritz — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
> Ok, I'm supportive of this, but be aware that this deprecation + release cycle is pretty quick for an infra component like the Ray Operator. If we get push back about this from our users, we should push it out 1-2 more Ray releases.

I agree with this general sentiment.

**Comment by DmitriGekhtman** [comment]
Doc lint passes. Checked rendered docs and README for consistency. Will merge now.

**Pull request merged**
