### PR TITLE
Revert "[Overview][Serve] Add Recent Serve Applications Card"

### PR DESCRIPTION
**Pull request by aslonnie**
Reverts ray-project/ray#34642

This seems be breaking all pipeline builds. as it is failing to build the base container.

### CODE REVIEW

**Comment by aslonnie** [comment]
Failure starts at: https://buildkite.com/ray-project/oss-ci-build-branch/builds/3815

**Comment by aslonnie** [comment]
cc @can-anyscale

**Comment by aslonnie** [comment]
A revert needs `-s`?

**Comment by aslonnie** [comment]
> A revert needs `-s`?

done..

**Comment by aslonnie** [comment]
failure point:

https://buildkite.com/ray-project/oss-ci-build-branch/builds/3815#0187fe05-e879-4d08-b6a9-61b2abac4ee5/385-1494

**Review by alanwguo — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
