### PR TITLE
[CI] Fix test result not found in client_runner

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?
PR 31978 replaced result_output_json and metrics_output_json with fixed values, but did not update client_runner.
GCE tests using client_runner is failing (https://buildkite.com/ray-project/release-tests-branch/builds/1451#0186f19a-803c-44d2-95ac-a1fcc9c7162f) with the following error because of that. Simple fix by reusing the fixed global values.
    
    > [Errno 2] No such file or directory: '/tmp/tmpr33nmui3'
    > Traceback (most recent call last):
    >  File "/tmp/release-HS2M44AnMX/release/ray_release/command_runner/client_runner.py", line 122, in _fetch_json
    >    with open(path, "rt") as fp:
    > FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpr33nmui3'
    
Signed-off-by: Cuong Nguyen <can@anyscale.com>

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X ] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [X ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X ] This PR is not tested :(

### CODE REVIEW

**Review by xwjiang2010 — APPROVED** [review]
Thanks for catching it!

**Comment by can-anyscale** [comment]
Absolutely. 

@jjyao: if this looks ok, can you help merge this as well. Thank you!

**Review by Yard1 — APPROVED** [review]

**Comment by jjyao** [comment]
Lint error: 

```
release/ray_release/command_runner/client_runner.py:6:1: F401 'tempfile' imported but unused
```

**Comment by can-anyscale** [comment]
Ah, thanks for catching. Will update shortly.

**Comment by can-anyscale** [comment]
'import tempfile' removed

**Pull request merged**
