### PR TITLE
[docs] new landing page

### PR DESCRIPTION
**Pull request by maxpumperla**

### CODE REVIEW

**Comment by simran-2797** [comment]
Thanks, Max! This is awesome! I just had a few comments from the design side: 
1. Could we change the font-weight of the titles to 600? I feel like they could be a bit bolder
2. We can also increase the spacing between various sections to make it a bit more clean
3. In the getting started section, we could increase the size of decorative icons and the square background. 
4. In the getting started section, the spacing between the getting started cards is missing. We can add a spacing of 16px there. 
5. The getting started cards could also be aligned with the title. 
6. We can remove the border from the box enclosing pip install in the getting started section. 
7. We can also add a shadow to the code section within scaling with Ray. 
8. In the beyond the basics section, the cards have a different color and are flat. LMK what you think about it. I understand why you have reused the cards. I'm okay with that too. We just need to add 16px spacing between them. 
9. The getting involved section is sort of shrinked for me horizontally. 
Screen Shot 2023-03-23 at 1 21 43 PM

**Comment by simran-2797** [comment]
One more request:
1. Is it possible to disable the ability to select things in this code section? Since these won't be runnable codes but just the ones that given the user an idea about the library, we want to make sure that the users don't select it and copy it. 
Screen Shot 2023-03-23 at 4 56 01 PM

**Comment by angelinalg** [comment]
Rebasing didn't fix the browser tab hover issue. Hoping that you'll know how to fix it, @maxpumperla. Thanks!

**Review by angelinalg — APPROVED** [review]
LGTM

**Pull request merged**
