### PR TITLE
[Test] Split long runtime env tests.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

`test_runtime_env` is timedout.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @iycheng Can you recommend a better name than `test_runtime_env_2.py` if there is?

**Comment by iycheng** [comment]
@rkooo567 really appreciate the help on this one! Probably we can rename it to `test_runtime_env_complicated.py` since they are downloading complicated runtime environments.

**Review by fishbone — APPROVED** [review]
Again, really appreciate it!

**Comment by rkooo567** [comment]
The build images is consistenlty happening in the PR build.

**Pull request merged**
