### PR TITLE
[serve] Update docs on max ongoing requests default change

### PR DESCRIPTION
**Pull request by zcin**
[serve] Update docs on max ongoing requests default change

When changing the default for `max_ongoing_requests` from 100 to 5, the autoscaling docs were updated but the "Configure Serve Deployment" docs were missed.
Update configure serve deployment docs with the new default value.

Signed-off-by: Cindy Zhang <cindyzyx9@gmail.com>

### CODE REVIEW

**Review by GeneDer — APPROVED** [review]
Thanks Cindy!

**Review by can-anyscale — APPROVED** [review]

**Comment by zcin** [comment]
@shrekris-anyscale @edoakes ping for merge

**Comment by edoakes** [comment]
@zcin merge conflict now

**Comment by zcin** [comment]
@edoakes fixed merge conflict

**Pull request merged**
