### PR TITLE
[core] Better error handling when core_worker missing for recording logs

### LINKED ISSUE #37758: [Core] better failure handling during worker exit
### What happened + What you expected to happen

Notice following crash log which cause cascading failures
```
Traceback (most recent call last):
  File "some_helper.py", line 246, in subprocess_call
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 776, in sigterm_handler
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1501, in ray._raylet.execute_task
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 569, in record_task_log_end
    self.core_worker.record_task_log_end(
AttributeError: 'Worker' object has no attribute 'core_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1787, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 1684, in ray._raylet.execute_task_with_cancellation_handler
  File "python/ray/_raylet.pyx", line 1366, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1367, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 1583, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 813, in ray._raylet.store_task_errors
AttributeError: 'Worker' object has no attribute 'core_worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1824, in ray._raylet.task_execution_handler
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/utils.py", line 174, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'Worker' object has no attribute 'core_worker'
Exception ignored in: 'ray._raylet.task_execution_handler'
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 1824, in ray._raylet.task_execution_handler
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/utils.py", line 174, in push_error_to_driver
    worker.core_worker.push_error(job_id, error_type, message, time.time())
AttributeError: 'Worker' object has no attribute 'core_worker'
[2023-07-21 17:57:05,836 C 1076 1076] direct_actor_transport.cc:201:  Check failed: objects_valid
*** StackTrace Information ***
```

### Versions / Dependencies

2.5.1

### Reproduction script

n/a

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
https://github.com/ray-project/ray/issues/37758

## Related issue number

Closes https://github.com/ray-project/ray/issues/37758

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
LGTM. I think we should make self.core_worker to be a property instead in the longer term...

**Comment by rickyyx** [comment]
> LGTM. I think we should make self.core_worker to be a property instead in the longer term...

I tried in this PR actually - i think it's not a huge difference, instead of calling `if hasattr(workrer, "core_worker")` we will do `if worker.core_worker`

**Comment by rkooo567** [comment]
I think the property could just raise an exception instead?

**Comment by rickyyx** [comment]
> I think the property could just raise an exception instead?

Then it will be similar with current approach right? When an attribute of `core_worker` not found, it will also just raise an exception.

**Comment by rkooo567** [comment]
>  Then it will be similar with current approach right? When an attribute of core_worker not found, it will also just raise an exception.

Yeah it is .But we don't need to write `if not hasattr(self, "core_worker"):` everywhere?

**Comment by rickyyx** [comment]
> > Then it will be similar with current approach right? When an attribute of core_worker not found, it will also just raise an exception.
> 
> Yeah it is .But we don't need to write `if not hasattr(self, "core_worker"):` everywhere?

I guess we could always don't check the existence of the attribute and let it raise exception.

**Pull request merged**
