### PR TITLE
Minor doc fix

### PR DESCRIPTION
**Pull request by heyucongtom**
## What do these changes do?

Straight forward doc fix. I think it shall be "will not" instead of "will". See code

### CODE REVIEW

**Review by richardliaw — DISMISSED** [review]

**Comment by robertnishihara** [comment]
@heyucongtom @richardliaw I think the documentation is correct as is, right? The provided addresses are for processes that have already been started I think.

**Review by robertnishihara — CHANGES_REQUESTED** [review]
See comment.

**Comment by heyucongtom** [comment]
If they are started already, they can’t “be started.”, which is my intention of using “not” here. 

Will double check while I am going through the source. Anyway, it seems to me that the wording is very vague though.

**Comment by richardliaw** [comment]
I see; after a closer read-through of source, I can see why original is correct (albeit very vague because the reference of "any processes" is not clear).

```
 address_info (dict): A dictionary with address information for
            processes in a partially-started Ray cluster. If
            start_ray_local=True, any processes not in this dictionary will be
            started.
``` 

At an initial read, if this is a dict of addresses, why would it have processes? It would be good to clarify, especially since `_init` is only called with `start_ray_local` is `redis_address` is None, so it should only have `node_ip_address`. 

It would be good to clarify this documentation to note what are the entities (addresses, not processes, right?) that would be included in this dictionary...

**Pull request closed without merging**
