### PR TITLE
Fixes Mac OSX installation error

### PR DESCRIPTION
**Pull request by gdtm86**
Includes fixes for Mac OSX build issues - [461](https://github.com/ray-project/ray/issues/461)

### CODE REVIEW

**Comment by pcmoritz** [comment]
ok to test

**Comment by gdtm86** [comment]
@pcmoritz @robertnishihara - looks like all checks have passed. Can we merge this to master?

**Comment by pcmoritz** [comment]
Merged it, thanks a lot for your help!

**Comment by robertnishihara** [comment]
Once https://github.com/apache/arrow/pull/567 is merged (into Arrow), we should be able to revert some of the changes in this PR (e.g., dependencies on `boost_regex`).

**Comment by wesm** [comment]
Appreciate the patience, I don't think the recent chaos will be the norm

**Pull request merged**
