### PR TITLE
Deflaky test failure in win32

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
To deflaky test_lease_request_leak failure in win32

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
@clarkzinzow Can you make a PR to fix the Dask issue (asap if possible)? Windows test has been very useful catching these API changes, so we should keep turning it on.

**Comment by clarkzinzow** [comment]
@rkooo567 Sure!

**Comment by iycheng** [comment]
I think I can revert these changes (on dask) and waiting for fixing from @clarkzinzow

**Comment by clarkzinzow** [comment]
Actually @iycheng you may want to keep that Dask skip, the change is much more complex than I had expected. We may have to reimplement a nontrivial portion of the Dask-on-Ray scheduler.

**Pull request merged**
