### PR TITLE
Avoid copying data multiple times during chunking.

### LINKED ISSUE #34771: [dataclient] Avoid copying `data` multiple times during chunking
### What happened + What you expected to happen

When transferring **large objects**, Ray performs chunking, but accessing the data field of protobuf during each chunking operation will result in copying **Every Time**. And this will result in the inability to fully utilize the bandwidth.

In fact, we can access the data once before the loop.

The following figure shows the time consumed when accessing the data field of a protobuf object with a size of 1 GiB

bench

### Versions / Dependencies

ray latest

### Reproduction script

Any scenario that requires transferring large objects

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by zen-xu**
## Related issue number
Closes #34771

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Thanks for the contribution! Could you fix the lint issue?

**Review by ckw017 — APPROVED** [review]
Great catch, thanks for spotting this! I am a bit surprised that this is the default behavior of Python's protobuf implementation (deserialization each time the field is accessed), is this documented somewhere?

This should be fine to merge once lint is passing. Lint check is [here](https://buildkite.com/ray-project/oss-ci-build-pr/builds/19827#0187bb5d-9796-4e51-9c52-a457e089efe0), looks like it just wants you to break up the comment into more lines


```
python/ray/util/client/dataclient.py:58:89: E501 line too long (96 > 88 characters)
python/ray/util/client/dataclient.py:86:89: E501 line too long (96 > 88 characters)
```

**Comment by zen-xu** [comment]
> Great catch, thanks for spotting this! I am a bit surprised that this is the default behavior of Python's protobuf implementation (deserialization each time the field is accessed), is this documented somewhere?

Because we have a need to transmit large objects but found that the up bandwidth during transmission with ray can only be ~30 MB/s (expected ~120 MB/s), we then performed a line-by-line analysis of the test results and located the issue with accessing protobuf `data` field.

https://github.com/ray-project/ray/blob/85dddb3b63ad3c1dff82f34caf16eb76e8345d06/python/ray/util/client/dataclient.py#L72-L98

bench

**Comment by zen-xu** [comment]
In addition, I found that the time it takes to serialize a protobuf object is not linear.

protobuf_benchmark

As shown in the graph, it can be seen that the serialization time of protobuf objects is not linear. When the data size is larger than 5MB, the serialization time becomes non-linear. The serialization time of 64MB data is **77 times** that of 5MB data.

**Comment by zen-xu** [comment]
So I did some chunk benchmarking between 2 nodes (10 GbE)

```python
import ray
import time
import numpy as np
from ray.util.client import common

ray.init(address="ray://xxxx:10001")

CHUNK_SIZE_MB = 1
common.OBJECT_TRANSFER_CHUNK_SIZE = CHUNK_SIZE_MB * 2 ** 20

@ray.remote
def demo(arr):
    return arr

def bench(bytes_mb, task_count):
    arr = np.zeros(int(bytes_mb * 1024 * 1024  / 8), dtype=np.int64)
    start = time.time()
    results = [demo.remote(arr) for _ in range(task_count)]
    ray.get(results)
    print("duration: {:.9f}", time.time() - start)

for mb, task_count in [(2000, 2), (200, 20), (20, 200), (2, 2000), (1, 4000)]:
    bench(mb, task_count)
```

bench result is [here](https://docs.google.com/spreadsheets/d/1EYgemiZ63WXvkK-dvnGIeE4-Qyam0XYpA2yD_z15wyg/edit#gid=626814170)

We can find that the default chunk size is not friendly to large objects, and there is no significant difference for small objects. Therefore, the optimal chunk sizes are 1MB, 5MB, and 10MB.

**Comment by ckw017** [comment]
This PR looks good to merge, can look into adjusting the chunk size in a separate PR.

**Comment by jjyao** [comment]
@zen-xu could you update the PR description and I'll merge the PR.

**Comment by zen-xu** [comment]
@ckw017 I have opened a new PR #35025 for chunk size.

**Pull request merged**
