### PR TITLE
[serve] Document multi-app

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

Cherry-pick https://github.com/ray-project/ray/pull/33496. Docs-only changes.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]

**Comment by clarng** [comment]
docs build is red, waiting for it to go green

**Comment by zcin** [comment]
@clarng Is this ready to merge?

**Comment by clarng** [comment]
Still fixing docs build

**Comment by clarng** [comment]
https://github.com/ray-project/ray/pull/34324

**Comment by zcin** [comment]
@clarng The fix looks merged, is this good to be merged?

**Pull request merged**
