### PR TITLE
[ADAG] Add checking for worker

### LINKED ISSUE #46796: [Core\aDAG] AttributeError: 'Worker' object has no attribute 'core_worker' upon destruction
### What happened + What you expected to happen

```
2024-07-24 23:46:13,852 INFO compiled_dag_node.py:1242 -- Tearing down compiled DAG
Exception ignored in: <function RayGPUExecutor.__del__ at 0x76b9206320d0>
Traceback (most recent call last):
  File "/home/ray/default/vllm/vllm/executor/ray_gpu_executor.py", line 397, in __del__
    self.forward_dag.teardown()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dag/compiled_dag_node.py", line 1442, in teardown
    monitor.teardown(wait=True)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/dag/compiled_dag_node.py", line 1244, in teardown
    outer._dag_submitter.close()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/experimental/channel/common.py", line 383, in close
    self._output_channel.close()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/experimental/channel/shared_memory_channel.py", line 628, in close
    channel.close()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/experimental/channel/shared_memory_channel.py", line 507, in close
    self._worker.core_worker.experimental_channel_set_error(self._writer_ref)
AttributeError: 'Worker' object has no attribute 'core_worker'
```

Happened when using aDAG + vLLM integration + tp 2 + benchmark_throughput.py in a10g instance

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None

### PR DESCRIPTION
**Pull request by Bye-legumes**
## Why are these changes needed?

close https://github.com/ray-project/ray/issues/46796
## Related issue number
 https://github.com/ray-project/ray/issues/46796
## Checks

- [√] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [√] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [√] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [√] Unit tests
   - [√] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@Bye-legumes when you worked on this, were you able to repro the issue, or is it more hypothetical fix? I think checking this makes sense as we cannot guarantee `core_worker` is not GC'ed at the time of `__del__`, but I wonder if there's more cleaner solution for shutdown in general

**Comment by Bye-legumes** [comment]
> @Bye-legumes when you worked on this, were you able to repro the issue, or is it more hypothetical fix? I think checking this makes sense as we cannot guarantee `core_worker` is not GC'ed at the time of `__del__`, but I wonder if there's more cleaner solution for shutdown in general

I repro this, but it's not stable. 
I think you are correct, we should investigate better solution to ensure the shutdown sequence of the work (by vLLM) and also the time to shutdown the channel. Let me check if we can move that shutdown to a more proper position, i.e. before kill work.

BTW: Also I found there is a regression on my machine with vLLM + aDAG + tp2 + llama 7b case.
default mp:
Tokens per second: 4250.70 
with ray  as backen
Tokens per second: 4258.55
With aDAG:
Tokens per second: 3235.51

**Comment by rkooo567** [comment]
> BTW: Also I found there is a regression on my machine with vLLM + aDAG + tp2 + llama 7b case.
default mp:
Tokens per second: 4250.70
with ray as backen
Tokens per second: 4258.55
With aDAG:
Tokens per second: 3235.51

This is related to the issue you opened last time?

**Comment by rkooo567** [comment]
Let's merge it after addressing my comments. I think warning is better than a random exception

**Comment by rkooo567** [comment]
@Bye-legumes https://github.com/ray-project/ray/pull/47702

I attempted to clean up shutdown path yesterday. do you mind trying this out?

**Comment by rkooo567** [comment]
with this approach, you will never need to use ray apis in `__del__` upon shutdown

**Comment by Bye-legumes** [comment]
> @Bye-legumes #47702
> 
> I attempted to clean up shutdown path yesterday. do you mind trying this out?

Sure! Thx! Let me try that!

**Comment by Bye-legumes** [comment]
> with this approach, you will never need to use ray apis in `__del__` upon shutdown

It.s fix now! thx!

**Pull request closed without merging**
