### PR TITLE
[tune] Fix Jenkins tests

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

This is to get Tune tests up and running - an issue has already been filed in #6025 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by ericl** [comment]
@edoakes did you merge the fix for this yet?

**Comment by edoakes** [comment]
Is there a reason why you're not calling `ray.shutdown()` before `cluster.shutdown()`? That would be a better fix.

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Review by edoakes — APPROVED** [review]

**Pull request merged**
