### PR TITLE
[Dashboard] Fix file size converter

### PR DESCRIPTION
**Pull request by Linniem**
## Why are these changes needed?

File size converter is not correct with Bytes and PB.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Linniem** [comment]
push to prevent auto close

**Comment by Linniem** [comment]
push

**Comment by ollie-iterators** [comment]
push

**Comment by Linniem** [comment]
Hi, @rkooo567 @rickyyx 
please help review, thank you

**Review by rickyyx — APPROVED** [review]
Looks good to me! 

cc @alanwguo

**Comment by alanwguo** [comment]
@Linniem this looks great! Can you add a basic unit test for this function?

It can be similar structure to: `dashboard/client/src/pages/job/hook/useJobProgress.unit.test.ts`.

**Comment by rkooo567** [comment]
oops @alanwguo I missed your comment...

**Comment by rkooo567** [comment]
@Linniem can you create a follow up PR?

**Pull request merged**
