### PR TITLE
Build from source in Jenkins

### PR DESCRIPTION
**Pull request by simon-mo**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by simon-mo** [comment]
@richardliaw @rkooo567 Jenkins passed on master with building ray from source. 

https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/25390/console

Some of those are flaky but all of them passed with 3 max retries.

**Comment by simon-mo** [comment]
This should be merged so Jenkins will compile from source cc @richardliaw

**Comment by rkooo567** [comment]
@simon-mo Will you plan to merge it?

**Comment by simon-mo** [comment]
Yes. Please approve

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Just did! @simon-mo

**Comment by richardliaw** [comment]
Thanks!

**Pull request merged**
