### PR TITLE
[doc] add Ray versions 1.9.1 - 1.10.0 to dask on ray compatibility table

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
I updated this version compatibility table on the release branch but didn't update it on master.  This is my mistake, the process is to make a PR to master and then cherry pick that commit to the release branch.  

This PR updates the table on master.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scv119 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
is this not working with 2021.12? Or there was no release on that month?

**Comment by architkulkarni** [comment]
> is this not working with 2021.12? Or there was no release on that month?

Not sure, following the release process I grabbed the most recent version from https://github.com/ray-project/ray/blob/master/python/requirements/data_processing/requirements.txt, which is 11.0

**Comment by rkooo567** [comment]
This should be tested against the latest Dask always.

https://pypi.org/project/dask/#history

Can you test with the latest version and update this doc?

**Comment by architkulkarni** [comment]
@rkooo567 Oh, I didn't know that.  Okay, I'll test with the latest dask and update the release process and this PR.

**Comment by rkooo567** [comment]
@architkulkarni lint failrue!

**Comment by architkulkarni** [comment]
test_cli and test_client_proxy are flaky on master and unrelated to this PR.

**Pull request merged**
