### PR TITLE
Remove remaining __future__ imports.

### PR DESCRIPTION
**Pull request by sven1977**
Some 10+ __future__ imports were not captured in previous PR. 

#6580 

#6580 

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
LGTM, please fix lint errors. You can run `./setup_hooks.sh` to create a pre-push hook that runs the linter.

**Comment by sven1977** [comment]
It's not LINT, it's some python 3.x incompatibility with the `print(.., file=xyz)` syntax. I'm taking a look.

**Comment by sven1977** [comment]
So we are getting this here after we removed the remaining `from __future__ import print`:
```
Setting environment variables from .travis.yml
185$ export TESTSUITE=streaming
186$ export JDK='Oracle JDK 8'
187$ export RAY_INSTALL_JAVA=1
188$ export PYTHON=3.5
189$ export PYTHONWARNINGS=ignore
190
cache.1
191Setting up build cache
201
202$ bash -c 'echo $BASH_VERSION'
2034.3.48(1)-release
204
2050.05s$ python $TRAVIS_BUILD_DIR/ci/travis/determine_tests_to_run.py
206  File "/home/travis/build/ray-project/ray/ci/travis/determine_tests_to_run.py", line 46
207    print(pformat(files), file=sys.stderr)
208                              ^
209SyntaxError: invalid syntax
210The command "python $TRAVIS_BUILD_DIR/ci/travis/determine_tests_to_run.py" failed and exited with 1 during .
``` 
My guess is, we are still running the `determine_tests_to_run.py` with py2.

**Comment by sven1977** [comment]
@edoakes
Yes, so apparently, somehow, it's still using py2. I don't know why, the PYTHON var is set to "3.5" for all travis tests.
```
$ python -V
Python 2.7.12
```

**Comment by sven1977** [comment]
Travis does not respect the $PYTHON env variable. I printed out the actual py version used via `python -V` inside install_dependencies.sh and it's indeed py 2.7.12, even though the env variable is set to PYTHON=3.5 (<- that's the one we print out, but it's not the actual one!).
I also tried setting `python:\n - "3.6"` in the head of the .travis.yml file, but that doesn't help either.
Not sure what else to do at this point.

**Pull request closed without merging**
