### PR TITLE
Revert "Add c++ usage stats client"

### PR DESCRIPTION
**Pull request by scv119**
Reverts ray-project/ray#30427

Looks it causing segmentation fault. https://buildkite.com/ray-project/oss-ci-build-branch/builds/1273#0184ad2e-5f3b-49b9-b396-5f9eea80e9af
```


PASSED*** SIGSEGV received at time=1669357131 ***
--
  | PC: @        0x114471cb8  (unknown)  ray::rpc::GrpcClient<>::CallMethod<>()
  | @        0x114b56be4  (unknown)  absl::lts_20211102::WriteFailureInfo()
  | @        0x114b5694b  (unknown)  absl::lts_20211102::AbslFailureSignalHandler()
  | @     0x7fff6950d5fd  (unknown)  _sigtramp
  | @                0x0  (unknown)  0x0
  | @        0x114471ba9  (unknown)  ray::rpc::GcsRpcClient::AddProfileData()::{lambda()#1}::operator()()
  | @        0x1144adbbf  (unknown)  ray::rpc::Executor::Execute()
  | @        0x1144432bf  (unknown)  ray::rpc::GcsRpcClient::AddProfileData()
  | @        0x114442e48  (unknown)  ray::gcs::StatsInfoAccessor::AsyncAddProfileData()
  | @        0x1143646db  (unknown)  ray::core::worker::Profiler::FlushEvents()
  | @        0x1145fd4b8  (unknown)  ray::PeriodicalRunner::DoRunFnPeriodicallyInstrumented()
  | @        0x1145ff43f  (unknown)  std::__1::__function::__func<>::operator()()
  | @        0x114622fa6  (unknown)  EventTracker::RecordExecution()
  | @        0x1145feefc  (unknown)  boost::asio::detail::binder1<>::operator()()
  | @        0x1145fe701  (unknown)  boost::asio::detail::wait_handler<>::do_complete()
  | @        0x114b42bb5  (unknown)  boost::asio::detail::scheduler::do_run_one()
  | @        0x114b391e1  (unknown)  boost::asio::detail::scheduler::run()
  | @        0x114b390db  (unknown)  boost::asio::io_context::run()
  | @        0x11429c9d2  (unknown)  ray::core::CoreWorker::RunIOService()
  | @        0x114316edd  (unknown)  std::__1::__thread_proxy<>()
  | @     0x7fff69519109  (unknown)  _pthread_start
  | @     0x7fff69514b8b  (unknown)  thread_start


```

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by jjyao** [comment]
hmm, is it related?

**Comment by jjyao** [comment]
hmm, is it related?

**Comment by scv119** [comment]
Waiting for @jjyao's investigation first.

**Comment by scv119** [comment]
> my guess would be the gcs_client is still accessed after Disconnect is called 
related to this change: https://github.com/ray-project/ray/pull/30427/files#diff-06efe8e472bafe14da6bd725a27f8e0ed585425ee0065f34606ff19006642a5eR134

**Pull request merged**
