### PR TITLE
[cmake] enable using thirdparty env variable to find installed dependency

### PR DESCRIPTION
**Pull request by chuxi**
## What do these changes do?

this pr enables the support of thirdparty env variable to find installed dependencies. So if the user has installed the package, for example, boost, then he can use `export BOOST_ROOT=/path/to/boost-install` to skip the download and building of boost, using the installed boost directly.

why do I post the PR?

em... for my ci environment, it is too slow to download thirdparty packages, and I want to speed up the ci process which is slow for the thirdparty. So by this PR, it offers developer more control to the build process.

Now it supports env variables:

- BOOST_ROOT
- FLATBUFFERS_HOME
- GLOG_HOME
- GTEST_HOME

And in parquet and arrow building, it also will download thrift and snappy, which you can set `THRIFT_HOME` and `SNAPPY_HOME` to skip the download and build.

A trick: without the env variables, building ray and you can get the the thirdparty source build result in `build/external`, just copy out and set your envs

### CODE REVIEW

**Comment by guoyuhong** [comment]
@chuxi Nice job! This PR will improve the building process.

**Comment by chuxi** [comment]
@robertnishihara  `test/runtest.py::GlobalStateAPI::testFlushAPI`, I am always blocked by the case... do you have any clue how to resolve it?

**Comment by robertnishihara** [comment]
@chuxi ah sorry for missing your question earlier, I think we should probably remove the `testFlushAPI` test because its only for legacy Ray anyway. However, I'm not sure what the issue is.

**Comment by robertnishihara** [comment]
@chuxi I am traveling now without much internet so won’t  be able rob look at it until Monday. Perhaps @pcmoritz or @atumanov or @concretevitamin could take a look?

**Comment by chuxi** [comment]
haha, I am also traveling at Thailand for aow diving certificate.

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
