### PR TITLE
Bug fix while determining ip address in reporter.py

### PR DESCRIPTION
**Pull request by Deathn0t**
## What do these changes do?

These change are returning the ip address using the socket lib instead of looking at their names. On some system an IP address of kind Ethernet doesn't start by "e". This change should not change de previous behaviour which remains the default one.

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]
This looks good to me given that it does not change previous behavior. Can you log a debug message saying that you are falling back to `gethostname`?

**Comment by Deathn0t** [comment]
@richardliaw I added a `logger.warning(...)`

**Comment by pcmoritz** [comment]
@Deathn0t Thanks! There is a small linting error left, see https://travis-ci.com/ray-project/ray/jobs/224974929

**Comment by Deathn0t** [comment]
@richardliaw I added the required space for inline comments.

**Pull request closed without merging**
