### PR TITLE
Light up Ask AI button When Seach is Open

### LINKED ISSUE #46136: [Doc] Make Ask AI button light up when a user clicks on the search bar
### Description

Currently we are investigating ways to improve search. For now, we'd also like to highlight the `Ask AI` button when a user clicks on the `search` button, just to remind them that it's there.
This issue is to track work on making a little animation that highlights the Ask AI button when the search button is clicked. cc @angelinalg

### PR DESCRIPTION
**Pull request by cristianjd**
## Why are these changes needed?

Lights up and adds a bounce animation when the search input is open
- used css sibling selector to target the ask AI button when the search input and overlay is open, to add a bounce and brighten the button by 50% as well as raise the z index so it is visible over the overlay
- JS to ensure that search is closed when ask AI is clicked
https://www.loom.com/share/c84653be0b4a42debaa71f361c11dc42?sid=58e13baf-30bc-4524-a569-9d26af2d7175

## Related issue number

Closes https://github.com/ray-project/ray/issues/46136

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by angelinalg — APPROVED** [review]
So cool! Thank you!! We should see if this increases the usage of the Ask AI button.

**Review by peytondmurray — APPROVED** [review]
If the user clicks on the search button, then Ask AI, then closes the Ask AI dialog, the search modal is then hidden. I think this is fine, though, since they can just open it again by clicking on the search button.

**Comment by angelinalg** [comment]
Simran is on vacation, so reassigning to @scottsun94. Thanks!

**Comment by scottsun94** [comment]
LGTM. Thanks!

**Pull request merged**
