### PR TITLE
[Train] Fully deprecate Ray SGD v1

### LINKED ISSUE #16435: [SGD] Remove `sgd_gpu` release test
Due to https://github.com/anyscale/product/issues/4573, ` release/nightly_gpu_tests/sgd_gpu/sgd_gpu_test.py` has been temporarily set to `num_workers=1` (https://github.com/ray-project/ray/pull/16382/) to allow it to pass and test fp16 support. Once the linked issue has been solved, it should be set back to `num_workers=2`.

### PR DESCRIPTION
**Pull request by amogkam**
Ray SGD v1 has been denoted as a deprecated API for a while. This PR fully deprecates Ray SGD v1. An error will be raised if `ray.util.sgd` package is attempted to be imported.

Closes #16435 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
For `ray.data`- it's just this one line change https://github.com/ray-project/ray/pull/24038/files#diff-5a812d24fc3efd599284bb40dcbd2c6627bbe324e1c89a6e623b4dccf8e5de44

**Review by ericl — APPROVED** [review]
Great to see this! Rubber stamping on tests passing.

**Review by matthewdeng — COMMENTED** [review]
This is awesome! Update this file as well? https://github.com/ray-project/ray/blob/master/python/ray/sgd/__init__.py

**Review by matthewdeng — COMMENTED** [review]
LGTM (other than failing tests)

**Review by maxpumperla — APPROVED** [review]
@amogkam this is great! should we maybe have 1-2 links on Ray Train's landing page to an older version of our docs that still have SGD? Like a sidebar.

**Comment by maxpumperla** [comment]
closes #22870

**Comment by amogkam** [comment]
@maxpumperla that's a great idea! I can add that to the landing page and will ping you again to take a look!

**Review by maxpumperla — APPROVED** [review]

**Pull request merged**
