### PR TITLE
[Minor]Run fn in specified io service completely

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
Before we completed the periodical runner, which would dispatch task in io service periodically.
However the first time the function would be invoked in current io service(thread) instead of the specified one.
We make a post in the beginning to make sure that.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @wuisawesome Isn't it fixing the same bug you found?

**Comment by rkooo567** [comment]
All MacOS builds are failing.

**Comment by rkooo567** [comment]
This is the same fix as @wuisawesome's fix; https://github.com/ray-project/ray/pull/15186/files, and it also has issues with the Mac build. Can you guys discuss how to fix this issue?

**Comment by rkooo567** [comment]
Hey @WangTaoTheTonic can you merge the latest master? The build status seems promising.

**Review by rkooo567 — APPROVED** [review]

**Comment by wuisawesome** [comment]
rllib timeout looks unrelated, merging

**Pull request merged**
