### PR TITLE
Revert "[Core] Put pg state to kv store when pg rescheduling (#34467)"

### PR DESCRIPTION
**Pull request by rkooo567**
This reverts commit af018f6639f10393c030e93d9688201483c36623.

## Why are these changes needed?

This is the only pg change we made recently, so I assume it could be related. I am not 100% sure though. Let's revert and see how it goes.

Screen Shot 2023-05-01 at 10 20 57 AM

cc @larrylian 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @larrylian I will monitor the pg_3 for a while and lyk. Please recreate a revert-revert PR!

**Comment by larrylian** [comment]
@rkooo567  resubmit PR: https://github.com/ray-project/ray/pull/34948

**Comment by larrylian** [comment]
@rkooo567   I checked the current situation of test_placement_group_3. There will still be flakey use cases. I think the reason for the error should be "bind: Address already in use". This should have nothing to do with my modification above.

image

**Comment by rkooo567** [comment]
yeah that sounds reasonable. Let me merge this PR again.

**Pull request merged**
