### PR TITLE
[docs][kubernetes] Shift docs into new structure

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

This PR shifts KubeRay docs into the structure introduced in https://github.com/ray-project/ray/pull/27036.
There are no content changes.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
Could you take a look at the [User Guides index page](https://ray--27239.org.readthedocs.build/en/27239/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides.html)? I think it could use a TOC, like [Ray Data has](https://ray--27239.org.readthedocs.build/en/27239/data/user-guide.html).

Oh, I just noticed the content isn't finished yet. Feel free to do later.

**Comment by cadedaniel** [comment]
Why doesn't the ml-example show up in the directory? it's present https://ray--27239.org.readthedocs.build/en/27239/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.html

**Comment by cadedaniel** [comment]
LGTM, I'd approve but I don't have those permissions :)

**Review by cadedaniel — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
> Why doesn't the ml-example show up in the directory? it's present https://ray--27239.org.readthedocs.build/en/27239/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.html

Because I had a typo in the toc.
Thanks for pointing it out -- I fixed it.

**Review by richardliaw — APPROVED** [review]

**Review by wuisawesome — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
I'm pretty sure I'm not the cause of the lint errors -- it's something about pytorch.

**Comment by zhe-thoughts** [comment]
Hi folks really quite note: can we always use `docs` label for docs PRs? Thanks!

**Pull request merged**
