### PR TITLE
Experimental Actor Pool

### PR DESCRIPTION
**Pull request by zhu-eric**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by richardliaw** [comment]
@ericl assigning to you for now to shepherd, feel free to pawn off? @zhu-eric will be in charge of this.

**Review by ericl — APPROVED** [review]
Lgtm. Did you check the test runs?

**Comment by ericl** [comment]
Lint is failing.

**Comment by ericl** [comment]
@zhu-eric Please fix the lint by running scripts/format.sh

**Pull request merged**
