### PR TITLE
[Autoscaler] Update default AMIs to latest versions

### LINKED ISSUE #25588: [docker] Open source GPU docker images fail to start with cuda error
### What happened + What you expected to happen

When starting any of the `nightly` docker images, we run into this:

```
 docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container: unknown.
```

The cause is likely that NVIDIA removed some drivers from their base image:

https://gitlab.com/nvidia/container-images/cuda/-/commit/da52c6cc317ea7f8afcb7d9bf75674ef51e28164?page=2

We should fix the docker image build.

### Versions / Dependencies

Master

### Reproduction script

--

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by amogkam**
Closes https://github.com/ray-project/ray/issues/25588

NVIDIA recently pushed updates to the CUDA image removing support for end of life drivers. Therefore, the default AMIs that we previously had for OSS cluster launcher are not able to run the Ray GPU Docker images.

This PR updates the default AMIs to the latest Deep Learning versions. In general, we should periodically update these AMIs, especially when we add support for new CUDA versions.

I manually confirmed that the nightly Ray docker images work with the new AMI in us-west-2. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
Are there any autoscaler tests that need to be run with these changes?

**Comment by DmitriGekhtman** [comment]
> Are there any autoscaler tests that need to be run with these changes?

Just the manual checks you've already done.

**Review by DmitriGekhtman — APPROVED** [review]
Thanks!

**Review by krfricke — APPROVED** [review]
Thank you very much!

**Pull request merged**
