### PR TITLE
Revert "[Serialization] Update CloudPickle to 1.6.0 (#9694)"

### PR DESCRIPTION
**Pull request by simon-mo**
This reverts commit f0c3910d598e7964a28b4245bd6e4024114bdbd2.

## Why are these changes needed?

Serve is blocked by https://github.com/ray-project/ray/issues/10459, so I propose to revert the cloudpickle upgrade until cloudpickle can work with Pydantic well. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Can you explain more about what and why this pr is blocking serve

**Comment by simon-mo** [comment]
Sure. Serve is planning to use pydantic for its config options. https://github.com/ray-project/ray/pull/10389 But cloudpickle has trouble with Pydantic classes, I documented in the issue linked in the description.

**Comment by simon-mo** [comment]
@rkooo567 another datapoint. The update also broke several rllib tests:
- //rllib:tests/test_io
- //rllib:test_rollout_w_learning
- //rllib:test_rollout_no_learning
- //rllib:test_marwil

Master build: https://github.com/ray-project/ray/runs/1046975986
One commit before: https://github.com/ray-project/ray/runs/1046973687

**Comment by rkooo567** [comment]
@simon-mo Thanks for the info! I will add an issue to continue this task in the future.

**Comment by rkooo567** [comment]
Actually, I saw you made an issue. I will give P2 on the issue

**Pull request merged**
