### PR TITLE
Evaluate debug logging only in debug mode

### PR DESCRIPTION
**Pull request by pcmoritz**
This PR makes it so debugging logs are only evaluated during debugging. We found that for the current code, functions called in debug logging code are evaluated even in release mode (even though nothing is printed).

(see also "Debug Mode" in http://rpg.ifi.uzh.ch/docs/glog.html)

cc @stephanie-wang

### CODE REVIEW

**Comment by pcmoritz** [comment]
cc @guoyuhong

**Comment by robertnishihara** [comment]
It seems undesirable to introduce a new logging macro. Now it's unclear when to use `RAY_LOG(DEBUG)` versus `RAY_DLOG(INFO)`. Also, why would `RAY_DLOG` take a "level" argument?

It may be preferable to just remove all `LOG_DEBUG` statements.

**Comment by pcmoritz** [comment]
`RAY_LOG(DEBUG)` is removed now, so there should be no problems with
clarity. This is the way that glog does it so I assume people would be
familiar with it.

I'm ok with removing some of the debug statements, but many of them seem
useful to me, what do @stephanie-wang and @atumanov think?

**Comment by guoyuhong** [comment]
Yes, current `RAY_LOG(DEBUG)` will do the evaluation but output nothing, which is a waist of resources.

If you don't want to introduce more macros, can the following code be an option? 
```c++
#define RAY_LOG_INTERNAL(level) ::ray::RayLog(__FILE__, __LINE__, level)
#ifndef NDEBUG
#define RAY_LOG(level) RAY_LOG_INTERNAL(RAY_##level)
#else
#define RAY_LOG(level) if (RAY_##level != RAY_DEBUG) RAY_LOG_INTERNAL(RAY_##level)
#endif
```

**Comment by robertnishihara** [comment]
@pcmoritz I prefer `RAY_LOG(DEBUG)` to `RAY_DLOG(INFO)`. However, it's OK if that's the standard glog way to do it.

**Comment by raulchen** [comment]
I think this solution may not be preferable. Because if we do this, we cannot enable debug logging without recompiling code.

I think the goals we want to achieve are:
1) determine logging level at runtime, which gives us the flexibility to switch logging level without recompiling code.
2) avoid unnecessary computation when the target logging level isn't enabled.

I discussed with @guoyuhong offline, the best solution would be:
```
#define RAY_LOG(level) if (CurrentLoggingLevel() < RAY_##level) RAY_LOG_INTERNAL(RAY_##level)
```

By doing this, if the target logging level isn't enabled, there will be only a condition check.

**Comment by pcmoritz** [comment]
@raulchen I agree and will change the PR accordingly

**Comment by pcmoritz** [comment]
closed in favor of https://github.com/ray-project/ray/pull/2869

**Pull request closed without merging**
