### PR TITLE
[autoscaler] GCP docs

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

Update docs to mention GCP support and examples. @richardliaw @hartikainen 

https://github.com/ray-project/ray/issues/2207

### CODE REVIEW

**Comment by richardliaw** [comment]
You should mention that they need to create their own `gcp-project` (see the example-full.yaml), as it doesn't work right out of the box...

**Review by hartikainen — COMMENTED** [review]
Looks good!

**Comment by ericl** [comment]
Added

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Relevant tests passed.

**Pull request merged**
