### PR TITLE
[ci] fix mac machines

### PR DESCRIPTION
**Pull request by can-anyscale**
- The current mac machines is getting into a weird state where one of the package installation is malformed, which breaks subsequent CI runs. Fix it by doing a fresh pip installation: https://buildkite.com/ray-project/postmerge-macos/builds/558#018eed8f-8190-439c-9cfb-8b0bb709c078/337-857
- Also add the constraint file to one of the pip installation command

This should have no impact on other parts of CI which always install packages on a fresh environment.

Test:
- CI
- https://buildkite.com/ray-project/postmerge-macos/builds/568

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]

**Review by khluu — APPROVED** [review]

**Comment by can-anyscale** [comment]
the `packaging` version in the requirements_compiled file somehow breaks tests

**Comment by khluu** [comment]
> the `packaging` version in the requirements_compiled file somehow breaks tests
I think it's because of the new conda version? 
`conda 24.1.2 requires packaging>=23.0, but you have packaging 21.3 which is incompatible.`

**Comment by can-anyscale** [comment]
@khluu nice catch!

**Comment by can-anyscale** [comment]
surprisingly so many things don't work with the packages in the constraint files; i just restart the macos to get them out of weird states for now ;)

**Pull request closed without merging**
