### PR TITLE
[Java] Add Plasma Free to Java code path

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
Add Plasma Free to Java code path.

This PR will wait until @raulchen 's refactor code merged.

Since `ray.internal.free` is tested in multi-node scenario, in Java, the test can be simpler in one-box mode.

### CODE REVIEW

**Comment by raulchen** [comment]
@guoyuhong my PR was merged. could you rebase this PR?

**Comment by guoyuhong** [comment]
@raulchen Rebased.

**Review by raulchen — COMMENTED** [review]
Thanks, I left a few small comments.

**Comment by guoyuhong** [comment]
@raulchen It looks like the java test fails.

**Comment by raulchen** [comment]
@guoyuhong the test is hanging in non-raylet mode. I think you can just skip your test for legacy ray. Search `Assume.assumeTrue` in the codebase to see how to do that. To test it locally, you can edit `ray.config.ini` and change `use_raylet` to false.

**Comment by jovan-wong** [comment]
It's a refs for u to ignore non raylet mode:
https://github.com/ray-project/ray/blob/master/java/test/src/main/java/org/ray/api/test/ResourcesManagementTest.java#L52

**Review by jovany-wang — APPROVED** [review]
Looks good. It can be merged once tests pass.

**Comment by robertnishihara** [comment]
Looks good to me also.

**Pull request merged**
