### PR TITLE
[Data] [Docs] Adding in missing typing imports

### PR DESCRIPTION
**Pull request by omatthew98**
## Why are these changes needed?
Adds more imports that were missing in #44203. Example failure here: https://buildkite.com/ray-project/postmerge/builds/3659#018e615b-eeeb-4a7a-8aed-b5cd139eb64b

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Comment by omatthew98** [comment]
Postmerge test run here for sanity checking: https://buildkite.com/ray-project/postmerge/builds/3664

**Review by scottjlee — APPROVED** [review]

**Comment by can-anyscale** [comment]
Can you help add a line here https://github.com/ray-project/ray/blob/master/ci/pipeline/determine_tests_to_run.py#L291 for .rst file so that permerge trigger the doc tests, thankkks

**Review by bveeramani — APPROVED** [review]
LGTM. Thanks Matthew!

**Pull request merged**
