### PR TITLE
[Azure][Autoscaler] Allow current user to use Docker

### LINKED ISSUE #13711: Got permission denied while trying to connect to the Docker daemon when deploying a ray-cluster in Azure
### What is the problem?

Splitting from [issue 13599](https://github.com/ray-project/ray/issues/13599), I'm unable to install a ray cluster in Azure.

```
$ ray up ~/sources/yaps/example-full.yaml --no-config-cache
Cluster: <hidden>

Checking Azure environment settings
2021-01-26 14:52:01,797 INFO config.py:39 -- Using subscription id: <hidden>
2021-01-26 14:52:01,797 INFO config.py:53 -- Creating/Updating Resource Group: <hidden>
No head node found. Launching a new cluster. Confirm [y/N]: y

Acquiring an up-to-date head node
  Launched a new head node
  Fetching the new head node
  
<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: <hidden>
ssh: connect to host <hidden> port 22: Connection refused
    SSH still not available (SSH command failed.), retrying in 5 seconds.
...
ssh: connect to host <hidden> port 22: Connection refused
    SSH still not available (SSH command failed.), retrying in 5 seconds.
Warning: Permanently added '<hidden>' (ECDSA) to the list of known hosts.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

 13:56:20 up 2 min,  1 user,  load average: 2.93, 1.01, 0.37
Shared connection to <hidden> closed.
    Success.
  Updating cluster configuration. [hash=b6e4a35cf161a0aeadf43c85d921602da74217c1]
  New status: syncing-files
  [2/7] Processing file mounts
Shared connection to <hidden> closed.
Shared connection to <hidden> closed.
  [3/7] No worker file mounts to sync
  New status: setting-up
  [4/7] Running initialization commands
Warning: Permanently added '<hidden>' (ECDSA) to the list of known hosts.
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

Connection to <hidden> closed.
  [5/7] Initalizing command runner
Shared connection to <hidden> closed.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=rayproject%2Fray-ml&tag=latest-gpu: dial unix /var/run/docker.sock: connect: permission denied
Shared connection to <hidden> closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.
```

### Reproduction (REQUIRED)

OS: ubuntu 18.02
Python: 3.7.1
VirtualEnv: [requirements.txt](https://github.com/ray-project/ray/files/5873812/requirements.txt)

example-full.yaml is the same provided by ray team (except by the cluster-name/resource_group/subscription_id fields)

e.g., ` pip install ray azure-cli azure-mgmt-compute==14.0.0`

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [  ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* The default user for the provided Azure VM Image does not haver docker permissions.
* This adds an initialization command that tries (best-effort) to give the current user those permissions.

## Related issue number

Closes #13711

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ijrsvt** [comment]
@gramhagen Can you look at this?

**Review by AmeerHajAli — APPROVED** [review]
LGTM. @gramhagen , @omnific9  @GiovanniGatti, does this solve your issue?

**Comment by omnific9** [comment]
@AmeerHajAli thanks for pinging. This solves the first problem mentioned in https://github.com/ray-project/ray/issues/13711 but does not seem to solve the second problem brought up by @richardlin047 , which I'm also experiencing. @ijrsvt 's proposed fix to change `setup_commands:` into `setup_commands: []` may work, but I've not tried it yet. I can give that a shot and get back.

**Comment by gramhagen** [comment]
this doesn't seem completely reliable, I ran it once and it work and the second time I got the same permission error. I think it's basically a race condition that succeeds if the ssh runner re-establishes a connection. would be helpful if we could force it to do that (the sleep hack is one way I guess).

i'm also worried that the azure node provider won't be able to access the managed service identity inside a docker container, so that's what I'm checking now.

**Comment by gramhagen** [comment]
Finally got a version working. I haven't found anything more reliable than the sleep hack, one change to the file_mounts is also needed because the user in docker is `ray` not `ubuntu`

```
file_mounts: {
     "~/.ssh/id_rsa.pub": "~/.ssh/id_rsa.pub"
}

initialization_commands:
    # get rid of annoying Ubuntu message
    - touch ~/.sudo_as_admin_successful
    # allow calling docker without sudo
    - sudo usermod -aG docker $USER
    - sleep 10

# List of shell commands to run to set up nodes.
setup_commands: []

# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - pip install azure-cli-core==2.22.0 azure-mgmt-compute==14.0.0 azure-mgmt-msi==1.0.0 azure-mgmt-network==10.2.0
```

the only irritating part now is the logs are filled with a repeated info level notification about the MSI token being in the cache. should be pretty easy to adjust the log level for msrestazure package. but that's just a nice to have.

**Comment by omnific9** [comment]
I managed to get my scripts working with this fix. However, I have to point out that this master branch does not work with the latest pip release, i.e. 1.2.0

I had to carve out this fix and the "setup_commands" section and copy/paste them onto my 1.2.0 release branch to get it to work.

Would be great if this can be addressed when 1.3.0 releases.

**Comment by omnific9** [comment]
@ijrsvt I got the following error when running the master script in 1.2.0:

```
Traceback (most recent call last):
  File "~/ray/venv/bin/ray", line 10, in <module>
    sys.exit(main())
  File "~/python3.8/site-packages/ray/scripts/scripts.py", line 1519, in main
    return cli()
  File "~/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/python3.8/site-packages/ray/scripts/scripts.py", line 887, in up
    create_or_update_cluster(
  File "~/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 224, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "~/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 299, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "~/python3.8/site-packages/ray/autoscaler/_private/azure/node_provider.py", line 298, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "~/python3.8/site-packages/ray/autoscaler/_private/azure/config.py", line 20, in bootstrap_azure
    config = _configure_key_pair(config)
  File "~/python3.8/site-packages/ray/autoscaler/_private/azure/config.py", line 109, in _configure_key_pair
    config[node_type]["azure_arm_parameters"]["adminUsername"] = ssh_user
KeyError: 'azure_arm_parameters'
```

This was because in the master script, head_node is {} and doesn't have an "azure_arm_parameters" key, which 1.2.0 was expecting.

I had to switch to the 1.2.0 script and replace these sections to get it to work:

```
initialization_commands:
    # get rid of annoying Ubuntu message
    - touch ~/.sudo_as_admin_successful
    - sudo usermod -aG docker $USER; sleep 10

# List of shell commands to run to set up nodes.
setup_commands:
    - (which conda && echo 'eval "$(conda shell.bash hook)"' >> ~/.bashrc) || true
    # - echo 'conda activate py37_pytorch' >> ~/.bashrc
    - (conda activate py37_tensorflow &> /dev/null && echo 'conda activate py37_tensorflow' >> ~/.bashrc) || true
    - which ray || pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"
```

**Comment by omnific9** [comment]
Also, this worked for me:

```
setup_commands:
    # Note: if you're developing Ray, you probably want to create an AMI that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    - (which conda && echo 'eval "$(conda shell.bash hook)"' >> ~/.bashrc) || true
    # - echo 'conda activate py37_pytorch' >> ~/.bashrc
    - (conda activate py37_tensorflow &> /dev/null && echo 'conda activate py37_tensorflow' >> ~/.bashrc) || true
    - which ray || pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"
```

But this did not:

```
setup_commands:
    # Note: if you're developing Ray, you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # To run the nightly version of ray (as opposed to the latest), either use a rayproject docker image
    # that has the "nightly" (e.g. "rayproject/ray-ml:nightly-gpu") or uncomment the following line:
    - echo 'eval "$(conda shell.bash hook)"' >> ~/.bashrc
    - echo 'conda activate py37_tensorflow' >> ~/.bashrc
    - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"
```

**Comment by ijrsvt** [comment]
@omnific9 Just to clarify, the setup_commands on GitHub (latest master) work with the fixes from this PR?

**Comment by omnific9** [comment]
@ijrsvt no, not for 1.2.0

**Comment by ijrsvt** [comment]
@omnific9 `1.3.0` has _not_ been released yet, but it should be released very soon.

**Comment by omnific9** [comment]
@ijrsvt may I suggest creating a develop branch to merge code into prior to a release?

As a user, it's pretty confusing that the latest ray version is 1.2.0 but the default script on the master branch is for 1.3.0 and doesn't work for 1.2.0

**Comment by ijrsvt** [comment]
@omnific9 We try not to make many breaking changes between Ray versions, but the change with `azure_arm_parameters` was mostly due to the migration to multi-node-type YAMLs

**Pull request merged**
