### PR TITLE
Add serialization/deserialization for MultiBinary space

### PR DESCRIPTION
**Pull request by alexandrelarouche**
## Why are these changes needed?
`MultiDiscrete([2] * n)` is supported, but not equivalent to `MultiBinary`. They both give vectors that look like `[0,1,0]` if `n = 3`. But it seems RLLib's internal comprehension of the size of MultiDiscrete spaces are `2 * n`. This is true for every size except `[2]`Trying to minimally reproduce the bug right now, but I had this fix implemented already in my version of `ray`.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

I've tested saving an environment with MultiBinary spaces and loading it. It works.

### CODE REVIEW

**Comment by ArturNiederfahrenhorst** [comment]
@Quoding Thanks for this PR! Can you reproduce the bug with a testcase in https://github.com/ray-project/ray/blob/43e69dda6cbfe03d6c339a926944f76b0c0f630b/rllib/utils/tests/test_serialization.py?

**Comment by Quoding** [comment]
Gonna look into it. Give you news once I do.

**Comment by Quoding** [comment]
@ArturNiederfahrenhorst 
Hey, just re-read your question. The "bug" I encountered has no link to the serialization process. The addition I made is a fix for another behavior I noticed when RLLib interacted with my own code. I have had no luck recreating the bug with a simple test, so I think it is more complex than I initially thought. I'm working on finding the reason right now, but it seems the entry space when creating dummy batches for the rolloutworker are twice as big as they need to be, my guess is the `[2] * n`

My things set up work with MultiBinary, however, so I've added functionality that was limiting me to use them in this commit.

**Comment by Quoding** [comment]
I found the offending line for the original problem. Working on a fix as well for it.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @Quoding , can you confirm that this is also resolved by https://github.com/ray-project/ray/pull/31025?

**Comment by ArturNiederfahrenhorst** [comment]
Closing because I think this is resolved by https://github.com/ray-project/ray/pull/31025
Feel free to reopen if not.

**Pull request closed without merging**
