### PR TITLE
[Serve] Cherry pick #37671

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

This change cherry picks #37671 into Ray 2.6.2.

## Related issue number

N/A

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
     - This change is tested by `test_deployment_function_node_build` in `test_deployment_graph_build.py`.

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
@shrekris-anyscale @edoakes could you help clarify why this is a release blocker? The issue https://github.com/ray-project/ray/issues/37669 is marked as P1. Thanks

**Comment by edoakes** [comment]
It's not a release blocker; P1 is an appropriate label. This is a "nice to have" bugfix for a patch release.

**Comment by zhe-thoughts** [comment]
Given the tight timeline of 2.6.2 I don't think we should pick this one. 

But @edoakes @shrekris-anyscale let me know if you agree. Thanks

**Comment by edoakes** [comment]
@zhe-thoughts that's fine w/ me

**Pull request closed without merging**
