### PR TITLE
[Metrics] Fix the dead actors are not counted properly when the driver exits

### LINKED ISSUE #30655: [Core/Metrics] Actor DEAD count is incorrect when the driver exits.
### What happened + What you expected to happen

Currently, due to a bug, GCSActors are GC'ed as soon as the driver exits which makes the DEAD count of actor metrics incorrect. This is the correctness issue, so it'd be ideal to fix (also impact of the fix is low).

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by rkooo567**
Signed-off-by: SangBin Cho <rkooo567@gmail.com>

## Why are these changes needed?

It's incorrect because as soon as the job is terminated we garbage collect GcsActor. It fixes the issue by never decrementing the DEAD count when the GCSActor is GC'ed. This is safe because we don't allow to transit states from DEAD -> other states. 

It is a replacement of https://github.com/ray-project/ray/pull/30523

## Related issue number

Closes https://github.com/ray-project/ray/issues/30655

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
You'll probably have to fix some unit tests. Also, not a release blocker?

**Comment by rkooo567** [comment]
Oh I thought you agreed on cherry picking this. I am okay not to cherry pick it although I prefer to. I will fix the unit test soon.

**Comment by rkooo567** [comment]
@ericl looks like none of unit tests failed actually?

**Comment by ericl** [comment]
I see, probably existing C++ unit tests didn't cover it. I think it would be great to have at least one (even very basic) test in gcs_actor_manager_test.cc. There is already one that checks the stats counts using `CountFor()`, though it didn't cover job exit so didn't catch this change.

**Comment by rkooo567** [comment]
Got it. Working on it...

**Comment by rkooo567** [comment]
cc @rickyyx

**Review by rickyyx — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/gifs/thumbs-up-bob-odenkirk-golden-globes-2016-3o6UB0WHErPubNDTfa">GIPHY</a></div>

**Pull request merged**
