### PR TITLE
Add runtime_env hash to scheduling class (proper fix for runtime env in scheduler bug)

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This PR supercedes the fix from https://github.com/ray-project/ray/pull/17163.
Part of https://github.com/ray-project/ray/issues/17154

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
make sure to run scalability envelop:
- https://buildkite.com/ray-project/periodic-ci
- New Build, options, env var
```
RAY_BRANCH="TEST_WHEEL_BRANCH_HERE"
RELEASE_TEST_SUITE="weekly"
FILTER_FILE="benchmarks"
FILTER_TEST="distributed"
```
see all the env var def at https://github.com/ray-project/ray/blob/dad8db46e1ed2acdb8e9b29b1c91b72c2800d60d/release/config_generator.html#L57-L62

**Comment by ericl** [comment]
https://buildkite.com/ray-project/periodic-ci/builds/611

**Comment by ericl** [comment]
```




[INFO 2021-07-22 10:55:30,650] e2e.py: 336  Latest 10 commits for branch sched-cls: ['0b0b63ff71dfb2aab39812d9dc1767973b5aced0', '3206bacdeb01e0c790c03ead0fbde1840b006b00', 'fa2b62d5dd4fe6c86f26299a954c1b236c2c5a36', 'a550eb3e978e82fcf40157f328160a2d86469f5d', 'b5194ca9f9804f9880b4f59e42d9e0facf5fd891', 'afd59be8ca87bd0e63c20aa183dede3491e2c86e', '64874e18776ce0ce0ae39fd51e46938c18fd883e', '250f0c24e08b26355b872fe550ac24f0e327c7d2', 'e881c6cff8d95e0e8d03977c4003a770cd886dab', 'dad8db46e1ed2acdb8e9b29b1c91b72c2800d60d']
  | Traceback (most recent call last):
  | File "release/e2e.py", line 1693, in <module>
  | raise RuntimeError(f"Could not find wheels for "
  | RuntimeError: Could not find wheels for Ray 2.0.0.dev0, branch sched-cls
 

<br class="Apple-interchange-newline">
```

@simon-mo how do you build wheels?

**Comment by simon-mo** [comment]
`git push upstream test_wheels/sched-cls`

**Comment by ericl** [comment]
Hmm @simon-mo it failed again https://buildkite.com/ray-project/periodic-ci/builds/625#231ef6f9-73fb-487e-bc99-2ad389c3b90f

Though the wheels build did pass: https://buildkite.com/ray-project/ray-builders-branch/builds/2495

**Comment by simon-mo** [comment]
the name didn't match, the wheels are uploaded to `sched-cls` branch directory but the release tests were launched under `RAY_BRANCH="test_wheels/sched-cls"`

**Comment by ericl** [comment]
https://buildkite.com/ray-project/periodic-ci/builds/635

**Comment by simon-mo** [comment]
looking good!

**Comment by ericl** [comment]
Hmm, I'm seeing issues like
```
Launching actors:  66%|██████▋   | 6645/10000 [00:06<00:04, 731.90it/s]2021-07-23 11:55:54,603	WARNING worker.py:1198 -- WARNING: 324 PYTHON workers have been started on a node of the id: f600bd5e5ff624dd6f54b68c7a18d71c984995c213d1eefacdc1780a and address: 172.31.76.222. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
```

Is this the original issue that the previous fix was addressing?

**Comment by simon-mo** [comment]
no this large number of pending workers warning is a known issue before and after my fix. My fix was mainly addressing this test/desired behavior
https://github.com/ray-project/ray/blob/8db61569f11685c816e2cbfb2c01fc45c3164f7c/python/ray/tests/test_runtime_env_complicated.py#L579

**Comment by simon-mo** [comment]
but 
```
(raylet, ip=172.31.27.23)   File "/home/ray/anaconda3/lib/python3.7/socketserver.py", line 466, in server_bind
(raylet, ip=172.31.27.23)     self.socket.bind(self.server_address)
(raylet, ip=172.31.27.23) OSError: [Errno 98] Address already in use
```
do seem like excessive number of workers has been started, @clarkzinzow was originally debugging the scalability test and saw bunch of `redis max client reached` error.

the tl;dr is that there should be some pending actors/too many workers error but not _too_ many. the error seems to indicating we are starting too many and socket failed to find, redis failed to connect, etc.

**Pull request closed without merging**
