### PR TITLE
Add --rm to docker run for Jenkins tests.

### PR DESCRIPTION
**Pull request by shaneknapp**
## What do these changes do?

help docker clean up after itself when done testing

## Related issue number

nope

### CODE REVIEW

**Comment by robertnishihara** [comment]
I'm confused about how this differs from the default behavior. Doesn't `docker run` always delete the container when the script finishes?

**Comment by shaneknapp** [comment]
from:  https://docs.docker.com/engine/reference/run/#clean-up---rm

'''By default a container’s file system persists even after the container exits. This makes debugging a lot easier (since you can inspect the final state) and you retain all your data by default. But if you are running short-term foreground processes, these container file systems can really pile up. If instead you’d like Docker to automatically clean up the container and remove the file system when the container exits, you can add the --rm flag:'''

**Comment by pcmoritz** [comment]
Thanks for the fix! I think you also need to add the flag in https://github.com/shaneknapp/ray/blob/219e2e730205ab76e72d2b9a191656b3a0aad216/test/jenkins_tests/multi_node_docker_test.py

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
actually, i don't think that the --rm and -d flags will work in a way that we expect.   from the docs (https://docs.docker.com/engine/reference/run/#detached--d):

'''Detached (-d)
To start a container in detached mode, you use -d=true or just -d option. By design, containers started in detached mode exit when the root process used to run the container exits, unless you also specify the --rm option. If you use -d with --rm, the container is removed when it exits or when the daemon exits, whichever happens first.'''

**Comment by robertnishihara** [comment]
Just reverted the changes to the Python launcher. Let's get the original commit merged and then figure out the Python part.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
