### PR TITLE
Revert "[Datasets] Arrow 7.0.0+ Support: Use Arrow IPC format for pickling Arrow data to circumvent slice view buffer truncation bug. (#29055)"

### PR DESCRIPTION
**Pull request by clarkzinzow**
This reverts commit c1d62d46495f0157faf3168aa87eed350802e10f.

This is breaking the Windows build: https://buildkite.com/ray-project/oss-ci-build-branch/builds/365#0183ada0-8558-4502-9298-7e0bed873e23

### CODE REVIEW

**Review by c21 — APPROVED** [review]

**Review by scv119 — APPROVED** [review]

**Review by jianoaix — APPROVED** [review]

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Are the dataset test breakages expected?

**Comment by clarkzinzow** [comment]
@ericl They are not, no, so we shouldn't merge this quite yet. Let me push up some fixes.

**Comment by rkooo567** [comment]
should I merge it? It looks like the windows test is broken.

**Comment by rkooo567** [comment]
Seems to be okay to merge based on the CI result.

**Pull request merged**
