### PR TITLE
[core][release] Improve many_tasks test

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

#28926 has been flaky. 
However, it wasn't clear during the test run if all tasks have been running and scheduled (the current test logic checks for resources usage). The test might be failing with false negatives. 

## Related issue number
#28926 

## Checks

Will be triggering a run on `many_tasks` to see how this looks like. 

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Release tests here: https://buildkite.com/ray-project/release-tests-pr/builds/16865

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
it is a test-only change right? Should I merge it?

**Comment by rickyyx** [comment]
> it is a test-only change right? Should I merge it?

Yeah - test only changes but let me make sure the test passing. I will remove the tag when so.

**Comment by rickyyx** [comment]
Merge with master - ready to be merged.

**Comment by rickyyx** [comment]
See https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_wFz4xw3sLVWv97hLrQQwK1H9?drivers-section=deployments&command-history-section=command_history for an example of how the API helps.

**Comment by rickyyx** [comment]
Release test ehre: https://buildkite.com/ray-project/release-tests-pr/builds/18531#0183f184-9279-4af0-b951-d58936ec8ddf

**Comment by scv119** [comment]
let's hold off this until we fixed many_tasks in master :)

**Pull request merged**
