### PR TITLE
Ray Job Submit Omegaconf support

### PR DESCRIPTION
**Pull request by joncarter1**
This PR proposes adding native support for [OmegaConf](https://omegaconf.readthedocs.io/en/latest/index.html) syntax in runtime environment YAMLs used by the Ray job submit CLI. This can be used to supercharge the runtime environment without needing to resort to the Jobs API.

A simple example `runtime.yaml` using omegaconf syntax is as follows:
```
py_modules: ${config.code_dir}/my_pkg # Variable interpolation
env_vars:
  USER: ${oc.env:USER} # Reading from env var

config:
  code_dir: ${oc.env:HOME}
```
where all keys under `config` are deleted during the parsing phase. This can be used with the Job CLI as before with:   
`ray job submit --runtime-env runtime.yaml`

[Custom OmegaConf resolvers](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html#custom-resolvers) can also be invoked using `config.resolvers` such as in [`ray/dashboard/modules/tests/test_config_files/omegaconf/advanced_oc_runtime_env.yaml`](https://github.com/joncarter1/ray/blob/dashboard/omegaconf-support/dashboard/modules/tests/test_config_files/omegaconf/advanced_oc_runtime_env.yaml). When coupled with RuntimeEnvPlugins this can elegantly enable complex behaviour at runtime.

Before I go any further with this PR (docs etc.) I'd like to ascertain the following:
1. That this is a desirable feature.
2. If so, how it should be bundled into Ray distributions e.g. into ray[default]?
3. Any strong opinions on the nomenclature used (`config`/`config.resolvers`)

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
Hi @joncarter1, thanks for the contribution! My main concern is that this adds complexity while only benefiting a very small percentage of users.  If users need OmegaConf, they can always parse their files outside of Ray before passing them to Ray, so I don't see why it should happen within Ray.  What are your thoughts?

**Comment by joncarter1** [comment]
@architkulkarni that’s a very fair counter point.

Indeed, this is essentially just a port of my own CLI tool that works exactly as you described:
`ray job submit —runtime-env-json $(ocj runtime.yaml)`
where ocj = my own Omegaconf to JSON converter. This enables me to neatly configure things such as a custom secrets plug-in that interacts with Hashicorp Vault.

The motivation for the PR was simply that I’ve found this to be super helpful in my workflows and so making it native it would increase awareness of the flexibility of the Submit CLI. (Something that took me a while to grasp!).

I totally understand the complexity trade off concerns though. Perhaps the solution simply lies in improving the documentation, particularly with advanced examples.

Your call! :)

**Comment by architkulkarni** [comment]
@joncarter1 Thanks for sharing the use case!  It makes sense, but I still think it's cleanest to have this logic outside of Ray.  

I think you're right that the best approach is to improve the docs, we'd be extremely interested in any feedback you have here!  Please feel free to share feedback here or in another issue, or directly open a docs PR.

**Comment by joncarter1** [comment]
@architkulkarni Agreed! I'll close down this PR but I'm sure I'll be back :)

**Pull request closed without merging**
