### PR TITLE
Revert "[ci] Reduce instance sizes for tests that require less resour…

### PR DESCRIPTION
**Pull request by scv119**
…ces [all_tests] (#29295)"

This reverts commit d0faec12859dd69061740e87b3d2c0b89408aaf1.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
image

**Review by rickyyx — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/southpark/">South Park</a> on <a href="https://giphy.com/gifs/southparkgifs-3o6Ztc92bcyzaGtPRC">GIPHY</a></div>


But maybe @krfricke will have more thoughts on this.

**Comment by rickyyx** [comment]
Oh didn't know revert could have conflict. Good catch.

**Comment by krfricke** [comment]
Should have been fixed by https://github.com/ray-project/ray/commit/b823bdf9ae341a8b073ebd1677fde6fe17851ff8 please wait with revert until that build is through

**Review by krfricke — CHANGES_REQUESTED** [review]
Blocking merge for now, let's wait until the fix build completed. feel free to override if problems persist.

**Comment by scv119** [comment]
as what @krfricke said :)

**Pull request closed without merging**
