### PR TITLE
[RLlib] Fit ES and ARS results dict to rest of RLlib, enable results to be fetched in release tests and and CI learning tests

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
## Why are these changes needed?

At the moment, ES humanoid release test does not pass even though rewards are high enough.
This is because we don't make use of our usual metrics construction in ES.
This PR makes it so that ES returns the reward from evaluation workers like other algorithms do.
This is needed because our test utils that are used for release tests expect the mean reward to be at the same place for all algorithms.

### CODE REVIEW

**Review by avnishn — APPROVED** [review]
sgtm run the release test from here and post when it passes !

**Comment by ArturNiederfahrenhorst** [comment]
Yep, workers are taking a while to be acquired these days..

**Review by kouroshHakha — APPROVED** [review]

**Comment by ArturNiederfahrenhorst** [comment]
@kouroshHakha Still running release tests. I can ping you when they succeed if you like.

**Comment by ArturNiederfahrenhorst** [comment]
Related: https://github.com/ray-project/ray/issues/35461

**Comment by kouroshHakha** [comment]
The failing test was caused by SIGTERM which we usually count towards infra failure. Merging now as the other 3 test are passing.

**Review by kouroshHakha — APPROVED** [review]

**Pull request merged**
