### PR TITLE
Revert "Revert "[ci/release] Move all release tests to use Ray jobs instead of SDK commands""

### PR DESCRIPTION
**Pull request by krfricke**
Reverts ray-project/ray#30956

### CODE REVIEW

**Comment by krfricke** [comment]
Build 1: https://buildkite.com/ray-project/release-tests-pr/builds/23332#_
Build 2: https://buildkite.com/ray-project/release-tests-pr/builds/23355

**Review by simon-mo — APPROVED** [review]

**Comment by rkooo567** [comment]
Are we confident this will work 100%? Why don't we migrate gradually? Like moving the wholes suites to job based executor first

**Review by rkooo567 — CHANGES_REQUESTED** [review]
Request change until we resolve the comment ^.

**Comment by krfricke** [comment]
Yeah this is moving gradually (we default to sdk_command).

It's currently not working for some tests, e.g. https://github.com/ray-project/ray/issues/31123 has to be resolved first

**Comment by krfricke** [comment]
Just to be clear, the relevant line (which was different in the original PR) is this:

```
DEFAULT_RUN_TYPE = "sdk_command"
```

**Review by rkooo567 — APPROVED** [review]
sgtm. do you migrate ml tests first? Feel free to merge it when it passes!

**Comment by krfricke** [comment]
A recent run of release tests passed (all failures are also failing on master): https://buildkite.com/ray-project/release-tests-pr/builds/24762

The default is to stay with sdk runner, so I'll merge this PR and we can the migrate the other tests piece by piece.

**Pull request merged**
