### PR TITLE
Clean up CODEOWNERS

### PR DESCRIPTION
**Pull request by aslonnie**
times change

### CODE REVIEW

**Comment by aslonnie** [comment]
cc @richardliaw @zhe-thoughts

**Review by anyscalesam — APPROVED** [review]

**Review by can-anyscale — APPROVED** [review]

**Comment by zhe-thoughts** [comment]
@aslonnie I understand the reasoning. But let's tag the people that we are removing as code owners and give them some time to acknowledge (that they are indeed no longer actively working code of those modules)

@ericl @scv119 @architkulkarni @amogkam @suquark @stephanie-wang

**Comment by aslonnie** [comment]
I don't think I changed @stephanie-wang

fwiw, @anyscalesam is the one actually wanting to do this; I am just his hands helping doing the edit.

**Comment by aslonnie** [comment]
for the reasoning of the change, the main thing is that non-active codeowners are blocking PRs.

**Comment by aslonnie** [comment]
but I can wait for a week. :)

**Comment by zhe-thoughts** [comment]
I suggest we make two separate PRs:
1. Adding some code owners (e.g. @aslonnie for some modules), to solve the "PRs being blocked issue"
2. Remove some inactive code owners

**Pull request merged**
