### PR TITLE
Add get_metadata() for workflow

### PR DESCRIPTION
**Pull request by lchu6**
## Why are these changes needed?

Add the functionality to retrieve metadata for a workflow or workflow step.

Design:
- Similar to `get_output`, this will either return the metadata for workflow (`workflow.get_metadata(workflow_id)`) or the metadata for a specific step (`workflow.get_metadata(workflow_id, step_id)`)
- Exceptions will only be raised if workflow id or step id not exist. Canceled job, running job, etc. will return proper metadata by retrieving information from checkpoint. See [here](https://github.com/ray-project/ray/blob/8c8ca609d7fb65ee0032ad2a352f6332f46f466f/python/ray/workflow/tests/test_metadata_get.py#L67) for more details.
- Returned metadata is an aggregated result from multiple checkpoint files based on previous [discussion](https://github.com/ray-project/ray/issues/17090#issuecomment-920481789). The aggregation logic is [here for step metadata](https://github.com/ray-project/ray/blob/8c8ca609d7fb65ee0032ad2a352f6332f46f466f/python/ray/workflow/workflow_storage.py#L451) and [here for workflow metadata](https://github.com/ray-project/ray/blob/8c8ca609d7fb65ee0032ad2a352f6332f46f466f/python/ray/workflow/workflow_storage.py#L484) which can be tuned with further discussion.

Example:
```python
>>>  user_step_metadata = {"k1": "v1"}
>>>  user_run_metadata = {"k2": "v2"}
>>>  step_name = "simple_step"
>>>  workflow_id = "simple"

>>>  @workflow.step
>>>  def simple():
>>>      return 0

>>>  simple.options(name=step_name, metadata=user_step_metadata).step().run(workflow_id, metadata=user_run_metadata)

# get workflow-level metadata
>>>  workflow.get_metadata("simple")
{'status': 'SUCCESSFUL',
 'user_metadata': {'k2': 'v2'},
 'stats': {'start_time': 1634173413.116535, 'end_time': 1634173413.149051}}

# get step-level metadata
>>> workflow.get_metadata("simple", "simple_step")
{'name': '__main__.simple',
 'step_type': 'FUNCTION',
 'workflows': [],
 'max_retries': 3,
 'workflow_refs': [],
 'catch_exceptions': False,
 'ray_options': {},
 'user_metadata': {'k1': 'v1'},
 'stats': {'start_time': 1634173413.131262, 'end_time': 1634173413.1347651}}
```

## Related issue number

https://github.com/ray-project/ray/issues/17090

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by fishbone — CHANGES_REQUESTED** [review]
Overall looks good to me. Some comments there. We should also update the documentation to include the feature there (ray/doc/source/workflows/)

**Comment by lchu-ibm** [comment]
@iycheng one clarification on nested workflow:

```python
@workflow.step
def inner():
    time.sleep(2)
    return 10

@workflow.step
def outer():
    time.sleep(2)
    return inner.step()
```

Say above nested workflow start at T0 (at 0 second) and ends at T4 (completed in 4 seconds).  What is workflow's convention here re. the "completion" of step `outer`?  Does it complete at T2 when it returns the inner workflow (i.e. it finishes right before the inner starts),  or it finishes at T4 when inner finishes (i.e. inner is part of the outer so outer only finishes when inner finishes)?

intuitively my original thought was T4, but I think from workflow point of view, outer finishes at T2 because the output is generated at T2 so it is literally completed.  So now I think maybe we take T2 as its completion?  What my metadata outputs is: workflow stats: 0 - 4, outer stats: 0 - 2, inner stats: 2 - 4.

**Comment by lchu-ibm** [comment]
@iycheng while I added tests for virtual actor, I noticed that `def options()` for actor method was defined not implemented. So I added the implementation in https://github.com/ray-project/ray/pull/19372/commits/f0dd2584ceada038bcd64cbf336075f8f2401dd1

Let me know if you want me to make any modifications. 

Corresponding test:
https://github.com/ray-project/ray/pull/19372/commits/c010426e38a3692f887cb4fa751378a0416b0ae4#diff-6cb6d4052e294f8c8cc901ed0e56dd4dbf493ba0db140ab2d9f029f5788e7c71R217-R243

**Comment by iycheng** [comment]
Sorry, I actually forgot virtual actor doesn't support options for now, and thanks for adding the support for this.

**Review by fishbone — APPROVED** [review]
@lchu-ibm  could you have a follow up PR to update the documentation?

**Pull request merged**
