### PR TITLE
[CI] Add missing release test infra dependencies.

### PR DESCRIPTION
**Pull request by aslonnie**
Also sort in alphabetical order and recompile requirements.

### CODE REVIEW

**Review by can-anyscale — COMMENTED** [review]
Hmm, is this for unit-test or release tests. They are passing on CI so why they need these dependencies?

**Review by can-anyscale — CHANGES_REQUESTED** [review]
Sending back mostly just for questions

**Comment by aslonnie** [comment]
> They are passing on CI so why they need these dependencies?

I think they are passing because ray has these dependencies, and our current CI sets up an environment that happens to have these package installed. In other words, they just happen to work as an accident.

The missing dependencies are discovered when I try to run them in a hermetic python environment here:

https://github.com/ray-project/ray/pull/34689

**Review by can-anyscale — APPROVED** [review]
gogogo

**Pull request merged**
