### PR TITLE
[rllib] implemented compute_advantages without gae

### LINKED ISSUE #3746: [rllib]compute_advantages doesn't support a critic without GAE
Looks like this was a [planned feature](https://github.com/ray-project/ray/blob/7edc677304f90bcab0a01e9722e59e36dd9afcb0/python/ray/rllib/evaluation/postprocessing.py#L47) that got overlooked. Seems like a simple fix but maybe I'm missing something.

### PR DESCRIPTION
**Pull request by roireshef**
## Why are these changes needed?

This replaces:

>          # TODO(ekl): support using a critic without GAE

## Related issue number

Closes #3746

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by roireshef** [comment]
Guys, it seems like PG is using compute_advantages() without initializing SampleBatch.VF_PREDS. I replaced ignoring the ciritic output (VF_PRED) with actually using it, but with current design they can't co-exist. It seems like it's better PG will use a different logic, probably passing in some "use_critic" flag into compute_advantage could help mitigate this issue

**Comment by ericl** [comment]
Yeah having a `use_critic` flag sounds good. We wouldn't want to add a critic to PG since it's meant to be a simple example.

There are a few places where we should make sure it is set properly:
```
examples/centralized_critic.py
24:from ray.rllib.evaluation.postprocessing import compute_advantages, \
122:    train_batch = compute_advantages(

agents/pg/pg_tf_policy.py
3:    compute_advantages
14:    return compute_advantages(sample_batch, 0.0, policy.config["gamma"],

agents/marwil/marwil_policy.py
3:from ray.rllib.evaluation.postprocessing import compute_advantages, \
73:        batch = compute_advantages(

agents/a3c/a3c_torch_policy.py
2:from ray.rllib.evaluation.postprocessing import compute_advantages, \
46:    return compute_advantages(sample_batch, last_r, policy.config["gamma"],

agents/a3c/a3c_tf_policy.py
6:from ray.rllib.evaluation.postprocessing import compute_advantages, \
64:    return compute_advantages(sample_batch, last_r, policy.config["gamma"],

agents/ppo/ppo_tf_policy.py
5:from ray.rllib.evaluation.postprocessing import compute_advantages, \
186:    batch = compute_advantages(

agents/ppo/appo_policy.py
15:from ray.rllib.evaluation.postprocessing import compute_advantages
387:        batch = compute_advantages(
```

**Comment by roireshef** [comment]
@ericl wherever it made sense, I kept `use_critic` and `use_gae` as config parameters. Wherever it didn't, I forced their values. I tried to leave enough flexibility so the user has control over those.

**Review by ericl — APPROVED** [review]

**Comment by roireshef** [comment]
Hi, I'm not very familiar with "Travis CI", which is failing. Should I worry about it?

**Comment by ericl** [comment]
I think the main error is the lint job failing

**Comment by ericl** [comment]
Can you make the following fixes (format script could not auto fix)?:

$ scripts/format.sh                        
WARNING: Ray uses clang-format 7.0.0, You currently are using 6.0.0-1ubuntu2. This might generate different results.
From https://github.com/ray-project/ray
 * branch                master     -> FETCH_HEAD
rllib/agents/a3c/a3c.py:9:80: E501 line too long (100 > 79 characters)
rllib/agents/ppo/appo.py:14:80: E501 line too long (100 > 79 characters)
rllib/agents/ppo/ppo.py:17:80: E501 line too long (100 > 79 characters)
rllib/evaluation/postprocessing.py:34:80: E501 line too long (112 > 79 characters)
rllib/evaluation/postprocessing.py:46:80: E501 line too long (100 > 79 characters)
rllib/evaluation/postprocessing.py:47:80: E501 line too long (84 > 79 characters)

**Comment by ericl** [comment]
Jenkins retest this please

**Pull request merged**
