### PR TITLE
[rllib] Fix APEX priorities returning zero all the time

### PR DESCRIPTION
**Pull request by ericl**
Since make_tf_callable caches the ops created, putting Python if statements inside them results in incorrect behaviour. Move the if outside the function.

### CODE REVIEW

**Review by richardliaw — CHANGES_REQUESTED** [review]
Please do not put the rllib tests above the examples; rllib fails half the time now.

**Comment by richardliaw** [comment]
The ray examples take 6 minutes to run

**Comment by ericl** [comment]
The examples segfaulted in this example. Are you sure they're more reliable?

**Comment by ericl** [comment]
jenkins retest this please

**Review by richardliaw — APPROVED** [review]
beautiful

**Comment by ericl** [comment]
Tests ok, segfault on tune

**Pull request merged**
