### PR TITLE
[GCS]Increase heartbeat interval to reduce pressure on gcs server

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
As heartbeat frequency is too large, gcs server cannot stand cpu pressure.
We increase default heartbeat interval but keep timeout seconds unchanged.

Meanwhile some tests depending on this parameter should be regularized.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by stephanie-wang — DISMISSED** [review]
I'm fine with doing this for some unit tests but let's not change the global default. This is just a band-aid and we should just fix the heartbeat problem for real.

**Comment by WangTaoTheTonic** [comment]
@stephanie-wang There's no need for raylet to heartbeat every 100 ms. The interval is too short.

**Comment by rkooo567** [comment]
@stephanie-wang Ant recently divided heartbeat & resource update to different RPC, and this will only update heartbeat. One question I have is do we really need this heartbeat RPC if we start using the pulling model instead of push cc @wuisawesome

**Comment by rkooo567** [comment]
Hey @wuisawesome Let's merge this PR if we'd like to keep the heartbeat.

**Comment by WangTaoTheTonic** [comment]
ping @rkooo567 @stephanie-wang @wuisawesome 
Now heartbeat is only used to check if node is alive. The default heartbeat interval is 100ms and a node is treated as dead if gcs didn't receive its heartbeat for 300 times(300 * 100ms = 30s).
The interval of 100ms is not necessary as the timeout is 30s. We can change it to 1000ms(1s) while keep the total timeout as unchanged 30s. (meanwhile we change `num_heartbeats_timeout ` to 30.
This can reduce pressure of gcs remarkably.

**Review by rkooo567 — APPROVED** [review]

**Review by wuisawesome — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @stephanie-wang do you think it is okay to merge it ?

**Comment by WangTaoTheTonic** [comment]
@rkooo567 Is it ok to go?
@stephanie-wang Any comments? : -p

**Comment by rkooo567** [comment]
@WangTaoTheTonic can you merge the lastest master? I assume it is fine. 

Btw, does 30 seconds timeout make sense in this case? theoretically the heartbeat thread shouldn't be impacted at all right?

**Comment by WangTaoTheTonic** [comment]
> @WangTaoTheTonic can you merge the lastest master? I will ping Stephanie in person about this.
> 
> Btw, does 30 seconds timeout make sense in this case? theoretically the heartbeat thread shouldn't be impacted at all right?

Yeah we keep 30 seconds as timeout value unchanged. Yes for heartbeat thread.

**Comment by rkooo567** [comment]
I mean why does it still have to be 30 seconds? Previously the issue was raylet sometimes became overloaded, and that could kill worker nodes unnecessarily if the timeout was short. But now we don't need to keep such a long timeout right?

**Comment by WangTaoTheTonic** [comment]
@rkooo567 I believe the 30 seconds timeout value has been set from the beginning, not for other reason, but just as it is  reasonable for a node timed out.

The pressure issue was found recently while the config value was set very long time ago.

**Comment by WangTaoTheTonic** [comment]
It doesn't have to be 30 seconds. Maybe 20 or 10 either is good but they don't make too much difference. Let's keep it unchanged.

**Comment by rkooo567** [comment]
It sure has differences. For example, raylets won’t need to send unnecessary rpcs to dead nodes. Let me actually create RFC and see what people think. (But it is out of scope of this PR definitely)

**Comment by WangTaoTheTonic** [comment]
> It sure has differences. For example, raylets won’t need to send unnecessary rpcs to dead nodes. Let me actually create RFC and see what people think. (But it is out of scope of this PR definitely)

The raylet part makes sense~ Ping me after the RFC created please.:) Looking forward to discussing and the comments

**Comment by WangTaoTheTonic** [comment]
@rkooo567 I'm gonna  ping you again :-)

**Comment by ericl** [comment]
@rkooo567 thanks for the quick revert!

**Pull request merged**
