### PR TITLE
[RLlib] Replay buffer API

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
## Why are these changes needed?

As a step towards making the replay buffer API more user friendly, these changes move buffers into their own folder, give the LocalReplayBuffer the more expressive name MultiAgentReplayBuffer and add/change docstrings for all buffer classes. 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
   
I have only run the tests inside RLlib connected to the classes I have made changes to. I suppose these are the unit tests listed under _Checks_.
I hope this procedure suffices, also for future changes.

### CODE REVIEW

**Comment by sven1977** [comment]
Looks great @ArturNiederfahrenhorst , thanks for the PR. Will take a look rn.

**Review by sven1977 — APPROVED** [review]
Very nice change! Thanks for this PR @ArturNiederfahrenhorst .
Looks good. Just the LINTer failing, but let me try fix this.

**Comment by sven1977** [comment]
Fixed LINT, just waiting for all tests to pass again, then will merge.

**Comment by ArturNiederfahrenhorst** [comment]
Great! Ich will make sure to adhere to "your" style from here on and make better use of a linter.

**Pull request merged**
