### PR TITLE
[WIP] Fix log monitor pid is reported as None

### PR DESCRIPTION
**Pull request by rkooo567**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Cannot reproduce. Will work on it again if issue is reproducible

**Comment by CavalloneChen** [comment]
This issue is quite annoying, when I run multiple jobs with ray, the first to the third jobs will have their pid printed normally, but other jobs that started later will all have pid=None. The most annoying part is that all the jobs with pid=None will have their logging output spamming all the shells with ray jobs running!

**Comment by rkooo567** [comment]
@CavalloneChen do you mind creating an issue with more detail? I can focus on fixing this if I can reproduce the issue

**Comment by CavalloneChen** [comment]
@rkooo567 Here is the [issue link](https://github.com/ray-project/ray/issues/20612), I'm sorry I can't provide a reproduction script at the moment as it is quite private. Let me know if I can help in other ways.

**Comment by rkooo567** [comment]
You can probably create mock scripts, and tell me how I should execute them? Note that better reproduction will help us solving issues more quickly as it’d take the minimal time to verify/debug problems

**Pull request closed without merging**
