### PR TITLE
[core][dashboard] Change file_tail_iterator to async.

### LINKED ISSUE #2355: [Bug] Exec probes are causing high load on Ray pods
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

As part of Ray scalability testing (see https://github.com/ray-project/kuberay/tree/master/benchmark/perf-tests), I've noticed that some Ray pods experience high load and become unready.

Upon further investigation, it seems that the most of the CPU usage in the pods are from the exec probes. 

Here's one example from a test. The Ray cluster is idle with no jobs but the pods are using full 2 CPUs allocated:
```
$ kubectl top pod
test-pkn9h-raycluster-5bqn8-head-4bgwf                              1877m        502Mi
test-pkn9h-raycluster-5bqn8-worker-small-group-q4jsq      1897m        326Mi
test-pkn9h-raycluster-5bqn8-worker-small-group-wjhsw      1920m        331Mi
``` 

When I exec into one of the pods run 'htop', I see that the exec probes is what's consuming most of the CPU:

Screenshot 2024-09-05 at 12 47 33 PM

Describing the pod shows the probes have been timing out: 
```
  Normal   Created    2m11s                kubelet            Created container ray-workers
  Normal   Started    2m10s                kubelet            Started container ray-workers
  Warning  Unhealthy  38s (x12 over 110s)  kubelet            Readiness probe errored: command timed out: "bash -c wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success" timed out after 1s
  Warning  Unhealthy  31s (x10 over 90s)   kubelet            Liveness probe errored: command timed out: "bash -c wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success" timed out after 1s
```

### Reproduction script

I haven't figured out exact steps to reproduce the issue, but it happens quite frequently in the new scalability tests.

### Anything else

Potentially related to https://github.com/ray-project/kuberay/issues/2264

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### LINKED ISSUE #47637: [core] Raylet health check on dashboard agent hangs if a job is created
### What happened + What you expected to happen

https://github.com/ray-project/kuberay/issues/2355#issuecomment-2344374832

### Versions / Dependencies

Ray 2.34.0

### Reproduction script

https://github.com/ray-project/kuberay/issues/2355#issuecomment-2344374832

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by rynewang**
On `ray job submit`, the CLI tails logs from the job agent. The agent needs to read log tails from an iterator and yields to a WebSocket. However the file reading iterator is SYNC so it blocks agent event loop, causing the agent to block, making downstream consumers like KubeRay to break. Changes the log reading function `file_tail_iterator` to an AsyncIterator and a 1s `time.sleep` to `asyncio.sleep` to unblock.

The issue was introduced from https://github.com/ray-project/ray/pull/44658.

Fixes #47637. 
Fixes https://github.com/ray-project/kuberay/issues/2355

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]
The change makes sense to me, but I’m curious why Ray 2.9 works. I thought we’ve been using Iterator instead of AsyncIterator for years.

**Comment by rynewang** [comment]
didn't take time to blame out the problematic pr...

**Comment by rynewang** [comment]
@kevin85421 so it's https://github.com/ray-project/ray/pull/44658 from 5 mo ago I think

**Comment by shaowei-su** [comment]
Hi @rynewang  @kevin85421  will this fix be included in the ray nightly release?

**Pull request merged**
