### PR TITLE
5667 - Changing use of sun NotImplementedException to apache NotImplementedException

### LINKED ISSUE #5667: [java] Usage of sun.reflect.generics.reflectiveObjects.NotImplementedException
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macos sierra
- **Ray installed from (source or binary)**: source
- **Ray version**: tag ray-0.7.4
- **Python version**: NA
- **Exact command to reproduce**: Install ray for java and try the simple example to store an int in object store

### Describe the problem
Issue raised when loading the test:
```
/Users/to124821/src/github.com/ray/java/runtime/src/main/java/org/ray/runtime/context/LocalModeWorkerContext.java
Error:(11, 46) java: package sun.reflect.generics.reflectiveObjects does not exist
Error:(27, 15) java: cannot find symbol
  symbol:   class NotImplementedException
  location: class org.ray.runtime.context.LocalModeWorkerContext
```
This is linked to the use of ```sun.reflect.generics.reflectiveObjects.NotImplementedException``` simply for throwing a ```NotImplementedException()``` in ```getCurrentWorkerId()```. If there no specific rationale to use this specific dependency to sun proprietary Class, it migght be better suited to switch to another Class. In ```LocalModeRayletClient.java```, it seems the apache lang version is preferred: ```org.apache.commons.lang3.NotImplementedException```

### Source code / logs

```java
package com.airbus.cto.donut.sim.plasma;

import org.junit.Before;
import org.junit.Test;
import org.ray.api.Ray;
import org.ray.api.RayObject;

public class RayTest {

    @Before
    public void initRay(){
        Ray.init();
    }

    @Test
    public void objectStoreTest(){
        Integer x = 1;
        RayObject<Integer> obj = Ray.put(x);
        Integer x1 = obj.get();
        assert (x.equals(x1));
    }
}
```

### PR DESCRIPTION
**Pull request by ggdupont**
## Why are these changes needed?

See https://github.com/ray-project/ray/issues/5667

Basically, the use of sun.reflect.generics.reflectiveObjects.NotImplementedException creates a dependency to sun proprietary Class. It might be better suited to switch to another Class. In LocalModeRayletClient.java, it seems the apache lang version is preferred: org.apache.commons.lang3.NotImplementedException

## Related issue number

Closes #5667

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
        => can't run it without installing yapf@0.23.0 which seems impossible now with brew
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
        => NA

### CODE REVIEW

**Comment by edoakes** [comment]
Could you please update the title and add a description of what the changes do?

**Comment by ericl** [comment]
There seems to be some issue with this PR -- it has unrelated rllib changes. Can you make a new one?

**Comment by ggdupont** [comment]
> There seems to be some issue with this PR -- it has unrelated rllib changes. Can you make a new one?

Sorry, I don't see the link with rllib... could you elaborate?

**Comment by ggdupont** [comment]
(re)done => https://github.com/ray-project/ray/pull/5677

**Pull request closed without merging**
