### PR TITLE
[Java] Fix: task spec's resource map should contains CPU

### PR DESCRIPTION
**Pull request by raulchen**
Otherwise it will cause a RAY_CHECK to fail here: https://github.com/ray-project/ray/blob/68cf194e902a948a772f1dd0368029c2d7a7760f/src/ray/raylet/scheduling_resources.cc#L132

### CODE REVIEW

**Review by jovany-wang — COMMENTED** [review]
Looks good. 
Btw, should we add a test to cover this?
Before this change, the test will fail, and it will pass after this change.

**Review by jovany-wang — APPROVED** [review]
LGTM

**Review by jovany-wang — CHANGES_REQUESTED** [review]
Test failed

**Review by jovany-wang — APPROVED** [review]
it could be merged once test pass.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
