### PR TITLE
[core] OOM killer: 2.2 readiness

### PR DESCRIPTION
**Pull request by clarng**
## Why are these changes needed?

Re-applying https://github.com/ray-project/ray/pull/30553 to adjust OOM killer defaults + clean up overrides. Also include a bunch of fixes

1. This fixes the doc test that was failing due to time out, that was caused by the exponential backoff added. We set "max_retries=0" so it doesn't trigger OOM retry, which also speeds up the example

2. This also adds an extra node for chaos_dataset_shuffle_sort_1tb. The original test has the memory threshold at 1.00. With this PR the memory threshold is 0.95. With the extra node (21) the memory available is 21 * 0.95 = 19.95, which is closer to the amount of memory given to the test previously. Ultimately, the test is unstable if we start killing tasks aggressively in addition to node failure, so we keep the amount of memory the same to maintain the previous behavior

3. The memory threshold was adjusted on the product side accidentally to 1.0 when we don't provide an override in the release test. This PR renames the variables so it won't accidentally override the default value in Ray. The configs have limited exposure so it is relatively safe to rename and not break users

## Related issue number

https://github.com/ray-project/ray/issues/30680
https://github.com/ray-project/ray/issues/30433
https://github.com/ray-project/ray/issues/30704

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by clarng** [comment]
Release test: https://buildkite.com/ray-project/release-tests-pr/builds/22465

**Review by rkooo567 — APPROVED** [review]

**Comment by clarng** [comment]
> > This also adds an extra node for chaos_dataset_shuffle_sort_1tb. The original test has the memory threshold at 1.00. With this PR the memory threshold is 0.95. With the extra node (21) the memory available is 21 * 0.95 = 19.95, which is closer to the amount of memory given to the test previously. Ultimately, the test is unstable if we start killing tasks aggressively in addition to node failure, so we keep the amount of memory the same to maintain the previous behavior
> 
> Consider running this release test from the PR?

Here's the result: https://buildkite.com/ray-project/release-tests-pr/builds/22512#0184c1a0-6035-42a8-a225-866756c6817d

**Review by ericl — APPROVED** [review]
Stamping

**Comment by ericl** [comment]
Can someone double check the release test / test output? Not sure if I have the complete context here.

**Comment by clarng** [comment]
> Can someone double check the release test / test output? Not sure if I have the complete context here.

CI: 
the test failures are unrelated and some of them are already fixed on master. I'll pull and do another run 

Nightly: 
read_tfrecords_benchmark_single_node - known failure that is fixed on master (https://github.com/ray-project/ray/pull/30714)
datasets_preprocess_ingest - also a known failure

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
the SIGSEV is concerning, created a separate issue https://github.com/ray-project/ray/issues/30747

**Comment by clarng** [comment]
looks good to merge, can someone shepherd? @rkooo567  @ericl  @scv119

**Comment by clarng** [comment]
I synced with @stephanie-wang regarding chaos_dataset_shuffle_sort_1tb, we think it is ok to disable the oom killer there for now, the failure is unrelated to oom and we should investigate / fix and re-enable oom killer there.

Issue to track the bug : https://github.com/ray-project/ray/issues/30772

**Pull request merged**
