### PR TITLE
Add CombinedStopper to documentation

### PR DESCRIPTION
**Pull request by klieret**
Signed-off-by: Kilian Lieret <kilian.lieret@posteo.de>

## Why are these changes needed?

`CombinedStopper` was not mentioned in the documentation.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by Yard1 — DISMISSED** [review]

**Comment by klieret** [comment]
```
reading sources... [100%] workflows/package-refsoppingpacesrialmnistization_utilse_example
ray.tune.stopper.stopper.CombinedStopper:1: WARNING: duplicate object description of ray.tune.stopper.stopper.CombinedStopper, other instance in tune/api_docs/stoppers, use :noindex: for one of them
```

Not sure where this one more description is.

If I run ` find . -name "*.rst" | grep "CombinedStopper"` on the repo, I come up with nothing (and I also don't find something with the search in the generated docs online)

**Comment by Yard1** [comment]
Ah @klieret it looks like it was already added? Maybe in a different commit in the meantime
Screenshot 2022-10-25 at 19 07 16

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
seems like this is already in the docs?

> 

/ray/python/ray/tune/stopper/stopper.py:docstring of ray.tune.stopper.stopper.CombinedStopper:1: WARNING: duplicate object description of ray.tune.stopper.CombinedStopper, other instance in tune/api_docs/stoppers, use :noindex: for one of them
--
  | /ray/python/ray/tune/stopper/stopper.py:docstring of ray.tune.stopper.stopper.CombinedStopper:1: WARNING: duplicate object description of ray.tune.stopper.stopper.CombinedStopper, other instance in tune/api_docs/stoppers, use :noindex: for one of them

**Comment by richardliaw** [comment]
I'll close this as this is redundant. thank you for the contribution anyways @klieret !

**Comment by klieret** [comment]
Ah! I might have accidentally only checked in the latest release rather than master. My bad, sorry for the noise! Thanks for the review :)

**Pull request closed without merging**
