### PR TITLE
[scheduler][cleanup] Remove one cpu optimization

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This PR removes the one-cpu optimization from resource reporting. The optimization doesn't make sense if we generalize the scheduling class beyond just a resource set (#17887 ), and afaik we've never had a user run into a problem from using more scheduling classes than the cap, so all the resources are always accounted for when autoscaling.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by stephanie-wang** [comment]
What can happen if the one-CPU class is not reported? Is the problem that we wouldn't autoscale up properly?

I'm wondering whether the better solution for #17887 is to actually sum up the queues for all of the one-CPU classes.

**Comment by wuisawesome** [comment]
>  Is the problem that we wouldn't autoscale up properly?

It will take longer to autoscale since the demand will eventually get reported. This is the same as if any other resource was not reported. (eventually, as we autoscale, those demands will go away and new resources can be reported though). 

If it helps, I can add a warning log if we ever hit the cap.

**Comment by stephanie-wang** [comment]
> > Is the problem that we wouldn't autoscale up properly?
> 
> It will take longer to autoscale since the demand will eventually get reported. This is the same as if any other resource was not reported. (eventually, as we autoscale, those demands will go away and new resources can be reported though).
> 
> If it helps, I can add a warning log if we ever hit the cap.

Ah I see. Sounds good, can you add at INFO level?

**Review by stephanie-wang — APPROVED** [review]

**Review by fishbone — APPROVED** [review]

**Comment by ericl** [comment]
//:cluster_task_manager_test                                             FAILED in 3 out of 3 in 0.3s

**Comment by wuisawesome** [comment]
Tests passing the broken mac wheel/jar test seems to be broken on master.

**Pull request merged**
