### PR TITLE
Fix typo in tune.

### PR DESCRIPTION
**Pull request by alok**

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
I'm super confused by the travis linting build. It looks like it's building the wrong PR or something.

**Comment by alok** [comment]
@robertnishihara Why does Jenkins randomly seem to pass or fail?

**Comment by robertnishihara** [comment]
@alok I think we have some flaky tests. The jenkins builds often timeout. I think this would not happen if we increased the timeout window a lot, but really the tests shouldn't be so slow.

**Comment by robertnishihara** [comment]
@alok I think we have some flaky tests. The jenkins builds often timeout. I think this would not happen if we increased the timeout window a lot, but really the tests shouldn't be so slow.

**Pull request merged**
