### PR TITLE
Support local py_modules in jobs

### PR DESCRIPTION
**Pull request by architkulkarni**
## Related issue number
Previously local py_modules were not uploaded to the remote cluster during job submission, so jobs could only use py_modules from remote URIs.  This PR uploads py_modules to the cluster, just like how it currently works for the non job-submission case.  

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
This looks great, it's basically what I suggested on the other PR a few minutes ago :)

I think we should take it a step further and do the same for working_dir.

Also, it seems to me that the callback should simply take a local zip file (or bytes?) and return a URI rather than needing to implement its own handling for `include_parent_dir` and `excludes`.

**Comment by architkulkarni** [comment]
> Also, it seems to me that the callback should simply take a local zip file (or bytes?) and return a URI rather than needing to implement its own handling for include_parent_dir and excludes.

@edoakes I agree that should be the final state.  How about we merge this first, and then I make a followup issue for that refactor?  I can also try to do it in https://github.com/ray-project/ray/pull/22368, since I need to support uploading local files/bytes anyway for that one.

**Review by edoakes — APPROVED** [review]

**Comment by architkulkarni** [comment]
`serve:test_cli` is flaky on master.

**Comment by edoakes** [comment]
@architkulkarni merge conflict from @shrekris-anyscale revert and subsequent revert-revert :(

**Pull request merged**
