### PR TITLE
[autoscaler] Enforce CommandRunnerInterface abstractions

### PR DESCRIPTION
**Pull request by AmeerHajAli**
## Why are these changes needed?
To enforce CommandRunnerInterface abstractions.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
Hey Ameer, what about doing:

```
@override_check(BaseCommandRunner)
class SubclassCommandRunner(BaseC...)
```

**Review by ijrsvt — APPROVED** [review]
LGTM, I think @richardliaw  has some thoughts.

The only other idea is to make a test that tests this

**Comment by AmeerHajAli** [comment]
@richardliaw , @ijrsvt  I actually like the idea of making it a test. Are you ok with that?

**Comment by richardliaw** [comment]
yes

**Comment by ijrsvt** [comment]
@AmeerHajAli  I'm totally fine with that!

**Review by ericl — APPROVED** [review]

**Review by ijrsvt — APPROVED** [review]
LGTM

**Comment by AmeerHajAli** [comment]
@richardliaw / @ericl , Can you merge?

Thanks!

**Pull request merged**
