### PR TITLE
[Serve] Fix serve failure flacky

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

Flacky tests

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — CHANGES_REQUESTED** [review]
The bad luck might happen to `handler.deploy()` call as well. I would like to see a more holistic approach here, can we maybe do some sort of failure tracking with tolerance?

**Comment by shrekris-anyscale** [comment]
I'm wondering if changing the test is the best approach– the smoke test has been [passing consistently](https://flakey-tests.ray.io/#) for a while:

Screen Shot 2022-06-03 at 7 03 48 PM

I think it's the recent flakiness may be related to a bug in the code rather than the test.

**Comment by shrekris-anyscale** [comment]
I submitted a potential code fix in #25478.

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
please merge master and fix lint

**Comment by shrekris-anyscale** [comment]
If #25478 fixes the flakiness, I think it might be better to keep the test the same since (1) the test wasn't flaky at all until very recently and (2) it might make it harder to detect issues like the deletion bug. @sihanwang41 what do you think?

**Comment by sihanwang41** [comment]
> If #25478 fixes the flakiness, I think it might be better to keep the test the same since (1) the test wasn't flaky at all until very recently and (2) it might make it harder to detect issues like the deletion bug. @sihanwang41 what do you think?

yes, I won't merge, if the test is already stable.

**Pull request closed without merging**
