### PR TITLE
[Doc] Promote Ray Jobs API from beta to stable

### PR DESCRIPTION
**Pull request by architkulkarni**
Signed-off-by: Archit Kulkarni <architkulkarni@users.noreply.github.com>

## Why are these changes needed?
In Ray 2.2, the Ray Jobs API will be GA. This PR updates the PublicAPI annotation of the APIs from "beta" to "stable" and updates the documentation.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
🎉

**Review by DmitriGekhtman — APPROVED** [review]
stamp

**Review by xwjiang2010 — APPROVED** [review]
stamp for tune!

**Comment by architkulkarni** [comment]
Lint failure `num_rollout_workers` unrelated and was broken on master
rllib:test_memory_leak_ppo unrelated
`test_cli` broken on master and unrelated
`two_trainer_workflow_tf` unrelated
`test_dataset` unrelated

**Pull request merged**
