### PR TITLE
[Core] check `metrics_export_port` is not already bound on `start_raylet`

### LINKED ISSUE #20665: [Bug] Prometheus Metrics Exporting not working
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I launched Ray successfully with a metrics export port, but then that port is unreachable. Tried the same thing on macOS and it works.

```bash
> ray start --head --metrics-export-port=8080
Local node IP: 10.10.0.4

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='10.10.0.4:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
> telnet localhost 8080
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

### Versions / Dependencies

- Problem exists on both the latest stable (1.8.0) and nightly master
- Problem only exists on Linux (Ubuntu 20.04); does not happen on macOS

### Reproduction script

see above

### Anything else

Happens every time now

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jon-chuang**
## Why are these changes needed?

Fix: https://github.com/ray-project/ray/issues/20665

CC: @rkooo567 

The error was uncaught because `prometheus_client` starts HTTPServer on another thread: https://github.com/prometheus/client_python/blob/ba5387b3ffd974b8644e04cdc115eb1d794e87fb/prometheus_client/__init__.py#L471

Concerns:
- This test might be flakey
- Binding to a socket takes time at startup. 

This PR also begs the question of whether we should also try to bind to other ports to ensure that they are free?

## Related issue number
https://github.com/ray-project/ray/issues/20665

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
For the PR, can you also add a description later of how you tackle the issue (in the PR description) next time?

About this issue;

Given the exact issue was https://github.com/ray-project/ray/issues/20665#issuecomment-1054615939, we should add a proper error message when the minimal ray is installed & --metrics-export-port is used (`pip install ray` vs `pip install ray[default]`. Prometheus feature is not working for the former case).

Also, the proposed solution still doesn't fully solve the problem. For example, imagine the port is being used after the code and before it is actually bound to the agent. I think the root cause is we choose the port ahead of time. We should fix this at some point, but it requires a bit bigger change. I'd like to suggest not to tackle this issue for now (but can you create an issue instead?). 

That said, can you just do `we should add a proper error message when the minimal ray is installed & --metrics-export-port is used ` here?

**Comment by jon-chuang** [comment]
@rkooo567 I see. So that is for minimal ray without prometheus, we should give an error saying that prometheus cannot be started via this installation of ray.

> I think the root cause is we choose the port ahead of time

I think this is very hard, as I mentioned, the code path to consume and bind to the port lives inside of prometheus_client. I think this solution is a good intermediate ground to catch most errors when users leave ports open inadvertantly.

**Comment by rkooo567** [comment]
IIUC, we can catch the exception from this https://github.com/ray-project/ray/blob/7b22d662df0aac5e32a78a94d0e9d981f0dd0152/python/ray/_private/metrics_agent.py#L79? 

For the separate problem (prom port could be conflicted), we always pre-select the port here https://github.com/ray-project/ray/blob/7b22d662df0aac5e32a78a94d0e9d981f0dd0152/python/ray/node.py#L246

And I think the ideal fix is to not pre-select port at all and choose the port right before we start the Prometheus exporter (basically here https://github.com/ray-project/ray/blob/7b22d662df0aac5e32a78a94d0e9d981f0dd0152/python/ray/_private/metrics_agent.py#L82). But this requires some changes to the core service discovery mechanism. 

I personally prefer not to handle this right now (with the half-working solution) as the issue user reported is not the conflicting port due to other processes, but just that minimal ray installation doesn't have a Prometheus client. Maybe we can discuss the proper solution in person and choose what to do tomorrow (either this or a different approach)?

**Comment by rkooo567** [comment]
Is this ready btw?

**Comment by jon-chuang** [comment]
> And I think the ideal fix is to not pre-select port at all and choose the port right before we start the Prometheus exporter (basically here

I think users may want to preselect port, we should allow them the flexibility. 

Interestingly, there is precedent for catching used port error for dashboard port:
https://github.com/ray-project/ray/blob/3e80da7e9fd2908d29fe0c471ff539519613f5d9/python/ray/_private/services.py#L1335
The behaviour is to throw error if dashboard is required (passed --include-dashboard=true) and log as info (warning) if dashboard is not required (no flag passed).

Since _get_cached_port already does a port check if no default port is specified, and only metrics ports provide default ports, I think it is best if we follow something similar and throw an error if default ports are passed.

----

Tangentially:

Interestingly, the behaviour is to find unused ports to assign as metrics_agent_port and metrics_export_port. This means that prometheus server will run regardless of whether user wants to run it? 
See:
https://github.com/ray-project/ray/blob/990b0ec93420973939c0d68284a774cfc6d4798f/dashboard/modules/reporter/reporter_agent.py#L168
This is quite weird as I'm not sure there is any clear indication to the user what the metrics_export_port would be if they do not specify it.

**Pull request closed without merging**
