### PR TITLE
[Core] Wait until runtime env agent is ready to receive requests

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

This is the PR to fix test_runtime_env_working_dir_3.

For the normal, successful case, the server side should receive requests
- GetOrCreateRuntimeEnv (ref count == 1)
- GetOrCreateRuntimeEnv (ref count == 2)
- DeleteRuntimeEnv (ref count == 1)

However, when the runtime env is first created, the agent wasn't ready to receive the request (because we start it asynchronously), which fails the runtime env GetOrCreate request. If GetOrCreateRuntimeEnv fails by a network failure, it is retried in 1 second. At the end

- GetOrCreateRuntimeEnv failed (agent not ready)
- GetOrCreateRuntimeEnv (ref count == 1)
- DeleteRuntimeEnv (ref count == 0) -> runtime env deleted
- GetOrCreateRuntimeEnv retried -> working dir recreated.

At the end, if the gc check happens after working dir is recreated, it succeeds. Otherwise it failed.

This PR fixes the issue by not sending http request until the "agent is ready". We check this by queueing requests until GetRuntimeEnvRequest is successfully replied. After that we flush all requests.

Note that this is the temporary fix. We should tackle the fundamental ordering issue. I am also open to not merge this PR and tackle this problem in Ray 2.10.
https://docs.google.com/document/d/1RsSEidS-KTKu1zXWwIdUZCGDonM9w7oRBgye8AAqHKI/edit

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
> because we start it asynchronously

Can/should we make it synchronously? Raylet can make sure the agent process is ready before marking itself as ready.

**Comment by rkooo567** [comment]
@jjyao last time when we tried this, this failed lots of tests. I think that approach has some implication (that raylet becomes slower to be ready).

**Comment by rkooo567** [comment]
I think it is worth trying though... But we may need some time to actually fix it properly (and I have no time for it at this point...)

Why don't we start from it to fix the flaky test & fix it properly when we fix the ordering issue?

**Comment by rkooo567** [comment]
decision: we will go with proper solution with ordering instead of quick fix since it is not urgent

**Pull request closed without merging**
