### PR TITLE
[docs] rllib conference material

### PR DESCRIPTION
**Pull request by maxpumperla**
Signed-off-by: Max Pumperla <max.pumperla@googlemail.com>

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by gjoliver** [comment]
the diff is pretty huge. is it intended that you want to include everything?
also there is a super minor lint error.

**Comment by maxpumperla** [comment]
@gjoliver fixed the linter. 600 loc, not small, yes. It's just doc changes though, to promote the RL conf.

**Review by mwtian — APPROVED** [review]
Poster looks great!

**Comment by mwtian** [comment]
If there is no objection to cherry picking, after lint passes I (or anyone) can merge the change.

**Comment by gjoliver** [comment]
> @gjoliver fixed the linter. 600 loc, not small, yes. It's just doc changes though, to promote the RL conf.

sure, you make the call 👌

**Review by gjoliver — APPROVED** [review]

**Comment by maxpumperla** [comment]
let's wait for the full build and then decide. it's desirable, but we don't have to force it (should tests still fail).

**Pull request merged**
