### PR TITLE
Pin gym version in Python 2 tests.

### PR DESCRIPTION
**Pull request by robertnishihara**
Looks like gym just released a new version that broke our tests in Python 2. https://pypi.org/project/gym/0.11.0/#history

### CODE REVIEW

**Comment by robertnishihara** [comment]
E.g.,

```
$ python -m pytest -v --durations=10 python/ray/rllib/test/test_catalog.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-4.2.0, py-1.7.0, pluggy-0.8.1 -- /home/travis/miniconda/bin/python
cachedir: .pytest_cache
rootdir: /home/travis/build/ray-project/ray/python, inifile:
plugins: timeout-1.3.3, flaky-3.5.3
collected 5 items                                                              
python/ray/rllib/test/test_catalog.py::ModelCatalogTest::testCustomModel FAILED [ 20%]
python/ray/rllib/test/test_catalog.py::ModelCatalogTest::testCustomPreprocessor FAILED [ 40%]
python/ray/rllib/test/test_catalog.py::ModelCatalogTest::testDefaultModels FAILED [ 60%]
python/ray/rllib/test/test_catalog.py::ModelCatalogTest::testGymPreprocessors FAILED [ 80%]
python/ray/rllib/test/test_catalog.py::ModelCatalogTest::testTuplePreprocessor FAILED [100%]
=================================== FAILURES ===================================
_______________________ ModelCatalogTest.testCustomModel _______________________
self = <ray.rllib.test.test_catalog.ModelCatalogTest testMethod=testCustomModel>
    def testCustomModel(self):
        ray.init()
        ModelCatalog.register_custom_model("foo", CustomModel)
        p1 = ModelCatalog.get_model({
            "obs": tf.constant([1, 2, 3])
>       }, Box(0, 1, shape=(3, ), dtype=np.float32), 5,
                                    {"custom_model": "foo"})
python/ray/rllib/test/test_catalog.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <[AttributeError("'Box' object has no attribute 'shape'") raised in repr()] SafeRepr object at 0x7fc58d45a878>
low = array([0., 0., 0.]), high = array([1., 1., 1.]), shape = (3,)
dtype = <type 'numpy.float32'>
    def __init__(self, low=None, high=None, shape=None, dtype=None):
        """
        Two kinds of valid input:
            Box(low=-1.0, high=1.0, shape=(3,4)) # low and high are scalars, and shape is provided
            Box(low=np.array([-1.0,-2.0]), high=np.array([2.0,4.0])) # low and high are arrays of the same shape
        """
        if shape is None:
            assert low.shape == high.shape
            shape = low.shape
        else:
            assert np.isscalar(low) and np.isscalar(high)
            low = low + np.zeros(shape)
            high = high + np.zeros(shape)
        if dtype is None:  # Autodetect type
            if (high == 255).all():
                dtype = np.uint8
            else:
                dtype = np.float32
            logger.warn("gym.spaces.Box autodetected dtype as {}. Please provide explicit dtype.".format(dtype))
        self.low = low.astype(dtype)
        self.high = high.astype(dtype)
>       super().__init__(shape, dtype)
E       TypeError: super() takes at least 1 argument (0 given)
```

**Comment by ericl** [comment]
We should actually not pin it right? Otherwise, gym will break us without us noticing.

**Comment by ericl** [comment]
We should actually not pin it right? Otherwise, gym will break us without us noticing.

**Comment by robertnishihara** [comment]
@ericl Gym already broke rllib, which is why I submitted this PR. I was going to pin it until the issue is fixed in gym, since I don't think we can work around it. It's just a syntax error in gym.

However, I can submit a patch upstream.

**Comment by robertnishihara** [comment]
https://github.com/openai/gym/pull/1312

**Comment by ericl** [comment]
Ah, makes sense as a temporary workaround. Looks like gym broke python2
compatibility by accident.

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
