### PR TITLE
[wip] fix doc theme

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

It currently looks like there is a big space after each title in the ray docs. This attempts to fix it.

cc @edoakes @simon-mo 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@richardliaw don't think it worked

Screen Shot 2021-04-05 at 12 08 07 PM

**Comment by simon-mo** [comment]
maybe change requirements-rtd.txt?

**Comment by sumanthratna** [comment]
just a guess but it looks like `p {margin-bottom: 1rem}` is being set by Bootstrap, so maybe we could just set `p {margin-bottom: 0}` in the custom css file

**Comment by richardliaw** [comment]
I don’t think that’s sufficient? Instead we want to make sure the caption
identifier is passed on correctly right?

**Comment by richardliaw** [comment]
fixed with #15485

**Pull request closed without merging**
