### PR TITLE
[Docs] Update example-full.yaml for ulimits as supported by docker.

### PR DESCRIPTION
**Pull request by Ivorforce**
## Why are these changes needed?

On `ulimit -n 65536`, the line `ulimit: open files: cannot modify limit: Operation not permitted` is printed in `redis.out` logs. This means the statement won't run and the default ulimit remains (1024 on my recent image).

See https://stackoverflow.com/a/31474407/730797.

## Checks

Before merging, please make sure this is the valid and only spot to change this in. I am not familiar with the structure of the project.

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
   - [x] I tested it with a custom setup file.

### CODE REVIEW

**Comment by richardliaw** [comment]
This is great! cc @ijrsvt to merge.

**Comment by richardliaw** [comment]
(We also probably want to do it for all the other examples that use docker)

**Comment by ijrsvt** [comment]
Thanks @Ivorforce ! This looks great!

**Comment by Ivorforce** [comment]
Done! 
Quick notes:

* I added the the ulimit to all files, even though python/ray/autoscaler/local/example-full.yaml didn't have it before. It did have a -c option though which is probably also replaceable with a docker command.
* No changes to python/ray/autoscaler/aliyun/example-full.yaml,  python/ray/autoscaler/staroid/example-full.yaml,  python/ray/autoscaler/kubernetes/example-full.yaml  since they don't use docker.
* No changes to legacy example files.

**Review by ijrsvt — APPROVED** [review]
This LGTM now!

**Pull request merged**
