### PR TITLE
[profile manager] add verbose option

### PR DESCRIPTION
**Pull request by aslonnie**
and prints profiler output on test failure

### CODE REVIEW

**Comment by can-anyscale** [comment]
Look like test failed, is that expected?

**Comment by aslonnie** [comment]
should be fixed. please take another look

**Comment by aslonnie** [comment]
@jonathan-anyscale is `attach_profile()` part of ray public API? is it okay to add the `verbose` arg?

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
seems that Jonathan is an intern and has already left the project

**Pull request merged**
