### PR TITLE
exclude doc_code from import sorting

### PR DESCRIPTION
**Pull request by clarng**
## Why are these changes needed?

Skip sorting the imports in doc_code.

## Related issue number

https://github.com/ray-project/ray/pull/25678

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Ran the following:
./scripts/format.sh --all 

./scripts/format.sh (no-op)
`
git diff --name-only --diff-filter=ACRM c92628138b9696b7a14489fcdc3d8bde95d333db -- '*.py' ':(exclude)doc/**/doc_code/*'
`

./scripts/format.sh  --files "X" 
--> will still format the file if specified

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]
Thanks!

**Review by wuisawesome — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
Needs codeowner review
@maxpumperla @richardliaw @ericl @edoakes @pcmoritz @simon-mo

**Review by richardliaw — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
Test failures unrelated.

**Comment by simon-mo** [comment]
can you open another PR to avoid this for doc/source/conf.py as well? the ordering there is carefully planned.

**Comment by clarng** [comment]
> can you open another PR to avoid this for doc/source/conf.py as well? the ordering there is carefully planned.

Fixed in here : https://github.com/ray-project/ray/pull/25824/files#diff-d8d3ed25802824d15bf411f8e97416d8fc6f9247e821b0617f2b869dc584b99c

For simplicity we could just ignore doc/ for now given the number of edge cases

**Pull request merged**
