### PR TITLE
Revert "Revert "[Object spilling] Avoid worker crash when an object is spille…"

### PR DESCRIPTION
**Pull request by kfstorm**
Reverts ray-project/ray#15964

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Let's merge it after this PR; https://github.com/ray-project/ray/pull/15986/checks?check_run_id=2648633207

**Comment by rkooo567** [comment]
Please merge the latest master! the above pr is merged

**Comment by kfstorm** [comment]
I can't push my changes. The branch is generated by GitHub and I can't update it.

```
Enumerating objects: 22, done.
Counting objects: 100% (22/22), done.
Delta compression using up to 12 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 877 bytes | 146.00 KiB/s, done.
Total 8 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/revert-15964-revert-kai.
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To github.com:ray-project/ray.git
 ! [remote rejected]       revert-15964-revert-kai -> revert-15964-revert-kai (protected branch hook declined)
error: failed to push some refs to 'github.com:ray-project/ray.git'
```

**Comment by rkooo567** [comment]
The pull request flaky failure is misleading (it actually succeed). Merging it.

**Pull request merged**
