### PR TITLE
[WIP] test change for adding plasma client mutex

### PR DESCRIPTION
**Pull request by zhijunfu**
## What do these changes do?

Test plasma change:
https://github.com/ant-tech-alliance/arrow/tree/plasma-client-mutex

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by zhijunfu** [comment]
@pcmoritz this failed with the following error, do you know what's missing here in my change? Thanks.

```
external/plasma/cpp/src/arrow/buffer.cc:28:31: fatal error: arrow/util/string.h: No such file or directory
 #include "arrow/util/string.h"
```

**Comment by pcmoritz** [comment]
@zhijunfu To fix this, `arrow/util/string.h` just needs to be added to the plasma bazel build file, let me look into it (I can also update `arrow-build` so they are synchronized).

**Comment by pcmoritz** [comment]
Moving forward with this is currently blocked on `https://github.com/apache/arrow/pull/4494` due to the `arrow-build` failure, but it should be merged pretty soon and then we can move forward!

**Comment by zhijunfu** [comment]
awesome. Thanks @pcmoritz

**Comment by pcmoritz** [comment]
https://github.com/ray-project/ray/pull/5011

**Pull request closed without merging**
