### PR TITLE
[sgd] show training result for examples

### PR DESCRIPTION
**Pull request by hhbyyh**
## Why are these changes needed?

Right now the training does not converge due to insufficient iterations. Change batch size to add more iterations and print out the trained models.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by hhbyyh** [comment]
Now it prints:
```
{'batch_time': 0.00023232650756835937, 'batch_processed': 1000, 'train_loss': 0.1853414798155427, 'data_time': 7.376670837402343e-05, 'd2h': 2.09808349609375e-06, 'fwd': 4.7206878662109375e-05, 'grad': 7.89642333984375e-05, 'apply': 2.3984909057617186e-05, 'epoch': 2, 'setup_proc_time_mean': nan, 'setup_proc_time_total': 0.0, 'setup_model_time_mean': nan, 'setup_model_time_total': 0.0, 'get_state_time_mean': nan, 'get_state_time_total': 0.0, 'set_state_time_mean': nan, 'set_state_time_total': 0.0, 'validation_time_mean': nan, 'validation_time_total': 0.0, 'training_time_mean': 0.058465003967285156, 'training_time_total': 0.058465003967285156}
{'batch_time': 0.0002258586883544922, 'batch_processed': 1000, 'train_loss': 0.015409790499601513, 'data_time': 7.273006439208985e-05, 'd2h': 2.6464462280273437e-06, 'fwd': 4.9686431884765626e-05, 'grad': 8.399486541748047e-05, 'apply': 1.8477439880371094e-05, 'epoch': 3, 'setup_proc_time_mean': nan, 'setup_proc_time_total': 0.0, 'setup_model_time_mean': nan, 'setup_model_time_total': 0.0, 'get_state_time_mean': nan, 'get_state_time_total': 0.0, 'set_state_time_mean': nan, 'set_state_time_total': 0.0, 'validation_time_mean': nan, 'validation_time_total': 0.0, 'training_time_mean': 0.056854963302612305, 'training_time_total': 0.056854963302612305}
{'batch_time': 0.00021982288360595704, 'batch_processed': 1000, 'train_loss': 0.0013168289518507663, 'data_time': 7.207012176513672e-05, 'd2h': 1.978874206542969e-06, 'fwd': 4.5371055603027346e-05, 'grad': 6.482601165771484e-05, 'apply': 1.4209747314453125e-05, 'epoch': 4, 'setup_proc_time_mean': nan, 'setup_proc_time_total': 0.0, 'setup_model_time_mean': nan, 'setup_model_time_total': 0.0, 'get_state_time_mean': nan, 'get_state_time_total': 0.0, 'set_state_time_mean': nan, 'set_state_time_total': 0.0, 'validation_time_mean': nan, 'validation_time_total': 0.0, 'training_time_mean': 0.055323123931884766, 'training_time_total': 0.055323123931884766}
{'batch_time': 0.00023706912994384766, 'batch_processed': 1000, 'train_loss': 0.00011125076558164438, 'data_time': 7.59735107421875e-05, 'd2h': 2.360343933105469e-06, 'fwd': 5.1355361938476564e-05, 'grad': 7.381439208984376e-05, 'apply': 1.7404556274414062e-05, 'epoch': 5, 'setup_proc_time_mean': nan, 'setup_proc_time_total': 0.0, 'setup_model_time_mean': nan, 'setup_model_time_total': 0.0, 'get_state_time_mean': nan, 'get_state_time_total': 0.0, 'set_state_time_mean': nan, 'set_state_time_total': 0.0, 'validation_time_mean': nan, 'validation_time_total': 0.0, 'training_time_mean': 0.059642791748046875, 'training_time_total': 0.059642791748046875}
{'batch_time': 0.00013239622116088866, 'validation_loss': 2.7971516976776913e-05, 'mean_accuracy': 0.0, 'epoch': 5.0, 'setup_proc_time_mean': nan, 'setup_proc_time_total': 0.0, 'setup_model_time_mean': nan, 'setup_model_time_total': 0.0, 'get_state_time_mean': nan, 'get_state_time_total': 0.0, 'set_state_time_mean': nan, 'set_state_time_total': 0.0, 'validation_time_mean': 0.013348102569580078, 'validation_time_total': 0.013348102569580078, 'training_time_mean': nan, 'training_time_total': 0.0}
trained weight:  2.00, bias:  4.99
```

**Comment by hhbyyh** [comment]
IMO we should also update the tune_example, appreciate suggestions. cc @richardliaw

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by hhbyyh** [comment]
Thanks for the review. Shall I continue to update other examples?

**Comment by richardliaw** [comment]
That sounds good. If you have any thoughts on an API for fetching different
checkpoints in a directory, I'd be all ears.

**Comment by hhbyyh** [comment]
> That sounds good. If you have any thoughts on an API for fetching different
> checkpoints in a directory, I'd be all ears.
Sure, I will work on that.

**Pull request merged**
