### PR TITLE
Make test_torch_predictor a medium test.

### LINKED ISSUE #35451: [CI] `linux://python/ray/train:test_torch_predictor` is failing on master
Screen Shot 2023-05-17 at 11 19 17 AM

### PR DESCRIPTION
**Pull request by gjoliver**
## Why are these changes needed?

Looking at test_torch_predictor, it is a suite of 35 test cases, and runs roughly a minute of time.
Most of the time these tests do finish fine actually. That's why it's just flaky.
Make this a medium test to de-flake it.

## Related issue number

Closes #35451

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by gjoliver** [comment]
evidence: https://buildkite.com/ray-project/oss-ci-build-branch/builds/3960#01882a62-b534-4b59-8262-fdf6b713021c

**Review by matthewdeng — APPROVED** [review]

**Review by krfricke — APPROVED** [review]

**Comment by zhe-thoughts** [comment]
Thanks for the note @ArturNiederfahrenhorst 

I'll wait for @gjoliver and @can-anyscale to comment first

**Comment by can-anyscale** [comment]
@zhe-thoughts , @ArturNiederfahrenhorst : let's cherry pick this yes; I'll look at all unit tests on release branches and mark opening issues as release-blockers.

**Comment by ArturNiederfahrenhorst** [comment]
@can-anyscale I'm also keeping a list of unit test failures and tracking them.

**Comment by ArturNiederfahrenhorst** [comment]
For some of them a solution is on the way already.

**Comment by can-anyscale** [comment]
@ArturNiederfahrenhorst ah ok, then please continue to do so, I'll sync with you on the list tomorrow or Monday, thankkks

**Comment by ArturNiederfahrenhorst** [comment]
Awesome, thanks :)

**Comment by ArturNiederfahrenhorst** [comment]
As per Slack discussion with Jun, this is zero risk and we can cherry pick it.

**Pull request merged**
