### PR TITLE
[core] Make ObjectRef compatible with asyncio.Future

### LINKED ISSUE #31606: [python3.11] Ray object refs can't be awaited using `asyncio.wait`
### What happened + What you expected to happen

Using `asyncio.wait` with Ray object refs like described in [the docs](https://docs.ray.io/en/latest/ray-core/actors/async_api.html#objectrefs-as-asyncio-futures) gives an error in Python 3.11.

### Versions / Dependencies

Python 3.11: `conda create --name py11 python=3.11 -c conda-forge`
Ray: `pip install -U ray-3.0.0.dev0-cp311-cp311-manylinux2014_x86_64.whl` ([link](https://docs.ray.io/en/master/ray-overview/installation.html))

### Reproduction script

```
import ray
import asyncio

@ray.remote
def some_task():
    return 1

async def main():
    await asyncio.wait([some_task.remote()])

asyncio.run(main())
```

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
With this change, `ObjectRef` will work just as if it's an asyncio.Future. 

API that only take `asyncio.Future` rather than awaitable will also work with ObjectRef, e.g. this issue will be resolved. https://github.com/ray-project/ray/issues/31606

## Related issue number
Closes https://github.com/ray-project/ray/issues/31606

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Will add some more test to verify the stub methods work - but this is generally the approach.

**Comment by pcmoritz** [comment]
Thanks a lot for doing this, this looks surprisingly simple -- do you forsee any trouble / problems with it going forward? What can go wrong here?

**Comment by rickyyx** [comment]
> Thanks a lot for doing this, this looks surprisingly simple -- do you forsee any trouble / problems with it going forward? What can go wrong here?

**Risk**
I think the only potential issues could be reference counting - I will do a few more testing to make sure the current approach (which seems to create a circular dependency on the obj ref and the stored future) doesn't break ray's reference counting. 

In general, I feel the changes are rather low risk, this shouldn't affect existing compatibility with asyncio, e.g. using `await` on an object reference. And it enables some more new API usage, as one could now called `cancelled`, `add_done_callback` on the object references, which we don't need to worry about backward compatibility. 

**Maintenance** 
Since we couldn't subclass the asyncio.Future due to ObjectRef being a cython class, we will need to maintain the stub functions as asyncio.Future iterates with api changes (see those if <python version> checks) 


I am also trying to add some more testing such that the behaviour is the same for an object ref / asyncio.Future where we swap the two, and mixing the two.

**Comment by rickyyx** [comment]
TODO

**Pull request closed without merging**
