### PR TITLE
[2.7.0/train] Fix issues in migration of tune_cifar_torch_pbt_example (#39158)

### PR DESCRIPTION
**Pull request by krfricke**
Cherry-pick of [f33b8eb](https://github.com/ray-project/ray/commit/f33b8ebba683ed58e47ff540bf120e7d9a07d942)

Resolves three issues that come up when migrating the `tune_cifar_torch_pbt_example` from Ray 2.6 to Ray 2.7:

1. There is a warning message because PBT uses the `_schedule_trial_save` interface. This is added to the white list attributes so it doesn't come up anymore.
2. PBT malfunctions in Python 2.7, so instead of silently failing, we raise an error and ask users to migrate
3. When users use old `ray.air.Checkpoint` APIs on `ray.train.Checkpoint`, we should raise an actionable error message.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
@matthewdeng is the new persistence mode disabled on 2.7?

**Comment by zhe-thoughts** [comment]
@krfricke @matthewdeng could you explain / confirm why this is a release blocker? Thanks

**Comment by krfricke** [comment]
This PR mainly introduces actionable error messages when users migrate their existing training scripts from Ray 2.6 to Ray 2.7.

**Comment by matthewdeng** [comment]
Yes this is needed for the new Train APIs in 2.7, but it's not clear to me why these errors are coming up in the CI tests. The new persistence mode should be enabled... @krfricke can you investigate?

**Comment by matthewdeng** [comment]
Oh @krfricke I think it's because you didn't pull the latest changes of the branch before committing this. The parent of https://github.com/ray-project/ray/commit/3fdfc126ba701f5aba45e753e1deb8d17dabd64e is https://github.com/ray-project/ray/commit/b0f638a0dc4443445a75617c24ddf6613166a3af (2 weeks ago).

**Comment by GeneDer** [comment]
Pick of https://github.com/ray-project/ray/pull/39158

@krfricke I will also log it to the sheet. Let me know if this is ready to be merged

**Comment by matthewdeng** [comment]
I'm going to close this one and include it in my list of picks :)

**Pull request closed without merging**
