### PR TITLE
[ci] Upgrade pydantic 1.9 to 1.10

### PR DESCRIPTION
**Pull request by can-anyscale**
Upgrade pydantic 1.9 to 1.10; we are seeing incompatible issues with pydantic 1.9 in release tests https://buildkite.com/ray-project/release-tests-branch/builds/1962#018971be-19e9-4c0d-85b1-a7e692790773

Test strategies:
- CI

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]

**Comment by can-anyscale** [comment]
Tests fail, doesn't work out-of-the-box :(

**Comment by shrekris-anyscale** [comment]
I'll be taking over this PR.

**Comment by can-anyscale** [comment]
CC: @shrekris-anyscale we might need this before the branch cut in one week

**Comment by shrekris-anyscale** [comment]
Thanks for bumping this @can-anyscale. We should have a fix by then.

**Review by edoakes — APPROVED** [review]

**Comment by can-anyscale** [comment]
We need a stamp from ray-docs owner as well, @ericl , @pcmoritz . For context, a recent change unexpectedly downgraded pydantic to 1.9.2, and we have seen some weird behaviors in ray.init with that downgrade. This PR upgrades it back.

**Review by ericl — APPROVED** [review]

**Pull request merged**
