### PR TITLE
Revert "Revert "[RLlib] Upgrade to gymnasium 1.0.0 (ale_py 0.10.1, mujoco 3.2.4, pettingzoo 1.24.3 supersuit 3.9.3).""

### PR DESCRIPTION
**Pull request by sven1977**
Reverts ray-project/ray#48297

### CODE REVIEW

**Review by simonsays1980 — APPROVED** [review]
LGTM.

**Review by can-anyscale — APPROVED** [review]

**Review by aslonnie — APPROVED** [review]

**Comment by can-anyscale** [comment]
rllib tests are still failing https://buildkite.com/ray-project/release/builds/24900 so reverting this

**Comment by can-anyscale** [comment]
revert PR: https://github.com/ray-project/ray/pull/48435

**Pull request merged**
