### PR TITLE
Updated integration to keras

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
## Why are these changes needed?
Introduced reporting of all the metrics used for a given Keras model (eg. AUROC) without effort.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by krfricke** [comment]
Hi @LucaCappelletti94 and thanks for your PR! It's great that you aim to improve our library.

As a matter of fact, I was working on a PR extending the Keras callbacks in parallel, which will mirror the API we introduced in the PyTorch Lightning callbacks and XGBoost callbacks. Is there any functionality you would like to see that wasn't included before and is included in your PR? It would be great to learn about your use case and what you tried to specifically improve with your changes.

**Comment by krfricke** [comment]
I added the PR here: https://github.com/ray-project/ray/pull/10509

Let me know if there's any functionality missing you'd like to see.

**Comment by LucaCappelletti94** [comment]
Hello @krfricke, could we have a google meet call to discuss this? I think I am missing a few steps in the structure of your pull request, such as re-implementing the checkpoint callback which is already available in Keras for instance.

Most likely you will be able to quickly clarify these things in a call.

Thanks!

**Comment by krfricke** [comment]
Sure, feel free to reach out to me at [kai at anyscale dot com].

As for the checkpoint callback, Tune requires to use the `tune.checkpoint_dir()` context and a subsequent call to `tune.report()` to register checkpoints. It's thus not just about saving the model (as would be with the Keras callback), but to make them usable for search/scheduling algorithms, like Population Based Training.

**Pull request closed without merging**
