### PR TITLE
Package pyarrow along with ray.

### PR DESCRIPTION
**Pull request by robertnishihara**
This is intended to address #810. There may be better ways to do this, so I'm open to suggestions.

**What this PR does:**
- When installing Ray, instead of running `python setup.py install` for pyarrow, we build pyarrow with `python setup.py build` and `python setup.py build_ext` (both are necessary).
- We then copy the directory `src/thirdparty/arrow/python/build/lib*/pyarrow` to `python/ray/pyarrow_files/pyarrow`, so that it gets installed along with `python/ray`. However, this pyarrow is not on the PYTHONPATH, so `import pyarrow` won't find it.
- In Ray's setup.py, we add all of the non-directory files to the list of files that we manually copy, so they get installed.
- When we start Ray, we add the internal copy of pyarrow to the PYTHONPATH so that `import pyarrow` finds it.

**Comments/Problems:**
- The directory that we copy doesn't have a consistent name, so I'm just grepping for `src/thirdparty/arrow/python/build/lib*`.
- We copy more files than we need to, but we don't copy anything in a directory, so we may miss some stuff.

### CODE REVIEW

**Comment by robertnishihara** [comment]
Interesting, one of the jenkins tests failed with

```
python: can't open file '/ray/python/ray/rllib/a3c/example.py': [Errno 2] No such file or directory
```

which makes me think it's using the docker image built by a different PR.

**Comment by robertnishihara** [comment]
test this please

**Comment by robertnishihara** [comment]
In terms of implementation, the Arrow format supports [dictionary encoding](https://github.com/apache/arrow/blob/master/format/Layout.md#dictionary-encoding), which basically lets you have multiple references to the same object. Presumably this feature could be used for serializing Python objects with multiple copies of the same internal object.

This should cover most important situations. However, if we do this, there will likely still be some shortcomings. In particular, consider the following.

```python
import numpy as np
import ray

ray.init()

x = np.zeros(3)

def f():
    return x
```

There is only one array involved.

```python
f()[0] = 1
assert x[0] == 1
```

However, suppose we wish to serialize the tuple `(x, f)`. Then we our serialization library will serialize `x` intelligently as an array. However, `f` is a function, which our serialization library will treat as a black box, so we'll fallback to cloudpickle for serializing `f`. When we deserialize things on the other side, the arrays `x` and `f()` will be different.

**Comment by wesm** [comment]
Now that pyarrow + plasma is in PyPI, might see if you can depend on a pinned version

**Comment by robertnishihara** [comment]
We still need to compile Arrow since we're linking in the Plasma client library in a few places (mostly in the plasma manager executable). But we could pull pyarrow from PyPI and avoid building pyarrow ourselves. That would probably be cleaner.

Pinning to a specific version (presumably through something like `install_requires=["pyarrow == 0.6.0"]` in our `setup.py` should work. Though it means that installing Ray would change people's version of pyarrow and also that upgrading/downgrading pyarrow would break their Ray installation.

**Comment by wesm** [comment]
Gotcha, makes sense. I figure at some point we'll get to enough ABI stability that this may not be as much of a concern

**Pull request merged**
