### PR TITLE
Adds Valgrind tests for multi-threaded object manager.

### PR DESCRIPTION
**Pull request by elibol**
Adds Valgrind tests for multi-threaded object manager.

### CODE REVIEW

**Comment by pcmoritz** [comment]
retest this please

**Comment by pcmoritz** [comment]
retest this please

**Comment by pcmoritz** [comment]
on travis the test seems to be hanging: https://travis-ci.com/robertnishihara/ray-private-travis/jobs/119180278

**Comment by elibol** [comment]
I think the hanging is fixed by the changes in #1891. I've updated the tests here to reflect the changes in that PR, and pushed to private travis.

**Comment by pcmoritz** [comment]
retest this please

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
