### PR TITLE
Move num_cpu note to resources page to avoid confusion

### LINKED ISSUE #48867: [Core] Misleading documentation about `num_cpus` and physical resources
### Description

The [Physical Resources and Logical Resources](https://docs.ray.io/en/latest/ray-core/scheduling/resources.html#physical-resources-and-logical-resources) section of the Ray docs, very explicitly states

>Resource requirements of tasks or actors do NOT impose limits on actual physical resource usage. For example, Ray doesn’t prevent a num_cpus=1 task from launching multiple threads and using multiple physical CPUs.

While _technically_ true, this sections reads as if `num_cpus` is strictly for scheduling and has _no_ implication for job performance. However, this is untrue and this section of the docs contradicts the **NOTE** in [Cluster Resources](https://docs.ray.io/en/latest/ray-core/configure.html#cluster-resources) which highlights explicitly the interaction of `num_cpus` and `OMP_NUM_THREADS` (and, by extension, `torch.get_num_cpus()`, etc).

> Ray sets the environment variable OMP_NUM_THREADS=<num_cpus> if num_cpus is set on the task/actor

In practice, lowering `OMP_NUM_THREADS` can lead to a pretty meaningful degradation in job perf, especially for jobs that require `torch` and `numpy`.

Of note, Physical Resources and Logical Resources is very high in the docs tree: it's under Ray -> User Guides. Cluster Resources is much lower under Developer Guides -> Configuring Ray. This adds to the confusion.

One suggestion would be to explicitly mention how `num_cpus` affects `OMP_NUM_THREADS` in the Physical Resources and Logical Resources section. Or, just link to Cluster Resources from there.

### Link

[Physical Resources and Logical Resources](https://docs.ray.io/en/latest/ray-core/scheduling/resources.html#physical-resources-and-logical-resources)

[Cluster Resources](https://docs.ray.io/en/latest/ray-core/configure.html#cluster-resources)

### PR DESCRIPTION
**Pull request by Superskyyy**
closes: https://github.com/ray-project/ray/issues/48867

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Superskyyy** [comment]
I can't tell where the doc build went wrong, any insights?

**Comment by can-anyscale** [comment]
@Superskyyy the following places in the doc refers to `omp-num-thread-note` which you deleted in your PR


```
[2024-11-22T18:47:06Z] /ray/doc/source/serve/resource-allocation.md:86: WARNING: 'myst' cross-reference target not found: 'omp-num-thread-note' [myst.xref_missing]
--
  | [2024-11-22T18:47:07Z] /ray/python/ray/train/tensorflow/tensorflow_trainer.py:docstring of ray.train.tensorflow.tensorflow_trainer.TensorflowTrainer:34: WARNING: undefined label: 'omp-num-thread-note'
  | [2024-11-22T18:47:07Z] /ray/doc/source/train/distributed-tensorflow-keras.rst:69: WARNING: undefined label: 'omp-num-thread-note'
```

**Comment by Superskyyy** [comment]
> @Superskyyy the following places in the doc refers to `omp-num-thread-note` which you deleted in your PR
> 
> ```
> [2024-11-22T18:47:06Z] /ray/doc/source/serve/resource-allocation.md:86: WARNING: 'myst' cross-reference target not found: 'omp-num-thread-note' [myst.xref_missing]
> --
>   | [2024-11-22T18:47:07Z] /ray/python/ray/train/tensorflow/tensorflow_trainer.py:docstring of ray.train.tensorflow.tensorflow_trainer.TensorflowTrainer:34: WARNING: undefined label: 'omp-num-thread-note'
>   | [2024-11-22T18:47:07Z] /ray/doc/source/train/distributed-tensorflow-keras.rst:69: WARNING: undefined label: 'omp-num-thread-note'
> ```

I see, let me fix that up.

**Comment by Superskyyy** [comment]
@can-anyscale Hi please review again. thanks

**Review by can-anyscale — APPROVED** [review]

**Pull request merged**
