### PR TITLE
Suggestions of correct inputs to `create_storage` in error message

### LINKED ISSUE #22640: [Bug] Ray Workflow in c:\ray does not work on windows
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

```python
from ray import workflow
workflow.init(r'c:\ray')
```
Fail with the following exception:

> File "C:\miniconda3\...\lib\site-packages\ray\workflow\storage\__init__.py", line 50, in create_storage
>     raise ValueError(f"Invalid url: {storage_url}")
> ValueError: Invalid url: c:\ray
> 
(`'c:/ray'` and `r'file:///c:\ray'` also fail)

### Versions / Dependencies

ray-1.10.0

### Reproduction script

see above

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by czgdp1807**
## Why are these changes needed?

N.B. - https://github.com/ray-project/ray/issues/22640#issuecomment-1063714842

## Related issue number

Closes #22640 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by suquark** [comment]
could we add a test for this? e.g., checking error messages under windows with incorrect URL

**Comment by suquark** [comment]
could we add a test for this? e.g., checking error messages under windows with incorrect URL

**Comment by czgdp1807** [comment]
> could we add a test for this? e.g., checking error messages under windows with incorrect URL

Done.

**Review by suquark — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
