### PR TITLE
[RLlib] Fix multi-agent PyTorch.

### PR DESCRIPTION
**Pull request by sven1977**
Fix multi-agent for PyTorch (broken since https://github.com/ray-project/ray/pull/7769) plus test case.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Review by ericl — CHANGES_REQUESTED** [review]
Actually this doesn't seem right. We should not be checking the policy type, it might be a custom policy.

**Comment by ericl** [comment]
In fact, it should be allowed to mix TF and torch policies in training.

**Comment by ericl** [comment]
I think we can https://github.com/ray-project/ray/pull/8241 instead for the release; would be good to have the tests here too though.

**Comment by sven1977** [comment]
Moved the hierarchical tests into another PR.

**Pull request closed without merging**
