### PR TITLE
[Windows] use correct interpreter and fix prometheus atomic file rename

### LINKED ISSUE #16084: Fail to connect to head in another machine
### What is the problem?

Ray --1.2.0
Windows10
Python 3.8.3

I was running ray in one machine and I cannot connect to the remote server. Ray 1.2.0 or 1.3.0 neither worked
on another machine which has already started the ray service and connected to the head node(They are in the same network)
```Python
import ray
from ray.util.queue import Queue

ray.init(address='auto', _redis_password='5241590000000000')
# You can pass this object around to different tasks/actors
print("Start to Run!")
```
The output is as follows
```
2021-05-26 21:04:53,912 INFO worker.py:654 -- Connecting to existing Ray cluster at address: 183.172.63.51:6379
```
Then nothing happened, even without an exit code
I cannot run the code except in the head node

### PR DESCRIPTION
**Pull request by carlogrisetti**
When `sys.platform == "win32"` don't use bash and use cmd instead.
Also, fix a "bug" in prometheus temporary file handling. os.rename is atomic in Linux but not on Windows, and often fails due to the file being locked.
os.replace does the same job as os.rename, is atomic in both Linux and Windows, and has been introduced in Python 3.3 (Ray targets Python 3.6+)

... and yes, I know Windows it's not supported and it's not working still... but one brick at a time... :)

### CODE REVIEW

**Comment by carlogrisetti** [comment]
This now looks for the interpreter, rather than relying on the platform. This allows leveraging Cygwin\WSL configurations, and should also include darwin.

**Comment by pcmoritz** [comment]
@edoakes Can somebody from your team review?

**Review by edoakes — COMMENTED** [review]
Looks good at a high level, just a concern about the shutil check vs. windows-specific guarding

**Comment by edoakes** [comment]
@carlogrisetti I think the reason we're doing `exec` instead of `os.system` is to avoid spawning in a subprocess because the raylet assumes it spawns a direct child process.

I believe `sys.platform` should only return `win32` when actually run on windows (it'll return `linux` in WSL and `cygwin` in Cygwin per this [stackoverflow post](https://stackoverflow.com/questions/446209/possible-values-from-sys-platform)), so how about we have a `if sys.platform == "win32": <new behavior> else: <old behavior`? That should maintain compatibility and make it explicit. Let me know if I'm missing something/mistaken on sys.platform.

**Comment by edoakes** [comment]
cc @architkulkarni @simon-mo FYI for runtime_env changes

**Comment by carlogrisetti** [comment]
Tests seem to be throwing a 500 internal server error while trying to download https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
Should be unrelated to the PR itself... I think

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
Yeah @carlogrisetti the CI failures look strange / unrelated -- could you merge master and push again to trigger another run?

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@carlogrisetti other PR merged, push to re-trigger CI?

**Pull request merged**
