### PR TITLE
[tune] Improve mnist_pytorch.py example

### LINKED ISSUE #3873: [tune] Option --no-cuda is misleading in mnist_pytorch.py example
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.2
- **Python version**: 3.5
- **Exact command to reproduce**:

```
python3 mnist_pytorch.py
```

### Describe the problem

Argument parser's option `--no-cuda` which is False by default is misleading as `resources_per_trial` does not allocate a GPU.

https://github.com/ray-project/ray/blob/eddd60e14e95a2aadb06192bd141d06c68d5f082/python/ray/tune/examples/mnist_pytorch.py#L45-L49

https://github.com/ray-project/ray/blob/eddd60e14e95a2aadb06192bd141d06c68d5f082/python/ray/tune/examples/mnist_pytorch.py#L178-L180

Thanks

### PR DESCRIPTION
**Pull request by vfdev-5**
## What do these changes do?

* Improved --no-cuda handling
* Removed deprecated Variable usage

## Related issue number

Fixes #3873

### CODE REVIEW

**Comment by richardliaw** [comment]
jenkins retest this please

**Comment by richardliaw** [comment]
This test is failing - can you resolve this? https://travis-ci.com/ray-project/ray/jobs/173926439

**Comment by vfdev-5** [comment]
@richardliaw sorry for that. Yes, I can fix flake8. Thanks for pointing out

**Comment by richardliaw** [comment]
jenkins retest this please

**Comment by richardliaw** [comment]
Yeah I would just run (in `ray/`), `./scripts/format.sh` - this will automatically fix formatting for your code (we have a format standard)

**Comment by richardliaw** [comment]
jenkins retest this please

**Review by richardliaw — APPROVED** [review]

**Pull request merged**
