### PR TITLE
Fix resnet crash by setting config.gpu_options.allow_growth = True.

### PR DESCRIPTION
**Pull request by ustcfriend**
Resnet example will crash when run with GPU, this fix could fix this issue.

### CODE REVIEW

**Comment by robertnishihara** [comment]
ok to test

**Comment by robertnishihara** [comment]
Thanks for the patch! I just tried it out and it does seem to address #916 for me.

I'll merge this when the tests run. @Wapaul1 please take a look if you have a chance.

Also @ustcfriend, note that a lot of this code will change soon. We are working on rewriting the ResNet example using datasets instead of queues (see #960).

**Comment by robertnishihara** [comment]
Why did you suspect that this would solve the problem? Do you have a deeper understanding of what was going wrong?

**Comment by ustcfriend** [comment]
@robertnishihara 
This issue is caused by the GPU memory was fully occupied by TF when start TF session, the train/test data couldn't be set into GPU memory.
The fix option is set to tell TF the GPU will be shared with more process, so the TF won't occupy the whole memory when start.

Thanks.

**Comment by robertnishihara** [comment]
@ustcfriend makes sense. Thanks a lot for the fix!

**Pull request merged**
