### PR TITLE
Fix typo in ray status output

### PR DESCRIPTION
**Pull request by Superskyyy**
## Why are these changes needed?
before
```text
RuntimeError: System error: Ray cluster at 10.218.163.85:6379 has version 2.10.0, but this processis running Ray version 2.9.2.
```
after 
```text
RuntimeError: System error: Ray cluster at 10.218.163.85:6379 has version 2.10.0, but this process is running Ray version 2.9.2.
```

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]
Thanks a lot for the fix!!

**Comment by jjyao** [comment]
@Superskyyy can you fix the DCO?

**Comment by Superskyyy** [comment]
> Thanks a lot for the fix!!

Thanks a lot, I think my email address in sign-off was wrongly matched, I did set it as primary email in  GitHub though, maybe didn't propagate in time.

**Comment by Superskyyy** [comment]
Maybe I need your help to trigger a rerun of DCO or should I reopen a PR? Please advice. The sign-off is already correct.

**Comment by Superskyyy** [comment]
@jjyao Fixed, please review again, thank you!

**Review by jjyao — APPROVED** [review]

**Pull request merged**
