### PR TITLE
Replaced discontinued rnn_cell.BasicLSTMCell with rnn_cell.LSTMCell

### PR DESCRIPTION
**Pull request by federicofontana**
## What do these changes do?
`rllib.models.lstm` is currently using [tf.nn.rnn_cell.BasicLSTMCell](https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell/BasicLSTMCell). However, as pointed out in the docs, `BasicLSTMCell` will be deprecated from tensorflow 1.13 and should be replaced with `tf.nn.rnn_cell.LSTMCell`. No need to change the signature. 

Tested on CartPoleStatelessEnv and it works:
image

## Related issue number
None

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by ericl** [comment]
Thanks. @joneswong is this ok to remove? Not sure which TF version rnn_cell.LSTMCell was added.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Tests look good, merging this.

**Comment by joneswong** [comment]
> Thanks. @joneswong is this ok to remove? Not sure which TF version rnn_cell.LSTMCell was added.

sorry for late reply (just came back from a trip). According to the TF docs, `tf.nn.rnn_cell.LSTMCell` has been introduced since TF1.1. Before that, e.g., in r1.0, this is still in tf.contrib folders.

**Comment by FedericoFontana** [comment]
I should probably remark that `LSTMCell` and `BasicLSTMCell` are comparable in terms of performance and training time when used to solve CartPoleStatelessEnv. I'm not sure if we can generalize this statement for complex environments. Another reason for this PR is that there is an annoying DepreciationWarning in ray's INFO loggings when using the older `BasicLSTMCell` with tf 1.12.0.

**Pull request merged**
