### PR TITLE
Revert "[core][dashboard] Task backend GC policy - GCS refactor [2/3]…

### PR DESCRIPTION
**Pull request by rickyyx**
…  (#38792)"

This reverts commit 3e8278dc8809274a7c324797897223b8a5b8bc5b.

The revert is to fix the memory leak seen in GCS: https://github.com/ray-project/ray/issues/40568

See https://github.com/ray-project/ray/issues/40568#issuecomment-1781686608 for more details

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by jjyao** [comment]
Could you update the PR description to include why

**Review by vitsai — APPROVED** [review]

**Comment by vitsai** [comment]
DCO

**Comment by rickyyx** [comment]
Instead of a cherry-pick, we are doing a direct revert here because a cherry pick of the master's revert (https://github.com/ray-project/ray/pull/40715) would be less trivial due to merge conflict. cc @zhe-thoughts

**Review by zhe-thoughts — APPROVED** [review]

**Comment by can-anyscale** [comment]
Forge merge since this is time-sensitive and the issue in premerge is unrelated

**Pull request merged**
