### PR TITLE
[1.10.0 release] [Do not merge] Add release logs for 1.10.0rc0

### PR DESCRIPTION
**Pull request by architkulkarni**
## Related issue number
Do not merge this PR.  In this PR I've added the release test logs for 1.10.0rc0 so that we can catch any potential regressions early.

When the final 1.10.0 release is ready, I will make another PR with the release test logs for 1.10.0, and we will merge that PR.

Here's the PR for 1.9 in case it's helpful: https://github.com/ray-project/ray/pull/20781

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Hi @rkooo567 and @wuisawesome, could you please check this for regressions?  It might be easiest to check this commit using the side-by-side diff: https://github.com/ray-project/ray/pull/21434/commits/d6440c80525d153e6195572d2d26529abcfb2b3d Please reassign if necessary and let me know if it looks good!

**Comment by architkulkarni** [comment]
One thing I noticed was that smoke_test was enabled for two tests, not sure if it's intended.

**Comment by rkooo567** [comment]
@architkulkarni you should run non-smoke test. Other number lgtm

**Comment by architkulkarni** [comment]
Ah you're right, the non-smoke tests are in Core Daily, which I didn't check.  I'll update the release process with that instruction and I'll let you know when I've updated this PR!

**Comment by architkulkarni** [comment]
Closed in favor of https://github.com/ray-project/ray/pull/21512

**Pull request closed without merging**
