### PR TITLE
[tune] Use traceback.format_tb() (fixes #5135)

### LINKED ISSUE #5135: [tune] err_tb.format_exc() undefined in function_runner
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary (PyPI)
- **Ray version**: 0.7.2
- **Python version**: 3.6
- **Exact command to reproduce**: N/A

### Describe the problem

When the objective function I am attempting to optimise with Tune crashes, Ray throws another exception complaining that the traceback object it gets has no `.format_exc()` attribute. It then claims that my function completed without dying or reporting any results.

### Source code / logs

Here is the relevant part of the traceback:

```
… traceback from my app up here…

(pid=21249) During handling of the above exception, another exception occurred:
(pid=21249)
(pid=21249) Traceback (most recent call last):
(pid=21249)   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=21249)     self.run()
(pid=21249)   File "/home/sam/.virtualenvs/asnets/lib/python3.6/site-packages/ray/tune/function_runner.py", line 105, in run
(pid=21249)     err_tb = err_tb.format_exc()
(pid=21249) AttributeError: 'traceback' object has no attribute 'format_exc'
(pid=21249)
2019-07-07 10:14:16,574 ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/home/sam/.virtualenvs/asnets/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/sam/.virtualenvs/asnets/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/sam/.virtualenvs/asnets/lib/python3.6/site-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_WrappedFunc:train() (pid=21249, host=sam-ThinkPad-E470)
  File "/home/sam/.virtualenvs/asnets/lib/python3.6/site-packages/ray/tune/trainable.py", line 150, in train
    result = self._train()
  File "/home/sam/.virtualenvs/asnets/lib/python3.6/site-packages/ray/tune/function_runner.py", line 206, in _train
    ("Wrapped function ran until completion without reporting "
ray.tune.error.TuneError: Wrapped function ran until completion without reporting results or raising an exception.
```

The error seems to be due to [the following lines](https://github.com/ray-project/ray/blob/6a14f1a540d1c97d812cfcc2aecb1654028b279f/python/ray/tune/function_runner.py#L100-L108) in `function_runner.py`:

```python
# report the error but avoid indefinite blocking which would
# prevent the exception from being propagated in the unlikely
# case that something went terribly wrong
err_type, err_value, err_tb = sys.exc_info()
err_tb = err_tb.format_exc()
```

Python traceback objects don't seem to have a `format_exc()` attribute (at least as of 3.7), so I assume that last was a typo. Importing the `traceback` module and replacing `err_tb.format_exc()` with `traceback.format_tb(err_tb)` (or `traceback.format_exc()`) makes it go away.

### PR DESCRIPTION
**Pull request by qxcv**
## What do these changes do?

Fixes lookup of unknown attribute in Tune's ` function_runner.py`. See #5135.

## Related issue number

Fixes #5135.

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by richardliaw** [comment]
This is great! Can I see what happens to your application after this patch?

**Comment by qxcv** [comment]
The relevant part of the log looks like this:

```
2019-07-07 17:08:58,598 ERROR trial_runner.py:545 -- Error processing event.
Traceback (most recent call last):
  File "/home/sam/repos/ray/python/ray/tune/trial_runner.py", line 494, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/sam/repos/ray/python/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/sam/repos/ray/python/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_WrappedFunc:train() (pid=25574, host=sam-ThinkPad-E470)
  File "/home/sam/repos/ray/python/ray/tune/trainable.py", line 154, in train
    result = self._train()
  File "/home/sam/repos/ray/python/ray/tune/function_runner.py", line 198, in _train
    self._report_thread_runner_error(block=True)
  File "/home/sam/repos/ray/python/ray/tune/function_runner.py", line 244, in _report_thread_runner_error
    err_tb=err_tb))
ray.tune.error.TuneError: Trial raised a <class 'ray.exceptions.RayTaskError'> exception with value: ray_worker:asnets.scripts.run_experiment.run_asnets_local() (pid=25577, host=sam-ThinkPad-E470)
  File "/home/sam/repos/l4p/asnets/asnets/scripts/run_experiment.py", line 159, in run_asnets_local
    raise Exception(msg)
Exception: could not find any snapshots in '/home/sam/repos/l4p/asnets/experiment-results/<dir>'
With traceback:
2019-07-07 17:08:58,599 INFO log_sync.py:59 -- Worker ip unknown, skipping log sync for experiment-results/tune/perform_trial/perform_trial_1_dropout=0.25,hidden_size=14,l1_reg=1.7357e-05,l2_reg=5.6581e-05,num_layers=2,opt_batch_per_epoch=1524,ssipp_teache_2019-07-07_17-08-48n63cje2i/
2019-07-07 17:08:58,601 INFO ray_trial_executor.py:187 -- Destroying actor for trial perform_trial_1_dropout=0.25,hidden_size=14,l1_reg=1.7357e-05,l2_reg=5.6581e-05,num_layers=2,opt_batch_per_epoch=1524,ssipp_teacher_heuristic=h-add,supervised_batch_size=100,target_rollouts_per_epoch=569. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/1 GPUs
Memory usage on this node: 7.6/16.7 GB
Result logdir: experiment-results/tune/perform_trial
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
…
```

**Comment by richardliaw** [comment]
Given the `With traceback:`, it looks like there's no traceback now? Here's the relevant part of the code:

```python
    def _report_thread_runner_error(self, block=False):
        try:
            err_type, err_value, err_tb = self._error_queue.get(
                block=block, timeout=ERROR_FETCH_TIMEOUT)
            raise TuneError(("Trial raised a {err_type} exception with value: "
                             "{err_value}\nWith traceback:\n{err_tb}").format(
                                 err_type=err_type,
                                 err_value=err_value,
                                 err_tb=err_tb))
        except queue.Empty:
            pass
```

**Comment by richardliaw** [comment]
With a quick function that raises a Value Error, I got:

```
2019-07-07 17:33:58,657	INFO log_sync.py:59 -- Worker ip unknown, skipping log sync for /Users/rliaw/ray_results/my_exp/easy_objective_1_height=-16.596,iterations=100,width=14.406_2019-07-07_17-33-539aj4npso/
2019-07-07 17:33:58,658	INFO ray_trial_executor.py:187 -- Destroying actor for trial easy_objective_1_height=-16.596,iterations=100,width=14.406. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2019-07-07 17:33:58,668	INFO log_sync.py:59 -- Worker ip unknown, skipping log sync for /Users/rliaw/ray_results/my_exp/easy_objective_5_height=-20.647,iterations=100,width=10.776_2019-07-07_17-33-58pnjkz3j0/
2019-07-07 17:33:58,682	ERROR trial_runner.py:545 -- Error processing event.
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 494, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 2195, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=39340, host=C02TX1VXHTDD)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 154, in train
    result = self._train()
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 198, in _train
    self._report_thread_runner_error(block=True)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 244, in _report_thread_runner_error
    err_tb=err_tb))
ray.tune.error.TuneError: Trial raised a <class 'ValueError'> exception with value: kill
With traceback:
['  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 93, in run\n    self._entrypoint()\n', '  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 144, in entrypoint\n    return self._trainable_func(config, self._status_reporter)\n', '  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/function_runner.py", line 263, in _trainable_func\n    output = train_func(config, reporter)\n', '  File "bayesopt_example.py", line 18, in easy_objective\n    raise ValueError("kill")\n']

```

**Comment by qxcv** [comment]
Good catch! I'm not sure why it's not producing any output on my end, but my `format_tb()` usage is wrong in any case. I've replaced with `sys.format_exc` and now I get this:

```
With traceback:                                                 
ray_WrappedFunc:train() (pid=28051, host=sam-ThinkPad-E470)                                                                                                                                                                                                                             
  File "/home/sam/repos/ray/python/ray/tune/function_runner.py", line 93, in run
    self._entrypoint()                                                                                    
  File "/home/sam/repos/ray/python/ray/tune/function_runner.py", line 144, in entrypoint                                                                                                                                                                                                     
    return self._trainable_func(config, self._status_reporter)                                                                                                                                                                                                                                                                                                                                                
  File "/home/sam/repos/ray/python/ray/tune/function_runner.py", line 263, in _trainable_func
    output = train_func(config, reporter)                                                                         
  File "./asnets/scripts/hype.py", line 54, in perform_trial          
    enforce_job_ncpus=True)                                                                                                             
  File "/home/sam/repos/l4p/asnets/asnets/scripts/run_experiment.py", line 384, in main_inner                                                                                                                                                     
    timeout=arch_mod.TIME_LIMIT_SECONDS))                                                                             
ray.exceptions.RayTaskError: ray_worker:asnets.scripts.run_experiment.run_asnets_local() (pid=28052, host=sam-ThinkPad-E470)
  File "/home/sam/repos/l4p/asnets/asnets/scripts/run_experiment.py", line 159, in run_asnets_local                                                                                                                                                                                                                                                                                                                                         
    raise Exception(msg)                                                                                                                            
Exception: could not find any snapshots in '/home/sam/repos/l4p/asnets/experiment-results/<dir>'
                                                                                                                                                                                                                                                                                             
                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                            
2019-07-07 17:36:49,282 INFO log_sync.py:59 -- Worker ip unknown, skipping log sync for experiment-results/tune/perform_trial/perform_trial_1_dropout=0.25,hidden_size=15,l1_reg=0.00042305,l2_reg=0.021143,num_layers=3,opt_batch_per_epoch=666,ssipp_teacher_h_2019-07-07_17-36-39muy_7oc0/                                                                                                                                          
2019-07-07 17:36:49,283 INFO ray_trial_executor.py:187 -- Destroying actor for trial perform_trial_1_dropout=0.25,hidden_size=15,l1_reg=0.00042305,l2_reg=0.021143,num_layers=3,opt_batch_per_epoch=666,ssipp_teacher_heuristic=h-add,supervised_batch_size=112,target_rollouts_per_epoch=321. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
== Status ==                                                                                           
Using FIFO scheduling algorithm.
…
```

**Comment by richardliaw** [comment]
Yeah, looks better; what if we just replace the error_queue with holding taking result of `traceback.format_exc`? I think that'll just make things simpler. The section:

```
("Trial raised a {err_type} exception with value: "
                             "{err_value}\n
```
is quite redundant and can be removed (`_report_thread_runner_error()`). Can you help make that change in this PR? I'd really appreciate it!

**Comment by qxcv** [comment]
You mean like this? (latest commit)

**Comment by richardliaw** [comment]
Looks great - will merge pending tests. Thanks a bunch!

**Review by richardliaw — APPROVED** [review]

**Pull request merged**
