### PR TITLE
[Tracing] Delay Opentelemetry Import to Avoid Pickling

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* Tracing causes many errors with RayClient because `opentelemetry` may be available locally, but not on the remote server. This causes errors because `opentelemtry` is **pickled** on the client side and causes an error when it is deserialized on the server!

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
LGTM but this is really hacky. However, I can't figure out a better way to fix this...

**Comment by AmeerHajAli** [comment]
I am testing this manually ...

**Comment by AmeerHajAli** [comment]
I am testing this manually ...
@ericl , are you ok with this fix for the opentelemetary bug (https://github.com/anyscale/product/issues/4782, part of the runtime envs)

**Comment by ericl** [comment]
I'm a bit confused, why not install opentelemetry in the cluster (shouldn't it come by default with the full ray install?)

**Comment by ijrsvt** [comment]
@ericl We are doing that now as well now. This is to ensure that these errors don't arise in other situations.

**Comment by ericl** [comment]
What other situations? I don't think we should merge this since this could happen with any of the libraries we use (are we going to do this for all of them)?

**Comment by ijrsvt** [comment]
@ericl We can avoid merging this if we put OTEL in the 'core' part of Ray (i.e. the base `pip install ray`, not `pip install ray[all]`).

> other situations
* A user creates a conda environment that doesn't explicitly include otel. 
* A user is using a minimal docker image that only has the core ray library.

**Comment by ijrsvt** [comment]
@ericl This is particularly important because, unlike other dependencies, this is transparently injected into functions. The tracing code is **supposed to be a NO-OP** when `otel` is not included; this PR makes that work for client mode.

**Comment by ericl** [comment]
Oh I see. Can we add a comment explaining the rationale for the shim in the
code then? Indeed I can see users not wanting a full install, but this is a
subtle operational point.

**Comment by ijrsvt** [comment]
@ericl Sure! Let me add that to the class :)

**Comment by ijrsvt** [comment]
Quick local test:
Where server was started with `ray start --head` in a conda environment that **does not have opentelemetry** installed.

Connected with a driver that **has opentelemetry** installed (using `ray.client("localhost:10001").connect()`

Results below:
```
In [4]: @ray.remote
   ...: def f():
   ...:     return 300

In [5]: ray.get(f.remote() # Pickling trace functions works!
   ...: )
Out[5]: 300

In [7]: import opentelemetry.trace # Passes in client side

In [8]: @ray.remote
   ...: def should_fail():
   ...:     import opentelemetry.trace

In [9]: ray.get(should_fail.remote()) # Server does not have opentelemetry.trace
---------------------------------------------------------------------------
RayTaskError(ModuleNotFoundError)         Traceback (most recent call last)
<ipython-input-9-dc03f3aedab0> in <module>
----> 1 ray.get(should_fail.remote())

~/ray/python/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     59     def wrapper(*args, **kwargs):
     60         if client_mode_should_convert():
---> 61             return getattr(ray, func.__name__)(*args, **kwargs)
     62         return func(*args, **kwargs)
     63 

~/ray/python/ray/util/client/api.py in get(self, vals, timeout)
     40             timeout: Optional timeout in milliseconds
     41         """
---> 42         return self.worker.get(vals, timeout=timeout)
     43 
     44     def put(self, *args, **kwargs):

~/ray/python/ray/util/client/worker.py in get(self, vals, timeout)
    200                     else:
    201                         op_timeout = MAX_BLOCKING_OPERATION_TIME_S
--> 202                     res = self._get(obj_ref, op_timeout)
    203                     break
    204                 except GetTimeoutError:

~/ray/python/ray/util/client/worker.py in _get(self, ref, timeout)
    223                 logger.exception("Failed to deserialize {}".format(data.error))
    224                 raise
--> 225             raise err
    226         return loads_from_server(data.data)
    227 

RayTaskError(ModuleNotFoundError): ray::should_fail() (pid=8853, ip=172.31.47.243)
  File "python/ray/_raylet.pyx", line 497, in ray._raylet.execute_task
    with ray.worker._changeproctitle(title, next_title):
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
    outputs = function_executor(*args, **kwargs)
  File "/home/ubuntu/ray/python/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/home/ubuntu/ray/python/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "<ipython-input-8-1d9b49134183>", line 3, in should_fail
ModuleNotFoundError: No module named 'opentelemetry.trace'
```

**Comment by ijrsvt** [comment]
Tune test failure is unrelated!

**Pull request merged**
