### PR TITLE
[runtime env] [test] Add nightly test to verify Ray wheel URLs are valid

### LINKED ISSUE #17838: [runtime env] Ray wheel URLs are wrong for Mac OS
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
As a side effect of https://github.com/ray-project/ray/pull/16913 a portion of the Ray Mac wheel URLs changed from `10_13` to `10_15`, e.g. `https://s3-us-west-2.amazonaws.com/ray-wheels/releases/$RAY_VERSION/$RAY_HASH/ray-$RAY_VERSION-cp36-cp36m-macosx_10_15_intel.whl`  

The functions `get_master_wheel_url()` and `get_release_wheel_url()` need to be updated to reflect this; until then runtime envs will be broken on Mac because the workers' conda environments will be downloading Ray from a broken URL. We should add a nightly test to catch this kind of thing (it should test the Mac URLs even when run from a Linux machine); a pre-merge CI test won't work because there won't be a commit and wheel URL to test against.
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Ray has an internal function that generates the URLs for the currently running Ray wheel.  These URLs are used by the runtime environments feature to download the current version of Ray into an isolated conda environment on each worker.

This PR adds a nightly test for this function that pings these generated URLs for the current Ray commit and for all platforms, to check that the URLs are valid. Because it's a nightly test and not a pre-merge test, at the time of running the test there will be wheels present at these URLs. This test will catch any change in the format of the wheel URLs (any such change would cause runtime environments to break because the generated wheel URL would then be wrong).  

Previously this function was only tested against old hard-coded commits in a pre-merge CI test, so it could not catch these kinds of changes.

This PR also adds Python 3.9 URLs to the function so that runtime environments can work with 3.9.

## Related issue number

Closes #17838 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Nice, good idea to add this to nightly tests!

**Comment by edoakes** [comment]
@architkulkarni there were some seemingly unrelated failures in CI so I merged master to re-run.

**Comment by architkulkarni** [comment]
Windows build is failing on master.

**Review by simon-mo — APPROVED** [review]

**Comment by c3-aatifjiwani** [comment]
@simon-mo @edoakes (cc @architkulkarni)

This merged PR crucially allows runtime environment support for Python 3.9, and although this was merged before Aug. 23, this 3.9 support is not present in the release of Ray 1.6.0. 

Will it be possible to include Python 3.9 Runtime Environment support in the very near future? To the best of our knowledge, there is nothing in the current release of Ray 1.6.0 that is preventing Python 3.9 support with the exception of a hardcoded list that checks the versioning: https://github.com/ray-project/ray/blob/b5ccee6ad3bf2b4b2fdc6966ddfea965e027030d/python/ray/_private/utils.py#L1052

**Comment by architkulkarni** [comment]
Hi @c3-aatifjiwani, it will be in the next release.  You can try it out on the release candidate: `pip install "ray[default]==1.7.0rc0"`

**Comment by c3-aatifjiwani** [comment]
Awesome, thanks for the quick response @architkulkarni

**Pull request merged**
