### PR TITLE
[air] update pytorch_training_e2e.py to use iter_torch_batches.

### PR DESCRIPTION
**Pull request by xwjiang2010**
## Why are these changes needed?

update pytorch_training_e2e.py to use iter_torch_batches.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jiaodong** [comment]
Shouldn't this change also hide TensorArray or it's already updated?

**Comment by xwjiang2010** [comment]
wow, what's going on with CI...
Merging master...

@jiaodong yes, Clark managed to change that as a follow up.

**Review by jiaodong — APPROVED** [review]
This training loop is much simpler :) Thanks for simplifying this !

**Comment by krfricke** [comment]
Kicked off tests: https://buildkite.com/ray-project/release-tests-pr/builds/11790

**Pull request merged**
