### PR TITLE
[docs] Fixed the link for ray core section

### PR DESCRIPTION
**Pull request by simran-2797**
The link for the learn more in the ray core card was incorrect. Fixed the issue now.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by angelinalg — APPROVED** [review]
LGTM

**Comment by angelinalg** [comment]
Thank you for fixing this so quickly, @simran-2797 !!

**Comment by angelinalg** [comment]
Can we fix the one under Contribute Ray, too? 
` <a class="no-underline" href="https://docs.ray.io/en/latest/ray-contribute/getting-involved.html" target="_blank"> <div class="community-box">
`

**Review by angelinalg — APPROVED** [review]
LGTM

**Comment by jjyao** [comment]
@simran-2797 could you solve the merge conflict? Thanks.

**Pull request merged**
