### PR TITLE
Revert "[Core]Fix ray.kill doesn't cancel pending actor bug"

### PR DESCRIPTION
**Pull request by simon-mo**
Reverts ray-project/ray#13254

This commit is consistently failing test_failure in both macOS and Linux. Here's a sample of the build log:
https://travis-ci.com/github/ray-project/ray/jobs/481449390#L1556
```
=================================== FAILURES ===================================
_______________________ test_warning_for_too_many_actors _______________________
shutdown_only = None
    def test_warning_for_too_many_actors(shutdown_only):
        # Check that if we run a workload which requires too many workers to be
        # started that we will receive a warning.
        num_cpus = 2
        ray.init(num_cpus=num_cpus)
    
        p = init_error_pubsub()
    
        @ray.remote
        class Foo:
            def __init__(self):
                time.sleep(1000)
    
        [Foo.remote() for _ in range(num_cpus * 3)]
        errors = get_error_message(p, 1, ray_constants.WORKER_POOL_LARGE_ERROR)
>       assert len(errors) == 1
E       assert 0 == 1
E         +0
E         -1
/home/travis/build/ray-project/ray/python/ray/tests/test_failure.py:759: AssertionError

```

also FYI the PR actually failed test_failure as well before it got merged. 
https://travis-ci.com/github/ray-project/ray/jobs/480263116

cc @ffbin @rkooo567

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @ffbin

**Review by rkooo567 — APPROVED** [review]

**Comment by simon-mo** [comment]
Please open a new PR to re-revert

**Comment by ffbin** [comment]
@simon-mo Sorry, i will take a look and open a new PR.

**Comment by ffbin** [comment]
image
@simon-mo @rkooo567 The reasons for `test_warning_for_too_many_actors` failure is that:  We didn't save actor, so it's out of scope. I save the actor, the testcase can run successfully.

**Pull request merged**
