### PR TITLE
[Serve] Remove shard_key, http_method, and http_headers

### LINKED ISSUE #20033: Remove shard_key, http_method, and http_headers

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
Remove three unused concepts:
- Sharding was removed after the 1:1 relationship between endpoint and backend
- http_method was removed after adoption of starlette and fastapi
- http_headers was removed because we no longer need to specify sharding and method through headers anymore.

I also skimmed over doc mentions of these concept, seems ok
## Related issue number
Closes #20033

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@simon-mo to clarify the description, there are no instances of these in the documentation ATM?

**Comment by simon-mo** [comment]
😅 to clarify I did a skim and some greps and can't find any mentions.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by edoakes** [comment]
ping to get this merged @simon-mo

**Pull request merged**
