### PR TITLE
On ReadTheDocs, use master documentation instead of latest documentat…

### PR DESCRIPTION
**Pull request by robertnishihara**
…ion.

I'm having trouble building the documentation on readthedocs. Doing this to work around it.. ideally there would be a better way.

### CODE REVIEW

**Comment by richardliaw** [comment]
after this, would any previous links like `http://ray.readthedocs.io/en/latest/index.html` work?

**Comment by richardliaw** [comment]
@robertnishihara I fixed `readthedocs` so I think we can close this now...

**Comment by robertnishihara** [comment]
Thanks @richardliaw how did you do it?

**Comment by richardliaw** [comment]
Well the problem was that readthedocs was trying to build off of a "default branch" that was left blank, and somehow registered that to be `windows-compat`. I just specified that the default branch was `master`.

**Comment by robertnishihara** [comment]
I see, I tried to do that but couldn't figure out how.

**Pull request closed without merging**
