### PR TITLE
[Data] Propagate driver `DataContext` to `RayTrainWorkers`

### LINKED ISSUE #39237: [data] datacontext setting does not work for preprocessor
### What happened + What you expected to happen

Setting `DataContext.get_current().enable_tensor_extension_casting = False` won't work for BatchMapper preprocessor. This config is not "global". It only works when it's set in the `train_loop_per_worker`  function used by the Trainer. 

### Versions / Dependencies

Ray 2.6.3

### Reproduction script

```python
ctx = DataContext.get_current()
ctx.enable_tensor_extension_casting = False

def pd_batch(df):
    return df

batch_mapper = BatchMapper(pd_batch, batch_format="pandas")

def train_loop_per_worker(config):
   # enable_tensor_extension_casting works here but not outside train_loop_per_worker
   # ctx = DataContext.get_current()
   # ctx.enable_tensor_extension_casting = False
   ...

trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    train_loop_config=...,
    datasets=...,
    preprocessor=batch_mapper,
    scaling_config=...,
    run_config=...,
)
result = trainer.fit()
```

### Issue Severity

None

### PR DESCRIPTION
**Pull request by scottjlee**
## Why are these changes needed?
Changes made to the driver's `DataContext` are not propagated to `RayTrainWorker`s, which can lead to unexpected and inconsistent behavior between driver and workers. This PR adds the driver's `DataContext` as an initialization parameter into `RayTrainWorker`s created in a `WorkerGroup`, so that each worker will have the driver's `DataContext`.

## Related issue number

Closes #39237

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
Can we consolidate with this codepath: https://github.com/ray-project/ray/pull/29192?

Looks like this is a regression

**Comment by woshiyyya** [comment]
Seems that previously #29192 we only passed DataContext to Ray Train Trainable, this PR aims to pass into further to Ray Train Workers. 

I am actually ok with this change. @matthewdeng what do you think?

**Comment by matthewdeng** [comment]
I was under the impression that by default it was supposed to propagate across the cluster, so this does make sense to me.

Propagating it by default and allowing workers to override the context (in the train loop) sounds good to me.

**Review by amogkam — APPROVED** [review]
Got it, makes sense. Lgtm!

**Comment by amogkam** [comment]
Actually looks like the context is saved as an attribute of the dataset: https://github.com/ray-project/ray/pull/36030/files#diff-71f73f8b71d468f63f8b3be7282ec12b657a2a3f86324eb740d369e874d74df4R126.

would it be safer to use that?

**Comment by scottjlee** [comment]
> Actually looks like the context is saved as an attribute of the dataset: https://github.com/ray-project/ray/pull/36030/files#diff-71f73f8b71d468f63f8b3be7282ec12b657a2a3f86324eb740d369e874d74df4R126.

@c21 did we ever come to a consensus on whether we wanted to set this through the context?

> would it be safer to use that? how would this work with multiple datasets?
With multiple datasets, I think they will still be using the same `DataContext` since this is set at the node level, and not an individual dataset level right?

**Pull request merged**
