### PR TITLE
[Core] minor refactor for usability of runtime_env

### PR DESCRIPTION
**Pull request by architkulkarni**
This PR allows URIs to be passed in the runtime env, as well as a hidden field `_ray_release` for specifying a Ray version.
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ijrsvt — APPROVED** [review]
LGTM, is this ready to merge?

**Comment by architkulkarni** [comment]
Yeah, it's ready

**Review by ijrsvt — APPROVED** [review]
LGTM! 
Can we add some more testing around these APIs in the near future?

**Comment by ijrsvt** [comment]
Failures are unrelated: 
`test_runtime_env_complicated` is **known to be flaky** because of a wheel naming issue.
This was fixed in https://github.com/ray-project/ray/pull/15952, but reverted in https://github.com/ray-project/ray/pull/15954

**Comment by ericl** [comment]
I believe this is breaking test_runtime_env_complicated, reverting in https://github.com/ray-project/ray/pull/15985

**Comment by architkulkarni** [comment]
Yeah, this has the same issue Ian mentioned above: https://buildkite.com/ray-project/ray-builders-pr/builds/5704#2f0657da-e250-4604-80d0-23d93bcede58/6-9520

The wheel built has the name "manymanylinux20142014."  It's weird because the changes in this PR shouldn't affect it

**Comment by ijrsvt** [comment]
FWIW, this pr did not break `test_runtime_env_complicated`. In #15981 (the revert of #15802), `test_runtime_env_complicated` did pass. 

Screen Shot 2021-05-21 at 12 29 31 PM

**Comment by ericl** [comment]
I see, it does look fine now in the test dashboard. It was difficult to tell before with the couple data points.

**Pull request merged**
