### PR TITLE
[Datasets] Update `read_tfrecords` example

### PR DESCRIPTION
**Pull request by bveeramani**
Signed-off-by: Balaji Veeramani <balaji@anyscale.com>

## Why are these changes needed?

See https://github.com/ray-project/ray/pull/28430#discussion_r975735058.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by clarkzinzow — APPROVED** [review]
Nice! Although am I reading that right, that the `iris.tfrecords` file is 21 KB?

**Comment by clarkzinzow** [comment]
I think it's ok as is, but does the current `iris.tfrecords` file have the same number of samples as e.g. the `iris.csv` file? I'd be surprised if so, I'd assume that the binary format would be smaller than the plain-text format.

**Comment by bveeramani** [comment]
> I think it's ok as is, but does the current `iris.tfrecords` file have the same number of samples as e.g. the `iris.csv` file? I'd be surprised if so, I'd assume that the binary format would be smaller than the plain-text format.

Yeah, `iris.tfrecords` is created from `iris.csv`. Both contain 150 samples.

**Comment by clarkzinzow** [comment]
Weird 🤔 Ok I think keeping it as-is sounds good! 22 KB isn't so bad.

**Pull request merged**
