### PR TITLE
[core][state] Case insensitive match for string value for state API filter. 

### LINKED ISSUE #34554: [core][ci] stress_test_state_api_scale.aws fails
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_6lg8cyf4uh3ki775b6rpc7uync

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
Ran into an unexpected failure on https://github.com/ray-project/ray/issues/34554, where the query changes as we changes one of the value from (`Worker` to `WORKER`)

I think state API filtering could be less strict about case sensitivity, and I feel loosing it altogether would be ok and more usable.

I can hardly think of a usecase where case sensitivity on some fields would be useful. Of course, we could add a flag to the API to toggle this behaviour.   

## Related issue number
Closes https://github.com/ray-project/ray/issues/34554

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
can you update the docstring it is case insensitive? (the CLI docstring)

**Comment by rickyyx** [comment]
TODO

**Comment by rickyyx** [comment]
Oops this slipped from the GA - @rkooo567 but I feel we could still get this in? Maybe add a change log in the docstring to document this like python does for each function.

**Comment by rkooo567** [comment]
yeah I think this makes more sense!

**Comment by rkooo567** [comment]
merge conflict?

**Comment by rickyyx** [comment]
A usability improvement for state API, would be great to get this in. cc @zhe-thoughts

**Comment by zhe-thoughts** [comment]
@rickyyx @rkooo567 Please get this merged into master first (master is unfrozen for now). Thanks

**Comment by rickyyx** [comment]
Test failures unrelated.

**Pull request merged**
