### PR TITLE
[tune] Remove extra check

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
Removes an extra check after all experiments have finished. Allows user to go through all results even if some trials errorred out.

@vlad17

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
This affects some tests right?

**Comment by ericl** [comment]
(I think this is fine but we need to go through the tests and check for success explicitly)

**Comment by ericl** [comment]
Actually a cleaner option would be to provide a function to retrieve results from the last experiment. Or, wrap exceptions and include a handle to the trial tunner in the error. That way we keep error semantics the same.

**Comment by richardliaw** [comment]
hm like `trials = tune.get_last_experiment()`?

cc: @vlad17, does that reasonable?

**Comment by vlad17** [comment]
what was wrong with just returning the list of trials as before? The trials have a state like ERRORED right? I was gonna add user-level logic to record the errored ones

**Comment by ericl** [comment]
The problem is that you can silently fail without throwing an exception.
Most users don't care about inspecting trial state, they just want their
script to throw an error when there is an error.

**Comment by vlad17** [comment]
In that case it sounds like TuneError should just give all failed trials.

**Comment by ericl** [comment]
Yeah, I would do that.

**Comment by richardliaw** [comment]
jenkins retest this please

**Comment by richardliaw** [comment]
jenkins retest this please

**Review by ericl — APPROVED** [review]

**Pull request merged**
