### PR TITLE
[Serve] [Docs] Revise "Serving Ray AIR Checkpoints" Header

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
Signed-off-by: Shreyas Krishnaswamy <shrekris@anyscale.com>

## Why are these changes needed?

Serve's documentation includes a page about "Serving Ray AIR `Checkpoint`s". However, since the header leaves "s" outside the code formatting, the index on the left has a long gap that makes it hard to read the title:

**The documentation**:

Screen Shot 2022-08-12 at 10 06 30 AM

**The index**:

Screen Shot 2022-08-12 at 10 06 43 AM

This change drops the code formatting, so the index is uniform.

Link to updated documentation: https://ray--27824.org.readthedocs.build/en/27824/serve/ray-air-serve-guide.html

## Related issue number

N/A

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - This changes only the documentation header, so no tests are needed.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
Let's drop the code formatting as well.

**Comment by ericl** [comment]
Yeah, we shouldn't code format in headers.

**Comment by shrekris-anyscale** [comment]
> Let's drop the code formatting as well.

Sounds good– I dropped the code formatting.

**Comment by simon-mo** [comment]
@ericl can you approve?

**Review by ericl — APPROVED** [review]

**Pull request merged**
