### PR TITLE
Redo agent-pid -> agent-id changes

### PR DESCRIPTION
**Pull request by mattip**
## Why are these changes needed?
Redo the agent-id changes from #24968. The original PR is in the first commit, the second commit fixes a fatal flaw when using `RAY_BACKEND_LOG_LEVEL=debug`, which caused the "Ray C++, Java" tests to fail on macOS.

## Related issue number

I checked that this works with `RAY_BACKEND_LOG_LEVEL=debug` on linux and macOS.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mattip** [comment]
The `book-lint` and `potable-water-dataset-tests-python3-dot-7` CI runs seems to be consistently failing in the last few buildkite runs.

**Comment by mattip** [comment]
The mac-apple-medium-a-j failure is similar to others like [this one for PR 25742](https://buildkite.com/ray-project/ray-builders-branch/builds/8190#01816a1b-d6c4-45fb-9746-c3cb14095d43)

The mac-apple-medium-k-z failure is similar to others like [this one for PR 25785](https://buildkite.com/ray-project/ray-builders-branch/builds/8189#01816a1a-3783-4f4e-b384-bc9a9f893772/876-1878)

The mac-apple-ray-c-plus-plus-java-and-libraries failure is similar to others like [this one for PR 25742](https://buildkite.com/ray-project/ray-builders-branch/builds/8190#01816a1b-d6af-46f4-932c-ab0534420886)

The potable-water-dataset-tests-python-3-dot-7 failure is very common.

**Comment by mattip** [comment]
@rkooo567 I think this is ready for a review.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
it is this https://github.com/ray-project/ray/pull/25669 + fix for test failures right?

**Comment by mattip** [comment]
> it is this #25669 + fix for test failures right?

@rkooo567 yes. The problem with #25669 was that I redid the debug printing to include the additional arguments. Then the arguments are again fed to the actual process startup call. The line `argv.push_back(NULL);` was mistakenly moved to before the debug print, which caused the printing to crash. The line is required for the process startup call.

**Comment by mattip** [comment]
@rkooo567 could you take a look at the test failures and confirm they are not related to crashing the raylet executable or the dashboard agent (they share fate, but the timeout to kill the raylet executable only kicks in after 30 seconds)

**Comment by scv119** [comment]
@mattip unfortunately we need to merge the master as dashboard/agent.py has confliction.

**Comment by mattip** [comment]
There is an error in [mac-apple-ray-c-plus-plus-java-and-libraries](https://buildkite.com/ray-project/ray-builders-pr/builds/37845#0181ef14-97fe-41ac-99ee-ca0edf72001f/6-13115). On the one hand I don't see how that is connected, but on the other I don't see that test on https://flaky-tests.ray.io. Is there some serialize/deserialize of the agent data in Java that needs adjusting?
```
java -cp bazel-bin/java/all_tests_shaded.jar -Dray.raylet.startup-token=0 io.ray.docdemo.UsingActorsDemo
2022-07-12 04:19:44,040 INFO RunManager [main]: Ray runtime started @ 127.0.0.1.
Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized metadata [55]
    at io.ray.runtime.object.ObjectSerializer.deserialize(ObjectSerializer.java:119)
    at io.ray.runtime.object.ObjectStore.get(ObjectStore.java:140)
    at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:138)
    at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:119)
    at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:114)
    at io.ray.api.Ray.get(Ray.java:98)
    at io.ray.runtime.object.ObjectRefImpl.get(ObjectRefImpl.java:77)
    at io.ray.docdemo.UsingActorsDemo.main(UsingActorsDemo.java:83)
```

**Comment by mattip** [comment]
@scv119 I think this is ready for another round of review

**Comment by pcmoritz** [comment]
I merged master to check about the test failures

**Pull request merged**
