### PR TITLE
Inherit Function Docstrings and other metedata

### PR DESCRIPTION
**Pull request by simon-mo**
## What do these changes do?
When user use `@ray.remote` decorate, the docstring and signature of original function is loss. This tiny PR makes it possible for users to see the signature and docstring for a ray remote task.

### Before
image

### After
image

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

## Discussion
I can't apply the same mechanism to inherit docstrings or signature for actors. Because ActorHandle only has actor_id not the original class. I'm happy to discuss here how to retrieve the original class from ActorHandle.

### CODE REVIEW

**Comment by richardliaw** [comment]
Would it make sense to at least add a note in the docstring that it's a wrapped function rather than full transparency?

**Comment by pcmoritz** [comment]
I think it's ok to not say that it is a remote function, the `.remote` already makes that plenty clear.

**Comment by pcmoritz** [comment]
I made sure there is no performance regression (via https://stackoverflow.com/a/55102697/10891801 and also testing functools.wraps:

```
def f(x): 
    return None

from functools import wraps                                                                                                                                                  

@wraps(f) 
def g(x): 
    return None  
```

gives

```
In [13]: %timeit g(1)                                                                                                                                                                
77.5 ns ± 0.101 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [14]: %timeit g(1)                                                                                                                                                                
77.7 ns ± 0.224 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [15]: %timeit f(1)                                                                                                                                                                
78.7 ns ± 0.118 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [16]: %timeit f(1)                                                                                                                                                                
79.7 ns ± 0.732 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [17]: %timeit f(1)                                                                                                                                                                
79.1 ns ± 0.373 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [18]: %timeit f(1)                                                                                                                                                                
83 ns ± 8.06 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [19]: %timeit g(1)                                                                                                                                                                
78.4 ns ± 0.371 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

@simon-mo Make sure to create PRs from your own ray fork in the future instead of from ray-project, to avoid keeping the latter clean :)

**Review by pcmoritz — APPROVED** [review]

**Comment by simon-mo** [comment]
Oops my bad. I messed up my git remote. Won’t happen again.

**Comment by pcmoritz** [comment]
So one way to implement this for actors is to store the needed information in the `ActorHandle`. We need to make sure however that there is no user defined objects in there so the ActorHandle can't become too big.

**Pull request merged**
