### PR TITLE
[GCS]Fix GcsActorManagerTest multithreading bug

### PR DESCRIPTION
**Pull request by ffbin**
## Why are these changes needed?
BUG: https://travis-ci.com/github/ray-project/ray/jobs/398164320
GcsActorManagerTest has the problem of multiple threads reading and writing the same variable. For details, see the code note. The current modification scheme is relatively simple. If you have a better plan, let me know, thanks.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
What fields are accessed by multiple threads?

**Comment by ffbin** [comment]
> What fields are accessed by multiple threads?

actor_to_create_callbacks_ /registered_actors_/actor_to_register_callbacks_

**Comment by rkooo567** [comment]
Hmm I see.. I am a little concerned about the maintainability here. This happens because we have a separate io_service thread for GCS operation, and the callback is called in that thread right?

**Comment by rkooo567** [comment]
Is there any way that we can, for example, run the whole test suite inside the io_service? Like all the test suite is running inside io_serivce.post or something.

**Comment by ffbin** [comment]
> Hmm I see.. I am a little concerned about the maintainability here. This happens because we have a separate io_service thread for GCS operation, and the callback is called in that thread right?

Yeah, you are right.

**Comment by ffbin** [comment]
> Is there any way that we can, for example, run the whole test suite inside the io_service? Like all the test suite is running inside io_serivce.post or something.

Sometimes we need to wait for the asynchronous operation to complete in UT. In this case, can't we put the test suite into a thread?

**Pull request merged**
