### PR TITLE
[Train] Report only once in `SklearnTrainer`

### LINKED ISSUE #29226: [AIR] SklearnTrainer prints results 2x
### What happened + What you expected to happen

As a user, I was confused when I saw AIR Trainer printing the exact same results 2x. I thought there was some scaling setting I didn't set right, and it was running trainer.fit() 2x.

Steps to reproduce:
1. Create a trainer = SklearnTrainer()
2. trainer.fit()

What you expect:  See the output of the trainer 1x
What you get:  Output of the trainer 2x

```
Result for SklearnTrainer_a0c12_00000:
  cv:
    fit_time: [0.6021759510040283, 0.5733859539031982, 0.5524029731750488, 0.548241138458252,
      0.5298299789428711]
    fit_time_mean: 0.5612071990966797
    fit_time_std: 0.024726195698579492
    score_time: [0.014327049255371094, 0.012712240219116211, 0.011623859405517578, 0.012640953063964844,
      0.011872053146362305]
    score_time_mean: 0.012635231018066406
    score_time_std: 0.0009458884827991883
    test_score: [0.029715876743435565, 0.0287470459655339, 0.023290904242954658, 0.027951351793749524,
      0.028513788554153652]
    test_score_mean: 0.02764379345996546
    test_score_std: 0.002249881034758939
  date: 2022-10-08_14-39-13
  done: false
  experiment_id: 010811a62037471da69c49fb27cd1972
  fit_time: 0.5957210063934326
  hostname: Christys-MacBook-Pro.local
  iterations_since_restore: 1
  node_ip: 127.0.0.1
  pid: 40650
  should_checkpoint: true
  time_since_restore: 7.0960259437561035
  time_this_iter_s: 7.0960259437561035
  time_total_s: 7.0960259437561035
  timestamp: 1665265153
  timesteps_since_restore: 0
  training_iteration: 1
  trial_id: a0c12_00000
  valid:
    score_time: 0.04503917694091797
    test_score: 0.028788152902767483
  warmup_time: 0.0026459693908691406
  
Result for SklearnTrainer_a0c12_00000:
  cv:
    fit_time: [0.6021759510040283, 0.5733859539031982, 0.5524029731750488, 0.548241138458252,
      0.5298299789428711]
    fit_time_mean: 0.5612071990966797
    fit_time_std: 0.024726195698579492
    score_time: [0.014327049255371094, 0.012712240219116211, 0.011623859405517578, 0.012640953063964844,
      0.011872053146362305]
    score_time_mean: 0.012635231018066406
    score_time_std: 0.0009458884827991883
    test_score: [0.029715876743435565, 0.0287470459655339, 0.023290904242954658, 0.027951351793749524,
      0.028513788554153652]
    test_score_mean: 0.02764379345996546
    test_score_std: 0.002249881034758939
  date: 2022-10-08_14-39-13
  done: true
  experiment_id: 010811a62037471da69c49fb27cd1972
  experiment_tag: '0'
  fit_time: 0.5957210063934326
  hostname: Christys-MacBook-Pro.local
  iterations_since_restore: 1
  node_ip: 127.0.0.1
  pid: 40650
  should_checkpoint: true
  time_since_restore: 7.0960259437561035
  time_this_iter_s: 7.0960259437561035
  time_total_s: 7.0960259437561035
  timestamp: 1665265153
  timesteps_since_restore: 0
  training_iteration: 1
  trial_id: a0c12_00000
  valid:
    score_time: 0.04503917694091797
    test_score: 0.028788152902767483
  warmup_time: 0.0026459693908691406
```

### Versions / Dependencies

Ray 2.0.0
Python 3.8
Mac AppleM1 processor

### Reproduction script

import sklearn
from sklearn.linear_model import LinearRegression
from ray.train.sklearn import SklearnTrainer, SklearnPredictor
from ray.air.config import ScalingConfig
from ray.air.result import Result

trainer = SklearnTrainer(
    # SKlearn specific params
    estimator=LinearRegression(),
    # Scaling params
    scaling_config=ScalingConfig(trainer_resources=trainer_resources),
    label_column=target,
    cv=5,
    # Ray Datasets to use for train/valid
    datasets={"train": train_ds, "valid": valid_ds},
    # Ray Datasets preprocessor before training
    preprocessor=preprocessor,
)
result = trainer.fit()

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

Sets `"done": True` in the `SklearnTrainer` report so that it only print the results only once.

## Related issue number

Closes https://github.com/ray-project/ray/issues/29226

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
@Yard1 is this a bug in Tune? Report is only being called once right?

**Comment by Yard1** [comment]
@amogkam I wouldn't call it a bug, it's more a quirk of Tune - obviously, Tune doesn't know ahead of time if the report its getting will be the last one (unless "done" is explicitly passed in there) - in which case, the functional trainable does the following:
```
        If the RunnerThread finishes without reporting "done",
        Tune will automatically provide a magic keyword __duplicate__
        along with a result with "done=True". The TrialRunner will handle the
        result accordingly (see tune/trial_runner.py).
```

I suppose a more generic fix to this issue would be to not *print* the duplicate result, as duplicate printing is the main issue here.

**Comment by amogkam** [comment]
Yeah I guess my main question is does this duplicate printing apply to function trainables as well? Since I've never seen any of our function trainable examples report with `"done": True`.

If that's the case, then I think we should avoid the duplicate printing on the Tune side.

**Comment by Yard1** [comment]
Yeah the duplicate printing with functional trainable is the exact issue here. It's not unique to SklearnTrainer, but it's easy to miss it with trainers that report multiple times (because it's just one more result printout out of dozens or hundreds).

**Review by amogkam — APPROVED** [review]
Sounds good. Can we also fix the duplicate printing on the Tune side as well?

**Comment by Yard1** [comment]
@amogkam followup in tune https://github.com/ray-project/ray/pull/30597

**Pull request merged**
