### PR TITLE
only count physical cores

### PR DESCRIPTION
**Pull request by yaroslavvb**
use number of physical cores, using default logical cores (8) launches too many processes on my MBP

### CODE REVIEW

**Comment by ericl** [comment]
I've also seen better training performance when allocating by physical cores on a cluster. Users might be surprised by this however since the AWS documentation only exposes virtual cores. One workaround is to request multiple virtual cores per task/actor to prevent oversubscription.

**Comment by yaroslavvb** [comment]
@ericl it seems to work on AWS

```
# Trying on p3.16xlarge
psutil.cpu_count(logical=True)  # 64
psutil.cpu_count(logical=False) # 32

# Trying on c5.18xlarge
psutil.cpu_count(logical=True) # 72
psutil.cpu_count(logical=False) # 36
```

**Comment by ericl** [comment]
Yea, my point was more that most people would find it confusing to use physical cores as the default. You can however emulate the desired behavior by requesting `num_cpus: 2` in tasks. Otoh it's harder to do the reverse, since IIRC we don't currently support fractional cpus (e.g. `num_cpus: 0.5`).

**Comment by robertnishihara** [comment]
Rather than having users set `num_cpus=2` in the remote function decorator, I'd prefer than they just pass in a different `--num-cpus` into the `ray start` command or `ray.init` command.

Yeah, I'm not too sure what we should do about this PR. Using physical CPUs is probably better for numerical workloads. Are there situations where we'd rather use virtual CPUs?

**Comment by virtualluke** [comment]
Setting --num-cpus equal to physical cores under utilizes the hardware on many tasks that I make use of. It may be fine for a default though.

**Comment by robertnishihara** [comment]
Closing for now because I think the current default is less confusing.

**Pull request closed without merging**
