### PR TITLE
[autoscaler] Fix rsync file mounts

### LINKED ISSUE #10720: [autoscaler] Rsync breaks when `target` or `source` is None
### What is the problem?
When `rsync` is run with `source` and `target` set to `None` and `file_mounts` are included in the YAML, ray fails with
```
None type is not iterable
```

Introduced by #10633 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by ijrsvt**
## Related issue number

Closes #10720

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]
we should probably add a unit test for this eventually, but i'm fine with merging this as a hotfix first.

**Comment by ijrsvt** [comment]
@wuisawesome  I `100` agree, I think the first step is creating an `updater` test.

**Comment by wuisawesome** [comment]
yeah i mean we also do test some of the methods in `commands.py` in `test_autoscaler.py` (mostly thinking of `getOrCreateHeadNode` here)

**Comment by richardliaw** [comment]
are tests ok here?

**Comment by wuisawesome** [comment]
I believe so, but honestly I have no clue what the state of `test_cli` is at this point

**Review by richardliaw — APPROVED** [review]

**Pull request merged**
