### PR TITLE
Pin gym everywhere

### PR DESCRIPTION
**Pull request by avnishn**
This PR Pins gym in the app config.yaml's for rllib and tune so that release tests are no longer broken by the new gym version.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
https://buildkite.com/ray-project/release-tests-branch/builds/238#_

**Review by krfricke — APPROVED** [review]
LGTM

**Comment by zhe-thoughts** [comment]
Thanks @avnishn @jianoaix ! Should the label be `1.12.0rc1-pick`

**Comment by jianoaix** [comment]
> Thanks @avnishn @jianoaix ! Should the label be `1.12.0rc1-pick`?

Yep, just updated it.

**Comment by jianoaix** [comment]
Btw, you may want to add this cherry-pick to the release tracker: https://docs.google.com/spreadsheets/d/1fkOvrLGuaKLDuBwgsArwzjV0zuWpjS6DEs9HiKsWZ3Q/edit#gid=0

**Pull request merged**
