### PR TITLE
[Serve] Remove logging requirement for `long_running_serve_failure`

### LINKED ISSUE #32169: [Ray 2.3 release] long_running_serve_failure fails due to misconfigured log file
* BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1324#_

From @shrekris-anyscale:
> The test itself ran successfully, but it reported as an error because it logged its updates to the wrong file.

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
Signed-off-by: Shreyas Krishnaswamy <shrekris@anyscale.com>

## Why are these changes needed?

#32063 fixed some issues with the `long_running_serve_failure` release test and then marked it `stable`. The test ran successfully afterwards (see [test run](https://buildkite.com/ray-project/release-tests-branch/builds/1324)), but the CI failed to access logs from the cluster and reported the test as errored. The logs were inaccessible on the cluster due to an issue with the cluster setup.

Since this test can run without persisting logs, this change drops the logging requirement for this test.

## Related issue number

Closes #32169

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Release tests
     - This change modifies the `long_running_serve_failure` test.

### CODE REVIEW

**Review by cadedaniel — APPROVED** [review]
LGTM. Can you kick off another run before cherry picking into 2.3.0?

**Comment by shrekris-anyscale** [comment]
> LGTM. Can you kick off another run before cherry picking into 2.3.0?

Definitely!

**Comment by shrekris-anyscale** [comment]
Kicked off a test here: https://buildkite.com/ray-project/release-tests-branch/builds/1331#

**Review by architkulkarni — APPROVED** [review]

**Comment by shrekris-anyscale** [comment]
Kicked off another run here: https://buildkite.com/ray-project/release-tests-pr/builds/27361#0186146c-8c6d-4be3-adb7-bf9d7777912a

**Comment by shrekris-anyscale** [comment]
The [run was successful](https://buildkite.com/ray-project/release-tests-pr/builds/27361#01861471-7807-4fe0-abaa-d11227a54b11), and the CI has passed. @architkulkarni could you please do one more pass, and then merge the change?

**Review by rkooo567 — APPROVED** [review]

**Review by krfricke — APPROVED** [review]

**Comment by krfricke** [comment]
Once the infra issues are resolved we should add back threshold. Otherwise this will only fail if the script fully crashes.

**Comment by zhe-thoughts** [comment]
Thanks @shrekris-anyscale , @architkulkarni . Could you help merge today since it's a release blocker?

**Pull request merged**
