### PR TITLE
[c++] Refine Log Code

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
1. Change logging level from macros to enum class.
2. Remove the APIs that are not used.
3. Change the provider to `void *` to avoid header mismatching when others use ray lib without defining `RAY_USE_GLOG`.

### CODE REVIEW

**Review by raulchen — COMMENTED** [review]
Left a few small comments

**Comment by guoyuhong** [comment]
@raulchen As discussed with @eric-jj , we'd use a config file to configure the log. For one thing, it is hard to set the environment variable in a large cluster. For another, not only the logging level, we may also need to config the logging file place for backend.

**Comment by raulchen** [comment]
@guoyuhong does that mean that we'll abort this PR?

**Comment by raulchen** [comment]
Config is good in prod env. But env var might be a little more convenient in dev env. For example, when you change the config file during local testing, the git status gets polluted. And you'll need to remember to revert the change before committing other changes. It's not a big deal though. I'm okay with only supporting config.

**Comment by guoyuhong** [comment]
Since I removed the environment variable setting code, this PR will only refine the logging code. I will also enable `glog` in Arrow Plasma later, because `glog` helps the debugging a lot. 

I removed some useless code and change back the provider with `void *`. When I was changing the Plasma logging code, I found I had to define `ARROW_USE_GLOG` in ray project when the following code existing in the arrow header file. Otherwise, the lib and the header file mismatched. I think this is not reasonable. @pcmoritz 
```c++
#ifdef RAY_USE_GLOG
typedef google::LogMessage LoggingProvider;	
#else
typedef ray::CerrLog LoggingProvider;	
#endif
```

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by pcmoritz** [comment]
@guoyuhong Thanks, sorry for the late response. The changes look good to me, can you rebase the PR?

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
