### PR TITLE
[Data] Upgrade Arrow 12 to Arrow 14 in CI

### PR DESCRIPTION
**Pull request by bveeramani**
**Stacked on**
- [x] #41036 

## Why are these changes needed?

We're testing against Arrow 12, but the latest version of Arrow is 14. This PR updates our CI so that we test against Arrow 14 (the latest version).

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by aslonnie — COMMENTED** [review]
(seems not ready for review yet?)

**Comment by bveeramani** [comment]
@aslonnie ah, yeah. Wanted to confirm that CI passes first.

Will ping you when ready.

**Comment by bveeramani** [comment]
@aslonnie is there any way to confirm which Arrow version is being used in CI (or I guess which package versions are installed in general)? I'd expect it to use Arrow 14, but based on the errors I suspect it's using Arrow nightly.

**Comment by can-anyscale** [comment]
The test is broken with pyarrow 14 as well, as far as I know. The version is somewhere in the logs, might be hard to see.

I can generate a pip freeze for every job, that will make it easier to know going forward.

**Comment by bveeramani** [comment]
Okay, I couldn't reproduce the issue locally with Arrow 14. Also, when I reviewed the Arrow git log, it seems like the offending commit a week ago (which checks out since Arrow nightly only recently starting breaking. If it was an issue with Arrow 14, we would've seen the error earlier).

> I can generate a pip freeze for every job, that will make it easier to know going forward.

That'd be awesome!

**Comment by can-anyscale** [comment]
The data14build has pyarrow14 https://buildkite.com/ray-project/premerge/builds/11711#018bd020-3d0b-4314-a56e-462ecab194d0/168-1231

**Comment by can-anyscale** [comment]
the 14.0.1 was released just a week ago; maybe 14.0.0 works (2 weeks ago)

**Comment by bveeramani** [comment]
Ah, you're right! Turns out I had 14.0.0 installed locally.

**Review by aslonnie — APPROVED** [review]

**Review by can-anyscale — APPROVED** [review]

**Pull request merged**
