### PR TITLE
[Tests] Added an exempt list for test_output.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Test output fails on Linux very occasionally because of this log.

```
2020-08-14 19:29:35,471	WARNING services.py:1616 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 2071465984 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
```

It happens because the test uses `tmp` instead of `/dev/shm` because it has low shared memory.

Since this type of logs should still be shown to users (they are proper warning messages), we'd like to avoid removing those logs just to pass test_output. Instead, this PR creates an `exempt list`, which is a list of regex that is okay to be printed in the startup logs.

This solution is the most suitable for this issue because 

1. test_output still checks if it outputs unnecessary outputs.
2. If the output is non-deterministically happening but okay to be printed, we should just ignore them from tests. This fix will satisfy this requirement.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by ericl** [comment]
I don't think this is a good idea, the whole point of this test is to test we aren't showing warnings like this by default. Why not disable the warning or change the test env?

**Comment by rkooo567** [comment]
disable warning => This doesn't seem to be a good solution because I think this warning is valid (because the warning is performance related).

I think changing env vs this solution are good candidates to solve the issue. This solution still satisfies the original purpose of the test, which is `the whole point of this test is to test we aren't showing warnings like this by default` because 

- The given logs are valid warning messages but not shown by default. That's when we add them to the exempt list. 
- If we know there are outputs that are not valid warning, we can disable warning messages. 
- Tests will still fail on logs that are not in exempt list (which is carefully selected), meaning the test will serve the original purpose.

**Comment by rkooo567** [comment]
Btw, I’d love to make another PR that fixes test env too. Will do next Mon if you don’t approve by then. I think I can fix it by running this test first (than other tests)

**Comment by ericl** [comment]
I'm against merging this, so going to close.

**Pull request closed without merging**
