### PR TITLE
[ci][core][cluster] Capture outputs for ray up/down commands to understand why it failed

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

There's currently no easy way of figuring out why ray/up/ down fails in the cluster launcher test script. 

Capturing output of the subprocess to allow debugging. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]

**Comment by rickyyx** [comment]
So it seems if a command exits non zero on the remote node (e.g. when ray stop fails to gracefully shutdown things) - we will fail the command, leading to SIGSEGV as shown here 
```
py:360 -- \x1b[33mIf you experience issues with the cloud provider, try re-running the command with \x1b[1m--no-config-cache\x1b[22m\x1b[26m.\x1b[39m\n2023-09-13 11:28:42,463\tINFO commands.py:440 -- Destroying cluster. \x1b[4mConfirm [y/N]:\x1b[24m y \x1b[2m[automatic, due to --yes]\x1b[22m\n2023-09-13 11:28:43,316\tINFO command_runner.py:204 -- \x1b[37mFetched IP\x1b[39m: \x1b[1m35.227.137.116\x1b[22m\n2023-09-13 11:28:43,316\tVINFO command_runner.py:371 -- Running `\x1b[1mdocker exec -it  ray_container /bin/bash -c \'bash --login -c -i \'"\'"\'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)\'"\'"\'\' \x1b[22m\x1b[26m`\n1/1 stopped.\r1/4 stopped.\r2/4 stopped.\r3/4 stopped.\r4/4 stopped.\r\x1b[33mStopped only 5 out of 6 Ray processes within the grace period 16 seconds. Set `\x1b[1m-v\x1b[22m\x1b[33m` to see more details. Remaining processes [psutil.Process(pid=192, name=\'gcs_server\', status=\'terminated\', started=\'11:25:00\')] will be forcefully terminated.\x1b[39m\r\n\x1b[33mYou can also use `\x1b[1m--force\x1b[22m\x1b[33m` to forcefully terminate processes or set higher `--grace-period` to wait longer time for proper termination.\x1b[39m\r\n\x1b[0m'
Traceback (most recent call last):
  File "launch_and_verify_cluster.py", line 336, in <module>
    run_ray_commands(cluster_config, retries, no_config_cache, num_expected_nodes)
  File "launch_and_verify_cluster.py", line 251, in run_ray_commands
    cleanup_cluster(cluster_config)
  File "launch_and_verify_cluster.py", line 180, in cleanup_cluster
    raise e
  File "launch_and_verify_cluster.py", line 173, in cleanup_cluster
    subprocess.run(
  File "/home/ray/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ray', 'down', '-v', '-y', '/tmp/tmpao_rgdsy.yaml']' died with <Signals.SIGSEGV: 11>.
```


Retry usually works. Thoughts on how to handle this? @architkulkarni 

I think in the long run, we should not fail this bad if the `ray stop` exits non-zero on the remote cluster, but prints warnings or retries.

**Comment by architkulkarni** [comment]
I agree, retry sounds good in the short term.

If "ray stop" fails to shut down all nodes, I still think it makes more sense for `ray down` to return a nonzero error code and also print a warning (maybe suggesting to rerun `ray down`), rather than to just return zero and print the warning.  I feel like if `ray down` succeeds the user should have confidence that the cluster was shut down.

I'm not sure why SIGSEGV is being raised and I wonder if that's a bug.

**Comment by rickyyx** [comment]
> I agree, retry sounds good in the short term.
> 
> If "ray stop" fails to shut down all nodes, I still think it makes more sense for `ray down` to return a nonzero error code and also print a warning (maybe suggesting to rerun `ray down`), rather than to just return zero and print the warning. I feel like if `ray down` succeeds the user should have confidence that the cluster was shut down.
> 
> I'm not sure why SIGSEGV is being raised and I wonder if that's a bug.

I think we could follow up with retry + warning logging?

**Comment by rickyyx** [comment]
Merging to help understand transient failures like this: https://github.com/ray-project/ray/issues/39883

**Pull request merged**
