### PR TITLE
[Data] Remove `local_uri` in `reader_args` to avoid error when using pyarrow's `read_csv` method.

### LINKED ISSUE #35133: `read_csv` doesn't work with `local://` URI
Running the code `ds = ray.data.read_csv("dataset.csv")` on the head node successfully executes, but running `ds = ray.data.read_csv("local://dataset.csv")` produces an error:
```
File "pyarrow/_csv.pyx", line 900, in pyarrow._csv.open_csv
(_execute_read_task_split pid=362) TypeError: open_csv() got an unexpected keyword argument 'local_uri'
```
Apparently, `local_uri` gets forwarded to pyarrow's `open_csv`, which doesn't have such argument.

### PR DESCRIPTION
**Pull request by 94929**
## Why are these changes needed?

This PR fixes the issue https://github.com/ray-project/ray/issues/35133

Basically, when submitting a ray job to a ray cluster with local file: 'local://LOCAL_FILE_PATH', `reader_args` is passed to pyarrow.csv's `read_csv` method.
`reader_args` contain `local_uri` keyword, so that the `{'local_uri':True}` is passed onto pyarrow.csv's `read_csv` where the `read_csv` does not accept `local_uri` keyword.

Thus, the PR simply removes the `local_uri` in `reader_args` dict, if one exists.

## Related issue number

Closes #35133 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scottjlee — APPROVED** [review]
Thanks for the fix!

**Comment by c21** [comment]
do we know if this error happens to other data sources, as well, such as JSON, images, etc?

**Comment by 94929** [comment]
> do we know if this error happens to other data sources, as well, such as JSON, images, etc?

In addition to `csv_datasource.py`, I have checked the following data sources' read method:

1. binary_datasource.py
2. image_datasource.py
3. json_datasource.py

and the `local_uri` does not seem to exist in `reader_args` in these read methods.

For example, running `ds = ray.data.read_images('.')` produces the following output (i.e. the content of `reader_args` for `image_datasource.py`)

```
(_get_read_tasks pid=11806) reader_args: {'paths': '.', 'filesystem': None, 'meta_provider': <ray.data.datasource.image_datasource._ImageFileMetadataProvider object at 0x7f189bd56f80>, 'open_stream_args': None, 'partition_filter': FileExtensionFilter(extensions=['.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif'], allow_if_no_extensions=False), 'partitioning': None, 'ignore_missing_paths': False}
```

As seen, the `local_uri` does not exist.

**Comment by bveeramani** [comment]
Looks like this is an issue with other formats like JSON.

```
>>> import ray
>>> ray.data.read_json("local://temp.jsonl")
Traceback
    ...
TypeError: read_json() got an unexpected keyword argument 'local_uri'
```

We manually add `local_uri` to the read kwargs in `_get_reader`:
https://github.com/ray-project/ray/blob/704f3091eddd0e00660840d209605e7fb654b094/python/ray/data/read_api.py#L2311-L2312

And then we pass that parameter to PyArrow's `read_json`:

https://github.com/ray-project/ray/blob/704f3091eddd0e00660840d209605e7fb654b094/python/ray/data/datasource/json_datasource.py#L36

@c21 I really think we should refactor our code to avoid passing around parameters with `**reader_args` and `**write_args`. It introduces a lot of complexity and implicit behavior (like passing `local_uri` to PyArrow functions).

**Comment by 94929** [comment]
Hi, is there any decision made yet?

**Comment by scottjlee** [comment]
I think we should merge this PR as is, and in a future PR, we can generally remove usage of `**args` in these methods -- thoughts @c21 @bveeramani ?

**Comment by bveeramani** [comment]
> I think we should merge this PR as is, and in a future PR, we can generally remove usage of `**args` in these methods -- thoughts @c21 @bveeramani ?

Yeah, totally makes sense to me. That change seems pretty out of scope for this PR

**Comment by c21** [comment]
I took a close look, the only place we need `local_uri` is for Parquet reader - https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/parquet_datasource.py#L177 . So it should impact all other reader when doing local read. Agree to merge this PR first, and holistically fix it later.

**Comment by c21** [comment]
Thank you @94929 for the contribution!

**Pull request merged**
