### PR TITLE
[RLlib] Fix A3C release tests (removing tf2 due to some shape mismatch error for eager mode)

### PR DESCRIPTION
**Pull request by kouroshHakha**
Signed-off-by: Kourosh Hakhamaneshi <kourosh@anyscale.com>

## Why are these changes needed?

The failure on tf2 started after migrating to tf >= 2.9. The problem is in apply_gradients where some grad -> var mapping is messed up after the update. @ArturNiederfahrenhorst has also looked into this in the past and reached the same conclusion. A3C is not a super great algorithm anyway, so we can probably move on for now and only run release tests for the tf version. 

This is the stack trace of the failure:
```
Detected at node 'Adam/Adam/update_1/ResourceApplyAdam' defined at (most recent call last):
    File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/workers/default_worker.py", line 233, in <module>
      ray._private.worker.global_worker.main_loop()
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/_private/worker.py", line 763, in main_loop
      self.core_worker.run_task_loop()
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/_private/function_manager.py", line 674, in actor_method_executor
      return method(__ray_actor, *args, **kwargs)
    File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
      return method(self, *_args, **_kwargs)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/tune/trainable/trainable.py", line 364, in train
      result = self.step()
    File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
      return method(self, *_args, **_kwargs)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/algorithms/algorithm.py", line 730, in step
      results, train_iter_ctx = self._run_one_training_iteration()
    File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
      return method(self, *_args, **_kwargs)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/algorithms/algorithm.py", line 2606, in _run_one_training_iteration
      results = self.training_step()
    File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
      return method(self, *_args, **_kwargs)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/algorithms/a3c/a3c.py", line 239, in training_step
      local_worker.apply_gradients(result["grads"])
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/evaluation/rollout_worker.py", line 1185, in apply_gradients
      self.policy_map[pid].apply_gradients(g)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/policy/eager_tf_policy.py", line 133, in _func
      return obj(self_, *args, **kwargs)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/policy/eager_tf_policy.py", line 251, in apply_gradients
      return super(TracedEagerPolicy, self).apply_gradients(grads)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/policy/eager_tf_policy_v2.py", line 641, in apply_gradients
      self._apply_gradients_helper(list(zip(grads, vars)))
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/policy/eager_tf_policy.py", line 91, in _func
      return func(*eager_args, **eager_kwargs)
    File "/tmp/ray/session_2022-11-14_12-56-29_849739_151/runtime_resources/py_modules_files/_ray_pkg_c380fcecf09da8cb/ray/rllib/policy/eager_tf_policy_v2.py", line 942, in _apply_gradients_helper
      self._optimizer.apply_gradients(
    File "/home/ray/anaconda3/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 738, in apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/ray/anaconda3/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 797, in _distributed_apply
      update_op = distribution.extended.update(
    File "/home/ray/anaconda3/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 776, in apply_grad_to_update_var
      update_op = self._resource_apply_dense(grad, var, **apply_kwargs)
    File "/home/ray/anaconda3/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/adam.py", line 177, in _resource_apply_dense
      return tf.raw_ops.ResourceApplyAdam(
Node: 'Adam/Adam/update_1/ResourceApplyAdam'
var and m do not have the same shape[32] [3,3,1,32]
	 [[{{node Adam/Adam/update_1/ResourceApplyAdam}}]] [Op:__inference__apply_gradients_helper_3235]
```

The tf version started to regress after #30118 due to slower throughput. #30509 solves that issue and needs to get merged for this release test to pass. 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by gjoliver — APPROVED** [review]
:(

**Comment by sven1977** [comment]
The A3C release test still seems to fail :)

**Comment by sven1977** [comment]
The A3C release test still seems to fail :)

**Comment by kouroshHakha** [comment]
What the heck? It seems to be this infra issue :(

**Pull request merged**
