### PR TITLE
[Ray Dataset] fix the type infer of pd.dataframe (when dtype is `object`)

### PR DESCRIPTION
**Pull request by JiahaoYao**
re-try CI

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by JiahaoYao** [comment]
image
RL tests are failing, @Yard1

**Comment by JiahaoYao** [comment]
https://github.com/ray-project/ray/pull/25790

**Review by Yard1 — APPROVED** [review]

**Comment by JiahaoYao** [comment]
@scv119 seems break again?

**Comment by JiahaoYao** [comment]
but it passed ci
image
@scv119

**Comment by clarkzinzow** [comment]
@JiahaoYao When you reopened this PR, did you ensure that it's based off of latest master?

**Comment by clarkzinzow** [comment]
Hmm it looks like latest master was merged into this PR before merging it into master...

**Comment by clarkzinzow** [comment]
We should revert the master commit, re-open a PR, and try to reproduce the master CI failure before merging it again

**Comment by JiahaoYao** [comment]
yes

**Comment by JiahaoYao** [comment]
sorry, i am contacting someone to revert my pr

**Comment by clarkzinzow** [comment]
@JiahaoYao No worries, this failure was definitely unexpected since the PR build passed! It seemed as if we did everything right before unreverting. 😢

**Comment by JiahaoYao** [comment]
thanks, and let me do a quick check!

**Pull request merged**
