### PR TITLE
Accelerated DAG: Compile fixes for Windows in MutableObjectManager

### PR DESCRIPTION
**Pull request by jackhumphries**
## Why are these changes needed?

Compile issues for Windows appeared in https://github.com/ray-project/ray/pull/46259. This PR fixes those issues.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
remove ray-doc as the reviewer since it's not about doc, but feel free to re-add otherwise, thankks

**Review by ruisearch42 — APPROVED** [review]
Thanks for the fix!

**Comment by aslonnie** [comment]
I am waiting for the wheels to be built on premerge.

**Comment by jackhumphries** [comment]
> I am waiting for the wheels to be built on premerge.

@aslonnie They just finished building.

**Comment by aslonnie** [comment]
merging this as wheel is building.

**Comment by jackhumphries** [comment]
The buildkite failure seems to be unrelated.

**Pull request merged**
