### PR TITLE
PyTorch Lightning Updates

### LINKED ISSUE #17687: Issue on page /tune/tutorials/tune-pytorch-lightning.html
The documentation is not rendering properly due to mis-highlighted regions.

cc @amogkam 

Screen Shot 2021-08-09 at 4 46 01 PM

### PR DESCRIPTION
**Pull request by amogkam**
Various updates for PyTorch Lightning + Ray

- Fixes the PTL+Tune tutorial code highlighting. Closes https://github.com/ray-project/ray/issues/17687.
- Upgrades PTL version to 1.4
- Adds Ray Lightning as an additional library and tests in CI
- Removes legacy lightning accelerators
- Deprecates Ray SGD `LightningOperator`

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Can you fix the conflicts and lint? Happy to review afterwards

**Comment by amogkam** [comment]
Blocked on https://github.com/ray-project/ray_lightning/pull/78

**Comment by amogkam** [comment]
OK this is ready for review again

**Review by richardliaw — APPROVED** [review]
looks good, please merge when tests pass

**Pull request merged**
