### PR TITLE
[Core] [runtime env] Cache created runtime envs

### LINKED ISSUE #17343: [Core] [runtime env] Dashboard agent outlives Ray script and tries to install envs
### What is the problem?
The following script starts a lot of tasks inside runtime environments:

```python
import ray
import random
import os

ray.init(runtime_env={"pip": ["requests==2.26.0"]})
versions = ["2.25.0", "2.26.0"]
envs = [{
    "pip": [f"requests=={versions[i]}"]
} for i in range(len(versions) - 1)]
# If a task's env is {}, we should have requests==2.26.0 from the job's env.
envs.append({})  

NUM_ITERATIONS = 10# 10
NUM_CALLS_PER_ITERATION = 1000# 1000
NUM_ENVS_PER_ITERATION = 5# 5

@ray.remote
def check_version_task(expected_version: str):
    import requests
    assert requests.__version__ == expected_version


for i in range(NUM_ITERATIONS):
    results = []
    for j in range(NUM_ENVS_PER_ITERATION):
        (env, expected_version) = random.choice(list(zip(envs, versions)))
        remote_task = check_version_task.options(runtime_env=env)
        results.extend([
            remote_task.remote(expected_version)
            for _ in range(NUM_CALLS_PER_ITERATION)
        ])
    ray.get(results)
    print(f"Finished iteration {i+1}/{NUM_ITERATIONS}")
```

The script exits, but the dashboard agent stays alive and uses 20% CPU for at least a few minutes.  Inspecting the logs, we see that it's working through a backlog of thousands of runtime env creation requests.  Most of the time is spent in calling `conda env list` in `_get_or_create_conda_env()` to figure out if the conda environment already exists or needs to be installed.  This command is quite slow, taking a few seconds.  

To fix this we should keep track of successfully created runtime envs so that if an env is already created, we can return early before calling `conda env list`.    
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by architkulkarni**
Caches successfully created runtime envs in the agent.  This improves the previous approach of using "conda as a database" which called ` conda env list` and checked if the environment name existed or not to figure out if the environment had been created.  The problem is that `conda env list` is slow, taking a few seconds.

Since the caching is now being done at the level of the agent instead of inside the function `get_or_create_conda_env()`, we should at some point probably remove the `conda env list`-type caching inside `get_or_create_conda_env()` as it is redundant.
## Related issue number
Closes https://github.com/ray-project/ray/issues/17343

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Looks good. We should probably limit the size of the "cache" at some point in the future but not a blocker for now.

**Comment by edoakes** [comment]
@architkulkarni did you confirm that this fixes the issue in the release test you were running?

**Comment by architkulkarni** [comment]
Yes, it fixes it

**Review by simon-mo — APPROVED** [review]
can you push a commit or make a follow up PR to track in progress install as well? so that two tasks requiring the same runtime env at the same time won't call the runtime_env hook twice, you can do it with an asyncio.Lock or other synchronization primitives. (yes there are the filelock thing but that's still run through all the commands, ideally we should do the following)

```python
with async_lock:
    if runtime_env in self._created:
        return
```

(what do you think @edoakes?)

**Comment by architkulkarni** [comment]
Sure, I can do it in a follow-up PR.  I didn't quite understand what you said about why filelock is worse here, are you saying that it happens at too deep of a layer?  Like it currently happens inside get_or_create_conda_env(), but we actually want the lock to be at the top level (on top of all runtime env creation)?

**Comment by architkulkarni** [comment]
(Actually, let me do it in this PR)

**Comment by edoakes** [comment]
@simon-mo good point, right now it'll be handled by the file locking but this would be much simpler & faster. We can also completely remove the file locking if we do this.

**Comment by edoakes** [comment]
Merged because all tests were already passing and I wanted to rebase my other PR. @architkulkarni will address this in a follow-up.

**Pull request merged**
