### PR TITLE
[Test] Change the workload for agent_stress_test

### LINKED ISSUE #30494: [release][core] agent_stress_test is failing
https://buildkite.com/ray-project/release-tests-branch/builds/1202#01848cdc-3024-4057-8897-42b1709345c6

### PR DESCRIPTION
**Pull request by rkooo567**
Signed-off-by: SangBin Cho <rkooo567@gmail.com>

## Why are these changes needed?

It's currently broken because the rllib is broken in the master. The test relies on rllib workload that starts many workers (which was the original script that detected the regression). But we can emulate this using just many actors. So we will just move away from rllib. 

## Related issue number

Closes https://github.com/ray-project/ray/issues/30494

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
seems the release test failed https://buildkite.com/ray-project/release-tests-pr/builds/21990#01849a91-e83f-4940-8f12-301d8451969d

**Comment by rkooo567** [comment]
Looks like we cannot find the wheel. I think this sort of PR that doesn't change the code doesn't build the wheel from the CI, so we cannot run the release test. I will run this manually.

**Comment by rkooo567** [comment]
Ran this locally. This works well

**Comment by rkooo567** [comment]
Will cherry pick once it passes the nightly

**Pull request merged**
