### PR TITLE
[Usage Stats][Hotfix] Import usage reported from workers.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

We currently only record usage stats from drivers. This can lose some of information when libraries are imported from workers (e.g., doing some rllib import from trainable).

@jjyao just for the future reference. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@ericl I found although we import tune / rllib together, it takes some time for usage report to pick up rllib import. I will investigate this. (this could be why there was only tune usage from the nightly test)

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
> @ericl I found although we import tune / rllib together, it takes some time for usage report to pick up rllib import. I will investigate this. (this could be why there was only tune usage from the nightly test)

Hmm indeed this could be a big problem. Any reason why they'd conflict? They write to separate kv-keys right?

**Comment by rkooo567** [comment]
> Hmm indeed this could be a big problem. Any reason why they'd conflict? They write to separate kv-keys right?

Yes, they are written to separate kv-keys. It's more like Tune is reported first, and then rllib is reported later I think (so rllib usage is eventually reported). 

I believe this only happens from seq_no == 0 (and usually resolved in seq_no == 1), so it might be okay. But let me do a bit more investigation

**Comment by ericl** [comment]
That's very odd. Maybe it's since RLlib tries to record usage on import? Not sure if Tune does the same.

**Comment by rkooo567** [comment]
ETA merge: EoD in Japan time zone

**Comment by rkooo567** [comment]
Failed build should be unrelated

**Pull request merged**
