### PR TITLE
Revert "[Datasets] Revert "Enable streaming executor by default (#324…

### PR DESCRIPTION
**Pull request by jianoaix**
…93)" (#33485)"

This reverts commit 5c7995454c03ad9ac28d50e7d339f8e8ee84c236.

## Why are these changes needed?
The failure in rllib should have been fixed by https://github.com/ray-project/ray/pull/33562

Verified with `python -m pytest rllib/core/learner/torch/tests/test_torch_learner.py::TestLearner::test_end_to_end_update`.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by c21 — APPROVED** [review]

**Review by ericl — APPROVED** [review]
Can we also touch an RLlib file, and get checkoff from @avnishn before proceeding?

**Comment by jianoaix** [comment]
The CI with rllib tests: https://buildkite.com/ray-project/oss-ci-build-pr/builds/15806#_

**Comment by ericl** [comment]
Looks good. Are we concerned about that 1 doctest failure?

**Comment by jianoaix** [comment]
It's just a rounding error, just pushed a fix.

**Pull request merged**
