### PR TITLE
[Debugger] Add note about RAY_DEBUG=legacy in 'ray debug'

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

To make sure people who use `ray debug` are aware of the new debugger semantics and also suggest the VS Code debugger to them (see also the release notes https://github.com/ray-project/ray/releases/tag/ray-2.39.0)

cc @kouroshHakha 

This is how it looks like:

Screenshot 2024-12-17 at 2 11 15 PM

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kouroshHakha** [comment]
Maybe add a coloring scheme to it so that people read it, or make it shorter. I think people would end up ignoring long plain texts.

**Comment by pcmoritz** [comment]
Thanks, I added color now and also made it shorter :)

**Comment by kouroshHakha** [comment]
great.

**Review by brycehuang30 — APPROVED** [review]
lgtm!

**Pull request merged**
