### PR TITLE
Fix doc typos.

### PR DESCRIPTION
**Pull request by zhanluxianshen**
## Why are these changes needed?
Fix doc typos.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by anyscalesam — APPROVED** [review]

**Comment by zhanluxianshen** [comment]
@anyscalesam 
thanks for the merge.
The code is rebased frequency. would you help to merge again?

**Review by can-anyscale — APPROVED** [review]

**Comment by can-anyscale** [comment]
still need a stamp from many other code owners it seems

**Review by kevin85421 — APPROVED** [review]

**Comment by zhanluxianshen** [comment]
... disabled auto-merge

**Review by omatthew98 — APPROVED** [review]
Thanks for the fix!

**Comment by zhanluxianshen** [comment]
wouldn't you merge directly? The code is changed so frequent， once rebased, the auto-merge is canceld.

**Review by anyscalesam — APPROVED** [review]

**Pull request merged**
