### PR TITLE
[docs][tune] remove low value tune examples and references to them 

### PR DESCRIPTION
**Pull request by angelinalg**
These examples are out of date or provide low value. Pruning body of examples to improve discovery of high value examples. 
cc: @pcmoritz @richardliaw @matthewdeng 

- https://docs.ray.io/en/master/tune/examples/dragonfly_example.html
- https://docs.ray.io/en/master/tune/examples/flaml_example.html
- https://docs.ray.io/en/master/tune/examples/nevergrad_example.html
- https://docs.ray.io/en/master/tune/examples/sigopt_example.html
- https://docs.ray.io/en/master/tune/examples/tune-serve-integration-mnist.html

## Checks

- [sx] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
Nice, this is great 🥳

**Comment by pcmoritz** [comment]
@matthewdeng Can you make a follow up PR that removes the `dragonfly-opt` package from the dependencies (and any extra code / tests we have)?

**Comment by matthewdeng** [comment]
@pcmoritz sure thing, can I get your thoughts on what the deprecation policy should be for these types of removals?

**Comment by pcmoritz** [comment]
For things like dragonfly which are not even really maintained upstream any more https://github.com/dragonfly/dragonfly (last substantial development was in 2020), we can just remove it without any deprecation.

**Comment by pcmoritz** [comment]
In general, if there is very low usage, very low doc views and/or the project seems abandoned, let's just remove it without deprecation. If you are unsure just use your best judgement :)

**Pull request merged**
