### PR TITLE
[Docs] pin ray lightning version to fix lint error.

### PR DESCRIPTION
**Pull request by xwjiang2010**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]

**Review by amogkam — CHANGES_REQUESTED** [review]
Actually sorry @xwjiang2010 lint is still failing. Can you pin to this commit instead? https://github.com/ray-project/ray_lightning/commit/cacd374370e858adc0c00c76fe2e657e38790e0a

**Comment by simon-mo** [comment]
merged the other revert, please pull master!

**Comment by xwjiang2010** [comment]
> Actually sorry @xwjiang2010 lint is still failing. Can you pin to this commit instead? [ray-project/ray_lightning@cacd374](https://github.com/ray-project/ray_lightning/commit/cacd374370e858adc0c00c76fe2e657e38790e0a)

I thought the one I pinned to is from last September and should work?

**Comment by amogkam** [comment]
@xwjiang2010 ah no commits from September are too old and the APIs were different.

**Comment by amogkam** [comment]
Lint is passing and doc preview lgtm! Going to merge, thanks for quick fix @xwjiang2010!

**Review by amogkam — APPROVED** [review]

**Pull request merged**
