### PR TITLE
[Core] Properly call shutdown instead of deleting a reference

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Single node scalability consistently failed on shutdown because of this scenario.

- Python garbage collects instances on the thread the last strong reference goes out of scope.
- When the Python gc.collect() is invoked due to the memory pressure, it happens on the IO thread which handles the RPC requests to the core worker. Note that the core worker main thread (main thread is a driver or a task execution io service) is not the io thread.
- If the GC request is not finished when the main driver is completed, the CoreWorker instance is GC'ed on the IO thread which processes RPC requests. 
- As a result, the CoreWorker instance is GC'ed on the IO service thread. When the CoreWorker is GC'ed it calls CoreWorker.Shutdown which cleans up all metadata (including the io service thread itself).
- That says, this function calls io_thread_.join(). But as you can imagine, this happens on the io thread itself now, which is a deadlock! (thus the system raises an exception).

The PR fixes the issue by always call Shutdown call in the main thread (fortunately, we always register the shutdown logic in the main thread). Now instead of just GC the core worker instance, we explictly call shutdown. This should be okay because after the main thread shutdown, no other threads should be useable. So, it makes sense the main thread basically waits until all of threads are "cleanable state" (which is .join). 

I ran the single node 3 times and verified this fix will remove the system error problem

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Merge conflict

**Comment by ericl** [comment]
Windows failure:

//python/ray/tests:test_ray_shutdown                                    TIMEOUT in 3 out of 3 in 60.3s
  Stats over 3 runs: max = 60.3s, min = 60.2s, avg = 60.3s, dev = 0.1s
  C:/users/runneradmin/_bazel_runneradmin/vlncal46/execroot/com_github_ray_project_ray/bazel-out/x64_windows-opt/testlogs/python/ray/tests/test_ray_shutdown/test.log
  C:/users/runneradmin/_bazel_runneradmin/vlncal46/execroot/com_github_ray_project_ray/bazel-out/x64_windows-opt/testlogs/python/ray/tests/test_ray_shutdown/test_attempts/attempt_1.log
  C:/users/runneradmin/_bazel_runneradmin/vlncal46/execroot/com_github_ray_project_ray/bazel-out/x64_windows-opt/testlogs/python/ray/tests/test_ray_shutdown/test_attempts/attempt_2.log

**Comment by rkooo567** [comment]
Debugging strategy: 
- Revert the main logic and see if Windows still fail.
- If so, I will just skip on Windows.
- If not, I should start debugging Windows issue.

**Comment by ericl** [comment]
Now failing on Linux too:


//python/ray/tests:test_ray_shutdown                                     FAILED in 3 out of 3 in 52.0s
  | Stats over 3 runs: max = 52.0s, min = 42.4s, avg = 48.4s, dev = 4.3s
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_ray_shutdown/test.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_ray_shutdown/test_attempts/attempt_1.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_ray_shutdown/test_attempts/attempt_2.log

**Comment by rkooo567** [comment]
@ericl This is flaky even without the fix (the new tests). I think there could be many possibilities of the flakiness here (could be a test issue, or just our shutdown path is not robust enough).  Any opposition in merging the PR with the flaky build tag on the test? (and I can take a closer look at this next sprint )

**Comment by rkooo567** [comment]
It succeeds when I re-ran

**Comment by ericl** [comment]
I don't think we should be merging flaky tests. If we can't unflake them, how about not merging them, or adding internal retries to the test such that it never flakes?

**Comment by rkooo567** [comment]
Not merging them means we don't test this code path right? I think I prefer that (internal retry might not work depending on what the root cause is). Let me actually spend a couple hours to see if I can find the root cause of flakiness, and I will remove tests if I cannot figure that out.

**Comment by rkooo567** [comment]
I probably found a potential issue. Let' see if it will fix the flakiness.

**Comment by rkooo567** [comment]
Okay/ I believe this fixes the issue. Let me merge it.

**Pull request merged**
