### PR TITLE
fix setting log-level to debug.

### PR DESCRIPTION
**Pull request by elibol**
## What do these changes do?

Setting log-level to DEBUG triggers a slew of issues. These issues have been fixed by using the appropriate format for various logged variables.

## Related issue number

None

### CODE REVIEW

**Review by robertnishihara — APPROVED** [review]
Thanks for the fix! I just tried it out.

**Comment by robertnishihara** [comment]
I'll merge this once the tests have run.

**Comment by robertnishihara** [comment]
Just repushed in order to trigger travis again.

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
+1 LGTM, the test failures look unrelated

**Pull request merged**
