### PR TITLE
2.3.1 sympy and test fixes cherrypick

### PR DESCRIPTION
**Pull request by csivanich**
## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zcin** [comment]
Looks like the `sympy` and `ax` issues are resolved with this PR - @csivanich is this the PR that will be merged into the release branch?

**Comment by csivanich** [comment]
@zcin yes, this is the release branch cherry-pick PR
https://github.com/ray-project/ray/pull/33350 is the PR for master

**Comment by zcin** [comment]
@csivanich do you want to try pulling/rebasing? Chen's fix has been merged [here](https://github.com/ray-project/ray/pull/33412)

**Comment by csivanich** [comment]
@zcin merged in HEAD of the branch, everything is green now except expected failures for `Lint` and `Minimal Install Python 3.11`

**Review by zcin — APPROVED** [review]

**Pull request merged**
