### PR TITLE
Revert "[GCS] GCS Based Actor Scheduler (#16580)"

### PR DESCRIPTION
**Pull request by ericl**
This reverts commit a9b45455024d8d72e2e51aa0c090048a056698e4.

## Why are these changes needed?

cc @Chong-Li reverted since a merge conflict caused test_advanced to fail on master.

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by ericl** [comment]
Needs owners approvals (merge at will on approval)

**Comment by ericl** [comment]
Oh actually, the conflict seems to be resolved with https://github.com/ray-project/ray/commit/a9073d16f4060a20943f4ef0ca06bcd1ba4c69bd

**Comment by ericl** [comment]
Re-opening this to see if it fixes the Windows build.

**Review by wuisawesome — APPROVED** [review]

**Comment by ericl** [comment]
Merging to fix test_advanced

**Comment by Chong-Li** [comment]
> Merging to fix test_advanced

Hi @ericl, the PR of GCS actor scheduling got merged and reverted several times. What's the status right now? Is there anything I need to do?

**Comment by ericl** [comment]
It's failing the Windows build of test_advanced. Fine to remerge once it
passes all tests.

I think we just need to be more careful about ensuring the PR is actually
passing all tests reliably here.

**Pull request merged**
