### PR TITLE
[docs] crisp chat for kapa.ai integration

### PR DESCRIPTION
**Pull request by maxpumperla**
Preview: https://anyscale-ray--34782.com.readthedocs.build/en/34782/

tomorrow, kapa.ai will finish our custom plugin for this chat interface, then we can use chatgpt for tech support on docs, and optionally loop in human operators.

### CODE REVIEW

**Comment by pcmoritz** [comment]
This is great, thanks for adding this! Maybe it is time now to get rid of the upvote / downvote button since it overlaps with this widget? cc @angelinalg

**Comment by maxpumperla** [comment]
I think we could move one of them, if the upvote system is still useful

**Comment by angelinalg** [comment]
Cool, @maxpumperla! I talked to @simran-2797 about the layout and she has an idea to make some design improvements. She's going to try something out.

**Comment by maxpumperla** [comment]
@angelinalg I already made some space, but happy to hear Simran's input here

Screenshot 2023-04-27 at 19 16 45

**Comment by scottsun94** [comment]
Pasted the screenshots on my phone here. Can we avoid the cutoff of the rate-the-doc component and maybe fix the wonky UI when it's collapsed? cc: @simran-2797 

IMG_3898
IMG_3899


Here are some instructions about how to update the rate-the-doc component:
The html is here https://github.com/ray-project/rate-the-docs/blob/main/src/widget.html 
The CSS is here https://github.com/ray-project/rate-the-docs/blob/main/src/widget.css
Some instructions for how to update it: https://github.com/ray-project/ray/pull/26330

**Review by angelinalg — APPROVED** [review]
LGTM

**Pull request merged**
