### PR TITLE
Update arrow with better dataframe serialization and get rid of custo…

### LINKED ISSUE #1305: Worker dies when passed pandas DataFrame.
### System information
- **Ray version**: 0.3.0
- **Python version**: 3.6.0
- **Exact command to reproduce**:

```python
import pandas as pd
import ray

pd.__version__  # '0.19.2'

ray.init()

df = pd.DataFrame(data={'col1': [1, 2, 3, 4], 'col2': [3, 4, 5, 6]})

@ray.remote
def f(x):
    pass

f.remote(df)
```

The last line causes the following error to be printed in the background.

```
A worker died or was killed while executing a task.
```

cc @devin-petersohn

### PR DESCRIPTION
**Pull request by robertnishihara**
This should fix #1305 (actually the bug wasn't really visible before this PR because we were falling back to pickle (because we weren't registering any custom DataFrame serializers)).

cc @devin-petersohn

### CODE REVIEW

**Review by devin-petersohn — APPROVED** [review]
Looks great! Happy we can get this bug fixed.

**Comment by devin-petersohn** [comment]
@robertnishihara it looks like these errors are happening in the arrow commit being checked out. I tried to build locally and got the same failures as travis.

**Comment by robertnishihara** [comment]
You're right, looks like there were some plasma client API changes in Arrow, so I'll need to fix those.

**Comment by robertnishihara** [comment]
This PR may have introduced a performance regression on the benchmark

```python
%time l = ray.get([f.remote() for _ in range(10000)])
```

for trivial functions `f`.

**Pull request merged**
