### PR TITLE
[CI] [GCP Cluster launcher] Use single SSH key for all tests

### LINKED ISSUE #40635: [CI] [Cluster launcher] GCP cluster launcher tests should all use the same SSH key
### Description

Previously each GCP cluster launcher test would generate a new SSH key.  This caused us to hit the SSH key limit per project, causing the issue https://github.com/ray-project/ray/issues/40241.  

We should use a single SSH key for the GCP cluster launcher tests, similar to how we do it for the EC2 cluster launcher tests.

### Use case

_No response_

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Previously a new key would be generated by the cluster launcher for each test run.  This caused us to hit the limit for the number of SSH keys per project.  This PR uses a single SSH key for all tests by storing a key in a GCS bucket and downloading it to each test cluster at startup.

## Related issue number
Closes #40635 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Screenshot 2023-10-31 at 9 58 04 AM
GCP cluster launcher tests passed.  (gcp-cluster-launcher-release-image is expected to fail on PR builds.)

**Comment by architkulkarni** [comment]
@rickyyx Do you mind reviewing this as codeowner?

**Review by rickyyx — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/gifs/share-very-discover-10uEX5kfeodYgo">GIPHY</a></div>

**Comment by rickyyx** [comment]
hmmm, we should add you or other folks as code owners for this.

**Comment by architkulkarni** [comment]
@rickyyx yeah good point, I'm codeowner but I can't approve my own PR... We'll figure out a better solution (maybe @hongchaodeng we can add you as another codeowner for OSS cluster launcher?)

**Comment by architkulkarni** [comment]
Failed tests unrelated, this PR only modifies the GCP cluster launcher tests

**Pull request merged**
