### PR TITLE
[train] rename _base_dataset to _base_datastream

### LINKED ISSUE #34418: [CI] `linux://python/ray/train:test_huggingface_trainer` is failing/flaky on master.
- 43920e21853f5f5099754a3027dfce1927cbb1cc FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3404#01878192-692f-4ce6-88bf-a14274049a5c)
- 43920e21853f5f5099754a3027dfce1927cbb1cc FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3404#0187818c-d856-405d-9cea-f3630acb892b)
- 0e0c15065507f01e8bfe78e49b0d0de063f81164 FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3403#01878165-8d12-48ad-8b02-32bbc2093714)
- 0e0c15065507f01e8bfe78e49b0d0de063f81164 FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3403#0187816a-fcf7-4214-822b-f134f498de26)
- ffeedbf63efea61f626b9e4f2895179534840025 FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3402#01878161-083b-41f5-baa3-facbd4122f4c)
- ffeedbf63efea61f626b9e4f2895179534840025 FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3402#01878166-7a8f-403d-982d-e4ece2adadba)
- d86624502b4e1f0acb4d68957fca1188947d971f FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3401#0187813e-9980-4bcb-be3a-6a8763bd6368)
- d86624502b4e1f0acb4d68957fca1188947d971f FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3401#01878146-ef64-437e-865e-351e00fba845)
- 6d69d79cfef1741dc11b0d9662ed120a90dd99a4 FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3400#01878141-b411-417f-af6d-dc4e8a834eff)
- 6d69d79cfef1741dc11b0d9662ed120a90dd99a4 FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3400#01878139-6a75-42ab-8e46-ccb427110a88)
- 1a0989a1c09581a799be28bdd2a09470cd928b28 FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3371#01877b70-f999-45e8-bb1e-1bc2b4cedd2f)
- 45b9067b5f0c463a62eb5ac50dadcbb13399a982 FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3271#01876d3c-78a4-4f86-916f-8d9cb1b3f75c)
- 45b9067b5f0c463a62eb5ac50dadcbb13399a982 FAILED [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3271#01876d43-2364-45fd-9847-31d8c01cbbd3)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/train:test_huggingface_trainer-END
....

### PR DESCRIPTION
**Pull request by matthewdeng**
## Why are these changes needed?

Dataset was renamed to Datastream in https://github.com/ray-project/ray/pull/34340. This looks to have been missed.

## Related issue number

Closes https://github.com/ray-project/ray/issues/34418.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ollie-iterators** [comment]
It looks like there may be a lint issue to fix before merging this PR

**Comment by ollie-iterators** [comment]
It looks like there is a lint issue to be fixed before merging this PR, since the merge issue was problably caused by the same PR that created the other issues.

**Comment by matthewdeng** [comment]
Fixes `test_huggingface`. Other failures due to cached protobuf build.

image

**Comment by xwjiang2010** [comment]
Thanks Matt!

**Pull request merged**
