### PR TITLE
[Data] Fix `read_tfrecords_benchmark`

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

`read_tfrecord_benchmark` generates synthetic datasets that are much smaller than expected. This PR fixes the implementation so that the synthetic dataset respects the specified `num_rows`.

Strict mode changed the type of `ray.data.range` batches from `list` to `dict`. Previously, this for loop generated one row per input row. Since `batch` is now a `dict` with one key, it instead generates one row per input batch. 
https://github.com/ray-project/ray/blob/a21713ef373d00aab6647e0902f264f72c73dc52/release/nightly_tests/dataset/read_tfrecords_benchmark.py#L50-L63

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scottjlee — APPROVED** [review]
Thanks for updating this!

**Comment by amogkam** [comment]
can you run the release test and make sure it passes?

**Comment by scottjlee** [comment]
Looks like it's good? https://buildkite.com/ray-project/release-tests-pr/builds/37714#0187fe33-a253-457b-b806-f004859e0ada

**Comment by bveeramani** [comment]
> Looks like it's good? https://buildkite.com/ray-project/release-tests-pr/builds/37714#0187fe33-a253-457b-b806-f004859e0ada
> 
> Wait, it's still finishing in less than a second. so maybe not

Lemme take a look. That weird

**Pull request merged**
