### PR TITLE
[CI][Bisect] Fix bisect due to wrong order of commit list

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?

Currently we are using `git rev-list` to get the commit lists. This command return the commits in the reverse order that we want, so reverse it before passing it to bisect.

## Related issue number

#34535

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests

### CODE REVIEW

**Review by xwjiang2010 — APPROVED** [review]
Thanks!!

**Comment by can-anyscale** [comment]
I'm kicking off a bisect to check this change, let see how it goes: https://buildkite.com/ray-project/release-tests-bisect/builds/52

**Comment by can-anyscale** [comment]
Actually this only works if the PR is in the master branch. Let's merge this then. 

I don't have the merge permission, is this something you can help @xwjiang2010. Thankkks

**Comment by xwjiang2010** [comment]
I can't either :) @krfricke probably has the access.

**Review by krfricke — APPROVED** [review]

**Comment by krfricke** [comment]
Linter error is unfortunately related cc @can-anyscale 

```
def _get_commit_lists(passing_commit: str, failing_commit: str) -> List[str]:
--
  | -    commit_lists = subprocess.check_output(
  | -        f"git rev-list --ancestry-path {passing_commit}..{failing_commit}",
  | -        shell=True,
  | -    ).decode("utf-8").strip().split("\n")
  | +    commit_lists = (
  | +        subprocess.check_output(
  | +            f"git rev-list --ancestry-path {passing_commit}..{failing_commit}",
  | +            shell=True,
  | +        )
  | +        .decode("utf-8")
  | +        .strip()
  | +        .split("\n")
  | +    )
```

**Comment by can-anyscale** [comment]
Ah by bad, lint is fixed now

**Pull request merged**
