### PR TITLE
[hotfix] Disable dashboard agent windows

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This PR effectively disabled the dashboard agent for Windows. Note that we do this because there are many checks to ensure that the dashboard process is still running and its logs are being properly generated. 

## Related issue number

Temporary solution to #14026 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
@edoakes this is becaus #14043 fails a bunch of tests still

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
`test_dashboard` failure is kind of scary?

**Comment by wuisawesome** [comment]
rerunning it, but a mac only, port collision seemed like a flakey test issue

**Comment by fyrestone** [comment]
The dashboard agent process leak is due to these two PRs:
- https://github.com/ray-project/ray/pull/13700
- https://github.com/ray-project/ray/pull/12948

These two PRs disable the fate-sharing function of dashboard agent. The root cause is that the environment vars are not passed from raylet to agent correctly, but I don't have the Windows development environment to reproduce the problem.

**Pull request merged**
