### PR TITLE
[core] remove pushing RayTaskError to driver

### PR DESCRIPTION
**Pull request by oliverhu**
## Why are these changes needed?
Fix [Core] [Error Message] Possible unhandled error from worker #12018

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @richardliaw Should I tag the core-api-change tag here?

**Comment by richardliaw** [comment]
@rkooo567 I'm not a codeowner for this part of the code, can you tag whoever previously introduced RayTaskError pushing?

**Comment by rkooo567** [comment]
cc @edoakes Can you write any comment about this change? We are thinking to remove the task exception push to the driver because it is redundant (since ray.get already can get the exception).

**Comment by edoakes** [comment]
Sounds good to me, I find this a bit spammy. Would consider this an API change though so let's have @pcmoritz take a look.

**Comment by ericl** [comment]
I don't think we should merge this PR (-1 veto), since it will silently swallow errors. This was a huge pain point for early Ray users.

Are there alternative patches that we can do to make this less spammy in particular cases?

**Comment by oliverhu** [comment]
@ericl do you have an example that the errors would be silently swallowed with this change?

**Comment by ericl** [comment]
If you run a task and don't retrieve the result, the error is lost.

**Comment by oliverhu** [comment]
@ericl  why would a user care about the underlying Python exception if they don't retrieve the results? Note this change is only for exceptions, not worker crashes.

**Comment by ericl** [comment]
Because they are executing it for side-effect, aren't sure about how to use Ray, or have a bug in their program.

My question here is: how do we mitigate excess log spam without making Ray harder to use for these kind of users? Is it just a matter of suppressing in more causes (for example, an active ray.get or ray.wait as well?)

**Comment by oliverhu** [comment]
@ericl it would be useful to have a concrete use case. 

I'd argue the goal is to maximize the experience for the majority of users (who are suffering now), and mitigate the gap for the small portion that depends on the side-effect.

**Comment by ericl** [comment]
Any actor or task call can demonstrate. I believe this happens most often in Jupyter notebooks though.

Are there other solutions here? What if we only reported errors for object refs deleted without retrieval?

**Comment by oliverhu** [comment]
@ericl  I see.. thanks for catching it. I think you meant this should also throw error but this change silent it:
```
import os
print (os.getpid())
@ray.remote
def foo():
    print (f"remote: {os.getpid()}")
    raise ArithmeticError("oops")

time.sleep(1)
foo.remote()
time.sleep(2)
```

**Comment by oliverhu** [comment]
However, in python futures, that is the expected behavior?

```
import concurrent.futures
from collections.abc import Iterable

def run_heavy_function():
    # return [1, 2]
    raise Exception("test")

if __name__ == '__main__':
    # Execute asynchronously with multi processing
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
        # result = executor.map(run_heavy_function, numbers)
        result = executor.submit(run_heavy_function)
    # if isinstance(result, Iterable):
    #   print(list(result))
    # else:
    #   print(result.result())
```
output: empty

```
import concurrent.futures
from collections.abc import Iterable

def run_heavy_function():
    # return [1, 2]
    raise Exception("test")

if __name__ == '__main__':
    # Execute asynchronously with multi processing
    with concurrent.futures.ProcessPoolExecutor(max_workers=4) as executor:
        # result = executor.map(run_heavy_function, numbers)
        result = executor.submit(run_heavy_function)
    if isinstance(result, Iterable):
      print(list(result))
    else:
      print(result.result())
```
output:
```
> python test3.py
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/khu/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/khu/test3.py", line 6, in run_heavy_function
    raise Exception("test")
Exception: test
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test3.py", line 16, in <module>
    print(result.result())
  File "/Users/khu/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/khu/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
Exception: test
```

**Comment by oliverhu** [comment]
https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.map
```If a func call raises an exception, then that exception will be raised when its value is retrieved from the iterator.```

**Comment by ericl** [comment]
Right, it's definitely true multiprocessing/etc don't provide this feature, however it's a low bar. So thinking about possible solutions, two come to mind:
(1) Add a env var to suppress these (e.g., in the error we can say "set RAY_WARN_UNCAUGHT_ERRORS=0 to suppress these messages").
(2) Only report errors if the future was never passed to ray.get/wait. This would require some more code, basically in the core worker memory store we would want to surface exception results that were deleted from the memory store without ever being retrieve.

How about starting with (1) since that's a simple fix? We can then try for (2), which should be straightforward

**Comment by oliverhu** [comment]
I'm not convinced that Python multiprocessing is `low bar`, my hunch is we are over engineering here... any rationale we want to reinvent this behavior for ray remote function?

**Comment by ericl** [comment]
Well, it was added based on user feedback in the past, where users were
confused about the silent exception swallowing.

I do think in general we should try to provide better error messages than
other concurrency libraries, user friendliness is something distinguishing
ray.

**Comment by oliverhu** [comment]
I don't necessarily agree with you that all other concurrent libraries bear crappy APIs.. but I guess you have a point to make it better positioned for users. 

Regardless of which impl to go down the road, perhaps you could share a bit more insight what exact behavior users would appreciate? `Only report errors if the future was never passed to ray.get/wait. ` is this enough or there are other cases?

**Comment by ericl** [comment]
> Regardless of which impl to go down the road, perhaps you could share a bit more insight what exact behavior users would appreciate? Only report errors if the future was never passed to ray.get/wait. is this enough or there are other cases?

I think this is sufficient (surfacing unhandled exceptions in remote functions). The issue happens when users aren't handling the result and think the function has succeeded. Normally when you call a function in the main thread, the exception will be printed if unhandled by some default exception handler.

**Comment by oliverhu** [comment]
Ok, not sure how realistic it is if we want to implement this feature without compiler support. `.get ` can be called anywhere.

**Comment by ericl** [comment]
That's true, though I believe you just need to add a deletion hook in the
core worker memory store for the common case. If the reference is passed
outside the worker, we can probably ignore that case (advanced user).

Eric

**Comment by oliverhu** [comment]
👌 will check out that path

**Comment by oliverhu** [comment]
close with https://github.com/ray-project/ray/pull/14049

**Pull request closed without merging**
