### PR TITLE
[Link Check] Fix the broken link check from the AIR doc

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

The original link doesn't exist. https://docs.ray.io/en/master/_images/air-ecosystem.svg

I fixed it by linking the raw github file link. This should have the exactly same flow as before. I tried finding a link to this image file, but I couldn't. I also couldn't find an easy way to add only a link (without embedding an image). Please lmk if you prefer other option

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Verified this fixes the link check.

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Though seems like this image doesn't render at all on browser?

**Comment by richardliaw** [comment]
Screen Shot 2022-08-08 at 1 08 28 AM

**Comment by richardliaw** [comment]
Updated

**Pull request merged**
