### PR TITLE
[air] Deprecate some fields/classes that are supposed to be gone in 2.6 (#38794)

### PR DESCRIPTION
**Pull request by xwjiang2010**
Cherry-picked from 
Deprecate some fields/classes that are supposed to be gone in 2.6 (#38794) and #39067

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]
This is necessary API cleanup

**Comment by GeneDer** [comment]
@xwjiang2010 Premerge is failing due to a linting issue https://buildkite.com/ray-project/premerge/builds/3943#018a4241-4bd4-4f2f-947a-02fd1ee16a80/187-427 Can you fix it so we can get this in?

**Comment by xwjiang2010** [comment]
Sounds good. will follow up.

**Review by zhe-thoughts — APPROVED** [review]
Necessary clean up

**Pull request merged**
