### PR TITLE
[direct call] Implement generic Get(), and integrate memory store provider

### PR DESCRIPTION
**Pull request by zhijunfu**
## What do these changes do?

This change generalizes support for `Get` with object IDs from different store providers, and to do this the `ObjectInterface` needs to talk with task transport for return objects in order to know if the tasks that produces these objects are finished or not, so that it can know if it should continue to wait.  

To support that, `ObjectInterface` and `Task Transport` would need to call each other, to resolve this inter-dependency and also make the architecture cleaner, this change also does a refactor to add a `StoreProviderLayer` and a `TaskTransportLayer` which hides all the details for underlying `store providers` and `task transports` respectively.

This change doesn't support generalized `Wait`, which currently only support plasma objects. I was about to implement it, but realized it would make the code a bit too complex, and also it's not as widely used as `Get`, so it is left as a TODO later when necessary.

## Related issue number

#5029 

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Review by pcmoritz — CHANGES_REQUESTED** [review]
This code structure is getting too complicated. Before more development happens on the direct actor call code path, we need to validate the design end-to-end (and also simplify it). Can you implement the direct actor calls in python and make sure the actor tests pass?

**Review by edoakes — CHANGES_REQUESTED** [review]
I didn't get through all of the details, but I'm concerned that especially with this change the core worker interfaces are getting too complex with so many layers of abstraction and indirection. The code is getting harder to understand and it's also getting harder to reason about the behavior (e.g., wait() not being fully implemented).

I think the code has diverged enough at this point from the design doc that it would be best to update it with all of the planned interfaces to ensure that everyone is on the same page with where this is going.

**Comment by zhijunfu** [comment]
Thanks for the comments, I understand your concern. The change basically deals with the following: 
1. Users can specify a list of objects from multiple store providers when using `Get`, `Wait`, and `Delete` for `StoreInterface`;
2. To take care of case that objects get evicted from store. This accounts for most of the complexities in this PR, including the introduction of `StoreProviderLayer` and `TaskTransportLayer`, and some other changes. 

It's possible that item 2 can be solved by using a `RayObject` in python/java, which includes the 
object ID and object data itself, so that the objects won't be evicted per our earlier discussions. In that case most of the complexities in this PR can be eliminated.  

Thus I'm thinking probably I can implement item 1 as a separate PR, which should be mostly straightforward. Item 2 can be postponed and we can have more discussions, and possibly this can be addressed by python/java worker as mentioned above.

For end to end test, once java worker is fully migrated to core worker (should be pretty close), then we can test direct call with java, by leveraging existing tests.

Would this make sense to you?

> This code structure is getting too complicated. Before more development happens on the direct actor call code path, we need to validate the design end-to-end (and also simplify it). Can you implement the direct actor calls in python and make sure the actor tests pass?

**Comment by zhijunfu** [comment]
Agreed on the complexities. I think architecture wise it's still clear, and the added `StoreProviderLayer` and `TaskTransportLayer` are just thin wrappers of the concrete store providers and transports respectively, but I do agree that implementation wise it adds non-trivial complexities. 

For example, `Wait` is not fully supported because I found it's a bit too complex to support waiting a part of a list of objects with potentially duplicates, and from different store providers, and to handle evicted objects the code needs to talk to the different transports in each iteration of the while loop...

As I mentioned in the reply above, most of the complexities is to handle evicted objects, for this part we can have more discussions, and it's possible that it can be handled in python/java.

For this PR, I plan to move the part to support multiple store providers for `Wait` and `Delete` to a separate one, which should be mostly straightforward and can be merged separately.

Kindly let me know what you think. thanks.

> I didn't get through all of the details, but I'm concerned that especially with this change the core worker interfaces are getting too complex with so many layers of abstraction and indirection. The code is getting harder to understand and it's also getting harder to reason about the behavior (e.g., wait() not being fully implemented).
> 
> I think the code has diverged enough at this point from the design doc that it would be best to update it with all of the planned interfaces to ensure that everyone is on the same page with where this is going.

**Comment by edoakes** [comment]
Thanks @zhijunfu, splitting these into separate changes definitely makes sense. I will take a look at the other PR, but at first glance it looks much clearer.

For handling evicted objects, it seems like the architecture/design is not completely clear. In this case, it would be best if you could write up a short design document that outlines the problem and potential solutions and we can decide on that before moving ahead on the implementation.

cc @pcmoritz

**Pull request closed without merging**
