### PR TITLE
[tune] remove legacy search algorithms

### PR DESCRIPTION
**Pull request by matthewdeng**
## Why are these changes needed?

This PR removes legacy search algorithms that are not seeing much usage. This list consists of:
- Dragonfly
- (FLAML) BlendSearch, CFO 
- Nevergrad
- SigOpt

## Related issue number

Follow-up to #41348.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
Very nice! Do we also need to regenerate `requirements_compiled.txt`?

**Comment by matthewdeng** [comment]
@pcmoritz yep waiting for it to generate [here](https://buildkite.com/ray-project/premerge/builds/12798#018c129e-7542-407e-8635-6f93475af7ef) and will update the PR with the update file!

**Comment by anhnami** [comment]
Nevergrad's OnePlusOne and the recent LogNormalOnePlusOne  have been my favorite. They yielded better performance than Optuna for me. Kind of sad because it got removed for no valid reason.

**Comment by anhnami** [comment]
Just want to add, this does not allow me to load my old tune results. 

`[327](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:327) fs, fs_path = get_fs_and_path(path_or_uri, storage_filesystem)
    [328](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:328) with fs.open_input_file(os.path.join(fs_path, _TUNER_PKL)) as f:
--> [329](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:329)     tuner_state = pickle.loads(f.readall())
    [331](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:331) old_trainable_name, flattened_param_space_keys = self._load_tuner_state(
    [332](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:332)     tuner_state
    [333](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:333) )
    [335](https://vscode-remote+ssh-002dremote-002be13k-002eeu-002eorg-002e47.vscode-resource.vscode-cdn.net/home/anhnht/csaiomodel/~/miniforge3/envs/dev/lib/python3.11/site-packages/ray/tune/impl/tuner_internal.py:335) # Perform validation and set the re-specified `trainable` and `param_space`

ModuleNotFoundError: No module named 'ray.tune.search.nevergrad'`

**Comment by JustasB** [comment]
@matthewdeng @pcmoritz I second @anhnami 's comment. My team uses Nevergrad extensively, and removal of it from ray tune is a major loss for us.

**Comment by teytaud** [comment]
I am one of the developers of Nevergrad. In Nevergrad's group we see users mentioning that we are not available anymore in Ray; is there anything we should do in Nevergrad so that it is not a problem for people taking care of Ray ? Happy to do anything that can help.

**Comment by teytaud** [comment]
> Nevergrad's OnePlusOne and the recent LogNormalOnePlusOne have been my favorite. They yielded better performance than Optuna for me. Kind of sad because it got removed for no valid reason.

I have added LogNormalOnePlusOne recently and I love it. As seemingly I am not the only one maybe I should add variants of it in Nevergrad as well.

**Comment by daveqs** [comment]
I presently use FLAML with Ray Tune to run automl jobs. With FLAML's blendsearch and cfo algos no longer available in Ray Tune, is their a recommended alternative for using Tune to perform automl?

**Pull request merged**
