### PR TITLE
[ci][wins/1] merge upload wheel logic into  wheel builder container

### PR DESCRIPTION
**Pull request by can-anyscale**
Context: this is a series of PR to move windows wheel to rayci (and deprecate [.buildkite/windows_ci.sh](https://github.com/ray-project/ray/blob/master/.buildkite/windows_ci.sh)). The mentioned script runs into issues when I try to upgrade it to python 3.11. Moving the script to rayci to uniform the window build environment.

Currently we use another container to upload the linux wheel. Merge the logic into the builder container, as a separated container is not necessary.

Test:
- CI

### CODE REVIEW

**Comment by aslonnie** [comment]
> The mentioned script runs into issues when I try to upgrade it to python 3.11

could you talk about what specific issues this runs into? why moving it into the build container fixes the issue?

**Review by aslonnie — COMMENTED** [review]
do you want to move the upload conditioning check out to the script too? or maybe just double check?

now it reads that it is uploading, but on the premerge pipeline, it is actually not?

**Comment by can-anyscale** [comment]
@aslonnie the [.buildkite/windows_ci.sh](https://github.com/ray-project/ray/blob/master/.buildkite/windows_ci.sh) calls `bash ci/ci.sh init` and `bash ci/ci.sh build` which installs dependencies that run into conflicts on windows (https://buildkite.com/ray-project/premerge/builds/20068#018dde20-be58-4569-b33a-18248f52586e/1523-2045). The wanda `windowbuilds` which install less dependencies doesn't run into the issues https://buildkite.com/ray-project/premerge/builds/20068#018dddd1-25f0-45d2-9878-c6398a44d484. I'm working on subsequent PRs to use this windowsbuilds to build windows wheel instead.

**Comment by can-anyscale** [comment]
I'll keep the [copy_build_artifacts script](https://github.com/ray-project/ray/blob/master/ci/build/copy_build_artifacts.sh) as a black box to rayci. It uploads to buildkite artifact on both premerge and postmerge; and only the release s3 bucket on postmerge; but yeah i keep that logic as a blackbox to rayci.

**Comment by aslonnie** [comment]
> which install less dependencies doesn't run into the issues

feels like this can be resolved by using the hermetic python? no?

**Review by aslonnie — APPROVED** [review]

**Comment by aslonnie** [comment]
> > which install less dependencies doesn't run into the issues
> 
> feels like this can be resolved by using the hermetic python? no?

ah, ok. I think I know what you mean now.

**Pull request merged**
