### PR TITLE
[WIP][Tune] Custom resources per worker added to default_resource_request

### PR DESCRIPTION
**Pull request by vakker**
## Why are these changes needed?

This resolves the `TODO(ekl): add custom resources here once tune supports them` item. 
Also, related to the discussion [here](https://discuss.ray.io/t/reserve-workers-on-gpu-node-for-trainer-workers-only/5972/5).

I'm not sure if this is the only change that's required. Currently this is failing with this test script:
```python
import ray
from ray import tune

ray.init(
    resources={"NO-GPU": 1},
    include_dashboard=False,
)

config = {
    "env": "CartPole-v0",
    "num_workers": 1,
    "num_gpus": 0,
    "framework": "torch",
    "custom_resources_per_worker": {"NO-GPU": 0.00001},
}

stop = {"training_iteration": 20}

results = tune.run(
    "PPO",
    config=config,
    stop=stop,
    num_samples=10,
    verbose=3,
)
```

Error:
```sh
(PPOTrainer pid=875980) 2022-05-04 14:45:40,129 ERROR worker.py:451 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPOTrainer.__init__() (pid=875980, ip=192.168.1.134, repr=PPOTrainer)
(PPOTrainer pid=875980)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1085, in _init
(PPOTrainer pid=875980)     raise NotImplementedError
(PPOTrainer pid=875980) NotImplementedError
(PPOTrainer pid=875980) 
(PPOTrainer pid=875980) During handling of the above exception, another exception occurred:
(PPOTrainer pid=875980) 
(PPOTrainer pid=875980) ray::PPOTrainer.__init__() (pid=875980, ip=192.168.1.134, repr=PPOTrainer)
(PPOTrainer pid=875980)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 881, in __init__
(PPOTrainer pid=875980)     super().__init__(
(PPOTrainer pid=875980)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/tune/trainable.py", line 156, in __init__
(PPOTrainer pid=875980)     self.setup(copy.deepcopy(self.config))
(PPOTrainer pid=875980)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 961, in setup
(PPOTrainer pid=875980)     self.workers = WorkerSet(
(PPOTrainer pid=875980)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 142, in __init__
(PPOTrainer pid=875980)     remote_spaces = ray.get(
(PPOTrainer pid=875980) ray.exceptions.ActorUnschedulableError: The actor is not schedulable: Could not create the actor because its associated placement group was removed.
```

Also, not sure about how to test this, probably it should go to `rllib/tests/test_placement_groups.py`.

## Related issue number

I couldn't find a corresponding issue, just the `TODO`.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — APPROVED** [review]
Sorry for the delay. This is great, thanks! I've just merged latest master to kick off CI again.

**Comment by vakker** [comment]
@krfricke thanks for looking into this.
Please note, that I'm not sure this works correctly, or at least my test script fails for some reason.
Also, I haven't written a unit test for this, I wasn't sure where that should go, but I'm happy to write a test if you give me a hint on that.

**Comment by krfricke** [comment]
Hi @vakker, it does pass for me locally. I've added a test to your PR that just runs the script you provided above (slightly altered) with three different algorithms - I've also added your changes to APEX and IMPALA, respectively. Once CI passes we should be good to go - thanks again for your contribution!

**Comment by krfricke** [comment]
cc @ArturNiederfahrenhorst would be great to get your review on this since I've contributed to this PR, thus another pair of eyes would be appreciated!

**Comment by ArturNiederfahrenhorst** [comment]
Yep, we worked on this in parallel and I forgot to assign myself prior to starting work on this.
I'd also like to extend the buffer-shard placement scheme we currently have but that is going to be another PR.
I'll do a review!

**Review by ArturNiederfahrenhorst — APPROVED** [review]
I actually played around with this the whole afternoon for AlphaStar. That algorithm is something else for sure. Lgtm!

**Comment by vakker** [comment]
@krfricke @ArturNiederfahrenhorst this doesn't seem to be working from the latest nightly build (d33148). It gives this error:

```
Usage stats collection is enabled by default for nightly wheels. To disable this, run the following command: `ray disable-usage-stats` before starting Ray. See https://docs.ray.io/en/master/cluster/usage-stats.h
tml for more details.                                                                                                                                                                                              
Started a local Ray instance. View the dashboard at http://127.0.0.1:8265.                                                                                                                                         
/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/util/placement_group.py:78: DeprecationWarning: placement_group parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrate
gy(...) instead, see the usage at https://docs.ray.io/en/master/ray-core/package-ref.html#ray-remote.                                                                                                              
  return bundle_reservation_check.options(                                                                                                                                                                         
/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/_private/ray_option_utils.py:266: DeprecationWarning: Setting 'object_store_memory' for actors is deprecated since it doesn't actually reserve 
the required object store memory. Use object spilling that's enabled by default (https://docs.ray.io/en/master/ray-core/objects/object-spilling.html) instead to bypass the object store memory size limitation.   
  warnings.warn(                                                                                                                                                                                                   
/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/actor.py:637: DeprecationWarning: placement_group parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrategy(...) instea
d, see the usage at https://docs.ray.io/en/master/ray-core/package-ref.html#ray-remote.                                                                                                                            
  return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)                                                                                                                                            
/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/actor.py:637: DeprecationWarning: placement_group_bundle_index parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrateg
y(...) instead, see the usage at https://docs.ray.io/en/master/ray-core/package-ref.html#ray-remote.     
  return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)                                                                                                                                            
/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/actor.py:637: DeprecationWarning: placement_group_capture_child_tasks parameter is deprecated. Use scheduling_strategy=PlacementGroupScheduling
Strategy(...) instead, see the usage at https://docs.ray.io/en/master/ray-core/package-ref.html#ray-remote.                             
  return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)                                                                                                                                            
(PPO pid=1461925) 2022-07-29 14:45:19,383       INFO ppo.py:378 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't 
work for you.                                                                                            
(PPO pid=1461925) 2022-07-29 14:45:19,384       INFO algorithm.py:351 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(PPO pid=1461925) /home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/_private/ray_option_utils.py:266: DeprecationWarning: Setting 'object_store_memory' for actors is deprecated since it doesn't
 actually reserve the required object store memory. Use object spilling that's enabled by default (https://docs.ray.io/en/master/ray-core/objects/object-spilling.html) instead to bypass the object store memory s
ize limitation.                                                                                          
(PPO pid=1461925)   warnings.warn(
(PPO pid=1461925) 2022-07-29 14:45:20,508       ERROR worker.py:754 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=1461925, ip=10.2
05.5.21, repr=PPO)
(PPO pid=1461925)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
(PPO pid=1461925)     super().__init__(config=config, logger_creator=logger_creator, **kwargs)
(PPO pid=1461925)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
(PPO pid=1461925)     self.setup(copy.deepcopy(self.config))
(PPO pid=1461925)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 418, in setup
(PPO pid=1461925)     self.workers = WorkerSet(
(PPO pid=1461925)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 125, in __init__
(PPO pid=1461925)     self.add_workers(
(PPO pid=1461925)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
(PPO pid=1461925)     self.foreach_worker(lambda w: w.assert_healthy())
(PPO pid=1461925)   File "/home/vince/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
(PPO pid=1461925)     remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
(PPO pid=1461925) ray.exceptions.ActorUnschedulableError: The actor is not schedulable: Could not create the actor because its associated placement group was removed.
```

Does this work in the unit test?

**Comment by vakker** [comment]
@krfricke @ArturNiederfahrenhorst 
I found the issue. If I use `"custom_resources_per_worker": {"custom_resource": 0.00001}` instead of `0.01`, then it gives the above mentioned error. Might this be some sort of float rounding issue? 

It's not really blocking me any more (I choose `0.00001` as a random small number), but it might indicate some deeper issue with the resource management.

**Pull request merged**
