### PR TITLE
[kuberay] add kuberay team, remove kuberay_operator tag

### PR DESCRIPTION
**Pull request by aslonnie**
transfers the test owner to kuberay team.

### CODE REVIEW

**Comment by aslonnie** [comment]
transfer as promised.

**Comment by aslonnie** [comment]
@can-anyscale , I leave it to you to handle this new team in the flaky test tracker.

**Comment by can-anyscale** [comment]
Will do! You may need to add a kuberay.tests.yaml for the test_in_docker to be happy.

**Review by architkulkarni — APPROVED** [review]

**Review by kevin85421 — APPROVED** [review]

**Comment by aslonnie** [comment]
> Will do! You may need to add a kuberay.tests.yaml for the test_in_docker to be happy.

added.

**Pull request merged**
