### PR TITLE
[C++] Add cpp nested remote tests

### LINKED ISSUE #21326: [C++] No tests for nested remote/get/put/wait calls
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

There is potentially an issue with linking to core worker dynamically when making nested calls to core worker in remote tasks.

The C++ API ought to add tests for such nested tasks to ensure such linkage issues do not occur.

CC: @qicosmos @SongGuyang 

### Use case

Ensure correct behaviour.

### Related issues

https://github.com/ray-project/ray/pull/21125

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jon-chuang**
## Why are these changes needed?
Add tests for nested calls Remote in C++

TODO: also test nested Put, Get, Wait?

## Related issue number

Closes: https://github.com/ray-project/ray/issues/21326

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by SongGuyang — APPROVED** [review]
LGTM. Thank you for this test.

**Comment by jon-chuang** [comment]
seems there are some flaky tests 

@SongGuyang should I include
> TODO: also test nested Put, Wait?
in this PR too?

**Comment by SongGuyang** [comment]
> 

Yep, I think the tests is necessary and useful.

**Comment by jon-chuang** [comment]
@SongGuyang , I seem to have found an issue revealed by the newest test, resulting in a sigsev. Could you reproduce?
`bazel run cluster_mode_test`
```
*** SIGSEGV received at time=1641529429 on cpu 2 ***
PC: @     0x562d91ccaf0b  (unknown)  ray::internal::NativeObjectStore::GetRaw()
    @     0x7f78141db3c0  (unknown)  (unknown)
    @     0x562d91cca797        176  ray::internal::NativeObjectStore::GetRaw()
    @     0x562d91ccb757         32  ray::internal::ObjectStore::Get()
    @     0x562d91cc560d         96  ray::internal::AbstractRayRuntime::Get()
    @     0x562d91ca16d2        160  ray::GetFromRuntime<>()
    @     0x562d91ca488e       2944  RayClusterModeTest_FullTest_Test::TestBody()
    @     0x562d92532c94         96  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x562d92532efe         48  testing::Test::Run()
    @     0x562d92533255         80  testing::TestInfo::Run()
    @     0x562d92533ab4         80  testing::TestSuite::Run()
    @     0x562d925341ea        176  testing::internal::UnitTestImpl::RunAllTests()
    @     0x562d925334a4         96  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @     0x562d925336ba        128  testing::UnitTest::Run()
    @     0x562d91c25fe3         80  main
    @     0x7f7813ca20b3  (unknown)  __libc_start_main
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317: *** SIGSEGV received at time=1641529429 on cpu 2 ***
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317: PC: @     0x562d91ccaf0b  (unknown)  ray::internal::NativeObjectStore::GetRaw()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x7f78141db3c0  (unknown)  (unknown)
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d91cca797        176  ray::internal::NativeObjectStore::GetRaw()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d91ccb757         32  ray::internal::ObjectStore::Get()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d91cc560d         96  ray::internal::AbstractRayRuntime::Get()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d91ca16d2        160  ray::GetFromRuntime<>()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d91ca488e       2944  RayClusterModeTest_FullTest_Test::TestBody()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d92532c94         96  testing::internal::HandleExceptionsInMethodIfSupported<>()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d92532efe         48  testing::Test::Run()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d92533255         80  testing::TestInfo::Run()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d92533ab4         80  testing::TestSuite::Run()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d925341ea        176  testing::internal::UnitTestImpl::RunAllTests()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d925334a4         96  testing::internal::HandleExceptionsInMethodIfSupported<>()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d925336ba        128  testing::UnitTest::Run()
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x562d91c25fe3         80  main
[2022-01-07 04:23:49,807 E 37877 37877] logging.cc:317:     @     0x7f7813ca20b3  (unknown)  __libc_start_main
```

**Comment by jon-chuang** [comment]
Actually, this is the result of not merging https://github.com/ray-project/ray/pull/21236

Let's get it merged quickly so this PR and others can also be unblocked.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Pull request closed without merging**
