### PR TITLE
[2.3.0][Doc] Remove Ray Client references from Tune and Train docs/examples

### PR DESCRIPTION
**Pull request by justinvyu**
## Why are these changes needed?

Cherry pick of https://github.com/ray-project/ray/pull/32299

This PR removes references to Ray Client in Tune and Train examples. It also removes outdated references of needing `ray.init("auto")` being used to connect to an existing cluster vs. `ray.init()` creating a new local cluster.

The latest `ray.init()` docstring explains that:

> This method handles two cases; either a Ray cluster already exists and we just attach this driver to it or we start all of the processes associated with a Ray cluster and attach to the newly started cluster.

New version of this PR: https://github.com/ray-project/ray/pull/31712

## Related issue number

Closes https://github.com/ray-project/ray/issues/31621
Closes https://github.com/ray-project/ray/issues/30227 (fixes the `pbt_ppo_example.ipynb` config to use a valid Humanoid env, and cleans up the display output)

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]
Approving for cherry picking into 2.3.0

**Comment by cadedaniel** [comment]
I think this breaks the docbuild on the release branch. Can you take a look @justinvyu ?

```
Document: tune/api_docs/stoppers
--------------------------------
2023-02-10 12:25:39,141	ERROR trial_runner.py:1062 -- Trial Trainable_13460_00000: Error processing event.
ray.exceptions.RayTaskError(NotImplementedError): ray::Trainable.train() (pid=15556, ip=172.16.16.3, repr=<ray.tune.trainable.trainable.Trainable object at 0x7fedb4ded350>)
  File "/ray/python/ray/tune/trainable/trainable.py", line 368, in train
    raise skipped from exception_cause(skipped)
  File "/ray/python/ray/tune/trainable/trainable.py", line 365, in train
    result = self.step()
  File "/ray/python/ray/tune/trainable/trainable.py", line 1120, in step
    raise NotImplementedError
```

**Comment by cadedaniel** [comment]
I'm a little confused, this PR passes but it fails later on an unrelated PR https://buildkite.com/ray-project/oss-ci-build-branch/builds/2283#01863cc5-e638-498e-b6ef-f4745e5b4ad8

**Comment by justinvyu** [comment]
Looking into it now.

**Comment by justinvyu** [comment]
@cadedaniel Looks like these two docs contain doc code that fails:

Document: tune/api_docs/integration
Document: tune/api_docs/stoppers

Quickly looking through it, there are code snippets that should never have passed, and are completely unrelated to this PR.
Should I make a fix for the doc code in these 2 files and cherry pick it?

Example:

```python
    class Stopper(abc.ABC):
        >>> import time
        >>> from ray import air, tune
        >>> from ray.tune import Stopper
        >>>
        >>> class TimeStopper(Stopper):
        ...     def __init__(self):
        ...         self._start = time.time()
        ...         self._deadline = 5
        ...
        ...     def __call__(self, trial_id, result):
        ...         return False
        ...
        ...     def stop_all(self):
        ...         return time.time() - self._start > self._deadline
        >>>
        >>> tuner = tune.Tuner(
        ...     tune.Trainable,
        ...     tune_config=tune.TuneConfig(num_samples=200),
        ...     run_config=air.RunConfig(stop=TimeStopper())
        ... )
        >>> tuner.fit()
        == Status ==...
```

**Comment by cadedaniel** [comment]
Moving to slack

**Pull request merged**
