### PR TITLE
Don't capture child tasks in placement groups by default

### LINKED ISSUE #17524: Placement groups should not capture child tasks by default
Capturing child tasks seems like a "gotcha" for library composition.

For example, if you use serve with workflows, the workflows will just hang if serve is using placement groups. Same with datasets + training.

Apparently, due to this Serve is already disabling it by default.

cc @rkooo567 @clay4444 @edoakes @richardliaw

### PR DESCRIPTION
**Pull request by ericl**
Capturing child tasks seems like a "gotcha" for library composition.

For example, if you use serve with workflows, the workflows will just hang if serve is using placement groups. Same with datasets + training.

Apparently, due to this Serve is already disabling it by default.

This is technically changing behavior, but the feature was never documented (and afaik no workloads rely on this).

Closes https://github.com/ray-project/ray/issues/17524

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by Yard1** [comment]
Won't we need to turn it on for Tune's trainables?

**Comment by richardliaw** [comment]
why is that? or rather which one in particular?

**Comment by Yard1** [comment]
@richardliaw if we have a trainable that spawns child actors (eg. XGBoost-Ray) we would want them to use the parent placement groups, so that resources per trial can be set properly. So we would need to set this flag to true in order for this behavior to continue (as far as I understand the change this PR is introducing, please correct me if I am wrong)

**Review by edoakes — APPROVED** [review]

**Comment by richardliaw** [comment]
Ah yes, we would have to force this to be the case in all placement group factories (which shouldn't be too many)

**Comment by ericl** [comment]
Hmm, the above discussion makes me think we don't have quite the right API here. Because it's certainly possible for one to want to capture trainable child actors, but not capture Dataset tasks/actors.

**Comment by Yard1** [comment]
Actually @ericl would it be possible to make `placement_group_capture_child_tasks` an attribute of the placement group itself?

**Pull request merged**
