### PR TITLE
[2.3][Docs] Refactor Ray Workflows API documentation (cherry-pick #32248 into 2.3.0 branch)

### PR DESCRIPTION
**Pull request by c21**
## Why are these changes needed?

Cherry pick https://github.com/ray-project/ray/pull/32248 to releases/2.3.0.

## Checks

- [] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
LGTM. @zhe-thoughts @richardliaw approval please

**Review by cadedaniel — APPROVED** [review]

**Review by zhe-thoughts — APPROVED** [review]
Approving this for cherry picking to 2.3. But someone from the ray-docs group should approve before we merge to master (and then cherry pick)

**Comment by c21** [comment]
@zhe-thoughts - the original PR was approved by ray-docs actually - https://github.com/ray-project/ray/pull/32248 .

**Comment by zhe-thoughts** [comment]
OK then sounds good to pick. Thanks!

**Pull request merged**
