### PR TITLE
bug fix: merging --config params with params.pkl

### LINKED ISSUE #4290: rllib rollout does not load the model automatically from params.json
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 4.4.0-135-generic x86_64 
- **Python version**: Python 3.6.5 

### Source code / logs

rllib rollout does not load the model automatically from params.json for a simple 256x256x256x256 model. 
When I run rllib rollout without specifying --config with "model": {"fcnet_hiddens": [256, 256, 256, 256]} it fails with the following error:
```
    assert len(vector) == i, "Passed weight does not have the correct shape."
AssertionError: Passed weight does not have the correct shape.
```

### PR DESCRIPTION
**Pull request by AmeerHajAli**
## What do these changes do?
merge params.pkl with --config when using rollout.py

## Related issue number
Closes #4290

### CODE REVIEW

**Comment by ericl** [comment]
Thanks! I also pushed a small change to ensure num_workers is still capped at 2 by default.

**Review by ericl — APPROVED** [review]

**Comment by AmeerHajAli** [comment]
I believe that your change does not affect the behavior of the script, because either ways `config = merge_dicts(config, args.config)` is after you set the minimum default. And if the path did not exit then `config = {}` either ways.

**Comment by ericl** [comment]
Ah, good point. I guess it is ok to leave changed since it may be slightly more readable (at least to me).

**Comment by ericl** [comment]
Tests look good! Thanks for contributing this.

**Pull request merged**
