### PR TITLE
[docs] Update RLlib install to not include Tensorflow

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?

Changes `ray[rllib]` installation not to include TensorFlow.

## Related issue number

#2038

### CODE REVIEW

**Comment by ericl** [comment]
Don't we kind of have a hard dep on tensorflow right now? This should also come with a test.

**Comment by richardliaw** [comment]
https://github.com/ray-project/ray/issues/2038#issuecomment-388708183

Another option is to try to import tensorflow, and if not able, then include it in the extra dependency.

**Comment by ericl** [comment]
I think we should remove it as a hard dep; just pointing out that we would need some more work to make sure it doesnt' accidentally end up as a dependency again.

**Comment by robertnishihara** [comment]
Removing it as a hard dependency makes sense to me

Trying to import TF I’m setup.py doesn’t make sense. These dependencies are
needed for PyPI primarily.

**Comment by ericl** [comment]
I see, looks good then.

**Review by ericl — APPROVED** [review]

**Comment by richardliaw** [comment]
@ericl how would I test to make sure it doesn't end up as a dependency again?

**Comment by ericl** [comment]
https://github.com/ray-project/ray/blob/master/python/ray/tune/test/dependency_test.py

**Comment by richardliaw** [comment]
Oh I see, I don't think this is the same thing; this is not removing the TF dependency but just making sure we don't force users to install multiple versions of TF.

**Comment by richardliaw** [comment]
Test failure unrelated.

**Pull request merged**
