### PR TITLE
[Refactor] Replace FractionalResourceQuantity with FixedPoint

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

As mentioned in https://github.com/ray-project/ray/issues/15943#issuecomment-847657365 ,  we want to clean up some stale data structures in `scheduling_resources.h`. 

I'll split it into several PRs:

1. Replace `FractionalResourceQuantity` with `FixedPoint`
2. Reimplement `ResourceSet` in the style of new scheduler in`cluster_resource_data.h`.
3. Move `SchedulingResources` to `cluster_resource_data.h`.
4. Replace `ResourceIds` with `ResourceInstanceCapacities`
5. Replace `ResourceIdSet` with `NodeResourceInstances`

This is the first PR that replaces `FractionalResourceQuantity` with `FixedPoint`. Please have a look, thanks!

## Related issue number

https://github.com/ray-project/ray/issues/15943#issuecomment-847657365

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
LGTM if tests pass. Note that test_basic_3 is failing, which seems highly related: test_many_fractional_resources

**Comment by lixin-wei** [comment]
@ericl `:test_many_fractional_resources` seems not written correctly. He compared a rounded fractional number with an ungrounded one.  For example, he passes an `{'Custom': 0.264}` as `accepted_resources` to `f`, and when calling `f`, he sets `resource={'Custom': 0.2641}`. In `f`, he gets worker's resource usage using ray's API, and got `{'Custom': 0.2641}`, then he compared it with `{'Custom': 0.264}` - absolutely they are not equal.

I modified this test and it will pass.

But I've no idea why it can be passed before, please double-check whether I've modified it correctly, thanks.

**Comment by ericl** [comment]
Hmm, I think the previous behavior was Ray was truncating resources to units of at fewest 0.0001. Should we preserve this behavior for backwards compatibility? I think systems like K8s do this rounding to avoid corner cases with very small units of resources.

**Comment by lixin-wei** [comment]
@ericl OK, I found the problem. `FixedPoint` uses rounding rather than truncating in `FractionalResourceQuantity`:
```cpp
FixedPoint::FixedPoint(double d) {
  // We need to round, not truncate because floating point multiplication can
  // leave a number slightly smaller than the intended whole number.
  i_ = (uint64_t)((d * RESOURCE_UNIT_SCALING) + 0.5);
}
```
```cpp
FractionalResourceQuantity::FractionalResourceQuantity(double resource_quantity) {
  resource_quantity_ =
      static_cast<int64_t>(resource_quantity * kResourceConversionFactor);
}
```

As alex commented, he wants to void precision lost in floating numbers. To keep backward compatibility, I changed it back to truncating. Do you think is OK?

cc @wuisawesome

**Review by ericl — APPROVED** [review]
LGTM. It makes sense to avoid precision loss, that could lead to resource inconsistencies.

**Comment by lixin-wei** [comment]
> LGTM. It makes sense to avoid precision loss, that could lead to resource inconsistencies.

Yes, We can open another PR to handle the precision loss. In this PR, Iet's keep backward compatibility first.

**Comment by ericl** [comment]
Ah, I meant that truncation avoids precision loss that might be introduced
by rounding. I think it's safer to keep using truncation.

**Comment by lixin-wei** [comment]
> Ah, I meant that truncation avoids precision loss that might be introduced by rounding. I think it's safer to keep using truncation.

I think the precision loss will always happen as long as float number is used. Rounding actually reduces the impact of precision loss.

For example, `2-1.1` will be `0.899999...` in float number. If we use truncation, it will be `0.8999` instead of `0.9`. There will be `0.0001` resources more. Users will be confused: why there is 0.0001 resource left?

**Comment by lixin-wei** [comment]
hi @ericl, I'm curious about what you said. Could you please explain more about it? Did I misunderstand anything?

**Comment by ericl** [comment]
I think you're right. But, it's probably fine to keep truncation.

**Comment by wuisawesome** [comment]
I think in the ideal future, we may want to define a `message FixedPoint` protobuf instead of sending floats over the wire to avoid these problems, but this PR looks like a great start.

**Pull request merged**
