### PR TITLE
[Docker] Downgrade to CUDA 11.0

### LINKED ISSUE #17796: rllib does not work on gpus on our default docker images
repro:
1) replace m5.large head node with p2.xlarge for example-full.yaml.
2) `ray up -y ray/python/ray/autoscaler/aws/example-full.yaml` 
3) set num_gpus=1 inside cartpole-impala.yaml (see step below)
4) call `rllib train -f ray/python/ray/rllib/tuned_examples/impala/cartpole-impala.yaml`

error:
```
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::IMPALA.__init__() (pid=1178, ip=192.168.78.58)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 584, in __init__
    super().__init__(config, logger_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 731, in setup
    self._init(self.config, self.env_creator)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 152, in _init
    num_workers=self.config["num_workers"])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 819, in _make_workers
    logdir=self.logdir)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 103, in __init__
    spaces=spaces,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 431, in _make_worker
    spaces=spaces,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 583, in __init__
    policy_config["framework"]))
RuntimeError: GPUs were assigned to this worker by Ray, but your DL framework (tf) reports GPU acceleration is disabled. This could be due to a bad CUDA- or tf installation.
```

Fix:
`pip install tensorflow==2.3.3`
OR
`pip install tensorflow==2.5.0 tensorflow-gpu==2.5.0`

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by amogkam**
Downgrade the Docker image to CUDA 11.0 to support TF 2.4. 

Confirmed that this setup results in `tf.config.experimental.list_physical_devices("GPU")`  and `torch.cuda.is_available()` are giving the correct output.

Note that we cannot upgrade to 2.5 since RLlib does not fully support this version yet. https://github.com/ray-project/ray/pull/15849

Closes https://github.com/ray-project/ray/issues/17796

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ijrsvt** [comment]
Hmm, should we trigger a rebuild of the `1.5.2` images with CUDA 11.0?

**Comment by amogkam** [comment]
yeah we probably should. this wouldn't require another Ray release would it? we would just need to cherry pick this into the 1.5.2 branch?

**Comment by ijrsvt** [comment]
@amogkam we should definitely merge this into the 1.6.0 branch!

**Comment by ijrsvt** [comment]
> yeah we probably should. this wouldn't require another Ray release would it? we would just need to cherry pick this into the 1.5.2 branch?


I'm not 100% sure, but that should work ❓ . I did this more/less manually last time we did something like this.

**Review by sven1977 — APPROVED** [review]
Great, thanks for this fix @amogkam ! This will make all things ML on Anyscale a lot easier. :)

**Comment by AmeerHajAli** [comment]
@amogkam , did we rebuild 1.5.2 images?
I am still getting the TF version mismatch error on anyscale on images 1.5.2...

**Comment by amogkam** [comment]
No I didn’t rebuild the 1.5.2 image, and I’m not sure if we want to do that anymore since it could create issues like this: https://github.com/ray-project/ray/issues/17857

If we downgrade the cuda version it could break existing user’s workflows that relied on cuda 11.2.

**Comment by AmeerHajAli** [comment]
Which ray version will work out of the box with tune and rllib on gpus?

**Comment by amogkam** [comment]
Nightly should work, and 1.6 once it is released

**Comment by amogkam** [comment]
You can also use 1.5.2 GPU image (not the ML image) and manually install tensorflow 2.5, which will work with tune and most of rllib.

**Pull request merged**
