### PR TITLE
[data] Make file datasource outputs streaming to avoid OOM

### LINKED ISSUE #37948: [data] OOM and churning workers when scaling ray.data range(N).map_batches().write_parquet()
### What happened + What you expected to happen

The following script works on a single machine with .range(20_000) but not .range(2000_000). On a cluster of 50 nodes, .range(2000_000) did work.

On a single machine, the error appears to be related to OOM. A bunch of workers die, the job seems to hang, and eventually the head node OOMs:
```
2023-07-31 13:21:11,493 WARNING worker.py:2033 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 7ac38ed8da51f4942c5686b2440b9f9072b72fca05000000 Worker ID: f530786cc9b151c9f869e67bb305a1527df20f17db908db549d8bb08 Node ID: fca0d09d1c781c91823983155a4fdbe0b0e3aeaf64c3ceddba6b80ca Worker IP address: 10.0.50.125 Worker port: 10125 Worker PID: 17011 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

### Versions / Dependencies

3.0dev

### Reproduction script

```python
import os
import resource
import time
from typing import List
import traceback

import numpy as np
import psutil

import ray
from ray.data.context import DataContext
from ray.data.datasource import Datasource, ReadTask


def generate(batch):
    batch["test"] = np.random.rand(len(batch["id"]), 1000_000 // 8)                                                                                                                                             
    return batch

if __name__ == "__main__":
    ray.init()

    ctx = DataContext.get_current()
    ray.data.DataContext.get_current().execution_options.verbose_progress = True

    start_time = time.time()
    ds = ray.data.range(200 * 1000).map_batches(generate, batch_size=1)
    ds.write_parquet("s3://swang-test-shuffle/test-parquet-2")
    end_time = time.time()

    print(ds._write_ds.stats())
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

If multiple blocks were to be written to the same file, it used to require all blocks to be in memory at once. This PR makes the FileBasedDatasource's internal interface streaming, so that each datasource can choose to write one block at a time. This limits memory usage per write task to about the size of one block (default 512MB).

Note that numpy and JSON datasources do not support writing multiple objects to one file. To support these, we would need to split to multiple output files.

## Related issue number

Closes #37948.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
As an alternative, what do you think about disabling fusion between map and write stages? This would allow block splitting to naturally occur and support JSON/numpy as well.

The tradeoff is there could be extra communication overheads, but in principle streaming should take care of this.

**Comment by stephanie-wang** [comment]
> As an alternative, what do you think about disabling fusion between map and write stages? This would allow block splitting to naturally occur and support JSON/numpy as well.
> 
> The tradeoff is there could be extra communication overheads, but in principle streaming should take care of this.

I don't think we should necessarily split here because this case is bit different from the read tasks being too large. This one can happen even if the map tasks have enough parallelism. So we may be paying a lot of materialization cost for no gain.

Long-term, I think the ideal scenario would be to write to multiple files to handle JSON/numpy better, and I wish the decision of when to split a task could also be decoupled from stage optimization rules.

**Review by ericl — COMMENTED** [review]
> Long-term, I think the ideal scenario would be to write to multiple files to handle JSON/numpy better, and I wish the decision of when to split a task could also be decoupled from stage optimization rules.

Got it. I think this makes sense then.

Btw for JSON, actually have you tried calling to_json() multiple times to append to the file? Since we use line-delimited json, I think in principle we don't need any special multi-write support.

Separately, I am also wondering how we can more rigorously test our block splitting support and/or make sure we raise warnings when splitting is not possible and we are exceeding the target block size. I feel like we've been playing whack-a-mole and lately almost all user stability issues are due to large blocks.

**Comment by stephanie-wang** [comment]
> Btw for JSON, actually have you tried calling to_json() multiple times to append to the file? Since we use line-delimited json, I think in principle we don't need any special multi-write support.

Ah good point, let me try this.

> Separately, I am also wondering how we can more rigorously test our block splitting support and/or make sure we raise warnings when splitting is not possible and we are exceeding the target block size. I feel like we've been playing whack-a-mole and lately almost all user stability issues are due to large blocks.

Definitely agree we need more testing/warning here. There are some issues out for this already:
- #37106
- #37915

**Comment by c21** [comment]
Actually after a second thought, can we just write multiple files from one task? When the accumulated in-memory blocks size exceed a threshold, we write one file. This should support all cases except NumPy.

I am a little worried about the Arrow file-appending now, espescially for Parquet. After a second thought, I don't know how it's possible to implement appending to Parquet file, which by design looks to me is not appendable. So I am afraid of it still accumulating Parquet row groups in memeory.

**Comment by c21** [comment]
For reference, Spark is having a threshold to allow maximal records/rows per each file, and will write a new file if exceeding the threshold - https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala#L167-L178 . I think we can do a better job here to write a file based on in-memory blocks sizes.

**Comment by stephanie-wang** [comment]
> Actually after a second thought, can we just write multiple files from one task? When the accumulated in-memory blocks size exceed a threshold, we write one file. This should support all cases except NumPy.
> 
> I am a little worried about the Arrow file-appending now, espescially for Parquet. After a second thought, I don't know how it's possible to implement appending to Parquet file, which by design looks to me is not appendable. So I am afraid of it still accumulating Parquet row groups in memeory.

Agreed, writing to multiple files is also safer for read-back, if the read datasources don't support streaming.

I think we should still add streaming writes eventually to minimize memory usage, so we should revisit this implementation later. Closing this for now in favor of

**Pull request closed without merging**
