### PR TITLE
[Doc] Remove pendo

### LINKED ISSUE #42884: [Pendo] Remove Pendo tracking from Ray docs
### Description

After talking to @angelinalg and @simran-2797 , we decide to stop using Pendo for Ray Docs analytics. I will submit a ticket to have the Pendo support team remove it from their end. We should also remove the tracking code from our side.

### Link

_No response_

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR removes pendo from the docs.

## Related issue number

Closes https://github.com/ray-project/ray/issues/42884.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by sijieamoy — APPROVED** [review]
LGTM - thank you @peytondmurray !

**Review by aslonnie — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/gifs/clean-NHHYRm7mAUQ6Y">GIPHY</a></div>

**Comment by peytondmurray** [comment]
Hey folks, is there anything else that needs to get done to get this merged?

**Comment by aslonnie** [comment]
some one in @ray-project/ray-docs need to approve.

@angelinalg maybe?

**Review by angelinalg — APPROVED** [review]

**Pull request merged**
