### PR TITLE
[Client] use SimpleQueue for streaming requests on Python 3.7 and above

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
As mentioned in https://github.com/ray-project/ray/issues/22082#issuecomment-1031821631, acquiring locks in `__del__()` can result in deadlock. This means queue.Queue() cannot be used in `__del__()` either. Using `queue.SimpleQueue` instead, which is implemented in C, avoids the problem.

However `queue.SimpleQueue` is only available from Python 3.7. There seems to be no good way to fix this for Python 3.6, other than backporting `queue.SimpleQueue` or implement something similar in cython / C++.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ckw017 — APPROVED** [review]
Looks good. IMO using regular queue on 3.6 is fine since 3.6 is at end of life.

**Comment by iycheng** [comment]
This one seems not working, and somehow there is still circular reference which I don't know how to identify. https://github.com/ray-project/ray/pull/22263

I'll vote for this solution.

**Comment by mwtian** [comment]
> I'll vote for this solution.

I see. IMO using weak ref to allow dropping worker earlier is good, regardless of whether #22263 fixes the timeout completely. For this PR, somehow Windows tests (using Python 3.8) are failing. Will come back later to debug.

**Comment by iycheng** [comment]
Btw, it seems like the code path actually is not tested in CI. Should we at least run py37 test for client code?

**Comment by mwtian** [comment]
> Btw, it seems like the code path actually is not tested in CI. Should we at least run py37 test for client code?

Maybe we can test this manually on Python 3.7 for now.

**Pull request closed without merging**
