### PR TITLE
[core] Nested tasks on by default

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This PR turns worker capping on by default. Note that there are a couple of faulty tests that this uncovers which are fixed here. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
Remaining TODOs here (will comment as i manually test them)

* Run `test_multinode_failure.py::test_worker_failed` 100x locally to make sure it's not flakey.
* Run `test_virtual_actor.py::test_readonly_method` 100x locally to make sure it's not flakey.
* Ensure no regressions in nightly testing.

**Comment by wuisawesome** [comment]
Ran `test_multinode_failure.py::test_worker_failed` 100x and it looks good

**Comment by iycheng** [comment]
Should we merge this after 1.10 cut?

**Comment by wuisawesome** [comment]
Yes, after 1.10 branch cut. Here are the results of the release tests: 

core-daily: https://buildkite.com/ray-project/periodic-ci/builds/1819
core-scalability: https://buildkite.com/ray-project/periodic-ci/builds/1821
serve-nightly: https://buildkite.com/ray-project/periodic-ci/builds/1823
core-nightly: https://buildkite.com/ray-project/periodic-ci/builds/1820

**Comment by ericl** [comment]
Can we run all tests, both CI and nightly tests multiple times here to make sure things didn't get lucky again?

**Comment by ericl** [comment]
I think we can merge this now?

**Comment by wuisawesome** [comment]
Release test run looks ok:

There's an infra failure, the chaos test that fails has a 0% pass rate, and the weekly failure looks like it's broken in master (still confirming this last one) 

core-scalability: https://buildkite.com/ray-project/periodic-ci/builds/2230
serve-nightly: https://buildkite.com/ray-project/periodic-ci/builds/2232
core-daily: https://buildkite.com/ray-project/periodic-ci/builds/2238
core-nightly: https://buildkite.com/ray-project/periodic-ci/builds/2239
weekly: https://buildkite.com/ray-project/periodic-ci/builds/2233

**Comment by ericl** [comment]
Seems promising. @rkooo567 @scv119 can you make a pass for due diligence on the results too?

**Comment by wuisawesome** [comment]
I think the remaining release test is good to go. `many_drivers` in the weekly tests is failing on master (see #21413)

which means all the release tests are still passing.

**Comment by wuisawesome** [comment]
@rkooo567 @scv119 does thumbs up mean "tests look ok" or "yes i will look later?"

**Comment by scv119** [comment]
Means I'll look now :)
Does https://buildkite.com/ray-project/periodic-ci/builds/2233#2f395d07-b2b7-468c-941b-cf658c74988e look concerning?

**Review by rkooo567 — APPROVED** [review]

**Comment by wuisawesome** [comment]
> Does https://buildkite.com/ray-project/periodic-ci/builds/2233#2f395d07-b2b7-468c-941b-cf658c74988e look concerning?

Concerning? yes, but see #21413, it's failing on master (looks like the failure mode is some dashboard memory leak) which seems unrelated to this PR.

**Review by ericl — APPROVED** [review]

**Pull request merged**
