### PR TITLE
[tune] Pass custom `sync_to_cloud` templates to durable trainables

### LINKED ISSUE #16284: [Tune] Syncing to self-hosted S3 storage fails when checkpointing
### What is the problem?
Syncing to a self-hosted S3 storage fails when checkpoint_freq >= 1 is set in tune.run.
Because the S3 storage is self-hosted, the --endpoint-url flag needs to be set in the AWS CLI or it can't be found. 
This can't be circumvented by configuring the AWS CLI as far as I know [https://github.com/aws/aws-cli/issues/1270](url).

So to run the aws sync command with a custom endpoint I created the following SyncConfig:
```
        sync_config = tune.SyncConfig(
            sync_to_driver=False,
            upload_dir=f's3://tune-trials/',
            sync_to_cloud=f'aws --endpoint-url {os.environ["S3_ENDPOINT"]} s3 sync ' \
                          '{source} {target} --only-show-errors'
        )
```

This works for:
```
        analysis = tune.run(tune.durable(TFTrainable),
                            sync_config=sync_config,
                            num_samples=5,
                            config=tune_config,
                            stop={'training_iteration': 10},
                            verbose=True
                            )
```

But fails for:
```
        analysis = tune.run(tune.durable(TFTrainable),
                            sync_config=sync_config,
                            num_samples=5,
                            config=tune_config,
                            stop={'training_iteration': 10},
                            verbose=True,
                            checkpoint_freq=1,
                            checkpoint_score_attr='validation_loss')
```

with the following error:

```
ray.tune.error.TuneError: Sync error. Ran command: aws s3 sync /home/ray/ray_results/TFTrainable_2021-06-07_01-17-35/TFTrainable_d0d56_00000_0_learning_rate=1e-06_2021-06-07_01-17-36/ s3://tune-trials/TFTrainable_2021-06-07_01-17-35/TFTrainable_d0d56_00000_0_learning_rate=1e-06_2021-06-07_01-17-36 --only-show-errors
Error message (1): fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

As you can see ray defaults to the standard aws s3 sync command instead of the one provided in SyncConfig.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Build from rayproject/ray-ml:e58ba6-py38 image on Ubuntu 18.04.4 LTS

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

`sync_to_cloud` templates are currently not passed to durable trainables. 

## Related issue number

Closes #16284

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
Hmm, looks like tests are failing?

**Review by richardliaw — COMMENTED** [review]
Generally looks fine ; ping when tests merge?

**Comment by krfricke** [comment]
ping @richardliaw

**Review by richardliaw — APPROVED** [review]
nice!

**Pull request merged**
