### PR TITLE
Enable dashboard on Windows

### LINKED ISSUE #15650: [dashboard] Dashboard completely empty
Ray version: 1.3.0, installed with `pip install -U ray[default]`
Python: 3.8 in a conda environment
OS: Ubuntu 18.04

No matter how I start ray, either with
* `ray start --head` from the command line
* or `ray.init()` from Python

When I visit http://127.0.0.1:8265 afterwards, I get a completely blank screen, in Firefox and Chrome.

In order to make sure this is not because of any installed add-on I did:

```
mkdir tmpff
firefox -profile tmpff -no-remote http://127.0.0.1:8265
```

This shows the dashboard for a very short time (from a fraction of a second to about a second) after which the page goes completely blank and stays that way. 

When adding arbitrary path elements to the URL, sometimes the left-hand pane with the NODES/JOBS/.. menu appears and stays. Clicking one of NODES, JOBS, ACTORS, LOGS, shows the screen OK and the screen stays.
However, clicking "BACK TO EXISTING DASHBOARD" shows a completely blank screen again.

When looking at the JS console of the page I get:
```
TypeError: e is undefined      react-dom.production.min.js:209:194
```

No idea if the following is unrelated or not, but the dashboard_agent.log contains many errors line this one:
```
2021-05-05 19:08:34,252	ERROR reporter_agent.py:531 -- Error publishing node physical stats.
13Traceback (most recent call last):
14  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 526, in _perform_iteration
15    records_reported = self._record_stats(stats, formatted_status)
16  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 415, in _record_stats
17    gpus_utilization += gpu["utilization_gpu"]
18TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
192021-05-05 19:08:36,772	ERROR reporter_agent.py:531 -- Error publishing node physical stats.
20Traceback (most recent call last):
21  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 526, in _perform_iteration
22    records_reported = self._record_stats(stats, formatted_status)
23  File "/home/johann/software/anaconda/envs/ray/lib/python3.8/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 415, in _record_stats
24    gpus_utilization += gpu["utilization_gpu"]
25TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

### LINKED ISSUE #18413: Dashboard error
I am trying some examples with rllib, python 3.9, pytorch, Windows 10, and all of them starts without any error
2021-09-08 02:48:17,754 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8265

And when I try to view the dashboard in browser I get this error

image

### PR DESCRIPTION
**Pull request by mattip**
## Why are these changes needed?

This builds on #19014 (which in general fixes windows process creation) to enable the dashboard on windows.
- use `pip install gpustat==1.0.0b1` (closes #15650)
- remove the code in `agent.py` that disabled the dashboard
- change the way a new redis connection is made in the dashboard so that the connection is created inside the thread that uses it.

## Related issue number

Closes #18413, #9620. 

I still cannot see http://127.0.0.1:8265/#/, I must go to any of the other links like http://127.0.0.1:8265/#/job or http://127.0.0.1:8265/#/node. The top-level link has a javascript exception 
```
TypeError: e.disk['/'] is undefined
    D NodeInfo.tsx:218
    Vn NodeInfo.tsx:218
```

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by carlogrisetti** [comment]
Thanks for contributing this PR... it was one of my objectives to tackle next :)

**Comment by carlogrisetti** [comment]
Might be useful to leave the warning message as a warning to the user that this is not a stable implementation, but changing the warning text not saying it's disabled but "broken" (taking inspiration from the comment)

**Comment by mattip** [comment]
@simon-mo I refactored the disk usage map, and now can see the whole dashboard when running locally. 

I tried running `>python -m pytest python\ray\tests\test_dashboard.py` and got `1 failed, 4 passed in 98.12s (0:01:38)`. The test that failed is `test_port_auto_increment`, it seems to segfault. Perhaps with #19014 the situation will improve.

**Review by simon-mo — APPROVED** [review]
LGTM. Can code owner take a look at the `setup.py` change? 
@edoakes @ericl @richardliaw

**Review by simon-mo — CHANGES_REQUESTED** [review]

**Review by simon-mo — APPROVED** [review]

**Comment by carlogrisetti** [comment]
@mattip Forgive me the commit intrusion, but my last addition is why you were seeing `dashboard\dashboard.py` and `dashboard/agent.py` (with the forward slashes). They were just representing the commandline used to start the script, thus reflected the os-specific way of typing the path. Only it was not consistently specified in the creation side.
This way it should be os-agnostic and consistent throughout the code.

**Review by edoakes — APPROVED** [review]

**Comment by mattip** [comment]
Edited, sorry

**Comment by carlogrisetti** [comment]
Ok you get the results processed by the workers, and you don't get errors anymore, but you get no dashboard functionality. Is this right? Like... if you browse to http://127.0.0.1:8265 while the workers are running and the ray head is up, do you get anything or you get an empty response?
It's more than OK if the purpose of this PR was to resolve the errors, in that case I just misinterpreted things :)

**Comment by mattip** [comment]
Which wheel are you trying? When I build locally and add a `import pdb; pdb.st_trace()` to stop after `ray.init`, I can see the dashboard.

**Comment by pcmoritz** [comment]
@carlogrisetti I'm getting the same error as you, I created an issue here: https://github.com/ray-project/ray/issues/19480

**Pull request merged**
