### PR TITLE
Update documentation and autoscaler to find 0.4.0.

### PR DESCRIPTION
**Pull request by robertnishihara**
Note that we'll have to actually upload wheels before this works.

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
retest this please

**Comment by richardliaw** [comment]
@robertnishihara maybe this needs to be rebased off master..?

**Comment by robertnishihara** [comment]
Why? There's no conflict as far as I can tell.

**Comment by richardliaw** [comment]
oh just for the sake of getting jenkins tests to pass, although there is no
conflict

**Comment by richardliaw** [comment]
should we merge this (despite all tests failing)?

**Comment by robertnishihara** [comment]
I'll rebase.

**Pull request merged**
