### PR TITLE
[xray] Better error messaging when pulling from self.

### PR DESCRIPTION
**Pull request by elibol**
Complain more loudly when a node pulls from itself, and return an invalid status when this happens.

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
+1 LGTM

**Comment by pcmoritz** [comment]
@elibol Can you fix the linting error?

**Comment by elibol** [comment]
I checked this PR for linting errors and it appears to be fine. However, I am seeing linting errors on master.

**Review by stephanie-wang — COMMENTED** [review]
Looks good, but can you also add the checks in the node manager to only pull non-local objects? This happens in two places: when handling a `ray.get`, and in the `TaskDependencyManager` when pulling a task's dependency.

**Comment by elibol** [comment]
I added a check for `NodeManager`. It looks like `TaskDependencyManager` already has this check in place.

**Pull request merged**
