### PR TITLE
Raise major version limit for msgpack

### LINKED ISSUE #8464: Bump msgpack to 1.0.0 for Python
We've started bumping msgpack to 1.0.0 in some of our repos at our company. However, some of our repos use Ray, which doesn't support version 1.0.0 for msgpack. We're hoping that Ray could support msgpack 1.0.0 - it doesn't look like there are too many breaking changes, and it looks like both major versions 0 and 1 can be supported. Thanks!

### PR DESCRIPTION
**Pull request by alecbrick**
## Why are these changes needed?

`msgpack` has released major version 1, which we should allow in order to ensure that others using `msgpack>=1.0.0` can use `ray`. The only breaking change that affects this project is that the argument `strict_map_key` to `unpackb` has had its default value changed from `False` to `True`, in order to prevent hash DoS. We need to explicitly set this value to `False` in order to allow tuples and lists to be map keys.

## Related issue number

Closes #8464.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
@alecbrick Thanks for the contribution! Let's make sure it doesn't break any test first. Our CI is not super stable yet, so there could be some flakey tests. I re-ran them to see what's going to happen.

**Comment by rkooo567** [comment]
This has a constant test failures with serve. Would you mind merging the latest master and push it?

**Review by chaokunyang — APPROVED** [review]
thanks for the contribution, LGTM if ci pass

**Comment by alecbrick** [comment]
Sure - just merged from master, we'll see if it works!

**Comment by rkooo567** [comment]
@simon-mo Is there any good way to check if tests are running the msgpack version >= 1.0?

**Comment by simon-mo** [comment]
Not directly I guess. Might also need to modify this https://github.com/ray-project/ray/blob/master/ci/travis/install-dependencies.sh#L268

**Comment by rkooo567** [comment]
@alecbrick ! Thanks again for the contribution. I'd like to make sure 2 things. 

1. The CI is running the right version of msgpack for testing. Would you mind pinning the msgpack version in the CI configuration as Simon showed? (We will revert this when we merge the PR).
2. Seems like these 2 tests are failing at Linux. Would you mind running unit test on your local machine and make sure they succeed to run?
Screen Shot 2020-05-22 at 12 14 41 AM

Thank you!

**Comment by alecbrick** [comment]
@rkooo567 Thanks for taking a look! I've temporarily pinned msgpack to be greater than or equal to 1.0.0.

I was looking into the failed tests, and while I haven't tested them locally (I'm running a Mac, not Linux), I've noticed that these tests have been consistently failing on master due to an out of memory error.

**Comment by rkooo567** [comment]
@alecbrick Thanks for finding that out! You were right, and I will make a PR to fix this soon. Let's see the test result after running msgpack == 1.0!

**Comment by rkooo567** [comment]
@alecbrick You can ignore ASAN build failure for now.

I think all the linux test failures are unrelated to this PR, but can we wait a little bit until they are resolved?

**Comment by alecbrick** [comment]
Sure, sounds good to me!

**Comment by alecbrick** [comment]
Hi! Any updates on this?

**Comment by simon-mo** [comment]
Sorry for the delay. This PR looks good to merge. The CI version pin is totally fine.

**Comment by rkooo567** [comment]
@simon-mo We should unpin the msgpack version before we merge.

**Comment by simon-mo** [comment]
The version is installed as 
```
    pip install "msgpack>=1.0.0"
```
so it will always install the latest anyway.

**Pull request merged**
