### PR TITLE
Bump version number to 0.5.2.

### PR DESCRIPTION
**Pull request by robertnishihara**
Unfortunately, it looks like we need to do another minor release due to https://github.com/ray-project/ray/issues/2763.

### CODE REVIEW

**Review by atumanov — APPROVED** [review]
LGTM

**Comment by guoyuhong** [comment]
Shall we turn `glog` off for later version?

**Comment by atumanov** [comment]
I actually like having `glog` ON, it produces nicer stack traces. I don't think we need to turn it off, since we can always build the wheels on an older version of mac and/or find a more permanent solution (e.g., compiler flags, building static libraries, etc).

**Comment by guoyuhong** [comment]
@atumanov Thanks, Alexey. Is this published Version 0.5.2 built in MacOS 10.11?

**Comment by atumanov** [comment]
@guoyuhong , yes.

**Pull request merged**
