### PR TITLE
[Serve] [Docs] Trim Ray Serve's "Getting Started" Page

### LINKED ISSUE #27437: [serve][docs] Trim "Getting Started" section to core workflow
This section is currently too long. We should focus on the core CUJ only and split out more advanced functionality to user guides. Things to remove (and put in user guides instead):
- Scaling out
- Fine-grained resource allocation
- Porting FastAPI

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

Ray Serve's "Getting Started" page has a lot of content. This change removes the following sections:

* Scaling out
* Fine-grained resource allocation
* Porting FastAPI

Trimmed info from "Scaling out" and "Fine-grained resource allocation" is consolidated into the "Converting to a Ray Serve Deployment" section.

Link to updated "Getting Started" page: https://ray--27670.org.readthedocs.build/en/27670/serve/getting_started.html

## Related issue number

Closes #27437.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
     -  Doc tests are updated.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Review by architkulkarni — APPROVED** [review]

**Review by dmatrix — COMMENTED** [review]
I don't see the copy in `getting_started.md`. My first nit is use lower case in the enumerated list.

This tutorial will walk you through the process of deploying models with Ray Serve. It will show you how to:

- expose your models over HTTP using Ray Serve [deployments](https://ray--27670.org.readthedocs.build/en/27670/serve/managing-deployments.html#serve-managing-deployments-guide)
- scale your deployments to meet your workload’s requirements
- allocate resources like fractional GPUs and CPUs to your deployments
- compose multiple-model machine learning pipelines with Ray Serve [deployment graphs](https://ray--27670.org.readthedocs.build/en/27670/serve/deployment-graph/deployment-graph-e2e-tutorial.html#deployment-graph-e2e-tutorial)
- port your FastAPI applications to Ray Serve

**Review by dmatrix — APPROVED** [review]

**Comment by dmatrix** [comment]
There are couple if questions that come to the front. Anyone new reading this page quick start might takeaway, from the example demonstrated, that this is all about external pre-trained models and how to use them with or deploy them onto Ray Serve. What if they have questions such as:

- I have an existing scikit-model or xgboost model in pickle format, stored on local FS or cloud, how do I deploy it?
- I have an existing PyTorch or TF model in its native format on disk or cloud, where do I find info to deploy it onto Ray Serve?
- I have experimental models in a model store (MLflow or W & B) and I wish to extract them and run them on Ray Serve?

A reader would have to forage those nuggets either by searching or perusing examples and guides. 

Perhaps, have some section toward the end that may link to assets that show them or speak to those concerns.

**Comment by shrekris-anyscale** [comment]
> Anyone new reading this page quick start might takeaway, from the example demonstrated, that this is all about external pre-trained models and how to use them with or deploy them onto Ray Serve.

@dmatrix Good point– I added a snippet in the first section in the documentation saying:

> You can also follow along using your own models from any Python framework.

The page also has links to [documentation](https://docs.ray.io/en/master/serve/tutorials/serve-ml-models.html) about serving ML models from popular Python frameworks– once at the end of the `Model Example: Before Ray Serve` section and once at the very end in `Next Steps`. That should help address concerns that Serve only works for pre-trained models.

**Comment by edoakes** [comment]
@shrekris-anyscale one more lint failure, then LGTM to merge

https://buildkite.com/ray-project/ray-builders-pr/builds/42455#01828a00-5adb-45fc-94f2-7e0775be22c6/9184-9514

**Pull request merged**
