### PR TITLE
[Metrics] Make DeltaProducer thread detached

### LINKED ISSUE #13532: [Metrics] Custom metrics don't work after calling `ray.shutdown()` followed by `ray.init()`
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray master, Python 3.6, Mac OS
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```python
import ray
from ray.util.metrics import Count

print(ray.init())
ray.shutdown()

print(ray.init())
counter = Count("TEST_COUNTER", description="desc")                                                                                                
counter.record(1)
```

This metric never appears at `localhost:<metrics-export-port>`.  However, if you remove the initial `ray.init()` `ray.shutdown()`, it works.

Adding debug print statements shows that `Ray::Stats::Shutdown()` is correctly being called in `ray.shutdown()`, and `Ray::Stats::Init()` is being correctly being called in the second (and first) `ray.init()`, so I'm not sure what the problem is.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
This PR fixes a problem with Ray stats not being correctly cleaned up upon `ray.shutdown()`.  This PR resets the global variables `handlers_`and `views_` in `StatsExporter` upon shutdown.  For `DeltaProducer`, shutdown is skipped because the global singleton thread cannot be restarted after `ray.shutdown()` followed by `ray.init()`.

## Related issue number

Closes https://github.com/ray-project/ray/issues/13532.
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Please add a description to the PR. Let's also let @rkooo567 review as he wrote the original patch.

**Comment by rkooo567** [comment]
Qusetions;

1. Does this mean we'll share the harvest thread between job A and B? (ray.init() (job A) => ray.shutdown() => ray.init() (job B)). 
2. Also I am concerned that not terminating the harvest thread will cause weird issues like segfault on shutdown hook. If the harvest thread touches any other parts that are shut down before the process terminates, it can cause weird issues. 
3. Also, why can't we restart the thread? Isn't it just we kill all threads => we restart? What prevents us?

Also @ashione Please take a look!

**Comment by ashione** [comment]
> I have some questions;
> 
> 1. Does this mean we'll share the harvest thread between job A and B? (ray.init() (job A) => ray.shutdown() => ray.init() (job B)).
> 2. Also I am concerned that not terminating the harvest thread will cause weird issues like segfault on shutdown hook. If the harvest thread touches any other parts that are shut down before the process terminates, it can cause weird issues.
> 3. Also, why can't we restart the thread? Isn't it just we kill all threads => we restart? What prevents us?
> 
> Also @ashione Please take a look!

In my experience, we'd better to fix the above issues rather than just skip shutdown or make harvest thread as a detached thread.
@simon-mo Could you give us some clues about why these will happend.

**Comment by ashione** [comment]
Please hold on. I'll try to figure out why opencensus thread crashed before next weekend.

**Comment by simon-mo** [comment]
@ashione any update?

**Comment by zhongchun** [comment]
> @ashione any update?

I have encountered the same problem and am looking for a solution. We'd better restart the thread.

**Comment by ashione** [comment]
> @ashione any update?

@rkooo567 @simon-mo I add some unit tests in metric exporter client test, but no such failures? In that case, ray stats had been setup and shutdown twice.

**Comment by ashione** [comment]
> > @ashione any update?
> 
> @rkooo567 @simon-mo I add some unit tests in metric exporter client test, but no such failures? In that case, ray stats had been setup and shutdown twice.

https://github.com/ray-project/ray/pull/13708

**Comment by edoakes** [comment]
ping @simon-mo

**Comment by zhongchun** [comment]
> ping @simon-mo

We've tried to close `DeltaProducer` in #13708, but found some other problems. It may introduce new problems if we modify more codes in opencensus. So we suggest do not support reopen in driver.

**Pull request closed without merging**
