### PR TITLE
[rllib] Queue lib for python 2.7

### PR DESCRIPTION
**Pull request by alexbao**
## What do these changes do?
Update queue lib for python 2.7

@robertnishihara

### CODE REVIEW

**Comment by richardliaw** [comment]
Thanks for the patch! Instead, let’s use “from six.moves.queue import
Queue” - this should be backward compatible.

**Comment by alexbao** [comment]
Updated.

The test log is truncated, the test failure should not be related to the changes in the PR though @richardliaw

**Review by richardliaw — APPROVED** [review]
looks good, conditioned on tests passing. Thanks @alexbao!

**Comment by richardliaw** [comment]
tests failing unrelated

**Pull request merged**
