### PR TITLE
[autoscaler] Log ips and ids when terminating nodes, code structure

### LINKED ISSUE #18151: [Autoscaler] Log ids and ips of nodes being terminated by autoscaler.
### Describe your feature request

For questions, post on our Discussion page instead: https://discuss.ray.io/

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

This PR does the following
(1) Makes sure the autoscaler logs node ids and ips when terminating nodes. 
(2) Consolidate node termination logic.
(3) Adds some structure to `autoscaler._update` .

## Related issue number

Closes https://github.com/ray-project/ray/issues/18151

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
cc @rkooo567

**Comment by AmeerHajAli** [comment]
@sasha-s , @DmitriGekhtman , what is the status of this one?

**Comment by sasha-s** [comment]
> @sasha-s , @DmitriGekhtman , what is the status of this one?

I am reading it now

**Comment by AmeerHajAli** [comment]
> > @sasha-s , @DmitriGekhtman , what is the status of this one?
> 
> I am reading it now

any updates?

**Comment by DmitriGekhtman** [comment]
Added a couple of assignees in case someone has a second to look.
(This is not extremely important, TBH.)

**Comment by AmeerHajAli** [comment]
I think @sasha-s is in the best position to review this. @sasha-s , can you please review this one?

**Review by sasha-s — APPROVED** [review]
Sorry it took me long to read the code.
Looks good.

**Comment by DmitriGekhtman** [comment]
flaky mac unrelated, going to do a quick manual test to see that log messages look good..

**Comment by AmeerHajAli** [comment]
> flaky mac unrelated, going to do a quick manual test to see that log messages look good..

Thanks for manual testing!

**Pull request merged**
