### PR TITLE
[rllib] mark flaky rllib tests as softfail

### PR DESCRIPTION
**Pull request by aslonnie**
so that they won't be blocking merges.

### CODE REVIEW

**Comment by aslonnie** [comment]
or, we can also skip them by default in test tags or something.

**Comment by can-anyscale** [comment]
if: build.branch == master ?

BTW, I'll leave it for @sven1977 who is the owner of rllib to decide ;)

**Comment by aslonnie** [comment]
hmm.. seems a bit better now after test skipping on master branch?

**Comment by aslonnie** [comment]
ok.. will leave them there for now.. and see how things evolve.

**Pull request closed without merging**
