### PR TITLE
[tests] Blacklist failing win32 tests

### PR DESCRIPTION
**Pull request by ericl**
wip

### CODE REVIEW

**Review by wuisawesome — CHANGES_REQUESTED** [review]
Let's post the Latex source for your petition in case other grad students want to use it too :p

**Comment by edoakes** [comment]
I'm so confused

**Comment by wuisawesome** [comment]
More directly, we should delete `doc/source/images/petition.general (2).pdf` before merging.

**Comment by ericl** [comment]
Removed @wuisawesome

**Review by wuisawesome — APPROVED** [review]
We should probably create a P1 ticket to fix these

**Comment by ericl** [comment]
We don't have the resources to put effort on Windows now, it's fine to just maintain the status quo.

**Pull request merged**
