### PR TITLE
[sgd] Add benchmarks

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

Benchmarking code for SGD.

TODO: 
 - [x] Merge #7384.
 - WONTDO Add smoke-test of benchmarks to Jenkins.
 - [x] Surface results on the documentation?
 - [x] Add temporary warning about not using a DataLoader

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ConeyLiu** [comment]
It seems the data and pic not matching. https://github.com/ray-project/ray/tree/master/python/ray/util/sgd/torch/examples/benchmarks

**Comment by richardliaw** [comment]
Ah, good point... - let me fix that.

**Comment by richardliaw** [comment]
@ConeyLiu https://github.com/ray-project/ray/pull/7553

**Comment by ConeyLiu** [comment]
thanks a lot for the quickly fixes.

**Pull request merged**
