### PR TITLE
[tests] fix mock for test_cli

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

test_cli didn't run locally before.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Review by ijrsvt — APPROVED** [review]
Oh nice! Thanks!

**Comment by AmeerHajAli** [comment]
@richardliaw @wuisawesome @ijrsvt , with this change we do not really have a real use case that actually tests the automatic resource filling. Why it has to pass locally (why don't you setup AWS auth locally)? or at least why not make it mock locally but use actual AWS on travis?
We want this test to fail if boto3 API stopped working or some other cases that we did not think about.

**Comment by richardliaw** [comment]
This test suite is a test for CLI output, and the entire test suite
previously is filled with boto mocks/aws auth disabled (see test fixtures).

If I can’t run test cli locally, it is incredibly difficult to debug cli
issues. Thus, this PR restores this test suite to its original
functionality.

**Comment by AmeerHajAli** [comment]
But you can test it locally right? because you are can just setup AWS auth right?

**Pull request merged**
