### PR TITLE
Fix some flaky tests

### PR DESCRIPTION
**Pull request by raulchen**
## What do these changes do?

- remove `test_actors_and_task_resource_bookkeeping`, which isn't useful.
- `test_actor_broadcast` and `test_reconstruction_suppression`: reduce work load as they often run out of memory in CI.
- `test_resource_constraints` and `test_gpu_ids`: give more time buffer. 

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by robertnishihara** [comment]
Thanks @raulchen! Some questions:

1. Do you have any idea why `test_actors_and_task_resource_bookkeeping` is failing? For it to fail, it seems that there must be two consecutive calls to `time.monotonic()` that are reversed in order, but the whole point of `time.monotonic` is that that should be impossible.
2. How do you know `test_actor_broadcast` and `test_reconstruction_suppression` run out of memory? I know they hang, but was't sure why.

**Comment by raulchen** [comment]
@robertnishihara 

For `test_actors_and_task_resource_bookkeeping`, my guess is that `time.monotonic` isn't sync'ed across different processes. So it's possible that the start time of an actor is earlier than the end time of the previous actor. Because I saw this check failed: https://github.com/ray-project/ray/blob/master/python/ray/tests/test_actor.py#L1331

For the other two, because now we have `pip install psutil` in Travis, they raise `RayOutOfMemoryError`.

**Comment by robertnishihara** [comment]
Ok, I just looked at it again and I don't think the test makes sense. It only makes sense to compare the intervals from a given actor, so e.g.,

```python
    # First make sure that we do not have more actor methods running at a
    # time than we have CPUs.
    actors = [Foo.remote() for _ in range(4)]
    interval_ids_list = []
    for actor in actors:
        interval_ids_list.append(actor.get_interval.remote())
        interval_ids_list = [actor.get_interval.remote()] + [actor.sleep.remote() for _ in range(4)]

    # Make sure that the intervals don't overlap.
    for interval_ids in interval_ids_list:
        intervals = ray.get(interval_ids)
        intervals.sort(key=lambda x: x[0])
        for interval1, interval2 in zip(intervals[:-1], intervals[1:]):
            assert interval1[0] < interval1[1]
            assert interval1[1] < interval2[0]
            assert interval2[0] < interval2[1]
```

Does that sound right? Then we can get rid of the sleep after the timing statement.

**Comment by raulchen** [comment]
I also noticed that it doesn't make sense to compare results of `time.monotic` from different processes. 

But I'm still confused about the purpose of this test. Do you want to assert that the `sleep` task won't start before the constructor ends?

**Comment by robertnishihara** [comment]
I guess the test sort of tests that the actor executes one method at a time and not multiple concurrently. However I don't think it's an important test. I'd be ok with removing it.

**Comment by raulchen** [comment]
Ok, let's remove it.

**Review by robertnishihara — APPROVED** [review]

**Review by guoyuhong — APPROVED** [review]
+1

**Comment by raulchen** [comment]
@robertnishihara `test_resource_constraints` is still unstable https://travis-ci.com/ray-project/ray/jobs/189774939. Maybe we shouldn't depend on time.

**Comment by robertnishihara** [comment]
@raulchen yes I agree. This seems to be the source of a lot of our problems.

**Pull request merged**
