### PR TITLE
Remove quotes from commandline parameters

### PR DESCRIPTION
**Pull request by carlogrisetti**
Quotes should not be typed in `ray start --address=ipaddr:port --redis-password=passw`
Current ray start help text shows to use `ray start --address='ipaddr:port' --redis-password='passw'`

### CODE REVIEW

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
@carlogrisetti 
Thanks for the fix and apologies for missing this earlier. Would you mind merging master? (It's good to re-run the tests just for good measure.)

**Comment by carlogrisetti** [comment]
Merged it is, although I did not change any code, just descriptions :)

**Comment by carlogrisetti** [comment]
Hell I passed almost an hour trying to find out why tests were failing, only to see that I half-merged from master.
Re-running now, after a full (and hopefully correct) merge.

**Comment by DmitriGekhtman** [comment]
Looks like `test_cli.py::test_ray_start` has to be modified to match the new output: 
https://buildkite.com/ray-project/ray-builders-pr/builds/18252#6a3c822a-ec32-4196-a99e-3673c6606024/1740-2041

**Comment by DmitriGekhtman** [comment]
Specifically, quotes need to be taken out of this line:
https://github.com/carlogrisetti/ray/blob/013f31f31f775aec99093cdc11679957c71133c0/python/ray/tests/test_cli_patterns/test_ray_start.txt#L9

**Comment by carlogrisetti** [comment]
Thanks for the tip. little rusty on tests :)

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
