### PR TITLE
Test PingPort

### PR DESCRIPTION
**Pull request by dHannasch**
This is built atop https://github.com/ray-project/ray/pull/12917. Look there first. I'm getting a bit ahead of myself here; the test for `PingPort()` needs to be based on the test for `Connect()`, so we need to sort out how to test `Connect()` first.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]
Looks good to me!

**Comment by richardliaw** [comment]
@dHannasch can you ping me when tests pass?

**Comment by dHannasch** [comment]
@richardliaw It's getting some failures on other tests with `OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 8265): address already in use`, but I would think if anything related to this could cause that it would have been https://github.com/ray-project/ray/commit/d747071dd9e883bd4ceefe80d0344f287630c4e5, which didn't, so I think it's a coincidence.

**Comment by richardliaw** [comment]
OK, let's merge and then monitor https://flakey-tests.ray.io/ closely for any testing irregularities.

**Comment by dHannasch** [comment]
> OK, let's merge and then monitor https://flakey-tests.ray.io/ closely for any testing irregularities.

Oh, neat. So if something went wrong, it would show up on https://flakey-tests.ray.io/ as a row of all green with then red on the far right?

**Pull request merged**
