### PR TITLE
Revert "Add support for Python 3.9 (#12613)"

### PR DESCRIPTION
**Pull request by edoakes**
This reverts commit 208cde8d9ba4948712b689d8ae76e799876e81d4.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]
😢

**Comment by edoakes** [comment]
@wuisawesome going to wait for build to complete to make sure this fixes the issue, will merge in the morning.

**Comment by wuisawesome** [comment]
Let's see if #15006 is ready before merging this in the morning?

**Comment by edoakes** [comment]
@wuisawesome [wheel build](https://travis-ci.com/github/ray-project/ray/jobs/494706390) was still failing over yonder. Merging this one.

**Pull request merged**
