### PR TITLE
[DataFrame] Adds axis utility methods

### PR DESCRIPTION
**Pull request by kunalgosar**
This adds `_get_axis_number`, `_get_axis_name` and `_get_axis`.

Rebased on #2018.

### CODE REVIEW

**Comment by kunalgosar** [comment]
Jenkins, retest this please

**Comment by devin-petersohn** [comment]
This is low priority and probably won't make it into the release. It's nice to have, but there are too many higher priority problems to get resolved.

**Comment by devin-petersohn** [comment]
@kunalgosar is this okay to close?

**Comment by kunalgosar** [comment]
Sure, I’m fine with closing this

**Pull request closed without merging**
