### PR TITLE
[dashboard] Disable dashboard by default on windows

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

https://github.com/ray-project/ray/issues/14026

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@wuisawesome ultimately your choice whether to cherry pick this into the release or not, but I think it's a good idea. We should merge it into master anyways.

**Review by wuisawesome — APPROVED** [review]

**Comment by wuisawesome** [comment]
I'm in favor of picking this. It's pretty unusable with the errors, and new users won't think to disable the dashboard.

**Comment by wuisawesome** [comment]
rip, looks like we're asserting the dashboard log exists in some tests.

**Comment by edoakes** [comment]
Pushed a fix

**Comment by wuisawesome** [comment]
I guess we should just close this and come up with a real solution before the next release?

**Pull request closed without merging**
