### PR TITLE
Remove deprecated ray.services package

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Deprecation warning was for Ray 1.4.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Review by richardliaw — APPROVED** [review]

**Comment by ericl** [comment]
LINT error

**Comment by edoakes** [comment]
This is blocked on a change in xgboost_ray:
https://github.com/ray-project/xgboost_ray/pull/154

cc @richardliaw @krfricke

**Comment by edoakes** [comment]
@krfricke will I need to update anything here to pick up the updated xgboost_ray code or does it always pull master?

**Comment by krfricke** [comment]
Hm, currently it installs `xgboost==0.1.2` in `python/requirements/tune/requirements_upstream.txt`. I can prepare a new XGBoost release (which will be `xgboost==0.1.3`) so you can update that dependency in this PR.

I'll ping you once this done (probably tomorrow morning European time)

**Comment by edoakes** [comment]
Sounds good, thank you @krfricke!

**Comment by krfricke** [comment]
xgboost_ray 0.1.3 has been released, I'd suggest merging master after https://github.com/ray-project/ray/pull/18632 has been merged

**Comment by krfricke** [comment]
You should be able to merge upstream/master into this PR now to make tests work

**Comment by krfricke** [comment]
I filed a PR to resolve the modin error here: https://github.com/modin-project/modin/pull/3427
But it will probably need another modin release until it's reflected in our CI (or we use modin master instead)

**Comment by edoakes** [comment]
https://github.com/modin-project/modin/issues/3426

**Comment by edoakes** [comment]
https://github.com/modin-project/modin/pull/3427

**Comment by edoakes** [comment]
@krfricke looks like the above PR was merged, do we need to wait for an upstream release?

**Comment by krfricke** [comment]
Yes, either that or we switch to latest master. If we can wait for a bit, upstream release would be better I think so users don't run into issues if they use ray latest master with modin latest release.

**Comment by edoakes** [comment]
Sounds good let's leave it open for awhile until they release...

**Comment by edoakes** [comment]
@krfricke I *think* modin [released](https://github.com/modin-project/modin/commit/c3b8d7e4863615f99c8a1c6b7316e680daaa4393), and I *think* I updated the right places, PTAL?

**Comment by krfricke** [comment]
Locations look good imo, but release has not landed, yet:

https://pypi.org/project/modin/#history
https://github.com/modin-project/modin/releases

(but seems this is 2 hours old, so probably on the way there...)

**Comment by edoakes** [comment]
Thanks @krfricke, will try again tomorrow :)

**Review by krfricke — APPROVED** [review]
I pushed a fix for the two failing tune tests, everything should be green after that

**Pull request merged**
