### PR TITLE
Ship plasma store with Ray

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

This PR copies files from the arrow/plasma upstream, and windows patches are applied to them.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by mehrdadn** [comment]
Can I ask what is the motivation for this? And also, what is the eventual goal for the Plasma store that's inside Arrow? Will it evolve in parallel with this one, or is it planned to be removed? (CC @pcmoritz)

If Arrow's copy isn't getting removed once this PR is merged, I feel like we should consider whether it might make sense to keep the patches separate, so that they're easier to maintain, since it'll let us just pull the changes from upstream. Otherwise the code will diverge from upstream and it'll become difficult to reconcile changes between the two.

(For what it's worth, I was hoping to upstream some of the patches, but only after I was finished with the initial part of the Windows port, so that I could e.g. be sure they wouldn't need further modifications.)

**Comment by suquark** [comment]
@mehrdadn I think the final goal is to disentangle with arrow. With this PR, we have shipped the plasma store with Ray, and windows patches are applied.

**Review by edoakes — COMMENTED** [review]
LGTM but let's wait for @pcmoritz to review this.

**Review by pcmoritz — APPROVED** [review]
The code and build system looks good, there are some tests that seem to be failing, @edoakes are any of them related to this PR or are they already happening on master?

Great job with the PR!

**Comment by edoakes** [comment]
Failures don't look relevant to me. @suquark could you merge master and push again to be sure and then we can merge?

**Comment by winningsix** [comment]
A quick question: For the future, how will we maintain the changes in Arrow community?

**Comment by ConeyLiu** [comment]
Same question here. What is the purpose of doing this? Will it be maintained separately?

**Comment by ConeyLiu** [comment]
@suquark thanks for the answer.

**Comment by winningsix** [comment]
@suquark  I am thinking it's not a good practice to have a self-maintained component. 
1. Plasma is a very important component to Ray.
2. Arrow Plasma is not used by many other components.
Code diverge is not good for both communities.

I would like to bring this into further discussion whether we can maintain a same code base for Plasma.

Like digest compute, it's required for general object store. But It's under Ray or our internal use case (we use Plasma as Spark data source), we can disable it for better performance. I think the Arrow version is maintainable by introducing a new configuration for that. We did have a plan for that.

For API changes, that could be a problem. In fact, we introduce a new set of async API based on your boost change in Arrow. We're thinking introducing a new client protocol to support API backward compatibility.

Any other cases not covered we need to address?

cc @jikunshang

**Comment by suquark** [comment]
@winningsix thanks for your response! Somehow I didn't receive notifications from the closed PR. maybe we can move our conversation to Ray Slack if it is convenient for you, and we can also discuss with other ray maintainers.

I am sure that Ray will still contain a different plasma store in the future (and the final goal is total integrating Plasma into Ray as a new distributed store). But we can still contribute to the Arrow Plasma Store upstream based on our experience of Plasma Store and share as much components as possible.

**Comment by winningsix** [comment]
@suquark Yes, let's move to Slack for boarder discussion. Hope we can develop a good practice balancing keeping the backward compatibility and new features.

**Pull request merged**
