### PR TITLE
[runtime_env] Print correct default  for expiration_s environment variable

### PR DESCRIPTION
**Pull request by architkulkarni**
Signed-off-by: Archit Kulkarni <architkulkarni@users.noreply.github.com>

## Why are these changes needed?
The default value of the runtime_env working_dir temporary reference expiration environment variable was changed in https://github.com/ray-project/ray/pull/29070 but the default value printed to the terminal was hard-coded and out of date. This PR updates the value printed in the message.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]
OOC is this easy to test?

**Comment by architkulkarni** [comment]
@wuisawesome pretty easy thankfully! Added a test with an induced failure

**Comment by architkulkarni** [comment]
Rllib and workflow tests flaky on master and unrelated
Linkcheck failures unrelated:


(ray-air/examples/torch_incremental_learning: line 160008) broken    https://docs.ray.io/en/master/ray-air/package-ref.html#module-ray.air.session - 404 Client Error: Not Found for url: https://docs.ray.io/en/master/ray-air/package-ref.html
--
  | (ray-air/examples/torch_incremental_learning: line 160008) broken    https://docs.ray.io/en/master/train/api.html#training-function-utilities - 404 Client Error: Not Found for url: https://docs.ray.io/en/master/train/api.html
  | (ray-contribute/docs: line 10113) broken    https://github.com/ray-project/ray/blob/master/doc/source/tune/api_docs/overview.rst - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/doc/source/tune/api_docs/overview.rst
  | (ray-contribute/docs: line 10144) broken    https://github.com/ray-project/ray/blob/master/doc/source/tune/api_docs/integration.rst - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/doc/source/tune/api_docs/integration.rst
  | (ray-overview/index: line   18) broken    https://www.datanami.com/2018/02/01/rays-new-library-targets-high-speed-reinforcement-learning/ - 403 Client Error: Forbidden for url: https://www.datanami.com/2018/02/01/rays-new-library-targets-high-speed-reinforcement-learning/
  | (ray-overview/index: line    9) broken    https://www.datanami.com/2019/11/05/why-every-python-developer-will-love-ray/ - 403 Client Error: Forbidden for url: https://www.datanami.com/2019/11/05/why-every-python-developer-will-love-ray/

**Comment by architkulkarni** [comment]
(cc @gvspraveen )

**Pull request merged**
