### PR TITLE
Bump pettingzoo==1.15.0 supersuit==3.3.3

### PR DESCRIPTION
**Pull request by empiricca**
## Why are these changes needed?
Bump pettingzoo and supersuit
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by gjoliver** [comment]
any reason you want to bump these in the default requirements and our unit tests?
we probably should have official policy about when to drop support of older versions of libraries.
just curious to know more about the background.
thanks.

**Comment by jkterry1** [comment]
Hey, I'm the maintainer of PettingZoo (and Gym and SuperSuit). The story behind these is that every new PettingZoo version we release introduces minor breaking changes each release, in this case just new environment versions. Following every release we've been submitting small PRs to use the newest version of PettingZoo etc. Older versions of PettingZoo and Gym have always been dropped immediately in favor of the newer one when they come out due to inherent breaking changes with each release caused by bumps to environment versions, so I'm not sure what policy about dropping old versions you'd like to propose?

**Comment by gjoliver** [comment]
> Hey, I'm the maintainer of PettingZoo (and Gym and SuperSuit). The story behind these is that every new PettingZoo version we release introduces minor breaking changes each release, in this case just new environment versions. Following every release we've been submitting small PRs to use the newest version of PettingZoo etc. Older versions of PettingZoo and Gym have always been dropped immediately in favor of the newer one when they come out due to inherent breaking changes with each release caused by bumps to environment versions, so I'm not sure what policy about dropping old versions you'd like to propose?

is there any deprecation period?

**Comment by jkterry1** [comment]
I don't think I understand your question? Whenever a new version is released people gradually update to it, like for any Python package. In some cases there are (usually fairly minor) breaking changes and in some cases there are none.

**Comment by jkterry1** [comment]
I mean the solution to your concern is to specify exact the version and manually update it after new releases, which is what this PR does?

**Comment by gjoliver** [comment]
> I mean the solution to your concern is to specify exact the version and manually update it after new releases, which is what this PR does?

agreed. new release will fix things. but it takes time for things to get released right?
anyways, let me ping @sven1977 to merge this PR.

**Review by gjoliver — APPROVED** [review]

**Review by sven1977 — APPROVED** [review]
Looks great! Thanks for the upgrade @dsctt !

**Pull request merged**
