### PR TITLE
[ADAG] Fix microbenchmark_unstable

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

In `ray_experimental_perf.py`, some DAGs call `experimental_compile` twice. Therefore, the first compiled node will become a leaf node. For example,

```python
a = DAGActor.remote()
with InputNode() as inp:
    dag = a.echo.bind(inp)
...
compiled_dag_1 = dag.experimental_compile()
# driver -> a.echo -> compiled_dag_1 (output)
...
compiled_dag.teardown()
...
compiled_dag_2 = dag.experimental_compile(enable_asyncio=True)
# driver -> a.echo -> compiled_dag_1
#                  |
#                  |-> compiled_dag_2 (output)
```

In this case, `a.echo` has two downstream nodes, `compiled_dag_1` and `compiled_dag_2`. However, it is not supported for a DAG node to be read by both output nodes and non-output nodes simultaneously.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
@kevin85421 

I think this is a regression actually because the semantic we expect that we want to recompile dag as long as teardown is called. But I am okay with the current fix for a short term workaround. Can you create an issue? 

also, before merging, did you verify the microbenhmark passes? If not, can you run a releas test in this branch?

**Comment by rkooo567** [comment]
> What is the use case for recompiling the same DAG?

Some use cases I can think of is when you want to handle fault tolerance. we teardown existing dag and create a new one with smaller set of actors.

regardless, I think the current behavior is buggy. If we don't want to allow recreating dag, we should at least raise an exception

**Comment by kevin85421** [comment]
> Some use cases I can think of is when you want to handle fault tolerance. we teardown existing dag and create a new one with smaller set of actors.

Discuss offline: let's raise an exception.

> regardless, I think the current behavior is buggy. If we don't want to allow recreating dag, we should at least raise an exception

Agree

**Comment by kevin85421** [comment]
Open an issue: https://github.com/ray-project/ray/issues/47408

**Pull request merged**
