### PR TITLE
[Core]Chaos testing nightly

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

This adds nightly chaos tests for basic sanity check. Test test basically runs a task/actor based workload that should successfully complete. During the run, we invoke node failures every X second. The goal is that at the end of the test, it should have a steady, consistent state that's expected. Placement group tests were not added yet. 

The PR also removes the previous thread based conftest and use the same `test_util.NodeKiller` implementation. So we are using the same implementation for both nightly test & Ci tests.

Lastly, this PR adds Dask-on-Ray with reconstruction on, but without actual node failure. We will add node failure scenario once reconstruction is confirmed to be stable cc @stephanie-wang lmk when I should do this. 

## Related issue number

https://github.com/ray-project/ray/issues/17383

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
can you add a link to the actual chaos run?
this is exciting btw!

**Comment by stephanie-wang** [comment]
I think it would be okay to try Dask-on-Ray with node failures! If this turns out to be unstable, we can then flag it off.

**Comment by rkooo567** [comment]
@scv119 

Task retry; 
https://beta.anyscale.com/o/anyscale-internal/projects/prj_3qqS82y6R2UUTWG4oHeMpF/clusters/ses_JJxGYRRf6SrGAnNPiCRJYwhZ?command-history-section=command_history

Actor retry; 
https://beta.anyscale.com/o/anyscale-internal/projects/prj_3qqS82y6R2UUTWG4oHeMpF/clusters/ses_yxpQ7PfDwrs3EbHa5cv3TjED?command-history-section=command_history (failed because I terminated early because I set multiplier too high, and it was too slow)

**Comment by rkooo567** [comment]
@stephanie-wang Can I make one more PR to do that after we merge this? The dev cycle is quite slow for this work (running tests), and I have other task I'd like to focus on right now (but I want to start running basic tests asap!)

**Comment by stephanie-wang** [comment]
Hmm so it looks like there are a few new tests added, but have they all been manually tested? Ideally we shouldn't merge the new tests unless we know they pass consistently (we can just skip Dask-on-Ray for now and add it later).

Also, I originally thought this would be more like a fixture where you could parametrize existing test yamls to run them with node-killing. Could we do that instead of adding all new tests in the first pass?

**Comment by rkooo567** [comment]
@stephanie-wang 

> Hmm so it looks like there are a few new tests added, but have they all been manually tested? Ideally we shouldn't merge the new tests unless we know they pass consistently (we can just skip Dask-on-Ray for now and add it later).

I ran them and saw they passed (actually they are the same test in the CI tests, but in a larger scale). But to check if it consistently passes,  we can just use our staging mode. https://docs.google.com/document/d/11OXVfpuGLMdUI1W8LxcNgXfCRtZ509Rzr1DtusmS968/edit#heading=h.5spf1gjl6sja (which this PR is doing).

> Also, I originally thought this would be more like a fixture where you could parametrize existing test yamls to run them with node-killing. Could we do that instead of adding all new tests in the first pass?

Sounds good. It is a great idea! I think since we are injecting failures in the application layer, the best way to achieve this is to just make a prepare_script to launch the detached actor that kills nodes. (Also, in this way, we can avoid adding new code to e2e.py now. It is not tested at all, so we should avoid adding code there for a while... this will be better at the end of the quarter since Kai is planning to refactor the code). 

Since dev cycle for this PR is pretty slow, and I'd like to see if the newly added tests are consistently working without weird issues ASAP, why don't we merge the PR with tests first, and then I make a follow up PR to

- Support fixture instead of adding code in the beg of the file. 
- Dask on Ray with node failures

? Do you think this sounds reasonable?

**Review by stephanie-wang — APPROVED** [review]

**Comment by rkooo567** [comment]
Tests failure seems unrelated

**Comment by rkooo567** [comment]
Follow ups; 

```
Support fixture instead of adding code in the beg of the file.
Dask on Ray with node failures
```

**Pull request merged**
