### PR TITLE
[Core] Logging config cleanup

### LINKED ISSUE #30005: [RFC] Logging configuration and message formats
### Description

In the interest of improving both the user and development experiences with Ray, and after having a discussion with @xwjiang2010, I'm opening this issue to solicit community input about Ray's logging capabilities.

### Logging configuration

Logging in Ray is currently set up in multiple places. Some modules set custom logging configurations with calls to `basicConfig`:

basicConfig

This makes sense to do inside separate processes because each process has its own root logger, although there are instances where `basicConfig` is called inside the main process.

From the [python docs](https://docs.python.org/3/library/logging.html#logging.basicConfig), `basicConfig`

> does nothing if the root logger already has handlers configured, unless the keyword argument force is set to True.

In principle I think this means that only the first call to `basicConfig` modifies the root logger, and all other calls have no effect. Additionally, modifying the root logger may also not be intended because Ray's main logger is set up with the name `ray` [here](https://github.com/ray-project/ray/blob/master/python/ray/_private/ray_logging.py#L14).

Currently the code to set up the main logger, `ray`, also appears in a number of different places in order to capture all the different entry points for ray execution, e.g. calling `ray.init()`, using the CLI to run `ray start`, etc:

setup_logger

### Log output

Currently for a number of different Ray use cases, a lot of output can be generated, which sometimes makes it hard to identify important information.

current_logging

In this example, there are logging statements from multiple Ray libraries but it's hard to tell at a glance which ones they are. In part this is due to the training results being interspersed throughout, but also because the logging formatter is different for the different Ray libraries, meaning that logging messages from different parts of the code may have different message formats. As part of this effort, I'm hoping we can improve the clarity of these logging statements so that they are more visible when they are shown to the user.

### Log Rotation

Another common requested feature is to allow for log rotation, particularly with respect to progress statements; see #28268.

## Proposal

One option is to create a logger for each Ray library (tune, train, air, etc), and convert existing logging calls to use the logger from the appropriate library. Logging configuration would be done in the `__init__.py` for each library, helping to make configuration more uniform and transparent across different modules, and making it easier to address the issue of log rotation.

To improve log message clarity, we can append the name of the Ray library to the logging statement to make it clear what part of the code the log message is being emitted from, and use similar message formats across multiple modules. For example:

```
[2022-11-02 13:19:32][Ray Core] INFO     Started a local Ray instance. View the dashboard at 127.0.0.1:8265        worker.py:1527
[2022-11-03 10:24:25][Ray Tune]	INFO     Total run time: 5.89 seconds (5.79 seconds for the tuning loop).          tune.py:787
```

The time, Ray library issuing the log statement, logging level, and location in the source where the message is emitted are clearly stated, and different Ray libraries have similar message formats.

**Note**: This RFC does not include any changes to remote actor logs, only driver side logging structure. Remote actor logs are for the most part [handled on the user side](https://docs.ray.io/en/latest/ray-observability/ray-logging.html#how-to-set-up-loggers), and so are outside the scope of this proposal.

I'd also be interested in input from the Ray community, so leave a comment if you have any feedback about anything discussed here. @xwjiang2010 Let me know if I missed anything here!

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR cleans up some legacy logging configuration code in various places, helping to consolidate logging to `ray._private.log`. The main changes are

* `ray.experimental.raysort.logging_utils` has been removed. There was only one function in there, and it called `logging.basicConfig` to configure the root logger. This was being called in various places, and each instance where it was being called has been removed. Logging configuration is now done at module initialization time (when `import ray` is executed). Additionally, all log messages in `ray.experimental.raysort` are now logged to the `__name__` logger for each file. 
This effect of this is that log messages are now handled by the `ray` logger. The root logger remains untouched, [following established python logging practices](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library).

* `ray.rllib` logging configuration has also been changed similarly - many places where `logging.basicConfig` was called have been removed, and we now use the existing ray logging configuration. The existing ray logging configuration already has the log level for the `ray.rllib` logger set to `logging.WARN`, so there shouldn't be much difference in logging behavior from the user perspective.

## Related issue number

Partially addresses #30005.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
awesome! excited to review this PR. For this one, I may wait until the first PR is merged. since it is pretty big

**Comment by peytondmurray** [comment]
@rkooo567 Refreshing this issue. Could you take a look now that https://github.com/ray-project/ray/pull/34182 is merged?

**Review by aslonnie — COMMENTED** [review]
maybe split it into smaller ones based on codeowners?

**Comment by peytondmurray** [comment]
:point_up: I like this idea, it'll reduce the difficulty in getting this merged. I'll break this into two, one that cleans up `rllib` and another that handles `raysort`. Thanks for the advice!

**Pull request closed without merging**
