### PR TITLE
[core] fix memory monitor test flakiness 

### PR DESCRIPTION
**Pull request by clarng**
## Why are these changes needed?

Fix flakiness in the test cases
- don't reuse condition var / mutex across test cases
- use alphanumeric file names

## Related issue number

https://github.com/ray-project/ray/issues/29405

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

run this couple hundred times to repro the failure:
bazel test //:memory_monitor_test --config=asan --sandbox_debug  --test_output=all --cache_test_results=no --build_tests_only --runs_per_test=100

before this PR it fails 10-20% of the time

### CODE REVIEW

**Comment by rkooo567** [comment]
//:memory_monitor_test                                                   FAILED in 3 out of 3 in 1.4s

Seems like it is failing now!

**Comment by clarng** [comment]
> //:memory_monitor_test FAILED in 3 out of 3 in 1.4s
> 
> Seems like it is failing now!

seems to pass now 

https://buildkite.com/ray-project/oss-ci-build-pr/builds/2700#0183f4a8-ba1e-4b7f-87b9-57ad158eda53

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Running mac tests now...

**Comment by clarng** [comment]
cc @scv119  

blocked on mac test which never ran

**Pull request merged**
