### PR TITLE
[core][state] Efficient get/list actors with filters on some high-cardinality fields

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
This improves the state API for listing/getting actors: if filtering by id/state/job, filtering is pushed down to the source (GCS). 

Other state API resources will be implemented in a similar way (e.g. tasks/workers). 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
I am planning to do similar things for tasks + workers + objects, and plan to work on other issues before optimizing for other resources, which usually has a lower number?

**Review by rkooo567 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
We should probably remove show_dead_jobs option

**Comment by rkooo567** [comment]
cc @scv119 for the protobuf approval

**Comment by rickyyx** [comment]
> We should probably remove show_dead_jobs option

Here: https://github.com/ray-project/ray/pull/34415

**Review by scv119 — APPROVED** [review]

**Pull request merged**
