### PR TITLE
Revert "Revert "Add ability to specify worker and driver ports (#7833…

### PR DESCRIPTION
**Pull request by edoakes**
This reverts commit 90ef585fd550625c319a171ae298bb645369107d.

## Why are these changes needed?

Adds the ability to specify a port range for workers and drivers connecting to a cluster started via `ray start`. It would be ideal to default this port range, but this has caused an endless battle with CI due to port collisions. There are users who need this, so merging without a default for now.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@edoakes Should this be reverted for the next releasse?

**Comment by edoakes** [comment]
@rkooo567 no. This is a "revert revert" :)

**Comment by rkooo567** [comment]
@edoakes This could be a quiet important features for many users. Do you think there's any way we can merge this by tomorrow?

**Comment by edoakes** [comment]
Note: most of the LoC changed here are due to splitting test_basic into three tests: test_basic, test_basic_2, test_serialization

**Pull request merged**
