### PR TITLE
Revert "[api] Second round of 1.0 API changes: exceptions, num_return…

### PR DESCRIPTION
**Pull request by rkooo567**
Seems like this commit breaks all tests. https://github.com/ray-project/ray/runs/1044158725

…_vals (#10377)"

This reverts commit 2a204260a85b832c8bf6cfcbfaae1dc786e2a0d8.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Ah probably a bad conflict

**Comment by ericl** [comment]
It might be easier just to fix forward btw

**Comment by rkooo567** [comment]
@ericl Please go ahead if we can push the easy fix!

**Comment by rkooo567** [comment]
I just thoguth since it is Fri, it might be better merging this now cuz I assume you'd like to take a break)

**Comment by ericl** [comment]
Ah you can try fixing if you want, it's probably some trivial thing.

**Comment by rkooo567** [comment]
@ericl Yeah I think it is just some tests used num_return_vals instead of num_returns. I might not have time rn, so I will probably spend some time this weekends (and merge this for now)!

**Comment by ericl** [comment]
@rkooo567 https://github.com/ray-project/ray/pull/10418/files should do it

**Pull request closed without merging**
