### PR TITLE
Add __init__.py to fix ModuleNotFoundError for ray.tests.

### LINKED ISSUE #11535: ray.init(address='auto') crashes *with* pytest
### What is the problem?
Ray is successfully started on the head with
```
$ ~/anaconda3/envs/38env/bin/ray start --head --port=6379
```
on on another node with
```
$ ~/anaconda3/envs/38env/bin/ray start --address=XYZ --redis-password=XYZ
```
When `ray.init(address='auto')` is run on that second node, if https://github.com/ray-project/ray/issues/11530 has been resolved, the terminal is immediately hit with an avalanche of
```
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 319, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 309, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 122, in run
(pid=raylet)     modules = self._load_modules()
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 76, in _load_modules
(pid=raylet)     agent_cls_list = dashboard_utils.get_all_modules(
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 205, in get_all_modules
(pid=raylet)     importlib.import_module(name)
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/importlib/__init__.py", line 127, in import_module
(pid=raylet)     return _bootstrap._gcd_import(name[level:], package, level)
(pid=raylet)   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
(pid=raylet)   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
(pid=raylet)   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
(pid=raylet)   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
(pid=raylet)   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
(pid=raylet)   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/modules/log/test_log.py", line 12, in <module>
(pid=raylet)     from ray.new_dashboard.tests.conftest import *  # noqa
(pid=raylet) ModuleNotFoundError: No module named 'ray.new_dashboard.tests'
(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 319, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 309, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 122, in run
(pid=raylet)     modules = self._load_modules()
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 76, in _load_modules
(pid=raylet)     agent_cls_list = dashboard_utils.get_all_modules(
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 205, in get_all_modules
(pid=raylet)     importlib.import_module(name)
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/importlib/__init__.py", line 127, in import_module
(pid=raylet)     return _bootstrap._gcd_import(name[level:], package, level)
(pid=raylet)   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
(pid=raylet)   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
(pid=raylet)   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
(pid=raylet)   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
(pid=raylet)   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
(pid=raylet)   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
(pid=raylet)   File "/home/david/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard/modules/log/test_log.py", line 12, in <module>
(pid=raylet)     from ray.new_dashboard.tests.conftest import *  # noqa
(pid=raylet) ModuleNotFoundError: No module named 'ray.new_dashboard.tests'
```
If *that* is fixed (or "fixed", see below), the same thing happens with `ModuleNotFoundError: No module named 'ray.tests'`.
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray is installed with:
```
$ ~/anaconda3/bin/conda create --name 38env python=3.8
$ ~/anaconda3/envs/38env/pip install --upgrade https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp38-cp38-manylinux1_x86_64.whl
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
ray.init(address='auto')
```

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

Fixing this is not as simple as fixing https://github.com/ray-project/ray/issues/11530. Leaving aside whatever's going on with new_dashboard, `ModuleNotFoundError: No module named 'ray.tests'` happens because ray.tests is in fact left out of the installation, as you can see by checking `site-packages/ray`.

As a manual hack, I restored the missing subpackages by directly copying them from the git repository:
```
~/anaconda/envs/38env/lib/python3.8/site-packages/ray$ cp -r /tmp/ray/python/ray/tests .
~/anaconda/envs/38env/lib/python3.8/site-packages/ray/new_dashboard$ cp -r /tmp/ray/dashboard/tests/ .
```
With those manually copied in, Ray was able to start and run just fine.

For a real fix, the obvious solution is to add an `__init__.py` to `ray.tests`. That will (I think?) cause it to be included. (Though I haven't been able to understand your wheel-building scripts all that well.) It looks like that would also work for 'ray.new_dashboard.tests'.

### PR DESCRIPTION
**Pull request by dHannasch**
## Why are these changes needed?

`ray.init(address='auto')` crashes with a ModuleNotFoundError. If that is fixed, it crashes with a different ModuleNotFoundError. This restores the missing modules.
## Related issue number
Closes https://github.com/ray-project/ray/issues/11535.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Actually, that test modules weren't supposed to be included in the wheel. I think we mistakenly merged a PR that caused this, but we should probably solve the problem with a different approach. cc @mfitton We merged the PR that reverted this issue right?

**Comment by mfitton** [comment]
@rkooo567 Yeah, this is an issue from that PR, and we should not be putting wheels in the release.
@dHannasch I'm not sure if you saw my reply in the issue you opened, but the problem we have currently is not this error, but rather that we have not been able to get a new wheel out since that error was released due to an issue with the Linux wheel build.

**Comment by dHannasch** [comment]
@mfitton I did see https://github.com/ray-project/ray/issues/11535#issuecomment-713806953, if that's what you're referring to, and I replied to it. It's just that this PR was opened prior to your comment.
Like I said in https://github.com/ray-project/ray/issues/11535#issuecomment-713819715, I hadn't seen that https://github.com/ray-project/ray/pull/11510/files already has `dashboard/tests/__init__.py` so this is pretty irrelevant in the face of https://github.com/ray-project/ray/pull/11510.

**Comment by richardliaw** [comment]
(closing this due to reverting the offending pr)

**Pull request closed without merging**
