### PR TITLE
Add flush flag for ray log

### PR DESCRIPTION
**Pull request by qicosmos**
## Why are these changes needed?

Add a flush switch for RayLog, default is always flush, you can turn it off when you don't need flush log every time. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests

### CODE REVIEW

**Comment by qicosmos** [comment]
> > > > If ERROR message, spdlog will flush it in a backend thread.(https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/async_logger-inl.h#L69)
> > > > I think flush_on(spdlog::level::err) is ok.
> > > 
> > > 
> > > This is async logger right? Is it the same in sync mode?
> > 
> > 
> > When flush log, spdlog will call async post_flush(https://github.com/gabime/spdlog/blob/29e5930090c81cc91ea079e35ffac7885f281884/include/spdlog/async_logger-inl.h#L40).
> 
> Tha's _async log_ right? I thought we use sync log here as discussed in the previous PR ([#19281 (comment)](https://github.com/ray-project/ray/pull/19281#issuecomment-941936755))
> 
> Here is flush for logger I think https://github.com/gabime/spdlog/blob/29e5930090c81cc91ea079e35ffac7885f281884/include/spdlog/logger-inl.h#L198-L208

We want to add a switch to avoid flush everytime and i have added it, right?

**Comment by iycheng** [comment]
@qicosmos sorry for not explaining it clearly.

I'm thinking maybe we should add flush for error message automatically with spd's builtin feature.

You mentioned:

>If ERROR message, spdlog will flush it in a backend thread.(https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/async_logger-inl.h#L69)
I think flush_on(spdlog::level::err) is ok.

Which I think is not correct since we are using sync logger and you are pointing to async logger code. I just want to make sure we are on the same page and there is no concern about this.

If you think it's ok, could you add it?

**Comment by qicosmos** [comment]
> @qicosmos sorry for not explaining it clearly.
> 
> I'm thinking maybe we should add flush for error message automatically with spd's builtin feature.
> 
> You mentioned:
> 
> > If ERROR message, spdlog will flush it in a backend thread.(https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/async_logger-inl.h#L69)
> > I think flush_on(spdlog::level::err) is ok.
> 
> Which I think is not correct since we are using sync logger and you are pointing to async logger code. I just want to make sure we are on the same page and there is no concern about this.
> 
> If you think it's ok, could you add it?

Right, i will add it.

**Comment by qicosmos** [comment]
> > @qicosmos sorry for not explaining it clearly.
> > I'm thinking maybe we should add flush for error message automatically with spd's builtin feature.
> > You mentioned:
> > > If ERROR message, spdlog will flush it in a backend thread.(https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/async_logger-inl.h#L69)
> > > I think flush_on(spdlog::level::err) is ok.
> > 
> > 
> > Which I think is not correct since we are using sync logger and you are pointing to async logger code. I just want to make sure we are on the same page and there is no concern about this.
> > If you think it's ok, could you add it?
> 
> Right, i will add it.

I have add test to test flush on error at asyn mode, it works, no problem.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Pull request closed without merging**
