### PR TITLE
Remove UT libraries and clean up remaining UT datastructures

### LINKED ISSUE #404: Replace UT data structures with C++ STL.
We began switching from C to C++ in #321. Everything now compiles with a C++ compiler, but the code is still written in the style of a C project. Instead of converting everything all at once to the style of a C++ project, things will happen more gradually.

One immediate benefit is that we can now use the C++ standard library. We've been using some macro-based data structures from here https://troydhanson.github.io/uthash/, which have worked quite well, but are much less convenient than the C++ standard library. The conversion from UT_hash and UT_array to the C++ STL is already happening in various places including #324 and #392. However, there are a bunch more places where it needs to happen.

### PR DESCRIPTION
**Pull request by pschafhalter**
## What do these changes do?

- Clean up remaining UT datastructures
- Remove UT libraries

## Related issue number

- Resolves #404

### CODE REVIEW

**Comment by pcmoritz** [comment]
Oh yes, this is a big moment!

**Comment by pcmoritz** [comment]
retest this please

**Comment by pcmoritz** [comment]
@shaneknapp Can you have a look at the Jenkins build? This is the same error that happened last time when Docker filled up the disk.

**Comment by robertnishihara** [comment]
@pcmoritz Most likely safe to merge this, but we can wait for Jenkins if you prefer.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
