### PR TITLE
Add noisy network and distributional Q-learning to implement Rainbow

### PR DESCRIPTION
**Pull request by joneswong**
## What do these changes do?

- [x] develop noisy network (implemented and in test now)
- [x] develop distributional Q-learning (implemented and in test not)

for DQN to enable Rainbow which is a combination of 6 improvements over DQN.

### CODE REVIEW

**Comment by ericl** [comment]
(copying comment from other PR)

It would be great to put Rainbow vs DQN stats on https://github.com/ray-project/rl-experiments

Let me know if you need any help with reproducing results.

**Comment by joneswong** [comment]
2. compare Double Dueling DQN with itself plugged with noisy net and distributional Q-learning respectively:
basic_dqn

details of double dueling DQN:
dqn_dd

details of DDDQN + noisy net:
dqn_dd_noisy

details of DDDQN + distributional Q-learning:
dqn_dd_dist

**Comment by joneswong** [comment]
3. compare DDDQN equipped by prioritized memory buffer with itself plugged with noisy net and distributional Q-learning respectively:
basic_dqn

details of DDDQN with prioritized buffer:
dqn_dd_priority

details of +noisy net:
dqn_dd_priority_noisy

details of + distributional Q-learning:
dqn_dd_priority_dist

**Comment by joneswong** [comment]
4. compare 3step-DDDQN equipped by prioritized memory buffer with itself plugged with noisy net and distributional Q-learning respectively:
basic_dqn

details of 3step-DDDQN equipped with prioritized buffer:
dqn_dd_priority_3step

details of + noisy net:
dqn_dd_priority_3step_noisy

details of + distributional Q-learning:
dqn_dd_priority_3step_dist

**Comment by joneswong** [comment]
5. compare basic DQN, DQN + 4 improvements existing in RLLib, and Rainbow (the four + the noisy net and distributional Q-learning introduced in this pr):
basic_dqn

details of Rainbow:
rainbow

**Comment by joneswong** [comment]
These improvements are not orthogonal. Without carefully tuning hyper-parameters, it is not straight to show the advantages of Rainbow over other combinations. I am confident on the correctness of implementation based on the experimental results listed above.

@ericl  I am not sure which kinds of experimental results qualify for rl-experiments project.

**Comment by ericl** [comment]
@joneswong the results look pretty good. I'll take a closer look at the code soon.

Since Pong is quite a simple game, it would also be good to try a few other ones such as {Breakout, BeamRider, SpaceInvaders, Qbert}, which are currently evaluated in the rl-experiments repo. Figure 5 of the rainbow paper shows that those games do much better with Rainbow compared to standard DQN: https://arxiv.org/pdf/1710.02298.pdf

Btw if you're doing other atari runs, make sure to pull in https://github.com/ray-project/ray/pull/2700, since that fixes a significant problem with reward counting with the Atari wrappers.

**Comment by ericl** [comment]
I am kicking off an experiment run with the following params, will let you know how it goes.

```
atari-rainbow:
    env:
        grid_search:
            - BreakoutNoFrameskip-v4
            - BeamRiderNoFrameskip-v4
            - QbertNoFrameskip-v4
            - SpaceInvadersNoFrameskip-v4
    run: DQN
    config:
        num_atoms: 51
        noisy: true
        target_network_update_freq: 8000  # 32K / 4
        lr: .0000625  # .00025 / 4
        hiddens: [512]
        learning_starts: 20000  # 80K / 4
        buffer_size: 1000000
        sample_batch_size: 4
        train_batch_size: 32
        schedule_max_timesteps: 2000000
        exploration_final_eps: 0.0
        exploration_fraction: .000001
        prioritized_replay: True
        prioritized_replay_alpha: 0.5
        beta_annealing_fraction: 1.0
        final_prioritized_replay_beta: 1.0
        n_step: 3
        gpu: true
```

**Comment by joneswong** [comment]
Hi Eric,
    there is a tiny difference that thay set Adam epsilon to 1.5 * 10^{-4}
(see Table 1) and we can specify it by `adam_epsilon: 0.00015` if you think
it is necessary.
    best
    Jones

**Pull request closed without merging**
