### PR TITLE
[CI][Clean] Reduce retry setting for _get_logs

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?

When we fail to get logs from anyscale job, the current retry setting will retry for another 15 minutes. Example: https://buildkite.com/ray-project/release-tests-pr/builds/33347#018735a2-f68f-4dc9-a1c6-4179ccaf8d54

That's a pretty long time, I think, especially for cases that there are no logs to fetch (anyscale failed to start for example).

Reduce it to retry 3 times, so around 1 minute.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests

### CODE REVIEW

**Comment by Yard1** [comment]
I think we should keep the initial delay to 30s as that's how long it usually took for the product to return the logs after cluster terminates. Happy to reduce the retries to 3, though!

**Comment by can-anyscale** [comment]
Address @Yard1's comments

**Review by Yard1 — APPROVED** [review]

**Comment by can-anyscale** [comment]
Can you help merge now that the master is unfreezed @Yard1 , @scv119 . Thanks!

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
nice discovery!

**Pull request merged**
