### PR TITLE
[Tune] Dynamically identify PyTorch Lightning Callback hooks

### LINKED ISSUE #27487: [Tune: Python] Pytorch-lightning deprecated hooks in TuneReportCallback
### What happened + What you expected to happen

1. Getting a ton of warnings from pytorch-lightning about deprecation of certain hooks.
2. Expect no warnings.
3. The `TuneCallback` has old hooks such as [`keyboard_interrupt`](https://github.com/ray-project/ray/blob/master/python/ray/tune/integration/pytorch_lightning.py#L165) which have been deprecated.
The most list of the deprecated hooks and their new versions (In pl v1.6+) are:
- `on_keyboard_interrupt` -> `on_exception`
- `on_init_start` -> just deprecated no new version
- `on_init_end` -> just deprecated no new version
- `on_batch_start` -> `on_train_batch_start`
- `on_batch_end` -> `on_train_batch_end`
- `on_epoch_end` -> `on_<train/validation/test>_epoch_end`
- `on_epoch_start` -> `on_<train/validation/test>_epoch_start`

### Versions / Dependencies

ray-tune                  1.12.1 
pytorch-lightning         1.6.5
python                    3.9.13 
(installed using mamba)
OS: Ubuntu 18.04.4 LTS (Bionic Beaver)

### Reproduction script

```python
from pytorch_lightning import Trainer, LightningModule
from torch import rand
from torch.nn import Linear
from torch.nn.functional import mse_loss
from torch.optim import Adam
from torch.utils.data import DataLoader, TensorDataset
from ray.tune.integration.pytorch_lightning import TuneReportCallback


class Model(LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = Linear(20, 4)

    def forward(self, x):
        return self.l1(x)

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = mse_loss(self(x), y)
        return loss

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=0.02)


trainer = Trainer(callbacks=[TuneReportCallback()], fast_dev_run=True)
model = Model()
dataset = TensorDataset(rand((16, 20)), rand(16))
train_loader = DataLoader(dataset, batch_size=4)
trainer.fit(model, train_loader)
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by amogkam**
Our current PTL integration Callback hooks are hard coded and contain deprecated hooks which log a warning: https://github.com/ray-project/ray/issues/27487.

Some of these hooks have already been deprecated in PTL 1.6, others are deprecated in PTL 1.7, and others in 1.8. Instead of maintaining a different PTL integration callback for each PTL version, we instead dynamically identify the available hooks for whatever PTL version the user has installed.

Closes https://github.com/ray-project/ray/issues/27487
Closes https://github.com/anyscale/product/issues/14165

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Yard1** [comment]
Can we test this somehow?

**Comment by amogkam** [comment]
We already have tests for this @Yard1

**Comment by Yard1** [comment]
Would it be possible to test the new logic introduced in this PR, though? Eg. use runtime envs to install 2 PTL versions and see that the hooks were detected correctly?

**Comment by amogkam** [comment]
Hmm but the logic introduced in this pr is already being tested right? There’s no version specific logic introduced in this pr.


Should we be testing all of our integrations against all external library versions?

**Comment by Yard1** [comment]
I suppose that's true, we don't really have a precedent here. I just find it a bit worrying that the intention of this PR is to make the callback version-independent but we have no way of checking if that was achieved

**Comment by amogkam** [comment]
I agree, but to be fair, the intention of the callback in general (even before this PR) was also to be version independent.

Ideally, there would be a good way to test this, but we end up having to test against lots of different versions.

**Comment by Yard1** [comment]
Yeah, that's understandable. The logic looks good to me!

**Review by Yard1 — APPROVED** [review]

**Comment by amogkam** [comment]
Failing test is flaky on master, going to merge

**Pull request merged**
