### PR TITLE
[rllib] dqn/ddpg policy customization

### PR DESCRIPTION
**Pull request by Scitator**
@ericl 
introduction - https://github.com/ray-project/ray/issues/2423

The simplest solution, I add several `_build` methods to DQN policy implementations. 
Just to check the idea, I decide to make as less changes as possible, so check it out.

PS. looking at `_build_q_network` and `_build_p_network` implementations, I wonder, does they use the same `ModelCatalog.get_model(obs, 1, self.config["model"])` or that is the purpose of custom preprocess model?

### CODE REVIEW

**Comment by ericl** [comment]
Looks good! Do you also want to add a section in `rllib-training.rst` on subclassing / how to insert custom policy graphs? It can go under `Accessing Global State` as a `Customizing Policy Graphs` sub-section or similar.

**Comment by Scitator** [comment]
@ericl docs done, but I am not sure about the jenkins errors.

**Review by ericl — APPROVED** [review]
Thanks! I also moved the example to rllib-models.rst since it seemed to fit better with the customization sections there.

The jenkins tests look unrelated (they seem flaky lately).

The travis lint build is failing though (see bottom): https://api.travis-ci.com/v3/job/135700804/log.txt
You can fix that by running `scripts/yapf.sh` to reformat the rllib files, otherwise looks good to merge.

**Comment by Scitator** [comment]
@ericl Not sure about the errors, but the PR looks like good enough. (just want to officially start to use this feature out of the Ray :) )

**Comment by ericl** [comment]
Test failures look unrelated, merging.

**Pull request merged**
