### PR TITLE
Sync vtrace.py with deepmind implementation

### PR DESCRIPTION
**Pull request by stefanpantic**
## What do these changes do?
* Synced ```vtrace.py``` with deepmind implementation in the original ```scalable_agent``` repo

### CODE REVIEW

**Comment by ericl** [comment]
Looks good assuming regression tests pass.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
Hm, looks like this actually breaks APPO-vtrace (and presumably IMPALA-vtrace?)

```
++ docker run --rm --shm-size=20G --memory=20G 84cd70247da462af11def6bd8df89ead40b5a3a925e1c748beac6c1906df567e
/ray/ci/suppress_output python /ray/python/ray/rllib/tests/run_regression_tests.py
/ray/python/ray/rllib/tuned_examples/regression_tests/cartpole-appo-vtrace.yaml

...

 - APPO_CartPole-v0_0:	TERMINATED, [2 CPUs, 0 GPUs], [pid=100], 50 s, 5 iter, 115450 ts, 9.37 rew

```

**Review by ericl — CHANGES_REQUESTED** [review]
Seems like this breaks on cartpole?

**Comment by stefanpantic** [comment]
@ericl I couldn't converge on BreakoutNoFrameskiv-v4, it seems that the code isn't equivalent. Will delete pull request.

**Pull request closed without merging**
