### PR TITLE
[nightly] Start to populate metrics for many_nodes_actor_test

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Now v2 stack has supported metrics population, this PR turn it on for our nightly test.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Can you run the release test before merging just in case?

**Comment by iycheng** [comment]
https://buildkite.com/ray-project/release-tests-pr/builds/28325 I've kicked it off and it's waiting for two hours :(

**Comment by iycheng** [comment]
The test failed because the infra issues. I'll rerun the test once it's fixed.

**Comment by iycheng** [comment]
Test passed

**Pull request merged**
