### PR TITLE
[serve] use true nulls in snapshot

### PR DESCRIPTION
**Pull request by iasoon**
## Why are these changes needed?

Change snapshot json values from "None" to an actual null value, which is a bit more ideomatic.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]

**Review by architkulkarni — CHANGES_REQUESTED** [review]
Hi @iasoon sorry for the change. I discussed with the team that consumes the snapshot and it turns out `rayJobId` should not be nullable.  I think `deployer_job_id` is never None, because it's only ever passed in here https://github.com/ray-project/ray/blob/03e05df9cb442a5e0609a5887988f2c7d58d7284/python/ray/serve/api.py#L234 and it's not `None` here.  So I think we just need to make `deployer_job_id` not `Optional`, as it currently is.  

This is a little outside the scope of this PR, so I can make a separate PR for that first, or you can do it in this PR.  What do you think?

**Comment by iasoon** [comment]
Well, as this PR was about making the declared nullability match reality, I think it fits with the theme ;-)

**Review by architkulkarni — APPROVED** [review]
Looks great, thanks :)

**Comment by architkulkarni** [comment]
@simon-mo could you please merge this when you get a chance?

**Pull request merged**
