### PR TITLE
Replace `queue.Queue` with `multiprocessing.JoinableQueue`

### PR DESCRIPTION
**Pull request by czgdp1807**
## Why are these changes needed?

Reason for not using `queue.Queue` for multiprocessing purposes on Windows is at https://stackoverflow.com/a/37244276 and in the second reply to https://stackoverflow.com/a/37245300
And reason for using `multiprocessing.JoinableQueue` over `multiprocessing.Queue` is https://stackoverflow.com/a/30725121

AFAIK, this is because in Windows each process gets it own `Queue` and hence nothing is shared among those processes. When `multiprocessing.Queue` is used, changes in it are shared via pipes internally along with proper locks.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by pcmoritz** [comment]
Hmm, this seems to be failing with a NonImplementedError at the moment on Windows.

**Comment by czgdp1807** [comment]
> Hmm, this seems to be failing with a NonImplementedError at the moment on Windows.

I checked logs on CI. Two unrelated (maybe) timeout on CI. Is there something that I am missing?

**Comment by pcmoritz** [comment]
Sorry, it was on the mac os Medium A-K test matrix:

```


/Users/ec2-user/.buildkite-agent/builds/bk-mac1-experimental-queue-i-01c19b72c735e77d2-1/ray-project/ray-builders-pr/python/ray/tests/test_multiprocessing.py:424:
--
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | self = <multiprocessing.queues.JoinableQueue object at 0x7fd3d91d0d30>
  |  
  | def qsize(self):
  | # Raises NotImplementedError on Mac OSX because of broken sem_getvalue()
  | >       return self._maxsize - self._sem._semlock._get_value()
  | E       NotImplementedError
  |  
  | /usr/local/opt/miniconda/lib/python3.6/multiprocessing/queues.py:117: NotImplementedError


```

**Comment by czgdp1807** [comment]
I see. May be we can change the `queue` depending on the OS?

**Comment by pcmoritz** [comment]
Yes, why don't we only use joinable queue on Windows?

**Comment by czgdp1807** [comment]
Sure I will do that. Right now I am working on `test_typing` path fix.

**Comment by pcmoritz** [comment]
Thanks, that's great :)

**Comment by czgdp1807** [comment]
Is it safe to conclude that `test_multiprocessing` is passing on CI? I can drop my last commit if that's the case. I don't see it failing though.

**Comment by czgdp1807** [comment]
`test_multiprocessing` times out on my system, but here on CI it passes. I will drop my second last commit to confirm that it passes on CI multiple times.

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
