### PR TITLE
WIP: Reorganize Ray's Worker

### PR DESCRIPTION
**Pull request by suquark**
## What do these changes do?

This PR refactors Ray to make its structure more reasonable. It does not change most APIs, it just refactors its internal structures.

I took a close look at Ray's code and thought its `Worker` could be factorized into the following parts:

1. A `serialization` module which
   - maintains mappings to `SerializationContext`
   - provides a fallback to deal with serialization failures from pyarrow
   - support custom object serialization register
   - checks whether a type is serializable
2. A `object_store_client` module which
   - maintains a `plasma_client`
   - providers interface for object transfer
3. A `exceptions` module which
   - defines common errors for object transfer
4. A `execution_info` module which
   - maintains imported functions & call counts
5. A `distributor` module which
   - caches functions & actors to be run before initialization of the worker
   - export remote function & actors
   - import remote function & actors
   - execute imported remote function & actors with a thread
6. A `logging` module which:
   - controls logging redirection 
   - pushes errors to driver
   - pull errors and print them

And the `Worker` itself is divided into 2 parts:

- A `Driver` which could transfer objects, export functions & actors and submit tasks
- A `Worker` subclass which imports tasks and executing them.

The separation is beneficial because these two parts have their own independent logics.

## The benefits

1. This PR reduces the internal coupling of the code, making the code easier to maintain and understand.
2. This PR make the code more modular and help with performance analysis and bug analysis.
3. This PR reveals the internal logic of Ray in a clear way.
4. Easier to hide all of the Redis interactions that behind C++ APIs.
5. Easier to instantiate multiple `Worker` objects.

If welcomed, I could write some docs to help new contributors understand the mechanisms of Ray after this PR merged. 

## Related issue number

https://github.com/ray-project/ray/issues/2016
https://github.com/ray-project/ray/issues/614

### CODE REVIEW

**Comment by richardliaw** [comment]
Hey @suquark, is it possible to break this PR up, preferably into +/- 500 each?

It would make the review process a lot simpler and extensive.

Thanks!

**Comment by robertnishihara** [comment]
Thanks for submitting this @suquark! This is a really large PR. I'll take a look.

**Comment by danielsuo** [comment]
@mihaic @gdoubleyew

We're also very interested in this. Thanks for getting it started! Also echo the other comments about breaking the PR up. It may also be helpful to have a design document since this will likely affect a lot of other WIP.

**Comment by suquark** [comment]
@raulchen @richardliaw @robertnishihara @danielsuo 
Thanks for your comments! I will break this PR down into smaller ones soon.

And about the name `dataflow`, it is because there is already existing a `worker.py` module and a `worker` module, I think it's better to have another name. And since a lot of modules are about object transfer & remote communication, I named it `dataflow`.

And this PR also starts to move `connect()` into `Worker`. Modularizing is also helpful in this situation for greatly reduce the size of `connect()`. Originally it is too big to be put into `Worker` in a nice way.

**Comment by robertnishihara** [comment]
Thanks @suquark for breaking it into smaller pieces. I completely agree that we need to clean up the Python side of things.

@raulchen making the `Worker` class more object oriented is a great idea.

@danielsuo I also agree that this is an important change so we should discuss the key design decisions (e.g., class hierarchy/interfaces) in a design document. @suquark what do you think about that?

**Comment by richardliaw** [comment]
+1 on the design docs (and if so, also consider moving the discussion onto ray-dev for better archiving).

**Comment by raulchen** [comment]
`dataflow` isn't very clear to me, it sounds like the name of a framework or something (e.g., [google cloud dataflow](https://cloud.google.com/dataflow/)).

One possible way to re-use the name `worker` is organizing the files in this way:
- move `worker.py` to `worker/worker.py`
- import public APIs from `worker/worker.py` in `worker/__init__.py` (so other places can still use `from ray.worker import something`)
- put other components under `worker/` directory

We can use the design doc to discuss more about the naming.

**Comment by suquark** [comment]
@robertnishihara @richardliaw @raulchen 

I have created a topic with a link to the design document:
https://groups.google.com/d/msg/ray-dev/STBXwsYQV98/4Iw4aTkADwAJ

Comments are welcome ; )

**Comment by suquark** [comment]
Could anyone review and merge #2597 and #2599? 
I want to fix https://github.com/ray-project/ray/issues/2605 after the merge.

**Comment by robertnishihara** [comment]
Closing for now due to staleness. The overall refactoring is still very important though.

**Comment by suquark** [comment]
@robertnishihara Do you plan to include the refactoring in 0.7.0 (or even earlier)? We could add it to the 0.7 project.

**Pull request closed without merging**
