### PR TITLE
[autoscaler] Add tmux support for attach and exec

### PR DESCRIPTION
**Pull request by richardliaw**
Adds a tmux flag that can be used to support background execution of experiments. Cannot be used
together with screen. Seems to be useful feature that has shown up with different users.

We can also consider making 'attach' have an option for tmux.

CC @eugenevinitsky @hartikainen

### CODE REVIEW

**Review by hartikainen — COMMENTED** [review]
Nice, this is super useful!

**Review by ericl — COMMENTED** [review]
Can we also have this for attach?

**Comment by richardliaw** [comment]
Attach is done

**Review by ericl — COMMENTED** [review]
Code looks good. I'll try it out tomorrow.

Btw it should probably be added to the `autoscaler.rst` docs?

**Comment by ericl** [comment]
Tried it and it works great. Only comment is that we can provide a better message. Currently you get:

```
$ ray exec sgd.yaml -n grid 'watch uptime' --tmux
Connection to 18.206.162.170 closed.
```

It would be nice to say "Use `ray attach .... --tmux` to check on command status" or something.

**Comment by ericl** [comment]
Doc link: https://ray.readthedocs.io/en/latest/autoscaling.html

**Comment by richardliaw** [comment]
Jenkins retest this please

**Comment by richardliaw** [comment]
Jenkins retest this please

**Review by ericl — APPROVED** [review]

**Pull request merged**
