### PR TITLE
Fix dask dependencies

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?

Some if not all of the dask release tests are failing because of [dependency hell](https://github.com/anyscale/product/pull/19270). In short, boto, s3sf does not work well with boto3 that is installed in anyscale dataplane. Good news is these tests do not need these dependencies anyway (since anyscale already installed them properly).

## Related issue number

Closes[ #19399](https://github.com/anyscale/product/issues/19399)

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Release tests - https://buildkite.com/ray-project/release-tests-pr/builds/34519#

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
Ah good call, I didn't think of removing `s3fs`.  How did you figure out `s3fs` needed to be removed?

Do we also need to update `large_scale_dask_on_ray_app_config`?

Can you trigger the relevant release tests on this PR?

**Comment by can-anyscale** [comment]
Any libraries related to s3 seem like potential culprit to me ;). Absolutely, let me update large_scale_dask_on_ray_app_config as well and trigger all dask tests.

**Review by architkulkarni — APPROVED** [review]
Will merge pending the release tests passing

**Comment by can-anyscale** [comment]
Ok, I think my latest change works, the tests already pass the point of failures. CC: @architkulkarni 

Can probably wait for all the tests to finish, but can be in several hours.

**Comment by architkulkarni** [comment]
@can-anyscale Sounds good, we don't need to wait for the release tests, but per policy I'll wait for the rest of the CI to finish before merging.  I think waiting a few hours is okay

**Comment by can-anyscale** [comment]
@architkulkarni  totally!

**Comment by architkulkarni** [comment]
Looks like everything passed, merging.

**Comment by architkulkarni** [comment]
Doc failures unrelated, this PR just edits the release tests.

**Comment by architkulkarni** [comment]
Sorry forgot to mark this as 2.4.0pick earlier.

**Comment by cadedaniel** [comment]
nice fix @can-anyscale ! are you taking on the cherry-pick PR? also have we verified that the dask release tests run now? (asking bc there's a release blocker because a dask test fails) https://github.com/ray-project/ray/issues/34259

**Comment by architkulkarni** [comment]
Yes, cherry pick PR is here https://github.com/ray-project/ray/pull/34332

**Pull request merged**
