### PR TITLE
[Dataset] optionally pin pipeline actors on driver node.

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

pin pipeline actors on driver node doesn't work when Ray dataset is used with Ray client.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
Could we auto fallback to not pinning if the resource isn't found in ray.available_resources()? This is a sufficiently severe bug I think it needs to work out of the box.

**Comment by ericl** [comment]
We could also special case detect client mode.

**Comment by clarkzinzow** [comment]
Another option would be checking to see if we're currently in client mode and using the head node IP instead:
```python
if ray.util.client.num_connected_contexts() > 0:
    # Use head node IP.
    ip_address = _get_head_node_ip()
else:
    ip_address = ray.util.get_node_ip_address()
resources = {f"node:{ip_address}": 0.0001}
```

Two things that I'm not sure of for this approach:
1. Does `_get_head_node_ip()` already exist somewhere as a helper (or on some Ray Client context/connection object, since we know that we're in Ray Client mode)?
2. How do we support users that can't use the custom node resource, i.e. when a Ray node doesn't directly map to an IP address?

**Comment by scv119** [comment]
> How do we support users that can't use the custom node resource, i.e. when a Ray node doesn't directly map to an IP address?

That's something @jjyao's proposal should fix?

**Review by ericl — APPROVED** [review]

**Pull request merged**
