### PR TITLE
[CI] Run Java CI on Mac

### LINKED ISSUE #19700: Run Java CI on Macos to avid breakages.

### PR DESCRIPTION
**Pull request by jjyao**
## Related issue number
Closes #19700

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
@simon-mo Do you know if we have access to the buildkite mac. Some tests failed because they don't have permission to execute `ps` but those tests passed on my local mac. I'm wondering if the mac environment is different.

**Comment by simon-mo** [comment]
The Mac environment runs inside a sandbox. Why do we need ps?

**Comment by jjyao** [comment]
> The Mac environment runs inside a sandbox. Why do we need ps?

Currently there is some Java code that uses `ps` to check the existence of a process.

**Comment by simon-mo** [comment]
I will modify the infra to allow `/bin/ps`
https://github.com/bazelbuild/bazel/issues/7448#issuecomment-628002457

**Comment by simon-mo** [comment]
done and deployed, https://github.com/ray-project/macos-sandbox-buildkite-plugin/commit/8d751f4b6ef6f45bea1608e9077599957d5f7ab8, please rebuild via pushing new empty commits or click "Rebuild" with buildkite UI.

**Review by jovany-wang — APPROVED** [review]
Looks great to me. Thanks for your efforts. :)

**Pull request merged**
