### PR TITLE
Added Dict/Tuple space support in '_check_view_requirement()'.

### LINKED ISSUE #31266: [RLlib] `_check_view_requirement()` does not work with `Dict` space
### What happened + What you expected to happen

# What happened
I am training a policy with `Dict` action space. When running my algorithm I got the following warning: 

```
[-1.13909018 -0.00525073 -1.20116985 -0.13585699 -0.87877417 -0.26143172
 -1.13827956  0.24254586 -1.38049316 -0.59437531  1.          1.
  1.          0.          0.          1.          1.          1.
  0.          1.        ]
 does not match space of view requirements actions.
Provided tensor has shape (20,) and view requirement has shape shape None. Make sure dimensions match to resolve this warning
```
I followed the stack trace up to the `_check_view_requirement()` function that does not account for the `shape` of `Dict` or `Tuple` spaces when comparing the view requirement's space's shape with the data shape. 

# What you expected to happen
That all spaces are covered in the check. 

### Versions / Dependencies

Fedora 37
Python 3.9.4
Ray 2.2.0

### Reproduction script

Use any algorithm with a `Dict` action space (should also occur with a `Dict` obs space). 

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by simonsays1980**
## Why are these changes needed?

The `_check_view_requirement()` function does not account for `Dict` and `Tuple` spaces (or in general more complex spaces), yet. This PR should solve this issue. 

When running an algorithm with a `Dict` or `Tuple` space the mentioned function throws a warning that might irritate the user. Furthermore the check of the shapes might be important for downstream tasks. 

It is still ambiguous what the shape of a `Dict` or `Tuple` space is - this is also left blank by the gym authors. I follow the size handling in [`ModelCatalog`](https://github.com/ray-project/ray/blob/875949453296c4d3f6e3afbf3382569be4e27844/rllib/models/catalog.py#L375) in this PR.

The PR is tested on `test_agent_collector.py` - all tests passing.

## Related issue number

Closes #31266 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ArturNiederfahrenhorst** [comment]
Just swapped the conditions to save some runtime because the condition you wrote is tested on every single timestep and is a little heavier. Also deleted the comment. Thanks a lot for this fix @simonsays1980 !

**Comment by simonsays1980** [comment]
> Just swapped the conditions to save some runtime because the condition you wrote is tested on every single timestep and is a little heavier. Also deleted the comment. Thanks a lot for this fix @simonsays1980 !

Good catch @ArturNiederfahrenhorst . I was so in love with the detail, I did not see the complete picture. Thanks for adding this!

**Comment by simonsays1980** [comment]
@ArturNiederfahrenhorst I see a lot of `import` errors for `ProfileDataTables` that might come from the core and not RLlib

**Comment by ArturNiederfahrenhorst** [comment]
Merged master again

**Review by sven1977 — APPROVED** [review]
LGTM! Thanks @simonsays1980 for the fix!

**Pull request merged**
