### PR TITLE
Printing messages to stderr

### PR DESCRIPTION
**Pull request by richardliaw**
Move core python code onto logging module (or something else
so that stdout isn't cluttered).

Addressing #1884.

@pcmoritz @robertnishihara

### CODE REVIEW

**Comment by ericl** [comment]
Nice. At some point we should start doing this for other modules too...

**Comment by richardliaw** [comment]
Specifically for the SampleBatch warnings; I'd like those not to appear :)

**Comment by robertnishihara** [comment]
Nice! Is the idea that we would use this from other files (e.g., `worker.py`) via `ray.services.logger`?

**Comment by richardliaw** [comment]
Not totally sure; there's something they do with `__name__` to get a particular logger per module, but I'm not an expert...

You may not want to use one centralized logger if you have different modules logging to different files.

**Comment by robertnishihara** [comment]
Do you want to go ahead and convert the print statements in `worker.py` and `actor.py` as well?

We can save that for a future PR, but we should leave #1884 open until we've gotten everything.

**Comment by richardliaw** [comment]
What is the verdict? Just do as already is for now?

**Comment by robertnishihara** [comment]
If you include the statement `logger = logging.getLogger(__name__)` in multiple files, will `__name__` always be the same? That is, for a given process, how many distinct logger objects will we have? I think we want just one.

**Comment by robertnishihara** [comment]
Actually, won't that potentially interfere with logging from the user's application? E.g., the user could easily have the same line `logger = logging.getLogger(__name__)`, right?

**Comment by robertnishihara** [comment]
A lighter weight approach would just be to use the `warnings` module (which would avoid global variables I think), but that is less configurable and may not allow for `INFO` statements.

**Comment by ericl** [comment]
I think one "root" logger is the way to go. Modules can create sub-loggers by calling `logger.getChild(name)`.

So if you're a top-level Ray file you would do:

```
import ray.services.logger as log
```

Then a module like RLlib could define:

```
import ray.services.logger as root_logger
logger = root_logger.getChild("rllib")
```

And rllib files could do
```
import ray.rllib.logger as log
```

**Comment by richardliaw** [comment]
Printing `__name__` in `ray/worker.py` gives me `ray.worker`.

Will go with Eric's suggestion and will include test for checking conflicts.

**Comment by richardliaw** [comment]
After reading docs; do we want to pass the same logger instance around? 

https://docs.python.org/2/library/logging.html#logging.getLogger says
> This means that logger instances never need to be passed between different parts of an application.

**Comment by robertnishihara** [comment]
Slight preference for the approach you took, but I think either would be ok.

**Comment by richardliaw** [comment]
OK lets leave as is; ready for review. I was more conservative with using “logger.error”.

**Review by robertnishihara — APPROVED** [review]
Looks good to me, but linting is failing I think.

**Comment by robertnishihara** [comment]
Could you rebase as well? Conflicts should be minor.

**Comment by richardliaw** [comment]
jenkins retest this please

**Pull request merged**
