### PR TITLE
[Core]: Fix ConnectionError on Autoscaler CR lookups in K8s clusters with custom DNS for Kubernetes API.

### LINKED ISSUE #48538: [Core]: Autoscaler fails to start because it can't resolve the kubernetes host.
### What happened + What you expected to happen

We're testing the kuberay autoscaler following [this guide](https://docs.ray.io/en/latest/serve/advanced-guides/advanced-autoscaling.html) and [this chart](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.autoscaler-v2.yaml) as a reference. 

The sidecar fails with this error:
```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kubernetes.default', port=443): Max retries exceeded with url: /apis/ray.io/v1/namespaces/ml-platform-model-v6/rayclusters/ml-platform-model-v6-raycluster-wzg8l (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16c1646b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

It seems the Ray Autoscaler needs to [call kubernetes APIs](https://github.com/ray-project/ray/blob/c7263e4a4bff73215bc1241dab51e0b355778a77/python/ray/autoscaler/_private/kuberay/node_provider.py#L195-L202). To do an equivalent of `kubernetes get rayclusters` using the API. The referenced part of the code makes an assumption about the kubernetes host, which is different in our case. 

### Versions / Dependencies

|    | Version |
|---|------------|
| Ray Version | 2.34.0 |
| Python | 3.10, 3.11 |
| OS | Ubuntu:22.04 |

### Reproduction script

I have a fix instead of repro:
```
curl https://kubernetes.default
curl: (6) Could not resolve host: kubernetes.default
```
If we use kubernetes set env vars or allow the kubernetes host as a parameter, we wouldn't face this issue.
```
curl -k https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by ltbringer**
update: kubernetes host is inferred from `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`.

## Why are these changes needed?

This PR fixes https://github.com/ray-project/ray/issues/48538. The Kubernetes API host is assumed to be `kubernetes.default` but clusters may have custom DNS for the API server.

In this PR we follow the official [guideline on directly using the k8s API](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api).

## Related issue number

Closes: #48538 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]
Nice!

**Review by kevin85421 — APPROVED** [review]
Nice!

**Comment by lxmanutd** [comment]
@kevin85421 @ltbringer Seems this issue fixed in master branch, but without package delivered? When will be package include the fix will be delivered? Thanks!

**Comment by ltbringer** [comment]
@lxmanutd I am not a Ray maintainer, so I am unsure; this commit missed the 2.39 release by ~3-4 days. We can expect it to be part of 2.40. I tested the patch using the nightly images, and autoscaling worked for me.

https://github.com/ray-project/ray/issues/48834 might be a different problem, though. I'd check these env vars inside the pod:
```
echo $KUBERNETES_SERVICE_HOST
echo $KUBERNETES_SERVICE_PORT_HTTPS
```
Since you say the auto scaler was up for 23 hours, this fix might not be related. In my case, the autoscaler could never start.

**Pull request merged**
