### PR TITLE
[RLlib] Support arbitrarily nested action Spaces.

### PR DESCRIPTION
**Pull request by sven1977**
RLlib currently does not support arbitrarily nested action spaces. Only depth=1 Tuples are supported (no Dicts either). For PyTorch, not even Tuples are allowed. This PR release these restrictions and allows arbitrarily nested Tuple and Dict action spaces for both tf and torch.

- Handles all actions within Policy classes as flattened actions (until sent back to the Env).
- Adds TorchMultiActionDistribution class.
- Adds framework-agnostic test cases for (Torch)MultiActionDistribution object.
- Adds tf and torch Beta distribution.
- Closes issue 6914.

Closes issue 6914.

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by ericl — CHANGES_REQUESTED** [review]
Is this ready to review? I see commented out parts still.

Also, now it's close to exceeding 1k lines changed. Can we split this into the core changes and the ARS / ES ones? Preferably, three PRs: pytorch support, arbitrary nesting, then other changes.

**Comment by sven1977** [comment]
Yeah, it's not ready yet. I'll split it once done.

**Comment by jsuarez5341** [comment]
How is this going? I have a use case for nested PyTorch action spaces and would be happy to try it out

**Comment by ericl** [comment]
@sven1977 is this still the right PR to review, or has it been broken up into others?

**Comment by jsuarez5341** [comment]
Any news on this? It's a pretty key feature for PyTorch, as there currently isn't any way to support environments that take multiple actions, as far as I am aware.

**Pull request closed without merging**
