### PR TITLE
Use retriable_lifo policy for shuffle 1tb nightly test

### PR DESCRIPTION
**Pull request by jianoaix**
## Why are these changes needed?
Fix release blocker issue: https://github.com/ray-project/ray/issues/32203

Ran 6 times and all of them passed.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by clarng** [comment]
Thanks for submitting this PR. I see the config is used by many tests. Should we just exclude dataset_shuffle_sort_1tb only?

**Comment by clarng** [comment]
FYI we also had the same issue before, with the retriable_lifo policy, seems to be a bug in the test or code, and is exacerbated by the chaos version of this test : https://github.com/ray-project/ray/issues/30680

But if we are seeing OOMError being thrown then i agree we should move back to retriable_lifo for this test

**Comment by jianoaix** [comment]
@clarng The error from the failure was OutOfMemoryError (https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_jxk4uxrewk4lvkstygni9q6641), not ObjectFetchTimedOutError.

**Comment by clarng** [comment]
> @clarng The error from the failure was OutOfMemoryError (https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_jxk4uxrewk4lvkstygni9q6641), not ObjectFetchTimedOutError in #30680.

I think there two errors, the one mentioned in https://github.com/ray-project/ray/issues/32203 I think may still trigger, but may be good enough for now if its not too flaky

**Comment by jianoaix** [comment]
> > @clarng The error from the failure was OutOfMemoryError (https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_jxk4uxrewk4lvkstygni9q6641), not ObjectFetchTimedOutError in #30680.
> 
> I think there two errors, the one mentioned in #32203 I think may still trigger, but may be good enough for now if its not too flaky

I see your concern. The first error `ObjectFetchTimedOutError` was seen when there was a re-execution of the Dataset plan due to the `ds.stats`. The stacktrace from https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_qeqb5xjas6jziu7bus2zzzk4ba?command-history-section=command_history is like:
```
File "dataset/sort.py", line 146, in <module>
    print(ds.stats())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 3926, in stats
    return self._get_stats_summary().to_string()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 3929, in _get_stats_summary
    return self._plan.stats_summary()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 608, in stats_summary
    self.execute()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 536, in execute
    dataset_uuid=self._dataset_uuid,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/legacy_compat.py", line 84, in execute_to_legacy_block_list
    bundles = executor.execute(dag, initial_stats=stats)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/bulk_executor.py", line 82, in execute
    return execute_recursive(dag)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/bulk_executor.py", line 62, in execute_recursive
    op.inputs_done()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/operators/all_to_all_operator.py", line 57, in inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/legacy_compat.py", line 245, in bulk_fn
    block_list, ctx, input_owned, block_udf, remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/stage_impl.py", line 214, in do_sort
    return sort_impl(blocks, clear_input_blocks, key, descending)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/sort.py", line 138, in sort_impl
    boundaries = sample_boundaries(blocks_list, key, num_reducers)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/sort.py", line 97, in sample_boundaries
    samples = sample_bar.fetch_until_complete(sample_results)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/progress_bar.py", line 76, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::_sample_block() (pid=143721, ip=172.31.205.93)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.ObjectFetchTimedOutError: Failed to retrieve object f57510499cea6ea7ffffffffffffffffffffffff0300000002000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.
```

This re-execution was due to a bug in the test itself and is now fixed.
I can re-run a few more times (without this PR but with the `ds.stats` fix) to see if `ObjectFetchTimedOutError` will appear again (if not, it'll confirm the OOM is the only remaining error).

**Comment by cadedaniel** [comment]
> This re-execution was due to a bug in the test itself and is now fixed.
I can re-run a few more times (without this PR but with the ds.stats fix) to see if ObjectFetchTimedOutError will appear again (if not, it'll confirm the OOM is the only remaining error).

Are we running these?

**Comment by jianoaix** [comment]
> > This re-execution was due to a bug in the test itself and is now fixed.
> > I can re-run a few more times (without this PR but with the ds.stats fix) to see if ObjectFetchTimedOutError will appear again (if not, it'll confirm the OOM is the only remaining error).
> 
> Are we running these?

Yep, running 4 concurrently. So far 2 of them already failed and both had OOM failures: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/?tab=session-list&user=usr_UZM7MP6d4gpYY2ST3Xet1TML.
Let's see the if other 2 are also OOM.

**Comment by jianoaix** [comment]
Somehow those remaining 2 tests were not actually running the scripts, so I kicked off 2 new tests (can be seen from the same link above), but it may take up to 2 hours.
So far we at least had 3 failures with OOM and 0 with `ObjectFetchTimedOutError`. Depending on when @cadedaniel  will need to start a new release test run, shall we merge and cherrypick this PR?

**Comment by cadedaniel** [comment]
> Somehow those remaining 2 tests were not actually running the scripts, so I kicked off 2 new tests (can be seen from the same link above), but it may take up to 2 hours.
So far we at least had 3 failures with OOM and 0 with ObjectFetchTimedOutError. Depending on when @cadedaniel will need to start a new release test run, shall we merge and cherrypick this PR?

Thanks. We are pushing back the handoff to product from 1pm to 3pm, see #release-management. Let's let them run, we can merge closer to handoff.

**Comment by cadedaniel** [comment]
how are we looking @jianoaix ? I think we should merge now

**Comment by jianoaix** [comment]
I ran 4 tests (after the 2 failed with OOM), and 3 of them failed with OOM and one succeeded. So we had at least 6 OOMs and still 0 `ObjectFetchTimedOutError`. We should be able to merge now.

**Review by cadedaniel — APPROVED** [review]

**Pull request merged**
