### PR TITLE
Rock paper scissors multi-agent example maintenance

### PR DESCRIPTION
**Pull request by lssr**
## Why are these changes needed?

Miscellaneous maintenance to Rock-Paper-Scissors scissors example code, replaces environment itself with upstream PettingZoo environment (it has identical functionality with more minor fixes). Upstreaming the environment removes maintenance on your end.

List of miscellaneous fixes:
- Removed Ray's Rock-Paper-Scissors environment file (previous location `rllib/examples/env/rock_paper_scissors.py`).
- Updated the BeatLastHeuristics class in `rllib/examples/policy/rock_paper_scissors_dummies.py` to account for an initial observation of None as it is done in PettingZoo's version of Rock-Paper-Scissors.
- Added the necessary code to create and register the PettingZoo environment in `rllib/examples/rock_paper_scissors_multiagent.py`. Also, the reward difference (`env.player1_score - env.player2_score`) is substituted by the accumulated total reward of the learned policy.

Also, if you're worried about this from a CI stability perspective then an exact PettingZoo version can just be pegged. 

@justinkterry 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by justinkterry** [comment]
@sven1977 this appears to be passing all meaningful tests and its been a month, can you please take a look?

**Comment by sven1977** [comment]
Hey @justinkterry @lssr , thanks for this commit! The example tests for rock paper scissors seem to be failing, though (for both torch and tf). Could you check why?

I'm seeing: `ValueError: Desired reward difference (1000.0) not reached! Only got to 0.`

**Comment by justinkterry** [comment]
@sven1977 the remaining failing tests don't appear meaningful

**Comment by richardliaw** [comment]
Closing this as we have a duplicate.

**Pull request closed without merging**
