### PR TITLE
[AIR] `load_best_model_at_end` validation for HF

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

Adds validation for `TrainingArguments.load_best_model_at_end` (will throw an error down the line if set to True), fixes validation for `*_steps`, adds test.

## Related issue number

https://discuss.ray.io/t/air-and-huggingface-trainers-checkpoint-paths-are-inconsistent/7182/

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]

**Comment by amogkam** [comment]
looks like test is failing @Yard1

**Comment by dumpmemory** [comment]
is there any plan to support steps setting for checkpoints ?

**Comment by Yard1** [comment]
Yes, it's on the backlog

**Comment by amogkam** [comment]
@Yard1 could you add a comment on why we raise an error for evaluation but override for the others? Should we have consistent behavior for all 3?

**Comment by Yard1** [comment]
@amogkam we would like that, ideally, but `save_strategy` and `logging_strategy` are set to STEPS by default by Hugging Face (and there doesn't seem to be a way to differentiate between user-set and default value). I'll clarify that in code

**Comment by amogkam** [comment]
Got it. For my understanding, what’s required in order to support steps strategy?

If steps is the default setting then we may want prioritize supporting that.

I’m concerned that changing the training arguments automatically may be confusing for the user.

**Comment by Yard1** [comment]
I'll have to investigate. Happy to look into it this week! Agreed that this should be prioritised (also given the community demand). I think we should merge this in the meanwhile though.

**Comment by amogkam** [comment]
Sounds good, thanks!

**Pull request merged**
