### PR TITLE
Update cloudpickle to 0.8.0.dev0

### PR DESCRIPTION
**Pull request by pcmoritz**
This updates cloudpickle to 0.8.0.dev0, specifically https://github.com/cloudpipe/cloudpickle/pull/245 with the fix https://github.com/cloudpipe/cloudpickle/pull/240 applied.

We should hold off merging this till https://github.com/cloudpipe/cloudpickle/pull/240 is merged.

This should fix the dataclass serialization problem in https://github.com/ray-project/ray/issues/3917

cc @suquark

### CODE REVIEW

**Comment by pcmoritz** [comment]
Looks like this is working now, nice!

**Comment by robertnishihara** [comment]
@pcmoritz is this ready to review? Or are there any more anticipated changes?

**Comment by pcmoritz** [comment]
@robertnishihara This is ready.

**Comment by robertnishihara** [comment]
I'll merge this once once it corresponds to an actual cloudpickle commit. Looks like the relevant PR still hasn't been merged in cloudpickle.

**Comment by robertnishihara** [comment]
Just updated cloudpickle to correspond to https://github.com/cloudpipe/cloudpickle/commit/9184a6755c2a5ed8af38fa496f34b5c043cbe1aa.

**Comment by robertnishihara** [comment]
Jenkins, retest this please.

**Comment by robertnishihara** [comment]
Jenkins, retest this please.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
