### PR TITLE
Update wheel in example.yaml.

### PR DESCRIPTION
**Pull request by robertnishihara**
This needs to be tested before merging.

### CODE REVIEW

**Comment by robertnishihara** [comment]
Actually, I just realized that the `example.yaml` file that we ship with a release will never work because it will install an old wheel. We should either point it at the "latest" wheel in S3.

**Comment by ericl** [comment]
If you changed the pip install to ray=0.3.1 would that work (after the 0.3.1 package is pushed?)

**Review by ericl — APPROVED** [review]
Lgtm (but I guess it can't really be tested?)

**Comment by robertnishihara** [comment]
Well I'm trying out the `ray create_or_update` command just to make sure it didn't break anything accidentally

**Pull request merged**
