### PR TITLE
[Ownership based object directory] Turn on by default

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

All tests seem to pass. Let's turn it on by default and fix all bugs by the next release :) 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
If there are not many failing tests, we can add this to our CI.

**Comment by rkooo567** [comment]
@clarkzinzow I will keep merging the master and run tests again here whenever you merge a new OBOD PRs.

**Comment by clarkzinzow** [comment]
As soon as the object spilling PR is merged, I'll be opening up a testing + benchmarking PR with the feature flag turned on, at which point we can probably close this PR.

**Comment by rkooo567** [comment]
@clarkzinzow Let's see if all tests pass before we do that first. I think if there are still test failures, we should isolate the fix PR from refactoring PR (as well as benchmark)

**Comment by rkooo567** [comment]
Pushing the change now...

**Comment by rkooo567** [comment]
@clarkzinzow I guess this will pass all tests (I will close it if so, lmk if you already checked it).

**Comment by rkooo567** [comment]
Okay. Every test seems to pass. Closing it!!

**Review by ericl — APPROVED** [review]

**Pull request merged**
