### PR TITLE
[flaky] Split test_failure_2 into 2

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Split test_failure_2 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
I'm rerunning the testing 3 times to make sure it's ok.

**Comment by iycheng** [comment]
First one looks good. retry now

**Comment by iycheng** [comment]
retry 3

**Comment by ericl** [comment]
Isn't the issue that ::test_parallel_actor_fill_plasma_retry[ray_start_cluster_head0] -- Test timed out at 2021-05-05 19:36:38 UTC --
 is hanging forever?

**Comment by iycheng** [comment]
@ericl  I run about 600 times `bazel test --test_output=all --test_timeout=1200 --cache_test_results=no --runs_per_test=1000 //python/ray/tests:test_failure_2`
It stopped due to out of disk.

There no timeout. Logs are [here](https://gist.github.com/iycheng/470105b2dd43a081670e01f907275d92) 

But there are some failures, which is because `address is in use`. It probably is because `ray stop` failed to kill all processes and I met that before. But I didn't reproduce the failure in the CI testing.

```
(raylet)   File "/home/ubuntu/ray/python/ray/_private/metrics_agent.py", line 74, in __init__
(raylet)     prometheus_exporter.new_stats_exporter(
(raylet)   File "/home/ubuntu/ray/python/ray/_private/prometheus_exporter.py", line 333, in new_stats_exporter
(raylet)     exporter = PrometheusStatsExporter(
(raylet)   File "/home/ubuntu/ray/python/ray/_private/prometheus_exporter.py", line 266, in __init__
(raylet)     self.serve_http()
(raylet)   File "/home/ubuntu/ray/python/ray/_private/prometheus_exporter.py", line 320, in serve_http
(raylet)     start_http_server(
(raylet)   File "/home/ubuntu/.local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 149, in start_wsgi_server
(raylet)     httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)
(raylet)   File "/home/ubuntu/miniconda3/lib/python3.8/wsgiref/simple_server.py", line 154, in make_server
(raylet)     server = server_class((host, port), handler_class)
(raylet)   File "/home/ubuntu/miniconda3/lib/python3.8/socketserver.py", line 452, in __init__
(raylet)     self.server_bind()
(raylet)   File "/home/ubuntu/miniconda3/lib/python3.8/wsgiref/simple_server.py", line 50, in server_bind
(raylet)     HTTPServer.server_bind(self)
(raylet)   File "/home/ubuntu/miniconda3/lib/python3.8/http/server.py", line 138, in server_bind
(raylet)     socketserver.TCPServer.server_bind(self)
(raylet)   File "/home/ubuntu/miniconda3/lib/python3.8/socketserver.py", line 466, in server_bind
(raylet)     self.socket.bind(self.server_address)
(raylet) OSError: [Errno 98] Address already in use
```

**Review by ericl — APPROVED** [review]
Hmm ok maybe we can merge and see. Btw, LINT failing (rebase?)

**Pull request merged**
