### PR TITLE
[rllib] Fix torch c51 dqn

### PR DESCRIPTION
**Pull request by gbartyzel**
## Why are these changes needed?

Currently, it is not possible to train a c51 torch agent. The output shape of the value head in DqnTorchModel should be equal to the num_atoms (now it is equal to 1). Also in the current implementation, the noisy option doesn't affect the value head. There are also minor fixes in QLoss, like target probs should be detached before loss calculation. 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
Hmm @Souphis it looks like `TestExplorations.test_td3` is failing because of this?

Is it possible to investigate that failure?

**Comment by Souphis** [comment]
I don't think that this PR is related to this failure, but I will investigate this.

**Comment by sven1977** [comment]
@Souphis , thanks for this PR! Taking a look at the failing test. I think it's not related to this PR, though, so should be good, but I'll confirm. ...

**Comment by Souphis** [comment]
I ran tests once again locally, both td3 and dqn passed them. So, I think that this error is not related to this PR.

**Comment by sven1977** [comment]
Merged with master, which has a fix for this test case. Waiting for tests to pass again. ...

**Comment by sven1977** [comment]
@Souphis , agree. Will merge as soon as everything passes. Should be today :)

**Review by sven1977 — APPROVED** [review]
Thanks for the fixes @Souphis !

**Pull request merged**
