### PR TITLE
Initialize some variables in constructor instead of header file.

### PR DESCRIPTION
**Pull request by robertnishihara**
Related to #3592.

### CODE REVIEW

**Comment by robertnishihara** [comment]
Strangely, #3592 seems to have introduced an error for me (though this doesn't make any sense).

If you do 

```python
import ray
ray.init()
```

on the deep learning AMI `ami-3b6bce43`, it fails with

```
In [2]: ray.init()
WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2018-12-23_07-32-54_51121/logs.
Waiting for redis server at 127.0.0.1:40071 to respond...
Waiting for redis server at 127.0.0.1:59940 to respond...
Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
Starting the Plasma object store with 20.0 GB memory using /dev/shm.
*** Aborted at 1545550375 (unix time) try "date -d @1545550375" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 51187 (TID 0x7f13ae703740) from PID 0; stack trace: ***

======================================================================    @     0x7f13ae0d4390 (unknown)

View the web UI at http://localhost:8890/notebooks/ray_ui.ipynb?token=cbb8bf7cd188268dd2dd72e44601f76aaf947fe35d3a1441
======================================================================
    @           0x4d3df0 flatbuffers::vector_downward::reallocate()

    @           0x4d3fde flatbuffers::FlatBufferBuilder::EndTable()
    @           0x58efd3 plasma::SendConnectRequest()
    @           0x5751ef plasma::PlasmaClient::Impl::Connect()
    @           0x5753bc plasma::PlasmaClient::Connect()
    @           0x55ee30 ray::ObjectStoreNotificationManager::ObjectStoreNotificationManager()
    @           0x51b243 ray::ObjectManager::ObjectManager()
    @           0x4c1e34 ray::raylet::Raylet::Raylet()
    @           0x4b1892 main
    @     0x7f13ad270830 __libc_start_main
    @           0x4b7451 (unknown)
```

This looks like a flatbuffer error, which could be related to a mismatch with Arrow (see e.g., #3559).

**Comment by atumanov** [comment]
1. we need to understand what it is about the conda env that makes this fail, because it doesn't fail on any other conda environments (linux or macosx) that I've tried: both py27 and py36. Ray install ships both Ray and Arrow in both cases. It's unclear why it would succeed everywhere except in this environment.
2. The change to ctor initialization list was entirely unnecessary. C++11 allows this initialization and it's clean:
```
cat hello.cc
#include <iostream>

using namespace std;

class Foo {
  public:
    int getx() {return x;}

    void setx(int newx) {x = newx;}

  private:
    int x = 1;

};

int main() {
  Foo fooobj;
  cout << fooobj.getx() << endl;
  fooobj.setx(5);
  cout << fooobj.getx() << endl;

  return 0;
}

$ ./hello
1
5
```

Tested with valgrind : 
```
$  valgrind --track-origins=yes --leak-check=full --show-leak-kinds=all --leak-check-heuristics=stdstring --error-exitcode=1 ./hello
==76059== HEAP SUMMARY:
==76059==     in use at exit: 0 bytes in 0 blocks
==76059==   total heap usage: 2 allocs, 2 frees, 73,728 bytes allocated
==76059==
==76059== All heap blocks were freed -- no leaks are possible
==76059==
==76059== For counts of detected and suppressed errors, rerun with: -v
==76059== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
and compiled as follows : `c++ --std=c++11 -Wall -Werror -pedantic -o hello hello.cc`

**Comment by atumanov** [comment]
https://en.cppreference.com/w/cpp/language/data_members

**Review by atumanov — APPROVED** [review]

**Comment by atumanov** [comment]
merging to try new wheels on DLAMI

**Pull request merged**
