### PR TITLE
[RFC] Eliminate free-floating "similar by convention" util functions from Train

### PR DESCRIPTION
**Pull request by ericl**
Signed-off-by: Eric Liang <ekhliang@gmail.com>

## Why are these changes needed?

Currently, Train has a number of util functions that are "similarly named", this includes: `load_model_from_checkpoint` and `to_air_checkpoint`. This is an antipattern for these reasons:
1. These methods are hard to discover. They're not attached to a particular class, so don't show up with `help(TorchPredictor)`, for example. By being free-floating, these methods also aren't implementing or defining a programmatically defined interface, again harming discoverability.
2. Suppose you wanted to create a Torch checkpoint from a different format, e.g., Torch state dict. This would clash with the `to_air_checkpoint`, which has a fixed signature taking in a torch module already.

Also, after we implement https://github.com/ray-project/ray/pull/26600, the `load_model_from_checkpoint` method becomes redundant with the get/set preprocessor methods.

This PR demonstrates how the TorchPredictor utils could be cleaned up by moving the methods into a custom TorchCheckpoint. We'd have to do similar refactorings for the other predictor implementations.

Edit: updated to implement TorchCheckpoint instead of adding methods to TorchPredictor.

### CODE REVIEW

**Comment by amogkam** [comment]
Thanks for opening the RFC @ericl! 

Copying over from Slack, but the main discussion points here are 

1. Supporting standalone training workflows. I am just doing training and what extract out my trained model. But I don't want to do prediction. Do I need to use Predictor APIs for this?
2. 
> For example, you would never want to use torch.to_air_checkpoint except in conjunction with TorchPredictor.

This is not always the case. For example, in our CUJ, we use `to_air_checkpoint` inside the train loop to construct the Torch Checkpoint. Having a `to_air_checkpoint` that can be used inside the train_loop_per_worker also allows us to add framework specific checkpointing features, such as using Tensorflow saved model format, which users have asked for.
```python
def train_loop_per_worker():
    for i in range(10):
        session.report(metrics=..., checkpoint=ray.train.tensorflow.to_air_checkpoint(model))
```

cc @krfricke @xwjiang2010

**Comment by ericl** [comment]
> Supporting standalone training workflows. I am just doing training and what extract out my trained model. But I don't want to do prediction. Do I need to use Predictor APIs for this?

Yeah this is a good point. I'm starting to think that the most natural way forward is actually to add back framework-specific Checkpoint types, which should be lightweight wrappers around the base Checkpoint class only. In other words, the base Checkpoint class handles storage and storage format conversions, and the framework-specific class is only providing additional accessors, e.g.:

```
chkpt = TensorFlowCheckpoint.from_directory(...)
chkpt.get_tf_model()  # TF-specific method
chkpt.get_preprocessor()  # common method for all checkpoints
```

This is also very natural for (2):
```
def train_loop_per_worker():
    for i in range(10):
        session.report(metrics=..., checkpoint=TensorFlowCheckpoint.from_model(model))
```

And makes it easy to support (3) as well:
```
def train_loop_per_worker():
    for i in range(10):
        session.report(metrics=..., checkpoint=TensorFlowCheckpoint.from_state_dict(s))
```

> I'm not sure I'm following here. Isn't this just a matter of changing the signature. Whether as a standalone function or a method, they would both have the same problem, no?

To be clear, the problem is you'd need two methods. So you'd end up with:
```
to_air_checkpoint(TorchModule)
to_air_checkpoint_2(state_dict)
```

Which doesn't seem quite right.

**Comment by amogkam** [comment]
Yes I agree framework specific checkpoints seem like they might be the best way forward here

**Comment by jiaodong** [comment]
I might not have complete context of all our existing implementations but reading the context of this discussion I would like like add a few thoughts as user with no attachments of how things are currently done:

1) We should only surface framework specific {Trainer, Checkpoint, Predictor} interface and implementations as the user facing API and hide our abstractions that aims to be "generic" as implementation details from user. 
  - There're really not that many we actually need to care about: Pytorch / Jax / Tensorflow for DL; Sklearn and a few others
  - Tensor presentation of different DL frameworks can be quite different without a generic checkpoint format.
  - I currently saw a bunch of if/else of tensor checks scattered across AIR class implementations ... which makes it error prone, hard to maintain and could significantly hurt performance.
 
2) Each framework specific implementation should only care about its own native tensor type, without any conversion needed. Conversion should be handled by us, ideally implicitly at the integration points.
  - If user is writing Pytorch code with AIR, this should be the only format they need to deal with. This means at any point of the development and model lifecycle, they have freedom to use framework-native tooling out of the box without hitting sharp edges that we introduced for interop but only works in specific way.

**Comment by krfricke** [comment]
I'm a fan of framework-specific checkpoints. This makes it very easy to accommodate to exporting needs (e.g. can replace `export_formats` in Tune/RLLib), and introduces more flexibility here (exporting the main policy in rllib could yield a Torch/TensorflowCheckpoint which can then be served standalone).

To be clear, this means if we use the generic `Checkpoint.from_directory(path)` it will not auto-detect the framework type (we could add this later e.g. with mlflow checkpoints). Users can however use `TensorflowCheckpoint.from_directory(path)` (we should probably add some superficial validation for this).

**Comment by bveeramani** [comment]
Closing this PR in favor of #26777 because I lost context on this PR and it was faster to start from scratch.

**Pull request closed without merging**
