### PR TITLE
Make README render properly on PyPI.

### LINKED ISSUE #3449: Fix formatting of PyPI package description.
See https://pypi.org/project/ray/.

Note that we can test this out first at https://test.pypi.org/project/ray/.

### PR DESCRIPTION
**Pull request by robertnishihara**
This makes the readme render properly on PyPI (I think the `.. raw:: html` line was messing it up). Note that this makes the logo obnoxiously big, but I don't see a good way around this at the moment due to https://github.com/github/markup/issues/295. The test will catch some (but not all) formatting errors. This fixes #3449.

### CODE REVIEW

**Comment by richardliaw** [comment]
Maybe try: 

```
Tune: Scalable Hyperparameter Search
====================================

.. image:: images/tune.png
    :scale: 30%
    :align: center

```

from: https://raw.githubusercontent.com/ray-project/ray/master/doc/source/tune.rst

**Comment by robertnishihara** [comment]
@richardliaw thanks for the pointer, I tried it just now and it doesn't work. I think GitHub intentionally strips this information. I think the size is ok though.

**Review by pcmoritz — APPROVED** [review]
Agreed it looks a little too large, if somebody has a solution that'd be great. Until then it's better than what we have now.

**Comment by robertnishihara** [comment]
Thanks @pcmoritz in the future if we want to make it smaller we can have a version of the logo with lots of whitespace on the sides.

**Pull request merged**
