### PR TITLE
[Core] Remove request queue in CoreWorkerClient

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

The request queue or send queue in CoreWorkerClient was originally designed to act as a back pressure mechanism for actor tasks. However,

* It only prevents memory issues for the receiver side, the submitter side will still suffer from memory usage due to the `io_service_.post` in `CoreWorkerDirectActorTaskSubmitter::SubmitTask`. https://github.com/ray-project/ray/blob/fef15869223e75e5d15cdcd76d847b6f2fcaa680/src/ray/core_worker/transport/direct_actor_task_submitter.cc#L93
* The queue length is not configurable.
* We already have a another implementation for back pressure. https://github.com/ray-project/ray/pull/20894.

So I think it should be removed.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hey @kfstorm has this been discussed some people from our end? My concern is the backpressure feature is not well-documented & not turned on by default (the default is -1). So this will highly likely just cause regressions.  cc @scv119

**Comment by kfstorm** [comment]
> Hey @kfstorm has this been discussed some people from our end? My concern is the backpressure feature is not well-documented & not turned on by default (the default is -1). So this will highly likely just cause regressions. cc @scv119

As I stated in the description, the implementation in CoreWorkerClient is not really helpful because we just move the pressure from the receiver side to the submitter side.

BTW, we've run it in production for almost one year. No problem was found regarding this change when back pressure is disabled.

**Comment by kfstorm** [comment]
> > As I stated in the description, the implementation in CoreWorkerClient is not really helpful because we just move the pressure from the receiver side to the submitter side.
> 
> Hmm I don't think this claim is correct. The receiver side is more prone to OOM than the submission side in some workloads. For example, imagine one actor is called by many other actors/tasks. Senders are more likely to be distributed than receivers in this scenario, so adding backpressure on the sender side can prevent OOM better.
> 
> I think instead of just removing this mechanism, we should either (1) serve side rejects when it is overloaded (2) Set the default backpressure limit instead of -1?

You are right about the N x 1 relationship. But on the other side, 1 to N relationship is the opposite. right? With the implementation on CoreWorkerClient, the caller in 1 x N relationship is very likely to OOM, too.

I'm in favor of enabling backpressure by default. In this case, it's an API breaking change and it should only be included in 2.0. We definitely need to update documentations if we go this way.

**Comment by rkooo567** [comment]
Yeah so with the current client-side queuing; 

1 X N -> problematic
N X 1 -> less likely an issue

Without this, both scenarios are problematic (that's why I said it seems regression). 

Overall, I am positive about removing queueing on the client side. However, I think we need a way to preserve the safeguard 
 (e.g., backpressure or reject on server side) instead of just removing client-side queuing. I'd like to see other people's opinions here too!

**Pull request closed without merging**
