### PR TITLE
[tune] Test TF2.0, TF1.14, TF1.12 Tensorboard support

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

TF breaks APIs all the time, so we should test specifically on these
versions (which seem to be more commonplace).

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by richardliaw** [comment]
cc @dmadeka @pschafhalter

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Comment by richardliaw** [comment]
jenkins test tune

**Review by ericl — APPROVED** [review]

**Pull request merged**
