### PR TITLE
[Data][Docs] Remove next steps from "Getting Started" page

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

The next steps after reading Getting Started should be to continue reading the Data documentation, not leave it to go to another part of the documentation. This PR moves the information about the Ray dashboard to the Performance Tuning user guide.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]

**Comment by rkooo567** [comment]
What's the reasoning behind this? If you guys have a FaQ page for troubleshooting and can have a link to the dashboard there, I might be okay for this. Otherwise, I'd like to see an alternative proposal to add a dashboard link rather than just removing it.

**Comment by amogkam** [comment]
It feels out of place in the Next Steps...the next steps should be to continue reading the Ray Data documentation, not to leave it to go to the dashboard page.

would this be a reasonable alternative to place it https://docs.ray.io/en/latest/data/performance-tips.html#performance-tips-and-tuning?

**Comment by ericl** [comment]
Another way of emphasizing the dashboard more here would be show
screenshots of the dashboard in relevant sections, such as loading data /
transforming data user guides. This would be a little more work, but I
think would be more natural and also higher value to users.

**Comment by amogkam** [comment]
+1 to @ericl, and we can work with you guys on this. I'm still in favor of merging this PR though as dashboard seems out of place for Next Steps.

**Comment by rkooo567** [comment]
yeah that proposal sgtm. Is it possible to just do it in this PR instead of merging this?

**Comment by rkooo567** [comment]
I don't see a reason to merge this PR urgently (anyway it won't be changed until 2.5 is released)

**Comment by amogkam** [comment]
Ok lets go with your original proposal of moving to a different section @rkooo567? We can follow up later with dashboard usage screenshots.

**Comment by rkooo567** [comment]
Sounds good to me!

**Comment by amogkam** [comment]
@bveeramani could we make the change and we can merge this in?

**Comment by bveeramani** [comment]
> @bveeramani could we make the change and we can merge this in?

Yes, I will.

**Pull request merged**
