### PR TITLE
[sgd] Benchmark Fixes

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

As caught by ConeyLiu

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by ConeyLiu** [comment]
Hi @richardliaw, the data related to horovod seems should be fixed too.

**Comment by richardliaw** [comment]
thanks for the catch!

**Comment by ConeyLiu** [comment]
thanks, LGTM.

**Review by edoakes — APPROVED** [review]
LGTM

**Pull request merged**
