### PR TITLE
[runtime env][observability]print debug string for runtime env uri reference table

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
The debug log like this:
image

The debug state like this:
image

## Related issue number

https://github.com/ray-project/ray/issues/21108

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
Why don't we just adding it to debug state?

**Comment by SongGuyang** [comment]
@rkooo567 I saw the `DumpDebugState` just now. Right, I can add this debug string to the debug state. But I have one question, Do we need to reserve the debug log in https://github.com/ray-project/ray/pull/21309/files#diff-8da3bea9467d731259dfeceef772e4796143b0119d352a6b4654eaf678705b5eR28? Debug state seems like a periodical running function and We can't know the accurate state after each interface calling.

**Comment by SongGuyang** [comment]
@rkooo567

**Comment by rkooo567** [comment]
> @rkooo567 I saw the DumpDebugState just now. Right, I can add this debug string to the debug state. But I have one question, Do we need to reserve the debug log in https://github.com/ray-project/ray/pull/21309/files#diff-8da3bea9467d731259dfeceef772e4796143b0119d352a6b4654eaf678705b5eR28? Debug state seems like a periodical running function and We can't know the accurate state after each interface calling.

Hmm I think we can keep it, but maybe not on debug log. It might become too spammy when debug log is on (maybe separate system config is better?)

**Comment by SongGuyang** [comment]
> Yeah I think we can keep it in this case, The log is printed when new worker is started / used /deleted right?

Right. 
Let me add it to debug state.

**Comment by SongGuyang** [comment]
@rkooo567 Take a look again？

**Review by raulchen — APPROVED** [review]

**Pull request merged**
