### PR TITLE
[all_tests] Strict mode on by default for Ray Data

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This PR contains all the staging code for the following pieces:
- [x] Strict mode on by default
- [x] Pydoc changes, with strict mode on by default
- [x] Make AIR preprocessor and predictors compatible with strict mode

Separate TODOs:
- [x] REP / RFC for the rollout process
- [ ] Update data docs and examples (@bveeramani )

### CODE REVIEW

**Comment by ericl** [comment]
cc @amogkam

**Comment by ericl** [comment]
I'm working on fixing the pure data tests for this PR.

Per offline discussion @amogkam will help with fixing the preprocessor / predictor API changes necessary for getting those tests to pass.

**Review by pcmoritz — APPROVED** [review]

**Comment by ericl** [comment]
The computer_vision doc_code is also failing on master, so I think we are clear for CI tests. Still waiting on release test results.

**Comment by ericl** [comment]
Finished a run through of the release tests and I believe all the issues are now addressed as well (at least, those that launched successfully).

**Pull request merged**
