### PR TITLE
[GCS] allow re-subscribing to updates from nodes & actors

### LINKED ISSUE #21789: [Bug] Shutdown check failure after gRPC based pubsub is enabled.
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

cc @mwtian 

Update this patch (https://github.com/ray-project/ray/pull/21787) (adds a little delay to the function).

And then run `pytest -vs python/ray/tests/test_placement_group_mini_integration.py::test_placement_group_remove_stress`.

This will generate lots of 
Screen Shot 2022-01-21 at 2 41 34 PM

### Versions / Dependencies

Master

### Reproduction script

Read the main description 

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
When reconnecting GCS client to GCS, the client can attempt to re-subscribe existing keys and channels. One mitigation is to unsubscribe first before re-subscribing, but it is complicated to implement and only done for actors. Instead, we can ignore subscribing to the same key in the GCS client.

## Related issue number
Closes #21789

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
Looking into implementing resubscribing in `Subscriber`

**Comment by rkooo567** [comment]
> Looking into implementing resubscribing in Subscriber

Hmm maybe we don't always want to reconnect, so it might need to be a feature flag (or implementing it in a higher level looks okay to me). Reconnect means the subscriber callback needs to be idempotent, but I am not sure if it is the case for ref count / object eviction / obod

**Comment by mwtian** [comment]
> > Looking into implementing resubscribing in Subscriber
> 
> Hmm maybe we don't always want to reconnect, so it might need to be a feature flag (or implementing it in a higher level looks okay to me). Reconnect means the subscriber callback needs to be idempotent, but I am not sure if it is the case for ref count / object eviction / obod

Yeah, I want to investigate exposing an API for resubscribing to all entities in the subscriber. Then `GcsClient` will not need to track the entities to resubscribe itself. Workers do not need to call this.

**Comment by rkooo567** [comment]
Lmk when it is ready to review! (or just remove a tag! )

**Comment by mwtian** [comment]
As discussed in the past two days, we decided to invest the minimum in pub/sub for GCS client. The plan is to rely on this fix in the short term, and after GCS HA is done, there will be a more comprehensive investigation pub/sub vs syncer for GCS.

**Comment by iycheng** [comment]
I'm ok with this. I'll let @rkooo567 have a look.

**Review by fishbone — APPROVED** [review]
@mwtian will put a test as a followup PR.

**Pull request merged**
