### PR TITLE
Fix Serve long running test

### PR DESCRIPTION
**Pull request by simon-mo**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
This will still probably fail with json(). Is it the intended behavior?

**Comment by simon-mo** [comment]
Yes. It should be `.text` because we are returning a string

**Comment by rkooo567** [comment]
Ok. Let's merge this once it is ready.

**Comment by rkooo567** [comment]
@simon-mo Rllib errors seem to be unrelated. Can you merge this PR?
(I have no access)

**Pull request merged**
