### PR TITLE
Change serve tests docker image and enable micro benchmark

### PR DESCRIPTION
**Pull request by jiaodong**
# Summary 

- Need to update base docker image to nightly in order to avoid old numpy version issues
- Enabled serve_micro_benchmark in nighyly release tests

# Test plan

Anyscale job runs

https://beta.anyscale.com/o/anyscale-internal/projects/prj_UgMsAz5Rqk2iuvHmyrBH3S4E/clusters/ses_sMWFKv8zcdGEZWwPALenRN6C?command-history-section=head_start_up_log

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Review by krfricke — APPROVED** [review]

**Comment by simon-mo** [comment]
looks like its hanging? 
```
(pid=499) 2021-09-13 12:38:34,006       WARNING backend_state.py:1073 -- Deployment 'ForwardActor' has 1 replicas that have taken more than 30s to start up. This may be caused by waiting for the cluster to auto-scale or because the constructor is slow. Resources required for each replica: {'CPU': 1}, resources available: {}. component=serve deployment=ForwardActor
```

**Review by simon-mo — APPROVED** [review]

**Comment by jiaodong** [comment]
@simon-mo i think it's having some issues to get resource on anyscale as it runs fine on my laptop, this test also only requires 1 node.

**Comment by jiaodong** [comment]
So microbenchmark test  has been broken due to constructor failure since the beginning, but i can still run since our previous behavior will loop infinitely until the downstream handle is up on running to self-resolve. But this became a legit blocking failure now because we will just throw and rollback for exception like this in constructor.

Solution here is simply defer self.handle to call time and use cached instance actor handle for subsequent calls.

**Comment by edoakes** [comment]
event_test failing on master.

**Pull request merged**
