### PR TITLE
[GCS]add callback for RegisterSelf api, make it done first

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?

Before (redis accessor) raylet register self to gcs synchronously, then do other things. When we turned into service based accessor, everything become synchronous operation, we need to add a callback for this api, so other things would be done after registering done.

(found heartbeat can be(usually) arrived earlier than registering message. We wanna make sure every other message is later than registering, so we can take one node for dead when we receive heartbeat but not registered.)

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
LGTM. But what was the reason why this was synchronous in the first place?

**Comment by rkooo567** [comment]
@ffbin I won't add author-action-required. So please review it and add the label!

**Comment by ffbin** [comment]
> @ffbin I won't add author-action-required. So please review it and add the label!

Ok, thanks.

**Review by ffbin — APPROVED** [review]
LGTM

**Comment by WangTaoTheTonic** [comment]
> LGTM. But what was the reason why this was synchronous in the first place?

At first we use redis accessor to register self. In order to insure register happens before everything so it was made synchronous.
Later we introduced service based accessor in which we used grpc to register, which makes all interfaces asynchronous.

No matter it is synchronous or asynchronous, register happening first is what we need.

**Review by raulchen — APPROVED** [review]

**Pull request merged**
