### PR TITLE
 add ray on yarn project

### PR DESCRIPTION
**Pull request by SongGuyang**
## What do these changes do?

- Add the ray on yarn project to the folder "devops/yarn" .
- This is a java project, which include ray on yarn client and appMaster. You can use this project to deploy a ray cluster on yarn environment.
- Please read the file ''devops/yarn/README.rst" to get the detail usage.
- Future works:
  * support deploy multiple language version, E.g ray java version.
  * support an integrated failover implement.

## Related issue number

The issue https://github.com/ray-project/ray/issues/2214

### CODE REVIEW

**Comment by imzhenyu** [comment]
@robertnishihara @pcmoritz please take a look and see whether there are more nits to be fixed. Get some people in Alibaba want to trying this from your repo:)

**Comment by robertnishihara** [comment]
Thanks @SongGuyang and @imzhenyu.

It'd be great if someone who has more experience with Yarn can take a look.

This is all in Java, but I assume that's just because Yarn uses Java? And that this will still allow the user to use Python?

**Comment by SongGuyang** [comment]
@robertnishihara Yes, the java code is just the yarn client and yarn appMaster modules.  We could setup a ray cluster which is implemented by any language(python cluster or java cluster). In fact, you can modify the run.sh script to change your processes running pattern. Please see the README and run.sh to know any more.

**Comment by ericl** [comment]
[closing stale issue]

**Pull request closed without merging**
