### PR TITLE
Add a nicer warning message when you pass the wrong thing to ray.wait()

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

I'm constantly passing the wrong thing to ray.wait (usually a single objectId), and the error message was pretty confusing before (failing to index into the object). This improves the message.

### CODE REVIEW

**Comment by pcmoritz** [comment]
@ericl Want to fix the the PythonModeTest and get this merged for 0.3.0?

**Comment by ericl** [comment]
That should do it I think

**Comment by robertnishihara** [comment]
@ericl, I made some small aesthetic changes and added a test.

I also made the list check a little stricter. My concern was that the prior code would succeed even if a dictionary was passed in (because applying `list()`) to a dict returns a list of the keys.

**Comment by robertnishihara** [comment]
Ok, I just realized you're actually using `ray.wait` this way because we're seeing the Travis error

```
======================================================================
ERROR: testAbruptReturn (__main__.TrainableFunctionApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/trial_runner_test.py", line 143, in testAbruptReturn
    "script_min_iter_time_s": 0,
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/tune/tune.py", line 77, in run_experiments
    runner.step()
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/tune/trial_runner.py", line 77, in step
    self._process_events()
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/tune/trial_runner.py", line 159, in _process_events
    [result_id], _ = ray.wait(self._running.keys())
  File "/home/travis/.local/lib/python3.6/site-packages/ray-0.2.2-py3.6-linux-x86_64.egg/ray/worker.py", line 2232, in wait
    type(object_ids)))
TypeError: wait() expected a list of ObjectID, got <class 'dict_keys'>
```

in  `python test/trial_runner_test.py`. I'll just cast to `list` in that test.

**Comment by ericl** [comment]
Hm that probably breaks this too https://github.com/ray-project/ray/blob/master/python/ray/tune/trial_runner.py#L158

(Though the tests seem to pass?)

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
