### PR TITLE
adding run quickstart button to ray serve stable diffusion tutorial

### PR DESCRIPTION
**Pull request by chris-ray-zhang**
Screenshot 2024-09-06 at 4 47 01 PM

### CODE REVIEW

**Review by GeneDer — APPROVED** [review]
Oh this is very cool! Just wondering if there is a way we can allow existing customers jumping to that page directly and not to the register page, but not a blocker.

**Review by saihaj — APPROVED** [review]

**Comment by chris-ray-zhang** [comment]
> Oh this is very cool! Just wondering if there is a way we can allow existing customers jumping to that page directly and not to the register page, but not a blocker.

Hi Gene, do you mean jumping directly into the Anyscale template?

**Comment by GeneDer** [comment]
More or less. Supposedly I already have an account and am logged in, it would be nice to get to that temple page directly. For none anyscale customer I understand this will probably redirect them to the template page after they sign up.

**Comment by chris-ray-zhang** [comment]
> More or less. Supposedly I already have an account and am logged in, it would be nice to get to that temple page directly. For none anyscale customer I understand this will probably redirect them to the template page after they sign up.

Yes if you are already logged in, it will drop you directly into the template page. You can try yourself with this example here: https://docs.ray.io/en/latest/data/examples/pytorch_resnet_batch_prediction.html

I've also attached a loom video for your reference
https://www.loom.com/share/7fd8f9a9a8d94885b470faa56e029443

**Comment by GeneDer** [comment]
Oh I see, so I guess once this is merged. The docs page will render the url to `/template-preview` path? (the one in the PR is going to `/register` that's why I was wondering in the first place)
image

**Comment by chris-ray-zhang** [comment]
> Oh I see, so I guess once this is merged. The docs page will render the url to `/template-preview` path? (the one in the PR is going to `/register` that's why I was wondering in the first place) image

Ah i see. great callout. let me check

**Comment by chris-ray-zhang** [comment]
> > Oh I see, so I guess once this is merged. The docs page will render the url to `/template-preview` path? (the one in the PR is going to `/register` that's why I was wondering in the first place) image
> 
> Ah i see. great callout. let me check

yes it should automatically redirect with the redirectTo param @saihaj can you pls confirm?

**Pull request merged**
