### PR TITLE
Revert "Upgrade grpcio to a secure version (#37398)"

### PR DESCRIPTION
**Pull request by rkooo567**
Screen Shot 2023-07-14 at 9 28 53 AM
This reverts commit 229c70bfdd22683db5430d6568b116d62ffd79e1.

## Why are these changes needed?

Seems like this PR breaks some of master tests ( grpc :( )

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
I think we should revert 61401dad86

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/37427 @jjyao

**Review by jjyao — APPROVED** [review]

**Comment by krfricke** [comment]
This broke master completely - revert revert or can we forward fix? cc @jjyao @rkooo567

**Comment by krfricke** [comment]
Screenshot 2023-07-14 at 12 58 10

**Comment by jjyao** [comment]
I'll have a fox forward soon

**Comment by rkooo567** [comment]
Hmm we should probably do the forward fix. I believe @jjyao is taking a look at it now

**Pull request merged**
