### PR TITLE
[serve] Don't pass full `Request` object in release tests

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

This is not expected to work; must pass the body or params directly.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by GeneDer — COMMENTED** [review]
Kinda wondering what error does this throw before the change? And how bytes help to fix the issue? Neither is json serializable so probably not related to that.

Also, is it tested? And should we also add a doc somewhere (maybe in [http guide](https://docs.ray.io/en/master/serve/http-guide.html) noting request object can't be recursive passed?

**Review by shrekris-anyscale — APPROVED** [review]

**Comment by edoakes** [comment]
> Kinda wondering what error does this throw before the change? And how bytes help to fix the issue? Neither is json serializable so probably not related to that.
> 
> Also, is it tested? And should we also add a doc somewhere (maybe in [http guide](https://docs.ray.io/en/master/serve/http-guide.html) noting request object can't be recursive passed?

It throws a bunch of error messages in the release test but we aren't actually checking that the requests succeed 😞 I'd like to rework the test to make it more useful.

Bytes fixes it because bytes are trivially serializable for `DeploymentHandle` calls. Let me make sure it's explicitly documented.

**Comment by sihanwang41** [comment]
@edoakes , are you going to cherry pick into the release branch? hopefully this can fix the release test failures in the release branch 🙏

**Comment by GeneDer** [comment]
Thanks Ed! yea, we should get this cherry picked and fix the release tests. Can rework the release tests and docs later :)

**Comment by edoakes** [comment]
it's picked: https://github.com/ray-project/ray/pull/41874

**Pull request merged**
