### PR TITLE
[azure][autoscaler] Fix Azure autoscaler node naming and deletion delays

### LINKED ISSUE #25971: [Azure cluster launcher] Deletion takes ~10 minutes without stopped node caching, fast with stopped node caching
### What happened + What you expected to happen

This came up in a [Discuss post](https://discuss.ray.io/t/question-about-the-cache-stopped-nodes-option-in-the-cluster-yaml-file/6242?u=cade). The user highlights confusing, undesired behavior where the Azure cluster launcher waits for virtual machines to completely terminate (~10 minutes) when `cache_stopped_nodes=False`. The expected behavior is that node removal is fast, as is the behavior when `cache_stopped_nodes=True`. "Fast" here means `idle_timeout_minutes`.

The fix is to remove this blocking [`wait`](https://github.com/ray-project/ray/blob/fa32cb7c401f5afa9a7cfb160c22aa62578af1ee/python/ray/autoscaler/_private/_azure/node_provider.py#L309), so that the node provider makes the request to terminate the virtual machine, but does not block waiting for termination.

More context:
* https://discuss.ray.io/t/question-about-the-cache-stopped-nodes-option-in-the-cluster-yaml-file/6242/10?u=cade

### Versions / Dependencies

I presume the user tested on latest released Ray, but not sure. The root cause [is present in the 1.13 branch](https://github.com/ray-project/ray/blob/releases/1.13.0/python/ray/autoscaler/_private/_azure/node_provider.py#L309).

### Reproduction script

Use [example-full.yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/azure/example-full.yaml) with [`cache_stopped_nodes=True|False`](https://github.com/ray-project/ray/blob/c3ac6fcf3fcc8cfe6930c9a820add0e187bff579/doc/source/cluster/config.rst#provider) and `idle_timeout_minutes=1`

### Issue Severity

Low: It annoys or frustrates me.

### LINKED ISSUE #31538: [Ray Azure Autoscaler] new unique_id generation process leads to Azure killing & relaunching running VMs
### What happened + What you expected to happen

@gramhagen @richardliaw 

The new release of Ray 2.1 and 2.2 creates a bug where `unique_id` is a fixed formula instead of old `uuid4()` random one. 
The problem is, b/c Ray by default launches 5 instances and gradually scale up, the new `unique_id` scheme will keep **re-using a pool of 5 unique ids**  and Azure as a result, will keep killing and restarting existing healthy running VMs.

You won't be able to scale more than 5, and also, your existing running VMs will constantly be killed and then relaunched.

This is old (Ray 2.0): https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/python/ray/autoscaler/_private/_azure/node_provider.py#L224

This is new: (Ray 2.1 or 2.2): https://github.com/ray-project/ray/blob/f1b8bfd219a98da69a612558cbae32441d98ca60/python/ray/autoscaler/_private/_azure/node_provider.py#L226

This is a pretty serious bug IMO.

### Versions / Dependencies

Ray = 2.1/2.2 (<= 2.0 is fine)

### Reproduction script

Just launch a cluster and you will see it.

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by gramhagen**
## Why are these changes needed?

This reverts prior changes to node naming which led to non-unique names, causing constant node refreshing
Currently the Azure autoscaler blocks on node destruction, so that was removed in this change

## Related issue number

Closes #31538 
Closes #25971

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by gramhagen** [comment]
tested this locally, and it looks good to me.

**Comment by wuisawesome** [comment]
PR seems pretty reasonable, though just taking a step back @gramhagen do you know if there's an easy way we can test these types of things in CI?

**Comment by gramhagen** [comment]
> PR seems pretty reasonable, though just taking a step back @gramhagen do you know if there's an easy way we can test these types of things in CI?

i'd love for that to happen but I'm not sure the best way to do that. the most thorough way would be to deploy a cluster to azure and confirm the head and worker node are healthy, then tear-down the resources.

there are some things you can do to lint the ARM template portion of this, but it wouldn't give you much of guarantee that things are working, just a flag if things are really messed up.
- https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit
- https://github.com/marketplace/actions/arm-ttk

**Review by wuisawesome — APPROVED** [review]
lgtm

**Comment by wuisawesome** [comment]
@gramhagen do you mind rebasing and doing the DCO?

**Comment by gramhagen** [comment]
> @gramhagen do you mind rebasing and doing the DCO?

ah, right forgot about that.

**Comment by gramhagen** [comment]
@wuisawesome anything else needed to close this?

**Comment by wuisawesome** [comment]
> @wuisawesome anything else needed to close this?

Nope sorry about the delay

Test failures look unrelated, merging

**Pull request merged**
