### PR TITLE
[core][release] threaded_actors_stress_test release lock before sleeping

### LINKED ISSUE #33219: [core][nightly] threaded_actors_stress_test failed
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1433#0186be33-bc96-4a0c-92e9-b9fd8a8931d8

The test timed out. However, I noticed even the successful run has been hitting very close to the 1hr timeout period. 

Looks like the inner loop (waiting for all actors to get pi) never completes (in this case, timeouts) or only complete once (almost hitting 1hr). I tried locally and it seems there is some straggler actor that's slow to return from `get_pi`, likely due the compute thread using all the CPUs and wasn't able to put results to unblock the `get_pi`

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
The other writer `do_compute` is being starved. 

## Related issue number
Closes https://github.com/ray-project/ray/issues/33219

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
TODO: run the release test.

**Comment by rickyyx** [comment]
https://buildkite.com/ray-project/release-tests-pr/builds/30545

**Review by rkooo567 — APPROVED** [review]
Lmk the result.

**Comment by rkooo567** [comment]
release test failed?

**Comment by rickyyx** [comment]
Timeout waiting on wheels I beleived. Reran.

**Comment by rickyyx** [comment]
Oh actually - there's no wheel built, using master wheel: https://buildkite.com/ray-project/release-tests-pr/builds/30676

**Comment by rickyyx** [comment]
The output definitely makes more sense now
```
  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.63it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.47it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.63it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.00s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.50it/s]
Kill all actors.
Create actors.
Took 3.196321964263916 to create 24 actors
Start computation.

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:02<00:46,  2.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:02<00:00,  9.82it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.68it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.57it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s](MemoryMonitorActor pid=1833) INFO:root:Memory usage: 2.9203948974609375 / 62.77336502075195
(MemoryMonitorActor pid=1833) INFO:root:Top 10 process memory usage:
(MemoryMonitorActor pid=1833) INFO:root:PID     MEM     COMMAND
(MemoryMonitorActor pid=1833) 244       0.3GiB  /home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/s
(MemoryMonitorActor pid=1833) 29743     0.18GiB ray::PiCalculator.get_pi
(MemoryMonitorActor pid=1833) 29744     0.16GiB ray::PiCalculator.get_pi
(MemoryMonitorActor pid=1833) 29745     0.15GiB ray::PiCalculator.get_pi
(MemoryMonitorActor pid=1833) 29742     0.13GiB ray::PiCalculator.get_pi
(MemoryMonitorActor pid=1833) 1743      0.11GiB python stress_tests/test_threaded_actors.py --test-runtime 1800 --kill-interval_s 30
(MemoryMonitorActor pid=1833) 609       0.11GiB /home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen
(MemoryMonitorActor pid=1833) 27        0.09GiB /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session web_terminal_server --deploy
(MemoryMonitorActor pid=1833) 350       0.07GiB /home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboa
(MemoryMonitorActor pid=1833) 14        0.07GiB /home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/jupyter-lab --allow-root --ip=127.0.0.1 --no-

Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.55it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.62it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.54it/s]

  0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   0%|          | 0/24.0 [00:00<?, ?it/s]
Computing Pi:   4%|▍         | 1/24.0 [00:01<00:23,  1.01s/it]
Computing Pi:  83%|████████▎ | 20/24.0 [00:01<00:00, 19.66it/s]
....

```

**Comment by rickyyx** [comment]
It's now 1800 secs as expected:

**Pull request merged**
