### PR TITLE
Upgrade to cloudpickle 0.9.0.dev0

### PR DESCRIPTION
**Pull request by pcmoritz**
This includes support for enum classes, see https://github.com/cloudpipe/cloudpickle/pull/246.

This is to test things out, we should wait merging this until the final version of https://github.com/cloudpipe/cloudpickle/pull/246 is merged.

Related issues: #3996 #3917

### CODE REVIEW

**Comment by ogrisel** [comment]
There are some tests failing at `test_actors_and_tasks_with_gpus_version_two` which does not seem to be related to cloudpickle.

There are other Python 2.7 tests that fail because the enum module does not exist. This is weird because the Python 2.7 tests pass on my `tox -e py27` env for cloudpickle. Maybe older Python 2.7 versions did not have enums?

Anyway, it should be quite easy to do a conditional import for this module in cloudpickle.

**Comment by ogrisel** [comment]
I've just pushed a new commit to [cloudpipe/cloudpickle#246](https://github.com/cloudpipe/cloudpickle/pull/246) to make the dependency on enum34 optional (under Python < 3.4).

**Comment by ogrisel** [comment]
The failure in https://travis-ci.com/ray-project/ray/jobs/178328001 is suspicious (the operation lasts 19s instead of less than 10s). It could be caused by a performance regression in cloudpickle but this test does not seem to involve any dynamic class definition so I am not sure how  [cloudpipe/cloudpickle#246](https://github.com/cloudpipe/cloudpickle/pull/246) could cause this.

**Comment by ogrisel** [comment]
The failure in https://travis-ci.com/ray-project/ray/jobs/178328007 is weird: no output for 10min looks like a deadlock. Has this been observed before in ray or it this the first time?

**Comment by ogrisel** [comment]
There is also this `ArrowIOError: Encountered unexpected EOF` in `test_multithreading`:

https://travis-ci.com/ray-project/ray/jobs/178327998

**Comment by pcmoritz** [comment]
@ogrisel Thanks for all the help! The tests look good except the testBadParams5 one which I haven't seen fail. I'll look some more about the cloudpickle changes and the code that is involved here and see if I can spot anything suspicious.

**Comment by ogrisel** [comment]
Alright thanks @pcmoritz. Let me know if you have any questions on the new semantics for dynamic class defintions introduced in the cloudpickle PR.

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by pcmoritz** [comment]
@ogrisel The PR looks good to me!

**Comment by ogrisel** [comment]
> @ogrisel The PR looks good to me!

That's excellent news. You mean that the remaining CI failures on Ray are unrelated? If so, please put a comment on the cloudpickle PR :)

**Comment by simon-mo** [comment]
We already updated cloudpickle. Thanks for the PR! Closing

**Pull request closed without merging**
