### PR TITLE
[autoscaler] Increased head and worker storage to 25 GiB

### PR DESCRIPTION
**Pull request by pschafhalter**
## What do these changes do?

- Increased head and worker storage to 25 GiB for development YAML configuration file.

### CODE REVIEW

**Comment by ericl** [comment]
Thanks for looking into this! Would it also make sense to update the `example.yaml` file as well?

**Comment by robertnishihara** [comment]
Yes, I think that's a good idea. Even though the example uses a 50GB AMI already, people will probably modify it and having a template in place for changing the disk size would be useful.

**Review by ericl — APPROVED** [review]
Added a example conf to the main example.yaml

**Comment by richardliaw** [comment]
All builds except one mac build pass, and the test failure is unrelated (`test/runtest.py`)

**Pull request merged**
