### PR TITLE
[Dask on Ray] Use spread as default scheduling for dask on ray

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Dask on Ray works better with spread scheduling especially when data loading is involved. This PR uses the spread scheduling by default for dask on ray. 

There are times pack scheduling works better. This can be optimized in a different way in the future (better locality scheduling, or different scheduling strategy depending on function names)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
LGTM assuming the test fails before the change.

**Comment by clarkzinzow** [comment]
@rkooo567 I don't know if we should merge the first pass of this as spread scheduling for **all** Dask tasks, since that could degrade performance/stability for common Dask workloads. Data loading stability is a P1 for a few Dask-on-Ray users, but a bad performance/stability degradation could end up being a P0. Given that our benchmark suite is very small, we wouldn't know about such regressions until a user reports it, which is concerning.

Ideally, we'd like to use spread scheduling for data loading tasks and the default policy for all other tasks. I see a few options here:

1. (Current PR) Apply spread scheduling to all Dask tasks. Use benchmarking and user reports to identify performance/stability regressions, and push off a better solution until we're sure that this is an issue.
2. Use pattern matching on the Dask task names to only apply spread scheduling to data loading tasks. I think that all data loading tasks have something like `load` in the task name, so this could work pretty well as a stopgap solution.
3. Use a custom optimization pass to tag data loading high-level graphs with a marker indicating that spread scheduling should be used. This would be a much less hacky, long-term solution, and the machinery developed for this would be useful for other Dask-on-Ray improvements (e.g. changing resource requests based on the type of Dask operation).

What do you think about seeing if (2) is doable? That should be low-effort if it's possible, and more directly targets the underlying issue of instability in Dask-on-Ray data loading.

**Comment by clarkzinzow** [comment]
If we go with (1), we should open a follow-up issue for benchmarking to make sure that this doesn't cause a performance/stability regression, and open an issue for eventually going with a long-term solution like (3).

**Comment by clarkzinzow** [comment]
If we go with (1), we should open a follow-up issue for benchmarking to make sure that this doesn't cause a performance/stability regression on common Dask-on-Ray workloads, and open an issue for eventually going with a long-term solution like (3).

**Review by ericl — CHANGES_REQUESTED** [review]
Good points @clarkzinzow. @rkooo567 how about making this a flag in the `enable_dask_on_ray(force_spread=True)` function for now then?

We should also change the documentation to recommend setting this for now.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
