### PR TITLE
Deprecate RuntimeContext.get(), use `RuntimeContext.context` instead.

### PR DESCRIPTION
**Pull request by jovany-wang**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — COMMENTED** [review]
Agree we should deprecate `get()` since we want to return xx_id as string.

Do we need to create another `context()` method or we just ask users to use the proper get_xx_id method directly? I guess I don't understand why we need `get()` method initially given it doesn't return all the runtime context properties.

**Comment by jovany-wang** [comment]
> I guess I don't understand why we need get() method initially given it doesn't return all the runtime context properties.

Because the `runtime_context` is not serializable, a `get()` method returns the states instead of the entity object.

But anyway, either solution should be better than `get()` I believe.

**Comment by jjyao** [comment]
@jovany-wang Do you know where `get()` is used? I did a quick check of the codebase and seems it's not used except in some tests.

> Because the runtime_context is not serializable, a get() method returns the states instead of the entity object.

The issue is that `get()` also doesn't return the full state of the entity object. For example, it doesn't return placement group id.

Seems we can simply deprecate it without introducing anything new? cc @rkooo567

**Comment by jovany-wang** [comment]
If we deprecate it, we should fix the serializing issue. It doesn't contain full states, but I guess it's enough to use. Maybe CC @rkooo567 for the initial thought.

**Comment by jjyao** [comment]
Actually why do we want to serialize runtime context?

**Pull request closed without merging**
