### PR TITLE
[Core] Remove alive keys from ray.nodes()

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Redundant key

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @virtualluke

**Review by wuisawesome — APPROVED** [review]
we may need to change some hardcoded strings, but lgtm. 

cc @ashione

**Comment by rkooo567** [comment]
cc @richardliaw I saw the "alive" key is better for application developers. Do you think we should keep that and instead remove "Alive"?

**Comment by richardliaw** [comment]
I think you can keep `Alive`. Don't forget to fix all the tests ;)

**Comment by jovany-wang** [comment]
I guess this change may make failures for some user applications because this is an API change as well.

**Comment by ashione** [comment]
I remember that it is compatible consideration to keep both 'alive' and 'Alive'. But it looks good to me to remove duplicated one. 
BTW, could you check all of tests and make sure that no python test could use it any more.

**Comment by richardliaw** [comment]
Also, @rkooo567 is there a reason to need to remove this?

I think a big issue is ray is that we do a lot of these minor changes, making it hard to upgrade.

**Comment by rkooo567** [comment]
Good points about backward compatibility. But ray.nodes is marked as debugging only, and having two same keys are a bit confusing in my opinion (as @virtualluke asked). I am not strongly thinking it is necessary, but if we really would like to ensure backward compatibility of this API, I’d like to standardize the API asap as @wuisawesome suggested before (and it will highly likely break the current semantics).

**Comment by richardliaw** [comment]
@rkooo567 the `(for debugging only)` statement was added in v1.0 (specifically in a commit on August 28, 2020), without raising any user warning/messaging; while the actual function itself has been here for much longer. I think an API that has not been marked as "debugging only" from the beginning of introduction and has not gone through proper user notification of this change should be treated as "public". 

If we want to make it treat it was semi-private and introduce backwards incompatible changes, how about let's first start raising user warning (with a `log_once` flag) saying that this is a debugging only, and then actually make any key changes after 2 releases?

**Pull request closed without merging**
