### PR TITLE
add RayExecutor

### LINKED ISSUE #29456: [Core] Implement Ray based concurrent.futures.Executor
### Description

https://docs.python.org/3/library/concurrent.futures.html#executor-objects

It would be very nice to have a ray based (so distributed) implementation of a `concurrent.futures.Executor`, an analogue of `concurrent.futures.ProcessPoolExecutor` simply working on a distributed cluster using Actors.

This would be similar to `ray.util.multiprocessing.Pool` with the important difference of supporting asyncio interfaces. 
One of the core strength of Ray is the asyncio support and this Feature request would continue Ray's progress on that front.

I found this issue [#1883](https://github.com/ray-project/ray/issues/1883) where other users expressed the same request in the past, which was incorrectly closed in my opinion when `cuncurrent.futures.Future` API compliance was added, and the remaining part of the request was ignored.

### Use case

The most useful use case would of course be for libraries and programs which already make use of the `concurrent.futures.ProcessPoolExecutor` interface for example. They would then be able to move to distributed by simply changing the import to use the ray version instead.

The other use case are the same as for `ray.util.multiprocessing.Pool`, where we would like to have Ray manage a pool of actors for us, but would like to be able to avoid blocking on results and instead use asyncio `loop.run_in_executor()` to be able to use await and handle many things concurrently.

What I personally would really like is the ability to have a managed pool of actors which can all make use of asyncio to avoid blocking on `ray.get` calls and the like. This way the submitted remote tasks can await other results and in the meantime handle other tasks. This can currently only be implemented with actors but the responsibility of scaling the actors and scheduling the work to them is on the shoulders of the developers using Ray, instead of being offered by Ray itself.

### PR DESCRIPTION
**Pull request by jeicher**
## Why are these changes needed?

After discussing the state of this PR with @rkooo567 and @jjyao I have created this new one to replace: https://github.com/ray-project/ray/pull/30826#issue-1471156849

## Related issue number

Closes #29456

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
thanks! I will merge the PR shortly. We may need a short RFC for the API semantics.

**Comment by GuillaumeDesforges** [comment]
Hey @rkooo567, I've taken over Johan on that topic on our side. :slightly_smiling_face: 
We'd love to see this work progress to the Ray project!
We will re-open a PR that is more up to date and we can work with.

**Review by aslonnie — COMMENTED** [review]
sounds like we are going to have a new PR for this? should we close this one for now?

**Comment by GuillaumeDesforges** [comment]
@aslonnie yes please :slightly_smiling_face: this PR is superseeded by https://github.com/ray-project/ray/pull/44922

**Pull request closed without merging**
