### PR TITLE
[serve] Fix DeploymentStatus enum to_proto

### LINKED ISSUE #36319: [Serve] Basic serve deployment example in documentation throws error with Python 3.11
### Description
The basic deployment example in "Key Concepts" of the Serve documentation throws an error when run with Python 3.11.  
https://docs.ray.io/en/latest/serve/key-concepts.html#serve-key-concepts-deployment

```
@serve.deployment
class MyFirstDeployment:
  # Take the message to return as an argument to the constructor.
  def __init__(self, msg):
      self.msg = msg

  def __call__(self):
      return self.msg

my_first_deployment = MyFirstDeployment.bind("Hello world!")
handle = serve.run(my_first_deployment)
```

### Expected behavior
Python 3.11 has experimental support in Ray 2.5, but it would be expected that the basic examples in the documentation would work. 

### Logs:
```
(ServeController pid=154501) INFO 2023-06-12 12:47:49,598 controller 154501 deployment_state.py:1298 - Deploying new version of deployment default_MyFirstDeployment.
(ServeController pid=154501) INFO 2023-06-12 12:47:49,630 controller 154501 deployment_state.py:1537 - Adding 1 replica to deployment default_MyFirstDeployment.
(HTTPProxyActor pid=154538) INFO:     Started server process [154538]
---------------------------------------------------------------------------
RayTaskError(ValueError)                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 handle = serve.run(my_first_deployment)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/api.py:544, in run(target, _blocking, host, port, name, route_prefix)
    530     deployment_parameters = {
    531         "name": deployment._name,
    532         "func_or_class": deployment._func_or_class,
   (...)
    541         "docs_path": deployment._docs_path,
    542     }
    543     parameter_group.append(deployment_parameters)
--> 544 client.deploy_application(
    545     name,
    546     parameter_group,
    547     _blocking=_blocking,
    548     remove_past_deployments=remove_past_deployments,
    549 )
    551 if ingress is not None:
    552     return ingress._get_handle()

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/client.py:44, in _ensure_connected.<locals>.check(self, *args, **kwargs)
     42 if self._shutdown:
     43     raise RayServeException("Client has already been shut down.")
---> 44 return f(self, *args, **kwargs)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/client.py:300, in ServeControllerClient.deploy_application(self, name, deployments, _blocking, remove_past_deployments)
    297     url = deployment["url"]
    299     if _blocking:
--> 300         self._wait_for_deployment_healthy(deployment_name)
    301         self.log_deployment_ready(deployment_name, version, url, tags[i])
    303 if remove_past_deployments:
    304     # clean up the old deployments

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/client.py:168, in ServeControllerClient._wait_for_deployment_healthy(self, name, timeout_s)
    165 start = time.time()
    166 while time.time() - start < timeout_s or timeout_s < 0:
--> 168     status_bytes = ray.get(self._controller.get_deployment_status.remote(name))
    170     if status_bytes is None:
    171         raise RuntimeError(
    172             f"Waiting for deployment {name} to be HEALTHY, "
    173             "but deployment doesn't exist."
    174         )

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/_private/auto_init_hook.py:18, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/_private/worker.py:2540, in get(object_refs, timeout)
   2538     worker.core_worker.dump_object_store_memory_usage()
   2539 if isinstance(value, RayTaskError):
-> 2540     raise value.as_instanceof_cause()
   2541 else:
   2542     raise value

RayTaskError(ValueError): ray::ServeController.get_deployment_status() (pid=154501, ip=172.31.205.52, actor_id=f8a11a1797548a78b16ce2cc01000000, repr=<ray.serve.controller.ServeController object at 0x7f806ab0f010>)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'DEPLOYMENT_STATUS_DeploymentStatus.UPDATING'

During handling of the above exception, another exception occurred:

ray::ServeController.get_deployment_status() (pid=154501, ip=172.31.205.52, actor_id=f8a11a1797548a78b16ce2cc01000000, repr=<ray.serve.controller.ServeController object at 0x7f806ab0f010>)
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/controller.py", line 779, in get_deployment_status
    return status[0].to_proto().SerializeToString()
           ^^^^^^^^^^^^^^^^^^^^
  File "~/sandbox/.venvs/py311/lib/python3.11/site-packages/ray/serve/_private/common.py", line 92, in to_proto
    return DeploymentStatusInfoProto(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ~/sandbox/.venvs/py311/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 556, in init
    field_value = _GetIntegerEnumValue(field.enum_type, field_value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/sandbox/.venvs/py311/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 494, in _GetIntegerEnumValue
    raise ValueError('Enum type %s: unknown label "%s"' % (
ValueError: Enum type ray.serve.DeploymentStatus: unknown label "DEPLOYMENT_STATUS_DeploymentStatus.UPDATING"
```

### Versions / Dependencies

Ray 2.5
Python 3.11.3
Ubuntu 22.04.1

### Reproduction script

```
@serve.deployment
class MyFirstDeployment:
  # Take the message to return as an argument to the constructor.
  def __init__(self, msg):
      self.msg = msg

  def __call__(self):
      return self.msg

my_first_deployment = MyFirstDeployment.bind("Hello world!")
handle = serve.run(my_first_deployment)
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by ddelange**
Fixes #36319

I think this will be covered by unit tests as soon as CI runs on cp311

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by ddelange** [comment]
@rickyyx I think there was a flake, could you re-run?

**Comment by ddelange** [comment]
@krfricke @rickyyx could you help get this small fix merged?

**Comment by ddelange** [comment]
cc @edoakes via recent serve commits

**Comment by ddelange** [comment]
cc @pcmoritz

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
Thanks @ddelange! Sorry I didn't see this PR sooner.

**Comment by ddelange** [comment]
no worries! thx 👍

**Comment by ddelange** [comment]
Hi :wave:

could this PR and https://github.com/ray-project/ray/pull/37258 be included in the 2.6.1 release?

**Comment by edoakes** [comment]
@ddelange yes we are planning for a 2.6.1 release shortly, let me make sure these are included

**Comment by edoakes** [comment]
@ddelange this and the other fix have been cherry-picked into 2.6.1 release branch: https://github.com/ray-project/ray/pull/37660

**Pull request merged**
