### PR TITLE
[core] Allow reuse of cluster address if Ray is not running

### LINKED ISSUE #27021: [Core] Ray start/stop/start does not work when using a custom temporary folder
### What happened + What you expected to happen

The changes introduced [here](https://github.com/ray-project/ray/pull/26678) have as side effect that the following logic no longer works:

Start a cluster with a custom temporary folder: `ray start --head --temp-dir /tmp/bla`
Now stop any active ray cluster using the typical: `ray stop`

Now there is nothing running anymore, but when you next run:  `ray start --head --temp-dir /tmp/bla`

You get  this error:
`ConnectionError: Ray is trying to start at 192.168.XXX.XXX:6379, but is already running at 192.168.XXX.XXX:6379. `

This due to the file `ray_current_cluster` not being deleted when using a non-default temporary directory. The `stop` command does not allow you to specify the `temp-dir` and as such it will not find `ray_current_cluster`  file. But when you then try to start ray again it will fail due to the file still being there. You can work around this by manually deleting the file or specifying a different port.

### Versions / Dependencies

Nightly

### Reproduction script

```
ray start --head --temp-dir /tmp/bla
ray stop
ray start --head --temp-dir /tmp/bla
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by stephanie-wang**
Signed-off-by: Stephanie Wang <swang@cs.berkeley.edu>

## Why are these changes needed?

Cluster address is now written to a temp file. Previously we raised an error if `ray start --head` tried to reuse the old cluster address in the temp file, even if Ray was no longer running. This PR allows `ray start --head` to continue if it can't find any GCS process associated with the recorded cluster address.

## Related issue number

Closes #27021.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
ah, this is a nice fix.

**Comment by scv119** [comment]
I think you need to change https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tests/test_ray_init.py?L88 as well.

**Comment by stephanie-wang** [comment]
> I think you need to change https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tests/test_ray_init.py?L88 as well.

Are you thinking of a different test? This one looks like it's still fine.

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
> Are you thinking of a different test? This one looks like it's still fine.
I thought this one should no longer throw exception, since the gcs hasn't been started.

should we also add a test to verify it works?

**Comment by stephanie-wang** [comment]
> > Are you thinking of a different test? This one looks like it's still fine.
> > I thought this one should no longer throw exception, since the gcs hasn't been started.
> 
> should we also add a test to verify it works?

Oh, the exception only applies to `ray start --head`. I think we should keep the error for trying to connect to a GCS that no longer exists.

Yeah, let me add a test!

**Pull request merged**
