### PR TITLE
[cuda] remove 11.5 and 11.6, add 12.3

### PR DESCRIPTION
**Pull request by aslonnie**
add newer cuda versions, and stop supporting cuda versions that do not support ubuntu 22.04

### CODE REVIEW

**Comment by aslonnie** [comment]
cc @matthewdeng @rkooo567 @sriram-anyscale

**Comment by rkooo567** [comment]
oh thought we are supporting 12.4?

**Comment by aslonnie** [comment]
> oh thought we are supporting 12.4?

@sriram-anyscale says we want 12.3

**Comment by can-anyscale** [comment]
maybe run one of those release tests that use the cuda... as the byod type to see if they still work

**Comment by aslonnie** [comment]
> maybe run one of those release tests that use the cuda... as the byod type to see if they still work

triggered one using gpu: https://buildkite.com/ray-project/release/builds/17225

or do you mean to trigger the cuda121 one(s)?

**Comment by aslonnie** [comment]
> maybe run one of those release tests that use the cuda... as the byod type to see if they still work

fwiw, the underlying image names are not changed, supposedly. only the base's image tags are changed.

let me trigger `workspace_template_finetuning_llms_with_deepspeed_llama_2_7b` maybe tomorrow.

**Comment by aslonnie** [comment]
> maybe run one of those release tests that use the cuda... as the byod type to see if they still work

ha, seems that I indeed missed some release test parts..

**Comment by aslonnie** [comment]
release test passes: https://buildkite.com/ray-project/release/builds/17227

**Review by can-anyscale — APPROVED** [review]
do we want to add a release test for 12.3.2?

**Comment by aslonnie** [comment]
> do we want to add a release test for 12.3.2?

I say yes.. @rkooo567 could you add one?

**Comment by aslonnie** [comment]
> > do we want to add a release test for 12.3.2?
> 
> I say yes.. @rkooo567 could you add one?

cc @matthewdeng @anyscalesam  too

**Comment by aslonnie** [comment]
will follow up with release test that uses 12.3

**Pull request merged**
