### PR TITLE
Add GRPC library into Bazel

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
We may use [GRPC](https://github.com/grpc/grpc) later on. This PR adds the GRPC library and the GRPC examples into our bazel building process. The main building process will not slowed down much by this PR. The directory of `grpc_example` can be removed after the real grpc proto buf definitions are added.

It looks like https://github.com/pubref/rules_protobuf is no longer maintained and moved to https://github.com/stackb/rules_proto . This rule will help us to reduce the building work of GRPC.

To test this GRPC example, run `bazel build //:grpc_example --verbose_failures`.
There will be a mesasge of `GRPC example path: /private/var/tmp/...XXX.../grpc_example` say `$GRPC_EXAMPLE_PATH`. 
Then we can start the server: `$GRPC_EXAMPLE_PATH/greeter_server` and a test client `python $GRPC_EXAMPLE_PATH/greeter_client.py`

The server will print following message:
```
Server listening on localhost:10086
Wed May 22 14:38:28 2019: Received greeting from: ray-client
Wed May 22 14:38:36 2019: Received greeting from: ray-client
```
The client will print following message:
```
Greeter client received: Wed May 22 14:38:36 2019: Hello ray-client
```

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by guoyuhong** [comment]
@zhijunfu

**Comment by robertnishihara** [comment]
@rsepassi is this the right way to incorporate gRPC? E.g., using https://github.com/stackb/rules_proto?

**Comment by raulchen** [comment]
1) did you try using this official rule? https://github.com/grpc/grpc/tree/master/src/cpp#bazel
2) We probably won't use gPRC directly from Python/Java (at least in the near future), given that we're re-writing worker core in C++. Maybe let's not introduce Python/Java grpc rules for now.
3) I feel that adding the examples isn't very useful. What do you think?

**Comment by robertnishihara** [comment]
We probably only need C++ for now.

**Comment by guoyuhong** [comment]
@robertnishihara @raulchen I thought we would use python and java at the beginning so I used  https://github.com/stackb/rules_proto . If we do not use python and java, the official rule is sufficient, though a bit complex. We need to call 3 functions other than 1 function. Moreover, I have a problem to build python lib using the official rule. I will close this PR since it is not complex to add GRPC to bazel. The first PR to rewrite the C++ worker can do so.

**Comment by robertnishihara** [comment]
@guoyuhong I think the first PR to rewrite the C++ worker (which I believe @raulchen is working on) should be separate from the gRPC changes, right?

**Comment by raulchen** [comment]
@robertnishihara yes, grpc doesn't depend on the new c++ core worker change. Because we'll only change worker-to-raylet and raylet-to-raylet communications to grpc for now. And these are all already in c++.

**Comment by guoyuhong** [comment]
@robertnishihara I mean the first PR that introduces the GRPC into our backend. It is not necessary to introduce this because it is very simple to add.

**Comment by robertnishihara** [comment]
Sounds good.

**Pull request closed without merging**
