### PR TITLE
[Core] Update Bazel (to 3.4.1), gRPC, boringssl, and absl as a precursor to gRPC streaming PR.

### PR DESCRIPTION
**Pull request by clarkzinzow**
Updates Bazel (to 3.4.1), gRPC, boringssl, and absl as a precursor to gRPC streaming PR. We isolate these dependency updates to this PR since they are producing Windows build failures, which should be easier to debug in isolation.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
```
com.google.devtools.build.lib.syntax.EvalException: Error applying patch /ray/thirdparty/patches/grpc-windows-python-header-path.patch: Cannot find file to patch (near line 13), old file name (a/third_party/py/python_configure.bzl) doesn't exist, new file name 
```
:( looks related

**Comment by clarkzinzow** [comment]
@scv119 Yep I probably just need to tweak the patch a bit, I optimistically thought that the patch should work without testing it. 😄

**Comment by clarkzinzow** [comment]
It appears that all MacOS jobs are timing out (I think?) due to compilation taking a good while, probably due to the timeouts not accommodating a cold Bazel cache. I'll try rerunning one of the jobs to see if it's able to benefit from a warm cache and pass.

**Comment by clarkzinzow** [comment]
Ah that's right, we can't rerun individual jobs. 😞

**Comment by clarkzinzow** [comment]
I'll try rerunning all of the tests after the Windows job finishes.

**Comment by rkooo567** [comment]
have a question about updating the bazel version; Is this necessary for grpc streaming? I am worried this will break many of us' dev environment (since many of us uses older versions probably).

**Comment by clarkzinzow** [comment]
> have a question about updating the bazel version; Is this necessary for grpc streaming? I am worried this will break many of us' dev environment (since many of us uses older versions probably).

Yes, it's necessary due to the gRPC update, since [gRPC uses `--incompatible_use_toolchain_transition`](https://github.com/grpc/grpc/blob/7ccb55ea73b29d4df4dc8628f776d5856f8890e5/third_party/upb/bazel/upb_proto_library.bzl#L314) which was [released in Bazel 3.4](https://blog.bazel.build/2020/07/13/bazel-3-4.html#rules). And yes, everyone should upgrade their local Bazel, but that shouldn't involve much more than rerunning [ci/travis/install_bazel.sh](https://github.com/ray-project/ray/blob/master/ci/travis/install-bazel.sh).

**Comment by iycheng** [comment]
I'm ok to update bazel. I have one question here if I'm using the old version of bazel and if I run it, will it complain about the version is incompatible? I feel we'll have issues like this when upgrading the components in the future and it's not avoided. 
But if we can make sure the developers understand what's the action item to fix it, it should be good enough.

**Comment by clarkzinzow** [comment]
> I have one question here if I'm using the old version of bazel and if I run it, will it complain about the version is incompatible?

If you're using the old version of Bazel, trying to compile Ray will fail during the loading phase since a target within gRPC will have an incompatible definition (linked to above).

> I feel we'll have issues like this when upgrading the components in the future and it's not avoided.
But if we can make sure the developers understand what's the action item to fix it, it should be good enough.

Agreed, I think that we should have a minimum Bazel version check for this reason. Shouldn't involve much more than adding the following to our `WORKSPACE`:
```
load("@bazel_skylib//lib:versions.bzl", "versions")
versions.check(minimum_bazel_version = "4.0.0")
```

**Comment by clarkzinzow** [comment]
@iycheng @rkooo567 @scv119 Windows build is borked external to this PR, but the fact that it builds and that the tests start to run shows that this is no longer breaking the Windows build (before it would fail on build). I think that this is good to go?

**Comment by rkooo567** [comment]
I prefer to wait until it is available rn just in case. Do you know what happens there?

**Comment by clarkzinzow** [comment]
> Do you know what happens there?

Where? You mean why the Windows build is broken? This reverting PR will hopefully fix it: https://github.com/ray-project/ray/pull/17935

**Comment by rkooo567** [comment]
Yeah sorry 😂 you answered my question haha. I prefer to just wait a bit. Would that be okay for you? (Maybe 1-2 days delay)

**Comment by clarkzinzow** [comment]
@rkooo567 Yep that's fine! This isn't blocking any other work, I can work on the other gRPC streaming items in parallel with this PR.

**Comment by clarkzinzow** [comment]
Windows test failures are unrelated (all failing/flaky on master) and lint failure is unrelated and is [fixed in master](https://github.com/ray-project/ray/pull/17945), so I think this is ready to merge.

**Comment by clarkzinzow** [comment]
Added Bazel version check for 3.4.0. Example of error:
```
    Expected Bazel version 3.4.1 but found 3.2.0
    Starting local Bazel server and connecting to it...
    Loading: 0 packages loaded
    DEBUG: /mnt/data/workspace/ray/bazel/ray_deps_setup.bzl:66:14: No implicit mirrors used because urls were explicitly provided
    ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/4b0c7d95a1a2a417d84b6788f088ac1e/external/bazel_skylib/lib/versions.bzl:105:13: Traceback (most recent call last):
        File "/mnt/data/workspace/ray/WORKSPACE", line 19
                versions.check(<1 more arguments>)
        File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/4b0c7d95a1a2a417d84b6788f088ac1e/external/bazel_skylib/lib/versions.bzl", line 105, in versions.check
                fail(<1 more arguments>)
    Current Bazel version is 3.2.0; expected at least 3.4.0
    ERROR: error loading package 'external': Package 'external' contains errors
    INFO: Elapsed time: 3.041s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
```
The first line about the expected Bazel version is from the `setup.py`, the error is from the Bazel version check in the WORKSPACE. This don't necessarily have to be strictly in sync, since the minimum accepted Bazel version can be different than the current CI Bazel version.

**Review by fishbone — APPROVED** [review]

**Comment by clarkzinzow** [comment]
@richardliaw @ericl @edoakes Need a codeowner review of setup.py

**Review by richardliaw — APPROVED** [review]
setup approval

**Comment by rkooo567** [comment]
Consider merging master?

**Review by rkooo567 — APPROVED** [review]

**Review by edoakes — APPROVED** [review]

**Comment by clarkzinzow** [comment]
Failing Windows test is flaky on master, this appears to be ready to merge.

**Pull request merged**
