### PR TITLE
[CI] Build only one wheel for ray containers

### PR DESCRIPTION
**Pull request by aslonnie**
Build only one wheel for the related python version when building container images.

Beforehand, it is building all 4 wheels every time.

Also apply styling changes to the manylinux wheel building script.

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
I also launched a build on the branch pipeline, and the container building seems to be doing the right thing:

https://buildkite.com/ray-project/oss-ci-build-branch/builds/3720#0187de6f-8090-4375-9404-a1b4cca3078f

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
https://buildkite.com/ray-project/oss-ci-build-branch/builds/3720#0187de6f-8090-4375-9404-a1b4cca3078f seems to save something like 20 mins? I am not sure because it might be affected by caching performance variance.

**Review by Yard1 — APPROVED** [review]

**Comment by can-anyscale** [comment]
Nice! Simple fix, big wins

**Pull request merged**
