### PR TITLE
add metadata put in workflow

### PR DESCRIPTION
**Pull request by lchu6**
## Why are these changes needed?

Add metadata to workflow.  Currently there is no option for user to attach any metadata to a step or workflow run, and workflow running metrics (except status) are not captured nor checkpointed.

We are adding various of metadata including:

1. step-level user metadata.  can be set with `step.options(metadata={})`
2. step-level pre-run metadata.  this captures pre-run metadata such as step_start_time, more metrics can be added later.
3. step-level post-run metadata.  this captures post-run metadata such as step_end_time, more metrics can be added later.
4. workflow-level user metadata. can be set with  `workflow.run(metadata={})`
5. workflow-level pre-run metadata.  this captures pre-run metadata such as workflow_start_time, more metrics can be added later.
6. workflow-level post-run metadata.  this captures post-run metadata such as workflow_end_time, more metrics can be added later.

## Related issue number

https://github.com/ray-project/ray/issues/17090

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
I think the high-level direction looks good, but we probably can improve the structure a little bit.
Here there are three metadata for workflow & step (6 in total):

For step metadata
- user meta
 - do it in commit step
- pre step meta
 - do it in commit step
- post step meta
 -  do it in checkpoint output

For workflow metadata
- user meta
 -  do it in run/run_async
 - pre meta/post meta
  - do it in workflow access

**Review by fishbone — CHANGES_REQUESTED** [review]
Thanks for the contribution! The highlevel direction looks good! Let's fix the comments and add some test and go with another round of review.

**Review by fishbone — CHANGES_REQUESTED** [review]
Really thanks for the updating! It looks nice! I have some comments there which shouldn't be too hard to fix

- let's try to keep workflow storage clean without logic related to the application
- except for user-facing API, let's rename metadata to user_metadata if it's from the user. Because for user-facing API, there is only one type of metadata so no confusion there. But internally, we have several kinds of metadata.
- once fixed them, please add some test cases you can follow the pattern here (python/ray/workflow/tests/test_basic_workflows_2.py)

**Comment by lchu-ibm** [comment]
> lint failure

@iycheng can you help me on this one?  I checked all failed checks and there is only one related - `lint` with the following error:
```
Warning, treated as error:
--
  | /ray/python/ray/workflow/common.py:docstring of ray.workflow.common.Workflow.run:27:Definition list ends without a blank line; unexpected unindent.
```

However, `scripts/format.sh` didn't give me any fix, and I couldn't find any problem with manual check on the docstring of `def run`.

**Review by fishbone — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
