### PR TITLE
Cleaning up remaining Local Mode Code

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
This fixes a few places that use the old LocalMode code and breaks an RLLib test.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Looks good, but there's a failure in the streaming test that I think was causing by your previous local mode PR:
https://travis-ci.com/github/ray-project/ray/jobs/311889350

**Comment by robertmash2** [comment]
Is local_mode being deprecated?  Is there another debugging modality preferred over local_mode?

**Comment by ijrsvt** [comment]
@robertmash2 No, its implementation was changed 2 months ago.

**Comment by ijrsvt** [comment]
And fails on even the latest versions of Ray?
I was also wondering what is the code that leads up to this?

**Pull request merged**
