### PR TITLE
Revert "[Datasets] Support ignoring NaNs in aggregations. (#20787)"

### PR DESCRIPTION
**Pull request by jjyao**
This reverts commit f264cf800ae80a2327de625dfc2db3613259f8e4.

## Why are these changes needed?
It failed `test_dataset`

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scv119 — APPROVED** [review]

**Review by ericl — APPROVED** [review]
LGTM. Very strange that this fails in master and not in the PR; seems to be nan vs None.

**Comment by scv119** [comment]
somehow this change doesn't enforce the pyarrow version in our prod env; i'm still getting pyarrow7.0.0

**Review by clarkzinzow — APPROVED** [review]

**Comment by clarkzinzow** [comment]
@ericl It looks like you never add `row_format=` to `.iter_rows()` as I called out in the [PR review](https://github.com/ray-project/ray/pull/21566#discussion_r785182337), so we can't prevent the Arrow --> Pandas conversion on `.iter_rows()` calls at the moment. Do you want to issue a follow-up PR or should I?

**Comment by ericl** [comment]
Ah feel free to add that, must have missed it.

**Comment by clarkzinzow** [comment]
@ericl No worries, I'll open a PR!

**Pull request merged**
