### PR TITLE
[core] GCS get all actors info no longer need to specify if dead jobs' actors need to be included

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
With https://github.com/ray-project/ray/pull/31019, we always have up to 10k dead actors cached by default. 

There's no existing usecase where we don't want to have actors from dead jobs (AFAIK) 

With https://github.com/ray-project/ray/pull/34348, one could filter actors with job id as well. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
cc @alanwguo is this flag used from you guys side?

**Comment by wuisawesome** [comment]
Don't have a strong opinion here. Just for historical context, IIRC the 10k actor limit and per-job cleanup were there to avoid leaking memory.

**Comment by rkooo567** [comment]
cc @rickyyx do you think it is hard to handle @alanwguo's comment in this PR? Seems like an easy change.

**Comment by rkooo567** [comment]
cc @scv119 to review gcs_service proto changes

**Comment by rickyyx** [comment]
TODO

**Pull request closed without merging**
