### PR TITLE
[Core] Turn on put_small_object_in_memory_store by default

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
Is there any reason this flag is off by default?

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
@stephanie-wang I recall this was implemented over the summer; any caveats?

**Comment by stephanie-wang** [comment]
I think it should be okay! Let's see how Travis feels about it.

**Review by stephanie-wang — APPROVED** [review]

**Comment by simon-mo** [comment]
Looks like `test_reconstruction: test_basic_reconstruction_actor_constructor[False]` failed consistently.

**Comment by simon-mo** [comment]
I don't have the bandwidth to work on this right now, closing. Others should feel free to open a new PR.

**Comment by simon-mo** [comment]
trying it again

**Comment by ericl** [comment]
I'd prefer we actually remove this feature to reduce the number of corner conditions, unless there is a compelling use case that requires it for performance.

**Comment by simon-mo** [comment]
sgtm, is there a PR to remove this feature to reduce dead code then? i will close this PR

**Pull request closed without merging**
