### PR TITLE
Update cloudpickle to version 0.5.6 (a couple commits after actually).

### PR DESCRIPTION
**Pull request by robertnishihara**
This brings in a number of recent cloudpickle fixes and may address #2685. This copies cloudpickle.py directly from https://github.com/cloudpipe/cloudpickle/commit/06b18afa11eca21576f1a463e9ace27857f3e28f.

### CODE REVIEW

**Comment by robertnishihara** [comment]
cc @mitar @suquark

**Comment by robertnishihara** [comment]
jenkins, retest this please

**Comment by suquark** [comment]
It's strange that `test/runtest.py::GlobalStateAPI::testFlushAPI` often fails in various tests. I have seen this many times.

**Comment by robertnishihara** [comment]
jenkins, retest this please

**Comment by robertnishihara** [comment]
jenkins, retest this please

**Comment by robertnishihara** [comment]
The error appears to be

```
Runner Thread raised error.
Traceback (most recent call last):
  File "/ray/python/ray/tune/function_runner.py", line 76, in run
    self._entrypoint(*self._entrypoint_args)
  File "/ray/python/ray/tune/examples/tune_mnist_keras.py", line 178, in <lambda>
    lambda cfg, rprtr: train_mnist(args, cfg, rprtr))
  File "/ray/python/ray/tune/examples/tune_mnist_keras.py", line 40, in train_mnist
    intra_op_parallelism_threads=args.threads,
AttributeError: 'Namespace' object has no attribute 'threads'
```

in `docker run -e RAY_USE_XRAY=1 --rm --shm-size=10G --memory=10G 11071230bfdb184c984566048cec671cf536cfbd087806d50f8c4d92ebfdc1a1 python /ray/python/ray/tune/examples/tune_mnist_keras.py --smoke-test`

**Comment by richardliaw** [comment]
odd; I guess somehow this causes cloudpickle to not capture the scope completely correctly?

**Comment by mitar** [comment]
BTW, I am guessing that eventually having also [this fix in](https://github.com/cloudpipe/cloudpickle/pull/197) might saves us some trouble. We are slowly porting code to use typing and it seems with Python 3.6 there could be troubles. So, maybe Ray could update cloudpickle to version which is includes that PR.

**Comment by mitar** [comment]
@suquark Could you check why tests here are failing?

**Pull request closed without merging**
