### PR TITLE
Inch toward using node UUID

### PR DESCRIPTION
**Pull request by dHannasch**
## Why are these changes needed?

Currently, several pieces of information are stored and retrieved for each node.

(Specifically, the object store address, the raylet socket name, and the node manager port. To be honest I'm shaky on why any of these things need to be stored and retrieved in the GCS, but the specifics are kind of beside the point: there's a general need to store and retrieve metadata about each node.)

Currently, `get_address_info_from_redis_helper()` pulls the `node_table()` from the GCS and looks for a matching IP address. This results in problems such as https://github.com/ray-project/ray/issues/11943.

The answer to the question "Can you use an IP address as a UUID?" is "W-well, yes, you...probably *could*." In the short term, we can make this work. https://github.com/ray-project/ray/pull/11944 is trying to solve the immediate problem, and will probably succeed. But if we keep trying to use IP addresses as UUIDs, the code needed to do so will only keep getting bigger, hairier and more complicated over time.

If information pertaining to each node needs to be retrieved from the GCS, then I think the UUID for each node should be used as the key.
In fact, the very call to `node_table()` that `get_address_info_from_redis_helper()` is making pulls a NodeID as a hex string.
https://github.com/ray-project/ray/blob/master/python/ray/state.py#L311
`"NodeID": ray.utils.binary_to_hex(item.node_id),`

If the UUID is generated in the moment that the node first reaches out to the head, then the node will also know its own UUID.

The head node doesn't know in advance what nodes might join. So while I haven't found where the node information gets added, I can say with certainty that, since it contains the node's IP address and ID, all that information must have come *from* the joining node in the first place, or was generated on-the-fly in response to that node joining. Therefore, it should be possible in principle for the node and the head to agree on a UUID in the moment it joins, so all the other information can be retrieved by the UUID instead of by IP address.

...unfortunately, I have not been able to figure out where first contact is made.

`get_address_info_from_redis()` and `get_address_info_from_redis_helper()` exist entirely in service to https://github.com/ray-project/ray/blob/master/python/ray/node.py. That's the only place they're ever called from.

Strangely, I don't see first contact being made in https://github.com/ray-project/ray/blob/master/python/ray/node.py before `get_address_info_from_redis()` is called. First contact *must* be made with the GCS before `get_address_info_from_redis()` is called, or else the GCS would not have an entry containing any information about this node. Perhaps first contact is made before the Node object is created, but I don't see any obvious place that happens either (e.g., in `scripts.start()`).

Coming at it from the other direction, the GCS must create these entries somehow. Where does the GCS live?
`node_table()` https://github.com/ray-project/ray/blob/master/python/ray/state.py#L297 flows down to `get_node_table()` https://github.com/ray-project/ray/blob/master/python/ray/includes/global_state_accessor.pxi#L48 to `GetAllNodeInfo()` https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_client/global_state_accessor.cc#L79 to `AsyncGetAll()` https://github.com/ray-project/ray/blob/master/src/ray/gcs/redis_accessor.cc#L549 to `client_table()` https://github.com/ray-project/ray/blob/master/src/ray/gcs/redis_gcs_client.cc#L129 ... poking around for where the information gets *added* turns up `GcsNodeManager::HandleRegisterNode()`.
https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_server/gcs_node_manager.cc#L131
This is, in fact, where the NodeID gets generated: https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_server/gcs_node_manager.cc#L134
`NodeID node_id = NodeID::FromBinary(request.node_info().node_id());`
So it looks like the NodeID *did* originally come from the node when it requested to join. So the node already has this ID! Somewhere! It's just a matter of comparing that ID to the `client_info["NodeID"]`.

Where are NodeIDs created?
https://github.com/ray-project/ray/blob/master/src/ray/gcs/redis_accessor.h#L101 creates a NodeID, but it says "the new GCS Client will no longer hold the local NodeID, so we use random NodeID instead." I don't really understand what's going on there, but whatever that ID is, it's not the local NodeID.
https://github.com/ray-project/ray/blob/master/src/ray/gcs/tables.h#L997 says "The reason for not using `local_node_id_`..." so apparently this `subscribe_id_` is not the local node ID either. But more importantly, ClientTable has the local node ID! Retrievable with `GetLocalClientId()` https://github.com/ray-project/ray/blob/master/src/ray/gcs/tables.h#L942 .

So it doesn't matter where first contact was made. The raylet has its local node ID.

...but it's not that simple. The raylet is running as a separate process. *The raylet* can fetch the local node ID that way. In fact, it turns out the raylet has the node ID at the top level, and that's where it's originally generated:
https://github.com/ray-project/ray/blob/master/src/ray/raylet/raylet.cc#L63

Still, all we need to do is retrieve the node ID from the raylet. I can't immediately think of a way to do that, but obviously `address='auto'` needs to fetch the Redis address from the raylet, so we can fetch the node ID the same way at the same time. How do we fetch the Redis address, again?
https://github.com/ray-project/ray/blob/master/python/ray/_private/services.py#L124
Oh...right...`find_redis_address()` crawls through the command line history.
...well, if that's the channel we have, then that's the channel we have. As long as we have a function that fetches the node ID along with the cluster ID (the address of the head *does* make sense as an ID for the cluster, since by definition that's how you find the cluster), the internals could change later.

This would mean, I suppose, adding `--node-id` to the raylet script as an additional command-line argument, similar to how https://github.com/ray-project/ray/pull/12038/files added `--node-ip-address` to the dashboard agent.
https://github.com/ray-project/ray/blob/master/python/ray/_private/services.py#L1457
(I guess that would imply generating the UUID up at the Python level and having it override the `NodeID::FromRandom` generated in https://github.com/ray-project/ray/blob/master/src/ray/raylet/raylet.cc#L63, which would definitely look weird, but I'm not sure it would hurt anything, and the ability to pin the `self_node_id_` might turn out to be useful in other ways.)

...but all this branch actually does is add a way to pass down the NodeID to compare it. This doesn't actually dig up the NodeID to pass it down for comparison.

(Though this write-up did end up in a different and more promising place than I was expecting.)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Thanks for the write up @dHannasch, can you help me understand the conclusion here? Right now we generate a random (unique) id for each node when the raylet starts
https://github.com/ray-project/ray/blob/4afaa46028f22efb02f7dc7794f68331c360f061/src/ray/raylet/raylet.cc#L63
and you are suggesting we should generate this id from whoever starts the raylet?

**Comment by dHannasch** [comment]
> Thanks for the write up @dHannasch, can you help me understand the conclusion here? Right now we generate a random (unique) id for each node when the raylet starts
> https://github.com/ray-project/ray/blob/4afaa46028f22efb02f7dc7794f68331c360f061/src/ray/raylet/raylet.cc#L63
> 
> 
> and you are suggesting we should generate this id from whoever starts the raylet?

Right, that's where the node ID is currently generated.
> the raylet has the node ID at the top level, and that's where it's originally generated:
> https://github.com/ray-project/ray/blob/master/src/ray/raylet/raylet.cc#L63

I know it's a little counter-intuitive to generate the node ID outside and pass it in. The thing is that I think we should be using the node ID everywhere, not just in the raylet. (Because treating the IP address as if it's a UUID, when it isn't, doesn't work in general.)

The question is: how do we get the node ID out of the raylet? We could retrieve it from Redis somehow, but we need to know the node ID first before we can retrieve it. It's a chicken-and-egg problem.

The ingenious workaround you found for retrieving the IP address (which is currently being used as if it were a UUID) was to pull it from the command history. It's not perfect, but it *works*, and we have to do that *anyway* to make the current hack work with the IP address. We can simply retrieve the actual node UUID from the command history too, and use the actual UUID as the UUID, instead of using the IP address as the UUID.

That's the main impetus for turning the UUID into a command-line argument to the raylet. It might also come in handy to be able to hard-code a specific node ID for debugging purposes, just as it's handy to be able to hard-code the node IP address on the command line.

Does that sound sane?

**Comment by wuisawesome** [comment]
@dHannasch do you mind stating the high level goal here? I agree that IP address isn't a good unique identifier, but we have other identifiers that should be unique. 

The easiest one to access via python should be `ray.worker.global_worker.node.unique_id`. 

If you _really_ need access to the NodeID, that should still be possible. We currently don't expose it via python, but workers do know this information (https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L369), so it shouldn't be too hard to expose in python.

**Comment by dHannasch** [comment]
> @dHannasch do you mind stating the high level goal here?

Currently, Ray is failing to retrieve the object store address, the raylet socket name, and the node manager port from Redis, because the head node stores those things under the IP address by which the head node finds the joining node, and the joining node has no way to know what that IP address is.

It would be possible to hack around it by sending the IP address back somehow and using that, in much the same way that it was possible to hack around https://github.com/ray-project/ray/issues/11943 with https://github.com/ray-project/ray/pull/11944. But adding more and more rickety scaffolding to support using an IP address as a UUID seems counterproductive.

I mean, look at what https://github.com/ray-project/ray/blob/master/python/ray/_private/services.py#L253 is already doing after the recent fix.
```
    for client_info in client_table:
        client_node_ip_address = client_info["NodeManagerAddress"]
        if (client_node_ip_address == node_ip_address
                or (client_node_ip_address == "127.0.0.1"
                    and redis_ip_address == get_node_ip_address())
                or client_node_ip_address == redis_ip_address):
            relevant_client = client_info
            break
```
For each entry stored in Redis, it pulls the `client_node_ip_address` and, if that `client_node_ip_address` matches the address of the *head* node (not the node that is running this code), then the object store address and the raylet socket name and the node manager port are set according to what they were set for the head node (not the node that is actually running this code). This *works*, because in almost all cases you can substitute the head node's values, but it makes mockery of the entire concept of storing these values for each node in the first place.

(I mean...right? Am I understanding this wrong? `redis_ip_address` comes from `redis_ip_address, redis_port = redis_address.split(":")` which is the head address that we're retrieving this stuff from, see `global_state._initialize_global_state(redis_address, redis_password)`. I thought that the point of the fix was to substitute the head's values.)

It *works*, it allows some people's Docker containers to run Ray, but it's rickety and the fix I want, if it were also done using IP addresses, would make things even *more* rickety. That's why I'm thinking to move toward proper UUIDs so we stop adding rickety scaffolding.

> I agree that IP address isn't a good unique identifier, but we have other identifiers that should be unique.
> 
> The easiest one to access via python should be `ray.worker.global_worker.node.unique_id`.
> 
> If you _really_ need access to the NodeID, that should still be possible. We currently don't expose it via python, but workers do know this information (https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L369), so it shouldn't be too hard to expose in python.

The only reason to use the NodeID is because the NodeID is already in the Redis store, so we don't need to add any extra information to the Redis store.
If we could add one of those other IDs to the Redis store, then we could use that as the key instead.

I did find where the GCS adds the NodeID to Redis.
https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_server/gcs_node_manager.cc#L134
```
  NodeID node_id = NodeID::FromBinary(request.node_info().node_id());
  RAY_CHECK_OK(
      gcs_table_storage_->NodeTable().Put(node_id, request.node_info(), on_done));
```
If the joining node passed some other kind of ID in the rpc::RegisterNodeRequest, then we could `NodeTable().Put` that ID instead.
I believe that the joining node sends its ID to the GCS here: https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_client/service_based_accessor.cc#L344
```
  auto node_id = NodeID::FromBinary(local_node_info.node_id());
  client_impl_->GetGcsRpcClient().RegisterNode(
      request, [this, node_id, local_node_info, callback](
                   const Status &status, const rpc::RegisterNodeReply &reply) {
```
I don't know whether adding an additional field to the rpc::RegisterNodeRequest, and to the Redis store might cause other problems I haven't thought of.
If we did add an additional field to the rpc::RegisterNodeRequest, I don't know of any easy way to access `ray.worker.global_worker.node.unique_id` from https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_client/service_based_accessor.cc#L344 .

The NodeID is conveniently already in the Redis store. So we can match against it. The only problem was that Ray actually consists of a couple of different running Python processes (right?), and the NodeID as it currently exists is not, in fact, a *node* ID. It is in effect a *process* ID, because each process generates its own "NodeID". We were able to get away with this because only one process actually used the NodeID while the other process was using the IP address instead of the NodeID.

(Right? That's what it looks like.)

So one solution would be to fix up the NodeID *somehow* so that it's a node ID, the same for all processes running on that node. That doesn't have to mean making it a command-line argument, but it would need to be accessible from all processes running on the same node.

Another solution would be to use a different form of ID that already is common to all processes running on that node.

https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L369 has a way to access the raylet's NodeID...
```
  local_raylet_client_ = std::shared_ptr<raylet::RayletClient>(new raylet::RayletClient(
      io_service_, std::move(grpc_client), options_.raylet_socket, GetWorkerID(),
      options_.worker_type, worker_context_.GetCurrentJobID(), options_.language,
      options_.node_ip_address, &raylet_client_status, &local_raylet_id, &assigned_port,
      &system_config, options_.serialized_job_config));
```
It looks like the NodeID local_raylet_id is an output parameter of the constructor: https://github.com/ray-project/ray/blob/master/src/ray/raylet_client/raylet_client.cc#L126
```
raylet::RayletClient::RayletClient(
    boost::asio::io_service &io_service,
    std::shared_ptr<ray::rpc::NodeManagerWorkerClient> grpc_client,
    const std::string &raylet_socket, const WorkerID &worker_id,
    rpc::WorkerType worker_type, const JobID &job_id, const Language &language,
    const std::string &ip_address, Status *status, NodeID *raylet_id, int *port,
    std::unordered_map<std::string, std::string> *system_config,
    const std::string &job_config)
    : grpc_client_(std::move(grpc_client)),
      worker_id_(worker_id),
      job_id_(job_id),
      job_config_(job_config) {
  *raylet_id = NodeID::FromBinary(reply_message->raylet_id()->str());
```
I'm not immediately sure how to expose this in Python, because this constructor has a ton of parameters that I don't really understand, but I think this is definitely what I wanted! (Or rather, this is much better than what I wanted because I thought we would have to do the clunky command-line thing.) Thank you! With this we can...somehow...retrieve the NodeID, and then pass it down to `get_address_info_from_redis` as already in this branch.

**Comment by wuisawesome** [comment]
> Currently, Ray is failing

Do you mind providing a reproduction of what is failing here?

**Comment by dHannasch** [comment]
> > Currently, Ray is failing
> 
> Do you mind providing a reproduction of what is failing here?

As with the original Docker issue, IP issues cannot simply be reproduced, since they depend on the network topology, nor on the code. The "reproduction" is just ray start. The specific code'd eventually run is irrelevant, what matters is the network you're running on.

The specific crash really isn't the point anyway, because the entire point is that I'm trying to *not* make a patch specifically to work around that the way we were able to work around the Docker issue.

You agree that using an IP address as a UUID inevitably leads to problems of *some* kind, right?

> I agree that IP address isn't a good unique identifier

As it happens I'm looking at a crash right now, but I didn't mention it in the original post because it's not important. I'm talking about the entire class of crashes like that, crashes like https://github.com/ray-project/ray/issues/11943, that crop up due to trying to use an IP address as a UUID.

**Comment by wuisawesome** [comment]
I agree, a network topology + `ray start` would be reasonable reproduction here. 

>You agree that using an IP address as a UUID inevitably leads to problems of some kind, right?

Yes, but I think IP+port is also a valid and useful unique id. 

#11943/11944 seem to be about connecting to GCS, so I don't see how NodeID is relevant at that step of the bootstrapping process.

**Comment by dHannasch** [comment]
> > You agree that using an IP address as a UUID inevitably leads to problems of some kind, right?
> 
> Yes, but I think IP+port is also a valid and useful unique id.

Ah. Sorry, I thought we were already on the same page there.

> #11943/11944 seem to be about connecting to GCS, so I don't see how NodeID is relevant at that step of the bootstrapping process.

It doesn't need to be the NodeID, but I brought up the NodeID because the GCS is *already* storing the NodeID. That's the relevance of the NodeID to the GCS.

The class of problems looks like this:

* The head node creates the node table.
* The head node indexes the node table by the IP address the head node uses to reach each node. (It's a little more complicated than that, but close enough.)
* The other node does not know the IP address by which the head node reached it, so the other node cannot find itself in the node table.

That's the problem of https://github.com/ray-project/ray/issues/11943. https://github.com/ray-project/ray/pull/11944 worked around it by allowing the other node to pull the "wrong" entry from the node table. That works, insofar as Ray will run fine in most cases using the wrong row from the node table, but the underlying problem is still that the node cannot find itself in the node table.

Storing a port number will not change that situation. (Though I'm not very clear on *which* port number you want to add there.)

Ideally the node would be able to find its own entry in the node table. One way the node could find itself in the node table is to look for its NodeID, since the node table already contains its NodeID.

Does that make sense?

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
