### PR TITLE
[Docs] Fix dark mode table visibility issues

### PR DESCRIPTION
**Pull request by MaxVanDijck**
Fixes text visibility issues present in tables in dark mode by updating `--bs-body-color`
Images of how the tables now look:
Screenshot 2024-06-23 at 5 27 33 PM
Screenshot 2024-06-23 at 5 28 31 PM

Closes: 

https://github.com/ray-project/ray/issues/44072
https://github.com/ray-project/ray/issues/45823
https://github.com/ray-project/ray/issues/44670
https://github.com/ray-project/ray/issues/44537

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
LGTM, not sure if @cristianjd wants to take a look; otherwise i can approve in one or two days

**Review by can-anyscale — APPROVED** [review]

**Comment by MaxVanDijck** [comment]
@can-anyscale Sorry, can you merge. I updated the branch due to the failed tests and it disabled auto-merge.

Do maintainers usually come back and merge master on contributors pull-requests marked with the `go` tag if the tests fail? or should I do the merge and ping you again?

**Comment by can-anyscale** [comment]
Thanks @MaxVanDijck, pinging me sound good, a merger needs to review again if the PR is updated ;)

**Pull request merged**
