### PR TITLE
[Windows] Suppress 'Windows fatal exception: access violation'

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

fixes
https://github.com/ray-project/ray/issues/15073
https://github.com/ray-project/ray/issues/18944
https://github.com/ray-project/ray/issues/13511

and other related issues

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
Note the errors are still in the log files so we are not loosing anything here. But it does remove some very annoying error message from running the tutorials and Ray libraries.

**Review by wuisawesome — CHANGES_REQUESTED** [review]
Sorry, last thing, can we add a test in `test_cli` for this?

**Comment by mattip** [comment]
How would such a test look? The fatal error output can be reproduced by running `python -c"import faulthandler as fh; fh.enable(); fh._read_null()" which raises an exception and kills the interpreter. On windows this prints
```
Windows fatal exception: access violation

Current thread 0x00002120 (most recent call first):
  File "<string>", line 1 in <module>
```

On linux it prints
```
Fatal Python error: Segmentation fault

Current thread 0x00007f137770e740 (most recent call first):
  File "<string>", line 1 in <module>
Segmentation fault
```

Aside: When I see this error, for instance when running the [test_call_matrix](https://github.com/ray-project/ray/blob/cba8480616a16abed223b9596bbb0ddb9750a946/python/ray/tests/test_basic_2.py#L199) test, I do not see a traceback, only this (where the `(pid-10522)` is blue):
```
(pid=10552) Windows fatal exception: access violation
(pid=10552)
```

**Review by wuisawesome — APPROVED** [review]
I approve your part, I suppose if you approve my part you can merge 😛

**Pull request merged**
