### PR TITLE
[SGD] Fix IterableDataset errors

### PR DESCRIPTION
**Pull request by ConeyLiu**
## Why are these changes needed?

Pytorch `IterableDataset` does not support custom `sampler` or `batch_sampler`: https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L144

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
@ConeyLiu Can you make sure this passes our formatting test?

`ray/format.sh`

You should see something like:
```
╰─ ~/Research/riselab/ray/scripts/format.sh .
WARNING: clang-format is not installed!
From https://github.com/ray-project/ray
 * branch                master     -> FETCH_HEAD
```

**Comment by ConeyLiu** [comment]
Hi @richardliaw, I have run the format.sh.

**Comment by ConeyLiu** [comment]
```
(tf) XianyangdeMacBook-Pro:ray xianyang$ ./scripts/format.sh
WARNING: clang-format is not installed!
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Total 162 (delta 36), reused 36 (delta 36), pack-reused 126
Receiving objects: 100% (162/162), 53.30 KiB | 28.00 KiB/s, done.
Resolving deltas: 100% (86/86), completed with 32 local objects.
From https://github.com/ray-project/ray
 * branch                master     -> FETCH_HEAD
   be5235d98..eb790bf3a  master     -> upstream/master
```

**Comment by ConeyLiu** [comment]
errors seem not related.

**Comment by richardliaw** [comment]
Thank you very much!

**Comment by ConeyLiu** [comment]
thanks @richardliaw

**Pull request merged**
