### PR TITLE
[WIP] Print fatal error to driver stderr

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Currently, the driver cannot print the FATA logs to stderr when that happens (but they are only logged to the log file). This is bad because it can look like there's abrupt crash without any informative log messages in the stderr for drivers.

This PR basically adds an option to add a console logger for core worker (that uses file logger). cc @SongGuyang  The PR is not ready, but it'd be great to get some feedback about the idea. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@scv119 Any good idea to test this? I was thinking to create an API to kill the driver with FATAL error, but do you think that's okay?

**Comment by rkooo567** [comment]
It looks like on failures that are caused by signals, it is printed to stderr properly, so the only case is it is crashed with the FATAL log.

**Comment by scv119** [comment]
https://sourcegraph.com/github.com/ray-project/ray/-/blob/src/ray/util/logging_test.cc?L63
is this something useful?

**Comment by rkooo567** [comment]
@scv119 hmm I was thinking to add tests on the python layer, but yeah I can probably just do that in cpp

**Comment by SongGuyang** [comment]
@rkooo567 Sorry for the late reply. Do you know the reason why we don't make a log file for raylet process and gcs process? I found that stdout and stderr has been used by logger in raylet and gcs. But in driver and workers, we distinguished stdout, stderr and ".log" file. I don't know the original design. If we can merge the log file of driver to stdout and stderr, your current issue will be solved? But I don't ensure the best practice of logging file.
image

**Comment by rkooo567** [comment]
We are starting workers from raylet, whereas raylet and gcs server is started from python code. I am not 100% sure about the design choice, but we don't redirect stdout / stderr to files for workers / drivers. For drivers, we shouldn't do this because python code should still be printed to stdout / stderr. For workers, I think we can do this, and I am not 100% sure why we don't do that (maybe not easy in cpp?)

**Comment by rkooo567** [comment]
Eric's PR to emit stderr will fix it

**Pull request closed without merging**
