### PR TITLE
Fix `IS_PYDANTIC_2` logic for `pydantic<1.9.0`

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

The `__version__` attribute didn't exist prior to 1.9.0 and our check does not work properly.

Tested manually with `pip install -U pydantic==1.8.0`.

## Related issue number

Closes https://github.com/ray-project/ray/issues/42413

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]

**Comment by architkulkarni** [comment]
serve minimal test failed in premerge: https://buildkite.com/ray-project/premerge/builds/17432#018d4208-b02c-4fa4-80ea-a8e50efdac0c

But I think I've seen a similar error before and it was unrelated.  Restarting to see what happens

**Comment by architkulkarni** [comment]
@edoakes serve-minimal failed again, can you see if it's related or if it's safe to ignore?

**Comment by GeneDer** [comment]
@architkulkarni That's actually related to starlette issue. We can cherry pick this PR to unblock from merging https://github.com/ray-project/ray/pull/42417 or wait for Sihan's cherry-pick fixes

**Comment by architkulkarni** [comment]
Ok, let's wait for Sihan's cherry pick fix then.  Better to avoid force-merging when possible.

**Comment by edoakes** [comment]
> Ok, let's wait for Sihan's cherry pick fix then. Better to avoid force-merging when possible.

Agreed!

**Comment by edoakes** [comment]
Other cherry pick that'll fix the test is now open: https://github.com/ray-project/ray/pull/42740

**Pull request merged**
