### PR TITLE
[Streaming] fix streaming redis interface not-found

### PR DESCRIPTION
**Pull request by ashione**
## Why are these changes needed?
Ray-streaming tests building is broken after this commit 06ed2313e2.

```cpp
Use --sandbox_debug to see verbose messages from the sandbox
In file included from streaming/src/test/streaming_queue_tests.cc:14:
streaming/src/test/queue_tests_base.h:12:27: error: use of undeclared identifier 'redisConnect'
  redisContext *context = redisConnect("127.0.0.1", 6379);
                          ^
streaming/src/test/queue_tests_base.h:13:19: error: use of undeclared identifier 'redisCommand'
  freeReplyObject(redisCommand(context, "FLUSHALL"));
                  ^
streaming/src/test/queue_tests_base.h:14:19: error: use of undeclared identifier 'redisCommand'
  freeReplyObject(redisCommand(context, "SET NumRedisShards 1"));
                  ^
streaming/src/test/queue_tests_base.h:15:19: error: use of undeclared identifier 'redisCommand'
  freeReplyObject(redisCommand(context, "LPUSH RedisShards 127.0.0.1:6380"));
                  ^
streaming/src/test/queue_tests_base.h:16:3: error: use of undeclared identifier 'redisFree'
  redisFree(context);
```

So queue_tests_base should include new hredis header file for accessing redis. 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by ashione** [comment]
@chaokunyang @MissiontoMars

**Review by mehrdadn — APPROVED** [review]

**Comment by mehrdadn** [comment]
By the way, I discovered this too late, but you can actually remove the `extern "C" { }` here. (It was included somewhere else so I just kept it, but it seems I didn't need to.)

**Comment by mehrdadn** [comment]
I think this has been fixed as part of another PR, so we can probably close this.

**Comment by ashione** [comment]
> By the way, I discovered this too late, but you can actually remove the `extern "C" { }` here. (It was included somewhere else so I just kept it, but it seems I didn't need to.)

I got it. This pr will be closed.

**Pull request closed without merging**
