### PR TITLE
[core] avoid scheduling on gpu nodes by default

### PR DESCRIPTION
**Pull request by AmeerHajAli**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by sasha-s — APPROVED** [review]

**Comment by sasha-s** [comment]
something finicky is going on with cluster_task_manager_test.cc:
tests pass if I run them in isolation, say with 
`bazel test //:cluster_task_manager_test --test_arg=--gtest_filter=TestSpillWaitingTasks`

**Comment by sasha-s** [comment]
I fixed the src/ray/raylet/scheduling/cluster_task_manager_test.cc tests (we were creating head node in the tests with GPUs and the scheduling changed as the result of this PR), remaining errors _seem_ unrelated.

**Comment by AmeerHajAli** [comment]
Thanks @sasha-s. @ericl, can I merge this one?

**Review by ericl — APPROVED** [review]

**Comment by AmeerHajAli** [comment]
all failing tests are knowon flaky on https://flakey-tests.ray.io/

**Pull request merged**
