### PR TITLE
[WIP] Test only sgd on jenkins

### PR DESCRIPTION
**Pull request by pcmoritz**
Running some tests, please do not merge.

### CODE REVIEW

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by pcmoritz** [comment]
jenkins retest this please

**Comment by pcmoritz** [comment]
jenkins retest this please

**Comment by pcmoritz** [comment]
jenkins retest this please

**Comment by pcmoritz** [comment]
jenkins retest this please

**Comment by pcmoritz** [comment]
jenkins retest this please

**Comment by richardliaw** [comment]
Do we still need this?

**Pull request closed without merging**
