### PR TITLE
[core] Enable cluster ID authentication by default

### PR DESCRIPTION
**Pull request by vitsai**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
Let's run some benchmark. The PR looks good to me.

**Comment by vitsai** [comment]
[Microbenchmarks on master](https://buildkite.com/ray-project/release-tests-branch/builds/1592#0187a4b4-b2bb-44c0-889f-22f00002a778): 

single_client_get_calls_Plasma_Store = [6220.115319914286, 224.5052300173086]
--
  | single_client_put_calls_Plasma_Store = [6427.78729348863, 84.21488331092435]
  | multi_client_put_calls_Plasma_Store = [13685.622603708454, 107.89607650269706]
  | single_client_put_gigabytes = [20.114238761619227, 6.003066360606937]
  | single_client_tasks_and_get_batch = [10.621044232599615, 0.7018065234293067]
  | multi_client_put_gigabytes = [31.944310601566972, 0.8025680665642678]
  | single_client_get_object_containing_10k_refs = [13.4303118492593, 0.17122469816034125]
  | single_client_wait_1k_refs = [5.669743175103769, 0.16404015686449241]
  | single_client_tasks_sync = [1402.5799311893395, 44.22066668152743]
  | single_client_tasks_async = [11589.713176381527, 69.968115451784]
  | multi_client_tasks_async = [34377.35783189367, 2098.212516049616]
  | 1_1_actor_calls_sync = [2627.6907826949946, 17.95559542036301]
  | 1_1_actor_calls_async = [8774.565215109124, 99.25145099727403]
  | 1_1_actor_calls_concurrent = [5556.408295085073, 310.93719458837893]
  | 1_n_actor_calls_async = [11443.027888783963, 87.49946447311738]
  | n_n_actor_calls_async = [34184.700321977085, 833.4165939251417]
  | n_n_actor_calls_with_arg_async = [3086.29057625603, 35.752775132663736]
  | 1_1_async_actor_calls_sync = [1749.332379578524, 36.34387252208381]
  | 1_1_async_actor_calls_async = [3053.0727243465535, 44.040906553833615]
  | 1_1_async_actor_calls_with_args_async = [2438.8474219503923, 88.20268908351537]
  | 1_n_async_actor_calls_async = [10589.09103935827, 106.34051316384893]
  | n_n_async_actor_calls_async = [27000.281282494278, 1192.3434495510094]
  | placement_group_create/removal = [1111.4458914419295, 36.12535104191624]
  | client__get_calls = [1150.072552279968, 36.79667266684934]
  | client__put_calls = [904.8795868787086, 13.073088078601502]
  | client__put_gigabytes = [0.045687216636994404, 0.00042081305098886794]
  | client__tasks_and_put_batch = [12964.98005883289, 319.3993930878376]
  | client__1_1_actor_calls_sync = [569.89256256793, 24.8044284674939]
  | client__1_1_actor_calls_async = [1084.4466197839831, 33.13091505679245]
  | client__1_1_actor_calls_concurrent = [1106.1285553207586, 25.829782511660305]
  | client__tasks_and_get_batch = [0.9467558674435517, 0.053000735219486415]

**Review by jjyao — APPROVED** [review]

**Comment by vitsai** [comment]
Let me rebase and check, now that the dust has settled with the perf variations around grpc/jemalloc.

**Comment by vitsai** [comment]
I just fetched the latest from master:
```
single_client_get_calls_Plasma_Store = [7430.409234303559, 228.38965366330189]
--
  | single_client_put_calls_Plasma_Store = [5753.9834852558215, 28.045639428053537]
  | multi_client_put_calls_Plasma_Store = [13154.101189642688, 295.6003710262152]
  | single_client_put_gigabytes = [20.348575361020224, 5.408540287976795]
  | single_client_tasks_and_get_batch = [9.065515972623475, 0.5173226613781294]
  | multi_client_put_gigabytes = [32.503361260996485, 2.3001996731025884]
  | single_client_get_object_containing_10k_refs = [13.073973911479964, 0.09524388030035986]
  | single_client_wait_1k_refs = [5.308789754570111, 0.2582837284015687]
  | single_client_tasks_sync = [1229.038495714442, 13.153222382849606]
  | single_client_tasks_async = [9161.118673274394, 439.4809003721284]
  | multi_client_tasks_async = [26060.10100084693, 3032.592017532771]
  | 1_1_actor_calls_sync = [2423.694305129211, 42.377221200940205]
  | 1_1_actor_calls_async = [7189.242608004282, 167.63786095181737]
  | 1_1_actor_calls_concurrent = [4485.893446837654, 81.15088552536584]
  | 1_n_actor_calls_async = [8482.405857796437, 293.7637737797243]
  | n_n_actor_calls_async = [29367.47922258948, 448.20078831517094]
  | n_n_actor_calls_with_arg_async = [2944.6229564606037, 27.4476841848971]
  | 1_1_async_actor_calls_sync = [1477.9734427661867, 37.17917408886031]
  | 1_1_async_actor_calls_async = [2828.7938684446694, 65.21439003265948]
  | 1_1_async_actor_calls_with_args_async = [2177.372915271255, 132.6109193715614]
  | 1_n_async_actor_calls_async = [8726.851341566678, 99.00063718264198]
  | n_n_async_actor_calls_async = [24501.875970951165, 490.84739144419643]
  | placement_group_create/removal = [989.3018517812677, 10.65803991813856]
  | client__get_calls = [1117.9106886437926, 29.52235346733713]
  | client__put_calls = [829.0290216479347, 36.753950246713444]
  | client__put_gigabytes = [0.13195088324631216, 0.002155235235063773]
  | client__tasks_and_put_batch = [12035.839701345585, 168.27589187183585]
  | client__1_1_actor_calls_sync = [569.0270201428352, 8.341985678515032]
  | client__1_1_actor_calls_async = [1056.9109541533435, 5.691932137585301]
  | client__1_1_actor_calls_concurrent = [1063.4930318624588, 11.563607791168687]
  | client__tasks_and_get_batch = [0.9082617145703034, 0.05587572310860428]
```

**Comment by vitsai** [comment]
Results on this PR:

```
single_client_get_calls_Plasma_Store = [7009.0575646576035, 289.5459061781799]
  | single_client_put_calls_Plasma_Store = [5795.066607850367, 70.13606093071157]
  | multi_client_put_calls_Plasma_Store = [13142.248893659835, 246.7846551494398]
  | single_client_put_gigabytes = [20.45201821474135, 5.838940678768044]
  | single_client_tasks_and_get_batch = [10.357964903921456, 0.7816870937242087]
  | multi_client_put_gigabytes = [37.04548715617638, 3.906983303580694]
  | single_client_get_object_containing_10k_refs = [13.610550243141818, 0.42380061306404265]
  | single_client_wait_1k_refs = [5.607377151887346, 0.12880179045396942]
  | single_client_tasks_sync = [1269.8164529864575, 13.446465725711837]
  | single_client_tasks_async = [10510.026651965854, 452.01416610525496]
  | multi_client_tasks_async = [28180.314909440283, 757.092397635015]
  | 1_1_actor_calls_sync = [2310.426069343179, 38.1428781457671]
  | 1_1_actor_calls_async = [7582.890467201976, 133.12846343157594]
  | 1_1_actor_calls_concurrent = [5047.667524963509, 231.53942439061743]
  | 1_n_actor_calls_async = [10164.276486072515, 274.4621326032757]
  | n_n_actor_calls_async = [31336.542334674097, 955.0874763784417]
  | n_n_actor_calls_with_arg_async = [3049.9137311158647, 36.83558571130899]
  | 1_1_async_actor_calls_sync = [1433.5548681044968, 19.3532761229221]
  | 1_1_async_actor_calls_async = [3320.295324150282, 62.239195847032136]
  | 1_1_async_actor_calls_with_args_async = [2411.418824859444, 68.13344831731789]
  | 1_n_async_actor_calls_async = [9064.405353886057, 75.61009631257284]
  | n_n_async_actor_calls_async = [27172.277186173094, 746.895115569878]
  | placement_group_create/removal = [972.6681898504849, 8.582980986595114]
  | client__get_calls = [1329.8702124544418, 12.059930950932879]
  | client__put_calls = [886.425541461635, 23.686677657002086]
  | client__put_gigabytes = [0.09375705565294579, 0.002669758704407111]
  | client__tasks_and_put_batch = [12018.162235376387, 217.43137777399346]
  | client__1_1_actor_calls_sync = [632.079339112979, 2.509652783950274]
  | client__1_1_actor_calls_async = [1183.2883116321432, 13.261224692612915]
  | client__1_1_actor_calls_concurrent = [1168.280006999547, 12.131321509482406]
  | client__tasks_and_get_batch = [1.091902562543786, 0.013065135748500002]

```

**Comment by vitsai** [comment]
I think it looks good. Some potential things to monitor after merge:

```
1_1_actor_calls_sync: [2627.6907826949946, 17.95559542036301] => [2310.426069343179, 38.1428781457671]
 client__put_gigabytes: [0.13195088324631216, 0.002155235235063773] => [0.09375705565294579, 0.002669758704407111]
```

**Pull request merged**
