### PR TITLE
[RLlib] Introduce total_global_timestep

### LINKED ISSUE #28289: [RLlib] Resuming from checkpoint with DQN and epsilon greedy let timesteps start from 0 again
### What happened + What you expected to happen

The bug
I start my code with a DQN algorithm and epsilon greedy with resume="AUTO" and checkpointing each iteration. Then I let it run for say 5 iteration stop it and start it again which resumes the checkpoint but the epsilon starts at 1 again because the timesteps start from 0 again. 
In my experiments the performance also completely collapses and it looks like it starts from scratch. 
I have checked the same with PPO and there the problem doesn't occur. 

Expected behavior
The expected behavior is that the timesteps will not begin by 0 but by for example 5000 (if 1000 timesteps per iteration and saved at iteration 5). So that epsilon also not start at 1 but will be set to the correct value corresponding to this timestep. 

### Versions / Dependencies

OS: Windows 10
Ray: 2.0.0
Python: 3.9

### Reproduction script

```
from ray import tune
from ray.rllib.algorithms.dqn import DQNConfig

from ray.rllib.utils.exploration.epsilon_greedy import EpsilonGreedy

num_iterations = 10
checkpoint_frequency = 1
config = DQNConfig().environment(env="CartPole-v0").framework(framework="torch").training(train_batch_size=32)


class EpsilonGreedyPrint(EpsilonGreedy):

    def get_exploration_action(
        self,
        *,
        action_distribution,
        timestep,
        explore=True,
    ):
        print("timestep: ", timestep)
        return super().get_exploration_action(action_distribution=action_distribution, timestep=timestep, explore=explore)


exploration_config = {
    "type": EpsilonGreedyPrint,  # The Exploration class to use
    "initial_epsilon": 1.0,  # Initial value of epsilon.
    "final_epsilon": 0.02,  # Final value of epsilon.
    "epsilon_timesteps": config.min_sample_timesteps_per_iteration * num_iterations * 0.7  # Epsilon timesteps to use.
}

config.exploration(exploration_config=exploration_config)

tune.run("DQN",
         resume='AUTO',
         config=config.to_dict(),
         stop={"training_iteration": num_iterations},
         verbose=0,  # Put to 1 for the progress table.
         checkpoint_freq=checkpoint_frequency,  # Checkpoint every checkpoint_frequency steps. Use 0 to disable.
         keep_checkpoints_num=None,  # If set, need to provide `checkpoint_score_attr`.
         checkpoint_at_end=True)
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Signed-off-by: Artur Niederfahrenhorst <artur@anyscale.com>

## Why are these changes needed?

Since we do not keep track of the "sum of global timesteps" that a policy has undergone, methods such as comput_actions end up utilizing global_timestep=0 after loading from a checkpoint. This is because upon loading from a checkpoint, the global_timestep will initially be set correctly, but with the first synchronization of global variables from the local rollout worker, this is overwritten.

## Related issue number

Closes #28289 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by RaymondKoopmanschap** [comment]
Is there any indication when this pull requests will be merged?

**Comment by jbedorf** [comment]
Coming here from issue #28289 . There is another slightly related issue with the time steps not being kept/restored with Ray 2.0. The tensorboard outputs no longer continues where you left off, instead the data start at 0 (as the timestep was reset). It would be good to test if these changes also solve that issue or if that variable also has to be updated to use global_timestep.

**Comment by ArturNiederfahrenhorst** [comment]
@RaymondKoopmanschap @jbedorf We've been discussing a larger overhaul of how such global info should be shared in RolloutWorkers so we postponed this fix. Sorry. We'll now put some more time into this.

**Comment by jbedorf** [comment]
@ArturNiederfahrenhorst  The stale bot reminded me of this issue. Is this now fixed in master or is this still work in progress?

**Comment by ArturNiederfahrenhorst** [comment]
@jbedorf Still wip 👍

**Pull request closed without merging**
