### PR TITLE
Revert "Revert "Revert "Revert "[serve][xlang]Support deploying Python deploy…"

### PR DESCRIPTION
**Pull request by yaxife**
Reverts ray-project/ray#28153

### CODE REVIEW

**Comment by yaxife** [comment]
Reason for ci error: Attempt to call ray's API after ray is closed. The problem existed before this PR was merged.
Other c++ libs, such as OpenCV, etc., will not exit the entire JVM if the java user uses it incorrectly.  @jovany-wang

**Comment by jovany-wang** [comment]
Hey, so could you comment on the line which we fixed the issue?

**Comment by yaxife** [comment]
> Hey, so could you comment on the line which we fixed the issue?
You can take a look at these two commits.
https://github.com/ray-project/ray/pull/27945/commits/16fb0f74150565bf1c2e40b2e3278554ffed2e38
https://github.com/ray-project/ray/pull/28287/commits/61daa4548f6f815fd50612b53ec22da772f3a6e7

**Review by jovany-wang — APPROVED** [review]
Fix commits look good to me.
@rkooo567 @simon-mo CC to make sure there is no any regression now.

**Comment by yaxife** [comment]
> 

`ExecutorService#shutdownNow` cancel thread via `Thread#interrupt`, It just sets a flag to thread and does nothing else. Therefore, it can't guarantee to stop all the ongoing threads.  I submitted a new commit to solve this problem. Please review the code.
https://github.com/ray-project/ray/pull/28287/commits/317cff15ba330caf31007529cf5effdebf6186e7

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
I have ran macOS and Linux Java job 3 times each. 
image

image

**Pull request merged**
