### PR TITLE
[Serve] Update the test_http_headers size

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

On Windows, tests sometimes timeout.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by GeneDer — APPROVED** [review]
Thanks Sihan!

**Review by zcin — APPROVED** [review]

**Comment by edoakes** [comment]
@zhe-thoughts just improving test stability, not sure if we want to merge such changes

**Comment by sihanwang41** [comment]
Thx Ed! Prefer to merge(very low risk), this will help to make our future pr being more safer to merge and stabilize release branch tests.

**Comment by zhe-thoughts** [comment]
@sihanwang41 could you help check if this is `tests-ok`? Thanks!

**Comment by sihanwang41** [comment]
Add tests-ok lable, all failures are not related. The change is not touching any code.

**Comment by edoakes** [comment]
@sihanwang41 `premerge` build failed (probably unrelated), but that's a blocking build so it can't be merged. Please rebase for latest fixes of other tests.

**Comment by edoakes** [comment]
(I did it via UI)

**Comment by sihanwang41** [comment]
> 

thx! lol i am confused for 1min in my terminal when I do git pull.

**Comment by sihanwang41** [comment]
ping for merge. @edoakes @zhe-thoughts

**Review by zhe-thoughts — APPROVED** [review]
Clean test change

**Pull request merged**
