### PR TITLE
[Disable Tests] New Dashboard Tests

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* These tests are failing on master.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
thansk, i will take a look! they appear to be flaky on master

**Comment by ijrsvt** [comment]
It actually looks like the nightly wheels are broken because of the PR (not just these tests). 
Revert in  #14846

**Comment by ijrsvt** [comment]
Quick update, this is actually a problem with #14848

**Comment by simon-mo** [comment]
Close this?

**Comment by ijrsvt** [comment]
Replaced by #14848

**Comment by ijrsvt** [comment]
@simon-mo these tests are actually broken :'(

**Pull request merged**
