### PR TITLE
[WIP] Create a Ray Operator for Kubernetes

### PR DESCRIPTION
**Pull request by liucimin**
## What do these changes do?
Ray is a great project but requires a lot of babysitting to set up and tear down clusters on demand.

I want to finish a kubernetes operator to make ray trivial to spin up and tear down ray clusters.

It would also solve the issue of autoscaling. The operator would manage the scale of individual ray clusters on kubernetes.

## Related issue number

https://github.com/ray-project/ray/issues/5044

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by ericl** [comment]
@liucimin this is a great initiative. Would it be possible to reuse the existing autoscaler code as part of the operator or do you think it would be better to have it separate?

**Comment by liucimin** [comment]
Yes I also think a separate project in Ray-project with name “ray-operator” is better.Because it will be golang project.
The autoscaler may also rewrite in it.But I think we should first have a operator with K8s crd first.Then reuse auto scale in it.


发自我的iPhone

------------------ Original ------------------

**Comment by ericl** [comment]
Sounds good. For more advanced scaling in the future we might want to pipe information from the python APIs to golang, but that's not a big hurdle. That information could also be read from the GCS directly perhaps.

**Comment by liucimin** [comment]
I am trying to make the ray-operator in my repos.
https://github.com/liucimin/ray-operator
Maybe  should open a new project in the ray-project for other people to commit?
Just myself to finish this operator may take few weeks~

**Comment by richardliaw** [comment]
Awesome! I opened up a repo here: https://github.com/ray-project/ray-operator. Can you make a PR with your changes? We can merge even before it's functional.

**Comment by liucimin** [comment]
Hi Richard
I have made a pr in the new repo.
Wish your reviews.
发自我的iPhone

------------------ Original ------------------

**Comment by edoakes** [comment]
Moved to https://github.com/ray-project/ray-operator.

**Pull request closed without merging**
