### PR TITLE
[Ray Data] `PythonObjectArray` missing methods causing serialization failures

### PR DESCRIPTION
**Pull request by akavalar**
`PythonObjectArray` is a subclass of `ExtensionArray`, but as such it is missing some of the mandatory methods described [here](https://github.com/pandas-dev/pandas/blob/main/pandas/core/arrays/base.py#L172-L183), specifically `isna`, `take`, `copy`, and `_concat_same_type` (the last method `interpolate` does not seem to be required). Such storage of Python objects in Arrow blocks was added to Ray Data in https://github.com/ray-project/ray/pull/45272 and was released as part of Ray 2.33.

Custom Python objects currently cannot be wrapped/serialized due to `pandas.errors.AbstractMethodError: This method must be defined in the concrete class PythonObjectArray` failures, as shown by the contrived example here: https://github.com/ray-project/ray/issues/48748

This PR adds the missing methods.

## Why are these changes needed?

See above.

## Related issue number

N/A

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
This is great! Think the failure is unrelated. Could you add some tests as well?

**Comment by xingyu-long** [comment]
Hey, I'd like to write some tests for this PR!

**Comment by akavalar** [comment]
@xingyu-long I started working on them but then stopped when I saw the `rllib` failures. If you intend to work on this right away then go for it, otherwise I'll probably want to finish the PR cause it's blocking us at work and we'd like to see it merge soon. Let me know, thanks!

Btw pandas has an [entire section](https://pandas.pydata.org/pandas-docs/stable/development/extending.html#testing-extension-arrays) on how to test extension arrays.

The original PR also added a small number of tests [here](https://github.com/ray-project/ray/pull/45272/files#diff-ef4f05e215c7d8962694b59238ffbb1c65112554907af713f90bf78d3f6ab56d).

**Comment by xingyu-long** [comment]
@akavalar thanks for quick response! Yeah I will work on it, will post some comments tomorrow.

**Comment by xingyu-long** [comment]
```python

def test_pandas_isna():
    arr = np.array([1, np.nan, 3, 4, 5, np.nan, 7, 8, 9], dtype=object)
    ta = PythonObjectArray(arr)
    np.testing.assert_array_equal(ta.isna(), pd.isna(arr))


def test_pandas_take():
    arr = np.array([1, 2, 3, 4, 5], dtype=object)
    ta = PythonObjectArray(arr)
    indices = [1, 2, 3]
    np.testing.assert_array_equal(ta.take(indices).to_numpy(), arr[indices])
    indices = [1, 2, -1]
    np.testing.assert_array_equal(
        ta.take(indices, allow_fill=True, fill_value=100).to_numpy(),
        np.array([2, 3, 100]),
    )


def test_pandas_concat():
    arr1 = np.array([1, 2, 3, 4, 5], dtype=object)
    arr2 = np.array([6, 7, 8, 9, 10], dtype=object)
    ta1 = PythonObjectArray(arr1)
    ta2 = PythonObjectArray(arr2)
    concat_arr = PythonObjectArray._concat_same_type([ta1, ta2])
    assert len(concat_arr) == arr1.shape[0] + arr2.shape[0]
    np.testing.assert_array_equal(concat_arr.to_numpy(), np.concatenate([arr1, arr2]))
```
^ I came up with these tests.

maybe you can add them or have something similar into your PR @akavalar 

cc @richardliaw

**Comment by richardliaw** [comment]
hey @akavalar - did you have a chance to take a look at the tests?

**Comment by akavalar** [comment]
hey guys, I had to pivot to something else at work and haven't yet found the time for this - should be able to do it today though. thanks for your patience!

**Comment by xingyu-long** [comment]
Hi @akavalar, were you be able to run the tests? Thanks!

**Comment by xingyu-long** [comment]
Heyy @akavalar, I talked with @richardliaw and we'd like to move forward, so I picked up your changes and added my test changes since you may not have time to work on this. Thanks!

**Comment by akavalar** [comment]
Hey @xingyu-long, thanks for the heads-up! I personally think the tests you added are insufficient, but I also don't have time to work on adding the full suite of tests as described by the pandas documentation linked above. That would actually be a pretty big task in itself, and it partly explains why I've been dragging my feet (+ change of priorities at work).

I'm fine if you want to get this over the finish line, as long as you provide proper attribution. Thanks!

**Comment by xingyu-long** [comment]
> Hey @xingyu-long, thanks for the heads-up! I personally think the tests you added are insufficient, but I also don't have time to work on adding the full suite of tests as described by the pandas documentation linked above. That would actually be a pretty big task in itself, and it partly explains why I've been dragging my feet (+ change of priorities at work).
> 
> I'm fine if you want to get this over the finish line, as long as you provide proper attribution. Thanks!

@akavalar Thanks for your understanding! so far, I added tests for all new code, it should be good, but I admitted that we can have full suite, which may comes later.  so that's why I decided to move forward.

btw,  I already mentioned this PR in my PR and also have your commits in there. thanks again!

**Comment by richardliaw** [comment]
Duplicate of https://github.com/ray-project/ray/pull/49202

**Pull request closed without merging**
