### PR TITLE
[tune] Add points_to_evaluate to NevergradSearch

### PR DESCRIPTION
**Pull request by viotemp1**
## Why are these changes needed?

Add points_to_evaluate  to NevergradSearch 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Hi @viotemp1, it seems you developed on an old version of ray and something didn't work with the commit history. Over 170 files are changed in this PR.

I'd suggest you clone a fresh fork, create a new branch and just copy the changes you made in nevergrad over.

**Comment by viotemp1** [comment]
> Hi @viotemp1, it seems you developed on an old version of ray and something didn't work with the commit history. Over 170 files are changed in this PR.
> 
> I'd suggest you clone a fresh fork, create a new branch and just copy the changes you made in nevergrad over.

I never did this. I have the file changed on my local machine, but the, rest I don't know how to do it.
Can you (or someone else) please help me on this? Thanks

**Comment by krfricke** [comment]
1. Create a fork from the [main Ray repo](https://github.com/ray-project/ray/) - just click on the button in the top right. This will create a new repo, probably https://github.com/viotemp1/ray/
2. `git clone` your own forked repo, e.g. `git clone git@github.com:viotemp1/ray.git`
3. Create a new branch (`git checkout -b tune-nevergrad`)
4. Make your changes
5. Commit your changes with `git commit -a`
6. Push your changes with `git push origin tune-nevergrad`. This will push the changes into a new branch of your forked repository
7. Visit the github repo of your own fork (https://github.com/viotemp1/ray/). Usually after pushes there is a button that offers you to create a Pull Request.

Click on that button and fill out the form - voila!

**Comment by viotemp1** [comment]
OK, thanks a lot for help. I will try tonorrow.

Viorel

**Comment by viotemp1** [comment]
Done. Thanks a lot!

**Pull request closed without merging**
