### PR TITLE
Try skipping problematic java tests

### PR DESCRIPTION
**Pull request by rkooo567**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
seems not working? also look at the crash, it seems a GO crash O_o
```

--
  | panic: runtime error: index out of range [255] with length 255
  |  
  | goroutine 81 [running]:
  | github.com/buildkite/agent/v3/bootstrap.(*Redactor).Write(0xc0002e4000, 0xc0004de000, 0x10e, 0x8000, 0x10e, 0x0, 0x0)
  | /work/bootstrap/redactor.go:125 +0xdd7
  | io.copyBuffer(0xf22900, 0xc0002e4000, 0xf23720, 0xc0000be688, 0xc0004de000, 0x8000, 0x8000, 0x442456, 0xdf4970, 0xc000316900)
  | /usr/local/go/src/io/io.go:425 +0x21c
  | io.Copy(...)
  | /usr/local/go/src/io/io.go:382
  | github.com/buildkite/agent/v3/process.(*Process).Run.func2(0xc0004a7000, 0xc0000be688, 0xc0003cd1b0, 0xc00033cfb0)
  | /work/process/process.go:181 +0xa9
  | created by github.com/buildkite/agent/v3/process.(*Process).Run
  | /work/process/process.go:176 +0x39c


```

**Comment by rkooo567** [comment]
Hmm yeah I wasn’t confident that this would fix the issue, and it seems like that was the case…

**Comment by rkooo567** [comment]
Looks like the test framework is written in go, and that was broken?

**Comment by rkooo567** [comment]
The issue turns out from the buildkite agent code. Close the issue. Tracking here; https://github.com/buildkite/agent/issues/1478

**Pull request closed without merging**
