### PR TITLE
Revert "[Core] revert: revert Unified worker starter (#18008)"

### PR DESCRIPTION
**Pull request by ericl**
This reverts commit b9978dd02b307bf95081b422e5427a13327c197a.

## Why are these changes needed?

This change regresses the async actor microbenchmark by 50+%: https://github.com/ray-project/ray/issues/18168

### CODE REVIEW

**Comment by ericl** [comment]
I can't think of a reason why this would regress actual actor performance. It must be mainly impacting startup speed of the workers.

**Comment by ericl** [comment]
Oh--- @stephanie-wang already got this! https://github.com/ray-project/ray/pull/18228

**Comment by chenk008** [comment]
I have make some benchmark about fork python process, fork-exec python overhead is about 40ms. I think it's the root cause.

```
time for((i=0;i<10000;i++)); do echo hello; done >/dev/null
real	0m0.060s
user	0m0.058s
sys	0m0.002s

time for((i=0;i<10000;i++)); do echo "$(echo hello)"; done >/dev/null
real	0m4.326s
user	0m2.456s
sys	0m2.275s
fork-exec overhead is less than 0.5ms

time for((i=0;i<10000;i++)); do echo "$(python --version)"; done >/dev/null
real	6m34.987s
user	3m16.149s
sys	3m42.504s
fork-exec python overhead is about 40ms
```

**Comment by ericl** [comment]
Fork overhead can be much higher in VMs btw.

**Pull request closed without merging**
