### PR TITLE
Upgrade plasma to latest version, use synchronous Seal

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

`plasma::Seal` was not synchronous in the previous version of Arrow. This meant that a worker trying to create an object would send an async `Seal` to the plasma store, then send an IPC to the local raylet to pin the object. The local raylet would send a `Get` to the plasma store, which could be received before the client's `Seal`. Then, it would appear as if the object is not in the plasma store.

This will likely have an impact on `ray.put()` performance for small objects. On my laptop:

Before this PR
```
single client put calls per second 10610.79 +- 161.55
single client put gigabytes per second 7.39 +- 0.18
multi client put calls per second 16235.04 +- 191.21
multi client put gigabytes per second 10.53 +- 0.53
```

After this PR:
```
single client put calls per second 8897.05 +- 41.73
single client put gigabytes per second 7.28 +- 0.33
multi client put calls per second 13717.71 +- 345.07
multi client put gigabytes per second 9.51 +- 0.33
```

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by zhijunfu** [comment]
Is the sync version of `Seal` supposed to be used by only workers?

Also it might impact raylet's processing of other events if we call Get() in its main event loop, and there are a lot of add/remove operations going on in plasma. Ideally we could have an async version of `Get()` which returns results via a callback instead.

**Comment by stephanie-wang** [comment]
> Is the sync version of `Seal` supposed to be used by only workers?

Yes, but I guess it will also affect the `Seal` that is performed by the object manager during object transfers.

> Also it might impact raylet's processing of other events if we call Get() in its main event loop, and there are a lot of add/remove operations going on in plasma. Ideally we could have an async version of `Get()` which returns results via a callback instead.

That's true, but I think this was already an issue before this PR. Async get sounds like a good idea.

**Comment by zhijunfu** [comment]
> > Is the sync version of `Seal` supposed to be used by only workers?
> 
> Yes, but I guess it will also affect the `Seal` that is performed by the object manager during object transfers.

I see, thanks. It might be less sensitive than raylet as it's multi-threaded. 

> 
> > Also it might impact raylet's processing of other events if we call Get() in its main event loop, and there are a lot of add/remove operations going on in plasma. Ideally we could have an async version of `Get()` which returns results via a callback instead.
> 
> That's true, but I think this was already an issue before this PR. Async get sounds like a good idea.

Right it's not introduced by this PR. Good to add a TODO comment though :)

**Comment by stephanie-wang** [comment]
> > > Is the sync version of `Seal` supposed to be used by only workers?
> > 
> > 
> > Yes, but I guess it will also affect the `Seal` that is performed by the object manager during object transfers.
> 
> I see, thanks. It might be less sensitive than raylet as it's multi-threaded.
> 
> > > Also it might impact raylet's processing of other events if we call Get() in its main event loop, and there are a lot of add/remove operations going on in plasma. Ideally we could have an async version of `Get()` which returns results via a callback instead.
> > 
> > 
> > That's true, but I think this was already an issue before this PR. Async get sounds like a good idea.
> 
> Right it's not introduced by this PR. Good to add a TODO comment though :)

Sure, I'll add a TODO to the `Get` in the raylet. I think this is the only place where this is an issue.

**Review by edoakes — APPROVED** [review]
LGTM

**Pull request merged**
