### PR TITLE
[Release Tests] shm size microbenchmark

### LINKED ISSUE #12895: [Docker] Microbenchmark client put gb/s perf regression
### What is the problem?
When running the release tests in Docker via the product, two aspects of the microbenchmark show a regression in speed, namely in `multi client put gigabytes per second` and `single client put gigabytes per second`
image (1)
image

Here is the analysis difference from the previous version:
image (2)

*Ray version and other system information (Python version, TensorFlow version, OS):* 
Run using the ray-project/releaser tool on the 1.1.0 release in the Anyscale product latest ray docker image. `python cli.py --git-branch releases/ray-1.1.0 suite:run microbenchmark` is what I'm using to trigger the build. The only difference with the release branch is a line:
image

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by mfitton**
## Why are these changes needed?
This does two things to fix a perf regression in the microbenchmark when running on docker.
- set shm-size to 100gb in docker image for microbenchmarks because otherwise client puts/gets run very slowly
- do not prepend OMP_THREAD arg to microbenchmark script. Actors should be functioning with one core each, not 64 each.

## Related issue number
Closes #12895 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@rkooo567 git blame says you set OMP_NUM_THREADS=64 here -- do you remember why? It's unintuitive to me.

**Comment by wuisawesome** [comment]
@ijrsvt should we be setting this option by default when using docker in general?

**Comment by ijrsvt** [comment]
@wuisawesome It is set automagically [here](https://github.com/ray-project/ray/blob/a7caa14d3d8951cd83d3fe205e1b3e6aa26606f2/python/ray/autoscaler/_private/command_runner.py#L807).

**Comment by wuisawesome** [comment]
If that's the case, we shouldn't need this PR right?

**Comment by ijrsvt** [comment]
@wuisawesome Maybe not then--I guess every future set of release tests will be run with the `Ray 1.1.0+ autoscaler`.

**Pull request closed without merging**
