### PR TITLE
[core] Cleanup shared pointer for ref counter in memory store

### PR DESCRIPTION
**Pull request by dentiny**
I'm trying to do some cleanup shared pointer usage in the codebase when waiting for compilation.
Shared pointer usage here is non-performant, and error prune to memory leak.

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by jjyao** [comment]
Test failure

**Comment by dentiny** [comment]
> Test failure

Should be fixed.

**Review by jjyao — APPROVED** [review]

**Review by dayshah — APPROVED** [review]

**Comment by dentiny** [comment]
I suffer flaky tests which has nothing to do with my change... merge master to trigger rerun...

**Comment by dentiny** [comment]
Hi @jjyao the CI is finally clean, could you please help me merge the PR? Thanks!

**Pull request merged**
