### PR TITLE
[Java] Allow to specify zero CPU as resource.

### PR DESCRIPTION
**Pull request by jovany-wang**
## Why are these changes needed?
This is aligned to the behavior of Python resources validation.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jovany-wang** [comment]
@yaxife

**Comment by kfstorm** [comment]
Can we specify zero for custom resources as well? I recall that there's a check in C++ code to disallow zero custom resource. Maybe we need to test it as well.

**Review by simon-mo — APPROVED** [review]

**Comment by jovany-wang** [comment]
> Can we specify zero for custom resources as well? I recall that there's a check in C++ code to disallow zero custom resource. Maybe we need to test it as well.

Yes. The 0 CPU test also failed due to the C++ check. I should filter all 0 resources. 

I'm going to move prepare_resources to core worker so that both Python,  Java and C++ worker can reuse it. https://github.com/ray-project/ray/blob/master/python/ray/_raylet.pyx#L318-L339

**Comment by jovany-wang** [comment]
Due to the filtering 0 resources logic is too simple, I decided not to move it to C++.
Also 0 custom resource test was introduced.

**Review by kfstorm — APPROVED** [review]

**Pull request merged**
