### PR TITLE
[Wheel] Turn off 3.9 build for macOS only

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
Wheels build for macOS is still broken. This attempt to fix it.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Should we merge it rn?

**Comment by tbabej** [comment]
Will the build pipeline produce also new `ray:nightly-py39` images after merging this, or is further action required for that?

**Comment by simon-mo** [comment]
We should make that happen. @ijrsvt any hint on how to add py39 imgs?

**Comment by ijrsvt** [comment]
@simon-mo (@tbabej )
To start building `py39` docker images we will need to make sure that _linux_ Py39 wheels are being built. It will require some modification to `build-docker-images.py` (but that should be _very_ minimal).

**Comment by wuisawesome** [comment]
Doesn't look like wheel need this anymore (hehehe)

**Pull request closed without merging**
