### PR TITLE
Add section on launching clusters on Kubernetes to Getting Started

### LINKED ISSUE #42129: [docs] [kuberay] Add instructions and link to RayClusters Quickstart in top level Getting Started
### Description

The top level Getting Started has quickstarts for all libraries except KubeRay. Please add a dropdown for KubeRay and link to the RayCluster Quickstart: cluster/kubernetes/getting-started/raycluster-quick-start.html

Screenshot 2023-12-29 at 1 58 30 PM

### Link

https://docs.ray.io/en/master/ray-overview/getting-started.html#ray-cluster-quickstart

### PR DESCRIPTION
**Pull request by omrishiv**
## Why are these changes needed?

Hopefully this helps give a quick overview of using KubeRay for deploying clusters to Kubernetes

## Related issue number

Closes #42129 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by kevin85421 — COMMENTED** [review]
Hi @omrishiv, thank you for the PR! Can we add a link to [RayCluster Quickstart](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/raycluster-quick-start.html#kuberay-raycluster-quickstart) instead of copying it?

**Comment by omrishiv** [comment]
@kevin85421 Hi! Should the link just go directly there? It seemed like the rest of the drop downs had a bit of information, so I wanted to make sure this had the minimal amount needed for deploying to Kubernetes

**Comment by kevin85421** [comment]
> Should the link just go directly there?

Yes, adding a link directly is fine. KubeRay tries to maintain a single source of truth for documents. We are trying to avoid maintaining consistency between the same content across different documents.

**Comment by omrishiv** [comment]
@kevin85421 Makes sense, hopefully this is more aligned with what you were expecting

**Review by kevin85421 — APPROVED** [review]
Awesome!

**Comment by kevin85421** [comment]
I will ask our doc team to review it.

**Review by can-anyscale — COMMENTED** [review]
do you mind adding a screenshot of the portion that is added here, thankks

**Comment by omrishiv** [comment]
Sure!:
Added section for getting started:

image

Where it leads to:

image

**Comment by omrishiv** [comment]
@can-anyscale just checking to see if the above looks good. Thanks!

**Review by angelinalg — APPROVED** [review]
Thank you for contributing to the Ray docs! I'm from the Docs team. 😄

**Comment by omrishiv** [comment]
@angelinalg Thank you! also sorry, I may have screwed something up by updating my branch with main 😞

**Comment by kevin85421** [comment]
cc @angelinalg or @can-anyscale would you mind merging this PR? Thanks!

**Comment by omrishiv** [comment]
@kevin85421 @angelinalg @can-anyscale Just wanted to gently nudge on this if possible.

**Comment by can-anyscale** [comment]
merged, thank you

**Pull request merged**
