### PR TITLE
[ci] Fix grpcio 1.44 break test_output

### LINKED ISSUE #22491: `test_output` failed
```
=================================== FAILURES ===================================
  | _________________________________ test_output __________________________________
  |  
  | def test_output():
  | # Use subprocess to execute the __main__ below.
  | outputs = subprocess.check_output(
  | [sys.executable, __file__, "_ray_instance"], stderr=subprocess.STDOUT
  | ).decode()
  | lines = outputs.split("\n")
  | for line in lines:
  | print(line)
  | if os.environ.get("RAY_MINIMAL") == "1":
  | # Without "View the Ray dashboard"
  | >           assert len(lines) == 1, lines
  | E           AssertionError: ['E0218 02:38:52.612027143   20833 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and pol...3   20833 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies', '']
  | E           assert 5 == 1
  | E             +5
  | E             -1
  |  
  | /ray/python/ray/tests/test_output.py:362: AssertionError
  | ----------------------------- Captured stdout call -----------------------------
  | E0218 02:38:52.612027143   20833 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
  | E0218 02:38:52.616586024   20833 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
  | E0218 02:38:53.128173624   20833 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
  | E0218 02:38:53.132153643   20833 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
  |  
  | ----------------------------- Captured stderr call -----------------------------
  | E0218 02:38:51.131946862   18362 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
  | =========================== short test summary info ============================
  | FAILED ::test_output - AssertionError: ['E0218 02:38:52.612027143   20833 for...
  | ============= 1 failed, 12 passed, 4 skipped in 144.97s (0:02:24) ==============
  | ================================================================================
 

<br class="Apple-interchange-newline">
```

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
This PR limit grpc to be <= 1.42. This will fix testoutput.

## Related issue number

Closes #22491 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by iycheng** [comment]
somehow 1.44 is still installed.

**Review by ericl — APPROVED** [review]

**Comment by amogkam** [comment]
Ah yes rllib test failures are unrelated, and this is a different dependency issue (https://github.com/ray-project/ray/pull/22510)

**Comment by iycheng** [comment]
ASAN test failed. @rkooo567  @scv119  do you have some idea about how to fix this?


```
pkg_resources.ContextualVersionConflict: (grpcio 1.44.0 (/opt/miniconda/lib/python3.6/site-packages), Requirement.parse('grpcio<=1.43.0,>=1.28.1'), {'ray'})
 ```

**Comment by rkooo567** [comment]
Hmm doesn't this mean just the wrong version is downloaded?

```
pkg_resources.ContextualVersionConflict: (grpcio 1.44.0 (/opt/miniconda/lib/python3.6/site-packages), Requirement.parse('grpcio<=1.43.0,>=1.28.1'), {'ray'})
```

Btw, what'd be the right fix? It seems like they changed the log level from INFO -> ERROR because the behavior itself is wrong. Doesn't that mean we are using gRPC in some wrong way?

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
hmm the window's failure looks related though:
```
<html>
<body>
<!--StartFragment-->

state = <grpc._channel._RPCState object at 0x000001E98AD9D910>
--
  | call = <grpc._cython.cygrpc.SegregatedCall object at 0x000001E98AD9E3C0>
  | with_call = False, deadline = None
  |  
  | def _end_unary_response_blocking(state, call, with_call, deadline):
  | if state.code is grpc.StatusCode.OK:
  | if with_call:
  | rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
  | return state.response, rendezvous
  | else:
  | return state.response
  | else:
  | >           raise _InactiveRpcError(state)
  | E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  | E           	status = StatusCode.DEADLINE_EXCEEDED
  | E           	details = "Deadline Exceeded"
  | E           	debug_error_string = "{"created":"@1645338788.229000000","description":"Error received from peer ipv4:127.0.0.1:59517","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Deadline Exceeded","grpc_status":4}"
  | E           >
  |  

<!--EndFragment-->
</body>
</html>
```

**Comment by iycheng** [comment]
> Hmm doesn't this mean just the wrong version is downloaded?
> 
> ```
> pkg_resources.ContextualVersionConflict: (grpcio 1.44.0 (/opt/miniconda/lib/python3.6/site-packages), Requirement.parse('grpcio<=1.43.0,>=1.28.1'), {'ray'})
> ```
> 
> Btw, what'd be the right fix? It seems like they changed the log level from INFO -> ERROR because the behavior itself is wrong. Doesn't that mean we are using gRPC in some wrong way? Feel like having the version upper bound is just a quick way to migrate problem, but we might need to address the underlying problem

@rkooo567  I think you are right about this. I think the current fix is just a temporary fix which is quick and fast and safetest.

The reason it failed is because somehow when install rllib requirements, it upgrade the grpc to the newest version although it only asks for `grpcio<2.0`.

**Comment by iycheng** [comment]
@amogkam  could you give this approval? You are the code owner here.

**Comment by amogkam** [comment]
@iycheng can you undo the changes for `requirements_dl.txt`? That's the only file I am code owner for.

For `setup.py` you need approval from @ericl @richardliaw or @edoakes

**Comment by iycheng** [comment]
> @iycheng can you undo the changes for `requirements_dl.txt`? That's the only file I am code owner for.
> 
> For `setup.py` you need approval from @ericl @richardliaw or @edoakes

Got it.... somehow my editor update it... :( Thanks for pointing it out.

**Comment by iycheng** [comment]
Merge it given this one passed (https://buildkite.com/ray-project/ray-builders-pr/builds/24916)

**Pull request merged**
