### PR TITLE
[core][dashboard] Feature flag task logs recording

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

This should address a few issues introduced by the original task log recording features:
- https://github.com/ray-project/ray/issues/33924
- https://github.com/ray-project/ray/issues/33949
- https://github.com/ray-project/ray/issues/33738

**The roocasue with the regressions are:**
With https://github.com/ray-project/ray/pull/32943, we are recording log file offsets before and after executing a task, which calls tell() on the file descriptor object for each worker.

The cost of that shows up when there are concurrent execution of tasks on a single worker.

I am turning this off by default for this release since the subsequent PRs are not merged yet. We will need to tackle or resolve the regression once we turn this feature on when we merge subsequent PRs. One idea is to make this "finding-out-offset-procedure" async, e.g. we try to locate the exact task id's log offset when we querying the task logs at querying time. 

## Checks
Release test runs: https://buildkite.com/ray-project/release-tests-pr/builds/33807

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
Can you run the release tests to verify the perf?

**Comment by rickyyx** [comment]
Release tests result on regressed metrics:
```
1_1_actor_calls_sync = [2537.4806201049246, 79.50073772393054]
1_1_actor_calls_async = [8080.69523961889, 198.15935493110175]
1_1_actor_calls_concurrent = [4908.792154434921, 44.89671843147798]
```


Most recent master:
```
1_1_actor_calls_sync = [2555.5161791253017, 116.31318984914702]
1_1_actor_calls_async = [7561.123153475535, 101.53602458003189]
1_1_actor_calls_concurrent = [3869.564842234081, 27.137047110223968]
```



Last Release:
```
1_1_actor_calls_sync = [2141.781296932585, 116.31318984914702]
1_1_actor_calls_async = [8098.766293651375,,222.2536677285019]
1_1_actor_calls_concurrent = [4927.728219186553,  43.87352163252427]

```

**Comment by rickyyx** [comment]
@zhe-thoughts Could we cherry-pick this in? This will fix some small regressions for our microbenchmark by featuring flagging a feature that's not fully working in 2.4 yet.

**Review by zhe-thoughts — APPROVED** [review]
We should cherry pick this into 2.4.0. cc @clarng

**Comment by rkooo567** [comment]
okay. This makes me pretty confidence the root cause is the file name report. Merging now

**Comment by rkooo567** [comment]
I see. So tell is the problem...

**Pull request merged**
