### PR TITLE
[ci][release] add `RAY_BACKEND_LOG_JSON` env for all release test

### PR DESCRIPTION
**Pull request by can-anyscale**
Add `RAY_BACKEND_LOG_JSON` as an cluster environment to all release tests; requested by @jjyao

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Review by aslonnie — COMMENTED** [review]
some release test still failing? is it related?

**Comment by can-anyscale** [comment]
yess, the flag might be the culprit

**Comment by jjyao** [comment]
@can-anyscale test passed https://buildkite.com/ray-project/release/builds/17138. We can merge the PR now

**Comment by can-anyscale** [comment]
merging \o/

**Comment by can-anyscale** [comment]
still need a stamp from either @khluu or @aslonnie

**Review by aslonnie — APPROVED** [review]

**Pull request merged**
