### PR TITLE
Add query param to limit number of actors in api/snapshot

### PR DESCRIPTION
**Pull request by alanwguo**
Default the value to 1000 actors

Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Reduces the latency of the api/snapshot, especially in cases where there is a ton of actors.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by alanwguo** [comment]
Known issue, currently the actor list that comes back is randomly ordered and does not prioritize alive actors first. This is a known follow-up item for state observability api work.

CC: @rkooo567 @rickyyx

**Review by edoakes — COMMENTED** [review]
add test pls 🙏

**Comment by wuisawesome** [comment]
+1 to a test, also a few other questions:

why 1000? I ask because release tests launch more actors that that I think?

also it seems like we're trying to solve the problem statement usually associated with pagination, but we don't have pagination in the core. Do we have a guarantee that we're returning the latest actors (by what definition of latest?)? Is the idea to hope that less than 1000 actors are started between calls to this api?

**Comment by alanwguo** [comment]
> +1 to a test, also a few other questions:
> 
> why 1000? I ask because release tests launch more actors that that I think?
> 
> also it seems like we're trying to solve the problem statement usually associated with pagination, but we don't have pagination in the core. Do we have a guarantee that we're returning the latest actors (by what definition of latest?)? Is the idea to hope that less than 1000 actors are started between calls to this api?

Yes, the lack of pagination in core is a known issue that will be addressed, but this fix is better than the alternative of api/snapshot being unconsumable because of it's large latency. 

Luckily this is a private internal api and we ingest it with enough frequency that there should be less than 1000 actors in between calls. Secondly, actors are not a critical usecase and we are willing to drop data for the sake of reliability.

**Review by wuisawesome — APPROVED** [review]
I'm still worried about which actors we return with this limit, but when doing the calculus of breaking the entire API and its consumers, or missing some actors, it probably still makes sense to do this as a mitigation/hotfix.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@alanwguo let's start discussing the API server stability requirements & improvements in general as soon as we finish Ray 2.0. I think we should prioritize this. (cc @scv119 )

**Pull request merged**
