### PR TITLE
[RLlib] Tests for connectors are not easily identifiable as such

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Signed-off-by: Artur Niederfahrenhorst <artur@anyscale.com>

## Why are these changes needed?
Screenshot 2022-09-28 at 12 40 07

Connector tests are only listed with "test_agent" and "test_action".
Both don't give away much about what is tested.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by sven1977 — APPROVED** [review]
Nit: Can we change these to:
```
name = "connectors/tests/test_action"
name = "connectors/tests/test_agent"
```
?
This would be the same then as most other tests from some sub-directory within RLlib, e.g. `policy/tests/test_policy.py`

**Comment by sven1977** [comment]
Also need to specify `src` then in the BUILD file, I guess.

**Comment by ArturNiederfahrenhorst** [comment]
> Also need to specify `src` then in the BUILD file, I guess.

Can't follow you with this one! The srcs always has to be defined in the BUILD file and is present for both test-cases, no?
What am I missing?

**Comment by sven1977** [comment]
I guess it's ok now. The py_test statements in BUILD need to have a reference to the actual py filename, iff the name does not match that filename. That's why I thought I saw an error before, but it seems resolved now. Will merge once all tests have passed ...

**Pull request merged**
