### PR TITLE
[tune] Support infinity value in report result

### PR DESCRIPTION
**Pull request by old-bear**
## What do these changes do?
Use default implementation of `iterencode` in `_SafeFallbackEncoder`, which supports serialization of `float('inf')`. The former code seems to be unnecessary according to the comments in the issue

## Related issue number
#2669

### CODE REVIEW

**Comment by richardliaw** [comment]
Can you add tests for this? Specifically for `nan` and `inf` values?

**Review by ericl — APPROVED** [review]
LGTM assuming tests pass-- I'm assuming we have tests for the safe encoding case ;)

**Comment by old-bear** [comment]
@richardliaw Done, and this UT will fail if we keep using the older JsonEncoder:
```
Result for f1_0:
Error processing event: Traceback (most recent call last):
  File "/Users/Bear/Playground/ant-ray/venv/lib/python2.7/site-packages/ray/tune/trial_runner.py", line 282, in _process_events
    result, terminate=(decision == TrialScheduler.STOP))
  File "/Users/Bear/Playground/ant-ray/venv/lib/python2.7/site-packages/ray/tune/trial.py", line 352, in update_last_result
    print("  {}".format(pretty_print(result).replace("\n", "\n  ")))
  File "/Users/Bear/Playground/ant-ray/venv/lib/python2.7/site-packages/ray/tune/logger.py", line 208, in pretty_print
    return yaml.safe_dump(json.loads(cleaned), default_flow_style=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by richardliaw** [comment]
jenkins retest this please

**Comment by ericl** [comment]
Tests look good, pytorch crash is unrelated.

**Pull request merged**
