### PR TITLE
[RLlib] Remove unneeded args from offline learning examples

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
## Why are these changes needed?

We largely got rid of replay buffers in the context of offline RL in RLlib, but the examples have not beed changed.
This PR gets the offline learning example back on track.

#26665 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by gjoliver — DISMISSED** [review]
I am actually not a fan of learning_starts -> min_size.
min_size seems to imply the size of the RB, not how many samples there are in the buffer.

**Comment by ArturNiederfahrenhorst** [comment]
> I am actually not a fan of learning_starts -> min_size. min_size seems to imply the size of the RB, not how many samples there are in the buffer.

This comment is directed at another PR that moves the learning_starts parameters but needed to be merged into this one because they interfere. The comment has been resolved in the other PR.

**Review by kouroshHakha — APPROVED** [review]
Approved conditioned on all tests passing.

**Comment by sven1977** [comment]
Hey @gjoliver , could you approve this, so it can be merged, now that questions have been addressed?

**Pull request merged**
