### PR TITLE
[Core][Python Worker] Add pid to log file name

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

I add pid to python worker's log file name. This is very useful  to find worker's log when debugging.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by lixin-wei** [comment]
@wuisawesome could you please review this PR?

**Comment by wuisawesome** [comment]
Can we update this too? https://github.com/ray-project/ray/blob/edd783bc327760a4892ab89222ee551e42df15b9/python/ray/log_monitor.py#L23

**Review by wuisawesome — APPROVED** [review]
As long as tests pass, once that regex is changed, I think we can just go ahead and merge this.

**Comment by lixin-wei** [comment]
> Can we update this too?
> 
> https://github.com/ray-project/ray/blob/edd783bc327760a4892ab89222ee551e42df15b9/python/ray/log_monitor.py#L23

Done. Please have a look.

**Comment by lixin-wei** [comment]
@wuisawesome Hi, test passed, can this PR be merged?

**Pull request merged**
