### PR TITLE
[Test] allow `Cluster` to connect to a running cluster

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Commands in `e2e.py` are ran with `ray job submit` on api server. But calling `ray stop` would kill the api server. This seems to make commands after `ray stop` unable to access the dashboard.

Instead, only kill the raylet started by default and use `Cluster` to connect to the existing cluster.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
cc @rkooo567 the goal here is to avoid failures in weekly tests due to running `ray stop` then submit a job. But this PR may introduce issues too.

**Comment by iycheng** [comment]
I feel we probably need to upgrade these tests and don't use `ray stop`. Or just run these with buildkite env. These tests seem only need a single machine to run.

But, for now, the short-term solution seems fine to me. @rkooo567 it's your call.

**Comment by rkooo567** [comment]
I am actually very confused about the original tests... Why do we need ray stop for all prepare scripts for these tests? This seems very weird

**Comment by rkooo567** [comment]
I see. I think the proposed solution sounds like working short term solution. But can you try running it first before merging this PR?

Also, it seems like the cleaner approach is to remove `Cluster` and just use real multi node clusters, does this sound reasonable? I can probably follow up in the sooner future

**Comment by mwtian** [comment]
> I see. I think the proposed solution sounds like working short term solution. But can you try running it first before merging this PR?
> 
> Also, it seems like the cleaner approach is to remove `Cluster` and just use real multi node clusters, does this sound reasonable? I can probably follow up in the sooner future

Sounds reasonable.

**Review by rkooo567 — APPROVED** [review]

**Comment by mwtian** [comment]
There seems to be an issue on nightly. Fixing.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Review by krfricke — CHANGES_REQUESTED** [review]
Lmk if this is still needed in new infra

**Pull request closed without merging**
