### PR TITLE
Support object spilling mode and data load failure mode in dask_on_ra…

### PR DESCRIPTION
**Pull request by jennakwon06**
…y_large_scale_test.py

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by jennakwon06** [comment]
@rkooo567

**Review by rkooo567 — APPROVED** [review]
This is a really great PR!! Thank you so much for making a great script :)!

**Review by fishbone — APPROVED** [review]
Thanks for the contribution!

**Comment by jennakwon06** [comment]
Great :) @rkooo567 , I am not authorized to merge this PR; let me know how I can merge it or whether you can do that!

**Pull request merged**
