### PR TITLE
Add Job Detail page

### PR DESCRIPTION
**Pull request by alanwguo**
The existing job detail page didn't work at all. There was no API feeding it data. Update the page to have new behavior:
- Meta data about the job
- progress bar for the tasks for the job
- TODO: a task list that shows progress split by task name.

Also:
Created Metadata common component for showing metadata about an entity
Created DurationText component for an automatic updating duration timer text

Screen Shot 2022-10-12 at 6 08 14 PM

Signed-off-by: Alan Guo <aguo@anyscale.com>

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
lmk when this is ready to review!

**Review by shawnpanda — APPROVED** [review]

**Comment by alanwguo** [comment]
> lmk when this is ready to review!

Ready for review!

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
are the new frontend tests currently executed from CI?

**Comment by alanwguo** [comment]
> are the new frontend tests currently executed from CI?

I was going to do that in a future PR but decided to include it in this one. Tests seem to be running now. I'll let you know when this is ready to merge

**Comment by alanwguo** [comment]
@rkooo567 , this hsould be ready to merge once tests pass

**Comment by rkooo567** [comment]
Really excited for this feature!

**Pull request merged**
