### PR TITLE
[core] Lazy import of pydantics 

### LINKED ISSUE #41338: [ci][core] Perf regression on tasks_per_second, pgs_per_second
### What happened + What you expected to happen

Regression on: 

image

image

### Versions / Dependencies

5a7071e5b0 [Core] Remove dead gcs monitor service (#41262)
1a986dea21 [data] add support for multiple group keys in map_groups (#40778)
84c0ba05a7 [Data] Expose max_retry_cnt parameter for BigQuery Write (#41163)
25bee340cc [GCS FT] Update Redis connection configs (#40860)
709dc1b710 [ci] build anyscale images for gcp (#41224)
31c6631b8c Make Ray compatible with `pydantic>=2.5.0` (#40451)
9dec6183c7 [ci] mark two core functions as flaky (#41237)
9a34839f7d [Doc][KubeRay]: Redis eviction suggestions when `ENABLE_GCS_FT_REDIS_CLEANUP=false` (#40949)
29dba630ba [KubeRay] [Doc] Update the link of KubeRay API reference (#41236)
7c7eaf2a6a [Train][Tune] Support reading train result from cloud storage (#40622)
7a75d096a4 [core][gcs] Remove ByteSizeLong call from GcsTaskManager (#41108)
8209893aa6 [core] make ProcessFD, [Client,Server]Connection non copyable. (#41106)
ca29feccd2 [RLlib] New ConnectorV2 API #01: Some preparatory cleanups and fixes. (#41074)
0e2a523374 Make Ray work on GH200 (#40816)

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
Closes https://github.com/ray-project/ray/issues/41338

The hypothesis is that we are importing some additional things when initializing the python workers, and changing the import to lazy seems to fix the issue. 

See https://buildkite.com/ray-project/release/builds/2492#018c1923-c5d0-4e09-a67e-b45cf2c3b553

Master: tasks_per_seconds = 430
This PR: tasks_per_seconds = 530

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
https://buildkite.com/ray-project/release/builds/2492#018c1923-c5d0-4e09-a67e-b45cf2c3b553 release test perf back to 530 level.

**Review by rkooo567 — APPROVED** [review]
Q: consider adding a unit test to avoid regression? (i.e., import serialization_addon.py and make sure libs are not imported

**Comment by rickyyx** [comment]
> Q: consider adding a unit test to avoid regression? (i.e., import serialization_addon.py and make sure libs are not imported

Sure - but i think what's more important is how we prevent this from happening again.

**Comment by rickyyx** [comment]
> > Q: consider adding a unit test to avoid regression? (i.e., import serialization_addon.py and make sure libs are not imported
> 
Sure - but i think what's more important is how we prevent this from happening again.

Don't

**Pull request merged**
