### PR TITLE
Turn dashboard UI off by default.

### PR DESCRIPTION
**Pull request by robertnishihara**
@ls-daniel what do you think of this?

This is essentially about managing expectations since there are some hiccups regarding the UI experience.

### CODE REVIEW

**Comment by ls-daniel** [comment]
Fairly indifferent. Do you have links to the issues, though?

**Comment by robertnishihara** [comment]
Thanks @ls-daniel, I ran into https://github.com/ray-project/ray/issues/4201.

**Comment by pcmoritz** [comment]
Let's merge it for this release and fix the issues + make it on by default again for the next

**Review by pcmoritz — APPROVED** [review]

**Comment by ls-daniel** [comment]
This wasn't actually enableable for me. Fixed in #4285.

**Pull request merged**
