### PR TITLE
[WIP] Avoid copying task spec for direct call submitter

### PR DESCRIPTION
**Pull request by zhijunfu**
## Why are these changes needed?

Right now TaskSpec is copied when the task is submitted, because we need to retry the task if it fails for direct task calls. Right now the copy is done for both direct actor and direct task call. There's also a copy on the receiver side when translating the task request to task spec.

This PR removes the copy for task submission by allowing `TaskSpecification` to hold a shared_ptr of `PushTaskRequest`. The copy is only required when the failed task is retried, it's actually on-demand and doesn't impact the main code path.  It also removes copy for task execution using the same way.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by ericl** [comment]
How's the ray microbenchmark results before and after?

**Comment by zhijunfu** [comment]
> How's the ray microbenchmark results before and after?

Here are the microbenchmark numbers. Also I saw a 20% time reduction for core_worker_test.

Before:
-------
single client tasks sync per second 1151.0 +- 113.13
single client tasks async per second 5223.35 +- 1370.85
multi client tasks async per second 9567.61 +- 768.44
1:1 actor calls sync per second 1856.25 +- 97.32
1:1 actor calls async per second 4098.37 +- 164.53
1:1 actor calls concurrent per second 4475.26 +- 387.33
1:n actor calls async per second 6263.96 +- 531.73
n:n actor calls async per second 9999.81 +- 307.26
n:n actor calls with arg async per second 4719.55 +- 221.85

After:
-----
single client tasks sync per second 1190.62 +- 99.28
single client tasks async per second 6206.01 +- 780.55
multi client tasks async per second 10127.21 +- 761.12
1:1 actor calls sync per second 1964.01 +- 94.53
1:1 actor calls async per second 3928.8 +- 398.92
1:1 actor calls concurrent per second 4749.61 +- 253.08
1:n actor calls async per second 6618.14 +- 449.69
n:n actor calls async per second 10879.2 +- 726.29
n:n actor calls with arg async per second 5090.14 +- 487.59

**Comment by ericl** [comment]
Seems like lots of Travis errors

**Comment by zhijunfu** [comment]
> Seems like lots of Travis errors

Mostly related unit tests and gcs rpc server, which didn't get compiled locally when I built ray. These are fixed, but there're still some unit test failures so far.

**Comment by zhijunfu** [comment]
> @zhijunfu What's the progress on this PR? Is it addressed in a different way?

This hasn't been actively worked on for quite a while I believe, and some of the changes might be out-of-date now.

**Comment by rkooo567** [comment]
I will then close it. Please reopen if you have a plan to continue!

**Comment by zhijunfu** [comment]
> I will then close it. Please reopen if you have a plan to continue!

Sure, thanks

**Pull request closed without merging**
