### PR TITLE
[WIP] Implementing Gcs sharding after putting Gcs data into redis data shard

### PR DESCRIPTION
**Pull request by heyucongtom**
## What do these changes do?

Basically a re-implementation of #2281, with modifications of #2298.
[+] Implement sharding for gcs tables. 
[+] Keep ClientTable and ErrorTable managed by the primary_shard. TaskTable is managed by the primary_shard for now, until a good hashing for tasks is implemented. 
[+] Move AsyncGcsClient's initialization into Connect function.
[-] Move GetRedisShard and bool sharding from RedisContext's connect into AsyncGcsClient. This may make the interface cleaner.

Please help review the changes and let me know if anything looks problematic.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@heyucongtom I think some unwanted changes got into this PR (perhaps through some rebasing). Now that #2298 has been merged, I think this PR can be simplified a bit.

**Comment by heyucongtom** [comment]
Sure. I would take a look. Could you point out some changes that shall be
reverted?

I do make some changes with regard to #2298. Is that part the problematic
one?

**Comment by robertnishihara** [comment]
E.g., all of the `#if !RAY_USE_NEW_GCS` changes. The addition of the `GetRedisShards` function.

**Comment by heyucongtom** [comment]
Emm these are interesting. Probably I will open up a new PR and work with
the current master.

**Pull request closed without merging**
