### PR TITLE
[RLlib] Faster remote worker space inference (don't infer if not required).

### PR DESCRIPTION
**Pull request by sven1977**
If an env is not constructed on the local worker (which is the default behavior), observation- and action spaces must be inferred from one of the remote workers. This causes the Trainer construction to take a considerable longer time (a few seconds) than w/o this step (ray.get).
This PR avoids this remote worker space lookup in case:
- we do have an env on the local worker (create_env_on_driver=True).
- observation AND action spaces are given manually via the config's "observation_space" and "action_space" keys.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sven1977** [comment]
@RuofanKong ^^

**Review by avnishn — APPROVED** [review]
LGTM 

Is there a small test that you want to add here first potentially? @sven1977

**Comment by sven1977** [comment]
Good point! I'll add this to `test_trainer.py`.

**Comment by sven1977** [comment]
Test case added.

**Pull request merged**
