### PR TITLE
Revert "[RLlib] Fix policy restore. Avoid keyward params. (#29227)"

### PR DESCRIPTION
**Pull request by jiaodong**
This reverts commit 75e9722a4d9c0d8d5cb0c37eb6316553f9e0789e.

Revert offending PR that leads to master test failure

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by avnishn — APPROVED** [review]

**Comment by Yard1** [comment]
I don't think this is related to Serve (starlette) test failures at all, and the CI for this PR is not running the tests that fail.

**Comment by gjoliver** [comment]
ditto. I am gonna be surprised, if this PR breaks Serve ...

**Comment by jiaodong** [comment]
i don't think this is directly related to master failure either but i need to at least kick off new rounds of CI to get signals before triaging to serve. cc: @simon-mo

**Comment by Yard1** [comment]
Can we make a dummy change to the serve files to kick off the tests then?

**Pull request closed without merging**
