### PR TITLE
[wip] Cleanup LRT

### PR DESCRIPTION
**Pull request by barakmich**
Move the release tests out from `ci/` to the new `release/` folder.

Flatten all the subtests into a common structure -- a release should be one project, and the new kickoff script should make it easy to run individual tests within that one project, for a given SHA. 

`cluster.yaml` is per subtest-set and should be called directly on `anyscale run`

There should be no setup commands in cluster.yaml -- since they were split between `run.sh` and those setup commands, it should live entirely in run.sh, as it's ultimately a script.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Btw, can you also update those test result to doc/dev/release_logs/1.0.0 for 1.0?

**Comment by rkooo567** [comment]
Also, cc @simon-mo Do we need any refactoring to release after this PR?

**Comment by simon-mo** [comment]
Let's merge this and update tests in https://github.com/ray-project/releaser later.

@barakmich good news, Sang and I built the took to basically do `kickoff.sh` in more programmable way.

cc @wuisawesome plz let me know when do you want to start release testing and I will guide you through the tool

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
LINT passed. Merging. cc @wuisawesome please cherry pick so you can use these for release testing.

**Pull request merged**
