### PR TITLE
Fix the problem that ray.remote reference is not visible at a document.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

`ray.remote` document is not visible at the latest document. It is because we use `fake_ray.remote` for doc generation. 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by simon-mo** [comment]
can you revert the deletion of `doc/_build/.gitkeep`? you can just `touch doc/_build/.gitkeep`

**Review by simon-mo — APPROVED** [review]
lgtm, let's check if the doc build successfully

**Comment by rkooo567** [comment]
@simon-mo  Btw, `format.sh` deleted `/doc/_build/.gitkeep`. I am wondering if it is okay? Can you confirm?

**Comment by rkooo567** [comment]
Jenkins test this please.

**Comment by rkooo567** [comment]
Jenkins test this please.

**Comment by simon-mo** [comment]
@rkooo567 don't worry about jenkins test, can you add `.gitkeep` back? once you have done that i'll merge it

**Comment by rkooo567** [comment]
@simon-mo  Please force merge once it is ready.

**Comment by fyrestone** [comment]
`@ray.remote` will be executed when sphinx generating doc. If a `isinstance(x, cython type)`  exists in `@ray.remote` logic, sphinx will raise an exception because cython types are mocked as objects not types.

**Review by raulchen — APPROVED** [review]
Thanks for fixing this.

**Comment by simon-mo** [comment]
@fyrestone the doc seems to be building with this PR (without the exception). Is there any way we can catch the `instance(x, cython type)` error? If so we you help us create a separate PR to fix the cython mocking?

**Pull request merged**
