### PR TITLE
[ci] Add flag for staging tests and disable the unstable one.

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
This PR tries to add a prefix for the staging ci test. This is useful to separate staging tests from stable tests in `https://flakey-tests.ray.io/`

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
I'm not sure how to do this job better.... Welcome any suggestions.

**Comment by scv119** [comment]
cc @mwtian

**Comment by mwtian** [comment]
Is it possible to do this in the `flakey-tests.ray.io` pipeline? It seems the pipeline already separates test results by platform (linux / macos / windows). I wonder if we can add the build step to that as well ..

**Comment by iycheng** [comment]
> Is it possible to do this in the `flakey-tests.ray.io` pipeline? It seems the pipeline already separates test results by platform (linux / macos / windows). I wonder if we can add the build step to that as well ..

@simon-mo  do you have some idea here?

**Comment by simon-mo** [comment]
What's the end goal here? Do you want them not showing up in flaky tests pipeline? Or put them in a separate group or something?

**Comment by iycheng** [comment]
> What's the end goal here? Do you want them not showing up in flaky tests pipeline? Or put them in a separate group or something?

Just putting them into the separate groups is good enough. The goal is that for some tests, oncall is not supposed to keep track of them since they are unstable and baking and the dev people will turn on the flag and remove the pipeline eventually. And we probably shouldn't count them into the metrics as well.

For example: linux://python/ray/tests:test_actor_resources is flaky recently, but actually all failure come from staging pipeline, and the feature is not turned on by default which won't impact the prod quality:

image

The idea here is to isolate them (put them into a separate page or just different name) so that the oncall can focus on the real issue and the dev people can fix the issue and plan for rolling out.

**Review by rkooo567 — APPROVED** [review]

**Comment by iycheng** [comment]
@simon-mo  could you check whether this is something you mentioned?

**Comment by simon-mo** [comment]
Yes but the test_large seems be having issue because the arg needs to be passed before target https://buildkite.com/ray-project/ray-builders-pr/builds/32137#acacba45-5851-4f18-ba0c-003f89e38594/252-261

**Review by simon-mo — APPROVED** [review]
LGTM. Please double check the bazel command in log before merge

**Comment by iycheng** [comment]
Manually check it and everything looks good.

**Comment by iycheng** [comment]
Also //python/ray/tests:test_actor_resources is turned off for staging tests shortly.

**Comment by simon-mo** [comment]
I'll work on flaky tracker improvement early next week.

**Comment by iycheng** [comment]
Thank you @simon-mo !

**Pull request merged**
