### PR TITLE
[KubeRay][Doc] KubeRay doc migration (3/n)

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

1. Rewrite the autoscaling doc
2. Move some advanced content to a new doc (`k8s-autoscaler.md`). I did not make any content changes for this part.
3. Update the YAML file by https://github.com/ray-project/kuberay/pull/1400.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @gvspraveen @architkulkarni @angelinalg 

Due to the urgency of the release, I opened a PR to the release branch directly. I will cherry-pick the PR to the master branch once it is merged into the release branch.

**Review by zhe-thoughts — APPROVED** [review]
Clean docs change and qualifies for picking

**Review by architkulkarni — APPROVED** [review]
Looks great and very polished!

**Comment by zhe-thoughts** [comment]
Actually @kevin85421 @architkulkarni could you help explain why this was not landed on master first?

**Comment by kevin85421** [comment]
> Actually @kevin85421 @architkulkarni could you help explain why this was not landed on master first?

Nothing special here. I just want to get the top priority thing (merge into the release branch) done first.

**Comment by GeneDer** [comment]
@kevin85421 btw both linkcheck and doctest are failing. Let me update branch to see if those are fixed

**Comment by zhe-thoughts** [comment]
@kevin85421 @architkulkarni Let's merge into master first and cherry pick

**Comment by kevin85421** [comment]
Close this one. I will open a cherry-pick PR after https://github.com/ray-project/ray/pull/39396 is merged.

**Pull request closed without merging**
