### PR TITLE
Fix ray website

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by robertnishihara** [comment]
This seems to have broken the images in the release blog post.

**Comment by pcmoritz** [comment]
Thanks, good call. It's fixed now.

**Comment by robertnishihara** [comment]
If the site lives at https://github.com/ray-project/ray-project.github.io, then there's no real reason to have the `_site` directory in this repo, right? Shall we just remove it?

**Comment by pcmoritz** [comment]
The consensus is to keep the site/ folder in the ray repo and make it the master copy; the one that is hosted on ray-project.github.io is just for serving the website.

**Pull request merged**
