### PR TITLE
added _get_policy_class as a class variable of rllib.agents.trainer_t…

### PR DESCRIPTION
**Pull request by ZhongxiaYan**
…emplate.trainer_cls

## Why are these changes needed?

Added a _get_policy_class class variable to trainer_cls, to facilitate getting the policy class. This is useful for getting the pytorch version of the policy.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by ericl** [comment]
Can you call `trainer.workers.local_worker.get_policy().__class__` instead?

**Comment by ZhongxiaYan** [comment]
So I think this defeats the purpose. For specifying multiagent policies through the config['multiagent'] field, I need the policy (either TFPolicy or TorchPolicy), but I would like the trainer to get it for me than manually getting it. I can't create a trainer because I'm calling tune.run instead of creating a trainer myself.

**Comment by ericl** [comment]
You can specify None for the multiagent policy and it will be filled in with the default policy, does that work?

**Comment by ZhongxiaYan** [comment]
Oh that's perfect! Thanks!

**Pull request closed without merging**
