### PR TITLE
Bump max_placement_group_load_report_size to 1k

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
Placement groups are sometimes used to bypass throttling, this config is too small that limits the number of pending placement groups the autoscaler is aware of at a time.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Comment by rkooo567** [comment]
Will this fix https://github.com/ray-project/ray/issues/15801? It looks like this shouldn't be the root cause of the isuse you are seeing?

**Review by rkooo567 — APPROVED** [review]

**Comment by simon-mo** [comment]
No it won't fix it. But it can make scaling up a lot faster.

**Comment by wuisawesome** [comment]
In general, we want this PR. The original 100 number was arbitrarily picked (assuming placement groups would have multiple bundles).

**Comment by rkooo567** [comment]
Hmm I have no strong objection, but note that this means we can iterate 1000 pgs every 1 second (which is probably fine but it could be problematic because the gcs server shouldn't use high CPU in general). But again, I am fine with the change.

**Comment by wuisawesome** [comment]
We only call the codepath ever 5s though. (Also @simon-mo can you bump up the `max_resource_shapes_per_load_report` too? Otherwise you'll see slow scaling when you turn the placement group flag off in serve)

**Comment by rkooo567** [comment]
Hmm I think it is 1 second here? https://github.com/ray-project/ray/blob/0dc34566fe0b99af53d14b8e02ab111cf25f794a/src/ray/gcs/gcs_server/gcs_placement_group_manager.cc#L588

Maybe there's other path as well?

**Comment by wuisawesome** [comment]
oh yeah i forgot the placement group load is calculated in a weird way. we can prob bump that constant to 5s too. The autoscaler is the only caller of the endpoint.

**Comment by wuisawesome** [comment]
(or better yet, run that function lazily instead)

**Comment by rkooo567** [comment]
Can we just do that here? (instead of just bumpting the value up to 1000)? We can probably at least make it tick every 5 seconds

**Comment by simon-mo** [comment]
can one of you, plz just push to this branch directly :-). You can use github cli to checkout the right branch: `gh pr checkout 15866`.

**Comment by rkooo567** [comment]
Hmm I can do tomorrow.

**Comment by rkooo567** [comment]
Btw, feel free to merge it first I will make a separate pr

**Comment by wuisawesome** [comment]
I think merging this isn't time sensitive (you can always mitigate this with system-config). Let's just do one commit where we do the necessary changes.

**Comment by simon-mo** [comment]
In favor of https://github.com/ray-project/ray/pull/15884

**Pull request closed without merging**
