### PR TITLE
Synchronous parameter server example.

### PR DESCRIPTION
**Pull request by elibol**
## What do these changes do?

Implements an example, with documentation, of a synchronous parameter server.

@robertnishihara @pcmoritz

### CODE REVIEW

**Comment by robertnishihara** [comment]
ok to test

**Review by robertnishihara — APPROVED** [review]
This looks great! Really nice work.

I pushed a few changes, mostly just tried to simplify things a little bit and consolidate the documentation for the sync and async examples.

**Comment by elibol** [comment]
Thanks!

**Comment by pcmoritz** [comment]
Looks great, this is really exciting :)

**Pull request merged**
