### PR TITLE
[AIR] Discard returns of train loops in Trainers

### PR DESCRIPTION
**Pull request by Yard1**
## Why are these changes needed?

Discards returns of user defined train loop functions to prevent deser issues with eg. torch models. Those returns are not used anywhere in AIR, so there is no loss of functionality.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]
Nice thanks @Yard1!

**Comment by richardliaw** [comment]
Can we document this behavior somewhere?

**Comment by matthewdeng** [comment]
Nice, can we also update the docs to not include returns?

**Comment by Yard1** [comment]
Documented!

**Pull request merged**
