### PR TITLE
[serve] catch errors caused by bad deployment configurations

### LINKED ISSUE #20396: [Serve][Bug] invalid runtime env cause Serve controller to error forever
```python
from ray import serve

serve.start()

@serve.deployment
def f(): pass

f.options(ray_actor_options={"runtime_env": {"working_dir": "."}}).deploy()
```

Serve doesn't support working per for per deployment because they won't be uploaded dynamically. However, this is erroring infinitely in controller, when you run the script, you can see the following printed out
```
(ServeController pid=28094) 2021-11-15 15:16:54,985	ERROR controller.py:201 -- Exception updating deployment state.
(ServeController pid=28094) Traceback (most recent call last):
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/_private/runtime_env/validation.py", line 36, in validate_uri
(ServeController pid=28094)     protocol, path = parse_uri(uri)
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/_private/runtime_env/packaging.py", line 169, in parse_uri
(ServeController pid=28094)     protocol = Protocol(uri.scheme)
(ServeController pid=28094)   File "/Users/simonmo/miniconda3/lib/python3.6/enum.py", line 293, in __call__
(ServeController pid=28094)     return cls.__new__(cls, value)
(ServeController pid=28094)   File "/Users/simonmo/miniconda3/lib/python3.6/enum.py", line 535, in __new__
(ServeController pid=28094)     return cls._missing_(value)
(ServeController pid=28094)   File "/Users/simonmo/miniconda3/lib/python3.6/enum.py", line 548, in _missing_
(ServeController pid=28094)     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
(ServeController pid=28094) ValueError: '' is not a valid Protocol
(ServeController pid=28094)
(ServeController pid=28094) During handling of the above exception, another exception occurred:
(ServeController pid=28094)
(ServeController pid=28094) Traceback (most recent call last):
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/controller.py", line 199, in run_control_loop
(ServeController pid=28094)     self.deployment_state_manager.update()
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/deployment_state.py", line 1388, in update
(ServeController pid=28094)     deleted = deployment_state.update()
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/deployment_state.py", line 1141, in update
(ServeController pid=28094)     running_replicas_changed = self._scale_deployment_replicas()
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/deployment_state.py", line 919, in _scale_deployment_replicas
(ServeController pid=28094)     self._target_version)
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/deployment_state.py", line 395, in start
(ServeController pid=28094)     self._actor.start(deployment_info, version)
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/deployment_state.py", line 189, in start
(ServeController pid=28094)     **deployment_info.replica_config.ray_actor_options).remote(
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/actor.py", line 496, in options
(ServeController pid=28094)     new_runtime_env = ParsedRuntimeEnv(runtime_env)
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/_private/runtime_env/validation.py", line 299, in __init__
(ServeController pid=28094)     validated_option_val = validate_fn(option_val)
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/_private/runtime_env/validation.py", line 73, in parse_and_validate_working_dir
(ServeController pid=28094)     validate_uri(working_dir)
(ServeController pid=28094)   File "/Users/simonmo/Desktop/ray/ray/python/ray/_private/runtime_env/validation.py", line 39, in validate_uri
(ServeController pid=28094)     f"{uri} is not a valid URI. Passing directories or modules to "
(ServeController pid=28094) ValueError: . is not a valid URI. Passing directories or modules to be dynamically uploaded is only supported at the job level (i.e., passed to `ray.init`).
```

cc @edoakes

### PR DESCRIPTION
**Pull request by iasoon**
## Why are these changes needed?

When a deployment is faulty due to bad user configuration (such as in #19771, #20396) the serve controller code will error forever. This PR catches deployment errors and reports them back to the `deploy` caller.

## Related issue number

Closes #20396

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@iasoon looks like there's a merge conflict. Also, I don't think we can rely on `tblib` here as it's a third-party dependency and we want to avoid dependencies to keep ray as slim as possible (unless they're really needed). You can see the ones currently depended on here:
https://github.com/ray-project/ray/blob/master/python/setup.py

**Comment by edoakes** [comment]
I believe we are currently passing the traceback as a string -- the relevant code is here:
https://github.com/ray-project/ray/blob/master/python/ray/exceptions.py#L66

We should be able to do the same thing here?

**Comment by edoakes** [comment]
Aside from tblib part, the changes looks reasonable to me

**Comment by iasoon** [comment]
@edoakes I switched the implementation to use RayTaskError, similar to errors that happen when calling a deployment. Does that look okay to you?

**Comment by jiaodong** [comment]
Looks good to me as well, thanks for helping to improve this !

**Review by edoakes — APPROVED** [review]
`RayTaskError` might not be ideal but I can't think of a better alternative for now. Thanks for the contribution :)

**Pull request merged**
