### PR TITLE
[Core] [Hackathon] Affinity and anti-affinity prototype (2/n): Taints and tolerations for inverted anti-affinity.

### PR DESCRIPTION
**Pull request by clarkzinzow**
## Motivation
When attempting to isolate workloads, relying on explicit task --> resource anti-affinity can result in whack-a-mole problem: every task that we want to avoid the resource must **explicitly opt-out**, which can become unwieldy as the number of tasks increases. By providing an option to invert this anti-affinity, where the **resource** expresses an anti-affinity such that all tasks **implicitly opt-out** unless the tasks indicate otherwise, this problem becomes much more tenable.

In this PR, we add support for such inverted anti-affinity by adding node taint labels and the ability for actors and tasks to tolerate these taints. This is very similar to the Kubernetes [taints and tolerations concept](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/).

This PR also adds the necessary plumbing for specifying a taint for a node type in the cluster config.

## API

A new node attribute, `taint`, is added, which can be specified at node startup time.
```
ray start --taint=foo
```
It can also be specified in the cluster config:
```
available_node_types:
    ray.head.default:
        taint: head_node
        ....
    some_pool:
        ...
    foo_pool:
        taint: foo
        ...
```

A new task option, `tolerations`, is added as well; this specifies the taints that this actor/task tolerates.
```python
@ray.remote(tolerations=["foo"])
class Worker:
    pass

@ray.remote
def do_something():
    pass

result = do_something.options(tolerations=["foo", "bar"]).remote()
print(ray.get(result))
```

**Note:** I'm slightly more in favor of the `tolerate=` verb for the tolerations API, but I thought it'd be better to piggyback heavily off of the existing Kubernetes tolerations concept, which uses `tolerations` for its API.

## Use case 1 - isolating CPU and GPU workloads

When trying to keep CPU-bound and GPU-bound work separate, it can be useful to ensure that CPU-bound work is only scheduled onto the non-GPU nodes. We can add a `"gpu_node"` taint to all GPU nodes, and ensure that only the GPU workload tolerates the taint.
```
# Start nodes.
ray start --head
ray start
ray start --taint=gpu_node --num-gpus=4
ray start --taint=gpu_node --num-gpus=4
```
or, using a cluster config
```
available_node_types:
    ray.head.default:
        taint: head_node
    ray.worker.cpu:
        node_config:
            InstanceType: m4.xlarge
    ray.worker.gpu:
        taint: gpu_node
        node_config:
            InstanceType: p3.8xlarge
```
```python
@ray.remote
def do_cpu_work(a):
    return a + 1

# Tolerates the "gpu_node" taint.
@ray.remote(tolerations=["gpu_node"])
class GPUWorker:
    pass

workers = [GPUWorker.remote() for _ in range(10)]

# Because do_cpu_work doesn't tolerate the "gpu_node" taint,
# do_cpu_work won't be scheduled onto the nodes with that taint.
result = do_cpu_work.remote()
print(ray.get(result))
```

TODOs:

- [ ] Update tests.
- [ ] Add `tolerations=` API for placement groups to enable placement group bundle allocation on tainted nodes.
- [ ] Add autoscaler integration.
- [ ] Add loud logging for infeasibility conditions.

### CODE REVIEW

**Comment by ericl** [comment]
This is great 👍 what's missing from productionization of this? One thing I can think of is autoscaler integration, but I imagine it's fairly straightforward.

**Comment by clarkzinzow** [comment]
>what's missing from productionization of this?

@ericl I assumed that we'd want to talk a bit more about:
1. Whether there is a need for inverted anti-affinity (my opinion is strongly yes, CPU and GPU workload isolation being a very common use case).
2. Whether we like this taint + tolerations API. Small thing, I actually like the `tolerate=` arg name more than `tolerations=`, but I think that the latter will map better to infra engineers' prior use of k8s taints + tolerations.

>One thing I can think of is autoscaler integration, but I imagine it's fairly straightforward.

Yes, that's definitely the biggest thing missing! It should be a fun problem too, first idea I had was scoping resource demands under tolerations and node resources under intersecting taints, which I _think_ should fit into our current bin packing pretty easily.

**Comment by scv119** [comment]
This is very cool! Some questions we might need to address
- how does this work with other scheduling ideas like placement group? maybe we should not allow taint/placement group to be specified together?
- observability: do we need extra logging/error message, when a taint requirement can't be met?

**Comment by clarkzinzow** [comment]
@scv119 Great questions!
1. I think that we can allow them to be used together. The simplest solution that comes to mind is adding the `tolerations=` API to placement groups; I think this makes sense since placement groups reserve resources, so they should need to tolerate a node's taint if it wishes to reserve its resources. If we do this, scheduling tasks within placement groups could be taint-agnostic.
2. Yes; we already have a debug log when a task is unable to be scheduled onto a node due to a taint, but we should probably have more logging there, especially around infeasibility conditions and within the autoscaler.

**Comment by stephanie-wang** [comment]
One question I have is about the GPU use case. In the example, I think often if you want to specify that it tolerates a "gpu" label, you also want to request `num_gpus=1`. Or are there cases where you would only do one or the other? I wonder if we can come up with something simpler that doesn't require specifying that a task/actor needs a GPU twice.

**Comment by clarkzinzow** [comment]
>One question I have is about the GPU use case. In the example, I think often if you want to specify that it tolerates a "gpu" label, you also want to request num_gpus=1... I wonder if we can come up with something simpler that doesn't require specifying that a task/actor needs a GPU twice.

@stephanie-wang That redundancy is definitely a valid concern and is something that I wrestled with! The Kubernetes model involves the same redundancy, where you would both specify a GPU resource request and a toleration for the GPU nodepool's taint in the pod spec; ideally, we could do better and eliminate this redundancy.

>Or are there cases where you would only do one or the other?

You could want a node to advertise a GPU resource while still allowing non-GPU tasks to be scheduled onto the node, e.g. to properly saturate the node's other resources (CPU), to colocate data loaders that contain a local shuffle buffer with a model trainer, etc. I'm less aware of use cases where you'd want to tolerate a taint that doesn't directly coincide with a resource request... One example is isolating workloads along non-resource lines, such as wanting to reserve the nodes of a particular instance type for a certain sensitive workload in order to prevent noisy neighbor problems. This use case can still be seen as resource-based isolation, but with out-of-band resources that would need to be mirrored with custom resource: `ray start --resources='{"instance_type_2": 1}'` and `ray.remote(resources={"instance_type_2": 0.001})`.

I briefly thought about eliminating this redundancy by shoehorning everything into resources:
1. A node can advertise optional resources (status quo) and required resources, where the latter **must** be requested by a task/actor in order for that task/actor to be scheduled onto the node: `ray start --required_resources='{"foo": 1}'`
2. A task/actor can ask for required resources (status quo) and optional/soft resources, where the latter **can** be present on a node but doesn't have to be, and will be used (a) as a priority tie-breaker among available nodes, and (b) to satisfy nodes advertising required resources: `ray.remote(soft_resources={"foo": 0.001})`

Pros:
1. No new concept for taints/tolerations needed, reducing both external API scope and internal implementation complexity.

Cons:
1. We're shoehorning a binary label constraint into resources, and the user will have to translate their mental model of this binary label into a numerical resource.
2. We're shoehorning this inverted anti-affinity into an inverted required resource, which might be a bit of a mental jump for infra users that are more familiar with the taint + tolerations concepts from Kubernetes.
3. The semantics of resources is now more complicated due to this optional/required distinction on both ends of a resource request.
4. The semantics of soft resource requests and advertised required resources are a bit messy, i.e. how will the magnitude of the resource request affect the node priority, will an advertised required resource be satisfied with a soft resource requests if the advertised required resource is unavailable, etc.
5. We still need a new API addition when starting a node to specify required resources and a new API addition when launching a task to specify soft resources, so it still results in the same API scope expansion, just without introducing entirely new concepts like taints and tolerations.

**Comment by jjyao** [comment]
Really cool!

One thing we need to consider is how it works with `scheduling_strategy`: conceptually seems it can also be viewed as one of the strategies. I think it works orthogonally with "SPREAD" strategy but probably not with "LOCAL_NODE_ONLY" strategy (what if local node has a taint and the task doesn't tolerate it).

**Comment by clarkzinzow** [comment]
>One thing we need to consider is how it works with scheduling_strategy: conceptually seems it can also be viewed as one of the strategies.

@jjyao I've been thinking about taints and tolerations as an extension (even syntactic sugar) for a binary inverted resource, i.e. the node has a resource request (taint) for the task, which either has the resource (toleration) or not. This has caused me to conceptually map this more as a resource extension rather than a scheduling strategy. But maybe that's because I've been thinking of resource requests being used to filter out infeasible nodes (which taints and tolerations does), while the scheduling strategy + the resource requests are subsequently used to choose the "best" node, even thought the placement group scheduling strategy kind of breaks this delineation.

>I think it works orthogonally with "SPREAD" strategy but probably not with "LOCAL_NODE_ONLY" strategy (what if local node has a taint and the task doesn't tolerate it).

Definitely orthogonal to `"SPREAD"` (spread within the tainted nodes), and if we had a `"PACK"` directive it would also be orthogonal to that (pack within the tainted nodes). If there was a `"LOCAL_NODE_ONLY"` strategy _and_ an untolerated taint on the local node, I think we'd detect that hopeless infeasibility in the scheduler and fail the task, or at least log it loudly.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Comment by clarkzinzow** [comment]
Not completely stale (yet), going to revisit this next week.

**Pull request closed without merging**
