### PR TITLE
Unpin Pydantic version

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
Now we merged #11837, let's unpin pydantic version so we stay up to date.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by suquark** [comment]
there seems still some other serialization failures...

**Comment by suquark** [comment]
I cannot reproduce the serialization error. The following script finishes successfully:

```python
from ray.serve import BackendConfig
import ray.cloudpickle

import typing

if __name__ == '__main__':
    obj = [BackendConfig(num_replicas=1, max_batch_size=None, batch_wait_timeout=0, max_concurrent_queries=8)]
    ray.cloudpickle.dumps(obj)
```

**Comment by suquark** [comment]
One thing could be related: pydantic just releases 1.7.2 recently...

**Comment by simon-mo** [comment]
Can you checkout and run serve's test with 1.7.2 though?

**Comment by simon-mo** [comment]
Stale PR, Ray Serve now works with all version of pydantic by using custom serializers

**Pull request closed without merging**
