### PR TITLE
[docs] structural overhaul part II

### PR DESCRIPTION
**Pull request by maxpumperla**
Follow-up of #21667. This time we're reflecting the clean-up in the folder structure by exposing a new overall navigation in alignment with discussions started at the hackathon, overview pics attached. In detail:

- [x] Split into Ray ML, Ray Core, Ray Deployments. 
- [x] All deps are pinned and fairly modern. The TOC collapses enough (this was a problem before) to justify upgrading sphinx and the book theme.
- [x] This implies that we now have docs optimized for mobile, too.
- [x] Some more ground work has been done to consolidate the individual library structures. Not perfect yet, we're iterating on it. Everything is slightly leaner.
- [x] Standalone API references (and FAQ section)

Of note is that the `_toc.yml` now clearly shows you where the current structure differs from the old (namely, when things get imported from other sub-projects).

Screenshot 2022-01-20 at 21 04 54
Screenshot 2022-01-20 at 21 05 20
.

See here for a current build:
https://ray--21759.org.readthedocs.build/en/21759/

### CODE REVIEW

**Comment by ericl** [comment]
Looks great 👍 Especially like putting the libraries first.

**Comment by sijieamoy** [comment]
Love the new structure as well! Some minor questions:
1. The section title "Ray ML" really catches the eyes of ML users. They will instantly know which section to look. In comparison, the "Ray Core" title is less clear or meaningful for new comers. I'll probably wonder what use case is it intended for, what's the relationship with Ray ML libs, etc.
2. (I might be getting too far ahead here) If I am looking for the reference of a particular API, what's the best search box to use? Looks like the API reference section doesn't have its own search, which presumably will be very helpful for generic function names such as `data.show()`.

**Comment by maxpumperla** [comment]
cannot really be salvaged due to revert in #21763 will have to start again. thanks @sijieamoy and @ericl for the review

**Comment by clarkzinzow** [comment]
@maxpumperla I don't think that this PR needs to be closed, couldn't this PR be salvaged with a revert of #21763 (i.e. an un-revert of #21667) along with the `suppress_warnings = ["etoc.toctree"]` fix?

**Comment by maxpumperla** [comment]
@clarkzinzow possibly. but then I have to wait at least 2x as long to get anything shipped. my productivity is already severely hampered by this situation. I need to be able to work in my timezone, not spend my entire Friday getting to where I was yesterday. I'll open a new PR consolidating both closed ones. thanks :v:

**Comment by zhe-thoughts** [comment]
@richardliaw Could you also advise what's the easiest way to merge this? Thanks

**Comment by maxpumperla** [comment]
all good, #21776 is up now. please help get this one reviewed and merged, please. I'd really like to move forward and push this project forward.

**Pull request closed without merging**
