### PR TITLE
[rllib] IMPALA sample throughput calculation and full queue slowdown fixes

### PR DESCRIPTION
**Pull request by Bam4d**
…availablility of data, calculate the sample time with respect to global time rather than local sample time

## Why are these changes needed?

This is a better fix for the issues around IMPALA causing issues when the sample queues are full up.

The fix is twofold:

1) Originally a thread.sleep was used which stopped python threads busy waiting when queues were full as this causes pytorch's CUDA scheduler to misbehave and switch processing to CPU.
* this worked, but caused issues with tests so was removed #16309
* the new solution should not introduce any more latency that is necessary, as it does not wait if the is capacity in the queues or if there are items to be taken from queues. For threads putting items on queues, if the queue is at capacity, waiting will occur through the queue mutex instead of time.sleep (which is more efficient). The same fix is also applied for threads that are waiting to take items off of queues. This stops the busywaiting/releases the GIL while the threads are in the waiting state.

2) The calculation for sample throughput only calculates the throughput of samples from the point the learner thread has stopped learning, and when a new batch is required. it does not take into account the time taken for a batch to be processed. If there is no waiting time between batches this causes the sample throughput to skyrocket as throughput is calculated using samples/waiting_time. 
* The second fix makes sure that waiting time is calulated including the time taken for samples to be gathered + time taken for batch to be processed. This gives an accurate value for sample throughput in all situations.

## Related issue number

#16162
#16309
#16529

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Bam4d** [comment]
@sven1977 @smorad more reliable fix for IMPALA and also the sample rate calculation is more accurate

**Review by sven1977 — APPROVED** [review]
This look super promising! Thanks for digging into this @Bam4d !

Just let me run quick some tests on GPU before I'll merge. ...

**Comment by sven1977** [comment]
Speedup of ~10x (when queue is full due to large number of workers).

Ran this config on a p3dn.24xlarge machine:

```
pong-impala-fast:
    env: PongNoFrameskip-v4
    run: IMPALA
    config:
        framework: torch
        rollout_fragment_length: 50
        train_batch_size: 600
        num_workers: 95
        num_envs_per_worker: 5
        broadcast_interval: 2
        max_sample_requests_in_flight_per_worker: 1
        num_data_loader_buffers: 2
        num_gpus: 2
        lr: 0.001
        model:
          dim: 42
```

**Comment by sven1977** [comment]
DDPG and TD3 tests also look stable now (no more flakiness/slowness in these algos caused by timeouts/sleeps).
Thanks again @Bam4d !

**Comment by smorad** [comment]
This is awesome, thanks @Bam4d!

**Comment by Bam4d** [comment]
> This is awesome, thanks @Bam4d! Much more elegant than the whole `sleep` thing.

Smashing!

**Pull request merged**
