### PR TITLE
[Dashboard] Refresh documentation 1.0.0

### PR DESCRIPTION
**Pull request by mfitton**
## Why are these changes needed?
This PR refreshes the dashboard documentation for the Ray 1.0 release. Many of the images in the documentation were outdated, and some of the explanations needed re-tooling.
I've attached some screenshots of the changed page, but the page is too long to attach all of them here.

Screen Shot 2020-09-09 at 1 46 55 PM
Screen Shot 2020-09-09 at 1 47 20 PM
Screen Shot 2020-09-09 at 1 47 41 PM
Screen Shot 2020-09-09 at 1 47 51 PM
Screen Shot 2020-09-09 at 1 48 05 PM
Screen Shot 2020-09-09 at 1 48 16 PM
Screen Shot 2020-09-09 at 1 48 28 PM

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by simon-mo** [comment]
Should we use the https://github.com/ray-project/images repo so this repo won't be bloated?

**Comment by mfitton** [comment]
Okay, I can do that. I noticed that most of the documentation was linking to the images directory, so I thought that was our convention.

**Comment by simon-mo** [comment]
The screenshots sum up to 1Mb+ which can be pretty big for the source git repo. especially it will stay in the git history forever.

**Review by simon-mo — APPROVED** [review]
LGTM pushed one minor change directly

**Pull request merged**
