### PR TITLE
Experiment code to resolve insufficient cluster resources

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
I doubt that the driver is too fast and fails before the workers get connected. So we need a way to make the driver wait for the workers.

I add a waiting logic in `_update_avail_resources` of `python/ray/tune/trial_runner.py`, which will wait until the resource does not change. It looks like this would solve the problem.

This may not be the final solution, it provide an insight of the solution. 

## Related issue number
https://github.com/ray-project/ray/issues/2649

### CODE REVIEW

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
cc @robertnishihara @pcmoritz

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
Hi, everyone. I may use this PR to do some test of Jenkins test. Please unsubscribe this topic, because the message may be annoying.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins , retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
There will be 2 test results for simple add 2-second wait before shutting down.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

**Comment by ericl** [comment]
Do we still need this? I haven't seen insufficient resources for a while.

**Comment by robertnishihara** [comment]
Closing for now. We can reopen if it makes sense.

**Pull request closed without merging**
