### PR TITLE
[Doc] Add troubleshooting guide about pkg_resources module not found error

### LINKED ISSUE #46205: [Doc] Cannot build docs: No module named 'pkg_resources'
### Description

When I followed the instructions in [the contribution guide](https://docs.ray.io/en/latest/ray-contribute/docs.html) and run `make develop`, the following error occured.

image

Note: I am working on a PR to fix this issue.

### Link

_No response_

### PR DESCRIPTION
**Pull request by MortalHappiness**
## Why are these changes needed?

See the description in the corresponding issue for details.

## Related issue number

Resolves: ray-project/ray#46205

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by MortalHappiness** [comment]
@kevin85421 Can you help me review this PR? Thanks.

**Comment by angelinalg** [comment]
Thank you for filing the issue and making this PR! @peytondmurray @can-anyscale, would you please review?

**Comment by can-anyscale** [comment]
i have seen this error with python 3.12 with other libraries as well; perhaps we can change the instruction to use python 3.11; i get a feeling that many packages out there doesn't work seamlessly with python 3.12 yet (or our requirements-doc.txt doesn't)

**Comment by peytondmurray** [comment]
> perhaps we can change the instruction to use python 3.11

I'd still vote to just bump the version or remove the extension. Active support for 3.11 has already ended months ago, we should really be on 3.12 at the moment IMO, especially since the fix is so straightforward :shrug:

**Comment by MortalHappiness** [comment]
My python version is 3.12. Actually the newest version of `sphinxemoji` has fixed this issue. So updating `sphinxemoji` to the latest version can fix this problem. However, there is another dependency with this problem: https://github.com/sphinx-contrib/redoc and it has not been updated for 4 years. Therefore `setuptools` still needs to be installed if we want to use that package.

**Comment by peytondmurray** [comment]
Maybe the right way to go then is to drop `redoc` and instead move to https://github.com/sphinx-contrib/openapi ? cc @angelinalg

**Comment by can-anyscale** [comment]
how much work will that be @peytondmurray?

**Comment by peytondmurray** [comment]
Probably not much - I'll build on a separate branch and send a screenshot to you and @angelinalg in a few minutes.

**Review by can-anyscale — CHANGES_REQUESTED** [review]
put back to your queue since the doc team is thinking about solving this in a different way; thanks for bring this up issue

**Comment by peytondmurray** [comment]
Closing this, as it has been resolved by instead updating the doc build requirements in https://github.com/ray-project/ray/pull/46208.

**Pull request closed without merging**
