### PR TITLE
update to slf4j, remove DynamicLog

### PR DESCRIPTION
**Pull request by chuxi**
## What do these changes do?

DynamicLog implementation impact the ray java performance badly. Many string concat in DynamicLog and it is based on log4j 1.2. To decouple from concrete log tool, use slf4j instead. 

Here is the first step to complete the whole work. It removed the DynamicLog and keep its original functions by calling System.setProperty() before Ray core log starts. Because it requires to support multi-workers processes logging. To tell apart each worker's log, it requires to set different names for the worker's log.

And in the future, any logging should use parameter instead of string concat.

```java
// the right way
String name = "tom";
logger.info("hello {}", name); 

// wrong way
logger.info("hello " + name);
```

## Related issue number
N/A

### CODE REVIEW

**Comment by chuxi** [comment]
anybody can help review the pull request?

**Comment by pcmoritz** [comment]
@eric-jj @raulchen Can you help review this or suggest somebody for review?

**Comment by raulchen** [comment]
@pcmoritz we've already reviewed this at https://github.com/ant-tech-alliance/ray/pull/46. 
I think it should be good to merge.
(Actually all PRs from Ant are internally reviewed at ant-tech-alliance/ray repo before pushing to ray-project/ray)

**Comment by robertnishihara** [comment]
@raulchen I see, I would strongly consider doing the reviewing on this repository instead. That way we can see the issues/considerations that were discussed.

If the concern is that it would cause too much clutter, I think it's worth it to provide more visibility.

**Comment by pcmoritz** [comment]
Great, thanks! The changes look good to me too.

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
(I second @robertnishihara's comment, it will be better for us and the other open source developers to have the reviews here. Also you shouldn't worry about posting half-finished PRs that are still being worked on here, that's completely fine.)

**Comment by raulchen** [comment]
@robertnishihara @pcmoritz Thanks for the feedback!

The main purpose of our internal reviews is to ensure a baseline of code quality, and avoid people accidentally violating company's open-source policy.

But I agree that it'd be worth it to share what was discussed before with you. That will help you review faster. I think, in the future, we can also link the original PR. Does this sounds good to you?

**Comment by chuxi** [comment]
Yes. I should also post the pull request in ant-ray. Thanks for reviewing the pr.

**Pull request merged**
