### PR TITLE
Fix metrics exporter exporting metrics in incorrect format

### LINKED ISSUE #23066: [core][Bug] Unexpected error when pushing prometheus metrics
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Monitoring & Debugging

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

When I sent the metric to pushGateway for ray prometheus metric, I encountered the next error message.

```
'text format parsing error in line 122: second HELP line for metric name "ray_operation_active_count"\n'
```

I think the reason is duplicated HELP string in ray prometheus metric.

### Versions / Dependencies

v1.9.0

### Reproduction script

-

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Ray was using prometheus client wrong a few ways:
1. We were registering the Collector to the RegistryCollector multiple times
2. The collector was exporting a new "metric" for each tag combination instead of using a single Metric with multiple samples.
3. We were creating a new RegistryCollector that was unused instead of re-using the "REGISTRY" singleton

Before fix:
```
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="NodeManagerService.grpc_client.GetResourceLoad",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="NodeInfoGcsService.grpc_server.RegisterNode",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="NodeManagerService.grpc_client.RequestResourceReport",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="ResourceUpdate",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="GcsResourceReportPoller.TryPullResourceReport",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="HeartbeatInfoGcsService.grpc_server.ReportHeartbeat",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
# HELP ray_operation_active_count activate operation number
```

After fix:
```
# HELP ray_operation_active_count activate operation number
# TYPE ray_operation_active_count gauge
ray_operation_active_count{Component="gcs_server",JobId="",Method="NodeManagerService.grpc_client.UpdateResourceUsage",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
ray_operation_active_count{Component="gcs_server",JobId="",Method="GcsResourceReportPoller.TryPullResourceReport",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
ray_operation_active_count{Component="gcs_server",JobId="",Method="GcsInMemoryStore.GetAll",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
ray_operation_active_count{Component="gcs_server",JobId="",Method="GcsResourceReportPoller.deadline_timer.pull_resource_report",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 1.0
ray_operation_active_count{Component="gcs_server",JobId="",Method="JobInfoGcsService.grpc_server.GetAllJobInfo",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
ray_operation_active_count{Component="gcs_server",JobId="",Method="NodeResourceInfoGcsService.grpc_server.GetAllResourceUsage",NodeAddress="127.0.0.1",Version="3.0.0.dev0",WorkerId=""} 0.0
```

## Related issue number

fixes #23066

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Great investigation! I wonder if this also explains some of our performance issues with the exporter.

**Comment by rkooo567** [comment]
Yeah I think it will highly likely fix the high CPU usage from the exporter side. The overhead is the glob operation from creating a new Prometheus Metric class. 

I also wonder if we should use the same metrics class instead of generating a new one every time we call `collect`. We can probably do as a follow up..

**Review by rkooo567 — APPROVED** [review]

**Review by rkooo567 — CHANGES_REQUESTED** [review]
Actually can you add a test? I think it could be one of unit tests in `test_metrics_agent_2.py`

**Review by rkooo567 — APPROVED** [review]
will merge once tests pass

**Pull request merged**
