### PR TITLE
[core][test] Deflake test_output by removing unblocking runs. (#43141)

### PR DESCRIPTION
**Pull request by rynewang**
The test_output test reads a Ray driver process's stdout and finds certain strings. However in Autoscaler v2 it's not flushed properly so the reader never gets it. This PR removed the unblocking process runs and reads all.

cherry-picked from #43141

### CODE REVIEW

**Comment by rynewang** [comment]
@zhe-thoughts this is a cherry pick to fix postmerge test failures. Test only, no functional change to prod code. Please reveiw.

**Review by GeneDer — APPROVED** [review]
Cherry pick test fixes. LGTM

**Review by zhe-thoughts — APPROVED** [review]

**Comment by rynewang** [comment]
Looks like this is not the root cause. Will not merge (for now) and Ricky is doing further investigation.

**Comment by aslonnie** [comment]
this PR can be closed now?

**Comment by zhe-thoughts** [comment]
Ping @rynewang , can this be closed?

**Comment by rynewang** [comment]
right, can be closed

**Pull request closed without merging**
