### PR TITLE
[Serve] Fix bug where `create_backend` fails in (base) conda env

### LINKED ISSUE #14631: [Serve] create_backend fails when run from (base) conda env
On master, introduced by https://github.com/ray-project/ray/pull/14430.  Probably a small logic error when dealing with conda paths.  Running from the (base) conda env is not recommended by conda, but we should still support it.

 ```python
(base) ray@ip-172-31-17-144:~/deploy-serve-demo$ ipython
Python 3.7.7 (default, May  7 2020, 21:25:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ray
   ...: from ray import serve
   ...: import requests
   ...: 
   ...: ray.init()
   ...: client = serve.start()
   ...: 
   ...: 
   ...: def say_hello(request):
   ...:     return "hello " + request.query_params["name"] + "!"
   ...: 
   ...: 
   ...: # Form a backend from our function and connect it to an endpoint.
   ...: client.create_backend("my_backend", say_hello)
   ...: client.create_endpoint("my_endpoint", backend="my_backend", route="/hello")
   ...: 
   ...: # Query our endpoint in two different ways: from HTTP and from Python.
   ...: print(requests.get("http://127.0.0.1:8000/hello?name=serve").text)
   ...: # > hello serve!
   ...: print(ray.get(client.get_handle("my_endpoint").remote(name="serve")))
   ...: # > hello serve!
2021-03-11 13:27:06,779 INFO worker.py:664 -- Connecting to existing Ray cluster at address: 172.31.17.144:6379
(pid=2634) 2021-03-11 13:27:07,244      INFO http_state.py:70 -- Starting HTTP proxy with name 'qIrAlt:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:172.31.17.144-0' on node 'node:172.31.17.144-0' listening on '127.0.0.1:8000'
(pid=2661) INFO:     Started server process [2661]
(pid=2634) Task exception was never retrieved
(pid=2634) future: <Task finished coro=<ServeController.run_control_loop() done, defined at /home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/controller.py:110> exception=ValueError('conda env base not found in conda envs directory. Run `conda env list` to verify the name is correct.')>
(pid=2634) Traceback (most recent call last):
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/backend_state.py", line 106, in start
(pid=2634)     self._actor_handle = ray.get_actor(self._actor_name)
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
(pid=2634)     return func(*args, **kwargs)
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1604, in get_actor
(pid=2634)     handle = worker.core_worker.get_named_actor_handle(name)
(pid=2634)   File "python/ray/_raylet.pyx", line 1458, in ray._raylet.CoreWorker.get_named_actor_handle
(pid=2634)   File "python/ray/_raylet.pyx", line 152, in ray._raylet.check_status
(pid=2634) ValueError: Failed to look up actor with name 'qIrAlt:SERVE_CONTROLLER_ACTOR:my_backend#volKMZ'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.
(pid=2634) 
(pid=2634) During handling of the above exception, another exception occurred:
(pid=2634) 
(pid=2634) Traceback (most recent call last):
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/controller.py", line 114, in run_control_loop
(pid=2634)     self.backend_state.update()
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/backend_state.py", line 513, in update
(pid=2634)     replica_state.start(self._backend_metadata[backend_tag])
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/backend_state.py", line 119, in start
(pid=2634)     backend_info.backend_config, self._controller_name)
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 476, in remote
(pid=2634)     override_environment_variables))
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 701, in _remote
(pid=2634)     conda_env_dir = get_conda_env_dir(conda_env)
(pid=2634)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/utils.py", line 872, in get_conda_env_dir
(pid=2634)     "verify the name is correct.")
(pid=2634) ValueError: conda env base not found in conda envs directory. Run `conda env list` to verify the name is correct.
```
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by architkulkarni**
Closes https://github.com/ray-project/ray/issues/14631.

Adds a test for the case where the caller starts in the (base) conda env.  Previously only the case where the caller starts in a non-(base) env was tested.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Comment by edoakes** [comment]
@architkulkarni lint failing
https://travis-ci.com/github/ray-project/ray/jobs/490261271

**Comment by architkulkarni** [comment]
https://buildkite.com/ray-project/ray-builders-pr/builds/2649#6771ca75-ef59-40dd-96c4-f7554689000c/356-3314

`tutorial_pytorch.py` is failing on CI and doesn't seem to have failed before in master.  I can't reproduce the failure locally, and Serve tests don't run with conda enabled, so not sure what the problem is.  I'll continue to investigate

**Comment by architkulkarni** [comment]
Maybe this is crazy, but Github was hanging when I was reviewing a PR around the time when this test ran, and the test pulls an image from Github, so maybe an outage caused the test to fail.  Merging master to re-trigger the tests

**Comment by edoakes** [comment]
@architkulkarni there was indeed an outage earlier today. LMK when tests pass.

**Pull request merged**
