### PR TITLE
[rllib] Use SGD optimizer for ARS

### PR DESCRIPTION
**Pull request by eugenevinitsky**
## What do these changes do?

Replaces the ARS ADAM optimizer with an SGD optimizer to put it in accord with the base code used in the ARS paper

## Related issue number

#2909 should be fixed by this

### CODE REVIEW

**Comment by ericl** [comment]
Looks good. Did you check if it affects the performance of any tuned examples?

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
I ran the swimmer example and got 

ars

Does that look ok?

**Comment by eugenevinitsky** [comment]
I'll run a few and get back to you. I'm not sure what expected performance is but we can benchmark against the curves in the ARS paper

**Comment by eugenevinitsky** [comment]
Expected behavior is blue line here: 
image

**Comment by eugenevinitsky** [comment]
yeah, I'm going to add smoothing but either way they don't seem to have any negative values?

**Comment by eugenevinitsky** [comment]
Fixed by smoothing: 
image

**Pull request merged**
