### PR TITLE
Revert "[ray_client]: Fix mutual recursion"

### PR DESCRIPTION
**Pull request by architkulkarni**
Reverts ray-project/ray#14122

`test_actor_client_mode` and `test_client_terminate` are very flaky on Windows starting from this PR: 
Screen Shot 2021-02-16 at 3 06 02 PM
Screen Shot 2021-02-16 at 3 06 12 PM

See:
https://github.com/ray-project/ray/runs/1913015469#step:7:3074
"::test_actor_deletion Windows fatal exception: access violation"

`test_client_terminate::test_cancel_chain[True]` appears to time out: https://github.com/ray-project/ray/runs/1913015469#step:7:3375

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @ericl @barakmich

**Comment by ericl** [comment]
Can we instead disable these on windows only?

**Comment by ericl** [comment]
Any idea why these are failing on Windows only? If not, maybe we should disable it on windows build.

**Comment by rkooo567** [comment]
@architkulkarni Can we just skip windows. client tests? @ericl client mode is not working with Windows now right?

**Comment by architkulkarni** [comment]
Oh yeah, if that's the case skipping Windows client tests makes sense.  Some client tests have already been skipped on Windows, but many others have not been skipped and seem to be passing consistently.  @barakmich @ericl should we go ahead and skip all the client tests on Windows, or just the ones that seem to be flaky?

**Comment by ericl** [comment]
How about we disable just the flaky ones for now? We can debug them later,
though I haven't any idea what would be causing the issue from a cursory
look.

**Comment by architkulkarni** [comment]
Sounds great, here's the PR to skip the flaky test `test_client_terminate::test_cancel_chain`: https://github.com/ray-project/ray/pull/14167

After seeing some more CI runs from recent commits, the second test mentioned in this PR (`test_actor_client_mode`) appears to not actually be that flaky, so I've left it in.

**Pull request closed without merging**
