### PR TITLE
[autoscaler] Move command runners into separate file and clean up interface.

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Move the command runners into their own file, and define an interface class. Mark methods as private as needed.

cc @AmeerHajAli

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
LGTM. We might consider making a base class with the public methods for documentation purposes.

**Comment by edoakes** [comment]
Oh, I just saw that you already did that, even better :)

**Review by ijrsvt — CHANGES_REQUESTED** [review]
i think [`commands.py`](https://github.com/ray-project/ray/blob/8f19f1eafbbaa46c5260da8b63093fcac5f41ae0/python/ray/autoscaler/commands.py#L28) and [`node_provider.py`](https://github.com/ray-project/ray/blob/8f19f1eafbbaa46c5260da8b63093fcac5f41ae0/python/ray/autoscaler/node_provider.py#L6) reference the different command_runners from `updater.py`. Otherwise it looks good! I appreciate the base class :)

**Comment by AmeerHajAli** [comment]
This is great!

**Comment by ericl** [comment]
Oops, fixed.

**Review by ijrsvt — APPROVED** [review]
LGTM

**Pull request merged**
