### PR TITLE
[Stats] add nodeaddress tag for stats test

### PR DESCRIPTION
**Pull request by ashione**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by ashione** [comment]
I found the stats test assert checker is invalid since current worker has no tag like NodeAddress. @edoakes please help me to review this PR.

**Comment by edoakes** [comment]
@ashione the PR seems ok, but why wasn't this failing in CI? Are we not running this test? If not, can you make sure to add it as part of this PR.

**Comment by ashione** [comment]
> @ashione the PR seems ok, but why wasn't this failing in CI? Are we not running this test? If not, can you make sure to add it as part of this PR.

I run basic unit tests befere pullrequest. Actually failed cases are related to rllib, but I will check it again.

**Comment by edoakes** [comment]
@ashione the tests running on this PR look fine. What I'm asking is: this PR seems to be fixing a unit test failure but I haven't seen this failing in CI - does this mean the test hasn't been running? If so, can we make sure it runs in CI?

**Comment by ashione** [comment]
> @ashione the tests running on this PR look fine. What I'm asking is: this PR seems to be fixing a unit test failure but I haven't seen this failing in CI - does this mean the test hasn't been running? If so, can we make sure it runs in CI?

Current work has no tag named NodeAddressKey, then this stats test will always pass because of the line 47 ```if (descriptor.columns()[i].name() == "NodeAddress") {`` has been never checked and its test is meaningless. So this PR is going to add this tag.

**Comment by ashione** [comment]
> > @ashione the tests running on this PR look fine. What I'm asking is: this PR seems to be fixing a unit test failure but I haven't seen this failing in CI - does this mean the test hasn't been running? If so, can we make sure it runs in CI?
> 
> Current work has no tag named NodeAddressKey, then this stats test will always pass because of the line 47 ```if (descriptor.columns()[i].name() == "NodeAddress") {`` has been never checked and its test is meaningless. So this PR is going to add this tag.

**Comment by edoakes** [comment]
@ashione looks like lint is failing in some of the github actions builds although it passed in travis.

@mehrdadn any idea what's happening here?

**Comment by mehrdadn** [comment]
@edoakes The GHA lint failure happens when master moves forward. It causes both master's changes _and_ the current branch's changes to be linted (due to the `...` symmetric difference syntax). I'm not entirely sure why this doesn't come up on Travis, but it should be possible to merge in master to work around it. Alternatively you can just ignore it and merge it, since it doesn't seem like it should affect the Windows GHA.

(The Mac error about not finding clang-format is something I have a patch for locally; you can also ignore that and just merge in regardless.)

**Comment by ashione** [comment]
> @edoakes The GHA lint failure happens when master moves forward. It causes both master's changes _and_ the current branch's changes to be linted (due to the `...` symmetric difference syntax). I'm not entirely sure why this doesn't come up on Travis, but it should be possible to merge in master to work around it. Alternatively you can just ignore it and merge it, since it doesn't seem like it should affect the Windows GHA.
> 
> (The Mac error about not finding clang-format is something I have a patch for locally; you can also ignore that and just merge in regardless. I plan to merge the fix in soon.)

Thx, I'll try to merge master first.

**Comment by ashione** [comment]
@edoakes @mehrdadn Could you check it again? I notice all failures are unrelated.

**Review by edoakes — APPROVED** [review]

**Pull request merged**
