### PR TITLE
Fix potential github action smells

### PR DESCRIPTION
**Pull request by ceddy4395**
Hey! 🙂
I want to contribute the following changes to your workflow:

- Use fixed version for runs-on argument
- Avoid jobs without timeouts

(These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by anyscalesam** [comment]
why does keeping to latest not work? same q - why add the TO as well?

**Comment by ceddy4395** [comment]
Keeping latest does in theory work, however you will not have any control on the OS the CI is being run on. Therefore, if Github at any point in time moves to the next version of Ubuntu you will automatically also be moved over on your CI. If, in the unlikely case that there is a (security?) bug in this version of ubuntu you could experience negative side effects because of this. 

Regarding the timeouts. It has been researched that ideally builds are kept 'short' therefore it could/should also be useful to know when builds start taking significantly longer (because of badly written tests, dependencies, etc.). Having a timeout will allow for this to be more quickly and easily noticed. 

I'm very interested to hear your opinion on these matters!

**Comment by anyscalesam** [comment]
@aslonnie thoughts?

**Comment by aslonnie** [comment]
- we do not really use github actions for anything important. 
- 22.04 is also a channel rather than a fixed version. I do not think it is better than latest for our use case. if you actually look at what we are using, we do not use anything really depends on ubuntu. for this case, using latest is probably slightly better.
- the timeout is fine, but it should be longer to cover the long tail. maybe 3 min or 5 min.

so here is the suggestion, fwiw:

- keep using the "latest" for the ubuntu tag.
- change timeout to 5min

and I will accept it.

**Review by aslonnie — COMMENTED** [review]
suggestion:

- keep using the "latest" for the ubuntu tag.
- change timeout to 5min

and I will accept it.

**Comment by ceddy4395** [comment]
@anyscalesam, @aslonnie Thank you very much for the suggestions, I've made the changes and rebased.

**Review by aslonnie — APPROVED** [review]

**Pull request merged**
