### PR TITLE
[CI][Ref-counting] deflake nested-id windows test failures

### PR DESCRIPTION
**Pull request by scv119**
Looks at the failures seems that the test failed to init ray, possibly due to plasma store size is too large. Fix it by setting plasma store size to 100MB.

```
>       raise TimeoutError("Timed out while waiting for node to startup.")
E       TimeoutError: Timed out while waiting for node to startup.

d:\a\ray\ray\python\ray\_private\services.py:288: TimeoutError

During handling of the above exception, another exception occurred:

shutdown_only = None

    def test_return_nested_ids(shutdown_only):
>       ray.init()

```

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
Let's see if this resolves the issue!

**Comment by scv119** [comment]
No it doesn't work... still looking.

**Comment by stephanie-wang** [comment]
Hmm I thought the error might be memory corruption? I'm not sure, though, I don't really know how to read Windows stacktraces.

```
2021-08-20T18:15:18.8353995Z ::test_return_nested_ids 
2021-08-20T18:15:18.8354671Z INTERNALERROR> Traceback (most recent call last):
2021-08-20T18:15:18.8355708Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\main.py", line 191, in wrap_session
2021-08-20T18:15:18.8356819Z INTERNALERROR>     session.exitstatus = doit(config, session) or 0
2021-08-20T18:15:18.8357894Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\main.py", line 247, in _main
2021-08-20T18:15:18.8359026Z INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
2021-08-20T18:15:18.8360132Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\hooks.py", line 286, in __call__
2021-08-20T18:15:18.8361212Z INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
2021-08-20T18:15:18.8362296Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
2021-08-20T18:15:18.8363570Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2021-08-20T18:15:18.8364689Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
2021-08-20T18:15:18.8365898Z INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2021-08-20T18:15:18.8367121Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 208, in _multicall
2021-08-20T18:15:18.8368136Z INTERNALERROR>     return outcome.get_result()
2021-08-20T18:15:18.8370510Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 80, in get_result
2021-08-20T18:15:18.8371552Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2021-08-20T18:15:18.8372594Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 187, in _multicall
2021-08-20T18:15:18.8373621Z INTERNALERROR>     res = hook_impl.function(*args)
2021-08-20T18:15:18.8374687Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
2021-08-20T18:15:18.8375934Z INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
2021-08-20T18:15:18.8377318Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\hooks.py", line 286, in __call__
2021-08-20T18:15:18.8378442Z INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
2021-08-20T18:15:18.8379602Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
2021-08-20T18:15:18.8380686Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2021-08-20T18:15:18.8381777Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
2021-08-20T18:15:18.8383050Z INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2021-08-20T18:15:18.8384270Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 208, in _multicall
2021-08-20T18:15:18.8385290Z INTERNALERROR>     return outcome.get_result()
2021-08-20T18:15:18.8386323Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 80, in get_result
2021-08-20T18:15:18.8387338Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2021-08-20T18:15:18.8388400Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 187, in _multicall
2021-08-20T18:15:18.8389425Z INTERNALERROR>     res = hook_impl.function(*args)
2021-08-20T18:15:18.8390502Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
2021-08-20T18:15:18.8391633Z INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
2021-08-20T18:15:18.8392780Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\runner.py", line 100, in runtestprotocol
2021-08-20T18:15:18.8393901Z INTERNALERROR>     reports.append(call_and_report(item, "call", log))
2021-08-20T18:15:18.8395000Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\runner.py", line 188, in call_and_report
2021-08-20T18:15:18.8396159Z INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
2021-08-20T18:15:18.8397302Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\hooks.py", line 286, in __call__
2021-08-20T18:15:18.8398416Z INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
2021-08-20T18:15:18.8399536Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
2021-08-20T18:15:18.8400630Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2021-08-20T18:15:18.8401755Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
2021-08-20T18:15:18.8402942Z INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2021-08-20T18:15:18.8404186Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 203, in _multicall
2021-08-20T18:15:18.8405182Z INTERNALERROR>     gen.send(outcome)
2021-08-20T18:15:18.8406264Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\skipping.py", line 129, in pytest_runtest_makereport
2021-08-20T18:15:18.8407362Z INTERNALERROR>     rep = outcome.get_result()
2021-08-20T18:15:18.8408626Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 80, in get_result
2021-08-20T18:15:18.8409695Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2021-08-20T18:15:18.8410724Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pluggy\callers.py", line 187, in _multicall
2021-08-20T18:15:18.8411747Z INTERNALERROR>     res = hook_impl.function(*args)
2021-08-20T18:15:18.8412991Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\runner.py", line 260, in pytest_runtest_makereport
2021-08-20T18:15:18.8414139Z INTERNALERROR>     return TestReport.from_item_and_call(item, call)
2021-08-20T18:15:18.8415263Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\reports.py", line 294, in from_item_and_call
2021-08-20T18:15:18.8416751Z INTERNALERROR>     longrepr = item.repr_failure(excinfo)
2021-08-20T18:15:18.8417891Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\python.py", line 1511, in repr_failure
2021-08-20T18:15:18.8419134Z INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
2021-08-20T18:15:18.8420247Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\nodes.py", line 369, in _repr_failure_py
2021-08-20T18:15:18.8421294Z INTERNALERROR>     truncate_locals=truncate_locals,
2021-08-20T18:15:18.8422331Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\code.py", line 635, in getrepr
2021-08-20T18:15:18.8423342Z INTERNALERROR>     return fmt.repr_excinfo(self)
2021-08-20T18:15:18.8424383Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\code.py", line 880, in repr_excinfo
2021-08-20T18:15:18.8425483Z INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
2021-08-20T18:15:18.8426614Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\code.py", line 824, in repr_traceback
2021-08-20T18:15:18.8427736Z INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
2021-08-20T18:15:18.8428923Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\code.py", line 774, in repr_traceback_entry
2021-08-20T18:15:18.8430021Z INTERNALERROR>     source = self._getentrysource(entry)
2021-08-20T18:15:18.8431136Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\code.py", line 685, in _getentrysource
2021-08-20T18:15:18.8432285Z INTERNALERROR>     source = entry.getsource(self.astcache)
2021-08-20T18:15:18.8433414Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\code.py", line 247, in getsource
2021-08-20T18:15:18.8434463Z INTERNALERROR>     self.lineno, source, astnode=astnode
2021-08-20T18:15:18.8435612Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\_pytest\_code\source.py", line 384, in getstatementrange_ast
2021-08-20T18:15:18.8436768Z INTERNALERROR>     astnode = ast.parse(content, "source", "exec")
2021-08-20T18:15:18.8437705Z INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\ast.py", line 35, in parse
2021-08-20T18:15:18.8438650Z INTERNALERROR> MemoryError
```

**Comment by stephanie-wang** [comment]
Oh never mind, I see the timeout error too. I'm not sure what the MemoryError is then.

**Comment by scv119** [comment]
running those test locally on my PC and it's passing. It probably just takes too long to finish in time. I'm going to split the test into its own file.

**Comment by scv119** [comment]
Looks this addressed the window ref counting issue but there are other windows failures, which looks unrelated to ref counting. so we should merge this PR?

**Pull request merged**
