### PR TITLE
[Core]Limit job error message size

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
Now we publish job error via Redis. In some cases the error message is too large(more than 10MiB) to publish, we need to limit it.

P.S. We encountered in our production environment but lost the logs in client side so couldn't find which error is the root cause. Cutting off all message that is too long is an acceptable solution, I think.
In addition I added some logs before reporting so we can find the murder when next time it kills.
image

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

**Comment by rkooo567** [comment]
Hey can you include in the error message that the message is cut, and give some guidance how to find it?

**Comment by rkooo567** [comment]
Maybe just one line is fine in the beginning of the error message (The message size exceeds, X bytes. Find the full log from the log files.) Or something like that

**Review by rkooo567 — CHANGES_REQUESTED** [review]
Maybe just one line is fine in the beginning of the error message (The message size exceeds, X bytes. Find the full log from the log files.) Or something like that

**Comment by WangTaoTheTonic** [comment]
> Maybe just one line is fine in the beginning of the error message (The message size exceeds, X bytes. Find the full log from the log files.) Or something like that

sure~

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
