### PR TITLE
[RLlib] Dreamerv3 fix forward inference bug

### PR DESCRIPTION
**Pull request by sven1977**
Dreamerv3
* fix forward inference bug
* fix DreamerV3 restore from checkpoint bug

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
Let's merge the master PR first. Thanks

**Comment by sven1977** [comment]
Of course! No worries, waiting for Artur's review ...

**Review by zhe-thoughts — APPROVED** [review]
This is a release blocking bug. OK to pick

**Comment by sven1977** [comment]
Please wait with picking this. Tests seem to break. I need to take another look. Thanks!

**Review by zhe-thoughts — APPROVED** [review]
OK to pick

**Comment by sven1977** [comment]
Ok, confirmed that this is good to pick now!
Thanks everyone!
cc: @zhe-thoughts

**Review by zhe-thoughts — APPROVED** [review]
Yes qualifies for picking

**Pull request merged**
