### PR TITLE
[serve] Gradio docs fixes

### LINKED ISSUE #32752: [Ray : Serve] The Gradio Ray Serve tutorial does not work in Ray 2.2 and the master
### What happened + What you expected to happen

The Ray Serve quickstart tutorial on scaling Gradio app fails both on the Ray 2.2 and the master branch too.

Following the instructions and running the command:
$ `serve run gradio_demo:app` results into stack trace. 

See the attacheh stack trace.

 
```
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/bin/serve:8 in <module>             │
│                                                                                                  │
│   5 from ray.serve.scripts import cli                                                            │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/click/c │
│ ore.py:1128 in __call__                                                                          │
│                                                                                                  │
│   1125 │                                                                                         │
│   1126 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1127 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1128 │   │   return self.main(*args, **kwargs)                                                 │
│   1129                                                                                           │
│   1130                                                                                           │
│   1131 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/click/c │
│ ore.py:1053 in main                                                                              │
│                                                                                                  │
│   1050 │   │   try:                                                                              │
│   1051 │   │   │   try:                                                                          │
│   1052 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1053 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1054 │   │   │   │   │   if not standalone_mode:                                               │
│   1055 │   │   │   │   │   │   return rv                                                         │
│   1056 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/click/c │
│ ore.py:1659 in invoke                                                                            │
│                                                                                                  │
│   1656 │   │   │   │   super().invoke(ctx)                                                       │
│   1657 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1658 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1659 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1660 │   │                                                                                     │
│   1661 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1662 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/click/c │
│ ore.py:1395 in invoke                                                                            │
│                                                                                                  │
│   1392 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1393 │   │                                                                                     │
│   1394 │   │   if self.callback is not None:                                                     │
│ ❱ 1395 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1396 │                                                                                         │
│   1397 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1398 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/click/c │
│ ore.py:754 in invoke                                                                             │
│                                                                                                  │
│    751 │   │                                                                                     │
│    752 │   │   with augment_usage_errors(__self):                                                │
│    753 │   │   │   with ctx:                                                                     │
│ ❱  754 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    755 │                                                                                         │
│    756 │   def forward(                                                                          │
│    757 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/scripts.py:333 in run                                                                         │
│                                                                                                  │
│   330 │   │   │   if gradio:                                                                     │
│   331 │   │   │   │   handle = serve.get_deployment("DAGDriver").get_handle()                    │
│   332 │   │   else:                                                                              │
│ ❱ 333 │   │   │   handle = serve.run(node, host=host, port=port)                                 │
│   334 │   │   │   cli_logger.success("Deployed Serve app successfully.")                         │
│   335 │   │                                                                                      │
│   336 │   │   if gradio:                                                                         │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/api.py:536 in run                                                                             │
│                                                                                                  │
│   533 │   │   │   "is_driver_deployment": deployment._is_driver_deployment,                      │
│   534 │   │   }                                                                                  │
│   535 │   │   parameter_group.append(deployment_parameters)                                      │
│ ❱ 536 │   client.deploy_group(                                                                   │
│   537 │   │   parameter_group, _blocking=_blocking, remove_past_deployments=True                 │
│   538 │   )                                                                                      │
│   539                                                                                            │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/_private/client.py:37 in check                                                                │
│                                                                                                  │
│    34 │   def check(self, *args, **kwargs):                                                      │
│    35 │   │   if self._shutdown:                                                                 │
│    36 │   │   │   raise RayServeException("Client has already been shut down.")                  │
│ ❱  37 │   │   return f(self, *args, **kwargs)                                                    │
│    38 │                                                                                          │
│    39 │   return check                                                                           │
│    40                                                                                            │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/_private/client.py:251 in deploy_group                                                        │
│                                                                                                  │
│   248 │   │   deployment_args_list = []                                                          │
│   249 │   │   for deployment in deployments:                                                     │
│   250 │   │   │   deployment_args_list.append(                                                   │
│ ❱ 251 │   │   │   │   self.get_deploy_args(                                                      │
│   252 │   │   │   │   │   deployment["name"],                                                    │
│   253 │   │   │   │   │   deployment["func_or_class"],                                           │
│   254 │   │   │   │   │   deployment["init_args"],                                               │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/_private/client.py:37 in check                                                                │
│                                                                                                  │
│    34 │   def check(self, *args, **kwargs):                                                      │
│    35 │   │   if self._shutdown:                                                                 │
│    36 │   │   │   raise RayServeException("Client has already been shut down.")                  │
│ ❱  37 │   │   return f(self, *args, **kwargs)                                                    │
│    38 │                                                                                          │
│    39 │   return check                                                                           │
│    40                                                                                            │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/_private/client.py:455 in get_deploy_args                                                     │
│                                                                                                  │
│   452 │   │   else:                                                                              │
│   453 │   │   │   ray_actor_options["runtime_env"] = curr_job_env                                │
│   454 │   │                                                                                      │
│ ❱ 455 │   │   replica_config = ReplicaConfig.create(                                             │
│   456 │   │   │   deployment_def,                                                                │
│   457 │   │   │   init_args=init_args,                                                           │
│   458 │   │   │   init_kwargs=init_kwargs,                                                       │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/ser │
│ ve/config.py:381 in create                                                                       │
│                                                                                                  │
│   378 │   │   config = cls(                                                                      │
│   379 │   │   │   deployment_def_name,                                                           │
│   380 │   │   │   cloudpickle.dumps(deployment_def),                                             │
│ ❱ 381 │   │   │   cloudpickle.dumps(init_args),                                                  │
│   382 │   │   │   cloudpickle.dumps(init_kwargs),                                                │
│   383 │   │   │   ray_actor_options,                                                             │
│   384 │   │   )                                                                                  │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/clo │
│ udpickle/cloudpickle_fast.py:73 in dumps                                                         │
│                                                                                                  │
│    70 │   │   │   cp = CloudPickler(                                                             │
│    71 │   │   │   │   file, protocol=protocol, buffer_callback=buffer_callback                   │
│    72 │   │   │   )                                                                              │
│ ❱  73 │   │   │   cp.dump(obj)                                                                   │
│    74 │   │   │   return file.getvalue()                                                         │
│    75                                                                                            │
│    76 else:                                                                                      │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ray/clo │
│ udpickle/cloudpickle_fast.py:627 in dump                                                         │
│                                                                                                  │
│   624 │                                                                                          │
│   625 │   def dump(self, obj):                                                                   │
│   626 │   │   try:                                                                               │
│ ❱ 627 │   │   │   return Pickler.dump(self, obj)                                                 │
│   628 │   │   except RuntimeError as e:                                                          │
│   629 │   │   │   if "recursion" in e.args[0]:                                                   │
│   630 │   │   │   │   msg = (                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot pickle 'Context' object
```

### Versions / Dependencies

same dependencies as needed in the tutorial
```
pip install "ray[serve]"
pip install gradio
pip install transformers
```

### Reproduction script

Just follow the script on the docs page: [Scaling your Gradio app with Ray Serve](https://docs.ray.io/en/latest/serve/tutorials/gradio-integration.html#scaling-your-gradio-app-with-ray-serve). 

Or use this [script.](https://github.com/dmatrix/misc-code/blob/master/py/ray/rayserve/gradio_demo.py)

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

* The gradio example in the docs uses deprecated API, which spews deprecated warnings if a user runs it.
* I updated the gradio version in the docs from 3.11 to 3.19, as I've verified the example runs fine with the most recent gradio version.
* I switched out EleutherAI/gpt-neo-125M for distilgpt2 in the docs example because of weird errors that occur when pulling it from hugging face. (not sure why the errors are happening, it's not related to gradio or serve)

## Related issue number

Closes #32752 
Closes #34052

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zcin** [comment]
> Just to make sure, can the model be pulled from ray serve without CI env?

Which model are you referring to? Also, the model should be pulled from Hugging Face.

**Review by krfricke — APPROVED** [review]
Thanks!

**Review by maxpumperla — APPROVED** [review]

**Comment by edoakes** [comment]
Docs build failed. Related?

**Comment by zcin** [comment]
> Docs build failed. Related?

Should be unrelated! Errors point to some walkthrough pages in the docs.

**Comment by maxpumperla** [comment]
@zcin doc failures in this build are from #34069 which got reverted

**Pull request merged**
