### PR TITLE
[core][wip] surface OOM error when actor is killed due to OOM 

### PR DESCRIPTION
**Pull request by clarng**
## Why are these changes needed?

Right now we show Actor error if the actor is killed due to OOM. This PR changes it so it surfaces a OOM error.

It does not implement actor oom retry, as the goal of this PR is to improve observability, given the size of this PR it is probably best to address actor oom retry in a follow up PR

The protocol for task oom retry and actor task oom retry is, per plan, made consistent in this PR, where the caller fetches the failure cause from raylet and uses that to determine whether it should use oom retry and whether to fail immediately.

For practical purposes, the caller receives actor death notification and then fetches the failure cause from raylet. This in turn sets the proper state that is used to propagate actor task failure, regardless of the state the actor task is in (inflight, pending, waiting for death cause, etc)

Summary of changes
- change 'get task failure' to 'get worker failure' so it works for both actor and task
- add client factory to actor task submitter so it can contact the raylet for the worker failure
- refactor the code that translates the worker failure into error info so it can be shared between task and actor task submitter
- add the error info to the request queue for the actor task submitter so it can be used in different parts of the code, particularly on request timeout
- some clean up to GetWorkerClient logic

[wip] since still need to fix mocks / unit test

## Related issue number

https://github.com/ray-project/ray/issues/29736

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
When we have an actor

```python3
```

**Comment by rkooo567** [comment]
Have one question;

If the actor fails without an in-flight tasks, would ray list actors have the correct death cause? E.g.,

```
import ray

@ray.remote
class A:
    pass

a = A.remote()
# sleep long and OOM a
```

After this, the OOM is correctly reported already. And this PR handles the case when the actor task to the actor is failed. Is this correct?

**Comment by rkooo567** [comment]
Given ^ is correct, I feel like this can produce inconsistent exception depending on when the actor failure is published from GCS? E.g., 

1. If GCS publishes the actor failure earlier than the actor task RPC reply, it will be RayActorError
2. If RPC replies first, it will be OOM error.

Given this, wouldn't it be cleaner to just read RayActorError, figure out the root cause, and raise OOM error if the worker fails due to OOM? Wdyt?

**Comment by clarng** [comment]
> Have one question;
> 
> If the actor fails without an in-flight tasks, would ray list actors have the correct death cause? E.g.,
> 
> ```
> import ray
> 
> @ray.remote
> class A:
>     pass
> 
> a = A.remote()
> # sleep long and OOM a
> ```
> 
> After this, the OOM is correctly reported already. And this PR handles the case when the actor task to the actor is failed. Is this correct?

This only affects the actor task error afaik

The actors are still retrying with actor error (it does not do OOM retry)

This PR seems pretty big already and hence it is best to implement actor oom retry in a separate PR. At that point, GCS and state table would have OOM record. And if state api is relying on GCS table then it would then be able to see the OOM error. In this PR Actor is still retrying on ActorError. 

There are more refactoring to be done to make actor oom retry (and pushing to state table) work

**Comment by clarng** [comment]
> Given ^ is correct, I feel like this can produce inconsistent exception depending on when the actor failure is published from GCS? E.g.,
> 
> 1. If GCS publishes the actor failure earlier than the actor task RPC reply, it will be RayActorError
> 2. If RPC replies first, it will be OOM error.
> 
> Given this, wouldn't it be cleaner to just read RayActorError, figure out the root cause, and raise OOM error if the worker fails due to OOM? Wdyt?

The current client logic waits for death cause if push task wins (which is not the default case)

when death cause arrive we fetch the oom error from raylet, before updating the push task failure.

so it is consistent for actor task

**Comment by clarng** [comment]
Favoring https://github.com/ray-project/ray/pull/32107 over this PR

**Pull request closed without merging**
