### PR TITLE
[air] Move python/ray/ml to python/ray/air

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

The package "ml" should be renamed to "air".

Main question: Keep a `ml.py` with `from ray.air import *` for some level of backwards compatibility?
I'd go for no to force people to use the new structure.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
> Main question: Keep a ml.py with from ray.air import * for some level of backwards compatibility?

Nope!

**Comment by amogkam** [comment]
I'd agree on no for ml backwards compatibility. We're only in alpha still and it just adds complication.

**Comment by clarkzinzow** [comment]
Missed this one in Datasets: https://github.com/ray-project/ray/blob/077f8c36adc4800815d62fc4fb0b9dc9b4f14048/python/ray/data/dataset.py#L2372

**Comment by clarkzinzow** [comment]
Also cc @bveeramani who is adding a similar import in his in-flight PR: https://github.com/ray-project/ray/pull/25133/files#diff-5a812d24fc3efd599284bb40dcbd2c6627bbe324e1c89a6e623b4dccf8e5de44R2532

**Comment by simon-mo** [comment]
Here as well: https://github.com/ray-project/ray/blob/master/python/ray/serve/tests/test_model_wrappers.py

**Comment by krfricke** [comment]
Weird my global search didn't catch those, but taking a stab right now...

**Comment by krfricke** [comment]
Let's see if this worked

**Review by ericl — APPROVED** [review]

**Comment by krfricke** [comment]
Linkcheck won't fail once merged into master (this is a link to master docs)

**Pull request merged**
