### PR TITLE
Add feedback button to dashboard

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Screen Shot 2022-11-17 at 6 48 03 PM
Screen Shot 2022-11-17 at 6 50 01 PM
Screen Shot 2022-11-17 at 6 48 07 PM

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Screen Shot 2022-11-17 at 6 57 55 PM

It should be the [dashboard]?

**Comment by rkooo567** [comment]
Also are we going to use the issue directly instead of having airtable survey?

**Comment by scottsun94** [comment]
Using either gh link or this [airtable form](https://airtable.com/shr7xNs4pXQrIy2Cg) is fine for me.

**Comment by alanwguo** [comment]
> Screen Shot 2022-11-17 at 6 57 55 PM
> 
> It should be the [dashboard]?

I'll update this to `[dashboard]` otherwise, I think we should stay with GH issues

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
