### PR TITLE
Update id_specification.md

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
According to here: https://github.com/ray-project/ray/blob/880797d5c2ae93c68e9d0267c86cd15969d67d2d/src/ray/common/id.cc#L239-L246

Index is added after task id

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jovany-wang** [comment]
Why not change the implementation to match the specification. It will help us to debug to if we make index as the prefix of object id.

According to the hex string of object id, the last 16B is the actor id. After this PR, we hard to read the actor id from it.

**Comment by iycheng** [comment]
> Why not change the implementation to match the specification. It will help us to debug if we make index as the prefix of object id.
> 
> According to the hex string of object id, the last 16B is the actor id. After this PR, we hard to read the actor id from it.

I have no preference for this. @ericl  @rkooo567  what do you think about this?

**Comment by ericl** [comment]
This PR isn't changing anything--- I'd prefer to preserve the status quo. It makes sense that two object IDs of the same return task have very similar ids, differing only in the low bits.

**Review by ericl — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
I also prefer to keep the status quo (since most of users won't know how to get actor id from the object id). This is more intuitive specification for non-expert users.

Imo, we should rather improve the implementation of `ID_OSTREAM_OPERATOR` if we'd like to expose other ids from object ids (for example, always print actor id when object id is printed).

**Pull request merged**
