### PR TITLE
[misc] Reformat Core BUILD files

### PR DESCRIPTION
**Pull request by khluu**
Ran `buildifier` to reformat all BUILD files related to Core team.

### CODE REVIEW

**Comment by rynewang** [comment]
@aslonnie do we also want CI/presubmit linters for BUILD files?

**Comment by aslonnie** [comment]
> @aslonnie do we also want CI/presubmit linters for BUILD files?

yes.. though we need to fix all the formats first..

**Comment by aslonnie** [comment]
ping?

**Review by jjyao — APPROVED** [review]

**Comment by khluu** [comment]
@aslonnie  I just merged with master again and assigned to you. Can you merge this PR once the checks pass?

**Pull request merged**
