### PR TITLE
[release tests] Move aws cluster launcher tests to v2 cloud

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Moves the AWS cluster launcher tests from the V1 cloud to the V2 cloud and the Anyscale job runner (in other words, using the defaults used for all release tests).  To do this, we move the ssh key to a bucket accessible from the V2 cloud.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Tests running here https://buildkite.com/ray-project/release-tests-pr/builds/33951

**Comment by wuisawesome** [comment]
Do you mind adding an example link of a successful run here?

**Comment by architkulkarni** [comment]
Tests rinning here https://buildkite.com/ray-project/release-tests-pr/builds/33962

**Comment by architkulkarni** [comment]
Hmm, failing with
```
2023-04-05 16:22:53,464	VINFO utils.py:150 -- Creating AWS resource `iam` in `us-west-2`
--
  | 2023-04-05 16:22:53,774	PANIC utils.py:122 -- Failed to fetch IAM instance profile data for ray-autoscaler-v1 from AWS.
  | Error code: AccessDenied
  | 2023-04-05 16:22:53,774	ERR utils.py:124 -- !!! Boto3 error:
  | 2023-04-05 16:22:53,774	VINFO utils.py:125 -- {'response': {'Error': {'Type': 'Sender', 'Code': 'AccessDenied', 'Message': 'User: arn:aws:sts::188439194153:assumed-role/cld_i2w99rzq8b6lbjkke9y94vi5-cluster_node_role/i-0c4e3939270f7e1ed is not authorized to perform: iam:GetInstanceProfile on resource: instance profile ray-autoscaler-v1 because no identity-based policy allows the iam:GetInstanceProfile action'}, 'ResponseMetadata': {'RequestId': '08b549c9-8281-4076-98d0-c6e13a3f267a', 'HTTPStatusCode': 403, 'HTTPHeaders': {'x-amzn-requestid': '08b549c9-8281-4076-98d0-c6e13a3f267a', 'content-type': 'text/xml', 'content-length': '530', 'date': 'Wed, 05 Apr 2023 23:22:53 GMT'}, 'RetryAttempts': 0}}, 'operation_name': 'GetInstanceProfile'}
  | 2023-04-05 16:22:53,774	PANIC utils.py:126 -- An error occurred (AccessDenied) when calling the GetInstanceProfile operation: User: arn:aws:sts::188439194153:assumed-role/cld_i2w99rzq8b6lbjkke9y94vi5-cluster_node_role/i-0c4e3939270f7e1ed is not authorized to perform: iam:GetInstanceProfile on resource: instance profile ray-autoscaler-v1 because no identity-based policy allows the iam:GetInstanceProfile action
  | 2023-04-05 16:22:53,774	ERR utils.py:126 -- !!!
```

**Comment by architkulkarni** [comment]
Trying again https://buildkite.com/ray-project/release-tests-pr/builds/33981

**Comment by architkulkarni** [comment]
New error after adding the `ray-autoscaler-v1` IAM to the YAML:


```
2023-04-05 17:03:21,176	PANIC utils.py:122 -- Failed to fetch EC2 key pair ray-autoscaler_us-west-2 from AWS.
--
  | Error code: UnauthorizedOperation
  | 2023-04-05 17:03:21,176	ERR utils.py:124 -- !!! Boto3 error:
  | 2023-04-05 17:03:21,176	VINFO utils.py:125 -- {'response': {'Error': {'Code': 'UnauthorizedOperation', 'Message': 'You are not authorized to perform this operation.'}, 'ResponseMetadata': {'RequestId': '3c78e9d2-aaab-489d-8fa0-50a2ebfd8385', 'HTTPStatusCode': 403, 'HTTPHeaders': {'x-amzn-requestid': '3c78e9d2-aaab-489d-8fa0-50a2ebfd8385', 'cache-control': 'no-cache, no-store', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'vary': 'accept-encoding', 'content-type': 'text/xml;charset=UTF-8', 'transfer-encoding': 'chunked', 'date': 'Thu, 06 Apr 2023 00:03:21 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}, 'operation_name': 'DescribeKeyPairs'}
  | 2023-04-05 17:03:21,176	PANIC utils.py:126 -- An error occurred (UnauthorizedOperation) when calling the DescribeKeyPairs operation: You are not authorized to perform this operation.
```

**Pull request closed without merging**
