### PR TITLE
Fix for operator role definition to add raycluster/finalizer

### PR DESCRIPTION
**Pull request by dmatch01**
## Why are these changes needed?

Fix to k8s operator role definition
## Related issue number

Fix for #13554 
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
I ran script with the following results:
```
$ scripts/format.sh
WARNING: Ray uses clang-format 7.0.0, You currently are using 11.0.1. This might generate different results.
From github.com:ray-project/ray
 * branch                master     -> FETCH_HEAD
 $
 ```
 From the output provided above, not sure if the script above is successful.

- [N/A] I've included any doc changes needed for https://docs.ray.io/en/master/.

- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/

Ran the following tests resulting in 2 failures:
```
$ bazel test --build_tests_only //:all  --test_output=streamed
Extracting Bazel installation...
//:actor_manager_test                                                    PASSED in 9.0s
//:client_connection_test                                                PASSED in 0.4s
//:cluster_resource_scheduler_test                                       PASSED in 0.7s
//:cluster_task_manager_test                                             PASSED in 0.7s
//:core_worker_test                                                      PASSED in 31.6s
//:create_request_queue_test                                             PASSED in 1.1s
//:dependency_manager_test                                               PASSED in 0.4s
//:direct_actor_transport_test                                           PASSED in 30.4s
//:direct_task_transport_test                                            PASSED in 0.4s
//:event_test                                                            PASSED in 3.6s
//:filesystem_test                                                       PASSED in 0.3s
//:gcs_actor_manager_test                                                PASSED in 0.5s
//:gcs_actor_scheduler_test                                              PASSED in 0.3s
//:gcs_node_manager_test                                                 PASSED in 0.4s
//:gcs_object_manager_test                                               PASSED in 0.4s
//:gcs_placement_group_manager_test                                      PASSED in 1.0s
//:gcs_placement_group_scheduler_test                                    PASSED in 0.7s
//:gcs_pub_sub_test                                                      PASSED in 7.2s
//:gcs_resource_manager_test                                             PASSED in 0.3s
//:gcs_resource_scheduler_test                                           PASSED in 0.3s
//:gcs_server_rpc_test                                                   PASSED in 3.6s
//:global_state_accessor_test                                            PASSED in 7.3s
//:id_test                                                               PASSED in 0.4s
//:in_memory_gcs_table_storage_test                                      PASSED in 0.7s
//:in_memory_store_client_test                                           PASSED in 0.8s
//:lease_policy_test                                                     PASSED in 0.4s
//:local_object_manager_test                                             PASSED in 0.4s
//:logging_test                                                          PASSED in 0.3s
//:metric_exporter_client_test                                           PASSED in 0.6s
//:object_recovery_manager_test                                          PASSED in 0.4s
//:placement_group_resource_manager_test                                 PASSED in 0.5s
//:pull_manager_test                                                     PASSED in 0.4s
//:push_manager_test                                                     PASSED in 0.4s
//:reconstruction_policy_test                                            PASSED in 1.5s
//:redis_gcs_table_storage_test                                          PASSED in 0.9s
//:redis_store_client_test                                               PASSED in 2.8s
//:reference_count_test                                                  PASSED in 0.4s
//:sample_test                                                           PASSED in 0.7s
//:scheduling_queue_test                                                 PASSED in 30.3s
//:sequencer_test                                                        PASSED in 0.5s
//:signal_test                                                           PASSED in 1.6s
//:stats_test                                                            PASSED in 3.9s
//:task_manager_test                                                     PASSED in 0.7s
//:util_test                                                             PASSED in 0.8s
//:worker_pool_test                                                      PASSED in 0.5s
//:asio_test                                                             FAILED in 1.4s
  /private/var/tmp/_bazel_darroyo/622e41ccb4a7fed29380a636c729d919/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/asio_test/test.log
//:gcs_server_test                                                       FAILED in 94.8s
  /private/var/tmp/_bazel_darroyo/622e41ccb4a7fed29380a636c729d919/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/gcs_server_test/test.log

Executed 47 out of 47 tests: 45 tests pass and 2 fail locally.
INFO: Build completed, 2 tests FAILED, 3568 total actions
$
```

- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
Thanks for these changes! This will allow the Ray operator to work with OpenShift. 

Could you confirm that the example in the documentation works for you after making the changes? https://docs.ray.io/en/master/cluster/k8s-operator.html

**Comment by dmatch01** [comment]
@DmitriGekhtman I was able to confirm that the `head` pod gets started (before then it was not starting at all).

```
kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
example-cluster-ray-head-5b6xs   1/1     Running   0          6h17m
ray-operator-pod                 1/1     Running   37         6h35m
$
```

Now I'm working on another error (see below).    

```
$ kubectl logs ray-operator-pod 
example-cluster:2021-01-19 13:51:48,200	DEBUG config.py:83 -- Updating the resources of node type head-node to include {'CPU': 1, 'GPU': 0}.
example-cluster:2021-01-19 13:51:48,201	DEBUG config.py:83 -- Updating the resources of node type worker-nodes to include {'CPU': 1, 'GPU': 0}.
example-cluster:2021-01-19 13:51:48,240	WARNING config.py:164 -- KubernetesNodeProvider: not checking if namespace 'ray' exists
example-cluster:2021-01-19 13:51:48,240	INFO config.py:184 -- KubernetesNodeProvider: no autoscaler_service_account config provided, must already exist
example-cluster:2021-01-19 13:51:48,240	INFO config.py:210 -- KubernetesNodeProvider: no autoscaler_role config provided, must already exist
example-cluster:2021-01-19 13:51:48,240	INFO config.py:236 -- KubernetesNodeProvider: no autoscaler_role_binding config provided, must already exist
example-cluster:2021-01-19 13:51:48,240	INFO config.py:269 -- KubernetesNodeProvider: no services config provided, must already exist
example-cluster:2021-01-19 13:51:48,399	INFO command_runner.py:171 -- NodeUpdater: example-cluster-ray-head-5b6xs: Running kubectl -n ray exec -it example-cluster-ray-head-5b6xs -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (uptime)'
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
 13:51:49 up 61 days, 35 min,  0 users,  load average: 0.51, 0.91, 1.12
example-cluster:2021-01-19 13:51:49,860	DEBUG updater.py:290 -- Node tags: {'ray-cluster-name': 'example-cluster', 'ray-launch-config': '98667bd93919c3750dd13f541b8a03e8f4642496', 'ray-node-name': 'ray-example-cluster-head', 'ray-node-status': 'waiting-for-ssh', 'ray-node-type': 'head', 'ray-node-uuid': 'add167be-4195-479a-9cdf-7ad34b45269c', 'ray-user-node-type': 'head-node'}
example-cluster:2021-01-19 13:51:49,997	INFO command_runner.py:171 -- NodeUpdater: example-cluster-ray-head-5b6xs: Running kubectl -n ray exec -it example-cluster-ray-head-5b6xs -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (mkdir -p ~)'
Unable to use a TTY - input is not a terminal or the right kind of file
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Unable to use a TTY - input is not a terminal or the right kind of file
rsync: mkstemp "/home/ray/.ray_bootstrap_config.yaml.zOQSSg" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
tar: ray_bootstrap_config.yaml: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
command terminated with exit code 2
2021-01-19 13:51:48,163	INFO commands.py:221 -- Cluster: example-cluster
2021-01-19 13:51:48,200	INFO commands.py:283 -- Checking Kubernetes environment settings
2021-01-19 13:51:48,266	INFO commands.py:555 -- Updating cluster configuration and running full setup.
2021-01-19 13:51:48,266	INFO commands.py:559 -- Cluster Ray runtime will be restarted. Confirm [y/N]: y [automatic, due to --yes]
2021-01-19 13:51:48,291	INFO commands.py:622 -- <1/1> Setting up head node
2021-01-19 13:51:48,292	INFO commands.py:666 -- Prepared bootstrap config
2021-01-19 13:51:48,292	WARN commands.py:501 -- The head node will not launch any workers because `ray start` does not have `--autoscaling-config` set.
Potential fix: add `--autoscaling-config=~/ray_bootstrap_config.yaml` to the `ray start` command under `head_start_ray_commands`.
2021-01-19 13:51:48,378	INFO updater.py:282 -- New status: waiting-for-ssh
2021-01-19 13:51:48,379	INFO updater.py:230 -- [1/7] Waiting for SSH to become available
2021-01-19 13:51:48,379	INFO updater.py:233 -- Running `uptime` as a test.
2021-01-19 13:51:49,833	SUCC updater.py:241 -- Success.
2021-01-19 13:51:49,833	INFO log_timer.py:27 -- NodeUpdater: example-cluster-ray-head-5b6xs: Got remote shell  [LogTimer=1455ms]
2021-01-19 13:51:49,861	INFO updater.py:318 -- Updating cluster configuration. [hash=6e9b1031a12a117b2dbdcaa1ccc5065b94dba980]
2021-01-19 13:51:49,997	INFO updater.py:322 -- New status: syncing-files
2021-01-19 13:51:49,997	INFO updater.py:208 -- [2/7] Processing file mounts
2021-01-19 13:51:52,616	INFO log_timer.py:27 -- NodeUpdater: example-cluster-ray-head-5b6xs: Synced /tmp/ray-bootstrap-v5fw6z3w to ~/ray_bootstrap_config.yaml  [LogTimer=2619ms]
2021-01-19 13:51:52,617	INFO log_timer.py:27 -- NodeUpdater: example-cluster-ray-head-5b6xs: Applied config 6e9b1031a12a117b2dbdcaa1ccc5065b94dba980  [LogTimer=4324ms]
2021-01-19 13:51:52,692	ERR updater.py:128 -- New status: update-failed
2021-01-19 13:51:52,692	ERR updater.py:130 -- !!!
2021-01-19 13:51:52,692	ERR updater.py:134 -- Setup command `['kubectl', '-n', 'ray', 'cp', '/tmp/ray-bootstrap-v5fw6z3w', 'ray/example-cluster-ray-head-5b6xs:/home/ray/ray_bootstrap_config.yaml']` failed with exit code 2. stderr:
2021-01-19 13:51:52,692	ERR updater.py:140 -- !!!
2021-01-19 13:51:52,716	PANIC commands.py:709 -- Failed to setup head node.
/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py:213: UserWarning: NodeUpdater: example-cluster-ray-head-5b6xs: rsync failed: 'Command '['/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh', '-aqz', '/tmp/ray-bootstrap-v5fw6z3w', 'example-cluster-ray-head-5b6xs@ray:/home/ray/ray_bootstrap_config.yaml']' returned non-zero exit status 23.'. Falling back to 'kubectl cp'
  UserWarning)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 207, in run_rsync_up
    "{}@{}:{}".format(self.node_id, self.namespace, target),
  File "/home/ray/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh', '-aqz', '/tmp/ray-bootstrap-v5fw6z3w', 'example-cluster-ray-head-5b6xs@ray:/home/ray/ray_bootstrap_config.yaml']' returned non-zero exit status 23.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 124, in run
    self.do_update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 324, in do_update
    self.rsync_up, step_numbers=(1, NUM_SETUP_STEPS))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 210, in sync_file_mounts
    do_sync(remote_path, local_path)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 198, in do_sync
    local_path, remote_path, docker_mount_if_possible=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/updater.py", line 459, in rsync_up
    self.cmd_runner.run_rsync_up(source, target, options=options)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/command_runner.py", line 219, in run_rsync_up
    target)
  File "/home/ray/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kubectl', '-n', 'ray', 'cp', '/tmp/ray-bootstrap-v5fw6z3w', 'ray/example-cluster-ray-head-5b6xs:/home/ray/ray_bootstrap_config.yaml']' returned non-zero exit status 2.

Process example-cluster:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/operator/operator.py", line 48, in _create_or_update
    self.start_head()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/operator/operator.py", line 60, in start_head
    no_config_cache=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 228, in create_or_update_cluster
    override_cluster_name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 709, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 585, in abort
    raise exc_cls("Exiting due to cli_logger.abort()")
click.exceptions.ClickException: Exiting due to cli_logger.abort()
$
```

**Comment by DmitriGekhtman** [comment]
@dmatch01 
I see -- this is progress!

It looks like OpenShift handles permissions a bit differently than vanilla Kubernetes.
The good news is that the violating piece of code is vestigial -- it's relevant only to the Ray cluster launcher, which uses the same code path.
So the new error can be circumvented.

I'll have to get back fixing this later in the week or on the weekend.
In the meantime, I'll file an issue to track the new error -- will cc you there.

Thanks for trying the Ray operator out and reporting these problems! I think we should be able to get it working on OpenShift in the very near future.

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
@edoakes 
Could you merge this PR?
The changes consist of a couple of additions to the operator pod's permissions.
I tested the the changes with the operator test here: https://github.com/ray-project/ray/pull/13437

**Comment by DmitriGekhtman** [comment]
@dmatch01 
The new issue is tracked here: https://github.com/ray-project/ray/issues/13569

**Comment by dmatch01** [comment]
> @dmatch01
> The latest error is tracked here: #13569

@DmitriGekhtman , @edoakes Thank you!

**Pull request merged**
