### PR TITLE
[Train] disable the log when train is used with tune

### LINKED ISSUE #25474: [Train] [Tune] When using Train with Tune, a `logdir` is created that's not the one specified by the user
### What happened + What you expected to happen

When initializing a Ray Trainer, we provide a `logdir` argument, and the `__init__` method of the Trainer stores it as a `logdir` class variable.

Then, when creating a Trainable with `Trainer.to_tune_trainable()`, it in-turn calls `_create_tune_trainable()`, which does not use `self.logdir`. So when `tune_function` is defined inside `_create_tune_trainable` with a Trainer initialization call, there's no logdir passed to it, and so, this Trainer ends up creating its own logdir in the default path `~/ray_results`.

https://github.com/ray-project/ray/blob/7f1bacc7dc9caf6d0ec042e39499bbf1d9a7d065/python/ray/train/trainer.py#L828-L843

This could be solved by passing `self.logdir` along to `_create_tune_trainable`.

Additionally, we also have the issue of the non-customizable run directory created by Ray Train as `run_<run_id>`. But since this directory is unused, it's not too much of an issue. And I believe it's partially being tracked here: https://github.com/ray-project/ray/issues/20807

### Versions / Dependencies

Python: 3.8.13
Ray: 1.12.1
Ubuntu 18.04.5

### Reproduction script

This isn't a reproduction script but should serve as an indicator of the variables that are being passed in.

```python
from ray import tune
from ray.train import Trainer

trainer = Trainer(
    backend="torch",
    num_workers=2,
    logdir=logdir,
)

trainable = trainer.to_tune_trainable(train_func)

tune.run(
    trainable,
    name=experiment_name,
    config=config,
    trial_name_creator=tune_trial_name_creator,
    trial_dirname_creator=tune_trial_dirname_creator,
    local_dir=local_dir,
    verbose=0,
)
```

### Notes
1. The `tune_trial_name_creator` function generates a unique name and uses the `config` in the `ray.tune.trial.Trial` object that's passed in to store the generated trial_name.
2. The `tune_dirname_creator` function simply returns the `trial_name` accessed from the `Trial` object. This way, we use the exact trial_name as the directory name.
3. The trial directory used by Tune is thus: `local_dir`/`experiment_name`/ `trial_name`.
4. The `logdir` passed to the `Trainer` is `local_dir`/`experiment_name`.

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by JiahaoYao**
pass a false flag so as to disable the log when train is used with tune, fix #25474. @amogkam 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by JiahaoYao** [comment]
image

Any idea about `if cond != False` does not pass the lint test? (basically wanna distinguish `False` and `None`)

**Comment by JiahaoYao** [comment]
image

these from rllib @amogkam

**Review by krfricke — APPROVED** [review]
LGTM

**Review by amogkam — CHANGES_REQUESTED** [review]
Thanks @JiahaoYao!

A couple questions that I have:
1. How does `logdir=False` affect Checkpointing? It seems like if you pass run_dir as None to the CheckpointManager this will break the checkpointing code path. The API for `CheckpointManager.on_start_training` does not accept None for the run_dir
2. How does this affect Callbacks? The start_training API does not accept None for the `logdir`. And it looks like not passing in one will cause `TBXLoggerCallback` to break.

I'm thinking that instead of exposing this to users and providing a footgun, we can instead disable run dir creation internally specifically for the Tune case, which doesn't use the above 2 codepaths and will still resolve the original issue.

**Comment by amogkam** [comment]
Use this as the implementation for `tune_function` https://github.com/ray-project/ray/blob/master/python/ray/train/data_parallel_trainer.py#L334-L368

**Pull request closed without merging**
