### PR TITLE
[ci] simplify rayci tags

### PR DESCRIPTION
**Pull request by aslonnie**
remove `RAY_CI_` prefixes, and `_AFFECTED` suffixes, and convert to lower cases. Tags should not shout.

### CODE REVIEW

**Comment by can-anyscale** [comment]
premerge failed, also does tags need to be an array?

**Comment by aslonnie** [comment]
let me check why the premerge fails..

**Comment by aslonnie** [comment]
> let me check why the premerge fails..

passing now.

python in the buildkite ami does not support typings.

**Review by can-anyscale — APPROVED** [review]

**Pull request merged**
