### PR TITLE
[Tune] Do not warn in BayesOpt w/ Uniform sampler

### LINKED ISSUE #30338: [Tune] Issue on page /tune/key-concepts.html
Im trying to run code from docs:
https://docs.ray.io/en/latest/tune/key-concepts.html

`from ray.tune.search.bayesopt import BayesOptSearch
from ray import air
from ray import tune
from ray.air import session

def objective(a, b):
    pred_F: float = 12 * a * 1.8 + b
    actual_F: float = 12 * 1.8 + 32
    MSE: float = (pred_F - actual_F) ** 2
    return MSE

def trainable(config):
    for x in range(20):
        score = objective(config["a"], config["b"])
        session.report({"score": score})

search_space = {"a": tune.uniform(0, 1), "b": tune.uniform(0, 20)}

algo = BayesOptSearch(random_search_steps=4)

tuner = tune.Tuner(
    trainable,
    tune_config=tune.TuneConfig(
        metric="score",
        mode="min",
        search_alg=algo,
    ),
    run_config=air.RunConfig(stop={"training_iteration": 20}),
    param_space=search_space,
)
tuner.fit()`

And i recieve this error. As far as i understand code in docs should work. If not how can i fix it. Thanx in advance.
```
2022-11-16 08:49:34,507	WARNING bayesopt_search.py:425 -- BayesOpt does not support specific sampling methods. The Uniform sampler will be dropped.
2022-11-16 08:49:34,508	WARNING bayesopt_search.py:425 -- BayesOpt does not support specific sampling methods. The Uniform sampler will be dropped.
```

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

BayesOpt supports only uniform sampling, but we erroneously warn when the Uniform sampler is used (as opposed to no sampler at all). This PR fixes that issue.

## Related issue number

Closes https://github.com/ray-project/ray/issues/30338

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by justinvyu** [comment]
Do we clarify in the docs what can be passed into the search space when using `BayesOptSearch`?

**Comment by Yard1** [comment]
@justinvyu We indirectly mention that by stating the space has to be continuous - we don't really call this out specifically in any searcher, really. We should improve that in a future PR!

**Comment by justinvyu** [comment]
Does the check need to also include other continuous spaces (`LogUniform`)? Maybe I am missing something here though.

**Comment by Yard1** [comment]
No, this searcher only supports basic uniform sampling:
```python
            if isinstance(domain, Float):
                if domain.sampler is not None and not isinstance(
                    domain.sampler, Uniform
                ):
                    logger.warning(
                        "BayesOpt does not support specific sampling methods. "
                        "The {} sampler will be dropped.".format(sampler)
                    )
                return (domain.lower, domain.upper) # <- BayesOpt domain definition allowing only for uniform sampling
```

**Review by xwjiang2010 — APPROVED** [review]

**Comment by xwjiang2010** [comment]
Just curious, why is that BayesOpt only supports uniform sampler? 

btw, will this page be updated? https://docs.ray.io/en/latest/tune/examples/bayesopt_example.html

It has the wrong warning..

**Comment by Yard1** [comment]
It only supports the uniform sampler as that's what's the underlying library supports.

**Review by krfricke — APPROVED** [review]
Thanks!

**Pull request merged**
