### PR TITLE
Allow customized initial worker count regardless of `num_cpus` and `maximum_startup_concurrent`

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

If the value of `--num-cpus` parameter specified in 'ray start' command is greater than `maximum_startup_concurrent`, Some workers are not started initially. We should ignore `maximum_startup_concurrent` while starting initial workers.

The fix:

I introduced two new internal configs - `num_initial_py_workers` and `num_initial_java_workers`. Raylet will start the specified count of initial workers of that language, regardless of `num_cpus` and `maximum_startup_concurrent`. The default value is `0`, so by default no workers will be started during startup.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

**Review by zhijunfu — APPROVED** [review]

**Comment by edoakes** [comment]
LGTM but seem to be some issues in the tests

**Comment by kfstorm** [comment]
@edoakes @robertnishihara Seems that some python tests specify a large value of `num_cpus` and with my code the tests spawn many python workers, which is much more than the situation with the master branch code and causes memory shortage.

For example, The test case `test_actor_multiple_gpus_from_multiple_tasks` needs to start 5 nodes with `num_cpus` of 50. When testing with the master branch, the amount of started workers was about 60.

```
$ ls raylet.*out | xargs -I {} bash -c "grep 'Started worker process' {} | wc -l"
13
11
12
12
16
```

But with this PR's code change, the amount of started workers was exactly 250.

```
$ ls raylet.*out | xargs -I {} bash -c "grep 'Started worker process' {} | wc -l"
50
50
50
50
50
```

If it's OK, I will add a new parameter to the `ray start` script, or maybe the internal config, to control the `num_initial_workers` parameter of raylet. So the `num_cpus` and the `num_initial_workers` can be decoupled. I'll also update these test cases to limit the actual workers started.

**Comment by edoakes** [comment]
@kfstorm Sure, that sounds like a good plan

**Comment by kfstorm** [comment]
I introduced two new internal configs `num_initial_py_workers` and `num_initial_java_workers`. I tried to update some Python test cases to specify a smaller `num_initial_py_workers` compared to `num_cpus`, but it's hard to find all the memory consuming test cases. I also tried to set the default values to 0 to not start any workers during startup, but it breaks some test cases which assume a number of `num_cpus` initial workers. So I end up with keep the existing behavior unless the two new configs are explicitly specified with non-negative values.

@raulchen @edoakes Please revisit this PR.

**Comment by robertnishihara** [comment]
Closing because this is stale, please reopen if this is a mistake.

**Pull request closed without merging**
