### PR TITLE
Bazelify tune tests in travis

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This switches the test runner to bazel for Tune tests, which automatically provides parallel testing and times out tests. See here for the timeouts enforced for each test size: https://docs.bazel.build/versions/master/test-encyclopedia.html

You can try this out by running:

```
$ bazel test python/ray/tune/...                          
INFO: Analyzed 17 targets (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 16 test targets...
INFO: Elapsed time: 437.721s, Critical Path: 338.90s
INFO: 20 processes: 16 linux-sandbox, 4 local.
INFO: Build completed successfully, 11 total actions
//python/ray/tune:test_automl_searcher                          (cached) PASSED in 3.6s
//python/ray/tune:test_checkpoint_manager                       (cached) PASSED in 5.7s
//python/ray/tune:test_cluster                                  (cached) PASSED in 160.8s
//python/ray/tune:test_commands                                 (cached) PASSED in 8.8s
//python/ray/tune:test_experiment                               (cached) PASSED in 3.4s
//python/ray/tune:test_tune_restore                             (cached) PASSED in 193.0s
//python/ray/tune:test_actor_reuse                                       PASSED in 56.4s
//python/ray/tune:test_dependency                                        PASSED in 13.3s
//python/ray/tune:test_experiment_analysis                               PASSED in 95.4s
//python/ray/tune:test_logger                                            PASSED in 8.0s
//python/ray/tune:test_ray_trial_executor                                PASSED in 75.4s
//python/ray/tune:test_track                                             PASSED in 16.4s
//python/ray/tune:test_trial_runner                                      PASSED in 338.6s
//python/ray/tune:test_trial_scheduler                                   PASSED in 60.1s
//python/ray/tune:test_tune_save_restore                                 PASSED in 3.0s
//python/ray/tune:test_tune_server                                       PASSED in 75.4s

Executed 10 out of 16 tests: 16 tests pass.
INFO: Build completed successfully, 11 total actions
```
Hopefully, we can bazelify other travis tests in this way too, to improve test reliability with timeouts.

### CODE REVIEW

**Comment by ericl** [comment]
@simon-mo does this break the test dash? You'll still get error dumps on failure, but on success only a summary of the tests run are shown.

**Comment by robertnishihara** [comment]
Nice! @ericl, I thought there was some deep incompatibility between bazel and pytest. Is that right?

**Comment by ericl** [comment]
@robertnishihara the trick is add a brief __main__ runner in each test script that calls pytest.main(): https://github.com/bazelbuild/rules_python/issues/240

A couple caveats: each file is treated as a single test. This means we should probably be breaking up large files into multiple test suites to get finer-grained failure detection. Also, you have to remember to add the test main.

**Comment by simon-mo** [comment]
@ericl Don't worry about test dashboard, I can update the regex once this is merged.

**Comment by ericl** [comment]
This is passing and ready for review.

**Review by simon-mo — APPROVED** [review]
Nice!
image

**Pull request merged**
