### PR TITLE
[core] fix potential dead lock

### LINKED ISSUE #17212: [core] Fix potential deadlocks in ray core
Running tests in debug mode reviews a bunch of potential deadlocks, with an example stacktrace at the later half of the issue. [[Failed tests](https://buildkite.com/ray-project/ray-builders-branch/builds/2408#47f37fa5-73d5-490e-86ef-ffff7d01fa0c)] [[turn on dbg](https://github.com/ray-project/ray/commit/dc49553f7bfd0a9342e2cec4c69e8234ebd2823c)]

Most likely absil detected we acquire two mutexes in different order, i.e. in one thread we acquire mutex a, then mutex b, whereas in another thread we acquire b prior than a. 

Our particular cases might not cause actual deadlock, but we avoid this anti-patterns whenever possible.

```


FAILED: //python/ray/serve:quickstart_class (Summary)
--
  | /private/var/tmp/_bazel_ec2-user/4a8641d6543be4086217113bd0a40cda/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/python/ray/serve/quickstart_class/test.log
  | /private/var/tmp/_bazel_ec2-user/4a8641d6543be4086217113bd0a40cda/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/python/ray/serve/quickstart_class/test_attempts/attempt_1.log
  | /private/var/tmp/_bazel_ec2-user/4a8641d6543be4086217113bd0a40cda/execroot/com_github_ray_project_ray/bazel-out/darwin-opt/testlogs/python/ray/serve/quickstart_class/test_attempts/attempt_2.log
  | (00:26:34) INFO: From Testing //python/ray/serve:quickstart_class:
  | ==================== Test output for //python/ray/serve:quickstart_class:
  | 2021-07-20 00:26:21,186	INFO services.py:1247 -- View the Ray dashboard at http://127.0.0.1:8265
  | (pid=6681) 2021-07-20 00:26:22,964	INFO http_state.py:75 -- Starting HTTP proxy with name 'wngTlf:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:10.0.1.52-0' on node 'node:10.0.1.52-0' listening on '127.0.0.1:8000'
  | 2021-07-20 00:26:23,129	INFO api.py:716 -- Started Serve instance in namespace 'serve'.
  | 2021-07-20 00:26:23,135	INFO api.py:418 -- Updating deployment 'Counter'.
  | (pid=6681) 2021-07-20 00:26:23,181	INFO backend_state.py:869 -- Adding 1 replicas to backend 'Counter'.
  | (pid=6672) INFO:     Started server process [6672]
  | [mutex.cc : 1368] RAW: Potential Mutex deadlock:
  | @ 0x10d582612 absl::lts_20210324::DebugOnlyDeadlockCheck()
  | @ 0x10d58253c absl::lts_20210324::Mutex::Lock()
  | @ 0x10d573223 absl::lts_20210324::MutexLock::MutexLock()
  | @ 0x10d572ccd absl::lts_20210324::MutexLock::MutexLock()
  | @ 0x10c21e92a ray::CoreWorker::CoreWorker()::$_15::operator()()
  | @ 0x10c21e78c std::__1::__invoke<>()
  | @ 0x10c21e717 std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c21e6b7 std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c21d3c8 std::__1::__function::__func<>::operator()()
  | @ 0x10c36c48a std::__1::__function::__value_func<>::operator()()
  | @ 0x10c35c3c7 std::__1::function<>::operator()()
  | @ 0x10c35f026 ray::TaskManager::PendingTaskFailed()
  | @ 0x10c3ab39e ray::CoreWorkerDirectActorTaskSubmitter::PushActorTask()::$_4::operator()()
  | @ 0x10c3ab066 std::__1::__invoke<>()
  | @ 0x10c3aafe7 std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c3aaf77 std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c3a9bc8 std::__1::__function::__func<>::operator()()
  | @ 0x10c1b3f4a std::__1::__function::__value_func<>::operator()()
  | @ 0x10c1b3e95 std::__1::function<>::operator()()
  | @ 0x10c1b98d1 ray::rpc::CoreWorkerClient::SendRequests()::{lambda()#1}::operator()()
  | @ 0x10c1b9746 std::__1::__invoke<>()
  | @ 0x10c1b96c7 std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c1b9677 std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c1b8288 std::__1::__function::__func<>::operator()()
  | @ 0x10c1b3f4a std::__1::__function::__value_func<>::operator()()
  | @ 0x10c1b3e95 std::__1::function<>::operator()()
  | @ 0x10c1b396f ray::rpc::ClientCallImpl<>::OnReplyReceived()
  | @ 0x10c041edc ray::rpc::ClientCallManager::PollEventsFromCompletionQueue()::{lambda()#1}::operator()()
  | @ 0x10c041e8d std::__1::__invoke<>()
  | @ 0x10c041e3d std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c041e0d std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c040b4e std::__1::__function::__func<>::operator()()
  | @ 0x10c16d9b5 std::__1::__function::__value_func<>::operator()()
  | @ 0x10c00e835 std::__1::function<>::operator()()
  | @ 0x10cd7b1d5 boost::asio::asio_handler_invoke<>()
  | @ 0x10cd7b1b2 boost_asio_handler_invoke_helpers::invoke<>()
  | @ 0x10cd7b081 boost::asio::detail::handler_work<>::complete<>()
  | @ 0x10cd7aedc boost::asio::detail::completion_handler<>::do_complete()
  | @ 0x10d07afc5 boost::asio::detail::scheduler_operation::complete()
  | @ 0x10d07a427 boost::asio::detail::scheduler::do_run_one()
  |  
  | [mutex.cc : 1380] RAW: Acquiring absl::Mutex 0x7fef652fec90 while holding  0x7fef34d5c348; a cycle in the historical lock ordering graph has been observed
  | [mutex.cc : 1381] RAW: Cycle:
  | [mutex.cc : 1395] RAW: mutex@0x7fef652fec90 stack:
  | @ 0x10d582612 absl::lts_20210324::DebugOnlyDeadlockCheck()
  | @ 0x10d58253c absl::lts_20210324::Mutex::Lock()
  | @ 0x10d573223 absl::lts_20210324::MutexLock::MutexLock()
  | @ 0x10d572ccd absl::lts_20210324::MutexLock::MutexLock()
  | @ 0x10c21e92a ray::CoreWorker::CoreWorker()::$_15::operator()()
  | @ 0x10c21e78c std::__1::__invoke<>()
  | @ 0x10c21e717 std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c21e6b7 std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c21d3c8 std::__1::__function::__func<>::operator()()
  | @ 0x10c36c48a std::__1::__function::__value_func<>::operator()()
  | @ 0x10c35c3c7 std::__1::function<>::operator()()
  | @ 0x10c35f026 ray::TaskManager::PendingTaskFailed()
  | @ 0x10c3ab39e ray::CoreWorkerDirectActorTaskSubmitter::PushActorTask()::$_4::operator()()
  | @ 0x10c3ab066 std::__1::__invoke<>()
  | @ 0x10c3aafe7 std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c3aaf77 std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c3a9bc8 std::__1::__function::__func<>::operator()()
  | @ 0x10c1b3f4a std::__1::__function::__value_func<>::operator()()
  | @ 0x10c1b3e95 std::__1::function<>::operator()()
  | @ 0x10c1b98d1 ray::rpc::CoreWorkerClient::SendRequests()::{lambda()#1}::operator()()
  | @ 0x10c1b9746 std::__1::__invoke<>()
  | @ 0x10c1b96c7 std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c1b9677 std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c1b8288 std::__1::__function::__func<>::operator()()
  | @ 0x10c1b3f4a std::__1::__function::__value_func<>::operator()()
  | @ 0x10c1b3e95 std::__1::function<>::operator()()
  | @ 0x10c1b396f ray::rpc::ClientCallImpl<>::OnReplyReceived()
  | @ 0x10c041edc ray::rpc::ClientCallManager::PollEventsFromCompletionQueue()::{lambda()#1}::operator()()
  | @ 0x10c041e8d std::__1::__invoke<>()
  | @ 0x10c041e3d std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c041e0d std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c040b4e std::__1::__function::__func<>::operator()()
  | @ 0x10c16d9b5 std::__1::__function::__value_func<>::operator()()
  | @ 0x10c00e835 std::__1::function<>::operator()()
  | @ 0x10cd7b1d5 boost::asio::asio_handler_invoke<>()
  | @ 0x10cd7b1b2 boost_asio_handler_invoke_helpers::invoke<>()
  | @ 0x10cd7b081 boost::asio::detail::handler_work<>::complete<>()
  | @ 0x10cd7aedc boost::asio::detail::completion_handler<>::do_complete()
  | @ 0x10d07afc5 boost::asio::detail::scheduler_operation::complete()
  | @ 0x10d07a427 boost::asio::detail::scheduler::do_run_one()
  |  
  | [mutex.cc : 1395] RAW: mutex@0x7fef34d5c348 stack:
  | @ 0x10d582612 absl::lts_20210324::DebugOnlyDeadlockCheck()
  | @ 0x10d58253c absl::lts_20210324::Mutex::Lock()
  | @ 0x10d573223 absl::lts_20210324::MutexLock::MutexLock()
  | @ 0x10d572ccd absl::lts_20210324::MutexLock::MutexLock()
  | @ 0x10c37fb9b ray::CoreWorkerDirectActorTaskSubmitter::CheckTimeoutTasks()
  | @ 0x10c00f7f4 ray::CoreWorker::InternalHeartbeat()
  | @ 0x10c21ccf8 ray::CoreWorker::CoreWorker()::$_14::operator()()
  | @ 0x10c21ccbd std::__1::__invoke<>()
  | @ 0x10c21cc6d std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10c21cc3d std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10c21b98e std::__1::__function::__func<>::operator()()
  | @ 0x10c16d9b5 std::__1::__function::__value_func<>::operator()()
  | @ 0x10c00e835 std::__1::function<>::operator()()
  | @ 0x10cd8ccd0 ray::PeriodicalRunner::DoRunFnPeriodically()
  | @ 0x10cd9835f ray::PeriodicalRunner::RunFnPeriodically()::$_0::operator()()
  | @ 0x10cd9821d std::__1::__invoke<>()
  | @ 0x10cd981cd std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @ 0x10cd9819d std::__1::__function::__alloc_func<>::operator()()
  | @ 0x10cd96e1e std::__1::__function::__func<>::operator()()
  | @ 0x10c16d9b5 std::__1::__function::__value_func<>::operator()()
  | @ 0x10c00e835 std::__1::function<>::operator()()
  | @ 0x10cd7b1d5 boost::asio::asio_handler_invoke<>()
  | @ 0x10cd7b1b2 boost_asio_handler_invoke_helpers::invoke<>()
  | @ 0x10cd7b081 boost::asio::detail::handler_work<>::complete<>()
  | @ 0x10cd7aedc boost::asio::detail::completion_handler<>::do_complete()
  | @ 0x10d07afc5 boost::asio::detail::scheduler_operation::complete()
  | @ 0x10d07a427 boost::asio::detail::scheduler::do_run_one()
  | @ 0x10d06ff0e boost::asio::detail::scheduler::run()
  | @ 0x10d06fdfe boost::asio::io_context::run()
  | @ 0x10c00e24e ray::CoreWorker::RunIOService()
  | @ 0x10c244288 ray::CoreWorker::CoreWorker()::$_22::operator()()
  | @ 0x10c24421d std::__1::__invoke<>()
  | @ 0x10c2441c5 std::__1::__thread_execute<>()
  | @ 0x10c243e46 std::__1::__thread_proxy<>()
  | @ 0x7fff6ad38109 _pthread_start
  | @ 0x7fff6ad33b8b thread_start
  |  
  | [mutex.cc : 1400] RAW: dying due to potential deadlock
  | *** SIGABRT received at time=1626740784 ***
  | PC: @     0x7fff6ac7b33a  (unknown)  __pthread_kill
  | @        0x10cf26043  (unknown)  absl::lts_20210324::WriteFailureInfo()
  | @        0x10cf25c0c  (unknown)  absl::lts_20210324::AbslFailureSignalHandler()
  | @     0x7fff6ad2c5fd  (unknown)  _sigtramp
  | @                0x0  (unknown)  0x0
  | @     0x7fff6ac02808  (unknown)  abort
  | @        0x10d5c4e66  (unknown)  absl::lts_20210324::raw_logging_internal::(anonymous namespace)::RawLogVA()
  | @        0x10d5c4c3e  (unknown)  absl::lts_20210324::raw_logging_internal::RawLog()
  | @        0x10d587b9e  (unknown)  absl::lts_20210324::DeadlockCheck()
  | @        0x10d582612  (unknown)  absl::lts_20210324::DebugOnlyDeadlockCheck()
  | @        0x10d58253c  (unknown)  absl::lts_20210324::Mutex::Lock()
  | @        0x10d573223  (unknown)  absl::lts_20210324::MutexLock::MutexLock()
  | @        0x10d572ccd  (unknown)  absl::lts_20210324::MutexLock::MutexLock()
  | @        0x10c21e92a  (unknown)  ray::CoreWorker::CoreWorker()::$_15::operator()()
  | @        0x10c21e78c  (unknown)  std::__1::__invoke<>()
  | @        0x10c21e717  (unknown)  std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @        0x10c21e6b7  (unknown)  std::__1::__function::__alloc_func<>::operator()()
  | @        0x10c21d3c8  (unknown)  std::__1::__function::__func<>::operator()()
  | @        0x10c36c48a  (unknown)  std::__1::__function::__value_func<>::operator()()
  | @        0x10c35c3c7  (unknown)  std::__1::function<>::operator()()
  | @        0x10c35f026  (unknown)  ray::TaskManager::PendingTaskFailed()
  | @        0x10c3ab39e  (unknown)  ray::CoreWorkerDirectActorTaskSubmitter::PushActorTask()::$_4::operator()()
  | @        0x10c3ab066  (unknown)  std::__1::__invoke<>()
  | @        0x10c3aafe7  (unknown)  std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @        0x10c3aaf77  (unknown)  std::__1::__function::__alloc_func<>::operator()()
  | @        0x10c3a9bc8  (unknown)  std::__1::__function::__func<>::operator()()
  | @        0x10c1b3f4a  (unknown)  std::__1::__function::__value_func<>::operator()()
  | @        0x10c1b3e95  (unknown)  std::__1::function<>::operator()()
  | @        0x10c1b98d1  (unknown)  ray::rpc::CoreWorkerClient::SendRequests()::{lambda()#1}::operator()()
  | @        0x10c1b9746  (unknown)  std::__1::__invoke<>()
  | @        0x10c1b96c7  (unknown)  std::__1::__invoke_void_return_wrapper<>::__call<>()
  | @        0x10c1b9677  (unknown)  std::__1::__function::__alloc_func<>::operator()()
  | @        0x10c1b8288  (unknown)  std::__1::__function::__func<>::operator()()
  | @ ... and at least 25 more frames
  | ================================================================================


```

cc @rkooo567

### PR DESCRIPTION
**Pull request by scv119**
absl complains there are [potential deadlocks](https://github.com/ray-project/ray/issues/17212) when running in debug mode.
after reading the stack it turns out we have following lock acquiring order:

-  in `CoreWorker::InternalHeartbeat`, we first acquire and hold lock `CoreWorker.mutex_`, then we acquire and hold `CoreWorkerDirectActorTaskSubmitter.mutex_` via `CoreWorkerDirectActorTaskSubmitter.SubmitTask` call.
- however, in `CoreWorkerDirectActorTaskSubmitter.PushActorTask`, we first acquire and hold lock `CoreWorkerDirectActorTaskSubmitter.mutex_`, and then we hold `CoreWorker.mutex_` through `TaskManager`'s `retry_task_callback_`

This leads to potential dead locks if those two call path happens in different threads. This PR fix it by releasing the lock before calling to `SubmitTask` in `CoreWorker::InternalHeartbeat`

## Test Plan
- [x] verified debug test no longer complains potential deadlocks.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Hmm the number of failing tests is suspicious, trigger a rerun?

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@scv119 btw, we probably need to verify this before merging it? (how do we know this fixes the issue now? )

**Comment by scv119** [comment]
lets wait for
https://github.com/ray-project/ray/pull/17399 which should show the bug.

**Comment by scv119** [comment]
@rkooo567 maybe we can merge this as we it will take a while to consolidate the debug-asan test?

**Comment by rkooo567** [comment]
SGTM. Btw Eric already merged it haha

**Pull request merged**
