### PR TITLE
[Logging] Merge .out and .err worker logs

### PR DESCRIPTION
**Pull request by rkooo567**
## Related issue number

https://github.com/ray-project/ray/issues/12310

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Looks good. Note that this is a breaking change for users that are ingesting the logs automatically right now, so we should be sure to broadcast it as well as we can (e.g., put it in docs, release notes, and announce on slack).

**Comment by rkooo567** [comment]
@edoakes That's a great point! I will merge the PR a few days after broadcasting it to the slack (and will update the documentation)

**Review by mfitton — APPROVED** [review]
Looks good!

**Comment by edoakes** [comment]
ping @rkooo567

**Comment by edoakes** [comment]
Closing stale

**Pull request closed without merging**
