### PR TITLE
[WIP] Revert unhandled exception PR for 1.3.0 temporarily

### PR DESCRIPTION
**Pull request by rkooo567**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @wuisawesome

**Comment by amogkam** [comment]
@rkooo567 can you please ping me when this is ready to be picked. Thanks.

**Comment by rkooo567** [comment]
Hey @simon-mo Do you know why the buildkite build fails?

**Comment by simon-mo** [comment]
`determine_tests_to_run` failed probably because your PR isn't based off releases/1.3.0. Can you run rebase (not merge)?

**Comment by rkooo567** [comment]
@simon-mo It should be based off of release 1.3.0. (I checked out from there). So, here's what I did.

1. Checked out release 1.3.0 branch.
2. Checked out to the current branch.
3. Call revert on the offending commit.
4. Fixed merge conflict.

**Comment by rkooo567** [comment]
@simon-mo maybe having a quick call?

**Comment by rkooo567** [comment]
Hey @wuisawesome Can you review the PR?

**Review by wuisawesome — APPROVED** [review]

**Review by wuisawesome — APPROVED** [review]

**Comment by rkooo567** [comment]
Both windows tests failures are from release 1.3.0 branch. Lint failure and buildkite failure is due to this PR is for release branch according to Simon. test_failure is a known flaky test. Merging it.

**Pull request merged**
