### PR TITLE
[Log] Ignore callstacktrace test for windows

### PR DESCRIPTION
**Pull request by ashione**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Why do we do this? Is this not working on Windows?

**Comment by ashione** [comment]
> Why do we do this? Is this not working on Windows?

Max depth of GetStackStrace is 32, but It will dump more than 32 frames before test case so we can't catch the all stack frames within 32 depth size.

**Comment by ashione** [comment]
> > Why do we do this? Is this not working on Windows?
> 
> Max depth of GetStackStrace is 32, but It will dump more than 32 frames before test case so we can't catch the all stack frames within 32 depth size.

You may find the detail in https://github.com/ray-project/ray/pull/11410/checks?check_run_id=1257791585

**Comment by ashione** [comment]
These are stacktrace on windows. I have no idea about that. It looks like other thread stack not main thread where gtest test case run in.
```
    @   00007FF669B968C0  public: class std::basic_ostream<char,struct std::char_traits<char> > * __ptr64 __cdecl google::base::CheckOpMessageBuilder::ForVar1(void) __ptr64
    @   00007FF669B956DF  public: virtual void __cdecl google::LogSink::WaitTillSent(void) __ptr64
    @   00007FF669B951BC  public: virtual void __cdecl google::LogSink::WaitTillSent(void) __ptr64
    @   00007FF669BA3D4C  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BA3C36  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BB54DC  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BB527D  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BB5D08  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BA3DEC  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BA3D16  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669BB571C  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF669B95AAF  public: virtual void __cdecl google::LogSink::WaitTillSent(void) __ptr64
    @   00007FF669BC1760  bool __cdecl google::Demangle(char const * __ptr64,char * __ptr64,int)
    @   00007FF8E8237974  BaseThreadInitThunk
    @   00007FF8E839A271  RtlUserThreadStart
```

**Comment by kfstorm** [comment]
@ashione Are you suggesting that `GetCallTrace` doesn't work on Windows?

**Comment by rkooo567** [comment]
+1 for @kfstorm's qusetion.

**Comment by ashione** [comment]
@rkooo567 @kfstorm I'll check code path of glog getcallstack on windows. I suspect this feature was originally unreliable.

**Comment by ashione** [comment]
Stacktrace seems unsupported in glog of ray on windows. I find the glog patch https://github.com/google/glog/pull/168 porting a feature to windows  about OS stacktrace. @rkooo567 @kfstorm

**Review by rkooo567 — APPROVED** [review]

**Review by kfstorm — APPROVED** [review]

**Pull request merged**
