### PR TITLE
[RLlib] Fix policy restore. Avoid keyward params. (#29227)

### PR DESCRIPTION
**Pull request by gjoliver**
Signed-off-by: Jun Gong <jungong@anyscale.com>

## Why are these changes needed?

Cherry pick a fix for the broken policy checkpoint loading functionality.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Could the TLs help approve this? @gjoliver

**Review by richardliaw — APPROVED** [review]
test pls

**Comment by gjoliver** [comment]
> test pls

ack. I will add a test now in MASTER.

**Comment by rickyyx** [comment]
Will you create another cherry pick PR with tests? Or should I merge this?

**Comment by gjoliver** [comment]
please merge this. we don't need to pick the test into this release branch.

**Comment by rickyyx** [comment]
Is /rllib:connectors/tests/test_agent  being fixed/tracked in other PRs/issues?

**Comment by gjoliver** [comment]
> Is /rllib:connectors/tests/test_agent being fixed/tracked in other PRs/issues?

this is one of the tests that are flaky due to infra issues.
I don't know what we can fix for those cases.

**Comment by rickyyx** [comment]
> > Is /rllib:connectors/tests/test_agent being fixed/tracked in other PRs/issues?
> 
> this is one of the tests that are flaky due to infra issues. I don't know what we can fix for those cases.

Gotcha, thanks! I will yolo as for now then - and open issues if this shows up in CI main branch.

**Pull request merged**
