### PR TITLE
[Docs] Remove unnecessary bases

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

**Before**
image

**After**
image

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by peytondmurray** [comment]
@bveeramani Does this message only appear if you explicitly subclass `object`? If so, we can tear out any of those instances, as it was only necessary to subclass `object` in Python 2.

**Review by angelinalg — APPROVED** [review]
Would the `object` class ever be listed in a list with multiple bases? Or is it automatically dropped if there is another base class to list?

**Comment by bveeramani** [comment]
> @bveeramani Does this message only appear if you explicitly subclass `object`? 

No, it shows up even if you don't explicitly subclass `object`.

> If so, we can tear out any of those instances, as it was only necessary to subclass `object` in Python 2.

Totally agree. I think we still have those in a handful of places.

**Comment by bveeramani** [comment]
> Would the `object` class ever be listed in a list with multiple bases? Or is it automatically dropped if there is another base class to list?

Don't think so unless you explicitly did something like `Subclass(BaseClass, object)`, but that would be incredibly unusual.

**Review by peytondmurray — APPROVED** [review]
Thanks for this :rocket:

**Pull request merged**
