### PR TITLE
[ci] Move ML windows tests to be continuous runs

### PR DESCRIPTION
**Pull request by khluu**
## Why are these changes needed?
- Move ML train windows tests to only run on fixed schedule on postmerge instead of every single merge.
- The tests only run whenever RAYCI_CONTINUOUS_BUILD env variable is on, which is flipped on in the Buildkite schedule builds.

## Checks

Ran 2 test builds on Buildkite, one with flag on & one with flag off. Can confirm that the one with flag off doesn't have the changed test listed.

### CODE REVIEW

**Comment by can-anyscale** [comment]
My bad, let's not move the windows wheel job to continuous run; rather let's move the windows ml job as an exercise

**Review by aslonnie — COMMENTED** [review]
could you update the PR title?

also we normally start the title with `[ci]` (lower case) rather than `[CI]`.

**Comment by can-anyscale** [comment]
FYI @matthewdeng, we are experiencing with moving some of the CI tests to a continuous, periodically basis (to save CI cost but still provide useful signals for engineers). Since the ml window job has only one test and window is less impact, we are moving it first. Let us know if you have strong opinion in not doing this. Thankkks.

**Comment by khluu** [comment]
Ran 2 test builds on Buildkite, one with flag on & one with flag off. Can confirm that the one with flag off doesn't have the changed test listed.

**Comment by khluu** [comment]
> could you update the PR title?
> 
> also we normally start the title with `[ci]` (lower case) rather than `[CI]`.

Just updated it!

**Review by aslonnie — APPROVED** [review]

**Review by can-anyscale — APPROVED** [review]
too fast!

**Pull request merged**
