### PR TITLE
[Streaming]new ray streaming doc page in ray project index sources

### PR DESCRIPTION
**Pull request by ashione**
Publish ray-streaming doc

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ashione** [comment]
@ericl @jovany-wang  @raulchen  This pr will publish ray streaming doc in released doc page.  Ray-Streaming sub-directory will be added in left column of index page. Coud you mind review these changes or give us some suggestions?

**Comment by ashione** [comment]
https://ray--20139.org.readthedocs.build/en/20139/streaming/streaming.html 
See more details from above url.

**Comment by ericl** [comment]
Hi @ashione , Ray streaming is a legacy project and we should not be recommending it to new users.

**Comment by ashione** [comment]
> Hi @ashione , Ray streaming is a legacy project and we should not be recommending it to new users.

In our plan, ray streaming directory will be moved to other repo of ray-project, but it's still developed in the future. So like ray-tune or ray-dataset, I hope ray-streaming main introduction can be searched in ray document page.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
