### PR TITLE
[Release] prefer last cluster env version in release tests

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Currently the release test runner prefers the first successfully version of a cluster env, instead of the last version. But sometimes a cluster env may build successfully on Anyscale but cannot launch cluster successfully (e.g. [version 2 here](https://console.anyscale.com/o/anyscale-internal/configurations/app-config-versions/apt_zQJupHXbpLBRuq9QbrTHCE6s)) or new dependencies need to be installed, so a new version needs to be built. The existing logic always picks up the 1st successful build and cannot pick up the new cluster env version.

Although this is an edge case (tweaking cluster env versions, with the same Ray wheel or cluster env name), I believe it is possible for others to run into it.

Also, avoid running most of the CI tests for changes under `release/ray_release/`.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
Gentle ping @krfricke? I want to add a test as well but not sure how to do it.

**Comment by krfricke** [comment]
Sorry this slipped - I'll take a look in a bit. Looks good so far, I'll think about the implications of not looping through the builds on my way home.

**Comment by krfricke** [comment]
For a test, you can copy `testBuildClusterEnvPreBuildSucceeded` and put the failing build second, then assert that the error is raised.

I think otherwise these changes look good!

**Review by krfricke — APPROVED** [review]
This is great, thanks!

**Pull request merged**
