### PR TITLE
[core] Allow worker Python interpeters to inherit -S and -s flags

### LINKED ISSUE #22977: [core][Bug] Ray processes escaping hermetic python environment
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

ray.init() the (grand)child python processes are escaping our hermetic python environment (specifically they start to look for modules on the system, instead of our bazel build sandbox)

This leads to Actor failures 
```
(TemporaryActor pid=550)     import google.auth
(TemporaryActor pid=550) ModuleNotFoundError: No module named 'google.auth'
(TemporaryActor pid=544) 2022-03-09 23:15:03,378	ERROR worker.py:431 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::Trainer.__init__() (pid=544, ip=xx.xxx.xxx.xx)
(TemporaryActor pid=544) RuntimeError: The actor with name Trainer failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
```

Looking at `python/ray/_private/services.py` most python subprocesses are started as `{sys.executable} <some script>` without the `-Ss` flags that would prevent extending the module search path into `site-packages`

Please let us know if there are any workarounds that can be applied to deal with this or code references that show this should not be happening.

### Versions / Dependencies

ray==1.9.1
python==3.7(via bazel)

### Reproduction script

Working on a shareable repro...

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

Starting the Python interpreter with flags "-S" and "-s" disables site package imports. This is useful when running Python scripts in hermetic build environments.

This PR allows the Python interpreter in worker processes to inherit these flags -- if you've gone through the trouble of starting Ray using these flags, it makes enough sense to pass the flags on to the Python workers.

## Related issue number

Closes https://github.com/ray-project/ray/issues/22977
(without explicit API change)

## Checks

Can add some tests if the change looks reasonable.

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
Thanks for adding this, looks like a clean solution that avoids an API change.
- How common do you think `-S` or -s` usage is currently? (Is there any risk that this could break some users' existing workflows?)
- Could you add a test for this? I guess it should be possible to check `sys.flags` in a remote task.

**Comment by DmitriGekhtman** [comment]
> * How common do you think `-S` or -s` usage is currently? (Is there any risk that this could break some users' existing workflows?)

I'd wager the use-case is extremely niche and that this will not break any user's workflow.

> * Could you add a test for this? I guess it should be possible to check `sys.flags` in a remote task.

Working on it...unfortunately, disabling site packages is a foot-gun for typical Ray installs :p

**Comment by DmitriGekhtman** [comment]
> I'd wager the use-case is extremely niche and that this will not break any user's workflow.

Like, I think you'd have to be doing something beyond bizarre for this change to cause problems for you.

> Working on it...unfortunately, disabling site packages is a foot-gun for typical Ray installs :p

Un-footgunned for CI purposes by manipulating the PYTHONPATH! Test added.

**Comment by architkulkarni** [comment]
Makes sense, you've convinced me that it won't break existing workflows. A few more questions:
- How do you actually start ray with these flags (when you call `ray start --head`, where do you specify them)?
- Related to the above, what's the problem with disabling site-packages for "typical Ray installs" and why didn't it work in CI?  What does your Ray install have to look like for it to work?

Lint is failing: https://buildkite.com/ray-project/oss-ci-build-pr/builds/12844#018677d7-19e7-4807-9755-d965dd7889e3/1701-1768 
Might be worth merging master, I think there are some old unrelated flaky tests failing.

**Comment by DmitriGekhtman** [comment]
> How do you actually start ray with these flags (when you call ray start --head, where do you specify them)?

For local Ray, `python -Ss my_local_script_that_calls_ray`.
For clusters with Ray start, you have to directly invoke the script `python -Ssm ray.scripts.scripts start`. 

> what's the problem with disabling site-packages for "typical Ray installs" and why didn't it work in CI? 

Typically, you'd have Ray itself in user site packages -- my first attempt at writing the unit test prevented the Python worker from importing Ray. Will make the comment in the test clearer.

> What does your Ray install have to look like for it to work?

Many organizations have hermetic build setups that require modules to be explicitly declared as dependencies in order to be imported. (I don't know by what mechanism the build system makes the declared modules available.)

**Review by architkulkarni — APPROVED** [review]
Thanks, that clears things up completely! Approving pending tests passing

**Comment by DmitriGekhtman** [comment]
Seems CI is having a sad related to Bazel versions.

**Comment by DmitriGekhtman** [comment]
Test failures appear to be unrelated build issues. Merging.

**Pull request merged**
