### PR TITLE
[RLlib] Export RLLIB_TEST_NO_JAX_IMPORT=1

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
## Why are these changes needed?

In order to fix currently failing release tests (for example [here](https://buildkite.com/ray-project/release-tests-branch/builds/1420#01869f4c-af3d-445e-b660-7658c078ad2b)), we need to limit JAX imports during testing.

### CODE REVIEW

**Review by kouroshHakha — APPROVED** [review]

**Comment by gjoliver** [comment]
flax errors out on import?
do we just need to pin flax version or something?

**Comment by gjoliver** [comment]
like what is flax but without jax import ... :)

**Comment by ArturNiederfahrenhorst** [comment]
I can't seem to find the error you are referring to.

**Comment by gjoliver** [comment]
> I can't seem to find the error you are referring to.

sorry, I asked about it before seeing you and amog's discussion.
is this PR good for merge? CI still has random errors, but I don't know if it's related.

**Comment by ArturNiederfahrenhorst** [comment]
Failures seem unrelated to me, too.

**Pull request merged**
