### PR TITLE
[CI][Fix] Fix a previous change that used wrong function names

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?

Fix a bug that I committed in a recent change where we used wrong function names. Also rename the function parameter to key for consistency

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] CI tests

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]

**Review by zhe-thoughts — APPROVED** [review]
Approved for merging to master

**Review by Yard1 — APPROVED** [review]

**Comment by scv119** [comment]
@can-anyscale which test shows this fixed the problem?

**Comment by can-anyscale** [comment]
This test shows the issue: https://buildkite.com/ray-project/release-tests-branch/builds/1491#0187299a-9690-47e6-9e4f-11d63332de7b/711-789. The error message pins point this issue

```
[ERROR 2023-03-28 12:29:05,257] util.py: 131  Retry function call failed due to 'JobFileManager' object has no attribute 'delete_s3_fn' in 8 seconds...
--
  | Traceback (most recent call last):
  | File "/tmp/release-IJgz66hUku/release/ray_release/util.py", line 125, in exponential_backoff_retry
  | return f()
  | File "/tmp/release-IJgz66hUku/release/ray_release/file_manager/job_file_manager.py", line 190, in delete_fn
  | self.delete_s3_fn(cloud_key, recursive)
  | AttributeError: 'JobFileManager' object has no attribute 'delete_s3_fn'
```


I running the test again on top of this diff to check if the issue is now gone: https://buildkite.com/ray-project/release-tests-pr/builds/32946

**Comment by can-anyscale** [comment]
Test passed now w00t w00t: https://buildkite.com/ray-project/release-tests-pr/builds/32946#_. Can you help merge @scv119. Thanks

**Pull request merged**
