### PR TITLE
[ci] Remove LinkCheck build

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Has been consistently red: https://flaky-tests.ray.io/

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
hmm, isn't this useful to find broken links?

**Comment by pcmoritz** [comment]
Yes it is! All the links it has been showing as broken recently (after we got rid of some initial flaky links) have actually been broken, we should fix them instead of removing the check.

**Comment by pcmoritz** [comment]
Most recently:
```


(rllib/core-concepts: line  323) broken    https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/dqn.py - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/dqn.py
--
  | (rllib/rllib-algorithms: line   83) ok        https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/apex.py
  | (rllib/rllib-concepts: line  378) broken    https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/simple_q_tf_policy.py - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/simple_q_tf_policy.py
  | (rllib/rllib-algorithms: line  793) ok        https://github.com/ray-project/ray/blob/master/rllib/agents/maddpg/maddpg.py
  | (rllib/package_ref/trainer: line   47) broken    https://github.com/ray-project/ray/blob/master/rllib/agents/pg/pg.py - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/rllib/agents/pg/pg.py
  | (rllib/rllib-algorithms: line  339) ok        https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/r2d2.py
  | (rllib/rllib-concepts: line   11) broken    https://github.com/ray-project/ray/blob/master/rllib/agents/pg/pg_tf_policy.py - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/blob/master/rllib/agents/pg/pg_tf_policy.py


```

**Comment by simon-mo** [comment]
Instead of treating this as a CI job that people can't possibly know whether it's related to their fix or not (for example, these docs link only breaks _after_ the PR has been merged), how about we make link check a nightly tests. Even better, split it up by teams given the doc build. 

Another way is to set up some sort of way to allow them to fail and don't prominently prioritize their failure in the flaky test tracker. But I'm not sure that would achieve the same goal.

**Comment by pcmoritz** [comment]
Happy to do alternative approaches here, as long as it satisfies the requirement to avoid broken links/get them fixed before the documentation goes out to users!

**Comment by richardliaw** [comment]
Would much rather prefer to do link-check at nightly users

**Comment by edoakes** [comment]
Ok, who wants to take the action item here? I'm just flying blind trying to make our builds more green here :)

**Comment by ericl** [comment]
I like the idea of making it a nightly test and part of our release process.

**Comment by richardliaw** [comment]
Can oncall take this?

**Comment by maxpumperla** [comment]
Well, in the case of the above referenced RLlib refactoring, if we have links directly to a GitHub remote, we have to refactor in two phases. First introduce the new code and merge, then point links to the new files and delete the old. It's certainly possible to do it right.

The broader question to me is: how to make devs take ownership of these kinds of "clean up after yourself" scenarios? This won't get better by hiding the check.

**Pull request closed without merging**
