### PR TITLE
[Data] dataset repartition by col with hash func

### PR DESCRIPTION
**Pull request by yiwei00000**
## Why are these changes needed?

Dataset repartition according to the specified col.
such as ：
            >>> data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 20, 'c': 21}]
            >>> df = pd.DataFrame(data)
            >>> ds = ray.data.from_pandas(df)
            >>> ds.repartition(10, shuffle=True,col='a').write_csv(path="/tmp/test")

### CODE REVIEW

**Review by yiwei00000 — COMMENTED** [review]
approve

**Comment by c21** [comment]
Hi @yiwei00000 thanks for the first-time contribution! This looks like an API change, so we need to discuss more. Are you open to meet and discuss this PR?

**Comment by yiwei00000** [comment]
> 



> Hi @yiwei00000 thanks for the first-time contribution! This looks like an API change, so we need to discuss more. Are you open to meet and discuss this PR?

Of course I would.

**Comment by yiwei00000** [comment]
> Hi @yiwei00000 thanks for the first-time contribution! This looks like an API change, so we need to discuss more. Are you open to meet and discuss this PR?

We used Spark for data processing before and want to change it to ray data. However, the current repartition does not support operations by col, so we hope to support such APIs.

**Pull request closed without merging**
