### PR TITLE
[Docs] Fix dependencies for Pong Example

### PR DESCRIPTION
**Pull request by amogkam**
## Why are these changes needed?

atari_py recently had a release that caused pong example to fail. This PR removes atari_py and gym[atari] as setup.py extras from `requirements.txt` to match with https://github.com/ray-project/ray/pull/15292. The pinned versions in `requirements_rllib.txt` will be used instead.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
Hmm, do you know what's the point about having these setup.py extras in `requirements.txt` when we have a separate `requirements-rllib.txt`?

**Comment by amogkam** [comment]
@richardliaw I believe the point is to emulate exactly what's installed when you do `pip install ray[tune]`, `pip install ray[rllib]`, etc. The pinning here should be exactly the same as what's in `setup.py`. This is a good point though- there are currently some discrepancies here, so I'll make another PR to clean this up.

**Comment by amogkam** [comment]
Also, there should not be any overlap between what's in `requirements.txt` and `requirements-tune.txt`/`requirements-rllib.txt`. I'll also clean this up as well.

**Review by ericl — APPROVED** [review]
nice!

**Comment by amogkam** [comment]
The only failing test is flaky and unrelated. Going to merge this in.

**Pull request merged**
