### PR TITLE
Revert "[core][autoscaler] Fix pg id serialization with hex rather than binary for cluster state reporting #37132"

### PR DESCRIPTION
**Pull request by rickyyx**
Reverts ray-project/ray#37176

### CODE REVIEW

**Comment by rickyyx** [comment]
The revert is failing still: https://buildkite.com/ray-project/oss-ci-build-pr/builds/28487#01894c4a-3099-4138-86fa-055eac5a3a3f

Likely a dependency issue.

**Comment by rkooo567** [comment]
Should we re-revert?

**Comment by rickyyx** [comment]
> Should we re-revert?

wdym

**Comment by rkooo567** [comment]
nvm. I thought we merged this PR

**Pull request closed without merging**
