### PR TITLE
[java] Add maxTaskRetries option for java actor creation

### PR DESCRIPTION
**Pull request by kira-lin**
Signed-off-by: Zhi Lin <zl1nn@outlook.com>

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kira-lin** [comment]
@jovany-wang I reopened this pr, sorry for the inconvenience

**Review by jovany-wang — APPROVED** [review]
Looks good to me. Thanks for the contribution.

**Comment by kfstorm** [comment]
@kira-lin Could you add a unit test case?

**Comment by kira-lin** [comment]
@kfstorm Do java tests have the utility (like ClusterUtils in python) to test object recovery? I didn't find a way to lose an object in plasma in java tests. Plus, this pr just opens the option for users, the function is implemented in ray core, and is tested in python.

**Comment by kfstorm** [comment]
> @kfstorm Do java tests have the utility (like ClusterUtils in python) to test object recovery? I didn't find a way to lose an object in plasma in java tests. Plus, this pr just opens the option for users, the function is implemented in ray core, and is tested in python.

Could you try copying `test_actor_restart_with_retry` into Java? I don't see any special logic about deleting objects in plasma.

**Comment by kira-lin** [comment]
OK. I was thinking about testing resubmitting actor task during object reconstruction, because that's our use case.

**Comment by kira-lin** [comment]
@kfstorm ci passed

**Review by kfstorm — APPROVED** [review]
LGTM. Thanks!

**Comment by kira-lin** [comment]
@ericl  @raulchen @WangTaoTheTonic @iycheng Could you please take a look and merge it if possible, appreciated

**Review by jovany-wang — APPROVED** [review]

**Pull request merged**
