### PR TITLE
[Datasets] Lazy import `tensorflow-metadata` when reading/writing TFRecords

### LINKED ISSUE #33404: [Datasets][nightly] read_tfrecords_benchmark_single_node is failling on master
It looks missing a depdency:
```
[INFO 2023-03-16 16:18:29,691] log.py: 11  Test read_tfrecords_benchmark_single_node finished after 0.00 seconds. Last logs:
--
  |  
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 2792, in write_fn_wrapper
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     return write_fn(blocks, ctx)
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/planner/write.py", line 16, in fn
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     return [[datasource.write(blocks, ctx, **write_args)]]
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/file_based_datasource.py", line 338, in write
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     return write_block(write_path, block)
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/file_based_datasource.py", line 313, in write_block
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     **write_args,
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/tfrecords_datasource.py", line 72, in _write_block
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     for example in examples:
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/tfrecords_datasource.py", line 123, in _convert_arrow_table_to_examples
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     schema_feature_type,
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/datasource/tfrecords_datasource.py", line 210, in _value_to_feature
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351)     from tensorflow_metadata.proto.v0 import schema_pb2
  | (ReadImage->MapBatches(images_to_bytes)->Write pid=1351) ModuleNotFoundError: No module named 'tensorflow_metadata'
```
More details: https://buildkite.com/ray-project/release-tests-branch/builds/1450#0186ec74-e4c9-44c3-8e0a-8ef7e18d60d0

### LINKED ISSUE #33420: [ci] `doc:source/ray-air/doc_code/computer_vision` failure
This test has started failing with `ModuleNotFoundError: No module named 'tensorflow_metadata'`

Looks like this was introduced in: https://github.com/ray-project/ray/pull/32857

Some initial ideas:
1. Should we make this a lazy import?
2. Should `tensorflow_metadata` be installed with `tensorflow`?

**Trace:**
```
(ReadTFRecord->MapBatches(decode_bytes) pid=4890)     from tensorflow_metadata.proto.v0 import schema_pb2
(ReadTFRecord->MapBatches(decode_bytes) pid=4890) ModuleNotFoundError: No module named 'tensorflow_metadata'
ReadTFRecord->MapBatches(decode_bytes) 0:   0%|                                                                                                                                              | 0/46 [00:05<?, ?it/s]Traceback (most recent call last):
  File "doc/source/ray-air/doc_code/computer_vision.py", line 430, in <module>
    main()
  File "doc/source/ray-air/doc_code/computer_vision.py", line 4, in main
    test(framework=framework, datasource=datasource)
  File "doc/source/ray-air/doc_code/computer_vision.py", line 20, in test
    dataset = dataset.limit(32)
  File "/ray/python/ray/data/dataset.py", line 2180, in limit
    block_list = self._plan.execute().truncate_by_rows(limit)
  File "/ray/python/ray/data/_internal/plan.py", line 577, in execute
    dataset_uuid=self._dataset_uuid,
  File "/ray/python/ray/data/_internal/execution/legacy_compat.py", line 101, in execute_to_legacy_block_list
    bundles = executor.execute(dag, initial_stats=stats)
  File "/ray/python/ray/data/_internal/execution/bulk_executor.py", line 85, in execute
    return OutputIterator(execute_recursive(dag))
  File "/ray/python/ray/data/_internal/execution/bulk_executor.py", line 66, in execute_recursive
    output = _naive_run_until_complete(op)
  File "/ray/python/ray/data/_internal/execution/bulk_executor.py", line 109, in _naive_run_until_complete
    op.notify_work_completed(ready)
  File "/ray/python/ray/data/_internal/execution/operators/task_pool_map_operator.py", line 65, in notify_work_completed
    task.output = self._map_ref_to_ref_bundle(ref)
  File "/ray/python/ray/data/_internal/execution/operators/map_operator.py", line 316, in _map_ref_to_ref_bundle
    all_refs = list(ray.get(ref))
  File "/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/ray/python/ray/_private/worker.py", line 2426, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ModuleNotFoundError): ray::ReadTFRecord->MapBatches(decode_bytes)() (pid=4894, ip=172.18.0.3)
  File "/ray/python/ray/data/_internal/execution/operators/map_operator.py", line 374, in _map_task
    for b_out in fn(iter(blocks), ctx):
  File "/ray/python/ray/data/_internal/execution/legacy_compat.py", line 274, in do_map
    yield from block_fn(blocks, ctx, *fn_args, **fn_kwargs)
  File "/ray/python/ray/data/_internal/planner/map_batches.py", line 106, in fn
    for batch in formatted_batch_iter:
  File "/ray/python/ray/data/_internal/block_batching.py", line 172, in batch_blocks
    for formatted_batch in batch_iter:
  File "/ray/python/ray/data/_internal/block_batching.py", line 400, in _format_batches
    for block in block_iter:
  File "/ray/python/ray/data/_internal/block_batching.py", line 363, in _blocks_to_batches
    for block in block_iter:
  File "/ray/python/ray/data/_internal/plan.py", line 1309, in wrapper
    yield from fn(block, ctx, *args, **kwargs)
  File "/ray/python/ray/data/_internal/plan.py", line 1187, in block_fn
    for block in read_fn():
  File "/ray/python/ray/data/datasource/file_based_datasource.py", line 490, in read_files
    for data in read_stream(f, read_path, **reader_args):
  File "/ray/python/ray/data/datasource/tfrecords_datasource.py", line 50, in _read_stream
    yield pa.Table.from_pydict(_convert_example_to_dict(example, tf_schema))
  File "/ray/python/ray/data/datasource/tfrecords_datasource.py", line 94, in _convert_example_to_dict
    record[feature_name] = _get_feature_value(feature, schema_feature_type)
  File "/ray/python/ray/data/datasource/tfrecords_datasource.py", line 146, in _get_feature_value
    from tensorflow_metadata.proto.v0 import schema_pb2
ModuleNotFoundError: No module named 'tensorflow_metadata'
```

### PR DESCRIPTION
**Pull request by scottjlee**
## Why are these changes needed?
`tensorflow-metadata` package is not installed by default by Ray AIR dependencies, and we do not wish to enforce it as a hard requirement. Therefore, we lazily import the library when it is specifically needed (i.e. when a user-specified schema is provided for `read_tfrecords` / `write_tfrecords`).

## Related issue number
Closes #33420 and closes https://github.com/ray-project/ray/issues/33404

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by bveeramani — APPROVED** [review]
LGTM

**Review by c21 — APPROVED** [review]

**Comment by c21** [comment]
@scottjlee? Can you re-trigger the CI to make sure tests are passed? Thanks.

**Comment by c21** [comment]
There's no flaky test in master - https://flakey-tests.ray.io/?owner=data .

**Comment by ollie-iterators** [comment]
It looks like the test is getting close to being all read on https://flakey-tests.ray.io/.
Screenshot 2023-03-21 at 5 10 42 PM

**Comment by scottjlee** [comment]
@amogkam this should be ready to merge now -- the remaining failures on `Documentation` and Windows tests looks unrelated.

**Pull request merged**
