### PR TITLE
[CI] skip failing java tests

### PR DESCRIPTION
**Pull request by amogkam**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
cc @kfstorm

**Comment by wuisawesome** [comment]
Hey, do we know if these tests are just flaky? or a symptom of a real issue with our java api? If this indicates a real stability issue, do we need to make it a release blocker?

**Comment by amogkam** [comment]
These tests are sometimes failing in the CI, but not always. I'm not sure what this means in terms of API stability, @kfstorm or @raulchen would be better suited to answer this question.

**Review by kfstorm — APPROVED** [review]
LGTM. Will fix them later.

**Comment by kfstorm** [comment]
There might be some real issues m, but they are rare to occur. So to me they are not release blockers.

**Comment by kfstorm** [comment]
@amogkam Please fix lint errors.

**Pull request merged**
