### PR TITLE
[Docs] Fix linkcheck for ecosystem gallery

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

Small typo in the ecosystem gallery generator caused links there to break.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by maxpumperla** [comment]
@Yard1 unfortunately this breaks the gallery. the tabs are needed. Can you elaborate how this relates to link checking? thanks!

**Review by krfricke — APPROVED** [review]
Thanks!

**Comment by krfricke** [comment]
Linkcheck looks good but let's address @maxpumperla's concerns

**Comment by maxpumperla** [comment]
Screenshot 2022-09-27 at 17 47 13

in case it's not clear what I meant, yaml is quite sensitive

**Comment by Yard1** [comment]
@maxpumperla @krfricke reverted the tabs change, should be good now - let's wait for docs build to see.

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
Thanks for fixing this!

**Pull request merged**
