### PR TITLE
[serve] Make Serve CLI and serve.build() non-public

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

This change makes `serve.build()` non-public and hides the following Serve CLI commands:
* `deploy`
* `config`
* `delete`
* `build`

## Related issue number

`serve.build()` was introduced recently in #23232.

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
     - This change refactors unit tests to use `build()` as a non-public API.

### CODE REVIEW

**Comment by edoakes** [comment]
@shrekris-anyscale could you please make sure that the docstrings for `.bind` and `DeploymentNode` are also up to date?

**Comment by shrekris-anyscale** [comment]
@edoakes I removed references to outdated and hidden commands, so they should be up to date. @jiaodong Could you please double check the new docstrings for [`DeploymentNode`](https://github.com/ray-project/ray/blob/9cbf0d6ea3f1ba4bb8b46369955df171144d644d/python/ray/serve/api.py#L1037) and `.bind` (in [DeploymentNode](https://github.com/ray-project/ray/blob/9cbf0d6ea3f1ba4bb8b46369955df171144d644d/python/ray/serve/api.py#L1052) and in [Deployment](https://github.com/ray-project/ray/blob/9cbf0d6ea3f1ba4bb8b46369955df171144d644d/python/ray/serve/api.py#L1225)) in this PR to confirm that they make sense?

**Comment by edoakes** [comment]
@shrekris-anyscale can we update the `DeploymentNode` docstring to say "deployment graph" instead of "multi-deployment applicaton" ?

**Comment by edoakes** [comment]
@shrekris-anyscale test failing

**Comment by shrekris-anyscale** [comment]
@edoakes Sounds good, I updated the docstring and the tests.

**Review by simon-mo — APPROVED** [review]

**Review by edoakes — APPROVED** [review]

**Review by jiaodong — APPROVED** [review]

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@jianoaix @zhe-thoughts we need to cherry-pick this to avoid surfacing APIs that aren't ready for public use. @shrekris-anyscale will make a PR to cherry-pick. Shouldn't require any additional release testing.

**Comment by shrekris-anyscale** [comment]
I made a cherry-pick PR at #23537.

**Pull request merged**
