### PR TITLE
[tune] Support for HyperOpt 

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
Adds HyperOpt support to Tune. Mainly to validate API.

TODOs:
- [ ] Docs 
  - [ ] Document specific functionality we are not supporting
- [ ] Tests
  - [ ] try a mix of hyperopt, regular exp, and json exp
  - [ ] Try mixing hyperopt and median_stopping
  - [ ] check error message when usage is improper
  - [ ] resolve `loss_attr` vs `reward_attr`? 
- [x] Verify that the TPE is being updated
- [x] Example
- [x] Clean up to move `generate_trials` into the Experiment class
  - [x] Maintain state in Experiment class - add hook from TrialRunner to update Experiment class?

## Related issue number
#1622

### CODE REVIEW

**Comment by richardliaw** [comment]
HyperOpt implementation tested on:
```
def easy_objective(args):
    # val = args["height"]
    return (args["height"] - 14) ** 2 + abs(args["width"] - 3)

space = {
    'width': hp.uniform('width', 0, 20),
    'height': hp.uniform('height', -100, 100),
} 
```

screenshot 2018-03-19 19 18 23

**Comment by ericl** [comment]
I'm not sure about subclassing `Experiment`. What's the advantage of doing so, does it allow you to combine it with e.g. Median stopping rule?

**Comment by richardliaw** [comment]
yeah, scheduling and suggestion doesn't need to be done in the same class

**Comment by richardliaw** [comment]
Closing this in case this is useful in the future, and going to open a new PR with previous commit.

**Pull request closed without merging**
