### PR TITLE
[docs][cherry-pick] Example Gallery clean up

### PR DESCRIPTION
**Pull request by angelinalg**
Cherry-picking for 2.9.0:
* [[docs] [rllib] Remove outdated RLlib examples from the docs 1/N](https://github.com/ray-project/ray/pull/41472#top)
* [[docs] [train] Example Gallery Train examples to be the same as the ones on the Train Examples page](https://github.com/ray-project/ray/pull/41596#top)
* [[docs][data][core][tune] remove mention of Many Model Training](https://github.com/ray-project/ray/pull/41682#top)
* [[docs] [data] remove Data Processing tag from sidenav and examples](https://github.com/ray-project/ray/pull/41686#top)
* [[docs][serve] Fix subsection title hierarchy](https://github.com/ray-project/ray/pull/41746#top)
cc: @architkulkarni 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
Is it OK to pick this after we build the wheel? This is just me being over cautious about having the wheel on time

**Comment by architkulkarni** [comment]
If all the changes were in `doc` I think it would be okay to merge after the final wheel build.  But this PR has changes outside of `doc`, and it even looks like an RLlib unit test is modified. So it might be better to merge it before.  (Assuming the unit test passes)

**Comment by angelinalg** [comment]
I believe the failing exploding-death-star tests were signed off by @sven1977 except for the `exploding-death-star-rllib-contrib-qmix-tests`. I presume this is also a flakey test. Could someone from RLlib confirm?

**Review by sven1977 — APPROVED** [review]
Approved from RLlib perspective.
Thanks for this PR @angelinalg !

**Review by zhe-thoughts — APPROVED** [review]
Approved, but @architkulkarni if possible let's pick after we are able to have a green wheel without this PR (that we can easily go back to)

**Comment by architkulkarni** [comment]
Sounds good. Everything looks good, will merge after we have the first "green commit" on the release branch

**Pull request merged**
