### PR TITLE
Fix doc lint

### PR DESCRIPTION
**Pull request by dentiny**
The linting issue blocks me from push commits (by my pre-commit hook) :(

### CODE REVIEW

**Comment by rynewang** [comment]
surprised your pre commit hook complains on a file you don't touch in a commit?

**Comment by dentiny** [comment]
> surprised your pre commit hook complains on a file you don't touch in a commit?

Yes! Exactly, I'm also surprised as well.
@rynewang could you please help me merge the PR?

**Comment by dentiny** [comment]
Meanwhile, I'm also surprised how these trailing blanks slip through our CI.

**Comment by rynewang** [comment]
@sven1977 a trivial doc-only PR, please stamp :)

**Pull request merged**
