### PR TITLE
Metrics export Service

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

The previous PR was broken when merged into master. This PR fixes all issues.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
Jenkins, test this please

**Comment by rkooo567** [comment]
Jenkins, retest this please.

**Comment by rkooo567** [comment]
Jenkins retest this please.

**Comment by rkooo567** [comment]
Jenkins retest this please.

**Review by simon-mo — APPROVED** [review]
passing travis, nice!

**Pull request merged**
