### PR TITLE
[CI] [Serve] Split `test_cli` into two tests

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

`test_cli` has been flaky in `master` recently:

Screen Shot 2023-07-10 at 10 34 05 AM

Generally, it fails due to timeout ([example](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4884#018932f1-d789-4e1f-8207-30d24829e6f1/2869-5099)). This change splits `test_cli` into two separate tests, so it stops timing out.

## Related issue number

N/A

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
     - This change doesn't affect existing behavior.

### CODE REVIEW

**Review by GeneDer — APPROVED** [review]
:shipit:

**Review by edoakes — APPROVED** [review]
nit: other tests are stylized as `test_standalone1.py` (no underscore). better to be consistent (I prefer what you have here)

**Comment by edoakes** [comment]
some relevant test failures

**Comment by shrekris-anyscale** [comment]
There were also some genuine failures with `test_deploy` in `test_cli.py`. It periodically failed to query an application after deploying it. The root cause was that some requests were still being processed by the previous application it deployed, so they took too long to shut down due to the graceful timeout.

I added a tighter `graceful_shutdown_timeout_s` to each deployment in these configs, and `test_deploy` passes consistently locally now. I also renamed `test_deploy` to `test_deploy_basic`.

**Pull request merged**
