### PR TITLE
AWS Spot Fleet support

### LINKED ISSUE #11506: [autoscaler] Support AWS Fleet Mode
### Describe your feature request

from @markgoodhead:

Have you guys considered a version of the autoscaler that instead uses the EC2 Autoscaling? Some of the features there are kind of redundant/managed by the autoscaler right now but the killer feature I'm thinking of right now would be the ability to dynamically select different instance types based on availability / capacity. We're currently struggling to get spot instances in a number of different regions in AWS and it's really hurting our ability to manage our ray instances. 

cc @mattearllongshot

### PR DESCRIPTION
**Pull request by mattearllongshot**
AWS Spot Fleet is a method of requesting EC2 instances in terms of
resources rather than explicitly specifying individual nodes to launch.
One defines a set of launch specs each of which might correspond with a
difference instance type, along with a so called instance weight, and a
total amount of instance weight to be launched.  AWS then works out the
optimal instance types to launch which would satify the total required
weight.

This PR adds support for spot fleet requests to the autoscaler. CPU
resource in Ray maps to instance weights in the spot fleet request.  To
achieve this a `ResourceLauncher` class has been added alongside the
`NodeLauncher` class which pulls requests to launch CPU resource off a
queue and passes the request onto the node provider.  The AWS node
provider in turn has new methods to handle launching nodes according to
total amount of required CPU (`create_cpu`) and for checking the current
amount of non-terminated CPU (`non_terminated_cpu`).

When operating in fleet mode (ie.
`auto_scaler['config']['fleet']['enabled']` is True), the logic in
`StandardAutoscaler` is changed to use a resource launcher instead of
node launcher and measure desired / running CPUs rather than desired /
running nodes.

Note that when fleet mode is enabled launching nodes via
the node launcher is not possible. In addition, when in fleet mode,
any other resource other than CPU is ignored, since the spot fleet API
only allows one dimension in its instance weighting.

## Why are these changes needed?

Adds support for spot fleet requests to the autoscaler, which removes the need for the user to have to manually try lots of different instance types.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mattearllongshot** [comment]
Any comments on this, or shall we wait until our meeting to discuss it?

**Comment by ericl** [comment]
Some thoughts given the other in-flight work on autoscaler.

1. We're currently working on removing the legacy autoscaling algorithm (the one that calculates target_nodes) and replacing it entirely with the new bin-packing resource_demand_scheduler. This will be a large code change, so it would be better to apply this change after that.
2. I think we can avoid adding a lot of new code to autoscaler.py by introducing a new "ResourceProvider" interface. Depending on the config, the resource provider can be a SpotFleetResourceProvider or the current ResourceDemandScheduler (which internally uses node provider).

@AmeerHajAli @wuisawesome can comment more.

**Comment by wuisawesome** [comment]
@mattearllongshot I plan on joining the meeting. Happy to talk more about it then too.

**Comment by AmeerHajAli** [comment]
I will join the meeting too :)

**Comment by markgoodhead** [comment]
I'm guessing this being closed means there's no desire to support this feature in the future? If so that's really disappointing as we use it a lot internally and will have to maintain our own fork indefinitely 😞

**Pull request closed without merging**
