### PR TITLE
[Java] Update log4j to 2.12.1

### PR DESCRIPTION
**Pull request by raulchen**
## Why are these changes needed?

Log4j 1.2 has vulnerability issues

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by pcmoritz** [comment]
Thanks @raulchen ! There is an error, is it related to the PR? Looks related:
```
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2

[TestNG] Running:

  /home/travis/build/ray-project/ray/java/testng.xml
```

**Comment by raulchen** [comment]
Yeah, configuration format has changed in log4j 2. We need to update that as well.

**Comment by robertnishihara** [comment]
@raulchen we should still fix the vulnerability. Do we know what the issue was?

**Comment by raulchen** [comment]
@robertnishihara I don't know know what the issue was. But I agree we should update to log4j 2.
This PR is too old. I'm closing it and will ask @chaokunyang to submit another PR.

**Pull request closed without merging**
