### PR TITLE
[CherryPick][Core][Doc] #32236 #32520 #32551 #32570

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
#32236 #32520 #32551 #32570

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by cadedaniel — APPROVED** [review]
LGTM, all changes are doc changes.

Let's wait until doc tests pass before merging

**Review by zhe-thoughts — APPROVED** [review]
Approved for picking into 2.3.0

**Comment by cadedaniel** [comment]
@jjyao is @justinvyu working on the doctest failures? is there a summary of the issue?

**Comment by justinvyu** [comment]
@cadedaniel PR with fix is here https://github.com/ray-project/ray/pull/32551 (waiting to merge into master)

**Pull request merged**
