### PR TITLE
Update CODEOWNERS for dashboard snapshot

### PR DESCRIPTION
**Pull request by wuisawesome**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by AmeerHajAli** [comment]
Should we put here @alanwguo / @joeybai instead since they maintain the dashboard snapshot?

**Comment by AmeerHajAli** [comment]
@wuisawesome , can you please put @ijrsvt instead and also add him to ray client boto?

**Comment by ijrsvt** [comment]
@wuisawesome added a PR to add Client Proto to CODEOWNERS https://github.com/ray-project/ray/pull/17210

**Review by ijrsvt — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
