### PR TITLE
Add a new blog article for Ray Serve

### PR DESCRIPTION
**Pull request by jbesomi**
I recently discovered Ray.io and think it's fantastic! Congratulations on creating such a great tool.  I tried to set-up Ray Serve on a remote cluster last week and found the documentation to be missing some important information, so I wrote an article about it in the hopes of helping others better understand how to use it.  Keep up the great work! 💪

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]
hey this is awesome! thanks a bunch for your contribution!

how do we improve our documentation, if you don't mind me asking?

**Comment by jbesomi** [comment]
I don't mind at all.

I would organise the content in a more structured way as well as reduce the levels of nested content.

For instance, assuming each service has it's own CLI, I would opt for a structure like:

Tool A:
 - CLI Tool A
 - ...
 
 Tool B
 - CLI Tool B
 - ...
 
As of now, to find the "Ray Serve Config" one needs to go to (Ray Serve > User Guides > Production Guide > Serve Config Files).

Hope this helps. Happy to provide more advices/support if needed.

**Comment by richardliaw** [comment]
I just realized.... you're the texthero author? I love that package :)

**Comment by richardliaw** [comment]
And thanks for the feedback btw! I've forwarded it to the team.

**Comment by jbesomi** [comment]
Glad you like Texthero :) I am currently working on a new next-gen package/product for ML (and considering using ray for the cloud/compute part), hopefully you will love that too 🎉

**Pull request merged**
