### PR TITLE
[DO NOT MERGE] wasm on ray test merge

### PR DESCRIPTION
**Pull request by wilsonwang371**
## Why are these changes needed?

wasm on ray merge test. This is for debugging the wasm-on-ray branch.

## Related issue number

N/A

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X] This PR is not tested :(

### CODE REVIEW

**Comment by ollie-iterators** [comment]
Why was there lots of force-pushing of this PR? I noticed that during the all the pushing, the setup.py file still errors so the tests that have failed will still likely be failing.

**Comment by wilsonwang371** [comment]
> Why was there lots of force-pushing of this PR? I noticed that during the all the pushing, the setup.py file still errors so the tests that have failed will still likely be failing.

Actually, the failures now reduced from 21 to around 12 now. I am mainly fixing the issues with the build environment compatibility. It is not directly related to the implementation. 

Thanks

**Comment by ollie-iterators** [comment]
> > Why was there lots of force-pushing of this PR? I noticed that during the all the pushing, the setup.py file still errors so the tests that have failed will still likely be failing.
> 
> Actually, the failures now reduced from 21 to around 12 now. I am mainly fixing the issues with the build environment compatibility. It is not directly related to the implementation.
> 
> Thanks

There was lots of force-pushing before the commit 11 hours ago, and nothing changed.

**Comment by ollie-iterators** [comment]
Perhaps this should wait until Python 3.7 has been removed because I think that part of the issue with setup.py is that it does not work well with Python 3.7.

**Comment by wilsonwang371** [comment]
> Perhaps this should wait until Python 3.7 has been removed because I think that part of the issue with setup.py is that it does not work well with Python 3.7.

Thanks. I will close this pull request later when most of the build and test issues resolved. I will periodically rebase my code to keep up with the latest master branch

**Pull request closed without merging**
