### PR TITLE
Disable flaky test test_delete_objects_multi_node

### PR DESCRIPTION
**Pull request by ericl**

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Actually, can you skip with new scheduler? This is the error log I am seeing;
```
(pid=raylet) [2020-12-02 00:47:24,811 C 10656 10656] node_manager.cc:1027:  Check failed: new_scheduler_enabled_ == false 

```

**Comment by rkooo567** [comment]
IT looks like the issue is that new scheduler is not enabled (idk why).
```
(pid=raylet) [2020-12-02 02:01:18,486 C 7855 7855] node_manager.cc:1027:  Check failed: new_scheduler_enabled_ == false 
```

**Comment by ericl** [comment]
Sure... why is it flaky though?

**Comment by rkooo567** [comment]
Hmm good point. I am not sure. The check is inside `DispatchTask`. Maybe we have code that calls DispatchTask around object spilling?

**Comment by rkooo567** [comment]
Ah, this seems to be the root cause

```cpp
      worker_pool_(
          io_service, config.num_initial_workers, config.num_workers_soft_limit,
          config.num_initial_python_workers_for_first_job,
          config.maximum_startup_concurrency, config.min_worker_port,
          config.max_worker_port, config.worker_ports, gcs_client_,
          config.worker_commands, config.raylet_config,
          /*starting_worker_timeout_callback=*/
          [this]() { this->DispatchTasks(this->local_queues_.GetReadyTasksByClass()); }),
```

`starting_worker_timeout_callback` is called in the object spilling path for some reason I guess. We should probably add new scheduler method that is equivalent to dispatch task here.

**Pull request merged**
