### PR TITLE
[ci] update release test requirements

### PR DESCRIPTION
**Pull request by can-anyscale**
Update release test requirements; there are some issues with existing wandb version on the latest release test run https://buildkite.com/ray-project/release/builds/19693

Need to update the gpu image to cuda 12.1 as well, because the latest upgrade of torch doesn't work with cuda 11.8 anymore.

Test:
- CI
- Release tests

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]
are the tests now passing?

**Comment by can-anyscale** [comment]
i'm running some of them here https://buildkite.com/ray-project/release/builds/19744

**Comment by aslonnie** [comment]
> i'm running some of them here https://buildkite.com/ray-project/release/builds/19744

seems that all failing again..

**Comment by can-anyscale** [comment]
not trivial as i though, will try again later

**Pull request closed without merging**
