### PR TITLE
[Core][nightly-test]increase volume size for pipeline ingestion

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

The pipelined ingestion tests failed [sporadically](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_CquQxkLGTagRw2ihVErPjFqV?command-history-section=command_history&user=usr_5CczuMLkCWrTs9mGb7m1rGBX) due to running out of disk spaces.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Is it always flaky? I thought it was quite stable before.  The issue might be due to scheduling changes which caused some unbalance.

**Comment by scv119** [comment]
Yup, it's quite stable until last Friday.

**Comment by rkooo567** [comment]
> Is it always flaky? I thought it was quite stable before. The issue might be due to scheduling changes which caused some unbalance.

+1 on this. Was there any suspicious PR merged between Th/Fri?

**Comment by jjyao** [comment]
Then probably we should try to bisect to find the offending PR instead of just increasing the volume size.

**Comment by scv119** [comment]
hmm the only PR changed related code is this one:
https://github.com/ray-project/ray/commit/d6dbf3b8bf294022f2be3e88a2169c1c9cc3169c

**Comment by rkooo567** [comment]
Hmm I guess this must be related then? Maybe this makes tasks not spread properly?

**Comment by jjyao** [comment]
Seems the test succeeded three times in a row. Maybe we should wait a bit to see if it's back to stable again.

**Pull request closed without merging**
