### PR TITLE
Revert "[Object Spilling] Implement level triggered logic to make str…

### PR DESCRIPTION
**Pull request by ericl**
…eaming shuffle work + additional cleanup (#12773)"

This reverts commit 9d939e66742556004a40f8898e7b80424be4965f.

@edoakes it seems this commit might be sometimes causing `run_object_manager_tests.sh` to time out.

### CODE REVIEW

**Comment by rkooo567** [comment]
Isn’t this test originally flaky? Is this pr causing it to be more flaky?

**Comment by rkooo567** [comment]
I will take a look at what’s the issue when I have some spare time

**Comment by ericl** [comment]
I'm not sure. Unfortunately I don't think flaky test tracker tracks it, but I saw it hang in several prs in the last couple hours

**Comment by ericl** [comment]
It is possible it is some other PR at fault

**Comment by rkooo567** [comment]
Hmm let me check if I can see the same issue from the past cis (I can spend some time tmrw) before this pr. I am sure this tests failed occasionally before that (tho i am not sure if it was the same issue as you are seeing)

**Comment by ericl** [comment]
Nevermind, it's https://github.com/ray-project/ray/pull/12894 at fault. Oddly enough, only a problem on the Linux build.

**Pull request closed without merging**
