### PR TITLE
combine workloads and use cases pages

### PR DESCRIPTION
**Pull request by angelinalg**
With the addition of the intro material for `ML workloads`, Eric requested that we combine it with the `Use Cases` page to reduce redundancy.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by angelinalg** [comment]
Hi @maxpumperla! Please review this draft PR. I'm afraid the filtering doesn't work on my local build. I'm sorry if I broke it somehow. Please advise on how to fix it. 

Also, I noticed that the filter is an "or" of all buttons that are selected. Is this the desired behavior? It seems a bit counter-intuitive as I expect it to be an "and" of all the buttons I select.

**Comment by maxpumperla** [comment]
hey @angelinalg, the build is fine. locally you have to host the docs on a server, e.g. with `python -m http.server`, so that the static tag file can be loaded by our `tags.js`. Check out one of our RTD builds in the "checks" to see what it looks like in action.

Cool, I think this looks really nice. My only concern now is that it's not really a gallery anymore, as it's too intertwined with other info. As a consequence, the tag system doesn't really work anymore. that's not a problem, we just have to clarify what our intentions are with this document. There's certainly a need for both ("which workflows are supported?" and "give me all your examples"). The question is if the combination makes sense.

Re: tags meaning OR and not AND, I think that depends. Within the same category, e.g. within ML frameworks, you certainly want e.g. PyTorch OR TensorFlow. Across categories, you're probably right. Let's clarify the above discussion first, and then we can fix the tag behaviour later.

**Comment by angelinalg** [comment]
@maxpumperla I agree that my additions make this page no longer strictly a gallery. I'm thinking it's more of a conceptual page with links to examples. Can you think of a better structure? @ericl mentioned that the content I added was the original intent of the Use Cases page. I also think combining them makes sense, but I do see your point that we should decide if it's a gallery or a conceptual page. Because we are low on high level content, I am leaning towards making it a conceptual page.  WDYT?

**Comment by ericl** [comment]
I think we may want a separate examples gallery. The original intent of the use cases page was to showcase the conceptual usage of Ray, including links to top blogs, talks, and examples.

Notably, we tried to limit the number of entries per use case to about 6, which excluded many more niche or less commonly seen examples. I think it makes sense for us to have a central tagged examples page if we want that to be browsable with tags, since otherwise you'd only be seeing the top 6 examples if that in each category.

**Comment by angelinalg** [comment]
Thanks for the feedback, @ericl and @maxpumperla. Removing the filtering tags clarifies that this is not a gallery and is a conceptual page with some related links. Does that sound good to you both? If so, I'll go ahead and implement the change.

**Comment by maxpumperla** [comment]
@angelinalg let me do the removal, we still want to keep the system around for that yet-to-come proper gallery

**Comment by angelinalg** [comment]
Sounds good, @maxpumperla. Thank you!

**Comment by angelinalg** [comment]
Talked to @maxpumperla and we agreed on a plan. He asked that I merge this PR and he will create a follow-up PR to remove the filtering tags.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Merged, thanks!

**Comment by matthewdeng** [comment]
@angelinalg it looks like this PR broke some of the links in [Overview](https://docs.ray.io/en/master/ray-overview/index.html#what-you-can-do-with-ray) page, but I'm not sure why this was ignored in linkcheck ([example from HEAD](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2586#0186b0a1-6f84-48d2-9535-bcdf2a3800ef))...

```
  | (ray-overview/index: line   27) -ignored- workloads.html#batch-inference-on-cpus-and-gpus
  | (ray-overview/index: line   28) -ignored- workloads.html#model-serving
  | (ray-overview/index: line   29) -ignored- workloads.html#parallel-training-of-many-models
  | (ray-overview/index: line   30) -ignored- workloads.html#distributed-training-of-large-models
  | (ray-overview/index: line   31) -ignored- workloads.html#parallel-hyperparameter-tuning-experiment
  | (ray-overview/index: line   32) -ignored- workloads.html#reinforcement-learning
  | (ray-overview/index: line   33) -ignored- workloads.html#ml-platform
```

**Comment by zcin** [comment]
Just confirmed these links are broken on the 2.3.1 release branch as well with https://github.com/ray-project/ray/pull/33001 merged in ([docs build](https://anyscale-ray--33017.com.readthedocs.build/en/33017/ray-overview/index.html) on head of release branch, [example of broken link](https://anyscale-ray--33017.com.readthedocs.build/en/33017/ray-overview/workloads.html#batch-inference-on-cpus-and-gpus)). Can someone help with pushing a fix for this? cc: @zhe-thoughts for awareness.

**Comment by zcin** [comment]
Looking at the linkcheck - why are so many docs links marked "ignored"? Is it possible other links are broken but we are unaware?

**Comment by matthewdeng** [comment]
@angelinalg could you make a fix for this particular issue?

@maxpumperla for the more general issue, do you know why these links are ignored? 😅 

@zcin for 2.3.1 (and in general) I think we should go ahead with disabling the Docker image builds when we have the desired commit we want to release, and make any additional doc fixes afterwards.

**Comment by angelinalg** [comment]
The broken links that I introduced are fixed and cherry-picked for 2.3.1: https://github.com/ray-project/ray/pull/33144

**Pull request merged**
