### PR TITLE
[Issue 2222] Provide better API method for dumping the task timeline …

### PR DESCRIPTION
**Pull request by surehb**
## What do these changes do?

Provide better API method for dumping the task timeline
## Related issue number
[2222](https://github.com/ray-project/ray/issues/2222)

### CODE REVIEW

**Comment by surehb** [comment]
@robertnishihara, @richardliaw , can you please approve it? Thanks!

**Comment by robertnishihara** [comment]
Hi @surehb, I've been doing some work recently on improving the timeline visualization (for the raylet code path) in #2306. One thing that I wanted to do was to have a single command for dumping the timeline as an html file, which could be loaded in a browser (by doing something similar to what you do in this PR). However, it seems to me that the HTML file that is dumped when you do this can't actually be loaded in a browser (it seems to only work when embedded in a Jupyter notebook). Is that your experience here? Or do you find that it can be opened in Chrome successfully?

**Comment by surehb** [comment]
@robertnishihara, I haven't tried that yet. Since this is just an interface chance, can we merge this in and do other fix inside the html context if need?

**Comment by robertnishihara** [comment]
Thanks @surehb, I was confused. I thought it was dumping an HTML but it's actually dumping a JSON, which should work. Can you fix the linting errors?

**Pull request closed without merging**
