### PR TITLE
[Dashboard][event] Basic event module

### LINKED ISSUE #16246: [Dashboard][event] Basic event module
- Collect events from log in event agent.
- Report the events from event agent to the event head.
- Provide an API to query events in event agent (for the new dashboard frontend).

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

### PR DESCRIPTION
**Pull request by fyrestone**
## Why are these changes needed?

The basic event module to collect events from all nodes. It provides a RESTful API for frontend to get events.

Limits: The dashboard does not persistence the event data.

proposal: https://docs.google.com/document/d/1I_0rcZmQHsjHrWi3UVSgxYcRDr8OEcDnenCdryMQwrM/edit#

## Related issue number

Closes https://github.com/ray-project/ray/issues/16246
https://github.com/ray-project/ray/pull/16283
https://github.com/ray-project/ray/pull/16676

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hey can we turn this off by default until we use it in our cpp code? (@scv119 and I are planning to use it soon)

**Comment by fyrestone** [comment]
> Hey can we turn this off by default until we use it in our cpp code? (@scv119 and I are planning to use it soon)

OK. I will disable the module by default.

**Comment by fyrestone** [comment]
@rkooo567 What happened to the Travis CI? There is no useful info in the CI log. The `test_actor_client_mode` and `test_object_spilling_2` are failed in windows-msvc CI. The `test_redeploy_scale_up` and `test_redeploy_multiple_replicas` are failed in the ray-builders-pr. There are too many failures in CI after I merged the latest master.

**Comment by fyrestone** [comment]
@rkooo567 @scv119 There are only flaky tests and Travis CI failed in the CI of this PR. Can you review again?

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
