### PR TITLE
[flakey] Deflakey `test_gcs_fault_tollerance.py` 

### LINKED ISSUE #24940: [Core][flakey-test] linux://python/ray/tests:test_gcs_fault_tolerance is flakey

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

There is a race condition where the failure message is sent but resubscription hasn't been established. In this case, we'll lose this message.

This PR fixes the test case only by making sure resubscription is done before killing the worker.

We are not going to fix this issue for the first version of GCS HA because:
1. Right now, only failed worker will be reported and it'll be used to eagerly kill the unnecessary workers. From correctness, it's ok.
2. worker/task support is not P0 for GCS HA (Ray Serve). Actor doesn't have this issue since the subscription for the actor is by actor id and raylet will fetch the actor status when resubscribing.

Things are not working:
- we won't kill workers which are not useful anymore. So for a very extreme case (the worker hangs), it'll have a resource leak.
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scv119 — APPROVED** [review]

**Comment by iycheng** [comment]
failure is not related

**Comment by rkooo567** [comment]
Hmm actually I think we should fix this for HA. Afaik, it is used for worker report right?

(1 )Basically we rely on worker failure reports raising a correct error message upon actor failures. https://github.com/ray-project/ray/pull/24468
(2) Worker info is used not just for reporting failures, but also reporting a new worker. (which is also needed for the above feature)
(3) IIUC, this code relies on the worker failure report, so I believe actor workload should be related to accurate report of worker failure report
```
        gcs_actor_manager_->OnWorkerDead(node_id,
                                         worker_id,
                                         worker_ip,
                                         worker_failure_data->exit_type(),
                                         creation_task_exception);
```

**Comment by iycheng** [comment]
@rkooo567 I don't mean we don't need to fix this. I only mean it's not a P0 and we should revisit it once we deliver all the P0 required features for ray 2.0.

**Comment by rkooo567** [comment]
Ah I see. I was confused with the actual RPC requests. It makes sense this is just for a subscription.

I still have some impression worker failure is closely related to actor schedules. Here's the scenario I can imagine, and please let me know if I am missing something! 

Looking at code, I think this can still cause some actor scheduler-related issues. For example, this worker failure report is used to detect owner failures, and if it is not reported properly, the scheduler won't detect owner failure properly (https://github.com/ray-project/ray/blob/841f7c81ff3c44d23a7eaea6376b8a266467a0af/src/ray/raylet/node_manager.cc#L375). I also remember @wuisawesome and I debugged issues scheduling behaves incorrectly when the owner detection is not handled properly. I forgot the exact symptoms, but this must be still related to actor schedules, which should be a part of Serve HA for 2.0?

**Comment by iycheng** [comment]
Offline sync result: in some cases, it's going to cause a leak: a worker owns an actor and the worker failed.

For ray serve it shouldn't happen that frequently. We are going to fix it after all p0s.

**Pull request merged**
