### PR TITLE
[tune] Fix error when restore checkpoint at tune.run()

### LINKED ISSUE #4714: [tune] Cannot restore checkpoint for experiment
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**: 0.7.0.dev2
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

Passing `restore=$HOME/exp/.../checkpoint-100` into `tune.run()`, the checkpoint will not be loaded and ray will start a brand new experiment.

### Source code / logs

In `tune.run()` function, an experiment are automatically initialized as:

```
        experiment = Experiment(
            name, run_or_experiment, stop, config, resources_per_trial,
            num_samples, local_dir, upload_dir, trial_name_creator, loggers,
            sync_function, checkpoint_freq, checkpoint_at_end, export_formats,
            max_failures, restore)
```

However, the arguments passed into the `Experiment.__init__()` have wrong order as:

```
    def __init__(self,
                 name,
                 run,
                 stop=None,
                 config=None,
                 resources_per_trial=None,
                 num_samples=1,
                 local_dir=None,
                 upload_dir=None,
                 trial_name_creator=None,
                 loggers=None,
                 sync_function=None,
                 checkpoint_freq=0,
                 checkpoint_at_end=False,
                 keep_checkpoints_num=None,
                 checkpoint_score_attr=None,
                 export_formats=None,
                 max_failures=3,
                 restore=None,
                 repeat=None,
                 trial_resources=None,
                 custom_loggers=None):
```

You can see that this is because the introduction of two new arguments:        

```
keep_checkpoints_num=None,
checkpoint_score_attr=None,
```

I believe this is caused by the #4490 . I will try to fix this problem.

### PR DESCRIPTION
**Pull request by pengzhenghao**
## What do these changes do?

Fix a problem causing checkpoint restoring fails when using `tune.run(..., restore='ckpt-path')`.

This issue is brought by PR #4490 

## Related issue number

Closes #4714 

## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by PengZhenghao** [comment]
```
======================================================================
FAIL: testSyncFilter (__main__.TestPolicyEvaluator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ray/python/ray/rllib/tests/test_policy_evaluator.py", line 427, in testSyncFilter
    self.assertLessEqual(obs_f.buffer.n, 20)
AssertionError: 22 not less than or equal to 20

----------------------------------------------------------------------
Ran 20 tests in 37.465s
```

What is this? I think my modification is trivial and should not cause error.

**Comment by ericl** [comment]
jenkins retest this please

**Comment by richardliaw** [comment]
@PengZhenghao would you be willing to add a small unit test for this?

**Comment by PengZhenghao** [comment]
I have added a some sort of "black box" test.

**Comment by richardliaw** [comment]
Somehow this diff is messed up ...

**Review by richardliaw — COMMENTED** [review]
Left some comments - can you look into the diff? some things i think aren't supposed to be there.

This can be approved after the bottom two comments are addressed.

**Comment by PengZhenghao** [comment]
Sorry for messing up everything. I will try a new PR to make everything clear...

**Pull request closed without merging**
