### PR TITLE
[RLlib] Fix FeatureImportance OfflineEvaluator construction. (#29222)

### PR DESCRIPTION
**Pull request by gjoliver**
Signed-off-by: Jun Gong <jungong@anyscale.com>

## Why are these changes needed?

Cherry pick a fix for the broken feature important feature.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by avnishn — APPROVED** [review]

**Comment by rickyyx** [comment]
Looks like there are quite a few tests failure - could we rebase or make sure tests are ok?

**Comment by rickyyx** [comment]
Does this PR try to fix any tests?

**Comment by gjoliver** [comment]
we don't have tests to capture it. I have a TODO for kourosh to add one after he comes back.
I will make sure the tests pass.

**Comment by gjoliver** [comment]
> Hey @gjoliver could you help double check the current test failures are fine? If so , I will merge this. Thanks!

yes.
apex_ddpg is flaky, I looked and couldn't find any errors. that's a mystery for another day.
backward_compat is being fixed by a PR that I will cherry pick now.
the tune test is definitely not relevant.
thanks.

**Comment by rickyyx** [comment]
Sounds good! I am opening an issue for apex_ddpg to track it separately then.

**Pull request merged**
