### PR TITLE
Revert "Revert "[Core] Implement long polling-based pubsub to reduce …

### PR DESCRIPTION
**Pull request by rkooo567**
…number of WaitForObjectEviction requests in flight. (#14638)" (#14905)"

This reverts commit ec3cfef88313c2f4cb023023fbf41c51887235d2.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @ericl I think the problem was from other PR (The util worker bug fix). If you approve the PR I will merge it after making sure it is safe to merge it.

**Comment by ericl** [comment]
I don't see that PR as a proximate cause in the dashboard, how did you conclude this?

**Comment by rkooo567** [comment]
Screen Shot 2021-03-24 at 1 18 06 PM

This was my reasoning (I induced based on the error message).

**Comment by ericl** [comment]
I see, that doesn't explain the always red status though.

**Comment by rkooo567** [comment]
So all yellow builds fail due to UTIL worker failure before the PR, and after that PR it has new flaky errors (and I think the root cause is the util worker is considered as restore workers, which cause the local object manager to send restoration requests to them).

**Comment by rkooo567** [comment]
Oh the red status was due to Stephanie's PR right?

**Comment by rkooo567** [comment]
If you are talking about the last red after reverting her PR, I will make sure to wait enough to conclude this PR was not the problem (So I will wait enough until reverting Util worker will resolve the issue).

**Comment by rkooo567** [comment]
@ericl I am fairly confident the object spilling was flaky due to the util worker error.

**Comment by rkooo567** [comment]
If you are still concerned, I can wait until this PR is merged; https://github.com/ray-project/ray/pull/14925

**Comment by ericl** [comment]
Can you take a look at any failing or flaky test and make sure it isn't related? I see test ref counting failed 3x!

**Comment by rkooo567** [comment]
@ericl The current CI failures seem unrelated. I also noticed the ref counting test becoming more flaky in the dashboard, but all the failures look the same as the previous flaky cases, so it is a little hard for me to figure out if that was related failure or just a coincidence. 

Would you like me to just keep running the test_reference_counting and see if it is flaky (if so, what's the best way to detect it)? I feel like trying to detect flaky tests when it doesn't introduce new failures slows down PR merge a lot (and obviously the failure is not reproducible). What about I just merge it and fix the flaky test next sprint if this actually makes things more flaky?

**Comment by ericl** [comment]
Can you identify the exact test that's flaky in test ref counting?

**Comment by rkooo567** [comment]
@ericl will do and ping you after that.

**Comment by rkooo567** [comment]
cc @ericl All of flaky tests should have been addressed.

**Review by ericl — APPROVED** [review]

**Pull request merged**
