### PR TITLE
[RLlib] Added CRR implementation

### PR DESCRIPTION
**Pull request by kouroshHakha**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by gjoliver — APPROVED** [review]
cool PR, nice job!
also, it takes 17 files to add a new algorithm today huh :)

**Comment by kouroshHakha** [comment]
> cool PR, nice job! also, it takes 17 files to add a new algorithm today huh :)

I guess :)

**Comment by kouroshHakha** [comment]
Do we want to move the core files (i.e `algorithm.py`, `algorithm_config.py`, `callbacks.py`, `registry.py`, and `mock.py`) to rllib.core or keep them under algorithms?

**Comment by sven1977** [comment]
Awesome, will merge once all tests pass ...

**Pull request merged**
