### PR TITLE
[ci] add optional network in test containers

### PR DESCRIPTION
**Pull request by aslonnie**
this allows test container to use host network (or any network)

### CODE REVIEW

**Comment by can-anyscale** [comment]
Will this cause issues when multiple docker runs in parallel?

**Comment by aslonnie** [comment]
> Will this cause issues when multiple docker runs in parallel?

yes, it will in cases where they all want to start ray clusters. they will run into port conflicts.

this is required for running the kuberay operator test, otherwise the test cannot connect to the kind cluster.

**Comment by aslonnie** [comment]
it is not an inherent conflict though. docker has no problem with running multiple containers on the same host network. it is just that ray cannot run on the same localhost network as multiple ray clusters.

**Review by can-anyscale — APPROVED** [review]
Let's do this and leave it up to the users to know what they are doing

**Comment by aslonnie** [comment]
> leave it up to the users to know what they are doing

I think the only users are you and maybe me..

**Pull request merged**
