### PR TITLE
[autoscaler] Migrate to Pathlib from os.path

### LINKED ISSUE #11633: Use Pathlib instead of strings in Autoscaler
### Describe your feature request
It would be great to use Pathlib `Paths` instead `os.path...`

For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!

### PR DESCRIPTION
**Pull request by firebolt55439**
## Why are these changes needed?

`Pathlib` is a superior, object-oriented replacement for `os.path` and its various functions. All functions taking in paths in recent versions of Python (3.6+) allow taking `os.Pathlike` objects instead, which `Path` and `PurePath` objects fall under, so there should not be any compatibility issues.

## Related issue number

Closes #11633 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Thanks for this PR!

@ray-project/ray-autoscaler, can anyone on the autoscaler team take a look at this?

**Comment by simon-mo** [comment]
Any update? Were you able to run some of these tests locally? Happy to help

**Comment by firebolt55439** [comment]
Apologies, have been out of town for a bit — should see some updates real soon.

Thanks,
-Sumer

**Comment by firebolt55439** [comment]
Tracked down where my misconception was after reviewing build logs — was incorrectly using the `Path.name` or `PurePath.name` attribute, which is equivalent to `os.path.basename`, rather than the `str(...)` or `.__str__()` intended for string conversion.

**Comment by firebolt55439** [comment]
Grrr, I'll take another look after my final exams this week.

**Comment by firebolt55439** [comment]
Dang, I just don't get it. Must be missing something obvious for the Python tests to fail but the artifacts aren't helping me pin down the cause of the problem. Any ideas?

**Comment by wuisawesome** [comment]
@firebolt55439 are you able to repro these test failures locally?

**Comment by firebolt55439** [comment]
I haven’t been able to yet, no. I’ll keep trying (I think my $PATH has some issues).

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
