### PR TITLE
[Core]Add api for String type get/set in kv manager

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
We already have methods to get/put values as wrapper of `HGET/HSET`. We need simple String type GET/SET and this time we add them.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
Re: autoscaler backwards compatibility -- it looks (at least after very brief review) that these changes are strictly API additions that shouldn't break anything.

**Comment by wuisawesome** [comment]
Yup, this looks good from an API perspective. 

@iycheng do you mind reviewing the code?

**Comment by WangTaoTheTonic** [comment]
@iycheng  Hi Yi, do you have bandwidth to take a review?

**Comment by iycheng** [comment]
Overall it's straightforward. But I have one question here: why do we need two types of put/get for string/blob? Should just one put/get for blob (the existing one) just work? Since we plan to remove Redis, we probably don't want to add extra API for GET/PUT if we treat the string as blob works. @WangTaoTheTonic

**Comment by WangTaoTheTonic** [comment]
@iycheng Yeah I makes sense that if we reuse existing blob put/get, but that means we need to change logics of setting/getting with string type to blob style.
Now I've found `session_dir` is getting/setting with string type, and that's why I need this extra API. I hate to add new API too so let me check if it's ok to change the `session_dir` value to blob type.

**Comment by iycheng** [comment]
> @iycheng Yeah I makes sense that if we reuse existing blob put/get, but that means we need to change logics of setting/getting with string type to blob style.
> Now I've found `session_dir` is getting/setting with string type, and that's why I need this extra API. I hate to add new API too so let me check if it's ok to change the `session_dir` value to blob type.

I remember we also use internal kv to store the string value. But after getting the value, we'll convert it to string from bytes. Do you think pickle/unpickle for py struct should work here?

**Comment by WangTaoTheTonic** [comment]
> > @iycheng Yeah I makes sense that if we reuse existing blob put/get, but that means we need to change logics of setting/getting with string type to blob style.
> > Now I've found `session_dir` is getting/setting with string type, and that's why I need this extra API. I hate to add new API too so let me check if it's ok to change the `session_dir` value to blob type.
> 
> I remember we also use internal kv to store the string value. But after getting the value, we'll convert it to string from bytes. Do you think pickle/unpickle for py struct should work here?

I changed the storage type of `session_dir` to hash style so it can be accessed via kv manager. This is enough for us to remove redis dependency in Java lang. Pleas take a review.
Removing redis dependency in Python lang need more work to do.

**Comment by WangTaoTheTonic** [comment]
https://github.com/ray-project/ray/pull/16958 can be a substitution, so I'm closing this. @iycheng

**Pull request closed without merging**
