### PR TITLE
[WIP] Disable profile of raylet

### PR DESCRIPTION
**Pull request by jovany-wang**
## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@jovany-wang I don't think we should provide an option to disable profiling. There is some discussion of this in https://github.com/ray-project/ray/pull/4522. Can you clarify why you want to do this? If the issue is performance, we should make the profiling faster.

**Comment by jovany-wang** [comment]
@robertnishihara  The issue is not performance to me.

When I run a long-running app on Ray cluster, the GCS will run out of memory because of the huge `PROFILE` table. It's unnecessary to enable profile in a prod-env to me.

**Comment by robertnishihara** [comment]
@jovany-wang I see. We currently solve this by doing LRU eviction from the GCS (which admittedly is an imperfect solution). This is a problem beyond just the profiling table. We also need a solution for the object table, task table, and everything else.

One possibility is to try to have a generic solution that works for everything (e.g., LRU eviction or maybe something better). Another possibility is to have different solutions for each separate table.

But I can imagine cases where it'd be valuable to have profiling information for production workloads.

There may be other solutions that make better tradeoffs. For example, we can create some Redis shards that only store non-critical information (like profiling info). We can do LRU from only those shards. That way, users will always have access to the profiling info, and profiling info won't cause us to run out of memory, and that will be the case both for production and non-production workloads. In contrast, the solution of disabling profiling could result in a situation where non-production workloads can run out of memory, and production workloads don't have access to profiling info.

**Comment by jovany-wang** [comment]
In our prod-env, there is no any sharding redis instance. We make the primary as a sharding. It means that one redis instance which is both a primary and a sharding.

So that we don't enable LRU cache.

I believe we should have a perfect solution in the future(I don't know the timeline of this), but I also think there is no any matter even if we have such `enable_profile` flag which is `on` by default.

**Pull request closed without merging**
