### PR TITLE
[Autoscaler] Allow GPU upscaling for non-GPU workloads, with lowest priority

### LINKED ISSUE #20476: [Bug] Autoscaler  doesn't scale CPU-only workloads to workers with GPU
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Clusters where *all* nodes have a GPU fail to autoscale on CPU-only workloads.
```
The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0} ,...
```

Changing the resource definition of the node type (leaving everything else intact) allows the cluster to autoscale.

I'm guessing that this _may_, in fact, be the intended behavior, as a cost-saving "feature".
In which case, the right "fix" would be to define node types both *with* and *without* GPU.

### Versions / Dependencies

Ray 1.8.0
Python 3.9

### Reproduction script

N/A

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

Closes https://github.com/ray-project/ray/issues/20476:
Instead of preventing GPU upscaling due to non-GPU tasks, **prefer non-GPU nodes** by assigning low utilization score to the GPU nodes.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — COMMENTED** [review]
I'm really not a fan of making this logic more and more complicated here. Could we achieve the same result or better by just making gpu nodes lower in the utilization scorer if the resource demand doesn't include gpu requests?

**Comment by DmitriGekhtman** [comment]
> I'm really not a fan of making this logic more and more complicated here. Could we achieve the same result or better by just making gpu nodes lower in the utilization scorer if the resource demand doesn't include gpu requests?

Brilliant, yes.

**Comment by DmitriGekhtman** [comment]
Actually, to retain the relative ranking, will implement this by pre-pending an extra field to the priority score.

**Comment by DmitriGekhtman** [comment]
> Actually, to retain the relative ranking, will implement this by pre-pending an extra field to the priority score.

Implemented that.

**Comment by DmitriGekhtman** [comment]
Can be reviewed again.

**Review by wuisawesome — APPROVED** [review]
beautiful

**Pull request merged**
