### PR TITLE
Automatically set CUDA_VISIBLE_DEVICES when worker gets task.

### PR DESCRIPTION
**Pull request by robertnishihara**
This addresses #975.

Should update the documentation before merging this.

### CODE REVIEW

**Comment by ericl** [comment]
Nice, I was going to do this in RLlib agents automatically but I think this is cleaner. Just a couple questions:
- Does this apply to actor tasks?
- Is it intentional to prohibit GPU usage for tasks that don't specify num_gpus?

**Comment by robertnishihara** [comment]
Yes, I believe that prohibiting GPU usage for tasks that don't specify `num_gpus` is intentional.

Note that this does not prevent the driver from using GPUs. Though if the driver does use GPUs that could conflict with tasks using GPUs.

**Comment by robertnishihara** [comment]
This can be merged once the tests pass.

**Review by pcmoritz — APPROVED** [review]
+1

**Pull request merged**
