### PR TITLE
[autoscaler] Support cache_stopped_nodes on Azure

### PR DESCRIPTION
**Pull request by mraheja**
## Why are these changes needed?

Ray's cluster launcher API uses a cache_stopped_nodes flag to support stopping and reusing VMs, however, this is currently not implemented for Azure. This PR implements the cache_stopped_nodes flag for Azure.

## Related issue number

N/A 

## End-to-end Test

```
- ray up azure_cluster.yaml
- ray down azure_cluster.yaml  # Check in Azure UI the node is not terminated, but stopped.
- ray up azure_cluster.yaml  # Check in Azure UI the same node is restarted - i.e., reused.
```

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by concretevitamin** [comment]
cc @suquark

**Comment by suquark** [comment]
@mraheja Feel free to assign a PR review to me when you feel it's ready.

**Comment by mraheja** [comment]
Hey @suquark, sorry I didn't see your comment earlier, but I formatted the code properly and it should be ready to review. It looks like you've already self-assigned this so let me know if there is anything else you want me to do.

**Review by suquark — APPROVED** [review]
Thanks! LGTM

**Comment by suquark** [comment]
The current lint issues may due to CI and not related to this PR. I'll merge it.

**Comment by mraheja** [comment]
@suquark thank you, i appreciate it!

**Pull request merged**
