### PR TITLE
Unpin prometheus_client dependency

### LINKED ISSUE #31104: [Dashboard] Prometheus client version is pinned to < 0.14.0
### What happened + What you expected to happen

The prometheus client version is pinned here https://github.com/ray-project/ray/blob/eab0480ce2afdac3d6c1a32a3ccda1f94bef8e92/python/setup.py#L244

This prevents Ray dashboard being installed with newer versions of prometheus. The pin should be removed.

### Versions / Dependencies

All recent Ray versions

### Reproduction script

None

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
The pin is no longer necessary after #23766

## Related issue number
fixes #31104 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
consider merging the latest master? Also is it tested / verified (from that PR)?

**Review by edoakes — COMMENTED** [review]
Always happy to unpin something :) please make sure it's tested/verified as @rkooo567 asked before merging

**Review by edoakes — APPROVED** [review]

**Comment by alanwguo** [comment]
> consider merging the latest master? Also is it tested / verified (from that PR)?

Yes, I tested locally.

**Review by ericl — APPROVED** [review]

**Comment by JoshKarpel** [comment]
Hi, just wanted to check in on this. Presumably it will go out in the next release - is there an ETA for that? Hoping to use some new features from the latest release of `prometheus_client` in my code. Thanks!

**Comment by rkooo567** [comment]
ETA is the mid feb!

**Comment by JoshKarpel** [comment]
Awesome, thank you!

**Pull request merged**
