### PR TITLE
[docs] Fix mock objects in Ray Core docs

### LINKED ISSUE #20892: [doc] API doc show things like "Mock name='mock.ObjectRef' id='140639907666512'"
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

https://docs.ray.io/en/latest/package-ref.html#ray-wait

shows

ray.wait(object_refs: List[<Mock name='mock.ObjectRef' id='140639907666512'>], *, num_returns: int = 1, timeout: Optional[float] = None, fetch_local: bool = True) → Tuple[List[<Mock name=’mock.ObjectRef’ id=’140639907666512’>], List[<Mock name=’mock.ObjectRef’ id=’140639907666512’>]][source]

It seems to have been this way since 1.6

### Versions / Dependencies

1.6+

### Reproduction script

https://docs.ray.io/en/latest/package-ref.html#ray-wait

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

Our API references are currently showing mock objects for some of our APIs -- this PR fixes them for the Ray Core API reference.

## Related issue number

Closes https://github.com/ray-project/ray/issues/20892

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by maxpumperla — APPROVED** [review]
Thank you, this is great!

There should be a couple more of these, or were those all we had?

**Comment by pcmoritz** [comment]
These are all the ones from Ray Core from our C extensions. There are a few more in the libraries that probably need to be fixed differently, I'm planning to have a look at them as well :)

**Comment by maxpumperla** [comment]
@pcmoritz makes sense. yeah, not that you say it, most mock issues came from `ObjectRef`, it seems.

**Review by ericl — APPROVED** [review]
lgtm. Is there any way we can lint these automatically?

**Comment by pcmoritz** [comment]
Yeah, let me look at that -- we might be able to grep the generated html files for "mock." for example or maybe there is a better way :)

**Comment by pcmoritz** [comment]
Ok, this is not fixing it remotely, only on my laptop -- what I think happened here is on my laptop I have full Ray installed, and replacing the objects with strings made it to use those "real" objects in the docs instead of the mocked ones.

I'll dig into it a bit more.

**Pull request merged**
