### PR TITLE
[core][state] State API scale losing data

### PR DESCRIPTION
**Pull request by rickyyx**
Signed-off-by: rickyyx <rickyx@anyscale.com>

## Why are these changes needed?

We are dropping data at 10K as default, changing the buffer size larger right now before we figure out a way to store bursty task submissions. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
Nice, let's merge. Can you kick off a run now so we can catch any failure as early as possible?

**Review by cadedaniel — APPROVED** [review]

**Comment by rickyyx** [comment]
https://buildkite.com/ray-project/release-tests-pr/builds/28015#0186394b-8a18-4231-b0b1-141e4a8fabb8

**Comment by cadedaniel** [comment]
Great :) thanks Ricky!

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
are we going to cherry pick this?

**Comment by cadedaniel** [comment]
I will create CP

**Pull request merged**
