### PR TITLE
First pass at scaling down request resources.

### LINKED ISSUE #19785: [Bug] autoscaler doesn't shutdown workers after calling request_resources
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

*What happens*: After calling `request_resources` an appropriate number of worker nodes are spun up (expected), however, they never scale down, even if they are unused. 

I observe the following in monitor.log even after reaching 3k CPU:
```
Demands:
 {'CPU': 1}: 3000+ from request_resources()
```

*Expectation*:  Unused workers are shut down.

The old behaviour (ray 1.0.0 and possibly later) used to clear the resource request when the running resources exceeded the request amount, so that the request only lasts until the cluster has scaled up.

### Versions / Dependencies

`ray==1.6.0`

### Reproduction script

Boot a cluster, call `request_resources(n)` where n is greater than the head node resources, wait for the workers to boot, observe that the workers are never shutdown, even after the idle timeout elapses.

### Anything else

I believe this functionality was removed as part of this PR: https://github.com/ray-project/ray/pull/11802/files#diff-32ec34dc41fb43d2614e8bc5a857aac8f9bdca6a985df52fc7f207d62e5cb162L161-L163  (search for `if len(nodes) >= target_workers` in autoscaler.py)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by SlowShip**
PR to fix [#19785]( https://github.com/ray-project/ray/issues/19785) By adding expire_when_satisfied flag to request_resources

Notable changes: 
* Moved AutoscalerSummary into it's own file to avoid circular reference when importing autoscaler commands from the autoscaler
* Handled the flag in the autoscaler when requested resources are met.

## Why are these changes needed?

We regularly run tasks where we know our expected resource requirements at launch, so call request_resources with the required number of cpus. The number of machines doesn't scale back down as our tasks are finishing, and just sit idle. This is costing more in aws hosting costs than necessary. 

## Related issue number

Closes [#19785]( https://github.com/ray-project/ray/issues/19785)

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/. 
^(are the doc strings enough?)
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
   - [x]  Tested manually on a cluster

### CODE REVIEW

**Comment by SlowShip** [comment]
@DmitriGekhtman was asked to bring this to your attention by @mattearllongshot

**Comment by DmitriGekhtman** [comment]
cc @wuisawesome, see discussion at the linked issue https://github.com/ray-project/ray/issues/19785

**Comment by DmitriGekhtman** [comment]
Thanks for the PR. These changes look reasonable, but I do want to learn more about your use-case to see if current APIs can make it work. Going to carry on discussion on the issue https://github.com/ray-project/ray/issues/19785.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by SlowShip** [comment]
Closing. See discussion on [#19785](https://github.com/ray-project/ray/issues/19785), we merged another PR to solve our problem.

**Pull request closed without merging**
