### PR TITLE
[RLlib] Add lr_schedule support to SimpleQ and PG.

### LINKED ISSUE #28266: [RLlib] SimpleQ ignores lr_schedule
### What happened + What you expected to happen

The SimpleQ algorithm accepts `lr_schedule` as a key in its configuration, but it appears that it doesn't do anything with it. Given that the key is accepted in the config, I would expect that it would vary the learning rate according to the schedule set there. Or if this is not meant to be supported, then I would expect the algorithm to fail or at least print a warning when it's given a `lr_schedule` in its configuration.

DQN and other algorithms based on SimpleQ do seem to support it. For instance, in `ray/rllib/algorithm/dqn/dqn_tf_policy.py:setup_mid_mixins()` this is implemented for DQN, but `simple_q_tf_policy.py` doesn't implement anything similar. 

On a related note, it seems basic PG also doesn't support a learning rate schedule. There it's at least not in the default config and PG will fail if given a `lr_schedule`. Is there a particular reason why PG (and indeed SimpleQ) should not support a learning rate schedule?

### Versions / Dependencies

ray==2.0.0

### Reproduction script

```
# Configure.
from ray.rllib.algorithms.simple_q.simple_q import SimpleQConfig

config = SimpleQConfig().environment(env="Taxi-v3")

# Set lr_schedule
config.lr_schedule = [[0, 0.0003], [10, 0.0001], [100, 0.00003]]

# Build.
algo = config.build()

# Train. lr_schedule will be ignored.
while True:
    print(algo.train())
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by mgerstgrasser**
## Why are these changes needed?

SimpleQ and PG currently don't support a learning rate schedule. SimpleQ does list a `lr_schedule` key in its default config, but will simply ignore it, which could lead to user confusion. PG does not accept a `lr_schedule` key, but there is no reason why it shouldn't support a learning rate schedule.

## Related issue number

Closes #28266 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for this PR! I'm adding some testing and minor stuff and then we can have a review and merge :)

**Comment by mgerstgrasser** [comment]
> Thanks for this PR! I'm adding some testing and minor stuff and then we can have a review and merge :)

Oh thank you! Anything I can do to help?

**Review by ArturNiederfahrenhorst — APPROVED** [review]

**Comment by ArturNiederfahrenhorst** [comment]
Not for now, thanks! @sven1977  will have to review next.

**Comment by sven1977** [comment]
Hey @mgerstgrasser , thanks for the PR! This looks great.
One test case seems to be failing: rllib/tests/test_nested_action_spaces.py

I'm getting this error here:

image

**Comment by mgerstgrasser** [comment]
> Hey @mgerstgrasser , thanks for the PR! This looks great. One test case seems to be failing: rllib/tests/test_nested_action_spaces.py
> 
> I'm getting this error here:
> 
> image

@sven1977 Should be fixed now, thanks for flagging this. Issue was in the test - it's passing a PG config into BC. I'm just removing the `lr_schedule` from the config now in that test.

**Pull request merged**
