### PR TITLE
[WIP] [GCS] refactor gcs_resource_scheduler

### PR DESCRIPTION
**Pull request by wumuzi520**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jon-chuang** [comment]
What is the purpose of this PR relative to https://github.com/ray-project/ray/pull/22762?

**Comment by rkooo567** [comment]
I don't think we need this change? I believe @scv119 will unify the cluster_resource_scheduler for both gcs and raylet

**Comment by wumuzi520** [comment]
> I don't think we need this change? I believe @scv119 will unify the cluster_resource_scheduler for both gcs and raylet

Yes, I discussed with @scv119 offline. The resource data structure of GCS needs to be refactor first, and then gcs_resource_scheduler and cluster_resource_scheduler can be unified.

Any way, I will close this PR, because another PR will be pushed soon, the new PR will refactor all resource data structure.
From `ResourceSet` to `ResourceRequest`
From `SchedulingResources` to `Node`

**Comment by wumuzi520** [comment]
> 

No, the goal of this PR is to refactor resource data structure in GCS.

**Comment by rkooo567** [comment]
Ah I see. It makes sense!

**Pull request closed without merging**
