### PR TITLE
[Doc] Remove Ray Summit 2023 banners

### LINKED ISSUE #39499: [docs infra] Take down Ray Summit banners in Ray docs and repo
### Description

This is a reminder to remove the banners after registration closes on Sep 19th, per Lance.

### Link

_No response_

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR removes the Ray Summit 2023 banner ads in `README.md` and the docs.

## Related issue number

Closes https://github.com/ray-project/ray/issues/39499.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by angelinalg — APPROVED** [review]
Thank you for being on top of this, @peytondmurray !

**Comment by cadedaniel** [comment]
seems pretty unrelated though..

**Comment by peytondmurray** [comment]
Looking into this, I can't even run the tests locally on `master`:

```
ray/python/ray $ pytest
Test session starts (platform: linux, Python 3.10.8, pytest 7.0.1, pytest-sugar 0.9.5)
rootdir: /home/pdmurray/Desktop/workspace/ray, configfile: pytest.ini
plugins: shutil-1.7.0, docker-tools-3.1.3, sugar-0.9.5, lazy-fixture-0.6.3, asyncio-0.16.0, typeguard-2.13.3, virtualenv-1.7.0, timeout-2.1.0, rerunfailures-10.2, anyio-3.6.2, forked-1.4.0
timeout: 180.0s
timeout method: signal
timeout func_only: False
collecting ... 
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR collecting test session ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
/home/pdmurray/.pyenv/versions/3.10.8/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/home/pdmurray/.pyenv/versions/3.10.8/envs/ray/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
util/collective/tests/conftest.py:6: in <module>
    from ray.util.collective.collective_group.nccl_collective_group import (
util/collective/collective_group/nccl_collective_group.py:6: in <module>
    import cupy
E   ModuleNotFoundError: No module named 'cupy'
2023-09-20 13:52:33,637	WARNING collective.py:20 -- NCCL seems unavailable. Please install Cupy following the guide at: https://docs.cupy.dev/en/stable/install.html.

====================================================================================================================================================================================================== short test summary info =======================================================================================================================================================================================================
FAILED ../.. - ModuleNotFoundError: No module named 'cupy'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Results (5.80s):
```

**Comment by peytondmurray** [comment]
Looks like a potential issue with the `gpustat` dependency?

```


The last 20 lines of /tmp/ray/session_2023-09-20_16-22-22_034480_2554/logs/dashboard.log (it contains the error message from the dashboard):
--


    __version__ : str = version : str = '1.1.1'
```

**Comment by cadedaniel** [comment]
Yeah, don't think it's related to your PR

**Pull request merged**
