### PR TITLE
[runtime_env] [CI] Use `emoji` instead of `requests` to speed up pip install in `test_runtime_env_complicated.py`

### LINKED ISSUE #30565: [CI][serve] `linux://python/ray/tests:test_runtime_env_complicated` is failing/flaky on master and 2.2 branch.
- 988f61c9f32e244d4028843cea10c75a6fa331f7 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1214#01849ca8-e84d-4cf3-8965-c525575d39fc)
- 988f61c9f32e244d4028843cea10c75a6fa331f7 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1214#01849ca8-e850-443b-827a-914577ed7e1a)
- 520fe92cd2dc1d715442dc889d59fdffafd3b1c7 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1213#01849ca3-a454-467b-a648-f21a1f4e627f)
- 29b8640cced93733e5346bd47fae18dd209b6940 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1211#01849c90-5525-45b4-b836-b8e4d7f9b8c5)
- 29b8640cced93733e5346bd47fae18dd209b6940 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1211#01849cb9-0778-4517-a60e-e79e4e397f6b)
- 29b8640cced93733e5346bd47fae18dd209b6940 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1211#01849cb7-36a9-4e71-9d9e-271ef9794b4f)
- 00d43d39f58f2de7bb7cd963450f7a763b928d10 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1210#01849cae-21c6-4934-8d54-92514d55f1f2)
- f9092dc55e662db00309c4345f744d399a00b9b9 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1209#01849c61-0696-4fd9-9555-6b73d12cde74)
- acff8b6fa615bfe6463fd76660b14ef2bbafda42 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1207#01849c48-9a08-4dfe-9101-cbe6e76f0a10)
- 4671cbf0bf9c2757c5ce267b7db8e6177f66d880 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1206#01849c45-07b6-4f99-a05c-7fafc094606a)
- 4671cbf0bf9c2757c5ce267b7db8e6177f66d880 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1206#01849caf-f9dc-48e7-b8d2-4a482465a61f)
- ba18004dc020a9d85526be599baf519d92bd0e37 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1205#01849c45-0a8f-4aca-a536-28b4e707a60c)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849c39-8466-46cf-b392-60ded7af6bb4)
- b8b32f3e1b4f878ab784cc331aa595fea483f8b5 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1200#01849c39-8608-4d35-8a1d-b5d435e45142)
- 3ea03183fbbacd0f538cf6ee333ae4d475915cbf FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1199#01849c02-99e0-4fc3-aa7b-b6ac7c76aa6e)
- 5f54406c1c271117872061c90a5651834d6b2fb5 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1197#01849bd6-0917-4d11-b727-f513497e6921)
- 26318068fe7fa153bf09dd8cee7b3a0b092883b7 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1122#018486d3-e28e-4ac2-8a42-21c25a04aba8)
- 64131d6dece417f78d0a947166a10e3848172f90 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1121#01848730-9a51-4290-a67d-97ffa6d242e7)
- 973a6eecafaa8722fc9cd5bdeae671b67648dfd4 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1119#018486b4-5fb5-4f77-a793-c50869422ddb)
- 87b821cc7567f284afbe0420ae152b488a352086 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1116#01848617-cba7-42ed-8058-aaae69c1eae4)
- ab60fa496453cadba051a036d27fd9d640b4c093 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1115#018485e1-df17-43d5-82cb-98864cf18b05)
- d59f189540b14269f49d976ba60e97b804f011ba FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1114#01848546-05ba-46b2-b7e9-e19d20af0864)
- c51b0c9a5664e5c6df3d92f9093b56e61b48f514 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1113#0184850c-1135-4776-9bca-c472f4eb4113)
- b0efdb8d9645add54f51aa18cbcf1530dab82791 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1112#01848458-3783-488b-8d9b-fc6c790978f6)
- 177cb44febe9056dc8465577bb34ad5192eb3f47 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1111#0184844d-b5f6-45ab-bbfa-459dfb8f57e7)
- c7115135ea131b29bd6ff3d32e4f90297e5e770e FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1110#01848416-041e-4fc4-87cd-eabbe113c11b)
- aa49c7a01b0877e6305c8c1423aded4abaf6f5d5 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1109#01848406-dbae-49b7-abdf-9f4e31ab52c7)
- 326da4664da68b184484a8b317c73dd0cb168f23 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1108#01848400-d560-491f-b867-b17c07752429)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_runtime_env_complicated-END
....

### PR DESCRIPTION
**Pull request by architkulkarni**
Signed-off-by: Archit Kulkarni <architkulkarni@users.noreply.github.com>

## Why are these changes needed?
To test out the runtime_env `conda` functionality, we install Ray's dependencies in the conda environment.

To test whether the correct environment has been activated, we also installed `requests==2.2.0` in one environment and `requests==2.3.0` in another environment.  The way we do this is to append `requests==2.2.0` to the bottom of a `requirements.txt` file which contains the other Ray dependencies, and call `pip install -r requirements.txt` inside the activated conda environment.

Due to some unknown change somewhere in the dependency tree, the `pip install` command recently started to take 20+ minutes due to [backtracking](https://pip.pypa.io/en/stable/topics/dependency-resolution/#backtracking), timing out the test.  Removing the line `requests==2.2.0` fixes this.

So the reason is likely that `requests` has too many dependencies or things that depend on it, and on top of that `2.2.0` is probably too old of a version. 

The fix is to replace it with the package `emoji` which likely has fewer dependency relationships with Ray's dependencies.

## Related issue number
Closes #30565 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
How about just https://pypi.org/project/pip-install-test/#history?

**Comment by architkulkarni** [comment]
@simon-mo Good question, I had tried that but `pip-install-test.__version__` doesn't seem to work, and I didn't know a workaround

**Comment by simon-mo** [comment]
https://stackoverflow.com/questions/3524168/how-do-i-get-a-python-modules-version-number-through-code

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
up to you. `emoji` is fine as well.

**Review by sihanwang41 — APPROVED** [review]

**Comment by architkulkarni** [comment]
`test_cli` flaky on master and unrelated
`rllib:learning_tests_stateless_cartpole_r2d2` flaky on master and unrelated

**Comment by architkulkarni** [comment]
> https://stackoverflow.com/questions/3524168/how-do-i-get-a-python-modules-version-number-through-code

Nice, that works.  Since this is time sensitive I'll stick with emoji for now (we also use `pip-install-test` in a bunch of other runtime env tests, so I don't want there to be any unforeseen interactions)

**Pull request merged**
