### PR TITLE
[air] update DummyTrainer to report once per epoch

### PR DESCRIPTION
**Pull request by matthewdeng**
Signed-off-by: Matthew Deng <matt@anyscale.com>

## Why are these changes needed?

Train expects each worker to call `report` the same number of times. 

`Datasets.split(equal=True)` guarantees each split will have the same number of _rows_ but not necessarily the same number of _blocks_. If `batch_size=None` the number of batches will correspond to the number of blocks.

This PR changes the logic to report once per epoch, instead of per batch. 

## Checks

Ran [air_benchmark_data_bulk_ingest](https://buildkite.com/ray-project/release-tests-pr/builds/10357#01821e4b-6521-408a-ac99-6508972934ad) successfully.

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — CHANGES_REQUESTED** [review]
This makes it much less useful for reporting. Aren't users of other Trainers likely to run into the exact same issue?

Why not disable reporting from non zero ranks as a more general fix?

**Comment by matthewdeng** [comment]
@ericl hmm if we were to run this with Torch distributed, the behavior would be that the workers hang while waiting for gradient synchronization. So in a practical train setup we don't actually expect users to run into this.

The other approach is to ensure each worker has the same number of batches, which can be done by either:
1. Specifying a `batch_size`.
2. Fixing the `split` logic to drop the empty blocks (which @scv119 is working on)

I felt like in this workload per-batch reporting might end up causing the timing of the benchmarks to be dominated by the reporting time, so that's what made me go with the current approach.

**Comment by ericl** [comment]
Right, that's my point: torch would hang, which is the underlying problem we should fix (un-even batch sizes). If we fix that, then there is no need for this PR.

**Comment by matthewdeng** [comment]
Okay just to be clear there are two different concerns:

1. Uneven number of blocks across splits.
2. Uneven batch sizes.


Uneven number of blocks will be fixed by Chen's PR and mitigate the original error.

For uneven batch sizes, should we change the behavior of `iter_batches(batch_size=None)` or even completely disallow it?
```
batch_size: Record batch size, or None to let the system pick.
```

I feel like it's unintuitive that this yields batches of different sizes. If we require this to be set or internally set it to a constant value, then this problem would be solved as well. Is there any case we wouldn't want to enforce a constant batch size?

**Comment by ericl** [comment]
> I feel like it's unintuitive that this yields batches of different sizes. If we require this to be set or internally set it to a constant value, then this problem would be solved as well. Is there any case we wouldn't want to enforce a constant batch size?

I agree. Actually, we have already set it to 4096 for `map_batches` for similar reasons. How about we set it to 4096 also for iter_batches() by default? cc @clarkzinzow

**Comment by matthewdeng** [comment]
Superseded by https://github.com/ray-project/ray/pull/26955.

**Pull request closed without merging**
