### PR TITLE
[rllib] Rename PolicyGraph => Policy, move from evaluation/ to policy/

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

This implements some of the renames proposed in https://github.com/ray-project/ray/issues/4813
We leave behind backwards-compatibility aliases for *PolicyGraph and SampleBatch.

This was partially done with these commands:
```
sed -i 's/policy-graph/policy/g' **/*.rst **/*.py
sed -i 's/policy_graph/policy/g' **/*.rst **/*.py
sed -i 's/PolicyGraph/Policy/g' **/*.rst **/*.py
sed -i 's/Policy Graph/Policy/g' **/*.rst **/*.py
sed -i 's/policy graph/policy/g' **/*.rst **/*.py
sed -i 's/Policys/Policies/g' **/*.rst **/*.py
sed -i 's/policys/policies/g' **/*.rst **/*.py

for file in `find . | grep policy_graph`; do
    mv $file ${file%_graph.py}.py;
done

sed -i 's/rllib.evaluation.policy/rllib.policy.policy/g' **/*.py
sed -i 's/rllib.evaluation.tf_policy/rllib.policy.tf_policy/g' **/*.py
sed -i 's/rllib.evaluation.dynamic_tf_policy/rllib.policy.dynamic_tf_policy/g' **/*.py
sed -i 's/rllib.evaluation.torch_policy/rllib.policy.torch_policy/g' **/*.py
sed -i 's/ray.rllib.evaluation.sample_batch/ray.rllib.policy.sample_batch/g' **/*.py
```

## Related issue number

https://github.com/ray-project/ray/issues/4813
## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by ericl** [comment]
@bbalaji-ucsd could you review this, especially making sure that the backwards compat aliases work as intended and I didn't miss anything?

**Comment by ericl** [comment]
jenkins retest this please

**Comment by bbalaji-ucsd** [comment]
> @bbalaji-ucsd could you review this, especially making sure that the backwards compat aliases work as intended and I didn't miss anything?

Yes. Let me go through the changes today.

**Comment by bbalaji-ucsd** [comment]
Looks good to me @ericl

**Review by richardliaw — APPROVED** [review]

**Pull request merged**
