### PR TITLE
Auto discover dashboard agent port

### LINKED ISSUE #17498: new dashboard agent port conflict issues
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 3.7

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

Users are getting a few different error messages, this is one that’s spamming me a lot:
```
(pid=4670) (raylet, ip=...) E0802 07:40:46.542383278   63998 server_chttp2.cc:49]        {"created":"@1627890046.542339446","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1627890046.542335288","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1627890046.542316804","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:59332"},{"created":"@1627890046.542334837","description":"Unable to configure socket","fd":19,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1627890046.542332583","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
(pid=4670) (raylet, ip=...) Traceback (most recent call last):
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 381, in <module>
(pid=4670) (raylet, ip=...)     raise e
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 366, in <module>
(pid=4670) (raylet, ip=...)     logging_params=logging_params)
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 94, in __init__
(pid=4670) (raylet, ip=...)     f"[::]:{self.dashboard_agent_port}")
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/aio/_server.py", line 84, in add_insecure_port
(pid=4670) (raylet, ip=...)     address, self._server.add_insecure_port(_common.encode(address)))
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
(pid=4670) (raylet, ip=...)     raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
```

Also, --include-dashboard=False does not flag this off.

cc @fyrestone @rkooo567

### PR DESCRIPTION
**Pull request by ericl**
This PR is fixing https://github.com/ray-project/ray/pull/18250 for merge.
- [x] Fix ray client server port discovery
- [x] Fix ray client tests
- [x] Fix streaming test
- [x] Fix tsan issue reading OCL harvest interval -> need to fix patch to use mutex or atomic
- [x] tests:test_runtime_env_ray_minimal
- [x] serve:test_ray_client
- [x] test_runtime_env [only in CI?]
- [x] test_runtime_env_complicated -> 5 tests fail
- [x] tests:test_client_multi -> hangs
- [x] serve:test_standalone -> hangs
- [x] tests:test_client_proxy -> failures [only in CI?]
- [x] tests:test_healthcheck -> failures

Closes https://github.com/ray-project/ray/issues/17498

### CODE REVIEW

**Comment by ericl** [comment]
@fyrestone I'm working on this now, let me know if you know any issues that need to be fixed.

**Comment by fyrestone** [comment]
> @fyrestone I'm working on this now, let me know if you know any issues that need to be fixed.

Thank you for fixing the PR.

**Comment by fyrestone** [comment]
I noticed that you changed a lot of code by using auto discover the dashboard agent port. It is good:thumbsup:, but i think these are not the blocking merge issue. It's planned in the next step, implement an API `get_agent_address()` instead of use the internal kv directly, then get the agent port by the API.

Thanks for fixing the PR.

**Comment by ericl** [comment]
It was causing Ray client tests to fail since the server wasn't starting. I think it's necessary to merge now, maybe it wasn't needed before.

**Comment by ericl** [comment]
Seems the the other client tests are now passing, except for those two issues above!

**Comment by ericl** [comment]
Hmm, it seems we are consistently failing a bunch of runtime_env / RLlib tests in CI, but the tests pass locally. This has changed from last week (we were passing all tests consistently).

**Comment by rkooo567** [comment]
There were incidents in the master. Maybe consider to merge the master again? It should be fine now

**Comment by ericl** [comment]
Per offline discussion, closing this PR since we think it's not the right long term architectural direction. We can instead remove the service discovery aspect entirely by:
1. Embedding the runtime agent in raylet as an embedded python interpreter.
2. Having Ray client server use high-level Ray APIs instead of RPC to agent.

**Comment by fyrestone** [comment]
> Per offline discussion, closing this PR since we think it's not the right long term architectural direction. We can instead remove the service discovery aspect entirely by:
> 
> 1. Embedding the runtime agent in raylet as an embedded python interpreter.
> 2. Having Ray client server use high-level Ray APIs instead of RPC to agent.
> 
> cc @edoakes @scv119

Is it safe to use multiple platforms of packages in one process? e.g. C++ protobuf & Python protobuf.

**Comment by fyrestone** [comment]
> > Per offline discussion, closing this PR since we think it's not the right long term architectural direction. We can instead remove the service discovery aspect entirely by:
> > 
> > 1. Embedding the runtime agent in raylet as an embedded python interpreter.
> > 2. Having Ray client server use high-level Ray APIs instead of RPC to agent.
> > 
> > cc @edoakes @scv119
> 
> Is it safe to use multiple platforms of packages in one process? e.g. C++ protobuf & Python protobuf, C++ gRPC & Python gRPC. Because some Python packages also have C++ so, they may have duplicated C++ symbols.

**Pull request closed without merging**
