### PR TITLE
Fix task is forwarded even if there is pending worker for it.

### PR DESCRIPTION
**Pull request by jovany-wang**
## Why are these changes needed?
If there has pending workers for a task, we shouldn't forward it to other node. But now I have no idea how I construct a test for it.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @wuisawesome 

Can you also add the same logic to the new scheduler?

**Comment by wuisawesome** [comment]
I don't think this is applicable to the new scheduler because you can only request a worker once you're on the dispatch queue. you can only spillback from scheduling queue, and you can't move from the dispatch queue to the scheduling queue

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Do we actually need this PR? The goal is to delete the old scheduler as soon as possible, so we shouldn't try to add code to it now.

Also, what prompted the PR? Generally, we shouldn't add functionality to Ray core unless there is a concrete problem that calls for it. Ideally, we should have a github issue with a reproducible example first.

**Comment by stephanie-wang** [comment]
Closing this since it seems to be stale.

**Pull request closed without merging**
