### PR TITLE
[xray] Handle duplicate actor creation notifications nicely

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

An actor creation notification may be processed twice by a raylet if the initial publication is slow. The check for duplicate actor notifications is too strict, causing the raylet to crash if a duplicate notification is received. This PR relaxes the check to just make sure that if a duplicate notification is received, the node manager IDs match.

### CODE REVIEW

**Review by robertnishihara — APPROVED** [review]
This looks good to me, what are the situations where a double notification can happen (without a failure)? Are actor notifications broadcast multiple times?

**Comment by robertnishihara** [comment]
jenkins retest this please

**Comment by stephanie-wang** [comment]
The scenario where I've seen it happen so far is when a node manager receives an actor task that it doesn't have a location for yet, so it does a lookup. Then it receives the published notification along with the lookup response, so it gets a duplicate notification.

I think it's necessary to keep the lookup step, though, in case there's a node that joins the cluster after some actor notifications have already been published.

**Comment by robertnishihara** [comment]
Got it, thanks.

**Review by elibol — APPROVED** [review]
LGTM.

**Pull request merged**
