### PR TITLE
Make it so pydantic is required before we launch dashboard api server

### LINKED ISSUE #27322: [Core] Ray 2.0.0rc0 missing `pydantic` from requirements.txt
### What happened + What you expected to happen

Installing Ray 2.0.0 should pull in any dependencies that are required. After doing `pip install ray==2.0.0rc0`, I got the following error when doing a simple `ray.init()`. 

```
2022-08-01 10:25:40,651	ERROR services.py:1363 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2022-08-01_10-25-38_629255_24646/logs/dashboard.log:
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/kvelayutham/opt/anaconda3/envs/modin-ray-2.0/lib/python3.9/site-packages/ray/dashboard/modules/job/job_head.py", line 33, in <module>
    from ray.dashboard.modules.job.pydantic_models import (
  File "/Users/kvelayutham/opt/anaconda3/envs/modin-ray-2.0/lib/python3.9/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
    from pydantic import BaseModel, Field
ModuleNotFoundError: No module named 'pydantic'
```

This fix is simple and just requires the requirements.txt file to be updated appropriately. 

### Versions / Dependencies

macOS 12.2.1
Ray 2.0.0rc0
Python 3.9.12

### Reproduction script

```python
In [1]: import ray

In [2]: ray.__version__
Out[2]: '2.0.0rc0'

In [3]: ray.init()
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Related issue number
fixes #27322 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
I'd like to make sure why this issue wasn't caught by the existing minimal tests (and we should add tests accordingly). @alanwguo do you happen to know what was the exact root cause of the issue?

**Comment by alanwguo** [comment]
> I'd like to make sure why this issue wasn't caught by the existing minimal tests (and we should add tests accordingly). @alanwguo do you happen to know what was the exact root cause of the issue?


@rkooo567, Yes, the dashboard api server is only attempted to be launched based on importing the imports in optional-utils. Since pydantic is not in that list, if all the other imports are there and not pydantic, then dashboard api will try to launch and the error will happen.

If none of the other imports were there, then dashboard api will not try to launch.

Our tests test the situation where none of the other imports are there (minimal install does not install any of those optional imports). Therefore, the tests pass. This is also the situation where users install into a fresh conda env.

Our tests does not test the situation where a user has some of the optional packages but none. For example if they previously installed some of the optional packages and then deleted a subset of them.

The only way we can create a test that is more robust, is if we test every possible subset of optional packages.

**Review by architkulkarni — APPROVED** [review]
Does it make sense to add a code comment somewhere so that a developer doesn't manually have to remember to copy certain new deps from `requirements.txt` to `optional_deps.py`?  Otherwise the same kind of issue might happen again when we add a new dep

**Comment by architkulkarni** [comment]
Something like this: https://github.com/ray-project/ray/blob/bda5026428c9b1a2e6c073aa808c78e3259ec329/python/requirements.txt#L5

**Comment by alanwguo** [comment]
@architkulkarni , I added some more documentation.

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
@alanwguo can you merge master again?
@richardliaw code owner can you also approve?

**Review by edoakes — APPROVED** [review]

**Pull request merged**
