### PR TITLE
[do-not-merge] 2.8 perf regression in diff form

### PR DESCRIPTION
**Pull request by vitsai**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hey @vitsai are these number updated one after fixing the infra issue that @rickyyx mentioned?

**Comment by vitsai** [comment]
```
REGRESSION 72.90%: dashboard_p95_latency_ms (LATENCY) regresses from 46.348 to 80.137 (72.90%) in 2.8.0/benchmarks/many_nodes.json
REGRESSION 64.43%: dashboard_p99_latency_ms (LATENCY) regresses from 14019.625 to 23052.355 (64.43%) in 2.8.0/benchmarks/many_tasks.json
REGRESSION 27.25%: dashboard_p95_latency_ms (LATENCY) regresses from 8149.28 to 10369.756 (27.25%) in 2.8.0/benchmarks/many_tasks.json
REGRESSION 20.13%: dashboard_p99_latency_ms (LATENCY) regresses from 145.645 to 174.969 (20.13%) in 2.8.0/benchmarks/many_nodes.json
REGRESSION 15.32%: 1000000_queued_time (LATENCY) regresses from 177.93132558000002 to 205.19758366500002 (15.32%) in 2.8.0/scalability/single_node.json
REGRESSION 13.14%: stage_2_avg_iteration_time (LATENCY) regresses from 60.438395738601685 to 68.37787942886352 (13.14%) in 2.8.0/stress_tests/stress_test_many_tasks.json
REGRESSION 11.01%: dashboard_p50_latency_ms (LATENCY) regresses from 3.687 to 4.093 (11.01%) in 2.8.0/benchmarks/many_nodes.json
REGRESSION 9.67%: 1_1_actor_calls_sync (THROUGHPUT) regresses from 2273.2464988756947 to 2053.5000943392597 (9.67%) in 2.8.0/microbenchmark.json
REGRESSION 8.44%: single_client_get_object_containing_10k_refs (THROUGHPUT) regresses from 13.009554585474522 to 11.911115119151876 (8.44%) in 2.8.0/microbenchmark.json
REGRESSION 8.18%: placement_group_create/removal (THROUGHPUT) regresses from 997.6322375478999 to 916.0390933731816 (8.18%) in 2.8.0/microbenchmark.json
REGRESSION 8.05%: single_client_wait_1k_refs (THROUGHPUT) regresses from 5.52141006441801 to 5.077083407402203 (8.05%) in 2.8.0/microbenchmark.json
REGRESSION 7.08%: stage_1_avg_iteration_time (LATENCY) regresses from 23.342886781692506 to 24.99666111469269 (7.08%) in 2.8.0/stress_tests/stress_test_many_tasks.json
REGRESSION 6.84%: stage_4_spread (LATENCY) regresses from 0.7296295246039273 to 0.7795093658217519 (6.84%) in 2.8.0/stress_tests/stress_test_many_tasks.json
REGRESSION 6.82%: 1_n_actor_calls_async (THROUGHPUT) regresses from 9672.982187721544 to 9013.345072517786 (6.82%) in 2.8.0/microbenchmark.json
REGRESSION 6.35%: 1_n_async_actor_calls_async (THROUGHPUT) regresses from 8657.20480299259 to 8107.296817082561 (6.35%) in 2.8.0/microbenchmark.json
REGRESSION 5.14%: 10000_get_time (LATENCY) regresses from 25.08259386100002 to 26.371442345999995 (5.14%) in 2.8.0/scalability/single_node.json
REGRESSION 5.03%: 10000_args_time (LATENCY) regresses from 17.291354780999995 to 18.161911279999998 (5.03%) in 2.8.0/scalability/single_node.json
REGRESSION 4.12%: actors_per_second (THROUGHPUT) regresses from 738.330085638146 to 707.91056858179 (4.12%) in 2.8.0/benchmarks/many_actors.json
REGRESSION 3.61%: tasks_per_second (THROUGHPUT) regresses from 429.0546317074886 to 413.5452010251431 (3.61%) in 2.8.0/benchmarks/many_tasks.json
REGRESSION 3.46%: single_client_put_calls_Plasma_Store (THROUGHPUT) regresses from 5845.356422909845 to 5642.93079417387 (3.46%) in 2.8.0/microbenchmark.json
REGRESSION 3.24%: single_client_tasks_async (THROUGHPUT) regresses from 9563.116886637355 to 9253.350380094456 (3.24%) in 2.8.0/microbenchmark.json
REGRESSION 1.49%: single_client_tasks_sync (THROUGHPUT) regresses from 1177.0860205196755 to 1159.5410057905888 (1.49%) in 2.8.0/microbenchmark.json
REGRESSION 1.38%: single_client_get_calls_Plasma_Store (THROUGHPUT) regresses from 7536.924380935448 to 7432.953617355073 (1.38%) in 2.8.0/microbenchmark.json
REGRESSION 1.29%: stage_3_creation_time (LATENCY) regresses from 2.1919972896575928 to 2.2203712463378906 (1.29%) in 2.8.0/stress_tests/stress_test_many_tasks.json
REGRESSION 1.01%: client__tasks_and_put_batch (THROUGHPUT) regresses from 11449.695712792654 to 11334.501893509201 (1.01%) in 2.8.0/microbenchmark.json
REGRESSION 0.14%: n_n_actor_calls_async (THROUGHPUT) regresses from 29270.036133623737 to 29229.518744061534 (0.14%) in 2.8.0/microbenchmark.json
```

**Comment by vitsai** [comment]
I believe yesterday's numbers should have reflected the infra fix already cc @rickyyx

**Comment by vitsai** [comment]
Ah sorry, this diff is not updated, only https://github.com/ray-project/ray/pull/40571

**Comment by vitsai** [comment]
Updated this, and there should be one against 2.7.1 here as well: https://github.com/ray-project/ray/pull/40711

**Comment by rkooo567** [comment]
Okay .ETA for the final go today

**Comment by rkooo567** [comment]
why don't we merge this btw?

**Comment by rickyyx** [comment]
coz it's updating 2.7.0 values I think

**Pull request closed without merging**
