### PR TITLE
Revert "WINDOWS: enable passing metric tests (#21705)"

### PR DESCRIPTION
**Pull request by rkooo567**
This reverts commit 8104fd5c7649bc552123859a18bc169d636c7741.

## Why are these changes needed?

This breaks the master lint.

cc @mattip 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by rkooo567** [comment]
Emergency merge. @mattip Please follow up with the new PR that fixes the lint! (Sorry that we revert this. This is the policy; we revert any offending PR asap, and the fix should come with a new PR)

**Comment by mattip** [comment]
Makes sense, sorry for the mess

**Comment by mattip** [comment]
Is there a way to see the broken lint run? The PR passes ci/travis/format.sh

**Comment by simon-mo** [comment]
sorry about the false positive here, please feel free to re-open the PR

**Comment by pcmoritz** [comment]
This PR was definitely not what broke the lint...

**Comment by rkooo567** [comment]
Yeah it was my fault.. sorry about the false negative report!

**Comment by pcmoritz** [comment]
Yeah no worries, thanks for keeping master green!

**Comment by mattip** [comment]
Reopened in #21755. I hope you found the root cause of the breakage.

**Pull request merged**
