### PR TITLE
[Dataset] avoid pyarrow 7.0.0 for dataset

### LINKED ISSUE #22177: [Bug] datasets_preprocess_ingest failed in master due to pyarrow==7.0.0
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/2676#65781171-8c7f-4d05-a638-018f400047d0

### Versions / Dependencies

master

### Reproduction script

core nightly

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

Turns out there is an (incompatibility) bug in pyarrow 7.0.0 that causes huge single object size in dataset.

I've verified revert pyarrow back to 6.0.0 fixed the issue in master on my linux dev server; need to trigger a release test run.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
what's the long term fix?

**Comment by scv119** [comment]
>  what's` the long term fix?

it's most likely a bug in pyarrow as a 2GB file results in 200GB object in dataset. we need to narrow it down and either report it to pyarrow, or fix ray dataset.

**Review by clarkzinzow — APPROVED** [review]

**Comment by scv119** [comment]
Hmm some how this doesn't install the right pyarrow version on product:
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_J1v4RFyDJRcv1Ndm5187TrN2?command-history-section=command_history&user=usr_5CczuMLkCWrTs9mGb7m1rGBX

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
For the root cause: it's very likely our serialization code doesn't work well with pyarrow 7.0.0.
I've narrow it down to this line returns over 200GB value:
https://github.com/ray-project/ray/blob/master/python/ray/_raylet.pyx#L2018

**Review by jjyao — APPROVED** [review]

**Review by ericl — APPROVED** [review]

**Pull request merged**
