### PR TITLE
[Scheduling] Report resource demand for infeasible 1-CPU tasks

### LINKED ISSUE #16935: [k8s][autoscaler][core] { "CPU": 0 } is not working for avoid task scheduling in rayHeadType Pod
### What is the problem?

I'm trying to avoid task scheduling on rayHead by setting `.values.rayResourses: { "CPU": 0 }` but it keeps trying to schedule tasks at headPod, failing due to lack of resources and, this way, getting stuck without scaling any workerPods.

- Python version: 3.8.5
- Linux: Ubuntu 18.04
- Kubernetes version: 1.18.14 (AKS)

### Reproduction (REQUIRED)
- Install k8s ray cluster using helm
- values.yaml
```
# RayCluster settings:
image: rayproject/ray:nightly-py38
headPodType: rayHeadType
podTypes:
  rayHeadType:
    minWorkers: 0
    maxWorkers: 0
    CPU: 1
    memory: 512Mi
    GPU: 0
    rayResources: { "CPU": 0, "GPU": 0 }
    nodeSelector: { use: development }
  rayWorkerType:
    minWorkers: 0
    maxWorkers: 6
    memory: 512Mi
    CPU: 1
    GPU: 0
    rayResources: { "GPU": 0 }
    nodeSelector: { use: development }

# Operator settings:
operatorOnly: false
clusterOnly: false
namespacedOperator: false
operatorNamespace: default
operatorImage: rayproject/ray:nightly-py38
```
- task.py
```
import ray
LOCAL_PORT = 10001

@ray.remote(num_cpus=1)
def f(i):
    import time
    print(f"Try number {i}")
    time.sleep(60)

if __name__ == "__main__":
    ray.util.connect(f"127.0.0.1:{LOCAL_PORT}")
    ray.get([f.remote(i + 1) for i in range(10)])
```
- task log
```
The actor or task with ID ehd9rsa79fe5783b8bbc6e3fba23srd094a7q98c7axec7 cannot be scheduled right now. It requires {CPU: 1.000000} for placement, however the cluster currently cannot provide the requested resources. The required resources may be added as autoscaling takes place or placement groups are scheduled. Otherwise, consider reducing the resource requirements of the task.
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
See https://github.com/ray-project/ray/issues/16935#issuecomment-909612684 for the reported issue. Basically, when a task requires 1 CPU and is infeasible because there is 0 CPU available in the cluster, the resource demand is not reported.

The problem is that scheduler has an optimization to treat 1-CPU tasks differently. However the logic did not include infeasible tasks, which can only happen when the cluster has 0 CPU. The fix here is to include infeasible tasks in resource demand.

## Related issue number
Closes #16935

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Nice! Is there an easy integration test we could write as well in Python?

**Comment by mwtian** [comment]
> Nice! Is there an easy integration test we could write as well in Python?

Will add one.

**Comment by mwtian** [comment]
Wrote an integration test with `ray status` in Python. Verified the tests failed before the fix.

**Comment by iycheng** [comment]
```
================================== FAILURES ===================================
_______________ test_head_node_without_cpu[ray_start_cluster0] ________________

ray_start_cluster = <ray.cluster_utils.Cluster object at 0x0000027C1A0AB6C8>

    @pytest.mark.parametrize(
        "ray_start_cluster", [{
            "num_cpus": 0,
            "num_nodes": 1,
        }], indirect=True)
    def test_head_node_without_cpu(ray_start_cluster):
        @ray.remote(num_cpus=1)
        def f():
            return 1
    
        f.remote()
    
        check_count = 0
        demand_1cpu = "Demands:\n {'CPU': 1.0}:"
        while True:
            status = subprocess.check_output(["ray", "status"]).decode()
            if demand_1cpu in status:
                break
            check_count += 1
>           assert check_count < 5, f"Incorrect demand. Last status {status}"
E           AssertionError: Incorrect demand. Last status ======== Autoscaler status: 2021-09-30 22:25:49.569028 ========

E             Node status

E             ---------------------------------------------------------------

E             Healthy:

E              1 node_23ce27c2b8160ef8dfb241db5202e7bb4e568d8ead0098f779ad0587

E             Pending:

E              (no pending nodes)

E             Recent failures:

E              (no failures)

E             

E             Resources

E             ---------------------------------------------------------------

E             Usage:

E              0.00/3.870 GiB memory

E              0.00/0.146 GiB object_store_memory

E             

E             Demands:

E              {'CPU': 1.0}: 2+ pending tasks/actors

E             
E           assert 5 < 5

\\?\C:\Users\RUNNER~1\AppData\Local\Temp\Bazel.runfiles_e9lpbukk\runfiles\com_github_ray_project_ray\python\ray\tests\test_scheduling.py:601: AssertionError
---------------------------- Captured stderr setup ----------------------------

```
Windows test failed which looks related to this one.

**Comment by ericl** [comment]
Did you push the integration test?

**Comment by mwtian** [comment]
Probably because of different new line characters .. Pushed a fix.

**Comment by mwtian** [comment]
Windows failure looks unrelated now.

**Review by ericl — APPROVED** [review]

**Pull request merged**
