### PR TITLE
Fix gap between total time and time in user code + blocked time, rename iterator overheads

### PR DESCRIPTION
**Pull request by omatthew98**
## Why are these changes needed?
The dataset stats output often has discrepancies between `Total time user code is blocked + Total time in user code` and `Total time overall` although they should match. Example output below:
```
Dataset iterator time breakdown:
* Total time user code is blocked: 28.25s
* Total time in user code: 1.01s
* Total time overall: 50.05s
* Num blocks local: 0
* Num blocks remote: 0
* Num blocks unknown location: 0
* Batch iteration time breakdown (summed across prefetch threads):
    * In ray.get(): 70.92us min, 1.29ms max, 301.84us avg, 7.55ms total
    * In batch creation: 199.83us min, 5.34ms max, 1.54ms avg, 6.16ms total
    * In batch formatting: 69.5us min, 502.63us max, 191.91us avg, 767.63us total
```

This PR addresses the missing time by adding a third subtotal `Total time in iterator initialization code` which represents this missing time (there is still ~1ms discrepancy but this addresses the large differences being shown). An example of the updated output is as follows:
```
Dataset iterator time breakdown:
* Total time user code is blocked: 28.27s
* Total time in user code: 1.02s
* Total time in iterator initialization code: 20.74s
* Total time overall: 50.02s
* Num blocks local: 0
* Num blocks remote: 0
* Num blocks unknown location: 0
* Batch iteration time breakdown (summed across prefetch threads):
    * In ray.get(): 92.46us min, 600.71us max, 205.08us avg, 5.13ms total
    * In batch creation: 166.71us min, 4.18ms max, 1.2ms avg, 4.81ms total
    * In batch formatting: 49.83us min, 474.38us max, 168.58us avg, 674.33us total
```

### Testing
To show the new subtotal and how it closes the gap the following code was executed with multiple trials and multiple different numbers of rows:
```python
def sleep(x):
    time.sleep(0.5)
    return x

ds = ray.data.range(num_rows).map(sleep)

for _ in ds.iter_batches():
    time.sleep(0.25)

print(ds.stats())
```

The results are as follows (all times in seconds):
| num_row | block_time | user_time | initialize_time | total_time | total_time - sum(...) |
| -- | -- | -- | -- | -- | -- |
| 1 | 0.598833958 | 0.251608333 | 0.27170975 | 1.123139791 | 0.00098775 |
| 1 | 0.586511375 | 0.252883583 | 0.254020416 | 1.09415875 | 0.000743376 |
| 1 | 0.552450125 | 0.253593833 | 0.252214208 | 1.060210833 | 0.001952667 |
| 10 | 0.860220708 | 0.253869333 | 0.454646625 | 1.570308625 | 0.001571959 |
| 10 | 0.744377792 | 0.253864125 | 0.465643667 | 1.46494825 | 0.001062666 |
| 10 | 0.855383416 | 0.252772166 | 0.454809625 | 1.564060958 | 0.001095751 |
| 100 | 4.117568541 | 0.254450084 | 2.152201792 | 6.525721417 | 0.001501 |
| 100 | 4.140707333 | 0.250147542 | 2.136471958 | 6.528766625 | 0.001439792 |
| 100 | 4.123388875 | 0.252757292 | 2.139699833 | 6.517074041 | 0.001228041 |
| 1000 | 28.26541546 | 1.0192635 | 20.735546 | 50.02154713 | 0.001322167 |
| 1000 | 28.33190604 | 1.015492333 | 20.76731429 | 50.11657058 | 0.001857917 |
| 1000 | 28.28550558 | 1.014310542 | 20.76522146 | 50.06668683 | 0.00164925 |

## Related issue number
Closes https://github.com/ray-project/ray/pull/42810

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Performance testing
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by omatthew98** [comment]
The above data raised some questions about why the iterator initialization time was as long as it was. The costly operation comes from the `next(gen)` call from this line in `execute_to_iterator`. For smaller datasets, the initialization time can be a dramatic portion of the total time. I suspect if all the data can fit into one block, then this call to `next` will result in all of the data being read, then it will be read again in `iter_batches`. For large datasets, this initialization will be a smaller fraction of the total time spent, but still will represent non-trivial un-timed work.

**Review by scottjlee — APPROVED** [review]

**Comment by omatthew98** [comment]
Closed #42787 in favor of this PR, those changes have been incorporated here:
* `Total time user code is blocked` -> `Total time user thread is blocked by iter_batches`
* `Total time in user code` -> `Total execution time for user thread`

Example of new output:
```
Operator 1 ReadRange->Map(sleep): 25 tasks executed, 25 blocks produced in 49.48s
* Remote wall time: 8.06s min, 20.66s max, 20.14s mean, 503.58s total
* Remote cpu time: 31.72ms min, 90.28ms max, 77.99ms mean, 1.95s total
* Peak heap memory usage (MiB): 143968.75 min, 145968.75 max, 144828 mean
* Output num rows per block: 16 min, 41 max, 40 mean, 1000 total
* Output size bytes per block: 128 min, 328 max, 320 mean, 8000 total
* Output rows per task: 16 min, 41 max, 40 mean, 25 tasks used
* Tasks per node: 25 min, 25 max, 25 mean; 1 nodes used
* Extra metrics: {'num_inputs_received': 13, 'bytes_inputs_received': 33468, 'num_inputs_processed': 1, 'bytes_inputs_processed': 2574, 'bytes_inputs_of_submitted_tasks': 33468, 'num_outputs_generated': 1, 'bytes_outputs_generated': 328, 'rows_outputs_generated': 41, 'num_outputs_taken': 1, 'bytes_outputs_taken': 328, 'num_outputs_of_finished_tasks': 1, 'bytes_outputs_of_finished_tasks': 328, 'num_tasks_submitted': 13, 'num_tasks_running': 12, 'num_tasks_have_outputs': 1, 'num_tasks_finished': 1, 'num_tasks_failed': 0, 'obj_store_mem_alloc': 328, 'obj_store_mem_freed': 2574, 'obj_store_mem_cur': 30894, 'obj_store_mem_peak': 31221, 'obj_store_mem_spilled': 0, 'block_generation_time': 20.64818425, 'cpu_usage': 12, 'gpu_usage': 0, 'ray_remote_args': {'num_cpus': 1, 'scheduling_strategy': 'SPREAD'}}

Dataset iterator time breakdown:
* Total time user thread is blocked by iter_batches: 28.8s
* Total execution time for user thread: 4.24ms
* Total time in iterator initialization code: 20.72s
* Total time overall: 49.53s
* Num blocks local: 0
* Num blocks remote: 0
* Num blocks unknown location: 0
* Batch iteration time breakdown (summed across prefetch threads):
    * In ray.get(): 84.92us min, 493.0us max, 189.09us avg, 4.73ms total
    * In batch creation: 13.54us min, 2.4ms max, 26.47us avg, 26.47ms total
    * In batch formatting: 10.88us min, 385.46us max, 24.39us avg, 24.39ms total
```

**Comment by omatthew98** [comment]
Slight modification to wording / formatting from @stephanie-wang's feedback.
```
Dataset iterator time breakdown:
* Total time overall: 49.52s
    * Total time in Ray Data iterator initialization code: 20.75s
    * Total time user thread is blocked by Ray Data iter_batches: 28.76s
    * Total execution time for user thread: 4.15ms
* Num blocks local: 0
* Num blocks remote: 0
* Num blocks unknown location: 0
* Batch iteration time breakdown (summed across prefetch threads):
    * In ray.get(): 65.12us min, 544.04us max, 217.22us avg, 5.43ms total
    * In batch creation: 10.67us min, 1.27ms max, 26.82us avg, 26.82ms total
    * In batch formatting: 8.58us min, 311.5us max, 26.0us avg, 26.0ms total
```

**Review by stephanie-wang — APPROVED** [review]
Thanks for this improvement!

**Pull request merged**
