### PR TITLE
[Core][GCS] remove gcs object manager

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Removing unused logic from GCS would reduce the work for the GCS / Redis decoupling project. We can revert this and fix the logic if similar logic is needed in future.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
Failed tests also failed on master: https://buildkite.com/ray-project/ray-builders-branch/builds/4417#_

**Comment by mwtian** [comment]
cc @lixin-wei @iycheng

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
(waiting on Windows build)

**Comment by mwtian** [comment]
> (waiting on Windows build)

Looks like Windows builds are taking a long time recently, sometimes exceeding the 6hr timeout. This may run for another 3hr before timing out too..

**Review by rkooo567 — APPROVED** [review]

**Comment by mwtian** [comment]
Windows build passed.

**Pull request merged**
