### PR TITLE
[CherryPick][Serve][Doc] Update metrics & log doc (#34222)

### PR DESCRIPTION
**Pull request by sihanwang41**
Update the logging & metrics for the 2.4. change.

## Why are these changes needed?

cherrypick: #34222 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by akshay-anyscale** [comment]
Do we also need to update list of metrics here - https://docs.ray.io/en/latest/serve/production-guide/monitoring.html#built-in-ray-serve-metrics

**Comment by sihanwang41** [comment]
> Do we also need to update list of metrics here - https://docs.ray.io/en/latest/serve/production-guide/monitoring.html#built-in-ray-serve-metrics

You are checking the 2.3.1, it is already updated in the 2.4.0 doc. https://anyscale-ray--34326.com.readthedocs.build/en/34326/serve/production-guide/monitoring.html

**Comment by sihanwang41** [comment]
tests are not related.

**Comment by sihanwang41** [comment]
ping @zhe-thoughts ^^

**Review by zhe-thoughts — APPROVED** [review]

**Comment by jjyao** [comment]
I'll merge after releasing to pypi

**Pull request merged**
