### PR TITLE
[Dashboard] Memory Page Loading Wheel

### LINKED ISSUE #10863: [Dashboard] Add loading bar in memory view.
### Describe your feature request
It takes some time to load memory view page. In this case, it was confusing me if the memory view was
1. loading the table
2. or just empty.

To avoid this, I think it'll be great to have a rotating wheel or something while it is loading.

### PR DESCRIPTION
**Pull request by mfitton**
## Why are these changes needed?
The user experience of the dashboard loading message was confusing and leading to users leaving the memory tab without waiting on it to load. This adds a loading wheel for better UX. See attached screenshot.

Screen Shot 2020-10-21 at 6 40 43 PM

## Related issue number

Closes #10863 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(
Manually QA'd but not tested like the rest of dashboard front-end.

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
Yay!

**Comment by rkooo567** [comment]
Please fix the lint error.

**Comment by mfitton** [comment]
Weird that it fails the lint in CI but doesn't fail the format.sh script. I'll need to figure out what's going on there.

**Comment by rkooo567** [comment]
Please resolve the merge conflict.

**Pull request merged**
