### PR TITLE
Error if shellcheck is not installed

### PR DESCRIPTION
**Pull request by suquark**
Add check for `shellcheck` in formatter.

This is at least my third time:

```
>>> scripts/format.sh
shellcheck: command not found
>>> pip install shellcheck
>>> no package "shellcheck"
>>> search for shellcheck -- oh it is a binary package
```

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by suquark** [comment]
This script requires review of the code owner

**Review by ericl — CHANGES_REQUESTED** [review]
Why don't we remove this instead? I don't think we should make this a required dependency, as it's rarely used.

**Comment by suquark** [comment]
really? everytime it raises an error if I do not have `shellcheck` installed.

**Review by ericl — APPROVED** [review]
I see, lgtm then. I still think we can just remove it entirely as it's not really needed and adds friction to new developers submitting PRs.

**Pull request merged**
