### PR TITLE
[docs] configurable ecosystem gallery

### PR DESCRIPTION
**Pull request by maxpumperla**
we've build a custom directive to read gallery information from a simple YAML file. This makes it much easier (presumably) to add new entries in the future and should hopefully attract more contributors. This PR is specifically set up for our "Ecosystems" gallery, but it's implemented to work for any other gallery on our docs as well. Apart from easier config, this should also look a bit more appealing.

On a side note, this simple format could be used for upcoming hackathons etc. to quickly display all projects in a concise way. (cc/ @zhe-thoughts @waleedkadous).

Before:

Screenshot 2022-09-21 at 10 55 02

After:

Screenshot 2022-09-21 at 10 54 50

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
Looks great! One question, is it possible to have two columns to show more at once? Seems to be using 1.5x columns per tile right now, which is a little awkward.

**Comment by maxpumperla** [comment]
@ericl yeah, one can configure that in the `meta` part of the yaml. I agree with you, not 100% happy with the formatting, but one detail to consider: we also generate section titles for all integrations (e.g. so that they show up in the right side bar for quick navigation). If we place e.g. two panels next to each other (more is bad anyway, given the amount of text), that makes no sense anymore.

the other option is to make the panels full-sized, instead of 9/12 of the width. wdyt?

**Comment by ericl** [comment]
Ah, that makes sense. Either full sized or the status quo seems reasonable to me then!

**Comment by maxpumperla** [comment]
@ericl made it full-width, looks less clunky. go ahead and merge, if you think it's ok

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Lgtm!

**Pull request merged**
