### PR TITLE
[Release 1.12.0] Cherrypick fix for protobuf-java

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Resolves a CVE (#23627) that affects services using protobuf-java.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jianoaix — APPROVED** [review]

**Comment by jianoaix** [comment]
Is this cherrypick-worthy? @ericl to approve?

**Comment by mwtian** [comment]
cc @zhe-thoughts the CVE seems to be not very severe, but users running security scanners on Ray may complain. I think we only need to cherry pick if it does not delay the release.

**Comment by zhe-thoughts** [comment]
Thanks @mwtian for the good find

If this is not a regression I don't think we should cherry-pick. It's only affecting Java and we can publish a 1.12.1 later. @thomasdesr any objections of the plan (not cherry-picking into 1.12.0)?

**Comment by jianoaix** [comment]
> cc @zhe-thoughts the CVE seems to be not very severe, but users running security scanners on Ray may complain. I think we only need to cherry pick if it does not delay the release.

It probably won't delay release (provided it's low-risk), the release is waiting for product testing now.

**Comment by zhe-thoughts** [comment]
Got it. Then let's not pick into 1.12.0

**Comment by mwtian** [comment]
I believe @jianoaix mentioned this PR should not delay the release? Regardless, I'm ok with not picking this.

**Comment by jianoaix** [comment]
@mwtian it's up to you to assess the need. I was just saying currently the release is blocked on product testing, so there is a little room for having low-risk cherrypicks.

**Comment by thomasdesr** [comment]
Agreed that this can probably defer to a point release; if you're in a position to trigger this you're also in a position to run arbitrary code so a DoS doesn't seem like a huge concern?

**Comment by mwtian** [comment]
@thomasdesr one possibility is that user ingests external input and uses protobuf-java to parse it. But yes for Ray this seems unlikely.

**Pull request closed without merging**
