### PR TITLE
[Dataset][nighlytest] use latest ray for running test

### LINKED ISSUE #21097: [1.10.0 Release] datasets_ingest_train_infer failing on master
Example: https://buildkite.com/ray-project/periodic-ci/builds/1952#6505dd83-6ed8-4cb7-bb52-0f0b19a7b507

It seems to be failing pretty consistently over the last few runs.  It's unable to grab a GPU:

```


Map Progress (8 actors 2 pending):   0%\|          \| 1/400 [00:22<23:41,  3.56s/it]2021-12-12 08:24:41,346	WARNING worker.py:1245 -- The actor or task with ID ffffffffffffffff9c08bcf94d34ab010a5c459102000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
--
  | Required resources for this actor or task: {GPU: 1.000000}
  | Available resources on this node: {4.000000/4.000000 CPU, 475072560.058594 GiB/475072560.058594 GiB memory, 0.000000/1.000000 GPU, 237536279.980469 GiB/237536279.980469 GiB object_store_memory, 1.000000/1.000000 accelerator_type:T4, 1.000000/1.000000 node:10.0.0.35}
  | In total there are 0 pending tasks and 2 pending actors on this node.
  |  
  | [INFO 2021-12-12 09:18:13,701] e2e.py: 2131  Exiting with exit code 6
  | Script failed on try 1/3 with exit code 6 (command timeout), aborting.
  | cp: cannot stat '/tmp/artifacts/*': No such file or directory
  | ----------------------------------------
  | e2e test finished with final exit code 6 after 1/3 tries
  | Run results:


```

### PR DESCRIPTION
**Pull request by scv119**
We are actually using the ray comes with the image, which is on a very old version of Ray. (suprised this actually works)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests: https://console.anyscale.com/o/anyscale-internal/configurations/app-config-details/bld_kzXDd1vfhEwGRfiJDJLka9qP kicked off a test run

   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Maybe we should include this as a base command 😂

**Comment by scv119** [comment]
yup

**Comment by clarkzinzow** [comment]
@scv119 @rkooo567 should we also include a manual uninstall? IIUC, if the image was ever changed to have a master wheel (with version`2.0.0-dev0`), then this install update would be a no-op and the old master wheel would be used. https://github.com/ray-project/ray/pull/21119

**Comment by clarkzinzow** [comment]
Also wasn't groupby and aggregations added in the latest release? Was the image wheel older than that, and if so, how was this working?

**Comment by scv119** [comment]
@clarkzinzow lol that's my question too. https://github.com/ray-project/ray/commit/236951ee4ce1b2c582c209fe7cc40d9fe5d0dd92 is the commit in the docker; that's actually after groupby being introduced

**Comment by clarkzinzow** [comment]
Ah so not _that_ old! 😉

**Comment by scv119** [comment]
https://console.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/clusters/ses_yu7vECmgC7XaSvx6J5Vyemp6?command-history-section=command_history passed

**Pull request merged**
