### PR TITLE
[RLLib] Fix MultiDiscrete not being one-hotted correctly

### PR DESCRIPTION
**Pull request by olipinski**
## Why are these changes needed?

Currently, the python sum used in complex_input_net will return an incorrect size, which will cause an error when trying to create the box. With np.sum the sum is correctly computed and a one-hot box can be created.

Also, the torch utils could not handle multidimensional MultiDiscrete spaces. This has also been fixed.

The old behaviour for the sum:

Space 
```
MultiDiscrete(
[[7 7 7 7 7 7]
[7 7 7 7 7 7]
[7 7 7 7 7 7]
[7 7 7 7 7 7]])
```

Space nvec: 
```
[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
```

Computed size: ```[28 28 28 28 28 28]```

New behaviour:

Space 
```
MultiDiscrete(
[[7 7 7 7 7 7]
[7 7 7 7 7 7]
[7 7 7 7 7 7]
[7 7 7 7 7 7]])
```

Space nvec: 
```
[[7 7 7 7 7 7]
[7 7 7 7 7 7]
[7 7 7 7 7 7]
[7 7 7 7 7 7]]
```

Computed size: ```168```

## Related issue number

N/A

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@gjoliver Can you take a look?

**Comment by smorad** [comment]
@gjoliver I can verify that `MultiDiscrete` observations seem to break RLlib for me :P

**Review by gjoliver — APPROVED** [review]
thanks a lot for the fix @olipinski 
I clean up lint and added a unit test to show the fix to this PR.
will merge after CI passes.

**Comment by olipinski** [comment]
Thanks for the clean-up and merge @gjoliver !

**Pull request merged**
