### PR TITLE
[Docs] Hyperlink upstream libraries to respective READMEs

### PR DESCRIPTION
**Pull request by amogkam**
We currently have multiple upstream libraries (for example xgboost-ray) that live in separate repos, but also have documentation and API reference in the Ray repo

However, keeping the docs in the Ray repo up to date with the source repos can lead to some complications:
1. We have to periodically manually update the docs in the Ray repo to match the source repo
2. Changes to the APIs in the source repo can lead to doc compilation errors on the Ray repo and break CI. This was the case recently with Ray Lightning https://github.com/ray-project/ray/issues/21426.

Instead of duplicating the docs in the Ray repo, this PR changes the doc structure to hyperlink the upstream libraries to the docs in the upstream repo. This means we will only have 1 source of truth for the docs for these upstream repos instead of 2.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Yard1** [comment]
Please ping when RTD passes @amogkam

**Comment by Yard1** [comment]
This looks good to me, though I am worried about the loss of API documentation from docstrings. I wonder if we could dynamically generate the pages by fetching the up to date readmes from the repos, or preserve this in some other way.

**Comment by amogkam** [comment]
@Yard1 I agree if we could automatically fetch the up to date info and render on the ray docs that would be great.

But in the meantime, I think having just one source of truth makes sense. IMO, if we want to show API docs, then they should be shown in the READMEs of the upstream repos, either via sphinx or some other tool.

**Comment by richardliaw** [comment]
API docs can’t be rendered on readmes though

**Comment by amogkam** [comment]
@richardliaw they can't be _automatically_ rendered, but there are tools that you can manually run to render markdown from python docstrings. For example https://github.com/NiklasRosenstein/pydoc-markdown/. 

I'm ok with not merging this in, but then we would need to have a better strategy for the maintenance of these docs.

Also, regardless of whether we merge this in, I think these libraries should all still have the API docs on the main repo page (so this shouldn't be a reason not to merge this).

**Comment by simon-mo** [comment]
@amogkam can you confirm this PR will fix the LINT issue? Or maybe there is a smaller diff that can fix master?

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by krfricke** [comment]
Is this still relevant?

**Comment by Yard1** [comment]
Yeah, we still need to decide on how to proceed.

**Comment by amogkam** [comment]
Yes we can close this! Thanks @Yard1!

**Pull request closed without merging**
