### PR TITLE
[Docker] Exclude `+dbg` builds when finding Wheels

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?

Fixes issue here: 
```
./.whl
--
  | ...
  | ./.whl/ray-2.0.0.dev0+dbg-cp38-cp38-manylinux2014_x86_64.whl
  | ./.whl/ray_cpp-2.0.0.dev0+dbg-cp38-cp38-manylinux2014_x86_64.whl
  | ./.whl/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
  | ./.whl/ray_cpp-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
  | ...
  | Building the following python versions:  {'-py38': '3.8.5'}
  | Building base images:  True
  | Pulling images for caching
  | Cleaned up 0.0MB
  | BUILT:  rayproject/base-deps:nightly-py38-cpu
  | Cleaned up 485.79284286499023MB
  | BUILT:  rayproject/base-deps:nightly-py38-gpu
  | Traceback (most recent call last):
  | File "./ci/travis/build-docker-images.py", line 473, in <module>
  | base_images_built = build_or_pull_base_images(args.base)
  | File "./ci/travis/build-docker-images.py", line 239, in build_or_pull_base_images
  | _build_cpu_gpu_images(image, no_cache=False)
  | File "./ci/travis/build-docker-images.py", line 143, in _build_cpu_gpu_images
  | wheel = _get_wheel_name(build_args["PYTHON_MINOR_VERSION"])
  | File "./ci/travis/build-docker-images.py", line 96, in _get_wheel_name
  | f"Found ({len(matches)}) matches for 'ray-*{PYTHON_WHL_VERSION}"
  | AssertionError: Found (2) matches for 'ray-*cp38*-manylinux*' instead of 1
  | 🚨 Error: The command exited with status 1

```

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
@scv119 @rkooo567 are we adding any other prefix? like asan or something?

**Comment by simon-mo** [comment]
nice find btw

**Comment by rkooo567** [comment]
+asan, +ubsan +tsan in the future

**Comment by ijrsvt** [comment]
@rkooo567 Should I just make this `if "+" not in file`?

**Comment by rkooo567** [comment]
I think we can hard code asan debug tsan ubsan. No plan to add anything new for a while. I think + could be a bit dangerous? But cc @simon-mo. Another thing we can do is to always add special keyword

**Comment by simon-mo** [comment]
@ijrsvt i think filter out the wheel with "+" is fine. Since the base wheel, which is what want, would never contains "+"

**Comment by ijrsvt** [comment]
Failure is unrelated as this is pure Linux-only, Docker Build Infra:
Failure:
```
Windows: basic_client_mode
```

**Pull request merged**
