### PR TITLE
In PushObjectInternal, wrap all params in a shared_ptr<struct>.

### PR DESCRIPTION
**Pull request by rynewang**
This PR comes from a small static analysis that discovered there are multiple big memcpy calls in ObjectManager.

Specifically, in the format of (instruct_addr, memcpy_bytes, location, signature) we have
```
 ('0000000100483330',
  '(src/ray/object_manager/object_manager.cc:483)',
  128,
  "ray::ObjectManager::PushObjectInternal(ray::ObjectID const&, ray::NodeID const&, std::__1::shared_ptr<ray::ChunkObjectReader>, bool)::$_13::operator()(long long) const::'lambda'()::('lambda'()&&)"),
 ('0000000100483ac8',
  '(src/ray/object_manager/object_manager.cc:483)',
  128,
  "ray::ObjectManager::PushObjectInternal(ray::ObjectID const&, ray::NodeID const&, std::__1::shared_ptr<ray::ChunkObjectReader>, bool)::$_13::operator()(long long) const::'lambda'()::('lambda'() const&)"),
 ('00000001004814e0',
  '(src/ray/object_manager/object_manager.cc:481)',
  116,
  'ray::ObjectManager::PushObjectInternal(ray::ObjectID const&, ray::NodeID const&, std::__1::shared_ptr<ray::ChunkObjectReader>, bool)::$_13::$_13($_13&&)'),
 ('0000000100481c78',
  '(src/ray/object_manager/object_manager.cc:481)',
  116,
  'ray::ObjectManager::PushObjectInternal(ray::ObjectID const&, ray::NodeID const&, std::__1::shared_ptr<ray::ChunkObjectReader>, bool)::$_13::$_13($_13 const&)'),
 ('0000000100488968',
  '(src/ray/object_manager/object_manager.cc:545)',
  96,
  'ray::ObjectManager::SendObjectChunk(ray::UniqueID const&, ray::ObjectID const&, ray::NodeID const&, unsigned long long, std::__1::shared_ptr<ray::rpc::ObjectManagerClient>, std::__1::function<void (ray::Status const&)>, std::__1::shared_ptr<ray::ChunkObjectReader>, bool)::$_14::$_14($_14&&)'),
 ('00000001004890dc',
  '(src/ray/object_manager/object_manager.cc:545)',
  96,
  'ray::ObjectManager::SendObjectChunk(ray::UniqueID const&, ray::ObjectID const&, ray::NodeID const&, unsigned long long, std::__1::shared_ptr<ray::rpc::ObjectManagerClient>, std::__1::function<void (ray::Status const&)>, std::__1::shared_ptr<ray::ChunkObjectReader>, bool)::$_14::$_14($_14 const&)')
```

This part mentions that `ObjectManager::SendObjectChunk` copies the same data twice, and `ObjectManager::PushObjectInternal` copies the same data 3 times.

This PR is a tentative one to see if we can reduce the copies with a shared ptr that wraps all data needed. This does not guarantee a performance gain: we saved some copies (488 bytes before, 128 bytes after), but introduced a shared_ptr with all the dynamic memory allocations and ref counting. A benchmark is needed.

### CODE REVIEW

**Comment by rkooo567** [comment]
for benchmark you can run 
```
- name: object_store
  group: core-scalability-test
  working_dir: benchmarks

  frequency: nightly
  team: core
  cluster:
    byod:
      type: gpu
      runtime_env:
        - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so
    cluster_compute: object_store.yaml

  run:
    timeout: 3600
    script: python object_store/test_object_store.py
    wait_for_nodes:
      num_nodes: 50

  variations:
    - __suffix__: aws
    - __suffix__: gce
      env: gce
      frequency: manual
      cluster:
        cluster_compute: object_store_gce.yaml
```

**Comment by rkooo567** [comment]
other than this, we don't really have a good set of object transfer benchmark

**Comment by rynewang** [comment]
Result:

`
[{'perf_metric_name': 'time_to_broadcast_1073741824_bytes_to_50_nodes', 'perf_metric_value': 84.94552126900004, 'perf_metric_type': 'LATENCY'}]
`

Previous:

image


so no visible perf gains.

**Comment by jjyao** [comment]
@rynewang is this ready for review?

**Comment by rynewang** [comment]
This PR did not have visible performance gains. Closing.

**Pull request closed without merging**
