### PR TITLE
Remove numpy for Ray wheel build

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

I don't think this is actually needed any more since Ray doesn't depend on numpy any more (it used to be that some of Ray's serialization code did, but that's not the case any more).

Follow up from https://github.com/ray-project/ray/pull/40399

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by aslonnie — COMMENTED** [review]
is this still relevant?

**Comment by can-anyscale** [comment]
Sorry I missed this for too long now that it has conflicts, this looks valid, @pcmoritz do you want to rebase and merge this

**Comment by pcmoritz** [comment]
Yeah, let's merge it if the tests pass :)

**Review by can-anyscale — APPROVED** [review]

**Pull request merged**
