### PR TITLE
[GCS]Add new message ReportResourceUsage

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?

We introduce a new message `ReportResourceUsage` that contains all fields in `HeartbeatTableData`, in order to splitting all resource related operations from heartbeat reporting.

## Related issue number

Part of https://github.com/ray-project/ray/issues/11825. In next pr we will implement the handlers and split `HeartbeatTableData`.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@WangTaoTheTonic I reverted the lightweight hearbeat PR. Does that impact the timeline of this PR?

I prefer you to merge the lightweight heartbeat PR again first.

**Comment by WangTaoTheTonic** [comment]
> @WangTaoTheTonic I reverted the lightweight hearbeat PR. Does that impact the timeline of this PR?
> 
> I prefer you to merge the lightweight heartbeat PR again first.

Reverting would not impact this PR but the global process. I agree to see if lightweight heartbeat has any problems first, then fix them if any.

**Comment by WangTaoTheTonic** [comment]
This one is not blocked since light heartbeat has been enabled.

**Comment by WangTaoTheTonic** [comment]
@rkooo567

**Comment by rkooo567** [comment]
@WangTaoTheTonic Will review by tonight.

**Review by rkooo567 — APPROVED** [review]

**Review by raulchen — APPROVED** [review]

**Pull request merged**
