### PR TITLE
[core] Task backend - increase worker side GC  limit to 100k

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
This should prevent data loss from worker side for most of the times. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Running releases tests here: https://buildkite.com/ray-project/release-tests-pr/builds/31846
- single_node
- microbenchmark
- stress_test_many_tasks

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Lmk if the release test result seems okay!

**Comment by rickyyx** [comment]
This is ready to merge: no active regressions with the master run on: https://buildkite.com/ray-project/release-tests-branch/builds/1460#_

**Comment by rickyyx** [comment]
image

**Pull request merged**
