### PR TITLE
GcsPublisher is being constructed with unsupported position argument

### PR DESCRIPTION
**Pull request by iamhatesz**
## Why are these changes needed?

To avoid this error:

```
(raylet) Traceback (most recent call last):
(raylet)   File "/home/iamhatesz/.pyenv/versions/alan-brain-py3.9/lib/python3.9/site-packages/ray/dashboard/agent.py", line 407, in <module>
(raylet)     gcs_publisher = GcsPublisher(args.gcs_address)
(raylet) TypeError: __init__() takes 1 positional argument but 2 were given
```

## Related issue number

None

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hmm how do we reproduce this? I wonder why this is not consistently happening?

**Review by mwtian — APPROVED** [review]
Thanks for fixing this!

**Comment by mwtian** [comment]
@iamhatesz CI errors can be fixed by merging / rebasing on master.

@rkooo567 Probably because this is only called when dashboard agent runs into an error, and we don't have test coverage here ..

**Comment by mwtian** [comment]
Adding @rkooo567 and @iycheng to help with merging.

**Pull request merged**
