### PR TITLE
[Ready for review] Support remote s3 package in runtime env 

### LINKED ISSUE #19412: runtime env to support s3 file path

### PR DESCRIPTION
**Pull request by jiaodong**
This PR only adds fetching existing s3 file path assuming user already uploaded working_dir files to s3 as a zip file.

## Notable changes:
- working_dir.py
  - Added S3 Protocol in existing working_dir.py
  - For s3 paths, it will deliberately skip all actual packaging, uploading, or check package existence in GCS. We always assume it's available as valid package on s3 and for now it's user's responsibility to upload the right files.
- test_runtime_env.py
  - Added a dummy task in driver script to kick off runtime env setup before using `test_module`, this is needed for proper s3 testing
  - Removed time.sleep(10) in driver script, it's kinda pointless and all existing tests still run with this.
  - Changed exception case to return stacktrace to STDOUT in driver script, so whoever needs to make runtime env changes can actually see useful errors.   

closes #19412 

## Changes Made
- Extended new Protocol enum in working_dir.py
- Added S3 downloading implementation in `fetch_package` while unzipping is the same 
- TODO: Add more tests and fix tests

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
Nice, this looks great. We will need to make some additional changes to do local ref counting / GC -- @architkulkarni do you think we should do it in this PR or a follow-up? I'm not sure how large the scope of that would be.

**Comment by jiaodong** [comment]
> Oh, @jiaodong I think you'll need to update this a little bit for it to work end-to-end, the s3 path needs to be put in the `uris` field of the runtime_env (this will go away, but for now it's how it works). Actually once we do that, the local ref counting/GC should work too.

> the s3 path needs to be put in the `uris` field of the runtime_env

Does this mean we need to change `rewrite_runtime_env_uris()` part that we're rewriting URI in job_config ?

**Review by edoakes — COMMENTED** [review]
I wonder if we can parametrize the existing working_dir tests to test dynamically gcs-uploaded and s3-downloaded? That way we can test all of the GC logic and such.

**Review by edoakes — COMMENTED** [review]
Looks good overall, just one small thing about using a single URI parsing utility and also wondering if some of these functions should be called at all on S3 paths. The second thing can be addressed in my other PR, no need to do it here.

**Review by edoakes — APPROVED** [review]

**Pull request merged**
