### PR TITLE
[Flaky]Try to fix flaky test: test_job_agent

### PR DESCRIPTION
**Pull request by Catch-Bull**
## Why are these changes needed?

Since the agent process will listen to the fixed port DEFAULT_DASHBOARD_AGENT_LISTEN_PORT, but the agent process on the last test may not exit in time (this is killing itself by observing whether the raylet is dead)

fix: try to find the process which listens to port DEFAULT_DASHBOARD_AGENT_LISTEN_PORT and kills this process to make sure the next test's agent can listen to port DEFAULT_DASHBOARD_AGENT_LISTEN_PORT

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]
Looks good to me!

**Comment by architkulkarni** [comment]
@Catch-Bull I got the following traceback consistently when running locally on Mac, do you mind taking a look? I'll trigger the Mac tests on CI to see if it happens there as well. (Mac tests don't run on PRs by default but they do run on every master commit, so if they start to fail we have to revert the PR)

```python-traceback
――――――――――――――――――――――――――――――――――――― ERROR at setup of test_job_log_in_multiple_node[ray_start_cluster_head0] ――――――――――――――――――――――――――――――――――――――

proc = <psutil._psosx.Process object at 0x7fbe5f9e8a00>

    @contextlib.contextmanager
    def catch_zombie(proc):
        """There are some poor C APIs which incorrectly raise ESRCH when
        the process is still alive or it's a zombie, or even RuntimeError
        (those who don't set errno). This is here in order to solve:
        https://github.com/giampaolo/psutil/issues/1044
        """
        try:
>           yield

../../../../python/ray/thirdparty_files/psutil/_psosx.py:365: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <psutil._psosx.Process object at 0x7fbe5f9e8a00>, kind = 'inet'

    @wrap_exceptions
    def connections(self, kind='inet'):
        if kind not in conn_tmap:
            raise ValueError("invalid %r kind argument; choose between %s"
                             % (kind, ', '.join([repr(x) for x in conn_tmap])))
        families, types = conn_tmap[kind]
        with catch_zombie(self):
>           rawlist = cext.proc_connections(self.pid, families, types)
E           ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo())

../../../../python/ray/thirdparty_files/psutil/_psosx.py:534: ProcessLookupError

During handling of the above exception, another exception occurred:

    @pytest.fixture
    def make_sure_dashboard_http_port_unused():
        for process in psutil.process_iter():
            should_kill = False
            try:
>               for conn in process.connections():

test_job_agent.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../../python/ray/thirdparty_files/psutil/__init__.py:1162: in connections
    return self._proc.connections(kind)
../../../../python/ray/thirdparty_files/psutil/_psosx.py:344: in wrapper
    return fun(self, *args, **kwargs)
../../../../python/ray/thirdparty_files/psutil/_psosx.py:534: in connections
    rawlist = cext.proc_connections(self.pid, families, types)
/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/contextlib.py:131: in __exit__
    self.gen.throw(type, value, traceback)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

proc = <psutil._psosx.Process object at 0x7fbe5f9e8a00>

    @contextlib.contextmanager
    def catch_zombie(proc):
        """There are some poor C APIs which incorrectly raise ESRCH when
        the process is still alive or it's a zombie, or even RuntimeError
        (those who don't set errno). This is here in order to solve:
        https://github.com/giampaolo/psutil/issues/1044
        """
        try:
            yield
        except (OSError, RuntimeError) as err:
            if isinstance(err, RuntimeError) or err.errno == errno.ESRCH:
                try:
                    # status() is not supposed to lie and correctly detect
                    # zombies so if it raises ESRCH it's true.
                    status = proc.status()
                except NoSuchProcess:
                    raise err
                else:
                    if status == _common.STATUS_ZOMBIE:
>                       raise ZombieProcess(proc.pid, proc._name, proc._ppid)
E                       psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=42352)
```

**Comment by architkulkarni** [comment]
Also, do you mind adding your fixture to `test_successful_job_status` and `test_failed_job_status` to see if you idea fixes the flakiness in `snapshot/tests/test_job_submission.py` as well? If you prefer I can do it in a separate PR.

**Comment by Catch-Bull** [comment]
> @Catch-Bull I got the following traceback consistently when running locally on Mac, do you mind taking a look? I'll trigger the Mac tests on CI to see if it happens there as well. (Mac tests don't run on PRs by default but they do run on every master commit, so if they start to fail we have to revert the PR)
> 
> ```
> ――――――――――――――――――――――――――――――――――――― ERROR at setup of test_job_log_in_multiple_node[ray_start_cluster_head0] ――――――――――――――――――――――――――――――――――――――
> 
> proc = <psutil._psosx.Process object at 0x7fbe5f9e8a00>
> 
>     @contextlib.contextmanager
>     def catch_zombie(proc):
>         """There are some poor C APIs which incorrectly raise ESRCH when
>         the process is still alive or it's a zombie, or even RuntimeError
>         (those who don't set errno). This is here in order to solve:
>         https://github.com/giampaolo/psutil/issues/1044
>         """
>         try:
> >           yield
> 
> ../../../../python/ray/thirdparty_files/psutil/_psosx.py:365: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <psutil._psosx.Process object at 0x7fbe5f9e8a00>, kind = 'inet'
> 
>     @wrap_exceptions
>     def connections(self, kind='inet'):
>         if kind not in conn_tmap:
>             raise ValueError("invalid %r kind argument; choose between %s"
>                              % (kind, ', '.join([repr(x) for x in conn_tmap])))
>         families, types = conn_tmap[kind]
>         with catch_zombie(self):
> >           rawlist = cext.proc_connections(self.pid, families, types)
> E           ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo())
> 
> ../../../../python/ray/thirdparty_files/psutil/_psosx.py:534: ProcessLookupError
> 
> During handling of the above exception, another exception occurred:
> 
>     @pytest.fixture
>     def make_sure_dashboard_http_port_unused():
>         for process in psutil.process_iter():
>             should_kill = False
>             try:
> >               for conn in process.connections():
> 
> test_job_agent.py:53: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> ../../../../python/ray/thirdparty_files/psutil/__init__.py:1162: in connections
>     return self._proc.connections(kind)
> ../../../../python/ray/thirdparty_files/psutil/_psosx.py:344: in wrapper
>     return fun(self, *args, **kwargs)
> ../../../../python/ray/thirdparty_files/psutil/_psosx.py:534: in connections
>     rawlist = cext.proc_connections(self.pid, families, types)
> /Users/archit/anaconda3/envs/ray-py38/lib/python3.8/contextlib.py:131: in __exit__
>     self.gen.throw(type, value, traceback)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> proc = <psutil._psosx.Process object at 0x7fbe5f9e8a00>
> 
>     @contextlib.contextmanager
>     def catch_zombie(proc):
>         """There are some poor C APIs which incorrectly raise ESRCH when
>         the process is still alive or it's a zombie, or even RuntimeError
>         (those who don't set errno). This is here in order to solve:
>         https://github.com/giampaolo/psutil/issues/1044
>         """
>         try:
>             yield
>         except (OSError, RuntimeError) as err:
>             if isinstance(err, RuntimeError) or err.errno == errno.ESRCH:
>                 try:
>                     # status() is not supposed to lie and correctly detect
>                     # zombies so if it raises ESRCH it's true.
>                     status = proc.status()
>                 except NoSuchProcess:
>                     raise err
>                 else:
>                     if status == _common.STATUS_ZOMBIE:
> >                       raise ZombieProcess(proc.pid, proc._name, proc._ppid)
> E                       psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=42352)
> ```

I modified the try ... except ..., it should work, Can you test it on mac?

**Comment by Catch-Bull** [comment]
> ~Also, do you mind adding your fixture to `test_successful_job_status` and `test_failed_job_status` to see if your idea fixes the flakiness in `snapshot/tests/test_job_submission.py` as well? If you prefer I can do it in a separate PR.~
> 
> Looks like it doesn't work ([buildkite.com/ray-project/oss-ci-build-pr/builds/6424#0184bffb-f7b7-48ea-abe7-713fd5010875/3334-3876](https://buildkite.com/ray-project/oss-ci-build-pr/builds/6424#0184bffb-f7b7-48ea-abe7-713fd5010875/3334-3876)), I'll continue the investigation for `snapshot/tests/test_job_submission.py` separately. But let me know if you have any ideas.

@architkulkarni  `make_sure_dashboard_http_port_unused ` should be placed first, it is used to kill the agent process launched by the last test case instead of the current test.I am going to fix it together in this PR

**Comment by architkulkarni** [comment]
> I modified the try ... except ..., it should work, Can you test it on mac?

It works now!

**Comment by architkulkarni** [comment]
> @architkulkarni `make_sure_dashboard_http_port_unused ` should be placed first, it is used to kill the agent process launched by the last test case instead of the current test.I am going to fix it together in this PR


Ah thanks, I wasn't thinking carefully about the order of execution of the fixtures.  I didn't know the order of the arguments was the order of executing the fixtures, good to know!

I'll leave it to you to do it together in this PR, thanks for the fix.

**Pull request merged**
