### PR TITLE
Container runtime env support (#40419)

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

Cherry pick of https://github.com/ray-project/ray/pull/40419.

This is a feature we want to get out for 2.9, quite a few OSS users are interested in trying it out (see [thread](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1699048167994279)). We want to reach out to users to try it out and gather feedback once it’s released in 2.9 (otherwise we will have to wait for 2.10). It’s also pretty low risk, the changes are confined to the `container` part of `runtime_env`, and most of the PR is actually adding tests.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by aslonnie** [comment]
this is a cherrypick; do not need my approval.

**Comment by zcin** [comment]
@zhe-thoughts @architkulkarni Could you review this cherry-pick?

**Comment by architkulkarni** [comment]
Thanks @zcin -- I just realized my approval is irrelevant for the process so I've stopped hitting approve for cherry picks. It just needs approval from @zhe-thoughts and a TL.

**Review by edoakes — APPROVED** [review]
One of the most widely-requested Serve features and want to get it out to get feedback.

The diff is large but mostly consists of newly-added tests and the changes are primarily confined to the scope of the `container` runtime_env plugin (which is broken without this changeset).

**Review by zhe-thoughts — APPROVED** [review]
Approved but let's carefully watch release tests

**Pull request merged**
