### PR TITLE
[clusters][docs] Provide urls to content, fix typos

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

There are a few spots in the clusters docs where we ask users to git clone either Ray or KubeRay to access a file.
This PR fixes this -- urls to the relevant release branches are supplied instead.
Often, you can just do `kubectl apply <url>` to deploy a config, rather than cloning and then applying.

**This PR also fixes several typos in deployment instructions.**

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — COMMENTED** [review]
Similar to the autoscaler wheels that have hard coded urls, is there a way to do this so that it links to nightly for the nightly docs/examples and release for the releases?

**Comment by DmitriGekhtman** [comment]
> Similar to the autoscaler wheels that have hard coded urls, is there a way to do this so that it links to nightly for the nightly docs/examples and release for the releases?

Maybe, but it could be tricky given that there are two repos involved.
I'm not sure which autoscaler wheels you're referring to, though -- could you link an example?

**Comment by wuisawesome** [comment]
This dude gets autochanged to a release wheel whenever a release happens https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/defaults.yaml#L127 

(it's a little easier in that case because it can be done via a simple find/replace)

**Comment by DmitriGekhtman** [comment]
> This dude gets autochanged to a release wheel whenever a release happens https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/defaults.yaml#L127
> 
> (it's a little easier in that case because it can be done via a simple find/replace)

Got it.

I think it's too complicated to do for now.

Also, I'm not sure if it's the right way to go -- we don't want people to _accidentally_ deploy from an unstable master commit. Users should have to very deliberately opt in to run nightly Ray on their cloud infra.

**Review by edoakes — APPROVED** [review]

**Review by richardliaw — APPROVED** [review]

**Pull request merged**
