### PR TITLE
[Do not merge] Test against gym master

### PR DESCRIPTION
**Pull request by amogkam**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jkterry1** [comment]
@amogkam Can you please rerun tests? Everything appears to have failed in one big transient error.

**Comment by amogkam** [comment]
We re-ran it again but looks like installing from master is timing out our CI system after 3 hours.

Is there another installation option we could try with?

**Comment by jkterry1** [comment]
@amogkam I just went ahead and released Gym 0.19.0. This PR is no longer necessary, but you should bump your internal version when possible.

**Comment by sven1977** [comment]
@jkterry1 , thanks for keeping us in the loop with this! We do update all dependencies' versions automatically via dependabot, so this should be fine.

**Comment by jkterry1** [comment]
@sven1977 FYI for the rllib maintainers because I don't know where to put this- Gym is deprecating monitor in the next release in a few weeks (see https://github.com/openai/gym/issues/2297, https://github.com/openai/gym/pull/2354, https://github.com/openai/gym/pull/2332, https://github.com/openai/gym/pull/2300, https://github.com/openai/gym/pull/2296)

**Pull request closed without merging**
