### PR TITLE
For a dataset comprised of both empty and non-empty blocks, let the non-empty blocks determine the schema

### LINKED ISSUE #22673: [Dataset][Bug] map_batches() handles the combining of results from empty and non-empty batches incorrectly
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

The map_batches() API of Dataset produces different results for the same input data, in these two conditions:
- There are no empty batch: the result is expected
- However when there are empty batch, the result is in different format

The expected behavior should be that the result is deterministic and the same, as long as we feed it the same input data.

Logs or how to reproduce (the first one produced a list expectedly, but the second one produced pyarrow table which is not expected):
>>> xs=[x % 3 for x in list(range(100))]
>>> xs
[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0]

>>> ds1=ray.data.from_items(xs).repartition(1).sort().map_batches(lambda x: x)
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

>>> ds2=ray.data.from_items(xs).repartition(30).sort().map_batches(lambda x: x)
>>> ds2.take_all()
[{'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}]

### Versions / Dependencies

Current code at head in Ray repo.

### Reproduction script

See the above section on how to reproduce.

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jianoaix**
## Why are these changes needed?

There is a bug in combining the results from map_batches: if we create two dataset out of the same data, but with different num of partitions, we may get different results when run the same map_batches() on them. That is, num of partitions is affecting the map_batches() results, which should not.

## Related issue number

Closes #22673 

## Checks

- [ Y] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ Y] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by naijoaix** [comment]
I realize I should have created a new branch for a different issue. The previous commit logs make it a bit messy.

**Review by clarkzinzow — APPROVED** [review]
Nice!

**Comment by naijoaix** [comment]
> Could you explain the root cause of the issue? Schema of empty block is wrong? Should we always set schema of empty block to None?

The schema for empty block is default to pyarrow (https://github.com/ray-project/ray/issues/22673#issuecomment-1051392319).

**Comment by jjyao** [comment]
If we don't want to trust the schema of empty block even if it's set, should we just set to None in the first place? Otherwise we will see inconsistent schemas for blocks in the same dataset?

**Comment by naijoaix** [comment]
The block is of type Union[List[T], "pyarrow.Table", "pandas.DataFrame", bytes], so even if it's empty, it already has a type and hence an implied the schema type.
Ideally if we know the output block type, we might pass it around and then use BlockBuilder.for_block_type(block_type).build() to create an empty one, which will have the right type and schema, even if it's empty. I was initial suggesting this in the comment linked above, but it looks we might not know the output type, so here we use non-empty block's schema.

**Review by jjyao — APPROVED** [review]

**Comment by ericl** [comment]
Seems tests are failing.

**Comment by naijoaix** [comment]
> Seems tests are failing.

Yeah. As I was working on fixing it, I realized that it is not feasible to rely on num_rows in block metadata to determine whether a block is empty. IIUC, we do not necessarily always know num_rows because we employ lazy execution/lazy data loading.

**Pull request merged**
