### PR TITLE
Separate raylet path and non-raylet path in python common extension.

### PR DESCRIPTION
**Pull request by eric-jj**
There are too much use_raylet switch in the code for different code path in the raylet and non-raylet setting. It mix the logical and data for the two paths together.
In the PR, I separate the data and logical to the two classes(RayletTask and NonRayletTask) and use polymorphism to call raylet and non-raylet code path in python common extension. 
The change is a AA change, I don't change the logical in the PR.
It will make the code more readable and maintainable. If we want to totally disable the non-raylet path, we can simply remove the NonRayletTask directly.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@pcmoritz can you take a look? As discussed in https://github.com/ray-project/ray/pull/2180#issuecomment-394135692, this code is all going away, so I think it would be simplest to avoid changing it much now. I agree this part of the code is very messy at the moment, but that should change.

**Comment by eric-jj** [comment]
@robertnishihara I agree to remove the old path, but the current java worker are using the non raylet code path. Even the whole ray switch to use the raylet, we still need some time to migrate the java worker to the new raylet code path. And for the internal version in the ant finance, we still use the old code path, we need some time to migrate to the raylet also, I don't think it is a short term change.

**Comment by robertnishihara** [comment]
@eric-jj, I see. The "raylet" and "non-raylet" C++ client APIs should be very similar, so I'm hopeful that transitioning the Java code will go smoothly, but we'll see I guess.

**Comment by eric-jj** [comment]
@robertnishihara the raylet and non-raylet c++ client API change is simple, but not only the c++ client change, the main change is in the java side. The if use_raylet switches are more common in python code than c++ code. We need many change in the java code also.

**Comment by robertnishihara** [comment]
That's a good point, it won't be completely trivial and it will involve some changes on the Java side.

**Comment by robertnishihara** [comment]
Closing because the non-raylet backend has been deprecated.

**Pull request closed without merging**
