### PR TITLE
[scheduler] Fix dynamically increasing resources

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This PR fixes a scheduler bug in which we increased the total resource instances, but don't update the total capacity in the non-instance view.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Good catch. Seems this might affect placement group (e.g., two placement bundles added to the same node?) cc @rkooo567 @scv119

**Comment by wuisawesome** [comment]
cc @rkooo567 @chenk008  maybe this is related to placement group issues?

**Comment by rkooo567** [comment]
Maybe not? Looks like code change is only applied to predefined resources (so the placement group doesn't use pre-defined resources), but I could be wrong.

**Comment by chenk008** [comment]
cc @clay4444

**Pull request merged**
