### PR TITLE
[Core] Update job id to hex in JOB_LOG_PATTERN (#20612)

### LINKED ISSUE #20612: [Bug] Pid=None after running multiple jobs
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I have one python script written with ray. There are one actor class and multiple task functions in that script, and gpus are used. When I run my script with different parameters, the first to the third jobs would generate logging information normally and they all have their corresponding pid printed. However, when more jobs are started with the same script, the later jobs will all have pid=None, and their logging output will spam all running shells, which is very annoying.

### Versions / Dependencies

ray                       1.8.0                    pypi_0    pypi
ray-cpp                   1.8.0                    pypi_0    pypi

### Reproduction script

I'm sorry I can't provide a reproduction script as it is quite private.

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xychu**
## Why are these changes needed?

While sharing one ray cluster with multi jobs, we found some remote tasks logs got mixed together.

Also: https://discuss.ray.io/t/worker-logs-are-sent-to-multiple-clients/3715

After some dig, I found it was happend at [`print_logs`](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L479-L482)
and when `job_id` is `None`, and the invalid `job_id` comes from a [wrong pattern](https://github.com/ray-project/ray/blob/master/python/ray/_private/log_monitor.py#L166-L172)

## Related issue number

Closes #20612

cc @rkooo567 seems you already have some work related. #19974 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Oh interesting. Thanks a lot for the pr! 

Is it possible to add a unit test for this? Did you happen to find the repro?

**Comment by xychu** [comment]
> Is it possible to add a unit test for this? Did you happen to find the repro?

Yeah, as long as Job [hex id](https://github.com/ray-project/ray/blob/master/src/ray/raylet/worker_pool.cc#L329) contains [a-f] it will cause the re match failed and all the logs of this job will send out to other drivers in [`print_logs`](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L479-L482).

Do we also need to change `print_logs` to make it work for future possible `None` job_id?

```python
                # Don't show logs from other drivers.
                if (self.filter_logs_by_job and data["job"]
                        and job_id_hex != data["job"]):
                    continue
```
to
```python
                # Don't show logs from other drivers.
                if (self.filter_logs_by_job and "job" in data
                        and job_id_hex != data["job"]):
                    continue
```

As regards to unit test, I'm not sure which level to test, cause the whole problem involves worker and job_monitor, also Job ID hex generating rule and pubsub of the logs.
But the root cause/fix just a pattern update :-)

**Comment by rkooo567** [comment]
> Do we also need to change print_logs to make it work for future possible None job_id?

Would the new code work? IIUC, if "job" is not contained in `data`, it should raise an exception, so I think the problem was that data["job"] was None. Maybe we should do `data["job"] is not None` instead? 

But I think it's probably better not doing this. pid=None is bad, but it is better than losing logs I think.. (and pid=None should be a bug. Maybe we can have a strong assert in log monitor instead).

> As regards to unit test, I'm not sure which level to test, cause the whole problem involves worker and job_monitor, also Job ID hex generating rule and pubsub of the logs.

Maybe having a test on python test is fine. Do you know the condition where job id contains non numeric values? If so, we can just keep creating drivers until that point and make sure log messages don't print pid=None.

**Review by rkooo567 — APPROVED** [review]

**Comment by xychu** [comment]
@rkooo567 test added.

**Comment by rkooo567** [comment]
Thanks for the contribution :)!!!

**Pull request merged**
