### PR TITLE
[tune][WIP] Sigopt Integration

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
Provides a wrapper around Sigopt.

This is WIP.

### CODE REVIEW

**Comment by richardliaw** [comment]
Current benchmark for sigopt using 50 trials - 

screenshot 2018-02-21 09 13 20

**Comment by richardliaw** [comment]
Benchmark for random search: 
screenshot 2018-02-20 10 58 25

**Comment by richardliaw** [comment]
Tried random search again: 
screenshot 2018-02-21 09 33 14

**Comment by robertnishihara** [comment]
@richardliaw still in progress or should we close this?

**Comment by richardliaw** [comment]
Closing for now.

**Pull request closed without merging**
