### PR TITLE
[WIP] [Placement Group] resizing placement group feature part1: dynamic add bundles.

### LINKED ISSUE #16403: [RFC] [Placement Group] Resizing feature API.
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

Hello guys, I want to add the resizing feature for the placement group as we talked about before, This API would like this:

```
def test_placement_group_add_bundles_api_basic(ray_start_cluster):
    @ray.remote(num_cpus=2)
    class Actor(object):
        def __init__(self):
            self.n = 0

        def value(self):
            return self.n

    cluster = ray_start_cluster
    cluster.add_node(num_cpus=4)
    ray.init(address=cluster.address)

    # Create a infeasible placement group first.
    infeasible_placement_group = ray.util.placement_group(
        name="name", strategy="PACK", bundles=[{
            "CPU": 8
        }])
    assert not infeasible_placement_group.wait(4)
    # Make sure the add bundles request will fail since it is pending now.
    with pytest.raises(
            ray.exceptions.RaySystemError,
            match="the placement group is in scheduling now"):
        infeasible_placement_group.add_bundles([{"CPU": 2, "memory": 50 * MB}])

    # Remove the infeasible placement group.
    ray.util.remove_placement_group(infeasible_placement_group)

    def is_placement_group_removed():
        table = ray.util.placement_group_table(infeasible_placement_group)
        if "state" not in table:
            return False
        return table["state"] == "REMOVED"

    wait_for_condition(is_placement_group_removed)

    # Create a feasible placement group now.
    placement_group = ray.util.placement_group(
        name="name", strategy="PACK", bundles=[{
            "CPU": 2
        }])

    # Wait for the placement group to create successfully.
    assert placement_group.wait(5)

    placement_group.add_bundles([{"CPU": 2,}])
    table = ray.util.placement_group_table(placement_group)
    assert len(list(table["bundles"].values())) == 2
    assert table["state"] == "CREATED"

    # Wait for the add new bundles operation to finish.
    assert placement_group.wait(5)

    # Schedule an actor through the new bundle index.
    actor = Actor.options(
        placement_group=placement_group,
        placement_group_bundle_index=1).remote()

    ray.get(actor.value.remote())
```

BTW, you can also replace the `wait(timeout)` API with the `ready()` API if you want.

Also, the related proposal document is here:  [API proposal](https://docs.google.com/document/d/1OHO0XkwMBFHXGiCrz45FfBjCGTIARs0OfFHQmIs2LAY/edit?usp=sharing)

Please leave comments if you have any requirements or questions, Thx!

### PR DESCRIPTION
**Pull request by clay4megtr**
## Why are these changes needed?

resizing placement group feature part1: dynamically add bundles.

the design doc [API proposal](https://docs.google.com/document/d/1OHO0XkwMBFHXGiCrz45FfBjCGTIARs0OfFHQmIs2LAY/edit?usp=sharing)

Note that there is **a new update** at the end of the document.

Python integration tests will be added later.

## Related issue number
Closes #16403

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@clay4444 still planning to contribute to this? We are planning to start integrating this feature.

**Comment by clay4444** [comment]
> Member

Yeah, sure, Let me resolve the conflict firstly

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by rkooo567** [comment]
cc @edoakes

**Comment by clay4444** [comment]
sorry, Sang, @rkooo567 , The pub-sub module was refactored too much, Do you know how can I configure enable Redis pub-sub for the test case?

**Comment by rkooo567** [comment]
Hey @clay4444 this has slipped for some reasons. 

I think you need to set

Screen Shot 2022-03-07 at 3 17 54 PM

false, 'redis', false

cc @mwtian can you confirm if this is right?

**Comment by mwtian** [comment]
Redis pubsub is no longer supported. Ray only supports external Redis KV now. I guess we need a guide for adding new topics to Ray pubsub.

**Comment by wuisawesome** [comment]
Hey @clay4444 how will this PR work with the autoscaler? Can we make sure we understand the plan for how this will work with autoscaling before merging?

**Comment by mwtian** [comment]
This is an example of adding a channel to Ray pubsub: https://github.com/ray-project/ray/pull/20075/files

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Comment by rkooo567** [comment]
It's not stale

**Pull request closed without merging**
