### PR TITLE
Limiting numpy version to below 1.24.0

### LINKED ISSUE #31193: [CI] `windows://python/ray/tests:test_numba` is failing/flaky on master.
- 49b1ed180d0447bcfd82d819bc1d37ef024afbab FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1591#01852ac1-d82b-403a-84c9-bcf66e8b0f2c)
- 9bb62fbe30910078885faaf51b9172a1042e9117 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1590#01852a63-93b9-4e20-9f12-be23457fb417)
- d28552b7b61b4ba74563d7710fdd6b5562fe73a2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1589#01852a62-baeb-4ebd-b955-3b2daba42b3a)
- 608276bb96b5b49769cd8816414c280c5431d843 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1588#01852a5b-f1f3-49c5-bf91-72b9be8f9253)
- c03c4c67182d7f79d36465f2ffbef88b2b958afb FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1587#01852a30-52c8-4cca-93c7-590cc27d4acd)
- 24b6a8035aa2afac641024d4d6664b6c066f6d20 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1586#01852a25-8d20-4a73-8d6f-2a0350b7908f)
- 70b0d039da09cb35f5b4584e5a9603643cf29757 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1585#01852a24-6506-4d23-af8e-d6459c7ce41e)
- 98fef7732852cdb3e9377cd87c1ee1085b894928 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1584#018529b1-d575-4051-8dc7-2d023a28d8d0)
- 69b2506c281c777c44980c376497bc2a8d2ad051 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1583#018529b1-9831-4a55-a797-613abb294a97)
- 8f499013de9c7beaf7bf5537a70aaa8bf0322203 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1582#018528ce-12a0-43fb-9d9b-bc3182fafeb8)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_numba-END
....

### LINKED ISSUE #31194: [CI] `windows://python/ray/tests:test_tensorflow` is failing/flaky on master.
- 49b1ed180d0447bcfd82d819bc1d37ef024afbab FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1591#01852ac1-d82e-439e-8aa1-da969ff836d0)
- 9bb62fbe30910078885faaf51b9172a1042e9117 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1590#01852a63-93ba-41cb-8fde-ed2c5e9cdc01)
- d28552b7b61b4ba74563d7710fdd6b5562fe73a2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1589#01852a62-baec-4422-aea0-d2cfec5490dc)
- 608276bb96b5b49769cd8816414c280c5431d843 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1588#01852a5b-f1f4-48b5-b195-53148d709617)
- c03c4c67182d7f79d36465f2ffbef88b2b958afb FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1587#01852a30-52c9-4481-b1b8-908139932d78)
- 24b6a8035aa2afac641024d4d6664b6c066f6d20 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1586#01852a25-8d21-43be-82b0-6e8f47ffa553)
- 70b0d039da09cb35f5b4584e5a9603643cf29757 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1585#01852a24-6506-4eb4-bf7a-7da323c4c791)
- 98fef7732852cdb3e9377cd87c1ee1085b894928 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1584#018529b1-d576-45d5-af44-815b73ba0b90)
- 69b2506c281c777c44980c376497bc2a8d2ad051 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1583#018529b1-9831-468d-86be-3adc5289bcce)
- 8f499013de9c7beaf7bf5537a70aaa8bf0322203 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1582#018528ce-12a1-426e-979c-40cc5c7c2ff4)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_tensorflow-END
....

### PR DESCRIPTION
**Pull request by cadedaniel**
numpy 1.24.0 [expires some existing deprecations](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations), which cause existing datasets code to fail. Until https://github.com/ray-project/ray/issues/31182 is fixed and we verify all tests pass with the newest numpy, we need to limit the numpy version to <1.24.0.

Closes https://github.com/ray-project/ray/issues/31193
Closes https://github.com/ray-project/ray/issues/31194

### CODE REVIEW

**Comment by pcmoritz** [comment]
If this only impacts windows, can you only introduce the constraint for windows? Upper version bounds are very disruptive :)

**Comment by cadedaniel** [comment]
It will break across all platforms, our windows CI is the first to encounter the version. cc @clarkzinzow there's a thread on this in runtime channel

**Comment by cadedaniel** [comment]
Removing this bound is possible but we need to fix https://github.com/ray-project/ray/issues/31182 first

**Comment by clarkzinzow** [comment]
A few spots where we might want to add this upper bound:
- AIR getting started - `pip install ray[air]` should cause a `numpy` version to be installed that respects that upper bound, but `pip install -U numpy>=1.19.5` will upgrade it beyond that upper bound: https://github.com/ray-project/ray/blob/f4b315705273e266268f8b92537b183823459ff5/doc/source/ray-air/getting-started.rst?plain=1#L71
- Datasets nightly tests app config - `pip install ray` will install `numpy < 1.24.0`, but the following `pip install -U numpy>=1.20` will upgrade it beyond that upper bound: https://github.com/ray-project/ray/blob/f4b315705273e266268f8b92537b183823459ff5/release/nightly_tests/dataset/app_config.yaml#L16

**Comment by pcmoritz** [comment]
Sounds good -- the pin in `setup.py` is particularly problematic -- let's make sure https://github.com/ray-project/ray/issues/31182 is fixed and the pins removed before the Ray 2.3 release :)

**Comment by cadedaniel** [comment]
The minimal tests are failing with the following error. Does anyone know a fix?
```
Traceback (most recent call last):
File "/opt/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", l...)
pkg_resources.DistributionNotFound: The 'numpy<1.24.0,>=1.16' distribution was not found and is required by ray
```

**Comment by cadedaniel** [comment]
> The minimal tests are failing with the following error. Does anyone know a fix?
> 
> ```
> Traceback (most recent call last):
> File "/opt/miniconda/lib/python3.8/site-packages/pkg_resources/__init__.py", l...)
> pkg_resources.DistributionNotFound: The 'numpy<1.24.0,>=1.16' distribution was not found and is required by ray
> ```

Looks like minimal install has a separate line which does `pip install -U numpy` without bounds. I removed it, will see what happens.

**Comment by cadedaniel** [comment]
Waiting for mac tests, all other tests look fine (one failure is a flaky rllib memory leak, another is the flaky memory monitor test https://github.com/ray-project/ray/issues/29702).

**Comment by cadedaniel** [comment]
All tests passed! Can we get this merged?

**Review by clarkzinzow — APPROVED** [review]

**Comment by edoakes** [comment]
@cadedaniel can you please file a follow-up issue to remove this bound and mark it as a release-blocker so we don't miss this for 2.3 release?

**Comment by cadedaniel** [comment]
> @cadedaniel can you please file a follow-up issue to remove this bound and mark it as a release-blocker so we don't miss this for 2.3 release?

Good call, created https://github.com/ray-project/ray/issues/31277. Let's wait on merging, Eric is thinking it might be better to just remove the tests / fix the 10 non-test non-doc usages of the broken APIs. Will wait for him to approve.

**Comment by ericl** [comment]
I'm against adding this version pin--- I think we could resolve the situation better by raising a runtime exception (or fixing the issue), since this is only impacting a niche use case. Pinning numpy has a much larger blast radius on Ray users in general.

**Comment by clarkzinzow** [comment]
>since this is only impacting a niche use case

@ericl This isn't just the ragged tensor use case, e.g. RLlib uses some of the hard-deprecated dtypes like `np.int` and `np.bool` in its library code (not just the test code).

- https://github.com/ray-project/ray/blob/d750c5cef22477cea7c54132523073b273e87db1/rllib/utils/numpy.py#L471
- https://github.com/ray-project/ray/blob/d750c5cef22477cea7c54132523073b273e87db1/rllib/env/wrappers/dm_control_wrapper.py#L49
- https://github.com/ray-project/ray/blob/d750c5cef22477cea7c54132523073b273e87db1/rllib/algorithms/alpha_zero/mcts.py#L28
- https://github.com/ray-project/ray/blob/d750c5cef22477cea7c54132523073b273e87db1/rllib/utils/pre_checks/env.py#L671

I'm fine with not adding this upper bound, just want to make it clear that it's not just a niche Datasets/AIR use cases that's impacted here.

**Comment by ericl** [comment]
Thanks, that makes sense. We can pretty simply fix the use of np.int and np.bool though right?

**Comment by clarkzinzow** [comment]
@ericl Yes, all of the known breaks should essentially amount to a find + replace. But we won't know the full blast radius of the release until we have the full ecosystem CI suite running on NumPy 1.24 (i.e. running on Python 3.8, since Python 3.7 was dropped in NumPy 1.22).

**Comment by afzalmushtaque** [comment]
Numpy 1.24 also introduced [changes](https://github.com/numpy/numpy/compare/v1.23.5...v1.24.0) to serialization of random number generators that breaks ray's deserialization logic when used with RLLIB remote workers. 
Specifically, Ray workers are not able to deserialize random number generators associated with openai gym's [space ](https://github.com/openai/gym/blob/master/gym/spaces/space.py)class which are used for random sampling of observation/action space
See #31293 for more details about this issue.

**Comment by krfricke** [comment]
It looks like the aliases haven't been supported for a long time, so we should fix the code occurrences in any case: https://github.com/ray-project/ray/pull/31329

We do keep a legacy test suite to test our lower bound of compatibilities. It seems like this particular regression is limited by us using Python 3.7 everywhere. We could introduce a "cutting edge" test suite that runs some tests on e.g. Python 3.10. Would that help alleviate problems like this in the future?

**Comment by cadedaniel** [comment]
> It looks like the aliases haven't been supported for a long time, so we should fix the code occurrences in any case: #31329
> 
> We do keep a legacy test suite to test our lower bound of compatibilities. It seems like this particular regression is limited by us using Python 3.7 everywhere. We could introduce a "cutting edge" test suite that runs some tests on e.g. Python 3.10. Would that help alleviate problems like this in the future?

Nice idea! We do something like this in core with minimal install tests where all dependencies are unbounded. Also, if we turn on pytest warnings we should see test failures for these DeprecationWarnings and can file issues ahead-of-time. Can you take a look at [this doc](https://docs.google.com/document/d/1TVMfmhO0vD1MdkVrqRS9t4om2shMTY9nqdqqOopNv0M/edit#) and add any comment?

**Comment by krfricke** [comment]
I think we can close this PR, right?

#31394 and #31194 fixed the failing tests

**Pull request closed without merging**
