### PR TITLE
[CI] Filter release tests by attr regex

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
Support filtering tests by test attr regex filters. Multiple filters can be specified with one line for each filter. The format is `attr:regex` (e.g. team:serve)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — CHANGES_REQUESTED** [review]
These filters should be unit tested (there are tests for the test name filter).

Additionally, I don't think we should introduce more filter fields, but rather should extend our existing filter field to more options. I've raised this offline, but my proposal would be something like this:

```
filters = filter_str.split(" ")
for filter in filters:
    if filter.startswith("name:"):
        value = filter[5:]
        apply_filters = NameFilter(value)
    elif filter.startswith("team:"):
        value = filter[5:]
        apply_filters = TeamFilter(value)
    # ...
    else:
        # Default (no prefix): name regex
        apply_filters = NameRegexFilter(filter)  # or `NameFilter(value, regex=True)`
```

For each test we can then loop through the apply_filters and only proceed if all match. Regular filters would be `in` filters, i.e. `name:xgboost` should match `xgboost_train_small` and also `tune_xgboost_sweep`. We don't need regex support for groups and teams (or we could introduce something like `team+:team_regex` or so).
Name regex filter should work like right now as a regex match (not search). This is useful to keep backwards compatibility but also to allow e.g. specifying several tests, e.g. via `long_running_many_drivers|tune_network_throughput` which currently works.

Let's discuss this before proceeding with this PR.

**Comment by jjyao** [comment]
Changed to `\n` delimited `attr:regex` format

**Review by krfricke — APPROVED** [review]
This looks great!
After merging this, can you update the buildkite pipeline?

**Comment by jjyao** [comment]
Yes! Since it's backward compatible, we can merge this PR first.

**Pull request merged**
