### PR TITLE
[RLlib] Cast rewards as tf.float32 to fix error in DQN in tf2

### LINKED ISSUE #28382: [RLlib] DQN, Apex-DQN, SimpleQ fail with tf2
### What happened + What you expected to happen

When using DQN, ApexDQN, or SimpleQ with tf2, the computation of `q_t_selected_target` in `model.loss()` fails with the error message `cannot compute AddV2 as input #1(zero-based) was expected to be a int64 tensor but is a float tensor [Op:AddV2]`. This seems to be the same issue as in #14736, but also happens with online training. I have verified this happens with DQN, Apex-DQN and SimpleQ, but there might be other algorithms affected. PG methods don't seem affected.

### Versions / Dependencies

ray==2.0.0

### Reproduction script
```
# From CLI:
rllib train --run DQN --env Taxi-v3 --framework=tf2

# Or in Python, to run Apex without a GPU:
from ray.rllib.algorithms.apex_dqn import ApexDQN as algorithm

config = {
    "env": "Taxi-v3",
    "framework": "tf2",
    "num_gpus": 0,
    "num_workers": 1,
}

algo = algorithm(config=config)

for _ in range(3):
    print(algo.train())
```
### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by mgerstgrasser**
Signed-off-by: mgerstgrasser <matthias@gerstgrasser.net>

## Why are these changes needed?

DQN, Apex-DQN and SimpleQ all fail when using tf2.

## Related issue number

Closes #28382

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by gjoliver** [comment]
which env do these fail with??
if it's a common gym env, can you help add a unit test?
I also wonder if this is the best place to do the cast. theoretically, if we cast this column in SampleBatch, it will benefit all algorithms?

**Comment by mgerstgrasser** [comment]
> which env do these fail with?? if it's a common gym env, can you help add a unit test? I also wonder if this is the best place to do the cast. theoretically, if we cast this column in SampleBatch, it will benefit all algorithms?

See the issue I opened for a reproduction script: https://github.com/ray-project/ray/issues/28382
I tested using Taxi-v3 from Gym, but it's also happening in my own custom environments. What would a unit test for this look like?

The `dones` are already cast in the same place in the DQN policy, and where I put it in SimpleQ mirrors where a previous PR put it in SAC (see #14736 ). So I assumed these were the right places to do the casts, but open to suggestions of course. In `SampleBatch` we would have to differentiate between torch and tf though, right?

**Comment by gjoliver** [comment]
I see, you are right, we should just follow however DONES are casted right now.
if Taxi-v3 can trigger this exception, can you add a simplest run in this file:
https://github.com/ray-project/ray/blob/master/rllib/algorithms/dqn/tests/test_dqn.py#L24
following test_dqn_compilation example?
make sure the error is triggered without your fix, and fixed after your fix.
thanks.

**Comment by mgerstgrasser** [comment]
> I see, you are right, we should just follow however DONES are casted right now. if Taxi-v3 can trigger this exception, can you add a simplest run in this file: https://github.com/ray-project/ray/blob/master/rllib/algorithms/dqn/tests/test_dqn.py#L24 following test_dqn_compilation example? make sure the error is triggered without your fix, and fixed after your fix. thanks.

Got it. Do we want a new test case for this? I could also switch the existing one to Taxi-v3. 

It seems that Taxi triggers this but Cartpole doesn't (in the current test case) - looks like the difference is that Cartpole returns float rewards, and Taxi returns integer rewards

**Comment by gjoliver** [comment]
> > I see, you are right, we should just follow however DONES are casted right now. if Taxi-v3 can trigger this exception, can you add a simplest run in this file: https://github.com/ray-project/ray/blob/master/rllib/algorithms/dqn/tests/test_dqn.py#L24 following test_dqn_compilation example? make sure the error is triggered without your fix, and fixed after your fix. thanks.
> 
> Got it. Do we want a new test case for this? I could also switch the existing one to Taxi-v3.
> 
> It seems that Taxi triggers this but Cartpole doesn't (in the current test case) - looks like the difference is that Cartpole returns float rewards, and Taxi returns integer rewards

yep. I saw it too.
let's add a new test case and some comments to point out the difference of the test cases?

**Comment by mgerstgrasser** [comment]
> > > I see, you are right, we should just follow however DONES are casted right now. if Taxi-v3 can trigger this exception, can you add a simplest run in this file: https://github.com/ray-project/ray/blob/master/rllib/algorithms/dqn/tests/test_dqn.py#L24 following test_dqn_compilation example? make sure the error is triggered without your fix, and fixed after your fix. thanks.
> > 
> > 
> > Got it. Do we want a new test case for this? I could also switch the existing one to Taxi-v3.
> > It seems that Taxi triggers this but Cartpole doesn't (in the current test case) - looks like the difference is that Cartpole returns float rewards, and Taxi returns integer rewards
> 
> yep. I saw it too. let's add a new test case and some comments to point out the difference of the test cases?

Done. I've added a new test case and left a comment to explain the difference. Verified locally that the new test fails without this fix. (See here for test without bugfix: https://github.com/mgerstgrasser/ray/tree/test_dqn_bugfix_tf2 )

**Review by gjoliver — APPROVED** [review]
thanks. I will find someone to merge this.

**Comment by mgerstgrasser** [comment]
> thanks. I will find someone to merge this.

Amazing. Thank you!

**Pull request merged**
