### PR TITLE
Clarify that Ray is not yet retrying to connect.

### PR DESCRIPTION
**Pull request by dHannasch**
## Why are these changes needed?

Now that the warning specifies where Ray is trying to connect to (https://github.com/ray-project/ray/pull/11916), it is possible to check on the connection, but since `RayConfig::instance().redis_db_connect_wait_milliseconds()` can be nontrivial, this also makes it worth clarifying that Ray is actually going to sleep for a bit before retrying.
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
This also seems to fail `test_ray_init`

**Comment by dHannasch** [comment]
Actually, it looks like the failure is stemming from https://github.com/ray-project/ray/pull/11893, which is *weird* because the same test passed on https://github.com/ray-project/ray/pull/11893 itself: https://travis-ci.com/github/ray-project/ray/jobs/434064778
```
//python/ray/tests:test_ray_init                                         PASSED in 11.1s
```
But now we're getting a redis.exceptions.ResponseError instead of the expected redis.exceptions.AuthenticationError.

**Comment by dHannasch** [comment]
https://github.com/ray-project/ray/pull/12024

**Comment by dHannasch** [comment]
I think https://github.com/ray-project/ray/pull/12024 is what's blocking this, so I'm going to go ahead and remove the author-action-required label from this one, if that's okay? I think once https://github.com/ray-project/ray/pull/12024 is settled this will be able to go.

**Comment by dHannasch** [comment]
@richardliaw 

Before: "Could not establish connection to Redis 123.456.78.910:6379 (context.err = 1), retrying."

After: "Could not establish connection to Redis 123.456.78.910:6379 (context.err = 1), will retry in 100 milliseconds."

**Pull request merged**
