### PR TITLE
Add TypeAlias annotations to RLlib typing.py (requires typing_extensions for Python<3.10)

### LINKED ISSUE #28383: [RLlib] Use TypeAlias throughout typing.py to prevent mypy errors
### What happened + What you expected to happen

In newer version of python, type aliases (e.g., where you do `TrainerConfigDict = dict`) have to be explicitly defined as a TypeAlias (e.g., `TrainerConfigDict: TypeAlias = dict`). Not doing this will cause MyPy to error (see [here](https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases)). For instance, if you save the reproduction script as `test.py` and run `mypy test.py`, it gives the output
```
test.py:7: error: Value of type AlgorithmConfigDict? is not indexable
test.py:8: note: Revealed type is "AlgorithmConfigDict?"
Found 1 error in 1 file (checked 1 source file)
```
If I manually change the line in `typing.py` to `AlgorithmConfigDict: TypeAlias = dict`, then it works fine:
```
test.py:8: note: Revealed type is "builtins.dict[Any, Any]"
Success: no issues found in 1 source file
```

I'm happy to submit a PR but the issue is that `TypeAlias` is only in newer versions of Python (3.10+). It has been backported through `typing-extensions`—does RLlib already have `typing-extensions` as a dependency? If so, I'm happy to implement this and submit a PR. Otherwise, what do you think is the right course of action?

### Versions / Dependencies

 * Python 3.9.7
 * Ray/RLlib 2.0.0
 * MyPy 0.971

### Reproduction script

```
import ray.rllib.algorithms.ppo as ppo

config = ppo.DEFAULT_CONFIG.copy()
algo = ppo.PPO(config=config, env="CartPole-v0")

algo.get_policy().config["num_workers"]
reveal_type(algo.get_policy().config)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by cassidylaidlaw**
## Why are these changes needed?

In newer versions of python, type aliases (e.g., where you do TrainerConfigDict = dict) have to be explicitly defined as a TypeAlias (e.g., TrainerConfigDict: TypeAlias = dict). Not doing this will cause MyPy to error (see [here](https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases)). For instance, take the following script:
```python3
import ray.rllib.algorithms.ppo as ppo

config = ppo.DEFAULT_CONFIG.copy()
algo = ppo.PPO(config=config, env="CartPole-v0")

algo.get_policy().config["num_workers"]
reveal_type(algo.get_policy().config)
```
If we save this to `test.py` and run `mypy test.py`, it complains:
```
test.py:7: error: Value of type AlgorithmConfigDict? is not indexable
test.py:8: note: Revealed type is "AlgorithmConfigDict?"
Found 1 error in 1 file (checked 1 source file)
```
However, with this PR, now the output is:
```
test.py:8: note: Revealed type is "builtins.dict[Any, Any]"
Success: no issues found in 1 source file
```

**Note:** this requires adding the `typing_extensions` dependency for Python 3.8 and 3.9 (it was previously only required for Python 3.7). This is because TypeAlias was only added to the standard library in Python 3.10. `typing_extensions` has backported it to earlier versions.

## Related issue number

Closes #28383.

Replaces #28386 which was reverted in #28862 due to breaking changes.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by cassidylaidlaw** [comment]
It looks like all tests are passing except `test_cli`, which is flakey in other commits. Can somebody review this?

**Comment by gjoliver** [comment]
RLlib changes seem fine.
can somebody help review the version change in setup.py? looks like typing.TypeAlias is available only from 3.10.

**Comment by cassidylaidlaw** [comment]
@gjoliver and others is there any update on this PR? It would be great to get it merged to stop all the errors from mypy in newer Python versions.

**Comment by ollie-iterators** [comment]
bump

**Comment by cassidylaidlaw** [comment]
@sven1977 @gjoliver this PR has been sitting around for a while, is there anything I can do to help it get merged? It would be great to be able to type check against RLlib without mypy giving a million errors.

**Comment by cassidylaidlaw** [comment]
Can anyone look over and/or merge? @sven1977 @gjoliver @avnishn @ArturNiederfahrenhorst @smorad @maxpumperla @kouroshHakha @krfricke @richardliaw @ericl @edoakes

**Comment by cassidylaidlaw** [comment]
I don't understand why this PR hasn't received any attention in several months. This is still causing me (and I'm sure others too) constant type errors unless I provide my own type annotations for RLlib.

**Comment by kouroshHakha** [comment]
Hey @cassidylaidlaw, I just noticed this now. But there are a couple of concerns with this PR:

1. The use of DEFAULT_CONFIG dict API is deprecated anyways in the newer versions of ray. You should use AlgorithmConfig objects instead. So your example becomes:

```
from ray.rllib.algorithms.ppo import PPOConfig

config = PPOConfig()
algo = config.build(env="CartPole-v0")

algo.get_policy().config["num_workers"]
reveal_type(algo.get_policy().config)
```

When I ran `mypy test.py` on this code it DID NOT give any errors and printed the following:

```
test.py:7: note: Revealed type is "Any"
Success: no issues found in 1 source file
```

2. This PR addresses something very specific to using mypy on top of ray and the weird usage of reveal_type() which as far as I know is not a built-in python function. mypy is a static type checker and we do not claim supporting it, and I don't see any reason that we should. This change may have implications for running ray in our product, and we do not want that to happen. 

Thanks for your contribution, and I hope you understand the decision factors here.

**Comment by cassidylaidlaw** [comment]
Thanks for your response.

It does seem like since I opened the PR more than 6 months ago mypy has updated and no longer gives an error for missing TypeAlias annotations. However, TypeAlias annotations are not a mypy-specific issue. They are specified by [PEP 613](https://peps.python.org/pep-0613/). While this no longer seems to have a practical impact for users of mypy, it could cause problems with type checkers in the future.

Also, despite the example in the original description being deprecated in newer versions of ray/RLlib, there are numerous other type aliases defined in `rllib/utils/typing.py` that are still used and should have TypeAlias annotations according to PEP 613.

Since this no longer seems to cause problems with mypy, it's not urgent for me any more, but I wanted to let you know the rationale behind the PR.

**Pull request closed without merging**
