### PR TITLE
[Serve] [Dashboard] Omit `colorama` characters in Serve RayTaskError message

### LINKED ISSUE #35678: [Serve] [Dashboard] Serve error contains `colorama` characters
### What happened + What you expected to happen

Serve errors on the dashboard sometimes contain `colorama` characters throughout the text. See reproduction script.

I expect these characters to be removed when the error is displayed on the dashboard.

### Versions / Dependencies

Ray on the latest master.

### Reproduction script

* Serve config

```yaml
import_path: "fruit:deployment_graph2"  # Fake import path
runtime_env:
  working_dir: "https://github.com/ray-project/test_dag/archive/81c1912273e512a3756e359e08900f0e5b2e1811.zip"
```

* `serve status` output (contains no `colorama` characters)

```console
name: default
app_status:
  status: DEPLOY_FAILED
  message: |-
    Deploying app 'default' failed:
    ray::deploy_serve_application() (pid=17820, ip=10.103.209.171)
      File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 839, in deploy_serve_application
        app = call_app_builder_with_args_if_necessary(import_attr(import_path), args)
    AttributeError: module 'fruit' has no attribute 'deployment_graph2'
  deployment_timestamp: 1684873608.110614
deployment_statuses: []
```

* Ray dashboard (contains `colorama` characters)

Screen Shot 2023-05-23 at 1 28 33 PM

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

When Serve fails to deploy a deployment graph inside its `deploy_serve_application` task, it stores the traceback of the error. If the error is a `RayTaskError`, the traceback contains `colorama` characters that get inserted into the string. On the dashboard, these characters appear as-is rather than coloring the string.

This change removes the `colorama` characters from this traceback.

## Related issue number

Closes #35678

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
     - This change adds a unit test to `test_traceback.py` to ensure that `RayTaskError` doesn't use `colorama` when `colorize` is disabled.

### CODE REVIEW

**Comment by edoakes** [comment]
Why is the underlying error a `RayTaskError` to begin with? Shouldn't it be some kind of user exception?

**Comment by shrekris-anyscale** [comment]
> Why is the underlying error a RayTaskError to begin with? Shouldn't it be some kind of user exception?

Yes, it is a user exception, but it's wrapped in a `RayTaskError`. [Here's the relevant line](https://github.com/ray-project/ray/blob/327d8e59852efa5897951aa7d8830a89906df13a/python/ray/serve/_private/application_state.py#L210). When we call `str()` on the `RayTaskError`, we trigger the logic that colorizes the user's traceback.

**Comment by edoakes** [comment]
Right but _why_ is it wrapped in a `RayTaskError`?

**Comment by shrekris-anyscale** [comment]
> Right but _why_ is it wrapped in a RayTaskError? Is it possible to just capture the raw exception instead?

This error originates from the Ray task that builds the Serve app and then returns it to the controller. If the app-building code contains a user error (or any other type of error), when the controller attempts to `ray.get()` the Ray task, it gets a `RayTaskError`.

The `RayTaskError` doesn't directly contain the original exception. However, it does contain [the original exception's class](https://github.com/ray-project/ray/blob/327d8e59852efa5897951aa7d8830a89906df13a/python/ray/exceptions.py#L125) and the [`traceback_str`](https://github.com/ray-project/ray/blob/327d8e59852efa5897951aa7d8830a89906df13a/python/ray/exceptions.py#L121).

I see 2 possible options here:
1. Keep the current approach– use `RayTaskError`'s existing traceback parsing logic.
2. Return the `traceback_str` as is. We could also include the original exception's class name.

@edoakes any preferences between (1) and (2)?

**Comment by edoakes** [comment]
@shrekris-anyscale I would suggest refactoring the task such that it does not raise an exception when the user code fails but instead explicitly returns an error code and the user traceback. Then we can directly use the traceback from the user exception instead of the `RayTaskError` (which is really an implementation detail).

(so basically option 2)

**Comment by shrekris-anyscale** [comment]
Closing this in favor of #36744

**Pull request closed without merging**
