### PR TITLE
[minor] Use a better timeline pic in the documentation

### PR DESCRIPTION
**Pull request by ericl**

### CODE REVIEW

**Comment by robertnishihara** [comment]
This picture seems a bit harder to understand to me.

**Review by richardliaw — APPROVED** [review]

**Comment by robertnishihara** [comment]
Before merging images, we should shrink them with a tool like http://compressjpeg.com/ so that the repository size doesn't grow out of control.

**Comment by richardliaw** [comment]
Just saw your comment - I feel like the second image is a little more "dynamic", in that it sort of signals a greater amount of value in the WebUI. But to your point, I can see how it conveys a little less immediate information... I'm ok with changing it, but if anyone feels strongly then we can leave it 🙂

**Comment by robertnishihara** [comment]
I'm ok with changing it. But generally I think we should prefer examples that are simple and easy to understand.

Please see if the image can be compressed at all. The previous image is 53K, so maybe it can't be, but it's worth trying.

**Comment by ericl** [comment]
Hm, I got 78k -> 53k with jpegcompress, but the artifacts are pretty visible. The compression seems minimal so I'll leave it as a png.

**Pull request merged**
