### PR TITLE
Broken link to Github python script

### PR DESCRIPTION
**Pull request by angelinalg**
## Why are these changes needed?

CSAT feedback:

"# Download the Python script curl https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/doc_code/pytorch_training_e2e_submit.py -o pytorch_training_e2e_submit.py URL is broken"

From Feb 1, 2023

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]

**Comment by architkulkarni** [comment]
Test failures are unrelated.

**Review by architkulkarni — CHANGES_REQUESTED** [review]
Actually, I'm getting that the original link works, and the new link doesn't work (404 not found)

**Comment by architkulkarni** [comment]
Maybe the user experienced a temporary Github outage?

**Comment by angelinalg** [comment]
Thanks for checking the link. Now both versions of the link work for me. I was not originally familiar with the https://raw.githubusercontent.com domain and thought that was the issue. If it's not, I can just close this issue. Would someone confirm what the right course of action is and I'll take it?
Thanks!

**Comment by architkulkarni** [comment]
I think we can just close this PR. It looks like https://raw.githubusercontent.com/ is used in a lot of places.

Here's how the first one succeeds and the second one fails:

```
> curl https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/doc_code/pytorch_training_e2e_submit.py -o pytorch_training_e2e_submit.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   667  100   667    0     0   2550      0 --:--:-- --:--:-- --:--:--  2555
> cat pytorch_training_e2e_submit.py
from ray.job_submission import JobSubmissionClient

client = JobSubmissionClient("http://127.0.0.1:8265")

kick_off_pytorch_benchmark = (
    # Clone ray. If ray is already present, don't clone again.
    "git clone -b ray-2.2.0 https://github.com/ray-project/ray || true;"
    # Run the benchmark.
    "python ray/release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py"
    " --data-size-gb=1 --num-epochs=2 --num-workers=1"
)


submission_id = client.submit_job(
    entrypoint=kick_off_pytorch_benchmark,
)

print("Use the following command to follow this Job's logs:")
print(f"ray job logs '{submission_id}' --address http://127.0.0.1:8265 --follow")
> curl https://github.com/ray-project/ray/master/doc/source/cluster/doc_code/pytorch_training_e2e_submit.py -o pytorch_training_e2e_submit.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     37      0 --:--:-- --:--:-- --:--:--    37
> cat pytorch_training_e2e_submit.py
Not Found%                                                                                                                                                                              
```

**Pull request closed without merging**
