### PR TITLE
[Core] Remove core worker test

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

According to https://github.com/ray-project/ray/pull/13514#issuecomment-764120791, core worker test is not used anymore for a long time. Currently, it is built in CI but not tested. So I removed the dead code.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

**Comment by scv119** [comment]
any chance of reenable them instead of deleting?

**Comment by jon-chuang** [comment]
Yes, we might preferably like to catch issues at core worker level rather than in language worker error. 

But I don't have enough context to know the status and relevance of the tests.

**Comment by kfstorm** [comment]
If we do want to test core_worker.cc, I believe we need to mock `ReferenceCounter`, `TaskManager`, `***Submitter/Receiver`, .etc, to make it truly **unit tests**. The current core worker test is more likely an E2E test of driver/worker without the language frontend. It's not easy to maintain and not easy to debug if a test case fails.

I prefer to delete the obsolete code and rewrite unit tests later.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
Hi, everyone! If we are not going to delete core worker test, maybe at least let's re-enable it in CI? Currently, it's disabled!!!

https://github.com/ray-project/ray/blob/2b6a0c71d744f319b914e5afbcf6830be190f1d9/.buildkite/pipeline.yml#L174

**Comment by kfstorm** [comment]
@scv119 @jon-chuang Kindly ping.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Comment by kfstorm** [comment]
@scv119 @jon-chuang Ping again.

**Comment by kfstorm** [comment]
@scv119 @jon-chuang Could you share your thoughts about re-enabling the core worker test or deleting the test code?

**Pull request closed without merging**
