### PR TITLE
[tune] Compatibility fix under py2 on str condition

### PR DESCRIPTION
**Pull request by old-bear**
## What do these changes do?
The following code snippet fails under py2 since unicode string is not a `str` by default
```
def to_argv(config):
    """Converts configuration to a command line argument format."""
    argv = []
    for k, v in config.items():
        if "-" in k:
            raise ValueError("Use '_' instead of '-' in `{}`".format(k))
        argv.append("--{}".format(k.replace("_", "-")))
        if isinstance(v, str):        <-------- HERE
            argv.append(v)   
        else:        
            # unicode string dumps as json, which will add extra quotes
            argv.append(json.dumps(v, cls=_SafeFallbackEncoder))   
```

As a result, if the user setup an Experiment like
```
tune.run_experiments({
    "my_experiment": {
        "run": "train_func",
        "stop": {"mean_accuracy": 99},
        "config": {
            "layer1": {
                "class_name": tune.grid_search(["a", "b"]),
                "config": {"lr": tune.grid_search([1, 2])}
            },
        },
        "local_dir": os.path.expanduser(u"result_dir")
    }
})
```
It would make a directory like `"result_dir"/my_experiment`

As for the fix itself, there exists other ways to achieve this, i.e.
```
from past.builtins import basestring  
if instance(v, basestring)                      # works both under py2 and py3
```
However this solution needs py3 to install future, thus I think the `type().__name__` way should be lighter. Glad to know any simpler way?

### CODE REVIEW

**Comment by richardliaw** [comment]
I don't often see `past` being used, but `six` is pretty standard:

`import six; isinstance(u"hi", six.text_type)`

**Comment by old-bear** [comment]
Done, use `six.string_types` as the base class of all strings
https://pythonhosted.org/six/#six.string_types

**Comment by richardliaw** [comment]
Maybe rebase off master to see if errors can be fixed?

**Review by richardliaw — APPROVED** [review]

**Comment by old-bear** [comment]
Confirmed, the issue above has been fixed. Thanks for the review

**Comment by richardliaw** [comment]
jenkins retest this please

**Comment by richardliaw** [comment]
test failures look unrelated.

**Pull request merged**
