### PR TITLE
Revert "[dist] swap mac/linux wheel build order (#9746)" and "Fix package and upload ray jar (#9742)"

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

cc @chaokunyang 

#9742 introduces Travis failure again (All travis CIs are failing now). Since #9746 makes conflicts, I also reverted this PR. Feel free to create a new PR to fix these issues! 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@rkooo567 can you please notify me when it's ready to merge?

**Comment by chaokunyang** [comment]
@rkooo567 Sorry for this break again. It's the wrong deployment triggerment in travis. Though I configured a condition `condition: $MULTIPLATFORM_JARS = 1 || $MAC_JARS=1`, deployment still got triggered for every job. Do you know why this happen? I'm not very familiar with travis.

**Comment by chaokunyang** [comment]
Found the problem, `condition: $MULTIPLATFORM_JARS = 1 || $MAC_JARS=1` should be `condition: $MULTIPLATFORM_JARS = 1 || $MAC_JARS = 1`. So sorry for this inconvenience.

**Comment by chaokunyang** [comment]
@rkooo567 @edoakes Created a new pr #9768 to fix this. Can you guys help review and merge it?

**Pull request merged**
