### PR TITLE
[rllib] Replace tf.minimum with tf.maximum in PPO loss.

### PR DESCRIPTION
**Pull request by alok**
Fixes \#2233

### CODE REVIEW

**Comment by richardliaw** [comment]
Thanks for the patch; I'd like to hold on this for a bit (basically waiting on #2170 and #1646, which I'm trying to patch) in order to reduce introducing more variability in regressions

**Review by richardliaw — DISMISSED** [review]
This looks good, but holding until #1646

**Comment by richardliaw** [comment]
Hey @alok can you verify there's no performance regression for `tuned_examples/pendulum-ppo` with this change?

**Review by ericl — COMMENTED** [review]
Looks good. Any difference on benchmarks?

**Comment by richardliaw** [comment]
Addressed in #2366

**Pull request closed without merging**
