### PR TITLE
Replace `pkg_resources` to `importlib.metadata` and `packaging.version`

### LINKED ISSUE #38257: [Core] Replace pkg_resources to importlib.metadata
### What happened + What you expected to happen

From @hauntsaninja 

`import pkg_resources` is an incredibly slow to import (time proportional to the size of the venv). it’s also deprecated and raises deprecation warnings. in 3.8 and higher you can use importlib.metadata. 3.7 is dead, but you can sys.version_info gate to use pkg_resources, or use the importlib_metadata backport. 

it’d be cool if ray could run tests with warnings set to error!

I also found deprecation warnings from this packages + it spends lots of time when starting a new ray worker. So it'd be great if we can remove the usage. 

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

### PR DESCRIPTION
**Pull request by anmyachev**
## Related issue number

Closes #38257 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by anmyachev** [comment]
cc @rkooo567

**Comment by anmyachev** [comment]
It seems that tests are failing that are not related to my changes. Considering that the tests take a long time, it would be great if someone restarted only those tests that failed.

**Comment by rkooo567** [comment]
Awesome PR! I will take a look shortly

some of window tests seem to fail. Let me retry them.

**Review by rkooo567 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Comment by anmyachev** [comment]
Hi @rkooo567! Is there anything else I can do here?

**Review by sven1977 — APPROVED** [review]
RLlib related changes look good to me!
Thanks @anmyachev

**Review by raulchen — APPROVED** [review]

**Comment by rkooo567** [comment]
hmm for some reasons, the window failure https://buildkite.com/ray-project/premerge/builds/12710#018c1ba3-c93a-4044-8e52-c36b89269752 lasts.

can you merge the latest master?

**Comment by anmyachev** [comment]
> hmm for some reasons, the window failure https://buildkite.com/ray-project/premerge/builds/12710#018c1ba3-c93a-4044-8e52-c36b89269752 lasts.
> 
> can you merge the latest master?

Sure, will do

**Comment by anmyachev** [comment]
@rkooo567 still not all tests pass, but it seems better.

**Comment by rkooo567** [comment]
Thank you so much @anmyachev !

**Comment by anmyachev** [comment]
> Thank you so much @anmyachev !

Thanks everyone for the review!

**Pull request merged**
