### PR TITLE
[testing] Turn on chaos test for non-streaming shuffle

### LINKED ISSUE #20408: [Bug] Lineage reconstruction not working always with no streaming shuffle.
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Please refer to https://github.com/ray-project/ray/pull/20277#discussion_r748034969

When enabling commented out test, I discovered the test is not passing as expected.

In the non streaming shuffle workload, all tasks are owned by the driver, so it should be a good representative workload for lineage reconstruction.

The test keeps killing worker nodes every X seconds. 

The expected behavior of non streaming shuffle + node failures is
1. Raising an exception without lineage reconstruction. -> Seems like it hangs occasionally.
2. succeeding with the lineage reconstruction -> Seems like it doesn't always succeeds.

### Versions / Dependencies

master

### Reproduction script

Check the link. This is the example;

```
@pytest.mark.skip(reason="Flaky.")
@pytest.mark.parametrize(
    "ray_start_chaos_cluster", [{
        "kill_interval": 8,
        "env_vars": {
            "RAY_lineage_pinning_enabled": "true"
        },
        "head_resources": {
            "CPU": 1
        },
        "worker_node_types": {
            "cpu_node": {
                "resources": {
                    "CPU": 8,
                },
                "node_config": {},
                "min_workers": 0,
                "max_workers": 4,
            },
        },
    }],
    indirect=True)
def test_chaos_lineage_reconstruction(ray_start_chaos_cluster):
    shuffle.run(
        ray_address="auto",
        no_streaming=True,
        num_partitions=200,
        partition_size=15e6)
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Tests that non-streaming shuffle can recover with lineage reconstruction enabled.

## Related issue number

Closes #20408.

### CODE REVIEW

**Comment by stephanie-wang** [comment]
I'm also going to add observability to this PR to make sure we can see how many objects are getting reconstructed.

**Comment by rkooo567** [comment]
Is it ready to review?

**Review by rkooo567 — APPROVED** [review]
LGTM. Should we add this to metrics too? (metric_defs.h)?

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
