### PR TITLE
[Serve] Remove release tests for checkpoint_path

### LINKED ISSUE #27189: [2.0][nightly] 8. serve_serve_cluster_fault_tolerance failed
### What happened + What you expected to happen

8. serve_serve_cluster_fault_tolerance https://buildkite.com/ray-project/release-tests-branch/builds/831#01824205-0d2c-4a28-b308-01092a229679

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by simon-mo**
This test should be removed when we officially removed the
checkpoint_path but it was missed. checkpoint_path is no longer
exposed API and we encourage user to use K8s operator and GCS FT.

Signed-off-by: simon-mo <simon.mo@hey.com>

## Related issue number
Closes #27189

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
@scv119 This PR just removes the test, it should be harmless to merge and cherry pick anytime.

**Review by sihanwang41 — APPROVED** [review]
I missed this one! Thank you!

**Comment by ericl** [comment]
This PR doesn't seem critical for 2.0--- let's not pick it.

**Comment by simon-mo** [comment]
@ericl This is a release test fix, please see the linked issue https://github.com/ray-project/ray/issues/27189

**Pull request merged**
