### PR TITLE
[core][state][ci] Fix stress_test_state_api_scale

### LINKED ISSUE #35329: [core][release-test] stress_test_state_api_scale.aws failed
### What happened + What you expected to happen

stress_test_state_api_scale.aws has been consistently failing on master

[bisect](https://buildkite.com/ray-project/release-tests-bisect/builds/146#_) blamed this PR: https://github.com/ray-project/ray/commit/047038357ebc175b1ce122164d5eedbca2ea467b. Please review and revert if it's relevant

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1648#01880e92-3821-4b36-b569-33ef77048cd0

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
We changed the logging content with per task magic token. Updating test logic. 

## Related issue number
Closes https://github.com/ray-project/ray/issues/35329#event-9242393519

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Release test: https://buildkite.com/ray-project/release-tests-pr/builds/38454

**Comment by rkooo567** [comment]
I feel like this test kept being broken. Can we have a simple unit test?

**Review by rkooo567 — APPROVED** [review]

**Comment by rickyyx** [comment]
> I feel like this test kept being broken. Can we have a simple unit test?

It's actually covered by unit tests - just that we didn't change the release test when the unit test was changed..

**Comment by rickyyx** [comment]
> I feel like this test kept being broken. Can we have a simple unit test?

It's actually covered by unit tests - just that we didn't change the release test when the unit test was changed..

**Pull request merged**
