### PR TITLE
[core] A new type-friendly Actor

### LINKED ISSUE #42474: [core] Better ray actor
It is very painful to manipulate actors because the Actor class decorated with `ray.remote` completely loses its class information, making it impossible for the IDE to provide autocompletion.

### PR DESCRIPTION
**Pull request by zen-xu**
## Why are these changes needed?

I once submitted a PR #37467 to resolve the lack of type hints in Ray's actor, but it failed. This time, I proposed a new way to solve this problem

## Related issue number

Closes #42474
## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zen-xu** [comment]
## A Demo
2c56743f-7378-4e43-a599-887798cb70a1

## Type hints
### 1. Constructor type annotation
image

### 2. methods
image

### 3. remote method
image

**Comment by zen-xu** [comment]
missing async method, I will implement it later

**Comment by zen-xu** [comment]
@rkooo567 hey，would you be able to take some time to review this pr?

**Comment by zen-xu** [comment]
## Async Support
868d0cda-53cf-4710-b353-163163d34660

**Comment by anyscalesam** [comment]
@kevin85421 can you start looking at this to see if we can shepherd this through?

**Comment by zen-xu** [comment]
Anyone who want to obtain a more robust ray can visit my new project at https://github.com/zen-xu/sunray.

**Pull request closed without merging**
