### PR TITLE
[serve] fix http proxy retry counter

### LINKED ISSUE #36469: [Serve] Http proxy retries fails on 4th try
### What happened + What you expected to happen

We have a default retry threshold of 3, meaning that we should fail the health check after 3rd retry failure. The current behavior fails after 4th retries. 

### Versions / Dependencies

lastest master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by GeneDer**
issue: https://github.com/ray-project/ray/issues/36469

## Why are these changes needed?

Currently the http proxy retry counter is only incremented when `self._consecutive_health_check_failures < PROXY_HEALTH_CHECK_UNHEALTHY_THRESHOLD` then early returns immediately. This creates the affect of only setting unhealthy on the 4th time when health check fails. Following the same logic in [deployment_state](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/deployment_state.py#L725) we should always increment the counter on unhealthy attempt. And only when this counter is greater than or equal to the threshold, we set the status to unhealthy (skip the early return in this case). 

## Related issue number

Closes #36469

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
Presumably there is a test that should be updated/added for this :)

**Review by GeneDer — COMMENTED** [review]
Haha, only did the manual test. Will add/ modify to make sure a test will catch this.

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@GeneDer you have a small merge conflict here

**Comment by GeneDer** [comment]
Thanks Ed! Will resolve it right away

**Pull request merged**
