### PR TITLE
[core] Add test case to verify certain behavior when the head node is down.

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
In this PR the following two cases are covered in e2e test:

1. When the headnode died, since actor death info is not published, actor calls are going to hang forever until GCS is back.
2. When the head node died, the object created by the actor can be fetched if it's stored locally.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
@edoakes I can't figure out a way to write test for the case that:

we have 3 nodes, one head (h) + two workers (w1 and w2) where h has an actor and w1's local store has an object ref owned by that actor and we are (or not?) able to get the object from w2.

I think it's not going to work until the actor is back because the object directory is owned by the owner, so w2 might not know where to find the object.


@scv119  could you share your thoughts about the behavior here?

**Comment by scv119** [comment]
> we have 3 nodes, one head (h) + two workers (w1 and w2) where h has an actor and w1's local store has an object ref owned by that actor and we are (or not?) able to get the object from w2.
I think it's not going to work until the actor is back because the object directory is owned by the owner, so w2 might not know where to find the object.

yup this sounds like the right behavior. I think we should avoid running user workload on head node for HA cluster?

**Comment by edoakes** [comment]
That's fine, I think anything owned by a process on a node not being available after node failure is a reasonable expectation.

I'd classify (1) in the PR description as a bug though -- we shouldn't have a case where any API call hangs indefinitely. Can we address this with some sort of internal timeout if we don't get an ACK back from the actor?

**Comment by edoakes** [comment]
Oh, @iycheng we should also have an extended version of case (2) where an actor tries to fetch an object in the object store from another worker node while the head node is down. So:

- Actor1 lives on workernode1
- Actor2 lives on workernode2
- Head node crashes
- Actor1 calls actor2, fetches a result that is put into the object store

**Comment by iycheng** [comment]
@edoakes I'd suggest for 1), the user can just ray.get/ray.wait with a timeout and don't depend on the core side.

The API right now is not defined well. We have max_restarts and max_task_retries, and should we wait until the method finished or just queue them until the actors are back? Since in the application layer, we have timeout, I'd suggest just use that. It doesn't always make sense to default timeout the request to a dead actors.

Besides, Actor death is announced by the GCS, and that's the only place doing this. If we did it in raylet or other places, it's going to make things complicated in extreme cases.

**Comment by iycheng** [comment]
I'll add the test for this:

```
Actor1 lives on workernode1
Actor2 lives on workernode2
Head node crashes
Actor1 calls actor2, fetches a result that is put into the object store
```

I actually can just modify some test for this.

**Comment by edoakes** [comment]
@iycheng the issue here is that there is no API to differentiate between an actor method being queued/slow and an actor not being reachable at all (which we do have at the Ray core level), so I don't think you can fully handle this situation from user code.

**Comment by iycheng** [comment]
@edoakes I think, even it's just queued, the client side should handle it. Timeout, no matter it's because of queuing or fault, should be handled well. For the failed ones, the user should always just cancel it first and then do the retry by some backoff. The method need to be idempotent.

If the request hang because of the network or thing queued, client need to cancel it and back off to avoid making things worse.

**Comment by edoakes** [comment]
@iycheng that's a fair point, let me think about the best way to handle it in the library layer...

**Comment by iycheng** [comment]
> @iycheng that's a fair point, let me think about the best way to handle it in the library layer...
> 
> cc @shrekris-anyscale

Btw, do you know what's the main benefit that the application know whether the timeout is because actor is dead or actor is slow?

**Comment by scv119** [comment]
@iycheng should I review it :) ?

**Pull request closed without merging**
