### PR TITLE
Add back job_id to submit_job API to maintain backwards-compatibility

### PR DESCRIPTION
**Pull request by alanwguo**
Fix for a unintentional backwards-compatibility breakage for #25902
job submit api should still accept job_id as a parameter

Signed-off-by: Alan Guo <aguo@anyscale.com>

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]

**Comment by rkooo567** [comment]
Hey @architkulkarni @alanwguo does this PR need to be cherry picked? We already finished the branch cut

**Comment by rkooo567** [comment]
Also can you update the PR description? (follow-up for https://github.com/ray-project/ray/pull/25902 -> i don't know follow up of which comment it is?)

**Review by rkooo567 — APPROVED** [review]

**Comment by alanwguo** [comment]
> Hey @architkulkarni @alanwguo does this PR need to be cherry picked? We already finished the branch cut

This does not have to be cherry-picked. This only impacts product users and we are releasing 2.0.0rcs as nightly and not actual releases.

**Comment by alanwguo** [comment]
@rkooo567 can you help merge this?

**Comment by rkooo567** [comment]
done. please make sure all these changes don't break the product job submission @architkulkarni for reminder

**Comment by matthewdeng** [comment]
> This does not have to be cherry-picked. This only impacts product users and we are releasing 2.0.0rcs as nightly and not actual releases.

Hey @alanwguo, my understanding is that we should be releasing release candidates on the product as well. cc @scv119 @zhe-thoughts

**Comment by alanwguo** [comment]
I remember reading this:
```
We will set clear expectations with Anyscale customers that this is a preview release, and also simplify the Anyscale product integration.
We won’t build a separate AMI image.
We will run a subset of important product integration tests.
Anyscale customers interested in 2.0.0beta will try it in the same way that they are using our nightlies (e.g. Riot).
```

Sounds like this is out of date (the nightly part)? If that's true, then we should make sure to cherry-pick this.

**Comment by zhe-thoughts** [comment]
Hi @alanwguo , the above paragraph is from the plan of releasing a special `2.0.0beta` release in June. We then decided not to do that special release

This `rc0` is a regular release candidate that we should deploy on Anyscale product to identify risks earlier. 

cc @scv119 @nikitavemuri

**Comment by alanwguo** [comment]
Yes, let's cherry-pick this.

**Pull request merged**
