### PR TITLE
Add seed for read_parquest

### LINKED ISSUE #46177: [Data] read_parquet with shuffle="files" has not seed option
### What happened + What you expected to happen

Calling [ray.data.read_parquet](https://docs.ray.io/en/latest/data/api/doc/ray.data.read_parquet.html) with `shuffle="files"` calls `np.random.default_rng()` with no argument, see https://github.com/ray-project/ray/blob/9d661677f942ccd7dfbbf2c2838e5dad9f50d12e/python/ray/data/datasource/parquet_datasource.py#L304

It makes it impossible to have a deterministic behavior across runs since, as per [numpy.random.default_rng](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng), if the `seed` parameter is `None`, "fresh, unpredictable entropy will be pulled from the OS."

Would it be possible to add an optional integer `seed` parameter to Ray Data's `read_parquet` that would be forwarded to NumPy's `random.default_rng` to ensure reproducibility when needed?

### Versions / Dependencies

Ray 2.30, any OS and version of Python, any recent version of NumPy (not specific to 2.0).

### Reproduction script

```
ray.data.read_parquet(..., shuffle="files")
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by Bye-legumes**
## Why are these changes needed?
Close https://github.com/ray-project/ray/issues/46177
## Related issue number

[
](https://github.com/ray-project/ray/issues/46177)
## Checks

- [√] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [√] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [√] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Bye-legumes** [comment]
@bveeramani can you check this PR?

**Comment by bveeramani** [comment]
Hey @Bye-legumes, I won't have bandwidth to review this PR.

@c21 would you mind taking a look?

**Comment by bthecohen** [comment]
Would be very useful to have this merged – we have a use case for file-based shuffling.

**Comment by bveeramani** [comment]
@Bye-legumes I talked with my team, and I think we have an idea of how we want to address https://github.com/ray-project/ray/issues/46177.

I messaged you on Slack with details.

**Comment by bthecohen** [comment]
@bveeramani do you have an estimated timeline on when this might get fixed? We are currently experimenting with the file-based shuffling feature but this is a potential showstopper for us.

**Comment by Bye-legumes** [comment]
> @bveeramani do you have an estimated timeline on when this might get fixed? We are currently experimenting with the file-based shuffling feature but this is a potential showstopper for us.

I will try to finish within week! I will ping you if I finished!

**Comment by bthecohen** [comment]
Thanks so much! Appreciate your contributions.

**Comment by Bye-legumes** [comment]
moved to https://github.com/ray-project/ray/pull/49129

**Pull request closed without merging**
