### PR TITLE
Fix dependencies for operation fusion

### PR DESCRIPTION
**Pull request by raulchen**
Chery-pick #37878 to the 2.6.2 release.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
@raulchen does this need to go in 2.6.2, or it's OK to have it in 2.7.0 instead? Thanks

**Comment by raulchen** [comment]
@zhe-thoughts this is a new bug introduced in 2.6. we prefer to fix it in 2.6 per offline discussion cc @c21 @stephanie-wang

**Comment by raulchen** [comment]
The original PR was merged.  This PR should be ready to merge when CI passes.

**Review by zhe-thoughts — APPROVED** [review]
OK agreed we should pick

**Pull request merged**
