### PR TITLE
Support setting extra_envs for remote function and Actor

### PR DESCRIPTION
**Pull request by ConeyLiu**
## Why are these changes needed?

Currently, we have two ways to set envs:

- Set system level. This is not always true for different purpose remote functions or Actors.

- For each function/actor, we set by `os.envrion`. This's not very convenient.

One common usage for this is set `OMP_NUM_THREADS` for trainer/rolloutworker in rllib. Because the `OMP_NUM_THREADS` can influence the TensorFlow performance a lot when training with CPU. I will add the support for rllib in the following patch.

API changes as following:
```python
@ray.remote(extra_envs={"OMP_NUM_THREADS": "1"})
def func():
    # ...
 
@ray.remote(extra_envs={"OMP_NUM_THREADS": "2"})
class Worker:
    # ....
```

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by ericl** [comment]
I don't think this implementation is sufficient for the following reason: many libraries read the environment variable at startup time to determine their settings. In the extreme case, the entire PYTHONPATH can be changed by an env var.

Setting it on a per-task basis is not so useful for these types of cases. In addition, you can already do this at the application level, by wrapping the function.

**Comment by ericl** [comment]
I don't think this implementation is sufficient for the following reason: many libraries read the environment variable at startup time to determine their settings. In the extreme case, the entire PYTHONPATH can be changed by an env var.

Setting it at runtime is not so useful for these types of cases. In addition, you can already do this at the application level, by wrapping the function with a decorator.

A complete solution will require launching a new worker per set of env vars. The environment variables need to be set before the worker is launched, and the worker cannot be reused if a task is requesting a different set of env vars.

**Comment by ConeyLiu** [comment]
Hi @ericl, thanks for reviewing. Actually this patch is aimed to we could set different envs for different remote tasks in rllib/tune.  In rllib, we could set different envs to tune the tf performance. And in tune, we could grid search the env setting for the parameter searching. So it's not very easy or convenient to add a decorator. 

> A complete solution will require launching a new worker per set of env vars. The environment variables need to be set before the worker is launched, and the worker cannot be reused if a task is requesting a different set of env vars.
Could we reset the env set after the remote task finished or the actor terminated?

**Comment by ericl** [comment]
>  So it's not very easy or convenient to add a decorator.

I think you can do something like this, in the tune trainable, have a hyperparam called "env_vars". Then, in your trainable, do

```
for k, v in env_vars.items():
   os.environ[k] = v
```

Since it's just a hyperparam then it supports grid search, etc. No need to change Ray if it can be done at the application level.

**Comment by ConeyLiu** [comment]
Good advice. Should we also support this in rllib?

**Comment by ConeyLiu** [comment]
I mean add a configuration option for rllib. You know there are some env could tune for tensorflow/pytorch. I think it's useful.

**Comment by ConeyLiu** [comment]
close this, replace solution with #8026 8026

**Comment by ericl** [comment]
Thanks! Will take a look, that sounds like a nice solution.

**Pull request closed without merging**
