### PR TITLE
[CI] Update bazel version

### PR DESCRIPTION
**Pull request by aslonnie**
## Why are these changes needed?

It has fixes for python hermetic toolchain setup.
It is required for improving ray release tests.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Comment by Yard1** [comment]
Can we rerun CI?

**Comment by aslonnie** [comment]
> Can we rerun CI?

merged master head

**Comment by aslonnie** [comment]
I honestly do not know how to parse the test results though..

**Comment by pcmoritz** [comment]
Let's try again :)

**Comment by aslonnie** [comment]
pledge to increase timeout here:

https://github.com/ray-project/buildkite-ci-pipelines/pull/18

I think the timeout has to be able to accommodate a clean build with no cache.

**Review by can-anyscale — APPROVED** [review]

**Review by matthewdeng — APPROVED** [review]

**Pull request merged**
