### PR TITLE
[RLlib] Add coin game env. Matrix social dilemma env. With tests and examples.

### PR DESCRIPTION
**Pull request by Manuscrit**
@sven1977 

## Why are these changes needed?
Add coin game env. Matrix social dilemma env. With tests and examples.

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR. => Some stuff are much less readable now ;) 
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X]_(only for the new tests in this PR)_ I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by sven1977 — CHANGES_REQUESTED** [review]
Thank you for this massive contribution! This looks really great!
Just a few changes required:
- Could you run the LINTer on your repo (some lines are too long)?
- - $ cd ray
- - $ ci/travis/format.sh
- Could you move the test cases into a new `examples/env/tests` dir? 
- Could you rename ipd_env.py into `iterated_prisoners_dilemma_env.py`?
- Could you move the reward-uncertainty class in `examples/utils/wrappers.py` into `rllib/env/wrappers/.`?
- Could you rename `examples/vectorized_coin_game.py` into `examples/coin_game.py`?
- Could you rename `test_coin_game.py` into `test_non_vectorized_coin_game.py`?

**Comment by sven1977** [comment]
Sounds great, let's rename these according to your suggestion.
Thanks!

**Comment by Manuscrit** [comment]
I committed the changes @sven1977

**Review by sven1977 — APPROVED** [review]
Thanks @Manuscrit for this great contribution!
One more thing before we can merge: Could you check the LINT output again? There seems to be 3 list comprehensions that need to be fixed.

**Comment by sven1977** [comment]
@Manuscrit no worries, I already fixed the LINT. Just waiting for all tests to pass now. ...

**Pull request merged**
