### PR TITLE
Enable worker in container CI test

### PR DESCRIPTION
**Pull request by chenk008**
## Why are these changes needed?

This PR try to. enable worker in container CI test.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by chenk008** [comment]
To minimize the CI job , I have commented most CI tests. After the worker in container job passed, I will revert all of them.

**Comment by chenk008** [comment]
I have reverted CI test, and the worker-in-container test has passed. Please take a look. @simon-mo

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
seeing some
```


2021-11-10 03:08:24,344	WARNING services.py:1819 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67022848 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=4.31gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
--
  | (pid=runtime_env) 2021-11-10 03:08:26,476	INFO container.py:74 -- start worker in container with prefix: podman run -v /tmp/ray:/tmp/ray --cgroup-manager=cgroupfs --network=host --pid=host --ipc=host --env-host --env RAY_RAYLET_PID=1285 --entrypoint python rayproject/ray-worker-container:nightly-py36-cpu-pandas
  | PASSED(raylet) time="2021-11-10T03:08:27Z" level=error msg="unable to write pod event: \"write unixgram @000a5->/run/systemd/journal/socket: sendmsg: no such file or directory\""
  | (raylet) time="2021-11-10T03:08:27Z" level=error msg="unable to write pod event: \"write unixgram @000a5->/run/systemd/journal/socket: sendmsg: no such file or directory\""
  | (raylet) time="2021-11-10T03:08:27Z" level=error msg="unable to write pod event: \"write unixgram @000a5->/run/systemd/journal/socket: sendmsg: no such file or directory\""
  | (raylet) time="2021-11-10T03:08:27Z" level=error msg="unable to write pod event: \"write unixgram @000a5->/run/systemd/journal/socket: sendmsg: no such file or directory\""

```

I think i have encountered it before and solved by adding `--events-backend=file` to podman options. Can you do that in a follow up?

**Comment by chenk008** [comment]
@simon-mo Thank you for your suggestion. I will fix it.

**Pull request merged**
