### PR TITLE
Add a script to collect built thirdparty libs to avoid download and building again.

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?
Add a script (collect_dependent_libs.sh) to cache built thirdparty libs to avoid download and build again.

After running `git clean -x -d -f`, we need to download and rebuild all the dependent thirdparty libs, which is very expensive for developers. This script will help the developers to cache the built libs and reuse the libs. 

The steps to cache the libs:
1. Run `./collect_dependent_libs.sh -d $user_dir`.
2. Run `source $user_dir/resource.txt`.

## Related issue number
N/A

### CODE REVIEW

**Comment by robertnishihara** [comment]
Thanks @guoyuhong, this looks like a good idea. Note that there is some danger of this script becoming stale since it is not called anywhere in the CI.

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
Actually, @guoyuhong, before merging, I think this script should be a little more hidden since it is just for developers, e.g., under `thirdparty/` or `thirdparty/scripts/`. Could you move it to one of those places?

**Comment by guoyuhong** [comment]
@pcmoritz It looks like this test is not related to my change. I can see [this test](https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/9981/consoleFull) also failed in https://github.com/ray-project/ray/pull/3473 .

**Comment by guoyuhong** [comment]
@robertnishihara I have moved the script to `thirdparty/scripts`. Yes, this script is not covered by CI. I will keep it update-to-data and may consider to add it to CI later.

**Comment by robertnishihara** [comment]
Thanks!

**Pull request merged**
