### PR TITLE
[Cluster] Fix Kuberay capitalization

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
replace Kuberay with KubeRay, and add Kuberay to the list of banned words in the linter

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]
LGTM for the documentation changes. Let's wait for the Autoscaler tests to pass.

**Comment by architkulkarni** [comment]
@angelinalg would you mind approving this on behalf of ray-docs?

**Review by angelinalg — APPROVED** [review]
Love this attention to detail. And I really appreciate you adding it to the linter. Thank you! There's also a Vale (go/vale) linter that we use. I'll see if we should consolidate the linting. cc: @bveeramani

**Comment by DmitriGekhtman** [comment]
kUBeraY

**Comment by architkulkarni** [comment]
@scv119 assigning you as core-oncall just for the codeowner stamp!

**Review by hongchaodeng — APPROVED** [review]
LGTM

**Review by edoakes — APPROVED** [review]

**Pull request merged**
