### PR TITLE
[Tune] `with_resources` takes in a `ScalingConfig`

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

We promote `ScalingConfig` as the canonical way to set resource requirements in AIR, but `tune.with_resources` only takes in `PlacementGroupFactories`. As a `ScalingConfig` can be easily converted to a PGF, we can allow it to be passed directly and do the conversion internally.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by justinvyu — APPROVED** [review]
Looks good to me!

**Comment by xwjiang2010** [comment]
Update doc?

**Review by xwjiang2010 — APPROVED** [review]

**Comment by justinvyu** [comment]
Comment on the docs we provide in the FAQ here: https://docs.ray.io/en/master/tune/faq.html#how-do-i-set-resources

Does this last example actually work for custom training functions? Seems like that example for specifying a `ScalingConfig` is for use with an AIR Trainer that actually takes it in as a param.

```python
tuner = tune.Tuner(
    train_fn,
    param_space={
        "scaling_config": ScalingConfig(
            trainer_resources=lambda spec: {"GPU": 1}
            if spec.config.use_gpu
            else {"GPU": 0}
        )
    },
)
tuner.fit()
```

**Comment by Yard1** [comment]
I'll try it locally, it looks suspect

**Comment by Yard1** [comment]
Yeah, it's not working. Good catch!

**Comment by justinvyu** [comment]
One other fix to the 2nd to last example in that section, while we're on it:

```diff
tuner = tune.Tuner(
    tune.with_resources(
        train_fn,
        resources=lambda spec: {"GPU": 1} if spec.config.use_gpu else {"GPU": 0},
    ),
+   param_space={"use_gpu": tune.grid_search([True, False])},
)
tuner.fit()
```

It's currently referencing a `use_gpu` config that is not set.

**Comment by Yard1** [comment]
@justinvyu updated, ptal

**Comment by amogkam** [comment]
can you please ping again once CI finishes

**Review by justinvyu — APPROVED** [review]

**Review by krfricke — APPROVED** [review]
Looks good to me!

**Pull request merged**
