### PR TITLE
[RLlib] get rid of the global registry to get rid of all the troubles.

### PR DESCRIPTION
**Pull request by gjoliver**
Signed-off-by: Jun Gong <jungong@anyscale.com>

## Why are these changes needed?

Global registry is not necessary at this point, and actually causes us a bunch of problems.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ArturNiederfahrenhorst — APPROVED** [review]
Restarted the failing CI tests that should be flakey, unrelated.
Lgtm!

**Comment by kouroshHakha** [comment]
actually I think test_algorithm failure is real. The other failures are getting addressed hopefully by this PR https://github.com/ray-project/ray/pull/30823

**Comment by kouroshHakha** [comment]
Once we fix that @gjoliver Can you launch the release tests?

**Comment by kouroshHakha** [comment]
release tests are running here: https://buildkite.com/ray-project/release-tests-pr/builds/22811

**Comment by kouroshHakha** [comment]
Can you rebase and run the release tests? @gjoliver

**Comment by gjoliver** [comment]
tests look good after reverting the flag flip. merging.

**Pull request merged**
