### PR TITLE
[GCS-Ray] remove Redis password from CLI messages

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Redis password should not be needed in the connection info printed by `ray start --head`.
We can make another cleanup for removing flags and arguments related to Redis password. But it is a bit more risky (affects external Redis) and needs more care.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by fishbone — APPROVED** [review]

**Comment by iycheng** [comment]
wired... why there is no ci run for this PR

**Comment by mwtian** [comment]
> wired... why there is no ci run for this PR

CI is problematic this morning. Many builds seem delayed.

**Comment by iycheng** [comment]
Test cli failed which seems related to this one.

**Comment by mwtian** [comment]
CI failure is fixed now.

**Pull request merged**
