### PR TITLE
[rllib] Update PettingZoo dependency versions

### PR DESCRIPTION
**Pull request by jkterry1**
Minor maintenance PR to update the tested/installed PettingZoo version.

## Checks
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
@jkterry1 hey, thanks for opening this pr!

Can you please cc @sven1977 and myself when opening PRs in the future? these are really easy to get lost.

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
It looks like this breaks a couple tests:

> pettingzoo.utils.deprecated_module.DeprecatedEnv: rps_v1 is now deprecated, use rps_v2 instead

https://buildkite.com/ray-project/ray-builders-pr/builds/11026#4d05b41d-9179-469e-81af-e5e3522ad5f4

@jkterry1 Could you take a look?

**Review by richardliaw — CHANGES_REQUESTED** [review]
(Will approve after tests are fixed!)

**Comment by jkterry1** [comment]
@richard4912 it should be good now

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
thanks!

**Pull request merged**
