### PR TITLE
error message on non-integral args with ray.remote

### LINKED ISSUE #8894: No proper error message when num_return_vals is negative or not integral
### What is the problem?
*Ray version and other system information (Python version, TensorFlow version, OS):*
    *Ubuntu 18.04.4 LTS*
    *Python 3.7.7*
    *ray-0.9.0.dev0-cp37-cp37m-manylinux1_x86_64.whl*

* For non integral values of `x`, eg. `x = 3.2` in the code below, ray doesn't give a proper error message. Instead the worker dies. This also happens when `x` is not equal to the true num return values, eg. `x = 5`.
`
ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task.
`
* For negative values of `x`, eg. `x = -2` the kernel dies altogether. 
` Aborted (core dumped)`

Although one would not expect the user to enter such values. But still. 

### Reproduction
```
import ray

ray.init()

def f(a):
    return a, 2

x = <some_value>
g = ray.remote(num_return_vals = x)(f)

print(ray.get(g.remote(3)))
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by kishansagathiya**
This PR type checks arguments for ray.remote and checks if they
belong to the valid range for that argument and shows informative error
if otherwise.

## Related issue number

Fixes #8894

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
This looks great @kishansagathiya! Would you mind also adding some basic tests for these?

**Comment by edoakes** [comment]
Also @kishansagathiya, yes floats are valid for `num_cpus`. We don't actually pin CPUs and users may want more than one task per CPU (e.g., if they're IO intensive)

**Comment by kishansagathiya** [comment]
@edoakes 
> This looks great @kishansagathiya! Would you mind also adding some basic tests for these?

Sure

**Comment by kishansagathiya** [comment]
@edoakes 
Added tests only check if things fail on invalid arguments. It doesn't check that things work on valid arguments like positive integers and -1 in some cases.

**Review by edoakes — APPROVED** [review]
LGTM

**Comment by rkooo567** [comment]
@kishansagathiya Can you merge the latest master? There were some master failures, and it should've been fixed by now.

**Comment by edoakes** [comment]
@kishansagathiya merged it, thanks for your contribution!

**Pull request merged**
