### PR TITLE
[autoscaler] Lint code that we forgot to lint in #4537

### PR DESCRIPTION
**Pull request by hartikainen**
I merged #4537 without linting. This fixes the lint errors.

### CODE REVIEW

**Comment by jovany-wang** [comment]
Hi @hartikainen, is the following case failure produced by #4537 ?
```
python/ray/tests/test_autoscaler.py::AutoscalingTest::testReportsConfigFailures FAILED [ 30%]
```
This is the CI result I met: https://travis-ci.com/ray-project/ray/jobs/191124885

**Comment by guoyuhong** [comment]
@jovany-wang @hartikainen Yes, it looks like `python/ray/tests/test_autoscaler.py::AutoscalingTest::testReportsConfigFailure` has reproducible failure. Please also fix that. You can ignore the failure of `python/ray/tests/test_stress.py::test_submitting_many_actors_to_one`.

**Comment by hartikainen** [comment]
https://github.com/ray-project/ray/pull/4584/commits/55e1cdb1f256ea51ef66a38730d8f7865f1f5ad1 should fix the test error as well. The problem was that the way we setup some of the autoscaler tests, the [setup command merge](https://github.com/ray-project/ray/pull/4537/files/aa2575f2cea476bdca5464e94d313b825a9cb39c#diff-6a987ff43a9906e4d9d2116bc57c22c7R715) was not called, and thus some of the commands were not run. I reverted the changes related to the setup command merge. @richardliaw do you mind takinga look (https://github.com/ray-project/ray/pull/4584/commits/55e1cdb1f256ea51ef66a38730d8f7865f1f5ad1)?

**Comment by hartikainen** [comment]
jenkins retest this please

**Review by guoyuhong — APPROVED** [review]
LGTM. I restarted the failed Travis tests. I will merge this PR once the tests finish.

**Comment by hartikainen** [comment]
@guoyuhong Don't merge this yet. I think there's still something off with my latest `setup_commands` change. I'll fix it tomorrow morning.

**Comment by hartikainen** [comment]
I just pushed a fix for this. Tested on GCP and everything looks good.

**Comment by guoyuhong** [comment]
@hartikainen That is to say I can merge this PR if the test passed, right?

**Comment by hartikainen** [comment]
@guoyuhong Yep!

**Comment by guoyuhong** [comment]
@hartikainen OK, I will keep an eye on it. This PR is better to get merged as soon as possible to unblock other PRs.

**Review by guoyuhong — APPROVED** [review]
This looks good. I will merge it.

**Comment by ericl** [comment]
Ah, thanks for fixing. Next time, we can merge hotfixes such as this immediately.

**Pull request merged**
