### PR TITLE
Boost performance improvements

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Boost inclusions slow down performance considerably.  

We use forward declarations and pointer members to gradually avoid including expensive Boost headers in files where they're not needed.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by zhijunfu** [comment]
> Boost inclusions slow down performance considerably.
Do we have any perf numbers on this?

**Comment by mehrdadn** [comment]
Yeah we do, see [Benchmark.txt](https://github.com/ray-project/ray/files/4162756/Benchmark.txt) for how long each header takes to compile on its own (in milliseconds), here's a snippet:

	1.9325	#include <boost/asio.hpp>
	1.8343	#include <boost/process/child.hpp>
	1.5990	#include <boost/thread.hpp>
	1.5303	#include <boost/date_time/posix_time/posix_time.hpp>
	1.5077	#include <boost/process/async.hpp>
	1.4326	#include <boost/process/search_path.hpp>
	1.3232	#include <boost/asio/ip/tcp.hpp>
	1.1324	#include <boost/asio/steady_timer.hpp>
	0.9898	#include <boost/process/args.hpp>
	0.9516	#include <boost/thread/shared_mutex.hpp>
	0.9207	#include <boost/fiber/all.hpp>
	0.8255	#include <boost/asio/detail/socket_holder.hpp>
	0.7895	#include <boost/thread/locks.hpp>
	0.7581	#include <boost/asio/io_service.hpp>
	0.7112	#include <boost/asio/ip/address.hpp>
	0.7080	#include <boost/function.hpp>
	0.6874	#include <boost/circular_buffer.hpp>
	0.6723	#include <boost/asio/thread_pool.hpp>
	0.6019	#include <boost/any.hpp>
	0.5806	#include <boost/asio/error.hpp>
	0.5331	#include <regex>
	0.4111	#include <boost/system/error_code.hpp>
	0.4104	#include <boost/type_traits.hpp>
	0.3794	#include <future>
	0.3667	#include <boost/optional.hpp>
	0.3623	#include <boost/optional/optional.hpp>
	0.3266	#include <boost/bind.hpp>
	0.3135	#include <iomanip>
	0.3114	#include <boost/enable_shared_from_this.hpp>
	0.2852	#include <random>
	0.2838	#include <complex>
	0.2796	#include <locale>
	0.2745	#include <shared_mutex>
	0.2626	#include <thread>
	0.2605	#include <condition_variable>
	0.2475	#include <istream>
	0.2462	#include <fstream>
	0.2440	#include <sstream>
	0.2347	#include <mutex>
	0.2342	#include <iterator>
	0.2301	#include <scoped_allocator>
	0.2295	#include <iostream>
	0.2260	#include <unordered_map>
	0.2211	#include <ostream>

**Comment by pcmoritz** [comment]
Can we have number here on how much the compile time is with and without these changes (without caching)? That will give a better picture on how much the compile time is reduced.

**Comment by mehrdadn** [comment]
That would have to wait a _long_ time until I fix all instances of these, since including a header even once will have the same impact as including it multiple times. :\

**Pull request closed without merging**
