### PR TITLE
Modify RayLogLevel to avoid conflicts with DEBUG macro and ERROR macros that are defined externally

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

The log severity macros are far too generic and easily conflict with those defined externally. For example:

- `DEBUG` is defined in debug builds
- `ERROR` is defined by Windows

## Related issue number

`glog` handles this a bit differently:

https://github.com/google/glog/commit/6febec361e73860cc77d9cb0c6c14013c0e36ef0#diff-6cf325139803cd98ccab9ff58ebaa0b3

But their solution is still problematic since there's still no way to refer to the `DEBUG` and `ERROR` variables once the macros are defined.

Also, it seems to me their solution increases their own logging code's verbosity in return for making it more terse for users who don't include such macros. In our case, it's the opposite: we want to minimize our own code's verbosity. The shortest way I could think of was making `RAY_LOG_ERROR()` a macro and also a regular `enum` value.

#631

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by edoakes** [comment]
Looks like the tests aren't compiling - can you ping when they're fixed?

**Review by ericl — DISMISSED** [review]
I don't think we should merge this. Why not use a workaround, even if more complex, rather than uglifying the logging API?

**Comment by mehrdadn** [comment]
@ericl What workaround do you suggest? I haven't been able to think of one.

**Comment by ericl** [comment]
How about undefining those macros

**Comment by mehrdadn** [comment]
Bazel [passes `DEBUG` automatically](https://github.com/bazelbuild/bazel/issues/3513#issuecomment-327787964). `ERROR` is used in Windows for other things. Are you sure you want everybody who includes the header to be able to access neither?

**Comment by mehrdadn** [comment]
@ericl Also note that `ERROR` is only defined if the Windows header is included. So to undefine it, either way have to _always_ include an irrelevant Windows header, or we have to block its inclusion entirely. Both of these seem pretty bad options to me... do you really prefer either?

**Comment by ericl** [comment]
Yes, why not block those from coming in from the windows header? Or undef
it after including the windows header.

I don't really understand the debug thing, it works fine today does it not?

**Comment by mehrdadn** [comment]
@ericl Not it doesn't. It depends on `compilation_mode`. See for example: https://travis-ci.com/ray-project/ray/jobs/257764226#L847

**Comment by mehrdadn** [comment]
To summarize, here is the issue:

- Bazel defines `DEBUG` in debug builds
- Windows defines `ERROR` in some drawing-related headers
- Both of these conflict with our log severity macros.

Here are the different approaches and the trade-offs I see:

1. [`glog`'s solution](https://github.com/google/glog/commit/6febec361e73860cc77d9cb0c6c14013c0e36ef0#diff-6cf325139803cd98ccab9ff58ebaa0b3): rename the severities (`ERROR` -> `GLOG_ERROR`), then define short aliases (like `ERROR`) iff the user doesn't opt-out via a `GLOG_NO_ABBREVIATED_SEVERITIES` macro.

    - Pros: Lets the user opt-out if necessary, but minimizes typing by default (`LOG(ERROR)` rather than `LOG(GLOG_ERROR)`) for files that don't include 
a Windows header defining `ERROR`.
    - Cons: `DEBUG` will be defined by Bazel in _every_ file when building in debug mode, so there is never a case when we can use the shorter version.

2. My solution (this PR): rename the severities (`ERROR` -> `RAY_LOG_ERROR`) as with glog's approach, but also define `RAY_LOG_ERROR()` as a macro that can be used instead of `RAY_LOG(ERROR)`.

    - Pros: Fully solves the semantic issue. No more conflicts or need to fight the operating system or build system in any way.
    - Cons: `RAY_LOG_ERROR()` is less elegant syntax than `RAY_LOG(ERROR)`. We also have to modify the entire codebase (which I have done in this PR).

3. @ericl's solution:
   For `DEBUG`: We never tell Bazel to build in debug mode with `--compilation_mode=dbg`. To get a debug build, we make all the necessary adjustments ourselves manually, e.g. by passing `--copt=-O0` instead.
   For `ERROR`: Block the Windows header that defines this. If the macro is already defined, we undefine it and/or raise an error.

    - Pros: Maintains the `RAY_LOG(ERROR)` syntax, which is a bit more elegant than `RAY_LOG_ERROR` and avoids modifying the macro's users.
    - Cons:  
      We have to actively fight Bazel and manually add workarounds for its facilities. Specifically, to get a debug build in the future, manually add a flag for every relevant language/toolchain every time (like `-g -O0` for GCC/Clang; I'm not sure if Rust has an equivalent). Furthermore, I know some C/C++ libraries come with compile-time flags (`-D_ITERATOR_DEBUG_LEVEL` in Visual C++, `-D_GLIBCXX_DEBUG` in libstdc++, etc.). We don't know exactly which ones Bazel might handle now or in the future, but we will definitely have to handle them manually moving forward.  
       Building in `opt` mode while manually passing debug flags may also have other repercussions, and neither of us is aware of their full extent. As one example, I know some C/C++ runtimes come with debug versions, so we'll have to include flags for that uniformly across the codebase (`/MDd` in Visual C++ runtimes; I'm not sure about the GCC/Clang equivalent if there is any) or we'll get linker errors. Furthermore, some languages have specific flags for _optimized_ builds. Rust seems to have `--release`, but I'm not familiar with it; perhaps someone more familiar with Rust can chime in. But in those cases it seems it would be impossible for us to get debug builds at all.  
      I'm not sure what other consequences might be, if any.  
      Lastly, it will likely be quite confusing for some developers and take some time to track down when we run across the conflicts. This was already the case when @pcmoritz and I [came across the errors](https://travis-ci.com/ray-project/ray/jobs/257764226#L847); it took us some time to track down how this happened at all.

I'm not sure if I missed anything, but if I did, please let me know.

**Comment by edoakes** [comment]
Did we settle on just using glog directly for this? I would be ok with that solution - don't see a need to swap in the immediate future.

**Comment by mehrdadn** [comment]
It's fine on my end too, but I think @pcmoritz was double-checking to make sure it's fine.

**Comment by mehrdadn** [comment]
@edoakes @pcmoritz I think I'll just put in a temporary patch for `ERROR` and ignore the issues with `DEBUG` for now. Can one of you approve this for the time being? We'll still want to do the migration to glog and fix the issue with `DEBUG`, but this is a change I need to be able to build on Windows at all. (So far I've been maintaining these changes locally, but they're becoming a lot of overhead as they accrue.)

**Review by edoakes — APPROVED** [review]

**Pull request merged**
