### PR TITLE
[no_early_kickoff][core][dashboard] Feature flag task logs recording (#34056)

### LINKED ISSUE #33949: [core] perf regression: 1_1_actor_calls_async
### What happened + What you expected to happen

REGRESSION 8.88%: 1_1_actor_calls_async (THROUGHPUT) regresses from 8098.766293651375 to 7379.572758156523 (8.88%) in 2.4.0/microbenchmark.json

last run shows worse results 

{'perf_metric_name': '1_1_actor_calls_async', 'perf_metric_value': 6939.589314887375, 'perf_metric_type': 'THROUGHPUT'}

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-pr/builds/33295#0187345e-42fb-4135-9ffc-ad8e23cd1f07

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
This should address a few issues introduced by the original task log recording features:

[core] perf regression: 1_1_actor_calls_concurrent #33924 [core] perf regression: 1_1_actor_calls_async #33949 [Tests] Fix two skipped Windows test for test_task_event_2.py #33738 The roocasue with the regressions are:
With #32943, we are recording log file offsets before and after executing a task, which calls tell() on the file descriptor object for each worker.

The cost of that shows up when there are concurrent execution of tasks on a single worker.

I am turning this off by default for this release since the subsequent PRs are not merged yet. We will need to tackle or resolve the regression once we turn this feature on when we merge subsequent PRs. One idea is to make this "finding-out-offset-procedure" async, e.g. we try to locate the exact task id's log offset when we querying the task logs at querying time.

## Related issue number
Closes #33924 
Closes #33949 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Approval here: https://github.com/ray-project/ray/pull/34056#pullrequestreview-1372028024

**Review by clarng — APPROVED** [review]

**Comment by clarng** [comment]
fix dco?

**Comment by rickyyx** [comment]
Fixed.

**Comment by clarng** [comment]
The workflow test failure looks new

2.4.0 doesn't have it : https://buildkite.com/ray-project/oss-ci-build-branch/builds/3201

**Comment by clarng** [comment]
> oh which job is that? It might be flaky.

https://buildkite.com/ray-project/oss-ci-build-pr/builds/17527#01875261-4ea5-41df-98ba-6e5a80845dfd

**Comment by rickyyx** [comment]
The test looks unrelated (workflow logging is completely different from this I believe). Let me retry first.

**Comment by clarng** [comment]
Hmm looks like it is still failing

**Comment by rickyyx** [comment]
Hmm, that's surprising. Let me look into it more closely.

**Review by fishbone — APPROVED** [review]

**Comment by rickyyx** [comment]
Ok - looks [no_early_kickoff] solves the issue. Must be some incompatability with the docker prebuilt on the release branch.

**Comment by rickyyx** [comment]
This should be ready to merge: cc @clarng

**Review by zhe-thoughts — APPROVED** [review]

**Pull request merged**
