### PR TITLE
[Event] set event_log_reporter_enabled True by default

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
We already made event framework thread-safe. So:
- Set event_log_reporter_enabled True by default
- Set "worker_id" field for core worker threads.

### CODE REVIEW

**Comment by rkooo567** [comment]
Mark as action required until the other PR is merged

**Comment by SongGuyang** [comment]
@rkooo567 Can we merge this?

**Comment by scv119** [comment]
@SongGuyang we probably want to first evaluate the pref hits before **enabling this by default**. Are you (Ants) blocked by this?

**Review by rkooo567 — APPROVED** [review]
We should run the nightly test before merging it

**Comment by scv119** [comment]
https://github.com/ray-project/ray/pull/18936 @rkooo567

**Comment by rkooo567** [comment]
@SongGuyang there are some test failures. I think it might not be related , but can you merge the latest master one more time?

**Comment by SongGuyang** [comment]
@rkooo567 All checks have passed.

**Pull request merged**
