### PR TITLE
[autoscaler][kubernetes] K8s memory detection tweak

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?
This is a minor tweak on top of https://github.com/ray-project/ray/pull/14567

Let's use the min of requests and limits for memory auto-detection on K8s.
This change should fix the error observed here
https://github.com/ray-project/ray/issues/14708
For later, we should consider validating that the user set a memory limit.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
 
Manual test.

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
What's the behavior if the user hasn't set a memory limit?

**Review by wuisawesome — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
> What's the behavior if the user hasn't set a memory limit?

As of #14567, you get a confusing error and the cluster fails to launch.

Before that, at least according to the potentially outdated comments in the example configs, it may have tried to allocate way too much object store memory.

It would worth investigating at some point exactly what happens.

**Comment by ConeyLiu** [comment]
Hi @DmitriGekhtman, Does the auto-detect memory size will be set in `RAY_OVERRIDE_RESOURCES` when the ray nodes startup. If set that means the raylet will only use the `min(requests, limit)` resources. Does this expect?

**Comment by DmitriGekhtman** [comment]
> Hi @DmitriGekhtman, Does the auto-detect memory size will be set in `RAY_OVERRIDE_RESOURCES` when the ray nodes startup? If set that means the raylet will only use the `min(requests, limit)` resources. Does this expect?

Users should set memory limits=request to get consistent behavior, and all of the example configs have comments expressing this.
Using min(requests, limit) is consistent with that expectation.

**Comment by ConeyLiu** [comment]
Thanks for the explanation. LGTM.

**Comment by edoakes** [comment]
@DmitriGekhtman LMK when this is ready to merge

**Comment by DmitriGekhtman** [comment]
Thanks for the reminder -- it's good to merge.

**Pull request merged**
