### PR TITLE
[core][state][log] Cherry pick changes to prevent state API from reading files outside the Ray log directory

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Cherry-pick two related PRs:

- https://github.com/ray-project/ray/pull/41467
- https://github.com/ray-project/ray/pull/41502

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]
tests results look good to me so far.

**Comment by aslonnie** [comment]
@edoakes are there going to be more changes, or is this ready to merge?

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
Since this is just cherry picking the PRs, I think we can just merge it whenever the tests look good -- I also kicked off the macOS ones but we probably don't need to block on that :)

**Comment by edoakes** [comment]
No further changes from me, thanks!

**Pull request merged**
