### PR TITLE
[runtime env] remove the API ray.runtime_env.get_current_runtime_env

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?

Remove the API `ray.runtime_env.get_current_runtime_env()` and use `ray.get_runtime_context().runtime_env` instead.

## Related issue number
https://github.com/ray-project/ray/pull/22594

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by SongGuyang** [comment]
@edoakes There is a new issue I want to discuss:
Currently, `ray.get_runtime_context().runtime_env` return a new dict instance so we can modify it directly for inheritance. Like:
```
Actor.options(runtime_env=ray.get_runtime_context().runtime_env.update(
            {"env_vars": {"A": "a", "B": "b"}}))
```

This use case is a little weird because `runtime_env` is a property API which often be seen as a reference. So, do we need to add a new API in runtime_context? Like:
```
Actor.options(runtime_env=ray.get_runtime_context().get_runtime_env().update(
            {"env_vars": {"A": "a", "B": "b"}}))
```

**Comment by edoakes** [comment]
@SongGuyang it's not safe to return a reference to the worker's runtime_env anyways (don't want users messing with it), so I think let's just document that it returns a copy

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
linter failing on docs

**Comment by edoakes** [comment]
@SongGuyang ping to get this merged

**Comment by edoakes** [comment]
Yes we should still merge this; it updates tests and removes the currently unused code

**Comment by SongGuyang** [comment]
OK.

**Pull request closed without merging**
