### PR TITLE
[Serve] Add py3.11 release test

### LINKED ISSUE #38611: [serve] Add basic release test for Python 3.11 to avoid breakages
In the future we will fully test Python 3.11, but for now we should do the minimal thing to avoid obvious breakages.

Example from Ray core that we can mimic: https://github.com/ray-project/ray/pull/38511

We could use our microbenchmark or the "1k deployment noop" test.

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

To discover any failures to migrate python311.

## Related issue number

Closes: https://github.com/ray-project/ray/issues/38611

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sihanwang41** [comment]
succeed: https://buildkite.com/ray-project/release-tests-pr/builds/49744

**Review by can-anyscale — APPROVED** [review]

**Comment by sihanwang41** [comment]
@edoakes ping for review & merge.

**Comment by sihanwang41** [comment]
@edoakes ping again ^^

**Review by edoakes — APPROVED** [review]

**Pull request merged**
