### PR TITLE
Remove deprecated Java PG APIs.

### PR DESCRIPTION
**Pull request by jovany-wang**
## Why are these changes needed?
These APIs were deprecated at least 7+ months and 4+ versions, it's the time and very necessary to remove them.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by clay4444** [comment]
should we remove it now?  cc @kfstorm

**Comment by jovany-wang** [comment]
Yes. i believe it's the time to remove them since these were deprecated in a long time.

**Comment by kfstorm** [comment]
I think it's OK to remove them.

**Review by kfstorm — APPROVED** [review]

**Comment by jovany-wang** [comment]
Hi @simon-mo , could you help to check why the CI jobs were not triggered, thx.

**Comment by simon-mo** [comment]
Seems to be running now.

**Comment by jovany-wang** [comment]
Windows failure is not related.

**Pull request merged**
