### PR TITLE
Add basic jobs release test with Tune script

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Adds basic jobs release tests that connects to the test cluster and runs a basic tune script.  Specifies `ray[tune]` in the `runtime_env` `pip` dependencies.  Two tests:

(1) Uses a local `working_dir`
(2) Uses a remote working_dir from a zip github URL. 

Manually tested on my laptop with `python ray_release/scripts/run_release_test.py --ray-wheels master jobs_basic_remote_working_dir` and `python ray_release/scripts/run_release_test.py --ray-wheels master jobs_basic_local_working_dir`

Sample output:

```
[INFO 2022-03-31 13:29:46,888] sdk_runner.py: 88  Link to cluster: https://console.anyscale.com/o/anyscale-internal/projects/prj_iDw44tDdgRQzaPYvCixQmnnp/clusters/ses_9GBC1YPNuEvyz3NgHdPQPMHZ
[INFO 2022-03-31 13:30:17,533] job_manager.py: 42  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/nhzjdyndjw --acl bucket-owner-full-control with {} via ray job submit
[ERROR 2022-03-31 13:30:21,327] glue.py: 237  Could not fetch results for test command
[ERROR 2022-03-31 13:30:21,327] glue.py: 238  Could not fetch results from session: 
Traceback (most recent call last):
  File "/Users/archit/ray/release/ray_release/command_runner/sdk_runner.py", line 164, in fetch_results
    self.file_manager.download(self.result_output_json, tmpfile)
  File "/Users/archit/ray/release/ray_release/file_manager/job_file_manager.py", line 51, in download
    retcode, _ = self._run_with_retry(
  File "/Users/archit/ray/release/ray_release/file_manager/job_file_manager.py", line 33, in _run_with_retry
    assert callable(f)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/archit/ray/release/ray_release/glue.py", line 235, in run_release_test
    command_results = command_runner.fetch_results()
  File "/Users/archit/ray/release/ray_release/command_runner/sdk_runner.py", line 172, in fetch_results
    raise ResultsError(f"Could not fetch results from session: {e}") from e
ray_release.exception.ResultsError: Could not fetch results from session: 
[INFO 2022-03-31 13:30:22,223] handle.py: 27  Checking results for test jobs_basic_local_working_dir using alerting suite default
[INFO 2022-03-31 13:30:22,223] handle.py: 41  No alerts have been raised - test passed successfully!
[INFO 2022-03-31 13:30:22,224] log.py: 10  Test jobs_basic_local_working_dir finished after 325.74 seconds. Last logs:

status: RUNNING
status: RUNNING
status: RUNNING
status: RUNNING
status: RUNNING
status: RUNNING
status: RUNNING
status: SUCCEEDED
Status message:  Job finished successfully.
PASSED


[INFO 2022-03-31 13:30:22,224] log.py: 16  Got the following metadata: 
  name:    jobs_basic_local_working_dir
  status:  finished
  runtime: 325.74
  stable:  True

  buildkite_url: 
  wheels_url:    https://s3-us-west-2.amazonaws.com/ray-wheels/master/2eaa54bd763ae0e63158ae0d939633c804394b78/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  cluster_url:   https://console.anyscale.com/o/anyscale-internal/projects/prj_iDw44tDdgRQzaPYvCixQmnnp/clusters/ses_9GBC1YPNuEvyz3NgHdPQPMHZ

[INFO 2022-03-31 13:30:22,224] log.py: 36  Did not find any results.
[INFO 2022-03-31 13:30:22,231] run_release_test.py: 142  Release test pipeline for test jobs_basic_local_working_dir completed. Returning with exit code = 0
```

It looks like it's passing, not sure how important the exceptions are.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — COMMENTED** [review]
Test looks good. Shall we run this on buildkite before merge?

Also to get rid of the exception, you'll have to write some dict to `TEST_OUTPUT_JSON`:

```
    test_output_json = os.environ.get(
        "TEST_OUTPUT_JSON", "/tmp/release_test_output.json"
    )
    with open(test_output_json, "wt") as f:
        json.dump(result, f)
```

`result` usually contains some metrics but it can also be empty or just `{passed: True}` or so

**Comment by architkulkarni** [comment]
> Test looks good. Shall we run this on buildkite before merge?
> 
> Also to get rid of the exception, you'll have to write some dict to `TEST_OUTPUT_JSON`:
> 
> ```
>     test_output_json = os.environ.get(
>         "TEST_OUTPUT_JSON", "/tmp/release_test_output.json"
>     )
>     with open(test_output_json, "wt") as f:
>         json.dump(result, f)
> ```
> 
> `result` usually contains some metrics but it can also be empty or just `{passed: True}` or so

Thanks!  I have this in the PR though: https://github.com/ray-project/ray/pull/23474/files#diff-d0d3c76c358518f90dd097c0d858cf3141ce8f29694bdb1634ab2fa04fec26c7R70-R76 Maybe it's throwing an exception because I didn't set the environment variable before running locally?

Anyways, here's the buildkite run I just started, let's see what happens: https://buildkite.com/ray-project/release-tests-branch/builds/324

**Comment by krfricke** [comment]
Ah right, sorry. This seems to be a release package error, I'll fix it

**Review by krfricke — APPROVED** [review]

**Comment by architkulkarni** [comment]
The release test passed: https://buildkite.com/ray-project/release-tests-branch/builds/324 @edoakes this is ready to merge!

**Pull request merged**
