### PR TITLE
[train] Upgrade transformers in requirements

### LINKED ISSUE #36011: [CI] Upgrade to newer `transformers` version
We currently have `transformers` pinned to 4.19.1 for our CI testing and ML docker images. This release is from May 2022, so it's missing a lot of the newer Huggingface features.

Upgrading to the latest 4.29.2 results in this issue with distributed pytorch training using gloo: https://github.com/huggingface/transformers/issues/22482, which was introduced in 4.27.

Using 4.26 instead leads to memory leak issues with `pbt_transformers` test.

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Transformers currently can't be upgraded as it breaks the PBT test due to memory shortage. We should run this test on a larger instance and upgrade transformers in the requirements file.

## Related issue number

Closes #36011

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]
Awesome thanks @krfricke!

**Comment by amogkam** [comment]
Bump on this @krfricke :)

**Comment by krfricke** [comment]
Apologies for the delay. Aiming to get this in soon.

**Comment by krfricke** [comment]
Breaks some CI jobs with OOM - hard to debug without access to CI machines, so tagging @matthewdeng for awareness and closing for now

**Pull request closed without merging**
