### PR TITLE
[ray_client] Add metadata to gRPC requests

### PR DESCRIPTION
**Pull request by pcmoritz**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by AmeerHajAli** [comment]
One thing I would recommend is to run this as a test:
https://github.com/ray-project/ray/blob/master/python/ray/experimental/client/client_app.py

**Comment by ericl** [comment]
Looks like some failing tests

**Review by barakmich — APPROVED** [review]
LGTM. Thanks for piping these through :)

**Review by AmeerHajAli — APPROVED** [review]

**Comment by pcmoritz** [comment]
@barakmich If I run `client_app.py` with this PR, I get the following assertion error:

**Comment by pcmoritz** [comment]
Additional datapoint: If I run the same test (also going over https and the proxies) from within the session, it passes. So either the time delay going over the internet from my laptop to the cloud introduces the failure or there is some kind of library versioning issue. In any case it seems independent of the PR so I will go ahead an merge it!

**Pull request merged**
