### PR TITLE
[tune] cache checkpoint serialization

### LINKED ISSUE #11233: [tune] efficient experiment checkpointing + slow down at large trials
### What is the problem?

Serializing experiment checkpoints and writing them to disk introduces much overhead with a growing number of trials.

```

2020-10-06 16:00:49,638	INFO tune.py:455 -- Total run time: 352.58 seconds (338.94 seconds for the tuning loop).
         966507954 function calls (693669931 primitive calls) in 366.603 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.047    0.047  366.643  366.643 /Users/kai/coding/ray/python/ray/tune/tune.py:70(run)
     9000    0.328    0.000  325.292    0.036 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:548(step)
     6035   22.127    0.004  232.843    0.039 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/json/__init__.py:120(dump)
     9001    0.036    0.000  232.199    0.026 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:466(checkpoint)
127546820/83287148   26.820    0.000  190.186    0.000 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/json/encoder.py:413(_iterencode)
306138387/83287148   67.773    0.000  177.002    0.000 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/json/encoder.py:333(_iterencode_dict)
84637053/83013228   13.932    0.000  162.742    0.000 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/json/encoder.py:277(_iterencode_list)
  1844153    4.992    0.000   62.349    0.000 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:44(default)
  1844153    3.316    0.000   53.859    0.000 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:53(_to_cloudpickle)
  1901173    5.175    0.000   47.817    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle_fast.py:58(dumps)
60004/57004    3.631    0.000   35.469    0.001 {built-in method builtins.all}
  1904173    1.017    0.000   33.343    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle_fast.py:654(dump)
  1904173   12.997    0.000   32.326    0.000 {function CloudPickler.dump at 0x119ab9830}
     9000    0.184    0.000   32.301    0.004 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:647(_get_next_trial)
     6000    0.079    0.000   30.728    0.005 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:664(_process_events)
     6000    0.225    0.000   25.079    0.004 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:713(_process_trial)
    18001    0.067    0.000   23.913    0.001 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:543(is_finished)
 26430541   11.491    0.000   21.444    0.000 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:545(<genexpr>)
 83284149   20.357    0.000   20.357    0.000 {method 'write' of '_io.TextIOWrapper' objects}
  3929395    3.983    0.000   19.056    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle_fast.py:537(reducer_override)
     3000    0.012    0.000   18.483    0.006 /Users/kai/coding/ray/python/ray/tune/ray_trial_executor.py:335(start_trial)
     3000    0.075    0.000   18.374    0.006 /Users/kai/coding/ray/python/ray/tune/ray_trial_executor.py:264(_start_trial)
     3000    0.045    0.000   15.740    0.005 /Users/kai/coding/ray/python/ray/tune/ray_trial_executor.py:179(_setup_remote_runner)
 39617310   14.743    0.000   14.743    0.000 /Users/kai/coding/ray/python/ray/tune/trial.py:571(is_finished)
        1    0.000    0.000   14.060   14.060 /Users/kai/coding/ray/python/ray/tune/analysis/experiment_analysis.py:326(__init__)
     3000    0.290    0.000   13.925    0.005 /Users/kai/coding/ray/python/ray/tune/trial.py:517(update_last_result)
102185912/102182912   12.540    0.000   13.783    0.000 {built-in method builtins.isinstance}
  1924513    2.085    0.000   13.738    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle_fast.py:372(_class_reduce)
        1    0.000    0.000   13.611   13.611 /Users/kai/coding/ray/python/ray/tune/analysis/experiment_analysis.py:40(__init__)
        1    0.015    0.015   13.611   13.611 /Users/kai/coding/ray/python/ray/tune/analysis/experiment_analysis.py:160(fetch_trial_dataframes)
     3000    0.022    0.000   13.573    0.005 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/io/parsers.py:530(parser_f)
     3000    0.065    0.000   13.539    0.005 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/io/parsers.py:416(_read)
     3000    0.030    0.000   12.026    0.004 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/io/parsers.py:1131(read)
    15002    0.499    0.000   11.876    0.001 /Users/kai/coding/ray/python/ray/state.py:282(node_table)
  1927536    0.943    0.000   11.677    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle.py:166(_is_importable_by_name)
  1927536    3.424    0.000   10.733    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle.py:171(_lookup_module_and_qualname)
 13213770    5.428    0.000   10.218    0.000 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:653(<genexpr>)
     6000    0.027    0.000    9.351    0.002 /Users/kai/coding/ray/python/ray/tune/trial_runner.py:912(_execute_action)
  1904173    6.732    0.000    9.038    0.000 /Users/kai/coding/ray/python/ray/cloudpickle/cloudpickle_fast.py:522(__init__)
3432104/36017    3.846    0.000    8.900    0.000 /Users/kai/.pyenv/versions/3.7.7/lib/python3.7/copy.py:132(deepcopy)

...

{'x': 2.003789495341138}
Took 366.75 seconds to run.
```

### Reproduction (REQUIRED)

```
import time
from ray import tune


def objective(config):
    x = config["x"]
    return (x - 2) ** 2


start = time.time()

import cProfile, pstats, io
from pstats import SortKey
pr = cProfile.Profile()
pr.enable()

analysis = tune.run(
    objective,
    metric="_metric",
    mode="min",
    config={"x": tune.uniform(-10, 10)},
    num_samples=3_000,
    reuse_actors=True
)

pr.disable()
s = io.StringIO()
sortby = SortKey.CUMULATIVE
ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
ps.print_stats()
print(s.getvalue())

print(analysis.best_config)
print(f"Took {time.time() - start:.2f} seconds to run.")
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Ray Tune's experiment state checkpointing incurs large overhead in serializing trial states. This is especially apparent when training a large number of trials. With the current version, just scaling to 6000 trials leads to a checkpointing operation of more than 10 seconds - coinciding with the checkpointing period. In effect, the tuning process breaks down as the trial runner spends all its time checkpointing. Profiling shows that json serializsation methods are called over 20 million times.

This PR fixes this issue by caching the serialized json states from trials, avoiding unnecessary serialization. This works through a two-level caching system. On the `Trial` side, a method `get_json_state()` is introduced, which returns a cached version of a serialized json string. This cache is invalidated whenever relevant trial properties are updated or changed.

On the `TrialExecutor` side (which collects the trial states), a lazy-caching process is introduced. Whenever `try_checkpoint_metadata` is called, the respective trial is added to a set of trials that has to be updated. Only when calling `get_checkpoints()` are the trials actually updated, potentially triggering new serialization on the `Trial` side.

These changes result in the following speedups that become more apparent with a rising number of trials (measured on my MBP):

- **100 trials**: 2.07 seconds (from 2.11 seconds)
- **1,000 trials**: 16.33 seconds (from 18.20 seconds)
- **2,000 trials**: 37.61 seconds (from 43.22 seconds)
- **4,000 trials**: 83.22 seconds (from 122.80 seconds)
- **10,000 trials**: 386.94 seconds (from _infeasible_)

Thus with more than 4000 trials we get about 33% speedup, and more than 6000 trials become feasible.

We also see this in the overhead logs:

Before (ever growing times):
```
2020-11-17 11:07:03,220	WARNING util.py:143 -- The `experiment_checkpoint` operation took 4.4502928256988525 seconds to complete, which may be a performance bottleneck.
2020-11-17 11:07:13,503	WARNING util.py:143 -- The `experiment_checkpoint` operation took 4.727848768234253 seconds to complete, which may be a performance bottleneck.
2020-11-17 11:07:24,045	WARNING util.py:143 -- The `experiment_checkpoint` operation took 5.266491889953613 seconds to complete, which may be a performance bottleneck.
```

After (constant times):
```
2020-11-17 11:09:39,041	WARNING util.py:143 -- The `experiment_checkpoint` operation took 0.6112241744995117 seconds to complete, which may be a performance bottleneck.
2020-11-17 11:09:49,018	WARNING util.py:143 -- The `experiment_checkpoint` operation took 0.5861878395080566 seconds to complete, which may be a performance bottleneck.
```

The checkpointing overhead seems to remain constant, though in the future we might get more speedups by optimizing disk IO (e.g. not always re-writing finished trials).

## Related issue number

Closes #11233

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
Code looks good! Can you check if the 4k benchmark changes?

**Comment by krfricke** [comment]
90.61 in the last run, so a little bit more, but still significantly faster than before.
2k is about the same performance (even 1 sec faster, but that's probably testing variance)

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
tests failing?

**Comment by krfricke** [comment]
Should be good now @richardliaw

**Pull request merged**
