### PR TITLE
Revert "[Dashboard] Fix missing actor pid"

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#13229

### CODE REVIEW

**Comment by amogkam** [comment]
@fyrestone @WangTaoTheTonic @rkooo567 #13229 looks to be causing `cluster_task_manager_test` to fail. 

You can check on the flakey test tracker: https://flakey-tests.ray.io/

**Comment by fyrestone** [comment]
Sorry, the `raylet::MockWorker::GetProcess` crashes at `RAY_CHECK(false) << "Method unused";`. I will fix it.

**Comment by amogkam** [comment]
Thanks @fyrestone! Can you please ping me when you do.

**Comment by fyrestone** [comment]
> Thanks @fyrestone! Can you please ping me when you do.

OK. I am watching the CI of the fix PR. I will ping you if the fix is merged.

**Comment by fyrestone** [comment]
> Thanks @fyrestone! Can you please ping me when you do.

The fix has been merged.

**Pull request closed without merging**
