### PR TITLE
[Dashboard] Make GPU name tooltip appear when hovering over entire GPU entry

### LINKED ISSUE #42208: Ray Dashboard: Better GPU utilization visibility
### Description

Feedback from @robin-anyscale:

Sometimes i dont know which GPU did ray cluster used for scaling, so i typically click on GRAM to find the accelerator (its cool that it tells me the GPU used) but i dont see same behavior when i click on GPU tab (marked in red). It will be great if we can see it consistently in both the places or find what gpu is being used from some other place

image

### Use case

Debugging serve workloads

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Previously the GPU name would only appear when hovering over the slot name (the part that says [0]).

This PR makes it appear also when hovering over the rest of the entry (the utilization bar).  This is consistent with how the GRAM entry is currently displayed.

## Related issue number

Closes #42208 

Context copied from the linked issue:
> Actually, for the GPU column, the tooltip currently appears, but only if you hover over the "[0]" part, not over the utilization bar.
> 
> Screenshot 2024-01-09 at 3 23 46 PM
>
> For the GRAM column, the tooltip appears if you hover over the "[0]" part or the utilization bar. 
> Screenshot 2024-01-09 at 3 24 26 PM
> 
> So I think we just need to make sure that the tooltip appears when hovering over the utilization bar in the GPU column.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
@alanwguo how would you recommend testing this part (manually or otherwise)?

**Comment by alanwguo** [comment]
> @alanwguo how would you recommend testing this part (manually or otherwise)?

One way is to let this PR build a ray wheel and install it as a cluster env to use on Anyscale and launch a machine with a GPU.

Alternatively, you can test with a kube-ray cluster with a GPU node?

**Comment by architkulkarni** [comment]
It works:


Uploading Screen Recording 2024-01-11 at 11.32.29 AM.mov…

**Comment by architkulkarni** [comment]
Screenshot 2024-01-11 at 11 38 49 AM

https://github.com/ray-project/ray/assets/5459654/db29bf91-6b95-4aac-95c4-662024aa9e56

**Review by alanwguo — APPROVED** [review]
awesome!

**Pull request merged**
