### PR TITLE
[Doc] Run pre-commit on rllib docs

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

Currently we have no linting on any part of the docs code. This PR runs pre-commit on the rllib docs.

This PR fixes the following issues:

```
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing doc/source/rllib/rllib-rlmodule.rst
Fixing doc/source/rllib/rllib-offline.rst
Fixing doc/source/rllib/images/catalog/ppo_catalog_and_rlm_diagram.svg
Fixing doc/source/rllib/key-concepts.rst
Fixing doc/source/rllib/rllib-fault-tolerance.rst
Fixing doc/source/rllib/images/connector-diagram.svg
Fixing doc/source/rllib/images/catalog/catalog_rlmspecs_diagram.svg
Fixing doc/source/rllib/images/catalog/catalog_and_rlm_diagram.svg
Fixing doc/source/rllib/rllib-learner.rst

fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing doc/source/rllib/package_ref/policy.rst
Fixing doc/source/rllib/images/episodes/sa_episode_getters.svg
Fixing doc/source/rllib/images/algos/sac-architecture.svg
Fixing doc/source/rllib/package_ref/evaluation.rst
Fixing doc/source/rllib/images/multi-flat.svg
Fixing doc/source/rllib/images/algos/marwil-architecture.svg
Fixing doc/source/rllib/images/rllib-config.svg
Fixing doc/source/rllib/images/sigils/cont-actions.svg
Fixing doc/source/rllib/images/sigils/rllib-sigil-vector-envs.svg
Fixing doc/source/rllib/images/algos/ppo-architecture.svg
Fixing doc/source/rllib/images/sigils/rllib-sigil-tf-and-torch.svg
Fixing doc/source/rllib/images/a2c-arch.svg
Fixing doc/source/rllib/images/sigils/rllib-sigil-distributed-learning.svg
Fixing doc/source/rllib/images/episodes/sa_episode_non_finalized.svg
Fixing doc/source/rllib/images/dqn-arch.svg
Fixing doc/source/rllib/images/episodes/sa_episode_non_finalized_vs_finalized.svg
Fixing doc/source/rllib/images/algos/appo-architecture.svg
Fixing doc/source/rllib/images/sigils/rllib-sigil-multi-agent.svg
Fixing doc/source/rllib/images/sigils/multi-gpu.svg
Fixing doc/source/rllib/images/episodes/usage_of_episodes.svg
Fixing doc/source/rllib/images/rollout_worker_class_overview.svg
Fixing doc/source/rllib/images/catalog/ppo_catalog_and_rlm_diagram.svg
Fixing doc/source/rllib/images/sigils/new-api-stack.svg
Fixing doc/source/rllib/images/sigils/old-api-stack.svg
Fixing doc/source/rllib/images/sigils/rllib-sigil-offline-rl.svg
Fixing doc/source/rllib/key-concepts.rst
Fixing doc/source/rllib/images/impala-arch.svg
Fixing doc/source/rllib/images/algos/dqn-architecture.svg
Fixing doc/source/rllib/images/episodes/sa_episode.svg
Fixing doc/source/rllib/images/sigils/rllib-sigil-external-simulators.svg
Fixing doc/source/rllib/images/episodes/sa_episode_finalized.svg
Fixing doc/source/rllib/images/rllib-envs.svg
Fixing doc/source/rllib/images/dreamerv3/atari100k_1_vs_4gpus.svg
Fixing doc/source/rllib/images/apex-arch.svg
Fixing doc/source/rllib/images/rllib-index-header.svg
Fixing doc/source/rllib/images/algos/icm-architecture.svg
Fixing doc/source/rllib/images/sigils/multi-agent.svg
Fixing doc/source/rllib/images/sigils/multi-node-multi-gpu.svg
Fixing doc/source/rllib/images/env_classes_overview.svg
Fixing doc/source/rllib/images/connector-diagram.svg
Fixing doc/source/rllib/images/rllib-components.svg
Fixing doc/source/rllib/images/algos/impala-architecture.svg
Fixing doc/source/rllib/images/rllib-sample-collection.svg
Fixing doc/source/rllib/images/policy_classes_overview.svg
Fixing doc/source/rllib/images/dreamerv3/dmc_1_vs_4gpus.svg
Fixing doc/source/rllib/images/algos/dreamerv3-architecture.svg
Fixing doc/source/rllib/package_ref/replay-buffers.rst
Fixing doc/source/rllib/images/catalog/catalog_rlmspecs_diagram.svg
Fixing doc/source/rllib/images/dreamerv3/pong_1_2_and_4gpus.svg
Fixing doc/source/rllib/images/ddppo-arch.svg
Fixing doc/source/rllib/images/multi-agent.svg
Fixing doc/source/rllib/images/rllib-logo.svg
Fixing doc/source/rllib/images/algos/curiosity-architecture.svg
Fixing doc/source/rllib/images/episodes/sa_episode_cut_and_lookback.svg
Fixing doc/source/rllib/images/rllib-trajectory-view-example.svg
Fixing doc/source/rllib/images/rllib-api.svg
Fixing doc/source/rllib/images/rllib-stack.svg
Fixing doc/source/rllib/images/sigils/discr-actions.svg
Fixing doc/source/rllib/images/algos/bc-architecture.svg
Fixing doc/source/rllib/images/rllib-batch-modes.svg
Fixing doc/source/rllib/images/rllib-external.svg
Fixing doc/source/rllib/images/catalog/catalog_and_rlm_diagram.svg
Fixing doc/source/rllib/images/sigils/single-agent.svg
Fixing doc/source/rllib/package_ref/utils.rst
Fixing doc/source/rllib/images/trainer_class_overview.svg
Fixing doc/source/rllib/rllib-learner.rst

check for added large files..............................................Passed
check python ast.........................................................Passed
check json...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
black....................................................................Passed
flake8...................................................................Passed
prettier.............................................(no files to check)Skipped
mypy.................................................(no files to check)Skipped
isort (python)...........................................................Passed
rst directives end with two colons.......................................Passed
rst ``inline code`` next to normal text..................................Failed
- hook id: rst-inline-touching-normal
- exit code: 1

doc/source/rllib/rllib-advanced-api.rst:268:An evaluation step runs - using its own ``EnvRunner``s - for ``evaluation_duration``

use logger.warning(......................................................Passed
check for not-real mock methods..........................................Passed
ShellCheck v0.9.0....................................(no files to check)Skipped
clang-format.........................................(no files to check)Skipped
Google Java Formatter................................(no files to check)Skipped
Check for Ray docstyle violations........................................Passed
Check for Ray import order violations....................................Passed
```

## Related issue number

Part of https://github.com/ray-project/ray/issues/42587.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
QQ: is this a local run or we have a ci lint check; if not the former should we have the ci lint check as well to lock in the win? thankks

**Comment by peytondmurray** [comment]
This is a local run - we do not have any kind of lint workflow set up to run on the docs at the moment (which is part of the reason there are issues to fix).

**Review by can-anyscale — APPROVED** [review]

**Review by sven1977 — APPROVED** [review]
LGTM.

**Pull request merged**
