### PR TITLE
[Dashboard] Delete old IA

### PR DESCRIPTION
**Pull request by alanwguo**
## Why are these changes needed?
Deletes the old IA. 
1. Deleted all routes from old IA that were no longer used. (One remained: CmdResult)
2. Moved all the new IA routes from `/new/<route>` to `/<route>`
3. Deleted all components that were no longer used as a result of removing old IA routes
4. Deleted all parameters for "newIA" and removed the code paths where newIA is false
5. Deleted the dark theme from the the app (theme was only adjustable in the old IA)

I manually tested every single button to make sure links still worked. Our testing on the dashboard is not quite good enough yet (it's getting better) to trust the tests to catch all possible bugs here. The earlier we get this into nightly, the more manual testing from users we can get.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
is this tested btw? (are we testing routing and stuff like that?)

**Comment by rkooo567** [comment]
dashboard test seems related

**Comment by alanwguo** [comment]
> dashboard test seems related

I don't think it is. The dashboard tests are failing job submission tests

**Comment by rkooo567** [comment]
Screen Shot 2023-03-15 at 5 32 25 PM

This test is clean in the master though. Do you use really old commit or sth?

**Comment by alanwguo** [comment]
tests are looking good now!

**Pull request merged**
