### PR TITLE
[Dashboard] Additional polish for jobs and progress bar

### PR DESCRIPTION
**Pull request by alanwguo**
## Why are these changes needed?
- Fix progress bar not showing loading bars on first load.
- Fix progress bar showing unloaded data when we have loaded data already cached
- Add spinnner and icons next to job status in jobs table and job detail page
- Fix progress bar using total tasks across all jobs instead of tasks specific to a single job
Screenshot 2023-04-25 at 5 00 46 PM
Screenshot 2023-04-25 at 5 00 52 PM

## Related issue number
Stacked commit on top of #19629

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by chaowanggg** [comment]
lgtm!

**Review by chaowanggg — APPROVED** [review]
lgtm!

**Comment by rkooo567** [comment]
I will merge it once @scottsun94 approves

**Comment by scottsun94** [comment]
Only have 1 question: If we put the spinner into the status box, will make it hard to main the consistency of the "Running" status box. (in other tables, like task table, we probably don't want add spinner since it could be distracting when a lot of tasks are running)
Screen Shot 2023-04-24 at 10 32 25 PM

**Comment by alanwguo** [comment]
> Only have 1 question: If we put the spinner into the status box, will it make it hard to maintain the consistency of the "Running" status box (in other tables, like task table, we probably don't want add spinner since it could be distracting when a lot of tasks are running) ?
> 
> Screen Shot 2023-04-24 at 10 35 34 PM

We can change the styling to look like that without adding them to all the pages. It can be an option like "withIcon=true"

**Comment by alanwguo** [comment]
> > We can change the styling to look like that without adding them to all the pages. It can be an option like "withIcon=true"
> 
> Cool. Can we put the spinner into the box then? Here is a simple spec. Screen Shot 2023-04-25 at 2 32 30 PM

Updated, please take another look

**Comment by scottsun94** [comment]
LGTM. Thanks!

**Comment by alanwguo** [comment]
@rkooo567 please merge!

**Pull request merged**
