### PR TITLE
[core] Fix bug in ref counting protocol for nested objects

### LINKED ISSUE #18751: [Bug] Ref count safety bug when inlining ObjectRefs or deserializing ObjectRefs multiple times
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

A ReferenceCountingAssertionError may be thrown when an object ref is deserialized multiple times or when an ObjectRef is inlined in another ObjectRef. This happens because of a broken optimization in the ref counting protocol that tries to avoid sending information about the same ObjectRef twice.

Here is an example. A contains B contains C. Worker starts with ref to A.

1. Worker deserializes A, gets ref to B.
2. Worker deserializes B, gets ref to C.
3. Worker deletes ref to C.
4. Worker deletes ref to A.
  - This triggers a callback to A's owner saying that worker is done using A but has a ref to B and C.
  - A's owner calls back again asking for reply once worker is done using B.
5. Worker deserializes B *again*, gets ref to C.
6. Worker deletes ref to B.
  - Worker responds to B's owner saying that worker is done using B.

The worker is supposed to say that it's still using C in step 6. Without this step, the worker gets a ReferenceCountingAssertionError when trying to use C. The reason is because of a broken optimization in the ref counting protocol where we only return info about nested refs once (in step 4).

### Reproduction script

```python
import ray

@ray.remote
def f(x):
    print(f"=> step {x}")
    if x > 400:
        return x
    return f.remote(x + 1)


r = f.remote(1)
while isinstance(r, ray.ObjectRef):
    r = ray.get(r)
```

This currently crashes due to #18552, but with a fix for that bug, the `ray.get` line may throw a RefCountingAssertionError.

### Anything else

In practice, this may not appear too often because it requires both nested refs and a certain order of messages in the ref counting protocol. The error can be reproduced very reliably with the included script.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

See #18751 for more info on the bug.

This changes the ref counting protocol to make sure that workers report any nested ObjectRefs that are still in scope. The main issue is that we need to make sure to eventually clean up all ObjectRefs that have gone out of Python scope, but we also need to make sure to account for all nested ObjectRefs that might still be in scope.

This PR uses a per-object flag to indicate whether it has any nested ObjectRefs that might still be in scope. The flag gets updated recursively whenever a nested ObjectRef is used. When an object ref goes out of scope and the borrower responds to the WaitForRefRemoved RPC, the reply includes all nested refs and we reset the flag. Then, we just have to make sure not to delete an ObjectRef if its flag is set.

This should not result in any additional messages, but individual messages may be larger because they can include object refs that have already gone out of scope and don't need to be reported. I chose not to optimize this for now.

## Related issue number

Closes #18751.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
src/ray/core_worker/reference_count.cc:233:28: error: reading variable 'object_id_refs_' requires holding mutex 'mutex_' [-Werror,-Wthread-safety-analysis]
--
  | auto contained_in_it = object_id_refs_.find(contained_in_borrowed_id);
  | ^
  | src/ray/core_worker/reference_count.cc:234:34: error: reading variable 'object_id_refs_' requires holding mutex 'mutex_' [-Werror,-Wthread-safety-analysis]
  | RAY_CHECK(contained_in_it != object_id_refs_.end());
  | ^

**Comment by ericl** [comment]
diff --git a/src/ray/core_worker/reference_count.cc b/src/ray/core_worker/reference_count.cc
  | index e63c591e0..96137725c 100644
  | --- a/src/ray/core_worker/reference_count.cc
  | +++ b/src/ray/core_worker/reference_count.cc
  | @@ -20,7 +20,7 @@
  | << " submitted_count: " << it->second.submitted_task_ref_count          \
  | << " contained_in_owned: " << it->second.contained_in_owned.size()      \
  | << " contained_in_borrowed: "                                           \
  | -                 << it->second.contained_in_borrowed_ids.size()                          \
  | +                 << (it)->second.contained_in_borrowed_ids.size()                        \
  | << " contains: " << it->second.contains.size()                          \
  | << " lineage_ref_count: " << it->second.lineage_ref_count;
  |  
  | diff --git a/src/ray/core_worker/reference_count_test.cc b/src/ray/core_worker/reference_count_test.cc
  | index 9816e5952..5877d7f65 100644
  | --- a/src/ray/core_worker/reference_count_test.cc
  | +++ b/src/ray/core_worker/reference_count_test.cc
  | @@ -258,7 +258,7 @@ class MockWorkerClient : public MockCoreWorkerClientInterface {
  | rc_(rpc::WorkerAddress(address_), publisher_.get(), subscriber_.get(),
  | /*lineage_pinning_enabled=*/false, client_factory) {}
  |  
  | -  ~MockWorkerClient() {
  | +  ~MockWorkerClient() override {
  | if (!failed_) {
  | AssertNoLeaks();
  | }
  | Reformatted changed files. Please review and stage the changes.
  | Files updated:
 

<br class="Apple-interchange-newline">

**Review by ericl — APPROVED** [review]
The solution LGTM. I wonder if it would be possible to remove the optimization entirely, but I imagine this could cause O(n^2) slowdowns in some cases, so maybe this extra logic is needed.

**Comment by stephanie-wang** [comment]
All failed tests are flaky.

**Pull request merged**
