### PR TITLE
Update wheel in autoscaler example.

### PR DESCRIPTION
**Pull request by robertnishihara**
Follow up to #1393.

cc @pschafhalter @ericl

### CODE REVIEW

**Comment by pcmoritz** [comment]
We should probably fix https://github.com/ray-project/ray/issues/1407 before creating the final wheel, what do you think? (Unless the fix just touches the yaml files)

**Comment by ericl** [comment]
Looks good -- I'm assuming this fixed the AZ error ?

**Review by ericl — APPROVED** [review]

**Comment by robertnishihara** [comment]
No this does not fix #1407. The autoscaler does not currently work with the default config.

**Comment by ericl** [comment]
Travis failures should have been fixed by the other pr

**Pull request merged**
