### PR TITLE
[ci] unmark documentation test as soft fail

### PR DESCRIPTION
**Pull request by matthewdeng**
## Why are these changes needed?

Reverts #36480 since this test is now passing.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by matthewdeng** [comment]
Documentation test in master is [passing](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4617#0188e669-84bc-469f-a934-18e84479e3a2) now.

Documentation test is [failing](https://buildkite.com/ray-project/oss-ci-build-pr/builds/26513#0188e673-4ae5-4806-8040-52734fad39b1) on the PR job, but this seems to be due to some caching behavior.

**Comment by aslonnie** [comment]
> this seems to be due to some caching behavior.

your pr does not include the final fix PR; it is 3 commits behind master:

https://github.com/matthewdeng/ray/compare/docs-softfail...ray-project:ray:master
image


you should merge master head and rerun the tests.

**Review by aslonnie — APPROVED** [review]
please merge master head and include the fix required.

**Comment by matthewdeng** [comment]
Lol woops.

**Pull request merged**
