### PR TITLE
[core] Don't preload jemalloc for worker.

### LINKED ISSUE #39306: Release test lightgbm_tune_4x16.aws failed
Release test **lightgbm_tune_4x16.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2129#018a69ca-04f5-4458-9859-12aa95fcfc53 for more details.

Managed by OSS Test Policy

### LINKED ISSUE #39307: Release test lightgbm_train_moderate.aws failed
Release test **lightgbm_train_moderate.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2129#018a69ca-23ef-4125-aef4-e35a5d02c96f for more details.

Managed by OSS Test Policy

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

Some library is not compatible with jemalloc. This PR disable jemalloc for python workers.
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
https://buildkite.com/ray-project/release-tests-pr/builds/52730#018a747a-c579-482c-8082-3c90eb54337a

passes, 

cc @krfricke @can-anyscale did it fail consistently in the release branch>? How many times should we run to verify it is fixed?

**Comment by GeneDer** [comment]
@rkooo567 Yes, both `lightgbm_train_moderate` and `lightgbm_tune_4x16` are failing consistently on the release branch
- https://buildkite.com/ray-project/release-tests-branch/builds/2135#018a714b-fca5-4be4-9c90-1adb46170acd
- https://buildkite.com/ray-project/release-tests-branch/builds/2135#018a7164-9de3-4747-bf76-e17696dfed11
- https://buildkite.com/ray-project/release-tests-branch/builds/2135#018a7196-b348-4915-a8bc-7992b60a2c21
- https://buildkite.com/ray-project/release-tests-branch/builds/2135#018a714b-fcb0-43d0-9e32-4568a6c5e5d1
- https://buildkite.com/ray-project/release-tests-branch/builds/2135#018a7164-a63d-4e6d-8ef2-a1a0118ad36e
- https://buildkite.com/ray-project/release-tests-branch/builds/2135#018a7196-bce9-43b7-8f96-d9d825c100a1

I think as long as we are able to see success runs each for both then it's good to go :)

**Comment by rkooo567** [comment]
Running lightgbm_tune_4x16 now https://buildkite.com/ray-project/release-tests-pr/builds/52784

**Comment by rkooo567** [comment]
test_advanced_4.py failure seems related

**Review by rkooo567 — APPROVED** [review]
@iycheng actually, I don't thnk I understand how this disables jemalloc only in workers. can you tell me some details?

**Comment by iycheng** [comment]
> @iycheng actually, I don't thnk I understand how this disables jemalloc only in workers. can you tell me some details?

Worker is started by raylet and raylet has LD_PRELOAD setup, so worker will have this too. Remove it will remove it from the  worker.

**Comment by Myasuka** [comment]
It seems I cannot enable Jemalloc on worker via setting the env `"RAY_LD_PRELOAD": "0"`, I wonder how can I preload Jemalloc for workers? @fishbone

**Pull request merged**
