### PR TITLE
Remove cloudpickle customization and just use plain cloudpickle.

### PR DESCRIPTION
**Pull request by robertnishihara**
I'm a little surprised that the cloudpickle modifications no longer seem to be necessary. I thought we needed those changes in order to pickle remote functions that invoked other remote functions.

@mehrdadn, do you remember any examples of functions that can't be pickled normally by cloudpickle but that could be pickled with the augmented version? I can't seem to recreate such an example at the moment.

The problem probably still exists, so if that's the case we should see if we can create a patch for cloudpickle.

### CODE REVIEW

**Comment by mehrdadn** [comment]
I have an example in my bug report [here](//github.com/cloudpipe/cloudpickle/issues/62#issue-165900306). It doesn't seem to have been marked as resolved, so I expect it to still be broken in the latest version of CloudPickle.

**Comment by robertnishihara** [comment]
Thanks. The reason we didn't submit your patch to cloudpickle was that it only works for CPython, is that right?

**Comment by mehrdadn** [comment]
Yup.

**Comment by wesm** [comment]
see also https://github.com/spartan-array/spartan/blob/master/spartan/cloudpickle.pyx, a cythonized version of cloudpickle

**Comment by robertnishihara** [comment]
Thanks for the link!

**Comment by pcmoritz** [comment]
@wesm Thanks for the link! Did you try it out by any chance and measure the speed vs. regular cloudpickle?

**Comment by robertnishihara** [comment]
The test failure here is #591.

**Comment by wesm** [comment]
I haven't tested it personally but it may be worth evaluating at some point

**Comment by pcmoritz** [comment]
mehrdad is fixing this whole class of problems upstream here: https://github.com/cloudpipe/cloudpickle/pull/89

**Pull request merged**
