### PR TITLE
[WIP] [Object Spilling] Initial efforts to deflake object spilling unit tests

### LINKED ISSUE #11096: [Object Spilling] Restart spilling workers when crasehd.
### Describe your feature request

If spawned spilling workers are killed or crashed, object spilling doesn't work as expected.

EX)
```python3
def test_spill_objects_manually(shutdown_only):
    # Limit our object store to 75 MiB of memory.
    ray.init(
        object_store_memory=75 * 1024 * 1024,
        _object_spilling_config={
            "type": "filesystem",
            "params": {
                "directory_path": "/tmp"
            }
        },
        _system_config={
            "object_store_full_max_retries": 0,
            "max_io_workers": 4,
        })
    arr = np.random.rand(1024 * 1024)  # 8 MB data
    replay_buffer = []
    pinned_objects = set()
    spilled_objects = set()
    import time

    # Create objects of more than 200 MiB.
    for _ in range(25):
        ref = None
        while ref is None:
            try:
                ref = ray.put(arr)
                replay_buffer.append(ref)
                pinned_objects.add(ref)
            except ray.exceptions.ObjectStoreFullError:
                ref_to_spill = pinned_objects.pop()
                ray.experimental.force_spill_objects([ref_to_spill])
                spilled_objects.add(ref_to_spill)
    time.sleep(30)
    # Kill spilling workers here.

    # Spill 2 more objects so we will always have enough space for
    # restoring objects back.
    refs_to_spill = (pinned_objects.pop(), pinned_objects.pop())
    ray.experimental.force_spill_objects(refs_to_spill)
    spilled_objects.update(refs_to_spill)

    # randomly sample objects
    for _ in range(100):
        ref = random.choice(replay_buffer)
        if ref in spilled_objects:
            ray.experimental.force_restore_spilled_objects([ref])
        sample = ray.get(ref)
        assert np.array_equal(sample, arr)
```

### PR DESCRIPTION
**Pull request by rkooo567**
## Related issue number

Will happen to fix https://github.com/ray-project/ray/issues/11096
https://github.com/ray-project/ray/issues/13597

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kfstorm** [comment]
@rkooo567 Are you still working on this? I've noticed the same issue internally. Unfortunately, we don't have the unlimited plasma feature yet, so when spill workers are killed by OS due to memory pressure, subsequent `ray.put` calls all fail with `ObjectStoreFullError`.

cc @Catch-Bull @MissiontoMars

**Comment by rkooo567** [comment]
Oh I don’t do this now. It’d be great if you guys can make a pr (should be pretty simple fix$

**Comment by kfstorm** [comment]
@rkooo567 I tried to write a UT to fix the issue that new IO workers are not started if previous ones are killed, but due to the unlimited plasma feature, there's no definite way to check if spilling is happening, right?

**Comment by kfstorm** [comment]
@rkooo567 BTW, is there any particular reason that you include IO workers in `GetRegisteredWorker`?

**Comment by rkooo567** [comment]
Hmm I am not sure if I am following it. Iirc, the root cause is we just don’t properly update states when io workers are killed? How is it related to unlimited plasma store feature?

**Comment by rkooo567** [comment]
Don’t remember 😂 haha…

**Comment by kfstorm** [comment]
> Hmm I am not sure if I am following it. Iirc, the root cause is we just don’t properly update states when io workers are killed? How is it related to unlimited plasma store feature?

I was testing like:

1. Putting objects larger than the object store size.
2. Kill spill workers.
3. Repeat step 1 and expect success.
4. Check that new spill workers are started.

But due to the unlimited plasma feature, step 3 succeeds even new spill workers are not started. And there's no way to turn the feature off now.

**Comment by rkooo567** [comment]
So you are saying it is hard to test?

**Comment by kfstorm** [comment]
@rkooo567 It's hard to check if a new spill worker is started by making ensure putting objects to the plasma store doesn't raise ObjectFullError, but we can leverage psutil to check if any process with the title "ray::SPILL_WORKER" exists. However, I've tried psutil and it only works on Linux, not macOS. 🤔

**Comment by kfstorm** [comment]
@rkooo567 BTW, we've fixed it internally. I can create a PR first.

**Comment by kfstorm** [comment]
@rkooo567 PR is out: https://github.com/ray-project/ray/pull/20752

**Comment by rkooo567** [comment]
Duplicated https://github.com/ray-project/ray/pull/20752#pullrequestreview-819790627

**Pull request closed without merging**
