### PR TITLE
unskip potentially flaky test on windows

### LINKED ISSUE #35553: [CI] [Windows] [Ray Client] Unskip `windows://python/ray/tests:test_multiprocessing_client_mode`
### What happened + What you expected to happen

This test became flaky on Windows (https://github.com/ray-project/ray/issues/35526) and was skipped in https://github.com/ray-project/ray/pull/35534.  We should unskip this test.

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Issue Severity

None

### PR DESCRIPTION
**Pull request by mattip**
## Why are these changes needed?
After PR #35526 the `test_multiprocessing_client_mode` test became flaky on windows. It was skipped in #35534. Let's see if it passes now

## Related issue number
Closes #35553

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by anyscalesam** [comment]
@can-anyscale can you share how one is able to manually kick off a CI test after we believe it's been unflaked? @mattip can help here else @architkulkarni can check tonight if the CI is passing now?

**Comment by can-anyscale** [comment]
Totally, @mattip is already doing the right thing here for window tests. Once we migrate windows over to civ2 the process can be more unified. Right now, enable/disable window test is case-by-case basis.

**Comment by can-anyscale** [comment]
The test itself looks good on CI https://buildkite.com/ray-project/oss-ci-build-pr/builds/41008#018baaa7-cc36-4c65-82f8-c44f7576bbfd/5266-7988

**Comment by can-anyscale** [comment]
I'll wait for @architkulkarni to take a look; otherwise I can stamp tomorrow

**Review by can-anyscale — APPROVED** [review]

**Comment by architkulkarni** [comment]
Premerge failed. Merging master

**Review by architkulkarni — APPROVED** [review]

**Pull request merged**
