### PR TITLE
[RLlib] Use observations (input_dict) for exploration

### PR DESCRIPTION
**Pull request by Stefan-1313**
@kouroshHakha

## Why are these changes needed?

Use observations (input_dict) for exploration.
For details, please see issue: #26437 .

## Related issue number

If this pull request is correct(ed), it closes enhancement issue #26437.

## Checks

- [ I did, some afterward, I don't know if this is how you want it... ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ I'm on Windows, does not work ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ I think this will be auto generated, I updated the doc string in the code for the developer API. ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ Yes, except for tests that already failed before my changes. Among them tests when using framework "tf", perhaps this is due to my environment, when using frameworks "torch" and "tf2" tests pass ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ X ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
   - [ X ] A test program I normally use, runs fine for both "torch" and "tf2" frameworks.

I did my best, this is my first Pull Request ever so please go easy on me :).
I'm not an very experienced Git user, so I had trouble fixing all the sign off stuff.

## EDIT:
I tried to fix the sign off issue with the instructions in the DCO check (`git rebase HEAD~7 --signoff` and `git push --force-with-lease origin master`), and now I have seen to signed off everyone's commit :O. That cannot be how it should be... But the DCO check is not complaining any more! :)

### CODE REVIEW

**Comment by Stefan-1313** [comment]
Commenting because of stale[bot].

This pull request is still usefull, and should still be able to merge without (much) problems.
Only a few files have changed and the sign off command I did somehow made it such that all commits that where done since I created my fork are seen as commits for this pull request.

Only look at the latest commits, only these are mine and are the relevant ones.

**Comment by xwjiang2010** [comment]
@Stefan-1313 
Thanks for the PR!
Could you clean up the commit history? With its current state, it is hard to get it reviewed and merged.

To fix it, i would just start a new brach, cherry-pick your PR onto that branch. Please also do git commit --amend --signoff to make sure that DCO check will pass. Then the same procedure with git push stuff (that will give you a new PR but I think it's ok in this case). 

@kouroshHakha assigning this to you as you have the most context about the problem the PR is addressing.

**Comment by Stefan-1313** [comment]
@xwjiang2010 I will try to clean up my commit history.
Currently I'm a bit low on time, but I will do it when I find some time.
Should I then create a new pull request? If yes, then I close this one after I created the new pull request.

**Comment by xwjiang2010** [comment]
Yes, that would work. Thank you!

**Comment by kouroshHakha** [comment]
@Stefan-1313 Please assign the clean PR to me. Thanks.

**Pull request closed without merging**
