### PR TITLE
[docs] add dask compatibility for 2.4.0

### PR DESCRIPTION
**Pull request by clarng**
## Why are these changes needed?

update dask compat for ray 2.4.0

dask ver same as 2.3.0 as there was no changes since last release

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by c21 — APPROVED** [review]

**Comment by rkooo567** [comment]
Hmm actually I am seeing the latest version is 2023.3.2 https://pypi.org/project/dask/#history.

Why not testing against the latest versions?

**Comment by clarng** [comment]
> Hmm actually I am seeing the latest version is 2023.3.2 https://pypi.org/project/dask/#history.
> 
> Why not testing against the latest versions?

Shouldn't it be based on this file instead?

https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/requirements/data_processing/requirements.txt

**Comment by rkooo567** [comment]
Hmm, what's the standard process here @c21 ? Not sure why we have this restriction now in versioning (also there are 2 dask[complete] version requirement with conflicting versions)

**Comment by c21** [comment]
> what's the standard process here

So the dependency update has two parts:
1. Update dependency in https://github.com/ray-project/ray/blob/master/python/requirements/data_processing/requirements.txt . A bot will submit a PR and oncall will review it. This is not bound with release.

2. Update compatibility version in documentation. This PR does it, and it bounds with release.

So I think we can look into update Dask version later in 2.5. This is not blocking release.


> Not sure why we have this restriction now in versioning (also there are 2 dask[complete] version requirement with conflicting versions)

Some of latest Dask versions does not support Python 3.8+, so we have the different version. This is latest PR to update Dask version - https://github.com/ray-project/ray/pull/28123 .

**Comment by clarng** [comment]
good to merge?

**Comment by c21** [comment]
cc @zhe-thoughts to approve before merging - this is doc change needed for 2.4 release.

**Comment by c21** [comment]
Sorry actually I remember now we already unfreeze master. I think it's good to merge.

**Comment by c21** [comment]
Merged to master. Thanks @clarng.

**Comment by zhe-thoughts** [comment]
OK to pick

**Pull request merged**
