### PR TITLE
Auto discover dashboard agent port

### LINKED ISSUE #17498: new dashboard agent port conflict issues
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 3.7

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

Users are getting a few different error messages, this is one that’s spamming me a lot:
```
(pid=4670) (raylet, ip=...) E0802 07:40:46.542383278   63998 server_chttp2.cc:49]        {"created":"@1627890046.542339446","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1627890046.542335288","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1627890046.542316804","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:59332"},{"created":"@1627890046.542334837","description":"Unable to configure socket","fd":19,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1627890046.542332583","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
(pid=4670) (raylet, ip=...) Traceback (most recent call last):
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 381, in <module>
(pid=4670) (raylet, ip=...)     raise e
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 366, in <module>
(pid=4670) (raylet, ip=...)     logging_params=logging_params)
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 94, in __init__
(pid=4670) (raylet, ip=...)     f"[::]:{self.dashboard_agent_port}")
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/aio/_server.py", line 84, in add_insecure_port
(pid=4670) (raylet, ip=...)     address, self._server.add_insecure_port(_common.encode(address)))
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
(pid=4670) (raylet, ip=...)     raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
```

Also, --include-dashboard=False does not flag this off.

cc @fyrestone @rkooo567

### LINKED ISSUE #18900: [dashboard][Bug] dashboard crash looping
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

seems our dashboard agent has been causing issues for product and customer. We should try to fix it.

```
2021-09-25 11:09:40,315 WARNING worker.py:1215 -- The agent on node worker-node-type-0-2486247baf464c8a8bd6614f3e5f4c62 failed with the following error:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 370, in <module>
    loop.run_until_complete(agent.run())
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 151, in run
    modules = self._load_modules()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 105, in _load_modules
    c = cls(self)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 153, in __init__
    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/metrics_agent.py", line 77, in __init__
    namespace="ray", port=metrics_export_port)))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py", line 334, in new_stats_exporter
    options=option, gatherer=option.registry, collector=collector)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py", line 266, in __init__
    self.serve_http()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py", line 321, in serve_http
    port=self.options.port, addr=str(self.options.address))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/prometheus_client/exposition.py", line 149, in start_wsgi_server
    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)
  File "/home/ray/anaconda3/lib/python3.7/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/home/ray/anaconda3/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/ray/anaconda3/lib/python3.7/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/home/ray/anaconda3/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/ray/anaconda3/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

The high level idea is to fallback gracefully for non critical component (like dashboard agent).
A few ideas:
check if the port is available before starting the agent, and fallback to run without agent if the port has already been in use.
exponential back off / limit the number of the retries

### Reproduction script

n/a this is easily reproducable

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by fyrestone**
- raylet updates the dashboard agent address to internal kv store.
- The metrics reporting logic auto find the latest dashboard agent address in GCS / raylet / core worker.
- Remove the metrics_agent_port argument from GCS / raylet / core worker.

## Related issue number
Closes #17498

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by fyrestone** [comment]
@simon-mo @rkooo567 I am not sure if the CI failure is related to this PR.

**Comment by fyrestone** [comment]
> @simon-mo @rkooo567 I am not sure if the CI failure is related to this PR.

@simon-mo @rkooo567 I ran the failed cases on a Windows PC many times, it passes the case. I believe this PR is ready to be merged.

**Comment by edoakes** [comment]
@fyrestone is this ready for review?

**Comment by edoakes** [comment]
I think we will also need logic to get the latest port in the Ray client server (it is used for setting up runtime_envs)

**Comment by fyrestone** [comment]
> I think we will also need logic to get the latest port in the Ray client server (it is used for setting up runtime_envs)

It's ready for review. BTW, the review is finished in this PR https://github.com/ray-project/ray/pull/17855. This PR added some commits to fix the CI.

After this PR is merged, I can add the `--dashboard-agent-port` param mentioned here: https://github.com/ray-project/ray/pull/17855#issuecomment-903403320, and I am glad to add some logic for the ray client to get the port.

**Comment by edoakes** [comment]
@fyrestone unless I'm missing something, I don't think we can merge this without the logic in the ray client server to get the latest port for the dashboard agent. Wouldn't that mean that if the dashboard agent crashes and comes up on a new port, the ray client server could no longer talk to it?

**Review by edoakes — APPROVED** [review]
Ah, I see now, this isn't actually changing how we set the port -- it's still static and passed to the ray client server.

**Pull request closed without merging**
