### PR TITLE
Added GLOBAL_GRPC_OPTIONS to Ray Client GRPC_OPTIONS

### LINKED ISSUE #37757: [Core] ray.init() ignores 'no_proxy' environment variable
### Problem
In my development environment both `https_proxy` and `no_proxy` environment variables are set. My ray cluster is deployed on a
Docker Swarm and the head node service is running with name `ray-head`. Adding this service to `no_proxy` environment variable does not prevent `https_proxy` environment variable from being used. The connection still tries to go through the proxy. If I unset the `https_proxy` environment variable the connection succeeds as expected and everything works.

### Expected Behavior
During the initialisation of the connection to the cluster, `no_proxy` environment variable must be checked. If the address is in the no proxy list, connection must not be established through the proxy.

### Logs
```text
INFO client_builder.py:237 -- Passing the following kwargs to ray.init() on the server: logging_level
DEBUG worker.py:378 -- client gRPC channel state change: ChannelConnectivity.IDLE
DEBUG worker.py:378 -- client gRPC channel state change: ChannelConnectivity.CONNECTING
DEBUG worker.py:378 -- client gRPC channel state change: ChannelConnectivity.READY
DEBUG worker.py:813 -- Pinging server.
197441 hpack_parser.cc:1218]                 Error parsing metadata: error=invalid value key=content-type value=text/html; charset=utf-8
DEBUG worker.py:230 -- Ray client server unavailable, retrying in 5s...
DEBUG worker.py:233 -- Received when checking init: Received http2 header with status: 404
DEBUG worker.py:237 -- Waiting for Ray to become ready on the server, retry in 5s...
DEBUG worker.py:813 -- Pinging server.
DEBUG worker.py:230 -- Ray client server unavailable, retrying in 10s...
DEBUG worker.py:233 -- Received when checking init: Received http2 header with status: 404
DEBUG worker.py:237 -- Waiting for Ray to become ready on the server, retry in 10s...
DEBUG worker.py:813 -- Pinging server.
DEBUG worker.py:230 -- Ray client server unavailable, retrying in 15s...
DEBUG worker.py:233 -- Received when checking init: Received http2 header with status: 404
DEBUG worker.py:237 -- Waiting for Ray to become ready on the server, retry in 15s...
/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/worker.py:253: UserWarning: Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine. See https://docs.ray.io/en/latest/cluster/ray-client.html#step-2-check-ports for more information.
  warnings.warn(
Traceback (most recent call last):
  File "/<workdir>/example.py", line 32, in <module>
    ray.init(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/_private/worker.py", line 1338, in init
    ctx = builder.connect()
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/client_builder.py", line 167, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client_connect.py", line 55, in connect
    conn = ray.connect(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/__init__.py", line 250, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/__init__.py", line 92, in connect
    self.client_worker = Worker(
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/worker.py", line 139, in __init__
    self._connect_channel()
  File "/<workdir>/.venv/lib64/python3.9/site-packages/ray/util/client/worker.py", line 260, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeout
```

### Versions / Dependencies

ray v2.6.0
Python 3.9.16
Rocky Linux v8.8

### Reproduction script

```python
import ray
import os
import time

# Set $https_proxy
os.environ['https_proxy'] = '<proxy-server>'  # e.g. 'http://proxy.company.com:1234'
# Add ray-head to $no_proxy
os.environ['no_proxy'] = f'{os.environ["no_proxy"]}, ray-head'

address = 'ray://ray-head:10001'
ray.init(address=address, logging_level='DEBUG')

# Simple example from https://docs.ray.io/en/latest/ray-core/examples/gentle_walkthrough.html
DATABASE = ["Learning", "Ray", "Flexible", "Distributed", "Python", "for", "Machine", "Learning"]


def retrieve(item):
    time.sleep(item / 10.0)
    return item, DATABASE[item]


@ray.remote
def retrieve_task(item):
    return retrieve(item)


object_references = [retrieve_task.remote(item) for item in range(8)]
data = ray.get(object_references)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

#### Workaround
```python
# Unset $https_proxy
os.environ['https_proxy'] = ''
address = 'ray://ray-head:10001'
ray.init(address=address, logging_level='DEBUG')
```

### PR DESCRIPTION
**Pull request by batuhanfaik**
## Why are these changes needed?

GRPC options of the client now extends the GLOBAL_GRPC_OPTIONS constant. Doing so allows the Ray client to obey the expected http/s proxy behaviour. Also gives the user to override this behaviour with the `RAY_grpc_enable_http_proxy` environment variable.

## Related issue number

Closes #37757

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
cc @ckw017 can you give a final go?

**Review by ckw017 — APPROVED** [review]
lgtm!

**Comment by rkooo567** [comment]
premerge failure. It seems unrelated, but I am rerunning it now

**Comment by rkooo567** [comment]
@batuhanfaik can you merge the latest master? Seems like premerge cannot pass for some reasons

**Comment by batuhanfaik** [comment]
done!

**Comment by batuhanfaik** [comment]
@rkooo567 premerge was successful

**Comment by rkooo567** [comment]
Thanks for the contribution @batuhanfaik !!

**Pull request merged**
