### PR TITLE
[nighly-test][test-placement-groups][rfc] call pg.ready() before using it

### LINKED ISSUE #18080: [nightly test] stress test placement group is timing out
[  Stress test placement group](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_XK8dGTQuc7i9va97p1u5YYGZ?command-history-section=command_history) has been timing out consistently. We should prioritize the fix of it.

### PR DESCRIPTION
**Pull request by scv119**
Reading the [doc](https://docs.ray.io/en/latest/placement-group.html) it suggests that we should always call pg.ready before using it.

> When using placement groups, users should ensure that their placement groups are ready (by calling ray.get(pg.ready())) and have the proper resources.

In our tests, however we use the pg before it's ready; this aligns which what I observed while debugging: some required pgs resources are not available when calling `ray status`.

**Follow up: should we warn user if a pg is used before ready is called?**

Test plan
-[x] verified release/stress_tests/workloads/test_placement_group.py no longer hangs.

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Comment by sasha-s** [comment]
> Follow up: should we warn user if a pg is used before ready is called?
Could we call pg.ready() automatically every time it is used (or on error) instead of warning the user?

**Comment by rkooo567** [comment]
This is because users can do “mistake” that they are creating pgs that exceed resources limit and schedule tasks (in that case it hangs). For this test, it is intentionally not used to test more drastic race condition since we know all of our pgs are scheduled within resources

**Comment by rkooo567** [comment]
So, I think this is what's happening; 

- There's a scheduling bug (race condition).
- It became worse recently for some reasons.
- And calling ready basically mask the race condition.

**Comment by scv119** [comment]
Discussed with @rkooo567 and @wuisawesome and the doc is a bit misleading, the pg should work without pg.read() being called. This is likely some scheduling bug and I'll dive deeper.

**Pull request closed without merging**
