### PR TITLE
[image] upgrade ray image base to ubuntu 22.04

### PR DESCRIPTION
**Pull request by aslonnie**
in ray release images only.

CI-use images are kept as 20.04 to be manylinux python wheel compatible.

### CODE REVIEW

**Review by jjyao — APPROVED** [review]
So the test coverage is release tests?

**Comment by aslonnie** [comment]
> So the test coverage is release tests?

yep.. pretty much it has always been like this for ray images..

**Comment by aslonnie** [comment]
> maybe collect the core perf metric for this PR

how to collect perf from PR?

**Comment by aslonnie** [comment]
> So the test coverage is release tests?

all nightly tests pass (except unstable ones)

**Comment by can-anyscale** [comment]
CC: @khluu  but i think this command should work for a PR branch as well

> bazel run devprod/rayrelease publish_perf_metrics -- --new_version=<X.Y.Z> --commit=<green_commit_sha> --branch=PR-branch

it's from this doc https://www.notion.so/anyscale-hq/Template-Weekly-release-e038c28b6edf436bbe7e99df1fe21e5d

i think many perf metrics are generated from the nightly-3x run

**Comment by aslonnie** [comment]
here is the perf metrics:

https://github.com/ray-project/ray/pull/46183

**Comment by aslonnie** [comment]
@jjyao in case you want to have another look.

**Comment by aslonnie** [comment]
also some 3x-nightly tests are failing (2 of the workspace template ones)

**Comment by can-anyscale** [comment]
i think there is an existing perf regression in the master branch now @jjyao  is investigating

**Comment by aslonnie** [comment]
> also some 3x-nightly tests are failing (2 of the workspace template ones)

those are failing due to insufficient gpu instances.

**Comment by aslonnie** [comment]
@can-anyscale let me know when I can or should merge this PR. this PR also requires your approval.

**Comment by can-anyscale** [comment]
@aslonnie do you want to sync with @jjyao, there are existing perf regressions so i'll leave it to your judgment

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
@jjyao says I can merge.

**Pull request merged**
