### PR TITLE
[release] Add utility script to fetch release logs

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

This PR adds a utility script to automatically fetch release test results from the Buildkite pipeline for a release branch. This was previously a manual process.

## Related issue number

See e.g. https://github.com/ray-project/ray/pull/24509

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Also tagging @amogkam and @architkulkarni for the 1.11.1/1.12.1 patch releases

**Review by simon-mo — APPROVED** [review]
Great addition

**Review by architkulkarni — COMMENTED** [review]
Looks good, thanks for doing this!  Just one potential concern, there are some release tests that run multiple times with the same name in different suites, but with different settings of `smoke_test`, and it led to some release delays in the past due to the smoke test being manually copied instead of the full test.  Happy to provide more details about this, I think it was during 1.10.  Does this PR handle this?

**Comment by architkulkarni** [comment]
^ That was the reason for this weird priority order in the release instructions:


> 1. Collect test outputs and create a **P0 release-blocker** [[PR](https://github.com/ray-project/ray/pull/18931)](https://github.com/ray-project/ray/pull/18931) (this is merged to master directly): You find those tests from:
>     1. **weekly** release suite first 
>     2. if not there, find them in **nightly** release
>     3. if not there, find them in **Core Daily**
>     4. if not there, find them in **Core Nightly**
>     5. if not there, find them in **Core Scalability**
>     
>     Some tests may appear in multiple suites but you should get result from the first suite you find it). All tests (and their suites) can be found in [[build_pipeline.py](https://github.com/ray-project/ray/blob/master/release/.buildkite/build_pipeline.py)](https://github.com/ray-project/ray/blob/master/release/.buildkite/build_pipeline.py).

**Comment by krfricke** [comment]
Smoke tests include "[smoke test]" in their job names and thus shouldn't match the regex. The builds are ordered by build number, so the latest results come first. I think this should handle these cases sufficiently, but let me know if you have any concerns!

**Comment by architkulkarni** [comment]
> Smoke tests include "[smoke test]" in their job names and thus shouldn't match the regex. The builds are ordered by build number, so the latest results come first. I think this should handle these cases sufficiently, but let me know if you have any concerns!

Awesome, sounds like a new addition since the time I was dealing with it.  Sounds good!

**Pull request merged**
