### PR TITLE
[dashboard] revert back to pushd and popd for win build

### PR DESCRIPTION
**Pull request by aslonnie**
so that the effect of `refreshenv` is preserved

### CODE REVIEW

**Comment by aslonnie** [comment]
trying to build the wheels here:
https://buildkite.com/ray-project/postmerge/builds/5353

**Review by can-anyscale — APPROVED** [review]
if tests pass

**Comment by aslonnie** [comment]
> if tests pass

I am also running windows tests on premerge.

**Comment by aslonnie** [comment]
wheels are building again:
https://buildkite.com/ray-project/postmerge/builds/5353#01909b15-f93b-40db-91c6-6b185fffc65a

**Comment by aslonnie** [comment]
also on premerge: https://buildkite.com/ray-project/premerge/builds/27706#01909b15-752d-4f29-aedc-2691f06d32d8

**Comment by aslonnie** [comment]
there is still one test that is failing on windows. I am merging to at least get wheels building.

**Pull request merged**
