### PR TITLE
Short alloc

### PR DESCRIPTION
**Pull request by qicosmos**
## Why are these changes needed?

We need such short_alloc to do small string optimization(SSO) to optimize performance.
I will use it for msgpack or protobuf serialization performance optimization later.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests

### CODE REVIEW

**Comment by scv119** [comment]
Thanks for pushing on this. Is there any reason we can't leverage libc++'s SSO instead? https://joellaity.com/2020/01/31/string.html

**Comment by iycheng** [comment]
I agreed with @jjyao. As you mentioned you'd like to support SSO for strings 25-500 bytes. Do you know the improvement of doing this? For example, the system is more stable or some important workload is more efficient.

- https://www.boost.org/doc/libs/1_60_0/doc/html/boost/container/small_vector.html

**Comment by qicosmos** [comment]
> @qicosmos I may miss some context here, but in the description could you describe what's the performance issue you are trying to fix and what's the performance improvement because of this PR? Thanks!

We can use short_alloc to do many improvements: such as msgpack pack/unpack, proto buffer serilization, ray log stringstream, and some other places can be did SSO. It's a basic util.

Actually if we also can use std::pmr to replace short_alloc, but the current ci not support it completely now, the short_alloc can support lower version compilers.

**Comment by qicosmos** [comment]
> I agreed with @jjyao. As you mentioned you'd like to support SSO for strings 25-500 bytes. Do you know the improvement of doing this? For example, the system is more stable or some important workload is more efficient.
> 
> Besides, let's put these vendered files into a separate dir to mange them (ray/src/thirdparty/)
> 
> The last thing is that, can we use small_vector for this?
> 
> * https://www.boost.org/doc/libs/1_60_0/doc/html/boost/container/small_vector.html

We need short-string not only small-vector.

I know boost has similar library, such as boost::contianer::pmr, but the implementation is not efficient, short_alloc is faster than boost.pmr.

**Comment by qicosmos** [comment]
“Besides, let's put these vendered files into a separate dir to mange them (ray/src/thirdparty/)”

No problem, maybe we will import more thirdparty short util files.

**Comment by jjyao** [comment]
> > @qicosmos I may miss some context here, but in the description could you describe what's the performance issue you are trying to fix and what's the performance improvement because of this PR? Thanks!
> 
> We can use short_alloc to do many improvements: such as msgpack pack/unpack, proto buffer serilization, ray log stringstream, and some other places can be did SSO. It's an important basic util.

Do we have quantified performance number of how much time is spent on those and how much SSO can help here? My worry is http://wiki.c2.com/?PrematureOptimization and https://en.wikipedia.org/wiki/Amdahl%27s_law (The performance improvement to be gained by making some part of the execution faster is limited by the fraction of the time that part uses.).

> 
> Actually if we also can use std::pmr to replace short_alloc, but the current ci not support it completely now, the short_alloc can support lower version compilers.

Do we know how much effort is needed to upgrade the compiler to support std::pmr? Seems it's better to use a standard library than a third party one.

> 
> I will use it for msgpack or protobuf serialization performance optimization later.

**Comment by qicosmos** [comment]
> > > @qicosmos I may miss some context here, but in the description could you describe what's the performance issue you are trying to fix and what's the performance improvement because of this PR? Thanks!
> > 
> > 
> > We can use short_alloc to do many improvements: such as msgpack pack/unpack, proto buffer serilization, ray log stringstream, and some other places can be did SSO. It's an important basic util.
> 
> Do we have quantified performance number of how much time is spent on those and how much SSO can help here? My worry is http://wiki.c2.com/?PrematureOptimization and https://en.wikipedia.org/wiki/Amdahl%27s_law (The performance improvement to be gained by making some part of the execution faster is limited by the fraction of the time that part uses.).
> 
> > Actually if we also can use std::pmr to replace short_alloc, but the current ci not support it completely now, the short_alloc can support lower version compilers.
> 
> Do we know how much effort is needed to upgrade the compiler to support std::pmr? Seems it's better to use a standard library than a third party one.
> 
> > I will use it for msgpack or protobuf serialization performance optimization later.

I will make a benchmark test, the test result will tell us the value of SSO.

I tested std::pmr::string on mac, but failed compile, gcc 8 don't support std::pmr, gcc9.1 begin to support std::pmr, some ci are based on gcc8.

**Comment by qicosmos** [comment]
> Hmm I don't think anyone here is opposed to performance optimizations, the only question is the actual performance impact. This is important for two reasons, (1) to validate the improvement is worth the maintenance cost, and (2) ensure any improvements don't regress (that they're covered by some benchmark we run regularly).
> 
> Why not test the performance delta using 'ray microbenchmark'? I don't think anyone can make any confident statements about roi without this data. E.g., if it improves performance by 20% in some important case then it might be worth it.

Good, i will do some benchmarks  to see the effect of such SSO.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Pull request closed without merging**
