### PR TITLE
[Serve] Run health check in separate thread (#24560)

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?

Cherry pick #24560 into release branch. 
I have also ran the nightly release test on the PR and they all passed. https://buildkite.com/ray-project/release-tests-pr/builds/2492 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by simon-mo** [comment]
@zhe-thoughts this is the cherry pick PR targeting release branch.

**Review by zhe-thoughts — APPROVED** [review]
There's some risk but since it'a blocker let's cherry pick it. But we need to run a full round of release tests

**Comment by simon-mo** [comment]
@avnishn should I merge here? Please let me know!

**Comment by avnishn** [comment]
Sounds good. I'll kick off a full round of release tests.

**Comment by avnishn** [comment]
Tests running here:
https://buildkite.com/ray-project/release-tests-branch/builds/507

**Pull request merged**
