### PR TITLE
[PlacementGroup]Add node manager test

### PR DESCRIPTION
**Pull request by ffbin**
## Why are these changes needed?
Add node manager test.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ffbin** [comment]
@rkooo567 Can you help to see if the windows failure is related to the cause of this PR? I didn't find the corresponding error message, thanks.

**Comment by ffbin** [comment]
Hi @rkooo567 , do we still need this PR?

**Comment by rkooo567** [comment]
@ffbin I think so? I still prefer to test the idempotency of placement group resource creation. But it still fails the Windows build.

**Comment by ffbin** [comment]
> @ffbin I think so? I still prefer to test the idempotency of placement group resource creation. But it still fails the Windows build.

Ok, i will try to fix it, thanks.

**Comment by rkooo567** [comment]
Stale.

**Pull request closed without merging**
