### PR TITLE
[CI] Bump Bazel version to 4.2.2

### LINKED ISSUE #24241: [CI] Use Bazel version 4.2.2 instead of 4.2.1 for MacOS Monterey
### What happened + What you expected to happen

When compiling Ray from source, [Mac users first install Bazel 4.2.1](https://docs.google.com/document/d/1XgpuUX0vtk82NIVQyEk8d3tnbpSFHO8ZGmF-i2J8_9A/edit#heading=h.qqaa63bz6477). However, [MacOS Monterey has an issue with protoc](https://github.com/protocolbuffers/protobuf/issues/9172) that is resolved only in Bazel 4.2.2. [/ci/env/install-bazel.sh](https://github.com/ray-project/ray/blob/65d9a410f7c7697372270ea2ac93d8121f69f53c/ci/env/install-bazel.sh#L49) should be updated to install Bazel 4.2.2 if the user is running MacOS Monterey.

[Example build error log on MacOS Monetery](https://docs.google.com/document/d/1vaytxdQqhhUCE4M0qZoqszxS9ZMz-PKrFNFHzQVp8hg/edit)

### Versions / Dependencies

Latest Ray on the Master branch. Python 3.8. MacOS Monterey.

### Reproduction script

Follow instructions from [this build runbook](https://docs.google.com/document/d/1XgpuUX0vtk82NIVQyEk8d3tnbpSFHO8ZGmF-i2J8_9A/edit#heading=h.xmeeytf4d7fv).

[Example build error log on MacOS Monetery](https://docs.google.com/document/d/1vaytxdQqhhUCE4M0qZoqszxS9ZMz-PKrFNFHzQVp8hg/edit)

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

[A compatibility issue between Bazel, Protoc, and MacOS Monterey](https://github.com/protocolbuffers/protobuf/issues/9172) is solved starting in Bazel 4.2.2. This change upgrades the Bazel version from 4.2.1 to 4.2.2.

## Related issue number

Closes #24241.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Review by jjyao — APPROVED** [review]
Could you also double check if there is any public doc that references 4.2.1?

**Review by edoakes — APPROVED** [review]

**Comment by shrekris-anyscale** [comment]
It looks like the Windows tests are failing. I'll investigate further, but there's a chance that Windows should continue using Bazel 4.2.1.

Depending on that, we may/may not want to change [this line](https://github.com/ray-project/ray/blame/65d9a410f7c7697372270ea2ac93d8121f69f53c/doc/source/ray-contribute/development.rst#L132) in the docs.

**Comment by shrekris-anyscale** [comment]
> Could you also double check if there is any public doc that references 4.2.1?

@jjyao Good idea! I didn't notice any public doc that references 4.2.1 other than the lines about Windows I mentioned [here](https://github.com/ray-project/ray/pull/24242#issuecomment-1111307566).

**Comment by shrekris-anyscale** [comment]
I made [a PR in the buildkite-ci-stack repo](https://github.com/ray-project/buildkite-ci-stack/pull/31) to upgrade the Windows' CI Bazel version to 4.2.2. I also updated the references in the Windows docs to refer to Bazel 4.2.2 instead of 4.2.1.

Once the buildkite-ci-stack PR is merged, the Windows tests on this PR should pass.

**Comment by shrekris-anyscale** [comment]
As a status update– we ran the `packer` command to update [Bazel for Windows](https://github.com/ray-project/buildkite-ci-stack/pull/31). However, the `packer` script ran into some issues:

```powershell
==> amazon-ebs.ci-windows: The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; ./main.ps1' returned a non-zero code: 1
```

See [here](https://docs.google.com/document/d/1c-IuHKDky20w9Xqo6qS0_4AUIrYoHaZU7TaCCwg-6E0/edit?usp=sharing) for full command output.

Once this issue is resolved, we can finish the Windows Bazel update and then merge in this change.

**Comment by pdames** [comment]
+1 to getting this PR finalized and merged ASAP. I just went through the same discovery and troubleshooting process on MacOS Monterey and was about to submit the same PR before finding this one.

**Pull request merged**
