### PR TITLE
[autoscaler] Add sync command

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
Refactors file syncing so that commands can call this segment of code independently.

This triggers the autoscaler to rerun worker setup, but not head setup. Not clear if this is desired behavior.

### TODOS:
- [ ] Add tests

### CODE REVIEW

**Comment by ericl** [comment]
What is the use of this command (why not just run create_or_update --no-restart)?

**Comment by robertnishihara** [comment]
Is this still in progress or should it be closed?

**Comment by richardliaw** [comment]
In progress; will work on this this week

**Comment by ericl** [comment]
I still don't get how this is different from create or update. Should we clarify that command or enhance it instead of adding another one?

**Comment by richardliaw** [comment]
Yeah the plan is to add a `--files-only` to create_or_update

**Comment by ericl** [comment]
I see, but in which scenario is syncing only files useful? You'd still want to rerun the setup commands right, or else the Ray cluster would still be using the old files.

**Comment by richardliaw** [comment]
No, I dont want to rerun setup commands, which often include installation
checks and file moving (which needs to happen after other setup commands).
I’ll only perhaps run an experiment script, but i’d be ok doing that by
hand, and I’ll want only to sync my files before running the script.

**Comment by ericl** [comment]
Note that setup commands should in general run very fast after the first time, if your setup is slow, you can rewrite the commands to be fast on re-execution (e.g., check if file exists before downloading), or snapshot an AMI. If the commands are slow b/c of the large number of them, we could also fuse them into one SSH call.

Also if you're syncing a git repo, you kind of need the setup commands block anyways to do the git pull.

**Comment by richardliaw** [comment]
The large number of calls is usually the problem - are you proposing to fusing them into one SSH call in general?

**Comment by richardliaw** [comment]
Closing due to #2678

**Pull request closed without merging**
