### PR TITLE
[ray_client]: Client PlacementGroup hooks

### LINKED ISSUE #13147: Support placement groups in Ray client

### PR DESCRIPTION
**Pull request by barakmich**
Way better than #13310 -- no extra client-classes, simply control placement groups by sending the commands as tasks

## Related issue number

Closes #13147 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
LGTM.

**Comment by rkooo567** [comment]
Btw, are we testing this somewhere?

**Comment by ericl** [comment]
Seems to be breaking placement group tests.

**Comment by ericl** [comment]
Closing for now

**Pull request closed without merging**
