### PR TITLE
Change fork to thread

### PR DESCRIPTION
**Pull request by Queimo**
I use the latest version of wandb 0.12.7 and "fork" does not exist, only "thread" and "spawn", so I think "thread" is the right choice, worked for me, at least.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
@krfricke can you take a look at this?

**Comment by krfricke** [comment]
Hi @Queimo, thanks for your patch.

Are you using Windows by any chance? It seems like `fork` only does not exist in Windows.

Can you update your PR to only conditionally use `thread` on windows?

**Comment by Queimo** [comment]
@krfricke Ah, yes that's correct! I just changed it. Is that fine?

**Comment by krfricke** [comment]
Generally yes, but the linter did not pass (you'd have to run `./scripts/format.sh`).

I had to make some changes to wandb today and incorporated your changes in the PR at #21892 - I'll add you as an coauthor to the commit and will close this once #21892 is merged, ok? No further action required on your part :-)
Thanks for contributing!

**Comment by Queimo** [comment]
Ah I see, yes that's great! Sorry for the extra work, this was actually my first PR.

**Comment by krfricke** [comment]
I've also messed up the git merge here just now, so let's use #21892 :-)

**Pull request closed without merging**
