### PR TITLE
[docs/kuberay] update docs with book text

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

Added text for KubeRay.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
Thanks, Richard! I'll now take over on this PR.

**Comment by richardliaw** [comment]
Some things to note:

1. You'll want to move the code snippets into a separate file and run that
in CI
2. You may want to consider breaking this up into multiple files

**Comment by DmitriGekhtman** [comment]
unstale, I'm using this as a reference for current doc writing, finding convenient to keep it in the open PRs list...

**Comment by DmitriGekhtman** [comment]
Thanks @richardliaw! This was extremely helpful.

Closing, as this material has been incorporated into the docs.

**Pull request closed without merging**
