### PR TITLE
[autoscaler v2] add unit tests for NodeProviderConfig

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

add tests and fix bugs for NodeProviderConfig

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rickyyx — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/gifs/test-gw3IWyGkC0rsazTi">GIPHY</a></div>

**Review by rkooo567 — APPROVED** [review]
LGTM... Feel like in the medium term, we need a schema to enforce the types for the yaml files. It is pretty complicated..

**Comment by DmitriGekhtman** [comment]
> LGTM... Feel like in the medium term, we need a schema to enforce the types for the yaml files. It is pretty complicated..

wooooo Dict[str, Any]

**Comment by edoakes** [comment]
> LGTM... Feel like in the medium term, we need a schema to enforce the types for the yaml files. It is pretty complicated..

Pydantic pls

**Pull request merged**
