### PR TITLE
[Java] Fix the issue that the cached value in `RayObject` is serialized

### PR DESCRIPTION
**Pull request by raulchen**
## Why are these changes needed?

No need to serialize the cached value, just serialize the id. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by kfstorm — APPROVED** [review]

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Does it make sense to add a test for serialization?

**Comment by raulchen** [comment]
@ericl I thought about adding a test. But this PR is more like a performance improvement, rather than a bug fix. If we want to add a test, I can only assert the size of the serialized object is small. But this seems weird. So I didn't do that.

**Comment by ericl** [comment]
Fair enough, I guess you can always assume T is serializable as well.

**Review by zhijunfu — APPROVED** [review]
LGTM

**Pull request merged**
