### PR TITLE
[Core]make thread of client manager in gcs server configurable

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
@iycheng and me tested scaling recently and found `gcs_server_rpc_server_thread_num` is a useful parameter with too much server call received. Thinking about client call sent by gcs server to raylet clients and core workers, we need to expose the thread number of client call manager.
This patch also changes the default value of thread number from 1 to 4.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kfstorm** [comment]
This PR looks great overall. But we'd better run some stress tests to see if regressions are found. @iycheng Could you or someone from Anyscale help to run some tests?

**Comment by WangTaoTheTonic** [comment]
@kfstorm The default number of threads is hart to decide and mostly it depends on knowledge. If you worried about the regression I can just add config item with no default value change.

**Comment by kfstorm** [comment]
@WangTaoTheTonic A'h

**Comment by kfstorm** [comment]
@WangTaoTheTonic Ah, I see. Making the number of threads from 1 to 4 will most likely improve multi-core usage rate and less likely to have performance regression.

**Review by kfstorm — APPROVED** [review]

**Comment by kfstorm** [comment]
The mac test failure should be unrelated.

**Pull request merged**
