### PR TITLE
add some modules of C++ worker cluster mode

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
We already have local mode in C++ worker now.  But local mode run all task in one single process, and we need cluster mode to achieve authentic distributed tasks. The PR is the beginning of C++ worker cluster mode developing.

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by SongGuyang** [comment]
@ericl This PR only is a code structure and interface, and test case can not run successfully. Maybe I can add test case after the cluster mode works? @AmeerHajAli and I will submit more PRs to implement this interfaces later.

**Comment by ericl** [comment]
Ok

**Comment by AmeerHajAli** [comment]
> It looks good, but do we need a test for this?

@ericl , this is the interface of the code that will interact with the core worker. It is important to make sure that it looks good to go from here.

**Comment by ericl** [comment]
@SongGuyang can you fix the lint errors?

**Comment by SongGuyang** [comment]
> @SongGuyang can you fix the lint errors?

I have fix the lint.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Thanks!

**Pull request merged**
