### PR TITLE
[minor] Remove get_global_worker(), RuntimeContext

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

We currently have three ways of getting the `global_worker` in python - accessing it directly from `ray.worker.global_worker`, calling `ray.worker.get_global_worker`, and calling `ray.runtime_context._get_runtime_context()`.

This PR changes it so that we only access the `global_worker` directly. I'm not very opinionated on this being the "right" way to do it, just want to unify all of the code. If anyone would prefer calling a function, I'm happy to change it.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by robertnishihara** [comment]
@edoakes some test failure

```
Traceback (most recent call last):
  File "/home/travis/.cache/bazel/_bazel_travis/b88c129a127452fc94033a29d9f90e20/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/python/ray/serve/echo_full.runfiles/com_github_ray_project_ray/python/ray/serve/examples/echo_full.py", line 15, in <module>
    serve.init(blocking=True)
  File "/home/travis/build/ray-project/ray/python/ray/serve/api.py", line 116, in init
    ray.util.get_actor(SERVE_NURSERY_NAME)
  File "/home/travis/build/ray-project/ray/python/ray/util/named_actors.py", line 30, in get_actor
    pickled_state = _internal_kv_get(actor_name)
  File "/home/travis/build/ray-project/ray/python/ray/experimental/internal_kv.py", line 14, in _internal_kv_get
    worker = ray.worker.get_global_worker()
AttributeError: module 'ray.worker' has no attribute 'get_global_worker'
```

**Review by robertnishihara — APPROVED** [review]
LGTM except that it's failing Travis.

**Comment by jovany-wang** [comment]
global_worker exposes too many fields. `runtime_context` is the public way that we expose fields to users.

Also this is aligned with Java part.

Fairly, I don't think it's a good idea that we allow users to access global_worker directly.

**Comment by edoakes** [comment]
@jovany-wang we don't expose this to users - it's not documented and in the internal namespace (prefixed by `_`)

**Pull request merged**
