### PR TITLE
fixed typo in kuber yaml

### PR DESCRIPTION
**Pull request by DuaneNielsen**
## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by DuaneNielsen** [comment]
Okies, here tis

**Comment by robertnishihara** [comment]
@virtualluke Does this look right to you?

**Comment by DuaneNielsen** [comment]
Lol, dunno how that change can cause a test to fail :)

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
Thanks @DuaneNielsen! Some of our tests are flaky unfortunately.

What command did you use to validate the config file? Maybe we should run that in our CI.

**Comment by virtualluke** [comment]
Sorry for the typo, to put a test I guess we could add a minikube run with the files (adds a lot of complexity I guess with k8s versions/platform), guessing other people have done that for testing and if you think it worthwhile I can explore.  Anyone else done this that is reading this?

**Comment by DuaneNielsen** [comment]
Well, I just ran 

```
kubectl create -f ray/kubernetes/head.yaml
```

I only got a warning though...  so dunno if that would even cause a failed build.

But a quick google reveals we are not the first to run into this challenge.  So through the wonders of open source...

https://github.com/garethr/kubeval

**Comment by robertnishihara** [comment]
I also ran the PR that introduced the typo in minikube before merging it and it still succeeded.

**Pull request merged**
