### PR TITLE
Revert pull retry

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

It looks like after these PRs are merged, the dask on ray test starts timeout (this test never times out for last 1 month).

## Related issue number
#19042

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by mwtian — APPROVED** [review]
Investigating in #19042

**Comment by rkooo567** [comment]
Btw I am not 100% sure yet if this is the root cause, so let’s merge it and see for a couple days. If you can repro it somehow that’d be great too

**Comment by mwtian** [comment]
Sounds good, let's see if time out will happen again. Currently it is a bit strange that no timeout happens for very similar tests.

**Comment by rkooo567** [comment]
Btw there was a lint failure https://buildkite.com/ray-project/ray-builders-pr/builds/15147#97e71d2b-9614-4830-8ff6-1e7b0ed87192, that I couldn't reproduce in my local env. Do you know why this happens? I've seen this a lot recently.

**Comment by rkooo567** [comment]
@scv119 can you merge the PR after tests are done?

**Comment by mwtian** [comment]
> Btw there was a lint failure https://buildkite.com/ray-project/ray-builders-pr/builds/15147#97e71d2b-9614-4830-8ff6-1e7b0ed87192, that I couldn't reproduce in my local env. Do you know why this happens? I've seen this a lot recently.

This is from `clang-tidy`. #19055 should run `clang-tidy` locally and give better messages.

**Comment by scv119** [comment]
//python/ray/tests:test_client_reconnect is failing on windows, shouldn't be related.

**Pull request merged**
