### PR TITLE
[CI] Print out the mismatched commit in ci

### PR DESCRIPTION
**Pull request by jjyao**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Before merging this, can you run some tests locally with this PR? Maybe try cherry-picking it with 1.7 and test it?

**Review by krfricke — APPROVED** [review]

**Comment by krfricke** [comment]
I merged this since it only adds a print to the assertion, i.e. behavior is basically the same as before

**Comment by jjyao** [comment]
Yea, I tested it locally and the `cmd` it builds works correctly.

**Comment by rkooo567** [comment]
Makes sense!

**Pull request merged**
