### PR TITLE
[Nightly test] disable oom killer for chaos-dask-on-ray

### LINKED ISSUE #29100: [release][CI] chaos_dask_on_ray_large_scale_test_no_spilling failed
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1092#0183a524-1ec3-49c8-8eea-a477b73da424)
[Cluster ](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_paXtVfrbrefk5QDGNRFmUTyb?command-history-section=command_history)

Seems OOM related. 

### Versions / Dependencies

NA

### Reproduction script

NA

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

It caused regression, and dask is not the first tier use cases for OOM killer. 
Failure case:
https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_paXtVfrbrefk5QDGNRFmUTyb?command-history-section=command_history

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rickyyx — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/funkofficial/">funk</a> on <a href="https://giphy.com/gifs/TrustoryDE-alcohol-funk-13xEKxMqnclCE0">GIPHY</a></div>

**Comment by scv119** [comment]
kicking off test here: https://buildkite.com/ray-project/release-tests-pr/builds/17364

**Comment by rkooo567** [comment]
Just ooc, 

> It caused regression, and dask is not the first tier use cases for OOM killer.

theoretically there's no reason this won't work well right? I think Dask has a pretty typical pattern (driver owning all tasks)

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
yeah, the devil is in the details.

**Pull request merged**
