### PR TITLE
Revert "[Core] revert: revert Unified worker starter (#18008)"

### LINKED ISSUE #18168: [Core] actor call microbenchmark perf regression
We've noticed there is a [40% regression](https://a5472365.us1a.app.preset.io/superset/dashboard/17/?preselect_filters=%7B%7D#CHART-Eiv4W7QpvZ) in n_n_(async)_actor_calls_async microbenchmark since Aug 27th. We should investigating if the trends continues.

### PR DESCRIPTION
**Pull request by stephanie-wang**
This reverts commit b9978dd02b307bf95081b422e5427a13327c197a.

## Why are these changes needed?

This PR is slowing down worker startup by about 2x, which causes the nightly test `many_tasks` to fail.

Closes https://github.com/ray-project/ray/issues/18168

cc @chenk008.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
test_failure_4 seems unrelated after retry; windows I believe is from master

**Comment by jovany-wang** [comment]
@stephanie-wang Can you tell us where the `many_tasks` test is?

Is this PR the root cause? or it's due to the conflict between this PR and async_pop?

**Comment by ericl** [comment]
@jovany-wang the most immediate manifestation of the performance regression is this microbenchmark issue, which I also tracked down to the same PR: https://github.com/ray-project/ray/issues/18168

I'm guessing the root cause is the same.

**Comment by stephanie-wang** [comment]
> @stephanie-wang Can you tell us where the `many_tasks` test is?
[Here](https://github.com/ray-project/ray/blob/master/benchmarks/benchmark_tests.yaml#L57) is the test, but it's a bit of a pain to set up because it requires a distributed cluster. The issue can easily be reproduced on a single node, though, by submitting lots of tasks that require less than 1 CPU each. I have a PR open [here](https://github.com/ray-project/ray/pull/18222) to simplify the test and allow you to run locally with the `--local` flag.

> 
> Is this PR the root cause? or it's due to the conflict between this PR and async_pop?

Yeah, I think the two PRs were both breaking the test, but it was hard to tell because the async pop PR was merged first. In both cases, the root cause is worker startup time. I believe if you run the test that I mentioned above with and without this revert, you should see about a 2x difference.

**Comment by jovany-wang** [comment]
> > @stephanie-wang Can you tell us where the `many_tasks` test is?
> 
> [Here](https://github.com/ray-project/ray/blob/master/benchmarks/benchmark_tests.yaml#L57) is the test, but it's a bit of a pain to set up because it requires a distributed cluster. The issue can easily be reproduced on a single node, though, by submitting lots of tasks that require less than 1 CPU each. I have a PR open [here](https://github.com/ray-project/ray/pull/18222) to simplify the test and allow you to run locally with the `--local` flag.
> 
> > Is this PR the root cause? or it's due to the conflict between this PR and async_pop?
> 
> Yeah, I think the two PRs were both breaking the test, but it was hard to tell because the async pop PR was merged first. In both cases, the root cause is worker startup time. I believe if you run the test that I mentioned above with and without this revert, you should see about a 2x difference.

Thanks. We'll investigate this PR.

**Pull request merged**
