### PR TITLE
Windows cleanup

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Cleans up a lot of Windows compatibility changes.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
Nice, LGTM! @suquark can you check the plasma includes a bit as well?

**Comment by suquark** [comment]
@mehrdadn Could we wait until merging this PR (https://github.com/ray-project/ray/pull/9431)? Because almost all unix/windows headers are dropped there.

**Comment by mehrdadn** [comment]
@suquark It seems it's a big PR that's been open to a few days... when do you plan to merge it?

**Comment by suquark** [comment]
Also I will drop the ae/ files entirely

**Comment by suquark** [comment]
I will merge it once I fix the windows compilation errors. All other tests have passed.

**Comment by mehrdadn** [comment]
@suquark Do you know when (approximately) that might happen? How much work is involved?

**Comment by suquark** [comment]
Could happen today if the CI passes. I have trial and error for days, so it is likely for me to find the tricks to pass windows compilation soon.

**Comment by mehrdadn** [comment]
Okay that should work. Ping me offline if you're still struggling with it tomorrow so I can see if I can take a look.

**Comment by suquark** [comment]
Thanks! I think we could cleanup even more after the plasma store refactoring. I have centralized remaining windows headers in only 2-3 few source files.

**Comment by mehrdadn** [comment]
Yeah I noticed that too, getting rid of `ae` is especially helpful.

**Comment by suquark** [comment]
@mehrdadn I think I still cannot fully fix the windows compilation errors here: https://github.com/ray-project/ray/pull/9431/checks?check_run_id=876436837

Internal boost::asio function names like `listen`, `accept` are replaced by `fh_listen`, `fd_accpet`, causing linking errors. It could be done by some windows shims, but I do not fully understand where they comes from.

**Comment by mehrdadn** [comment]
@suquark Those are from my `win32fd.h` layer. You don't necessarily need that header if you handle things in a cross-platform manner. To remove it you can removing `"/FI" + "win32fd.h"` from the Bazel files (and also remove `#include <win32fd.h>` from the .cc files). I don't know how easy it will be to implement things without it, though.

**Comment by suquark** [comment]
@mehrdadn I have not handled all of them, but instead I have centralized them into only `fling.cc`, `shared_memory.cc` and `dlmalloc.cc`

**Comment by mehrdadn** [comment]
@suquark Yeah that should be fine, as long as it actually works. I found it difficult to track which FD is passed where, so please make sure it actually works before merging, otherwise we will need to revert your PR.

**Comment by mehrdadn** [comment]
@suquark In particular please make sure you don't attempt to use an FD opened with `fh_*` APIs with other APIs 
(or vice-versa). They may appear to work in some cases but actually break.

**Comment by suquark** [comment]
What does "don't attempt to use an FD opened with fh_* APIs with other APIs" mean? For example, in this case `fh_get` is used with MapViewOfFile in the original code:

```
  pointer_ = reinterpret_cast<uint8_t*>(MapViewOfFile(reinterpret_cast<HANDLE>(fh_get(fd)), FILE_MAP_ALL_ACCESS, 0, 0, length_));
```

**Comment by mehrdadn** [comment]
@suquark That's fine. If you actually need the `HANDLE` like that then it's fine to use it that way. What I mean is e.g. don't call `CloseHandle(fh_get(fd))` or `fh_close(dup(fd))` or things like that.

**Comment by suquark** [comment]
@mehrdadn The windows build is still failing. Could you have a look at #9431?

**Comment by mehrdadn** [comment]
@suquark I took a look. Some of your errors are due to the fact that you took out `#include <sys/socket.h>` in `fling.h`. I had put definitions there for some things you need, and now they're missing. Also, the order in which Windows headers are included unfortunately matters. [`WinSock2.h` sometimes needs to be included before `Windows.h`](https://stackoverflow.com/a/1372836). Fixing these might get rid of some (or all) of your compile errors.

However, there may be a bigger problem here. `win32fd.h` was not designed to be included haphazardly at arbitrary points in source code. It was designed to be included before certain headers, only in certain files, to resolve very particular issues. Some of your compile errors are an indication of that. You might be able to force the code to compile anyway, but I wouldn't be surprised if the runtime behavior ends up buggy.

I don't think you should expect getting it right to be trivial—while some of this is re-using previous work, I did spend a significant amount of time debugging issues arising from conflicting definitions. I don't yet understand what your changes are (this is a large PR), but I would need to a while to re-review the existing codebase, then review your PR, then understand how they fit together and whether the changes are being made consistently before I can provide an adequate solution. This is too much for me to put on my plate right now, but I would expect it to be a significant chunk of work taking several days, not a quick PR.

If you don't finish it by the end of this week, I'd like to slow down and avoid blocking this PR (or others) for that one, because I do expect it to be rather complicated and time-consuming.

**Comment by suquark** [comment]
thanks a lot for your analysis. I think maybe the easiest way is to totally get rid of win32fd.h in these files. Since only 3 files depends on windows, I can rewrite them in pure windows and unix style. I can work on other PRs while keep fixing them consistently until there are definitely no problems. I do not think it will be buggy if it is written with pure windows headers.

**Comment by mehrdadn** [comment]
If you can do it by all means please do; we should reduce dependence on it as much as possible. Note that `win32fd.h` is still used elsewhere (Arrow? I forget), so if there are any interactions with those components, you might have to use it somewhere eventually.

**Review by suquark — APPROVED** [review]

**Comment by suquark** [comment]
LGTM. The CI errors are not likely related. Let's merge this first.

**Comment by mehrdadn** [comment]
Thanks!

**Pull request merged**
