### PR TITLE
Exit worker when parent raylet dies

### LINKED ISSUE #20706: [Bug][core] Worker processes may leak on raylet crash
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Python workers are supposed to check whether their local raylet is still alive using the PID. But this PID is not currently set. If the PID is not set, then the utils check whether the parent PID == 1, but this also isn't guaranteed to work (see stackoverflow [post](https://unix.stackexchange.com/questions/250153/what-is-a-subreaper-process) on process reaper).

This is can lead to application hangs and worker process leaks if the driver/worker's local raylet dies. We should update this to:
1. Have a more robust way to check the raylet PID. We can do this by asking the raylet to give us their PID during worker registration.
2. As a backup, timeout local raylet failures. If we fail to send IPCs to our local raylet for a few minutes, exit the worker.

### Versions / Dependencies

Ray 2.0dev

There shouldn't be issues as long as worker processes are reaped by PID=1, but apparently this is not the case on my local env.

### Reproduction script

Can test with `pytest python/ray/tests/test_chaos.py::test_chaos_task_retry`. This test has nested tasks, so you can see that some of the intermediate tasks hang when trying to send tasks to their local raylet.

Example output (I added the log message to check the raylet PID, which is set to ""). At this point, the local raylet process has already exited:
```
[2021-11-24 10:25:14,366 I 1496545 1496632] direct_task_transport.cc:616: The worker failed to receive a response from the local raylet, but raylet is still alive. Try again on a local node. Error: IOError:
[2021-11-24 10:25:14,366 D 1496545 1496632] direct_task_transport.cc:532: Requesting lease from raylet fffffffffffffffffffffffffffffffffffffffffffffffffff00004 for task 42e17b47e07dbe2f46156e6bccd3b6fb669e9f6501000000
[2021-11-24 10:25:14,366 D 1496545 1496632] util.cc:385: Checking raylet PID  ppid is 3921
[2021-11-24 10:25:14,366 I 1496545 1496632] direct_task_transport.cc:616: The worker failed to receive a response from the local raylet, but raylet is still alive. Try again on a local node. Error: IOError:
[2021-11-24 10:25:14,366 D 1496545 1496632] direct_task_transport.cc:532: Requesting lease from raylet fffffffffffffffffffffffffffffffffffffffffffffffffff00004 for task 231a5a7a0b7f3f3aa489e02441523a09a000bb0e01000000
[2021-11-24 10:25:14,366 D 1496545 1496632] util.cc:385: Checking raylet PID  ppid is 3921
[2021-11-24 10:25:14,366 I 1496545 1496632] direct_task_transport.cc:616: The worker failed to receive a response from the local raylet, but raylet is still alive. Try again on a local node. Error: IOError:
[2021-11-24 10:25:14,366 D 1496545 1496632] direct_task_transport.cc:532: Requesting lease from raylet fffffffffffffffffffffffffffffffffffffffffffffffffff00004 for task 8fdd40143354c0fe1966c629f2206ea38ec4e00901000000

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jjyao**
This makes sure worker can correctly exit when parent raylet dies. This doesn't cover driver since it needs a different handling (i.e. driver shouldn't exit when raylet dies) and will be addressed separately.

## Related issue number
#20706 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Other approaches I considered:

1. Rely on gcs raylet death notification. This is portable and works across all platforms. The problem is that gcs currently offers at-most once guarantee not at-least once.
2. Rely on OS to notify when raylet dies (i.e. fate share with raylet): https://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits/36945270. This is nice since child process doesn't need to check periodically to see if raylet dies and it works for all child processes raylet creates. However, it needs more work to implement since it's not portable and is more complicated than the PR's approach.

**Comment by stephanie-wang** [comment]
Hmm why can't we do the same thing for the driver? Are you worried about the PID getting reused?

**Comment by ericl** [comment]
You don't want to exit the driver, but raise an exception (Ray shouldn't abruptly exit user driver programs).

**Comment by rkooo567** [comment]
So client rpc failure handling (due to node failure) will be in a diff pr right?

**Comment by jjyao** [comment]
> So client rpc failure handling (due to node failure) will be in a diff pr right?

Yea, I think it's clean to separate these two since they are two issues.

**Comment by jjyao** [comment]
Ready for review.

**Review by stephanie-wang — APPROVED** [review]

**Pull request merged**
