### PR TITLE
[Core] Use const data for buffer where possible, fix: SharedMemoryBuffer should not be constructible from generic Buffer, only SharedMemoryBuffer

### LINKED ISSUE #21632: [Core] Ray Buffers should have const data
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

There is no situation where Buffer needs to have non-const data. We should always restrict our types as much as possible. Hence, we should restrict Buffer to only have const data. (i.e. `data_` pointer is of type `const uint8_t *`)

Agreed, @jovany-wang ?

### Use case

Better type restrictions on code

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jon-chuang**
## Why are these changes needed?

Also, note that `SharedMemoryBuffer` does not own its data in any situation.

## Related issue number

closes: https://github.com/ray-project/ray/issues/21632

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jon-chuang** [comment]
Reading now, I feel uncomfortable with this direction. I'd prefer to split up LocalMemoryBuffer type into `LocalOwnedMemoryBuffer` and `LocalReferenceMemoryBuffer`

I'm also unclear on the semantic distinction between a `LocalMemoryBuffer` and `SharedMemoryBuffer`. 

Personally, I think it should just be `OwnedMemoryBuffer` and `SharedMemoryBuffer`. I believe that the Buffer class should be a chance to enforce lifetimes and ownership of data.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by scv119** [comment]
Yes, I recall that the guarantee of SharedMemoryBuffer is a bit off; and the sub class (or parent class) doesn't share the same guarantee.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Pull request closed without merging**
