### PR TITLE
[core] Use FileLock on ports_by_node.json

### LINKED ISSUE #18779: [Bug] Multiple nodes may write to ports_by_node.json at the same time
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

The `ports_by_node.json` file got corrupted, which then again causes new connections to fail.
```
Traceback (most recent call last): 
File "/usr/local/bin/ray", line 8, in <module> sys.exit(main()) 
File "/usr/local/lib/python3.8/dist-packages/ray/scripts/scripts.py", line 1923, in main return cli() 
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__ return self.main(*args, **kwargs) 
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main rv = self.invoke(ctx) 
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1668, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) 
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) 
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke return __callback(*args, **kwargs) 
File "/usr/local/lib/python3.8/dist-packages/ray/scripts/scripts.py", line 717, in start node = ray.node.Node( 
File "/usr/local/lib/python3.8/dist-packages/ray/node.py", line 221, in __init__ self.metrics_agent_port = self._get_cached_port( 
File "/usr/local/lib/python3.8/dist-packages/ray/node.py", line 662, in _get_cached_port ports_by_node.update(json.load(f)) 
File "/usr/lib/python3.8/json/__init__.py", line 293, in load return loads(fp.read(), 
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads return _default_decoder.decode(s) 
File "/usr/lib/python3.8/json/decoder.py", line 340, in decode raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: line 1 column 6876 (char 6875)
```

This is the `ports_by_node.json` from the session:
```json
{"10.48.0.95:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store": {"metrics_agent_port": 64504, "metrics_export_port": 43667}, "10.48.2.7:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.1": {"metrics_agent_port": 41554, "metrics_export_port": 64232}, "10.48.20.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.2": {"metrics_agent_port": 59247, "metrics_export_port": 53143}, "10.48.1.73:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.3": {"metrics_agent_port": 63354, "metrics_export_port": 58974}, "10.48.3.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.4": {"metrics_agent_port": 58685, "metrics_export_port": 41838}, "10.48.1.74:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.5": {"metrics_agent_port": 61963, "metrics_export_port": 63880}, "10.48.2.12:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.6": {"metrics_agent_port": 47842, "metrics_export_port": 64614}, "10.48.2.13:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.7": {"metrics_agent_port": 42637, "metrics_export_port": 52815}, "10.48.2.13:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.8": {"metrics_agent_port": 58020, "metrics_export_port": 49245}, "10.48.1.76:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.9": {"metrics_agent_port": 61421, "metrics_export_port": 47469}, "10.48.21.34:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.10": {"metrics_agent_port": 57831, "metrics_export_port": 47137}, "10.48.4.3:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.11": {"metrics_agent_port": 63317, "metrics_export_port": 51570}, "10.48.4.4:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.11": {"metrics_agent_port": 57113, "metrics_export_port": 37068}, "10.48.4.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.11": {"metrics_agent_port": 59396, "metrics_export_port": 45126}, "10.48.4.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.12": {"metrics_agent_port": 57299, "metrics_export_port": 41762}, "10.48.4.4:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.12": {"metrics_agent_port": 63973, "metrics_export_port": 56212}, "10.48.5.5:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.13": {"metrics_agent_port": 63861, "metrics_export_port": 48443}, "10.48.6.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.14": {"metrics_agent_port": 60190, "metrics_export_port": 64378}, "10.48.7.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.15": {"metrics_agent_port": 54022, "metrics_export_port": 60396}, "10.48.9.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.16": {"metrics_agent_port": 48611, "metrics_export_port": 55860}, "10.48.8.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.17": {"metrics_agent_port": 62267, "metrics_export_port": 58525}, "10.48.5.3:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.18": {"metrics_agent_port": 60627, "metrics_export_port": 52910}, "10.48.5.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.19": {"metrics_agent_port": 64110, "metrics_export_port": 58746}, "10.48.4.3:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.20": {"metrics_agent_port": 58802, "metrics_export_port": 63770}, "10.48.5.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.21": {"metrics_agent_port": 61587, "metrics_export_port": 59232}, "10.48.21.34:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.22": {"metrics_agent_port": 42592, "metrics_export_port": 60061}, "10.48.4.6:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.23": {"metrics_agent_port": 58999, "metrics_export_port": 59053}, "10.48.4.5:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.24": {"metrics_agent_port": 37718, "metrics_export_port": 63012}, "10.48.5.9:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.24": {"metrics_agent_port": 56620, "metrics_export_port": 58482}, "10.48.21.34:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.25": {"metrics_agent_port": 60821, "metrics_export_port": 57837}, "10.48.10.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.26": {"metrics_agent_port": 61800, "metrics_export_port": 48176}, "10.48.10.3:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.27": {"metrics_agent_port": 48116, "metrics_export_port": 46690}, "10.48.4.3:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.28": {"metrics_agent_port": 59151, "metrics_export_port": 63539}, "10.48.5.10:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.29": {"metrics_agent_port": 62717, "metrics_export_port": 57894}, "10.48.5.5:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.30": {"metrics_agent_port": 60250, "metrics_export_port": 58534}, "10.48.5.11:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.31": {"metrics_agent_port": 64970, "metrics_export_port": 54966}, "10.48.2.14:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.32": {"metrics_agent_port": 62308, "metrics_export_port": 59181}, "10.48.1.77:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.33": {"metrics_agent_port": 43968, "metrics_export_port": 44853}, "10.48.5.12:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.34": {"metrics_agent_port": 54999, "metrics_export_port": 56455}, "10.48.21.35:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.35": {"metrics_agent_port": 55888, "metrics_export_port": 62116}, "10.48.4.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.36": {"metrics_agent_port": 49943, "metrics_export_port": 59966}, "10.48.4.4:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.37": {"metrics_agent_port": 63618, "metrics_export_port": 51502}, "10.48.9.2:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.38": {"metrics_agent_port": 61651, "metrics_export_port": 52517}, "10.48.4.3:/filestore/prod/ray/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.39": {"metrics_agent_port": 63709, "metrics_export_port": 62020}}y/session_2021-09-21_06-35-34_918317_69/sockets/plasma_store.39": {"metrics_export_port": 55409}}
```

Seems like two nodes have written to the file at the same time causing it to become invalid.

We are using `/filestore/prod/ray/` which is a shared folder for the temporary files, by using `--temp-dir /filestore/prod/ray`.

### Reproduction script

No script.

### Anything else

We have only noticed this case once.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by birgerbr**
The new code uses a file-lock before reading and writing to `ports_by_node.json`.
Without it, multiple nodes may write to ports_by_node.json at the same time.

## Related issue number
Closes  #18779

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Looks good to me, thanks for catching the bug and for the fix.  Question for @edoakes, I think you had mentioned we were trying to remove the `filelock` dependency from Ray Core.  Is this still true, and if so was there a suggested alternative?

**Comment by edoakes** [comment]
@birgerbr I'm a bit confused by the behavior you're describing here. As far as I know, there should only ever be one process trying to write to this file because the directory it's in is scoped to a single Ray instance. Could you explain more about what your setup is here?

**Comment by birgerbr** [comment]
> @birgerbr I'm a bit confused by the behavior you're describing here. As far as I know, there should only ever be one process trying to write to this file because the directory it's in is scoped to a single Ray instance. Could you explain more about what your setup is here?

We were using a shared network drive for the as ray's temp-dir, by setting `--temp-dir` to `/filestore/prod/ray/` on both the head node and the worker nodes. The motivation for this was to keep the log files after the corresponding Kubernetes pods were terminated.

Not sure if that is supposed to be supported, also I could not manage to use different `temp-dir` folders for the workers as they just ended up using what was set on the head node.

**Comment by edoakes** [comment]
@birgerbr I see, the setup makes sense to me now.

I'm still not sure that this PR will solve the issue though. Based on my understanding, the `ports_by_node.json` file is generated and updated by a single writer for a single cluster, so while this PR will avoid the corruption, you still still have an issue where you're only getting the ports for the nodes of a single cluster.

Is it possible for you to allocate a separate subdir for each cluster? I think that might solve the issue. For example, `--temp-dir=/filestore/prod/ray/cluster_0` for one cluster and `--temp-dir=/filestore/prod/ray/cluster_1` for another

**Comment by birgerbr** [comment]
> @birgerbr I see, the setup makes sense to me now.
> 
> I'm still not sure that this PR will solve the issue though. Based on my understanding, the `ports_by_node.json` file is generated and updated by a single writer for a single cluster, so while this PR will avoid the corruption, you still still have an issue where you're only getting the ports for the nodes of a single cluster.
> 
> Is it possible for you to allocate a separate subdir for each cluster? I think that might solve the issue. For example, `--temp-dir=/filestore/prod/ray/cluster_0` for one cluster and `--temp-dir=/filestore/prod/ray/cluster_1` for another

We do have two clusters, but they are already using different `temp-dir` paths (`/filestore/staging/ray` and `/filestore/staging/ray`).

Are you saying that the `ports_by_node.json` is only written to by a single process running on the head-node, not by any of the workers or clients?

Not sure if this is relevant, but the head node and the worker nodes are in the Kubernetes cluster's ray namespace, while our applications that connect to ray are in the cluster's default namespace, and there are at times many of those applications.

**Comment by edoakes** [comment]
@birgerbr that's right, there should only be one process in the cluster that's writing to `ports_by_node.json`. Was there a typo in your message? You said that the two clusters are both using `/filestore/staging/ray`.

@rkooo567 can you please confirm that there is only a single writer to the file per cluster?

**Comment by birgerbr** [comment]
> @birgerbr that's right, there should only be one process in the cluster that's writing to `ports_by_node.json`. Was there a typo in your message? You said that the two clusters are both using `/filestore/staging/ray`.
> 
> @rkooo567 can you please confirm that there is only a single writer to the file per cluster?

Sorry. Yes that was a typo. What I wanted to write was:
"We do have two clusters, but they are already using different temp-dir paths (/filestore/staging/ray and /filestore/prod/ray)."

**Comment by rkooo567** [comment]
> @rkooo567 can you please confirm that there is only a single writer to the file per cluster?

Hmm, I am not sure about this. I think it is better having a safety check here though. I can imagine this can have issues when we use things like cluster utils?

**Review by edoakes — APPROVED** [review]

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by birgerbr** [comment]
The format commit was pushed with '--no-verify' as I got this error:
```
Linting changes as part of pre-push hook

ci/travis/format.sh:
WARNING: Ray uses shellcheck 0.7.1, You currently are using 0.7.0. This might generate different results.
WARNING: Ray uses clang-format 7.0.0, You currently are using 10.0.0-4ubuntu1. This might generate different results.
From github.com:ray-project/ray
 * branch                master     -> FETCH_HEAD
python/ray/node.py:26:80: E501 line too long (80 > 79 characters)
python/ray/node.py:40:9: B007 Loop control variable 'i' not used within the loop body. If this is intended, start the name with an underscore.
python/ray/node.py:58:9: B007 Loop control variable 'i' not used within the loop body. If this is intended, start the name with an underscore.
python/ray/node.py:196:80: E501 line too long (80 > 79 characters)
python/ray/node.py:205:80: E501 line too long (81 > 79 characters)
python/ray/node.py:210:80: E501 line too long (83 > 79 characters)
python/ray/node.py:212:80: E501 line too long (80 > 79 characters)
python/ray/node.py:625:80: E501 line too long (84 > 79 characters)
python/ray/node.py:729:80: E501 line too long (80 > 79 characters)
python/ray/node.py:900:80: E501 line too long (85 > 79 characters)

Linting changes failed.
Please make sure 'ci/travis/format.sh' runs with no errors before pushing.
If you want to ignore this and push anyways, re-run with '--no-verify'.
```

**Comment by architkulkarni** [comment]
@birgerbr Thanks for updating the PR!  Sorry about the lint errors, is it possible to fix them manually?  You can check the linter locally by running `ci/travis/format.sh `.  Alternatively, if you give me permission to push to your branch, I would be happy to fix them myself and get this PR merged.

**Comment by architkulkarni** [comment]
Oh actually, can you merge the latest master into your branch?  It looks like it's using the old `format.sh` (because from the error message, it seems to be using the old line length limit.)

**Comment by birgerbr** [comment]
> Oh actually, can you merge the latest master into your branch? It looks like it's using the old `format.sh` (because from the error message, it seems to be using the old line length limit.)

Thanks! Now I could push without `--no-verify` :pray:

**Comment by architkulkarni** [comment]
@edoakes ready for merge!

**Pull request merged**
