### PR TITLE
[Core][Refactor CoreWorker 1/n] move CoreWorkerOptions to its own file

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

This is a serial of PRs to make CoreWorkerProcess thread-safe and CoreWorker Code easy to read. [#19675 #19677 #19678 #19679]

Move CoreWorkerOptions out of core_worker.h; makes the code easier to read. 

Next PR: #19677

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by fishbone — APPROVED** [review]

**Review by jovany-wang — APPROVED** [review]
🚀

**Review by kfstorm — COMMENTED** [review]
Nice change!

**Review by kfstorm — APPROVED** [review]

**Comment by MissiontoMars** [comment]
@kfstorm I think we can pick these refactor PRs to internal codebase separately, maybe reduce the pain of merge code.

**Comment by scv119** [comment]
windows://python/ray/serve:test_standalone is broken on master.

**Comment by scv119** [comment]
Why are these changes needed?
This is a serial of PRs to make CoreWorkerProcess thread-safe and CoreWorker Code easy to read. [#19675 #19677 #19678 #19679]

Move CoreWorkerOptions out of core_worker.h; makes the code easier to read.

Next PR: #19677

**Pull request merged**
