### PR TITLE
[Serve] Fix flaky test_controller_recover_and_delete

### LINKED ISSUE #26822: [CI] `linux://python/ray/serve:test_standalone2` is failing/flaky on master.
- e043f49957a16c706d269fa0658c314fea8a6e5a FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8781#01821e00-c923-48df-9d68-3a86f0756074)
- 8271406a04e380421c6226cbec1b6ea55189ea72 FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8779#01821dd5-8038-4c66-bd12-372707c90380)
- 7f908c408666acc24ca68ca3e45fa73755c1dd4f FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8778#01821d95-7241-4fed-b218-f8a4895b7b96)
- e7957f4a3ee92cd0869b453091b253e3217b3eb3 FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8775#01821d8d-6953-4553-9b58-ec9d06329847)
- 6a71a293b2aef733a4047fd580640e88aad03545 FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8764#01821cd9-ece9-4a29-ab2d-b6526abdeca4)
- e157989a7a0f222d38b0915b0dba1d3652031422 FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8761#01821a3a-157c-4e74-969e-421b995b47b3)
- 887f6726d552be38ab79811dd070af1247189ec8 FAILED [Buildkite :serverless: Serve Tests](https://buildkite.com/ray-project/ray-builders-branch/builds/8757#018219b4-4b42-4101-b6e7-474adafcd7fc)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/serve:test_standalone2-END
....

### PR DESCRIPTION
**Pull request by simon-mo**
Signed-off-by: simon-mo <simon.mo@hey.com>

## Why are these changes needed?
The commit 887f6726d552be38ab79811dd070af1247189ec8 removed the placement group deletion, which made deployment deletion too fast that made our tests flaky.

In particular, we
- removed the check that assumed slow deletion. deflake `test_controller_recover_and_delete`
- added proper cleanup.  deflake `test_shutdown_remote`

## Related issue number
Closes #26822

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Fantastic. I will try this on my local branch where I also had failures.

**Review by sihanwang41 — APPROVED** [review]
awesome!

**Comment by edoakes** [comment]
I'm still getting some errors on my local branch:
```
ERROR tests/test_standalone2.py::test_controller_deserialization_deployment_def - ValueError: stdout argument not allowed, it will be...
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_basic - ValueError: stdout argument not allowed, it will be overridden.
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_with_overriden_config - ValueError: stdout argument not allowed, it w...
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_update_config - ValueError: stdout argument not allowed, it will be o...
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_update_num_replicas - ValueError: stdout argument not allowed, it wil...
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_update_timestamp - ValueError: stdout argument not allowed, it will b...
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_overwrite_apps - ValueError: stdout argument not allowed, it will be ...
ERROR tests/test_standalone2.py::TestDeployApp::test_deploy_app_runtime_env - ValueError: stdout argument not allowed, it will be ove...
ERROR tests/test_standalone2.py::TestDeployApp::test_controller_recover_and_deploy - ValueError: stdout argument not allowed, it will...
ERROR tests/test_standalone2.py::test_shutdown_remote - ValueError: stdout argument not allowed, it will be overridden.
```

**Comment by simon-mo** [comment]
lint and serve tests passed

**Pull request merged**
