### PR TITLE
[Datasets] Upgrade Dask dependency to 2022.6.0 for Python 3.8+

### PR DESCRIPTION
**Pull request by c21**
Signed-off-by: Cheng Su <scnju13@gmail.com>

## Why are these changes needed?

This is a munual redo of https://github.com/ray-project/ray/pull/25697, as Dask `2022.2.0` is the last version to support Python 3.7 - https://docs.dask.org/en/stable/changelog.html#v2022-02-0 .

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by c21** [comment]
cc @matthewdeng FYI.

**Comment by matthewdeng** [comment]
Looks like there is still a conflict for the py38 image that should be looked into!

**Comment by c21** [comment]
```
"stream":"\u001b[91mERROR: Cannot install -r requirements_dl.txt (line 14), -r requirements_dl.txt (line 4), -r requirements_rllib.txt (line 37), -r requirements_tune.txt (line 27), -r requirements_tune.txt (line 31) and dask because these package versions have conflicting dependencies.\n\u001b[0m"}
--
  |  
  | {"stream":"\nThe conflict is caused by:\n    tensorflow 2.6.2 depends on typing-extensions~=3.7.4\n    torch 1.9.0+cpu depends on typing-extensions\n    onnx 1.9.0 depends on typing-extensions\u003e=3.6.2.1\n    nevergrad 0.4.3.post7 depends on typing-extensions\u003e=3.6.6\n    pytorch-lightning 1.5.10 depends on typing-extensions\n    bokeh 2.4.3 depends on typing-extensions\u003e=3.10.0\n    tensorflow 2.6.2 depends on typing-extensions~=3.7.4\n    torch 1.9.0+cpu depends on typing-extensions\n    onnx 1.9.0 depends on typing-extensions\u003e=3.6.2.1\n    nevergrad 0.4.3.post7 depends on typing-extensions\u003e=3.6.6\n    pytorch-lightning 1.5.10 depends on typing-extensions\n    bokeh 2.4.2 depends on typing-extensions\u003e=3.10.0\n\nTo fix this you could try to:\n1. loosen the range of package versions you've specified\n2. remove package versions to allow pip attempt to solve the dependency conflict\n\n"}
  |  
  | {"stream":"\u001b[91mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts\n\u001b[0m"}
```

Thanks @matthewdeng, right just saw it as well. Will take a look.

**Comment by c21** [comment]
The current issue is:

We depend on `tensorflow==2.6.2` in https://github.com/ray-project/ray/blob/master/python/requirements/ml/requirements_dl.txt#L4 and
`dask[complete]==2022.6.0` in this PR.

Further down:
`tensorflow==2.6.2` depends on `typing-extensions~=3.7.4`
while  `dask[complete]==2022.6.0` depends on `bokeh 2.4.2` , and `bokeh 2.4.2`  depends on `typing-extensions >=3.10.0` (https://github.com/dask/dask/blob/71aa6ffb3cfdc2a7dcfbc5f5ed91b20f7735c7fd/docs/source/install.rst).

So there's a conflict dependency on version of `typing-extensions` for now as blocker of this PR.

Offline discussed with @matthewdeng and @richardliaw, we decide to hold off on Dask upgrade for now, and revisit later for a push to upgrade all our dependencies. Closing the PR now.

**Pull request closed without merging**
