### PR TITLE
Add BuildFlow to ecosystem gallery

### PR DESCRIPTION
**Pull request by JoshTanke**
## Why are these changes needed?
BuildFlow has added a Ray integration, and wants to make Ray users aware of it. This PR results from instructions on the [Ray Ecosystem](https://docs.ray.io/en/latest/ray-overview/ray-libraries.html) page.

## Related issue number
N/A

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(
   - [X] Verified change using a yaml editor / parser

### CODE REVIEW

**Comment by JoshTanke** [comment]
@richardliaw Sorry for the direct ping - I wasn't sure who to reach out to. Is there anything blocking this PR?

**Comment by richardliaw** [comment]
hey @angelinalg could you review this?

**Comment by JoshTanke** [comment]
> hey @angelinalg could you review this?

Friendly ping, anything I can do to help this land?

**Review by angelinalg — APPROVED** [review]
Thanks for the ping. Apologies for the delay! Thanks for contributing to the Ray docs.

**Comment by angelinalg** [comment]
@richardliaw I approved this but I don't have merge permissions. Could you merge?

**Comment by dmatrix** [comment]
Congrats on your first PR with Ray! Keep more coming....

**Pull request merged**
