### PR TITLE
Add disconnect button for RayContext in notebooks

### LINKED ISSUE #34431: [ray and Jupyter] Add a "disconnect" button for the output of ray.init in jupyter
### Description

When people run `ray.init()` in jupyter, it starts a ray job automatically and users can view it in Ray Dashboard.
Screen Shot 2023-04-14 at 1 19 46 PM

In order to kill the ray job, users have to run `ray.shutdown()`. People are not aware of this and it's easy to forget about it.
First, we should make it easier to do. Can we add a button like `disconnect` 

Screen Shot 2023-04-14 at 3 53 10 PM

### Use case

see above

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR adds a nice button for disconnecting (i.e. calling `ray.shutdown()`) when `ray.init()` is called in a notebook.

I also was able to dedup a bit of code that was in `RayContext` and `ClientContext` classes, moving it up to the shared parent class of both. :tada: 

image

## Related issue number

Closes #34431.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

I manually tested this by doing `ray.init()` -> click disconnect -> `ray.init()` to make sure that I was able to connect again without error. Everything seems to work just fine.

### CODE REVIEW

**Comment by scottsun94** [comment]
Great. Thanks! Can we use the correct ray logos? I added two svgs, one on dark bg and the other on light bg.

logo-dark-bg
logo-white-bg

Can you also make the logo a bit smaller, something like this?
Screen Shot 2023-05-09 at 4 48 23 PM

**Comment by peytondmurray** [comment]
Definitely! I need to work out how to use one or the other (depending on the jupyterlab theme used?) but I'll put this in today.

**Comment by peytondmurray** [comment]
Wanted to post an update: I haven't forgotten about this, but I am having an issue with building Ray at the moment: https://github.com/ray-project/ray/issues/35200. Will return to this once the other issue is resolved.

**Comment by peytondmurray** [comment]
I've modified the PR to include the logo above, and modified it to adapt to the current Jupyterlab theme. If the user chooses dark mode, the logo looks like this:

image

And if they select light mode:

image

I really like the look of this - thanks for the input @scottsun94!

**Comment by peytondmurray** [comment]
100% agree about providing feedback to the user. I've updated the behavior of the button to follow your suggested pattern.

**Comment by scottsun94** [comment]
@peytondmurray Thanks for the great work! LGTM. Ping @rkooo567 to review

Screenshot 2023-05-16 at 10 10 18 AM
Screenshot 2023-05-16 at 10 10 11 AM

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Failures seem unrelated.

**Pull request merged**
