### PR TITLE
[runtime env] plugin refactor [5/n]: support priority

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?

Currently, the setup order of runtime env plugins is not guaranteed and we can not specify the setup priority of plugins. But in some scenes we need priority. For example, the `env_vars` should be set up first because others rely on it, such as `pip`.

So, in this PR, we support priority configuration for the plugins.
- Add "priority" attribute to `RuntimeEnvPlugin`. The plugin developer can set a static priority in the code.
- Change the format of runtime env plugin to json. You can enable the plugins and overwrite the priority like
```
export RAY_RUNTIME_ENV_PLUGINS='[{"class": "xxx.xxx.xxx_plugin", "priority": 10}]'
```
- The priority should be an integer between 0 and 100. The default priority is 10. A smaller number indicates a higher priority and the plugin will be set up first.

### CODE REVIEW

**Comment by architkulkarni** [comment]
I'm not sure if we discussed this, but why not let `priority: int` be an attribute of `RuntimeEnvPlugin`, like `name`?  That seems like it would be a simpler API and the code would be simpler (we won't have to have these `Context` classes).

One downside I can think of is you can't change the priority without editing the code of your plugin, but dynamically editing the priority doesn't seem like a very common use case.  Is there another downside?

**Comment by SongGuyang** [comment]
@architkulkarni Yep, we didn't discuss about this before. The main reason of putting the priority outside is that I think a plugin developer can't determine the priority by himself. If you develop a plugin and release it, you are not able to know whole of the plugins which users will use. So in my imagination, the controller of priority is the users, not the plugin developers. The users can adjust the setup order of runtime env by setting different priority.

But If all of the plugins are developed by Ray Team and integrated in our main repo, I think putting the priority in the plugin attributes also works.

Overall, maybe we can support both of them? I can add the default priority to the plugin attributes. And if users want to change it, they can overwrite it outside. Wdyt?

**Review by architkulkarni — APPROVED** [review]
I like the idea of supporting both.  Looks good to me!

**Comment by architkulkarni** [comment]
`test_cartpole_crr` flaky on master and unrelated
`//python/ray/serve:test_standalone2` Windows flaky on master and unrelated

**Pull request merged**
