### PR TITLE
Implemented db_client_cache as unordered_map

### PR DESCRIPTION
**Pull request by pschafhalter**
- Replaced the db->db_client_cache data structure in the file src/common/state/redis.cc with a C++ unordered_map.
- This makes further progress on #404

### CODE REVIEW

**Comment by pcmoritz** [comment]
ok to test

**Comment by pcmoritz** [comment]
This looks very nice, can you try to figure out why this is now leaking memory:
https://travis-ci.org/ray-project/ray/jobs/271348615 (you could also use C++ strings and RAII to avoid the problem altogether)

The failure https://travis-ci.org/ray-project/ray/jobs/271348612 is unrelated and the wheels one seems to have timed out when downloading boost.

**Comment by pschafhalter** [comment]
From the valgrind output, it looks like the memory allocated by `db->client_type = strdup(client_type);` is never freed. Adding `free(db->client_type)` to the `db_disconnect` function should solve the issue.

Should I implement that fix and update the pull request to see if that solves the issue?

It seems a bit strange to me because it doesn't seem like `db->client_type` was freed before the changes either.

**Comment by pcmoritz** [comment]
You are right, that is the problem (I think you accidentally removed the free as part of the PR); putting it back should fix it :)

**Comment by pcmoritz** [comment]
Cool, thanks! You should also fix the linting: https://travis-ci.org/ray-project/ray/jobs/271499143

**Comment by pcmoritz** [comment]
This looks great and the other tests failures are unrelated (https://github.com/ray-project/ray/issues/898 and https://github.com/ray-project/ray/issues/922). I'll merge it when the other tests ran.

**Pull request merged**
