### PR TITLE
Revert "Revert "[Prototype] [Core] Make expensive subpackage imports dynamic. (#27658)""

### LINKED ISSUE #29557: [Core] Eagerly importing non-core subpackages slows down Python worker startup
Certain Ray subpackages are expensive to import, either due to their size, dependencies, or their import-time logic that must be executed. E.g. a change in a Datasets import caused a regression for the many_tasks nightly test, despite many_tasks only using Ray Core. However, we want subpackages like `data` and `workflow` to be accessible via attributes on a simple `import ray` import:
```python
import ray
ds = ray.data.read_parquet(...)
```

## Possible Solution

One solution is to delay the import of these expensive subpackages until attribute access, e.g. none of the Datasets code will be run until `ray.data` is accessed.

### PR DESCRIPTION
**Pull request by rickyyx**
Reverts ray-project/ray#29659

Closes #29557

### CODE REVIEW

**Comment by rickyyx** [comment]
@clarkzinzow Do you know which gcs tests this original PR is causing the regression?

**Comment by rickyyx** [comment]
Somehow there were 2 builds associated with PR: https://buildkite.com/ray-project/oss-ci-build-pr/builds/4997#_ seems to be the more useful one. 
Rather than this branch build https://buildkite.com/ray-project/oss-ci-build-branch/builds/1035

**Comment by rickyyx** [comment]
Test failures look unreleated to me. 

tests:test_gcs_fault_tolerance PASS: https://buildkite.com/ray-project/oss-ci-build-pr/builds/4997#0184688c-4c0e-41cf-be6b-3e798bc3d660
tests:test_gcs_pubsub PASS: https://buildkite.com/ray-project/oss-ci-build-pr/builds/4997#0184688c-4c0e-41cf-be6b-3e798bc3d660

**Comment by rkooo567** [comment]
cc @scv119

**Comment by scv119** [comment]
hmm there are a bunch of tests failed to run?

**Comment by rickyyx** [comment]
> hmm there are a bunch of tests failed to run?

This should be right CI: https://buildkite.com/ray-project/oss-ci-build-pr/builds/4997#

**Review by scv119 — APPROVED** [review]

**Pull request merged**
