### PR TITLE
[dataset] Support callable classes to simplify state initialization

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This allows users to specify stateful functions as a class instead of using global variables directly.

### CODE REVIEW

**Comment by clarkzinzow** [comment]
It'd be nice if this could expose constructor args for the class, somehow, without muddying e.g. the `.map()` API with an optional `callable_class_kwargs` arg.

**Comment by ericl** [comment]
I thought about that, but you don't really need constructor args as you can closure capture over them instead.

**Comment by clarkzinzow** [comment]
Probably not a big deal to start. Given any callable class `A` with some constructor arg `a`, you can get the desired functionality by deriving a class `B` that hardcodes construction with `a`:
```python
class A:
    def __init__(self, a):
        # initialize state using a

    def __call__(self, batch):
         # map batch

class B(A):
    def __init__(self):
        super().__init__("some_a_value")

ds.map(B)
```

**Review by clarkzinzow — APPROVED** [review]
Nice!

**Pull request merged**
