### PR TITLE
[Core][Streaming Generator] Fix the perf regression from a serve handle bug fix 

### LINKED ISSUE #38163: [Core][Streaming Generator] Potential perf regression from serve streaming handle fix (https://github.com/ray-project/ray/pull/37972)
### What happened + What you expected to happen

It is expected https://github.com/ray-project/ray/pull/37972 causes some level of perf issue. But it seems like this actually impacts Aviary. @Yard1 will double verify this Monday if this is true. 

To fix the issue, we should

1. post the cpp level code to a thread pool. Previously, we called cpp code that doesn't hold GIL inside a main thread, so event loop thread could focus on running python code. Now, we are running the cpp code inside the event loop, so nogil doesn't have much impact anymore (because there's no concurrency). 
2. Start running microbenchmark that could catch regressions. (@edoakes is it also possible to start tracking serve microbenchmark separately? )

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Before https://github.com/ray-project/ray/pull/37972, we ran the reporting & serilization output (in cpp) in a main thread while all the async actor tasks run in an async thread. However, after the PR, we now run both of them in an async thread.

This caused regression when there are decently large size (200~2KB) generator workloads (Aviary) because the serialization code was running with nogil. It means we could utilize real multi-threading because serialization code runs in a main thread, and async actor code runs in an async thread.

This PR fixes the issue by dispatching a cpp code (reporting & serialization) to a separate thread again. I originally tried using `ThreadpoolExecutor`, but I found this causes weird circular reference bug (that is covered by a new unit test in `test_streaming_generator.py`) that leaks Python objects when exceptions occur. 

Also note that it seems like this PR causes a big of regression in a small output + short task (with one generator output) from a serve microbenchmark. We should verify if the fix is acceptable before reviewing the PR

## Related issue number

Closes https://github.com/ray-project/ray/issues/38163

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Is this ready for review?

**Comment by rkooo567** [comment]
@jjyao I will tag you once it is ready!

**Comment by rkooo567** [comment]
Status: This works & fixes the regression from Aviary, but there's one concern regarding the perf regression from serve microbenchmark. I am discussing it with @edoakes

**Comment by rkooo567** [comment]
Prefer https://github.com/ray-project/ray/pull/38280

**Pull request closed without merging**
