### PR TITLE
use sha1 for hashes instead of md5

### LINKED ISSUE #40534: [Core] MD5 not supported as is for FIPS enabled machines
### Description

FIPS (Federal Information Processing Standards) is a series of security standards required for most government workflows. FIPS compliance requires packages to adhere to a certain level of security and comes with requirements for cryptographic libraries. One of my coworkers (@jbusche) was running into [issues](https://github.com/project-codeflare/codeflare-sdk/issues/357) on a FIPS enabled machine when trying to submit jobs to a Ray Cluster. The key part of the linked issue is this:
```
File /opt/app-root/lib64/python3.8/site-packages/ray/_private/runtime_env/packaging.py:152, in _hash_directory.<locals>.handler(path)
    151 def handler(path: Path):
--> 152     md5 = hashlib.md5()
    153     md5.update(str(path.relative_to(relative_path)).encode())

ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
```
MD5 is not supported for security related applications on a FIPS enabled machine

If the community is open to addressing this issue I see two options:
* change `hashlib.md5(...)` to `hashlib.md5(..., usedforsecurity=False)` because, everywhere in the Ray library that I've found md5 being used it is being used only for calculating file hashes and not for security purposes
* use a SHA-X for computing hashes since it is FIPS compliant

I'm happy to open a PR to solve this issue.

### Use case

Using Ray in a FIPS enabled OpenShift cluster

### PR DESCRIPTION
**Pull request by KPostOffice**
## Why are these changes needed?

Use FIPS compliant hashing algorithm for file hashes

## Related issue number

closes #40534 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by thomasdesr** [comment]
These hashes aren't really used for anything sensitive so that they're md5 isn't really an issue. I'll find someone appropriate to review what the consequences are if we change all these paths :D

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
can you merge the latest master? One premerge test failure seems to keep failing

**Comment by rkooo567** [comment]
hmm some of the premerge failures may be related to failures in the master. I will lyk one more time when you need to merge the latest master...

**Comment by rkooo567** [comment]
can you merge it now? I believe it should be working now...

**Comment by architkulkarni** [comment]
> can you merge it now? I believe it should be working now...

@rkooo567 I noticed we have access to this button now, I think it's a new thing...  I'm going to hit it now just to speed things up and start CI again
Screenshot 2023-11-15 at 11 31 01 AM

**Comment by KPostOffice** [comment]
@rkooo567 LMK if there's anything else you need me to do

**Comment by rkooo567** [comment]
I believe if you merge master, it should pass!

**Comment by rkooo567** [comment]
retrying failed test now///

**Comment by rkooo567** [comment]
I will merge this after the branch cut

**Comment by rkooo567** [comment]
cc @jjyao not sure if it can impact any performance, but please take a close look in regression!

**Pull request merged**
