### PR TITLE
[docs] algolia v3 docsearch

### PR DESCRIPTION
**Pull request by maxpumperla**
Upgrade from older v2 to docsearch v3, which should be easier to customize and maintain due to LTS from Algolia. Comes with a fancier pop-up:

Screenshot 2023-01-27 at 09 34 34

The search bar is now in the top nav, similar to how we e.g. do it in product docs:

Screenshot 2023-01-27 at 09 34 47

On a side note, we also improved the Algolia crawler config under the hood, so regardless of this PR, we should see much improved search already.

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Review by pcmoritz — APPROVED** [review]
Very nice :)

**Comment by maxpumperla** [comment]
@pcmoritz @richardliaw let's NOT merge this before 2.3. I think we need to run a couple of tests, as this changes the UX quite a bit and I'm not sure without frontend tweaking this version is better than what we currently have.

**Comment by maxpumperla** [comment]
See here, the information is similar, but not quite the same context info:

Screenshot 2023-01-28 at 08 36 32
Screenshot 2023-01-28 at 08 37 03

**Comment by maxpumperla** [comment]
closing this for now, as we first need to upgrade to the new theme version, which already breaks lots of things. v3 just creates too much noise on top, will reopen after.

**Pull request closed without merging**
