### PR TITLE
[WIP] Implement global logging configuration

### PR DESCRIPTION
**Pull request by peytondmurray**
This PR changes how the logging configuration for Ray is set, and changes the format of log messages.

### Changes

* Attempts to consolidate logging configuration by introducing reasonable defaults in `ray/log.py`.
* This new logging configuration is done once in `ray/__init__.py` at the top of the module. Subsequent calls to the configuration are ignored.
* A logger for `ray.rllib` is configured at the WARN level, to address https://github.com/ray-project/ray/pull/31858. With this change,
https://github.com/ray-project/ray/pull/31858 can be reverted, again simplifying and consolidating logging configuration.
* Modified `test_output.py::test_logger_config` to test only the logger config, not launch a ray cluster. The test was failing intermittently, I think due to a race condition between the launch of the cluster and the reading of the subprocess's stdout, and anyway it wasn't necessary to call `ray.init` here to check that logging was configured correctly.
* Modified `python/ray/tune/tests/test_commands.py::test_ls_with_cfg` to test the underlying data, not what gets printed to stdout (which has changed with the new logging system).
* Modified a logging message in `ray.tune.automl.search_policy.AutoMLSearcher.on_trial_complete`, which in certain cases emits a logging message which tries to format a `NoneType` into a `%f` during log message formatting. This was a previously-undetected bug which showed up because the default log level is now `INFO`. This fixes a test that was failing in `test_automl_searcher.py::AutoMLSearcherTest`.

## Related issue number

Partially addresses #30005. Originally merged in #32741, this was reverted in #34126 because it broke doctests. This is a second try.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
You can just create revert revert PR!

**Comment by rkooo567** [comment]
Btw lmk if you need any assistance of pair debugging.

**Comment by rkooo567** [comment]
I think your original theory that it is rich formatted for some reasons is the most likely cause of the failure

**Comment by peytondmurray** [comment]
Closing in favor of a revert PR.

**Comment by peytondmurray** [comment]
Closing in favor of a revert PR.

**Pull request closed without merging**
