### PR TITLE
[image] add data test deps into ray-ml

### PR DESCRIPTION
**Pull request by aslonnie**
rllib, train, tune test deps are all added, but data test deps was missing.

### CODE REVIEW

**Comment by can-anyscale** [comment]
Do we need to change the docker build files to install this too?

**Comment by can-anyscale** [comment]
Oh it find files using .* so as long as it is here it will install

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
closing this. talked with @bveeramani offline, this seems to be adding too many deps into the ray-ml image.

**Pull request closed without merging**
