### PR TITLE
[Test]Add a time check for task benchmark

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
In `test_many_tasks.py` case, we usually found the case failing and found the reason.

We sleep for `sleep_time` seconds to wait all tasks to be finished, but the computation of actual sleep time is done by `0.1 * #rounds`, where 0.1 is the sleep time every round.
It looks perfect but one factor was missed, and that's the computation time elapsed. In this case, it is the time consumed by
```
            cur_cpus = ray.available_resources().get("CPU", 0)
            min_cpus_available = min(min_cpus_available, cur_cpus)
```
especially the `ray.available_resources()` took a quite time when the cluster is large. (in our case it took beyond 1s with 1500 nodes).

The situation we thought it would be:
```
for _ in range(sleep_time / 0.1):
    sleep(0.1)
```
The actual situation happens:
```
for _ in range(sleep_time / 0.1):
    do_something(); # it costs time, sometimes pretty much
    sleep(0.1)
```

We don't know why `ray.available_resources()` is slow and if it's logical, but we can add a time checker to make the sleep time precise.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
This is quite simple and useful, @rkooo567 @wuisawesome could you help take a quick review?

**Comment by wuisawesome** [comment]
> We don't know why ray.available_resources() is slow and if it's logical, but we can add a time checker to make the sleep time precise.

IIRC it blocks until it receives a pubsub/grpc message from GCS.

**Comment by WangTaoTheTonic** [comment]
> > We don't know why ray.available_resources() is slow and if it's logical, but we can add a time checker to make the sleep time precise.
> 
> IIRC it blocks until it receives a pubsub/grpc message from GCS.

Yeah the point is that it costs time. Maybe it should be more efficient but the time cost is unavoidable.

**Review by rkooo567 — APPROVED** [review]
To make sure I understood, this doesn't change any test result right? It is just a better way to wait for the sleep time

**Comment by WangTaoTheTonic** [comment]
@rkooo567 Yeah, it will make the test precise.

**Pull request merged**
