### PR TITLE
Add `from_partitioned` to create Dataset from any data source implements `partitioned`

### PR DESCRIPTION
**Pull request by kira-lin**
## Why are these changes needed?

We intend to propose a protocol to make large, distributed, partitioned data exchange between frameworks(like ray, modin, dask) easier. Several PRs are in progress, please check [here](https://github.com/modin-project/modin/pull/3452#issuecomment-927660497). 

It's also possible to do for ray dataset, but to start with, MLDataset is simpler. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
MLDataset is deprecated, so I don't think we should be accepting patches to it.

**Comment by kira-lin** [comment]
Yes, I can do this for ray dataset. I just want to first discuss about this [protocol](https://github.com/IntelPython/DPPY-Spec/blob/draft/partitioned/Partitioned.md).  @fschlimb

**Comment by ericl** [comment]
Sounds good. Btw, the integration point for Datasets would be to define a custom datasource (e.g., `PartitionedDatasource` or similar), via the datasource API: https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/datasource.py

**Comment by kira-lin** [comment]
I did not use Datasource API for a few reasons:
1. data can be in ray object store before `from_partitioned` 
2. we want to utilize data's locality given by location in the partitions.

**Comment by fschlimb** [comment]
Broader discussion started here: https://github.com/data-apis/consortium-feedback/issues/7

**Comment by ericl** [comment]
> Why is that not possible with Datasource?

I believe both of these are possible with Datasource. For locality, Ray will internally manage locality-aware execution, the use of node: labels is not recommended since it interferes with auto-scaling and fault tolerance.

**Comment by kira-lin** [comment]
The data could be in dask, that make things hard. Anyway, I'll update it once the protocol settles

**Comment by ericl** [comment]
If the data is in Dask on Ray, then locality scheduling will apply to those objects. We don't support Dask unless it's run via Dask on Ray.

Alternatively, we could modify the data source API to allow custom read tasks to be generated.

Can you let me know if one of the above alternatives works?

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
