### PR TITLE
Add Apple Silicon GPU Acceleration 

### LINKED ISSUE #37150: [CI] Run macOS test pipeline on Apple Silicon
### Description

Given that more and more apple macs use the Apple Silicon architecture, we should run our CI tests on those going forward.

This issue is not urgent and should be implemented when we have time :)

### Use case

_No response_

### PR DESCRIPTION
**Pull request by NripeshN**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — CHANGES_REQUESTED** [review]
Thanks for the contribution!

I think introducing the different device paths in the example code makes them less legible. CUDA is still the standard for GPUs, and users with other accelerators can adjust the code for their use cases.

That said, I'd propose the following:

1. We keep the changes in `train.torch.get_device()` - this effectively adds support for Apple silicon GPUs in Ray Train
2. We add docs on how to use different Accelerator backends - i.e. a section [here](https://docs.ray.io/en/master/train/user-guides/using-gpus.html)


Could you update your PR with these changes?

I'm also happy to change the GPU guide in the docs in a separate follow-up, then we would only keep the changes to `get_device` in this PR.

**Comment by NripeshN** [comment]
> Thanks for the contribution!
> 
> I think introducing the different device paths in the example code makes them less legible. CUDA is still the standard for GPUs, and users with other accelerators can adjust the code for their use cases.
> 
> That said, I'd propose the following:
> 
> 1. We keep the changes in `train.torch.get_device()` - this effectively adds support for Apple silicon GPUs in Ray Train
> 2. We add docs on how to use different Accelerator backends - i.e. a section [here](https://docs.ray.io/en/master/train/user-guides/using-gpus.html)
> 
> Could you update your PR with these changes?
> 
> I'm also happy to change the GPU guide in the docs in a separate follow-up, then we would only keep the changes to `get_device` in this PR.

Hi @krfricke, I have decided to keep the changes in `train.torch.get_device()` which would add support to mps accelerator to ray

**Review by krfricke — APPROVED** [review]
Thanks! I'll merge once CI passes

**Comment by NripeshN** [comment]
Hi @krfricke, please review this PR https://github.com/ray-project/ray/pull/38464

**Pull request closed without merging**
