### PR TITLE
[RLlib] Trajectory view API docs.

### PR DESCRIPTION
**Pull request by sven1977**
This PR adds detailed documentation on:
- The SampleCollector API used by samplers (async and sync) to collect data from the environments and retrieve and preent this data to the Model for action computations/postprocessing/training.
- The Trajectory View API usable by Models to specify, which data and data-time-slices it requires to see for each forward call.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
Thanks for the detailed documentation, the diagrams here are really great. I made a pass, the highest level comment is I think it's important we **narrow the scope of the trajectory view API to be relevant for models only, not the policy**.

Finer notes:

- The sample collection page doesn't seem to be linked from any top level pages. How about linking to it from index.rst, rllib.rst, and adding it to the rllib-toc.rst?
- The first diagram refers to postprocess_train_batch, but later on it's called postprocess_trajectory. Can we always call it postprocess_trajectory?

> The trajectory view API is a common format by which Models and Policies communicate to each other as well as to the SampleCollector, which data to store, how to store and retrieve this data, and how to present it as inputs to the Policy’s different methods.

I would word this differently (and change the scope of the API): `The trajectory view API allows custom models to define what parts of the trajectory the require to execute the forward pass. For example, in the simplest case a model might only look at the latest observation. However, a RNN / attention based model could look at previous state emitted by the model, or look over a history window of previous observations. The trajectory view API lets models define their requirements and lets RLlib gather the required data for the forward pass in an efficient way.`

> In particular, the methods receiving inputs that depend on trajectory view rules are:

`Since the following methods all call into the model class, they are all indirectly using the trajectory view API. It is important to note that only the model class is aware of the trajectory view, the policy and loss etc. components of the policy do not need to be aware of the trajectory view.`.

> View requirements for Models (Model.forward) and Policies (Policy.compute_actions_from_input_dict and Policy.learn_on_batch) are stored within the view_requirements properties of the ModelV2 and Policy base classes:

Can we remove the policy view requirements (scope it to *model only*)? This requires changing the rest of the doc text to omit any policy view references (model view only).

**Comment by sven1977** [comment]
Thanks for the feedback!
- Yes, I wasn't sure, from where exactly to link it. It's quite a new section about which we never really talked in the rest of the docs (env runner, etc..).
- I'll do another pass and factor in your comments.
- I agree that it's really only an API for users with custom models. The Policy handles all its ViewRequirements under the hood, so the API has no user-facing side here.

**Comment by sven1977** [comment]
@ericl This is ready for review again.

**Review by ericl — APPROVED** [review]
Just read through the whole sample collector doc, it looks fantastic! We should make sure to publicize this in release notes, etc.

Btw, one suggestion for a follow-up: it would be great to have a couple code examples of specifying custom trajectory view requirements in a model. Right now, it is explained well with code snippets only, which is good but adds some friction for users to get started.

**Comment by ericl** [comment]
Some travis failures:

Tue Dec 29 18:12:52 UTC 2020 Flake8....
rllib/evaluation/collectors/sample_collector.py:38:29: F821 undefined name 'DefaultCallbacks'

**Comment by sven1977** [comment]
+1 on that we should add the model examples. I'm working on another PR that does just that: Add more examples on how to build custom Models with RLlib. This will include a trajectory view example (e.g. pass recent n rewards into model).

**Pull request merged**
