### PR TITLE
[RLlib] Issue 23689: tf Initializer has hard-coded float32 dtype.

### LINKED ISSUE #23689: [Bug] [RLib] rlib type hardcoding issues
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

In the normc_initializer in `rllib/models/tf/misc.py:12` as shown below

```
def normc_initializer(std: float = 1.0) -> Any:
    def _initializer(shape, dtype=None, partition_info=None):
        out = np.random.randn(*shape).astype(np.float32)
        out *= std / np.sqrt(np.square(out).sum(axis=0, keepdims=True))
        return tf.constant(out)

    return _initializer
```

the input `dtype` is ignored, risulting in a hard-coded np.float32 initialization, regardless of the required dtype.
It should just be used like the following:
```
def normc_initializer(std: float = 1.0) -> Any:
    def _initializer(shape, dtype=None, partition_info=None):
        out = np.random.randn(*shape).astype(dtype)
        out *= std / np.sqrt(np.square(out).sum(axis=0, keepdims=True))
        return tf.constant(out)

    return _initializer
```

### Versions / Dependencies

Python 3.6.8, 
Linux/Windows

### Reproduction script

pass

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sven1977**
[RLlib] Issue 23689: tf Initializer has hard-coded float32 dtype.

## Why are these changes needed?
Issue #23689 

## Related issue number

Closes #23689 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by avnishn — APPROVED** [review]

**Comment by avnishn** [comment]
The idea is fine but I guess we'll need some function to convert to the analogous np type.

**Review by gjoliver — APPROVED** [review]
good catch ...

**Comment by gjoliver** [comment]
a lot of unit test failure though. I think the default type for dtype may need to be np.float32.

**Comment by sven1977** [comment]
Oh, yeah, didn't even think about this. Let's just make float32 the default (instead of None). I do think float64 could also make sense here, so the PR and issue themselves are valid.

**Pull request merged**
