### PR TITLE
[Test] Change `test_placement_group.py` to large test

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

We recently added tests to this file, and it seems to occasionally exceed 300 seconds timeout (before adding tests, it took about 260~270 seconds, so it is natural).

This promotes this test to be large so that we can avoid this issue. (Lmk if you think it is better sharding test even more.)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by ericl** [comment]
IMO would be better to split, but this is also fine

**Comment by rkooo567** [comment]
@ericl let me just split

**Comment by rkooo567** [comment]
Failed tests should be unrelated

**Comment by rkooo567** [comment]
@ericl I splitted instead

**Pull request merged**
