### PR TITLE
Revert "[ci] upgrade dataplane image"

### PR DESCRIPTION
**Pull request by can-anyscale**
Reverts ray-project/ray#41450

Breaking gcp tests https://buildkite.com/ray-project/release/builds/2507#_

### CODE REVIEW

**Comment by aslonnie** [comment]
how do you know it is caused by this?

looking at the logs, it seems like some other permissions issues.

maybe consider fix forward:

````
2023-11-29 09:50:20,655 INFO worker.py:1639 -- Connected to Ray cluster. View the dashboard at http://10.138.0.24:8265 
Shared connection to 35.247.96.39 closed.
======================================
Ray verification successful.
======================================
Cleaning up cluster...
======================================
Finished executing script successfully.
Subprocess return code: 0
[INFO 2023-11-29 01:51:01,146] anyscale_job_wrapper.py: 190  Process 2724 exited with return code 0.
[INFO 2023-11-29 01:51:01,146] anyscale_job_wrapper.py: 292  Finished with return code 0. Time taken: 185.24580742799998
[WARNING 2023-11-29 01:51:01,146] anyscale_job_wrapper.py: 68  Couldn't upload to cloud storage: '/tmp/release_test_out.json' does not exist.
WARNING: There was an error checking the latest version of pip.
ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
````

we cannot release with this change reverted anyways.

**Review by aslonnie — COMMENTED** [review]
I do not think reverting is the right thing to do.

also do not quite understand why revert would work.

**Comment by can-anyscale** [comment]
I'm running the tests to confirm https://buildkite.com/ray-project/release/builds/2563#_. I see similar failures when I work on py311 upgrades - I thought the failures was caused by py311 but it's likely due to the dataplane itself.

**Comment by can-anyscale** [comment]
I just assume that something has to change in the dataplane for this to work?

**Comment by aslonnie** [comment]
yeah, it might be that the upgraded `gsutil` now needs additional permissions to perform `cp`. this can be fixed by just granting the required permissions to the GCS bucket.

**Comment by can-anyscale** [comment]
Ok, release test passed. Something in the new dataplane made the gcloud users become anonymous.

**Comment by can-anyscale** [comment]
@aslonnie let's revert this first and fix forward with another PR to keep signals on these tests; it might be more complicated than a bucket permission change (user is anonymous)

**Comment by can-anyscale** [comment]
Totally, release blocker: https://github.com/ray-project/ray/issues/41510

**Review by aslonnie — APPROVED** [review]

**Comment by can-anyscale** [comment]
Ok, found a fix forward https://github.com/ray-project/ray/pull/41494

**Pull request closed without merging**
