### PR TITLE
[Data] Add scale for tqdm

### PR DESCRIPTION
**Pull request by Bye-legumes**
## Why are these changes needed?

When the number of row (or ref bundle currently) is large, it's difficult to read the numbers. So we need to add scale unit to show the results.

## Checks

- [√] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [√] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [√] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Bye-legumes** [comment]
@scottjlee HI, I found a elegant solution now. And this is what look like now. 
image
BTW: Fixed a problem that the total need to be 0 when we use use_tqdm_ray=False. otherwise there is a exception now.

**Review by scottjlee — APPROVED** [review]
thanks for the fix!

**Review by bveeramani — APPROVED** [review]

**Comment by Bye-legumes** [comment]
@bveeramani I just update branch to rerun the premerge, so you may need to merge it manually now? Thanks! Also take look at https://github.com/ray-project/ray/pull/46699 Thanks!

**Comment by bveeramani** [comment]
Merged! Thanks for your contribution

**Pull request merged**
