### PR TITLE
Docs mock compiled modules

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR does two things:

1. Compiled ray modules are mocked out using sphinx's `autodoc_mock_modules`. This means we no longer need to roll our own mocking system for the compiled ray modules, and removes some unsightly type annotations in certain places in the docs.
2. Intersphinx mappings were added for a lot of ray's dependencies. For types that are documented with sphinx and hosted elsewhere, our type annotations will now be clickable links to the appropriate documentation for that type. See for example the Python type annotations below, which are links to the pages of the official Python docs for those types:

image

**NOTE:** The changes to `memory_utils.py` are needed because here we mock out `ray._raylet`, a compiled module. Previously `memory_utils.py` was doing arithmetic on objects that are now mocked out, which would raise an exception when building the docs. I therefore had to move this arithmetic inside the functions that actually need these quantities to get the docs to build. I checked everywhere in the code base, and I can't see any reason that these are being computed at module initialization time, but if someone else sees a problem with this approach I'd be open to other suggestions.

In testing this change, I also noticed some incorrect type annotations for external dependencies, so I've fixed those too so that intersphinx can link them correctly.

## Related issue number

Partially fulfills https://github.com/ray-project/ray/issues/37944.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by angelinalg — APPROVED** [review]
@maxpumperla, please review. Thanks!

**Review by maxpumperla — APPROVED** [review]
Perfect, thanks so much @peytondmurray!

**Review by cadedaniel — APPROVED** [review]
core changes LGTM

**Review by bveeramani — APPROVED** [review]
Data changes LGTM

**Comment by peytondmurray** [comment]
Looks like there's an issue on the server side for `https://lightning.ai/docs/pytorch/stable/objects.inv`. I'll push a dummy commit to retrigger CI.

**Pull request merged**
