### PR TITLE
[docs] Improve AIR table of contents titles

### PR DESCRIPTION
**Pull request by ericl**
Signed-off-by: Eric Liang <ekhliang@gmail.com>

## Why are these changes needed?

- Clean up the table of contents titles

### CODE REVIEW

**Comment by richardliaw** [comment]
Can you update the index page for user guides?

**Comment by ericl** [comment]
Sure. To clarify, you mean the page of questions like "How to configure Data Ingest"? Not sure if that was intentional.

**Comment by richardliaw** [comment]
Yeah, the pages like "How to configure Data Ingest". I was thinking they should be consistent with the side bar.

**Comment by ericl** [comment]
@richardliaw done.

**Review by richardliaw — APPROVED** [review]
thanks!

**Pull request merged**
