### PR TITLE
Fix mnist sgd jenkins tests on master

### PR DESCRIPTION
**Pull request by pcmoritz**
see https://github.com/ray-project/ray/pull/4145

### CODE REVIEW

**Review by richardliaw — DISMISSED** [review]

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by pcmoritz** [comment]
So this is working locally for me now (without further changes), let's see what Jenkins says. Unfortunately Jenkins seems to be down right now :(

**Comment by richardliaw** [comment]
Can you delay the nccl import? It is only dependent, and is only needed in
the nccl codepath

**Comment by pcmoritz** [comment]
Thanks, should be fixed now!

**Comment by pcmoritz** [comment]
+1 looks like this fixes it!

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Should we fix the rest of jenkins in this PR?

**Comment by richardliaw** [comment]
Wait I'd like to fix jenkins in this PR - there's a couple easy fixes.

**Comment by pcmoritz** [comment]
K

**Comment by richardliaw** [comment]
jenkins retest this please

**Pull request merged**
