### PR TITLE
[data] Optimization to reduce ArrowBlock building time for blocks of size 1

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Many Data ops depend on converting numpy batches to Arrow blocks. A single np array -> pyarrow is normally zero-copy, but blocks with multiple rows will need a copy to make the column of np arrays into one contiguous ndarray. This PR avoids this step for blocks of a single row by using `np.expand_dims` to reshape the array instead of copying it.

## Related issue number

Needed for #37474.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by stephanie-wang** [comment]
For a single-row block `[{"field": 100MB np.array}]`:

Before:
In [11]: %timeit b.build()
385 ms ± 8.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

After:
In [13]: %timeit b.build()
116 µs ± 3.59 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

**Comment by ericl** [comment]
Nice!

**Review by c21 — APPROVED** [review]
LGTM

**Comment by zhe-thoughts** [comment]
Please verify `tests-ok` and then I will review / merge. Thanks!

**Comment by stephanie-wang** [comment]
Hey @zhe-thoughts this is ready to merge.

**Review by raulchen — APPROVED** [review]

**Review by zhe-thoughts — APPROVED** [review]

**Comment by zhe-thoughts** [comment]
"buildkite/premerge" is a x

**Comment by stephanie-wang** [comment]
> "buildkite/premerge" is a x

The failure is unrelated (it's flaky on master)

**Comment by c21** [comment]
I guess `buildkite/premerge` is mandatory to pass before merging. Let me retry it.

**Comment by zhe-thoughts** [comment]
Yes other checks we can use manual judgement, `buildkite/premerge` must pass. cc @aslonnie

**Comment by stephanie-wang** [comment]
> Yes other checks we can use manual judgement, `buildkite/premerge` must pass. cc @aslonnie

It's passing now.

**Pull request merged**
