### PR TITLE
ray ignores TMPDIR variable

### LINKED ISSUE #13606: ray ignores TMPDIR variable -> Spawning ray fails
We have set `$TMPDIR` to `/scratch/tmp/$USER` on our system since we have fast SSD scratch space on our nodes available.
However, when calling `ray.init()` we always get `/tmp/ray` back:
```python
{'node_ip_address': ...,
 'raylet_ip_address': ...,
 'redis_address': ...,
 'object_store_address': '/tmp/ray/session_2021-01-21_16-22-54_796050_43968/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-01-21_16-22-54_796050_43968/sockets/raylet',
 'webui_url': '127.0.0.1:8265',
 'session_dir': '/tmp/ray/session_2021-01-21_16-22-54_796050_43968',
 'metrics_export_port': 65081,
 'node_id': ...}
```

This also causes Ray to fail spawning the dashboard:
```python
#> cat /tmp/ray/session_2021-01-21_16-22-54_796050_43968/logs/dashboard.err 
Traceback (most recent call last):
  File "/opt/modules/anaconda/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 975, in <module>
    raise e
  File "/opt/modules/anaconda/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 962, in <module>
    dashboard.run()
  File "/opt/modules/anaconda/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 572, in run
    self.log_dashboard_url()
  File "/opt/modules/anaconda/envs/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 567, in log_dashboard_url
    with open(os.path.join(self.temp_dir, "dashboard_url"), "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ray/dashboard_url'
```

### PR DESCRIPTION
**Pull request by ericl**
Closes https://github.com/ray-project/ray/issues/13606

### CODE REVIEW

**Comment by ericl** [comment]
//python/ray/tests:test_tempfile                                         FAILED in 3 out of 3 in 30.2s
  | Stats over 3 runs: max = 30.2s, min = 29.2s, avg = 29.5s, dev = 0.4s
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_tempfile/test.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_tempfile/test_attempts/attempt_1.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/python/ray/tests/test_tempfile/test_attempts/attempt_2.log
 

<br class="Apple-interchange-newline">

**Review by richardliaw — APPROVED** [review]
hmm interesting; shouldn't this be whatever you set in `ray start --temp-dir`?

**Review by clarkzinzow — APPROVED** [review]
LGTM

**Comment by clarkzinzow** [comment]
Also @richardliaw `--temp-dir` should be respected since this temp dir will only be set if `--temp-dir` wasn't provided: https://github.com/ray-project/ray/blob/a1a51a0a7fe20ef367b698c34952738324817c56/python/ray/node.py#L147

I am concerned about a few discrepancies when `--temp-dir` is given between most of the Ray node using `--temp-dir` and some Ray components and external libs using `get_ray_temp_dir()` and `get_user_temp_dir()` directly.
https://github.com/ray-project/ray/search?q=get_ray_temp_dir
https://github.com/ray-project/ray/search?q=get_user_temp_dir

**Comment by ericl** [comment]
> @ericl I am concerned about a few discrepancies when --temp-dir is given between most of the Ray node using --temp-dir and some Ray components and external libs using get_ray_temp_dir() and get_user_temp_dir() directly.

Yeah... maybe we should just deprecate --temp-dir and recommend TMPDIR?

**Comment by ericl** [comment]
Rolled that change into https://github.com/ray-project/ray/pull/17133

**Pull request merged**
