### PR TITLE
update the brew and pip packages

### PR DESCRIPTION
**Pull request by cybermaster**
Added few of the mission pieces for brew install and pip install on Mac OS X.

### CODE REVIEW

**Comment by robertnishihara** [comment]
Hey @cybermaster thanks for bringing this up, I agree this dependencies need to be documented somewhere (they are similar on Linux as well).

Ray itself doesn't really depend on tensorflow, smart_open, h5py, and opencv, which is why they currently aren't listed. But the RL libraries do have these dependencies.

One natural place to document these dependencies would be in http://ray.readthedocs.io/en/latest/rllib.html. What do you think about that?

Also, `pip install opencv-python` should suffice on both Linux/Mac instead of using `brew`.

**Comment by robertnishihara** [comment]
test this please

**Comment by robertnishihara** [comment]
Note that the "test this please" comment is an instruction to Jenkins.

**Comment by pcmoritz** [comment]
Thanks for submitting this!

One thing we could do is have "pip install ray[rllib]" and have that automatically pull in the right dependencies, see https://github.com/openai/gym/blob/master/setup.py#L9

But we might not want to install tensorflow by default and we certainly don't wan't to install opencv by default, it often causes trouble.

**Comment by cybermaster** [comment]
@robertnishihara, the documenting in the http://ray.readthedocs.io/en/latest/rllib.html page should be a good place.

**Pull request closed without merging**
