### PR TITLE
Ensure job registered first before return.

### LINKED ISSUE #19172: [Core][Bug] Gcs crashed and cluster hangs
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
(pid=gcs_server, ip=XX) [2021-10-06 23:59:31,998 C 1900 1900] gcs_job_manager.cc:176:  Check failed: it != ray_namespaces_.end() Couldn't find job with id: 26b30000
(pid=gcs_server, ip=XX) *** StackTrace Information ***
(pid=gcs_server, ip=XX)     ray::SpdLogMessage::Flush()
(pid=gcs_server, ip=XX)     ray::RayLog::~RayLog()
(pid=gcs_server, ip=XX)     ray::gcs::GcsJobManager::GetRayNamespace()
(pid=gcs_server, ip=XX)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server, ip=XX)     ray::gcs::GcsActorManager::RegisterActor()
(pid=gcs_server, ip=XX)     ray::gcs::GcsActorManager::HandleRegisterActor()
(pid=gcs_server, ip=XX)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server, ip=XX)     boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server, ip=XX)     boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server, ip=XX)     boost::asio::detail::scheduler::run()
(pid=gcs_server, ip=XX)     boost::asio::io_context::run()
(pid=gcs_server, ip=XX)     main
(pid=gcs_server, ip=XX)     __libc_start_main


2021-10-06 23:59:36,466	WARNING worker.py:1231 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 419, in run
    self._run()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 307, in _run
    self.update_load_metrics()
  File "/opt/conda/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 227, in update_load_metrics
    request, timeout=4)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Broken pipe"
	debug_error_string = "{"created":"@1633564776.437866949","description":"Error received from peer ipv4:XX:36477","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Broken pipe","grpc_status":14}"
```

### Reproduction script

n/a

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Before this PR, there is a race condition where:
- job register starts
- driver start to launch actor
- gcs register actor ===> crash
- job register ends

Actor registration should be forced to be after driver registration. This PR enforces that.

## Related issue number

Closes #19172 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
The fix makes sense to me. Maybe you can manually test that reverse the order (first register actor then register the driver) could reproduce the bug?

**Comment by rkooo567** [comment]
@iycheng I think we can only reproduce only when we add artificial delay inside gcs_client_->Jobs().AsyncAdd... (maybe re-post to the io service in 100ms or sth) Maybe checking manually?

**Comment by iycheng** [comment]
@scv119 it's not like what you mean there. It's like this:

```
ray.init(address='auto')
#ray.init register with node manager
#ray.init node manager register it to worker pool

a = Actor.remote()
#Actor.remote() core worker register it to gcs
#Actor.remote() gcs tries to register it ===> Crash

#ray.init node manager register it to GCS
```

**Comment by iycheng** [comment]
Let me artificially inject some errors ad-hoc just for reproducing it.

**Comment by iycheng** [comment]
```
(pid=gcs_server) [2021-10-12 04:21:51,104 C 12457 12457] gcs_job_manager.cc:176:  Check failed: it != ray_namespaces_.end() Couldn't find job with id: 01000000
(pid=gcs_server) *** StackTrace Information ***
(pid=gcs_server)     ray::SpdLogMessage::Flush()
(pid=gcs_server)     ray::RayLog::~RayLog()
(pid=gcs_server)     _ZNK3ray3gcs13GcsJobManager15GetRayNamespaceB5cxx11ERKNS_5JobIDE
(pid=gcs_server)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server)     ray::gcs::GcsActorManager::RegisterActor()
(pid=gcs_server)     ray::gcs::GcsActorManager::HandleRegisterActor()
(pid=gcs_server)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server)     boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server)     boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server)     boost::asio::detail::scheduler::run()
(pid=gcs_server)     boost::asio::io_context::run()
(pid=gcs_server)     main
(pid=gcs_server)     __libc_start_main
(pid=gcs_server)
(pid=gcs_server) [2021-10-12 04:21:51,105 E 12457 12457] event.cc:125: [ Event 665447ac8145999ab54aa3cf90fcab6a7652 null ] src/ray/gcs/gcs_server/gcs_job_manager.cc:176: Check failed: it != ray_namespaces_.end() Couldn't find job with id: 01000000
(pid=gcs_server) *** StackTrace Information ***
(pid=gcs_server)     ray::SpdLogMessage::Flush()
(pid=gcs_server)     ray::RayLog::~RayLog()
(pid=gcs_server)     _ZNK3ray3gcs13GcsJobManager15GetRayNamespaceB5cxx11ERKNS_5JobIDE
(pid=gcs_server)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server)     ray::gcs::GcsActorManager::RegisterActor()
(pid=gcs_server)     ray::gcs::GcsActorManager::HandleRegisterActor()
(pid=gcs_server)     std::_Function_handler<>::_M_invoke()
(pid=gcs_server)     boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server)     boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server)     boost::asio::detail::scheduler::run()
(pid=gcs_server)     boost::asio::io_context::run()
(pid=gcs_server)     main
(pid=gcs_server)     __libc_start_main
(pid=gcs_server)
```


It looks like match the stacktrace showing in the issue.

**Review by scv119 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
Thanks for verifying this :)! I wonder if we need support on adding delays to some RPC calls... (so that we can test this sort of issues better)

**Pull request merged**
