### PR TITLE
[core] fix actor task depth calculation

### PR DESCRIPTION
**Pull request by clarng**
## Why are these changes needed?

Fix the actor task depth. Currently the depth is equal to the submitter. Make it 1 + depth of the submitter. In the case of circular calls it (actor calling task calling actor again) the depth would continue to increment 

E.g. current bug
Driver (d=0) creates actor (d=1)
Driver schedules the actor task to run on the actor (d=0)
Actor task creates a nested task (d=1)

Current behavior: nested task depth is 1
Expected behavior: nested task depth is 2

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by stephanie-wang** [comment]
Could you leave a bit more context about what can go wrong with the current depth implementation? It's not immediately obvious to me that using the depth of the actor is objectively better.

**Comment by clarng** [comment]
> Could you leave a bit more context about what can go wrong with the current depth implementation? It's not immediately obvious to me that using the depth of the actor is objectively better.

I think it is a bug, I added an example. Let me know if you disagree

**Comment by rkooo567** [comment]
Does it fix any known / open issue? If so can you link it?

**Comment by clarng** [comment]
> Does it fix any known / open issue? If so can you link it?

It address this corner case for OOM:

https://docs.google.com/document/d/1ScC88dSVceP1-XXm74yIxG6j20YXBGBqsS8JWaYanGM/edit#heading=h.stubzlgi76nb

**Review by stephanie-wang — APPROVED** [review]
Thanks for fixing this!

**Review by scv119 — APPROVED** [review]

**Pull request merged**
