### PR TITLE
Add autoregressive KL

### PR DESCRIPTION
**Pull request by jon-chuang**
If you do the math you can check this is the correct way to write an autoregressive KL

## Why are these changes needed?
Completes the example

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Some lint errors.

**Comment by jon-chuang** [comment]
The lint errors are coming from accessing private functions with _ in other, it seems I must make these functions public; or is it fine to leave it as such?

**Comment by ericl** [comment]
Actually this is the error ./rllib/examples/autoregressive_action_dist.py:104:1: W293 blank line contains whitespace

**Comment by ericl** [comment]
Merged, thanks!

**Pull request merged**
