### PR TITLE
remove unused params in grpc macros

### PR DESCRIPTION
**Pull request by zhijunfu**
## Why are these changes needed?

Remove unused params for GRPC method definition macros

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by ffbin** [comment]
LGTM

**Review by raulchen — APPROVED** [review]

**Comment by raulchen** [comment]
Can you fix the lint error?

**Comment by zhijunfu** [comment]
> Can you fix the lint error?

fixed, thanks

**Comment by ffbin** [comment]
Because https://github.com/ray-project/ray/pull/6685 is merged, this pr need rebase master,thanks

**Pull request merged**
