### PR TITLE
[RLlib] Fix RLlib CLI: e.g. `rllib example run cartpole-ppo` fails. (#30664)

### PR DESCRIPTION
**Pull request by xwjiang2010**
## Why are these changes needed?

cherry-pick of https://github.com/ray-project/ray/pull/30664

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by xwjiang2010** [comment]
This PR should replace https://github.com/ray-project/ray/pull/30665.

Also as a separate action item, rllib team should look into make links relative instead of absolute. See comment here: https://github.com/ray-project/ray/pull/30665#issuecomment-1329896091

**Review by gjoliver — APPROVED** [review]
stamp for RL

**Comment by xwjiang2010** [comment]
slack thread: https://anyscaleteam.slack.com/archives/C01DVKB5SHE/p1669726106588839?thread_ts=1669625930.314069&cid=C01DVKB5SHE

**Comment by xwjiang2010** [comment]
Failing test is not related. Merging.

**Comment by sven1977** [comment]
Thanks @xwjiang2010 !!

**Pull request merged**
