### PR TITLE
Relint codebase with yapf

### PR DESCRIPTION
**Pull request by pcmoritz**
should be merged before https://github.com/ray-project/ray/pull/1843

Relinting can be run with a single command:
```
find . -name '*.py' -type f -exec yapf -i -r {} \;
```

### CODE REVIEW

**Review by concretevitamin — APPROVED** [review]
Thanks!

**Comment by pcmoritz** [comment]
Relinting can be run

**Comment by richardliaw** [comment]
How urgent is there? There's a few PRs in flight from undergrads.

**Review by robertnishihara — CHANGES_REQUESTED** [review]
Please exclude everything under `python/ray/cloudpickle` as that is directly copied from the cloudpickle repo.

**Pull request closed without merging**
