### PR TITLE
[ci] remove ray from ml base

### PR DESCRIPTION
**Pull request by aslonnie**
base does not need ray; we will reinstall ray in later layers.

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
cc @matthewdeng

**Review by matthewdeng — APPROVED** [review]

**Comment by aslonnie** [comment]
this PR might fix the issues related to here:
https://buildkite.com/ray-project/postmerge/builds/2564#018d1a25-9e78-44f2-95c5-6095d3b7ab00

I feel that it is the mass move (of an installed ray in the container) caused the overlay fs of docker build to panic somehow (maybe run out of temp disk or something)

**Comment by aslonnie** [comment]
the overlayfs issue might be associated with the buildkite stack upgrade.

**Comment by aslonnie** [comment]
woohoo~ going in~

let's see if this makes things build and run a bit better..

**Pull request merged**
