### PR TITLE
Adding Ray Clusters (Under Construction) doc section with new structure

### LINKED ISSUE #26894: [Ray clusters][docs]: Restructure docs, put filler content to compare changes against

### PR DESCRIPTION
**Pull request by cadedaniel**
This PR:

- Creates a new chapter in the docs titled "Ray Clusters (Under Construction)".
- The new chapter makes the Ray Clusters docs follow the same structure as the other docs (https://diataxis.fr/)
- The new chapter will eventually replace the old chapter.
- I want to merge this now so that @DmitriGekhtman can put his Kuberay docs into the new structure.

### CODE REVIEW

**Comment by jjyao** [comment]
What's the difference between `User Guides` and `Tutorials`? For other docs, we have `Examples`.

**Comment by cadedaniel** [comment]
> What's the difference between `User Guides` and `Tutorials`? For other docs, we have `Examples`.

This is following the Kuberentes style of docs ([tasks](https://kubernetes.io/docs/tasks/), [their explanation](https://kubernetes.io/docs/contribute/style/page-content-types/#task)), but @scottsun94 brought up a good point that users could confuse this with Ray tasks. So User Guides (ex Tasks) show how to do a single thing, whereas Tutorials cover a topic end-to-end with surface-level explanations.

**Comment by jjyao** [comment]
It's more about being consistent with other ray docs (not sure if it's necessary). The layout is typically: Getting Started. Key Concepts. User Guides. Examples. API References.

**Comment by DmitriGekhtman** [comment]
I'd actually prefer to have the new Ray-on-K8s docs as a top-level "Ray on Kubernetes", directly under Clusters, along the same lines as "Serve" under Ray Libraries.

It would effectively (or, literally, after some renaming) have its own "Getting Started", "Key Concepts", "API reference", and "User guides", with links to the relevant top-level "Clusters" pages where appropriate
(e.g. links to the place where the mechanics of scheduling and autoscaling is discussed).

The idea here is that K8s users (who account for a significant fraction of Ray users) will see the "Ray on Kubernetes" node as soon as they land on the Ray docs and will have exactly all of the info they need to get going under the drop-down.

Another consideration is that there are additional "Key Concepts" specific to K8s deployment scenarios:
- A Ray cluster is represented as a Custom Resource Definition
- A Ray cluster on Kubernetes runs one Ray node per pod
- blah blah blah

Thoughts, @pcmoritz, @richardliaw, @cadedaniel, @wuisawesome other reviewers?

**Comment by cadedaniel** [comment]
> I'd actually prefer to have the new Ray-on-K8s docs as a top-level "Ray on Kubernetes", directly under Clusters, along the same lines as "Serve" under Ray Libraries.
> 
> Ray-on-K8s would effectively (or, literally, after some renaming) have its own "Getting Started", "Key Concepts", "API reference", and "User guides", with links to the relevant top-level "Clusters" pages where appropriate (e.g. links to the place where the mechanics of scheduling and autoscaling is discussed).
> 
> The idea here is that K8s users (who account for a significant fraction of Ray users) will see the "Ray on Kubernetes" node as soon as they land on the Ray docs and will have exactly the info they need to get going under the drop-down.
> 
> Another consideration is that there are additional "Key Concepts" specific to K8s deployment scenarios:
> 
> * A Ray cluster is represented as a Custom Resource Definition
> * A Ray cluster on Kubernetes runs one Ray node per pod
> * etc.
> 
> Thoughts, @pcmoritz, @richardliaw, @cadedaniel, @wuisawesome other reviewers?

What is the intersection between the user experience of creating+using+maintaining a cluster on a VM stack (`ray up`) and a cluster on Kubernetes? It seems to me that creating+maintaining a Ray cluster on Kubernetes has no intersection with doing the same via `ray up`, except for common Key Concepts. However, the user experience (application developer) _is_ common between the two.

If this is the case, why not take your suggestion to follow the Serve example further with the following structure?
```
* Ray Clusters
  * Managing Ray Clusters on Kubernetes
    * Getting Started
    * Key Concepts
    * User Guides
    * Examples
    * Reference
  * Managing Ray Clusters via `ray up`
    * Getting Started
    * Key Concepts
    * User Guides
    * Examples
    * Reference
  * Using Ray Clusters
    * Getting Started
    * Key Concepts
    * User Guides
    * Examples
    * Reference
```

We live with potential duplication of Key Concepts. But I think we can get away with that since we can have a single-source-of-truth for each Key Concept and `include` that in each respective `Using Ray Clusters>Key Concepts`, `Managing Ray Clusters via ray up>Key Concepts` and `Managing Ray Clusters on Kuberentes>Key Concepts`. Or, maybe we have a common Key Concepts page and let each individual Key Concepts page focus on concepts that are unique to the use-case.

I fee like @wuisawesome has been saying something like this for a while :sweat_smile: , sorry if I'm just now fully understanding your point.

**Comment by ericl** [comment]
How about a middle ground here? A few points of feedback:
- "Key concepts" should really be shared. If the concept is significantly different between K8s/VM mode that cannot be addressed in copy or tab sections... maybe it's not a key concept?
- "Using ray clusters" should be very short, basically one page on how to submit jobs / connect. This part is also like K8s / VM mode specific, and hence we should incorporate it into each section instead of trying to have a common "Using clusters" section.

Implementing this would give you:
```

* Ray Clusters
  * Getting Started
    Direct users, based on what they are trying to accomplish, to the
    correct page between "Managing Ray Clusters on Kubernetes",
    "Managing Ray Clusters via `ray up`", and "Using Ray Clusters".
    There should be some discussion on Kubernetes vs. `ray up` for
    those looking to create new Ray clusters for the first time.

  * Key Concepts

  * Ray Clusters on Kubernetes
    * Getting Started
    * User Guides
    * Examples
    * Reference

  * Ray Clusters on VMs
    * Getting Started
    * User Guides
    * Examples
    * Reference
```

**Comment by wuisawesome** [comment]
I don't think there should be a difference in key concepts between `ray up` and kuberay, therefore I have weak preference for bubbling the key concepts up to the top level. 

There may need to be an additional section under k8s and `ray up` which helps map key ray concepts to VM/k8s concepts.

**Comment by ericl** [comment]
Yeah I think this is implementation detail (making key-concepts work for both). The few places I can think of:
- nodes vs pods. Can tackle this in bullet points under node concept.
- autoscaler location: head node vs kuberay pod. Can have a couple bullet points here too.

Btw, the key concepts section needs to be trimmed way down. It's supposed to be a single, concise page of key concepts. Right now, it's introducing a lot of other stuff that isn't really key (there's like 10 things). I think you can keep it to:
- Worker Nodes
- Head Node
- Autoscaler
- Clients and Jobs

The other sub-sections can be moved under user guides in the K8s/VM specific sections.

**Comment by cadedaniel** [comment]
Okay, fair point that concepts in Key Concepts should be "key". However, I think we should be open to having a non-"key" conceptual dictionary if the documentation calls for it (_a la_ [Kubernetes Concepts section in their docs](https://kubernetes.io/docs/concepts/)).

For example, I think a lot of Ray Discuss posts can be preemptively answered if we had a Configuration Best Practices section, like [Kubernetes does](https://kubernetes.io/docs/concepts/configuration/overview/). These kinds of things may very well be specific to K8s/VM stacks.

So, maybe a `Concepts` section under both `Ray Clusters on Kubernetes` and `Ray Clusters on VMs`?

**Comment by DmitriGekhtman** [comment]
@ericl's suggestion of one "key-concepts" makes sense.

The "node" concept can explain that a Ray node is a bundle of processes that can be hosted on a VM or in a pod.

If there are K8s-specific or VM-specific ideas that are left over, that's fine -- can mention briefly in the shared section and go into greater detail in the relevant subsections. Could for example add an "architecture" section to Kubernetes docs (or just link to the diagram in the KubeRay repo's docs :) )

**Comment by DmitriGekhtman** [comment]
> So, maybe a Concepts section under both Ray Clusters on Kubernetes and Ray Clusters on VMs?

For the time being, let's not be picky about this detail and just get the content out.
After that, we can uniformize for consistency between the VM and K8s sections.

**Comment by cadedaniel** [comment]
Do I need all code owners to give approval? Or just one?

cc @richardliaw @DmitriGekhtman

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
Looks like I'm not enough.
I'll spam everyone on the relevant internal Slack channel again.

**Review by edoakes — APPROVED** [review]
stamp for codeowner council

**Pull request merged**
