### PR TITLE
[Core][Streaming Generator] Fix memory leak from the end of object stream object

### LINKED ISSUE #38089: [Ray Serve] Memory leak in 2.6
### What happened + What you expected to happen

See a memory leak in HTTPProxy on multiple serve clusters in Anyscale Workspaces/Services. This regression was likely introduced in 2.6
Screenshot 2023-08-03 at 1 52 12 PM

### Versions / Dependencies

Ray 2.6.1

### Reproduction script

Run a serve deployment and send requests repeatedly

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

https://github.com/ray-project/ray/blob/4304e45527a68e6326bedb69ae96d623cedb8bd4/src/ray/core_worker/core_worker.h#L446

Currently, the objects are deleted from the memory store manually when the reference is removed (via `__dealloc__` from `ObjectRef` class here; https://github.com/ray-project/ray/blob/4304e45527a68e6326bedb69ae96d623cedb8bd4/python/ray/includes/object_ref.pxi#L62).

This causes the leak from streaming generator because it doesn't actually create a Cython object ref class for the end of stream.

This PR fixes the issue by manually deleting the objects from memory store when the ref of streaming generator objects goes to 0. 

In the long term, we should fix this by modifying reference_count.cc to actually delete the object from the memory store. I will follow up with this, but I chose the current solution as a short term because we should merge this by 2.6.3 (which we try to branch cut by Sun)

## Related issue number

Closes https://github.com/ray-project/ray/issues/38089

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
Feels like there are cpp unit tests missing here to verify that the ref counting works as expected

**Comment by edoakes** [comment]
@rkooo567 did you re-run the Serve repro to verify it's fixed? I'll kick off a long run on workspaces using these wheels too just to be sure.

**Comment by edoakes** [comment]
Looks good

Screen Shot 2023-08-06 at 2 15 38 PM

**Comment by rkooo567** [comment]
> Feels like there are cpp unit tests missing here to verify that the ref counting works as expected

Good catch... Adding it now. 

Btw, is it possible to add that long-running test as a regular long running test or some sort of release tests?

**Comment by rkooo567** [comment]
Unit tests are added

**Review by edoakes — APPROVED** [review]

**Review by scv119 — APPROVED** [review]

**Pull request merged**
