### PR TITLE
[requirements] Install with compiled requirements as constraints [build_base]

### PR DESCRIPTION
**Pull request by krfricke**
Following up from #36808, this PR now uses the compiled constraints file in the installation of the dependencies in CI and in the ray-ml docker images. In result, both environments will share the same versions of (sub)dependencies.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
Do we need to pick this for 2.6.0? Would it potentially break anything?

**Review by aslonnie — COMMENTED** [review]
leaving this to @can-anyscale to make the call.

seems to have conflicts?

**Comment by can-anyscale** [comment]
We probably don't need to pick this anymore?

**Comment by krfricke** [comment]
Yes, it was too much effort to retrofit this to 2.6. We made some progress in 2.6 and this will be included in 2.7, so this should be fine.

**Pull request closed without merging**
