### PR TITLE
release gil in global state accessor

### PR DESCRIPTION
**Pull request by kisuke95**
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
Can you try running `ray microbenchmark` and compare the result from the branch that doesn't have this?

**Comment by kisuke95** [comment]
> Can you try running `ray microbenchmark` and compare the result from the branch that doesn't have this?

with `with nogil`, result is:

**Comment by kisuke95** [comment]
@rkooo567 I already run `ray microbenchmark` several times, but there is no obvious difference between them.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Just out of curiosity. If there’s no speedup, what’s the motivation for this change?

**Comment by rkooo567** [comment]
Cuz I know gil can speedup (because there’s no gil!) or slow down (because acquiring / releasing gil takes more time than actual operations).

**Comment by kisuke95** [comment]
Because there are some I/O operation in thest c++ function, it we don't release GIL, it may block other thread which call the same function. But i'm not sure if this situation exists.

**Comment by rkooo567** [comment]
I see that makes sense! Feel free to merge the change :)

**Review by raulchen — APPROVED** [review]

**Pull request merged**
