### PR TITLE
Add Flower to the ray library

### LINKED ISSUE #21651: Adding new Framework to Ray library
Hey Ray team,

I'm working on the open source project Flower that enables federated learning for different ML frameworks such as scikit, PyTorch (Lightning), and many more. In order to perform multi-machine simulations of Federated Learning, we have used Ray to spawn virtual clients and making different research settings in the field of federated learning possible.
Our open-source repository contains already example available here: https://github.com/adap/flower/blob/main/examples/simulation_pytorch

We wanted to reach out to ask whether you'd be interested in adding Flower to your ecosystem at the documentation ray-libraries.html and/or adding/linking our example to your documentation as well? If so, we could open a PR.

We would also be interested in writing a Blog Post about this example and promoting it together with Ray. Is this something you would be interested in?

Many regards,
Maria

### PR DESCRIPTION
**Pull request by mariaboerner1987**
## Why are these changes needed?

Add Flower to the documentation in ray-libraries

## Related issue number

One out of two PRs to close https://github.com/ray-project/ray/issues/21651

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by maxpumperla** [comment]
@mariaboerner1987 thanks for this PR! It seems like the `flower` reference is not defined. 

```
sphinx.errors.SphinxWarning: /ray/doc/source/ray-overview/ray-libraries.rst:50:Undefined substitution referenced: "flower".
--
  |  
  | Warning, treated as error:
  | /ray/doc/source/ray-overview/ray-libraries.rst:50:Undefined substitution referenced: "flower".
  | 🚨 Error: The command exited with status 1
```

p.s.: Adap sitzt auch in Hamburg?

**Comment by mariaboerner1987** [comment]
> @mariaboerner1987 thanks for this PR! It seems like the `flower` reference is not defined.
> 
> ```
> sphinx.errors.SphinxWarning: /ray/doc/source/ray-overview/ray-libraries.rst:50:Undefined substitution referenced: "flower".
> --
>   |  
>   | Warning, treated as error:
>   | /ray/doc/source/ray-overview/ray-libraries.rst:50:Undefined substitution referenced: "flower".
>   | 🚨 Error: The command exited with status 1
> ```
> 
> p.s.: Adap sitzt auch in Hamburg?

All right. I will try to fix this!

p.s.: Ja, am Mühlenkamp! :-D

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by mariaboerner1987** [comment]
> ## ‼️ ACTION REQUIRED ‼️
> We've switched our code formatter from YAPF to Black (see #21311).
> 
> To prevent issues with merging your code, here's what you'll need to do:
> 
> 1. Install Black
> 
> ```
> pip install -I black==21.12b0
> ```
> 
> 2. Format changed files with Black
> 
> ```
> curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
> chmod +x ./format-changed.sh
> ./format-changed.sh
> rm format-changed.sh
> ```
> 
> 3. Commit your changes.
> 
> ```
> git add --all
> git commit -m "Format Python code with Black"
> ```
> 
> 4. Merge master into your branch.
> 
> ```
> git pull upstream master
> ```
> 
> 5. Resolve merge conflicts (if necessary).
> 
> After running these steps, you'll have the updated `format.sh`.

I have done all the steps and pushed the update again. Is there anything else I have to do.

**Comment by mariaboerner1987** [comment]
@maxpumperla do I need to make any additional task to make the CI happy?

**Comment by maxpumperla** [comment]
@mariaboerner1987 the linter still doesn't seem to be happy. Could you please run `scripts/format.sh`?

**Comment by mariaboerner1987** [comment]
@maxpumperla the pipeline passed now.

**Comment by bveeramani** [comment]
@maxpumperla can we merge this in?

**Pull request closed without merging**
