### PR TITLE
[minor] Perf optimizations for direct actor task submission

### PR DESCRIPTION
**Pull request by ericl**
Perf optimizations split out from https://github.com/ericl/ray/pull/15

- Use absl::flat_hash containers in core worker (~2x faster)
- Save parsing resources map for actor calls
- Replace getattribute with precomputed method table
- Support returning raw bytes
- Skip signature parsing if no args

### CODE REVIEW

**Comment by ericl** [comment]
raise RayTestTimeoutException(
>           "Timed out while waiting for process to exit.")
E       RayTestTimeoutException: Timed out while waiting for process to exit.
python/ray/tests/utils.py:45: RayTestTimeoutException
---------------------------- Captured stderr setup -----------------------------
2019-11-01 02:29:13,186	INFO resource_spec.py:216 -- Starting Ray with 1.61 GiB memory available for workers and up to 0.15 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
----------------------------- Captured stderr call -----------------------------
Exception RuntimeError: RuntimeError('Lost reference to actor',) in <bound method ActorHandle.__del__ of Actor(Actor, a7db0aa301000000)> ignored
 ray/tests/test_actor.py::test_actor_deletion ⨯                    4% ▌

**Comment by zhijunfu** [comment]
Just curious are the performance differences measurable in the perf results?

**Comment by ericl** [comment]
@zhijunfu it's not measurable in the current single-threaded core worker, but makes a big difference for https://github.com/ericl/ray/pull/15

**Review by pcmoritz — APPROVED** [review]
LGTM :)

**Comment by zhijunfu** [comment]
> @zhijunfu it's not measurable in the current single-threaded core worker, but makes a big difference for [ericl#15](https://github.com/ericl/ray/pull/15)

Thanks, good to know:)

**Pull request merged**
