### PR TITLE
Fix deprecated tf_ops import

### PR DESCRIPTION
**Pull request by carlogrisetti**

### CODE REVIEW

**Comment by carlogrisetti** [comment]
@simon-mo seein you active so pinging you :)
Can an adult help me understand why the test is timing out? Is this related to this PR? (doesn't seem so to me...)

**Comment by simon-mo** [comment]
Thanks @carlogrisetti I assigned our rllib folks.

**Comment by carlogrisetti** [comment]
Thanks! I have yet to understand who's who :)

**Review by sven1977 — APPROVED** [review]
Thanks for the fix @carlogrisetti ! :)

**Comment by sven1977** [comment]
Hey @carlogrisetti , we are working on making PR assignments to the right (Ray) people more accessible. In the meantime, it could help tagging your PRs with the `[RLlib]` prefix in its description. That way it's easier for me to find it and assign myself.

**Comment by carlogrisetti** [comment]
Ok, wilco :)

**Pull request merged**
