### PR TITLE
[Train][Docs] Test code snippets in `session.py`

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

Many of the code snippets in `session.py` aren't tested, and some of them are broken. This PR fixes and tests the examples.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by matthewdeng — APPROVED** [review]
Looks great! Let me know when tests pass?

**Comment by woshiyyya** [comment]
LGTM. Seems that the tests timed out. Maybe we can reduce the number of training steps?

**Comment by bveeramani** [comment]
> LGTM. Seems that the tests timed out. Can we reduce the number of training steps?

Time out is because one of the tests requests GPUs but is run on a CPU-only node. Update the BUILD file.

**Review by woshiyyya — APPROVED** [review]
Great work. Let's wait for the test to pass. Thank you Balaji!

**Pull request merged**
