### PR TITLE
[core] Fix session key check

### LINKED ISSUE #40412: [core] Silent failure when retrieving session key from Redis
ray.init may fail to retrieve a session key from Redis but continue executing, in which case it will generate a new session key, leading to two inconsistent keys (in Redis and passed in from the frontend).

### PR DESCRIPTION
**Pull request by vitsai**
Assert that they are equal, not the opposite.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by fishbone — APPROVED** [review]
Is it easy to add a simple test?

**Comment by vitsai** [comment]
`test_gcs_ha_e2e.py` already checks this behavior -- the reason it passed before (which is how the bug wasn't caught) is because the bytes object is not equal to the string object even when they encode the same characters.

**Comment by vitsai** [comment]
The tune multinode and kuberay autoscaler failures are the same as on `go/flaky`

**Comment by iycheng** [comment]
Got it. Sounds good!

**Comment by iycheng** [comment]
@vitsai  I think we need to cherry-pick this PR.

**Pull request merged**
