### PR TITLE
Revert "GCS server task info handler use storage instead of redis acc…

### PR DESCRIPTION
**Pull request by ericl**
…essor (#8531)"

This reverts commit 9823e1531187f908fad34861a4c3e02654a6a300.

## Why are these changes needed?

[ASAN build seems to be broken since that PR; testing it out]

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
LGTM assuming it fixes the issue

**Comment by ericl** [comment]
Bizarrely, this does fix the ASAN build. I'll merge it for now to unbreak master. @ffbin do you have any idea why that PR would cause compilation failures in asan?

**Comment by ericl** [comment]
Nevermind, master is still broken: https://travis-ci.com/github/ray-project/ray/jobs/339142307

```
(02:41:13) ERROR: /home/travis/build/ray-project/ray/BUILD.bazel:475:1: C++ compilation of rule '//:core_worker_lib' failed (Exit 1)
==29317==ERROR: AddressSanitizer failed to allocate 0x1a8000 (1736704) bytes of LargeMmapAllocator (errno: 12)
ERROR: Failed to mmap
```

@edoakes do we use a different travis config in master compared to PR builders?

**Comment by edoakes** [comment]
I'm not sure - @mehrdadn or @simon-mo should know.

**Comment by mehrdadn** [comment]
I believe caching is different, but it should only affect uploading? I can't think of anything else...

**Comment by mehrdadn** [comment]
I can look into this though, let me know if you'd like me to.

**Comment by ericl** [comment]
I suspect it's just using too much memory, I'll try turning down the
parallelism on asan builds. Locally I've seen it use a lot more memory than
normal.

**Pull request merged**
