### PR TITLE
[Train] Set `torch.distributed` env vars

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

This PR allows for automatic setting of `torch.distributed` environment variables (https://pytorch.org/docs/stable/elastic/run.html#environment-variables) in Torch training for compatibility with third-party libraries. Additionally, `ACCELERATE_TORCH_DEVICE` env var is also set for better Hugging Face Accelerate compatibility. This necessitated making `get_device` fully detached from `_TorchAccelerator`.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
Thanks @Yard1! Can you explain a bit more on why the changes to session & TorchAccelerator are needed?

**Comment by Yard1** [comment]
@amogkam We need to obtain the correct device for Accelerate to use. Without any changes, calling `train.torch.get_device()` will set the `TorchAccelerator` on the session and therefore make it impossible for the user to set their own accelerator later.

The device to use does not depend on the state of the `TorchAccelerator`, therefore I think it is fine to make it a class method and not require the `TorchAccelerator` to be instantiated in the first place.

**Comment by amogkam** [comment]
> Without any changes, calling train.torch.get_device() will set the TorchAccelerator on the session and therefore make it impossible for the user to set their own accelerator later.

What accelerator does the user need to set later?

**Comment by Yard1** [comment]
Moved `get_device` out of `_TorchAccelerator`

**Review by amogkam — APPROVED** [review]

**Pull request merged**
