### PR TITLE
Integrate DagsHub Logger

### PR DESCRIPTION
**Pull request by timho102003**
## Why are these changes needed?
Integrate DagsHub logger with Ray
Users can now leverage DagsHub's capabilities to track their experiments, including metrics, parameters, and artifacts, by simply changing the log configuration.

## Checks
- [x]  I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by deanp70** [comment]
Is it possible to get an update on whether the test failing are a result of the PR or an internal problem that's unrelated?

**Comment by deanp70** [comment]
Is it possible to get an update on whether the test failing are a result of the PR or an internal problem that's unrelated?

**Comment by nirbarazida** [comment]
Hey,
We're still waiting for feedback whether the test failure is a result of the PR or an internal problem that's unrelated.

**Comment by nirbarazida** [comment]
Hey @raulchen , @scottjlee , @ericl , @scv119 , @amogkam , @bveeramani 

We'd love to get your input on this PR and get feedback on whether the test failure is a result of the PR or an internal problem that's unrelated.

Thanks,
Nir

**Comment by bveeramani** [comment]
Hey @nirbarazida, sorry for the delayed response.

Looking at https://flakey-tests.ray.io/, it seems like the failures are all failing or flaky on master.

@matthewdeng could you take a look and confirm?

**Comment by matthewdeng** [comment]
Hey sorry for the late reply on this. The test failures should be unrelated.

We're in the process of revamping some of our logger right now, would it be possible for me to set up some time to sync with you on this change, say next week?

**Comment by nirbarazida** [comment]
Hey @matthewdeng,

Thanks for reaching out! The engineer who is leading this integration is away for this week. Can we schedule the call for next week, Wednesday, September 4th at 9 AM EST?

**Comment by nirbarazida** [comment]
@matthewdeng I just sent you a connection request on LinkedIn to set up the meeting.

**Comment by bveeramani** [comment]
Closing as stale

**Pull request closed without merging**
