### PR TITLE
[core][metric] Move periodic metric recording to be controlled by metric report interval and fix test_exit_observability

### LINKED ISSUE #29715: [CI] `linux://python/ray/tests:test_exit_observability` is failing/flaky on master.
- 98da294f0b8fbf0ab9d94ebd552c4d78b4d3aaf8 FLAKY [Buildkite :python: (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841512-f482-425f-81b2-2f7b8d323bbd)
- 98da294f0b8fbf0ab9d94ebd552c4d78b4d3aaf8 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841512-f490-4bd1-b3ec-5f2549b8ce18)
- 182744bbd151c166b8028355eae12a5da63fb3cc FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/736#018413b1-1935-423a-b107-9fd5e67451e3)
- 37de814a8598e0ea3dea23d5ae0caf9df54fa0e6 FAILED [Buildkite :python: (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/734#01841305-cbc9-415e-9eb2-3b99f5fa691f)
- 824c79011e32fa4a0e9c409ef55a62a05fb70da8 FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/732#018412a4-e036-4706-a744-4a408ee04882)
- 7a50e23478a32687e87528b2fbdae3ce953ae579 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/731#0184129c-95c2-4cf8-b28e-2081d9ae42e6)
- 161567dbd93f94bef941c17779d3880f310a0373 FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/730#01841280-1286-4208-8705-0bf81fe1bb31)
- 161567dbd93f94bef941c17779d3880f310a0373 FAILED [Buildkite :python: (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/730#01841280-1278-421e-8cf1-bea6b8d04b14)
- 160c3cfa8959d133088bc56ecf9443351c17a558 FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/689#01840bdc-aea8-4e5d-8218-6f9ff905714a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_exit_observability-END
....

### LINKED ISSUE #29722: [CI] `windows://python/ray/tests:test_task_metrics` is failing/flaky on master.
- 98da294f0b8fbf0ab9d94ebd552c4d78b4d3aaf8 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841506-822f-4872-aca4-0de1d02b98b6)
- 182744bbd151c166b8028355eae12a5da63fb3cc FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/736#018413a3-6cf1-44f0-9c86-c7fd7c73565a)
- 37de814a8598e0ea3dea23d5ae0caf9df54fa0e6 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/734#018412f7-94e7-4d8d-9e0f-d8355a2989e9)
- 875193ca8d4720a7215aad2a275851f5157674c2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/733#018412b7-3338-4110-bdcb-1bebb871b9cb)
- 824c79011e32fa4a0e9c409ef55a62a05fb70da8 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/732#01841297-b3ee-4fc1-b5fe-3ba2bcbc8fb8)
- 7a50e23478a32687e87528b2fbdae3ce953ae579 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/731#01841291-36cc-4257-ae94-98127c946498)
- 161567dbd93f94bef941c17779d3880f310a0373 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/730#01841271-225e-4e8e-aa76-658929b0acfc)
- 97e120d3835f239cc3fd4886996faf4d9bff46e4 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/714#01841007-8983-4803-ae8b-765ee1ea29d3)
- 813e1a857d5dfc060b3b6cb846157fdca425e6b0 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/710#01840f90-125e-4e02-88e6-18103336e595)
- 3562cb4be86ddb3ad9bbe2942cdf029ca1eb6497 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/694#01840c23-2dba-473f-b677-0ab28651792a)
- 3f0c294223390b2184c523bef1616c7ce328f328 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/672#0183ffd1-2ff7-442c-b3e3-1ddb467f093a)
- c0284c071dc16b3481d8488a3fe3a9311b8ddd60 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/662#0183fbd0-2fa6-47f9-8ef7-f93642a0a14b)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_task_metrics-END
....

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

This PR does a couple of things: 
1. Fix the test_exit_observability test logic 
2. Couple task metric record with `metric_report_interverval_ms` rather than heart beat interval in CoreWorker 
3. Skip metric test on windows. 

## Related issue number

Closes #29715
Closes #29722

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by cadedaniel** [comment]
Let's make sure https://github.com/ray-project/ray/issues/29715 passes as well, I think it's caused by the same PR

Screen Shot 2022-10-26 at 12 11 53 PM

**Review by rkooo567 — APPROVED** [review]

**Comment by rickyyx** [comment]
So the root cause for why #29678 introduces regression to `test_exit_observability` might deserve some more attention or follow ups: 
- We are handling worker forced kill and normal worker exit in two independent execution loops w/o synchronization. 
  - [Forced kill](https://github.com/ray-project/ray/blob/b412a46ccc4cfdb8898c74ff286b71fbe922be0f/src/ray/core_worker/core_worker.cc#L3149) at the grpc service (grpc_service_) 
  - [Normal exit](https://github.com/ray-project/ray/blob/b412a46ccc4cfdb8898c74ff286b71fbe922be0f/src/ray/core_worker/core_worker.cc#L2414-L2416) at `task_execution_service_`
- Since we are now also exporting metrics while worker exiting in #29678, the race becomes more visible in runs, leading to more flaky test. 


Do we need to consider better synchronization between the multiple event loops core worker runs? Or if there's any existing contract? 

cc @ericl @scv119 @rkooo567

**Comment by rickyyx** [comment]
TODO: fix the lint. Will fix, but right now letting CI to run more tests.

**Comment by rickyyx** [comment]
> So the root cause for why #29678 introduces regression to `test_exit_observability` might deserve some more attention or follow ups:
> 
> * We are handling worker forced kill and normal worker exit in two independent execution loops w/o synchronization.
>   
>   * [Forced kill](https://github.com/ray-project/ray/blob/b412a46ccc4cfdb8898c74ff286b71fbe922be0f/src/ray/core_worker/core_worker.cc#L3149) at the grpc service (grpc_service_)
>   * [Normal exit](https://github.com/ray-project/ray/blob/b412a46ccc4cfdb8898c74ff286b71fbe922be0f/src/ray/core_worker/core_worker.cc#L2414-L2416) at `task_execution_service_`
> * Since we are now also exporting metrics while worker exiting in [Optimize task metrics to avoid synchronous recording overhead. #29678](https://github.com/ray-project/ray/pull/29678), the race becomes more visible in runs, leading to more flaky test.
> 
> Do we need to consider better synchronization between the multiple event loops core worker runs? Or if there's any existing contract?
> 
> cc @ericl @scv119 @rkooo567


Synced with @rkooo567 offline. The two event loops now are rather independent - there's no urgent issues to fix.  The root cause was more of a bug in the original test logic.

**Comment by ericl** [comment]
Hmm the windows test seems to be failing still. I think it's timing out (on Linux it already takes 250s, and the limit is 300s).

**Comment by rickyyx** [comment]
Hmm yeah - maybe I should try splitting it? Or skipping on windows?

**Comment by ericl** [comment]
Why don't we just skip it on windows then? I don't think there is much reason to also test this on windows, as the metrics code should be platform independent.

**Comment by rickyyx** [comment]
Skipping the last test (potentially we skip more) - but this should fix the timeout.

**Pull request merged**
