### PR TITLE
Fix a bug from many drivers.

### LINKED ISSUE #22238: [Bug] many_drivers failed
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

many_drivers test is failing with the following error messages; 

```
(pid=1042) [2022-02-08 10:16:54,601 E 1042 1248] core_worker_process.cc:347: The global worker has already been shutdown. This happens when the language frontend accesses the Ray's worker after it is shutdown. The process will exit
Traceback (most recent call last):
  File "workloads/many_drivers.py", line 124, in <module>
    ray.get(ready_id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1934, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(UnicodeDecodeError): ray::run_driver() (pid=1044, ip=172.31.86.142)
  File "workloads/many_drivers.py", line 92, in run_driver
    output = run_string_as_driver(driver_script)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 421: ordinal not in range(128)
```

I am taking a look at it now.

### Versions / Dependencies

Master

### Reproduction script

N/A

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

After this PR (https://github.com/ray-project/ray/pull/22156), for some reasons the driver script has some string that cannot be encoded with ascii. It seems like using utf-8 solves the problem. 

## Related issue number

Closes https://github.com/ray-project/ray/issues/22238

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Do you know why utf-8 fix the issue?

**Review by ericl — APPROVED** [review]
Should we just default to utf-8 always?

**Comment by rkooo567** [comment]
Hmm actually a good question. Let me try changing the default and see if it breaks any test.

**Comment by rkooo567** [comment]
I will merge it first since there's the fire (broken test). Will create one more PR

**Pull request merged**
