### PR TITLE
Fixes bug #17424.

### LINKED ISSUE #17424: Can't resume from checkpoint.
https://github.com/ray-project/ray/blob/47cd0758299b430483ae41fd70e809d0330978a9/python/ray/tune/examples/mnist_pytorch_lightning.py#L186

When trying to resume from a interrupted trial, one gets the following attribute error:

> 2021-07-29 02:01:04,447	ERROR trial_runner.py:773 -- Trial train_mnist_tune_checkpoint_8eef9_00000: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 729, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1564, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=991, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 534, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 178, in train_buffered
    result = self.train()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 237, in train
    result = self.step()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 513, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=991, ip=172.28.0.2)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/utils/trainable.py", line 339, in inner
    trainable(config, **fn_kwargs)
  File "<ipython-input-3-83ee6f83de0d>", line 185, in train_mnist_tune_checkpoint
AttributeError: can't set attribute

To reproduce, 
1. comment out line 289, 
2. start an experiment (on Colab),
3. interrupt runtime mid-experiment,
3. add 'resume='PROMPT'' option in line 270,
4. rerun, type 'y' when prompted.

I did some debugging: the problem seems to be that the 'current_epoch' attribute of a trainer object can't be assigned a value explicitly. I can say that this issue wasn't present even 5 days back. I could happily resume from checkpoints of incomplete experiments. Now I have to comment out line 186 before rerunning the experiment. The experiment does resume, but there is an expected mismatch between the 'training_iteration' in the summary table and the epoch number on the progress bar.

Can someone dig out how to reconcile the two going forward?

### PR DESCRIPTION
**Pull request by souravraha**
## Why are these changes needed?
This change is a more straightforward method for loading checkpoints. The current code throws up an error as the 'current_epoch' attribute of trainer doesn't accept explicit assignments.

## Related issue number
This change allows one to escape issue https://github.com/ray-project/ray/issues/17424.

edit @sumanthratna: closes #17424 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Thanks @souravraha! Can you run the linter script in `scripts/format.sh`? You might need to `pip install -r python/requirements_linters.txt` first

**Comment by souravraha** [comment]
> 
> 
> Thanks @souravraha! Can you run the linter script in `scripts/format.sh`? You might need to `pip install -r python/requirements_linters.txt` first

I tried a bunch of steps, and I am sure I am doing it incorrectly.  Can I have more detailed instructions? Sorry, novice here.

**Comment by juliusfrost** [comment]
> > Thanks @souravraha! Can you run the linter script in `scripts/format.sh`? You might need to `pip install -r python/requirements_linters.txt` first
> 
> I tried a bunch of steps, and I am sure I am doing it incorrectly. Can I have more detailed instructions? Sorry, novice here.

Here's the documentation on linting and formatting:
https://docs.ray.io/en/master/getting-involved.html?highlight=format.sh#lint-and-formatting

**Review by sumanthratna — APPROVED** [review]

**Comment by krfricke** [comment]
Ah, that file is excluded from linting, so there was no difference.

I made some minor adjustments to the formatting so it matches the style we usually use in Ray.

**Review by krfricke — APPROVED** [review]

**Pull request merged**
