### PR TITLE
Polish the Dashboard new IA part 2

### PR DESCRIPTION
**Pull request by alanwguo**
- Adds back the metrics page
- Adds button to visit new dashboard and to go back
- Adds buttons for leaving feedback and viewing docs
- Add color to status badges of tasks and placement groups table
- Add alert when grafana is not running
- Fix copy button icon
- Separate metrics page into sections (both new IA and old IA)

Screenshot 2023-01-25 at 4 56 23 PM
Screenshot 2023-01-25 at 4 56 36 PM
Screenshot 2023-01-25 at 4 57 38 PM
Screenshot 2023-01-25 at 4 57 50 PM
Screenshot 2023-01-25 at 6 14 07 PM

Signed-off-by: Alan Guo <aguo@anyscale.com>

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scottsun94** [comment]
1. Bottom alignment of the filters of the events. It seems that the last 2 input boxes miss a parent div wrapper which lead to the misalignment.
Screen Shot 2023-01-25 at 11 08 22 PM
Screen Shot 2023-01-25 at 11 08 04 PM

2. Small visual adjustments:
- Shall we change the text to "Back to the old UI" which is consistent with "Try the new UI"?
- css of the text
  - the font-weight: 500
  - letter-spacing: 0.25px
  - the spacing between the button and the icon should be 24px. Currently, it's 20.
Screen Shot 2023-01-25 at 11 22 34 PM

3. When grafana is enabled and prometheus is not enabled, shall we also have a warning?
Screen Shot 2023-01-25 at 5 22 07 PM

4. The status pill in the metadata box also needs coloring.
Screen Shot 2023-01-25 at 11 32 11 PM

5. The sticky bar for "View in grafana" and duration picker seems to take a lot of vertical space. Maybe we don't have to make them sticky at the top for now?
Screen Shot 2023-01-25 at 11 44 28 PM

(Will add the rest of the comments tomorrow...)

**Comment by rkooo567** [comment]
Do we also plan to design individual components differently? I remember mock has different designs for individual components.

**Comment by scottsun94** [comment]
> Do we also plan to design individual components differently? I remember mock has different designs for individual components.

IMO, we probably don't have time for it in 2.3 and we should spend more time doing the polish and hardening work (both UI and functionality) in 2.4.

**Comment by alanwguo** [comment]
Addressed all the comments. Need to verify tests are passing then this should be ready to merge

**Comment by scottsun94** [comment]
Thanks for the fixes! Only see two small visual nits on the "Try new UI" button.
1. The button dimension could be improved:
- The 4px padding I gave is a bit tight. Could we increase the left and right padding to 8px?
- Could we let the width fit the content (I used `width: fit-content)`
Screen Shot 2023-01-26 at 8 44 26 PM

2. when hovering over the button, the blue background conflicts with the text color. I originally thought it could just be changed to look the same as other items when hovering (white text) but it might be more complicated.
- could we just not apply the blue background? (I just remove the background and it seems to use the default gray background which looks pretty good)
Screen Shot 2023-01-26 at 8 32 32 PM
Screen Shot 2023-01-26 at 8 49 28 PM

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Let;s do @scottsun94 's follow up in a follow up PR. I think we should also close the collapsible section for task/actor/pg table by default from the job detail page

**Pull request merged**
