### PR TITLE
[Do NOT SUBMIT] Revert "[runtime env] runtime env inheritance refactor (#22244)"

### PR DESCRIPTION
**Pull request by xwjiang2010**
This reverts commit 5783cdb25464f2fca02da15a6426a7ceb121edcd.

## Why are these changes needed?

I was suspecting the runtime env PR broke our train_torch_linear_test.py in nightly release: training just hangs forever.
The timing matches (1st failure shows up on Monday 10am run). So wanted to see if reverting it would fix the failing test and it did: https://buildkite.com/ray-project/periodic-ci/builds/2890#05a9ce04-e2a9-4b4e-8b2f-25ba63f3053d
See more context here: https://github.com/ray-project/ray/issues/22595

Do you guys know what may be causing it? I will prepare a proper revert PR tmr (or if you guys prefer to do it, go ahead!). This one is just a quick try and didn't do the merge conflict entirely right.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @SongGuyang 

Also there's the conflictc

**Comment by rkooo567** [comment]
@xwjiang2010 Can you also write why we need to revert it?

**Review by rkooo567 — APPROVED** [review]

**Comment by SongGuyang** [comment]
@rkooo567 I don't think we can approve this PR before the author adds the description of the reason.

**Comment by xwjiang2010** [comment]
You guys beat me by speed :) 

I was suspecting the runtime env PR broke our train_torch_linear_test.py in nightly release: training just hangs forever. 
The timing matches (1st failure shows up on Monday 10am run). So wanted to see if reverting it would fix the failing test and it did: https://buildkite.com/ray-project/periodic-ci/builds/2890#05a9ce04-e2a9-4b4e-8b2f-25ba63f3053d
See more context here: https://github.com/ray-project/ray/issues/22595

Do you guys know what may be causing it? I will prepare a proper revert PR tmr (or if you guys prefer to do it, go ahead!). This one is just a quick try and didn't do the merge conflict entirely right.

**Comment by rkooo567** [comment]
Oh yeah. Sorry about that. I thought it was a typical test failed in the master cases. I just saw the [tryout] from the title

**Review by rkooo567 — CHANGES_REQUESTED** [review]
Revert approval until description updated

**Comment by SongGuyang** [comment]
@xwjiang2010 Thanks for your description. I saw that `train_torch_linear_test.py` has set a job level runtime_env. https://github.com/ray-project/ray/commit/5783cdb25464f2fca02da15a6426a7ceb121edcd this commit has changed the behavior of runtime env inheritance. Can you check if ray train set a task/actor level runtime_env internally?

**Comment by SongGuyang** [comment]
By the way, can we add a test case for this? I didn't find this issue in the CI of my PR.

**Comment by xwjiang2010** [comment]
@SongGuyang Let's continue discussion on the linked bug: https://github.com/ray-project/ray/issues/22595

**Pull request closed without merging**
