### PR TITLE
Replace time.time() with timeit.default_timer()

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

This ensures use of a monotonic clock rather than a wall clock (which can change).

## Related issue number

#6304 ([comment](https://github.com/ray-project/ray/pull/6304#discussion_r351489801))

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by edoakes** [comment]
Given that we’re going to deprecate python 2 soon, can we actually just wait until then and then change these to `time.monotonic()`?

**Comment by mehrdadn** [comment]
I think we shouldn't :) here's why:

- (Personal/subjective) I dislike breaking compatibility when it's so trivial to avoid doing so; it just makes other's life harder.
- The availability of `time.monotonic` also seems to be questionable pre-Python 3.5 too.
- I'm not actually sure if there's any benefit (besides having a nicer name) to doing so.

But actually, those are nothing compared to the following:

- `time.monotonic` is, surprisingly, strictly worse. (!)

Regarding that point, it's because they're fundamentally not used for the same purpose. `timeit.default_timer` uses performance counters to measure time on a fine-grained level, rather than the cheap system clock (which is very coarse).

Compare these on Windows (and possibly other platforms):

    >>> (int(timeit.default_timer() * 1E7), int(time.monotonic() * 1E7), time.monotonic_ns() // 100)
    (4327258147, 551917500000, 551917500000)

- `time.monotonic` seems to be using the cheap method of just reading the system uptime counter from memory, which is updated at every thread time slice. (So its precision can be ~15ms, which is awful.)

- `timeit.default_timer` seems to be using a (more expensive—about 100ns to measure last time I checked—but still ridiculously cheap compared to Python) performance counter function that measures the program uptime.

There are also added benefits here, which are that (a) program uptime is independent of the system uptime (so closer to being deterministic and comparable across runs), and (b) program uptime is a small number that's meaningful on its own, but these are more minor than the precision issue I think.

But yeah, overall, I think we should be using `timeit.default_timer` everywhere regardless. :P

**Comment by ericl** [comment]
Looks like time.perf_counter() works the same as timeit. And yeah I'd also rather wait for python 2 deprecation too, it's less than a month away.

**Comment by mehrdadn** [comment]
Note that [RedHat will be supporting it until 2024](https://access.redhat.com/solutions/4455511), and I suspect plenty of users (especially business users, especially those with legacy code) will still be using it. It won't just suddenly die in a month.

**Comment by edoakes** [comment]
Looks like there are some tests failing - this is a bit scary because the high-level semantics of `time.time()` and `timeit.default_timer()` are different. We will only be supporting python 3.5+ in ~a month barring some unforeseen circumstances, so let's table this until then

**Comment by mehrdadn** [comment]
Ok

**Pull request closed without merging**
