### PR TITLE
[Dashboard] Don't show GPU columns if no GPU in cluster

### LINKED ISSUE #10295: [dashboard] Don't show GPU columns when no GPUs are detected
Should clean up the UI a bit for simple use cases.

### PR DESCRIPTION
**Pull request by mfitton**
## Why are these changes needed?
No need to show GPU information for a cluster that has no GPUs
Screen Shot 2020-10-29 at 11 26 44 AM
## Related issue number
Closes #10295

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@mfitton not related, but why is plasma store usage `N/A` in the screenshot? AFAICT that should never be the case.

**Review by edoakes — APPROVED** [review]
LGTM

**Comment by mfitton** [comment]
That's a good question @edoakes I'll look into that prior to merging this.

**Comment by mfitton** [comment]
@edoakes thanks for pointing out the issue. N/A was being rendered when 0 memory was used. The latest commit on the branch fixes it.

**Pull request merged**
