### PR TITLE
Downgrade six to 1.0.0

### PR DESCRIPTION
**Pull request by guoyuhong**
## What do these changes do?

Copy `ensure_str` to `utils.py` and downgrade six back to 1.0.0.
## Related issue number
https://github.com/ray-project/ray/issues/4169

### CODE REVIEW

**Comment by guoyuhong** [comment]
cc @raulchen

**Comment by raulchen** [comment]
I think we need to go back to `1.0.0`

**Comment by guoyuhong** [comment]
@raulchen Sorry, my mistake.

**Review by raulchen — APPROVED** [review]

**Review by robertnishihara — APPROVED** [review]
Thanks!

**Pull request merged**
