### PR TITLE
[Placement Group] Fix resource index assignment between with bundle index and without bundle index pg

### PR DESCRIPTION
**Pull request by clay4megtr**
## Why are these changes needed?

Currently, the placement group consists of two kinds of resources, one of them contains bundle index like `GPU_group_1_xxxx` and another doesn't contain the bundle index like `GPU_group_xxxx`.  we have made sure that the resource that contains the bundle index will keep order when assigning GPU ids to workers,  but besides this, we should also make sure that the `resource index` (like GPU ids) allocated to the resource request that `does not contain` the bundle index must be kept same with the `resource index` allocated to the resource request that `contains` the bundle index.

for instance: 
one node with 4 GPU, one placement group, four bundles, and every bundle has a GPU. so the generated eventually resource maybe like this: 
GPU_group_0_xxx:  {1, 0, 0, 0}
GPU_group_1_xxx:  {0, 1, 0, 0}
GPU_group_2_xxx:  {0, 0, 1, 0}
GPU_group_3_xxx:  {0, 0, 0, 1}

GPU_group_xxx: {1, 1, 1, 1}

then let's imagine these steps:
1. Create one actor that uses the first bundle, then `GPU_group_0_xxx:  {1, 0, 0, 0}` and  `GPU_group_xxx: {1, 0, 0, 0}` will be assigned to this actor(worker)
2. Create one actor that uses the **third** bundle, then `GPU_group_0_xxx:  {0, 0, 1, 0}` and  `GPU_group_xxx: {0, 1, 0, 0}` will be assigned to this actor(worker)
3. Create one actor that uses the **second** bundle, then `GPU_group_0_xxx:  {0, 1, 0, 0}` and  `GPU_group_xxx: {0, 0, 1, 0}` will be assigned to this actor(worker)
4. Create one actor that uses the **fourth** bundle, then `GPU_group_0_xxx:  {0, 0, 0, 1}` and  `GPU_group_xxx: {0, 0, 0, 1}` will be assigned to this actor(worker)

so, the GPU ids assigned to the second actor and the fourth actor are wrong. 

## Related issue number
 #16614 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by clay4444** [comment]
Note: this is nothing to do with that how the cluster started, and you can reproduce this bug by this code:
```
#!/usr/bin/python
# -*- coding:utf-8 -*-

import ray
from ray.util.placement_group import placement_group
import time

ray.init(num_gpus=4)

# Create placement group with 4 bundles using 1 GPU each.
num_gpus = 4
bundles = [{"GPU": 1, "CPU": 1} for _ in range(num_gpus)]
pg = placement_group(bundles)
ray.get(pg.ready())

# Actor using 1 GPU that has a method to print $CUDA_VISIBLE_DEVICES env variable
@ray.remote(num_gpus=1, num_cpus=1)
class Foo:

    def bar(self):
        import os
        print(f'CUDA_VISIBLE_DEVICES={os.environ.get("CUDA_VISIBLE_DEVICES", "<none>")}')

# Necessary to prevent SystemErrors to occur.
time.sleep(5)

# Create one actor per GPU and print the corresponding #CUDA_VISIBLE_DEVICES env variable.
actors = []
actors.append(Foo.options(placement_group=pg, placement_group_bundle_index=0).remote())
actors.append(Foo.options(placement_group=pg, placement_group_bundle_index=3).remote())
actors.append(Foo.options(placement_group=pg, placement_group_bundle_index=2).remote())
actors.append(Foo.options(placement_group=pg, placement_group_bundle_index=1).remote())

for ac in actors:
    ac.bar.remote()

# Necessary to prevent SystemErrors to occur.
time.sleep(5)

# Cleanup
del actors
ray.util.remove_placement_group(pg)
```

**Comment by clay4444** [comment]
@ericl sorry for the delay, it takes some time to debug.

**Comment by ericl** [comment]
Hmm trying to think of a simpler solution. What if we don't track the GPU index from the bundle resource, and only used the GPU indices from the bundleless one? Then they can't get out of sync.

**Comment by clay4444** [comment]
> Hmm trying to think of a simpler solution. What if we don't track the GPU index from the bundle resource, and only used the GPU indices from the bundleless one? Then they can't get out of sync.

That sounds like a great idea!

**Review by ericl — APPROVED** [review]

**Pull request merged**
