### PR TITLE
[CI] Skip Java Doc Test

### LINKED ISSUE #13742: [CI] Java CI UsingActorsDemo is flaky
The UsingActorsDemo fails from time to time, with varying errors. 
https://travis-ci.com/github/ray-project/ray/jobs/476534877
https://travis-ci.com/github/ray-project/ray/jobs/474922579

### PR DESCRIPTION
**Pull request by simon-mo**
Should help resolve https://github.com/ray-project/ray/issues/13742
but it's retreating the symptom not the cause

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Comment by simon-mo** [comment]
waiting for travis java to pass before merging

**Comment by wuisawesome** [comment]
Rip, test fails still. Maybe we should just skip it for now.

**Comment by simon-mo** [comment]
Yeah good point

**Comment by simon-mo** [comment]
as a reference:
https://travis-ci.com/github/ray-project/ray/jobs/477442269
```
+java -cp bazel-bin/java/all_tests_deploy.jar io.ray.docdemo.UsingActorsDemo
2021-01-27 19:58:33,101 INFO RunManager [main]: Ray runtime started @ 10.30.0.241.
Exception in thread "main" io.ray.runtime.exception.RayActorException: The actor e320f439b49c51573c28d4a901000000 died unexpectedly before finishing this task.
	at io.ray.runtime.object.ObjectSerializer.deserialize(ObjectSerializer.java:79)
	at io.ray.runtime.object.ObjectStore.get(ObjectStore.java:100)
	at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:95)
	at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.ray.runtime.RayRuntimeProxy.invoke(RayRuntimeProxy.java:44)
	at com.sun.proxy.$Proxy0.get(Unknown Source)
	at io.ray.api.Ray.get(Ray.java:77)
	at io.ray.runtime.object.ObjectRefImpl.get(ObjectRefImpl.java:45)
	at io.ray.docdemo.UsingActorsDemo.main(UsingActorsDemo.java:127)
+[[ 1 -lt 3 ]]
+(( n++ ))
+echo 'Command failed. Attempt 2/3:'
Command failed. Attempt 2/3:
+sleep 0
+true
+java -cp bazel-bin/java/all_tests_deploy.jar io.ray.docdemo.UsingActorsDemo
2021-01-27 19:58:39,716 INFO RunManager [main]: Ray runtime started @ 10.30.0.241.
Exception in thread "main" io.ray.runtime.exception.RayActorException: The actor e320f439b49c51573c28d4a901000000 died unexpectedly before finishing this task.
	at io.ray.runtime.object.ObjectSerializer.deserialize(ObjectSerializer.java:79)
	at io.ray.runtime.object.ObjectStore.get(ObjectStore.java:100)
	at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:95)
	at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.ray.runtime.RayRuntimeProxy.invoke(RayRuntimeProxy.java:44)
	at com.sun.proxy.$Proxy0.get(Unknown Source)
	at io.ray.api.Ray.get(Ray.java:77)
	at io.ray.runtime.object.ObjectRefImpl.get(ObjectRefImpl.java:45)
	at io.ray.docdemo.UsingActorsDemo.main(UsingActorsDemo.java:127)
+[[ 2 -lt 3 ]]
+(( n++ ))
+echo 'Command failed. Attempt 3/3:'
Command failed. Attempt 3/3:
+sleep 0
+true
+java -cp bazel-bin/java/all_tests_deploy.jar io.ray.docdemo.UsingActorsDemo
2021-01-27 19:58:46,184 INFO RunManager [main]: Ray runtime started @ 10.30.0.241.
Exception in thread "main" io.ray.runtime.exception.RayActorException: The actor e320f439b49c51573c28d4a901000000 died unexpectedly before finishing this task.
	at io.ray.runtime.object.ObjectSerializer.deserialize(ObjectSerializer.java:79)
	at io.ray.runtime.object.ObjectStore.get(ObjectStore.java:100)
	at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:95)
	at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.ray.runtime.RayRuntimeProxy.invoke(RayRuntimeProxy.java:44)
	at com.sun.proxy.$Proxy0.get(Unknown Source)
	at io.ray.api.Ray.get(Ray.java:77)
	at io.ray.runtime.object.ObjectRefImpl.get(ObjectRefImpl.java:45)
	at io.ray.docdemo.UsingActorsDemo.main(UsingActorsDemo.java:127)
+[[ 3 -lt 3 ]]
+fail 'The command has failed after 3 attempts.'
+echo 'The command has failed after 3 attempts.'
The command has failed after 3 attempts.
+exit 1
```

**Review by wuisawesome — APPROVED** [review]

**Pull request merged**
