### PR TITLE
[Data] Allow specifing both `num_cpus` and `num_gpus` for map APIs

### PR DESCRIPTION
**Pull request by scottjlee**
## Why are these changes needed?

Currently, we enforce that `num_cpus` and `num_gpus` cannot be both set for map operations. This PR enables the user to specify both of these parameters, as we believe that with the recent improvements to the scheduler, Ray Data should be able to smoothly support this scenario. However, we will warn users that this is still an experimental feature.

Updated doc example (updated for all map APIs):
Screenshot at Oct 11 19-00-23

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by bveeramani — APPROVED** [review]
OOC -- do you know why we can't set both?

**Comment by scottjlee** [comment]
> OOC -- do you know why we can't set both?

@bveeramani according to the docstring:

> Namely, args must explicitly specify either CPU or GPU, not both. Disallowing
    mixed resources avoids potential starvation and deadlock issues during scheduling,
    and should not be a serious limitation for users.

**Comment by raulchen** [comment]
actually, I'm not sure if this issue still exists with a lot of scheduler changes. 
And some users do want to set both.
I was gonna suggest that we should probably remove this limitation and see what happens.

**Comment by scottjlee** [comment]
@raulchen should we just go ahead and remove the restriction then? any other testing that i should do / concerns to be addressed?

**Comment by raulchen** [comment]
@scottjlee maybe let's update the error to a warning first

**Review by raulchen — APPROVED** [review]

**Pull request merged**
