### PR TITLE
Update PR10233

### PR DESCRIPTION
**Pull request by kisuke95**
## Why are these changes needed?
A better way to initialize `CoreWorkerOptions` #10233 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
I am a little concerned we can possibily forget to initialize some values, and that causes unexpected behavior. Do we have any checking logic inside coreWorker.Initiaize(options) -> this method?

**Comment by kisuke95** [comment]
> I am a little concerned we can possibily forget to initialize some values, and that causes unexpected behavior. Do we have any checking logic inside coreWorker.Initiaize(options) -> this method?

Looks like no check code in `Initiaize` function, and it maybe difficult to check whether some member are initialized or not. So i add a default constructor of `CoreWorkerOptions`

**Comment by kisuke95** [comment]
@rkooo567 There are some build error in master branch, which are caused by the wrong header file path. Can someone fixed them ?
`./streaming/src/test/run_streaming_queue_test.sh` command will faild because 
```
Use --sandbox_debug to see verbose messages from the sandbox
streaming/src/test/mock_actor.cc:11:25: fatal error: ring_buffer.h: No such file or directory
 #include "ring_buffer.h"
                         ^
```
in file `mock_actor.cc`, `#include "ring_buffer.h"` should be `#include "ring_buffer/ring_buffer.h"`

**Comment by rkooo567** [comment]
@kisuke95 Maybe we can just merge this PR and have another fix later?

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/10630

**Pull request merged**
