### PR TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'get_shape' when running with framework config tf2 or tfe

### PR DESCRIPTION
**Pull request by kk-55**
## Why are these changes needed?

See description in issue ray-project#15764

## Related issue number

ray-project#15764

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
Thanks! Can you run the linter script and push again?

`./scripts/format.sh`

**Comment by kk-55** [comment]
@krfricke Can I also run the linter script `format.sh` under Windows 10?

**Comment by krfricke** [comment]
Hey @kk-55, you should be able to do this with the bash subsystem! https://docs.microsoft.com/en-us/windows/wsl/install-win10

If this doesn't work for you, please ping me, I'm happy to run the script and push to your PR after doing so.

**Comment by kk-55** [comment]
@krfricke I've gotten the script to work. What to do next? Push and open a new PR?

**Comment by krfricke** [comment]
You can just push to your fork, it will update the PR automatically.

I noticed you pushed to `kk-55/master` - for the future, it is usually preferable to push to a branch on your fork instead of master, so that you can bring your fork's master in sync with origin/master easily.

**Comment by kk-55** [comment]
Thanks @krfricke! It's the first time I do something like this and I hope it's all fine now. Otherwise please let me know.

**Comment by krfricke** [comment]
This looks great - the linter passed. Thanks! I'll wait until the rest of the tests passed before approving and merging

**Comment by kk-55** [comment]
@krfricke Still some issues?

**Review by krfricke — APPROVED** [review]
This is great, thanks!

**Pull request merged**
