### PR TITLE
Log an error instead of an info event when the local inference thread of PolicyClient

### LINKED ISSUE #30174: [RLlib] PolicyClient _LocalInferenceThread reports exceptions as info
### What happened + What you expected to happen

While experimenting the `_LocalInferenceThread` died because of an error in my code. This was however not clear as the exception was not logged because my log_level was `warning`. It's strange and unexpected that an exception flow does not result in at least a `warning`.

I would expect that `_LocalInferenceThread.run` would change the following line:
` except Exception as e:
            logger.info("Error: inference worker thread died!", e)`

To:

` except Exception as e:
            logger.error("Error: inference worker thread died!", e)`
or

` except Exception as e:
            logger.warning("Error: inference worker thread died!", e)`

The text inside the logging implies that it should be an error.

### Versions / Dependencies

Ray: 2.0.0
Python: 3.8.10
OS: Ubuntu 20.04.05

### Reproduction script

Should be clear from code

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by MattiasDC**
Log an error instead of an info event when the local inference thread of PolicyClient

## Why are these changes needed?
Better debug-ability when a crash occurs in the `PolicyClient` when using the `_LocalInferenceThread`. If one was running rllib with loglevel 'warning/error/critical', one would miss an exception/crash of the reason, unless the loglevel was 'info'.

## Related issue number
Closes #30174

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by MattiasDC** [comment]
Removing stale label, @sven1977 could you have a look?

**Comment by MattiasDC** [comment]
Hi @avnishn ,

Could you also give this review a look and merge if ok?

**Comment by MattiasDC** [comment]
Trying another maintainer @krfricke, could you do a review?

**Comment by MattiasDC** [comment]
Removing stale label..

**Review by krfricke — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
