### PR TITLE
[2.3.0] Cherry-pick: IA polish for demo (#32158)

### PR DESCRIPTION
**Pull request by alanwguo**
This PR is about cherry-picking #32158 into 2.3.0 branch

Add links between progress bar and task table and actor table Add links from task table to logs and to view stack trace fix horizontal scroll of table view Fix logs link going to old IA instead of new IA.
fix horizontal scroll of table view
Add beta label

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
Are there any release tests that this will impact? Can we run those before to derisk merging?f

**Comment by alanwguo** [comment]
> Are there any release tests that this will impact? Can we run those before to derisk merging?

How do I do this? Are there instructions? I thought the CI will run tests automatically

**Comment by rkooo567** [comment]
@cadedaniel we just need to run stress_test_state_api_scale

**Comment by rkooo567** [comment]
@alanwguo click the release-tests-pr button -> specify which release tests  you want to run -> type name: stress_test_state_api_scale (no space) in the test filter

**Comment by alanwguo** [comment]
Hm, release tests keep timing out with:
```
ray_release.exception.RayWheelsTimeoutError: Time out when waiting for URL to be available: https://ray-ci-artifact-pr-public.s3.amazonaws.com/8205fc7e92254b4ada828b24afdb7b5213ee0aaa/tmp/artifacts/.whl/ray-2.3.0rc0-cp37-cp37m-manylinux2014_x86_64.whl
```

**Comment by rkooo567** [comment]
Ah maybe there's an edge case that we are not building wheels when only frontend is changed... Imo, this is safe to merge @cadedaniel

**Comment by cadedaniel** [comment]
Cc @zhe-thoughts approval please

**Review by zhe-thoughts — APPROVED** [review]
Approving for cherry picking. But let's keep an eye on any release test failures for timely revert if needed. @cadedaniel

**Pull request merged**
