### PR TITLE
[Serve] Turn on HTTP logging and some cleanup

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
This PR turn on for HTTP access log, which is always on by default. User can turn it off by setting redirect to driver to false in Ray level.

Also removed few unused, outdated example files.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@simon-mo one unfortunate thing is that we can't turn off the `log_to_driver` behavior for only a single actor, it's "all or nothing."

Could you post some example logs of what this would look like for a few requests?

**Comment by edoakes** [comment]
Also, without log rotation for workers (cc @rkooo567), this may somewhat quickly fill up a disk under load.

**Comment by edoakes** [comment]
ping @simon-mo

**Comment by simon-mo** [comment]
This will gets folded into some Serve CUJ work

**Pull request closed without merging**
