### PR TITLE
[rllib] Allow command line args to override config file

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
Allows CLI to override a given configuration file.

TODO: 
 - [ ] Add tests

## Related issue number
Addresses #2983.

@visatish

### CODE REVIEW

**Comment by ericl** [comment]
After reading this, I'm less sure if we want to support it. Is it possible to just detect when any of those flags are passed with `-f` and throw an exception (or have argparse forbid it somehow?)

**Comment by richardliaw** [comment]
Yeah you can do mutually exclusive argument groups; would be good to get some user feedback though. @visatish

**Comment by visatish** [comment]
Hmm, I guess that works. The use case I saw for this was that you might want to change the result directory or a similar experiment-related hyper-parameter between runs and not want to have to keep on opening the config to change that. Or I guess even for changing small training hyper-parameters it would be convenient.

**Comment by richardliaw** [comment]
I'm going to close this for now; the mutually exclusive arguments can be addressed next time

**Pull request closed without merging**
