### PR TITLE
[Docker] Support multiple CUDA Versions

### LINKED ISSUE #17857: [docker] Ray GPU images use inconsistent CUDA version
Currently, Ray docker images do not explicitly tag the version of CUDA being used. This can lead to some pernicious bugs popping up where training suddenly becomes a lot slower, because the framework version is incompatible with the version of CUDA in the image.

This most recently happened to us on the Ludwig.ai team when #17806 downgraded from CUDA 11.2 to 11.0. Since we were using TensorFlow 2.6 (latest), we were no longer able to get GPU acceleration when a newer base image version was pulled.

Ideally, Ray would tag the generated Docker image with the version of CUDA so even if CUDA versions change, users of the image are not automatically upgraded / downgraded without warning. Something like `rayproject/ray:1.5.1-gpu-cuda112` or similar.

It would also be helpful if multiple versions of CUDA could be supported through CI. I understand that RLib needs to use TF 2.4, which uses CUDA 11.0, but most users would probably prefer to use the latest version of TensorFlow if they're not using RLib explicitly.

cc @richardliaw

### PR DESCRIPTION
**Pull request by amogkam**
Adds creation of Ray Docker images with multiple CUDA versions.

For all supported Python versions, we build Ray Docker images for CUDA 11.2, 11.1, 11.0, 10.2, and 10.1, as well as CPU. ray-ml docker images are still only built for CUDA 11.2, and are no longer built for CPU. 

- No device type specified will still refer to the CPU image
- "gpu" tag will refer to CUDA 11.2
- ray-ml Docker images will no longer be built for CPU
- No Python version specified will still refer to 3.7

After this PR, the build matrix will be:

ray: {3.6, 3.7, 3.8, 3.9} x {cpu, cu101, cu102, cu110, cu111, cu112}.
ray-ml: {3.6, 3.7, 3.8} x {cu112}

For both, "gpu" will refer to "cu112". No device tag will refer to "cpu". No Python version will refer to 3.7.

This PR also officially deprecates the "autoscaler" image.

Closes https://github.com/ray-project/ray/issues/17857

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ijrsvt — COMMENTED** [review]
Overall looks good--a few minor comments.

I was wondering what the delta in CI time is for this change?

**Comment by amogkam** [comment]
Yeah this will definitely increase CI time. I'll make sure this is working first and see how long the build times are, and then once it's working I'll split it up into multiple jobs.

**Review by richardliaw — COMMENTED** [review]
We also need to update the Ray docs for this I think

**Review by alanwguo — COMMENTED** [review]
@amogkam ,
As long this isn't cherry-picked into 1.8 branch, this won't impact the images built for the 1.8 release right? I'm concerned that the product side of 1.8 release will be impacted if we make this change now.

CC: @yifeif

**Review by richardliaw — COMMENTED** [review]
didn't read carefully. Can you add the exact matrix of docker versions that will be built after this PR?

Will leave it to @ijrsvt to review/approve

**Comment by amogkam** [comment]
@richardliaw the build matrix will be:

ray: {3.6, 3.7, 3.8, 3.9} x {cpu, cu101, cu102, cu110, cu111, cu112}. 
ray-ml: {3.6, 3.7, 3.8} x {cu112}

For both, "-gpu" will refer to "cu112". No device tag will refer to "cpu". No Python version will refer to 3.7.

**Review by ijrsvt — APPROVED** [review]
One final question, what should we do about the `ray-ml:nightly` image? 
Should we:
1. Delete the tag on DockerHub
2. Have it alias to`ray-ml:nightly-gpu` 

^^ We can do this in a fast-follow-on PR if you want!

**Pull request merged**
