### PR TITLE
[Core] Fix the race condition where grpc requests are handled while core worker not yet initialized [take 2]

### LINKED ISSUE #36829: [release-test] `placement_group_performance_test.aws` failed
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_gnvzua6c5abyhb4q4cabeyl4v6

```
[INFO 2023-06-25 23:58:59,221] anyscale_job_wrapper.py: 175  Starting process 2179.
+ python placement_group_tests/placement_group_performance_test.py
2023-06-25 23:58:59,720 INFO worker.py:1309 -- Using address 10.0.36.202:6379 set in the environment variable RAY_ADDRESS
2023-06-25 23:58:59,720 INFO worker.py:1427 -- Connecting to existing Ray cluster at address: 10.0.36.202:6379...
2023-06-25 23:58:59,768 INFO worker.py:1608 -- Connected to Ray cluster. View the dashboard at https://session-8rinvlkmlvbd2zljycszbb2vfq.i.anyscaleuserdata-staging.com 
*** SIGSEGV received at time=1687762739 on cpu 13 ***
PC: @     0x7f90056875d0  (unknown)  absl::lts_20220623::Mutex::Lock()
    @     0x7f9006448420       3376  (unknown)
    @     0x7f9004e48bba        192  ray::core::CoreWorker::HandleNumPendingTasks()
    @     0x7f9004df6bd5        144  ray::rpc::ServerCallImpl<>::HandleRequestImpl()
    @     0x7f900511f4f6         80  EventTracker::RecordExecution()
    @     0x7f90050bc79e         48  std::_Function_handler<>::_M_invoke()
    @     0x7f90050bccf6        112  boost::asio::detail::completion_handler<>::do_complete()
    @     0x7f9005670d7b        128  boost::asio::detail::scheduler::do_run_one()
    @     0x7f9005672849        288  boost::asio::detail::scheduler::run()
    @     0x7f9005672d02         96  boost::asio::io_context::run()
    @     0x7f9004e48e2d        240  ray::core::CoreWorker::RunIOService()
    @     0x7f90056a3800  (unknown)  execute_native_thread_routine
    @          0x1b96fb0   69494744  (unknown)
    @     0x7f9004d86cb0  (unknown)  (unknown)
    @ 0x900091cb71e90789  (unknown)  (unknown)
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361: *** SIGSEGV received at time=1687762739 on cpu 13 ***
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361: PC: @     0x7f90056875d0  (unknown)  absl::lts_20220623::Mutex::Lock()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9006448420       3376  (unknown)
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9004e48bba        192  ray::core::CoreWorker::HandleNumPendingTasks()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9004df6bd5        144  ray::rpc::ServerCallImpl<>::HandleRequestImpl()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f900511f4f6         80  EventTracker::RecordExecution()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f90050bc79e         48  std::_Function_handler<>::_M_invoke()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f90050bccf6        112  boost::asio::detail::completion_handler<>::do_complete()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9005670d7b        128  boost::asio::detail::scheduler::do_run_one()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9005672849        288  boost::asio::detail::scheduler::run()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9005672d02         96  boost::asio::io_context::run()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9004e48e2d        240  ray::core::CoreWorker::RunIOService()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f90056a3800  (unknown)  execute_native_thread_routine
[2023-06-25 23:58:59,846 E 2181 2228] logging.cc:361:     @          0x1b96fb0   69494744  (unknown)
[2023-06-25 23:58:59,850 E 2181 2228] logging.cc:361:     @     0x7f9004d86cb0  (unknown)  (unknown)
[2023-06-25 23:58:59,851 E 2181 2228] logging.cc:361:     @ 0x900091cb71e90789  (unknown)  (unknown)
Fatal Python error: Segmentation fault

/tmp/ray/session_2023-06-25_23-58-17_716277_50/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_placement_group_performance_test_aws_bamaxwxxhc__anyscale_pkg_a3ae00d02caf5513b000a94bcaf7edec/workload.sh: line 1:  2181 Segmentation fault      (core dumped) python placement_group_tests/placement_group_performance_test.py
Subprocess return code: 139
```

It segment.

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

The previous attempt (https://github.com/ray-project/ray/pull/37301) seems causing hangs. In this PR, we fail the request instead of waiting, which shouldn't cause any hang.

we also defer the GCS registration as the last of construction.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
Lgtm if tests pass

**Comment by rkooo567** [comment]
Rerunning the release tests (it didn't work for some reasons)

**Comment by can-anyscale** [comment]
@rkooo567 , @scv119 , you'll need to rebase past https://github.com/ray-project/ray/commit/811b453e093b1a1cf54605da8a6220a0536d30d1 which reverts the PR that causes hanging

**Comment by can-anyscale** [comment]
BTW, the revert of the previous attempt was likely incorrect. The culprit PR was https://github.com/ray-project/ray/commit/4d8c2c9bf591d38076d16352f4995df511350582. 

I'll revert the revert of the previous attempt in release branch to see if tests can pass with that solution. If it is, let's use that one for 2.6.0.

Let me know otherwise, thankkks

**Comment by rkooo567** [comment]
According to @can-anyscale the original issue didn't break tests, and the culprit was the other core changes. So we will just re-introduce the original PR

**Comment by rkooo567** [comment]
Closing over  https://github.com/ray-project/ray/pull/37495

**Pull request closed without merging**
