### PR TITLE
[core] introduce Watchdog

### LINKED ISSUE #23566: [Feature] Catch worker process exit status using SIGCHLD
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently when worker process exit abnormally we don't know the exit code. One way we get this information in raylet is to handle system SIGCHLD signal in worker_pool.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Catch-Bull**
similar to #23905

closes https://github.com/ray-project/ray/issues/23566

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scv119** [comment]
@Catch-Bull thanks for contributing to ray core! Can you fix the windows build?

**Review by scv119 — COMMENTED** [review]
also can you update the description?

**Comment by rkooo567** [comment]
Let me know when it is ready! Pretty exciting to have this change :)

**Comment by rkooo567** [comment]
Hey @Catch-Bull Is there any estimation regarding when this PR will be available for a review? Thank you!

**Comment by rkooo567** [comment]
hey @Catch-Bull if there's no activity, I will close the PR and we will do something similar on our end. Thank you!

**Pull request closed without merging**
