### PR TITLE
[serve] Add Deployment.replicas and runtime_metadata

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Adds a new API to the `ServeDeployment` that exposes the current running replicas. This is useful for two purposes:

1. It's an incremental step towards allowing more fine-grained control over how to route requests to replicas.
2. It enables integrating with serve discovery for direct ingress to replicas.

For (2), we also need some way for replicas to expose metadata at runtime (e.g., their IP address and port). For this purpose, backend classes can now define a `health_check` method that will be run to transition the replica to the `RUNNING` state and can return any serializable metadata.

In the future we should migrate the `ServeHandle` to be built on top of this abstraction, but we'll need to wait until the `endpoint` concept is removed for that.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Why don't we put the replica inside handles? `Deployment.get_handle().replicas` is more natural abstraction. We can discuss more here? https://github.com/ray-project/ray/issues/15312

**Comment by edoakes** [comment]
Responded on issue

**Comment by edoakes** [comment]
Btw @simon-mo we'll need to implement the change to directly call methods on the replicas if we want users to be able to send requests directly to these `replicas` (the `replica.handle_request` API is currently private and messy)

**Comment by edoakes** [comment]
ping @simon-mo

**Comment by simon-mo** [comment]
> In the future we should migrate the ServeHandle to be built on top of this abstraction, but we'll need to wait until the endpoint concept is removed for that.

Is that true? If a "endpoint" is part of a deployment, we can just use this API right? I'm a little bit worry about the duplicated code in both places.

**Pull request closed without merging**
