### PR TITLE
Try deflaking worker capping on Windows

### PR DESCRIPTION
**Pull request by rkooo567**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@wuisawesome Do you think that's the right fix or could it be masking some problem? We should merge either this or https://github.com/ray-project/ray/pull/20605, the CI has been broken too long :)

**Comment by wuisawesome** [comment]
Thanks, I actually think we should merge #20605 since some of these timeouts should happen (i.e. we want to assert that `ray.wait` _does_ have incomplete tasks), so the long timeout will just make some of these tests take a super long time to run

**Comment by rkooo567** [comment]
I think 1 second is too short timeout. Also given Github action uses a really small machine (IIRC, it uses 2 CPUs + 4 or 8GB of memory which is smaller than buildkite machines), increasing timeout to at least 5~10 seconds seem reasonable (I am not 100% sure if this will fix the issue, but worth trying).

**Comment by wuisawesome** [comment]
We merged #20605 so that should be good for now, I'll try to reenable the test with a longer timeout in a bit, but I don't think we want to increase all of the timeouts

**Comment by rkooo567** [comment]
Isn't that the different test though? I saw this test was failing from Windows CI I think

**Comment by pcmoritz** [comment]
Yeah, it is a different test :)

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
