### PR TITLE
[Core]Abstract gcs publisher interface to wipe those if-else off

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
This is a code re-construct. Redis/gRpc based gcs publishers before are implemented in one same class and there're `if-else`es in every method.
We separate those two implementation into different subclasses, whose super class is a gcs publisher interface. 

The next step is abstracting gcs subscribers.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
Hi @WangTaoTheTonic, good refactoring, but the plan of the Redis removal project is to remove the Redis pub/sub implementation all together. We just need a single `GcsPublisher` class with gRPC implementation.

**Comment by WangTaoTheTonic** [comment]
> Hi @WangTaoTheTonic, good refactoring, but the plan of the Redis removal project is to remove the Redis pub/sub implementation all together. We just need a single `GcsPublisher` class with gRPC implementation. i.e. the Redis publisher implementation can be removed. You can leave the work to me.

got it. What's the plan to remove redis based implementation?

**Comment by mwtian** [comment]
Hopefully we can merge https://github.com/ray-project/ray/pull/23520 soon, which removes the Redis pubsub implementation.

**Comment by WangTaoTheTonic** [comment]
Alright. Closing this.

**Pull request closed without merging**
