### PR TITLE
[serve] Pin `fastapi==0.99.1` in `requirements-doc.txt` to fix API reference (#37340)

### LINKED ISSUE #37337: [serve] API reference docs are broken
The API reference is not rendering properly on the docs for both master and 2.6 release branch. Example:
https://docs.ray.io/en/master/serve/api/index.html

Screen Shot 2023-07-12 at 9 54 03 AM

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Cherry-pick https://github.com/ray-project/ray/pull/37340

Also cherry-picks: https://github.com/ray-project/ray/pull/37375, which is a one-line change to fix the Windows build in CI.

## Related issue number

Closes https://github.com/ray-project/ray/issues/37337

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]

**Comment by edoakes** [comment]
Oops, forgot DCO. Fixed.

**Comment by edoakes** [comment]
The windows test failure is relevant: https://buildkite.com/ray-project/oss-ci-build-pr/builds/28438#01894b71-31e4-4ce5-bfa9-a029a3cb4b45/5693-8608

Let's hold off on merging this.

**Comment by edoakes** [comment]
I think this is technically against policy, but I cherry-picked https://github.com/ray-project/ray/pull/37375 as well here (it just adds `[all]` to the requirements file which is required for the Windows build to pass).

Given they're tightly related & minimal in scope I figure this is fine. LMK if you want me to split into two PRs (though then the first would break CI in a known way).

**Comment by zhe-thoughts** [comment]
Thanks @edoakes for fixing it! I think it's OK in this case.

**Comment by edoakes** [comment]
API ref looks good.

Test failures unrelated (`test_metrics` serve test flaky on master)

**Pull request merged**
