### PR TITLE
[java] Remove multi-return API

### PR DESCRIPTION
**Pull request by raulchen**
This PR removes a set of multi-return APIs that turned out to be useless. Because `RayList`, `RayMap`, and `MultiReturnX` can always be replaced by `RayObject<List>`,  `RayObject<Map>` and `RayObject<TupleX>`.

By removing them, we can simplify the API and implementation while providing the same ability. 

We're working on a series of changes that targets to improve the code quality of Java worker, includes:
- simplifying and improving API, code structure, and implementation;
- narrowing down the inconsistent behaviors between Python and Java;
- improving naming and documentation;
- deprecating non-raylet code path;
- etc.

These changes will come in the near future.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@raulchen this seems like a reasonable change, however, a "tuple of object IDs" is not exactly equivalent to an "object ID for a tuple".

Returning multiple `ObjectID`s from a task allows you to send only part of the returned data to different downstream tasks and avoid shipping unnecessary data. Are you saying that this benefit is not worth the additional complexity?

**Comment by raulchen** [comment]
@robertnishihara Yep, that's a good point. I thought about that as well.

I think with the single-object API, we can achieve the same ability as well. For example, we can
1) either put different parts in multiple objects, and only return a tuple of object ids;
2) or refactor the code and let the function who returns multiple values send different parts to different downstream nodes directly.

Currently, there's no real use case of returning multiple values. The problem of the current design and implementation is that it introduces too much complexity to almost every piece of code, to support a requirement that doesn't exist. Thus, I don't think it's worth it.

Even if this becomes a common use case in the future and we do want to have multi-return APIs (instead of manually doing Approach 1). We can re-add the APIs on top the single-return APIs, without changing the underlying code.

**Comment by robertnishihara** [comment]
Ok, that sounds good.

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
@raulchen it looks like the Java Travis test failed with

```
[31;1mThe command "./java/test.sh" exited with 1.[0m
```

Any idea about that?

**Comment by raulchen** [comment]
there's a lint issue. I'll fix it.

**Pull request merged**
