### PR TITLE
[script] expose options of xxx_port in 'ray start' command

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
We need to expose the options of  xxx_port in 'ray start' command because of some port conflict issues such as https://discuss.ray.io/t/runtime-env-fails-when-running-ray-in-docker/5508

### CODE REVIEW

**Comment by rkooo567** [comment]
Can you also update https://docs.ray.io/en/master/ray-core/configure.html#ports-configurations?

**Comment by SongGuyang** [comment]
Updated.

**Comment by jjyao** [comment]
@SongGuyang Is it possible for us to detect what ports are exposed by docker and select a random port from those? I think that's even better UX.

**Review by rkooo567 — APPROVED** [review]

**Comment by SongGuyang** [comment]
@jjyao We‘ve already done that https://github.com/ray-project/ray/blob/master/python/ray/node.py#L717.

**Comment by jjyao** [comment]
> @jjyao We‘ve already done that https://github.com/ray-project/ray/blob/master/python/ray/node.py#L717.

@SongGuyang Then why would we have port conflict? If it's implemented correctly, we should use an unused port?

**Comment by SongGuyang** [comment]
@jjyao No conflict. The unused port is not exposed in user's network.

**Pull request merged**
