### PR TITLE
[KubeRay][Doc] KubeRay doc migration (4/n)

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

Copy from https://github.com/ray-project/kuberay/blob/master/docs/guidance/volcano-integration.md.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by GeneDer** [comment]
@kevin85421 Is this also a PR raised against the release branch or if this is a cherry pick?

**Review by architkulkarni — APPROVED** [review]
The code to add the doc looks good. I have not reviewed the content of the doc because it was already reviewed in the other repo.

**Review by zhe-thoughts — APPROVED** [review]
Clean and necessary docs change; qualifies for picking

**Comment by kevin85421** [comment]
> @kevin85421 Is this also a PR raised against the release branch or if this is a cherry pick?

@GeneDer Yes, this PR is for the release branch. I will cherry-pick this commit to the master branch after it is merged into the release branch.

**Comment by kevin85421** [comment]
I did not address the Vale writing recommendations in this PR. I will review all the recommendations from Vale for all KubeRay docs after the Ray Summit.

**Comment by kevin85421** [comment]
Close this PR. I will open a cherry-pick PR after https://github.com/ray-project/ray/pull/39393 is merged into the master branch.

**Pull request closed without merging**
