### PR TITLE
[Serialization] Update CloudPickle to 1.6.0

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

After #9622, we no longer need the numpy workaround in cloudpickle. Also the latest cloudpickle natively supports pickle5. This PR ships the latest cloudpickle to Ray without any patch (except adding "ray" prefix in `__init__.py` for correct module import)

We also move some serialization tests to the correct test script.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by suquark** [comment]
retriggered build to use the latest upstream

**Comment by suquark** [comment]
retriggered build to use the latest upstream

**Comment by suquark** [comment]
It seems `test_serialization` gets timeout. Let me look deeper into it.

**Comment by rkooo567** [comment]
@suquark Do you have any plan to take a look at this sooner or later?

**Comment by suquark** [comment]
let's see if rebasing would result in a successful build

**Comment by rkooo567** [comment]
Still fails on `test_serialization.`

**Comment by suquark** [comment]
not sure what actually happened. the test is green on my local macbook. I may not have enough time to fully investigate into this issue recently.

**Comment by rkooo567** [comment]
No problem! Please take ur time. If you can point me resources, I can take a look if I can fix the issue

**Comment by suquark** [comment]
It only seems like the macos run takes more time than the linux one. I do not find any problem on my own macbook

**Comment by rkooo567** [comment]
Ah, I see. Our Mac test is usually slower than Linux, and it causes timeout error for "small" bazel tests (which is supposed to be done within 60 seconds I believe). Just move the test to medium size test https://github.com/ray-project/ray/blob/0d22c0b6535817b582a501a613717f30a0e5a73a/python/ray/tests/BUILD#L84

**Review by rkooo567 — APPROVED** [review]
@suquark Thanks for fixing issues!

**Pull request merged**
