### PR TITLE
[RLlib] Deflake replay buffer demo - Up test size to leave a little more time for ReplayBufferDemo

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Signed-off-by: Artur Niederfahrenhorst <artur@anyscale.com>

## Why are these changes needed?

The replay buffer demo likes to take approx 10 iterations to reach the nice reward of 50 but often gets cancelled earlier (for example after 7 like in the picture) because it is marked as a test of size medium.

Screenshot 2023-01-04 at 12 26 33

Screenshot 2023-01-04 at 12 27 51

### CODE REVIEW

**Review by krfricke — APPROVED** [review]

**Review by gjoliver — COMMENTED** [review]
need 15 mins to run 10 iterations??
what is taking all this time? should we just make an iteration shorter by setting min_time_s_per_iteration?

**Comment by ArturNiederfahrenhorst** [comment]
@gjoliver min_time_s_per_iteration is None by default, but we could lower minimum samples per iteration from 1000 to something lower. However then the script probably would never learn, also not on user's machines.
I've given it three rolloutworkers now and I'm guessing its running much quicker locally. Should we try that?

**Comment by gjoliver** [comment]
> @gjoliver min_time_s_per_iteration is None by default, but we could lower minimum samples per iteration from 1000 to something lower. However then the script probably would never learn, also not on user's machines. I've given it three rolloutworkers now and I'm guessing its running much quicker locally. Should we try that?

how long does it take to reach 50 now that we have 3 workers? does it ever stop because of 10-iter limit?

**Comment by ArturNiederfahrenhorst** [comment]
> > @gjoliver min_time_s_per_iteration is None by default, but we could lower minimum samples per iteration from 1000 to something lower. However then the script probably would never learn, also not on user's machines. I've given it three rolloutworkers now and I'm guessing its running much quicker locally. Should we try that?
> 
> how long does it take to reach 50 now that we have 3 workers? does it ever stop because of 10-iter limit?

It usually stops bc of the 10-iter limit.
On my own machine, execution time is halved:

Screenshot 2023-01-05 at 01 01 58
Screenshot 2023-01-05 at 00 55 40

**Comment by ArturNiederfahrenhorst** [comment]
Should be more than enough to make this green I guess

**Comment by gjoliver** [comment]
this is very cool!

**Comment by ArturNiederfahrenhorst** [comment]
Yeah let's hope it has a super similar effect on CI! 🥳

**Pull request merged**
