### PR TITLE
[Core] update code owner for setup.py

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

Makes it easier to update requirements.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — CHANGES_REQUESTED** [review]
I'm actually going to push back on this--- historically few people have been willing to push back hard enough on dependency sprawl.

**Comment by edoakes** [comment]
+1, I don't see having some friction for dependency changes as a bad thing

**Comment by pcmoritz** [comment]
+1 on having a very high bar here!

Another possible implementation is that 2 out of {@richardliaw @ericl @edoakes @scv119} need to approve. I do think @scv119 has very good judgement and is an important stakeholder :)

**Comment by scv119** [comment]
let me try another day then :)

**Pull request closed without merging**
