### PR TITLE
Add top navigation to documentation

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

This adds a top navigation to our documentation that will be unified with the top navigation of the ray.io website going forward so we can have a unified experience between ray.io website and documentation.

Before this is merged, @sijieamoy graciously offered to improve the styling of the top bar to fit better with the overall design. Currently the design is a placeholder with minimal work.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by maxpumperla** [comment]
@pcmoritz this is cool! we have been discussing this a while ago. how did we intend to solve the "old doc releases will have outdated navigations"? just curious to hear your thoughts (we have the same issue with old algolia indices).

**Comment by pcmoritz** [comment]
So the navigation will always link to material within the same doc version (I'm careful about that and it took a while to get it right), so we can change things going forward and they will still be consistent. However I'm trying somewhat hard to iterate on something that makes sense before Ray 2.2 gets released, and then also making docs + ray.io navigation consistent. A little inconsistency I think is fine, if we want to evolve things going forward.

So the short answer is: Release the nav bar together with the docs, so things will never be inconsistent within the docs, and then ray.io could be a little inconsistent with older things, but will always be consistent with the latest release. I think this is as good as it can get :)

Let me know if you have further thoughts / ideas on how this should look like btw, I'm still very much iterating on it :)

**Comment by maxpumperla** [comment]
great, thanks. yeah, I'm sure we can keep consistency _within_ docs.ray.io. what I meant is the compatibility between ray.io (which has no versions) and docs.ray.io (which is versioned). maybe I'm overthinking this, though.

One idea that we can still implement later, if we wanted to, is to try and go with a similar route to the "marketing banners" we implemented a while ago. I.e., host the current navigation item names and links on a separate app, so that we can dynamically change it without having to submit a PR against the main ray repo.

**Review by richardliaw — APPROVED** [review]

**Comment by pcmoritz** [comment]
Tests are passing except for an unrelated linkcheck error :)

**Pull request merged**
