### PR TITLE
IA polish for demo

### PR DESCRIPTION
**Pull request by alanwguo**
- Add links between progress bar and task table and actor table
- Add links from task table to logs and to view stack trace fix horizontal scroll of table view
- Fix logs link going to old IA instead of new IA.
- fix horizontal scroll of table view
- Add beta label

Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Screenshot 2023-01-31 at 7 40 26 PM
Screenshot 2023-01-31 at 7 40 28 PM
Screenshot 2023-01-31 at 7 40 35 PM

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scottsun94** [comment]
Look good to me!

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
There are merge conflicts. @alanwguo

**Comment by rkooo567** [comment]
Let's cherry pick this PR

**Comment by rkooo567** [comment]
Unfortunately, there's a failure from tests:test_state_api_summary

**Comment by alanwguo** [comment]
I think test should be fixed now. But i see branch was cut yesterday at 10am so we need to cherry-pick

**Pull request merged**
