### PR TITLE
[Core] Remove code paths that run plasma store as a process

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

I find that plasma running as thread actually has been enabled by default (because java launches Ray using python scripts). Some critical functions like object spilling are assuming that plasma store is running as a thread. So the outdated code path is no longer used and it is not functioning correctly. This PR removes the old code path that runs plasma store as a process.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by suquark** [comment]
@rkooo567 I find that running plasma store as a thread is not only by default but also a must because object spilling etc depends on it. So there is not reason to keep the code path that is not functioning. I update the PR to remote outdated code.

**Comment by suquark** [comment]
I will wait test fixes in #14950

**Comment by rkooo567** [comment]
So should I review the other one first?

**Comment by suquark** [comment]
@rkooo567 Yes. I will assign to you after I fixed the errors in the other one.

**Comment by suquark** [comment]
@rkooo567 I have fixed the failed tests. Could you review the PR again?

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
