### PR TITLE
More informative error message if ray start fails to connect to Redis

### PR DESCRIPTION
**Pull request by dHannasch**
## Why are these changes needed?

Currently, if `ray start` is unable to connect to Redis, it doesn't give a lot of help in figuring out why.

This branch has two changes. Strictly speaking, these two changes are orthogonal, but they affect the same lines (so they would have merge conflicts) and they have the same purpose: debugging when Redis is unreachable.

The first change is simply to report the address that it tried and failed to connect to. This information can technically be dug up with ``--log-level debug``, but there's no reason not to report this when the function already has this information.

The other change is to chain in the original redis.ConnectionError. This might help with, for example, disambiguating between a failure due to the port being unreachable and a failure due to the password being incorrect.

The redis.ConnectionError is chained in by taking advantage of Python's permissive scoping rules to pick it up outside of its block.
The linter doesn't like this:
```
python/ray/_private/services.py:563:9: F841 local variable 'redisConnectionError' is assigned to but never used
python/ray/_private/services.py:575:50: F821 undefined name 'redisConnectionError'
```
In fairness to the linter's point of view, this is pretty clunky, but anything else (raising inside the except block, or something like using https://www.python.org/dev/peps/pep-3134/#implicit-exception-chaining) would require significantly rearranging the control flow of `wait_for_redis_to_start()`, which might cause unanticipated problems.
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
@dHannasch this is super useful. Do you have an idea for how to unit test this?

**Comment by dHannasch** [comment]
> @dHannasch this is super useful. Do you have an idea for how to unit test this?

Well, I don't know how to deliberately block a port, but we could deliberately provide a wrong Redis password, or just run ray start when the head node is in fact not running.

**Comment by rkooo567** [comment]
@dHannasch Please resolve the merge conflict! I will review the PR after that.

**Comment by richardliaw** [comment]
@dHannasch are tests failing? see `redis password` test

**Review by richardliaw — APPROVED** [review]

**Pull request merged**
