### PR TITLE
[core] Upgrade redis from 6.x to 7.0.5.

### PR DESCRIPTION
**Pull request by fishbone**
Signed-off-by: Yi Cheng <74173148+iycheng@users.noreply.github.com>

## Why are these changes needed?
Due to the SSL support and also security issues, upgrade the redis from 6.x to 7.0.5.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ijrsvt — APPROVED** [review]
LGTM!

**Comment by iycheng** [comment]
some test failures. let me check.

**Review by scv119 — APPROVED** [review]
as long as CI passes

**Comment by iycheng** [comment]
mac and linux looks good. windows still fails.

**Comment by iycheng** [comment]
test failure is not related.

**Pull request merged**
