### PR TITLE
Add action space to model

### PR DESCRIPTION
**Pull request by stefanpantic**
## What do these changes do?
* Added action space to TensorFlow model class
* ```Model.get_model``` now takes an aditional argument ```action_space``` which is the target gym env action space.

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Looks good. I pushed a change to satisfy the linter (scripts/format.sh)

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
Looks like you missed a spot:

Traceback (most recent call last):
  File "/ray/python/ray/rllib/tests/../examples/custom_loss.py", line 96, in <module>
    "input_files": args.input_files,
  File

**Comment by stefanpantic** [comment]
@ericl Fixed

**Pull request merged**
