### PR TITLE
[log_monitor] Always reopen files

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This PR prevents the log monitor for keeping files open for long periods of time. In settings in which the autoscaler and head node are not tightly coupled, leaving files open implies that the inode for a file never changes, but depending on how fs synchronization between the autoscaler and head node containers works, the inode could change. Thus, we should keep try reopening files. 

This is done via setting max open files to 1, so that it's easy to revert this behavior.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
Empirically I see no performance regressions when i try to generate tons of logs

```
(base) ubuntu@ip-172-31-19-143:~$ export RAY_LOG_MONITOR_MAX_OPEN_FILES=200
(base) ubuntu@ip-172-31-19-143:~$ time python temp.py > /dev/null

real    0m25.219s
user    0m1.975s
sys     0m0.573s
(base) ubuntu@ip-172-31-19-143:~$ export RAY_LOG_MONITOR_MAX_OPEN_FILES=1
(base) ubuntu@ip-172-31-19-143:~$ time python temp.py > /dev/null

real    0m25.181s
user    0m1.982s
sys     0m0.582s
(base) ubuntu@ip-172-31-19-143:~$ 
```

using the script 

```
import ray

ray.init()

@ray.remote
def print_alot():
    for i in range(10**6):
        print("hello", i)

ray.get([print_alot.remote() for _ in range(10)])
```

**Comment by wuisawesome** [comment]
I'm a little confused by the release test failures. I tried to run one manually (serve_single_deployment_1k_noop_replica_1658346728) and it passed :o

**Comment by wuisawesome** [comment]
Compared to yesterday's run it looks like the failures are actually broken on master too.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
LGTM.

**Comment by wuisawesome** [comment]
Screen Shot 2022-07-20 at 4 11 32 PM

Yay it works

**Pull request merged**
