### PR TITLE
[CI] Fix python/ray/tests:test_autoscaler_aws

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?

https://github.com/ray-project/ray/pull/34804 broke python/ray/tests:test_autoscaler_aws because that unit-test does not allow to specify a key-value pair in the aws provider. Release tests need to specify that key though. Fix release tests to use the same file to we don't have to specify separated keys.

## Related issue number
Fix issue 34935

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests
   - [X] Release tests

### CODE REVIEW

**Review by aslonnie — APPROVED** [review]

**Comment by can-anyscale** [comment]
Previously failing tests now pass: https://buildkite.com/ray-project/oss-ci-build-pr/builds/20391#0187d9f1-92e4-4783-b07c-d24a3d89f420

**Review by scv119 — APPROVED** [review]

**Comment by can-anyscale** [comment]
Pass to @wuisawesome or @ericl  for code owner approval. Thanks!

**Comment by scv119** [comment]
hmm is removing `key-pair` breaking the autoscaler example? @wuisawesome or @DmitriGekhtman to confirm.

**Comment by can-anyscale** [comment]
https://github.com/ray-project/ray/pull/34804 added the key-pair and broke unittest; this pr reverted it ;)

**Review by ericl — APPROVED** [review]

**Review by krfricke — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
