### PR TITLE
Pin gym version to 0.9.5 in tests.

### PR DESCRIPTION
**Pull request by robertnishihara**
This is a temporary workaround for #1486. We'll need to address the "actual" problem though.

### CODE REVIEW

**Comment by robertnishihara** [comment]
cc @pcmoritz @richardliaw @ericl

**Comment by pcmoritz** [comment]
Let's fix it instead, since users will probably have the latest version of gym.

**Comment by robertnishihara** [comment]
I think it's a bug in gym, see openai/gym#850. It may make sense to merge this until that is resolved.

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
test error unrelated... why does GPUid test keep failing?

**Pull request merged**
