### PR TITLE
[tune] Ea scope avg n step

### LINKED ISSUE #8147: [tune]add 'last-n-avg' option for scope parameter in get_best_* methods
### Describe your feature request
As described in the [Google Groups](https://mail.google.com/mail/u/0/#inbox/FMfcgxwHMZGcqCZltQQjfxMpKMWpXKdK), it makes sense to evaluate model on every batch of time series data (like _hour-01, hour-02, ..., hour-23_) when we are doing some online learning stuff (for example ads\feeds recommending).
When dealing with such situation, it's better to take **average of last n or all** steps' metric of one trial into consideration when we are retrieving the best trial.
So I sugguest add **'avg'**, **'last-n-avg'** options to the **scope** parameter in following methods

- ray.tune.ExperimentAnalysis.get_best_trial
- ray.tune.ExperimentAnalysis.get_best_config
- ray.tune.ExperimentAnalysis.get_best_logdir

### PR DESCRIPTION
**Pull request by krfricke**
Continuing #8147, this adds `last-n-avg`, specifically `last-5-avg` and `last-10-avg` scopes to the collected experiment metrics. These _n_ are currently hardcoded since a variable number of steps would need an extension of the API for trials and the experiment runner.

Closes #8147.

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Looks like tune tests are failing?

**Comment by krfricke** [comment]
There seems to be an error when restoring a run where the `self.metric_n_steps` don't get initialized: https://github.com/ray-project/ray/runs/681419121#step:3:2390 I'll fix this tomorrow.

**Comment by krfricke** [comment]
The error was in restoring the n-step metrics. The dict keys were restored as strings, while they were originally created as integers. We should talk about whether this is expected behavior. For the meantime, we're now converting the integers to strings for the dict keys.

**Comment by richardliaw** [comment]
ah can we fix up the PR? looks like the merge history is broken

**Comment by krfricke** [comment]
I rebased the PR against the current master and resolved any merge conflicts. I hope it works now. Alternatively, I could re-create the changes on a fresh branch to avoid the messy commit history.

**Pull request closed without merging**
