### PR TITLE
Object store full with cyclic python references

### PR DESCRIPTION
**Pull request by ericl**

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]

**Comment by edoakes** [comment]
Unfortunately I don't think this fixes the case I reported because we would be calling gc.collect on the driver but the issue is on the worker. Still seems worth merging though. Please leave a comment pointing to the issue.

**Comment by ericl** [comment]
Which put path in the worker doesn't go through this flow? Is it possible
to also add a GC in that one?

**Comment by edoakes** [comment]
The path for task returns. We could do that but not sure the performance impact of doing it every time.

**Comment by ericl** [comment]
I guess for a full solution, you will need to force GC on every worker that could potentially be pinning too much memory.

However, this PR should be harmless and fixes once case, so going ahead with merging.

**Pull request merged**
