### PR TITLE
Revert "[GCS]Open light heartbeat by default (#11968)"

### PR DESCRIPTION
**Pull request by krfricke**
This reverts commit d525e612

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@WangTaoTheTonic Maybe there's another bug :(... Let me merge this PR!

**Comment by rkooo567** [comment]
I will see if this fixes the test failures first

**Comment by rkooo567** [comment]
Seems like the fault tolerance tests are consistently failing after this PR. Since we skipped those tests in the master, we don't need to revert this PR. But @ffbin it can be the hint that lightweight heartbeat is related to the fault tolerance tests failure. (since it seems like that test fails 100% after we merged this PR).

**Comment by WangTaoTheTonic** [comment]
Maybe this https://github.com/ray-project/ray/commit/c49554fb7ae62f2b03ebfadb8e6f99e0ccbfaa46

**Comment by ffbin** [comment]
@richardliaw I tested the placement group testcase on the Mac and find that the light heartbeat is the cause.

**Comment by ffbin** [comment]
I suspect it is caused by heartheart. After GCS is restarted, raylet does not report the heartbeat again, resulting in no node for placement group to schedule.

**Comment by richardliaw** [comment]
ok, please merge at first convenience!

**Comment by rkooo567** [comment]
We will fix the bug as we already skipped tests. Close it.

**Pull request closed without merging**
