### PR TITLE
[RLlib] Put learning test into own folders

### LINKED ISSUE #26579: [RLlib Release Tests] Learning Tests a-e and f-z are failing
### What happened + What you expected to happen

learning tests should be passing.

### Versions / Dependencies

Master

### Reproduction script

n/a

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by avnishn**
Learning tests A-E are failing and we need to find out whether that's because of competition for resources.
This PR puts them onto their own clusters to see what happens.

Closes #26731 . @ArturNiederfahrenhorst for whatever reason I couldn't push to your branch after running gh pr checkout so I had to reopen this my bad

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ArturNiederfahrenhorst** [comment]
@avnishn Would like to underline that the release tests in their individual folders have oversized clusters to run on. Hence the PR was tagged "do-not-merge"!

**Comment by avnishn** [comment]
My plan is the increase the amount of cpus/gpus each algorithm is using to decrease learning time. In a separate PR. 

For now, this is good to merge to unblock the release.

**Review by gjoliver — COMMENTED** [review]
I am actually a big fan of this change.
so most of these 2gpu compute configs can be changed to 1gpu right?

**Comment by avnishn** [comment]
> I am actually a big fan of this change. so most of these 2gpu compute configs can be changed to 1gpu right?

the 2 gpu tags are incorrectly named across the whole CI 

its actually just 1 g3.8xlarge instance. 

1 gpu 32 cpus

**Review by gjoliver — APPROVED** [review]

**Pull request merged**
