### PR TITLE
fix NCCL_BFLOAT16 typo in TORCH_NCCL_DTYPE_MAP

### PR DESCRIPTION
**Pull request by SeaOfOcean**
## Why are these changes needed?

fix NCCL_BFLOAT16 typo in TORCH_NCCL_DTYPE_MAP

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by SeaOfOcean** [comment]
@stephanie-wang

**Review by kevin85421 — APPROVED** [review]

**Comment by SeaOfOcean** [comment]
How can this pull request get merged? @kevin85421

**Comment by kevin85421** [comment]
Oh, I don't have the merge permission. Let me ping my colleague.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Thanks for the contribution!

**Pull request merged**
