### PR TITLE
[Java] Attach owner address for pass-by-reference task arguments

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

Corresponding Python (and core worker) PR: #9152 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by stephanie-wang — APPROVED** [review]

**Comment by stephanie-wang** [comment]
Do you think this java test failure is related? https://api.travis-ci.com/v3/job/363746344/log.txt

**Comment by kfstorm** [comment]
> Do you think this java test failure is related? [api.travis-ci.com/v3/job/363746344/log.txt](https://api.travis-ci.com/v3/job/363746344/log.txt)

@stephanie-wang Thanks for the heads-up. It is indeed related. I've pushed a commit to fix it. The tests passed locally though. It's always tricky to find out when bugs are memory-related.

**Comment by kfstorm** [comment]
@stephanie-wang I just found out that we missed a lot of code in Java related to *owner address* or *ownership*. Some core worker APIs are currently used by Python only, like `PromoteObjectToPlasma`, `GetOwnershipInfo`, `RegisterOwnershipInfoAndResolveFuture`. And currently, we don't store the owner address in the serialized data of an `ObjectRefImpl` either.

Maybe we should hold this PR and I'll try to port the logic to Java. BTW, What's the usage of `PromoteObjectToPlasma`? Does it mean that once an object is added into the memory store, it's also copied to the plasma store? Any documentation about this?

**Comment by stephanie-wang** [comment]
> @stephanie-wang I just found out that we missed a lot of code related to _owner address_ or _ownership_ in Java. Some core worker APIs are currently used by Python only, like `PromoteObjectToPlasma`, `GetOwnershipInfo`, `RegisterOwnershipInfoAndResolveFuture`. And currently, we don't store the owner address in the serialized data of an `ObjectRefImpl` either.
> 
> Maybe we should hold this PR and I'll try to port the logic to Java. BTW, What's the usage of `PromoteObjectToPlasma`? Does it mean that once an object is added into the memory store, it's also copied to the plasma store? Any documentation about this?

Ah yes, that's right. I didn't realize that hadn't been implemented in Java yet. It'd be fine to add those to this PR too, shouldn't be too much code and it's all related to passing the owner address around.

The promotion is for object refs that get serialized. It's actually not strictly necessary anymore now that we have distributed ref counting, but the idea is to "promote" objects whose refs get serialized, so that the deserializing process can get the object through plasma. The issue is that the value of the object may not be available yet at the time that the ref is serialized, so previously we didn't have a good way to pass objects that were in the direct memory store. No docs about this right now, but yeah that'd be good to add.

**Comment by stephanie-wang** [comment]
Hi @kfstorm, could you fix the merge conflicts?

**Comment by kfstorm** [comment]
@stephanie-wang As we talked before, this PR is not ready to merge yet because of some missing code about owner address. However, I can resolve conflicts.

**Pull request merged**
