### PR TITLE
[AIR] Tf end2end CV example

### PR DESCRIPTION
**Pull request by JiahaoYao**
tensorflow end2end example using air.

### CODE REVIEW

**Comment by JiahaoYao** [comment]
the hardcode: 

1. #25055 `to_tf`
```python
def to_tf(
    self,
    *,
    output_signature: Union[
        TensorflowFeatureTypeSpec, Tuple[TensorflowFeatureTypeSpec, "tf.TypeSpec"]
    ],
    label_column: Optional[str] = None,
    feature_columns: Optional[
        Union[List[str], List[List[str]], Dict[str, List[str]]]
    ] = None,
    prefetch_blocks: int = 0,
    batch_size: int = 1,
    unsqueeze_label_tensor=True,
    drop_last: bool = False,
) -> "tf.data.Dataset":
    """Return a TF Dataset over this dataset.

    The TF Dataset will be created from the generator returned by the
    ``iter_batches`` method. ``prefetch_blocks`` and ``batch_size``
    arguments will be passed to that method.

    For the features tensor (N is the ``batch_size`` and n1, ..., nk
    are the number of features per tensor):

    * If ``feature_columns`` is a ``List[str]``, the features will be
        a tensor of shape (N, n), with columns corresponding to
        ``feature_columns``

    * If ``feature_columns`` is a ``List[List[str]]``, the features will be
        a list of tensors of shape [(N, n1),...,(N, nk)], with columns of each
        tensor corresponding to the elements of ``feature_columns``

    * If ``feature_columns`` is a ``Dict[str, List[str]]``, the features
        will be a dict of key-tensor pairs of shape
        {key1: (N, n1),..., keyN: (N, nk)}, with columns of each
        tensor corresponding to the value of ``feature_columns`` under the
        key.

    This is only supported for datasets convertible to Arrow records.

    Requires all datasets to have the same columns.

    It is recommended to call ``.split()`` on this dataset if
    there are to be multiple TensorFlow workers consuming the data.

    The elements generated must be compatible with the given
    ``output_signature`` argument (same as in
    ``tf.data.Dataset.from_generator``).

    Time complexity: O(1)

    Args:
        output_signature (Union[TensorflowFeatureTypeSpec, \
Tuple[TensorflowFeatureTypeSpec, "tf.TypeSpec"]]): If ``label_column`` is specified,
            a two-element tuple containing a ``FeatureTypeSpec`` and
            ``tf.TypeSpec`` object corresponding to (features, label). Otherwise, a
            single ``TensorflowFeatureTypeSpec`` corresponding to features tensor.
            A ``TensorflowFeatureTypeSpec`` is a ``tf.TypeSpec``,
            ``List["tf.TypeSpec"]``, or ``Dict[str, "tf.TypeSpec"]``.
        label_column (Optional[str]): The name of the column used as the label
            (second element of the output tuple). If not specified, output
            will be just one tensor instead of a tuple.
        feature_columns (Optional[Union[List[str], List[List[str]], Dict[str, \
List[str]]]): The names of the columns to use as the features. Can be a list of lists
            or a dict of string-list pairs for multi-tensor output. If None, then
            use all columns except the label columns as the features.
        prefetch_blocks: The number of blocks to prefetch ahead of the
            current block during the scan.
        batch_size: Record batch size. Defaults to 1.
        drop_last (bool): Set to True to drop the last incomplete batch,
            if the dataset size is not divisible by the batch size. If
            False and the size of dataset is not divisible by the batch
            size, then the last batch will be smaller. Defaults to False.

    Returns:
        A tf.data.Dataset.
    """

    # argument exception checking is done in from_generator

    try:
        import tensorflow as tf
    except ImportError:
        raise ValueError("tensorflow must be installed!")

    # `output_signature` can be a tuple but not a list. See
    # https://stackoverflow.com/questions/59092423/what-is-a-nested-structure-in-tensorflow.
    if isinstance(output_signature, list):
        output_signature = tuple(output_signature)

    def get_df_values(df: "pandas.DataFrame") -> np.ndarray:
        # TODO(Clark): Support unsqueezing column dimension API, similar to
        try:
            values = df.values
            values = np.stack(values)

        except ValueError as e:
            import pandas as pd

            # Pandas DataFrame.values doesn't support extension arrays in all
            # supported Pandas versions, so we check to see if this DataFrame
            # contains any extensions arrays and do a manual conversion if so.
            # See https://github.com/pandas-dev/pandas/pull/43160.
            if any(
                isinstance(dtype, pd.api.extensions.ExtensionDtype)
                for dtype in df.dtypes
            ):
                values = np.stack([col.to_numpy() for _, col in df.items()], axis=1)
            else:
                raise e from None
        return values

    def make_generator():
        for batch in self.iter_batches(
            prefetch_blocks=prefetch_blocks,
            batch_size=batch_size,
            batch_format="pandas",
            drop_last=drop_last,
        ):
            if label_column:
                targets = get_df_values(batch[label_column])

            features = None
            if feature_columns is None:
                features = get_df_values(batch)

            elif isinstance(feature_columns, list):
                if all(isinstance(column, str) for column in feature_columns):
                    if len(feature_columns) == 1: 
                        features = get_df_values(batch[feature_columns[0]])
                    else: 
                        features = get_df_values(batch[feature_columns])
                elif all(isinstance(columns, list) for columns in feature_columns):
                    features = tuple(
                        get_df_values(batch[columns]) for columns in feature_columns
                    )
                else:
                    raise ValueError(
                        "Expected `feature_columns` to be a list of strings or a "
                        "list of lists."
                    )
    
            elif isinstance(feature_columns, dict):
                features = {
                    key: get_df_values(batch[columns])
                    for key, columns in feature_columns.items()
                }
            else:
                raise ValueError(
                    "Expected `feature_columns` to be a list or a dictionary, "
                    f"but got a `{type(feature_columns).__name__}` instead."
                )

            if label_column:
                yield features, targets
            else:
                yield features

    dataset = tf.data.Dataset.from_generator(
        make_generator, output_signature=output_signature
    )

    return dataset
```

2. #25069 the [predictor code](https://github.com/ray-project/ray/blob/master/python/ray/ml/predictors/integrations/tensorflow/tensorflow_predictor.py#L128-L153)
```python
        if self.preprocessor:
            data = self.preprocessor.transform_batch(data)
            
        if isinstance(data, pd.DataFrame):
            if feature_columns:
                data = data[feature_columns[0]]
            data = data.values
            data = np.stack(data)
        else:
            data = data[:, feature_columns]

        tensor = tf.convert_to_tensor(data, dtype=dtype)
        # TensorFlow model objects cannot be pickled, therefore we use
        # a callable that returns the model and initialize it here,
        # instead of having an initialized model object as an attribute.
        model = self.model_definition()
        if self.model_weights:
            model.set_weights(self.model_weights)

        prediction = model(tensor).numpy()

        prediction_list = []
        for i in range(prediction.shape[0]): 
            prediction_list.append(prediction[i, :])

        return pd.DataFrame({"predictions": prediction_list})
```

**Comment by JiahaoYao** [comment]
my notebook is shipped, @xwjiang2010 @amogkam could some one review this PR?

**Comment by xwjiang2010** [comment]
Does the example work as it is on master? Do you need any change in tensorflow predictor? I wonder if we should wait for Balaji's change to land before this one.

**Comment by JiahaoYao** [comment]
> Does the example work as it is on master? Do you need any change in tensorflow predictor? I wonder if we should wait for Balaji's change to land before this one.

make sense to me, thanks @xwjiang2010 , let's wait and i can retest on that!

**Comment by xwjiang2010** [comment]
Balaji's PR is merged. 
@JiahaoYao Do you mind rebasing and cleaning up this one? Thanks!!

**Comment by JiahaoYao** [comment]
Hi @xwjiang2010 , if the https://github.com/ray-project/ray/issues/25554 and https://github.com/ray-project/ray/issues/25556 are resolved, the example are ready to ship.

**Comment by xwjiang2010** [comment]
@clarkzinzow

**Comment by JiahaoYao** [comment]
@xwjiang2010 @clarkzinzow  the changes are merged, ready for review!

**Review by clarkzinzow — APPROVED** [review]

**Pull request merged**
