### PR TITLE
Update cloudpickle

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

There has been a lot of changes going on the upstream (including a lot of bug fix), especially the one that drops python2 support. This PR will shorten the gap between the upstream version.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by suquark** [comment]
let's see if we can pass all tests

**Comment by pcmoritz** [comment]
We should also update cloudpickle_fast.py :)

**Comment by pcmoritz** [comment]
Ooop, you already did!

**Comment by pcmoritz** [comment]
Benchmark:
```
single client put gigabytes per second 10.84 +- 8.14
```

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
