### PR TITLE
[RLlib] Fix erroneous use of LinearSchedule (in DDPG's exploration annealing).

### PR DESCRIPTION
**Pull request by sven1977**
Erase schedules_obsoleted.py.

LinearSchedule does not clamp at initial_p and final_p values but "keeps going" beyond t=0 and t=schedule_timesteps, leading to unexpected behavior in DDPG.

DQN has undergone a similar fix a while back (PR #6973).

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
jenkins retest this please

**Comment by sven1977** [comment]
Strange "dataset is busy" error. Trying again. ...

**Comment by sven1977** [comment]
@ericl All good now (jenkins RLlib tests all ok, Travis ok'ish), please merge.

**Pull request merged**
