### PR TITLE
[k8s] Broken Command Interactivity

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

https://ray-distributed.slack.com/archives/CN2RGCHRR/p1598296004012900?thread_ts=1598049069.006900&cid=CN2RGCHRR

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by wuisawesome** [comment]
Do you mind adding a unit test to `tests/test_command_runner.py` for this?

**Comment by richardliaw** [comment]
@wuisawesome can someone from the Core team take this and push it over the finish line?

Unfortunately, I'm a bit swamped up until the release cut with some other things. Thanks!

**Review by wuisawesome — APPROVED** [review]
lol role reversal on reviewing this @richardliaw

**Review by richardliaw — COMMENTED** [review]
lgtm if tests pass - thanks for putting this together!

**Comment by yiranwang52** [comment]
The additional parentheses caused a minor issue for product, that had to be fixed by adding newline:
https://github.com/anyscale/product/pull/1137

**Comment by richardliaw** [comment]
@yiranwang52 oh its wrong?

**Comment by yiranwang52** [comment]
Well it caused problem for this one special case.
We expected the command to end with newline, but ray added a `)`.
I don't think it's a p0 bug, but it's problematic.

**Comment by wuisawesome** [comment]
I added the parentheses because I was concerned about how commands with semicolons were being parsed. Let's talk offline about this

**Pull request merged**
