### PR TITLE
[Docs] Executable notebook tutorial

### PR DESCRIPTION
**Pull request by maxpumperla**
We're introducing the usage of [MyST Notebooks](https://myst-nb.readthedocs.io/en/latest/index.html) here and demonstrate how it works by rewriting (and extending) the RLLib Serve tutorial. Benefits:

- [x] Write notebooks in markdown. Can be converted into other formats e.g. with `jupytext`
- [x] Tutorials like this have a binderhub link added to the top nav (launch button).
- [x] Notebooks get executed when docs are built, so it's impossible to have stale docs.
- [x] But locally those builds are cached so that you don't have to wait too long.
- [x] The notebook cell outputs can be shown, hidden or removed.  In particular, we can now avoid adding expected code output as comments in our scripts (which might get outdated).

We're also clarifying  #22022. 

@simon-mo let me know what you think about this. A "drawback" of this approach is that we're not using `literalinclude` anymore. The jupyter philosophy is to keep text and code in a common source. But then again, I'm not sure these snippets [here](https://github.com/ray-project/ray/tree/master/python/ray/serve/examples/doc) are actually tested anyway. 

Old tutorial: [here](https://docs.ray.io/en/latest/serve/tutorials/rllib.html)
New tutorial (preview): [here](https://ray--22030.org.readthedocs.build/en/22030/serve/tutorials/rllib.html)

### CODE REVIEW

**Comment by maxpumperla** [comment]
not entirely sure what's going on with the build, but I have a hard time believing that's caused by a md file. :D

**Comment by simon-mo** [comment]
One issue I foresee is that when building the doc in readthedocs, their server doesn't have enough resource to let us execute end to end.

**Comment by maxpumperla** [comment]
@simon-mo I've made notebook execution configurable. By default, readthedocs will not have to run them, but we can force that behaviour on CI like this:

```
RUN_NOTEBOOKS="force" sphinx-build -b html -d _build/doctrees  source _build/html
```

Not necessary right now, can be added later.

**Comment by simon-mo** [comment]
@maxpumperla this is great! I think this will definitely work in readthedocs environment now. However, how can we execute as a test case in CI now we don't have the python script anymore? It would be great if we can change the bazel rule in python/ray/serve/BUILD's `test_rllib_tutorial` to executing this. Thanks!

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
