### PR TITLE
[data] Fix ragged tensor conversion with map()

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

From https://github.com/ray-project/ray/pull/35143, we found a map() case that is not covered in our numpy support test cases.

### CODE REVIEW

**Review by raulchen — APPROVED** [review]
LGTM

**Comment by zhe-thoughts** [comment]
Thanks @ericl @raulchen . Once there's a cherry pick PR please add me and @ArturNiederfahrenhorst as assignees

**Comment by raulchen** [comment]
Once it's merged, I'll merge #35143, which needs to be cherry-picked as well.

**Comment by ericl** [comment]
The problem with the patch seems to be that our Arrow extension doesn't properly support binary dtype.

```
ray.data.range(1).map_batches(lambda x: {"x": np.array([[b"abc"]])}).show()
```

Will produce:

```
(ReadRange->MapBatches(<lambda>) pid=456982)   File "/home/eric/Desktop/ray/python/ray/air/util/tensor_extensions/arrow.py", line 339, in from_numpy
(ReadRange->MapBatches(<lambda>) pid=456982)     data_array = pa.Array.from_buffers(
(ReadRange->MapBatches(<lambda>) pid=456982)   File "pyarrow/array.pxi", line 1084, in pyarrow.lib.Array.from_buffers
(ReadRange->MapBatches(<lambda>) pid=456982) ValueError: Type's expected number of buffers (3) did not match the passed number (2).
```

**Pull request merged**
