### PR TITLE
[Dashboard][event] Basic event module

### PR DESCRIPTION
**Pull request by fyrestone**
## Why are these changes needed?

Try to make the test_events more stable.
- Fix `_update_error_info` raises an exception.  **_We should avoid pubsubing error info and log info._

## Related issue number

https://github.com/ray-project/ray/pull/16698

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Review by edoakes — APPROVED** [review]

**Comment by fyrestone** [comment]
@amogkam Can you review this PR before reverting the PR: https://github.com/ray-project/ray/pull/17004?

**Comment by amogkam** [comment]
@fyrestone #17004 is already merged since the PR it reverted introduced a flaky test `test_event` (which you can see here https://flakey-tests.ray.io/). If you can deflake the test then feel free to re-revert it.

**Comment by fyrestone** [comment]
> @fyrestone #17004 is already merged since the PR it reverted introduced a flaky test `test_event` (which you can see here https://flakey-tests.ray.io/). If you can deflake the test then feel free to re-revert it.

I have created the fix PR (this PR) to improve the test_event stability when I found the flaky, and requested you to review it. But you rejected the review and reverted the PR.

**Comment by amogkam** [comment]
Ah @fyrestone sorry I missed this context. 

The policy is to always revert the offending PR since that can be done immediately rather than wait for a fix. We can always then re-create the original PR with a fix and then merge it back in. If you can include the original PR into this one, then we can merge this.

**Comment by fyrestone** [comment]
> Ah @fyrestone sorry I missed this context.
> 
> The policy is to always revert the offending PR since that can be done immediately rather than wait for a fix. We can always then re-create the original PR with a fix and then merge it back in. If you can include the original PR into this one, then we can merge this.

There are many flaky tests, can you revert or disable them? I will merge the original PR into this one, and please review it.

**Comment by fyrestone** [comment]
@amogkam Sorry for the waiting, the fix arrives 1 day before the reverting.

**Comment by amogkam** [comment]
@fyrestone yes we really appreciate the quick fix! The thing is even though the fix was made earlier we still had to do a code review and get approvals which takes more time. Reverting the original PR just requires a rubber stamp approval and doesn't even require the CI to finish running which is why we prefer to always revert if the offending PR can be identified since we can always merge back the original PR and it minimizes the time that the build is failing.

**Pull request merged**
