### PR TITLE
[docs] Sixth cherry pick 2.5

### PR DESCRIPTION
**Pull request by angelinalg**
Docs observability cherry-picks. One observability refactor PR and three build fix PRs.
[#35816](https://github.com/ray-project/ray/pull/35816)
[#36054](https://github.com/ray-project/ray/pull/36054)
[#36112](https://github.com/ray-project/ray/pull/36112)
[#36150](https://github.com/ray-project/ray/pull/36150)

This replaces https://github.com/ray-project/ray/pull/36084.

## Why are these changes needed?

rolling out for 2.5
cc: @ArturNiederfahrenhorst @scottsun94 @rkooo567 @zhe-thoughts 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]

**Comment by ArturNiederfahrenhorst** [comment]
@zhe-thoughts This PR touches the docstrings and type annotations of a file outside the docs folder, but inside _python/ray_. Can you approve again with respect to this?

**Comment by ArturNiederfahrenhorst** [comment]
So technically this would not be a docs PR, but the changes don't carry risk afaics.
I would still like to make this explicit.

**Comment by zhe-thoughts** [comment]
Thanks for the caution @ArturNiederfahrenhorst . Could you help me understand whether this requires rebuilding the wheel? if not, I approve for picking

**Comment by ArturNiederfahrenhorst** [comment]
@zhe-thoughts This will not require rebuilding the wheel.

**Comment by zhe-thoughts** [comment]
OK to pick then. Thanks

**Pull request merged**
