### PR TITLE
[Core/GCS] remove default 100 concurrent rate limit for heartbeat

### LINKED ISSUE #20773: [Bug] Make the heartbeat handler limit -1
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Heartbeat is an important rpc and we shouldn't backpressure them. Mark them as -1 is good for now. We need to test 2k nodes with this change to measure the gain.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jon-chuang**
## Why are these changes needed?
See https://github.com/ray-project/ray/issues/20773

better scalability
## Related issue number
Closes https://github.com/ray-project/ray/issues/20773

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@iycheng anything else we should do? I think it should be sufficient to merge

**Comment by rkooo567** [comment]
Lint failure

**Comment by jon-chuang** [comment]
sry, thought I got the script to work.

Now it works.

**Comment by iycheng** [comment]
I think this is good. It'll be nice if we can check whether it helps to scale to 2k nodes.

**Comment by rkooo567** [comment]
Retrying windows test now

**Comment by jon-chuang** [comment]
I tested on local. I used Rust gRPC client to hammer gcs with heartbeat connections. Fails after 1000 connections with 
```
E0225 05:45:49.641746673  702245 tcp_server_posix.cc:215]    Failed accept4: Too many open files
E0225 05:45:54.008250784  702233 ev_epollex_linux.cc:1454]   pollset_set_add_pollset: {"created":"@1645785954.008218796","description":"Too many open files","errno":24,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/ev_epollex_linux.cc","file_line":563,"os_error":"Too many open files","syscall":"epoll_create1"}
E0225 05:45:54.008426714  702233 ev_epollex_linux.cc:1404]   assertion failed: i != pss->pollset_count
```

**Comment by rkooo567** [comment]
It’s because of number of open files. We usually recommend to set ulimit high so that we avoid this issue.

**Comment by jon-chuang** [comment]
My ulimit is unlimited. So its weird that I see this error... Maybe I'll try again after restarting.

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
