### PR TITLE
Use getppid() to check if the raylet has failed

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Given that we want to migrate to using gRPC for all RPC communication, need a different solution than using the unix domain socket to detect that the raylet has gone down.

This also removes the in-scope object ID heartbeat code given that we have implemented proper reference counting now.

cc @mehrdadn we will need a different solution on Windows as discussed.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by mehrdadn** [comment]
Sorry if this is already address (on my phone - difficult to check), but are ordering issues considered/addressed? Specifically when death is detected relative to when the final messages are received.

**Review by pcmoritz — APPROVED** [review]
This looks good to me! @mehrdadn Concerning the ordering, given that the raylet already died, we probably don't care which messages arrive at the worker and when, right?

**Comment by mehrdadn** [comment]
@pcmoritz that might very well be true. I might not have a chance to review this until late next week so I don't really know; I just mentioned it in case there's something to think about on that front.

**Comment by edoakes** [comment]
@pcmoritz is right, once the raylet dies the workers should just go down as soon as possible.

**Comment by mehrdadn** [comment]
Were there any instances in which e.g. a new raylet could claim an old worker before the worker detects the raylet's death? Or any other weird scenarios like that? I feel like I saw something like this trigger a `RAY_CHECK` or `RAY_LOG` a while ago, but I don't remember the details or whether it was on master or not.

**Comment by zhijunfu** [comment]
For migrating worker to raylet communication to grpc, what's the plan for local raylet to detect worker death timely and reliably?  Probably we should to keep the asio connection from worker to local raylet for this purpose?

**Comment by edoakes** [comment]
@mehrdadn the workers fate-share with the raylet to avoid worrying about issues like this

@zhijunfu the current plan is to use `SIGCHLD`. AFAIK that's guaranteed to be delivered and should be as timely as the connection reset

**Comment by zhijunfu** [comment]
> @zhijunfu the current plan is to use `SIGCHLD`. AFAIK that's guaranteed to be delivered and should be as timely as the connection reset

Thanks, that sounds good!

**Pull request merged**
