### PR TITLE
Raise an exception in Jenkins tests after a timeout.

### LINKED ISSUE #1436: [build system] hanging docker containers after build fails or aborts
### System information
- **Linux Ubuntu 16.04**:
- **Ray installed from source for CI builds**:

### Describe the problem
When a Ray build ends prematurely, and after test/jenkins_tests/multi_node_docker_test.py runs, it leaves behind docker containers that take ~500G of disk space.

### Source code / logs
in test/jenkins_tests/multi_node_docker_test.py:
```
        command = (["docker", "run", "-d"] + mem_arg + shm_arg + volume_arg +
                   [docker_image, "ray", "start", "--head", "--block",
                    "--redis-port=6379",
                    "--num-redis-shards={}".format(num_redis_shards),
                    "--num-cpus={}".format(num_cpus),
                    "--num-gpus={}".format(num_gpus),
                    "--no-ui"])
        print("Starting head node with command:{}".format(command))

        proc = subprocess.Popen(command,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

after speaking w/dan crankshaw about his docker testing approach, he strongly suggests the following (which i agree with):

1.  add a tag/label to each and every docker container that is launched
2.  add a final step to your tests that goes through this list of tags and explicitly kills these containers
3. set up all of your builds to be limited to one executing on a worker at any time.  this will keep builds from stomping on other ray containers.

### PR DESCRIPTION
**Pull request by robertnishihara**
This should partially/mostly fix #1436.

For each test that we run in Jenkins, this raises an exception after 10 minutes so that the test can exit gracefully and shut down the docker containers. The alternative is for Jenkins to send a sigkill or something like that to the test which prevents it from exiting gracefully.

cc @shaneknapp

### CODE REVIEW

**Comment by robertnishihara** [comment]
test this please

**Comment by robertnishihara** [comment]
@shaneknapp the Jenkins tests don't seem to be getting triggered. Any idea about this?

**Comment by shaneknapp** [comment]
it got itself wedged.  i restarted it now and it should pick up queued
builds.

On Fri, Jan 26, 2018 at 10:19 PM, Robert Nishihara <notifications@github.com

**Comment by shaneknapp** [comment]
test this please

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
