### PR TITLE
[gRPC] Improve blocking call Placement group

### PR DESCRIPTION
**Pull request by rkooo567**
This reverts commit 407db84276f86d25e3ab6aa57a2d95483c42bcd3.

## Why are these changes needed?

Use Sync methods with timeout for placement group RPCs

## Related issue number

Part 3 https://github.com/ray-project/ray/issues/20899

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
it seems like we don't support async creation anymore. To help me understand the underline reason and why the previous one failed, could you share some info here?

**Comment by rkooo567** [comment]
Placement group creation was always sync (there was no asyncCreatePlacementGrouo
P)!

**Comment by iycheng** [comment]
So is the update in this one compared with previous one is just the async -> sync and get rid of std future, right?

**Comment by rkooo567** [comment]
Yes. Correct! Another difference is this will have the proper timeout implementatiob

**Review by fishbone — APPROVED** [review]

**Comment by rkooo567** [comment]
Failing tests seem unrealted

**Pull request merged**
