### PR TITLE
[core][state] Add head node flag `is_head_node` to state API and GcsNodeInfo

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
There have been requests for checking which/if a node is the head node. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
cc @alanwguo @architkulkarni after this PR, the node data will contain `is_head` in the field. Can you guys change your head-discovery code after we merge this PR from job submission + dashboard?

**Comment by rickyyx** [comment]
Tests failure unrelated.

**Comment by rickyyx** [comment]
> Thanks for this PR!
> 
> @rkooo567 last time we discussed this you raised a concern that the state API depends on the jobs API so the jobs API should not depend on the state API, and also that the jobs API is critical so it shouldn't depend on the state API. Is this still a concern? I think it would still be an improvement from the current approach (which is to dump the head node id in the internal KV
> 
> https://github.com/ray-project/ray/blob/8ce253e5c96cb6003c5fb12aa3ee1a1e46c443f2/dashboard/modules/node/node_head.py#L164-L172
> 
> )

Yeah, I think decoupling is better. We could get it from GCS rather than state API I guess.

**Review by scv119 — APPROVED** [review]

**Comment by rkooo567** [comment]
Yeah I meant to access the `is_head` field from the GCS directly! not from the state API

**Pull request merged**
