### PR TITLE
[AIR] Don't add Trainer resources when running on Colab

### PR DESCRIPTION
**Pull request by amogkam**
Signed-off-by: Amog Kamsetty <amogkamsetty@yahoo.com>

Google Colab only has 2 CPUs. Because of this resource scarcity, we have to be careful on where these resources are allocated and users need to be hyper aware on all the tasks and actors that are reserving resources.

In AIR, the Trainer reserves 1 CPU by default which is unintuitive for users. As a stopgap solution, we special case when running on Google Colab so that the trainer does not reserve any resources, and `num_workers=2` works for data parallel training. As Google Colab is not distributed, the scalability concerns on doing this are no longer applicable.

This has been a headache for me when running AIR on Google Colab and also for users as well: https://discuss.ray.io/t/ray-trainer-looking-for-more-cpus-than-that-of-its-initialized-on/7696

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Yard1** [comment]
Hmm, I wonder if it would make sense to extend this to any single-node cluster case. What do you think?

**Comment by amogkam** [comment]
yeah I don't think ray provides good abstractions on figuring out cluster size and autoscaling behavior. Let's prioritize Colab for now since it has the most resource scarcity (only 2 CPUs), compared to other instances which have like 4-16. 

We can cover all single node cases in a follow up.

**Comment by amogkam** [comment]
Most people try out the AIR examples on either Colab or their own laptop. Laptops have 16 CPUs, so this is less of a problem. However, we can't have users churn if basic workflows don't work on Colab.

**Comment by Yard1** [comment]
This all makes sense, let's follow up later

**Review by Yard1 — APPROVED** [review]

**Pull request merged**
