### PR TITLE
[GCP] Allow Google Compute Engine instance templates

### PR DESCRIPTION
**Pull request by max0x7ba**
## Why are these changes needed?
Allow Google Compute Engine instance templates.

Google Compute Engine templates may be easier to configure and update using the Google Console UI.

## Checks
Tested in Google Compute Engine that it does create node instances using the template.

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ijrsvt** [comment]
Hey @max0x7ba Thanks for contributing this!! Two quick things:
1. It looks like lint is failing (see the results [here](https://buildkite.com/ray-project/ray-builders-pr/builds/13796#220a2a48-b4cd-4591-b74a-288f648aa855)). You can run it locally by running `./scripts/format.sh`
2. Have you tested this locally?

**Comment by max0x7ba** [comment]
> Hey @max0x7ba Thanks for contributing this!! Two quick things:
> 
> 1. It looks like lint is failing (see the results [here](https://buildkite.com/ray-project/ray-builders-pr/builds/13796#220a2a48-b4cd-4591-b74a-288f648aa855)). You can run it locally by running `./scripts/format.sh`

`./scripts/format.sh` reports errors on the existing code, not my changes. 

In other words, the existing code in the repo doesn't pass `./scripts/format.sh` checks.

> 2. Have you tested this locally?

Yes, I use Google Compute Engine templates to create head and worker node instances and this issue was a blocker for me.

**Comment by Yard1** [comment]
Should we document this addition in the example config?

**Comment by max0x7ba** [comment]
> Should we document this addition in the example config?

My expectation was that `sourceInstanceTemplate` was supported out of the box. But it wasn't due to the fact that it must be passed as an extra argument to `instances.insert` call rather than in `config` dictionary. From this perspective it is a bugfix rather than a new feature.

**Comment by Yard1** [comment]
Merging master should fix lint

**Comment by Yard1** [comment]
I think something got messed up when merging here

**Comment by max0x7ba** [comment]
> I think something got messed up when merging here

It did indeed. Let me make another PR.

**Comment by Yard1** [comment]
@max0x7ba You can also try force pushing to this branch after fixing locally, but a new PR also works

**Comment by max0x7ba** [comment]
> @max0x7ba You can also try force pushing to this branch after fixing locally, but a new PR also works

That worked like a charm. TIL.

**Comment by Yard1** [comment]
Generally you want to avoid force pushing, but it does have its uses!

**Comment by max0x7ba** [comment]
> Generally you want to avoid force pushing, but it does have its uses!

Yes, the main use case is rebasing the change on top of the latest master.

**Comment by ijrsvt** [comment]
Flaky test is known to be failing on the branch this has been merged with!

**Review by ijrsvt — APPROVED** [review]
LGTM!

**Pull request merged**
