### PR TITLE
[RLlib] Rename all np.product usage to np.prod

### PR DESCRIPTION
**Pull request by MaxVanDijck**
## Why are these changes needed?

The as of numpy version 1.15.0 `np.product` was made to be an alias of `np.prod`, and is now deprecated in numpy 2.0.0 
This pr switches all usage of `np.product` to use `np.prod`

refer: https://stackoverflow.com/a/49864286

## Related issue number
https://github.com/ray-project/ray/issues/46250

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scottjlee — APPROVED** [review]
Approving Data change

**Review by simonsays1980 — APPROVED** [review]
LGTM. Very nice PR. Thanks a ton @MaxVanDijck! Could you merge the master again and push in the branch? Some tests are not passing, yet.

**Comment by MaxVanDijck** [comment]
> LGTM. Very nice PR. Thanks a ton @MaxVanDijck! Could you merge the master again and push in the branch? Some tests are not passing, yet.

Done, looks like tests are passing now

**Review by sven1977 — APPROVED** [review]
LGTM from RLlib perspective.

**Comment by sven1977** [comment]
Auto-merge enabled. Just waiting for the last test to pass ...

**Comment by MaxVanDijck** [comment]
Many `rllib_contrib` tests are failing due to the pinned tensorflow version not being compatible with numpy 2.0.0 so I have added `numpy<2` to the `requirements.txt` and `pyproject.toml` files

**Pull request merged**
