### PR TITLE
[dashboard] Rename "new_dashboard" -> "dashboard"

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

It hasn't been "new" for quite awhile :)

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@architkulkarni can you give me codeowner stamp pls?

**Review by architkulkarni — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Review by ijrsvt — APPROVED** [review]
LGTM! Thanks for doing this!!

**Comment by edoakes** [comment]
Hmm looks like I need a second codeowner stamp from @ericl or @richardliaw for some reason...

**Review by richardliaw — APPROVED** [review]
stamp

**Pull request merged**
