### PR TITLE
Add buffering to object spilling

### PR DESCRIPTION
**Pull request by kennethlien**
An optional argument, `buffer_size` has been added to `object_spilling_config` to enable the user to customize the buffer size used to write objects when spilling. On hard disks, this will greatly increase write speeds and potentially increase read speeds due to locality for sequential reads.

## Why are these changes needed?
This change is needed for object fusing to see performance increases on HDD. Currently, smaller object writes are slow even with fusing since the writes are not buffered (negating the point of fusing). Benchmarks show that while the default is sufficient for fast SSDs, on a slow HDD, increasing the buffer size reduces write times by several magnitudes.

### Performance Changes
A microbenchmark where 500KB objects were produced (then spilled) and consumed to observe changes in object fusing/spilling.

| Run | Produce (s) | Consume (s) | Total (s) |
| -- | -- | -- | -- |
| Baseline (original) | 347.332281 | 355.611272 | 705.560750 |
| Baseline (w/ fix) | 181.815852 | 347.692850 | 532.847759 |
| No fusing (original) | 453.574554 | 525.047998 | 981.620108 |
| No fusing (w/ fix) | 452.614848| 519.787698 | 975.412639 |

The baseline runs should be notably faster due to object fusing reducing I/O requests. With the fix, Ray's defaults allow this microbenchmark to have a 48% time reduction with negligible impact on runtime when fusing is disabled.

See [this followup](https://github.com/ray-project/ray/pull/22618#issuecomment-1054838715) for information on the differences between SSD and HDD performance with different buffer sizes.

## Related issue number
N/A

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Thanks for the contribution! Could you also contribute a perf test to show the effect?

**Comment by scv119** [comment]
this is pretty cool!

**Review by scv119 — APPROVED** [review]

**Comment by stephanie-wang** [comment]
Nice find!

**Comment by franklsf95** [comment]
@jjyao how should we contribute a performance test? We have a benchmark script but not sure where we should put it in the ray repo. Do you have an example?

Also @kennethlien, in addition to showing the perf increase for 500KB objects, can you also make sure large objects (say 2MB) spilling performance stays the same, and maybe one more test for 100KB objects to show that buffering doesn't cause performance degradation?

We should also mention that these tests were done on AWS `sc1` HDD volumes, which peaks at 250 IOPS and 250 MiB/s throughput. The buffering effect will be less significant on regular `gp2` or `gp3` SSDs, but I think is still nice to have.

Another followup is that we might also want to do this with `smart_open` spill options (e.g. S3). We'll run some performance tests and come back with a fix.

**Comment by stephanie-wang** [comment]
For @jjyao's request, you can add a microbenchmark to [this file](https://github.com/ray-project/ray/blob/master/python/ray/_private/ray_perf.py#L126) (link to an existing test that you can copy). You can test just the write path instead of write and read.

**Comment by rkooo567** [comment]
This is nice! Btw, how is 1KB chosen as a default buffer size (should we find a better default)? Also, what's the python default?

**Comment by franklsf95** [comment]
@rkooo567 The Python default buffer size is usually 4KB or 8KB, according to https://docs.python.org/3/library/functions.html#open and https://docs.python.org/3/library/io.html#io.DEFAULT_BUFFER_SIZE.

We chose 1MB because for HDDs we believe that's a size that gives good sequential write performance. For example, AWS [https://aws.amazon.com/ebs/volume-types/] provides the max HDD throughput based on 1MB I/O size. For SSDs it doesn't matter that much I think.

**Comment by stephanie-wang** [comment]
> @rkooo567 The Python default buffer size is usually 4KB or 8KB, according to https://docs.python.org/3/library/functions.html#open and https://docs.python.org/3/library/io.html#io.DEFAULT_BUFFER_SIZE.
> 
> We chose 1MB because for HDDs we believe that's a size that gives good sequential write performance. For example, AWS [https://aws.amazon.com/ebs/volume-types/] provides the max HDD throughput based on 1MB I/O size. For SSDs it doesn't matter that much I think.

Oh I didn't realize that there is also buffering by default. Does that mean the default size just isn't the right one? I do agree with Sang we should do a quick test with other sizes too then. Hopefully we can avoid overfitting to this microbenchmark.

**Comment by franklsf95** [comment]
@stephanie-wang yeah, the default buffer size is just the OS page size, I think. How about this: we test spilling ~1GB of objects of sizes {100MB, 10MB, 1MB, 100KB, 10KB}, using buffer sizes {10MB, 1MB, 100KB, default}, on both HDD and SSD EBS volumes on S3 and check their performance?

**Comment by rkooo567** [comment]
Sounds good to me! Btw, let's say we have a buffer size 10MB, and we only fuse 1MB. How is write going to happen in this case? (is it happening before the spill RPC is replied?)

**Comment by franklsf95** [comment]
> Sounds good to me! Btw, let's say we have a buffer size 10MB, and we only fuse 1MB. When is write going to happen in this case? (is it happening before the spill RPC is replied?)

Yes Python will flush the buffer when the file is closed, which happens at the end of this function and before the RPC reply.

**Comment by kennethlien** [comment]
After profiling on SSD vs. HDD, it appears that the default buffer size is best on SSD. HDD strongly benefits from having a larger buffer though. I'll be closing this PR and will work on adding buffer size to `object_spilling_config` so that the user can customize to their content. Some metrics are pasted below:

SSD Spilling Results:
```
Buffer size: -1
10000 objects of size 100.0KB -- Total time: 0.44803738594055176
1000 objects of size 1000.0KB -- Total time: 0.45813822746276855
100 objects of size 10.0MB -- Total time: 0.47328996658325195
10 objects of size 100.0MB -- Total time: 0.6941838264465332

Buffer size: 100000
10000 objects of size 100.0KB -- Total time: 3.212421417236328
1000 objects of size 1000.0KB -- Total time: 3.457113027572632
100 objects of size 10.0MB -- Total time: 3.1422245502471924
10 objects of size 100.0MB -- Total time: 3.4049835205078125

Buffer size: 1000000
10000 objects of size 100.0KB -- Total time: 3.816929578781128
1000 objects of size 1000.0KB -- Total time: 3.8391289710998535
100 objects of size 10.0MB -- Total time: 3.8370420932769775
10 objects of size 100.0MB -- Total time: 3.868173599243164

Buffer size: 10000000
10000 objects of size 100.0KB -- Total time: 3.835341215133667
1000 objects of size 1000.0KB -- Total time: 3.820946216583252
100 objects of size 10.0MB -- Total time: 3.867074489593506
10 objects of size 100.0MB -- Total time: 3.8603475093841553

Buffer size: 100000000
10000 objects of size 100.0KB -- Total time: 3.825284242630005
1000 objects of size 1000.0KB -- Total time: 3.8354034423828125
100 objects of size 10.0MB -- Total time: 3.8551316261291504
10 objects of size 100.0MB -- Total time: 3.8573572635650635
```

HDD Spilling Results:
```
Buffer size: -1
10000 objects of size 100.0KB -- Total time: 75.09691572189331
1000 objects of size 1000.0KB -- Total time: 11.943308353424072
100 objects of size 10.0MB -- Total time: 4.772138357162476
10 objects of size 100.0MB -- Total time: 3.770331859588623

Buffer size: 100.0KB
10000 objects of size 100.0KB -- Total time: 76.09500193595886
1000 objects of size 1000.0KB -- Total time: 11.948934555053711
100 objects of size 10.0MB -- Total time: 4.793262004852295
10 objects of size 100.0MB -- Total time: 3.7462708950042725

Buffer size: 1000.0KB
10000 objects of size 100.0KB -- Total time: 11.936119079589844
1000 objects of size 1000.0KB -- Total time: 11.9759202003479
100 objects of size 10.0MB -- Total time: 4.757033348083496
10 objects of size 100.0MB -- Total time: 3.749232769012451

Buffer size: 10.0MB
10000 objects of size 100.0KB -- Total time: 4.767698287963867
1000 objects of size 1000.0KB -- Total time: 4.752996921539307
100 objects of size 10.0MB -- Total time: 4.7645933628082275
10 objects of size 100.0MB -- Total time: 3.7461647987365723

Buffer size: 100.0MB
10000 objects of size 100.0KB -- Total time: 3.818115711212158
1000 objects of size 1000.0KB -- Total time: 3.802107572555542
100 objects of size 10.0MB -- Total time: 3.771754026412964
10 objects of size 100.0MB -- Total time: 3.7340433597564697
```

**Comment by kennethlien** [comment]
After profiling on SSD vs. HDD, it appears that the default buffer size is best on SSD. HDD strongly benefits from having a larger buffer though. I'll be reworking this PR to add buffer size to `object_spilling_config` so that the user can customize to their content. Some metrics are pasted below:

SSD Spilling Results:
```
Buffer size: -1
10000 objects of size 100.0KB -- Total time: 0.44803738594055176
1000 objects of size 1000.0KB -- Total time: 0.45813822746276855
100 objects of size 10.0MB -- Total time: 0.47328996658325195
10 objects of size 100.0MB -- Total time: 0.6941838264465332

Buffer size: 100000
10000 objects of size 100.0KB -- Total time: 3.212421417236328
1000 objects of size 1000.0KB -- Total time: 3.457113027572632
100 objects of size 10.0MB -- Total time: 3.1422245502471924
10 objects of size 100.0MB -- Total time: 3.4049835205078125

Buffer size: 1000000
10000 objects of size 100.0KB -- Total time: 3.816929578781128
1000 objects of size 1000.0KB -- Total time: 3.8391289710998535
100 objects of size 10.0MB -- Total time: 3.8370420932769775
10 objects of size 100.0MB -- Total time: 3.868173599243164

Buffer size: 10000000
10000 objects of size 100.0KB -- Total time: 3.835341215133667
1000 objects of size 1000.0KB -- Total time: 3.820946216583252
100 objects of size 10.0MB -- Total time: 3.867074489593506
10 objects of size 100.0MB -- Total time: 3.8603475093841553

Buffer size: 100000000
10000 objects of size 100.0KB -- Total time: 3.825284242630005
1000 objects of size 1000.0KB -- Total time: 3.8354034423828125
100 objects of size 10.0MB -- Total time: 3.8551316261291504
10 objects of size 100.0MB -- Total time: 3.8573572635650635
```

HDD Spilling Results:
```
Buffer size: -1
10000 objects of size 100.0KB -- Total time: 75.09691572189331
1000 objects of size 1000.0KB -- Total time: 11.943308353424072
100 objects of size 10.0MB -- Total time: 4.772138357162476
10 objects of size 100.0MB -- Total time: 3.770331859588623

Buffer size: 100.0KB
10000 objects of size 100.0KB -- Total time: 76.09500193595886
1000 objects of size 1000.0KB -- Total time: 11.948934555053711
100 objects of size 10.0MB -- Total time: 4.793262004852295
10 objects of size 100.0MB -- Total time: 3.7462708950042725

Buffer size: 1000.0KB
10000 objects of size 100.0KB -- Total time: 11.936119079589844
1000 objects of size 1000.0KB -- Total time: 11.9759202003479
100 objects of size 10.0MB -- Total time: 4.757033348083496
10 objects of size 100.0MB -- Total time: 3.749232769012451

Buffer size: 10.0MB
10000 objects of size 100.0KB -- Total time: 4.767698287963867
1000 objects of size 1000.0KB -- Total time: 4.752996921539307
100 objects of size 10.0MB -- Total time: 4.7645933628082275
10 objects of size 100.0MB -- Total time: 3.7461647987365723

Buffer size: 100.0MB
10000 objects of size 100.0KB -- Total time: 3.818115711212158
1000 objects of size 1000.0KB -- Total time: 3.802107572555542
100 objects of size 10.0MB -- Total time: 3.771754026412964
10 objects of size 100.0MB -- Total time: 3.7340433597564697
```

**Review by stephanie-wang — APPROVED** [review]
Awesome work with the benchmarking!

**Comment by rkooo567** [comment]
Thanks for this PR/benchmark @kennethlien! It is really awesome!

**Pull request merged**
