### PR TITLE
Fix numpy int/bool dtype references

### LINKED ISSUE #31258: [Datasets] numpy 1.24 breaks np.int, np.long which are used in tests
We need to remove usage of these deprecated attributes (deprecated in 1.20, broken in 1.24). We pinned numpy to <1.24.0 to get around this, will need to fix our tests before we unpin numpy.

`AttributeError: module 'numpy' has no attribute 'long'` seen in https://github.com/ray-project/ray/issues/31193. `AttributeError: module 'numpy' has no attribute 'int'` seen in https://github.com/ray-project/ray/issues/31194.

### PR DESCRIPTION
**Pull request by krfricke**
Signed-off-by: Kai Fricke <kai@anyscale.com>

## Why are these changes needed?

Numpy version 1.24.0 removed aliases for `numpy.int` and `numpy.bool` to `numpy.int_` and `numpy.bool_`, respectively. We are using these deprecated aliases in our code. This PR updates the Ray repo to use the underscore properties/methods instead.

This will resolve some of the incompatibilities we currently experience with numpy >= 1.24

## Related issue number

Related to #31240

Closes #31258

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by avnishn — APPROVED** [review]
All good from RLlib

**Review by cadedaniel — APPROVED** [review]
Nice simple fix!

**Comment by cadedaniel** [comment]
Feel free to mark this as closing https://github.com/ray-project/ray/issues/31258

**Review by sven1977 — APPROVED** [review]
LGTM (only checked RLlib files). Thanks for the fix @krfricke !

**Comment by sven1977** [comment]
Sorry @avnishn , accidentially requested another review from you. Please ignore :)

**Review by scv119 — APPROVED** [review]

**Review by ericl — APPROVED** [review]

**Pull request merged**
