### PR TITLE
[CherryPick][Serve] Http proxy & router & handle to support multiplex impl (#35399)

### PR DESCRIPTION
**Pull request by sihanwang41**
- Support handle.options(multiplexed_model_id="")
- Http proxy to extract model id on the fly
- Choose correct replica based on information.
- nit: Move handle metrics pusher to router.

## Why are these changes needed?

cherry-pick pr #35399

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sihanwang41** [comment]
^^ @zhe-thoughts for cherry-picking the multiplexed impl.

**Comment by zhe-thoughts** [comment]
Hi @sihanwang41 was there any conflict when you `git cherry-pick`? If so I'd like to review those conflicts. Otherwise, +1

**Comment by sihanwang41** [comment]
> Hi @sihanwang41 was there any conflict when you `git cherry-pick`? If so I'd like to review those conflicts. Otherwise, +1

Nope, I don't change anything code.  However it is failing the ci.. retrying.

**Comment by sihanwang41** [comment]
test_standalone2 is unrelated, it is failing on the 2.5.0 branch.

**Comment by zhe-thoughts** [comment]
@sihanwang41 let me know when the PR is ready for reviewing / merging. Thanks

**Comment by sihanwang41** [comment]
> @sihanwang41 let me know when the PR is ready for reviewing / merging. Thanks

Hi @zhe-thoughts , it is ready now. No code change, test failure not reteated.

**Review by zhe-thoughts — APPROVED** [review]
Approved for picking into 2.5.0

**Pull request merged**
