### PR TITLE
[ci/bazel][2] bazelize all other ray_release tests

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?
Bazelize all other ray-release tests

## Checks
- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests

### CODE REVIEW

**Review by aslonnie — COMMENTED** [review]
while I welcome the direction, can we try to land this first:

https://github.com/ray-project/ray/pull/34689

otherwise I will spend something like another day to trace the dependencies of these tests..

**Comment by can-anyscale** [comment]
Ah totally, let's finish the other one first

**Review by krfricke — APPROVED** [review]

**Comment by krfricke** [comment]
Conflicting right now, and looks like we have a duplicate:

```
Error in py_test: py_test rule 'test_bisect' in package 'release' conflicts with existing py_test rule, defined at /ray/release/BUILD:384:8
```

**Comment by ollie-iterators** [comment]
File "/tmp.6vT99Y5lSm/ci/lint/check-bazel-team-owner.py", line 50, in <module>
--
  | perform_check(raw_xml_string)
  | File "/tmp.6vT99Y5lSm/ci/lint/check-bazel-team-owner.py", line 23, in perform_check
  | tree = ET.fromstring(raw_xml_string)
  | File "/opt/miniconda/lib/python3.7/xml/etree/ElementTree.py", line 1316, in XML
  | return parser.close()
  | xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by can-anyscale** [comment]
Rebase, resolve conflicts

**Review by aslonnie — APPROVED** [review]

**Review by aslonnie — APPROVED** [review]

**Comment by krfricke** [comment]
One linter error left:

```




Exception: Cannot find owner for tests ['//release:test_anyscale_job_manager', '//release:test_template'], please add `team:*` to the tags.
 

<br class="Apple-interchange-newline">
```

**Comment by can-anyscale** [comment]
<div><br/>via <a href="https://giphy.com/afv/">America&#x27;s Funniest Home Videos</a> on <a href="https://giphy.com/gifs/afv-funny-fail-lol-3o7ZesJdQccI0sO3fy">GIPHY</a></div>

**Pull request merged**
