### PR TITLE
[microbenchmark] avoid noisy neighbor

### LINKED ISSUE #22045: [Release 1.11.0][Core] plasma performance regression (`single_client_put_gigabytes` -50%)
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://github.com/ray-project/ray/pull/22041#discussion_r797065162 we noticed regression in plasma performance regression in ray 1.10.rc

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

see https://github.com/ray-project/ray/issues/22045, add sleep between benchmark tests avoid noisy neighbor tests.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Maybe we should create a follow up issue to fix the root cause?

**Comment by scv119** [comment]
yes, I’ll follow up!

**Comment by jjyao** [comment]
Do we know the root cause?

**Comment by scv119** [comment]
still under investigation, seem this issue https://github.com/ray-project/ray/issues/22045

**Pull request merged**
