### PR TITLE
[ci] Add a script to login to gcloud docker registry

### PR DESCRIPTION
**Pull request by can-anyscale**
Add a script that can be run in buildkite machine to use AWS credential to login into gcloud docker registry

Test:
- Run locally/buildkite

### CODE REVIEW

**Review by aslonnie — COMMENTED** [review]
where is this script being used? any proof that the script works?

**Comment by can-anyscale** [comment]
It's the copy of this one https://github.com/ray-project/buildkite-ci-stack/pull/96. It's currently used in release test pipeline, as a list of command in buildkite.

**Comment by aslonnie** [comment]
ah, got it! you would need to fix the lints though

**Review by aslonnie — APPROVED** [review]

**Comment by can-anyscale** [comment]
fixed lint, and I think I requested review from @aslonnie by mistake

**Pull request merged**
