### PR TITLE
[grpc] change  from "worker get task" to "raylet assign task to worker"

### PR DESCRIPTION
**Pull request by zhijunfu**
## What do these changes do?

Currently worker calls GetTask to fetch a task from raylet, executes it, and then calls GetTask again to fetch the next one. To support direct actor call, the worker needs to be able to receive tasks from other workers as well as raylet. For the first step, this PR adds a grpc server to the worker, and changes raylet to push tasks to worker, instead of worker calling GetTask on it own.

To make review easier, this change is broken up to 2 PRs:

PR 1:   https://github.com/ray-project/ray/pull/5054 
Convert RayletClient references to unique_ptr. Add a gRPC server to the worker that registers with the raylet (but no communication through here yet).

PR 2:  
Convert GetTasks to have the raylet push tasks to the worker.
This would depend on PR1

## Related issue number

#5029 

## Linter

- [Y] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by zhijunfu** [comment]
@raulchen @robertnishihara @pcmoritz @stephanie-wang @ericl

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Sorry I'm new to this code, but it would be really helpful for me if you could break up this PR into smaller chunks. Here is what I think would make sense, and let me know what you think:
1. Convert `RayletClient` references to `unique_ptr`.
2. Add a gRPC server to the worker that registers with the raylet (but no communication through here yet).
3. Convert `GetTasks` to have the raylet push tasks to the worker.

PR 1 is independent, but PR 3 would depend on PR 2.

**Comment by zhijunfu** [comment]
@stephanie-wang  Thanks for the comments. Agreed that breaking up the PR would make review easier.  PR 1 is pretty straightforward, how about I combine PR1 & PR2 into one, and leave PR3 as a separate one?

**Comment by stephanie-wang** [comment]
> @stephanie-wang Thanks for the comments. Agreed that breaking up the PR would make review easier. PR 1 is pretty straightforward, how about I combine PR1 & PR2 into one, and leave PR3 as a separate one?

Sure, that sounds perfect!

Also, do you have ideas for how we should test this code? It will probably be some time still before we can integrate fully with the Python worker API, so we won't be able to take advantage of the integration tests in Python. It would be great if we could include some tests for these PRs.

**Comment by zhijunfu** [comment]
> Sure, that sounds perfect!
> 
> Also, do you have ideas for how we should test this code? It will probably be some time still before we can integrate fully with the Python worker API, so we won't be able to take advantage of the integration tests in Python. It would be great if we could include some tests for these PRs.

For the testing, we already has some basic test cases in `core_worker_test.cc `, which include scenarios like submitting tasks (both actor tasks and normal tasks) that will get executed remotely, or getting objects from other nodes. I think the basic functionality will be covered in C++ tests which will be included together with the functionality implementation, while more complex scenarios will be covered by existing python/java test. btw @kfstorm is working on migrating java worker to core worker architecture, when that is ready we can leverage java's integration tests and would have a much better coverage.

**Comment by stephanie-wang** [comment]
Sounds good!

**Comment by zhijunfu** [comment]
@stephanie-wang FYI. PR 1 is here. https://github.com/ray-project/ray/pull/5054

**Comment by stephanie-wang** [comment]
> @stephanie-wang FYI. PR 1 is here. #5054

Thanks, I'm closing this one!

**Pull request closed without merging**
