### PR TITLE
Fix missing __init__ for wheels

### PR DESCRIPTION
**Pull request by ericl**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by clarkzinzow — APPROVED** [review]

**Review by richardliaw — APPROVED** [review]

**Comment by ericl** [comment]
Build seems sane so merging as hotfix

**Comment by waleedkadous** [comment]
@ericl Can you help me understand how this passed tests? 

Can we write a test to prevent this happening in future?

**Comment by ericl** [comment]
@simon-mo the issue as I understand is that it was a problem in the wheel upload process. Is it possible to add some sanity check to the wheel build job that tests you can install / ray.init() a wheel?

**Comment by simon-mo** [comment]
They are actually tested https://github.com/ray-
project/ray/blob/master/ci/travis/test-wheels.sh#L24-L25

On March 11, 2021, GitHub ***@***.***> wrote:
> @simon-mo <https://github.com/simon-mo> the issue as I understand is

> that it was a problem in the wheel upload process. Is it possible to

> add some sanity check to the wheel build job that tests you can
> install / ray.init() a wheel?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/ray-

project/ray/pull/14615#issuecomment-796959197>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AFBD7AZHEC26BXTUPDSSVNLTDD6S7ANCNFSM4Y7HUY6Q>.

**Comment by ericl** [comment]
Got it, so it was just my fault not checking the wheel status here. It infrequently breaks so I tend to ignore it :)

Separately, I think downstream consumers of nightly should run sanity checks (import ray; ray.init()) before auto ingesting new nightly builds.

**Comment by waleedkadous** [comment]
Can we communicate when it fails more effectively, e.g. have it send an e-mail / page when it happens? I can't see from the code where buildkite failures are surfaced.

**Pull request merged**
