### PR TITLE
Fix Cloudpickle losing parents of types defined in __main__ if an ancestor used a type annotation

### PR DESCRIPTION
**Pull request by andenrx**
## Why are these changes needed?

When ray cannot find a valid import for a type (ie. the type was defined in `__main__`), it pickles the object by providing a skeleton class function. This function creates a new class on the remote that is intended to be identical to the local version. It chooses the parents of the type through the `_get_bases` function. Currently the function takes `__orig_bases__` if it is defined and uses `__bases__` as a fallback. However, `__orig_bases__` is populated by the most recent type annotated ancestor (ie `Generic[T]`), which might not necessarily be the parents. Meanwhile `__bases__` is always parents. For this reason, objects can behave differently remotely vs locally. 

Suppose we have:
```
class A(Generic[T]): pass
class B(A): pass
```
In this case we have `B.__bases__ == (A,)` (the parent) and `B.__orig_bases__ = (Generic[T],)` (the most recent ancestor with type annotations).
However, if we move `B` to a worker, we end up with an inheritance structure of `Generic[T] => B` rather than `Generic[T] => A => B` like what we have locally.
This is quite problematic as `isinstance(B, A)` will give `True` locally and `False` remotely. Additionally, `super` calls will fail and any methods defined for A but not B will be inaccessible for remote B objects. 

More detail on the issue is included in https://github.com/ray-project/ray/issues/22552 along with reproducible code.

My solution is to always use `__bases__` for the parents and then copy over the `__orig_bases__` meta data if it exists.

## Related issue number

https://github.com/ray-project/ray/issues/22552 [Bug] Cloudpickle losing parents of types defined in `__main__` if an ancestor used a type annotation 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
@ericl @simon-mo should we fix the upstream (https://github.com/cloudpipe/cloudpickle) instead and pull the change?

**Comment by simon-mo** [comment]
cc @suquark

**Comment by suquark** [comment]
This fix seems valid to me. But we should probably also post to the upstream to see the opinion of the cloudpickle maintainers.

**Comment by suquark** [comment]
@andenrx I think the recent fix from upstream should have addressed your issue: https://github.com/cloudpipe/cloudpickle/pull/448. Could you confirm that? Thanks!

**Comment by andenrx** [comment]
@suquark Yeah, that should fix it. 

Although is there a reason why there's two different codebases for cloudpickle as opposed to just making it a dependency for ray?

**Comment by suquark** [comment]
@andenrx This is because it usually takes cloudpickle several months for a release, but Ray almost releases monthly. Also the changes in cloudpickle often breaks Ray. So we decide to ship our own version to include latest patches and exclude problematic changes.

**Comment by scv119** [comment]
cc @gjoliver @avnishn

**Comment by scv119** [comment]
@suquark looks this blocks tune upgrading to latest gym. should we merge this PR or upgrade to latest cloudpickle?

**Review by avnishn — APPROVED** [review]

**Review by scv119 — APPROVED** [review]

**Comment by rkooo567** [comment]
Waiting for https://github.com/ray-project/ray/issues/23661

**Comment by scv119** [comment]
https://github.com/ray-project/ray/issues/23661 is not really a blocker. but we need to make sure if we revert the format changes we don't accidentally revert this one.

**Pull request merged**
