### PR TITLE
[RLLib] RE3 exploration algorithm TF2 framework support

### PR DESCRIPTION
**Pull request by n30111**
## Why are these changes needed?

This fixes the numpy  data type issue while using `RE3` with `tf2` framework.  I have added a test for `tf2` training in the test file. 

## Related issue number

N/A
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by gjoliver — APPROVED** [review]

**Comment by n30111** [comment]
@gjoliver I have rebased the code, please check.

**Review by gjoliver — APPROVED** [review]

**Comment by sven1977** [comment]
Hey @n3011 , thanks so much for the PR! Could you pull from master again and resolve the conflicts? Then we can merge this.

**Comment by n30111** [comment]
Hi @gjoliver @sven1977 Any actions required my side in this PR? It would be great to have this feature in ray 2.0. Thanks.

**Comment by gjoliver** [comment]
thanks, I will find someone to get this merged.

**Pull request merged**
