### PR TITLE
[rllib] Support * import

### PR DESCRIPTION
**Pull request by richardliaw**
Support * import for rllib;

`from ray.rllib import *`

### CODE REVIEW

**Comment by robertnishihara** [comment]
Is this actually desirable? If I understand correctly, this introduces two separate ways to use the RLlib API, e.g., I could do `rllib.env.AsyncVectorEnv` or I could do `rllib.AsyncVectorEnv`, and now I'm not sure which one is preferable. Ideally there would be a single way to do things.

Having things grouped together hierarchically feels a bit cleaner to me.

Also, we don't exactly want to encourage people to do `import *`..

**Comment by richardliaw** [comment]
Good point - the target use case for this are upcoming demos, and also tutorial notebooks that we would release for RLlib.

From the [python docs](https://docs.python.org/3.6/tutorial/modules.html):
> Note that in general the practice of importing * from a module or package is frowned upon, since it often causes poorly readable code. However, it is okay to use it to save typing in interactive sessions.

I'm not married to this change, as it would probably reduce the number of imports from 3 to 1...

**Comment by robertnishihara** [comment]
I see, I don't think it makes sense to optimize for the demos.

**Comment by richardliaw** [comment]
Ok, I'll revert for now and if @ericl has a strong opinion later it wouldn't be hard change back.

**Comment by robertnishihara** [comment]
k, sounds good

**Comment by ericl** [comment]
Let's just do this in https://github.com/ray-project/ray/pull/2348/files

**Pull request closed without merging**
