### PR TITLE
[Data/AIR] Move `TensorExtension` to `ray.air` for use in other packages

### PR DESCRIPTION
**Pull request by amogkam**
Moves Tensor extensions to `ray.air` to facilitate their use in other Ray libraries (AIR, Serve).

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
Can we move this to `ray.air` instead of `ray.util`? The reason is util can be agnostic of ML libraries.

**Comment by amogkam** [comment]
Sure I can make the change. My understanding was that these extensions are useful for general data related things, not specifically for ML use cases.

**Comment by simon-mo** [comment]
How do we deal with conditional import/dependency here? Is pyarrow and pandas a core dep for Ray AIR? In the context of Serve, should we depend on all Ray AIR dependencies as well?

**Comment by clarkzinzow** [comment]
@simon-mo As long as consumers of the tensor extension type dynamically import it as-needed, those consumers (Datasets, AIR, Serve) can still have Pandas/Arrow as an optional dependency.

**Comment by ericl** [comment]
I just merged a PR moving air.utils to air.util, could you make that change here too?

**Comment by amogkam** [comment]
Updated @ericl

**Review by ericl — COMMENTED** [review]
Can you grep the docs and other code for references to this? Those + tests should be fixed.

It might be better to just not move it actually, what's the original motivation? It's fine to have a dependency on dataset package.

**Comment by amogkam** [comment]
> Can you grep the docs and other code for references to this? Those + tests should be fixed.

`ray.data.extensions` still exists. All the tests and docs are still passing.

> It's fine to have a dependency on dataset package.
Serve & standalone predictors will be using this too. We don't want a dataset dependency for those right? cc @simon-mo

**Review by ericl — APPROVED** [review]

**Comment by clarkzinzow** [comment]
AIR ingest doc code and Datasets tests are failing, it looks like there's still one or more spots where we need to change `ray.air.utils` -> `ray.air.util`.
https://buildkite.com/ray-project/ray-builders-pr/builds/34587#01813d23-e7cb-4810-b948-539c01d00600
https://buildkite.com/ray-project/ray-builders-pr/builds/34587#01813d23-e7c5-46db-a0e5-22d584ea27ad

**Pull request merged**
