### PR TITLE
[Dashboard] Stop processing logs from the dashboard

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

We don't use this feature anymore in the new dashboard, and we just removed the old dashboard. This feature also adds lots of overhead to the dashboard when there are lots of logs (which is bad)

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@alanwguo do we still use the log processing? I think since we remove the old dashboard, it is great to remove it. This also adds unnecessary overhead to the dashboard when there are lots of logs

**Comment by alanwguo** [comment]
logCounts is only used by the old dashboard. Although we removed the button to access the old dashboard, it is technically still accessible via going to a specific URL. 

Can you go to `http://localhost:8265/#/legacy` and see what the log viewing experience is like after you remove this code? My guess is that the log button is completely broken.

**Comment by rkooo567** [comment]
I can do all in this PR

**Comment by alanwguo** [comment]
> I can do all in this PR

okay, let's do it.

**Comment by alanwguo** [comment]
CC: @triciasfu @scottsun94 ,

We're already removing the "go to legacy dashboard" button. IN this PR, the log features of the legacy dashboard will be completely removed so it can't be used as an escape hatch starting in 2.2...

**Comment by rkooo567** [comment]
cc @alanwguo updated. Can you have a separate PR to remove old legacy dashboard frontend code?

**Comment by rkooo567** [comment]
I will remove memory_table related code in the separate PR

**Review by ericl — APPROVED** [review]

**Pull request merged**
