### PR TITLE
Fix redis dependency

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

Something seems to have gone wrong in https://github.com/ray-project/ray/pull/26446.
Redis was not available in the built image.
This PR makes an attempt to fix the issue.

I'm not sure how to test this PR.
I will try to verify the PR manually by poking around the CI environment.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
You should be able to build that docker image locally and see if this does the right thing (running the commend from the CI manually from your laptop)

**Comment by DmitriGekhtman** [comment]
> You should be able to build that docker image locally and see if this does the right thing (running the commend from the CI manually from your laptop)

Thanks for the tip. Let me try it out -- it might not have worked out last time I tried it on a Mac.

**Comment by DmitriGekhtman** [comment]
Ok, I figured out how to work the build command locally. Now just need to fidget the formatting some more with some local experiments.

**Comment by DmitriGekhtman** [comment]
It seems I had some spare spaces.
I've opened a separate PR (not for merging) to verify https://github.com/ray-project/ray/pull/26480/files.

**Comment by DmitriGekhtman** [comment]
Verified that it works in https://buildkite.com/ray-project/ray-builders-pr/builds/37972#0181f40c-b88f-468e-ae1d-0716246005b4

**Review by brucez-anyscale — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
Thank you for the stamps. Will pull nightly to re-confirm once it's built in ~1 hour.

**Pull request merged**
