### PR TITLE
Fix actor table Delete bug

### PR DESCRIPTION
**Pull request by kisuke95**
## Why are these changes needed?

In `ActorTable`'s `Put` function, it add tow records in redis: `key -- value` and `index_key -- key`. But in it's `Delete` function, it only delete `key -- value` record.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

**Comment by rkooo567** [comment]
Can you also comment when this is the issue?

**Comment by rkooo567** [comment]
I totally got the point of this change. Just curious if this is actually used in our code? (I am not saying we don't need this. It is just 100% out of curiosity). It looks like gcs actor manager only uses `DeleteBatch`, which also doesn't delete data with index keys. Isn't this causing any problem?

**Comment by kisuke95** [comment]
> I totally got the point of this change. Just curious if this is actually used in our code? (I am not saying we don't need this. It is just 100% out of curiosity). It looks like gcs actor manager only uses `DeleteBatch`, which also doesn't delete data with index keys. Isn't this causing any problem?

We (@ffbin and I) want to add some multi-threads tests in `redis_gcs_table_storage_test.cc`, the old `Delete` will leave some index keys in redis, which beaks next test.

**Comment by rkooo567** [comment]
I see. Don’t we also need to create a DeleteBatch method that deletes indexes to avoid the same problem inside actor manager?

**Review by rkooo567 — APPROVED** [review]

**Comment by kisuke95** [comment]
Yes, you are right ! I will do it later.

**Comment by kisuke95** [comment]
@rkooo567  Can we merge this PR? I connect to redis server with `redis-cli`, all data are removed after `BatchDelete` called.

**Comment by rkooo567** [comment]
Sure go ahead :)!

**Pull request merged**
