### PR TITLE
[Tune] call show_in_webui in trainable

### PR DESCRIPTION
**Pull request by zzyunzhi**
## Why are these changes needed?

Call show_in_webui in trainable to display mean accuracy in dashboard. Should be merged after #6574 is merged. 

cc @richardliaw 
 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by pcmoritz** [comment]
@richardliaw It would be good to get some feedback on where the best place is that this should be called :) Right now it needs to be called in the actor that executes the trial so it will show up in the right row in the webui, so that's why it is added in the trainable. Later we can also add an actor_handle argument to `ray.show_in_webui` that makes it possible to update the display from a different actor.

**Comment by richardliaw** [comment]
This is probably not the right place to add it; all of the Tune logging is done via `ray/tune/logger.py`, which is done on the driver process. A trial can have different actors over the course of training.

**Comment by pcmoritz** [comment]
How can we get an actor handle to the actor(s) that execute a trial?

**Comment by richardliaw** [comment]
It should be available via self.trial.runner where self is a logger object.

**Comment by simon-mo** [comment]
@richardliaw should this be closed? since there will be a specific tune dashboard?

**Comment by simon-mo** [comment]
displaying those inline actor view also seems really useful, can @aannadi try to update this PR?

**Comment by richardliaw** [comment]
I'm not sure what this solves though; maybe for representing the trial_id?

**Pull request closed without merging**
