### PR TITLE
fix install jdk8 on mac

### PR DESCRIPTION
**Pull request by chaokunyang**
Fix mac jdk install which broke mac wheel build.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by chaokunyang** [comment]
image
Homebrew insists that only builds from jdk.java.net are true OpenJDK builds and we can only get the current version. See https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/524

**Comment by ijrsvt** [comment]
Out of curiosity do you know why the `cask install` still takes 30+ minutes (PR Build for this PR):
Screen Shot 2021-03-18 at 8 55 19 AM

As opposed to a few weeks back ([here](https://travis-ci.com/github/ray-project/ray/jobs/490276074)) it took <5 minutes:
Screen Shot 2021-03-18 at 8 57 33 AM

**Comment by chaokunyang** [comment]
> Out of curiosity do you know why the `cask install` still takes 30+ minutes (PR Build for this PR):
> Screen Shot 2021-03-18 at 8 55 19 AM
> 
> As opposed to a few weeks back ([here](https://travis-ci.com/github/ray-project/ray/jobs/490276074)) it took <5 minutes:
> Screen Shot 2021-03-18 at 8 57 33 AM

Homebrew will build and install jdk from source. But I don't know why. I try to remove java formula, but seems doesn't take an effect.

**Comment by chaokunyang** [comment]
Now it took 30 minutes again
image

**Review by raulchen — APPROVED** [review]

**Pull request merged**
