### PR TITLE
[Core][Streaming Generator] Fix a bug where each yield will create a new task name

### LINKED ISSUE #37147: [streaming] Current task being changed during async iteration
After each `yield` of an async iterator, the task running the user code seems to change. This breaks user code and libraries (it was discovered because it causes an exception when trying to release a lock that uses the current task as an ID).

Repro:
```python
import asyncio
import ray

@ray.remote
class A:
    async def gen(self):
        print("BEFORE LOOP:", asyncio.current_task())
        for i in range(5):
            print("BEFORE YIELD:", asyncio.current_task())
            yield i
            print("AFTER YIELD:", asyncio.current_task())

        print("AFTER LOOP:", asyncio.current_task())

a = A.remote()
for obj_ref in ray.get(a.gen.options(num_returns="streaming").remote()):
    print(ray.get(obj_ref))
```

Output:
```
(ray) eoakes@Edwards-MBP-2 serve % python test_ray.py
2023-07-06 10:43:47,140 INFO worker.py:1610 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
(A pid=82093) BEFORE LOOP: <Task pending name='Task-2' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) BEFORE YIELD: <Task pending name='Task-2' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
0
1
2
3
4
(A pid=82093) AFTER YIELD: <Task pending name='Task-3' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) BEFORE YIELD: <Task pending name='Task-3' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) AFTER YIELD: <Task pending name='Task-4' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) BEFORE YIELD: <Task pending name='Task-4' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) AFTER YIELD: <Task pending name='Task-5' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) BEFORE YIELD: <Task pending name='Task-5' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) AFTER YIELD: <Task pending name='Task-6' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) BEFORE YIELD: <Task pending name='Task-6' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) AFTER YIELD: <Task pending name='Task-7' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
(A pid=82093) AFTER LOOP: <Task pending name='Task-7' coro=<<async_generator_asend without __name__>()> cb=[_chain_future.<locals>._call_set_state() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/futures.py:367]>
```

In comparison, vanilla `asyncio`:
```python
import asyncio

async def gen():
    print("BEFORE LOOP:", asyncio.current_task())
    for i in range(5):
        print("BEFORE YIELD:", asyncio.current_task())
        yield i
        print("AFTER YIELD:", asyncio.current_task())
    print("AFTER LOOP:", asyncio.current_task())

async def consume():
    async for i in gen():
        print(i)

asyncio.new_event_loop().run_until_complete(consume())
```

```
(ray) eoakes@Edwards-MBP-2 serve % python test.py
BEFORE LOOP: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
BEFORE YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
0
AFTER YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
BEFORE YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
1
AFTER YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
BEFORE YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
2
AFTER YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
BEFORE YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
3
AFTER YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
BEFORE YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
4
AFTER YIELD: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
AFTER LOOP: <Task pending name='Task-1' coro=<consume() running at test.py:14> cb=[_run_until_complete_cb() at /Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/base_events.py:184]>
```

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

This PR fixes https://github.com/ray-project/ray/issues/37147 by dispatching the whole generator task into an event loop (instead of dispatching individual anext). 

Originally, I took the approach to put all the async generator and do RerportGerneatorReturn inside it, but it turns out **Cython doesn't seem to support async generator**. Whenever I define a async generator, it gives me a random compiler error. This means this approach will trigger the circular dependency error (because cython needs to import async generator from python code, and the python code needs to import `RerportGerneatorReturn` related logic from Cython). 

So I decided to use the queue approach (sadly, it is a bit hacky. But I couldn't find a better way doing this).
- Create an async queue
- Dispatch the whole async generator task into the event loop "none-blocking". none-blocking is important because otherwise we cannot get the result before the generator is finished.
- Dispatch another async generator task (defined outside Cython, so that it can get around async generator compilation issue) that keeps polling the queue and return the result. This one will be passed to `execute_streaming_generator`.

## Related issue number

Closes https://github.com/ray-project/ray/issues/37147

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@edoakes what's the flag I need to flip in order to enable streaming handle?

**Comment by edoakes** [comment]
@rkooo567 you should just delete this flag and the code should always acquire the lock:
https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/replica.py#L645

No need to add additional tests. You can run `serve/tests/test_handle_streaming.py` locally to verify that it works w/ your change.

**Comment by rkooo567** [comment]
actually don't review this PR yet. I need to investigate the serve failure

**Comment by rkooo567** [comment]
```                                                   62% ██████▍   (ServeController pid=22179) INFO 2023-07-24 22:12:27,860 controller 22179 deployment_state.py:1319 - Deploying new version of deployment default_SimpleGenerator.
(ServeController pid=22179) INFO 2023-07-24 22:12:27,966 controller 22179 deployment_state.py:1586 - Adding 1 replica to deployment default_SimpleGenerator.

(HTTPProxyActor pid=22187) ERROR 2023-07-24 22:12:29,818 http_proxy 127.0.0.1 xiNwPataWa / default http_proxy.py:834 - Expected ASGI message 'http.response.body', but got 'http.response.start'.
(HTTPProxyActor pid=22187)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/http_proxy.py", line 817, in send_request_to_replica_streaming
(HTTPProxyActor pid=22187)     status_code = await self._consume_and_send_asgi_message_generator(
(HTTPProxyActor pid=22187)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/http_proxy.py", line 769, in _consume_and_send_asgi_message_generator
(HTTPProxyActor pid=22187)     await send(asgi_message)
(HTTPProxyActor pid=22187)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/http_proxy.py", line 867, in send_with_request_id
(HTTPProxyActor pid=22187)     await send(message)
(HTTPProxyActor pid=22187)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 519, in send
(HTTPProxyActor pid=22187)     raise RuntimeError(msg % message_type)
(HTTPProxyActor pid=22187) RuntimeError: Expected ASGI message 'http.response.body', but got 'http.response.start'.
(HTTPProxyActor pid=22187) ERROR:    ASGI callable returned without completing response.
(ServeReplica:default_SimpleGenerator pid=22341)     await self.send_user_result_over_asgi(result, scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/replica.py", line 608, in send_user_result_over_asgi
(ServeReplica:default_SimpleGenerator pid=22341)     await result(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/work/ray/python/ray/serve/tests/test_streaming_response.py", line 222, in hi_gen_async
(ServeReplica:default_SimpleGenerator pid=22341)     def hi_gen_sync():
(HTTPProxyActor pid=22187) Traceback (most recent call last): [repeated 2x across cluster]
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/replica.py", line 764, in call_user_method
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/responses.py", line 244, in __call__
(ServeReplica:default_SimpleGenerator pid=22341)     await wrap(partial(self.listen_for_disconnect, receive))
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
(ServeReplica:default_SimpleGenerator pid=22341)     raise exceptions[0]
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/responses.py", line 240, in wrap
(ServeReplica:default_SimpleGenerator pid=22341)     await func()
(ServeReplica:default_SimpleGenerator pid=22341)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/responses.py", line 229, in stream_response
(ServeReplica:default_SimpleGenerator pid=22341)     async for chunk in self.body_iterator:
(ServeReplica:default_SimpleGenerator pid=22341) Exception: raised in generator
(ServeReplica:default_SimpleGenerator pid=22347) ERROR 2023-07-24 22:12:29,816 default_SimpleGenerator default_SimpleGenerator#YcrLzJ xiNwPataWa / default replica.py:672 - Request failed due to RayTaskError:
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/replica.py", line 669, in wrap_user_method_call
(ServeReplica:default_SimpleGenerator pid=22347)     yield
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/replica.py", line 756, in call_user_method
(ServeReplica:default_SimpleGenerator pid=22347)     raise e from None
(ServeReplica:default_SimpleGenerator pid=22347) ray.exceptions.RayTaskError: ray::ServeReplica:default_SimpleGenerator.handle_request_streaming() (pid=22347, ip=127.0.0.1)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/utils.py", line 244, in wrap_to_ray_error
(ServeReplica:default_SimpleGenerator pid=22347)     raise exception
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/replica.py", line 737, in call_user_method
(ServeReplica:default_SimpleGenerator pid=22347)     result = await method_to_call(*request_args, **request_kwargs)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/work/ray/python/ray/serve/_private/http_util.py", line 415, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await self._asgi_app(
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/fastapi/applications.py", line 261, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await super().__call__(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await self.middleware_stack(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     raise exc
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await self.app(scope, receive, _send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     raise exc
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await self.app(scope, receive, sender)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     raise e
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await self.app(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await route.handle(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
(ServeReplica:default_SimpleGenerator pid=22347)     await self.app(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/routing.py", line 64, in app
(ServeReplica:default_SimpleGenerator pid=22347)     await response(scope, receive, send)
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/responses.py", line 244, in __call__
(ServeReplica:default_SimpleGenerator pid=22347)     await wrap(partial(self.listen_for_disconnect, receive))
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
(ServeReplica:default_SimpleGenerator pid=22347)     raise exceptions[0]
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/responses.py", line 240, in wrap
(ServeReplica:default_SimpleGenerator pid=22347)     await func()
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/anaconda3/envs/core/lib/python3.8/site-packages/starlette/responses.py", line 229, in stream_response
(ServeReplica:default_SimpleGenerator pid=22347)     async for chunk in self.body_iterator:
(ServeReplica:default_SimpleGenerator pid=22347)   File "/Users/sangbincho/work/ray/python/ray/serve/tests/test_streaming_response.py", line 222, in hi_gen_async
(ServeReplica:default_SimpleGenerator pid=22347)     def hi_gen_sync():
(ServeReplica:default_SimpleGenerator pid=22347) Exception: raised in generator
(ServeReplica:default_SimpleGenerator pid=22347) INFO 2023-07-24 22:12:29,817 default_SimpleGenerator default_SimpleGenerator#YcrLzJ xiNwPataWa / default replica.py:680 - __CALL__ ERROR 14.6ms
(ServeController pid=22179) INFO 2023-07-24 22:12:29,990 controller 22179 deployment_state.py:1611 - Removing 1 replica from deployment 'default_SimpleGenerator'.
 python/ray/serve/tests/test_streaming_response.py::test_exception_in_generator[True-True] ✓     
```

@edoakes btw, this is an expected output from this test right?

**Comment by rkooo567** [comment]
>  @rkooo567 you should just delete this flag and the code should always acquire the lock:
https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/replica.py#L645

> No need to add additional tests. You can run serve/tests/test_handle_streaming.py locally to verify that it works w/ your change.

Verified it works locally. Can you check code to make sure I removed the parts you mentioned properly?

**Comment by rkooo567** [comment]
@edoakes also can you recommend me to run a serve release to run to see if there's any perf changes?

**Comment by rkooo567** [comment]
Hmm there's one issue that only happens in CI but not in my local... debugging.

**Comment by edoakes** [comment]
> > @rkooo567 you should just delete this flag and the code should always acquire the lock:
> > https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/replica.py#L645
> 
> > No need to add additional tests. You can run serve/tests/test_handle_streaming.py locally to verify that it works w/ your change.
> 
> Verified it works locally. Can you check code to make sure I removed the parts you mentioned properly?

LGTM

**Comment by rkooo567** [comment]
Prefer this approach https://github.com/ray-project/ray/pull/37972. Closing the issue

**Pull request closed without merging**
