### PR TITLE
Revert "Revert "Revert "[Job Submission][refactor 1/N] Add AgentInfo …

### PR DESCRIPTION
**Pull request by rkooo567**
One of suspicious PRs that make the master flaky. 

…to GCSNodeInfo (…" (#27308)"

This reverts commit ccf411604ea86e19b3b2a53dcf62cb6df17d67b4.

I also suspect this is the root cause of all master flakiness 

Screen Shot 2022-08-07 at 8 53 51 AM

Let's see how it turns out...

cc @Catch-Bull 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Comment by rkooo567** [comment]
This seems to fix 4 all tune & windows related flaky tests

**Comment by rkooo567** [comment]
I am pretty confident this PR was the root cause of following failures (none of them happens in this PR)

Windows:Test reference counting
Window:Test queue
Test tune restore
Test cluster
test_trainer

cc @Catch-Bull I will try reverting this PR again. If the above tests are fixed, it should be highly likely to be related to add_node speed regression. We should discuss how to merge this more gracefully.

**Comment by rkooo567** [comment]
cc @Catch-Bull to inform this PR has been reverted again!

**Comment by iycheng** [comment]
Nice fix!

**Pull request merged**
