### PR TITLE
Add warning/error if object store memory exceeds available memory

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

- Log a warning if the default object store size exceeds 50% of available memory (it should only really consume 30% if all memory is available). The value 50% is chosen here to include the 20% of memory allowed to redis.
- Raise an error if the default object store size exceeds 90% of available memory.
- Exclude shared memory from the reported mem stats, since it is quite misleading and already reported as object store memory. Also, report up to the 10 memory consumers.

The error looks something like this:
```
Traceback (most recent call last):
  File "./train.py", line 153, in <module>
    run(args, parser)
  File "./train.py", line 142, in run
    num_gpus=args.ray_num_gpus)
  File "/home/eric/Desktop/ray-private/python/ray/worker.py", line 1387, in init
    head=True, shutdown_at_exit=False, ray_params=ray_params)
  File "/home/eric/Desktop/ray-private/python/ray/node.py", line 150, in __init__
    self.start_ray_processes()
  File "/home/eric/Desktop/ray-private/python/ray/node.py", line 514, in start_ray_processes
    self.start_plasma_store()
  File "/home/eric/Desktop/ray-private/python/ray/node.py", line 414, in start_plasma_store
    plasma_store_socket_name=self._plasma_store_socket_name)
  File "/home/eric/Desktop/ray-private/python/ray/services.py", line 1455, in start_plasma_store
    object_store_memory, plasma_directory, huge_pages)
  File "/home/eric/Desktop/ray-private/python/ray/services.py", line 1313, in determine_plasma_store_config
    round(avail_memory / 1e9, 2)))
ValueError: The default object store size of 3.68 GB will use more than 90% of the available memory on this node (1.54 GB). Please reduce the object store memory size to avoid memory contention with other applications, or shut down the applications using this memory.
```

## Related issue number

https://github.com/ray-project/ray/issues/4877

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by NikEyX** [comment]
Eric,

While you're at it, I just wanted to let you know that I ended up running my code with 
```
os.environ['RAY_DEBUG_DISABLE_MEMORY_MONITOR'] = "True"
```
always set. At least that's the latest in my Ray adventures. Unfortunately this is the only way to stop ray from crashing when other apps are temporarily using more memory. The default behaviour, in my opinion, should not be to raise an exception, but merely issuing a warning. There is no need for forcing the crash imo. 

Cheers

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
Friendly ping on review.

**Comment by ericl** [comment]
I think one way to go here may be to raise an error if the assumed memory isn't actually available due to other applications (i.e., check available memory ~= total memory on the machine). The error could tell the user to manually configure memory allocation in this case.

The problem with turning off the memory check by default is that then the errors that get raised when memory is actually out are quite confusing (e.g., IOerror), and it becomes difficult to determine that memory was actually the root cause of the crash.

**Comment by ericl** [comment]
Hmm, the check is tripping on stress test suites on Travis. This might explain why some Travis tests are flaky...

**Comment by ericl** [comment]
Ok I think this is finally passing travis.

**Review by pcmoritz — APPROVED** [review]
LGTM, this is great! Obviously, it's good that the error is just raised at the beginning :)

**Pull request merged**
