### PR TITLE
[Jobs] [Job Status refactor 1/n] Use JSON for JobInfo instead of pickled Python class

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Updates the JobInfo storage to use JSON instead of a pickled Python class. This allows it to be read by the GCS (which is in C++).  

## Related issue number
This a first step towards resolving https://github.com/ray-project/ray/issues/29621. The goal is to unify the GCS APIs and Ray Jobs API for getting the status of jobs. Plan copied from that issue:

1. [This PR] Have the job server store extended JobInfo in a proto or JSON form, instead of pickled Python data. The proto/JSON JobInfo can still be stored in the internal KV.
2. Enhance `ListAllJobs` to pre-join the data from `job_submission_id` in the internal KV. This means that GCS will need to lookup the extended JobInfo for jobs that have `job_submission_id` defined.
3. Add a `limit` field to ListAllJobs to bound the number of returned jobs.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@architkulkarni if this is going to be read by the GCS, should it be promoted to a full GCS table?

**Comment by edoakes** [comment]
@ericl thoughts on dumping JSON into internal_kv vs. defining a structured table?

**Comment by ericl** [comment]
I don't have an opinion here, both provide the same semantics as far as I know. If going the GCS table route though, we don't need a new table right? Just extend the existing jobs info table?

**Comment by edoakes** [comment]
@architkulkarni Ok, seems there are no strong opinions here so by default let's go with the one that requires fewer code changes, which seems to be using JSON. We can always come back and add it to a structured table later.

**Comment by architkulkarni** [comment]
@edoakes Sounds good! If you approve it then you or I can merge it.

**Review by edoakes — APPROVED** [review]

**Pull request merged**
