### PR TITLE
Revert "Same worker id in python and c++ (#16568)"

### PR DESCRIPTION
**Pull request by rkooo567**
This reverts commit 9b5c0c32da373fa476f794e1c3a171ca975e0ce4.

## Why are these changes needed?

Breaking java tests. cc @wuisawesome 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]
Thanks @rkooo567

**Comment by amogkam** [comment]
Going to emergency merge this.

cc @wuisawesome

**Comment by rkooo567** [comment]
Cc @wuisawesome

**Comment by kfstorm** [comment]
May I know where the worker ID in python comes from? I thought worker IDs are only generated in core worker. Is it possible to align these two by reading the actual value in core worker when trying to get the worker ID in Python?

I believe we don't generate a worker ID in Java. When a user tries to get the worker ID in a Java worker, we go through JNI.

https://github.com/ray-project/ray/blob/d1db4744e35384753e55ba63a2e6c0c69a4d0c13/java/runtime/src/main/java/io/ray/runtime/context/NativeWorkerContext.java#L17-L20

https://github.com/ray-project/ray/blob/d1db4744e35384753e55ba63a2e6c0c69a4d0c13/src/ray/core_worker/lib/java/io_ray_runtime_context_NativeWorkerContext.cc#L53-L59

 Also please be aware that a Java worker process may include multiple CoreWorker instances, so we need to change `std::string worker_id` to `std::string worker_ids[]` in `CoreWorkerOptions` if you guys still want to pass in worker IDs.

**Pull request merged**
