### PR TITLE
ActorStatisticalData() debug metrics bog down raylet with 100% CPU

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This is an issue discovered during debugging of https://github.com/ray-project/ray/issues/11239. A quick workaround is to disable this (to unblock further debugging with latest wheels).

Quick repro is `rllib train --run=PPO --env=CartPole-v0 --config={"num_workers": 32} --stop={"timesteps_total": 1000} --num-samples=10000 --ray-address=auto -vv`

@stephanie-wang @rkooo567 it seems the number of dead actors in this map increases without bound, is there a way we can fix this? I think we'll have map resizing issues

### CODE REVIEW

**Comment by rkooo567** [comment]
We also don’t gc actor handles on core workers. Need to think more about if raylet doesn’t remove entries because of the same reason, but I think we should be able to clean up properly on both.

**Comment by ericl** [comment]
I don't see any call to actor_registry_.erase() in node manager.

@rkooo567 the core worker map is only actors we communicate to right? Not all actors in the cluster. I guess this can also increase if a driver is talking to many actors over time.

**Comment by rkooo567** [comment]
Yeah. It only receives actors it communicates to. But I think core worker doesn’t constantly iterate through all handles like raylet (so impact might be lower).

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Btw, this will break the dashboard. Looking at code, it looks totally safe the delete the actor from the entry when it receives the DEAD state notification. Here is the reason Stephanie said why we cannot gc actor handle after actor reference has gone out of scope, and it doesn't seem to be relevant to the raylet.

```
yes! for 1, the guarantees are that the delete callback will get called once the language frontend no longer has a reference to the ActorHandle and any submitted tasks on the actor handle have been executed. however, there is a catch to this. a process can receive another copy of the same ActorHandle later on, and because we use counters to keep track of how many tasks have been submitted so far, we need to keep around the previous task count. this is the main reason why we don't GC the actor handles at the moment
```

Also, there's one possible edge case. Since ordering is not guaranteed, there can be possibility (very low) that RESTARTING notification is coming after DEAD. or even ALIVE is coming after DEAD. 

@stephanie-wang what do you think is a good solution here? Since this change can break the dashboard, I'd like to see if there's a quick fix here.

**Comment by rkooo567** [comment]
Also, looking more, I wonder if we ever need this entry? The only meaningful place that seems to use this map is this method;

```cpp
void NodeManager::HandleObjectLocal(const ObjectID &object_id) {
  // Notify the task dependency manager that this object is local.
  const auto ready_task_ids = task_dependency_manager_.HandleObjectLocal(object_id);
  RAY_LOG(DEBUG) << "Object local " << object_id << ", "
                 << " on " << self_node_id_ << ", " << ready_task_ids.size()
                 << " tasks ready";
  // Transition the tasks whose dependencies are now fulfilled to the ready state.
  if (new_scheduler_enabled_) {
    cluster_task_manager_->TasksUnblocked(ready_task_ids);
    ScheduleAndDispatch();
  } else {
    if (ready_task_ids.size() > 0) {
      std::unordered_set<TaskID> ready_task_id_set(ready_task_ids.begin(),
                                                   ready_task_ids.end());

      // First filter out the tasks that should not be moved to READY.
      local_queues_.FilterState(ready_task_id_set, TaskState::BLOCKED);
      local_queues_.FilterState(ready_task_id_set, TaskState::RUNNING);
      local_queues_.FilterState(ready_task_id_set, TaskState::DRIVER);

      // Make sure that the remaining tasks are all WAITING or direct call
      // actors.
      auto ready_task_id_set_copy = ready_task_id_set;
      local_queues_.FilterState(ready_task_id_set_copy, TaskState::WAITING);
      // Filter out direct call actors. These are not tracked by the raylet and
      // their assigned task ID is the actor ID.
      for (const auto &id : ready_task_id_set_copy) {
        if (actor_registry_.count(id.ActorId()) == 0) {
          RAY_LOG(WARNING) << "Actor not found in registry " << id.Hex();
        }
        ready_task_id_set.erase(id);
      }

      // Queue and dispatch the tasks that are ready to run (i.e., WAITING).
      auto ready_tasks = local_queues_.RemoveTasks(ready_task_id_set);
      local_queues_.QueueTasks(ready_tasks, TaskState::READY);
      DispatchTasks(MakeTasksByClass(ready_tasks));
    }
  }
}
```

And based on the comment, it looks like we don't even need this line?

**Comment by stephanie-wang** [comment]
Yeah actually I don't think we even need the `actor_registry_` or any actor notifications at all in the raylet. I think we missed this in the legacy code cleanup. If the dashboard is using this code, we should migrate it to the GCS instead. Probably the right way to do it is to have the dashboard subscribe directly to the actor notifications from the GCS, so we avoid looping there too.

Deleting actor handles from the core worker is a different problem since there is connection state there.

**Pull request merged**
