### PR TITLE
[Docs] Theme revamp: primary sidebar

### LINKED ISSUE #41618: [Docs] Theme revamp:  primary sidebar
### Description

Change the style of the navigation bar to kickoff the ray docs theme redesign project. 
Summary of changes: 
1. Font type change, let's not make changes to font size
2. Add styles to the nav bar as per the design 
3. The nav bar should not have any margins on the left side as shown in the figma 
4. Add a gradient (light version and dark version) to the background of ray docs

[Figma designs](https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=8%3A2244&mode=design&t=1LB8jzUvQjJHF0Ex-1)
cc: @angelinalg 

Doc for overriding colors: https://docs.google.com/document/d/1cxfBVKYSmGSCnq8PXWmxT4Ji0jD8fkYrSJ_A77EK9m4/edit?usp=sharing

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR implements a number of style changes to the docs to match new designs created by @simran-2797.

### Changes

- Added an `::after` pseudo-element that gives a splash of color to the main content of the page
- Set the `max-width` of the primary sidebar to 30% for the example gallery; otherwise the primary sidebar grows indefinitely to accommodate the flexbox that holds the tag filter buttons
- Set background, text-base, text-muted, and heading CSS color variables for dark and light themes
- Removed the empty space on either side of the main article content, allowing articles to expand to the size of the user's browser. This gives us a HUGE increase in screen real estate!
- Modify styles of primary sidebar dropdown; highlight the current page in the sidebar
- Add the `Inter` font globally
- Added css to the list of filetypes formatted by the `prettier` pre-commit hook. Also now that pre-commit is in the repo, the hooks ran on these files, causing a bit of reformatting.

Docs splash page:

image

## Related issue number

Closes #41618.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simran-2797** [comment]
Thanks @peytondmurray . 
1. When I hover over the sidebar, can we remove the underline? 
2. Can we change --pst-color-border to #2C333A?
3. On some places, the width of the primary nav exceeds it's original width. 
Screenshot 2023-12-19 at 9 53 00 AM

**Comment by peytondmurray** [comment]
After a discussion on slack for clarification:

- [ ] Remove link hover underline text decoration for all links sitewide
- [ ] Hovered links should have a different color: light mode `#1D7AFC`, dark mode `#388BFF`
- [ ] Set the sidebar to a fixed width of 280px

**Comment by peytondmurray** [comment]
Hmm, the hover link colors are nearly indistinguishable from standard ray blue, so it will be really hard to perceive any kind of hover color change. Let's revisit the color changes in a separate PR.

**Comment by simran-2797** [comment]
lgtm

**Comment by peytondmurray** [comment]
@maxpumperla If the build looks good to you, would you be able to merge this?

**Pull request merged**
