### PR TITLE
Modify Ray's map_async() to match Multiprocessing's map_async() behavior

### PR DESCRIPTION
**Pull request by shrekris-anyscale**
## Why are these changes needed?

This PR modifies Ray's `map_async` to ensure that the `callback` is only called once on the entire batch of results at the end of `map_async`'s execution. `map_async` will only be called if all the results are successful. If any of the results throws an exception, the `exception_callback` will be called only once on the first erroring result. These modifications match the behavior of the Multiprocessing library's `map_async`.

## Related issue number
This PR addresses the `map_async` issue from [#19289](https://github.com/ray-project/ray/issues/19289). However, `apply_async` may require further investigation and code changes.

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - I revised the `test_callbacks` test in test_multiprocessing.py to now check for the new behavior. I also modified the same test to also check the new behavior in Multiprocessing's `map_async` to ensure that both versions are consistent.

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
Looks good!

**Review by jiaodong — COMMENTED** [review]
Great start !

**Review by jiaodong — COMMENTED** [review]
lg overall ! Just some nits

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
LGTM, please add @tests-ok when you want me to merge

**Review by jiaodong — APPROVED** [review]
lg !

**Comment by edoakes** [comment]
@shrekris-anyscale sorry, there were some build infra problems that should now be addressed, could you please merge master and push one last time to double-check the CI failures?

**Pull request merged**
