### PR TITLE
[ci] always build docker on postmerge

### PR DESCRIPTION
**Pull request by aslonnie**
so that docker builds are not only covered by core_cpp

also removes unecessary `core_cpp` build tags. building the container only requires building the wheel, and has nothing to do with core cpp code.

### CODE REVIEW

**Comment by aslonnie** [comment]
I am actually not sure why `core_cpp` needs to trigger docker build (but not building the wheel). I feel that it should only trigger building the wheel. the docker build simply extracts the wheel inside the container and does nothing much else.

**Review by can-anyscale — APPROVED** [review]

**Comment by can-anyscale** [comment]
I think on postmerge the bootstraper doesn't even compute tags which default to run everything regardless of tags

**Comment by aslonnie** [comment]
it computes tags in the otherworld..

**Comment by aslonnie** [comment]
I can also use another config in the otherworld..

I think the removal of `core_cpp` tags is going to be good anyways.

**Pull request merged**
