### PR TITLE
[serve] Also pin `fastapi` in `requirements.txt`

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Extension of https://github.com/ray-project/ray/pull/42682.

This is apparently supposed to be updated in tandem with `setup.py`.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by GeneDer — APPROVED** [review]
Oh was this it😯 I was also testing out where else this needs to be pinned as well. Thanks for fixing it Ed!

**Comment by edoakes** [comment]
> Oh was this it😯 I was also testing out where else this needs to be pinned as well. Thanks for fixing it Ed!

Not 100% confirmed yet but I believe so :/

**Comment by edoakes** [comment]
Turns out it's not the whole story, we need to fix: https://github.com/ray-project/ray/issues/42757

But this should still be merged (but tbh I'm not sure what it does)

**Comment by GeneDer** [comment]
> Turns out it's not the whole story, we need to fix: #42757
> 
> But this should still be merged (though tbh I'm not sure what it does)

Oh I see, no wonder my PR also keeps failing XD that `python -m pip install -U "ray[serve]"` always overrides the pinned fastapi version. Good find!

**Pull request merged**
