### PR TITLE
[dataset] Pipeline task submission during reduce stage in push-based shuffle

### LINKED ISSUE #25412: [core] Scheduler stalls during shuffle reduce stage with 100k concurrent tasks or more
### What happened + What you expected to happen

So far, running 100TB shuffle on Datasets seems to pass the map stage successfully, but the reduce stage fails almost immediately. @franklsf95 confirms it passes if the driver throttles task submission for the reduce stage, so this is most likely due to load related to too many tasks. The head node becomes unreachable for some time and the worker raylets also crash because of this. Another thing that supports the "too many tasks" theory is that if we run simple shuffle on the same number of objects, but fewer tasks and much less data, the job completes with no problems.

### Versions / Dependencies

2.0dev

### Reproduction script

dataset_push_based_random_shuffle_1tb, but change to 200k partitions of 500MB each.

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Reduce stage in push-based shuffle fails to complete at 100k output partitions or more. This is likely because of driver or raylet load from having too many tasks in flight at once.

We can fix this from ray core too, but for now, this PR adds pipelining for the reduce stage, to limit the total number of reduce tasks in flight at the same time. This is currently set to 2 * available parallelism in the cluster. We have to pick which reduce tasks to submit carefully since these are pinned to specific nodes. The PR does this by assigning tasks round-robin according to the corresponding merge task (which get spread throughout the cluster).

In addition, this PR refactors the map, merge, and reduce stages to use a common pipelined iterator pattern, since they all have a similar pattern of submitting a round of tasks at a time, then waiting for a previous round to finish before submitting more.

## Related issue number

Closes #25412.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Adds a multinode test, but it would be nice to add a test that hooks into ray.remote and ray.get to check that we are actually submitting the right tasks at the right time.

### CODE REVIEW

**Comment by stephanie-wang** [comment]
(also includes changes from #25734)

**Review by ericl — COMMENTED** [review]
The key config here is num_merge_tasks_per_round, is that right? Given this is a temporary workaround, I think we should make this feature flagged, and add a TODO to remove this once we fix the core issue. 100k tasks should fit comfortably within our scalability envelope, so this is a bit odd.

**Comment by ericl** [comment]
It would also be great to have a unit test that things work with pipelining enabled/disabled, so we can easily remove it in the future.

**Review by ericl — APPROVED** [review]
Feature flag lgtm... rubber stamping on the rest.

**Pull request merged**
