### PR TITLE
[Fix] fix issue #30144, reporter not parse customized metric correctly

### PR DESCRIPTION
**Pull request by spacegoing**
## Related issue number

Fix issue #30144

### CODE REVIEW

**Comment by xwjiang2010** [comment]
Thanks @spacegoing ! Could you fix the lint error and could you add a test for this?

**Comment by pcmoritz** [comment]
@xwjiang2010 Can you give some guidance as to how and where this test should be added?

**Comment by spacegoing** [comment]
@xwjiang2010 Hi Xiaowei, many thanks for your help! That's really detailed instructions, very much appreciated!

I did not setup a ray development environment on my local. I need to spend some time tweak my dev env and will let u know when I'm ready :D

**Comment by justinvyu** [comment]
Hey @spacegoing, just wanted to follow up - were you able to setup the development environment to add the unit test? I can also help get this one across the finish line if needed!

**Comment by spacegoing** [comment]
@justinvyu Hi Justin, thanks for your reply. Yes please help me with this. I am trying to set up a dev env in docker on MacOS, however the ray seems not to support Linux ARM docker. Would be really appreciate if you can help with this. Many thanks!

**Pull request closed without merging**
