### PR TITLE
ADd troubleshooting doc for untrusted dev for prometheus

### LINKED ISSUE #29950: [Observability Documentation] Unable to follow instructions for starting prometheus on Mac
### What happened + What you expected to happen

I followed the instructions in the **Getting Started (Single Node)** section of this page https://docs.ray.io/en/latest/ray-observability/ray-metrics.html#getting-started-single-node.

When I ran `./prometheus --config.file=./prometheus.yml`, I got the following popup. I wasn't sure how to get around this.

image
****

### Versions / Dependencies

MacOS 10.15.7
Ray: Latest nightly e85355b9b593742b4f5cb72cab92051980fa73d3
Python: 3.7.4

### Reproduction script

See above

### Issue Severity

Blocker for using Prometheus.

### PR DESCRIPTION
**Pull request by alanwguo**
Signed-off-by: Alan Guo <aguo@anyscale.com>

## Why are these changes needed?
Screen Shot 2022-11-03 at 9 34 06 AM

## Checks
fixes #29950
- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by scottsun94** [comment]
Screen Shot 2022-11-03 at 9 42 21 AM
Shall we also add a note like this above when we ask users to run prometheus?

**Review by maxpumperla — APPROVED** [review]

**Comment by alanwguo** [comment]
> Screen Shot 2022-11-03 at 9 42 21 AM
> 
> Shall we also add a note like this above when we ask users to run prometheus?

you mean instead of this separate section?

**Comment by scottsun94** [comment]
> Screen Shot 2022-11-03 at 9 42 21 AM
> 
> Shall we also add a note like this above when we ask users to run prometheus?

**Comment by alanwguo** [comment]
@scottsun94 

Screen Shot 2022-11-03 at 11 30 18 AM

**Comment by scottsun94** [comment]
Thanks!

**Review by scottsun94 — APPROVED** [review]

**Pull request merged**
