### PR TITLE
[ci] deflake test_http_events_2

### PR DESCRIPTION
**Pull request by can-anyscale**
Put some core tests back to flaky states. They are still flaky. CC: @rkooo567 

Test:
- CI

### CODE REVIEW

**Comment by rkooo567** [comment]
Screenshot 2023-11-16 at 9 25 10 AM

hmm interesting. This seems to become flaky after I take it out from the list.

**Comment by can-anyscale** [comment]
Yes, please help investigate the error logs, they are still flaky in some certain environments

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
we can't debug issues that are not reproducible. what do you mean by "different environment" here? Are you saying the tests are running concurrently vs serially? What's the exact difference between tests in flakiness vs not?

**Comment by can-anyscale** [comment]
@rkooo567 some of the workflow tests use 4 core and we run them only a medium size machine (with 4 core); we should run these tests serially

**Review by fishbone — APPROVED** [review]

**Comment by aslonnie** [comment]
> we can't debug issues that are not reproducible

you should try to rewrite/redesign the test to make the test's behavior more deterministic or easier to debug/reproduce, so that it relies less on the specific test environment.

a unit test is a test that runs under certain resource assumptions, like overall time out, like memory size or number of cores it has, basic file system and networks, etc. and that's it.

a unit test should be able to run with other stuff running concurrently. it is not part of the spec that when running unit tests, one have to clear the system and exit all other programs.

the timing behavior of the OS or machine is also not part of the spec. unit tests should pass on cpus faster or slower with only adjustments on the overall timeout.

the test env container and bazel is supposed to capture all the dependencies and the setup of test already, if we run a bazel unit test in the same test container, and it passes on one machine, but fails on another machine, or if it passes when running by itself, but fails when running with other tests, that normally means that the test itself is not very well designed or written, and the code should be re-examined on its assumptions of the environment.

----

at the end of the day, ray code will need to run in all kinds of different environments, when a user reports a bug that something does not work for them in their environment, and we tell user that "we cannot debug or fix it because we cannot reproduce the error by ourselves", the user will probably just stop using ray.

it is ultimately the code maintainer's job to make test failures easier to reproduce. the CI team will try our best to make the "test environment" part easier to reproduce, but we cannot help that much on reproducing a particular flaky test failure.

----

for example, a racing condition issue might only happen under stress, and even when under stress, it might only happen in 0.1% of the time. it is very very hard to reproduce, but still can be a serious bug when the consequence is for example losing the training progress of a big AI model, or crash a production system of vital importance.

and in cases like these, sometimes the best way to debug, is not trying to reproduce it, but just read the code carefully, comment it with texts, try to understand it, refactor it into a structure where its behavior and concurrency pattern is easier to comprehend, double check all the assumptions of the environment, and try to find the potential racing condition based on the clues we have in hand. form a theory, and tune the stress level of different components (e.g. by injecting intentional spins, or manipulate the cache) and see if it is possible to make the racing condition easier to trigger.

**Comment by rkooo567** [comment]
Previously, we had no issues reproducing flaky tests. You cannot just change all infra and ask us to rewrite all tests. Yes, ray has too many integration tests, and we should improve it, but We have limited bandwidth, and we should find practical iterative approach.

**Comment by aslonnie** [comment]
> we had no issues reproducing flaky tests
first of all, you can still reproduce now. like create a PR, disable all other tests on the pipeline, and rerun the job with a buildkite job matrix of like 20 times, and I am pretty sure you can reproduce it. otherwise it won't even show up as flaky on the flaky dashboard. it is more like the change of test environment revealed more flaky test issues. 

> ask us to rewrite all tests
that is not what we asked. ultimately, there is a bug, you can decide if it is important, and based on the bandwidth you have, decide to fix it or not.

**Comment by aslonnie** [comment]
but you cannot really say that "I cannot reproduce it, so I cannot fix it". the statement is just false.

but it is totally reasonable to say, we have limited bandwidth, so I won't be able to fix it now. if it is important, then we can block release, or ask engineer managers to allocate more resources.

like in the worse case, I or Cuong can even allocate time to fix it for you.

or maybe it is not an important bug, and we just mark it as not PR blocking, not release blocking let it fail for some more time, or just stop running it for a while, that is totally okay.

**Review by aslonnie — APPROVED** [review]

**Pull request merged**
