### PR TITLE
Revert "[runtime env] redefine runtime env to protobuf"

### PR DESCRIPTION
**Pull request by wuisawesome**
Reverts ray-project/ray#19511

Breaks windows compilation

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
Thanks for catching this!

**Review by ericl — APPROVED** [review]
This is unfortunate. @raulchen how can we ensure the Windows build isn't ignored for merge?

**Review by ijrsvt — APPROVED** [review]
LGTM!

**Comment by jovany-wang** [comment]
> This is unfortunate. @raulchen how can we ensure the Windows build isn't ignored for merge?

Why not split it to 2 CI jobs, Windows build and Windows test? And only mark the Windows test as allowfailure.

**Pull request merged**
