### PR TITLE
Remove streaming deploying process.

### PR DESCRIPTION
**Pull request by jovany-wang**
## Why are these changes needed?

1. Remove the streaming from deploying to maven central.
2. Remove related streaming stuff from setup.py.
## Related issue number
#21602

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jovany-wang** [comment]
Hi @architkulkarni  @simon-mo  do you guys know if we deploy the streaming python wheels when releasing?
We'd like to remove them from this repo.

**Comment by simon-mo** [comment]
I don't think it's in our release process, we only deploy python wheels, cpp wheels and jars.

**Comment by jovany-wang** [comment]
But the streaming libraries actually are packed into our wheels. https://github.com/ray-project/ray/blob/master/python/setup.py#L143

**Comment by simon-mo** [comment]
I see. In that case we should remove it from wheel. 

On January 14, 2022, GitHub ***@***.***> wrote:
> But the streaming libraries actually are packed into our wheels.
> <https://github.com/ray-project/ray/blob/master/python/setup.py#L143>
>

—
Reply to this email directly, view it on GitHub <https://github.com/ray-
project/ray/pull/21603#issuecomment-1013272774>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AFBD7AZU3GDVUKJGQNCQGDDUWBFOJANCNFSM5L7A6S6Q>.
You are receiving this because you were mentioned.Message ID: <ray-
***@***.***>

**Comment by chaokunyang** [comment]
Two questions:
1. do we need to remove streaming python build from this PR?
2. do we need to remove bazel build from this PR? Currently `ray_pkg`&`ray_java_pkg` still contain streaming build.

**Comment by jovany-wang** [comment]
> Two questions:
> 
> 1. do we need to remove streaming python build from this PR?
> 2. do we need to remove bazel build from this PR? Currently `ray_pkg`&`ray_java_pkg` still contain streaming build.

Yes, no.
This PR aims to remove the deploying processing from ray, so we need to remove them from ray_dist.jar and python wheel.
But this PR is not intended to remove building process. @ashione CC

**Review by ericl — APPROVED** [review]

**Review by ashione — APPROVED** [review]

**Pull request merged**
