### PR TITLE
Simplify Cython ID types and fix bug of ActorCheckpointID

### PR DESCRIPTION
**Pull request by raulchen**
## What do these changes do?

- Remove unnecessary indirection (the id types being imported `unique_ids.pxd -> common.pxd -> unique_ids.pxi`)
- Remove unused imports.
- Fix the bug that `ActorCheckpointID` not being added to `_ID_TYPES`.

### CODE REVIEW

**Review by robertnishihara — APPROVED** [review]
This looks good to me. Thanks!

**Comment by raulchen** [comment]
> Cool, I thought I tried that and ctypedef didn't support a typedef with a different name than wInias in the c++ source, that's why this strange renaming via the import was there.

Initially I put the `ctypedef`s in the `cdef extern from` block, and got errors saying `there's no CObjectID in ray namespace`. Moving the `ctypedef`s out of the block fixed this issue.

**Review by suquark — APPROVED** [review]
LGTM. Thanks!

**Comment by robertnishihara** [comment]
Looks like linting is failing in a couple places.

**Pull request merged**
