### PR TITLE
Revert "Revert "[Cluster Events] Add basic job events. (#29164)" (#29…

### PR DESCRIPTION
**Pull request by rkooo567**
…195)"

This reverts commit 75a0c491e8ee4009e8828081059cfc98543c4d51.

## Why are these changes needed?

This reverts the PR and fixes the test failures

This also fixes a bug around `_monitor_jobs` API. the monitor job can be called on the same job twice now, which will break the event (because at the end of monitor job, we record the event that job is completed). The same completed event can be reported twice without the fix

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rickyyx — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @architkulkarni I also added the idempotent `monitor_jobs` method here. Can you review one more time? I am planning to merge it soon.

**Comment by rkooo567** [comment]
test_dashboard is unrelated. It is flaky in the master, and the flaky test has been fixed from other PR

**Comment by architkulkarni** [comment]
@rkooo567 can you add some context to the PR description (what test was broken, how does this fix it)

**Review by architkulkarni — APPROVED** [review]
`monitor_jobs` changes look good!

**Comment by architkulkarni** [comment]
`test_event` failed https://buildkite.com/ray-project/oss-ci-build-pr/builds/3935#018438f6-bd8b-4397-bc31-8523630b6a5f/3477-4459

Ideally we would also have a unit test for `self._monitored_jobs`.

**Comment by rkooo567** [comment]
Let me make a follow up PRs for unit tests. I will add a bunch of them including verifying events.

**Comment by rkooo567** [comment]
the dashboard failure should be unrelated and fixed in the mastesr

**Pull request merged**
