### PR TITLE
Windows dockerfile v3

### PR DESCRIPTION
**Pull request by ellimac54**
this time I removed some unused functions in PS scripts

### CODE REVIEW

**Comment by simon-mo** [comment]
@ellimac54 seems like bazel test failed in the container
https://buildkite.com/ray-project/ray-builders-pr/builds/10284#85236286-17c4-483f-a791-10b67ea40426/6-4099

You can trigger new builds by push new commits to this branch/PR and click 
image
to go view the log

**Comment by ellimac54** [comment]
Hi Simon, unfortunately it seems disk space allocated by buildkite is too small for visualstudio installation (vs needs 39 GB of free disk space, even if it is not using all). I found a page explaining how to allocate more disk space with docker on windows: https://unrealcontainers.com/docs/environments/local-windows-server
it is the section "Configuring Docker for building and running Windows containers". I hope it is easy to configure this with buildkite!

**Comment by simon-mo** [comment]
Thanks @ellimac54 I will try to increase the configuration and rerun the test!

**Comment by simon-mo** [comment]
Ok I was able to get a the container to build. Some tests were able to ran successfully however it seems like using Python's re

```
(pid=6748)   File "C:\Python38\lib\urllib\request.py", line 1397, in https_open
--
  | (pid=6748)     return self.do_open(http.client.HTTPSConnection, req,
  | (pid=6748)   File "C:\Python38\lib\urllib\request.py", line 1357, in do_open
  | (pid=6748)     raise URLError(err)
  | (pid=6748) urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>

```

Do we need to install certificates for Python here?

**Comment by simon-mo** [comment]
https://buildkite.com/ray-project/ray-builders-pr/builds/10543#9295861f-7dbc-4401-b87b-baaef34dc64b/6-6710

**Comment by simon-mo** [comment]
Additionally, it would be great if we use anaconda python instead of system python, can you make the change in the docker file? You might want to consider directly using ./ci/travis/ci.sh script and commands called by ./github/workflows/main.yml.

**Comment by ellimac54** [comment]
> 
> 
> Ok I was able to get a the container to build. Some tests were able to ran successfully however it seems like using Python's re
> 
> ```
> (pid=6748)   File "C:\Python38\lib\urllib\request.py", line 1397, in https_open
> --
>   | (pid=6748)     return self.do_open(http.client.HTTPSConnection, req,
>   | (pid=6748)   File "C:\Python38\lib\urllib\request.py", line 1357, in do_open
>   | (pid=6748)     raise URLError(err)
>   | (pid=6748) urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
> ```
> 
> Do we need to install certificates for Python here?

Hi Simon, I don't know where this problem is coming from, I will check it

**Comment by ellimac54** [comment]
> 
> 
> Additionally, it would be great if we use anaconda python instead of system python, can you make the change in the docker file? You might want to consider directly using ./ci/travis/ci.sh script and commands called by ./github/workflows/main.yml.

ok

**Comment by ellimac54** [comment]
Hi Simon, there are still some bugs I am unable to solve on buildkite. It is working fine locally on my dev computer, but there is still a problem with some jdk include files and some too long executable path on buildkite. I am not out of ideas to solve these problems.

**Comment by simon-mo** [comment]
yeah I was able to see the error log for file name too long, instead of the `startup --output_user_root=C:/tmp`, what if we try 8dot3 file name support? https://docs.bazel.build/versions/main/windows.html#enable-83-filename-support

**Comment by ellimac54** [comment]
fsutil 8dot3name set 0 is already executed in scripts\ImageHelpers\VisualStudioHelpers.ps1, so I don't understand the problem...

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
