### PR TITLE
[C++ worker]Support ActorHandle type return value

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?
Before we support `ActorHandle` type as parameter, this PR adds support for `ActorHandle` type as return type.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by SongGuyang** [comment]
@WangTaoTheTonic Thanks for this fix. I have one question, can you explain why we need to do some special works for `Actorhandle` type args and return value? Can we serialize it in the common way like a user defined Class? We already declared the field by the macro of message pack https://github.com/ray-project/ray/blob/master/cpp/include/ray/api/actor_handle.h#L83

**Comment by WangTaoTheTonic** [comment]
@SongGuyang `ActorHandle` type is kinda different from other common types. Before being used(like `actorhandle.task(...)`), it must be registered in `actor_manager` of core worker, in addition to deserialization.

**Review by SongGuyang — APPROVED** [review]
Make sense! Thanks.

**Comment by WangTaoTheTonic** [comment]
@SongGuyang The `LinkCheck` failure is not related. Could you merge it? Thanks.

**Pull request merged**
