### PR TITLE
[data] Add pickle support for PyArrow CSV WriteOptions

### PR DESCRIPTION
**Pull request by pdames**
## Why are these changes needed?

Users cannot specify custom Dataset write options when writing output to CSV via `dataset.write_csv()`, because the `pyarrow.csv.WriteOptions` class retrieved from `writer_args["write_options"]` in `CSVDatasource._write_block()` cannot be pickled by Ray. 

This PR presents a solution to this problem via a `_WriteOptionsWrapper` class that wraps `WriteOptions` while implementing the required `__getstate__` and `__setstate__` methods.

## Related issue number
Closes https://github.com/ray-project/ray/issues/19366

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
Looks pretty good. Could we also rename the functions to be more consistent with the kwargs (e.g., arrow_parquet_args => arrow_parquet_args_fn, writer_args => writer_args_fn etc.)? I made a suggestion.

**Comment by ericl** [comment]
> If we're happy with the current changes, then I could also update the read-side APIs to accept a read kwargs supplier lambda that works in a similar way, which could help us both with code consistency and to head off other similar read kwarg pickling problems that may pop up on the read side either now or in the future.

Also sounds good.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
still timing out on that json datasource test

**Review by clarkzinzow — APPROVED** [review]
Nice, thanks for adding this!

I personally find the "args provider" route less appealing since:
1. It adds an extra API arg that duplicates behavior of an existing API arg in a slightly confusing way for the user, who will ask: why are there two ways to give args, and when do I have to use the lambda?
2. The user having to package up their unserializable args into a provider lambda is worse UX than being able to pass it directly with us taking care of making it serializable under-the-hood.
3. Once Arrow fixes the serializability issues upstream, we'd need to break the API in order to remove this now unnecessary arg provider, compared to the wrapper class route which is an internal change.
4. The code impact is much larger overall compared to the wrapper, which only needed to wrap/unwrap at serialization boundaries.

But I don't think this is worth blocking this from getting merged.

**Comment by ericl** [comment]
+1 on removing the ** and making it explicit, I think that's probably a
usability improvement even by itself.

**Pull request merged**
