### PR TITLE
Refactor ID Serial 2: change all IDs to  `CamelCase`

### PR DESCRIPTION
**Pull request by guoyuhong**
## Linter

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by guoyuhong** [comment]
There is modin test fail, because the modin has used `ray.ObjectID`. Modin is another repo, what is the step to fix that?

**Comment by robertnishihara** [comment]
Thanks @guoyuhong, do you prefer `ObjectId` because it is more consistent with the camelcase that we use in other places (e.g., `Gcs`)? `ObjectID` looks better to me since `ID` is typically capitalized (since it is an acronym).

Regarding the Modin issue, one option would be to comment out that test until it's changed in Modin and then update the version of Modin after that.

**Comment by guoyuhong** [comment]
I prefer `ObjectId` a bit, because current Java lint tool require Java code to use `ObjectId`. That is to say, Java has different Id name than C++ and python.

**Comment by raulchen** [comment]
Just quickly googled "camel case abbreviations". It seems that different languages and guides have different rules. 
I don't have preference. But I think at least we should rename the class methods in id types to use camel case, e.g., `UniqueID.FromRandom()`.

**Comment by guoyuhong** [comment]
@raulchen OK, that will be done.

**Comment by guoyuhong** [comment]
Close this PR and move the function `CamelCase` PR to https://github.com/ray-project/ray/pull/4896 .

**Pull request closed without merging**
