### PR TITLE
Add getCurrentTaskId in RuntimeContext

### PR DESCRIPTION
**Pull request by raulchen**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by kfstorm** [comment]
Can you elaborate the purpose of adding this new API?

**Comment by raulchen** [comment]
> Can you elaborate the purpose of adding this new API?

The original reason is because users want to use current task id as a seed to generate random numbers deterministically (generate the same value before and after a failover).
This might not be a strong reason. But I guess users would sometimes want to know current task id in other cases as well. And for the completeness of `RuntimeContext`, adding this API makes sense as well.

What do you think?

**Comment by kfstorm** [comment]
@raulchen I don't believe the current task ID can be a reliable source to generate consistent random numbers across FO. We allow multi-threading in a task, the IDs of sub-tasks generated are not guaranteed to be predictable. I wonder if someone used this API, would the application more likely go wrong?

**Comment by robertnishihara** [comment]
@raulchen should this be closed?

**Comment by robertnishihara** [comment]
Closing because this is stale, please reopen if this is a mistake.

**Pull request closed without merging**
