### PR TITLE
[Doc] Allow docs example gallery to specify tags with url query params

### LINKED ISSUE #37250: [docs] Update Use Cases page with a link to Examples Gallery
### Description

Now that we have the Examples Gallery, we can link to it from each of the sections of the Use Cases page. Each section should have a link to a filtered Examples Gallery for that use case/workload. This will help shorten the already long page, too. This work is targeted for 2.6.

Screenshot 2023-07-10 at 3 44 46 PM

### Link

https://docs.ray.io/en/latest/ray-overview/use-cases.html

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR modifies the `Use Cases` docs page. Instead of displaying lists of example links, the page now points to the example gallery. Using a custom sphinx extension, I was able to generate links to the example gallery which include URL query parameters; when the example gallery page loads, these query parameters are used to activate tag filters in the side bar, automatically filtering out specific subsets of examples.

Here's what the new `Use Cases` page looks like:

image

Here's a look at the new URL query parameter filtering mechanism. If I load the example gallery with the following URL:

image

The page looks like:

image

While I was working on this, I also fixed an issue where `tags.js` would not be executed if the URL included query parameters or other stuff (e.g. `#`) at the end.

## Related issue number

Closes https://github.com/ray-project/ray/issues/37250.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
Nice!

Eric

**Review by maxpumperla — APPROVED** [review]
very nice, thank you!

**Comment by simran-2797** [comment]
When I click on explore Ray train examples and explore Rlib examples, it just points me to the example gallery with no filters applied. Should we create another group of filters called "Ray libraries"? @peytondmurray

**Comment by peytondmurray** [comment]
Yes, you're right. It's because filters we don't have buttons for are ignored. I think we should make a new issue and design docs for a "Ray Libraries" set of tags.

For this PR, can we leave this as is or would you prefer a different behavior here?

**Comment by simran-2797** [comment]
Okay. I can create a new issue for library filter. 
For the issue I mentioned: 
I feel for use cases which do not have corresponding filter in the example gallery, let's keep them as bulleted list. When we have filters, we can direct them to the example gallery. Wdyt?

**Comment by peytondmurray** [comment]
Sounds great, I'll make it happen!

**Review by simran-2797 — APPROVED** [review]

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
