### PR TITLE
[tune/sgd] Import ABC from collections.abc instead of collections for Python 3 compatibility

### LINKED ISSUE #7981: [python] Importing ABC directly from collections was deprecated and will be removed in Python 3.10
### What is the problem?

Importing ABC directly from collections was deprecated and will be removed in Python 3.10. Use collections.abc instead.

### Reproduction (REQUIRED)

```
python/ray/tune/progress_reporter.py
104:        if isinstance(self._metric_columns, collections.Mapping):
294:    if isinstance(metric_columns, collections.Mapping):
306:    if isinstance(metric_columns, collections.Mapping):

python/ray/util/sgd/torch/training_operator.py
28:    return isinstance(component, collections.Iterable) and len(component) > 1
69:        assert isinstance(models, collections.Iterable), (
72:        assert isinstance(optimizers, collections.Iterable), (
80:            assert isinstance(schedulers, collections.Iterable), (

python/ray/util/sgd/torch/torch_runner.py
136:        if not isinstance(self.schedulers, collections.Iterable):
156:        if not isinstance(self.models, collections.Iterable):
166:        if not isinstance(self.optimizers, collections.Iterable):
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by tirkarthi**
## Why are these changes needed?

Import ABC from collections.abc instead of collections for Python 3 compatibility

## Related issue number

Fixes #7981 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Looks like the lint test is failing: https://travis-ci.com/github/ray-project/ray/jobs/318480675#L347-L377

**Comment by richardliaw** [comment]
Can you please fix this and ping me when done?

**Comment by tirkarthi** [comment]
@richardliaw I have fixed the lint error. I am not sure about the windows failure.

**Comment by rkooo567** [comment]
@mehrdadn Is this window build failure related to this change? 

@richard4912 I think it is safe to merge if @mehrdadn says it is okay to merge!

**Comment by mehrdadn** [comment]
@rkooo567 Ahh no that's unrelated, it was already fixed in #7987. (I think we merged the fix day or two ago.) Thanks for checking!

**Pull request merged**
