### PR TITLE
Revert "[Dataset] [DataFrame 2/n] Add pandas block format implementation (partial) (#20988)

### PR DESCRIPTION
**Pull request by jjyao**
This reverts commit 4a55d10bb1b70971f50a3872421f2c1eebd84e64.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Seems this PR caused `//python/ray/tests:test_threaded_actor` and `pg_long_running_performance_test` (https://buildkite.com/ray-project/periodic-ci/builds/2408) to fail. I don't know why but I think we can revert it first.

**Review by scv119 — APPROVED** [review]

**Comment by kfstorm** [comment]
Anyone will follow up on `pg_long_running_performance_test`? I don't have the permission to view the log.

**Comment by rkooo567** [comment]
Jiajun will bisect it!

**Review by rkooo567 — APPROVED** [review]

**Comment by kfstorm** [comment]
BTW, I've tested `test_threaded_actor` locally on commit 4a55d10bb1 and it passes.

**Comment by rkooo567** [comment]
Failing tests seem unrelated. (also interestingly threaded actor test didn't fail in this CI...)

**Comment by kfstorm** [comment]
@jjyao That makes sense. Will test it again today.

**Comment by jjyao** [comment]
Let me know if you need any help @kfstorm.

**Comment by ericl** [comment]
@jjyao looking at the flaky test dashboard, it seems linux://python/ray/tests:test_threaded_actor and linux://python/ray/tests:test_plasma_unlimited started flaking with this PR, but didn't exactly get fixed when this PR got reverted.

Threaded actor actually fixed itself the build before the revert, and plasma unlimited took 1 more build to get fixed.

I'm wondering if this was just a fluke, and the real cause was some environmental issue in the build cluster (i.e., slow disks).

**Comment by jjyao** [comment]
@ericl there is also pg_long_running_performance_test nightly test that fails with this commit.

**Comment by ericl** [comment]
Could be some other PR in the recent changes? This one seems pretty unlikely

**Comment by jjyao** [comment]
Based on bisect, this is the exact  commit that starts to fail. Also I tried to run thread_actor test locally with and without this commit, it's slower with this commit.

**Comment by ericl** [comment]
Ah, I see an eager import of pandas, that's the only thing I can think of that might be the cause.

 @kfstorm it's not enough to catch import error, we should avoid even loading pandas until datasets is used. Otherwise, importing pandas early could cause problems.

**Comment by kfstorm** [comment]
@ericl Thanks for the investigation. Could you point out the exact location of pandas import?

**Comment by ericl** [comment]
Line 7 of pandas_block.py

**Comment by kfstorm** [comment]
@ericl But there's `import pyarrow` in `arrow_block.py` as well, and both are `try except` protected. Is the `try except` not efficient? Shouldn't the test fail on importing `arrow_block.py` as well? Am I missing something?

**Comment by ericl** [comment]
I'm not sure, but pandas is a different library. Try it out?

**Comment by kfstorm** [comment]
@ericl I tried `pip install ray[data]` in a newly created virtualenv, and the log shows that both `pandas` and `pyarrow` are installed as dependencies. I also tried `pip install ray` and `pip install ray[default]`, and neither `pandas` nor `pyarrow` is installed.

So I'm confused now. In which case will `pyarrow` be installed as a dependency but not `pandas`?

**Comment by ericl** [comment]
Maybe it's just pyarrow doesn't break the test. I'd just try it and see if it fixes the issue, it's just a guess.

**Comment by kfstorm** [comment]
@ericl I also tried running `python release/nightly_tests/placement_group_tests/long_running_performance_test.py --local --num-pgs-stage=10` locally without pandas installed. No errors occurred. Could you please paste the original error log?

**Comment by kfstorm** [comment]
I've found the root cause of slowing down `test_threaded_actor`. Before my PR: `import ray` costs about 0.7s, but it's 1.0s after my PR. The reason is that `import pandas` adds about 0.3s overhead and maybe it leads to much slower worker spawning. If I run `pip uninstall pandas` then `import ray` costs about 0.7s with my PR.

So I'm going to implement lazy import to replace the `import pandas` at the beginning of `pandas_block.py` to speed up `import ray`. The change will look like this:

```diff
diff --cc python/ray/_private/utils.py
index 1c5d8cdb5a2,1c5d8cdb5a2..71959283f84
--- a/python/ray/_private/utils.py
+++ b/python/ray/_private/utils.py
@@@ -1156,3 -1156,3 +1156,15 @@@ def check_dashboard_dependencies_instal
          return True
      except ImportError:
          return False
++
++
++def lazy_import(name):
++    if name in sys.modules:
++        return
++    spec = importlib.util.find_spec(name)
++    loader = importlib.util.LazyLoader(spec.loader)
++    spec.loader = loader
++    module = importlib.util.module_from_spec(spec)
++    sys.modules[name] = module
++    loader.exec_module(module)
++    return module
diff --cc python/ray/data/impl/pandas_block.py
index ffbbcfbaa83,ffbbcfbaa83..fca654bdc8f
--- a/python/ray/data/impl/pandas_block.py
+++ b/python/ray/data/impl/pandas_block.py
@@@ -1,10 -1,10 +1,11 @@@
  from typing import Dict, List, Tuple, Any, TypeVar, Optional, TYPE_CHECKING
++from ray._private.utils import lazy_import
  
  import collections
  import numpy as np
  
  try:
--    import pandas
++    pandas = lazy_import("pandas")
  except ImportError:
      pandas = None

```

**Comment by jjyao** [comment]
@clarkzinzow Do we even need to import data module when we import ray?

**Comment by clarkzinzow** [comment]
@jjyao No, if it's getting imported on `import ray` that's definitely unintentional. I'll try to see why that's happening!

**Comment by jjyao** [comment]
Oh, I see the reason, thanks for the explanation!

**Comment by clarkzinzow** [comment]
@jjyao We could try to get the best of both worlds by subclassing `types.ModuleType`, implementing `__getattr__` that lazy loads modules, and doing some module munging to lazy-load the `data` module on use (`ds = ray.data.read_parquet()`) rather than eagerly load it on package import (`import ray`). Werkzeug [used to do this](https://github.com/pallets/werkzeug/blob/c3322bd51fb511fa4be6f208ad048f87d57694d7/src/werkzeug/__init__.py#L181-L209). However, this would most likely mess up most IDE's introspection of the `ray` package and possibly mess up code completion in notebooks, so I don't think it's worth it. Werkzeug [moved away from this](https://github.com/pallets/werkzeug/pull/1640) after all.

**Comment by clarkzinzow** [comment]
Actually @jjyao @kfstorm it seems as if we can just use the `importlib.LazyLoader()` as @kfstorm suggested, but for the `data` and `workflow` modules in `python/ray/__init__.py`. I'd be curious to know how well that would work, if that would break anything.

**Pull request merged**
