### PR TITLE
[core] `check_health` address not handling names with ":"

### LINKED ISSUE #38785: [Ray Core][GCS FT] ray status after head node restart in FT mode
### What happened + What you expected to happen

I have my local deployment of Ray with GCS in FT mode. Let's assume this is a single node cluster.

After the head node restart from failure, once I submit a new job to the recovered cluster, the `ray status` CLI constantly fails with below error:

```
Traceback (most recent call last):
  File "/miniconda/envs/ray/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/miniconda/envs/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2474, in main
    return cli()
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/miniconda/envs/ray/lib/python3.10/site-packages/ray/scripts/scripts.py", line 1950, in status
    if not ray._raylet.check_health(address):
  File "python/ray/_raylet.pyx", line 2597, in ray._raylet.check_health
ValueError: too many values to unpack (expected 2)
```

### Versions / Dependencies

2.6.3

### Reproduction script

1. create a single node ray cluster with external redis for gcs FT
2. submit a single ray job with long running command such as `sleep 10000`
3. restart the head the node (in a new machine)
4. submit a new job (not sure if this is required)
5. run `ray status`, and you may see the above error

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
We could also pass in address names with ":" for ray address, thus allowing ":" to split it into more than 2 parts. 

Related, but we won't close https://github.com/ray-project/ray/issues/38785

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Q: do you know which address was passed to the given issue?

**Comment by rickyyx** [comment]
> Q: do you know which address was passed to the given issue? It means after we merge this PR, the user will still see the failure right?

oh no, we do `rsplit(s, 1) which will split to max 2 tokens.

**Comment by rickyyx** [comment]
> Q: do you know which address was passed to the given issue?

Asked in the original issue

**Comment by rkooo567** [comment]
I am hesistant to merge the PR before we knew the exact address. Is this common you have address with more than one :?

**Comment by rickyyx** [comment]
> I am hesistant to merge the PR before we knew the exact address. Is this common you have address with more than one :?

But the change in this PR actually makes things more resilient to malformed address? I think this is the right check to enforce regardless the response from the original issue though.

**Comment by rkooo567** [comment]
Hmm feel like it is not very meaningful changes here though. We can merge it, but if the address is malformed like that, it basically means even ray start should already fail (and we should have better format check in the highest layer by e2e principle, i.e., ray start)?

**Comment by rickyyx** [comment]
> Hmm feel like it is not very meaningful changes here though. We can merge it, but if the address is malformed like that, it basically means even ray start should already fail (and we should have better format check in the highest layer by e2e principle, i.e., ray start)?

Seems in the original issue, it didn't raise an issue when ray start? But we could wait for OP to gather more info. If that's the case, we should not mark it as P0 as of now?

**Comment by rkooo567** [comment]
Hmm yeah it is pretty odd. Let's just merge this (since it will give a better error message for us upon failure) and not close the issue until the person replies. And we downgrade the priority (until the person replies)?

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
