### PR TITLE
[Data/Train] Fix ipython representation

### PR DESCRIPTION
**Pull request by amogkam**
Fixes a bug where repr would fail on ipython shell

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Stamping, but is there a way we could test this in some way? E.g., validating at least we hit the right code paths in different mock envs.

**Comment by amogkam** [comment]
this is tested here right https://github.com/ray-project/ray/pull/35414/files#diff-985f87e17650b080fd02c45cca10db51bfd291160c9312c60fb2a2da692433cb

**Comment by zhe-thoughts** [comment]
Echoing what @ericl said

And @amogkam I need this PR to land on master first. Then I'll review / approve the cherry pick

**Comment by amogkam** [comment]
failing tests are unrelated, going to merge

**Pull request merged**
