### PR TITLE
Partial Bazel BUILD file

### PR DESCRIPTION
**Pull request by rsepassi**
Partial BUILD file. Missing: external deps, flatbuffers, and credis

Could serve as a starting point for full conversion (#2887)

### CODE REVIEW

**Comment by ericl** [comment]
Is this buildable as is? I get errors like

```
ERROR: /home/eric/Desktop/ray-private/BUILD:43:1: //:raylet_lib: invalid label 'THIRDPARTY:boost' in element 10 of attribute 'deps' in 'cc_library' rule: invalid target name 'THIRDPARTY:boost': target names may not contain ':'
```

Also, I had to create  WORKSPACE file that grabs the go rules:
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "io_bazel_rules_go",
        remote = "https://github.com/bazelbuild/rules_go.git",
            commit = "a390e7f7eac912f6e67dc54acf67aa974d05f9c3",
            )
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

```

**Comment by pcmoritz** [comment]
Thanks, this is great! How did you handle building arrow/including it into the build?

**Comment by rsepassi** [comment]
This does not build as-is unfortunately because the external deps need to
be built. Internally all the external libraries are also built with Bazel,
but externally they need to use other means:
https://docs.bazel.build/versions/master/external.html

**Comment by rsepassi** [comment]
Have some comments at the top of the BUILD file re what needs to be done: https://github.com/ray-project/ray/pull/2899/files#diff-96239ee297e0a92ac6ff96a6bc434ef0R5

**Comment by robertnishihara** [comment]
Replacing with #3806 and other subsequent PRs.

**Pull request closed without merging**
