### PR TITLE
[Workflow] Cleanup workflow docs

### LINKED ISSUE #26971: [Workflow][Docs] Update Workflow Docs from Workflows to Workflow (removing s)
### Description

In the past I have seen inconsistent naming for Ray Workflow in both **Ray Workflow** and **Ray Workflows** (i.e. with and without "s").

Most recently, in Ray Summit 2022 (https://www.anyscale.com/ray-summit-2022/agenda/sessions/230) it is called without s while in latest and master docs (https://docs.ray.io/en/master/workflows/concepts.htm) it is called with s.  After confirming with Workflow team, the most updated correct name should be Workflow without s.  So we need to update the docs.

### Link

https://docs.ray.io/en/latest/workflows/concepts.html
https://docs.ray.io/en/master/workflows/concepts.htm

### PR DESCRIPTION
**Pull request by suquark**
Signed-off-by: Siyuan Zhuang <suquark@gmail.com>

## Why are these changes needed?

* Unify the component name - "Ray Workflow" instead of "workflow", "workflows", "Ray workflow", "Ray workflows", "Ray Workflows"
* Remove remaining part about virtual actors

## Related issue number

Closes #26971

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by suquark** [comment]
Note: there will be a link CI check failure due to renaming https://docs.ray.io/en/master/workflows/concepts.html -> https://docs.ray.io/en/master/workflow/concepts.html. This is normal.

**Comment by iycheng** [comment]
LGTM. Please create a ray 2.0 cherry-pick pr (similar to https://github.com/ray-project/ray/pull/27114)

**Review by fishbone — APPROVED** [review]

**Comment by suquark** [comment]
The CI failure is unlikely related to the doc cleanup. I'll merge it.

**Comment by zhe-thoughts** [comment]
hi folks, great work here :) quick note that let's also not forget "ticket hygiene" of applying / removing labels as appropriate

**Pull request merged**
