### PR TITLE
Revert "[docs][examples] Ray Core walkthrough for beginners"

### PR DESCRIPTION
**Pull request by maxpumperla**
Reverts ray-project/ray#32814, seems to break docs

### CODE REVIEW

**Comment by maxpumperla** [comment]
@clarng  reverting prior PR

**Comment by maxpumperla** [comment]
fixes #34064

**Review by krfricke — APPROVED** [review]

**Review by richardliaw — APPROVED** [review]

**Comment by clarng** [comment]
Can we cherrypick this to 2.4.0?

cc @zhe-thoughts  for approval

**Comment by zhe-thoughts** [comment]
Approved for picking

**Pull request merged**
