### PR TITLE
[RLlib] Derive SAC model from AlgorithmConfig["model"] instead of MODEL_DEFAULTS

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Signed-off-by: Artur Niederfahrenhorst <artur@anyscale.com>

## Why are these changes needed?

AlgorithmConfig.model is a deepcopy of MODEL_DEFAULTS.
When creating SAC models, we don't use AlgorithmConfig.model (which might be configured by users) but configure directly based on MODEL_DEFAULTS.

## Related issue number

https://github.com/ray-project/ray/issues/31783

### CODE REVIEW

**Comment by gresavage** [comment]
The issue is actually more pervasive than just SAC and using custom models-

I ran into the same *kind* of issue as mentioned in #31783 with PPO: I set up a custom policy which subclassed PPO, as well as a custom AlgorithmConfig which subclassed PPOConfig.

In the custom PPOConfig I set default values for settings whose values themselves are dicts (example: PPOConfig.model['custom_model_config']). Then, at runtime, I passed additional values to tune.run in the custom_model_config dict. Rather than the default values being merged with the runtime values, the custom_model_config dict was completely overwritten by the runtime values.

The issue lies everywhere an Algorithms `__init__` method sets up the config as follows:

```
def __init__(obs_space, action_space, config)
        config = dict(ray.rllib.algorithms.<algo>.AlgorithmConfig().to_dict(), **config)
```

By constructing this way it's essentially the same as doing a `<dict object>.update(<new dict>)` which has no recursion, and thus any values which are dictionaries will be overwritten.

Instead, the first line of `__init__` should be:

```
def __init__(obs_space, action_space, config)
        config = ray.tune.utils.merge_dicts(ray.rllib.algorithms.<algo>.AlgorithmConfig().to_dict(), **config)
```

Below are a list of algorithms I know to use the bad methodology in their init:

- PPO
- SAC
- DDPG
- ApexDDPG
- SimpleQ
- APPO
- Bandit
- BC
- MARWIL
- DDPPO
- Dreamer
- IMPALA
- MADDPG
- MAML
- MBMPO
- QMix

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for pointing that out. That's very related (but not the same) issue that we'll treat with an updated way of configuring models soon. (And possibly other config objects). But I found that the same issue you pointed was in the RNNSAC code.

**Comment by gresavage** [comment]
Oops, my apologies! Thanks again for your hard work.

**Review by sven1977 — APPROVED** [review]
LGTM.

**Pull request merged**
