### PR TITLE
Improve Clang-IWYU to automatically make #include fixes

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Uses `fix_include` from Clang's include-what-you-use tool to make automatic `#include` fixes and produces a diff that can be used to patch includes.

## Related issue number

#7081

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by simon-mo** [comment]
I recommend leave this PR here for future reference. Browsing through the diff, I think the includes are too verbose right now:
- `<bits/...>` includes are distraction and hurts iteration time. A developer forgot to include shared_ptr now needs to go through CI again.
- A lot of transitive includes are well covered by `common/...`, `core_worker.h`, `...client.h`. By including these headers, developer understand they also included all necessary protobufs, common data structures (like ObjectID). The fixes bringing those transitive includes in-scope are unnecessary and again hurt readability.

IWYU is a great step but unfortunately I think the changes actually won't make the code better. There are too much false positive.

**Comment by mehrdadn** [comment]
@simon-mo This PR is just intended to improve what's already there—the IWYU output is less useful before this PR than after it, since currently there's no diff at all. I'm not suggesting we should apply the diffs directly, but with this PR at least we have a diff. (And it resolves a couple bugs with the existing code too.) There shouldn't be any harm in merging it (just like there hasn't been any harm with the existing code for this).

**Review by simon-mo — APPROVED** [review]
Good point. Since this change only applies to existing non-fatal CI steps, we can include it and serve as a template for future use.

**Comment by mehrdadn** [comment]
Thanks!

**Pull request merged**
