### PR TITLE
Revert "Enable TryCreateImmediately to use the fallback allocation path"

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#16522

### CODE REVIEW

**Comment by amogkam** [comment]
cc @ericl #16522 is breaking Ray Client with Dask tests.

**Review by architkulkarni — APPROVED** [review]

**Comment by amogkam** [comment]
Emergency merge due to build failure

**Comment by ericl** [comment]
I think the failure is actually unrelated, since the PR passes the tests. Was Dask just upgraded?

**Comment by amogkam** [comment]
Ah yes Dask just had a release. Sorry my bad, I though this PR was related. Let's re-revert this and I'll make a new PR to pin the dask version

**Pull request merged**
