### PR TITLE
Use requests.Session object to reuse connections in PolicyClient

### LINKED ISSUE #30136: [RLlib] PolicyClient does not reuse http sessions
### Description

In `PolicyClient._send(self, data)` a post request is made using 'requests.post'. This is suboptimal and slow. Reusing connections by using a session prevents handshaking on every request.

In the constructor of `PolicyClient `a `requests.Session` object could be made that is then used in the `_send` method to perform all post requests.

### Use case

Improve performance and resource usage of PolicyClient

### PR DESCRIPTION
**Pull request by MattiasDC**
## Why are these changes needed?
Uses connections/resources more efficiently in PolicyClient. By using a `requests.Session` object, instead of using `requests` directly, connections are reused.

## Related issue number
Closes #30136

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests

### CODE REVIEW

**Comment by MattiasDC** [comment]
@sven1977 this has been marked as stale, could someone do a review?

**Comment by MattiasDC** [comment]
@sven1977 this has been marked as stale, could someone do a review?

**Comment by ArturNiederfahrenhorst** [comment]
@sven1977 @kouroshHakha According to https://requests.readthedocs.io/en/latest/user/advanced/#session-objects, sessions can bring significant speedups.

I've timed this a little and from a quick look I could not observe a speedup.
Nevertheless, since the code definitely works, I think we should merge this.

**Review by ArturNiederfahrenhorst — APPROVED** [review]

**Comment by MattiasDC** [comment]
Hi @kouroshHakha,

I agree that it's cleaner to close the session. Typically a session is automatically closed when you use it as a context manager. There is an example in the [requests doc](https://requests.readthedocs.io/en/latest/api/#requests.Session).
Using it here as a context manager would imply that either the session object has to be passed as an argument to the constructor of the PolicyClient, and the context manager is created 'outside' of the PolicyClient, or we make PolicyClient a context manager itself.

Alternatively we simply call `self.session.close()` in the destructor of the PolicyClient. This seems to me the approach with the least impact on the user, while still adhering to closing sessions. If you're ok with this approach, I can update the PR.

**Comment by MattiasDC** [comment]
@kouroshHakha I agree with your suggestion and pushed it

**Comment by ArturNiederfahrenhorst** [comment]
Cool stuff! :)

1. Since the tests are running on nightly wheels, they failed because we are migrating major stuff there (@MattiasDC please push again tomorrow, CI should run on updated wheels then)
2. One last minor request: Can you document the reasoning in the code? Basically, include in the docstring that using a session can lead to speedups and that it must be closed by the creator of the session itself.

Thanks for this PR!

**Comment by MattiasDC** [comment]
@ArturNiederfahrenhorst can you have a look at the ones still failing and let me know if they are caused by my PR?

**Comment by kouroshHakha** [comment]
All RLlib tests are passing. Merging now ...

**Review by kouroshHakha — APPROVED** [review]

**Pull request merged**
