### PR TITLE
Revert "[runtime_env] Move URI deletion logic to the agent, remove ut…

### LINKED ISSUE #18528: [nightly-test] many_nodes_actor_test is broken
Last two many_node_actor_test failed without infra failure: [[1](https://buildkite.com/ray-project/periodic-ci/builds/962#218702ed-aff2-4efb-88c9-f323f74e772a)][[2](https://buildkite.com/ray-project/periodic-ci/builds/965#9777f227-ca42-4517-8833-f00474313896)]

The first known [broken](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_PrExYMKYjYwPcuA4pW1mpH8Q?command-history-section=command_history) commit is 1587eb22f030047469dee0a211de9072392fe9ae
Last known [unbroken](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/app-config-details/bld_SAnSpemXSzKsa1n19ESMdEqn) commit is 688dbeb4c

### PR DESCRIPTION
**Pull request by scv119**
As part of bisecting result, https://github.com/ray-project/ray/pull/18471 breaks the many_nodes_actor_test nightly test so we revert it. 

Here is the bisecting result:

2fcfea10b3604d61c6fe664b9360043f1b55de3b[ breaks the test]( https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_WDsACjpjHrEzrH1GgD1tTRXL)
its parent f2d8f23 [passes the test](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_Vpky45WfR7jR8zdAjsPv4uU2?command-history-section=command_history)

While waiting for author's confirm, I will trigger a nightly test with this[ reverted PR ](https://github.com/ray-project/ray/tree/test-wheels/fix-many-node-actor-test)to ensure the revert fix the issue.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by scv119** [comment]
huh, with the reverted PR test still fails: https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_MXPJ8TBrhZiCVpk46N9mexsd?command-history-section=command_history

**Comment by edoakes** [comment]
@scv119 this seems unlikely to me to be the culprit for breaking the test given that none of the codepaths touched in this PR should be exercised at all in the test given that it doesn't use runtime_env

**Comment by edoakes** [comment]
@scv119 seems like there might be some flakiness here given that it's still failing after the revert?

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
@edoakes yup, the weird part is the test has been very stable until last weekend. need some more investigation.

**Comment by rkooo567** [comment]
I wonder if there was an infra update. Maybe we can ping the prod team?

**Comment by rkooo567** [comment]
(Or maybe test is originally flaky, but this pr increaes the freq?)

**Comment by scv119** [comment]
@iycheng there might some test runs help you to investigate.

**Pull request closed without merging**
