### PR TITLE
[RLlib] Get rid of experimental_relax_shapes

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Signed-off-by: Artur Niederfahrenhorst <artur@anyscale.com>

## Why are these changes needed?

Our logs:
Screenshot 2022-10-11 at 16 36 53

From the docs of tf.function:
Screenshot 2022-10-11 at 16 37 12

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
@ArturNiederfahrenhorst is this still relevant?

**Comment by ArturNiederfahrenhorst** [comment]
@krfricke Yes this is still relevant, reopening

**Comment by ArturNiederfahrenhorst** [comment]
@sven1977 I've been trying to reproduce these warnings I got for the original post. They are not coming up anymore.
Anyway: experimental_relax_shapes is being deprecated: https://www.tensorflow.org/api_docs/python/tf/function

**Review by sven1977 — APPROVED** [review]
stamp! Thanks for the upgrade @ArturNiederfahrenhorst .

**Pull request merged**
