### PR TITLE
Revert "[Java] upgrade jar deps to fix cves"

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#16870

### CODE REVIEW

**Comment by amogkam** [comment]
#16870 looks like it's breaking CI

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Per Amog, seems this was a fluke. Should we undo the revert?

**Comment by richardliaw** [comment]
Let's undo the revert then

**Comment by amogkam** [comment]
Made the revert PR: https://github.com/ray-project/ray/pull/16899

**Pull request merged**
