### PR TITLE
[Dashboard] Update dashboard port checking to prevent unexpected port change

### PR DESCRIPTION
**Pull request by allenyin55**
## Why are these changes needed?

Dashboard port sometimes is incremented unexpectedly (when the default port is available) when restarting ray clusters with short delays.

The root cause seems to be the socket gets into the `TIME_WAIT` state and can't be immediately reused (see the last example [here](https://docs.python.org/3/library/socket.html) for more details). Setting the `SO_REUSEADDR` option prevents this from happening.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [x] Manually tested
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by mfitton — APPROVED** [review]
Looks good! I'm glad you found the cause of this, it'd happened to me on occasion.

**Comment by allenyin55** [comment]
Can we merge this? The tests failures don't seem relevant.

**Comment by mfitton** [comment]
@allenyin55 I actually am not able to merge pull requests. @rkooo567 could you please merge?

**Comment by rkooo567** [comment]
i guess this is not working. CI tests are all failing, and metrics agent test on Windows also fail.

**Comment by rkooo567** [comment]
Please merge the latest master, so that I can see if the test failure is unrelated.

**Comment by allenyin55** [comment]
> Please merge the latest master, so that I can see if the test failure is unrelated.

Just did.

**Pull request merged**
