### PR TITLE
Fix cluster page stack trace and flame graph links

### LINKED ISSUE #37844: [Dashboard] Links to Stack Trace and CPU Flame Graph don't work behind a reverse proxy
### What happened + What you expected to happen

When hosting the Ray dashboard behind a reverse proxy, Stack Trace and CPU Flame Graph links from the Clusters page do not work. On other pages like the Jobs page these links work fine. The issue appears to be that the broken links are resolved with a leading `/`, which does not work behind a reverse proxy.

Looking at the code in question, it seems like most Stack Trace/CPU Flame Graph links use the `ProfilingLink` file for rendering links, but for whatever reason the Clusters page introduces additional redundant code for these links that is equivalent apart from including a leading `/`.

### Versions / Dependencies

This issue exists on Ray >=2.4

### Reproduction script

This is fairly easy to identify simply by looking at the code

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by noahjax**
## Why are these changes needed?
In addition to removing unnecessary code duplication, these changes fix the links to the stack trace and flame graph pages when behind a reverse proxy. Previously the links used in `NodeRow.tsx` included a leading `/` that is not included in other links and does not work when hosting the Ray dashboard behind a reverse proxy.

## Related issue number
Closes https://github.com/ray-project/ray/issues/37844

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by alanwguo** [comment]
@chaowanggg , can you take a look at this PR? Does this have conflicts with your current work on "task-based" profiling links?

**Review by alanwguo — APPROVED** [review]

**Comment by noahjax** [comment]
@alanwguo Thanks for approving. Is there anything else I can do to help get this merged?

**Comment by alanwguo** [comment]
@rkooo567 , can you merge?

**Comment by noahjax** [comment]
@rkooo567 Is there anything I can do that would help this merge?

**Comment by rkooo567** [comment]
Sorry I updated the branch now

**Pull request merged**
