### PR TITLE
Add many_ppo long running test

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This test covers the 100% raylet cpu bug found in https://github.com/ray-project/ray/pull/12148

### CODE REVIEW

**Comment by richardliaw** [comment]
oh nice, do you have to add instructions for how to run this + what to expect?

**Review by edoakes — APPROVED** [review]
LGTM. Do you have initial results from running it that we can use to verify there aren't regressions for the next release?

**Comment by ericl** [comment]
It should run successfully to completion (but this takes too long for a small cluster). No results, just check CPU is stable.

**Comment by edoakes** [comment]
Sounds good, can you please add that to a bullet in `release/RELEASE_PROCESS.md`?

**Comment by ericl** [comment]
@edoakes I think this is the contract for all long running tests, it should be the same as the others (e.g., apex which this is copied from)

**Comment by edoakes** [comment]
There's no existing check for CPU being stable. I'm not even completely sure what to look for given that description.

**Comment by ericl** [comment]
@edoakes it was poorly documented, I recently added a clause here to check the AWS console: https://github.com/ray-project/ray/blob/master/release/RELEASE_PROCESS.rst

For any of the tests, if the CPU load increases or decreases over time, that's an indication of non-steady-state behavior and a likely bug. This has caught many issues in the past.

**Comment by edoakes** [comment]
Ah, beautiful. Thanks for the link -- I should have checked the docs for that clause!

**Pull request merged**
