### PR TITLE
Remove `requests` from blacklist of minimal install test

### PR DESCRIPTION
**Pull request by jiaodong**
While working on https://github.com/ray-project/ray/pull/20577 we noticed `requests` module is not blacked listed in minimal install test, but not sure why. As a result we missed coverage on P0 issue like https://github.com/ray-project/ray/issues/20574.

This is an attempt to see what would happen if we blacklist it and if we're able to get any signals from CI.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
@jiaodong looks like it fails minim-install. that means we can close this right?

**Comment by jiaodong** [comment]
@wuisawesome yep so minimal install actually requires `requests` module to be installed, or at least is installed somewhere. I don't know minimal install tests well enough if this is expected, but this PR served its purpose to verify. Do you mind tagging other relevant folks if you think this info needs to be further triaged ?

**Comment by jiaodong** [comment]
cc: @krfricke 

We require `requests` module installed in order to run `minimal install` tests but in the meantime we skipped it in dependency blacklist check: https://sourcegraph.com/github.com/ray-project/ray/-/blob/ci/travis/check_minimal_install.py?L18

Is it intentional that we should ensure to always keep `requests` dependency in minimal test, or we should rather exclude it ?

**Comment by krfricke** [comment]
Just to follow up here (sorry for the delay), `requests` is automatically installed by conda (and might be required there?). We could explicitly uninstall it in the minimal environment build, do you want to try that? (Not sure if it's actually possible because it seems to be a core conda dependency)

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by krfricke** [comment]
@jiaodong seems like `requests` is required by one of the dependencies - can we close this?

**Comment by jiaodong** [comment]
hi @krfricke thanks for getting back on this ! let me make a commit to remove the commented "requests" then given it's required to avoid confusion, does that sound good to you ?

**Review by krfricke — APPROVED** [review]

**Pull request merged**
