### PR TITLE
[Doc] [Jobs] Document `JobDetails`, `JobType` and `DriverInfo`

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
The classes `JobDetails`, `JobType` and `DriverInfo` are exposed to the user because they are the return type of `JobSubmissionClient.get_job_info`, so we need to document them. 

This PR adds them to the API reference.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
Please add the `PublicAPI` decorator to the classes

**Comment by architkulkarni** [comment]
@alanwguo I have marked these as Beta because there are some TODOs, but if we think the changes will be backwards compatible we can mark them as "stable".  What do you think?

**Review by DmitriGekhtman — APPROVED** [review]
stamp

**Comment by architkulkarni** [comment]
test_cli broken on master
Java test failure `Ray component dashboard_agent_http is trying to use a port number 52365 that is used by other components.` unrelated
test_job_agent and test_http_job_server were broken on master, unrelated. Other job tests are passing.
rllib `test_pendulum` flaky on master and unrelated
rllib `test_memory_leak` flaky on master and unrelated

**Comment by architkulkarni** [comment]
Merging now, we can always bump to "stable" later.

**Comment by architkulkarni** [comment]
The `test_job_agent` failure was actually related to this PR and not related to the previous breakage, which was unrelated.

**Comment by architkulkarni** [comment]
It's likely because `pydantic` is not in the `ray-minimal` dependencies.

**Pull request merged**
