### PR TITLE
bump jobs version after making a backwards-incompatible change

### PR DESCRIPTION
**Pull request by alanwguo**
Cherry-pick of #27281

Backwards incompatible change was #25902

2.0.0 cherry-pick but not a rc0 blocker

Signed-off-by: Alan Guo <aguo@anyscale.com>

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
is this necessary given the job API is still beta? (cc @architkulkarni ?)

**Comment by rkooo567** [comment]
also is it an internally tracked version?

**Comment by scv119** [comment]
@rkooo567 @alanwguo who should approve this before I merge it?

**Comment by rkooo567** [comment]
I think @architkulkarni or @edoakes

**Review by architkulkarni — APPROVED** [review]

**Comment by architkulkarni** [comment]
@rkooo567 What do you mean by internally tracked?  I think the idea is to just bump it every time there's a backwards incompatible change, and the `CURRENT_VERSION` constant is the source of truth.

I think this PR is necessary for third-party job managers that need to support multiple versions of Ray and need to call into one of the REST API endpoints that had a backwards incompatible change, though there might be some creative way around it without this PR.

**Comment by scv119** [comment]
@alanwguo can you rebase? looks a bunch of tests are failing.

**Pull request merged**
