### PR TITLE
[ci][v2/1] move lint logic into its own script

### PR DESCRIPTION
**Pull request by can-anyscale**
This is part of a series of PR to move some CI jobs into a separated blocking pipeline.

- This PR moves lint logic into its own script and its own pipeline. Purely and refactoring PR with no additional logic, where the bulk is to move files around

Test strategies:
- CI tests

### CODE REVIEW

**Comment by can-anyscale** [comment]
Screenshot 2023-07-12 at 12 29 18 PM

**Review by aslonnie — COMMENTED** [review]
seems like a lot of changes. do we really need to move all the files?

what is the overall plan? and what is the overall structure of these lints?

**Comment by can-anyscale** [comment]
@aslonnie: they look like a lot but there are two main changes:

- mv ci/lint ci/v2/lint
- move all lint functions from ci.sh to ci/v2/lint.sh

All other changes are places that hard code the location of the files that are moved.

So at a high level, move lint and its dependencies from ci.sh to its own script, no other logical changes

**Review by aslonnie — APPROVED** [review]
gogogo!

**Pull request merged**
