### PR TITLE
move profiling code to a new file and fix thread safety

### PR DESCRIPTION
**Pull request by raulchen**
## What do these changes do?

- Move profiling code to a new file `python/ray.profiling.py`.
- Use a `Profiler` class to hold profiling events buffer, which was previously held in the worker (`worker.events` -> `worker.profiler.events`).
- Protect the events buffer with a lock (because it's being accessed from 2 threads).
- Minor efficiency improvement: for non-raylet code path, events will be logged only if worker mode is worker. Thus we don't need to create new LogSpan when worker mode isn't worker (see the old `_log` function and the new `profile` function).

## Related issue number
#2385

Previously discussions: https://github.com/ant-tech-alliance/ray/pull/50

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
LGTM

**Comment by robertnishihara** [comment]
Thanks! There are some linting issues.

**Comment by raulchen** [comment]
Thanks, linter error fixed.

**Comment by robertnishihara** [comment]
Thanks for the fix!

**Pull request merged**
