### PR TITLE
[Release] Download compressed metrics from cluster

### PR DESCRIPTION
**Pull request by Yard1**
Signed-off-by: Antoni Baum <antoni.baum@protonmail.com>

## Why are these changes needed?

Compress metric json files before downloading them from the cluster to save bandwidth and time.

For consistency, all json writing/reading code has been abstracted using `write_json` and `read_json` functions.

This is first of iterative improvements aimed at making metrics collection more robust, performant and able to handle long running tests.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
have we done some perf analysis before? My gut feeling is that the root cause is prometheus returning the data slowly when it has cardinality rather than download being slow to the local machine?

**Comment by Yard1** [comment]
@rkooo567 yeah so this is not aiming to fix the root cause - as mentioned in the PR description, this is a simple iterative improvement (there is no reason *not* to gzip the json).

For the "proper" fix, the following are in the works:
* The prometheus queries will be obtained asynchronously.
* Large prometheus metric files will be uploaded directly to s3.

**Comment by rkooo567** [comment]
How much time is saved? I don't prefer to add this unless it is necessary (especially when this PR requires duplicated code in 2 files)

**Comment by Yard1** [comment]
I'll run some benchmarks and get back to you.

**Pull request closed without merging**
