### PR TITLE
simplify ObjectRef::Get

### PR DESCRIPTION
**Pull request by qicosmos**
## Why are these changes needed?

Simplify the usage of ObjectRef<T>::Get, make it more easier  to use.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by AmeerHajAli — COMMENTED** [review]
you need to fix:
cluster_mode_test.cc (check the travis failure).
Can you please keep RAY::GET inside cluster_mode_test.cc?

**Review by AmeerHajAli — CHANGES_REQUESTED** [review]
you need to fix:
cluster_mode_test.cc (check the travis failure).
Can you please keep RAY::GET inside cluster_mode_test.cc?

**Comment by qicosmos** [comment]
> you need to fix:
> cluster_mode_test.cc (check the travis failure).
> Can you please keep RAY::GET inside cluster_mode_test.cc?

Ok, i will fix the compile error.

**Comment by kfstorm** [comment]
@qicosmos Can we ensure there's no additional copy?

**Comment by SongGuyang** [comment]
Why two PR with same changes? https://github.com/ray-project/ray/pull/14233/files

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

**Pull request closed without merging**
