### PR TITLE
Deflake test_dataset.py: split tensor tests

### PR DESCRIPTION
**Pull request by jianoaix**
## Why are these changes needed?
One of the flakiness of test_dataset.py is due to the timeout. This splits out the tensor tests from this big test file.

https://github.com/ray-project/ray/issues/32067

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by clarkzinzow — APPROVED** [review]

**Comment by ericl** [comment]
Need to re-run with master merged? Some bazel version error.

**Review by c21 — APPROVED** [review]
LG

**Comment by jianoaix** [comment]
> Need to re-run with master merged? Some bazel version error.

It seems weird to have Bazel issue as this PR has no change related to that.

**Comment by c21** [comment]
@jianoaix can we rebase and retrigger the CI? thanks.

**Review by amogkam — APPROVED** [review]

**Comment by jianoaix** [comment]
> @jianoaix can we rebase and retrigger the CI? thanks.



> @jianoaix can we rebase and retrigger the CI? thanks.

Is this issue fixed somewhere now?

**Pull request merged**
