### PR TITLE
[CI] Enable CI for the new scheduler.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

@wuisawesome Feel free to merge whenever you think it is needed. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
Thanks so much for making this! I restricted the tests that we run and skipped a few flaky tests. You should probably take a look and make sure I did it correctly though, because I'm not very familiar with the CI. If you think it looks good though, I think we can merge it.

**Review by wuisawesome — APPROVED** [review]

**Comment by rkooo567** [comment]
It looks like the build is broken after the change?

**Comment by rkooo567** [comment]
Added a possible fix. Let's see if it is fixed @wuisawesome

**Comment by wuisawesome** [comment]
#11381 will make the rest of the tests non-flaky, so we may as well wait until then to merge this

**Comment by rkooo567** [comment]
This is currently broken btw. Not famliar enough to bazel to fix the current issue. I think we can have only a single test in the bazel build file now. I tried changing some code to fix it, but it didn't work.

**Comment by rkooo567** [comment]
It looks like Eric's new PR for the new scheduling handles this. I will close

**Pull request closed without merging**
