### PR TITLE
Cherry-pick "[docs] navigation and search fixes #32428"

### PR DESCRIPTION
**Pull request by cadedaniel**
See https://github.com/ray-project/ray/pull/32428

### CODE REVIEW

**Comment by jjyao** [comment]
This PR might have caused some issues. @justinvyu could you add some details.

**Comment by zhe-thoughts** [comment]
@richardliaw @maxpumperla I thought we decided to make the search improvement change in 2.4? Could you confirm? Thanks

**Comment by justinvyu** [comment]
@cadedaniel @zhe-thoughts This PR currently breaks the right hand side navigation UI on the docs.

**Comment by cadedaniel** [comment]
OK. Let's not merge. @maxpumperla can you fix this so it can go into 2.3?

**Pull request closed without merging**
