### PR TITLE
[Core] Deflake test_dedup_error_warning_logs

### LINKED ISSUE #41519: [CI] `linux://python/ray/tests:test_output` is failing/flaky on master.
....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_output-END
....

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
When running on test machine with limited memory, the test might fail due to Ray oom killer.

## Related issue number
Closes #41519

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
Hmm if it always oom fail, it won't test anything? Is there any way to just avoid oom by limiting concurrency or sth like that? The test is not supposed to use high memory.

**Comment by jjyao** [comment]
> Hmm if it always oom fail, it won't test anything?

It still test things since all the assertions are still there.

**Comment by rkooo567** [comment]
Hmm still feel a little hacky though. I feel like it is probably more ideal just creating less actors than 30? (like 10 should still trigger the warning?)

**Review by rkooo567 — APPROVED** [review]
Comment is not a hard blocker

**Comment by jjyao** [comment]
>  Hmm still feel a little hacky though. I feel like it is probably more ideal just creating less actors than 30? (like 10 should still trigger the warning?)

I think it's fragile to figure about a number that's enough to trigger the warning without OOM since it depends on the test machine and the environment. With the current way, we don't need a figure out an exact number and it should just work as long as all assertions pass.

**Pull request merged**
