### PR TITLE
[ci] add a gpu build for core

### PR DESCRIPTION
**Pull request by can-anyscale**
Add a gpu build for core to run multi-gpu tests. This is requested by core team since they are adding a few gpu tests for core DAG work.

Test:
- CI

### CODE REVIEW

**Comment by can-anyscale** [comment]
once this merge, on your buildkite multigpu test step, add the `depends_on: coregpubuild` (so that the step runs only after coregpu build already fininshes), and i think the step will work

**Review by stephanie-wang — APPROVED** [review]

**Review by aslonnie — APPROVED** [review]
could you or @stephanie-wang add a bit more context? is this for the DAG work?

**Comment by stephanie-wang** [comment]
> could you or @stephanie-wang add a bit more context? is this for the DAG work?

Yes, we need a small multi-GPU instance for a few tests.

**Comment by can-anyscale** [comment]
i added what @stephanie-wang said to the pr description

**Pull request merged**
