### PR TITLE
Revert "[train] Restructure `ray.train` HuggingFace modules"

### PR DESCRIPTION
**Pull request by cadedaniel**
Reverts ray-project/ray#35270
Screen Shot 2023-05-18 at 10 04 24 AM

### CODE REVIEW

**Comment by matthewdeng** [comment]
I saw this and didn't think it was related:
```
Document: ray-core/actors/async_api
--
  | -----------------------------------
  | **********************************************************************
  | File "ray-core/actors/async_api.rst", line 241, in default
  | Failed example:
  | import concurrent
  |  
  | refs = [some_task.remote() for _ in range(4)]
  | futs = [ref.future() for ref in refs]
  | for fut in concurrent.futures.as_completed(futs):
  | assert fut.done()
  | print(fut.result())
  | Expected:
  | 1
  | 1
  | 1
  | 1
  | Got:
  | [09:30:14 AM] ERROR    exception calling callback for <Future at                               0x7f02a09c6290 state=finished returned int>
  | Traceback (most recent call last):
  | File
  | "/opt/miniconda/lib/python3.7/concurrent/fut
  | ures/_base.py", line 324, in
  | _invoke_callbacks
  | callback(self)
  | File
  | "/opt/miniconda/lib/python3.7/asyncio/future
  | s.py", line 365, in _call_set_state
  | dest_loop.call_soon_threadsafe(_set_stat
  | e, destination, source)
  | File
  | "/opt/miniconda/lib/python3.7/asyncio/base_e
  | vents.py", line 736, in call_soon_threadsafe
  | self._check_closed()
  | File
  | "/opt/miniconda/lib/python3.7/asyncio/base_e
  | vents.py", line 479, in _check_closed
  | raise RuntimeError('Event loop is
  | closed')
  | RuntimeError: Event loop is closed
  | 1
  | 1
  | 1
  | 1
  | **********************************************************************
  | 1 items had failures:
  | 1 of   5 in default
  | 5 tests in 1 items.
  | 4 passed and 1 failed.
  | ***Test Failed*** 1 failures.
```

If reverting this PR actually does fix it, I'd hypothesize that the issue actually somehow has to do with [this dependency change](https://github.com/ray-project/ray/pull/35270/files#diff-669005e47ce65c8b9eaba2906e6212fd9247d6cf76c8bd497762b8b0da5dff77).

**Comment by cadedaniel** [comment]
Ok, can we get someone to look into it asap?

**Comment by matthewdeng** [comment]
@jjyao do you have any ideas about this? Saw you just enabled this 3 days ago in #35274. 

It looks like the job still runs and outputs the expected results, but there is some issue with the cleanup?

**Comment by cadedaniel** [comment]
@jjyao has a fix here https://github.com/ray-project/ray/pull/35506

**Pull request closed without merging**
