### PR TITLE
Revert "Revert "[core] Support encrypted redis connection." (#28991)"

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Fix the mac building issues. Verified in local mac.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
Try to run mac test as well.

**Comment by iycheng** [comment]
@krfricke  I clicked the run mac tests and the mac still won't run.

Actually in the first PR (the one being reverted), I also trigger the mac tests and it's pending:
https://buildkite.com/ray-project/oss-ci-build-pr/builds/1046#01839af1-230c-49f9-a766-62bab131fb01

Is there something wrong in the testing infra?

**Review by rkooo567 — APPROVED** [review]
approval. Let's merge it when it passes Mac tests

**Comment by iycheng** [comment]
Synced offline:

@krfricke is going to debug why the mac tests hang forever. I'm going to merge it first. We'll revert it again if it breaks anything.

**Pull request merged**
