### PR TITLE
[all_tests] Remove calling of get_event_loop from python version >= 3.10 

### LINKED ISSUE #25025: [Core | Python3.10] Stop using `get_event_loop`
### What happened + What you expected to happen

`get_event_loop` will be deprecated and print spammy logs to the driver. We should use `new_event_loop ` and `get_running_loop` instead. https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop

### Versions / Dependencies

Ray for Python 3.10

### Reproduction script

pytest -vs python/ray/tests/test_basic.py::test_put_get

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by rickyyx**
The previous PR broke many tests due to a bug in merge conflict resolution that's also fixed.  
See commits after 2add72a9dea308f3bdf625cce91d7d28f3cc5493 for added changes as compared to https://github.com/ray-project/ray/pull/29285

## Related issue number
Closes #25025

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Tests irrelevant - those flaky and failing in master as well.

**Review by architkulkarni — APPROVED** [review]
Serve codeowner stamp

**Review by scv119 — APPROVED** [review]

**Comment by edoakes** [comment]
@rickyyx @scv119 please give @simon-mo a chance to review this before merging, he has had to dealt with some really tricky event loop-related behaviors in Serve in the past.

**Review by simon-mo — APPROVED** [review]
LGTM. This is a simple compatibility change. How do we ensure the future test won't break it again though?

**Comment by rickyyx** [comment]
> LGTM. This is a simple compatibility change. How do we ensure the future test won't break it again though?

Great question - I was thinking of having a linter to print warnings if there's any new usage of this. But seems flake8 isn't supporting custom rules natively so we might have to end of writing some our own linting script to detect any to-be-deprecated things in higher python versions. 

I will imagine the 3.10+ tests in the future will impose a stronger requirement than just "recommending not to use these deprecating functions".

**Review by richardliaw — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Review by fishbone — APPROVED** [review]

**Comment by rickyyx** [comment]
> > LGTM. This is a simple compatibility change. How do we ensure the future test won't break it again though?
> 
> Great question - I was thinking of having a linter to print warnings if there's any new usage of this. But seems flake8 isn't supporting custom rules natively so we might have to end of writing some our own linting script to detect any to-be-deprecated things in higher python versions.
> 
> I will imagine the 3.10+ tests in the future will impose a stronger requirement than just "recommending not to use these deprecating functions".

As a follow up - I am thinking of using pylint's customized checker to check any deprecating functions calls. https://pylint.pycqa.org/en/latest/development_guide/how_tos/custom_checkers.html

**Pull request merged**
