### PR TITLE
Check if the provider is external before getting the config.

### PR DESCRIPTION
**Pull request by barrachri**
Fixes https://github.com/ray-project/ray/issues/1737

### CODE REVIEW

**Comment by richardliaw** [comment]
Pushed a fix for docker as it was getting snagged

**Comment by richardliaw** [comment]
Do you have an example yaml where this works?

**Review by richardliaw — CHANGES_REQUESTED** [review]
some form of test/example would be good to make sure this codepath actually works!

**Comment by barrachri** [comment]
> Do you have an example yaml where this works?

I am adding a `external_config_example.yml` for this.

> some form of test/example would be good to make sure this codepath actually works!

Testing that the path actually works or more like end to end test?

**Comment by richardliaw** [comment]
Something like a `external_config_example.yml` would probably be fine; ideally we could test this end to end by treating the AWS provider classes as external modules, but probably not too urgent at this point.

**Comment by ericl** [comment]
I'm fine without an example file -- I think only very technical users would use this feature, so it may even be better to leave it out as it might be confusing.

**Comment by ericl** [comment]
```
    type: external
    module: ray.autoscaler.aws.node_provider.AWSNodeProvider
```

does something reasonable (no AWS autoconfigure, but that's expected).

**Review by ericl — APPROVED** [review]

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Test error was valgrind - seems unrelated.

**Pull request merged**
