### PR TITLE
Remove log suppression code

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

When running in a screen (or any other time it is hard to scroll up), printing "Suppressing previous error message" is not helpful since the previous error is lost far above past scrollback. Better to just print it repeatedly at the end.

### CODE REVIEW

**Comment by robertnishihara** [comment]
The `screen` setting was actually the reason for suppressing the error messages in the first place (see https://github.com/ray-project/ray/pull/2104). If one thing raises an exception (e.g., an actor constructor), then everything downstream will fail (e.g., all actor method invocations), and so in many settings only the first error message is relevant and all subsequent ones are irrelevant. The goal was to make it easy to find the "first" error by having less output.

So, printing the error instead of suppressing it is only helpful if the last error message is also the same as the first error message.

I also considered just not printing anything, but the issue with that is that you can invoke a remote function and if nothing is printed it feels like it succeeded, which can be very misleading (especially when you're doing this interactively).

I'm not sure what the right solution here is, but any sort of scrolling is a common pain point with `screen`.

One possibility could be when an application exits, we can retrieve the first couple error messages and print those.. That would be annoying when using Ray interactively from IPython, but could be useful for scripts.

**Comment by ericl** [comment]
Is this (indirect error causes) something we can fix by saving the constructor error and re-throwing it on subsequent passes? I believe this is what Java does for static initialization errors.

Regardless, I don't think suppressing is a viable solution since if you have a finite scrollback, you can never find the error. Printing some unrelated error (possibly useful) is better than the not-useful message (never useful). Btw the common case I see here is "some error happened", followed by tens of thousands lines of "Suppressed" messages.

**Comment by ericl** [comment]
This re-raises the actor error btw https://github.com/ray-project/ray/pull/2843

**Comment by ericl** [comment]
err

**Review by robertnishihara — APPROVED** [review]
Looks good to me, can you rebase to fix the linting errors?

**Comment by robertnishihara** [comment]
I think we should merge this and see how we like it. In the past people have complained about Ray vomiting out tons and tons of error messages, and this was an attempt to fix that, but we probably need a different/better fix.

**Comment by ericl** [comment]
Lint error looks like a yapf version issue.

> I think we should merge this and see how we like it. In the past people have complained about Ray vomiting out tons and tons of error messages, and this was an attempt to fix that, but we probably need a different/better fix.

I totally agree, we should figure out how to avoid emitting duplicate errors in any case. If there's something retrying indefinitely then that needs a timeout or retry limit.

**Pull request merged**
