### PR TITLE
[CI][Clean][2] Make s3 function names more agnostic

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?

Some existing functions that work with both s3 and gs but has the word s3 in his name. Refactor those. Also create constants for commonly used values, reduce duplications, etc.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] python -m pytest ray_release/tests/ 
   - [X] Release tests

### CODE REVIEW

**Review by krfricke — APPROVED** [review]
Looks good, thanks for doing this! Can you merge latest master to kick off tests again? (there were some CI issues today)

**Comment by can-anyscale** [comment]
@krfricke: absolutely, will do so!

**Comment by can-anyscale** [comment]
Rebase, re-tested and ready to merge: https://buildkite.com/ray-project/release-tests-pr/builds/33891

**Comment by can-anyscale** [comment]
@scv119 do you mind help me merge this into master. Thankks!

**Review by aslonnie — APPROVED** [review]

**Pull request merged**
