### PR TITLE
[RLLib] fix reduce mean to take into consideration FLOAT_MIN

### PR DESCRIPTION
**Pull request by ingambe**
## Why are these changes needed?

Current `reduce_mean_ignore_inf` ignore only `float('-inf')`values, by when using action masking we use the `FLOAT_MIN` constant, and this is not considered currently.

## Related issue number

#14355 I'm working on making dueling work for masked actions

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by sven1977** [comment]
Thanks for this commit @ingambe , but some of the tests are now failing and it's related to your changes.
Could you take another look and possibly fix these?

**Review by sven1977 — CHANGES_REQUESTED** [review]
Some of our RLlib tests are failing b/c of the change. These need to be passing before we can merge this.

**Comment by sven1977** [comment]
@ingambe could you check on the failing test cases? Thanks! :)

**Comment by ingambe** [comment]
Sorry @sven1977, I had little time before to look at it.
I've seen where the error was coming from. However, there is one build that doesn't pass ([MAC_WHEELS=1 MAC_JARS=1](https://travis-ci.com/github/ray-project/ray/jobs/494846847)), but I don't think this is linked to this PR as the error his: `ModuleNotFoundError: No module named 'setproctitle'` this as little to do with this PR

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
