### PR TITLE
Depend on uvicorn[standard] instead of uvicorn so that it pulls in uvloop

### LINKED ISSUE #25023: ray docker images do not have uvloop installed
It looks like `uvloop` is not a dependency of `uvicorn` but only of `uvicorn[standard` as per the documentation of `uvicorn`: 

> $ pip install uvicorn
> 
> This will install uvicorn with minimal (pure Python) dependencies.
> 
> $ pip install uvicorn[standard]
> 
> This will install uvicorn with "Cython-based" dependencies (where possible) and other "optional extras".
> 
> In this context, "Cython-based" means the following:
> 
>     the event loop uvloop will be installed and used if possible.

https://www.uvicorn.org/#quickstart

_Originally posted by @fkaleo in https://github.com/ray-project/ray/pull/9216#discussion_r878185365_

### PR DESCRIPTION
**Pull request by fkaleo**
## Why are these changes needed?

Ensures that `uvloop` is installed thus making uvicorn many times faster.

## Related issue number

Closes #25023

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Would you mind changing https://github.com/ray-project/ray/blob/master/python/setup.py#L219 as well?

**Comment by fkaleo** [comment]
> Would you mind changing https://github.com/ray-project/ray/blob/master/python/setup.py#L219 as well?

done

**Comment by mwtian** [comment]
One last location containing `uvicorn` is `doc/requirements-doc.txt`

**Comment by simon-mo** [comment]
Doc should be fine left unchanged though. 

On May 20, 2022, GitHub ***@***.***> wrote:
> One last location containing uvicorn is doc/requirements-doc.txt
>

—
Reply to this email directly, view it on GitHub <https://github.com/ray-
project/ray/pull/25027#issuecomment-1133157697>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AFBD7A6O2O5TMSBBTJIPZKDVK7E6RANCNFSM5WPVBDAA>.
You are receiving this because you were assigned.Message ID: <ray-
***@***.***>

**Comment by zhe-thoughts** [comment]
Thanks for the contribution @fkaleo !

What still remains to be done for this PR?

**Comment by simon-mo** [comment]
Looks like I can't push to this branch. 
- @fkaleo would you mind merge upstream master to refresh the tests?
- @ericl @richardliaw can code owners please approve the dependency changes for Serve in `setup.py`?

**Review by simon-mo — APPROVED** [review]

**Review by ericl — APPROVED** [review]
LGTM given the dep change is scoped to [serve]

**Pull request merged**
