### PR TITLE
Deprecate experimental / dynamic resources

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Deprecate the dynamic resource experimental API, it was always buggy and isn't supported in the new scheduler.

(please comment about your use case if you are using dynamic resources; and can't use placement groups instead)

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
nice

**Comment by stephanie-wang** [comment]
Shouldn't we have request comments from the community for this? I know it's an experimental API, but I think this has been in the Ray core long enough that it deserves some deliberation (plus anecdotally, it's often recommended as a solution to Ray users). I personally have some benchmark scripts that depend on this and the current placement group semantics are not sufficient.

Also, some more information would be useful here. I actually have not noticed this being buggy.

**Comment by edoakes** [comment]
@ericl should we just completely deprecate it instead of pointing users to turn off the new scheduler? I don't imagine this will be well-supported/well-tested for long anyways.

**Comment by ericl** [comment]
@stephanie-wang good point, I created a RFC to gather comments here. Could you also describe your use case any why static resources / placement groups aren't good enough?

**Comment by stephanie-wang** [comment]
> @stephanie-wang good point, I created a RFC to gather comments here. Could you also describe your use case, and why static resources / placement groups aren't good enough?

Thanks, yeah I added a description to the RFC.

**Comment by ffbin** [comment]
@ericl Does Java API need to be deleted? Pls create an issue and assign to me, thanks.

**Review by pcmoritz — APPROVED** [review]

**Comment by ericl** [comment]
Given the new scheduler is now on by default, I'm going to merge this to provide a better error message for users. Further discussion should be done on the RFC issue: https://github.com/ray-project/ray/issues/13021

**Pull request merged**
