### PR TITLE
[Scheduler] Fix string id map bug

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

We risk the potential conflict if a custom resource or a node id's hash value conflict with those predefined resources in cluster_resource_scheduler.

Resolve it by preallocate predefined resources.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
Is the primary purpose to see if this can happen? I feel like different named resources should have different hash values, so we shouldn't have a conflict for custom resources? If it is not guaranteed, maybe we should fix that issue (since the current behavior seems a bit drastic that it crashes nodes)?

**Comment by jjyao** [comment]
It would be nice to try to remove string int map all together (this makes debug harder since we need to do int <-> string translation manually). I remember @wuisawesome mentioned that this might be a premature optimization.

**Comment by wuisawesome** [comment]
I'm happy to stamp off on this commit, but yeah, we can probably just remove this optimization.

**Comment by scv119** [comment]
Yeah i'm now going into this rabbit-hole of cleaning up string id map. My initial reaction is this is not as trivial as I though

**Review by fishbone — APPROVED** [review]

**Comment by scv119** [comment]
test failures are unrelated. will submit the string-id-map deprecation in a separate PR as its very involved change.

**Pull request merged**
