### PR TITLE
Disable KubeRay tests on windows.

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
This PR disables KubeRay tests on windows, because they're not relevant there.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
hmm 
```


DEBUG: C:/install/ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
--
  | ERROR: no such target '//python/ray/tests:kuberay/test_autoscaling_e2e': target 'kuberay/test_autoscaling_e2e' not declared in package 'python/ray/tests' defined by C:/install/ray/python/ray/tests/BUILD


```

**Comment by mattip** [comment]
Bazel cannot skip single tests this way. I think you need to add a `@pytest.mark.skipif()` decorator to the test itself.

**Comment by mattip** [comment]
Maybe the slash `/` in the test name is confusing bazel? I see other test names in `tests/BUILD` avoid having a `/` even when the test file is in a subdirectory

**Comment by DmitriGekhtman** [comment]
> ~Bazel cannot skip single tests this way. I think you need to add a `@pytest.mark.skipif()` decorator to the test itself.~

I'm going to try something of that nature.

**Comment by DmitriGekhtman** [comment]
Actually, looks like I just forgot to merge master before pushing -- the test file and BUILD target were missing.

**Comment by DmitriGekhtman** [comment]
That fixed it. Mac failures unrelated. Merging.

**Pull request merged**
