### PR TITLE
Upgrade arrow to include tensorflow op fix

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by robertnishihara** [comment]
I'm not sure, but the Java failure looks potentially related

`[ERROR] Failed to execute goal on project ray-api: Could not resolve dependencies for project org.ray:ray-api:jar:1.0: Failure to find org.apache.arrow:arrow-plasma:jar:0.10.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]`

**Comment by pcmoritz** [comment]
The error I'm getting now is

**Comment by pcmoritz** [comment]
The error I'm getting now is
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) on project ray-superpom: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Could not transfer artifact com.puppycrawl.tools:checkstyle:jar:6.19 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.184.215] failed: Connection timed out (Connection timed out) -> [Help 1]
```
@kingchin1218 @chuxi @zhijunfu Any ideas how to fix this?

**Comment by kingchin1218** [comment]
Can It be built on ur local machine? @pcmoritz

**Comment by raulchen** [comment]
@pcmoritz did that error happen consistently? It looks like just network connection issue.

**Comment by pcmoritz** [comment]
@raulchen Yeah, I re-ran the test a number of times and it consistently fails.

**Comment by raulchen** [comment]
I checked the latest build, the actual error is `Could not find artifact org.apache.arrow:arrow-plasma:jar:0.10 in central`.
The reason is because the version number should be `0.10.0`, not `0.10`. I tried this locally, and it succeeded.

**Comment by kingchin1218** [comment]
@raulchen 
Changing the version number to `0.10.0`  will be successful on my local machine, but it still does fail in ci.
I have already check it in this [commit](https://github.com/kingchin1218/ray/commit/b1dd000b1fb8428b47b9b6bdbe7a794a19599ace) .
And it also shows connection timeout.
```
[ERROR] Failed to execute goal on project ray-common: Could not resolve dependencies for project org.ray:ray-common:jar:1.0: Could not transfer artifact quartz:quartz:jar:1.5.2 from/to central (http://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:80 [repo.maven.apache.org/151.101.44.215] failed: Connection timed out (Connection timed out) -> [Help 1]

```

This is the [ci log](https://travis-ci.org/kingchin1218/ray/jobs/414885391).

**Comment by kingchin1218** [comment]
@pcmoritz @raulchen 
The ci will pass if the version number is `0.10.0` in  [this change](https://github.com/kingchin1218/ray/pull/2/files).

Could u plz change the number version in this PR  than see the ci result?

**Comment by pcmoritz** [comment]
@raulchen  @kingchin1218 Thanks a lot for your help, that worked

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
