### PR TITLE
Revert "[RLlib] Replay Buffer API documentation."

### PR DESCRIPTION
**Pull request by fishbone**
image

Reverts ray-project/ray#24683

### CODE REVIEW

**Comment by avnishn** [comment]
Please don't revert, we're fixing this, its a 1 line change:
https://github.com/ray-project/ray/pull/25666

**Review by avnishn — CHANGES_REQUESTED** [review]
see my comment, thanks :)

**Comment by sven1977** [comment]
Same! Please hold on this PR. Thanks @avnishn for providing the fix for this.

**Comment by iycheng** [comment]
@sven1977 @avnishn by principle we shouldn't have another PR to fix this one. The reason is that, with the new PR, we need to wait until all tests pass before merging and for revert one, one stamp and then merge which is the fastest way.

The workflow is:

1. Revert the broken one
2. The author revert the revert PR and adding the fix there
3. Merge the fixed one (waiting for CI passing)

I'm OK with giving one exception here, but please keep an eye on the fixing PR and merge it as soon as possible.

**Comment by sven1977** [comment]
[Fix merged](https://github.com/ray-project/ray/pull/25666). Closing this PR.

**Comment by richardliaw** [comment]
BTW, guys -- @iycheng is correct here. We should always rollback and not roll forward.

**Comment by ArturNiederfahrenhorst** [comment]
Sorry for the broken link everyone!

**Pull request closed without merging**
