### PR TITLE
Cherry pick #32902

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

[RLlib; CI] Pinned git dependency for minigrid since the pypi wheel is broken

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kouroshHakha** [comment]
2.1.1 is not broken afaik. The 2.1.0 was broken.

**Comment by kouroshHakha** [comment]
https://github.com/ray-project/ray/pull/32902

**Comment by kouroshHakha** [comment]
Oh is this a revert? why? which test is failing?

**Comment by zcin** [comment]
This is cherry-picking https://github.com/ray-project/ray/pull/32902 since a bunch of docs/air examples tests were failing on the release branch.

**Comment by zcin** [comment]
Ah, sorry I realized the description is wrong, let me update it.

**Review by zhe-thoughts — APPROVED** [review]
Approved for cherry picking into 2.3.1

**Pull request merged**
