### PR TITLE
[ci/release] Update to recent anyscale API changes

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Recent changes in the anyscale API rendered the current e2e script incompatible. This PR resolves these subtle API changes.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hey @krfricke do you know why it wasn't communicated to us? This is really bad some APIs have deprecated without us noticing it (and didn't have enough migration time).

**Comment by krfricke** [comment]
I think there is no process in place to track this. Product is not aware of the APIs we're using. I think a solution will be, once we split up e2e.py, to run some unit tests on the product CI.

**Review by nikitavemuri — APPROVED** [review]
This will work, but `get_auth_api_client` is not actually a public API either. Only imports under `anyscale.sdk` are considered public, so it would be good to eventually move to using those instead. It looks like `session_controller` is currently being used to call deprecated CLI commands (`push`, `pull`), so we should either add more functionality in the SDK or restructure the tests.

**Review by architkulkarni — APPROVED** [review]
Thanks Kai!

**Comment by richardliaw** [comment]
@alanwguo FYI

**Comment by alanwguo** [comment]
@rkooo567, agreed. This shouldn't have happened like this.

1. We will make sure to broadcast these changes more widely. The original email was sent out only to field team. The email has since been expanded to include oss-dev. We didn't expect users to be using these functions. This will hopefully prevent this from happening again.
2. We have clarified in the anyscale docs what is considered public apis: The SDK functions are public to import and the CLI's terminal commands are public to use.

The anyscale CLI/SDK codebase is closed source. Because of this, we think it's reasonable to expect that only the things that are disclosed in our documentation are considered public apis.

Hopefully this won't be a problem in the future once the e2e tests are fully using public APIs.

**Comment by rkooo567** [comment]
I see. This makes sense!

@krfricke do we have other private api use cases? Maybe just removing all of them asap would help us in the long term.

**Comment by krfricke** [comment]
Merged master, test run here: https://buildkite.com/ray-project/periodic-ci/builds/2225

**Pull request merged**
