### PR TITLE
Fix Cluster Page UI

### LINKED ISSUE #39026: [Dashboard UI] `CPU Flame Graph` and `Stack Trace` are put on the same line together
### What happened + What you expected to happen

Screenshot 2023-08-28 at 2 13 49 PM

We shouldn't put them next to each other

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

### PR DESCRIPTION
**Pull request by chaowanggg**
## Why are these changes needed?
1. Unify the text in NodeRow "Log" and WorkerRow "Logs"
2. There is an underline under "Logs," but not under "CPU Flame Graph" and "Stack Trace."
3. Add a line break between "CPU Flame Graph" and "Stack Trace."

These revisions should help maintain a more consistent and clear user interface on the cluster page. 

| after| before |
|----------|----------|
| Screenshot 2023-09-27 at 3 39 50 PM | Screenshot 2023-09-27 at 3 43 13 PM |

## Related issue number
Fix #39026 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by alanwguo — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
is there a good way to avoid regressions like this in general for frontend?

**Comment by chaowanggg** [comment]
> is there a good way to avoid regressions like this in general for frontend?

One way we could do it is by adding component tests using React or end-to-end tests using Cypress. However, the UI is continuously changing, making it hard to assert what the correct UI should be. My suggestion is to use screenshots to ensure there are no major regressions, and it's also easy to implement.


cc @alanwguo Any idea?

**Comment by chaowanggg** [comment]
> Why

Discussed offline

**Comment by chaowanggg** [comment]
@rkooo567 Could you help me merge this branch?

**Pull request merged**
