### PR TITLE
[lint] fix lint error

### PR DESCRIPTION
**Pull request by aslonnie**
replace tab with space.

### CODE REVIEW

**Comment by aslonnie** [comment]
example: https://buildkite.com/ray-project/oss-ci-build-branch/builds/4653#0188eb4c-5b05-452e-b850-86457fd7852e/1462-1541

**Comment by aslonnie** [comment]
should we remove @wuisawesome and @DmitriGekhtman from code owner list?

**Comment by aslonnie** [comment]
not that I want code owners to be in the company, but I would like code owners to be responsive at least.

**Review by ericl — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
> should we remove @wuisawesome and @DmitriGekhtman from code owner list?

I like getting updates on autoscaler-related PRs. (Though if you want to prune the list to people who actively maintain the code, I won't mind.)

You could add more code owners -- looks like @scv119 and @rickyyx are the main current contributors.

**Pull request merged**
