### PR TITLE
Bazelify Redis

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Creates Bazel rules for Redis so we can integrate it into the build system and use the same compile settings without needing to call an external Makefile.

This removes `jemalloc`. This simplifies the build files. As [others have also found](https://github.com/tensorflow/tensorflow/commit/8b21130fb6a9575db953ae46a9cc353bb9de8d57#diff-781a53e648f3df8d16a08ec083b04bf4R34), its performance is similar to that of the system allocator.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@mehrdadn is this still being developed or should it be closed?

**Comment by mehrdadn** [comment]
@robertnishihara The former

**Comment by edoakes** [comment]
@mehrdadn does this remove `jemalloc` from all of Ray? If so, we should do some benchmarking if we want to change this.

If possible, let's not remove it in the PR and consider it in a follow-up.

**Comment by mehrdadn** [comment]
@edoakes No, this only affects `jemalloc` in `redis-server`, which is used by default by its Makefile. Though I'm not even ware of `jemalloc` being used elsewhere; perhaps you're thinking of `dlmalloc`?

And we can't just do it in another PR since the entire reason for removing it is that Bazelifying would be an immense amount of work (Bazelifying Redis itself pales in comparison) for no real gain (if not an actual loss of performance). Tensorflow moved away from it when they realized it doesn't gain noticeable performance either. Here's 1 run of benchmarks if you're curious (notice pretty much everything is within the noise bars, and many are average speedups rather than slowdowns):

```
Test	Before	After	Speedup %
single client get calls/s	12323.14 +- 210.59	12369.08 +-  84.3   	 0.4%
single client put calls/s	 5486.11 +-  33.4	 5522.03 +-  33.17  	 0.7%
single client put gigabytes/s	   29.89 +-   9.06	   28.75 +-   9.1   	-3.8%
multi client put calls/s	 8261.05 +-  98.93	 8286.09 +- 112.24  	 0.3%
multi client put gigabytes/s	   11.56 +-   6.17	   11.67 +-   6.24  	 1.0%
single client tasks sync/s	 1760.71 +-   8.38	 1781.49 +-   4.26  	 1.2%
single client tasks async/s	16465.98 +- 105.51	16867.5  +- 176.43  	 2.4%
multi client tasks async/s	23081.35 +- 140.94	23177.65 +- 251.9   	 0.4%
1:1 actor calls sync/s	 2945.06 +-  12.91	 2915.8  +-  13.41  	-1.0%
1:1 actor calls async/s	 8315.62 +-  68.16	 8209.42 +- 146.99  	-1.3%
1:1 actor calls concurrent/s	 7086.05 +- 104.3	 7103.7  +-  47.94  	 0.2%
1:n actor calls async/s	19108.58 +- 202.06	19288.13 +- 273.98  	 0.9%
n:n actor calls async/s	28126.38 +- 432.75	28275.95 +- 378.98  	 0.5%
n:n actor calls with arg async/s	 9963.35 +-  61.9	 9909.96 +-  52.92  	-0.5%
1:1 async-actor calls sync/s	 1896.2  +-  15.71	 1916.14 +-  15.26  	 1.1%
1:1 async-actor calls async/s	 4378.48 +-  91.62	 4450.58 +-  17.47  	 1.6%
1:1 async-actor calls with args async/s	 2824.06 +-   8.67	 2841.09 +-   7.44  	 0.6%
1:n async-actor calls async/s	12965.95 +- 161.76	12950.36 +-  63.67  	-0.1%
n:n async-actor calls async/s	15880.98 +- 226.18	16077.21 +- 115.37  	 1.2%
```

**Review by edoakes — APPROVED** [review]
@mehrdadn thanks for the explanation, this makes sense to me.

**Pull request closed without merging**
