### PR TITLE
[Datasets] Fetch block `size_bytes` if unknown during execution/windowing.

### LINKED ISSUE #32773: [Datasets] Can't use `FastFileMetaProvider()` when windowing a dataset by bytes
### What happened + What you expected to happen

I have a dataset of parquet shards with a size estimate of 220G (train,val: 85/15 split).

Initial training of a DL-model with TorchTrainer goes well when only train_epoch is done for model-training using train-set.

Later on I also included a val_epoch to perform model-testing at the end of each-epoch with updated model but I was getting OOM error. I thought this might be a bulk-ingest issue which is causing object-store to blow when I include val-set. 

I saw the stream-ingest option [https://docs.ray.io/en/latest/ray-air/check-ingest.html#enabling-streaming-ingest](url)
and updated dataset config for the val-set by setting use_stream_api = True but it throws an error as shown in error-log:

Failure # 1 (occurred at 2023-02-23_07-17-04)
ray::_Inner.train() (pid=1355, ip=19.41.16.64, repr=TorchTrainer)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py", line 335, in entrypoint
    return self._trainable_func(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/base_trainer.py", line 480, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py", line 652, in _trainable_func
    output = fn()
  File "/usr/local/lib/python3.8/dist-packages/ray/train/base_trainer.py", line 390, in train_func
    trainer.training_loop()
  File "/usr/local/lib/python3.8/dist-packages/ray/train/data_parallel_trainer.py", line 366, in training_loop
    training_iterator = self._training_iterator_cls(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 58, in __init__
    self._start_training(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 87, in _start_training
    self._run_with_error_handling(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 97, in _run_with_error_handling
    return func()
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 88, in <lambda>
    lambda: self._backend_executor.start_training(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py", line 375, in start_training
    self.dataset_shards = dataset_spec.get_dataset_shards(actors)
  File "/usr/local/lib/python3.8/dist-packages/ray/train/_internal/dataset_spec.py", line 183, in get_dataset_shards
    dataset = dataset.window(
  File "/usr/local/lib/python3.8/dist-packages/ray/data/dataset.py", line 3759, in window
    it = Iterable(blocks, self._epoch)
  File "/usr/local/lib/python3.8/dist-packages/ray/data/dataset.py", line 3674, in __init__
    self._splits = blocks.split_by_bytes(bytes_per_window)
  File "/usr/local/lib/python3.8/dist-packages/ray/data/_internal/block_list.py", line 91, in split_by_bytes
    raise RuntimeError(
RuntimeError: Block has unknown size, cannot use split_by_bytes()

### Versions / Dependencies

Ray-version: 2.2.0

### Reproduction script

def train_func(config: Dict):
    batch_size = config["batch_size"]
    lr = config["lr"]
    epochs = config["epochs"]    
    loss_fn1 = nn.MSELoss()
    loss_fn2 = nn.L1Loss()

    train_dataset_pipeline_shard = session.get_dataset_shard("train")
    val_dataset_pipeline_shard = session.get_dataset_shard("validation")

    # Create model.
    model = train.torch.prepare_model(model,parallel_strategy='ddp')

    optimizer = train.torch.prepare_optimizer(torch.optim.RMSprop(model.parameters(), lr=lr))
    
    loss_results = []

    print('no. of epochs: ', str(epochs))

    print_metrics = False
    if session.get_world_rank()==0 and session.get_local_rank()==0:
        print_metrics = True

    for epoch in range(epochs):
        device = train.torch.get_device()
        train_epoch(epoch_shard, model, loss_fn1, optimizer, device, batch_size, epoch, print_metrics)
        session.report({},checkpoint=Checkpoint.from_dict(dict(epoch=epoch, model=model.state_dict())))
            
        if print_metrics:
            for epoch_shard in val_dataset_pipeline_shard.iter_epochs(1):    
                device = train.torch.get_device()
                validate_epoch(epoch_shard, model, loss_fn2, device, batch_size, epoch)

def get_training_datasets(path):
     train_ds = ray.data.read_parquet_bulk(glob.glob(os.path.join(path,'train*')),tensor_column_schema={"rois": (np.float32, (128, 128, 3))},columns=["rois","labels"])
      test_ds = ray.data.read_parquet_bulk(glob.glob(os.path.join(path,'val*')),tensor_column_schema={"rois": (np.float32, (128, 128, 3))},columns=["rois","labels"])
      return {"train": train_ds, "validation": test_ds}
    
trainconfig = {"lr": 1e-3, "epochs": 30, "batch_size": 32}
train_loop_config=trainconfig, scaling_config=ScalingConfig(num_workers=8,use_gpu=True), datasets=get_training_datasets(path))
trainer = TorchTrainer(train_loop_per_worker=train_func, train_loop_config=trainconfig, scaling_config=ScalingConfig(num_workers=8,use_gpu=True), datasets=get_training_datasets(path),dataset_config={"validation": DatasetConfig(use_stream_api=True)})
result = trainer.fit()`

I tried val-epoch in two ways:
(a) Above code shows val-epoch being called on only one worker which uses entire val-set
(b) Also tried giving split=True for Datasetconfig for val-set and not limiting val-epoch to only single worker. This approach also throws the same error.

### Issue Severity

High: It blocks me from completing my task.

### LINKED ISSUE #32900: [Datasets] Support `FastFileMetaProvider()` in the new executors
Using `FastFileMetaProvider()` currently fails when used with the new executors, since the block size in bytes must be known at planning time to convert the input `BlockList` to `RefBundle`s. We should fetch the block size in bytes in these cases.

### PR DESCRIPTION
**Pull request by clarkzinzow**
If the block size in bytes is unknown when:
1. executing a dataset, or,
2. windowing a dataset by bytes,

we currently raise an error. This PR fixes this by fetching the block size in bytes from the underlying blocks in these cases.

Closes https://github.com/ray-project/ray/issues/32773, closes https://github.com/ray-project/ray/issues/32900

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
The performance penalty on this is going to be huge. A couple options:
1. Continue to not support this? Btw, the DatasetPipeline API is going to be deprecated anyways.
2. Add a logical operator like `EnsureMetadataResolved` to the plan and execute it?

I think generally we should avoid ad-hoc operations and instead represent things in the logical/physical plan moving forwards.

**Comment by clarkzinzow** [comment]
@ericl TL;DR: agreed that this should be part of a more generic metadata resolution pass of the plan, as other systems do, and we have that work planned, but this is a P0 to unblock a customer workload that I don't think should be blocked on a P1 deliverable for Ray 2.4.

To address your points:

>The performance penalty on this is going to be huge.

I changed this to be an bulk object locations fetch on only the objects with missing block sizes, where we use the returned object size as the resolved block size. This should be anything more than a lightweight batched RPC per block owner, and should be much, much more lightweight than a task; we already rely on this operation being cheap in the executor, in our locality logic. Does this suffice to address your performance concerns?

>Continue to not support this? Btw, the DatasetPipeline API is going to be deprecated anyways.

This isn't just for `DatasetPipeline`: using the `FastFileMetaProvider` just plain doesn't work with the new executors (bulk or streaming). I fixed the same issue for windowing as a driveby.

>Add a logical operator like EnsureMetadataResolved to the plan and execute it? I think generally we should avoid ad-hoc operations and instead represent things in the logical/physical plan moving forwards.

That's the similar to the current plan, but can we not block on that for this P0?

**Comment by ericl** [comment]
Hang on, let's step back a little here. Doesn't just fixing FastFileMetaProvider to resolve file sizes address the issue? I think this is actually a bug. Also, enhancing the DefaultFileMetaProvider to be faster would be another viable option.

Both of these options could be considered bug-fixes, don't require any design changes, and would address the issue.

**Comment by ericl** [comment]
My preference here is to actually *deprecate* the FastFileMetaProvider, and instead enhance the default one to resolve metadata in parallel / using batched filesystem scans.

This would close both https://github.com/ray-project/ray/issues/32773 and https://github.com/ray-project/ray/issues/32900

How about we file that as a P0 issue instead (fix performance issues in non-parquet default file meta provider)?

**Comment by clarkzinzow** [comment]
>Doesn't just fixing FastFileMetaProvider to resolve file sizes address the issue? I think this is actually a bug.

As mentioned offline, having `FastFileMetaProvider` hit the external storage system to fetch the file sizes would break the existing "no metadata network requests" semantics for that provider, which Amazon relies on to achieve very high throughput and was originally the whole point of that meta provider, so making that change makes me a bit nervous. I'd rather deprecate `FastFileMetaProvider` and ensure that `DefaultFileMetaProvider` is efficient enough to obviate the need for it, which we'd need to validate with a few users.

>Also, enhancing the DefaultFileMetaProvider to be faster would be another viable option.
>How about we file that as a P0 issue instead (fix performance issues in non-parquet default file meta provider)?

Yep, that's already in progress as a separate item, I should have a PR out for it today. However, even with that fix, that still leaves `FastFileMetaProvider` broken in master.

>My preference here is to actually deprecate the FastFileMetaProvider.

Agreed, especially since we have a relatively strict requirement around the block sizes in bytes always being defined in the block metadata in order for the executors to be able to apply backpressure on object store usage. But what do we want that deprecation timeline to be? I know that there are a few users relying on it, so we'd need to do some validation there.

**Comment by ericl** [comment]
How about we require users to pass an estimated file size for the fast metadata provider then? They could alternatively fall back to the bulk executor.

I think then in 2.4 we could be in a world where metadata is always available, and resolved by the data source.

**Comment by ericl** [comment]
Ah ok, maybe we can unbreak it for the bulk mode at least, if necessary. I believe it's only critical for streaming since we need to know it for memory management.

**Comment by zhe-thoughts** [comment]
@c21 Is this actually stale?

**Pull request closed without merging**
