### PR TITLE
change hmset to hset on is start dashboard method since hmset was dep…

### PR DESCRIPTION
**Pull request by tahentx**
…racated in redis 4.0

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
Thanks @tahentx!

**Comment by mfitton** [comment]
@tahentx thank you for your contribution! Unfortunately, it seems like there's an issue, as CI is failing with errors like:
```
>           redis_client.hset("webui", {"url": self._webui_url})
664E           TypeError: hset() missing 1 required positional argument: 'value'
```
Could you please take a look and ping me afterwards? Thanks!

**Comment by tahentx** [comment]
Thanks @mfitton ! After some research, it seems like this same issue came up in this repo: https://github.com/rq/rq/issues/1256 , and that an update was required with the redis server. I believe it might be the resolution here because the old function (hmset) took the same arguments in the same form as the new function (hset). And I didn't touch those. I look forward to your feedback.

**Comment by kfstorm** [comment]
Guys, FYI, there is a similar PR #11776.

**Pull request closed without merging**
