### PR TITLE
[serve] Remove Deployment Graph API (docs) [2/3]

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

The Serve deployment graph API (user facing object is DAGDriver) was deprecated in 2.8. We are removing it completely in 2.9. This PR removes all references to the API in docs.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by angelinalg — APPROVED** [review]
Thank you for keeping the docs up to date, @zcin!

**Comment by zcin** [comment]
@shrekris-anyscale @sihanwang41 @GeneDer PTAL!

**Review by GeneDer — APPROVED** [review]
:shipit:

**Comment by zcin** [comment]
@architkulkarni This PR is ready to merge! Checked the linkcheck build and confirmed none of the errors are related

**Pull request merged**
