### PR TITLE
[core][dashboard] GCS task attempts limit

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

We have seen users complaining missing task data due to the current 100K task attempts stored in GCS: we start dropping task metdata once the limit is hit, and this results in: 
- incorrect progress bar
- bad task table
- missing logs from task log

Given the overhead of a single task attempt is ~ 500 Bytes, a back of envelop calculation would mean storing 1M tasks in GCS max would be in hundreds of MiB (500MiB) data, which isn't too much in general cases. 

Users with more memory constraint could set  `RAY_task_events_max_num_task_in_gcs` to a smaller value. 

## Related issue number
Helps https://github.com/ray-project/ray/issues/25718

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Running the below release tests (which have been impacted by task backend recently) to see the impact: 
- microbenchmark
- stress_test_many_tasks
- long_running_many_actor_tasks

**Review by rkooo567 — COMMENTED** [review]
can we run some release tests to see 

1. if there's perf benchmark? (I guess not becuase it is gcs only but just in case)
2. verify the mem usage is 500MB~ish when there are 1 million tasks? (maybe you can verify it locally)

**Comment by rickyyx** [comment]
> if there's perf benchmark? (I guess not becuase it is gcs only but just in case)

I guess we will look at memory usage of the release tests + any perf metrics for these. 

I don't think we have any release tests on GCS specifically. 


> verify the mem usage is 500MB~ish when there are 1 million tasks? (maybe you can verify it locally)

Yeah, this is what I did the last time - I can double-check locally again.

**Comment by rkooo567** [comment]
lmk when you finish ^

**Comment by fjeremic** [comment]
> Users with more memory constraint could set `RAY_task_events_max_num_task_in_gcs` to a smaller value.

I couldn't find this in the docs. How does one set this value? Is it an envvar? Can it be set programatically?

**Comment by rickyyx** [comment]
> lmk when you finish ^

Actually looks like each task would result in 2-3 KiB data in GCS:
- 100K -> 300MiB
- 1M -> 3GiB 

Wonder if that would be ok. Or we could do 500K -> 1.5GiB max. 

Also, without running tasks - GCS already uses up 1.7 GiB.

**Comment by rkooo567** [comment]
@rickyyx should we merge this?

**Comment by rickyyx** [comment]
> @rickyyx should we merge this?

See the above message for memory impact. Also, I think the front end 10K limit might make this change less significant: if users can query max 10K tasks, even if we have 1M in GCS, they still couldn't see much of them.

**Comment by rickyyx** [comment]
Instead of increasing the static thresholds, I think what we really need is:
1. An easy way to configure the static thresholds (e.g. on Anyscale)
2. An easy way to allow users specify the limit at query time cc @alanwguo 

I am closing this for now to favor approach ^

**Comment by dizhouwu** [comment]
@rickyyx Is there a follow up to this issue?

**Pull request closed without merging**
