### PR TITLE
[RLlib] Make pickle5 RLlib's requirement now that we use cloudpickle to save/restore checkpoints.

### PR DESCRIPTION
**Pull request by gjoliver**
## Why are these changes needed?

RLlib Algorithm now relies on cloudpickle for saving and restoring checkpoints.
https://github.com/ray-project/ray/blob/master/rllib/algorithms/algorithm.py#L32
That means pickle5 getting used for python versions 3.6 and 3.7 on Anyscale.
If they don't have pickle5 installed in their local environment, they wouldn't be able to restore the checkpoint for inference.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
pickle5 is actually vendored with Ray (the reason for that is they don't provide wheels), see here:
https://github.com/ray-project/ray/blob/3268a90c917a48ca59179b851f8303ca80c439b7/python/setup.py#L361

Is anything going wrong with the vendoring? This should just work and having pickle5 as a dependency will lead to problems :)

**Review by pcmoritz — CHANGES_REQUESTED** [review]
see my comment above :)

**Comment by pcmoritz** [comment]
Actually the latest version of pickle5 now has wheels, so if you want to do this we could remove the vendoring and depend on pickle5 for older python versions.

See https://pypi.org/project/pickle5/0.0.12/#files

**Comment by gjoliver** [comment]
yeah, I have been pip installing pickle5.
let me update this PR then :)

**Comment by gjoliver** [comment]
@pcmoritz what do you think about this now?

**Comment by pcmoritz** [comment]
Thanks, I think it is the right direction! There are a couple of details to consider:

- There are several more references to pickle5 in the code base that we should remove as well
- pickle5 only has wheels for python 3.6 and 3.7, so I wonder what will happen with the "gap" of Python 3.8.0, 3.8.1, 3.8.2 -- given that they are already very old, maybe the stance that people should have upgraded by now is fine
- We have to take extra care that things will continue to work on Windows

**Comment by gjoliver** [comment]
not sure where does this 3.8.2 version come from actually.
I looked around, and everyone seems to say protocol 5 is supported for all of 3.8
https://peps.python.org/pep-0574/
I can double check.

**Comment by gjoliver** [comment]
tried python 3.8.0, I think the default protocol for 3.8.0 is still 4, but it reads and writes protocol 5 pickle files fine.

**Pull request closed without merging**
