### PR TITLE
[core] Setting ray default handler to use `logging._StderrHandler()`.

### PR DESCRIPTION
**Pull request by xwjiang2010**
Setting ray default handler to use `logging._StderrHandler()`, which is *almost* the same as `StreamHandler`.

And the doc string says it all:
"""
    This class is like a StreamHandler using sys.stderr, but always uses
    whatever sys.stderr is currently set to rather than the value of
    sys.stderr at handler construction time.
"""

This is needed for Rich FileProxy redirect to work properly, no matter whether a particular logger is instantiated outside of rich.live.Live() or inside of it.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
cc @peytondmurray

**Comment by rkooo567** [comment]
I think it is a low risk change. Actually the behavior of the LastResort looks close to the behavior I'd expect from StreamHandler

**Review by Yard1 — CHANGES_REQUESTED** [review]
One thing, actually - we will be changing the formatting of the handler, and it will impact other libraries too. Perhaps it will be better to create a new instance of the `_StderrHandler` in this case @xwjiang2010

**Comment by rkooo567** [comment]
I think in that case, you should probably set the logger to tune's `__init__` method and set propagte=False to the handler

**Comment by Yard1** [comment]
Oh, I meant in this very code @rkooo567  - next line: `_default_handler.setFormatter(logging.Formatter(logging_format))` - this will affect all libraries using the `lastResort` handler

**Comment by xwjiang2010** [comment]
@Yard1 good point. Changed it `logging._StderrHandler()`. Also I notice the `level` should be `NOTSET` to mimic the previous behavior of using `StreamHandler()`. Let's see if it fixes the failing unit tests.

**Review by Yard1 — APPROVED** [review]

**Pull request merged**
