### PR TITLE
[kubernetes] Adding cpu limit to make ray helm chart working in environments which require set resource limits

### PR DESCRIPTION
**Pull request by crdnb**
## Why are these changes needed?
Adding cpu limit to make ray helm chart working in environments which require set resource limits. Otherwise the operator pod does not start.

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
Thank you for fixing this oversight!

Two requests:
(a) Could you change the limit to 1? (One could change this to suit their personal needs, but 1 CPU should be sufficient.)
(b) Could you also apply the limit in these stand-alone files: https://github.com/ray-project/ray/blob/master/deploy/components/operator_namespaced.yaml#L62
https://github.com/ray-project/ray/blob/master/deploy/components/operator_cluster_scoped.yaml#L62

Thanks!!

**Comment by crdnb** [comment]
Hi @DmitriGekhtman

Thank you very much for your feedback.
As I think the operator should not run with QoS class "guaranteed" I set a cpu limit of 1.1. I hope these is fine for you. As suggested, I made the same updates to the standalone files.

Thank you!

**Comment by DmitriGekhtman** [comment]
Taking a look at the k8s docs, it seems the discrepancy between memory request and limits will already put the operator pod into QoS class Burstable (whether or not cpu requests and limits are equal).

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

I did a quick check to confirm the behavior. Are there other considerations that would suggest leaving a slight gap between CPU requests and limits?

**Review by DmitriGekhtman — APPROVED** [review]
Thanks, looks good to me.

**Comment by DmitriGekhtman** [comment]
@ijrsvt could you merge this?

**Comment by crdnb** [comment]
> 
> 
> Thanks, looks good to me.

@DmitriGekhtman: Thank you very much for your feedback, you were right!

**Comment by ijrsvt** [comment]
This only affects YAMLs for K8s, so Windows Failures are **unrelated**!

**Pull request merged**
