### PR TITLE
[CI][Clean][1] Clean up test infra client runner, and some of job runner

### LINKED ISSUE #32715: [Release][Tune] Migrate `tune_cloud_gcp_k8s_*` tests to v2 stack and Anyscale Jobs
### What happened + What you expected to happen

Migrate `tune_cloud_gcp_k8s_*` tests to v2 stack and Anyscale Jobs. If migration is impossible, consider rewriting the test or removing it. If there are features missing in v2 stack or/and Anyscale Jobs that make the migration impossible, please outline them in this issue.

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

None

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?
Ray client runner is a deprecated way to run ray job. Deprecated it from all release tests and test infra code.

Ray job runner is a, should-be, deprecated way to run ray job as well. However, there are some dependencies on local CLI that still need support for Ray job. Release tests however should no longer use Ray jobs

Also removed the gs-k8 tests as we do not plan to support GCE with kubernetes setting

Closes #32715

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests - python -m pytest ray_release/tests
   - [X] Release tests

### CODE REVIEW

**Comment by ollie-iterators** [comment]
The issue with "operation not permitted: sudo" could be fixed by using gosu. It is a very simple utility, similar to sudo, that runs a given instruction as a given user.

**Comment by can-anyscale** [comment]
Thanks @ollie-iterators, I saw 'operation not permitted: sudo' in some of the CI jobs. Do you mean to update those CI code to use gosu, or is there anything I can change in the way I put up this PR? Thanks

**Comment by ollie-iterators** [comment]
I mean that you could replace sudo with gosu

**Comment by ollie-iterators** [comment]
The issue with sudo is that it it has unpredictable TTY and signal-forwarding behavior that can cause problems

**Review by krfricke — APPROVED** [review]
Looks good to me!

**Comment by krfricke** [comment]
Looks like there is one more linter error:

```
release/ray_release/glue.py:37:1: F401 'ray_release.file_manager.remote_task.RemoteTaskFileManager' imported but unused
```

after this is done we can merge this and tackle the next PR

**Pull request merged**
