### PR TITLE
Use matrix to run minimal installs.

### PR DESCRIPTION
**Pull request by aslonnie**
Avoid copy and pasting on pipeline definitions.

### CODE REVIEW

**Comment by aslonnie** [comment]
example branch run: https://buildkite.com/ray-project/oss-ci-build-branch/builds/4473

**Comment by aslonnie** [comment]
cc @krfricke

**Review by can-anyscale — APPROVED** [review]

**Review by matthewdeng — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/peacock/">Peacock</a> on <a href="https://giphy.com/gifs/peacocktv-matrix-keanu-reeves-dodging-bullets-eIm624c8nnNbiG0V3g">GIPHY</a></div>

**Pull request merged**
