### PR TITLE
Revert "[AutoRun] Fix Auto-Run for Client"

### PR DESCRIPTION
**Pull request by fishbone**
Reverts ray-project/ray#18457

test broken:
```
pytest ./ray/workflow/tests/test_lifetime.py  -svx
```

### CODE REVIEW

**Comment by ijrsvt** [comment]
@iycheng where is this broken?

**Comment by ijrsvt** [comment]
Ahh I see that this test has become fully flaky:
Screen Shot 2021-09-30 at 12 08 39 AM

**Review by ijrsvt — APPROVED** [review]
LGTM!

**Comment by ericl** [comment]
Hmm since it's only flaky on first run, how about fixing the root cause instead of reverting? Probably just a bug in the workflows test.

**Comment by ijrsvt** [comment]
@ericl I much prefer fixing the root cause! I can investigate & fix today!

**Comment by ericl** [comment]
Awesome!

**Pull request closed without merging**
