### PR TITLE
fix offset by one issue

### PR DESCRIPTION
**Pull request by tianyapiaozi**
## What do these changes do?

fix offset by one issue with local scheduler

## Related issue number

#2651

### CODE REVIEW

**Comment by robertnishihara** [comment]
Thanks @tianyapiaozi! Is this a bug that gets exposed under certain conditions?

**Review by stephanie-wang — APPROVED** [review]
@tianyapiaozi, thanks, this looks good! I believe the failing tests are unrelated, so I'll merge.

@robertnishihara, it looks like this codepath was getting hit, but I think we wouldn't have seen the error unless an actor that was forked was reconstructed. The test cases for that are turned off right now due to other issues with the implementation.

**Comment by stephanie-wang** [comment]
Closes #2652.

**Comment by tianyapiaozi** [comment]
@robertnishihara 
I noticed the bug during reading code.

**Comment by tianyapiaozi** [comment]
@robertnishihara Thanks for your advice.

**Pull request merged**
