### PR TITLE
[Serve] Relaxed input Serve config's schemas to allow extra params

### LINKED ISSUE #38744: [Serve] Make Serve configs forward-compatible
### What happened + What you expected to happen

Currently (input) Serve configs are specified as following (forbidding extra parameters):

```
class ServeDeploySchema(BaseModel, extra=Extra.forbid):
```

This makes them _not forward-compatible_: ie adding new parameter to a config makes it incompatible with prior versions, meaning that if we submit the config from a newer Serve version to an older one (with new parameter) it would not be handled appropriately (rejected or failed).

This is problematic in cases when you have to handled multiple Serve versions deployed at the same time and want to use functionality from newer versions w/o a pain of keeping track of Ray versions.

### Versions / Dependencies

N/A

### Reproduction script

 - Add new config to either of Serve configs (HttpOptionsSchema, ServeDeploySchema)
 - Submit new config to previous Serve version
 - It will fail to parse

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by alexeykudinkin**
## Why are these changes needed?

This change is needed to make Serve configs [forward-compatible](https://en.wikipedia.org/wiki/Forward_compatibility#:~:text=Forward%20compatibility%20or%20upward%20compatibility,file%20formats%2C%20and%20programming%20languages.).

## Related issue number

Addresses https://github.com/ray-project/ray/issues/38744

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zcin** [comment]
If we make this change, should we also do it for DeploymentSchema and RayActorOptionsSchema?

**Review by GeneDer — APPROVED** [review]
LGTM, but might want to add a test case for this in `test_schema.py`. Also, might be good to log some messages to the user for any additional configs that are not being considered.

**Comment by alexeykudinkin** [comment]
@zcin good catch! Missed it for `DeploymentSchema` (and will do it for RayActorOptionsSchema as a result as well)

@GeneDer yes, i'm gonna be adding/fixing tests for it

**Comment by sihanwang41** [comment]
Is it possible to add warnings for any unrecognized attribute? 
I feel that is the trade off for UX, if I set `porttttt: 9000` (typo for `port`)  we will ignore the unrecognized attribute, and user might mistakenly think he is setting the port number.

**Review by zcin — APPROVED** [review]

**Comment by alexeykudinkin** [comment]
> Is it possible to add warnings for any unrecognized attribute? I feel that is the trade off for UX, if I set `porttttt: 9000` (typo for `port`) we will ignore the unrecognized attribute, and user might mistakenly think he is setting the port number.

Yes, we should still be doing validation, we should just do it differently: instead of mandating that no extra fields be allowed we have to make sure that _required_ fields are provided and if they are not -- we fail outright. In that case should be fairly obvious to the user what the problem is.

**Review by edoakes — APPROVED** [review]

**Comment by alexeykudinkin** [comment]
Doesn't seem like test failures are related.

@edoakes can you help merge this one?

**Comment by GeneDer** [comment]
Branch is freezed at this point. Please ask Zhe for approval and merge 🙏

**Comment by zhe-thoughts** [comment]
@alexeykudinkin  @edoakes could you help me understand whether this is important enough to include in Ray 2.7? If not, we can still commit to master after Friday

**Review by zhe-thoughts — APPROVED** [review]
Talked to @edoakes offline. Yes this should be merged

**Pull request merged**
