### PR TITLE
Revert "[RLlib] Add support for multi-GPU to DDPG."

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#17586

### CODE REVIEW

**Comment by amogkam** [comment]
fyi @sven1977

**Review by richardliaw — APPROVED** [review]
stamp

**Comment by richardliaw** [comment]
BTW, if merged, please open a new issue tracking this and assign to sven

**Comment by amogkam** [comment]
Sure I can, but in the past this has gone against test cop instructions.

**Pull request merged**
