### PR TITLE
Fix run_function_on_all_workers

### LINKED ISSUE #15201: ray.worker.global_worker.run_function_on_all_workers will run function twice on the current driver
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)

```python
import ray
import os
import time

if __name__ == '__main__':
    ray.init()
    ray.worker.global_worker.run_function_on_all_workers(
        lambda x: print(os.getpid())
    )
    # wait for spinning up workers
    time.sleep(1)
```

output:

```
8264
8264
(pid=8288) 8288
(pid=8284) 8284
(pid=8286) 8286
(pid=8289) 8289
(pid=8287) 8287
(pid=8285) 8285
(pid=8291) 8291
(pid=8290) 8290
```
This is done intentionally:

https://github.com/ray-project/ray/blob/4289fa8d43dc4b38a0066cf54a0dadd84a658a77/python/ray/worker.py#L358-L360

https://github.com/ray-project/ray/blob/4289fa8d43dc4b38a0066cf54a0dadd84a658a77/python/ray/_private/import_thread.py#L164

I am not sure if this is expected or a bug. Someone need to confirm it.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by suquark**
## Related issue number

Closes #15201 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
@kfstorm I assume you modified this part? Can you review the PR?

**Comment by kfstorm** [comment]
@rkooo567 I didn't modify this part, but I see the point.

The current fix seems a little tricky to me because it assumes that `fetch_and_execute_function_to_run` in a driver can only be triggered by `run_function_on_all_workers`.

How about we just remove this

https://github.com/ray-project/ray/blob/4289fa8d43dc4b38a0066cf54a0dadd84a658a77/python/ray/worker.py#L358-L360

and this

https://github.com/ray-project/ray/blob/4289fa8d43dc4b38a0066cf54a0dadd84a658a77/python/ray/_private/import_thread.py#L164

**Comment by suquark** [comment]
Currently, `fetch_and_execute_function_to_run` in a driver is only be triggered by `run_function_on_all_workers`. However, I am not sure if it could be triggered by a worker. In theory a worker can also call this function, but it is never done in practice.

**Comment by kfstorm** [comment]
> Currently, fetch_and_execute_function_to_run in a driver is only be triggered by run_function_on_all_workers.

I agree. But maybe the situation will be different in the future. In my opinion `job_id != self.worker.current_job_id.binary()` is like a hack which works currently but is not necessary.

**Comment by suquark** [comment]
I agree that remove `function({"worker": self})` is simpler. But it would change the behavior of `run_function_on_all_workers` slightly: it no longer guarantee that this function would run locally first. Not sure about its impact. Maybe @simon-mo have some ideas about this because this function seems now mostly used in ray serve.

**Comment by simon-mo** [comment]
@suquark it should ok as long as you modify https://github.com/ray-project/ray/blob/580b2bb9cc22f55ff9d8172841572e6216cd5a58/python/ray/serve/utils.py#L308 to run the `ray.util.register_serializer` in the current driver.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
