### PR TITLE
[RLlib] Fix time dimension shaping for PyTorch RNN models.

### LINKED ISSUE #13075: [RLlib] Bug when using RNNs, time_major and PyTorch
Hello,
When using TrajectoryView the padding of the sequences doesn't take into account `time_major`. The padded sequences are then given to `add_time_dimension` which returns the wrong output if `time_major=True`.

What currently happens: [A, B, B, C] -> [A, P, B, B, C, P] -> [[A,P, B], [B,C,P]]
While it should be: [[A, B,C], [A,B,P]]

I have managed to fix it by reshaping it as if it were `time_major=False` and transposing the first two axes. There might be a cheaper way to do it by modifying the padding function.

https://github.com/ray-project/ray/blob/85f1716a1f011501c9d5f8bf2043c0c3f356ba95/rllib/policy/rnn_sequencing.py#L175-L180

@sven1977 If you could take a look :)

### PR DESCRIPTION
**Pull request by XuehaiPan**
## Why are these changes needed?

- Fix `tensor.reshape` to `tensor.transpose` when storing data in time-major format. See https://github.com/ray-project/ray/issues/13075#issuecomment-1017425289 for more details.
- Use `tensor.view` instead of `tensor.reshape`, which will not create a new tensor instance.

## Related issue number

Closes #13075

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Review by gjoliver — APPROVED** [review]
would be nice to create a small unit test for add_time_dimension() based on your research.
good debugging btw.

**Comment by sven1977** [comment]
Hey @XuehaiPan , thanks a ton for this PR! Could you check the failing test cases here?
https://buildkite.com/ray-project/ray-builders-pr/builds/29015

Some things may have been broken by your changes.

**Comment by XuehaiPan** [comment]
Hi @sven1977, I updated my PR. The CI test errors seem irrelevant.

**Comment by sven1977** [comment]
Merged! :) Thanks for the fix @XuehaiPan.

**Pull request merged**
