### PR TITLE
Fix the `java_worker_options` parameter

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

Fix the Java CI failure introduced by #7439.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by mehrdadn — COMMENTED** [review]
Ah, sorry for the breakage! I searched the entire codebase for where `java_worker_options` was passed and missed this code on the Java side.

Regarding the current code, I think it means [this](/ray-project/ray/blob/a8bda9b55173e18335ed023531411473071e4d38/python/ray/services.py#L1253) would need to be changed as well (since we're not passing JSON there, but an actual list), and that the function documentations (e.g. [here](/ray-project/ray/blob/a8bda9b55173e18335ed023531411473071e4d38/python/ray/services.py#L1346)) would need to be updated too.

However, for passing command-line options, I would avoid JSON entirely, since it's a command-line interface, and hence it should behave that way to the user as well.

Now ideally, Java, would have a way to convert argument lists into command-lines, but it doesn't seem to. Here's one implementation you can use:

	static String list2cmdline(String args[]) {
		List<String> pieces = new ArrayList<String>();
		for (String arg : args) {
			String qarg = arg;
			if (arg.matches(".*[\"\\s\\\\].*")) {
				qarg = "\"" + arg.replaceAll("(\\\\*)(\"|\\\\\\z)", "$1$1\\\\$2") + "\"";
			}
			pieces.add(qarg);
		}
		return String.join(" ", pieces);
	}

Examples:

	Input : a
	Output: a

	Input : b c
	Output: "b c"

	Input : d'
	Output: d'

	Input : \
	Output: "\\"

	Input : e\f
	Output: "e\f"

	Input : g\h\
	Output: "g\h\\"

	Input : \i\\j\k\\
	Output: "\i\\j\k\\\\"

	Input : "
	Output: "\""

	Input : ?
	Output: ?

	Input : a b"c s\ e? f !g ;
	Output: "a b\"c s\ e? f !g ;"

Notice that backslashes are used in a _very_ limited manner here: they're only used to escape further backslashes that precede a quote. This is because it would be the shell's responsibility to collapse e.g. `\\\\` into `\\` before the program is even invoked, but there's no shell involved here at all. Meanwhile, this would match Windows's for compatibility, which passes command-lines to programs as a single string with a specific syntax rather than as an argument array.

On the Python side, you'll need to parse command-line strings, but there's no `cmdline2args`.

There _is_ `shlex.split`, but unfortunately I just noticed it doesn't quite do what we want: with `posix=True`, it would break on backslashes in Windows (e.g. it would fail `assert r'x\y' == shlex.split(r'x\y', posix=True)`), but with `posix=False`, it fails to strip quotes on all systems (e.g. it would fail `assert r'x\y' == shlex.split(r'"x\y"', posix=False)`).

Here's an implementation that I think should behave decently in any case we care about on every platform:

	import re

	def cmdline2args(cmdline):
		pat = "\'([^\']*)\'|\"((?:[^\\\\\"]+|\\\\.)*)(?:\"|$)|([^\'\" \\t]+)"
		return [tup[0]
		        or re.sub("((?:\\\\)*)\\1(\\\\|$)", "\\1\\2", tup[1])
		        or tup[2].replace("\\\\", "\\")
		        for tup in re.findall(pat, cmdline)]

This should behave as follows. If we pass the command-line `a '' "" "b c" 'd e' "f\g\\" h\i`, we should get these arguments (1 per line):

	a
	
	
	b c
	d e
	f\g\
	h\i

This matches Windows escaping behavior for backslashes while maintaining POSIX-like quote behavior.  

For example, if the user is in Bash and types

	ray --java_worker_command="foo \"x\y\" x\y"

then the arguments parsed would be `["foo", "x\\y", "xy"]`, which I think is what the user would expect on Linux/Mac.

And for example, if the user is in the Command Prompt and types

	ray --java_worker_command="foo \"C:\file\" C:\folder"

then the arguments parsed would be `["foo", "C:\\file", "C:\\folder"]`, which I think is also what the user would expect on Windows.

Meanwhile I think any reasonable command-line passed from the Java code to the Python code should also get quoted and unquoted as expected (but it would be good to double-check).

Sorry this is complicated, let me know what you think!

**Comment by jovany-wang** [comment]
@kfstorm Could you merge the current master branch to pass the CI.

**Comment by kfstorm** [comment]
@mehrdadn Thanks for the thorough explanation! I see your point.

Here we only tries to pass the `java_worker_options` argument from Java to `ray start`. And here we start `ray start` command with the `ProcessBuilder` class, which takes in a list of string as arguments. I believe `ProcessBuilder` can correctly handle the escaping. So I think JSON is totally fine here.

As for starting the Raylet process, I don't think `subprocess.list2cmdline` and `SplitStrByWhitespaces` are fully compatible. I don't see any unescaping in `main.cc` and `worker_pool.cc`.

Anyway, I missed the `java_worker_options or ["-classpath", default_cp]` part and I've moved the `json.loads` out of `build_java_worker_command`.

Could you take a look again?

Note: In `RunManager.java` we start the Raylet process directly - for users who wants to start a ray cluster with the Java code `Ray.init()` instead of the `ray start` script. In this case we still use joining with whitespace to construct Java and Python worker commands. Maybe you want to align with `subprocess.list2cmdline`? See https://github.com/ray-project/ray/blob/fbac2569827558227e1e2cca71f837f5a3baa3b9/java/runtime/src/main/java/org/ray/runtime/runner/RunManager.java#L320-L321

**Review by jovany-wang — APPROVED** [review]
LGTM

**Comment by jovany-wang** [comment]
This can be merged to unblock CI, and other concerns can be addressed in other PRs.

**Comment by mehrdadn** [comment]
@kfstorm: I've actually been working on getting rid of `SplitStrByWhitespaces` the past 3 days, so that will be gone very soon, don't worry. :-) I might not be able to look into Windows compatibility for Java very soon, but thanks for mentioning that, it's helpful to know. I do think we shouldn't suddenly switch to JSON in the middle of the command line but maybe I can look into fixing it myself later.

**Comment by kfstorm** [comment]
@mehrdadn I do agree that passing JSON in command line is not a good idea. Java CI has been broken for a long time and we finally make it passed. So we want to merge this ASAP. Hope you can understand.

And thanks for your efforts on improving the command line argument passing. I can also help if you need me. 😉

**Comment by kfstorm** [comment]
@mehrdadn One thing just come to my mind is that the `--internal-config` parameter accepts a JSON string. Maybe you want to update that too?

**Comment by mehrdadn** [comment]
Ooh okay, thanks for letting me know!

**Pull request merged**
