### PR TITLE
[Metric] export metric types for users

### PR DESCRIPTION
**Pull request by ashione**
Ray python metric has been provided for users. But we do not export them in experimental __init__.py.
So this PR changes can let upper users record metrics by this following usage:
```python
import Gauge from ray.experimental
gauge = Gauge(
      'ray.worker.metric',
      'description',
      'unit',
      ['tagk1', 'tagk2'])
gauge.record(1.0)
```

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ashione** [comment]
@jovany-wang I'm not sure which is better? `import Gague from ray.experimental` or `import Gague from ray.experimental.metrics`

**Comment by ashione** [comment]
> @jovany-wang I'm not sure which one is better? `import Gague from ray.experimental` or `import Gague from ray.experimental.metrics`. The second import style can show directly to users that metric gauge will be captured.

@rkooo567 Any suggestions about that?

**Review by zhongchun — APPROVED** [review]
LGTM.

**Comment by zhongchun** [comment]
> @jovany-wang I'm not sure which one is better? `import Gague from ray.experimental` or `import Gague from ray.experimental.metrics`. The second import style can show directly to users that metric gauge will be captured.

I prefer the latter.latter

**Comment by jovany-wang** [comment]
this is API exposing, @ericl  cc

**Comment by jovany-wang** [comment]
Once this PR merged, it's better to add some documents.

**Comment by rkooo567** [comment]
I thought we moved it to util?

**Comment by ashione** [comment]
> I thought we moved it to util?

Metrics might not belong to util. I remember that ericl or edoakes suggest me to keep it in experimental before released.

**Comment by rkooo567** [comment]
Hmm I am confused. I think we moved metrics api to ray.util.metrics, not experimental?

**Comment by ashione** [comment]
> Hmm I am confused. I think we moved metrics api to ray.util.metrics, not experimental? When did they say that to you?

You may find more details in this link https://github.com/ray-project/ray/pull/9469#issuecomment-658925683.

**Comment by jovany-wang** [comment]
@rkooo567 @ashione There is already metrics under util, why we need another one?

**Comment by ashione** [comment]
> @rkooo567 @ashione There is already metrics under util, why we need another one?

We'd better unify them to one.

**Comment by rkooo567** [comment]
We don’t have metrics api in the experimental folder anymore. Check https://github.com/ray-project/ray/tree/master/python/ray/experimental

**Comment by ashione** [comment]
> https://github.com/ray-project/ray/tree/master/python/ray/experimental

@rkooo567 I notice that other metric api/exporter was used in rllib. @jovany-wang Shall we merge them into one module?

**Comment by ashione** [comment]
I notice that metric module has been integrated into  `util.metric`, but no SUM metric in that.

**Pull request closed without merging**
