### PR TITLE
[Release] Use nightly base images for release tests

### PR DESCRIPTION
**Pull request by amogkam**
Revert back to using nightly base images instead of pinning to 1.12.1. Pinning the docker image had led to uncaught errors in the past. Instead, we should be using nightly to make sure release tests will work on the most up to date versions of docker/cluster envs. If there are any test failures, the underlying issues should be fixed rather than pinning the docker image.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
@krfricke do we have mechanism to wait until the nightly image is built and pushed to anyscale from the release tool?

**Comment by amogkam** [comment]
@rkooo567 anyscale has a daily job to build a new nightly image. When our release tests run, it will use the most recent anyscale nightly image, which will always be slightly out of date, but the "outdatedness" will not grow over time which is what happens when we pin to a specific version.

**Comment by krfricke** [comment]
Genereally I'd be happy to switch  back to nightlies, but there are two things

1. In the past we had problems with anyscale docker image updates that lead to e.g. this error on startup

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container: unknown.
Shared connection to 34.215.195.95 closed.
```

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_Cd7tfNdAiB8dEHkVBUwyxACx?command-history-section=head_start_up_log

2. We're only pinning the container dependencies (but we are re-installing the ray wheels always). If I understand correctly the nightly anyscale image uses the latest release anyway (can someone confirm? @ijrsvt ?) so I'm wondering if we can document this somewhere and see what we actually change when switching to nightly *anyscale* images.

**Comment by rkooo567** [comment]
What's the action item for this?

**Comment by krfricke** [comment]
No, it currently doesn't work - we have to wait until https://github.com/ray-project/ray/issues/25588 is resolved

**Comment by krfricke** [comment]
It was resolved. Let's wait for new anyscale nightly images to be built (tomorrow) and then try to kick this off again!

**Comment by krfricke** [comment]
Kicked off a run here: https://buildkite.com/ray-project/release-tests-pr/builds/6939

**Comment by krfricke** [comment]
Still failing:

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container: unknown.
```

**Comment by amogkam** [comment]
This is still blocked by https://github.com/anyscale/product/issues/11457

**Comment by amogkam** [comment]
@krfricke I commented on https://github.com/anyscale/product/issues/11457, but we need a new AMI build in addition to nightly Docker image build I think

**Comment by amogkam** [comment]
Ok cluster is able to start up successfully, going to merge!

**Pull request merged**
