### PR TITLE
[rllib] SAC tuple observation space fix

### PR DESCRIPTION
**Pull request by juliusfrost**
## Why are these changes needed?

Fixes a concatenation error with tuple observation spaces in SAC

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by juliusfrost** [comment]
Would appreciate a review 🙂 @richardliaw @sven1977

**Comment by richardliaw** [comment]
Is there a simple env that we can test against?

**Comment by juliusfrost** [comment]
https://github.com/ray-project/ray/blob/7225f28fff23be4b39a361fb9aea765dc99f4ddc/rllib/agents/sac/tests/test_sac.py#L68
This function looks like it tests tuple observation spaces but I'm not sure if it hits the lines I modified. I got the error by running my using the train.py with a custom environment

**Comment by richardliaw** [comment]
Hmm, would it be possible to add some custom environment in the test that has the same behavior as your env?

**Comment by juliusfrost** [comment]
Okay, so I figured out that the problem was that the gym tuple observation space doesn't enforce it's space to be a tuple type, therefore rllib has to do the work to enforce type correctness.

**Comment by juliusfrost** [comment]
The test should now fail if you remove https://github.com/ray-project/ray/pull/17356/commits/2ba02466ab6daac5aae4895e083ddff6c2905f59

**Review by richardliaw — APPROVED** [review]
awesome looks great!

**Comment by richardliaw** [comment]
hmmm looks like tests failing?

**Comment by juliusfrost** [comment]
Odd, it's failing in the test I didn't modify

**Comment by sven1977** [comment]
Re-running test_sac.py. Seems to have failed for an unrelated reason (loss func test is still somewhat flakey).

**Comment by sven1977** [comment]
Will merge once test confirmed. ...

**Comment by sven1977** [comment]
Thanks for this fix @juliusfrost !

**Comment by juliusfrost** [comment]
@sven1977 Thanks for the merge!

**Pull request merged**
