### PR TITLE
[Test] Try fixing a flaky gcs heartbeat manager test.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Heartbeat manager starts its own thread to run its background task and that shares the same data structured used within `HandleReportHeartbeat ` (`heartbeats_`). That said, both methods should run in the same thread. This achieves it by running `HandleReportHeartbeat` within the io_service thread

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by fishbone — APPROVED** [review]

**Comment by iycheng** [comment]
Hmmm asan failed, probably because the stopping code is wrong

**Comment by rkooo567** [comment]
@iycheng at least it seems like the original issue has disappeared. Let me take a look at it again

**Comment by iycheng** [comment]
@rkooo567  really thanks for the help!

**Comment by rkooo567** [comment]
Just found dead_nodes field is not protected by mutex. Let me add a lock and see if it fixes the issue

**Pull request merged**
