### PR TITLE
[spark] Make ray on spark support spark local mode

### PR DESCRIPTION
**Pull request by WeichenXu123**
## Why are these changes needed?

Make ray on spark support spark local mode.
Databricks Runtime single node cluster runs in spark local mode, so we need to support it.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jjyao — APPROVED** [review]

**Comment by jjyao** [comment]
Can we add a test for it?

**Comment by WeichenXu123** [comment]
CC @jjyao Test is added.

**Comment by jjyao** [comment]
lint errors.

**Comment by WeichenXu123** [comment]
CC @jjyao Fixed!

**Pull request merged**
