### PR TITLE
[WIP] Support a bisecting tool for release tests

### PR DESCRIPTION
**Pull request by rkooo567**
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @krfricke I am thinking to contribute this feature (I used it to bisect some commits). Lmk if you have any concern. Note that code is not complete yet.

**Comment by krfricke** [comment]
Yeah this sounds good! IMO It should be pretty simple - we allow more than one value to be passed to `ray_commit` variable and then just iterate over these in `build_pipelines.py`

**Comment by krfricke** [comment]
Yeah this looks good! I like that it's a full automatic bisect. Wondering if we could also implement this on Buildkite so we don't have to run on our laptops for that long

**Comment by rkooo567** [comment]
we definitely should! I will probably look into it after merging this PR

**Comment by ollie-iterators** [comment]
bump

**Pull request closed without merging**
