### PR TITLE
[Datasets] Fix Dataset docstring

### PR DESCRIPTION
**Pull request by c21**
Signed-off-by: Cheng Su <scnju13@gmail.com>

## Why are these changes needed?

Quick followup fix of https://github.com/ray-project/ray/pull/32390 .
## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by cadedaniel** [comment]
Can you confirm that you ran doctest and it produced no errors?

**Comment by c21** [comment]
Test - https://buildkite.com/ray-project/release-tests-pr/builds/28170

**Comment by c21** [comment]
@cadedaniel - I want to wait https://buildkite.com/ray-project/oss-ci-build-pr/builds/12015#01863e47-d759-4cdf-9097-8d911d3a2789 before merging this.

**Comment by c21** [comment]
The failed test is irrelevant, so good to merge:

```
File "../../python/ray/data/dataset.py", line ?, in default
--
  | Failed example:
  | ds.zip(ds).take()
  | Expected:
  | [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]
  | Got:
  | [(0, 0), (1, 1), (3, 2), (2, 3), (4, 4)]
  | **********************************************************************
  | 1 items had failures:
  | 1 of   3 in default
  | 3 tests in 1 items.
  | 2 passed and 1 failed.


```

**Review by ericl — APPROVED** [review]

**Pull request merged**
