### PR TITLE
[core] Forward task lineage when putting object with assigned owner

### PR DESCRIPTION
**Pull request by kira-lin**
## Why are these changes needed?

Currently objects converted from raydp dataframe is not recoverable. This PR solves this problem.

## Related issue number
#23824 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kira-lin** [comment]
Hi @stephanie-wang , I tried this implementation, but it seems like task_id obtained in the RPC is not the same as the task executing on the actor. Is this true? How should I fix this?

**Comment by stephanie-wang** [comment]
> Hi @stephanie-wang , I tried this implementation, but it seems like task_id obtained in the RPC is not the same as the task executing on the actor. Is this true? How should I fix this?

Hmm could have something to do with multithreading? I'm not sure exactly how it works, but I think if a task is multithreaded, the other threads will create a thread-local task ID to avoid collisions in other parts of the system.

**Comment by kira-lin** [comment]
```python
import ray
@ray.remote
class foo:
  def bar(self):
    print(ray.get_runtime_context().task_id) # 1
    time.sleep(10)
ray.init()
handle = foo.remote()
ref = handle.bar.remote()
print(ray.put(1, _owner=handle)) # 2
ray.get(ref)
```
I've been using this script to test, but the task id printed in the two places are different. This actor is not multi-threaded, right? I guess it's because I use RPC to connect to it? How should I obtain the task id then?

**Comment by kira-lin** [comment]
I've been testing another approach recently, but it's very limited. I tried to call into spark executors and fetch data from blockmanager directly, but I couldn't re-compute it because spark context/rdd is not available. 

I wonder how can I implement this forwarding? Why did I get a different taskid, and how can I fix it? @stephanie-wang

**Pull request closed without merging**
