### PR TITLE
Synchronize arrow version and put changes upstream

### PR DESCRIPTION
**Pull request by pcmoritz**
The goal of this PR is to make sure the version of arrow linked into Ray via Bazel and the python wheels are at the same version and synchronized with the latest arrow master.

- [x] Merge https://github.com/apache/arrow/pull/3927
- [x] Merge https://github.com/apache/arrow/pull/4001
- [x] Rebuild base docker image `rayproject/arrow_linux_x86_64_base` for latest arrow
- [x] Build new python wheels via `https://github.com/ray-project/arrow-build` (i.e. merge https://github.com/ray-project/arrow-build/pull/3)

### CODE REVIEW

**Comment by guoyuhong** [comment]
It looks like there is test failures in Mac. I cannot repro that error in my local machine. My colleague reported that some of plasma fails to start when the tests run some time in his old Mac system. I'm not sure whether this is the same problem.

**Comment by pcmoritz** [comment]
So the new wheels are now building successfully.

I also can't reproduce the macOS failure unfortunately. Increasing the timeout for connecting didn't help.

**Comment by guoyuhong** [comment]
@pcmoritz You may also noticed that there are test failures in MacOS. It looks like that the plasma store fails to start when the travis test runs some time. This only happens in MacOS 10.11. @raulchen is investigating the same problem.

**Comment by raulchen** [comment]
I tried using the default osx version (xcode 9.4 and macOS 10.13), but CI still failed.

Plasma store log has the following error:

```
==> /tmp/ray/session_2019-03-19_06-06-41_89976/logs/plasma_store.err <==

external/plasma/cpp/src/plasma/store.cc:1093: Allowing the Plasma store to use up to 1.28849GB of memory.

external/plasma/cpp/src/plasma/store.cc:1120: Starting object store with directory /tmp and huge page support disabled

external/plasma/cpp/src/plasma/dlmalloc.cc:90: failed to ftruncate file /tmp/plasmayAfIcY
```

**Comment by raulchen** [comment]
Printed the error message: `external/plasma/cpp/src/plasma/dlmalloc.cc:107: failed to ftruncate file /tmp/plasmawsYIAN No space left on device`
@pcmoritz it seems that new arrow changes introduced memory leak on macOS?

Also, most of the tests use default plasma store size. This needs to be fixed.

**Comment by raulchen** [comment]
Setting default plasma memory to 100mb can fix this issue.

**Comment by guoyuhong** [comment]
I think I found the root cause. Let's search `df -h` twice in https://travis-ci.com/ant-tech-alliance/ray/jobs/185955879 . The first time was before the test failure. It showed that the disk space had only 4% spared space and soon later the test failed. `df -h` showed that there were 45% spared space. It looks like that `/tmp/plasmaXXXXXX` is unlinked but not really deleted before pytest exiting. This problem could be introduced by recent arrow update. Furthermore, previously, pytest is called per file and this problem won't show up. I will specify the plasma memory to 100 MB to mitigate this problem in https://github.com/ray-project/ray/pull/4390 .

**Comment by raulchen** [comment]
It seems that the python process doesn't release the fd. 

I run `init/shutdown` multiple times in a python process on my Macbook with macOS 10.13.4, `lsof` shows that the process is holding the following fds.
image

However, `df -h` doesn't should usage increase on my machine. I guess that might be because of the OS versions.

**Comment by pcmoritz** [comment]
@raulchen Thanks, that looks promising. I suspect the problem is fixed by https://github.com/apache/arrow/compare/master...pcmoritz:plasma-client-unmap?expand=1, I'm trying that out now.

**Comment by raulchen** [comment]
CI is failing with error:
```
bazel-out/k8-opt/bin/external/plasma/_virtual_includes/plasma_lib/plasma/store.h:31:35: fatal error: plasma/external_store.h: No such file or directory
```

**Comment by pcmoritz** [comment]
Looks like this is finally passing 🤕

**Review by raulchen — APPROVED** [review]
Thanks!

**Comment by raulchen** [comment]
Is this ready for merge now?

**Comment by pcmoritz** [comment]
We need to merge https://github.com/apache/arrow/pull/4001, then rebuild the wheels from that, and then it can be merged. I expect we can merge this tomorrow.

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Review by guoyuhong — APPROVED** [review]
Thanks for all the efforts!

**Comment by robertnishihara** [comment]
It'd be nice to have a good way to keep these in sync in the future, though I guess we're going to have to do it manually?

I just merged this, but it occurred to me, we should add a comment at each place where we specify the arrow commit telling people that both places need to be updated simultaneously.

**Pull request merged**
