### PR TITLE
[all_tests][core] Ping grpcio to <= 1.49.1 due to thread pool hanging issue on mac

### PR DESCRIPTION
**Pull request by rickyyx**
Signed-off-by: rickyyx <rickyx@anyscale.com>

## Why are these changes needed?
With grpcio >= 1.50.0, this PR is included: https://github.com/grpc/grpc/commit/6b95573959f4efd62c60a144b29b430e093d2813

Tracking issue on grpc repo: https://github.com/grpc/grpc/issues/31772

And this has caused hanging of tests on mac, leading to multiple flaky tests. 
E.g. 
- https://github.com/ray-project/ray/issues/30954
- [osx://python/ray/tests:test_reconstruction](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1458#0184ef73-4ca6-4d21-ae7c-6fba362b0d05/2004-4542)
- [osx://python/ray/tests:test_placement_group](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1465#0184f2f2-3288-43db-b2cb-2b53688c2fd7/943-2191)

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scv119 — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
can you verify this actually fixes the issue? Also, can you create an issue to unpin grpc version (with a link to their issue page)

**Comment by rickyyx** [comment]
Running all tests.

**Comment by rickyyx** [comment]
mac tests all good - no timeout and no thread pool message.

**Comment by rickyyx** [comment]
Could any of the code owners PTAL? Thanks, cc @richardliaw @ericl @edoakes

**Review by edoakes — APPROVED** [review]
+1 to @rkooo567's comment -- let's please make sure we follow up and unpin when we can. Don't want to end up stuck on an old version.

**Review by rkooo567 — APPROVED** [review]

**Pull request merged**
