### PR TITLE
Pin pydantic to < 2.0.0

### PR DESCRIPTION
**Pull request by alanwguo**
## Why are these changes needed?
2.0.0 brings breaking changes

Here's a failed CI run: https://buildkite.com/ray-project/oss-ci-build-pr/builds/27338#01890d26-94ff-42f2-80be-c2ac0a86e8d3/447-762

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
Don't forget to fix the code and unpin it after this is merged :)

**Review by pcmoritz — APPROVED** [review]
Let's get this merged -- at least it puts out the fire and then we can make sure we can be compatible with both pydantic 1 and 2 going forward.

**Comment by alanwguo** [comment]
CI seems to be in a really bad state. i doubt any of the failures are related. Should we just merge?

**Comment by pcmoritz** [comment]
Yeah, I believe the failures are unrelated.

We need one more codeowner approval, @ericl can you do that? :)

**Review by ericl — APPROVED** [review]

**Comment by ddelange** [comment]
hi 👋 will this be part of the ray 2.7 release? or more generally: will ray 2.7 release from `master` branch?

**Pull request merged**
