### PR TITLE
Revert "[Core]Support back pressure."

### PR DESCRIPTION
**Pull request by krfricke**
Reverts ray-project/ray#19936

Breaks current master (rllb tests_gpu) which was not caught because RAY_CI_RLLIB_DIRECTLY_AFFECTED was not triggered

https://buildkite.com/ray-project/ray-builders-branch/builds/5039#e48a3acc-750f-41d2-996b-e6866bb524d8

cc @gjoliver should we extend RAY_CI_RLLIB_DIRECTLY_AFFECTED?

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
we should make sure to add proper unit tests for this regression when this pr is re-merged. Cc @ericl

**Comment by ericl** [comment]
It seems unlikely to be causing `ValueError: Cannot concat data under key 'new_obs'`. Shall we wait for the tests to pass?

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
cc @MissiontoMars you need resubmit the PR again

**Review by ericl — APPROVED** [review]

**Comment by MissiontoMars** [comment]
> cc @MissiontoMars you need resubmit the PR again

I resubmit a new PR https://github.com/ray-project/ray/pull/20894. But I can't figure out which test case is blocked. What is the regression scenario?

**Pull request merged**
