### PR TITLE
[RLlib] Pin ALE-py In Rllib Requirements And Other Release Test Fixes

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Signed-off-by: Artur Niederfahrenhorst <artur@anyscale.com>

## Why are these changes needed?

The following issue persists in our RLlib release tests:
Screenshot 2022-09-30 at 00 29 10
The [initial fix](https://github.com/ray-project/ray/pull/28703) is overwritten when install the requirements_rllib.txt, since Python versions >=3.7 will reinstall gym instead of gym[atari].

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by avnishn** [comment]
release tests running here: https://buildkite.com/ray-project/release-tests-pr/builds/16786

**Review by avnishn — APPROVED** [review]

**Comment by avnishn** [comment]
new release tests: https://buildkite.com/ray-project/release-tests-pr/builds/16830

**Comment by avnishn** [comment]
https://buildkite.com/ray-project/release-tests-pr/builds/16853

just need to check to see if these ^ tests get kicked off and if they do then this is ready to merge

**Comment by avnishn** [comment]
tests were able to be kicked off 

image
this is ready to merge

**Review by gjoliver — APPROVED** [review]

**Pull request merged**
