### PR TITLE
Address leftover comments from https://github.com/ray-project/ray/pull/16394/files

### PR DESCRIPTION
**Pull request by ericl**
Followup for https://github.com/ray-project/ray/pull/16394/files

### CODE REVIEW

**Comment by stephanie-wang** [comment]
Can you also address this comment? https://github.com/ray-project/ray/pull/16394#discussion_r658997713

**Comment by stephanie-wang** [comment]
Can you also address this comment? https://github.com/ray-project/ray/pull/16394#discussion_r658997713

**Comment by ericl** [comment]
> Can you also address this comment? #16394 (comment)

The thrashed stat was actually violating thread-safety, by reading the pulled objects map without holding the mutex. It seemed nontrivial to fix this issue, so I dropped the stat (frankly, I don't think the detailed breakdown of cancelled is that necessary).

**Comment by stephanie-wang** [comment]
Can we also lower the debug level for this statement? https://github.com/ray-project/ray/blob/master/src/ray/object_manager/pull_manager.cc#L135

It's causing a lot of spam when task args are queued.

**Comment by ericl** [comment]
Done. It was supposed to be debug level...

**Comment by stephanie-wang** [comment]
> > Can you also address this comment? #16394 (comment)
> 
> The thrashed stat was actually violating thread-safety, by reading the pulled objects map without holding the mutex. It seemed nontrivial to fix this issue, so I dropped the stat (frankly, I don't think the detailed breakdown of cancelled is that necessary).

Isn't this easily fixed by holding the mutex? It was actually useful in tracking down the spillback bug in #16488. Otherwise, it was hard to tell why objects were no longer being pulled.

**Comment by ericl** [comment]
> Isn't this easily fixed by holding the mutex? It was actually useful in tracking down the spillback bug in #16488. Otherwise, it was hard to tell why objects were no longer being pulled.

It's hard. Feel free to add it back in your PR if you want, but the changes are extensive.

**Review by stephanie-wang — APPROVED** [review]

**Pull request merged**
