### PR TITLE
[post-0.4.0 KubeRay release] Update KubeRay versions

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
Signed-off-by: Dmitri Gekhtman <dmitri.m.gekhtman@gmail.com>

## Why are these changes needed?

This PR updates KubeRay versions in the Ray CI to 0.4.0.
It also removes a couple of warnings specific to KubeRay 0.3.0.
It should be merged once KubeRay 0.4.0 images are built.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
(Noting that the operator test passes with the recently pushed `kuberay/operator:v0.4.0` image.)

**Comment by DmitriGekhtman** [comment]
Code owners, please stamp and merge.

**Review by simon-mo — APPROVED** [review]

**Review by wuisawesome — APPROVED** [review]

**Review by kevin85421 — COMMENTED** [review]
Are the CI failures related to this PR? If not, the changes look good to me.

**Comment by DmitriGekhtman** [comment]
> Are the CI failures related to this PR? If not, the changes look good to me.

No

**Pull request merged**
