### PR TITLE
[RLlib] Exploration API: parameter noise components only (no DQN/DDPG changes).

### PR DESCRIPTION
**Pull request by sven1977**
Goal: Move hard-coded parameter noise feature from DQN into new Exploration API.

The new methods ...

on_episode_start
on_episode_end
before_forward_pass
postprocess_trajectory

... have been added to enable the Exploration classes to control the ModelV2 before a forward pass (which is executed by the Policy) and to setup things before and after each episode.

NOTE: THIS PR DOES NO LONGER INCLUDE CHANGES TO DQN REGARDING PARAMETER-NOISE. This will be a separate PR.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by sven1977** [comment]
@ericl This is ready for review again. It's the "smaller" version of the previous one. DQN/DDPG are not affected yet. They will be cleaned-up and made compatible with the new ParameterNoise class in a next PR.

**Comment by ericl** [comment]
Hm I still see DDPG/dwn changes, need to push?

**Comment by sven1977** [comment]
The DDPG changes have to stay there, otherwise the algo will break due to some other changes we made in the exploration API.
- we enforced using named args in some explorations and their methods.
- we enforced passing in the model in eery exploration's constructor.
- we construct `distribution_inputs` (if possible and useful) and pass that into the TFPolicy super constructor.

DDPG in this PR is not using ParameterNoise, though.

**Comment by sven1977** [comment]
Branch updated, please merge.

**Comment by ericl** [comment]
This PR is still quite large (37 files, 1500 changed lines).I think we should be more surgical about major changes, since it both makes it hard to review, and for anyone casually following changes to see the important deltas in the PRs. Can you please make a PR with the bare minimal patch for param noise?

I'm generally fine with some unrelated changes, just not in critical PRs.

**Comment by ericl** [comment]
Closing these for now since they build on #7772

**Pull request closed without merging**
