### PR TITLE
[Train] Support returning multiple devices in `train.torch.get_device()`

### PR DESCRIPTION
**Pull request by amogkam**
For model parallel workloads like stable diffusion fine-tuning, we may want to use multiple GPUs per Ray Train worker. This PR implements support for `train.torch.get_device()` returning a List of devices for these use cases so that users do not need to manage device setting themselves.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — APPROVED** [review]
Thanks, LGTM.

This will still require us to change the `prepare_model()` methods to allow to select a specific device. We can update this in a follow-up (we may just want to pass in the cuda device ID directly and otherwise default to `get_device()[0]`

**Comment by amogkam** [comment]
Good point, updated

**Comment by Yard1** [comment]
Isn't this technically a breaking change?

**Comment by amogkam** [comment]
I think it should be fine since this is only affecting the multi-GPU case and this is still beta API.

**Pull request merged**
