### PR TITLE
[core] log error and handle abortion from accept() call

### PR DESCRIPTION
**Pull request by hongchaodeng**
## Why are these changes needed?

This PR improves the code in two places:
- logs the error message from accept() call
- if the error is `operation_aborted`, that means the server is shutting down and we should not continue to do accept()

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
Could you update the PR description: what's the issue and what's the fix? You can also link the GH issue under `Related issue number`

**Comment by hongchaodeng** [comment]
@jjyao  There is no related issue. It is just some improvement that I think of as I read the code.

Do you want me to create an issue or do you only want PR that has an explicit issue?

**Comment by stephanie-wang** [comment]
> @jjyao There is no related issue. It is just some improvement that I think of as I read the code.
> 
> Do you want me to create an issue or do you only want PR that has an explicit issue?

It's okay if there's no issue for small improvements. But let's add a PR description - it helps for reviewing and we use it as the commit message on master.

**Comment by hongchaodeng** [comment]
@stephanie-wang Thanks! Have updated the title and description.

**Comment by hongchaodeng** [comment]
Hi @stephanie-wang 
I have added the PR description. Let me know what else changes are needed from my side? Thanks!

**Review by jjyao — APPROVED** [review]

**Pull request merged**
