### PR TITLE
[operator] expose RAY_CONFIG_DIR env var (fix #14074)

### LINKED ISSUE #14074: [operator] RAY_CONFIG_DIR should be an environment var
### What is the problem?

hard-coding `RAY_CONFIG_DIR` to `~/ray_cluster_configs` assumes there is a user defined on the image: this is true for the upstream ray images but not guaranteed for custom ray images.

propose that RAY_CONFIG_DIR should be an environment variable that can be configured via the downward api for k8s

*Ray version and other system information (Python version, TensorFlow version, OS):*
head of main dev branch (ray 2.0 dev)

### Reproduction (REQUIRED)

run `ray-operator` using a custom ray image where `~` does not refer to a normal home directory, and `~/ray_cluster_configs` is just `/ray_cluster_configs`

example:
https://github.com/erikerlandson/ray-ubi

### PR DESCRIPTION
**Pull request by erikerlandson**
## Why are these changes needed?

Exposing RAY_CONFIG_DIR environment variable to improve configurability of where ray writes config files

## Related issue number

Closes #14074

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by erikerlandson** [comment]
cc @DmitriGekhtman

**Comment by erikerlandson** [comment]
buildkite failures do not seem to be related to this code change.

**Review by DmitriGekhtman — APPROVED** [review]
LGTM. Thanks!

**Comment by DmitriGekhtman** [comment]
I'll document this the next time I update push a PR updating the docs
(plans for this in the not-too-distance future)

@simon-mo Could you merge this?

**Comment by erikerlandson** [comment]
Thanks, this is working for me!

**Pull request merged**
