### PR TITLE
[rllib] Remove bad spinlocks to allow pytorch GPU scheduler to interrupt.

### PR DESCRIPTION
**Pull request by Bam4d**
## Why are these changes needed?

Discussion of this bug and the fix can be found here: 
https://discuss.ray.io/t/very-slow-gradient-descent-on-remote-workers/1278
and here:
https://discuss.ray.io/t/rllib-ray-trains-extremely-slow-when-learner-queue-is-full/289/6

Summary: pytorch GPU scheduler breaks and defaults to using CPU if sample queues in the IMPALA implementation are full.

When the sample queues are full, the worker threads spinlock which does not allow the [thread to be interrupted and used i the GPU scheduler](https://stackoverflow.com/questions/60086108/forward-pass-gets-10000x-slower-after-iterating-for-a-while).

Fix: Instead of spinlocking, introduce a small sleep (which allows the thread to be interrupted). This also stops wasting of CPU time spinning. By default if the `_NextValueNotReady(Exception)` class is used to mark queues that are full then a small sleep is executed.

This small wait fixes the bug and keeps the GPU running at full capacity!

@smorad I did try `sleep(0)` however this did not seem to solve the issue, I think the small wait is a good thing in this case as it allows CPU to rest and also at this point there are already 16 samples per queue ready to go which will not slow down learing at all.

@sven1977 Please note: This does actually introduce a bug that the "sample_throughput" calculation actually only calculates the throughput through the "ConcatBatches" part of the pipeline, which if there queues are full is tiny. Therefore sample throughput time is completely mis-calculated as it does not need to wait at all for new batches.

## Related issue number

Issues are in discuss.ray.io listed above.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by smorad** [comment]
IIRC the sample throughput bug is already present, even without this patch.
When the worker spinlocks the throughput metric shoots through the roof,
while samples are being processed much slower.

**Comment by smorad** [comment]
I'm curious how you figured out this was due to the pytorch GPU scheduler not getting any processing time. It sounds like python should automatically switch between threads unless you are holding the GIL (for example, executing a wrapped c function). If the `LearnerThread` is preventing context-switching between threads, I suspect this could cause issues elsewhere as well.

**Comment by smorad** [comment]
Can you verify that https://github.com/ray-project/ray/pull/16162/files#diff-a0c81396e13bb0aace30b34c28b3d3ca9430963c5db9d28ef799491ccecf4018R75 is actually fixing the issue? Because `_NextValueNotReady` is actually called in many places, such as here:

https://github.com/ray-project/ray/blob/35ec91c4e04c67adc7123aa8461cf50923a316b4/rllib/execution/concurrency_ops.py#L100
https://github.com/ray-project/ray/blob/35ec91c4e04c67adc7123aa8461cf50923a316b4/rllib/agents/impala/impala.py#L281

https://github.com/ray-project/ray/pull/16162/files#diff-a0c81396e13bb0aace30b34c28b3d3ca9430963c5db9d28ef799491ccecf4018R75

I suspect that sleeping is the correct solution, but this may be sleeping more than it needs to (in the above case, once for each training batch in the queue)!

Perhaps changing the default config is too much work, but I think it would make sense to have something like:

```
config = {
  # Time for the learner thread to sit idle. This allows
  # torch GPU scheduling to occur under heavy load
  learner_thread_wait_time_ms = 1
  ...
}
...
def step(self):
  time.sleep(cfg['learner_thread_wait_time_ms'] / 1000)
```

**Comment by Bam4d** [comment]
> I'm curious how you figured out this was due to the pytorch GPU scheduler not getting any processing time. 

Just a bunch of googling and experience with deadlocks in distributed systems. I had seen the spinlocks before your comment in discuss.ray.io threads, but when you mentioned something to do with the GPU scheduler, i put two and two together and thought that the spinlocks might be stopping the thread getting interrupted. Also Ray does some stuff where it assigns single cpus to processes, so if you're spinlocking there's even less threads for the interrupts (i think).

As for putting the sleep in the `_NextValueNotReady()`.. its pretty much used in all cases where there a queue thats full or empty. In general its good to add small waits in these scenarios because its waiting on some other process to do work, so releasing the thread and letting the OS use it somewhere else if it needs to is fine. Much better than just 100% spinning the thread until the data is available.

I think you can do sub-millisecond sleeps also which may be adequate. 

Not sure why you would ever want this configurable as a parameter, I think this would probably add unecessary complexity to a fairly saturated set of configuration options. Also changing this parameter would have pretty much no effect.

Did you try the change on your own hardware? Did it solve for you?

**Comment by smorad** [comment]
I can't interrupt my current experiments, but after they finish I will clone this repo and give it a shot! Since we had the exact same problem, if this works for you it very likely works for me.

**Review by sven1977 — APPROVED** [review]
Awesome! Thanks @Bam4d for this fix.

**Pull request merged**
