### PR TITLE
Updates to azure autoscaler for authentication and dependency updates

### LINKED ISSUE #19523: [Bug] Ray Autoscaler does not work with Azure due to deprecated method
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

`ray up azure.yaml` fails. See stack trace here https://github.com/Azure/azure-sdk-for-python/issues/21313

The reason is that MS is deprecating this method `get_client_from_cli_profile`, see https://github.com/Azure/azure-sdk-for-python/pull/21337

```
  File "/Users/lsf/opt/miniconda3/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 7, in <module>
    from azure.common.client_factory import get_client_from_cli_profile
```

### Versions / Dependencies

Ray 1.7.0
Python 3.8.11
Latest install of `azure-cli`
macOS

### Reproduction script

`ray up azure.yml` where the yml can be the example yaml file

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by gramhagen**
## Why are these changes needed?

1. moves authentication for azure autoscaler to azure-identity package
2. quiets some http logging
3. provides better backwards compatibility for all azure sdk functions
4. updates azure sdk dependencies 
5. moves vm images to use the latest version to handle frequent deprecation of vm offer versions

## Related issue number

Closes #19523
Fixes #15274

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [X] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ijrsvt — COMMENTED** [review]
Overall looks good--just two comments :)

**Review by ijrsvt — APPROVED** [review]
One minor comment, but otherwise LGTM!

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by ijrsvt** [comment]
@gramhagen Can you rebase this on master? I'm unsure why CI is not wanting to build for this

**Comment by gramhagen** [comment]
bumping this, what needs to happen to get this merged? @ijrsvt

**Comment by ijrsvt** [comment]
@gramhagen Sorry! Can you rebase against master?

**Comment by franklsf95** [comment]
Bump

**Comment by gramhagen** [comment]
@ijrsvt Ian, I'm a bit lost on how to resolve these tests, any suggestions?

**Comment by ijrsvt** [comment]
Hmm @gramhagen, I'm not 100% sure what the best way is to reproduce this, but it looks like some timeout with pip installs? 
https://buildkite.com/ray-project/ray-builders-pr/builds/20494#fedc36da-6e58-4445-a381-6ebe19b3c5d8

**Comment by gramhagen** [comment]
merging again, hopefully that was due to aws outage?

**Comment by ijrsvt** [comment]
Hmm, I tried to make the hanging command print more output here: https://buildkite.com/organizations/ray-project/pipelines/ray-builders-pr/builds/20646/jobs/a6d7f7e9-d580-4fd4-bab7-3952a8666dfd/raw_log

It appears to be hanging on finding a version for `pyasn1-modules`. I'm trying to add some pinned dependencies in https://github.com/ray-project/ray/pull/20940

**Comment by gramhagen** [comment]
i expect pyasn1-modules is just the straw that broke the camels back, once pip starts trying to resolve different dependency versions it's super slow, and it looked like there were a few instances of that happening. pinning the dependencies is probably the right way to go, but it will be a bit tedious to find them all. is this replicable in a docker env?

**Comment by ijrsvt** [comment]
@gramhagen I'm not 100% sure of the exact docker env setup, but using these requirements.txt and `pip==21.0.1`.

Some possible resolutions: 
* Loosening the pinned requirements (i.e. using `package~=version` or `package>=version`)
* Removing unnecessary pinned requirements (from the ones added)

**Comment by ijrsvt** [comment]
Alright @gramhagen Sorry for the confusion and delays here, but after various attempts at pinning dependencies (https://github.com/ray-project/ray/pull/20940 & https://github.com/ray-project/ray/pull/21105), it looks like just updating pip was the solution #21111


I can't seem to push to your branch, but I ran tests with merging master here: 
https://github.com/ray-project/ray/pull/21121


Closes 
#20940 
#21105 
#21121

**Comment by gramhagen** [comment]
great news, thanks @ijrsvt !
trying agian🤞

**Pull request merged**
