### PR TITLE
[jobs] Fix recovery race condition in `JobManager`

### LINKED ISSUE #40062: [jobs] Race condition in `JobManager` between `_recover_running_jobs` and `submit_job`
There's a rare race condition that can cause jobs to be marked as `FAILED` with the following error message (reported by users):
```
2023-10-03 07:34:56,856	ERROR job_manager.py:654 -- Failed to get job supervisor for job raysubmit_6aDX39CVuKAHauRQ.
```

This can happen because `_recover_running_jobs` is run async as a task. If it starts running after `submit_job` adds a new job info to the internal KV, but before `submit_job` actually creates the job actor, `_monitor_job_internal` can run, fail to lookup the actor, and mark the job failed.

We can address this by waiting until `_recover_running_jobs` has run to accept job submissions.

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

There are multiple race conditions between `JobManager.submit_job` and `JobManager._recover_running_jobs` because the latter runs as an async task on the event loop. This can cause a duplicate monitoring task to be started for a job before the actor is event spawned. This has caused multiple issues:

- https://github.com/ray-project/ray/pull/34223
- https://github.com/ray-project/ray/issues/40062

This PR adds synchronization so `submit_job` will only run after `_recover_running_jobs` finishes (note that `_recover_running_jobs` is async and will exit after a single GCS read RPC, so this should have no practical impact).

## Related issue number

Closes https://github.com/ray-project/ray/issues/40062

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
Hmm I may be misunderstaing some parts, but is there a repro + test we can add, or is it purely a theoretical fix? 

I have 2 parts that I feel sketchy;

1. Currently `run_background_task(self._monitor_job(job_id))` starts `monitor_job` asynchronously, so although we have this event, there's still a possibility `_monitor_job_internal ` is triggered between Put job info <> actor creation?
2. This part of code
```
                if job_supervisor is None:
                    job_supervisor = self._get_actor_for_job(job_id)
                if job_supervisor is None:
                    if job_status == JobStatus.PENDING:
                        # Maybe the job supervisor actor is not created yet.
                        # We will wait for the next loop.
                        continue
```
should avoid the race you mentioned from the original issue (because we never overwrites the PENDING state to others until we create an actor iiuc)?

I am actually curious if it is just 

1. supervisor actor is removed somehow (killed, failed to start, or whatever) after it is added to the monitor loop.
3. monitor job "overwrites" the already failed job. It seems like the current logic allows to do it.

**Comment by edoakes** [comment]
@rkooo567 the race condition happens because the background task is _started_ for the pending job. The fix in this PR will avoid kicking off the `_monitor_internal` task for jobs between when their status is added as `PENDING` and the actor is started.

The `PENDING` check is not sufficient because what happens is the actor actually fails to be created (in the in the linked issue it was because of the runtime_env being invalid). So it passes that check, tries to get the actor, fails, and overwrites the status with the weird system error message.

So sequence of events is:

1. Constructor runs, schedules `_recover_running_jobs` task.
2. `submit_job` runs, marks the job `PENDING` then yields.
3. `_recover_running_jobs` runs, kicking off a `_monitor_internal` task for the job that's `PENDING`.
4. `submit_job` tries to create the actor, fails, and marks the job as `FAILED`.
5. `_monitor_internal` tries to get the actor, fails, and overwrites the status.

**Comment by rkooo567** [comment]
So, it looks like if a supervisor actor fails to start, I can easily reproduce the error message. Can you add a unit test? (maybe we can provide a bad runtime env to the supervisor actor). I could verify this PR fixes the issue. 

Regarding the problem, I have the impression the root cause is actually that we don't health check actor right after we create it, but we rely on monitor_internal which always calls `get_actor` first (which will always fail if actor fails to be created). In this case, isn't the right solution we just health check actor immediately to check if it is started or failed? For example, https://github.com/ray-project/ray/pull/40402. (and we should avoid overwriting the failed status message if it is already failed). 

Regarding the current fix, I could verify the fix, but I feel like there's still fundamental possibility of race. The reason why I feel this way is because "monitor_job" is a task, so theoretically it is still able to be created in the middle of PENDING <> actor creation (since we await on putting the PENDING status RPC). For example, I feel like the following scenario is possible. 

1. submit_job, await event.wait
2. _recover_running_jobs creates a task (not scheduled) _monitor_job and set event. 
3. _monitor_job scheduled and starts _monitor_job_internal. await on `self._job_info_client.get_status(job_id)`
4. submit_job puts PENDING info (and await on `new_key_added = await self._job_info_client.put_info`)
5. _monitor_job_internal returned and await on `job_info = await self._job_info_client.get_info(job_id)`
6. submit_job fails to create an actor
7. _monitor_job_internal returned from `job_info = await self._job_info_client.get_info(job_id)` and call `job_supervisor = self._get_actor_for_job(job_id)`. It fails (because actors didn't start) and writes the incorrect status.

**Review by rkooo567 — APPROVED** [review]
Since the current fix seems to work, I will leave it up to you which solution you chooses, but let's add a unit test before merging it!

**Comment by edoakes** [comment]
> 1. submit_job, await event.wait
> 2. _recover_running_jobs creates a task (not scheduled) _monitor_job and set event.
> 3. _monitor_job scheduled and starts _monitor_job_internal. await on `self._job_info_client.get_status(job_id)`
> 4. submit_job puts PENDING info (and await on `new_key_added = await self._job_info_client.put_info`)
> 5. _monitor_job_internal returned and await on `job_info = await self._job_info_client.get_info(job_id)`
> 6. submit_job fails to create an actor
> 7. _monitor_job_internal returned from `job_info = await self._job_info_client.get_info(job_id)` and call `job_supervisor = self._get_actor_for_job(job_id)`. It fails (because actors didn't start) and writes the incorrect status.

For a single job manager, this sequence of events cannot happen for a single `job_id` under the current solution. The reason it cannot happen is because `submit_job` can only run _after_ `_recover_running_jobs`, which means the job ID cannot be present in `self._job_info_client.get_all_jobs()`, so `_monitor_job_internal` will not be started for it (until it hits the "happy path" in `submit_job`).

Re: your proposed solution about health checking immediately after starting the actor, that is effectively what happens in this case (with a bad `runtime_env`, the `ActorCls.remote()` call fails immediately).

**Review by architkulkarni — APPROVED** [review]
Fix was discussed offline. Nice test!

**Pull request merged**
