### PR TITLE
[RLlib] Fix IMPALA/APPO when using multi GPU setup and Multi-Agent Env

### PR DESCRIPTION
**Pull request by RocketRider**
When I tried to run a APPO Training with more than one GPU and a Multi-Agent Env I got the following error:

```
Failure # 1 (occurred at 2023-05-08_06-54-37)
^[[36mray::CustomTFTrainerSearch.train()^[[39m (pid=1797305, ip=10.10.10.102, repr=CustomTFTrainerSearch)   File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 388, in train     raise skipped from exception_cause(skipped)
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 385, in train     result = self.step()
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 801, in step     results, train_iter_ctx = self._run_one_training_iteration()   File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 2842, in _run_one_training_iteration     results = self.training_step()
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/algorithms/appo/appo.py", line 372, in training_step     train_results = super().training_step()
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/algorithms/impala/impala.py", line 738, in training_step     self.update_workers_if_necessary(
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/algorithms/impala/impala.py", line 1165, in update_workers_if_necessary     "num_grad_updates_per_policy": {
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/algorithms/impala/impala.py", line 1166, in <dictcomp>     pid: local_worker.policy_map[pid].num_grad_updates   File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/utils/threading.py", line 24, in wrapper     return func(self, *a, **k)
  File "/home/ubuntu-vm/MyProject/MyProjectim/venv/lib/python3.9/site-packages/ray/rllib/policy/policy_map.py", line 104, in __getitem__     raise KeyError(
KeyError: "PolicyID 'default_policy' not found in this PolicyMap! IDs stored in this map: {'BTL'}." 
```

"BTL" is the policy_id but at the requested change it was overwrite by the "default_policy". The Code change is tested and now it is running as expected.
The default param policy_id= "default_policy" is hiding this issue. For Multi-Agent it is necessary to use the correct policy_id.

## Checks

- [ x ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- Testing Strategy
   - Tested Tune training on 2x 3090 GPU with Multi-Agent Env

### CODE REVIEW

**Comment by RocketRider** [comment]
@sven1977 Could you look into this change, as you are currently working on the APPO/IMPALA Implementation and did write the affected code.

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for this PR @RocketRider ,

The change looks sensible from my point of view, now we only need a unittest for it.
I looked through our tests and we don't have a _multi-gpu  mult-agent_ test.

Would you be willing to contribute one?

This can be a broken-down version of your own script that simply creates an instance of APPO with a multi-agent environment and multi GPU and then runs one training step.
The test should fail before your PR with the error you posted and succeed afterwards.

Let me know what you think! Cheers

**Comment by RocketRider** [comment]
@ArturNiederfahrenhorst 
Writing a test is easy. But I am not sure if the test server provides 2 GPUs.
The following test is failing without my change, and is passing with the change: 
https://github.com/ray-project/ray/blob/master/rllib/tests/test_supported_multi_agent.py

    def test_impala_multiagent_multi_gpu(self):
        check_support_multiagent("IMPALA", {"num_gpus": 2})

**Comment by ArturNiederfahrenhorst** [comment]
@RocketRider Thanks for the suggestion!  I can take over this PR.
I've added the test. I'll do some additional validation on a GPU cluster to validate.

**Comment by ArturNiederfahrenhorst** [comment]
@kouroshHakha I've confirmed manually that this test fails without the fix and succeeds with the fix.

**Review by ArturNiederfahrenhorst — APPROVED** [review]

**Review by kouroshHakha — APPROVED** [review]
looks good. Thank you both @RocketRider and @ArturNiederfahrenhorst. will merge once the tests pass.

**Pull request merged**
