### PR TITLE
[serve] Change Gradio integration to take a builder function to avoid serialization issues

### LINKED ISSUE #31161: [Serve] error running Gradio Serve example
### What happened + What you expected to happen

Running the example in this notebook https://maxpumperla.com/learning_ray/ch_11_ecosystem/ locally we see a strange pickle error that didn't come up before (we tested this on Ray 2.0) when running `serve run gradio_demo:app`, namely:

```
2022-12-16 12:13:34,989 INFO scripts.py:304 -- Deploying from import path: "gradio_demo:app".
2022-12-16 12:13:43,820 INFO worker.py:1535 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266 
(ServeController pid=94942) INFO 2022-12-16 12:13:46,439 controller 94942 http_state.py:132 - Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-f81802bedd5a4c7d6683582cee5bd36bda82264b61c4a7939f58d5a0' on node 'f81802bedd5a4c7d6683582cee5bd36bda82264b61c4a7939f58d5a0' listening on '127.0.0.1:8000'
Traceback (most recent call last):
  File "/Users/maxpumperla/code/learning_ray_public/venv/bin/serve", line 8, in <module>
    sys.exit(cli())
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/scripts.py", line 333, in run
    handle = serve.run(node, host=host, port=port)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/api.py", line 537, in run
    parameter_group, _blocking=_blocking, remove_past_deployments=True
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 37, in check
    return f(self, *args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 260, in deploy_group
    is_driver_deployment=deployment["is_driver_deployment"],
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 37, in check
    return f(self, *args, **kwargs)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/_private/client.py", line 459, in get_deploy_args
    ray_actor_options=ray_actor_options,
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/serve/config.py", line 381, in create
    cloudpickle.dumps(init_args),
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/maxpumperla/code/learning_ray_public/venv/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 627, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle Context objects
(HTTPProxyActor pid=94946) INFO:     Started server process [94946]
```

Of note is that running the gradio interface with `demo.launch()` works as expected, so it's not an issue with loading the AIR checkpoint etc.

To reproduce this, first run the training step and generate a checkpoint from [this notebook](https://github.com/maxpumperla/learning_ray/blob/main/notebooks/ch_11_ecosystem.ipynb) and then run this [gradio demo](https://github.com/maxpumperla/learning_ray/blob/main/notebooks/gradio_demo.py).

My hope is that this might just be a wonky dependency issue that's just not obvious. 

### Versions / Dependencies

! pip install "ray[air, serve]==2.2.0" "gradio==3.11.0" "requests==2.28.1"
! pip install "mlflow==1.30.0" "torch==1.12.1" "torchvision==0.13.1"

### Reproduction script

discussed above

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by zcin**
Signed-off-by: Cindy Zhang <cindyzyx9@gmail.com>

## Why are these changes needed?

New versions of Gradio make Gradio objects un-serializable in Ray. This makes it impossible to directly pass in a Gradio object to `GradioIngress`, so to avoid this the API is changed to accept a builder function that constructs the Gradio object on the Ray cluster.

## Related issue number

Closes #31161

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by sihanwang41** [comment]
The fix looks good to me. General question: does it mean we will not support Gradio 3.5 in this case?

**Review by sihanwang41 — APPROVED** [review]

**Comment by zcin** [comment]
> The fix looks good to me. General question: does it mean we will not support Gradio 3.5 in this case?

No, earlier versions should still be supported. We are just sidestepping the serialization issue by changing the API of our integration - functionality is still the same, the Gradio object is just built remotely on the cluster instead of locally to avoid serialization.

**Comment by zcin** [comment]
Test `linux://rllib:test_memory_leak_a3c` is flaky on master, seems unrelated.

**Comment by sihanwang41** [comment]
sorry, click wrong button....

**Pull request merged**
