### PR TITLE
[WIP] Test wheels/sched cls

### PR DESCRIPTION
**Pull request by ericl**
For https://github.com/ray-project/ray/pull/17221

### CODE REVIEW

**Comment by ericl** [comment]
https://buildkite.com/ray-project/periodic-ci/builds/625

**Comment by ericl** [comment]
Hmm @simon-mo it still failed. Do the post wheel tests need to pass for it to be uploaded?

**Comment by simon-mo** [comment]
🤦‍♂️  my bad not explaining well, can you close this PR and push an empty commit so the branch build (insetad of wheel build) will get triggered?

**Comment by simon-mo** [comment]
also you only need to wait for the "Wheels and Jars" build to finish, usually 10-20min

**Pull request closed without merging**
