### PR TITLE
[serve] Fix HTTP proxy controller namespace bug

### LINKED ISSUE #22265: [serve] Error calling serve.start(detached=True) on a local ray cluster
Repro:
`ray start --head`

Then run:
```python
import ray
ray.init(address='auto')

from ray import serve

serve.start(detached=True)

@serve.deployment(route_prefix="/hi")
def f(): pass

f.deploy()
```

Spits out errors:
```
(HTTPProxyActor pid=39296) INFO:     Started server process [39296]
(HTTPProxyActor pid=39296) Exception in callback <function LongPollClient._process_update.<locals>.chained at 0x7fc7f62e0670>
(HTTPProxyActor pid=39296) handle: <Handle LongPollClient._process_update.<locals>.chained>
(HTTPProxyActor pid=39296) Traceback (most recent call last):
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 682, in _connect
(HTTPProxyActor pid=39296)     controller = ray.get_actor(controller_name, namespace=controller_namespace)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
(HTTPProxyActor pid=39296)     return func(*args, **kwargs)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/worker.py", line 2152, in get_actor
(HTTPProxyActor pid=39296)     return worker.core_worker.get_named_actor_handle(name, namespace or "")
(HTTPProxyActor pid=39296)   File "python/ray/_raylet.pyx", line 1877, in ray._raylet.CoreWorker.get_named_actor_handle
(HTTPProxyActor pid=39296)     check_status(named_actor_handle_pair.second)
(HTTPProxyActor pid=39296)   File "python/ray/_raylet.pyx", line 173, in ray._raylet.check_status
(HTTPProxyActor pid=39296)     raise ValueError(message)
(HTTPProxyActor pid=39296) ValueError: Failed to look up actor with name 'SERVE_CONTROLLER_ACTOR'. This could because 1. You are trying to look up a named actor you didn't create. 2. The named actor died. 3. You did not use a namespace matching the namespace of the actor.
(HTTPProxyActor pid=39296)
(HTTPProxyActor pid=39296) During handling of the above exception, another exception occurred:
(HTTPProxyActor pid=39296)
(HTTPProxyActor pid=39296) Traceback (most recent call last):
(HTTPProxyActor pid=39296)   File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/long_poll.py", line 158, in chained
(HTTPProxyActor pid=39296)     callback(arg)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/http_proxy.py", line 237, in _update_routes
(HTTPProxyActor pid=39296)     self.prefix_router.update_routes(endpoints)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/http_proxy.py", line 133, in update_routes
(HTTPProxyActor pid=39296)     self.handles[endpoint] = self._get_handle(endpoint)
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/http_proxy.py", line 196, in get_handle
(HTTPProxyActor pid=39296)     return serve.api._get_global_client().get_handle(
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 75, in _get_global_client
(HTTPProxyActor pid=39296)     return _connect()
(HTTPProxyActor pid=39296)   File "/Users/eoakes/code/ray/python/ray/serve/api.py", line 684, in _connect
(HTTPProxyActor pid=39296)     raise RayServeException(
(HTTPProxyActor pid=39296) ray.serve.exceptions.RayServeException: There is no instance running on this Ray cluster. Please call `serve.start(detached=True) to start one.
```

Calling the HTTP endpoint also fails.

### PR DESCRIPTION
**Pull request by edoakes**
Closes https://github.com/ray-project/ray/issues/22265

This was caused by implicitly inferring the namespace from within the HTTP proxy when calling `get_handle`. This makes me think we really need to simplify the namespace handling logic.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
Nice! Can we follow up with a regression test case in test standalone?

**Comment by edoakes** [comment]
@mwtian this fixes a P0 bug in Serve, can we pick it into release please? LMK if I need to do something else.

**Comment by architkulkarni** [comment]
@edoakes As part of the new cherry pick process, the owner of the issue should make a cherry-pick PR to the release branch.  Can you do that?  If you're busy I'm also happy to do it

**Comment by edoakes** [comment]
Oh man, I got a bunch of merge conflicts due to the linter change. @mwtian should we cherry-pick the black formatting PR to the release branch as well?

**Comment by mwtian** [comment]
@edoakes one alternative is to make a release branch only change. Another which I'm proposing is to re-cut the branch this weekend. Will let you know how it goes.

**Comment by zhe-thoughts** [comment]
@edoakes @mwtian : A quick process comment: I think we should make a new PR for the cherry pick. Otherwise https://github.com/ray-project/ray/labels/1.11.0rc0-pick won't show it

**Comment by mwtian** [comment]
@edoakes @zhe-thoughts it was decided that we will not re-cut 1.11.0, so reformatting the change with the previous formatter is the only choice. Feel free to send the cherry pick PR to me (go/cherry-pick)!

**Pull request merged**
