### PR TITLE
[RLlib] Example for how to use custom GNN models based on TF-GNN

### PR DESCRIPTION
**Pull request by kk-55**
## Why are these changes needed?

There was no example/support for GNN models in RLlib. I've introduced a new `Graph` space (built upon `Dict` space) and added an example which shows how to set up an env with an obs in form of a graph. This dict-like obs stores the current state of a graph and gets converted into a `GraphTensor` (a composite tensor introduced in TF-GNN library). This `GraphTensor` then is the input for a custom GNN model based on the TF-GNN library. This library allows to build a wide variety of state-of-the-art GNNs.
The env and GNN in my example are for illustration purposes only (no deeper sense). More realistic examples might be small use cases of Shortest Path or Traveling Salesman Problem.

The PR is related to my [topic](https://discuss.ray.io/t/rllib-compatible-with-gnns-e-g-tf-gnn-graphtensor-or-spektral/8334?u=klausk55) in the discuss forum.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by kouroshHakha — COMMENTED** [review]
Hey @kk-55, Thanks for the contribution. This is absolutely amazing. Sorry I wasn't notified on this PR. The rllib team at anyscale is trying to reduce the burden of maintaining the examples and algorithms that we have in the code-base so that we can only focus on the core rllib core components. And as part of that effort we plan to move most of existing externally contributed examples / algorithms that uses rllib as the foundation to another repo that will require less maintenance. What we could do with this amazing PR is to turn it into a separate repo (maintained by yourself) and then link it in our ray documentations as an example or use-case and make it available to community. In this self-contained repository you can pin the specific dependencies + the rllib version that was used. It will also not be part of CI/CD pipeline that the whole ray ecosystem goes through. WDYT?

**Comment by kouroshHakha** [comment]
@kk-55 , awesome!

Here is my suggestion:

Create a separate repository under your own github account and put the files there. Please also include a requirements.txt file to let the community know the dependencies your code was tested with. Also include a comprehensive Readme.md to explain the architecture of your integration with RLlib. You can also optionally create CI/CD hooks to do some unittesting.

Once the repo is up, link the url here. I or someone else will create a doc PR that will redirect an example hyperlink on our doc pages to your repository.

Please note that if your example needs any feature changes to the core of RLlib framework, those changes have to be submitted as separate PRs to the main repo to get reviewed separately. We ideally do not want people to have to fork different versions of RLlib to be able to use externally contributed examples. As long as you develop on top of RLlib you do not need to push your new features to the main repo.

**Comment by kk-55** [comment]
Hey @kouroshHakha,

Did I understand it correctly?

> Create a separate repository under your own github account and put the files there. Please also include a requirements.txt file to let the community know the dependencies your code was tested with. Also include a comprehensive Readme.md to explain the architecture of your integration with RLlib. You can also optionally create CI/CD hooks to do some unittesting.

A separate repo w/o any ray/RLlib files, just the four additional source files in this PR?

> Please note that if your example needs any feature changes to the core of RLlib framework, those changes have to be submitted as separate PRs to the main repo to get reviewed separately. We ideally do not want people to have to fork different versions of RLlib to be able to use externally contributed examples. As long as you develop on top of RLlib you do not need to push your new features to the main repo.

I would say this is not the case here as I have not changed any file from the ray/RLlib framework. Correct or is this not what you mean?

**Comment by kouroshHakha** [comment]
> A separate repo w/o any ray/RLlib files, just the four additional source files in this PR?

Yes, Correct.

> I would say this is not the case here as I have not changed any file from the ray/RLlib framework. Correct or is this not what you mean?

Yes, Correct.

**Comment by kk-55** [comment]
> @kk-55 , awesome!
> 
> Here is my suggestion:
> 
> Create a separate repository under your own github account and put the files there. Please also include a requirements.txt file to let the community know the dependencies your code was tested with. Also include a comprehensive Readme.md to explain the architecture of your integration with RLlib. You can also optionally create CI/CD hooks to do some unittesting.
> 
> Once the repo is up, link the url here. I or someone else will create a doc PR that will redirect an example hyperlink on our doc pages to your repository.
> 
> Please note that if your example needs any feature changes to the core of RLlib framework, those changes have to be submitted as separate PRs to the main repo to get reviewed separately. We ideally do not want people to have to fork different versions of RLlib to be able to use externally contributed examples. As long as you develop on top of RLlib you do not need to push your new features to the main repo.

@kouroshHakha 
Here is the url to the [repo ](https://github.com/kk-55/tf-gnn-example-for-rllib.git) (no CI/CD hooks since I have no experience with such things). It's minimalistic but hopefully sufficient.
Please let me know when there is anything wrong or I have to add something more.

**Comment by kk-55** [comment]
> @kk-55 , awesome!
> 
> Here is my suggestion:
> 
> Create a separate repository under your own github account and put the files there. Please also include a requirements.txt file to let the community know the dependencies your code was tested with. Also include a comprehensive Readme.md to explain the architecture of your integration with RLlib. You can also optionally create CI/CD hooks to do some unittesting.
> 
> Once the repo is up, link the url here. I or someone else will create a doc PR that will redirect an example hyperlink on our doc pages to your repository.
> 
> Please note that if your example needs any feature changes to the core of RLlib framework, those changes have to be submitted as separate PRs to the main repo to get reviewed separately. We ideally do not want people to have to fork different versions of RLlib to be able to use externally contributed examples. As long as you develop on top of RLlib you do not need to push your new features to the main repo.

@kouroshHakha 
Here is the url to the [repo](https://github.com/kk-55/tf-gnn-example-for-rllib.git) (no CI/CD hooks since I have no experiences with such things). It's minimalistic but hopefully sufficient.
Please let me know when there is anything wrong or I have to add something more.

**Comment by kouroshHakha** [comment]
Awesome. I can link this repo in the rllib_contrib Readme.

**Comment by kouroshHakha** [comment]
Here is the PR that adds the link to the repo in the right place. 

https://github.com/ray-project/ray/pull/35516

I assume we can close the issue now?
https://github.com/ray-project/ray/pull/35516

**Pull request closed without merging**
