### PR TITLE
Add error details for failed jobs

### PR DESCRIPTION
**Pull request by alanwguo**
1. Add error details for failed jobs in the job list view and job detail view
2. Add error details for failed serve apps in the application detail view
3. Fix color of StatusChip for HTTPPRoxy detail page
4. Add max width for error details for Serve deployments

Error details for jobs
Screenshot 2023-05-23 at 4 23 01 PM
Screenshot 2023-05-23 at 4 23 05 PM
Screenshot 2023-05-23 at 4 32 21 PM

Http proxy detail page
Screenshot 2023-05-23 at 4 38 22 PM

Serve Application detail page
Screenshot 2023-05-23 at 4 38 11 PM

## Related issue number
partially addresses #35685

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by chaowanggg** [comment]
lgtm!

**Review by chaowanggg — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]
cc @scottsun94 for the UI design approval

**Review by architkulkarni — APPROVED** [review]
I'm not familiar with TSX, but the Job code looks reasonable and the screenshots look good and like what I would expect.

**Comment by scottsun94** [comment]
Can we reduce the width of status message column a bit? It seems that you have to expand to see the useful info for most of the time?  `Runtime_env setup failed: failed...` is enough?

**Comment by alanwguo** [comment]
Reduced width:
Screenshot 2023-05-23 at 5 12 51 PM

**Comment by scottsun94** [comment]
LGTM. Thanks!

**Comment by ArturNiederfahrenhorst** [comment]
@alanwguo I'm tracking this now, can you please create the pick after merging?

**Pull request merged**
