### PR TITLE
[CI] Pin aiohttp version to fix master branch

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
aiohttp 3.8.0 release broke our tests.
```
Traceback (most recent call last):
  File "/ray/python/ray/_private/services.py", line 1262, in start_dashboard
    import ray.dashboard.optional_deps  # noqa: F401
  File "/ray/python/ray/dashboard/optional_deps.py", line 8, in <module>
    import aiohttp.signals
ModuleNotFoundError: No module named 'aiohttp.signals'
```

ping for now, going to fix it soon.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Review by edoakes — APPROVED** [review]

**Comment by simon-mo** [comment]
i'll merge after confirming it works. ETA 30min

**Comment by edoakes** [comment]
@simon-mo looks like it's still failing.

**Comment by iycheng** [comment]
@simon-mo  I suspect it might be related to buildkite change. When I run the docker image locally, the failed tests actually passed

**Comment by simon-mo** [comment]
missed a file, the version was still 3.8.0 in some tests.

**Comment by jjyao** [comment]
Is it possible that we have a central place for defining aiohttp dependency?

**Comment by WangTaoTheTonic** [comment]
nice fix!

**Pull request merged**
