### PR TITLE
Store temporary files in subfolder of temp_dir

### LINKED ISSUE #4330: No session_* subfolder if temp_dir is specified
Currently if `temp_dir` is specified, the sockets and logs are directly stored there, and not in a `session_${DATE}_${PROCESS_ID}` subfolder. This may lead to logs being mixed from multiple runs and/or collisions for the socket files if the `temp_dir` is hardcoded in a script which is run multiple times.

cc @nileshtrip

### PR DESCRIPTION
**Pull request by pcmoritz**
fixes https://github.com/ray-project/ray/issues/4330

### CODE REVIEW

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by robertnishihara** [comment]
The command that the autoscaler prints to let you cat the monitor logs needs to be updated.

**Comment by suquark** [comment]
I can fix the autoscaler later.

**Comment by suquark** [comment]
@robertnishihara I tried to show the correct temporary path but I found it nasty. Currently, the autoscaler works more like a general autoscaling module rather than a ray-specific one (i.e. You can write anything in `head_start_ray_commands`). If I want to get the `temp_dir` provided by Ray, I have to parse the starting commands. It is undesirable because these parameters are not supposed to be parsed twice and someone should be able to access them from the running Ray instance instead of the scripts. It will bring us more problems if we want to get `redis_address` or some dynamic properties from the autoscaler.
So I would like to fix it with another PR which makes full use of the existing `Node` class (I have created some PRs like #4383 to improve `Node`). What I expect to see is that Ray itself serves as an autoscaling tool since it is a distributed framework, where we can use instances of `Node` to control the global state, temporary files and resources for a computing task.

**Comment by suquark** [comment]
Closed for #4605

**Pull request closed without merging**
