### PR TITLE
[Autoscaler][hotfix] Remove additionalProperties from available_node_types schema

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

Hot fix because in some cases additionalProperties in the available_node_types schema breaks validation. It's unclear why or when, but it seems to be prevalent and not caught by unit tests.  

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by wuisawesome** [comment]
cc @alanwguo

**Comment by ericl** [comment]
What's the actual error? I think we really want to keep this false.

**Comment by alanwguo** [comment]
@ericl, traceback included

This is a schema syntax error. I don't think `additionalProperties` can be used inside of `patternProperties`. The `additionalProperties` on the outside might be enough?

https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/worker.py", line 920, in custom_excepthook
    worker_id = global_worker.worker_id
AttributeError: 'Worker' object has no attribute 'worker_id'

Original exception was:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/monitor.py", line 356, in <module>
    redis_password=args.redis_password)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/monitor.py", line 53, in __init__
    self.load_metrics)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 61, in __init__
    self.reload_config(errors_fatal=True)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 300, in reload_config
    raise e
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/autoscaler/autoscaler.py", line 281, in reload_config
    validate_config(new_config)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/autoscaler/util.py", line 57, in validate_config
    jsonschema.validate(config, schema)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/jsonschema/validators.py", line 540, in validate
    cls.check_schema(schema)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/jsonschema/validators.py", line 83, in check_schema
    raise SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: False is not of type 'object'

Failed validating 'type' in schema['properties']['properties']['additionalProperties']['properties']['patternProperties']['additionalProperties']['properties']['properties']['additionalProperties']:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'default': {},
     'definitions': {'positiveInteger': {'minimum': 0, 'type': 'integer'},
                     'positiveIntegerDefault0': {'allOf': [{'$ref': '#/definitions/positiveInteger'},
                                                           {'default': 0}]},
                     'schemaArray': {'items': {'$ref': '#'},
                                     'minItems': 1,
                                     'type': 'array'},
                     'simpleTypes': {'enum': ['array',
                                              'boolean',
                                              'integer',
                                              'null',
                                              'number',
                                              'object',
                                              'string']},
                     'stringArray': {'items': {'type': 'string'},
                                     'minItems': 1,
                                     'type': 'array',
                                     'uniqueItems': True}},
     'dependencies': {'exclusiveMaximum': ['maximum'],
                      'exclusiveMinimum': ['minimum']},
     'description': 'Core schema meta-schema',
     'id': 'http://json-schema.org/draft-04/schema#',
     'properties': {'$schema': {'format': 'uri', 'type': 'string'},
                    'additionalItems': {'anyOf': [{'type': 'boolean'},
                                                  {'$ref': '#'}],
                                        'default': {}},
                    'additionalProperties': {'anyOf': [{'type': 'boolean'},
                                                       {'$ref': '#'}],
                                             'default': {}},
                    'allOf': {'$ref': '#/definitions/schemaArray'},
                    'anyOf': {'$ref': '#/definitions/schemaArray'},
                    'default': {},
                    'definitions': {'additionalProperties': {'$ref': '#'},
                                    'default': {},
                                    'type': 'object'},
                    'dependencies': {'additionalProperties': {'anyOf': [{'$ref': '#'},
                                                                        {'$ref': '#/definitions/stringArray'}]},
                                     'type': 'object'},
                    'description': {'type': 'string'},
                    'enum': {'minItems': 1,
                             'type': 'array',
                             'uniqueItems': True},
                    'exclusiveMaximum': {'default': False,
                                         'type': 'boolean'},
                    'exclusiveMinimum': {'default': False,
                                         'type': 'boolean'},
                    'format': {'type': 'string'},
                    'id': {'format': 'uri', 'type': 'string'},
                    'items': {'anyOf': [{'$ref': '#'},
                                        {'$ref': '#/definitions/schemaArray'}],
                              'default': {}},
                    'maxItems': {'$ref': '#/definitions/positiveInteger'},
                    'maxLength': {'$ref': '#/definitions/positiveInteger'},
                    'maxProperties': {'$ref': '#/definitions/positiveInteger'},
                    'maximum': {'type': 'number'},
                    'minItems': {'$ref': '#/definitions/positiveIntegerDefault0'},
                    'minLength': {'$ref': '#/definitions/positiveIntegerDefault0'},
                    'minProperties': {'$ref': '#/definitions/positiveIntegerDefault0'},
                    'minimum': {'type': 'number'},
                    'multipleOf': {'exclusiveMinimum': True,
                                   'minimum': 0,
                                   'type': 'number'},
                    'not': {'$ref': '#'},
                    'oneOf': {'$ref': '#/definitions/schemaArray'},
                    'pattern': {'format': 'regex', 'type': 'string'},
                    'patternProperties': {'additionalProperties': {'$ref': '#'},
                                          'default': {},
                                          'type': 'object'},
                    'properties': {'additionalProperties': {'$ref': '#'},
                                   'default': {},
                                   'type': 'object'},
                    'required': {'$ref': '#/definitions/stringArray'},
                    'title': {'type': 'string'},
                    'type': {'anyOf': [{'$ref': '#/definitions/simpleTypes'},
                                       {'items': {'$ref': '#/definitions/simpleTypes'},
                                        'minItems': 1,
                                        'type': 'array',
                                        'uniqueItems': True}]},
                    'uniqueItems': {'default': False, 'type': 'boolean'}},
     'type': 'object'}

On instance['properties']['available_node_types']['patternProperties']['.*']['properties']['additionalProperties']:
    False
```

**Comment by alanwguo** [comment]
actually, since `patternProperties` is `.*`, you could just use additionalProperties right?

**Comment by ericl** [comment]
I see. That's uh, interesting that it validates in OSS though. Is there some json schema version difference?

**Comment by alanwguo** [comment]
the session where I got this error was using json-schema `3.2.0`

**Comment by alanwguo** [comment]
could be related to draft 4 vs draft 7. I noticed the error message shows draft 4... What version of jsonschema is used in the autoscaler monitor process? Should it be the same python env that's set in the bashrc?

**Review by ericl — APPROVED** [review]

**Comment by wuisawesome** [comment]
I also have `3.2.0` so I have no clue what's wrong. This is pretty harmless to merge for now though.

**Pull request merged**
