### PR TITLE
Update build rules and patches for darwin_arm64 platform.

### PR DESCRIPTION
**Pull request by gjoliver**
Changes include:

Update nelhage/rules_boost package from current version (08/5/2020) to 5/27/2021 version.
Remove rules_boost-undefine-boost_fallthrough.patch, since BOOST_FALLTHROUGH seems to be defined now.
Minor changes to rules_boost-windows-linkopts.patch to use default condition to add -lpthread flag for all platforms.
Add darwin_arm64 config to BUILD files for lib civetweb pulled in via prometheu dependency.

## Why are these changes needed?

Build fixes for Apple M1 laptop.

## Related issue number

#16621

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [*] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by gjoliver** [comment]
Let's see if the CI tests pass.

**Review by wuisawesome — APPROVED** [review]
I'm so excited for this to work

**Comment by gjoliver** [comment]
don't merge until the tests pass :)

**Comment by wuisawesome** [comment]
```


bazel-out/k8-fastbuild/bin/_virtual_includes/ray_api/boost/throw_exception.hpp:23:10: fatal error: boost/assert/source_location.hpp: No such file or directory
--
  | 23 \| #include <boost/assert/source_location.hpp>
  | \|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | compilation terminated.
  | Target //:example failed to build

```

ripperoni, looks like we'll need some other changes?

**Comment by gjoliver** [comment]
huh ... it's ok, we will get there 😮‍💨

**Comment by gjoliver** [comment]
huh, windows build is actually working now. the 2 tests failed are both timeouts that have been failing all day.

**Comment by gjoliver** [comment]
finally all green. I even fixed a bunch of deprecation warnings caused by boost/bind.hpp.
ready to be merged.

**Comment by pcmoritz** [comment]
Great work, really glad to see this!

**Pull request merged**
