### PR TITLE
Fix log monitor issue.

### PR DESCRIPTION
**Pull request by rkooo567**
## Related issue number

https://github.com/ray-project/ray/issues/13181#issuecomment-819495217

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Hey @richardliaw Is it okay to pick this up for the new release? It is a very simple fix, and many people said they've seen the issue; https://github.com/ray-project/ray/issues/13181#issuecomment-819495217

**Comment by richardliaw** [comment]
change looks OK to pick

**Comment by rkooo567** [comment]
@richardliaw The serve failure should be unrelated (but I can run again if you are worried). Can you approve the PR?

**Review by richardliaw — APPROVED** [review]

**Comment by amogkam** [comment]
@rkooo567 can you merge this? I can pick after.

**Comment by rkooo567** [comment]
Buildkite build image is failing commonly in the PR build, so they seem to be unrelated. The windows serve test should be unrelated. Merging it.

**Pull request merged**
