### PR TITLE
[spark] Fix Ray-on-Spark cluster crashing bug when user cancels cell execution

### PR DESCRIPTION
**Pull request by WeichenXu123**
## Why are these changes needed?

Fix Ray-on-Spark cluster crashing bug when user cancels cell execution:

When interrupting ray.get calls inside Databricks notebooks, this crashes the entire notebook session. Quick repro: on a ML 15.3 cluster, run this cell to kick off a bunch of async Ray tasks:

```
import ray
from ray.util.spark import setup_ray_cluster

setup_ray_cluster(min_worker_nodes=1, max_worker_nodes=1)

@ray.remote
def f():
  import time
  time.sleep(100)

pending = [f.remote() for _ in range(10)]
```
Then, run the following cell. After it starts, interrupt the cell execution and re-run the cell:

```
ray.get(f.remote())
```
The second call will hang and if you try to interrupt / retry you’ll get Fatal error: The Python kernel is unresponsive. This causes the notebook to lose all session state / restarts the Ray cluster.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Nice fix! Is it possible to also add a unit test?

**Comment by WeichenXu123** [comment]
CC @ericl Could you enable CI run ?

**Comment by ericl** [comment]
@richardliaw can you help weichen out?

**Comment by WeichenXu123** [comment]
CC @jjyao

**Comment by richardliaw** [comment]
@can-anyscale anything we can do to unblock?

**Comment by can-anyscale** [comment]
the newly added test fails on CI: https://buildkite.com/ray-project/microcheck/builds/3629#01910c76-2f89-4c15-bfc6-484172058912/184-3104

**Comment by WeichenXu123** [comment]
@richardliaw @can-anyscale PR is ready!

**Comment by can-anyscale** [comment]
thanks, i enabled auto-merge; it will merge automatically once the test is green

**Pull request merged**
