### PR TITLE
Revert "[WIP] CPU/memory usage per func class"

### PR DESCRIPTION
**Pull request by krfricke**
Reverts ray-project/ray#31234

Runtime env tests broke at this point. However, they might be unrelated. Opening revert PR to check if this resolves the issues.

### CODE REVIEW

**Comment by krfricke** [comment]
@rkooo567 runtime env tests in windows seem to pass with this revert

**Comment by architkulkarni** [comment]
@rkooo567 It looks like the failure is caused by printing the `serialized runtime env` which could contain sensitive info.  For consistency with the strategy here https://github.com/ray-project/ray/pull/29985, maybe we can print the runtime env only if the debug flag is on.

**Review by architkulkarni — APPROVED** [review]

**Comment by architkulkarni** [comment]
`test_metrics_agent` also [passed](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1653#018552de-800d-4103-b553-6a52ec23988f/1748-2075) on this PR, but is broken on master.

**Comment by architkulkarni** [comment]
It looks like Sang is out of office, so I'll go ahead and merge this to fix master CI

**Pull request merged**
