### PR TITLE
Fix the incorrect serialization behavior with pickle

### PR DESCRIPTION
**Pull request by suquark**
## Related issue number

related to #5856

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by richardliaw** [comment]
Can you add a test for this?

**Comment by pcmoritz** [comment]
Thanks Ryans, the fix looks good to me! Let's also add a test :)

**Comment by suquark** [comment]
@pcmoritz I have added tests (including pickle tests for custom_serializers)

**Comment by suquark** [comment]
A bug that prevents using pickle with custom serializer is also fixed.

**Comment by pcmoritz** [comment]
@suquark Thanks! Actually, you cannot combine `use_pickle` inside of register_class with specifying a serializer or deserializer. The `use_pickle` argument for register_class is different from the one for ray.init (the former means `use pickle to serialize this particular class, in which case it doesn't make sense to specify a custom serializer/deserializer, the latter means `use pickle globally for everything). So you just need to test if `use_pickle` in register_class can be combined with the global one.

**Comment by pcmoritz** [comment]
Do you want to update the test?

**Comment by suquark** [comment]
oh, this is a bit confusing. I think logically they should work in the same way, maybe 
we should treat `use_pickle=True` as the default value of `use_pickle` in `register_custom_serializer`. Do you agree with this? @pcmoritz

**Comment by suquark** [comment]
oops, I understand what you mean. I will change the tests

**Review by pcmoritz — APPROVED** [review]
This is great, thanks for fixing it :)

**Pull request merged**
