### PR TITLE
[train] Turn off TF autosharding internally

### LINKED ISSUE #19324: [train] Better TF Autosharding Usability
To use Ray Datasets properly with Ray SGD and Tensorflow MultiWorkerMirroredStrategy, TF autosharding needs to be disabled. Currently, this is left to the user to handle, but SGD should handle this internally.

### PR DESCRIPTION
**Pull request by jwyyy**
## Why are these changes needed?

This PR disables TF autosharding internally but provides users with an option to turn it on.

## Related issue number

Closes #19324.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
@amogkam @matthewdeng

**Comment by jwyyy** [comment]
Two failed tests were due to network error. The rest seems okay.

**Review by amogkam — COMMENTED** [review]
@jwyyy do you mind also updating this section in the docs https://docs.ray.io/en/latest/train/user_guide.html#distributed-data-ingest-ray-datasets? I think we can just remove the warning.

**Comment by jwyyy** [comment]
Hi @amogkam, just removed the warning. I realize the section only contains a PyTorch example. Should we include a TF example for completion? (But `to_tf()` behavior is consistent with `to_torch()`'s with this PR. The TF example may not add too much value.)

**Comment by amogkam** [comment]
Thanks @jwyyy! yeah if you're up for it we add a tensorflow example in a separate tab. I agree it can pretty much just be the same code with to_tf instead of to_torch

**Comment by jwyyy** [comment]
> Thanks @jwyyy! yeah if you're up for it we add a tensorflow example in a separate tab. I agree it can pretty much just be the same code with to_tf instead of to_torch

No problem! I can add an TF example shortly 😄

**Comment by jwyyy** [comment]
Close this PR due to changes in the implementation plan.

**Pull request closed without merging**
