### PR TITLE
Fix high CPU usage in object manager due to O(n^2) iteration over active pulls list

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

We discovered while testing object spilling that the current pull manager iterates over the entire list of active pull requests for each new pull request. This leads to O(n^2) CPU usage with respect to the number of object dependencies in Ray, causing the cluster to grind to a halt.

### CODE REVIEW

**Comment by ericl** [comment]
cc @wuisawesome we should probably pick this into 1.2 since it causes workloads with lots of objects to grind to a halt

**Review by wuisawesome — APPROVED** [review]

**Comment by wuisawesome** [comment]
Sounds good, can one of you add it to the tracker and shepherd it?

**Review by stephanie-wang — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@ericl Lint failures are there.

**Comment by wuisawesome** [comment]
Lint :(

**Pull request merged**
