### PR TITLE
[Lint] Run `clang-format` via `scripts/format.sh` from `ci.sh`

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Currently in `ci.sh`, lint has logic to
1)  Format all script files, e.g. all Python files, not just the changed lines.
2)  Format changed C++ lines with clang-format

(1) seems unnecessary since only changed lines need to be formatted. (2) duplicates logic from `format.sh`. This change uses the default way to call `format.sh` from `ci.sh`, to avoid both issues above.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — CHANGES_REQUESTED** [review]
^

**Review by ericl — CHANGES_REQUESTED** [review]
--all is needed

**Comment by mwtian** [comment]
With `--all`, some existing C++ files will be reformatted: https://buildkite.com/ray-project/ray-builders-pr/builds/16434#4f566ca1-bd9e-43ed-ab2e-e2faf4c27fe5/420-465. Is this ok?

**Comment by mwtian** [comment]
Sounds good. Btw delta can be printed with `FORMAT_SH_PRINT_DIFF=1`.

**Pull request closed without merging**
