### PR TITLE
COPY in wheel in user space so don't even need sudo in the first place.

### LINKED ISSUE #12058: Wheel builds failing
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
master on Travis
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

`LINUX_WHEELS=1 LINUX_JARS=1` are failing to build on Travis.
The failures started with https://github.com/ray-project/ray/commit/9920933e318986cfe6cd8a8fad12b1d8b4490917, ~though it looks like the failures might be unrelated to the commit itself. https://github.com/ray-project/ray/commit/90574b66cce07f8f4fabe99bee6ff6419c097a0b appears to be aimed at fixing the problem by pinning aiohttp.~

What's interesting is that https://github.com/ray-project/ray/commit/8609e2dd90e78cfc7e95f453ad7eb9f17a74bcb7 changed the wheel build from erroring out to failing normally, apparently incidentally. It's unclear why that happened (and it might not matter).
(That's the only real reason for creating this issue, noting that fact in case it turns out to be a clue.)

https://github.com/ray-project/ray/commit/bea0031491876ee8b1fd3057508041a5a5819a74 was meant to fix the build but doesn't appear to have done so.

After further investigation, this does have to do with https://github.com/ray-project/ray/commit/9920933e318986cfe6cd8a8fad12b1d8b4490917 after all. The current error is:
```
{"stream":"Successfully installed ray-1.1.0.dev0\n"}
{"stream":"\u001b[91m/bin/sh: 1: sudo: not found\n\u001b[0m"}
{"errorDetail":{"code":127,"message":"The command '/bin/sh -c $HOME/anaconda3/bin/pip --no-cache-dir install `basename $WHEEL_PATH`[all] \u0026\u0026 sudo rm `basename $WHEEL_PATH`' returned a non-zero code: 127"},"error":"The command '/bin/sh -c $HOME/anaconda3/bin/pip --no-cache-dir install `basename $WHEEL_PATH`[all] \u0026\u0026 sudo rm `basename $WHEEL_PATH`' returned a non-zero code: 127"}
```
It's unclear why `sudo` fails here and not elsewhere.

### PR DESCRIPTION
**Pull request by dHannasch**
## Why are these changes needed?

I couldn't sworn someone already created a pull request to resolve https://github.com/ray-project/ray/issues/12058 (something about allowing the rm to fail?), but I don't see it now.

Rather than try to figure out why we can't sudo, this COPYs in the wheel in user space so we don't need sudo.
Unfortunately, the RAY_UID and RAY_GID were set way back in the base-deps Dockerfile, and I don't see a way to retrieve the current user ID in a Dockerfile for a --chown. Which is weird, it seems like an obvious need, to be able to COPY in a file that the current user owns.
## Related issue number

https://github.com/ray-project/ray/issues/12058
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by amogkam** [comment]
Thanks for making this PR @dHannasch! @simon-mo could you take a look at this?

**Comment by richardliaw** [comment]
Hmm, is this supposed to fix the linux wheel build? seems like there's uid issue

**Comment by dHannasch** [comment]
> Hmm, is this supposed to fix the linux wheel build? seems like there's uid issue

Yeah, this was intended to close https://github.com/ray-project/ray/issues/12058. Looks like this might be superseded soon by https://github.com/ray-project/ray/pull/12119.

**Comment by ijrsvt** [comment]
@dHannasch If #12119 works, I think we should still keep the part where we copy in the wheel as the `ray` user!

**Comment by ijrsvt** [comment]
@dHannasch any updates on this?

**Comment by dHannasch** [comment]
@ijrsvt Unfortunately, this is not going to work without upgrading Docker, and I haven't figured out how to upgrade Docker (https://github.com/ray-project/ray/pull/12182).

**Comment by dHannasch** [comment]
Current status: with the new version of Docker, we are copying in the file in user space, and becoming that user...but the `rm` still fails. It's baffling.
```
{"stream":"\u001b[91mrm: cannot remove 'ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl': Permission denied\n\u001b[0m"}
{"errorDetail":{"code":1,"message":"The command '/bin/sh -c $HOME/anaconda3/bin/pip --no-cache-dir install `basename $WHEEL_PATH`[all] \u0026\u0026 rm `basename $WHEEL_PATH`' returned a non-zero code: 1"},"error":"The command '/bin/sh -c $HOME/anaconda3/bin/pip --no-cache-dir install `basename $WHEEL_PATH`[all] \u0026\u0026 rm `basename $WHEEL_PATH`' returned a non-zero code: 1"}
```

**Comment by ijrsvt** [comment]
@dHannasch Hmm, I'm not really sure why this keeps breaking? Does the simple `sudo rm ` work now?

**Comment by dHannasch** [comment]
> Does the simple `sudo rm ` work now?

Oh, certainly, but if we still need to `sudo` then clearly something's wrong somewhere, right?

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
