### PR TITLE
[Core] Remove actor deletion upon job termination

### PR DESCRIPTION
**Pull request by rkooo567**
Signed-off-by: SangBin Cho <rkooo567@gmail.com>

## Why are these changes needed?

There's a feature to remove all actor information 5m after the job is terminated. We will remove this feature for 2 reasons.

1. This feature never worked
```
      [this](std::function<void(void)> fn, boost::posix_time::milliseconds delay) {
        boost::asio::deadline_timer timer(main_service_);
        timer.expires_from_now(delay);
        timer.async_wait([fn](const boost::system::error_code &error) {
          if (error != boost::asio::error::operation_aborted) {
            fn();
          } else {
            RAY_LOG(WARNING)
                << "The GCS actor metadata garbage collector timer failed to fire. This "
                   "could old actor metadata not being properly cleaned up. For more "
                   "information, check logs/gcs_server.err and logs/gcs_server.out";
          }
        });
      },
```
The timer is GC'ed as soon as this method is finished, so this callback was never invoked. That said, this feature never worked anyway. 
2. For the actual garbage collection, we already have the logic to clean the dead actor metadata when we have more than 10K dead actors cached. So this feature is redundant. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Note: This is the only part that the timer was used incorrectly.

**Comment by rkooo567** [comment]
Fixing build errors.. will ping you guys when it is ready

**Comment by rkooo567** [comment]
it is ready for the review

**Comment by ollie-iterators** [comment]
The documentation bug could be fixed by merging in the recent changes

**Review by rickyyx — APPROVED** [review]
Nice, great clean-up. 

<div><br/>via <a href="https://giphy.com/matthewjocelyn/">matthewjocelyn</a> on <a href="https://giphy.com/gifs/matthewjocelyn-halloween-zombie-undead-3o85xr89frMOGSvSTK">GIPHY</a></div>

**Pull request merged**
