### PR TITLE
[Client] Add gRPC Keep-Alive messages

### LINKED ISSUE #15636: [client] Ray Client timeout
### What is the problem?
* Ray Client times out after ~6 minutes of being idle.
* Possible solution is to use [gRPC Keep Alive](https://github.com/grpc/grpc/blob/master/doc/keepalive.md)

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
* This prevents the Ray Client connection from failing during idle periods.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Nice!

**Comment by AmeerHajAli** [comment]
Looks good. Is it possible to add a test for the > 350S case?

**Comment by ijrsvt** [comment]
@AmeerHajAli I'm not sure the best way to test the timeout behavior. This sort of test requires setting up a proxy for the client server connection to go over. This is rather heavy weight.

**Comment by AmeerHajAli** [comment]
Makes sense, is it at least possible to test manually?

**Review by AmeerHajAli — APPROVED** [review]

**Comment by ijrsvt** [comment]
@AmeerHajAli I have not been able to get the setup working to manually test it, but I did do some cursory packet inspection to check if keep-alive messages were sent.

**Pull request merged**
