### PR TITLE
Make binbacking prioritize nodes better

### LINKED ISSUE #19124: [Bug] [Autoscaler] Autoscaler can start unnecessary nodes due to poor bin packing heuristic ordering
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

When running the repro script underneath that creates 

1 placement group with 31 CPUs + 1 GPU

head node: 16 CPUs
worker nodes 1 GPU + 16 CPUS

we are supposed to get 1 head node + 1 gpu node.

This is the case when running Ray 1.6, but in Ray 1.7, it starts one more CPU node unnecessary.

1.6 ray status
```
Node status
---------------------------------------------------------------
Healthy:
 1 head_node
 1 gpu_node
Pending:
 (no pending nodes)
Recent failures:
 (no failures)
```

1.7 ray status
```
Node status
---------------------------------------------------------------
Healthy:
 1 head_node
 1 gpu_node
 1 cpu_node
Pending:
 (no pending nodes)
Recent failures:
 (no failures)
```

### Reproduction script

Script
```python3
import time

import ray
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group
)


@ray.remote(num_cpus=1)
class Worker(object):
    def __init__(self, i):
        self.i = i

    def work(self):
        time.sleep(0.1)
        print("work ", self.i)


@ray.remote(num_cpus=1, num_gpus=1)
class Trainer(object):
    def __init__(self, i):
        self.i = i

    def train(self):
        time.sleep(0.2)
        print("train ", self.i)


def main():
    ray.init(address="auto")
             # cluster_env="jun-julia-working-2:1")

    bundles = [{"CPU": 1, "GPU": 1}]
    bundles += [{"CPU": 1} for _ in range(30)]

    pg = placement_group(bundles, strategy="PACK")

    ray.get(pg.ready())

    workers = [Worker.options(placement_group=pg).remote(i) for i in range(30)]

    trainer = Trainer.options(placement_group=pg).remote(0)

    while True:
        ray.get([workers[i].work.remote() for i in range(30)])
        ray.get(trainer.train.remote())



if __name__ == "__main__":
    main()

```

Env
```yaml
base_image: "anyscale/ray-ml:pinned-nightly-py37"
debian_packages: []

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  # - pip install -U https://ray-wheels.s3.us-west-2.amazonaws.com/releases/1.7.0/2367a2cb9033913b68b1230316496ae273c25b54/ray-1.7.0-cp37-cp37m-manylinux2014_x86_64.whl
  # 1.6
  # - pip install -U ray==1.6
  # master
  - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip3 install -U ray[default]

```

Cluster
```yaml
cloud_id: {{env["ANYSCALE_CLOUD_ID"]}}
region: us-west-2

aws:
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 500

head_node_type:
    name: head_node
    instance_type: m5.4xlarge

worker_node_types:
    - name: cpu_node
      instance_type: m5.4xlarge
      min_workers: 0
      max_workers: 10
      use_spot: false
    - name: gpu_node
      instance_type: g3.4xlarge
      min_workers: 0 
      max_workers: 10
      use_spot: false

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sasha-s**
Make binpacking prefer nodes that match multiple
resource types.

Without this change, we are launching unneeded nodes in cases similar to

-----
1 placement group with 31 CPUs + 1 GPU

head node: 16 CPUs
worker nodes 1 GPU + 16 CPUS
-----

Also, made binpacking order resource demands from more complex to simpler ones, followed by the demand size (from largest to smallest).

Fixes #19124 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
I thought the original issue wasn't this, but that the "CPU-only" bundle got bin-packed first. So regardless of the scoring, Ray would decide to launch a new CPU node if it considered the CPU-only bundle first, and then only after realize we needed a GPU node. By that time, it's too late and we already added a CPU node, hence the redundant allocation.

But if we tried to pack more complex (e.g., GPU+CPU) requests first, the GPU node would get allocated first, and the CPUs would get packed into the GPU node.

**Comment by AmeerHajAli** [comment]
> I don't think this solves the issue entirely though. I ran the following unit test on master and on this branch:
> 
> ```
> def test_bug():
>     TYPES = {
>         "cpu": {
>             "resources": {
>                 "CPU": 16,
>             },
>             "max_workers": 10,
>         },
>         "gpu": {
>             "resources": {
>                 "CPU": 16,
>                 "GPU": 1,
>             },
>             "max_workers": 10,
>         },
>     }
>     print("NODES TO ADD:")
>     print(
>         get_nodes_for(TYPES, {}, "cpu", 9999, ([{"GPU": 1, "CPU": 1}] + [{"CPU": 1}] * 30)))
> ```
> 
> On master, I got `{'gpu': 1, 'cpu': 2}`. On this branch I got `{'gpu': 1, 'cpu': 1}`. But isn't the optimal solution just `{'gpu': 1}`? (since the head node type = "cpu" has 16 CPUs already).

Dont you need to pass a non empty dict for the second argument for it to know the available resources of the head node?

**Comment by ericl** [comment]
Oh I stand corrected-- seems get_nodes_for() assumes all existing nodes are full. So the output is indeed right.

**Review by ericl — APPROVED** [review]
LGTM, just a suggestion on the sort key

**Comment by AmeerHajAli** [comment]
I still feel like there is some unexpected behavior. Please see me comment. I hope I am missing something.

**Comment by sasha-s** [comment]
> I still feel like there is some unexpected behavior. Please see my comment. I hope I am missing something.

I think the new code is an improvement in typical cases.
We could definitely do better (but that would be more involved).

**Review by DmitriGekhtman — APPROVED** [review]
lgtm, 
left a nit about sets vs. dicts

**Comment by DmitriGekhtman** [comment]
cc @wuisawesome -- this is the heuristic change I mentioned earlier.
Specifically this was the issue --
https://github.com/ray-project/ray/issues/19124#issuecomment-937442919
The change in this in PR made the heuristic closer to what you were describing -- prioritize bigger nodes that get filled, where bigger means satisfying more resource types.

**Pull request merged**
