### PR TITLE
Add a classic yet small-sized ML dataset for demo/documentation/testing

### PR DESCRIPTION
**Pull request by jianoaix**
## Why are these changes needed?

To facilitate easy demo/documentation/testing with realistic, small-sized yet ML-familiar data. Have it as a source file with code will make it self-contained, i.e. after user "pip install" Ray, they are all set to run it.

IRIS is a great fit: super classic ML dataset, simple schema, only 150 rows.

## Related issue number

#23088

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by clarkzinzow — APPROVED** [review]
Nice, IRIS is a great choice!

For the location of the data, could you put it under `ray/data/examples/data/`? I don't think that this should be a top-level `testdata` directory, and this data is going to be used in examples, so I think nesting the data directory under `examples` makes more sense.

**Comment by zhe-thoughts** [comment]
@maxpumperla @pcmoritz Take a quick look? Thanks

**Comment by pcmoritz** [comment]
Can we integrate this end-to-end into the docs? It is very hard to give any comments/make suggestions for improvements if only the dataset is committed.

**Comment by zhe-thoughts** [comment]
@clarkzinzow you are right. My bad -- I misread the PR description and thought this is the example code

**Comment by clarkzinzow** [comment]
@zhe-thoughts No worries! 😄

**Comment by jianoaix** [comment]
Yes, this is just adding a dataset that can be used in the code of Getting Started or other places.

What to review:
- Is a good data example? I think we are on the same page that we want simple/small but realistic dataset which sounds familiar to people.
- Is it in the location we want? I think I agree Clark's feedback here that we should refrain from adding more top level directory, and the existing examples/ sounds good.

Next steps:
- Add example code (which will live in the same directory of this dataset) where we may do something like this to show data loading/saving:
```
ds = ray.data.read_parquet("iris.parquet")
ds.show()
....
ds2 = ds.map(lambda)
ds2.show()
ds2.write_parquet("...")
```
- Revamp the documentation (Getting Started) with references to the example code to explain features/APIs of dataset

**Pull request merged**
