### PR TITLE
[Datasets] Fix test_dataset_map.py

### PR DESCRIPTION
**Pull request by jianoaix**
## Why are these changes needed?
Fixes for python/ray/data/tests/test_dataset_map.py which is failing in streaming mode.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jianoaix** [comment]
cc @kira-lin

**Review by c21 — APPROVED** [review]

**Comment by kira-lin** [comment]
@jianoaix we'll fix this ASAP

**Comment by kira-lin** [comment]
Hi @jianoaix , CI of streaming executor failed because I didn't add ./install-java.sh there, so the jar is not built. You probably don't have the ray jar locally, either. I tested with ray nightly and raydp nightly, it worked. And other arrow dataset tests didn't fail. I'll open a PR to add ./install-java.sh to streaming executor

**Comment by jianoaix** [comment]
> Hi @jianoaix , CI of streaming executor failed because I didn't add ./install-java.sh there, so the jar is not built. You probably don't have the ray jar locally, either. I tested with ray nightly and raydp nightly, it worked. And other arrow dataset tests didn't fail. I'll open a PR to add ./install-java.sh to streaming executor

Great, thanks for taking quick action and fix!
I'll drop the part related to raydp here, and only keep the other fix in this PR.

**Review by clarkzinzow — APPROVED** [review]

**Pull request merged**
