### PR TITLE
[docker/dashboard] Fix ray dashboard

### LINKED ISSUE #11171: ray dashboard doesn't work when using docker
Since dashboard only sends port_forward and cmd=None, it crashes on this line. The line above would require something like:
`if run_env == "auto" and cmd is not None:`

https://github.com/ray-project/ray/blob/0d5b09f42646592222c5c4ade333ee9bb8807a6e/python/ray/autoscaler/_private/command_runner.py#L537

### PR DESCRIPTION
**Pull request by ijrsvt**
## Why are these changes needed?
The `ray dashboard` CLI command does not currently work--this fixes it.

## Related issue number

Closes #11171

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by mfitton — APPROVED** [review]
I watched Ian implement and validate, I can vouch for the fix's efficacy.

**Comment by mfitton** [comment]
Closes https://github.com/ray-project/ray/issues/11171

**Comment by edoakes** [comment]
@ijrsvt any good way to test this in CI to avoid regressions?

**Comment by ijrsvt** [comment]
@edoakes Actually, I can add this into the CLI tests! That should prevent regressions :)

**Comment by simon-mo** [comment]
Just merged master, will merge once test passes

**Review by simon-mo — APPROVED** [review]

**Comment by kangsan0420** [comment]
Didn't it fixed yet?

**Comment by ijrsvt** [comment]
@kangsan0420 Are you able to still repro this issue?

**Comment by jziegle4** [comment]
I'm sorry to bother you guys, but im currently using the dockerimage rayproject/ray-ml:latest-py38-gpu. When I'm calling ray.init(dashboard_host="0.0.0.0") and try to run the docker using -p=5090:8625 I'm not able to connect to the dashboard. Is there still a problem with the ray dashboard or how can I see the dashboard inside the docker from outside?

**Comment by kangsan0420** [comment]
> I'm sorry to bother you guys, but im currently using the dockerimage rayproject/ray-ml:latest-py38-gpu. When I'm calling ray.init(dashboard_host="0.0.0.0") and try to run the docker using -p=5090:8625 I'm not able to connect to the dashboard. Is there still a problem with the ray dashboard or how can I see the dashboard inside the docker from outside?

Try `ray.init(dashboard_host="0.0.0.0", dashboard_port=5090)`

**Pull request merged**
