### PR TITLE
new landing page with relative links for 2.4.0

### PR DESCRIPTION
**Pull request by angelinalg**
Cherry-pick of https://github.com/ray-project/ray/pull/34534 that is merged into master.

## Why are these changes needed?

To release new landing page with 2.4.0

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by angelinalg** [comment]
cc: @jjyao @zhe-thoughts

**Comment by architkulkarni** [comment]
Took the liberty of changing the base branch to releases/2.4.0, feel free to change it back if I made a mistake

**Comment by angelinalg** [comment]
[](url)

**Review by zhe-thoughts — APPROVED** [review]
I'm OK with picking. But someone from @raydocs should also approve

**Review by zhe-thoughts — APPROVED** [review]
Ah actually this is just cherry pick. So approved for picking

**Pull request closed without merging**
