### PR TITLE
[runtime env] Enable reference counting for URIs for actors

### LINKED ISSUE #19602: [runtime_env] Per-actor URIs aren't GC'd properly when the actor exits
See skipped test case added in https://github.com/ray-project/ray/pull/19597.

### PR DESCRIPTION
**Pull request by architkulkarni**
## Related issue number

Closes https://github.com/ray-project/ray/issues/19602
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@architkulkarni you had some merge conflicts, fixed them

**Review by edoakes — APPROVED** [review]
Looks good. Any thoughts on how to address this for tasks?

**Comment by edoakes** [comment]
@architkulkarni merge conflict

**Comment by architkulkarni** [comment]
Only failure is https://github.com/ray-project/ray/runs/4156496205?check_suite_focus=true#step:8:536 on Windows, which is a known issue being addressed in a different PR

**Pull request merged**
