### PR TITLE
[serve] Move route to deployment options

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Move the route_prefix option to `@serve.deployment` so it can be updated independently of the underlying code.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
@edoakes Do you mean "router"?

**Comment by edoakes** [comment]
@zhe-thoughts no, I meant route (it's called `http_prefix` in this PR because I can't settle on a name for it yet :)). It's just moving the option from the `@serve.ingress` decorator to the `@serve.deployment` one so it can be updated, changed, etc.

**Comment by edoakes** [comment]
@simon-mo thoughts on the naming for this option? Three options I can think of are: `route_prefix`, `http_prefix`, and `path_prefix`. `path_prefix` seems like it might be a bit confusing to some users (e.g., is it a filepath? is it a path to my model?). `http_prefix` is ok but kind of redundant and couldn't be used for another transport type in the future (not a hard requirement). I'm leaning towards `route_prefix` because it's most similar to the existing API.

**Comment by simon-mo** [comment]
How about just `prefix`?

**Review by simon-mo — APPROVED** [review]
LGTM

**Pull request merged**
