### PR TITLE
[WIP] New scheduler On

### PR DESCRIPTION
**Pull request by wuisawesome**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
@wuisawesome Is it going to be included in the next release? What's the purpose of the PR?

**Comment by wuisawesome** [comment]
Nope, this won’t make it

Thanks,
Alex

**Comment by WangTaoTheTonic** [comment]
Is anyone working on this?

**Comment by wuisawesome** [comment]
@WangTaoTheTonic I'm working on getting the new scheduler turned on. #9186 was just merged, and we'll need to make additional changes before it's turned on.

**Pull request closed without merging**
