### PR TITLE
[docs] address build time issues

### PR DESCRIPTION
**Pull request by maxpumperla**
we recently figured out that one of the key reasons behind the blown-up build time in the aftermath of refactoring API docs is that the main navigation is quite bloated because of it. Having a large, collapsible navigation page means that every single documentation page on our site, including all the API refs, now have a huge additional HTML snippet for this navigation. This explodes the write time of our docs. In fact, all generated html pages have 10k+ lines at the moment.

In this PR, we use the  `sphinx-remove-toctrees` plugin to manually remove the generated API pages from the TOC. This comes as a trade-off. API references at the most granular level don't have a dropdown navigation anymore, but we should see much improved build times now.

### CODE REVIEW

**Comment by ollie-iterators** [comment]
Also, as you can see, the documentation build is failing again.

**Comment by maxpumperla** [comment]
@ollie-iterators the failure was unrelated, but I fixed it anyway. thanks for the feedback, though!

**Review by jjyao — APPROVED** [review]
Thanks! I think it's a good enough workaround for now. After you merge this PR, I'll create a PR to autosummary all the classes by default.

**Comment by maxpumperla** [comment]
thanks @jjyao. This cuts the build time in half, so I think it's absolutely worth it.

**Comment by ollie-iterators** [comment]
If you merge the recent changes, then I think the failures should be fixed.

**Comment by c21** [comment]
Thanks for the workaround @maxpumperla. btw have we done some research that the navigation page/card is not useful enough? This navigation card is standard for other systems - Pandas, NumPy, etc. I am ok to remove it, just want to make sure we are aware of trade-off - that shortening build time is more valuable than having the navigation card.

**Comment by c21** [comment]
btw this is the original motivation to add in Ray Data - https://github.com/ray-project/ray/pull/31204#issuecomment-1362216956

**Comment by maxpumperla** [comment]
@c21 yeah, I think I mentioned the trade-off in the PR description. The problem is described well here https://github.com/pydata/pydata-sphinx-theme/issues/364, with a thread of possible solutions discussed here https://github.com/pydata/pydata-sphinx-theme/pull/492, and an example of how pandas solves this https://github.com/pandas-dev/pandas/pull/40761 (which amounts to the same thing as the plugin I'm using, I think).

**Comment by pcmoritz** [comment]
@maxpumperla Would it be possible to have the best of both worlds and not build the navigation in CI builds and for development (e.g. turn it off with an environment variable) and only have it for the release or if people explicitly build it on their dev machine? (Just and idea, if you want to merge the PR as is that's also fine)

**Comment by maxpumperla** [comment]
@pcmoritz wow, great idea!

@c21 @jjyao I now made it so that you can locally run "FAST=1 make html", which brings regular builds back to ~10mins and incremental builds to only around 1min (which is a huge relief for DevX, I think). On CI, this flag is also used. But, of course, our readthedocs build has to be unchanged/slow to generate the full TOC.

This should be a great compromise.

**Review by c21 — APPROVED** [review]
Thanks @maxpumperla!

**Review by richardliaw — APPROVED** [review]

**Review by kouroshHakha — APPROVED** [review]

**Review by avnishn — APPROVED** [review]

**Comment by jjyao** [comment]
> But, of course, our readthedocs build has to be unchanged/slow to generate the full TOC.

This means we still cannot autosummary all the classes since it will timeout on readthedocs.

I think the tradeoff is between having a worse nav bar and fewer autosummary classes.

Given auto-summaried classes are good for search-ability etc I feel we should favor that.

A better workaround is what pandas does (https://pandas.pydata.org/docs/reference/index.html): we selectively generate nav var based on the page we are viewing. Like if I'm viewing dataset docs, the nav var contains dataset apis but don't apis from other libraries.

cc @c21 @maxpumperla

**Comment by maxpumperla** [comment]
@jjyao you're right! I consider this PR a quality of life improvement for now.

Pandas has a different theme. The page you've linked is not something we can reproduce with ours. Essentially, our theme allows for nav dropdowns without page reloads. that means the nav bar needs to be complete to start with, on any page.

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
Looks great! Consider making `make develop` (I think that's what it is -- for development) to use `FAST` by default, so people who don't know about this trick still get the benefit :)

**Comment by maxpumperla** [comment]
@pcmoritz will do a follow-up!

**Comment by maxpumperla** [comment]
@jjyao haven't found a solution yet, but will keep looking.

**Pull request merged**
