### PR TITLE
[rllib] Rrk/12079 custom filters

### LINKED ISSUE #12079: [rllib] custom filters
If you see the get_filer function in https://docs.ray.io/en/latest/_modules/ray/rllib/utils/filter.html

Filters must be a string that matches a predefined set of filters. some of which are a bit limiting.

I propose allowing filters to be a callable that will create a filter object that can be used instead.

### Describe your feature request
adding an if callable(filter_config): return filter_config(shape)

### PR DESCRIPTION
**Pull request by raoul-khour-ts**
This allows a user to specify a custom filter function instead of using one of the built ins

Closes #12079

example code is included in (rllib/examples/custom_observation_filters.py)

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests

### CODE REVIEW

**Comment by raoul-khour-ts** [comment]
@richardliaw we discussed this a while back in the ray:rllib slack but I passed on implementing it. Today someone else on my team was saying they wish they had it. So I thought if multiple people on my team had asked for this independently there must be people out there that want it.

**Review by ericl — APPROVED** [review]
Looks good but tests are failing:

//rllib:examples/custom_observation_filters                              FAILED in 3 out of 3 in 15.3s
  Stats over 3 runs: max = 15.3s, min = 12.0s, avg = 13.6s, dev = 1.3s

**Comment by raoul-khour-ts** [comment]
@ericl Thanks for checking on this seemed like I requested too many cpus for the example run, so I took that down. I also re ordered the build file to make sure complex was before custom.

**Comment by ericl** [comment]
Hmm still seems to be failing: //rllib:examples/custom_observation_filters                             TIMEOUT in 3 out of 3 in 75.1s

**Comment by raoul-khour-ts** [comment]
@ericl is there a way to see what is in /home/travis/.cache/bazel/_bazel_travis/b88c129a127452fc94033a29d9f90e20/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/rllib/examples/custom_eval_tf/test_attempts/attempt_1.log

**Comment by raoul-khour-ts** [comment]
@ericl it looks like travis passed finally can you or @richardliaw merge?

**Pull request merged**
