### PR TITLE
[Core] Log restore errors by default

### PR DESCRIPTION
**Pull request by kennethlien**
## Why are these changes needed?
Failed restores result in Ray silently hanging. This should alert users when restores have failed

## Related issue number

https://github.com/ray-project/ray/issues/24248

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by stephanie-wang — APPROVED** [review]
Huh, not sure why this was DEBUG only before... :D

**Comment by stephanie-wang** [comment]
cc @rkooo567 in case he knows why.

**Comment by stephanie-wang** [comment]
@kennethlien could you address the lint errors? You can use `./ci/lint/format.sh`.

**Comment by kennethlien** [comment]
@stephanie-wang Whoops, fixed!

**Comment by rkooo567** [comment]
I think this was extremely noisy when the failure actually happens because we do infinite retry. I think we should go this direction instead of just turning the log https://github.com/ray-project/ray/pull/25000.

**Comment by rkooo567** [comment]
So I prefer not to merge this, but if you feel strong about this, please go ahead. But I'd prefer to make progress on this PR asap https://github.com/ray-project/ray/pull/25000 instead of merging this.

**Comment by kennethlien** [comment]
We're awaiting a response on https://github.com/ray-project/ray/issues/24248#issuecomment-1135532557, not too sure how to proceed with related work for https://github.com/ray-project/ray/pull/25000.

**Comment by rkooo567** [comment]
We will take over this task if there's no progress. cc @rickyyx  (I am thinking this is important as a part of state improvement after 2.0 branch cut)

**Pull request closed without merging**
