### PR TITLE
[train] Simplify `ray.train.xgboost/lightgbm` (5/n): Remove `xgboost_ray` and `lightgbm_ray` dependencies (for release tests)

### PR DESCRIPTION
**Pull request by justinvyu**
## Why are these changes needed?

This PR removes release tests for the external `xgboost_ray` and `lightgbm_ray` packages that are no longer used by the new implementation of `XGBoostTrainer` and `LightGBMTrainer`. See https://github.com/ray-project/ray/pull/42767 and https://github.com/ray-project/ray/pull/43244 for more details on the new implementations.

`air_benchmark_xgboost_cpu_10` is the only release test that actually tests `XGBoostTrainer`, which has been kept around. **TODO:** A follow-up PR will add 2 more release tests (for each framework) to add back test coverage: a training and a tuning release test that uses `XGBoostTrainer`/`LightGBMTrainer` in a multi-node cluster.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
There are some lint errors but otherwise exciting! Let's run some release tests to validate. Thankks.

**Review by aslonnie — COMMENTED** [review]
for @can-anyscale to review

**Review by can-anyscale — CHANGES_REQUESTED** [review]
failing lint; do you want to run some release tests to validate the changes as well, thankks

**Review by can-anyscale — APPROVED** [review]

**Comment by justinvyu** [comment]
cc @woshiyyya @matthewdeng I am removing these for now because they're just testing `xgboost_ray`/`lightgbm_ray` but will add back 2 release tests in the next PR.

**Comment by justinvyu** [comment]
The remaining `XGBoostTrainer` release test passed here without installing `xgboost_ray`!

https://buildkite.com/ray-project/release/builds/9540#018dec19-aae3-4d0b-9368-0504d37b7d72

**Pull request merged**
