### PR TITLE
[Core] Use `actor_options` in `ActorPool` and `ActorHandle`

### LINKED ISSUE #22978: [Bug] An exception in a task cannot be caught with ActorPool.map_unordered making restarting meaningless
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

I have defined an actor as shown below. I have set `@ray.remote(max_restarts=-1, max_task_retries=-1)` thus expecting tasks to be retried indefinitely and workers restarted as necessary. However, unlike `get_next_unordered` which could be wrapped in a `try`... `except`, this is not possible with `map_unordered`. Thus an exception in my remote call is re-raised thus crashing my program. I would like to avoid this and retry that task. How can I achieve this, please?

### Versions / Dependencies

```
ray 1.10.0
Python 3.8.10
Linux 5.15.15-76051515-generic (ubuntu 20.04)
```

### Reproduction script

```python
import random

import ray
from ray.util import ActorPool


@ray.remote(max_restarts=-1, max_task_retries=-1)
class AgentSmith:
    def spawn(self, number: int) -> int:
        if random.random() < 0.1:
            raise RuntimeError("Mr Anderson. Welcome back, we missed you.")
        return number**2


if __name__ == "__main__":
    ray.init(num_cpus=4)
    pool = ActorPool([AgentSmith.remote() for _ in range(4)])
    for square in pool.map_unordered(
        lambda actor, value: actor.spawn.remote(value),
        list(range(100)),
    ):
        print(square)

```

### Anything else

This happens every time an exception occurs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by tupui**
## Why are these changes needed?

* Enables support for `actor_options` in `ActorPool` through `ActorHandle`.
* Adds a retry strategy for `max_task_retries`.

Need discussions:
* I am not sure about shared variables to better test the PR.
* Please advise on what should be done for `max_restarts`.
* Not sure about changing `_raylet.pyx` call to `ActorHandle` to pass `actor_options`

## Related issue number

Closes #22978

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by tupui** [comment]
@Midnighter did you get a chance to look at this?

**Comment by tupui** [comment]
@pcmoritz what should be done with `max_restarts`?

**Comment by tupui** [comment]
Bump

**Comment by tupui** [comment]
Up

**Comment by stephanie-wang** [comment]
Sorry I'm a bit confused about the context for this PR. Why do we need to implement `max_task_retries` at the actor pool level? It should already be implemented within Ray core for individual actor handles.

**Comment by tupui** [comment]
@stephanie-wang as per the linked issue and OP's example, how would you set a `max_task_retries` for an `ActorPool` then?

**Comment by tupui** [comment]
Up

**Comment by jjyao** [comment]
@tupui is this ready for review?

**Pull request closed without merging**
