### PR TITLE
[civ2] use wanda to build base images

### PR DESCRIPTION
**Pull request by aslonnie**
civ2 will use the new wanda tool to build all forge/ci-base images (and eventually all container images that ray ci builds). benefits:

- build input is explicitly declared and minimized.
- will have content-addressed image build cache
- can be integrated into civ2 rayci bootstraping, with arbitrary dependency graph support.

### CODE REVIEW

**Comment by aslonnie** [comment]
build proof:

https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/388#0189e634-e32f-4c65-9fdb-f20f4e10f920/168

**Review by can-anyscale — APPROVED** [review]

**Comment by aslonnie** [comment]
with wanda binary: https://buildkite.com/ray-project/oss-ci-base-image-builder/builds/390

**Comment by aslonnie** [comment]
requires https://github.com/ray-project/rayci/pull/64 to be merged first.

**Pull request merged**
