### PR TITLE
[air] Surface tuner via __init__

### PR DESCRIPTION
**Pull request by richardliaw**
## Why are these changes needed?

'from ray.tune import Tuner'

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — COMMENTED** [review]
So the problem with this is that it will introduce a dependency from Ray Tune --> Ray AIR and thus from Tune to Train and Data. This also shows in the import conflicts we currently experience.
Alternatively, would we want to expose this as `ray.ml.Tuner` / `ray.air.Tuner`?

**Comment by amogkam** [comment]
After all the refactoring the dependency issue is no longer a problem (ray.air no longer depends on ray.data)

I think we should still merge this in since top level import will have consistency with the other primary tune modules.

**Review by amogkam — APPROVED** [review]

**Comment by amogkam** [comment]
@krfricke can we revisit this?

**Comment by krfricke** [comment]
Ah I've been including some of these changes during my docs refactor, opened a new PR for this: https://github.com/ray-project/ray/pull/26882

Doesn't run into circular imports for me locally

**Comment by krfricke** [comment]
Closing in favor for https://github.com/ray-project/ray/pull/26882

**Pull request closed without merging**
