### PR TITLE
Revert "[GCS] refactor gcs initialization (#11890)"

### PR DESCRIPTION
**Pull request by amogkam**
This reverts commit 1ae4d2873af5c1815e702fbb2b8bc2c6ad29ec0e.

This PR is breaking test_gcs_fault_tolerance

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
cc @wumuzi520

**Review by rkooo567 — APPROVED** [review]

**Comment by wumuzi520** [comment]
The test_gcs_fault_tolerance is fixed by @ffbin in PR https://github.com/ray-project/ray/pull/12346.

It is not introduced by `[GCS] refactor gcs initialization (#11890)`

**Comment by wumuzi520** [comment]
> The test_gcs_fault_tolerance is fixed by @ffbin in PR #12346.
> 
> It is not introduced by `[GCS] refactor gcs initialization (#11890)`

@rkooo567 I have verified that the fix in PR(https://github.com/ray-project/ray/pull/12346) is OK

**Comment by raulchen** [comment]
I've merged #12346

**Comment by amogkam** [comment]
@rkooo567 @wumuzi520 @raulchen 

#12346 still doesn't fix test_gcs_fault_tolerance. 
image

And it looks like #11890 is what is causing the test failure.
image

I opened another PR to revert #11890 https://github.com/ray-project/ray/pull/12411. We should merge the revert for now while a fix is in progress.

**Pull request closed without merging**
