### PR TITLE
[tune] Fix Trial Logging File name

### PR DESCRIPTION
**Pull request by richardliaw**
## What do these changes do?
Addresses #1463.

Example usage:

```
import ray
from ray.tune.trial_runner import TrialRunner
from ray.tune.trial_scheduler import FIFOScheduler
from ray.tune.variant_generator import generate_trials
from ray.tune.registry import register_trainable
import numpy as np

ray.init()

def train(config, reporter):
    reporter(timesteps_total=1)

register_trainable("my_class", train)

config = {
    "hyperband_test": {
        "run": "my_class",
        "config": {
            "a" * 50: lambda spec: np.random.randint(10, 60123412),
            "b" * 50: lambda spec: np.random.uniform(0.1, 1.0),
            "c" * 50: lambda spec: np.random.randint(10, 60123412),
            "d" * 50: lambda spec: np.random.uniform(0.1, 1.0)
        },
    }
}

runner = TrialRunner(FIFOScheduler())

for name, spec in config.items():
    for trial in generate_trials(spec, name):
        runner.add_trial(trial)

runner.step()
t = runner.get_trials()
print(t[0].logdir) 
```

On my local machine, this returns `'/Users/rliaw/ray_results/hyperband_test/my_class_0_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=55362204,bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb=0.21339,_2018-01-24_23-10-14sprj91s0'`

TODO:
 - [x] Write a test for this
 
## Related issue number
#1463.

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Tried it out, this looks good.

```
PENDING trials:
 - my_func_5_alpha=0.6,beta=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:	PENDING
RUNNING trials:
 - my_func_1_alpha=0.4,beta=a:	RUNNING
 - my_func_3_alpha=0.2,beta=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:	RUNNING
 - my_func_4_alpha=0.4,beta=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:	RUNNING
```

**Comment by richardliaw** [comment]
test this please

**Comment by richardliaw** [comment]
Test passes on private Travis (build 64341053) except one MacOS failure (#1304)

**Comment by robertnishihara** [comment]
@richardliaw does this mean that we lose config information? Would it make sense to also print the full config as the first line in the log file so that the information is not lost? Or is this not an issue?

**Comment by ericl** [comment]
@robertnishihara the config is also written into `params.json`, so nothing is lost

**Pull request merged**
