### PR TITLE
[AIR] Replace references of `to_torch` with `iter_torch_batches`

### PR DESCRIPTION
**Pull request by c21**
Signed-off-by: Cheng Su <scnju13@gmail.com>

## Why are these changes needed?

This PR is to replace references of `to_torch` with `iter_torch_batches`. We decide to replace `to_tf` in another PR as there's some pending issue there.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by c21** [comment]
Updated all places using to_torch, except following places:

2 notebook

* https://github.com/ray-project/ray/blob/master/doc/source/ray-air/examples/torch_incremental_learning.ipynb
* https://github.com/ray-project/ray/blob/master/doc/source/ray-air/examples/torch_image_example.ipynb

4 nightly test:

* https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/ray_sgd_runner.py
* https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/dataset_shuffle_data_loader.py
* https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/ray_sgd_training.py
* https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/pipelined_training.py

2 unit test:

* https://github.com/ray-project/ray/blob/master/python/ray/data/tests/test_dataset.py
* https://github.com/ray-project/ray/blob/master/python/ray/data/tests/test_raydp_dataset.py

I assume the nightly test and unit test is not needed for RC1. For notebook changes, I don't know how to do it, can I get more help there? cc @matthewdeng

**Review by richardliaw — APPROVED** [review]

**Review by richardliaw — CHANGES_REQUESTED** [review]
Hmm still see some references in:

doc/source/ray-air/doc_code/hvd_trainer.py
doc/source/ray-core/_examples/datasets_train/datasets_train.py
doc/source/train/dl_guide.rst
python/ray/train/torch/torch_trainer.py

**Comment by c21** [comment]
> doc/source/ray-air/doc_code/hvd_trainer.py
doc/source/ray-core/_examples/datasets_train/datasets_train.py
doc/source/train/dl_guide.rst
python/ray/train/torch/torch_trainer.py

ah let me update them, seems some files moved by https://github.com/ray-project/ray/pull/27481 .

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
tests failing?

**Pull request merged**
