### PR TITLE
[Data] [Docs] Cleanup Examples section 

### PR DESCRIPTION
**Pull request by amogkam**
- Removes images from the gallery, since some of them are not very relevant (for example the taxi image doesn't provide much value).
- Make the Examples page non collapsable so it's not overloaded with many examples

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by angelinalg** [comment]
It's too bad the dropdown carrot still appears for `Examples` on the LHS side nav, but I think that's a limitation because `Examples` is a directory for other libraries.

**Review by angelinalg — APPROVED** [review]

**Comment by amogkam** [comment]
@maxpumperla do you know how we can remove the caret symbol from the nav bar?

**Comment by maxpumperla** [comment]
@amogkam the carets are injected in JS by naming convention. A quick fix would be to rename this entry to e.g. "Ray Data Examples". I'll have to see that I make the specification of caret placement a bit more precise long-term.

**Review by maxpumperla — APPROVED** [review]
great, thanks!

**Pull request merged**
