### PR TITLE
[KubeRay][Autoscaler][Core] Add a flag to disable ray status version check

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
## Why are these changes needed?

`ray health-check` checks if the local Ray version agrees with the GCS Ray version,
which is a reasonable thing to do,
unless you're deliberately mismatching Ray versions.

During this development phase of the KubeRay autoscaler integration, we are deliberately mismatching Ray and autoscaler versions. As a result, users have encountered trouble starting up the autoscaler.

Thus, we need a way of disabling the version check.
This PR introduces a flag for that.

This PR also has ray health-check print error output in a couple of spots where it previously did not, for ease of debugging.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Manual check
   I'll manually check compatibility of autoscaler with these changes against Ray 1.11.0

### CODE REVIEW

**Review by tbabej — APPROVED** [review]
LGTM!

**Comment by iycheng** [comment]
We actually introduced a light weighted health check for GCS in this [PR](https://github.com/ray-project/ray/pull/26408/files)

Do you think we should update the kube ray one to use the healthz?

**Review by wuisawesome — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
> We actually introduced a light weighted health check for GCS in this [PR](https://github.com/ray-project/ray/pull/26408/files)
> 
> Do you think we should update the kube ray one to use the healthz?

Ah, I see. Thanks for the context. Maybe we can actually update "ray health-check" to use the healthz? What do you think?

**Comment by iycheng** [comment]
One down side for the healthz is that it needs dashboard to be alive to use this (maybe not good for autoscaler). The good thing about `ray health-check` is that it has no dependence.

But the cons for `ray health-check` is that it always need to start a gRPC connection, which is slightly heavier. And also, it needs ray to be installed.

I feel each has its use case. Maybe we should unify their health check code in some way in the future.

**Comment by DmitriGekhtman** [comment]
Confirming that this works as expected. ML test failures are unrelated.

Will merge, wait for the new image to build, and set that as the default in KubeRay.

**Pull request merged**
