### PR TITLE
[GCS] bug fix about gcs restart

### PR DESCRIPTION
**Pull request by wumuzi520**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
@ffbin @wumuzi520 Is it addressing test cases we discussed last time?

**Comment by ffbin** [comment]
> @ffbin @wumuzi520 Is it addressing test cases we discussed last time?

yes

**Comment by rkooo567** [comment]
@wumuzi520 Please update the description!

**Comment by rkooo567** [comment]
@ffbin What's the status of this PR?

**Comment by ffbin** [comment]
> @ffbin What's the status of this PR?

@wumuzi520  has not been working on this PR recently. I will communicate with him offline.

**Comment by rkooo567** [comment]
@ffbin When are you guys going to work on this PR?

**Comment by ffbin** [comment]
> @ffbin When are you guys going to work on this PR?

I have fixed the PR problem. I think we can close it.

**Pull request closed without merging**
