### PR TITLE
Re-enable raydp test & Support to_spark while using ray client

### PR DESCRIPTION
**Pull request by kira-lin**
## Why are these changes needed?

RayDP has updated their code and tests can be re-enabled now.

In addition, we want to support ray client in raydp dataset operation. Right now, if users want to do dataset.to_spark(spark) while using ray client, it will immediately fail because the local ray worker is not connected. By wrapping it in a function decorated with @client_mode_wrap, It works well no matter ray client is used or not. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kira-lin** [comment]
Hi @clarkzinzow ,
It now passes the test. Not sure why all the apple tests failed.
By the way, what's the plan for ray client? Does the community plan to support all ray dataset operations when using ray client?

**Comment by kira-lin** [comment]
hi @clarkzinzow , ready for review

**Review by clarkzinzow — APPROVED** [review]
LGTM, thanks for the ping!

**Comment by kira-lin** [comment]
@ericl @scv119 @jjyao please review and merge, thanks

**Comment by kira-lin** [comment]
@ericl @scv119 @jjyao ping again

**Comment by kira-lin** [comment]
Anything prevent this from merging? @clarkzinzow

**Comment by clarkzinzow** [comment]
Hi @kira-lin, thank you for the PR and the ping! This still LGTM, and I have merge privileges now. 😁

**Pull request merged**
