### PR TITLE
[ci] fix insecure tempfile.mktemp()

### PR DESCRIPTION
**Pull request by aslonnie**
use `tempfile.TemporaryDirector()` instead

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]
Maybe run a release test (shuffle_100gb.aws, that runs pretty fast) for testing

https://media3.giphy.com/media/u3jMHijwoCBaORpGeX/giphy.gif?cid=5a38a5a2l2n43aux0zsf05hkjq4zmgnv9fthjb13h4ok23d1&ep=v1_gifs_search&rid=giphy.gif&ct=g

**Review by ijrsvt — APPROVED** [review]
LGTM!

**Comment by aslonnie** [comment]
> Maybe run a release test

could you help me run it?

**Comment by aslonnie** [comment]
I think after the `_find_job_driver_and_ray_error_logs`, all the logs are never read again, so they are safe to delete (wrap the dir with `with`)

**Comment by aslonnie** [comment]
I kicked off a run here: https://buildkite.com/ray-project/release-tests-pr/builds/51256

**Comment by aslonnie** [comment]
> shuffle_100gb.aws, that runs pretty fast

this test still needs to run for like 30+ minutes..

**Comment by aslonnie** [comment]
the test passed. I am merging.

**Pull request merged**
