### PR TITLE
[RLlib] Contribution of LeelaChessZero algorithm for playing chess in a MultiAgent env

### PR DESCRIPTION
**Pull request by Capiru**
## Why are these changes needed?

This implements a version of LeelaChessZero, largely inspired by AlphaZero but with some structural changes. This changes also enable the slightly changed MCTS in the LeelaChessZero folder to run on MultiAgent environments. LeelaChessZero comes with an implementation of a MultiAgentChess env and also a test for making sure it builds and runs on the appropriate chess environment.

## Related issue number

no related issue

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests: added a test to the new algorithm folder that runs successfully locally, might require "pip install chess"
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Capiru** [comment]
The tests related to the LeelaZero contribution are passing, other tests seem to be unrelated to the changes.
The link check test should pass when the contribution is merged, as for the time being the leela zero folder in the master branch doesn't exist.

**Comment by scottsun94** [comment]
cc: @avnishn

**Comment by avnishn** [comment]
sorry this slipped through the cracks -- I'll take a look this week

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for this PR @Capiru !

**Comment by sven1977** [comment]
Hey @Capiru , thanks so much for your contribution! New Algorithm implementations are always very valuable and highly appreciated. The CI test you wrote seems solid, however, could you also provide a "release test" for this, which contains learning a more difficult problem (like playing chess vs some simple minimax-based agent)?

Take a look at the `ray/release/rllib_tests/learning_tests/yaml_files/`.
* Add your own yaml (or python config) file in there. For a python based config file, see `ray/rllib/tuned_examples/a2c/cartpole_a2c.py`
* Make sure you add the new test case to `ray/release/release_tests.yaml`:

```
- name: rllib_learning_tests_leela_chess_zero
  group: RLlib tests
  working_dir: rllib_tests

  legacy:
    test_name: learning_tests
    test_suite: rllib_tests

  frequency: nightly
  team: rl
  env: staging

  cluster:
    cluster_env: app_config.yaml
    cluster_compute: 2gpus_32cpus.yaml   # <- you might have to pick a better suited machine here. For all available machines, see yaml files under `ray/release/rllib_tests/l`

  run:
    timeout: 18000
    script: python learning_tests/run.py --yaml-sub-dir=leela_chess_zero
    type: sdk_command
    file_manager: job

  alert: default
```

**Comment by Capiru** [comment]
Sorry for the delay in response, as I was on vacation. And also thanks for the comments and suggestions @sven1977 @avnishn ! 

I spent a lot of time testing on my local tower as well, and for 5 hours of training i couldn't find that the model trains anything meaningful on the chess environment, requiring millions of samples to show improvement. I shall continue to investigate as part of a personal project and update this to include a release test of LeelaChessZero training on Chess in the future, as i make the code more efficient.

In the meantime, i have added a release test and multiagent environment for connect4, that shows to converge to meaningful values much quicker as a proof that the algorithm learns, and performs better versus a negamax agent (as the mcts implementation, without model training, given enough monte carlo simulations should be equivalent to a simple negamax agent).
This is the expected behavior that I saw from testing locally on the connect 4 environment:
Screenshot 2022-12-21 204144

**Comment by Capiru** [comment]
I've converted to draft while i investigate why the lint is failing even after rebasing the branch with the master ray branch.

**Comment by sven1977** [comment]
Hey @Capiru , this looks great! Let's leave it at the connect-4 release test for now. I completely understand, chess is a difficult enough problem that would require more tuning and experimentation.
Could you pull once more from master to resolve possible merging conflicts and fix the extra diffs (seems like your branch has some strange diffs against mast, which shouldn't be there). Then we can merge this.

**Comment by Capiru** [comment]
> Hey @Capiru , this looks great! Let's leave it at the connect-4 release test for now. I completely understand, chess is a difficult enough problem that would require more tuning and experimentation. Could you pull once more from master to resolve possible merging conflicts and fix the extra diffs (seems like your branch has some strange diffs against mast, which shouldn't be there). Then we can merge this.
@sven1977 
I might have messed up at a rebase or at some point, as merging latest changes from master didn't fix the weird files being in the PR.  I redid the commits at a different branch, and did a new PR at https://github.com/ray-project/ray/pull/31480 so that we can see the actual files that were changed.

**Pull request closed without merging**
