### PR TITLE
[core] Delete gcs heartbeat manager

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
The pull-based health check has been running for a month and no significant issue. This PR delete the old code to keep the codebase clean.

We'll maintain the new ones in the future.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
as long as it passes..

**Comment by ericl** [comment]
LGTM minus test failures

**Comment by iycheng** [comment]
let me fix the test.

**Comment by iycheng** [comment]
@ericl  another look?

**Review by scv119 — APPROVED** [review]

**Pull request merged**
