### PR TITLE
[tune] convert search spaces: parse spec before flattening

### LINKED ISSUE #12622: [tune] Raises Error when grid_search is defined in the config for AxSearch search alg
### What is the problem?

Raises Error when `grid_search` is defined in the config for `AxSearch` search alg

*Ray version and other system information (Python version, TensorFlow version, OS):*
`Python 3.7.5`
`ray==1.0.1.post1`

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

#### Script
```python
from ray import tune
from ray.tune.suggest.ax import AxSearch

config = {
    "x1": tune.uniform(0.0, 1.0),
    "x2": tune.uniform(0.0, 1.0),
    "x3": tune.grid_search([1, 2, 3])
}

def easy_objective(config):
    for i in range(100):
        intermediate_result = config["x1"] + config["x2"] * i
        tune.report(score=intermediate_result)

ax_search = AxSearch(metric="score")
tune.run(
    easy_objective,
    config=config,
    search_alg=ax_search, mode="min")
```

#### How does the Error look like?
```
~/ludwig/venv/lib/python3.7/site-packages/ray/tune/suggest/ax.py in set_search_properties(self, metric, mode, config)
    182         if self._ax:
    183             return False
--> 184         space = self.convert_search_space(config)
    185         self._space = space
    186         if metric:

~/ludwig/venv/lib/python3.7/site-packages/ray/tune/suggest/ax.py in convert_search_space(spec)
    297             "type": "fixed",
    298             "value": val
--> 299         } for path, val in resolved_vars]
    300 
    301         # Parameter name is e.g. "a/b/c" for nested dicts

~/ludwig/venv/lib/python3.7/site-packages/ray/tune/suggest/ax.py in <listcomp>(.0)
    297             "type": "fixed",
    298             "value": val
--> 299         } for path, val in resolved_vars]
    300 
    301         # Parameter name is e.g. "a/b/c" for nested dicts

TypeError: sequence item 1: expected str instance, int found
```

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Fixes #12622

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by krfricke** [comment]
I'll review the changes from this PR once more before submitting it for review. The tests seems to pass fine (even with hierarchical spaces), but I'll double check that there are no drawbacks in removing the flattening in some of the algorithms.

**Comment by richardliaw** [comment]
Sounds good! thanks a bunch :) and no rush -- have a good weekend!

**Comment by krfricke** [comment]
Sorry for the delay. It turns out we should be using the flattened variables, but then will need to resolve the variables twice. Since this is low overhead (just parsing through low nested dicts) this shouldn't be much overhead.

This should be ready for review.

**Comment by krfricke** [comment]
Just a quick ping @richardliaw

**Review by richardliaw — APPROVED** [review]

**Comment by richardliaw** [comment]
Should we add a test?

**Comment by krfricke** [comment]
Good point, I'll add a quick test tomorrow

**Comment by krfricke** [comment]
Added a test that checks for `ValueError` if a grid search parameter is passed (raised a `TypeError` before).

**Pull request merged**
