### PR TITLE
[C++ worker] set native library path for shared library search 

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
- When default worker starts, it should be able to find shared libraries from ray core and user side.
- For example, we set `LD_LIBRARY_PATH` environment variable to achieve that. We add "cpp/lib" and users' code search path to this variable.

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
@SongGuyang is it possible that we move this logic to the runtime_env agent instead? I'd like to avoid adding more logic to the C++ worker startup code given that we're trying to unify on `RuntimeEnvContext`.

**Comment by edoakes** [comment]
@SongGuyang ideally we would centralize all of the worker setup command logic to `RuntimeEnvContext`. Similar idea, just want to put it there so it's centralized & unified with the runtime_env worker command changes.

**Comment by SongGuyang** [comment]
@edoakes how about approve current PR first？We need this to fix library loading issue. I can try to clean up the commands in next step.

**Review by edoakes — APPROVED** [review]
@SongGuyang sure, sounds good, please make sure to follow up with that

**Review by qicosmos — APPROVED** [review]
LGTM

**Pull request merged**
