### PR TITLE
Updated PettingZoo+RLlib tutorial

### PR DESCRIPTION
**Pull request by Rohan138**
Updated the tutorial and added link to the blog post by the PettingZoo team.

## Checks

- [ Y] I've run `scripts/format.sh` to lint the changes in this PR.
- [ Y] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ Y] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jkterry1** [comment]
@richardliaw @sven1977 could you please merge this when you get a chance?

**Comment by jkterry1** [comment]
@sven1977 @richardliaw could this please be merged? it's been 6 days

**Comment by richardliaw** [comment]
Hi @jkterry1 @Rohan138, it looks like there is a merge conflict and tests are also not passing; could you help address those? Happy to merge after.

**Review by sven1977 — CHANGES_REQUESTED** [review]
Hey @Rohan138 , thanks for the PR. Could you make these few changes I suggested?

**Review by sven1977 — APPROVED** [review]
Looks good now, sorry for the delay. Was out last week and last few days.
We may still have to remove the pettingzoo.py script from our BUILD file as it's currently part of our tests. Will take care of it.

**Pull request merged**
