### PR TITLE
[build_base] Use bazelisk for better bazel version management.

### LINKED ISSUE #31542: [Core] Upgrade bazel to latest version (cur:4.2, latest:6.0)
We should upgrade compatibility with latest bazel. Currently one issue is known which causes failures with newer bazels: https://github.com/ray-project/ray/issues/31504

cc @scv119

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Upgrading bazel require a lot of file changes: 

- update setup.py
- update windows bazel fix
- update workspace

This PR make Ray use bazelisk instead of bazel to make the management easier.

## Related issue number
Closes #34305

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
LGTM as long as tests pass..!

**Comment by rkooo567** [comment]
Also cc @can-anyscale

**Review by krfricke — APPROVED** [review]
LGTM

**Comment by krfricke** [comment]
Can you merge master?

**Comment by iycheng** [comment]
@krfricke I think the build failure is because of the cache miss. I'm going to merge it first and observe for a day. If build still failed, we should just revert it.

**Pull request merged**
