### PR TITLE
[Doc] [Job submission] [Dashboard] Add tip for long runtime_env installation and improve error

### LINKED ISSUE #26332: [Runtime Environments] [Jobs] Propagate a warning when pip install hangs
### Description

In #26260, a job was stuck in `PENDING` because the `runtime_env` failed to `pip install` a package. The core issue was that the Kubernetes cluster disallowed outbound internet access, so the `pip install` hung indefinitely.

The only relevant message propagated back was `"Job has not started yet, likely waiting for the runtime_env to be set up."`. However, additional errors were logged about insufficient resources, which was a red herring during debugging.

The only way to detect that the `pip install` was hanging was to manually `exec` into a pod and try pip installing, which revealed the hang.

Ideally, Ray should instead detect the hang and propagate an error message specifically mentioning that the pip package’s install is hanging due to a network connection issue.

### Use case

This enables quicker debugging when `pip install` hangs.

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
- The dashboard can display the message `<actor> cannot be created because the Ray cluster cannot satisfy its resource requirements` in the case where the runtime env setup is stalled.  This PR updates this message to include the possibility of the runtime env setup failing.
- This PR adds a tip to the Job Submission doc saying that if a job is stalled in PENDING, the runtime env setup may have stalled.  It adds a pointer to the log files which should have more information.

The runtime env cannot stall forever, it fails after 10 minutes.  This is a new feature added after the Ray 1.13 branch cut.  In Ray <= 1.13, the runtime env can still stall forever.

## Related issue number

Closes https://github.com/ray-project/ray/issues/26332
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]
Btw, how difficult is it to generate a event log (log to the driver) to warn stalled runtime env creation?

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by wuisawesome** [comment]
@cadedaniel @architkulkarni have y'all/can y'all work together on this since Cade is in the process of rewriting the exiting docs.

**Comment by architkulkarni** [comment]
> So to be clear, the user wouldn't have the issue if he uses >= 1.13?

Sorry for the confusion, I've edited the description.  The issue is in 1.13 and was fixed after 1.13

**Comment by architkulkarni** [comment]
> Btw, how difficult is it to generate a event log (log to the driver) to warn stalled runtime env creation?

@rkooo567 Do you mean having two time thresholds, one for "likely stalled, should send a warning to driver" and one for "fail and raise an exception"?  Right now we just do the second one: once 10 minutes is reached we raise a RuntimeEnvSetupError that also prints a TimeoutError.  This is printed in the driver only when we `ray.get` a task or create an actor that uses the runtime_env.

```
Connecting to existing Ray cluster at address: 127.0.0.1:6379...
Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265.
Traceback (most recent call last):
  File "repro.py", line 9, in <module>
    assert ray.get(f.remote())
  File "/Users/archit/ray/python/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/archit/ray/python/ray/_private/worker.py", line 2241, in get
    raise value
ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.
Traceback (most recent call last):
  File "/Users/archit/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 366, in _create_runtime_env_with_retry
    runtime_env_context = await asyncio.wait_for(
  File "/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by architkulkarni** [comment]
`//python/ray/serve:test_air_integrations ` was broken on Windows.

**Comment by rkooo567** [comment]
> @rkooo567 Do you mean having two time thresholds, one for "likely stalled, should send a warning to driver" and one for "fail and raise an exception"? Right now we just do the second one: once 10 minutes is reached we raise a RuntimeEnvSetupError that also prints a TimeoutError. This is printed in the driver only when we ray.get a task or create an actor that uses the runtime_env.

Yes the the former case. I think we should do this after some threshold? (maybe just once for one runtime env). 10 minutes are still pretty long timeout. I am not asking you to do it now, but I'd like to understand the complexity of the feature

**Comment by architkulkarni** [comment]
I think there's two parts:
- For logging to the driver itself, I checked `log_monitor.py` and if my understanding is correct, we just need a small refactor to allow some special logs even when `RAY_RUNTIME_ENV_LOG_TO_DRIVER_ENABLED` is disabled (which is the default).  In the current setup, it looks like we need a separate file for these logs, but maybe we can refactor this more.
- To trigger a log after a short threshold without aborting the `asyncio.wait_for(runtime_env_setup, timeout=600)` operation, I'm guessing there's some simple way to do it with asyncio or threads, I don't know the details but I can ask around or figure it out

So it sounds like small/medium complexity

**Pull request merged**
