### PR TITLE
Revert "Revert "Revert "[Dashboard][Serve] Move Serve related endpoints to dashboard agent"""

### PR DESCRIPTION
**Pull request by Yard1**
Reverts ray-project/ray#26336

### CODE REVIEW

**Comment by xwjiang2010** [comment]
Lots of tests failing in post submit. Notably
```
ModuleNotFoundError: No module named 'ray.air'
ModuleNotFoundError: No module named 'ray.tests'
``` 

Not sure how it may be caused by this PR tho...

**Comment by Yard1** [comment]
Closing as it didn't fix it. https://buildkite.com/ray-project/ray-builders-branch/builds/8511#_

**Comment by SongGuyang** [comment]
Do you know the root cause of the tests failing?

**Comment by krfricke** [comment]
The problem is that one of the dependencies requires: `ray<1.13.0,>=1.8.0`

I'll find out which one that is...

**Comment by krfricke** [comment]
Hopefully this fixes it: https://github.com/ray-project/ray/pull/26356

**Pull request closed without merging**
