### PR TITLE
Remove object store memory cap

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Now that we have ref counting and eager eviction enabled, remove the object size cap, which was a workaround for excess memory usage. Also disable ray_get_and_free.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Looks great. Have you had a chance to run any benchmarks on this?

**Comment by stephanie-wang** [comment]
Is this missing the ray_get_and_free change?

**Comment by edoakes** [comment]
@ericl looks like you removed the actual change to `ray_get_and_free`

**Comment by ericl** [comment]
Yeah, seems like it is causing test failures.

**Review by stephanie-wang — APPROVED** [review]

**Comment by ericl** [comment]
Going to merge without the rllib change.

**Pull request merged**
