### PR TITLE
[serve] deflake serve proxy count in autoscaler shutdown test

### PR DESCRIPTION
**Pull request by aslonnie**
use `wait_for_condition()`

### CODE REVIEW

**Comment by aslonnie** [comment]
failure example: https://buildkite.com/ray-project/postmerge/builds/2563#018d19e1-046d-42e8-b332-5649659e4118/10766-10833

**Comment by aslonnie** [comment]
no idea if this is the right fix..

**Comment by aslonnie** [comment]
any comment @jjyao and @zcin ?

**Comment by aslonnie** [comment]
seeing again:

https://buildkite.com/ray-project/postmerge/builds/2590#018d2275-2e48-46e5-890f-0fdc1757c6f9/10529-10596

**Review by edoakes — APPROVED** [review]

**Pull request merged**
