### PR TITLE
[Core] Close RPC Server After GcsHearbeatManager

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

When GCS is stopped(e.g. receives a SIGTERM), it will stop RPC Server first, then close the heartbeat_manager_.

Closing RPC server will cost several seconds, during this time, GcsHeartbeatManager is still checking nodes' heartbeat timeout.

Since RPC Server won't handle heartbeat calls anymore, some nodes will be marked as dead during this time.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Review by WangTaoTheTonic — APPROVED** [review]
I don't think this is the main reason that causes node failures as the timeout interval is 30s by default, but heartbeat manager should be stopped first so LGTM

**Comment by lixin-wei** [comment]
> I don't think this is the main reason that causes node failures as the timeout interval is 30s by default, but heartbeat manager should be stopped first so LGTM

Yeah, there is another problem that causes a long heartbeat delay when GCS FO. I'm trying to dig it out.  But this fix is necessary because it will cause node death when the heartbeat delay is long.

**Comment by lixin-wei** [comment]
CI passed, would please merge this PR?

**Comment by lixin-wei** [comment]
hi @wuisawesome CI passed, would you please merge this PR? :)

**Pull request merged**
