### PR TITLE
[Serve][Nightly] Environment for Nightly K8s Tests

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
This PR adds a simple test case environment that runs on top of a live GKE cluster. The workload is just a placeholder for now.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — COMMENTED** [review]
..

**Comment by simon-mo** [comment]
OK seems to work! 
image

**Review by fishbone — APPROVED** [review]

**Comment by iycheng** [comment]
@simon-mo  are we going to merge this?

**Comment by simon-mo** [comment]
fixing lint...

**Pull request merged**
