### PR TITLE
[Tune] Fix checkpointing error message on K8s

### LINKED ISSUE #20338: [Bug] [Tune] checkpointing fails on k8s clusters
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

running https://docs.ray.io/en/latest/train/examples/tune_cifar_pytorch_pbt_example.html .. throws the following error:
```
(pid=12287) 2021-11-13 23:51:41,217	ERROR trial_runner.py:1100 -- Trial tune_function_33667_00000: Error handling checkpoint /home/ray/ray_results/tune_function_2021-11-13_23-48-05/tune_function_33667_00000_0_lr=0.001_2021-11-13_23-48-05/checkpoint_-00001/
(pid=12287) Traceback (most recent call last):
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 1095, in _process_trial_save
(pid=12287)     checkpoint=trial.saving_to)
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/callback.py", line 259, in on_checkpoint
(pid=12287)     callback.on_checkpoint(**info)
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 482, in on_checkpoint
(pid=12287)     self._sync_trial_checkpoint(trial, checkpoint)
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 457, in _sync_trial_checkpoint
(pid=12287)     trial, checkpoint.value))
(pid=12287) ray.tune.error.TuneError: Trial tune_function_33667_00000: Checkpoint path /home/ray/ray_results/tune_function_2021-11-13_23-48-05/tune_function_33667_00000_0_lr=0.001_2021-11-13_23-48-05/checkpoint_-00001/ not found after successful sync down.
```

### Versions / Dependencies

python 3.7, ray 1.8

### Reproduction script

`RAY_ADDRESS=anyscale://cluster-7 python tune_cifar_pytorch_pbt_example.py --use-gpu`

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by AmeerHajAli**
Where is this tested? where the test should be added here?

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by krfricke — APPROVED** [review]
Thanks!

**Comment by richardliaw** [comment]
@AmeerHajAli these changes are fundamentally hard to test since it requires a multi-node / aws setup. 

@krfricke any thoughts on this? perhaps after we have the fake-multi-node test harness?

**Comment by krfricke** [comment]
I can add a simple unit test that just interacts with the syncer and checks the error message.

For end to end, yes, let's use the fake multi node test harness for that! We want to leverage that for checkpoint CI testing anyway.

**Comment by AmeerHajAli** [comment]
Yes, I think a unit test should be good.

**Pull request merged**
