### PR TITLE
Fault tolerance for node_provider on node termination

### LINKED ISSUE #22999: [autoscaler][Bug] Autoscaler randomly fails on potential race condition.
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

We are running jobs on preemptible VMs and the autoscaler eventually fails with the following error:
```
2022-03-09 16:05:17,289 ERROR autoscaler.py:267 -- StandardAutoscaler: Error during autoscaling.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 264, in update
    self._update()
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 298, in _update
    self.load_metrics.prune_active_ips(active_ips=[
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 299, in <listcomp>
    self.provider.internal_ip(node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 144, in internal_ip
    node = self._get_node(node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 36, in method_with_retries
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node_provider.py", line 175, in _get_node
    instance = resource.get_instance(node_id=node_id)
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/gcp/node.py", line 551, in get_instance
    instance = self.resource.projects().locations().nodes().get(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://tpu.googleapis.com/v2alpha1/projects/******/locations/europe-west4-a/nodes/ray-o
scar-ray-debug-worker-fb721449-tpu?alt=json returned "Resource 'projects/********/locations/europe-west4-a/nodes/ray-********-worker-fb721449-tpu' w
as not found". Details: "[{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceName': 'projects/********/locations/europe-west4-a/nodes/ray-********-worker-fb721449-tpu'}]">
```

I think this whole thing might be a race condition. The workers get updated here:
https://github.com/ray-project/ray/blob/ray-1.10.0/python/ray/autoscaler/_private/autoscaler.py#L291

 and then the individual instances are queried again later:
```
  File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 299, in <listcomp>
    self.provider.internal_ip(node_id)
```

 If a VM gets deleted in between the error occurs .

There is also something very strange that I don't understand:

The autoscaler catches the error and logs the following message:

https://github.com/ray-project/ray/blob/ray-1.10.0/python/ray/autoscaler/_private/autoscaler.py#L267

The stack trace after that indicates that we hit autoscaler max errors (=5 by default). However, I don't find any other error messages in monitor log (there should be 5, right?).  Furthermore, if the stack trace appears there should be a message: "StandardAutoscaler: Too many errors, abort." which it isn't. So where does the stack trace come from and why is the autoscaler down?

### Versions / Dependencies

1.10

### Reproduction script

None, sorry.

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by dirkweissenborn**
Fixes #22999

## Related issue number

Should (at least partially) resolve #22999.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — CHANGES_REQUESTED** [review]
Thanks for the contribution, can we do a few polish items?

1. Catch a narrower class of exceptions, or if we must catch all exceptions, can we print what the exception is?
2. Use warning instead of error If we think things are in fact properly functioning.
3. We shouldn't need to start the message with "NodeProvider: " since `logger` already adds that prefix.

**Comment by dirkweissenborn** [comment]
Sure happy to.
I was just following the codestyle in that file. See logging message above
for instance. I rarely saw exceptions being printed explicitly in the rest
of the code. I agree with the warning.

**Comment by wuisawesome** [comment]
> I was just following the codestyle in that file. See logging message above

Hmm yeah i'm not sure why we're doing that, but fair enough. 

>I rarely saw exceptions being printed explicitly in the rest of the code. 

If we can narrow down the exception (e.g. handle some boto exception in the AWS node provider) then I think it would make sense to not print the exception.

**Comment by DmitriGekhtman** [comment]
@dirkweissenborn 
If you're using the GCP Node Provider, could you please catch a specific error (something like a 404) in the GCP Node Provider implementation
(rather than skipping it in the autoscaler code)

**Comment by DmitriGekhtman** [comment]
Here's a fix that addresses these issues: https://github.com/ray-project/ray/pull/23101

**Comment by dirkweissenborn** [comment]
Closing in favor of: #23101

**Pull request closed without merging**
