### PR TITLE
[rllib] Reduce concat memory usage, allow object store memory to be specified in init

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

These changes should reduce some inefficiences and allow object store to be specified in ray.init() to bound memory usage.

## Related issue number

https://github.com/ray-project/ray/issues/1517

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]
This looks good to me. I wonder if actors can actually call `__ray_terminate__` on themselves; this would be better when nesting actors.

@robertnishihara or @pcmoritz would be nice to get an approval on the ray.init portion of this pr

**Review by richardliaw — CHANGES_REQUESTED** [review]
Actually - `_stop` is actually not ever called...

You dropped `def stop` when migrating the diff from the previous PR

**Comment by ericl** [comment]
Doesn't the stop() method of trainable call it? Definitely recall this working

**Comment by robertnishihara** [comment]
Piping through `object_store_memory` looks good to me.

**Comment by richardliaw** [comment]
Oh right, only looked at rllib code - approving

**Review by richardliaw — APPROVED** [review]

**Comment by robertnishihara** [comment]
We should also allow `object_store_memory` to be passed into `ray start`.

**Pull request merged**
