### PR TITLE
Fix runtest.py on the ubuntu system python 3

### LINKED ISSUE #596: Test failure with python3 on ubuntu 14.04
With the system python3 on ubuntu 14.04, the following fails, which makes runtest.py fail:

```
import re
regex = re.compile(r"\d+\.\d*")
assert pickle.loads(pickle.dumps(regex)) == regex
```

Thanks @cbfinn for reporting this!

### PR DESCRIPTION
**Pull request by pcmoritz**
This fixes #596

### CODE REVIEW

**Comment by pcmoritz** [comment]
This should fix https://github.com/ray-project/ray/issues/596

**Comment by robertnishihara** [comment]
I'd prefer to weaken the test but leave it in, perhaps test for equality first and if that fails then try running the resulting regex on a string and make sure it gives the right output.

**Comment by robertnishihara** [comment]
Great, this looks good.

**Comment by pcmoritz** [comment]
Testing it out now, just to be sure :)

**Comment by robertnishihara** [comment]
The plasma store test failure may be #383.

**Pull request merged**
