### PR TITLE
[rllib] Add vf clipping param to fix pendulum example

### PR DESCRIPTION
**Pull request by ericl**
## What do these changes do?

The vf clip param is sensitive to the scale of the rewards. This broke the pendulum tuned example when clipping was fixed. cc @eugenevinitsky 

## Related issue number

https://github.com/ray-project/ray/issues/2233

### CODE REVIEW

**Comment by richardliaw** [comment]
Any plots?

**Comment by ericl** [comment]
You get about the same performance as before: -900 within about 100k, and
-140 by 300k ish.

**Comment by eugenevinitsky** [comment]
this is actually probably why PPO hasn't been working for us; our rewards are on the wrong scale too. Thanks for this fix!

**Comment by eugenevinitsky** [comment]
I think that's pretty compelling; it's kind of a hidden failure mode. I'm not sure there's a consensus on how to appropriately scale your rewards, so I could easily imagine users using relatively large reward

**Review by richardliaw — APPROVED** [review]
I would be ok with turning off clipping by default; but 10.0 is fine too.

**Pull request merged**
