### PR TITLE
[docs] turn on fail-on-warning for Sphinx builds

### PR DESCRIPTION
**Pull request by angelinalg**
We are missing build failures that Sphinx issues warnings for. This flag causes the ReadTheDocs build to fail if Sphinx issues warnings.
cc: @matthewdeng @edoakes @akshay-anyscale @rickyyx @zhe-thoughts 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
How will we test it?

**Comment by rickyyx** [comment]
I guess need to merge this first? https://github.com/ray-project/ray/pull/37628

**Comment by matthewdeng** [comment]
> I guess need to merge this first? https://github.com/ray-project/ray/pull/37628

Yeah, for the build to pass.

> How could we test it?

The fact that the job failed in this PR shows that the change is working as expected. 😄 

image

**Review by rkooo567 — APPROVED** [review]

**Review by matthewdeng — APPROVED** [review]
Awesome!

**Comment by edoakes** [comment]
Thanks a lot for following up on this @angelinalg

**Pull request merged**
