### PR TITLE
Pin the number of CPUs in failing actor test.

### PR DESCRIPTION
**Pull request by robertnishihara**
This may address a test failure that was introduced in #2364. The error is

```
testRemoteFunctionWithinActor (__main__.ActorNesting) ... Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:53145 to respond...
Waiting for redis server at 127.0.0.1:27100 to respond...
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 100}.
Failed to start the UI, you may need to run 'pip install jupyter'.
The actor with ID a1034d4ef284a01b3d1d7a5de13833682f93ff3f is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 CPU 
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Suppressing duplicate error message.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
    import ray
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
    import ray
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
    import ray
    import ray
    import ray
    import ray
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
    import ray
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
/home/travis/.travis/job_stages: line 78: 20913 Killed                  python test/actor_test.py
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/workers/default_worker.py", line 8, in <module>
    import ray
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/__init__.py", line 58, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/travis/.local/lib/python2.7/site-packages/ray-0.4.0-py2.7-linux-x86_64.egg/ray/pyarrow_files/pyarrow/lib.so: failed to map segment from shared object: Cannot allocate memory
travis_time:end:0c0bdde4:start=1530938144299180450,finish=1530938343848302667,duration=199549122217
[0K
[31;1mThe command "python test/actor_test.py" exited with 137.
```

### CODE REVIEW

**Comment by shaneknapp** [comment]
i'm going to kill the current PRB and reboot the ubuntu workers.  i'll retrigger when they're back up.

**Comment by shaneknapp** [comment]
test this please

**Comment by robertnishihara** [comment]
jenkins, test this please

**Comment by pcmoritz** [comment]
jenkins retest this

**Comment by pcmoritz** [comment]
retest this please

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
