### PR TITLE
[tune] Deprecate DurableTrainable

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Everything is now a DurableTrainable as long as an `upload_dir` is specified.

Having to specify both a sync config and a durable trainable is confusing to users. Instead, we should always use trial cloud checkpointing when an upload dir is specified.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]
Looks awesome!

**Comment by krfricke** [comment]
Release test build: https://buildkite.com/ray-project/periodic-ci/builds/1555

**Comment by xwjiang2010** [comment]
Looks good! Really love it that we are moving towards a simplified external API.

A few high level questions:
* What is the difference between Syncer and SyncClient? Why should we keep both?
* What is the difference between get_sync_client() and get_cloud_sync_client()? 
* Not sure if I am missing it, but I can't seem to find an example of what is expected of sync_to_cloud. It would be great to have some example for user to swap out things, e.g. replace s3 with gs etc.

**Comment by krfricke** [comment]
1) The Syncer is the user (developer) facing interface and the SyncClient is a storage-specific syncing mechanism. I agree that we should consider consolidating this in the future
2) `get_sync_client` returns a sync client, where `get_cloud_sync_client` would try to detect a cloud environment (e.g. docker/k8s) and return the respective sync client (usually if no regular sync client is found). This should be refactored with 1
3) We'll be deprecating this in a follow up PR this week (which is already being developed), but generally yeah, we should have good examples in place for cloud checkpointing

Tests (CI and release) are passing by the way :-)

**Review by xwjiang2010 — APPROVED** [review]

**Pull request merged**
