### PR TITLE
Add link to github from documentation.

### LINKED ISSUE #1384: Add link to GitHub from documentation.

### PR DESCRIPTION
**Pull request by robertnishihara**
Fixes #1384.

### CODE REVIEW

**Comment by richardliaw** [comment]
Looks good; we can also consider a "Fork me on Github" banner.

**Review by richardliaw — APPROVED** [review]

**Comment by robertnishihara** [comment]
The "fork me on github" banner could be a good idea, although most people who click on that usually don't want to "fork" the repository, they just want to go to the github page, right?

**Comment by richardliaw** [comment]
Not sure... Another option for the banner is to customize it to say "View Ray on Github".

I'd imagine there are people who are interested in contributing and also others who are interested in the implementation. The banner is probably good for the former while source links (like in Numpy and Pandas https://github.com/pandas-dev/pandas/issues/14178) are good for the latter.

**Comment by robertnishihara** [comment]
Ok, I added the banner. Should I get rid of the other link then? Or is it fine as is?

**Pull request merged**
