### PR TITLE
[Pubsub] increase subscriber timeout

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
As mentioned in https://github.com/ray-project/ray/issues/22161#issuecomment-1039661368, increase subscriber timeout to avoid subscriber state being deleted too soon.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mwtian** [comment]
Test failures seem unrelated.

**Review by ericl — APPROVED** [review]

**Comment by rkooo567** [comment]
Btw, as a side effect, it’s possible some of non-gcs disconnection can take really long time to detect. For example, previously if the owner dies, it takes 30 seconds to detect and clean up resources, but after this pr, it will take 5 minutes.

i wonder if we should set 5 m timeout only for gcs pubsub, but not for ref count and obj eviction

**Comment by ericl** [comment]
That's a good point. Also, we should make sure to reduce the timeout once the protocol becomes fault tolerant (maybe even set it to zero to test fault tolerance in some suites).

**Comment by mwtian** [comment]
For core worker subscribers, do they try to unsubscribe on worker shutdown, or primarily rely on the timeout logic for cleanup? I believe it is the 1st but I can look into this more.

**Comment by ericl** [comment]
> previously if the owner dies, it takes 30 seconds to detect and clean up resources

@mwtian we should also make sure fault tolerance is handled here too (don't lose object locations in case of timeouts). That could cause spurious hangs.

**Comment by mwtian** [comment]
Sounds good. Do object location and ref count fit the state notification paradigm?

**Comment by mwtian** [comment]
Btw this timeout also determines how frequently subscriber polls. A problem with short timeout / polling interval is that the publisher gets a concentrated wave of poll requests every 30s. Smearing polling across a longer interval or switch to streaming could workaround this bottleneck.

**Comment by ericl** [comment]
Yeah, I think both these also fit into state notification (you're just interested in the location set changes, or if ref state changes). Agreed the hard timeout could be a problem, though there will be some natural jitter from internal delays.

**Comment by rkooo567** [comment]
@mwtian can you follow up with having a separate timeout for non GCS publisher / subscribers? I think that will help us avoid unexpected regression in this path. 

> For core worker subscribers, do they try to unsubscribe on worker shutdown, or primarily rely on the timeout logic for cleanup? I believe it is the 1st but I can look into this more. If core worker subscribers unsubsribe before shutdown, there should not be many timeout.

Right now, subscribers can detect the publisher being dead because the request is long polling. 

But publisher won't be able to detect subscribers being dead in this scenario.

- Subscriber sends a request
- Publisher publishes
- Subscriber dies

-> in this case, it will take 5 minutes for publisher to detect subscribers. This can be problematic in cases like reference counting protocol (it can take 5 minutes for borrowers (publisher) to detect the owner is dead (subscriber)).

**Comment by rkooo567** [comment]
> @mwtian we should also make sure fault tolerance is handled here too (don't lose object locations in case of timeouts). That could cause spurious hangs.

@ericl This case is actually currently handled. IN the pubsub module, timeout is being considered as the publisher / subscriber is dead.

**Pull request merged**
