### PR TITLE
[release] [no_ci] fix tune torch large gpu weekly test.

### LINKED ISSUE #29777: [release] air_benchmark_tune_torch_mnist_large_gpu keeps timing out
### What happened + What you expected to happen

Examples:

https://buildkite.com/ray-project/release-tests-branch/builds/1163#01841b05-9162-4cab-9116-d9027a756bd1
https://buildkite.com/ray-project/release-tests-branch/builds/1163#01841a5c-c8b9-4f1a-aa7d-c9d5f5c24d5d
https://buildkite.com/ray-project/release-tests-branch/builds/1163#01841826-0352-40fb-854f-91cfc10a89e6

The test are running longer than expected, so timed out. Wondering is this the timeout threshold set to tight, or it's a real slow-running issue?

### Versions / Dependencies

releases/2.1.0

### Reproduction script

nightly test as above

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by xwjiang2010**
Signed-off-by: xwjiang2010 <xwjiang2010@gmail.com>

## Why are these changes needed?

fix tune torch large gpu weekly test.
right now we use strict_pack. For the large gpu test, we are requiring 8 workers, however, there are only 4 GPUs per node. So the resource request cannot be met. Making it an option that can be overwritten.

## Related issue number

closes #29777

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by xwjiang2010** [comment]
release test running at https://buildkite.com/ray-project/release-tests-pr/builds/19462

**Review by krfricke — APPROVED** [review]
LGTM, can you add a bit of context in the PR description? 3-4 sentences is enough.

Also do we have a passing run?

**Comment by xwjiang2010** [comment]
updated!

**Comment by c21** [comment]
Thanks @xwjiang2010 for the fix!

**Pull request merged**
