### PR TITLE
[docs] Reorganize and promote the Ray use cases index page

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

1. Organize the Ray use cases page by workload
2. Add an initial set of talk/blog highlights.

graphs

### CODE REVIEW

**Comment by richardliaw** [comment]
I think we need a better name for "Batch Training" -- it seems to mean something different to other people.

Perhaps we can say something about time series, like "Scalable Time Series Training"? or "Partitioned Training"?

Screen Shot 2022-12-02 at 9 47 38 AM

**Comment by pcmoritz** [comment]
Why not calling it Many Model Training?

**Review by pcmoritz — APPROVED** [review]
Thanks for doing this, this looks great!

**Comment by ericl** [comment]
I'm ok to rename to "Many Model Training" to avoid making up terminology. Going to gather some more feedback on best content to highlight prior to merge.

**Comment by pcmoritz** [comment]
Sounds great! One thing I notice is the every library has a link to its example gallery at the moment except serve, we can just link to https://ray--30846.org.readthedocs.build/en/30846/serve/tutorials/index.html and maybe also ask the serve team to make this into an example gallery? cc @simon-mo @sihanwang41 @edoakes

**Comment by pcmoritz** [comment]
Are people ok with cherry picking this onto the Ray 2.2 branch? It is obviously independent of the release process so won't have impact on the release. I think it is a great change that we should make visible sooner rather than later :)

The same goes for the follow up PR Eric made.

**Comment by ericl** [comment]
Pick sgtm. I'd only double check the links are still functional--- some of the references examples may be only in master. We can probably just drop those.

**Pull request merged**
