### PR TITLE
[Docs] Remove signatures from API summaries

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

Our API summaries contain signatures like `(fn, *[, compute, ...])`. However, they aren't helpful, so it's better to exclude them.

**Before**

image

**After**

image

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by bveeramani** [comment]
cc @justinvyu

**Comment by justinvyu** [comment]
Looks clean 👌

**Review by edoakes — APPROVED** [review]

**Comment by peytondmurray** [comment]
@bveeramani Any chance we can either a) change the behavior with an autosummary option, b) modify autosummary to do this globally, or c) add an upstream option to sphinx.ext.autosummary to configure it to not show signatures globally? It would be really nice if we don't have to keep adding `:nosignatures:` everywhere,

**Review by angelinalg — APPROVED** [review]

**Review by scottjlee — APPROVED** [review]

**Comment by bveeramani** [comment]
> @bveeramani Any chance we can either a) change the behavior with an autosummary option, b) modify autosummary to do this globally, or c) add an upstream option to sphinx.ext.autosummary to configure it to not show signatures globally? It would be really nice if we don't have to keep adding `:nosignatures:` everywhere.

I looked into it and wasn't able to find an option to do this globally.

> add an upstream option to sphinx.ext.autosummary to configure it to not show signatures globally

Would be awesome if we could do this but I don't have the bandwidth personally. Hopefully, developers will continue to use `nosignatures` by convention.

**Comment by peytondmurray** [comment]
I'll make an issue to track this on the sphinx-doc/sphinx repo. I don't think the ask is very large here, so I might just do this if there's time in the next few weeks.

**Pull request merged**
