### PR TITLE
[serve] Fix flaky `test_replica_scheduler`

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

`test_prefer_az_off` fails occasionally because the test chooses a replica 10 times and makes sure all 3 replicas are chosen at the end of the 10 iterations.

However sometimes even though the router logic is correct, only 2 out of the 3 replicas are chosen after 10 iterations. The probability of this happening is (2/3)^10 * 3 = 5%. This makes the test very flaky.
Changing it to run for up to 1000 iterations in batches of 10 at a time. This deflakes the test while still maintaining fast average times.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by shrekris-anyscale — COMMENTED** [review]
Can you use `set_queue_state_response` to make each replica stop accepting requests after accepting a request for the first time? That way, we can guarantee that after sending 3 requests, each replica should be assigned. Would that test the behavior correctly?

**Comment by edoakes** [comment]
@shrekris-anyscale I think that'd be testing a _slightly_ different path because in that case we're verifying the behavior when replicas are occupied. As written, the test is verifying that we load balance even when replicas are free to take more requests.

**Review by shrekris-anyscale — APPROVED** [review]
Sounds good, nice work @zcin!

**Comment by edoakes** [comment]
@zcin instead of having a set number of, can we iteratively schedule a small batch up to a maximum number of times? If you make it a large number, say 1000, then the odds of this flaking should be approximately zero while maintaining very fast average/median runtime.

**Comment by zcin** [comment]
@edoakes Good idea, I've changed the test from running 30 iterations to your suggested approach.

**Review by GeneDer — APPROVED** [review]
:shipit:

**Pull request merged**
