### PR TITLE
Revert "[Dashboard][event] Basic event module"

### PR DESCRIPTION
**Pull request by amogkam**
Reverts ray-project/ray#16985

Sorry I have to revert this again @fyrestone. This is causing Mac Wheel Build to fail

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]
+1

**Comment by fyrestone** [comment]
@amogkam Where can i find the build error log?

**Comment by amogkam** [comment]
You can see it by clicking on the bug icon on the flaky test tracker https://flakey-tests.ray.io/

**Comment by fyrestone** [comment]
> You can see it by clicking on the bug icon on the flaky test tracker https://flakey-tests.ray.io/

There are many errors in the build log, but none of them related to this PR. P.S. many failed build has no output.

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by fyrestone** [comment]
I found some worker crashes in this build log: https://travis-ci.com/github/ray-project/ray/jobs/524307882

```
[2021-07-14 04:57:17,712 C 11573 47781] core_worker.cc:207:  Check failed: core_worker_process The core worker process is not initialized yet or already shutdown.
*** StackTrace Information ***
    ray::GetCallTrace()
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::CoreWorkerProcess::EnsureInitialized()
    ray::CoreWorkerProcess::GetCoreWorker()
    __pyx_pw_3ray_7_raylet_10CoreWorker_21get_worker_id()
    method_vectorcall_NOARGS
    call_function
    _PyEval_EvalFrameDefault
    function_code_fastcall
    property_descr_get
    _PyObject_GenericGetAttrWithDict
    _PyEval_EvalFrameDefault
    function_code_fastcall
    call_function
    _PyEval_EvalFrameDefault
```

I am not sure if it is the root cause of the failure. Some other errors are caused by missing `psutil`.

```
=================================== FAILURES ===================================
___________________________ test_user_setup_function ___________________________
    @pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows")
    def test_user_setup_function():
        script = """
    import ray
    ray.init()
    @ray.remote
    def get_pkg_dir():
        return ray._private.runtime_env.VAR
    
    print("remote", ray.get(get_pkg_dir.remote()))
    print("local", ray._private.runtime_env.VAR)
    
    
    """
    
        out = run_string_as_driver(
            script, {"RAY_USER_SETUP_FUNCTION": "ray.test_utils.set_setup_func"})
        (remote_out, local_out) = out.strip().split("\n")[-2:]
>       assert remote_out == "remote hello world"
E       AssertionError: assert '\x1b[2m\x1b[...import psutil' == 'remote hello world'
E         - remote hello world
E         + (raylet)     import psutil
python/ray/tests/test_basic.py:215: AssertionError
```

**Comment by fyrestone** [comment]
The `event` module is disabled by default, it is only enabled in the `test_event.py`. I need more clue about the build failure.

**Comment by fyrestone** [comment]
@amogkam I noticed that the mac wheel build still fails after the revert. I think it's better to show the error details in the build log, so that we can fix it quickly. Currently, I don't know which error caused the build to fail.

**Comment by amogkam** [comment]
You're right @fyrestone this isn't causing the failures. We can merge back in.

**Comment by fyrestone** [comment]
> You're right @fyrestone this isn't causing the failures. We can merge back in.

Thanks.

**Pull request merged**
