### PR TITLE
[Data] Remove Arrow nightly test

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

Currently, we run Data tests against Arrow nightlies in CI. Because the Arrow version isn't pinned, and because Arrow nightlies are unstable, CI can unexpectedly break. 

To minimize operational overhead and improve CI reliability, this PR removes the Arrow nightly tests. Going forward, we'll upgrade the stable Arrow version in CI and manually fix issues whenever a new stable version is released.

## Related issue number

See also https://github.com/ray-project/ray/pull/41036

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
SGTM, do you need someone else from data to approve as well, or you all already agree on this?

**Review by can-anyscale — APPROVED** [review]

**Comment by bveeramani** [comment]
Already discussed, but wouldn't hurt to get stamp.

**Review by c21 — APPROVED** [review]

**Review by aslonnie — APPROVED** [review]

**Comment by pcmoritz** [comment]
This is not a good move. It makes it impossible to detect issues before a new arrow version is released. After it is released, it is too late and it will already be shipped to users.

Do you have any other mechanisms in place to make sure we detect breakages?

**Comment by bveeramani** [comment]
> After it is released, it is too late and it will already be shipped to users.

How would we prevent new Arrow versions from breaking the stable Ray release? Even if we fix Arrow-related issues on master, it'd only help users who use Ray nightly or future releases, right?

**Comment by pcmoritz** [comment]
If it is a relevant regression in Arrow, we can file an issue upstream and get it fixed before the Arrow release goes out. That's the purpose of these nightly tests (we have similar tests for some Ray Core dependencies).

**Comment by bveeramani** [comment]
I see. So the core issue is that we want to identify issues with Arrow itself before an Arrow release? 

In that case, we could run to Arrow nightly tests pre-merge and permanently mark it as unstable.

**Comment by aslonnie** [comment]
just some thoughts and general principles:

- the purpose of premerge/postmerge is testing the code in the repo, not probing the Internet.
- we can have another probe pipeline that probes the Internet.
- if a python package does not have an 1.0 or does not follow semver, or does not have any kind of spec at all, we cannot expect things work with a future version.
- for those kind of packages, even if we test against them, when the test break, we have not much to do, other than file an issue and maybe disable the test.
- for those kind of packages, IMO, the right solution is to maintain a set of versions that work together and recommend this set to users, which we are already kind of doing in a way with constraint files + container images
- pip and its ecosystem is basically broken. pip install from pypi heads without constraint file is guaranteed not to work reliably for most of the cases, and we probably just should not endorse/support that workflow. I think there is no point to fight a fundamentally failing workflow.

**Comment by bveeramani** [comment]
Arrow follows semver, sort-of. Virtually every release is a major release so backwards compatibility isn't guaranteed. 

> for those kind of packages, IMO, the right solution is to maintain a set of versions that work together and recommend this set to users, which we are already kind of doing in a way with constraint files + container images

@pcmoritz do you feel strongly that we keep the nightly tests? I think, given the tradeoffs, it might make sense to remove nightly from pre- and post-merge, and recommend a set of supported Arrow versions to users.

That said, I'm not strongly opposed to keeping them either.

**Comment by pcmoritz** [comment]
Having a restricted list of supported versions is not acceptable -- Ray is a code execution tool and we need to be compatible with all versions a user wants to use (otherwise we get into the very painful situation that we were in with grpc a while back). That's why we must pick our dependencies extremely carefully.

Whether you want to solve that problem by running nightly tests in the CI or some other means / different pipeline is up to you all, but we need to have a solution for it :)

**Comment by bveeramani** [comment]
Okay, sounds good 👍🏾 

Let's go with pre-merge and marked unstable

**Comment by aslonnie** [comment]
> Ray is a code execution tool and we need to be compatible with all versions a user wants to use 
> we need to have a solution for it :)

hmm.. maybe consider buying out the arrow library maintainers? :)

kidding aside, reacting fast to third-party changes is a probe monitoring+oncall job. you can even declare an incident or something if arrow nightly is breaking us, but I would prefer premerge/postmerge pipelines not doing Internet probing work.

**Pull request closed without merging**
