### PR TITLE
[tune] Right-aline + wrapped abbreviated columns in table output

### LINKED ISSUE #27011: [Tune][Air] Unreadable CLI report table due to `train_loop_config` string
### Description

Hi,

How can I simplify the CLI progress reporter column names? Some features become too long to display, such as `train_loop_config/batch_size`. The `train_loop_config` string seems useless.

Screenshot from 2022-07-26 19-48-20

I am using the latest nightly version of Ray with the `Tuner` api:

```Python
tuner = Tuner(
        trainer,
        param_space={"train_loop_config": config})
```

### Use case

Allow users to remove/rename CLI report table columns

### PR DESCRIPTION
**Pull request by krfricke**
Signed-off-by: Kai Fricke <kai@anyscale.com>

## Why are these changes needed?

Parameter columns are currently left-aligned. In long parameter names, this means the table columns share the same abbreviated column name, which makes it unusable. Users can pass a custom CLIReporter, but to alleviate the problem in the default case, this PR updates the render function to right-align abbreviated column names.

Before:

```
+---------------------------------+----------+-----------------+------------------------+------------------------+
| Trial name                      | status   | loc             |   train_loop_per_wo... |   train_loop_per_wo... |
|---------------------------------+----------+-----------------+------------------------+------------------------|
| DataParallelTrainer_e670e_00000 | ERROR    | 127.0.0.1:50895 |                0.14336 |              0.0372097 |
+---------------------------------+----------+-----------------+------------------------+------------------------+
```

After:

```
+---------------------------------+----------+-----------------+------------------------+------------------------+
| Trial name                      | status   | loc             |   ...p_per_worker/beta |   ...oop_per_worker/lr |
|---------------------------------+----------+-----------------+------------------------+------------------------|
| DataParallelTrainer_65099_00000 | ERROR    | 127.0.0.1:49806 |               0.110931 |              0.0350912 |
+---------------------------------+----------+-----------------+------------------------+------------------------+
```

## Related issue number

Closes #27011

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]
would it be possible to instead wrap text around?

**Comment by krfricke** [comment]
Great idea actually. I'll take a look

**Comment by Yard1** [comment]
Awesome!

**Review by xwjiang2010 — APPROVED** [review]
wow, nice!

**Pull request merged**
