### PR TITLE
[Autoscaler] Frequent update to Raycluster headpod's annotation "ray.io/autoscaler-update-timestamp" causing reconciliation by argocd

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

Frequent updates to the head Pod may lead to performance degradation of the Kubernetes API Server. The annotation `ray.io/autoscaler-update-timestamp` appears to be solely for user observability purposes and is not utilized in either Ray or KubeRay. That's why I decide to use `GET` instead of `PATCH`.

## Related issue number
https://github.com/ray-project/kuberay/issues/1182

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @DmitriGekhtman, would you mind providing some feedback on this PR? Does the change make sense to you? Thanks!

**Review by DmitriGekhtman — APPROVED** [review]
This looks fine. There's a slight chance autoscaling might be less stable, due to the older resource version after this change. But I understand someone is working on improving autoscaling anyway.

**Comment by DmitriGekhtman** [comment]
(The purpose of the patch is to extract a relatively fresh pods resource version for the subsequent list pods request.)

**Comment by kevin85421** [comment]
Hi @DmitriGekhtman, thank you for the reply!

> There's a slight chance autoscaling might be less stable, due to the older resource version after this change. But I understand someone is working on improving autoscaling anyway.

Would you mind explaining more about this? Unlike the KubeRay operator, the autoscaler sends a GET request directly to the Kubernetes API Server instead of relying on the local informer cache. Is it still possible to get a stale resource version?

If we are concerned about this race condition, would it be reasonable to replace the `patch` operation with an `update` operation? This way, if a race condition occurs, the request will be rejected with a 409 conflict error.

**Comment by DmitriGekhtman** [comment]
> the autoscaler sends a GET request directly to the Kubernetes API Server instead of relying on the local informer cache. Is it still possible to get a stale resource version?

You will get the pods resource version at which the head pod was last updated, which could be a bit old.

**Comment by DmitriGekhtman** [comment]
> If we are concerned about this race condition, would it be reasonable to replace the patch operation with an update operation?

You'd still get an extra update of the head pod annotation, which IIUC was the source of the original concern.

**Comment by kevin85421** [comment]
> You will get the pods resource version at which the head pod was last updated, which could be a bit old.

Got it. I just realized that we can compare `resourceVersion` between Pods.

> With an update, you'd still get an extra update of the head pod annotation, which IIUC was the source of the original concern.

Sorry for the lack of clarity. The `patch` here is referred to the patch to update `replicas` and `workersToDelete` rather than the patch for annotations.

I now understand the stability issue. Would it be acceptable to change `PATCH` to `GET`, or should we explore alternative solutions if the stability impact is significant?

**Comment by DmitriGekhtman** [comment]
> > You will get the pods resource version at which the head pod was last updated, which could be a bit old.
> 
> Got it. I just realized that we can compare `resourceVersion` between Pods.
> 
> > With an update, you'd still get an extra update of the head pod annotation, which IIUC was the source of the original concern.
> 
> Sorry for the lack of clarity. The `patch` here is referred to the patch to update `replicas` and `workersToDelete` rather than the patch for annotations.
> 
> I now understand the stability issue. Would it be acceptable to change `PATCH` to `GET`, or should we explore alternative solutions if the stability impact is significant?

Removing the patch should _probably_ be fine. I think _most_ of the time you'd get up-to-date information.

**Comment by DmitriGekhtman** [comment]
One idea we've considered is having KubeRay write the list of pod names to CR status (based on the content of its informer cache) and having that autoscaler read that info.

**Comment by DmitriGekhtman** [comment]
> What's the reason to read CR's status? In this case, the information that the autoscaler reads may be relatively outdated.

Hmm, yeah. That's true and might be one reason we didn't do this. On the other hand, with such a scheme the autoscaler sees more or less the same information that the operator does, with a slight delay to get the status update.

**Pull request merged**
