### PR TITLE
[GCS]Open light heartbeat by default

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?

Cherry pick 612ddb2dd171647c4793ddd32326f2f68b53c27b. Tests to be added.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
test_autoscaler & test_resource_demand_scheduler seems broke in master.

**Review by rkooo567 — APPROVED** [review]

**Comment by WangTaoTheTonic** [comment]
Looks like failed tests are unrelated. Gonna retry them.

**Comment by WangTaoTheTonic** [comment]
image
STEAMING_TEST failed but not related.

**Comment by WangTaoTheTonic** [comment]
Shall we merge this? @rkooo567

**Comment by ericl** [comment]
This seems to have broken test_placement_group--- please revert

**Comment by ericl** [comment]
This seems to have broken test_placement_group: see https://travis-ci.com/github/ray-project/ray/jobs/441235543

**Pull request merged**
