### PR TITLE
[RLlib] nit: Correct spelling and double-dots in code example

### PR DESCRIPTION
**Pull request by cwenner**
## Why are these changes needed?

These changes are minor and unimportant - they merely fix two spelling/syntax mistakes that stood out a bit in the RL documentation.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
@cwenner Can you merge master into this? There are some failures in the CI that I think are unrelated in the PR, it would be great to get the PR merged! Thanks for your contribution!

**Comment by pcmoritz** [comment]
@sven1977 @gjoliver Can one of you approve / merge this?

**Comment by cwenner** [comment]
Thank you, @pcmoritz. I am not authorized to merge though.

I'm not sure what is going on with the CI or whether this is normal.

Previously, only one unrelated check and the sign-off check failed. I corrected the sign off and repushed. Then when CI reran, there was this large number of failures. I am not sure how to force-rerun them until they pass.

As you say, these are just some doc changes so I don't see how they could cause these failed checks.

**Comment by gjoliver** [comment]
@cwenner thanks for the clean ups. these CI tests fail because this PR is based off an old commit.
can you do the following to rebase to the latest master? that will re-trigger and fix the tests.
First sync your forked Ray repo to the latest. Then
```
git checkout master
git pull --rebase
git checkout patch-1
git rebase master
git push -f origin patch-1
```

**Pull request closed without merging**
