### PR TITLE
[RLlib] Add `torch` flag to train.py

### PR DESCRIPTION
**Pull request by sven1977**
Unification of tf and torch (make torch 1st class citizen in RLlib).

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by sven1977** [comment]
Updated documentation.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Lint errors

**Comment by sven1977** [comment]
LINT fixed.

**Comment by sven1977** [comment]
Lint is clean now.

**Comment by sven1977** [comment]
Thanks!

**Pull request merged**
