### PR TITLE
Use XRay by default

### PR DESCRIPTION
**Pull request by pcmoritz**
This change will enable XRay for everybody compiling Ray from source by default. While XRay is not stable/tested enough for everybody to use, we would like to encourage feedback on what still needs to be improved from everybody brave enough to compile Ray from source.

See #2789

### CODE REVIEW

**Comment by concretevitamin** [comment]
This seems to allow the possibility that functionality included in RAY_USE_NEW_GCS but not in RAY_USE_XRAY to be quietly left out.  What's the migration path you have in mind?  Should we eliminate the previous flag first?

**Comment by robertnishihara** [comment]
@concretevitamin Turning on x-ray by default is a prerequisite for turning on flushing by default. I think it makes sense to do these as two separate steps.

The path for turning on flushing by default will probably be to first remove the compile time flag so that it can be used without recompiling, then start testing it heavily, then turn it on. What do you think?

**Comment by concretevitamin** [comment]
@robertnishihara Yeah, that's exactly what I have in mind (eliminating the compile-time flag RAY_USE_NEW_GCS)

**Comment by robertnishihara** [comment]
Done by #3020.

**Pull request closed without merging**
