### PR TITLE
[Nightly test] Add dask on ray failure tests

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Still running...

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Looks like no spilling is failed; https://console.anyscale.com/o/anyscale-internal/projects/prj_3qqS82y6R2UUTWG4oHeMpF/clusters/ses_xavv3GAV5jMS14sG1cLRmNLy?command-history-section=command_history

**Comment by rkooo567** [comment]
Looks like no spilling also doesn't work https://console.anyscale.com/o/anyscale-internal/projects/prj_3qqS82y6R2UUTWG4oHeMpF/clusters/ses_YseFfy86vRFPq1giWXxwsiAu?command-history-section=worker_log

Do you think the setup is too stressful? My assumption is however stressful is, it should work since all owners are driver anyway (and we limit the max nodes to 10). But lmk what you think!

**Comment by stephanie-wang** [comment]
Hmm the spill test logs have an error message that looks like a real bug:
```
(raylet) [2021-12-16 06:01:55,848 C 210 210] local_object_manager.cc:260:  Check failed: objects_pending_spill_.count(object_id) 
(raylet) *** StackTrace Information ***
(raylet)     ray::SpdLogMessage::Flush()
(raylet)     ray::RayLog::~RayLog()
(raylet)     ray::raylet::LocalObjectManager::SpillObjectsInternal()::{lambda()#1}::operator()()
(raylet)     std::_Function_handler<>::_M_invoke()
```
I can take a look at this one.

The no-spill logs don't have anything obvious. Looks like maybe the head node crashed? Can you figure out why that happened and make sure it's not the node-killer?

**Comment by rkooo567** [comment]
Closing it for now. Stephanie will take it over!

**Pull request closed without merging**
