### PR TITLE
[Serve] Add queue handle metrics into the autoscaling decision

### PR DESCRIPTION
**Pull request by sihanwang41**
## Why are these changes needed?

- Add "tag" into the InMemoryMetricsStore
- Remove raw datatype passing the data, instead use TimeStampedValue
- Add queue handle metrics into the calculate_desired_num_replicas function

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
Overall looks good!  Added a some nit-type comments inline.

Apart from that, two high-level questions, these are also minor:
- How likely is it we'll use other keys for `tags` in the future?  Right now it makes the `latest` function return value a bit confusing.  What if we just add `handle_id` as a `TimeStampedValue` field?
- Is it possible to capture the autoscaling behavior improvement in this PR in a release test or some other kind of test?

Also, it might be worth running the current serve autoscaler release tests on this PR, if it's easy enough to do it on buildkite.

**Comment by simon-mo** [comment]
At high level, i think the metrics store code is now at a tipping point of complexity. @sihanwang41 do you think using a sqlite3 in memory db can help reduce the implementation complexity here? https://docs.python.org/3/library/sqlite3.html

**Comment by sihanwang41** [comment]
> 

I totally agree for potential complexity increase.

For using sqlite, I will test for a benchmark (release tests) to understand any potential performance regression and instability.

Given the priority, I might go back to this pr next week. Currently I will put more efforts on the graph deployments issues and our tests migration.

**Comment by simon-mo** [comment]
Don't forget to revive this after 2.0!

**Pull request closed without merging**
