### PR TITLE
Bump version from 0.7.1 to 0.8.0.dev1.

### LINKED ISSUE #4932: Bumping to 0.8.0.dev1?
@robertnishihara @devin-petersohn Is there a followup PR to bump back to 0.8.0.dev1?

_Originally posted by @richardliaw in https://github.com/ray-project/ray/pull/4890#issuecomment-498979267_

### PR DESCRIPTION
**Pull request by robertnishihara**
Fixes #4932.

### CODE REVIEW

**Comment by richardliaw** [comment]
Can all the strings in the repository be synced at the same time? anywhere pointing to `dev0` and `0.7.1` to `0.8.0.dev1`?

**Comment by robertnishihara** [comment]
I’ve thought about it, but those links actually won’t work until the wheel
finishes building, which can be several hours after the code is merged.

**Comment by richardliaw** [comment]
Sounds good; can you make a followup PR?

**Review by richardliaw — APPROVED** [review]

**Comment by robertnishihara** [comment]
Done in https://github.com/ray-project/ray/pull/4941.

**Pull request merged**
