### PR TITLE
[train] set auto_transfer cuda device

### LINKED ISSUE #26707: [air/train] Multi GPU training occupies more memory memory on first GPU
### What happened + What you expected to happen

This is a 4 node, 4 GPUs per node setup. I'm running a [GPU benchmark script](https://github.com/ray-project/ray/blob/16500901808923125e18e9cb248456491aec402e/release/air_tests/air_benchmarks/workloads/torch_benchmark.py#L209-L239) comparing training with Ray AIR and Vanilla PyTorch.

When training with Ray AIR, the GPU with ID 0 on the head node occupies more memory than expected. It seems that worker models are instantiated on the GPU. This seems to happen during setup.

This is the output of nvidia-smi for Ray AIR, which shows that the GPU with ID 0 is used in multiple processes:

```
(base) ray@ip-172-31-73-133:~/oss-release-tests$ nvidia-smi
Tue Jul 19 02:13:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1B.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |   5148MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:00:1C.0 Off |                    0 |
| N/A   41C    P0    27W /  70W |   1047MiB / 15360MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            On   | 00000000:00:1D.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |   1031MiB / 15360MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   40C    P0    27W /  70W |   1071MiB / 15360MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      9077      C                                    1303MiB |
|    0   N/A  N/A      9078      C                                    1281MiB |
|    0   N/A  N/A      9079      C                                    1281MiB |
|    0   N/A  N/A      9080      C                                    1281MiB |
|    1   N/A  N/A      9079      C                                    1077MiB |
|    2   N/A  N/A      9078      C                                    1043MiB |
|    3   N/A  N/A      9080      C                                    1071MiB |
+-----------------------------------------------------------------------------+
```

For comparison, when running with the vanilla training script, this is the GPU usage (only one process per GPU ID):

```
(base) ray@ip-172-31-73-133:~/oss-release-tests$ nvidia-smi
Tue Jul 19 02:15:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1B.0 Off |                    0 |
| N/A   42C    P0    35W /  70W |   1325MiB / 15360MiB |     40%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:00:1C.0 Off |                    0 |
| N/A   42C    P0    36W /  70W |   1325MiB / 15360MiB |     43%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            On   | 00000000:00:1D.0 Off |                    0 |
| N/A   43C    P0    36W /  70W |   1325MiB / 15360MiB |     45%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   41C    P0    36W /  70W |   1325MiB / 15360MiB |     46%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     18473      C                                    1323MiB |
|    1   N/A  N/A     18474      C                                    1323MiB |
|    2   N/A  N/A     18475      C                                    1323MiB |
|    3   N/A  N/A     18476      C                                    1323MiB |
+-----------------------------------------------------------------------------+
```

When restarting with Ray AIR and monitoring the GPU usage, this comes up:

```
Tue Jul 19 02:18:43 2022       
...
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     32150      C                                     311MiB |
|    0   N/A  N/A     32151      C                                     309MiB |
|    0   N/A  N/A     32152      C                                     311MiB |
|    0   N/A  N/A     32153      C                                     331MiB |
+-----------------------------------------------------------------------------+
```

a few seconds later:

```
Tue Jul 19 02:18:49 2022       
...
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     32150      C                                    1303MiB |
|    0   N/A  N/A     32151      C                                    1281MiB |
|    0   N/A  N/A     32152      C                                    1281MiB |
|    0   N/A  N/A     32153      C                                    1281MiB |
|    1   N/A  N/A     32151      C                                     769MiB |
|    2   N/A  N/A     32153      C                                     793MiB |
|    3   N/A  N/A     32152      C                                     751MiB |
+-----------------------------------------------------------------------------+
```

It thus seems to be a setup issue.

### Versions / Dependencies

Latest master

### Reproduction script

Run the air_benchmark_torch_mnist_gpu_4x4 release test (preferably manually on anyscale).

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by matthewdeng**
Signed-off-by: Matthew Deng <matt@anyscale.com>

## Why are these changes needed?

This sets the CUDA Stream on the correct device (and not the default one) when calling ` train.torch.prepare_data_loader(auto_transfer=True)`.

**Repro**
```python
import subprocess

from torch.utils.data import DataLoader
from torchvision import datasets

from ray import train
from ray.air.config import ScalingConfig
from ray.train.torch import TorchTrainer


def train_func(config):
    training_data = datasets.FashionMNIST(
        root="/tmp/data_fashion_mnist",
        train=True,
        download=True,
    )
    train_dataloader = DataLoader(training_data)
    train_dataloader = train.torch.prepare_data_loader(train_dataloader, auto_transfer=True)
    subprocess.run(["nvidia-smi"])


if __name__ == "__main__":
    trainer = TorchTrainer(
        train_loop_per_worker=train_func,
        scaling_config=ScalingConfig(
            num_workers=4,
            use_gpu=True,
        ),
    )
    result = trainer.fit()

```

**Before:**
```
(BaseWorkerMixin pid=4197) +-----------------------------------------------------------------------------+
(BaseWorkerMixin pid=4197) | Processes:                                                                  |
(BaseWorkerMixin pid=4197) |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
(BaseWorkerMixin pid=4197) |        ID   ID                                                   Usage      |
(BaseWorkerMixin pid=4197) |=============================================================================|
(BaseWorkerMixin pid=4197) |    0   N/A  N/A     47105      C                                    1281MiB |
(BaseWorkerMixin pid=4197) |    0   N/A  N/A     47106      C                                    1281MiB |
(BaseWorkerMixin pid=4197) |    0   N/A  N/A     47107      C                                    1281MiB |
(BaseWorkerMixin pid=4197) |    0   N/A  N/A     47109      C                                    1281MiB |
(BaseWorkerMixin pid=4197) +-----------------------------------------------------------------------------+
```

**After:**
```
(BaseWorkerMixin pid=5604) +-----------------------------------------------------------------------------+
(BaseWorkerMixin pid=5604) | Processes:                                                                  |
(BaseWorkerMixin pid=5604) |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
(BaseWorkerMixin pid=5604) |        ID   ID                                                   Usage      |
(BaseWorkerMixin pid=5604) |=============================================================================|
(BaseWorkerMixin pid=5604) |    0   N/A  N/A     14123      C                                    1281MiB |
(BaseWorkerMixin pid=5604) |    1   N/A  N/A     14124      C                                    1281MiB |
(BaseWorkerMixin pid=5604) |    2   N/A  N/A     14125      C                                    1281MiB |
(BaseWorkerMixin pid=5604) |    3   N/A  N/A     14126      C                                    1281MiB |
(BaseWorkerMixin pid=5604) +-----------------------------------------------------------------------------+
```

## Related issue number

Closes https://github.com/ray-project/ray/issues/26707

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by JiahaoYao** [comment]
Hi @matthewdeng , could u print out the cuda memory? 

https://discuss.pytorch.org/t/how-to-check-the-gpu-memory-being-used/131220

say 

```python
cuda_mem = [torch.cuda.memory_allocated(i)/1024/1024/1024) for i in range(4)] 
assert min(cuda_mem) == max(cuda_mem) and cuda_memo[0] > 0
```

**Comment by JiahaoYao** [comment]
more reference here: https://stackoverflow.com/questions/58216000/get-total-amount-of-free-gpu-memory-and-available-using-pytorch

**Comment by JiahaoYao** [comment]
i mean in the second case

```python
cuda_memo[0] = 4x1281, cuda_memo[1] = 0, ....
```

**Review by amogkam — APPROVED** [review]
Ah this is a great find!

Do you think we should treat this optimization as experimental and disable by default until we can more rigorously test it?

**Comment by matthewdeng** [comment]
@amogkam hah I was actually thinking the same thing, updated!

**Review by krfricke — APPROVED** [review]
LGTM - this should solve the benchmark script GPU util issue, right?

**Comment by matthewdeng** [comment]
@krfricke yep if you're referring to https://github.com/ray-project/ray/issues/26707!

**Pull request merged**
