### PR TITLE
[Placement Group]Fix actor scheduling with Placement Group bug.

### LINKED ISSUE #15801: Actors not scheduling when some placement groups cannot be placed
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

When you try to create more placement groups than the available resources in the cluster, some of the placement groups are created, and others are pending. 

If you try to schedule actors on all the placement groups, you would expect some of the actors to be scheduled (because some of the placement groups are ready), but others to be pending. 

For some reason, none of the actors seem to be useable. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
See @simon-mo 's repro in the comment below https://github.com/ray-project/ray/issues/15801#issuecomment-842791609

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by clay4megtr**
## Why are these changes needed?
fix #15801 .

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by clay4444** [comment]
some reasons for this bug:
1. ActorCreationTask use the `required_placement_resource` to scheduler, not `required_resource`, for ActorCreationTask, the `required_resource` is empty.
2. The creation of placement group is one by one with a queue, there can only be one at a time, it will insert into the end of the queue if the current placement group create failed.

**Comment by clay4444** [comment]
Let me give an example here:
we want to create 1000 pgs, index as 0 ~ 999,  2 pgs create successfully at first, that means 2 actor creation task will create successfully, then we create the 3rd actor, it will create failed and put into the `infeasible_tasks_`  because the 3rd pg isn't created yet, the `infeasible_tasks_` container is a map that key is `SchedulingClass` and value is a queue. then we add a new node, suppose the 500th pg created successfully at this time, we expected that the 500th actor creation task will be created, but it won't, and the 500th actor creation task is in the same queue with the 3rd actor creation task because their `SchedulingClass` are the same.

**Comment by clay4444** [comment]
hi, @simon-mo , I don't know what your requirement is,  but it seems weird that create 1000 actors with 1000 placement groups,  Is it just a test case or a real situation? 
Also,  if you want to verify this fix with so mush actors and placement groups, you need to wait a little longer because the submission of the tasks is a bit slow for some reason.

**Comment by wuisawesome** [comment]
Looks great!

Can you add a test case though?

**Comment by clay4444** [comment]
@wuisawesome , hmmm. I actually think the python test case that @simon-mo given is a little bit heavy as a python ut, so I didn't add it,  Can I add a c++ test case to verify the actors that use the different placement groups will generate different `SchedulingClass`?

**Comment by ericl** [comment]
Hmm, in this case, I think it would be worth it to add something similar to
Simon's test case. It's a bit heavyweight, but I can't think of anything
simpler that would ensure we don't regress with some similar issue.

Btw, it would be good to check the test doesn't pass before this fix.

**Comment by edoakes** [comment]
@clay4444 the example @simon-mo gave is a real issue we found using Ray Serve. We currently create one placement group per actor because that enables Serve to bypass the autoscaler scaling throttling without needing to have the user modify the upscaling speed or using request_resources (whose semantics wouldn't work with user-created tasks/actors).

**Comment by clay4444** [comment]
> @clay4444 the example @simon-mo gave is a real workload from Ray Serve. We currently create one placement group per actor because that enables Serve to bypass the autoscaler scaling throttling without needing to have the user modify the upscaling speed or using request_resources (whose semantics wouldn't work with user-created tasks/actors).

oh, I got it, so this is the reason why you want the resizing feature of the placement group. right?  @edoakes

**Comment by clay4444** [comment]
@ericl  sorry for the late reply,  I lost my computer at the airport when a business trip.... I will add the test as soon as possible

**Comment by edoakes** [comment]
@clay4444 yep that's exactly right :) then we could just have a single placement group for all of the replicas in a Serve deployment and we could also leverage the placement policies such as PACK, SPREAD, etc.

**Comment by clay4444** [comment]
ping~ @rkooo567 @ericl  @wuisawesome   I have added the test and I tried more than 10 times to make sure this test will fail before this fix.

**Review by rkooo567 — APPROVED** [review]

**Comment by edoakes** [comment]
@simon-mo let's make sure to test the Serve workload and re-enable placement groups once this is merged.

**Comment by clay4444** [comment]
hi, @edoakes   Did you get the message I send to you in slack? I plan to feedback the resizing feature recently, what do you think?    cc @rkooo567

**Comment by simon-mo** [comment]
merged, the only test failing is a doc test that was fixed about 50 commits ago. Thanks @clay4444 for the quick fix.

**Comment by ericl** [comment]
Thanks for the prompt investigation, much appreciated!

**Comment by edoakes** [comment]
@clay4444 that sounds good, the API you sent me looked pretty reasonable but we should get feedback from others. Could you post an RFC issue with the proposed API before opening the PR (or in parallel)?

**Comment by clay4444** [comment]
> @clay4444 that sounds good, the API you sent me looked pretty reasonable but we should get feedback from others. Could you post an RFC issue with the proposed API before opening the PR (or in parallel)?

@edoakes  Yeah~ sure.

**Pull request merged**
