### PR TITLE
[Hotfix] Unbreak lint in master

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
We have to revert two commits together to make lint green.

https://github.com/ray-project/ray/commit/ffcbb30552586216b119cbcf19bbe5c7a716d63b

needs to be reverted due to it breaks documentation build:

```
/Users/simonmo/Desktop/ray/ray/doc/source/rllib/rllib-algorithms.rst:513:Include file '/Users/simonmo/Desktop/ray/ray/rllib/agents/mbmpo/mbmpo.py' not found or reading it failed
```

https://github.com/ray-project/ray/commit/bc3a1d35cf6e9a5fd7eef908a8e76aefb80ce6a9

needs to be reverted due to code formatting failure https://buildkite.com/ray-project/ray-builders-branch/builds/7539#d897c4ed-d43c-41bf-8d9d-454647004da0/1446-1519

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by gjoliver — APPROVED** [review]
thanks

**Review by avnishn — APPROVED** [review]

**Comment by simon-mo** [comment]
verified locally 
- `./scripts/format.sh` passed
- `make html` for doc passed

so this PR has high likelihood of success.

but i'll only merge after lint actually passed.

**Comment by simon-mo** [comment]
lint passed https://buildkite.com/ray-project/ray-builders-pr/builds/32149#18f97416-1ab5-4e11-9a00-f3b3bf34fdb6/1

**Comment by simon-mo** [comment]
@sven1977 FYI for the revert.

**Pull request merged**
