### PR TITLE
[Cleanup] delete remaining protos related to ObjectLocation in GCS

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
Object metadata are fully managed by workers now, so the related protos and logic in GCS are obsolete. Most of the logic has been removed in https://github.com/ray-project/ray/pull/19963. This PR removes some remaining obsolete protos.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by MissiontoMars — APPROVED** [review]
LGTM.

**Review by ericl — COMMENTED** [review]
It looks good, but can you add a description to this PR?

**Comment by mwtian** [comment]
Description added.

**Review by ericl — APPROVED** [review]
Thanks!

**Pull request merged**
