### PR TITLE
[autoscaler] Optimize finding the node id

### PR DESCRIPTION
**Pull request by sriram-anyscale**
## Why are these changes needed?

This is a simple refactoring change and my first PR in ray-project. This change moves an if statement outside of a loop. This way the check is not repeated for each iteration.

## Related issue number

None

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
nice! a couple of housekeeping items: Can we include a bit more detail in the title and description? The idea is that if you're perusing the git log, you should have some idea of what the commit is doing (i.e. that it's related to the autoscaler's node provider as opposed to some loop in Serve).

For example, something like "[autoscaler] Optimize finding the node id" 

In the description, perhaps mention that it's a first PR, since it's a little strange to be doing this type of hyper-optimization here.

**Comment by wuisawesome** [comment]
(After making the changes, you should remove the "author-action-required" label and add a "tests-ok" label)

**Comment by wuisawesome** [comment]
Finally, this codepath is covered by other unit tests, so it's fine to not write a test for this PR, but just for reference, if you wanted to unit test this PR, you could do the following.

1. Create a new test suite (by creating a new file `test_node_provider.py`), or add your test to an existing test suite (for the sake of completeness, let's assume you wanted to create a new test suite for this).
2. Add that test suite to CI by adding it to one of the existing bazel test suites, which are located in `python/ray/tests/BAZEL` (I trust you'd be able to pattern match to figure out how to do this ;) ).
3. Write your test case. We make pretty basic use out of pytest for our unit tests, so essentially as long as the name of the function starts with `test_*` it will get picked up as a test. There are lots of helpful, global test fixtures in `conftest.py`, and in the case of the autoscaler, useful mocks in `test_autoscaler.py`.

**Comment by sriram-anyscale** [comment]
Addressed comments from @wuisawesome

**Comment by wuisawesome** [comment]
Test failures look unrelated (flakey in master). Merging

**Review by wuisawesome — APPROVED** [review]

**Pull request merged**
