### PR TITLE
[Datasets] Make `from_numpy()` more user-friendly.

### LINKED ISSUE #23870: [Datasets] [UX] `from_numpy()` only takes ndarray futures, can silently fail.
`ray.data.from_numpy()` currently expects to be given a list of ndarray futures, instead of handling concrete ndarrays, as expected (and as allowed by other `from_*` APIs, e.g. `from_pandas`). This is bad UX.

### PR DESCRIPTION
**Pull request by clarkzinzow**
`ray.data.from_numpy()` currently expects to be given a list of ndarray futures, instead of handling concrete ndarrays, as expected (and as allowed by other `from_*` APIs, e.g. `from_pandas`). This PR renames the existing `from_numpy` API to `from_numpy_refs`, and exposes `ray.data.from_numpy`, which takes concrete ndarrays (not object references).

## Related issue number

Closes https://github.com/ray-project/ray/issues/23870

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Awesome!

**Review by jianoaix — APPROVED** [review]
Clearly distinguish value v.s. reference semantics looks good, thanks for fixing it.

**Review by ericl — COMMENTED** [review]
Could you also update `dataset.rst` to have these in the big supported input formats list?

**Comment by clarkzinzow** [comment]
@ericl I already checked, we already have `from_numpy` listed, and we don't list developer APIs in that compatibility matrix, so no need to add `from_numpy_refs`.

**Comment by ericl** [comment]
Alright then!

**Pull request merged**
