### PR TITLE
[Doc] [Job Submission] Add warning about entrypoint command in quotes

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
A common error is to wrap the entrypoint command in quotes.  However this leads to errors because bash interprets it as a single command. 

Example:
`ray job submit --working_dir="." -- "python script.py"`
yields
`/bin/sh: 1: python script.py: not found`

This PR adds a warning about this to the docs.

In the future we should consider making this work by removing the quotes internally or by some other solution.  Not sure if there are edge cases we need to think about.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Review by jiaodong — APPROVED** [review]
as a nit, can you also add example of how to pass other args to `python script.py` ?

**Review by DmitriGekhtman — APPROVED** [review]
Hey, thanks for the rapid follow-up to the [user issue](https://github.com/ray-project/kuberay/issues/283#issuecomment-1147941246).

There are likely few use-cases for wrapping the entire entrypoint in quotes.
I wonder if it's possible for the job submission code to log a warning in that case.

**Review by tchordia — COMMENTED** [review]
why doesn't this case work? shouldn't we just support this? otherwise it's hard to escape characters

**Comment by architkulkarni** [comment]
> why doesn't this case work? shouldn't we just support this? otherwise it's hard to escape characters

For escaping I think you can just quote the individual word in the command, you wouldn't need to quote the whole command.

This doesn't work because of how we're using `subprocess`: https://github.com/ray-project/ray/pull/22011

For the API, I think we should match whatever other popular CLI tools do that use ` -- `.  Does anyone know any examples of this?

I can see an argument for why the current behavior is preferred; it doesn't do any custom logic to remove quotes or otherwise process the user's command.  Indeed if I type `"python script.py"` into my terminal with quotes, I get `zsh: command not found: python script.py`.  So the current Jobs CLI matches this result exactly.

**Comment by architkulkarni** [comment]
Linkcheck failure looks unrelated

**Pull request merged**
