### PR TITLE
Multiagent experiment resume

### PR DESCRIPTION
**Pull request by alex-petrenko**
## What do these changes do?

This little change fixes multi-agent experiment resume.
When the configuration is read from .json file is read the entries in `spec['config']['multiagent']['policies']` get converted from tuples to lists, while this function `_validate_multiagent_config` expects tuples and thus fails the experiment.
There does not seem to be any apparent harm in allowing lists here.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Looks good

**Comment by alex-petrenko** [comment]
> Test FAILed.

Judging by the test output, this fail is probably not related to my changes. Is there something I should do?

**Comment by ericl** [comment]
I think the only relevant test is this one (the others are flaky at the moment):
```
28.07s$ flake8 --inline-quotes '"' --no-avoid-escape --exclude=python/ray/core/generated/,doc/source/conf.py,python/ray/cloudpickle/ --ignore=C408,E121,E123,E126,E226,E24,E704,W503,W504,W605
./python/ray/rllib/evaluation/rollout_worker.py:754:80: E501 line too long (83 > 79 characters)
The command "flake8 --inline-quotes '"' --no-avoid-escape --exclude=python/ray/core/generated/,doc/source/conf.py,python/ray/cloudpickle/ --ignore=C408,E121,E123,E126,E226,E24,E704,W503,W504,W605" exited with 1.
44.01s$ ./ci/travis/format.sh --all
From https://github.com/ray-project/ray
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream/master
--- python/ray/rllib/evaluation/rollout_worker.py	(original)
+++ python/ray/rllib/evaluation/rollout_worker.py	(reformatted)
@@ -751,7 +751,8 @@
         if not isinstance(v, (tuple, list)) or len(v) != 4:
             raise ValueError(
                 "policy values must be tuples/lists of "
-                "(cls or None, obs_space, action_space, config), got {}".format(v))
+                "(cls or None, obs_space, action_space, config), got {}".
+                format(v))
         if allow_none_graph and v[0] is None:
             pass
         elif not issubclass(v[0], Policy):
The command "./ci/travis/format.sh --all" exited with 1.```

**Comment by alex-petrenko** [comment]
Ok, I ran the format script on the file. I didn't want to do this for the original commit because it changes a bunch of other things in the file, and (frankly) some of the reformats are quite ugly :)

Hope it'll pass this time!

**Comment by ericl** [comment]
Oh yeah, there's this issue where you have to have a specific version of yapf and flake8 otherwise it will do that -- this pr should fix it: https://github.com/ray-project/ray/pull/5083

**Comment by alex-petrenko** [comment]
```
ERROR: error loading package '': in /Users/travis/build/ray-project/ray/bazel/ray_deps_build_all.bzl: Encountered error while reading extension file 'python/deps.bzl': no such package '@build_stack_rules_proto//python': java.io.IOException: Error downloading [https://github.com/stackb/rules_proto/archive/b93b544f851fdcd3fc5c3d47aee3b7ca158a8841.tar.gz] to /private/var/tmp/_bazel_travis/7c557718f3877739c657a427203800b1/external/build_stack_rules_proto/b93b544f851fdcd3fc5c3d47aee3b7ca158a8841.tar.gz: connect timed out
```

Looks like it could not download one of the dependencies when creating the build.

**Comment by ericl** [comment]
Btw you can avoid building ray with:
https://ray.readthedocs.io/en/latest/rllib-dev.html#development-install

>

**Comment by alex-petrenko** [comment]
> Btw you can avoid building ray with: https://ray.readthedocs.io/en/latest/rllib-dev.html#development-install
> […](#)

That's great but I am commenting on why the build has errored on Travis. Sorry for the confusion.
Good to know though!

**Comment by alex-petrenko** [comment]
@ericl Please let me know if I can do something about the errored test. It's not clear at this point whether it's my fault or not.

**Comment by ericl** [comment]
I pushed a lint fix, I think it should be good after that. A lot of the tests are flaky right now.

**Pull request merged**
