### PR TITLE
Adding pytest flags to measure time elapsed per test case

### PR DESCRIPTION
**Pull request by fcardoso75**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

Tagging @pcmoritz

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Hey @fcardoso75 can you lmk when it is ready to be merged?

**Comment by fcardoso75** [comment]
Hi, SangBin.

Thanks for following up. The build is not delivering the output information
that I wanted and I'm investigating why. I will let you know when it is
ready.

Fabiano

Em ter., 1 de jun. de 2021 às 15:49, SangBin Cho ***@***.***>
escreveu:

**Comment by fcardoso75** [comment]
Please merge these changes.

**Comment by rkooo567** [comment]
Can you merge the latest master? There are concerning number of CI failures (including the lint)

**Comment by fcardoso75** [comment]
Master merged into branch. Build passed.

**Comment by rkooo567** [comment]
Screen Shot 2021-06-09 at 6 40 32 PM

**Comment by pcmoritz** [comment]
@rkooo567 Can you help @fcardoso75 get this PR merged? It looks like the remaining errors are from test timeouts, so maybe the additional metrics have shifted the timing slightly and there needs to be some rebalancing? Or maybe something else is going on if the timing has changed a lot now.

**Comment by rkooo567** [comment]
@pcmoritz if you look at the PR, many of tests are not failing with the timeout  (it is purely just failed), and I cannot find the failure logs from any build. This must be related to this PR's change cuz I can check falure logs from all other PRs out there.

**Pull request closed without merging**
