### PR TITLE
[Multi-tenancy] Delete flag `enable_multi_tenancy` and remove old code path

### LINKED ISSUE #11136: [Multi Tenancy] Remove the feature flag and old code path.
### Describe your feature request

There's an already open PR from @kfstorm. After a single release cycle, if we validate the feature works well, we should remove the feature flag and the old code path. https://github.com/ray-project/ray/pull/10573

### LINKED ISSUE #12035: Update document about code search path
The `--code-search-path` parameter in `ray start` is for clusters with multi-tenancy off. Since now we've enabled multi-tenancy, we should document the new way to pass the code search path, that is, via job config.

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

Since now multi-tenancy is quite stable, we can remove the old code path.

## Related issue number

closes #11136.
closes #12035.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
As discussed, we should probably do this a version after we turn on multi tenancy by default. This is to ensure the stability.

**Comment by rkooo567** [comment]
@kfstorm Can you start working on this after 11/11?

**Comment by kfstorm** [comment]
@rkooo567 Sure.

**Comment by kfstorm** [comment]
@rkooo567 I've updated this PR and I've tested C++ tests and Java tests locally. Let's wait for the CI results. You can start reviewing now.

**Comment by kfstorm** [comment]
@rkooo567 The CI results look promising. Let me merge the latest master and see if the failed tests could pass.

**Comment by rkooo567** [comment]
SGTM.

**Review by rkooo567 — APPROVED** [review]
LGTM!

**Pull request merged**
