### PR TITLE
Remove test_autoscaler_yaml from windows tests

### PR DESCRIPTION
**Pull request by AmeerHajAli**
test_autoscaler_yaml fails on windows. This prevents the test from running on windows.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
Seems like this blacklists the entire test. Can you instead ignore just the failing test case?

**Review by edoakes — APPROVED** [review]
Looks fine. It would be preferable to skip it from in the test using pytest.skipif so that we don't lose track of it. If that's not possible we can merge this.

**Comment by rkooo567** [comment]
Seems like it is still not skipped from the Windows build?

**Comment by Gekho457** [comment]
Ugh, looks it failed on Windows.

**Comment by AmeerHajAli** [comment]
I will go with Edward's suggestion and lets do pytest.skipif :)

**Pull request merged**
