### PR TITLE
[WIP] Update Ray Data pydoc and types to reflect strict mode by default

### PR DESCRIPTION
**Pull request by ericl**
This contains the pydoc changes from https://github.com/ray-project/ray/pull/34643

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
Nice simplification! For future PRs: For map_batches, it might be great to have something like
```
@overload
def map_batch(self, fn: Dict[str, np.array], batch_format="numpy")

@overload
def map_batch(self, fn: pd.DataFrame, batch_format="pandas")

@overload
def map_batch(self, fn: pa.Table, batch_format="pyarrow")
```

or similar to make this as ergonomic as humanly possible (e.g. with people's IDE autocompletion or type checking and docs). This can go a long way in reducting the friction :)

**Comment by ollie-iterators** [comment]
Lint error: python/ray/data/tests/test_pipeline.py:11:1: F401 'ray.data._internal.arrow_block.ArrowRow' imported but unused

**Comment by ericl** [comment]
Yup let me try to do the overload in the next PR. It might be a little tricky to get right so don't want to have it tied up in this one as well.

**Comment by ericl** [comment]
I'm going to close this for now. It might be easiest to merge all the changes atomically, to avoid CI breakages here.

**Pull request closed without merging**
