### PR TITLE
[Train][release_test] Update release tests for xgboost and lightgbm trainer to V2

### PR DESCRIPTION
**Pull request by hongpeng-guo**
## Why are these changes needed?
This PR upgrades the release tests for `XGBoostTrainer` and `LightGBMTrainer` from a previous version to a recent version. Both trainers are now subclass of `DataParallelTrainer`, similar to `TorchTrainer`

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by justinvyu — APPROVED** [review]
Thanks! I just ran the release test, and if that passes, we can merge.

**Comment by justinvyu** [comment]
Release test: https://buildkite.com/ray-project/release/builds/27902

**Review by matthewdeng — APPROVED** [review]

**Comment by hongpeng-guo** [comment]
The new release test link is here: https://buildkite.com/ray-project/release/builds/28263

**Review by hongpeng-guo — COMMENTED** [review]
Update: the release test passed.

**Comment by hongpeng-guo** [comment]
@justinvyu @matthewdeng  Please merge :)

**Pull request merged**
