### PR TITLE
Revert "Revert "Bump pytest from 5.4.3 to 7.0.1""

### PR DESCRIPTION
**Pull request by Riatre**
## Why are these changes needed?

See #26334, #26517.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Riatre** [comment]
Test result with https://github.com/ray-project/ray/commit/0c5e796b0eb437d64922f66749c61b0412486970 ("debug: run all tests"): https://buildkite.com/ray-project/ray-builders-pr/builds/38573

Windows failure: https://github.com/ray-project/ray/pull/26615

**Review by scv119 — APPROVED** [review]
second time is the charm!

**Review by jianoaix — APPROVED** [review]

**Comment by pcmoritz** [comment]
fixed a merge conflict that just came up, let's merge it as soon as tests pass again to avoid further conflicts :)

**Review by pcmoritz — APPROVED** [review]

**Review by ericl — APPROVED** [review]

**Review by ericl — APPROVED** [review]

**Review by jjyao — APPROVED** [review]

**Review by avnishn — APPROVED** [review]
If passing the CI lgtm

**Comment by pcmoritz** [comment]
@Riatre There are some more failures on the CI:

```
https://buildkite.com/ray-project/ray-builders-pr/builds/38794#01821334-f5ba-469a-a8dc-d16c56b5dc27

FileNotFoundError: /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/python/ray/data/tests/test_dataset_formats.runfiles/com_github_ray_project_ray/python/ray/data/tests/image-folder
```

```
https://buildkite.com/ray-project/ray-builders-pr/builds/38794#01821334-f4dc-4eec-9ccd-57da6b936552

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/rllib/test_dataset_reader.runfiles/com_github_ray_project_ray/rllib/tests/data/pendulum/enormous.zip'
```

**Comment by Riatre** [comment]
Pushed a new commit to fix the two tests merged since last rebase (#26458 and #24641).

Windows failure looks unrelated, it segfaults:

```
Windows fatal exception: access violation
```

**Pull request merged**
