### PR TITLE
[CI][GCE/1] Setup dependencies to run GCE tests in buildkite

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?
This PR setups several things:
- Add google-cloud-storage so we can access Google Cloud Storage at runtime
- A new test environment that points go anyscale-gce-cloud cluster, GCS project and credential
- A workload identity federation config to allow AWS iam to work as a GCE iam. This config file has no secret information and be stored publicly, according to Google (https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#use_the_credential_configuration_to_access)

No new runtime code, later PR will use this to setup test runs later.

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] CI/CD test https://buildkite.com/ray-project/release-tests-pr/builds/32119

### CODE REVIEW

**Comment by can-anyscale** [comment]
Any good soul willing to accept; just configuration files so will break nothing @aslonnie @krfricke @Yard1

**Review by Yard1 — APPROVED** [review]
just kicked off one test to be sure that the google cloud package doesn't break anything https://buildkite.com/ray-project/release-tests-pr/builds/32293

**Comment by can-anyscale** [comment]
Thank you!

**Comment by can-anyscale** [comment]
Or if @scv119 can help merge. Thanks!

**Review by aslonnie — APPROVED** [review]
(providing spiritual support)

**Pull request merged**
