### PR TITLE
[RLlib] Enable training with offline data for DQN

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
Since importance weights are computed in postprocessing, offline data will not provide them in many cases and we whould set them to ones.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Review by avnishn — APPROVED** [review]
seems good enough to me

**Comment by Rohan138** [comment]
Actually, can we keep this open for now? We should still fix this because offline DQN is currently only working with prioritized replay.

**Comment by Rohan138** [comment]
This also means DQN isn't doing postprocessing for offline data

**Comment by ArturNiederfahrenhorst** [comment]
> Actually, can we keep this open for now? We should still fix this because offline DQN is currently only working with prioritized replay.

Sure thing. You are taking care of this PR I reason?

**Comment by Rohan138** [comment]
Closing: @charlesjsun figured out the fix, we just need to set `.offline_data(postprocess_inputs=True)`. Should probably make this True for offline algorithms i.e. `input != sampler`.

**Pull request closed without merging**
