### PR TITLE
[Core] GCS Actor management on by default.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

As there's no more blocker for GCS actor management, we will turn it on by default.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by stephanie-wang** [comment]
Shouldn't we wait for #8679?

**Comment by rkooo567** [comment]
#8679 happens regardless of gcs actor management turned on or off (it happens as long as GCS service is on). I realized when I reproduced the problem, GCS actor management was off.

**Comment by stephanie-wang** [comment]
Ohh gotcha, makes sense! Let's remember to remove this flag after the next release as well.

**Review by stephanie-wang — APPROVED** [review]

**Comment by rkooo567** [comment]
@stephanie-wang Actually, should we just remove all the flags after releasing the next version? Test failures in CI makes me concerned me..

**Review by ffbin — APPROVED** [review]

**Pull request merged**
