### PR TITLE
Add nightly test for alpa opt 30b inference.

### PR DESCRIPTION
**Pull request by gjoliver**
## Why are these changes needed?

Add a nightly test for alpa inference.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ollie-iterators** [comment]
It looks like the book lint errors that happen with this PR are different than the book lint issues that happen when a PR gets merged. They are:


dashboard/modules/job/common.py:274:16: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/_private/state.py:170:17: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/data/_internal/lazy_block_list.py:347:23: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/data/_internal/plan.py:871:26: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/data/_internal/plan.py:872:26: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/data/dataset.py:1273:28: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/train/huggingface/_huggingface_utils.py:75:23: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/tune/execution/placement_groups.py:116:14: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/tune/search/optuna/optuna_search.py:590:40: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/util/client/common.py:692:16: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/util/client/server/dataservicer.py:36:16: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/util/client/server/dataservicer.py:159:20: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/util/client/server/server.py:58:20: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/util/client/server/server.py:457:20: C416 Unnecessary dict comprehension - rewrite using dict().
python/ray/util/client/worker.py:722:27: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/algorithms/sac/tests/test_sac.py:516:13: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/core/learner/learner.py:308:33: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/env/remote_base_env.py:335:20: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/env/vector_env.py:503:20: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/env/wrappers/open_spiel.py:54:23: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/env/wrappers/open_spiel.py:66:19: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/models/torch/mingpt.py:192:18: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/dynamic_tf_policy.py:788:38: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/dynamic_tf_policy_v2.py:753:38: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/eager_tf_policy.py:1034:46: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/eager_tf_policy.py:1041:32: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/eager_tf_policy.py:1044:21: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/eager_tf_policy_v2.py:1018:42: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/eager_tf_policy_v2.py:1024:24: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/eager_tf_policy_v2.py:1025:24: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/sample_batch.py:344:17: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/sample_batch.py:389:24: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/sample_batch.py:451:24: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/sample_batch.py:783:24: C416 Unnecessary dict comprehension - rewrite using dict().
rllib/policy/tf_policy.py:422:31: C416 Unnecessary dict comprehension - rewrite using dict().

**Review by krfricke — APPROVED** [review]
Looks good to me!

**Comment by richardliaw** [comment]
Please add me as reviewer for these PRs, thanks!

**Comment by gjoliver** [comment]
> Please add me as reviewer for these PRs, thanks!

sure! do you have any comments for this one. or can I move on to the next one now?

**Comment by gjoliver** [comment]
ok, I am gonna merge this now to move thing forward.
will update the names of these scripts when the 66b example is merged anyways.

**Pull request merged**
