### PR TITLE
[Serve] [Docs] Change incorrect Serve app name in Stable Diffusion tutorial

### PR DESCRIPTION
**Pull request by robin-anyscale**
ray serve command was not matching the correct object

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by shrekris-anyscale — COMMENTED** [review]
Thanks for catching this! Could we change the variable name to `entrypoint`, so it matches the `text-classification` tutorial?

We would need to change [this variable](https://github.com/ray-project/ray/blob/51569e61b631ac381df5e33337927709b664cff6/doc/source/serve/doc_code/stable_diffusion.py#L62) to `entrypoint`.

**Comment by robin-anyscale** [comment]
@shrekris-anyscale Good point. Changed to entrypoint to maintain consistently across tutorials.

**Review by shrekris-anyscale — COMMENTED** [review]
Nice! Could you also update [this line](https://github.com/ray-project/ray/pull/34426/files#diff-528fbb7f4a8e2bad4f0306f86023198fe8425bef8a153b78e3f46254a5386e12R91) with the new variable name, so the test runs successfully?

**Review by shrekris-anyscale — APPROVED** [review]
Nice work, thanks for the changes!

**Comment by architkulkarni** [comment]
Lint failure on `bazel.py`, unrelated
GPU test failure `huggingface_text_classification` unrelated

**Pull request merged**
