### PR TITLE
[Cherry-pick][3/N] Streaming Generator. E2e integration (#35325)

### PR DESCRIPTION
**Pull request by rkooo567**
This PR implements the e2e integration of previous APIs to the Cython execution path. This PR introduces a new private API num_returns="streaming", which works independently from num_returns="dynamic". Note that the dynamic return will be replaced by this implementation once dataset integration is finished.

After this PR, the following features will work.

num_returns="streaming" will create a generator
Users can access the objects via generator which follows the standard python generator interface. Exception & system level failures are handled correctly. The return values will be available before tasks finish if you specify num_returns="streaming" for both tasks and actors. The async actor will be implemented in a follow up PR, and when that's merged, serve can use this feature.

## Related issue number

https://github.com/ray-project/ray/issues/35634

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by zhe-thoughts — APPROVED** [review]
Let's pick and be careful about potential issues. cc @ArturNiederfahrenhorst and @can-anyscale

**Comment by rkooo567** [comment]
The test_generator failure is due to timeout. We should increase the timeout for this test. I will make a PR to the master and cherry pick separately

**Comment by zhe-thoughts** [comment]
@rkooo567 : quick note, @ArturNiederfahrenhorst should merge actually.

**Comment by rkooo567** [comment]
Oops... yeah he told me about this last time. Sorry for merging this @ArturNiederfahrenhorst...

**Comment by ArturNiederfahrenhorst** [comment]
I don't mind really, it's just hard to keep an overview and an overview is what we want when things break. I've included this PR in the xls 🙂

**Comment by rkooo567** [comment]
Btw this also has been merged in case it is not tracked https://github.com/ray-project/ray/pull/35707#pullrequestreview-1441809575

**Pull request merged**
