### PR TITLE
[rllib] Rollout extensions

### PR DESCRIPTION
**Pull request by DaveyBiggers**
## What this PR addds:

New command-line parameters for the rollout.py script:

* --episodes option to generate set number of episodes (overrides the --steps setting)
* --use-shelve option to store rollouts in a python shelf db file rather than one flat pickle
* --track-progress option to store current progress in a temp file adjacent to the rollout file
* --monitor option to wrap environment in gym monitor, in order to record mp4s
* --save-info option to include the step `info` field in the saved information

It also now records the ray version number in the checkpoint metadata files.

## Why are these changes needed?

* For analysing rollouts, it is often useful to work with whole episodes - specifying the number of _steps_ to rollout means that the last episode in the generated file is often incomplete. If the number of steps varies per episode, there is no current way to ask for, say, 10 whole episodes. The `--episodes` option addresses this.
* The current behaviour waits until all rollouts have been generated, and only _then_ attempts to save them to disk. If anything goes wrong in the generation process, or if the user specified an invalid `out` path, all is lost. If your observations are large, and you request a large number of steps, memory could easily become an issue, also potentially resulting in all trajectories being lost. Finally, if everything _does_ run through to completion, the resulting pickle file could be enormous, which can be inconvenient for users down the line. Since Python doesn't allow partial loading or streaming of pickle files, there is no way to (for example) sample trajectories from the rollouts without first loading the entire file into memory. The `--use-shelve` option provides a work-around for this - if used, it will save each episode as it is completed (which guards against data loss during the generation process), and it also provides a way to query the resulting trajectories without needing to deal with them all en masse.
* If attempting to automate rollout generation, it can be useful to know how far through the generation process we are. In the simple case of a single user running rollout.py and waiting, this is less important, but in cases where you might not have access to rollout.py's stdout, there is currently no way to know how things are progressing. (A typical use-case might be running parallel rollout.py scripts in a cluster setting.) The `--track-progress` option adds a small file in the requested rollout location which contains an indication of the progress - eg "20 / 100 episodes completed", or "1000 / 2000000 steps completed", etc. (depending on whether --steps or --episodes was used.)
* At the moment, it's not easy to request video of the rollouts. While `"monitor":true` could be passed in to the script via the configs setting, there are some limitations to this approach. Firstly, there is no way to change _where_ the videos will be stored (it's automatically set to the `local_dir` variable, which is not configurable via rollout.py). Secondly, there is no way to change the monitor recording schedule from the default (which records only the 1st, 8th, 27th, 64th... 1000th, 2000th, etc episodes). If you want to, say, run rollout.py to generate 20 videos, you'd need to run for 11,000 episodes. Passing the `--monitor` flag means every episode will be recorded, and the mp4s will be saved alongside the trajectories.
* In custom environments, the `info` field returned from the `step()` function is often used for custom metrics or other useful diagnostics. At the moment, this is thrown away, rather than saved into the trajectory. The `--save-info` flag allows this to be kept.
* At the moment, the checkpoint file format isn't versioned, and changes to Ray often mean breaking changes to the checkpoint files. If the version of Ray that created the checkpoints is different to the version of Ray that is attempting to use them to roll out, strange errors can occur. There's currently no way to know which version of Ray was responsible for creating the checkpoints (other than manual book-keeping by the user). The change to `trainable.py` in this PR means that the Ray version is saved into the checkpoint metadata, providing an easy way to ensure that the correct version of Ray can be used for rolling out in the future.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing.

### CODE REVIEW

**Comment by ericl** [comment]
@AmeerHajAli want to take a look at this?

**Comment by AmeerHajAli** [comment]
@ericl, sure.

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
jenkins retest this please

**Comment by AmeerHajAli** [comment]
jenkins retest this please

**Comment by AmeerHajAli** [comment]
The code looks good to me.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Great, merging!

**Comment by AmeerHajAli** [comment]
Thanks @DaveyBiggers!

**Pull request merged**
