### PR TITLE
[core][cherry-pick] Pick of autoscaler v2 consistency fix

### PR DESCRIPTION
**Pull request by vitsai**
Pick of https://github.com/ray-project/ray/pull/40369

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
@vitsai @jjyao @rickyyx  Should we have this in 2.8 or leave to 2.9? The entire ASv2 will be released in 2.9 right?

**Comment by vitsai** [comment]
For context, many users have brought up the issue: https://github.com/ray-project/ray/issues/36926

**Review by zhe-thoughts — APPROVED** [review]
I see, and thanks @vitsai for pointing out. We should pick this one

**Comment by rickyyx** [comment]
> @vitsai @jjyao @rickyyx Should we have this in 2.8 or leave to 2.9? The entire ASv2 will be released in 2.9 right?

This is to fix the issue with product autoscaler. And once we have v1 fixed (in another PR) or when we roll out OSS ASv2 in 2.9, we should have resolved this issue for OSS users as well.

**Pull request merged**
