### PR TITLE
Adds a note on how to avoid contention when using PyTorch.

### PR DESCRIPTION
**Pull request by andyljones**
This adds a short note to the troubleshooting readme on how to avoid contention in PyTorch.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@andyljones, so are you saying that `torch.set_num_threads(1)` doesn't work? Or are you saying that torch appears to be using all of the cores but it actually isn't using all of the cores?

**Comment by andyljones** [comment]
The latter - it appears to be using all cores, but it badly underperforms unless `torch.set_num_threads(1)` is called.

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
Thanks. One thing I often do in this case (on Linux) is

```python
import psutil

@ray.remote
def f(i):
    psutil.Process().cpu_affinity([i])
    # All subsequent work should just use CPU core i
```

**Comment by jaks19** [comment]
This one-liner is a life changer!!
`torch.set_num_threads(1)`

I was implementing a Parameter server and I was really confused for more than **a month** about why performance on a 56 CPU machine is the same as locally on my laptop. I tried tons of different variants, changing which component of my system is the bottleneck etc, and nothing worked. Then decided to just use the python multiprocessing package instead. Same thing happened.

Finally saw [the troubleshooting guide](https://ray.readthedocs.io/en/latest/troubleshooting.html) and that one line worked wonders!

It would be great if this is emphasized more than it currently is. I mainly used the Ray Documentation, Release 0.7.0.dev3 pdf and never saw this. Now that I am aware of it I see it is on page 219. Maybe readers could be warned of it earlier? 

Also I am not sure if this is possible, but if within a remote process, a user is using pytorch, it would be awesome to just throw in a warning of some sort. 

It would help save time and money. Thanks.

**Pull request merged**
