### PR TITLE
[Jobs] [CI] Add multinode and GPU release test for Jobs

### PR DESCRIPTION
**Pull request by architkulkarni**
Followup to #28654 
- Adds a minimal test which connects to the Ray cluster remotely from the CI machine.  (To do this we use the `type: job` option which is already provided by the release test infrastructure, but is only used by one test right now.) Previously all Jobs tests ran a JobSubmissionClient from the head node.
- Adds release tests for https://github.com/ray-project/ray/issues/24455.
  - Checks that by default, GPUs are available in the driver script (by default the driver is scheduled on the head node, and the head node has a GPU in this test).
  - Checks that if a positive `num_gpus` is passed to the Jobs API, the driver script is scheduled on a node which has a GPU (as opposed to the head node, which is the default and which does not have a GPU in this test).
  - For both of the above, checks that GPUs are available to tasks scheduled from the driver script.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Looks good, but let's at least run a few tasks in each of the drivers and check that they get scheduled across the nodes. same for the GPUs one but have some tasks use GPUs.

You could replace the existing `len(ray.nodes())` check and implement it by spawning tasks that use `get_runtime_context()` to get their node_id and want until all of the nodes are seen.

**Review by edoakes — CHANGES_REQUESTED** [review]
oops meant to just comment not approve on last one

**Comment by architkulkarni** [comment]
@edoakes Makes sense, updated

**Review by edoakes — APPROVED** [review]

**Comment by architkulkarni** [comment]
Screen Shot 2022-11-18 at 1 36 36 PM
New tests passed.

Linkcheck failure (cluster/kubernetes/index: line    1) broken    https://github.com/ray-project/ray/tree/master/python/ray/ray_operator - 404 Client Error: Not Found for url: https://github.com/ray-project/ray/tree/master/python/ray/ray_operator
Unrelated

**Pull request merged**
