### PR TITLE
 remove redundant scaler of l2 reg

### PR DESCRIPTION
**Pull request by joneswong**
## What do these changes do?
remove redundant scaler (0.5) of l2 regularization from ddpg_policy.py

## Related issue number
#5047 

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Some linting errors: https://travis-ci.com/ray-project/ray/jobs/215106817

**Comment by simon-mo** [comment]
Hi @joneswong, thanks for the PR. Would you mind pushing from a fork next time? so we can keep the main repo clean. 😃

**Comment by simon-mo** [comment]
It seems the branch `dev_071_fix_l2reg` is related as well.

**Comment by joneswong** [comment]
> Hi @joneswong, thanks for the PR. Would you mind pushing from a fork next time? so we can keep the main repo clean.

I see. I will invoke pull-request from Alibaba/ray next time.

**Comment by joneswong** [comment]
I made lint calibration but still some errors. Do they matter? sorry but i cannot figure out them.

**Comment by ericl** [comment]
Lint looks good now, I triggered a retest.

**Comment by joneswong** [comment]
jenkins test again

**Comment by joneswong** [comment]
> jenkins test again

@ericl  Hi Eric, I don't know how to re-trigger a check. Could you help me handle this pr, so that I can do this re-test by myself in the future? Thanks.

**Pull request merged**
