### PR TITLE
Unify quote style in codebase

### PR DESCRIPTION
**Pull request by alok**
## What do these changes do?

1. Adds flake8-quotes, which checks for idiomatic Python quoting (single quotes
   and double quotes for docstrings, except where there's a single quote inside
   the string).
2. Adds script that users can run themselves to fix quote styles.
3. Applies changes to codebase.

## Related issue number

None.

### CODE REVIEW

**Comment by robertnishihara** [comment]
I like the idea, why close this PR?

**Comment by richardliaw** [comment]
Oh I just didn't now who would review this PR and didn't seem particularly urgent (in discussion offline); however, if you're up to review, @alok could reopen :)

**Comment by concretevitamin** [comment]
Yes, single quotes are lovely, took less effort to type than holding down
shift.  One counterargument that can be made is that one should maintain
consistency with C++.  I personally slightly lean towards preferring single
quotes in Python.

**Comment by alok** [comment]
@robertnishihara  I'd be happy to reopen the PR. I don't actually care if we have single or double quotes, I just care that we have one style. I picked single quotes because that's the standard for python. It really bugs me that even in a *single file*, the quote style isn't consistent (see `rllib/train.py` for use of both quote styles. I picked that file at random, so I'm sure there's more.)

FWIW, this PR may not need a line by line review of all 6k lines. I use [unify](https://github.com/myint/unify) in all my personal projects and I've never had any issues, and neither have any of the users of unify or [pyformat, which uses unify internally](https://github.com/myint/pyformat). They have a total of 100 github stars, and looking through their github issues, no one has reported an issue with the quote unification.

**Pull request closed without merging**
