### PR TITLE
[Docs] Fix `:book: Doctest (GPU)`

### PR DESCRIPTION
**Pull request by bveeramani**
**Depends on**:
- [ ] #36359 

## Why are these changes needed?

#36206 replaced `:options: +MOCK` with `:skipif: True` in `batch_inference.rst`. As a result, doctest is failing: https://buildkite.com/ray-project/oss-ci-build-pr/builds/25117#0188a1b9-31f9-47df-89cb-f508a90685d9. 

This PR reverts the change.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by angelinalg — APPROVED** [review]

**Comment by raulchen** [comment]
there is still a doc test failure. related? https://buildkite.com/ray-project/oss-ci-build-pr/builds/25377#0188b64d-bf3b-4ec2-8ce8-6df2a36cabc6

**Comment by bveeramani** [comment]
> there is still a doc test failure. related? https://buildkite.com/ray-project/oss-ci-build-pr/builds/25377#0188b64d-bf3b-4ec2-8ce8-6df2a36cabc6

That's for the CPU doctest (this PR fixes the GPU doctest), and that's a known flaky example: https://github.com/ray-project/ray/pull/36384.

**Review by raulchen — APPROVED** [review]

**Comment by raulchen** [comment]
is this ready for merge?  there is a dependency not merged yet.

**Comment by bveeramani** [comment]
> is this ready for merge? there is a dependency not merged yet.

Both PRs are ready to merge. Could you first merge https://github.com/ray-project/ray/pull/36359 and then this PR?

**Pull request merged**
