### PR TITLE
[minor] improve warning message for Ray

### PR DESCRIPTION
**Pull request by richardliaw**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — APPROVED** [review]
Looks good. @AmeerHajAli can we deprecate non-multi-node-type cluster configs yet? That would definitely make things simpler.

**Comment by AmeerHajAli** [comment]
@edoakes, what do you mean? They are already deprecated in our defaults/examples. All our defaults/examples are multi node (check it out in aws/example-full.yaml for example or the documentation).

**Comment by edoakes** [comment]
@AmeerHajAli I mean remove the old code and only support multi-node

**Comment by AmeerHajAli** [comment]
> @AmeerHajAli I mean remove the old code and only support multi-node types

ahh, I will see if we can fit this into the Q2 planning.

**Pull request merged**
