### PR TITLE
[release/air] Fix `air_example_gptj_deepspeed_fine_tuning.gce` failing to pull model from a public s3 bucket

### LINKED ISSUE #36274: [release/air] `air_example_gptj_deepspeed_fine_tuning.gce` release test is failing
This release test fails due to not being able to download the model from AWS s3:
* [Job link](https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_jtk5fb36hl4tihunkqblrpi8m)
* [Buildkite](https://buildkite.com/ray-project/release-tests-branch/builds/1743#01887f81-ce97-47ac-a7d5-bc8306e55776)

Error log:

```python
    subprocess.run(
        [
            "aws",
            "s3",
            "sync",
            "--quiet",
            "s3://large-dl-models-mirror/models--EleutherAI--gpt-j-6B/main/",
            os.path.join(path, "snapshots", "main"),
        ]
    )  # aws s3 sync fails on GCE
    with open(os.path.join(path, "snapshots", "main", "hash"), "r") as f:
        f_hash = f.read().strip()
```

```
Traceback (most recent call last):
  File "/tmp/tmp7_lq_gyw", line 146, in <module>
    _ = run_on_every_node(download_model)
  File "/tmp/tmp7_lq_gyw", line 113, in run_on_every_node
    return ray.get(refs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2540, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(FileNotFoundError): ray::download_model() (pid=6869, ip=10.138.1.165)
  File "/tmp/tmp7_lq_gyw", line 137, in download_model
FileNotFoundError: [Errno 2] No such file or directory: '/home/ray/.cache/huggingface/hub/models--EleutherAI--gpt-j-6B/snapshots/main/hash'
```

### LINKED ISSUE #36772: [Train] `TransformersTrainer` doesn't work with `datasets==2.13.1`
### What happened + What you expected to happen

Might be caused by https://github.com/huggingface/datasets/pull/5852/files#diff-02930e1d966f4b41f9ddf15d961f16f5466d9bee583138657018c7329f71aa43

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2540, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::_Inner.train() (pid=3729, ip=10.0.0.229, actor_id=615f1285d041de794d0ef0be01000000, repr=TransformersTrainer)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 389, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 54, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(AttributeError): ray::_RayTrainWorker__execute.get_next() (pid=4278, ip=10.0.0.229, actor_id=2cc5412a2d35204211975fd301000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f9b5bfa1240>)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/worker_group.py", line 32, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/utils.py", line 129, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/huggingface/transformers/transformers_trainer.py", line 482, in _huggingface_train_loop_per_worker
    trainer.train()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1317, in train
    return inner_training_loop(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1528, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data.append(next(self.dataset_iter))
  File "/home/ray/anaconda3/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 772, in __iter__
    for element in self.dataset:
  File "/home/ray/anaconda3/lib/python3.10/site-packages/datasets/iterable_dataset.py", line 1344, in __iter__
    if self._formatting and (ex_iterable.iter_arrow or self._formatting.format_type == "arrow"):
AttributeError: 'RayDatasetHFIterable' object has no attribute 'iter_arrow'
```

### Versions / Dependencies

datasets: 2.13.1
transformers: 4.19.1
ray: a03efd9931128d387649dd48b0e4864b43d3bfb4

### Reproduction script

```python
import transformers

# Hugging Face imports
from datasets import load_dataset
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer

import ray
from ray.air.config import ScalingConfig
from ray.train.huggingface import TransformersTrainer

# If using GPUs, set this to True.
use_gpu = False

model_checkpoint = "gpt2"
tokenizer_checkpoint = "sgugger/gpt2-like-tokenizer"
block_size = 128

datasets = load_dataset("wikitext", "wikitext-2-raw-v1")
tokenizer = AutoTokenizer.from_pretrained(tokenizer_checkpoint)


def tokenize_function(examples):
    return tokenizer(examples["text"])


tokenized_datasets = datasets.map(
    tokenize_function, batched=True, num_proc=1, remove_columns=["text"]
)


def group_texts(examples):
    # Concatenate all texts.
    concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])
    # We drop the small remainder, we could add padding if the model
    # supported it.
    # instead of this drop, you can customize this part to your needs.
    total_length = (total_length // block_size) * block_size
    # Split by chunks of max_len.
    result = {
        k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
        for k, t in concatenated_examples.items()
    }
    result["labels"] = result["input_ids"].copy()
    return result


lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    batch_size=1000,
    num_proc=1,
)
ray_train_ds = ray.data.from_huggingface(lm_datasets["train"])
ray_evaluation_ds = ray.data.from_huggingface(lm_datasets["validation"])


def trainer_init_per_worker(train_dataset, eval_dataset, **config):
    model_config = AutoConfig.from_pretrained(model_checkpoint)
    model = AutoModelForCausalLM.from_config(model_config)
    args = transformers.TrainingArguments(
        output_dir=f"{model_checkpoint}-wikitext2",
        evaluation_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        learning_rate=2e-5,
        weight_decay=0.01,
        no_cuda=(not use_gpu),
    )
    return transformers.Trainer(
        model=model,
        args=args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
    )


scaling_config = ScalingConfig(num_workers=3, use_gpu=use_gpu)
trainer = TransformersTrainer(
    trainer_init_per_worker=trainer_init_per_worker,
    scaling_config=scaling_config,
    datasets={"train": ray_train_ds, "evaluation": ray_evaluation_ds},
)
result = trainer.fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by justinvyu**
## Why are these changes needed?

This PR fixes the `air_example_gptj_deepspeed_fine_tuning.gce` release test. It was failing due to our GCE nodes not having an AWS credentials file. This is not needed due to the s3 bucket being public, so we just pass a `--no-sign-request` flag to use AWS cli as an anonymous user. This also removes the `--quiet` flag since this cell is not shown to users anyways, and it'd help us catch some aws cli error in the future.

This PR also fixes the recent `datasets==2.13.0` breaking `TransformersTrainer`.
## Other notes

1. I tried switching to `IterableDataset.from_generator` to avoid using these semi-private `ExamplesIterable` way of creating the iterable dataset, but this led to an infinite recursive pickling error.
2. I switched to using the base class instead of `ExamplesIterable` because we don't use anything in `ExamplesIterable` anyways.
3. I will leave bumping the `datasets` pinned version to another PR.

## Related issue number

Closes https://github.com/ray-project/ray/issues/36274 and fixes https://github.com/ray-project/ray/issues/36772

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by justinvyu** [comment]
Running release test: https://buildkite.com/ray-project/release-tests-pr/builds/41795

**Comment by justinvyu** [comment]
GCE:
```
Training finished iteration 85 at 2023-06-09 18:01:20. Total running time: 55min 9s
╭────────────────────────────────────╮
│ Training result                    │
├────────────────────────────────────┤
│ time_this_iter_s           104.014 │
│ time_total_s               3301.77 │
│ training_iteration              85 │
│ epoch                            1 │
│ learning_rate                    0 │
│ loss                        0.0715 │
│ step                            85 │
│ train_loss                 0.32492 │
│ train_runtime              3058.86 │
│ train_samples_per_second     0.441 │
│ train_steps_per_second       0.028 │
╰────────────────────────────────────╯
```

AWS:
```
+---------------------------------+------------+------------------+--------+------------------+--------+-----------------+---------+
| Trial name                      | status     | loc              |   iter |   total time (s) |   loss |   learning_rate |   epoch |
|---------------------------------+------------+------------------+--------+------------------+--------+-----------------+---------|
| TransformersTrainer_85e6a_00000 | TERMINATED | 10.0.59.140:4477 |     85 |          2708.04 | 0.0715 |     4.70588e-07 |       1 |
+---------------------------------+------------+------------------+--------+------------------+--------+-----------------+---------+
```

Timeout = 1 hour, so the GCE one failed.

**Review by krfricke — COMMENTED** [review]
Generally looks good to me but it looks like the test timed out - should we increase the timeout here?

**Comment by justinvyu** [comment]
@krfricke The GCE version is taking like 10 minutes longer for some reason. The instances used between GCE and AWS are slightly different which could be the reason, but I'm wondering if there's another underlying problem here.

Let's increase the timeout as you suggest and then we can investigate what takes the GCE 10 minutes longer after.

**Comment by justinvyu** [comment]
The tests are now failing due to a new HF datasets release. This PR now also includes a fix for that.

See release tests running here: https://buildkite.com/ray-project/release-tests-pr/builds/42420

**Review by Yard1 — APPROVED** [review]
Thanks! Looks good to me.

**Review by krfricke — APPROVED** [review]

**Pull request merged**
