### PR TITLE
Fix broken SVG in Ask AI Dialog

### PR DESCRIPTION
**Pull request by cristianjd**
## Why are these changes needed?

The copy button svg in the "Ask AI" tool is broken on all pages outside of the home page. Fixed by setting the svg path as absolute with a root of `window.DOCUMENTATION_OPTIONS.URL_ROOT`

## Related issue number

https://github.com/ray-project/ray/issues/46137

## Checks

- [X ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [X ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [X ] This PR is not tested :(
Manually tested

### CODE REVIEW

**Comment by peytondmurray** [comment]
Huh, cool, I had no idea that `DOCUMENTATION_OPTIONS` existed - there's nothing about it on the sphinx docs :/. Do you have any idea where this is being set?

**Comment by cristianjd** [comment]
@peytondmurray So looks like that specific root URL was removed in a PR after our current version but the documentation options were set here https://github.com/ray-project/ray/pull/46236. Seems like a useful group of data to be accessible in JS

**Review by can-anyscale — APPROVED** [review]
please continue the conversation if needed; a stamp from code owner so you can merge when ready

**Comment by cristianjd** [comment]
@peytondmurray updated to add a script tag in the head to hold JS data to be available on every page. then passed through the specific path to the copy icon

**Comment by peytondmurray** [comment]
Tested, looks like it's working. Thank you! :ship:

**Review by peytondmurray — APPROVED** [review]

**Pull request merged**
