### PR TITLE
unpin pyarrow for windows

### PR DESCRIPTION
**Pull request by mattip**
## Why are these changes needed?
Toward fixing #38300 

PR #29993 added a local ray fix for issue apache/arrow#26685, but at the time windows failed the tests with pyarrow7. In issue #38300 the suggested fix was
- [x] release the pin
- [ ] add a version check when serializing a pyarrow dataset
- [ ] Handle any remaining behavior gap related to `_register_arrow_data_serializer()`, and include an environment variable to override the Pyarrow version check
  

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mattip** [comment]
step 1: release the pin. Let's see what tests fail?

**Comment by mattip** [comment]
I also ran the test added in #29993 locally and it passed.

**Comment by mattip** [comment]
cc @anyscalesam

**Comment by mattip** [comment]
I think releasing the pin is enough to solve the issue.

**Comment by mattip** [comment]
I don't think the CI failure is related. It would be nice to get some eyes on this.

**Comment by scottjlee** [comment]
Contents of PR LGTM - I triggered a postmerge test to see how things look on windows side.
https://buildkite.com/ray-project/postmerge/builds/2689

**Review by scottjlee — APPROVED** [review]
LGTM, @c21 to approve and merge

**Review by edoakes — APPROVED** [review]

**Comment by RocketRider** [comment]
Could we pick that for 2.9.2?

**Comment by tonyhoo** [comment]
When will this fix be released. It introduced installation [issue](https://github.com/autogluon/autogluon/issues/3807) for AutoGluon on Windows platform with Python 3.11

**Pull request merged**
