### PR TITLE
[CI] use clang for C++ tests

### PR DESCRIPTION
**Pull request by scv119**
Introducing clang-12 into our CI pipeline to run C++ tests.

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]

**Comment by scv119** [comment]
to fix build failures

**Review by mwtian — APPROVED** [review]

**Comment by scv119** [comment]
image

**Comment by scv119** [comment]
rebase

**Comment by scv119** [comment]
looks there is a bug...

**Pull request merged**
