### PR TITLE
[docs] new structure

### PR DESCRIPTION
**Pull request by maxpumperla**
This PR consolidates both #21667 and #21759 (look there for features), but improves on them in the following way:

- [x] we reverted renaming of existing projects `tune`, `rllib`, `train`, `cluster`, `serve`, `raysgd` and `data` so that links won't break. I think my consolidation efforts with the `ray-` prefix were a little overeager in that regard. It's better like this. Only the creation of `ray-core` was a necessity, and some files moved into the `rllib` folder, so that should be relatively benign.
- [x] Additionally, we added Algolia `docsearch`, screenshot below. This is _much_ better than our current search. Caveat: there's a sphinx dependency that needs to be replaced (`sphinx-tabs`) by another, newer one (`sphinx-panels`), as the former prevents loading of the `algolia.js` library. Will follow-up in the next PR (hoping this one doesn't get re-re-re-re-reverted).

Screenshot 2022-01-21 at 16 16 38

### CODE REVIEW

**Comment by maxpumperla** [comment]
@xwjiang2010 in the other PR you mentioned a link to buildkite that I don't have access to. could you please tell me if that issue still persists here?

**Comment by xwjiang2010** [comment]
> 

Hi Max, sorry that I didn't mention it clearly.
The issue is for some release tests (post submit), we run examples from the `doc` folder. For example, https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/golden_notebook_tests/workloads/dask_xgboost_test.py?L7:1.

This path would need to be updated if we are moving things around.

**Comment by maxpumperla** [comment]
@xwjiang2010 thanks for clarifying! ok, the path is now `doc/sources/ray-core/_examples`, and not `doc/examples` anymore. how can I change that path? could you maybe help with that?

**Comment by zhe-thoughts** [comment]
> Also, if you could give me a general idea of what is tested when and how, that'd be so appreciated. I really want to understand our test coverage better.

Hey @maxpumperla : our release tests are listed here: https://github.com/ray-project/ray/blob/master/release/.buildkite/build_pipeline.py

**Review by richardliaw — APPROVED** [review]
btw we should monitor the docs.ray.io closely because it is possible some of these dependency changes may not get reflected properly

**Comment by zhe-thoughts** [comment]
> btw we should monitor the docs.ray.io closely because it is possible some of these dependency changes may not get reflected properly

Yup I agree. @richardliaw Other than manually checking docs.ray.io, what other monitor or testing can we add?

**Comment by richardliaw** [comment]
This is more of a function of readthedocs being broken... we already have
rendered PR previews on each commit

**Review by scv119 — APPROVED** [review]

**Comment by richardliaw** [comment]
pendulum_sac is flaky and unrelated

**Pull request merged**
