### PR TITLE
[tune] remove scikit-optimize search algorithm

### PR DESCRIPTION
**Pull request by matthewdeng**
## Why are these changes needed?

Removing `SkOptSearch` as there is little usage, and the `scikit-optimize` library has not been maintained. 
1. The last commit is from 3 years ago.
2. The latest stable release does not support Python 3.11.
3. The repo has now been archived.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by can-anyscale** [comment]
some doc tests are failing; otherwise ci change looks great, thanks for doing this matt

**Review by justinvyu — APPROVED** [review]
Could we add a bit more of explanation for removing in the PR description (library is not maintained, 3.11 support, etc.)? Thanks!

**Review by woshiyyya — APPROVED** [review]
LGTM. Any other searchers to deprecate?

**Review by angelinalg — APPROVED** [review]

**Comment by angelinalg** [comment]
Love the purging and maintenance! Thank you!

**Pull request merged**
