### PR TITLE
[Serve] Fix flaky test_deployment_graph_autoscaling test

### LINKED ISSUE #37120: [Serve] Fix flaky test_deployment_graph_autoscaling test
### What happened + What you expected to happen

https://buildkite.com/ray-project/oss-ci-build-branch/builds/4813#01891f7c-303b-4c4b-b1ef-13e1f3cac7a6

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by GeneDer**
## Why are these changes needed?

`test_deployment_graph_autoscaling` failed in the shutdown sequence for MetricsPusher. Delete metrics pusher explicitly when the replica is ready to be shutdown.

## Related issue number

Closes https://github.com/ray-project/ray/issues/37120

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
@GeneDer is this confirmed to fix the issue?

**Comment by GeneDer** [comment]
@edoakes Both `test_deployment_graph_autoscaling` and `test_autoscaling_policy` tests are no longer failing and no new tests are failing so I assumed it's fixed. I can do some empty commits to trigger the build few more times to double check

**Review by shrekris-anyscale — APPROVED** [review]

**Comment by edoakes** [comment]
@GeneDer please go ahead and trigger a few more builds

**Comment by GeneDer** [comment]
Second time also have all tests passing, will try again

**Pull request merged**
