### PR TITLE
Fix verbose shutdown error and test_env_with_subprocesses

### LINKED ISSUE #6584: Long error message on actor shut down
<!--Please include [tune], [rllib], [autoscaler] etc. in the issue title if relevant-->

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Python 3.7 on macOS

*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?*

On the latest master, I'm seeing the following error message when an actor gets shut down:
```
(pid=65417) F1222 13:53:06.256846 377052608 core_worker.cc:122]  Check failed: _s.ok() Bad status: IOError: [RayletClient] Connection closed unexpectedly.
(pid=65417) *** Check failure stack trace: ***
(pid=65417)     @        0x1081299d2  google::LogMessage::~LogMessage()
(pid=65417)     @        0x107e1f715  ray::RayLog::~RayLog()
(pid=65417)     @        0x107cecb12  std::__1::__function::__func<>::operator()()
(pid=65417)     @        0x107d13592  _ZN5boost4asio6detail18completion_handlerIZZN3ray28CoreWorkerDirectTaskReceiver14HandlePushTaskERKNS3_3rpc15PushTaskRequestEPNS5_13PushTaskReplyENSt3__18functionIFvNS3_6StatusENSC_IFvvEEESF_EEEENK3$_3clEvEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(pid=65417)     @        0x107ce6470  boost::asio::detail::scheduler::do_run_one()
(pid=65417)     @        0x107ce5fe2  boost::asio::detail::scheduler::run()
(pid=65417)     @        0x107cdbc92  ray::CoreWorker::StartExecutingTasks()
(pid=65417)     @        0x107c7016b  __pyx_pw_3ray_7_raylet_10CoreWorker_5run_task_loop()
(pid=65417)     @        0x1077de3e3  _PyMethodDef_RawFastCallKeywords
(pid=65417)     @        0x1077eae24  _PyMethodDescr_FastCallKeywords
(pid=65417)     @        0x10791ad65  call_function
(pid=65417)     @        0x1079179ed  _PyEval_EvalFrameDefault
(pid=65417)     @        0x1077ddbe5  function_code_fastcall
(pid=65417)     @        0x10791ac67  call_function
(pid=65417)     @        0x1079179ed  _PyEval_EvalFrameDefault
(pid=65417)     @        0x10790c34a  _PyEval_EvalCodeWithName
(pid=65417)     @        0x10796fb80  PyRun_FileExFlags
(pid=65417)     @        0x10796eff7  PyRun_SimpleFileExFlags
(pid=65417)     @        0x10799cccf  pymain_main
(pid=65417)     @        0x1077b08dd  main
(pid=65417)     @     0x7fff7271c2e5  start
```

This was introduced in https://github.com/ray-project/ray/pull/6536

cc @edoakes @ericl 

### Reproduction

This can be reproduced in the following way:
```
In [1]: import ray                                                                                                                                                                                                                                            In [2]: ray.init()                                                                                                                                                                                                                                            
2019-12-22 13:52:55,987	INFO resource_spec.py:216 -- Starting Ray with 18.99 GiB memory available for workers and up to 9.52 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2019-12-22 13:52:57,103	INFO services.py:506 -- Failed to connect to the redis server, retrying.
Out[2]: 
{'node_ip_address': '192.168.1.58',
 'redis_address': '192.168.1.58:21072',
 'object_store_address': '/tmp/ray/session_2019-12-22_13-52-55_975558_65397/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2019-12-22_13-52-55_975558_65397/sockets/raylet',
 'webui_url': None,
 'session_dir': '/tmp/ray/session_2019-12-22_13-52-55_975558_65397'}In [3]: @ray.remote 
   ...: class Actor(object): 
   ...:     def __init__(self): 
   ...:         pass 
   ...:                                                                                                                                                                                                                                                       In [4]: a = Actor.remote()                                                                                                                                                                                                                                    In [5]: del a  
```

### PR DESCRIPTION
**Pull request by ericl**
Closes https://github.com/ray-project/ray/issues/6584

### CODE REVIEW

**Review by edoakes — CHANGES_REQUESTED** [review]
I think there's a simpler fix and this will cause silent errors. We should just not be calling `worker.core_worker.disconnect()` in `actor.py::exit_actor()`. This is causing the problem and isn't necessary anymore because it's handled in the core worker. I believe we can also stop exposing `core_worker.disconnect()` to python entirely with that change.

**Comment by ericl** [comment]
Updated.

**Comment by ericl** [comment]
The disconnect thing also fixes a broken test on jenkins (test_env_with_subprocess.py)

**Review by edoakes — APPROVED** [review]
LGTM if tests pass

**Comment by ericl** [comment]
jenkins retest this please

**Pull request merged**
