### PR TITLE
[rllib] RNNSAC agent

### LINKED ISSUE #16014: [rllib]RNN support for SAC
Me and my team was lacking an option to train SAC algorithm with support for RNNs, so i've implemented a RNNSAC trainer with a relevant RNNSAC policy and model that more or less bases on original SAC agent implementation and I also took inspiration from R2D2 implementation for RNNs support. I've added support for hidden states in RNN based policy and q models, burn_in and zero_init_states, as well as use_prev_reward/action TrajectoryView api. Tested it on repeat_after_me and stateless_cartpole env. 

Here is my forked repo: https://github.com/ddworak94/ray
Main contribution is implementation of rllib/agents/sac/rnnsac.py , rnnsac_torch_policy.py and rnnsac_torch_model.py.
I've also added registry record for this model and lastly a thing i would consider a bug:
in rllib/policy/rnn_sequencing.py:388
`is_last_episode_ids[0] is not True` yields True even if first element of the list is True due to np._True type i think. 
Casting it to bool() fix this and allow init_states to be correctly passed to the sequance.

I was wondering if I could get an opinion from someone in dev team whether this feature looks alright and could be integrated into the master via pull request or some further adjustments needs to be done?

### PR DESCRIPTION
**Pull request by ddworak94**
## Why are these changes needed?

No rnn support for off-policy SAC algorithm is present in current build. 
This patch provides new agent - RNNSAC which supports that.

Additionally a bug in rnn_sequencing.py was found and a fix is implemented in this patch.

## Related issue number

Closes #16014

## Checks

- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by ddworak94** [comment]
Hi again,

I've created PR as @sven1977 asked in related issue topic.
After some refactor lint script passes all checks :) I'm not sure what 2 failed tests means (FAIL: //rllib:tests/test_dependency_torch) and how to fix those. 
Regarding the code, I think rnnsac_example.py should be either moved to examples or removed entirely - let me know which is better.
Last thing is documentation and unit tests. I suppose that they are required, but missing for now. 

Looking forward to get some feedback!

**Comment by juliusfrost** [comment]
Hi, this issue may be related #9206. It would be great if you could share your insights on how you went about design this

**Comment by sven1977** [comment]
Looks great @ddworak94 , just fixed some of the torch imports for torch not to be mandatory for RLlib.
One has to use `ray.rllib.utils.framework.try_import_torch()` for all torch imports reachable from the __init__ file, otherwise, torch would by accident become a hard dependency.
Just waiting for all tests to re-run, then we can merge. ...

**Comment by sven1977** [comment]
@juliusfrost ^^

**Review by sven1977 — APPROVED** [review]
Looks great @ddworak94 . Thanks for this additional algo!!
I moved the example script into the examples folder and added it to the CI tests. Also fixed the torch dependency issue. Simply always use `ray.rllib.utils.framework.try_import_torch()` for not hard-requiring torch to be installed.

**Comment by ddworak94** [comment]
@sven1977 Thank you for review!

Regarding recent failed tests - the problem seems to be in "TEST" part of the example script, where I'm loading checkpoint (which is ok), but also rendering env. The latter might cause issues on servers without graphical interfaces such as git CI...

**Pull request merged**
