### PR TITLE
Move travis build script to after the deploy stage

### PR DESCRIPTION
**Pull request by simon-mo**
So we don't need to wait for the docker to build to test the wheels.

### CODE REVIEW

**Review by edoakes — APPROVED** [review]

**Comment by simon-mo** [comment]
@edoakes feel free to cherry pick this to release branch

**Comment by robertnishihara** [comment]
One problem with this change is that now it is not tested in the CI, so if we break it in a PR we won't know. See https://github.com/ray-project/ray/pull/9720

@simon-mo @edoakes

**Comment by simon-mo** [comment]
Agreed. @ijrsvt should we consider try to build the docker images (but not pushing them) in PR?

**Comment by ijrsvt** [comment]
I think that building in PR is a waste of resources? It already seems like overkill to build the images in *every*  commit. The images really don't change much because they are just dependencies and not the actual dev version of ray. That being said, I think we should start bundling ray in the image, but that may require us to use a different build infra.

**Comment by robertnishihara** [comment]
@ijrsvt how much resources are we talking about?

The issue is that if we only do it in the master, then if it breaks we won't know. Ideally the PR builds should catch all of the bugs.

We also build the wheels in the CI even though they are never used.

**Comment by ijrsvt** [comment]
It is mostly just downloading repos and running scripts. I totally forgot about our wheel building for PRs. I think in that light, it probably isn't much harm in adding it. Is it something that we should run on all PR builds or *only those affecting docker files*.

**Comment by edoakes** [comment]
@ijrsvt can we set up a separate travis job that only rebuilds the containers when the docker files are affected and always runs on master? I think that would be a good compromise.

**Comment by ijrsvt** [comment]
That seems like a great idea!

**Pull request merged**
