### PR TITLE
[Core] Rmove the GetActorIfno RPC for Current Actor When Creating Actors

### PR DESCRIPTION
**Pull request by lixin-wei**
## Why are these changes needed?

When creating actors, we'll register the current actor's handle to ActorManager.

Inside ActorManager.RegisterActorHandle(), we'll send a RPC to GCS to get the actor's info.

We found that this RPC will make GCS stressed when a lot of actors are creating(in our case, 10k/s).

For the current actor itself, it's unnecessary to get actor info from GCS. So I remove this RPC in this PR. Please have a look, thanks!

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jovany-wang — APPROVED** [review]
Very nice change. LGTM

**Comment by jovany-wang** [comment]
Java CI failure is related.

**Review by WangTaoTheTonic — APPROVED** [review]

**Comment by rkooo567** [comment]
Hmm.. in this case, how does the worker subscribe the state like actor is dead? Are we subscribing somewhere else as well? The notification is also sent when the actor states are changed.

**Review by rkooo567 — CHANGES_REQUESTED** [review]
Maybe I am missing something, but I have a question that needs to be answered! I am down to merge it once that concern turns out to be a non-issue

**Comment by lixin-wei** [comment]
@rkooo567 I only removed the subscription of the current actor itself. The current actor will know its latest state at first. And doesn't need to subscribe to the state of itself.

**Comment by lixin-wei** [comment]
The title seems to mislead you, I've changed it.

**Comment by rkooo567** [comment]
Oh I see. That's a good point. (it will know when it dies lol)

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Retrying java test...

**Comment by lixin-wei** [comment]
CI passed :)

**Pull request merged**
