### PR TITLE
[serve][docs] Unify `doc_code` directories and add bazel target

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

Split off from https://github.com/ray-project/ray/pull/24693/, unifying the redundant directories we had and making sure all `serve/doc_code` snippets are run in CI.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Ah i remember one of the issue... the test is currently covered under https://github.com/ray-project/ray/blob/master/.buildkite/pipeline.ml.yml#L374-L382 which doesn't trigger on Serve changes

**Comment by simon-mo** [comment]
we might want to consider splitting though. to make our CI run faster

**Comment by edoakes** [comment]
@simon-mo I think I added it in the right place, PTAL. I don't think we need to split right now, the doc tests are fast.

**Comment by simon-mo** [comment]
CI will probably fail because these are no longer valid target
https://github.com/ray-project/ray/blob/master/python/ray/serve/BUILD#L458-L471

**Review by simon-mo — APPROVED** [review]
LGTM. Please feel free to merge as soon as we confirmed all these scripts in doc_code are properly tested and passed in CI.

**Pull request merged**
