### PR TITLE
[core] Prevent new worker from being creating if there is workers exiting

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
When workers are exiting, there should be some probability that the exiting worker failed to exit and it can be reused to delegate jobs to. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Let's run the multi tenancy test 3 times before merging it.

**Comment by rkooo567** [comment]
Hmm it seems like it times out (and it doesn't fail). I wonder if our change introduces some other bugs (like retrying is not properly happening or sth?).

**Comment by rkooo567** [comment]
@iycheng I am not sure why the mac test sometimes times out. Can you check if the upper level caller retries when pop worker doesn't start a new worker in this case?

**Comment by iycheng** [comment]
@rkooo567  I'm not sure about that. Right now, I don't have the bandwidth for this issue. We should plan time for this in the next sprint.

**Comment by rkooo567** [comment]
Why do we close it?

**Comment by iycheng** [comment]
Sorry, I was cleaning up branches and accidentally closed this one :( Re-opening it!

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
