### PR TITLE
[all_tests][ci] Add 310 for test wheels on linux 

### PR DESCRIPTION
**Pull request by rickyyx**
Signed-off-by: rickyyx <rickyx@anyscale.com>

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Actually, I noticed `test_wheels` is only called in `pipeline.macos.yaml`, does that mean we could deprecate the related code for other systems? 

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+test_wheels&patternType=standard&sm=1

**Comment by rkooo567** [comment]
can you update the PR description?

**Comment by rickyyx** [comment]
> Actually, I noticed `test_wheels` is only called in `pipeline.macos.yaml`, does that mean we could deprecate the related code for other systems?
> 
> https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+test_wheels&patternType=standard&sm=1

Actually I think this part of code for linux is never called in our pipeline now. cc @krfricke . Should we just remove them altogether?

**Comment by krfricke** [comment]
Yeah it doesn't look like it's being called in CI. Instead of removing it, should we run it in Linux instead?

**Comment by rickyyx** [comment]
Open

**Review by krfricke — APPROVED** [review]
Changes looks good to me, please let me know if this is ready to merge

**Comment by krfricke** [comment]
@rickyyx is this still active?

**Comment by rickyyx** [comment]
Ah i will try to update it!

**Pull request closed without merging**
