### PR TITLE
[RLlib] Issue 7421: can't convert cuda tensor to numpy in torch ppo.

### PR DESCRIPTION
**Pull request by sven1977**
The post-processing batch was not generically translated into non-torch Tensor types by TorchPolicy leading to CUDA tensors sometimes being fed into np methods (throws errors).

Fixes issue #7421 

Closes issue #7421 

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Lint failure.

**Comment by sven1977** [comment]
@ericl Tests are ok now, please merge.

**Comment by ericl** [comment]
Done.

**Comment by mullinix** [comment]
I've rebuilt with these changes and am finding the following error on the same toy problem:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-26453c96c435> in <module>
----> 1 from ray.rllib.utils.torch_ops import convert_to_non_torch_type

/ray/python/ray/rllib/__init__.py in <module>
      7 from ray.rllib.env.multi_agent_env import MultiAgentEnv
      8 from ray.rllib.env.vector_env import VectorEnv
----> 9 from ray.rllib.evaluation.policy_graph import PolicyGraph
     10 from ray.rllib.evaluation.rollout_worker import RolloutWorker
     11 from ray.rllib.evaluation.tf_policy_graph import TFPolicyGraph

/ray/python/ray/rllib/evaluation/__init__.py in <module>
      1 from ray.rllib.evaluation.episode import MultiAgentEpisode
----> 2 from ray.rllib.evaluation.rollout_worker import RolloutWorker
      3 from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
      4 from ray.rllib.evaluation.interface import EvaluatorInterface
      5 from ray.rllib.evaluation.policy_graph import PolicyGraph

/ray/python/ray/rllib/evaluation/rollout_worker.py in <module>
     17 from ray.rllib.env.vector_env import VectorEnv
     18 from ray.rllib.evaluation.interface import EvaluatorInterface
---> 19 from ray.rllib.evaluation.sampler import AsyncSampler, SyncSampler
     20 from ray.rllib.policy.sample_batch import MultiAgentBatch, DEFAULT_POLICY_ID
     21 from ray.rllib.policy.policy import Policy

/ray/python/ray/rllib/evaluation/sampler.py in <module>
      9 from ray.rllib.evaluation.episode import MultiAgentEpisode, _flatten_action
     10 from ray.rllib.evaluation.rollout_metrics import RolloutMetrics
---> 11 from ray.rllib.evaluation.sample_batch_builder import \
     12     MultiAgentSampleBatchBuilder
     13 from ray.rllib.policy.policy import clip_action

/ray/python/ray/rllib/evaluation/sample_batch_builder.py in <module>
      4 
      5 from ray.util.debug import log_once
----> 6 from ray.rllib.policy.sample_batch import SampleBatch, MultiAgentBatch
      7 from ray.rllib.utils.annotations import PublicAPI, DeveloperAPI
      8 from ray.rllib.utils.debug import summarize

/ray/python/ray/rllib/policy/__init__.py in <module>
      1 from ray.rllib.policy.policy import Policy
----> 2 from ray.rllib.policy.torch_policy import TorchPolicy
      3 from ray.rllib.policy.tf_policy import TFPolicy
      4 from ray.rllib.policy.torch_policy_template import build_torch_policy
      5 from ray.rllib.policy.tf_policy_template import build_tf_policy

/ray/python/ray/rllib/policy/torch_policy.py in <module>
      8 from ray.rllib.utils.framework import try_import_torch
      9 from ray.rllib.utils.schedules import ConstantSchedule, PiecewiseSchedule
---> 10 from ray.rllib.utils.torch_ops import convert_to_non_torch_type
     11 from ray.rllib.utils.tracking_dict import UsageTrackingDict
     12 

/ray/python/ray/rllib/utils/torch_ops.py in <module>
----> 1 import tree
      2 
      3 from ray.rllib.utils.framework import try_import_torch
      4 
      5 torch, _ = try_import_torch()

ModuleNotFoundError: No module named 'tree'
```

The issue was also found in the [Jenkins failure](https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/22815/console)

**Pull request merged**
