### PR TITLE
Update cloudpickle

### PR DESCRIPTION
**Pull request by suquark**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by suquark** [comment]
This is not a full update, but to see if the CI could run correctly.

**Comment by suquark** [comment]
jenkins retest this please

**Comment by suquark** [comment]
Ready for review. Some CI fails with `E           AttributeError: 'ActorHandle' object has no attribute '__ray_kill__'`. But this also happens on the master branch. So I suppose this is not an issue caused by this PR.

**Comment by robertnishihara** [comment]
1. Is this directly copying the cloudpickle files, or are there any modifications?
2. We should also update the version in ray/cloudpickle/__init__.py. Should probably also leave a comment pointing to the precise commit that this is coming from.
3. Is this coming from a specific cloudpickle commit or from a specific release?

**Comment by suquark** [comment]
@robertnishihara yes, there is modifications as we did before. It is from a recent release. Let me update __init__.py to include the release number.

**Comment by robertnishihara** [comment]
> @robertnishihara yes, there is modifications as we did before. It is from a recent release. Let me update **init**.py to include the release number.

@suquark can you remind me what the modifications are? Would they make sense to commit as part of cloudpickle?

**Comment by suquark** [comment]
@robertnishihara the only difference is in the `cloudpickle_fast.py`. In cloudpickle, `cloudpickle_fast.py` only targets at python3.8+, so I add some code to support older python versions.

**Comment by suquark** [comment]
sync with master branch to retrigger CI builds

**Comment by suquark** [comment]
Ready to review. CI errors are same with the master branch, so they may be not related to this PR.

**Comment by jakirkham** [comment]
FWIW I think PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ) is close, but it has a couple of test failures on 3.5 and 3.6 that I haven't quite worked out. Python 3.7 already works with those changes. It would be nice to get this to cross the line if we can. Any help that people here might be able to offer would be much appreciated 🙂

**Comment by suquark** [comment]
@jakirkham yes, I think we have figure out how to combine pickle5 protocol, pickle5-backport, and python3.5-3.8 properly in Ray for a while. After this PR is merged, I can try to commit these changes to the cloudpickle upstream.

**Comment by suquark** [comment]
(Rebase on master to get rid of some CI errors)

**Comment by jakirkham** [comment]
@suquark when it comes to implementing pickling methods on classes (`__getstate__`, `__reduce__`, etc.), the easiest path is to use NumPy arrays as arguments since these already can be pickled with older protocols and already have the logic to support out-of-band pickling with the backport package or integrated pickle protocol 5 support. It's also possible coerce other [`bytes`-like objects]( https://docs.python.org/3/glossary.html#term-bytes-like-object ) to `memoryviews`, which `numpy.asarray` can consume zero-copy.

From the cloudpickle side of things, my guess is we can optimize `memoryview`s, which cloudpickle already special cases anyways. We have discussed doing this in issue ( https://github.com/cloudpipe/cloudpickle/issues/365 ). So this seems like a pretty easy path to go down.

As to the particular test failures that I was stuck on earlier, Pierre has already helped sort those out. So I think mainly what we need at this stages is reviews from others.

I can't comment too much on Ray's serialization logic as I'm less familiar. Though hopefully those ideas are useful. Please let us know if you have other thoughts 🙂

**Comment by pcmoritz** [comment]
Diff to the upstream cloudpickle:
```
18c18,19
< 
---
> import _pickle
> import pickle
21a23
> import typing
23c25
< import numpy
---
> from _pickle import Pickler
27,30c29,31
<     _find_imported_submodules, _get_cell_contents, _is_global, _builtin_type,
<     Enum, _ensure_tracking,  _make_skeleton_class, _make_skeleton_enum,
<     _extract_class_dict, dynamic_subimport, subimport, cell_set,
<     _make_empty_cell
---
>     _find_imported_submodules, _get_cell_contents, _is_importable_by_name, _builtin_type,
>     Enum, _get_or_create_tracker_id,  _make_skeleton_class, _make_skeleton_enum,
>     _extract_class_dict, dynamic_subimport, subimport, _typevar_reduce, _get_bases,
33,41c34
< if sys.version_info[:2] < (3, 8):
<     import pickle5 as pickle
<     from pickle5 import Pickler
<     load, loads = pickle.load, pickle.loads
< else:
<     import _pickle
<     import pickle
<     from _pickle import Pickler
<     load, loads = _pickle.load, _pickle.loads
---
> load, loads = _pickle.load, _pickle.loads
86,87c79,80
<     return (type(obj), obj.__name__, obj.__bases__, type_kwargs,
<             _ensure_tracking(obj), None)
---
>     return (type(obj), obj.__name__, _get_bases(obj), type_kwargs,
>             _get_or_create_tracker_id(obj), None)
93c86
<             obj.__module__, _ensure_tracking(obj), None)
---
>             obj.__module__, _get_or_create_tracker_id(obj), None)
118a112
>         "__closure__": func.__closure__,
146,157c140,147
<     # TODO: not sure if we are going to implement it for python < 3.7.
<     # But we are sure that we didn't have the '_abc_impl' field in python < 3.7,
<     # and there are currently no reported issues about it.
<     if sys.version_info >= (3, 7):
<         if issubclass(type(obj), abc.ABCMeta):
<             # If obj is an instance of an ABCMeta subclass, dont pickle the
<             # cache/negative caches populated during isinstance/issubclass
<             # checks, but pickle the list of registered subclasses of obj.
<             clsdict.pop('_abc_impl', None)
<             (registry, _, _, _) = abc._get_dump(obj)
<             clsdict["_abc_impl"] = [subclass_weakref()
<                                     for subclass_weakref in registry]
---
>     if issubclass(type(obj), abc.ABCMeta):
>         # If obj is an instance of an ABCMeta subclass, dont pickle the
>         # cache/negative caches populated during isinstance/issubclass
>         # checks, but pickle the list of registered subclasses of obj.
>         clsdict.pop('_abc_impl', None)
>         (registry, _, _, _) = abc._get_dump(obj)
>         clsdict["_abc_impl"] = [subclass_weakref()
>                                 for subclass_weakref in registry]
203,219c193,200
<     if hasattr(obj, "co_posonlyargcount"):  # pragma: no branch
<         args = (
<                 obj.co_argcount, obj.co_posonlyargcount,
<                 obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
<                 obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
<                 obj.co_varnames, obj.co_filename, obj.co_name,
<                 obj.co_firstlineno, obj.co_lnotab, obj.co_freevars,
<                 obj.co_cellvars
<             )
<     else:
<         args = (
<             obj.co_argcount, obj.co_kwonlyargcount, obj.co_nlocals,
<             obj.co_stacksize, obj.co_flags, obj.co_code, obj.co_consts,
<             obj.co_names, obj.co_varnames, obj.co_filename,
<             obj.co_name, obj.co_firstlineno, obj.co_lnotab,
<             obj.co_freevars, obj.co_cellvars
<         )
---
>     args = (
>         obj.co_argcount, obj.co_posonlyargcount,
>         obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
>         obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
>         obj.co_varnames, obj.co_filename, obj.co_name,
>         obj.co_firstlineno, obj.co_lnotab, obj.co_freevars,
>         obj.co_cellvars
>     )
223,228d203
< def _make_cell(contents):
<     cell = _make_empty_cell()
<     cell_set(cell, contents)
<     return cell
< 
< 
232c207
<         contents = (obj.cell_contents,)
---
>         obj.cell_contents
234,240c209
<         contents = ()
< 
<     if sys.version_info[:2] < (3, 8):
<         if contents:
<             return _make_cell, contents
<         else:
<             return _make_empty_cell, ()
---
>         return types.CellType, ()
242c211
<         return types.CellType, contents
---
>         return types.CellType, (obj.cell_contents,)
367c336
<     elif not _is_global(obj):
---
>     elif not _is_importable_by_name(obj):
388a358
>     obj_closure = slotstate.pop("__closure__")
398a369,376
>     if obj_closure is not None:
>         for i, cell in enumerate(obj_closure):
>             try:
>                 value = cell.cell_contents
>             except ValueError:  # cell is empty
>                 continue
>             obj.__closure__[i].cell_contents = value
> 
418,462d395
< def _numpy_frombuffer(buffer, dtype, shape, order):
<     # Get the _frombuffer() function for reconstruction
<     from numpy.core.numeric import _frombuffer
<     array = _frombuffer(buffer, dtype, shape, order)
<     # Unfortunately, numpy does not follow the standard, so we still
<     # have to set the readonly flag for it here.
<     array.setflags(write=not buffer.readonly)
<     return array
< 
< 
< def _numpy_ndarray_reduce(array):
<     # This function is implemented according to 'array_reduce_ex_picklebuffer'
<     # in numpy C backend. This is a workaround for python3.5 pickling support.
<     if sys.version_info >= (3, 8):
<         import pickle
<         picklebuf_class = pickle.PickleBuffer
<     elif sys.version_info >= (3, 5):
<         try:
<             import pickle5
<             picklebuf_class = pickle5.PickleBuffer
<         except Exception:
<             raise ImportError("Using pickle protocol 5 requires the pickle5 "
<                               "module for Python >=3.5 and <3.8")
<     else:
<         raise ValueError("pickle protocol 5 is not available for Python < 3.5")
<     # if the array if Fortran-contiguous and not C-contiguous,
<     # the PickleBuffer instance will hold a view on the transpose
<     # of the initial array, that is C-contiguous.
<     if not array.flags.c_contiguous and array.flags.f_contiguous:
<         order = "F"
<         picklebuf_args = array.transpose()
<     else:
<         order = "C"
<         picklebuf_args = array
<     try:
<         buffer = picklebuf_class(picklebuf_args)
<     except Exception:
<         # Some arrays may refuse to export a buffer, in which case
<         # just fall back on regular __reduce_ex__ implementation
<         # (gh-12745).
<         return array.__reduce__()
< 
<     return _numpy_frombuffer, (buffer, array.dtype, array.shape, order)
< 
< 
486,489c419
<     if sys.version_info[:2] >= (3, 8):
<         dispatch[types.CellType] = _cell_reduce
<     else:
<         dispatch[type(_make_empty_cell())] = _cell_reduce
---
>     dispatch[types.CellType] = _cell_reduce
495a426
>     dispatch[typing.TypeVar] = _typevar_reduce
542,551d472
< 
<         # This is a patch for python3.5
<         if isinstance(obj, numpy.ndarray):
<             if (self.proto < 5 or
<                     (not obj.flags.c_contiguous and not obj.flags.f_contiguous) or
<                     (issubclass(type(obj), numpy.ndarray) and type(obj) is not numpy.ndarray) or
<                     obj.dtype == "O" or obj.itemsize == 0):
<                 return NotImplemented
<             return _numpy_ndarray_reduce(obj)
< 
587c508
<         if _is_global(obj):
---
>         if _is_importable_by_name(obj):
615c536,544
<         return code, base_globals, None, None, func.__closure__
---
>         # Do not bind the free variables before the function is created to
>         # avoid infinite recursion.
>         if func.__closure__ is None:
>             closure = None
>         else:
>             closure = tuple(
>                 types.CellType() for _ in range(len(code.co_freevars)))
> 
>         return code, base_globals, None, None, closure
```

**Comment by pcmoritz** [comment]
@suquark We are not using `cloudpickle.py`, only `cloudpickle_fast.py`, right? Can we remove `cloudpickle.py`?

**Comment by pcmoritz** [comment]
It looks to me that there is still a lot of changes vs upstream, not just the numpy changes we needed to make (and `cloudpickle.py` is changed too).

Can we move closer to upstream here @suquark?

**Review by pcmoritz — APPROVED** [review]

**Pull request merged**
