### PR TITLE
Update cloudpickle to 0.6.1

### PR DESCRIPTION
**Pull request by suquark**
## What do these changes do?

This PR is used to fix problems found in updating cloudpickle.

## Related issue number

https://github.com/ray-project/ray/issues/2685
https://github.com/ray-project/ray/pull/2928

### CODE REVIEW

**Comment by suquark** [comment]
It's so weird. `recursion_test` always fails. I tried in different systems and cannot reproduce such errors.  I am not sure what has happened.

**Comment by suquark** [comment]
@robertnishihara We haven't enabled debug mode for our travis CI, right?
https://docs.travis-ci.com/user/running-build-in-debug-mode/
Could you send a email to them to enable debug mode? It could be much easier to solve some problems with debug mode (I often did such things in CircleCI).

**Comment by robertnishihara** [comment]
@suquark, I think that debug mode is enabled. However, I've always found it difficult to use. Have you tried both linux and mac?

**Comment by suquark** [comment]
Yes. I have tried. It will succeed when running the recursive test alone.

**Comment by suquark** [comment]
Currently, I think a workaround is just keep the changes we need in cloudpickle.

**Comment by robertnishihara** [comment]
Did you run it with `python -m pytest -v test/recursion_test.py`?

The error is very interesting, I wonder if it's related to 9a52ba31f270fb6888d31c012e14a841f8b82acb or 8eaf637e78733fe5b4c295d9204dc6dcc76fb342.

It's also possible that we need to undo this code https://github.com/ray-project/ray/blob/653c5b114a26c91ba59c484179d51d6329fb8fad/python/ray/function_manager.py#L105-L121

**Comment by suquark** [comment]
Yes. I run exactly the command.

**Comment by suquark** [comment]
jenkins, retest this please

**Comment by suquark** [comment]
It is repaired by removing global-related code in cloudpickle. Comments are left in code to mark those removals.

**Comment by robertnishihara** [comment]
Thanks @suquark, is it a bug in cloudpickle? If so, can we submit a PR to fix cloudpickle?

**Comment by suquark** [comment]
@robertnishihara I don't think it is a bug. Pickling python objects itself is not well-defined because what are needed to be serialized and what should be kept as references really depend on the application. So we just keep what we need from their code. 
And we could ask cloudpickle to control the 'level' of serialization just like compilers to avoid some over-serialization. But it will certainly take more time. I suggest merge this PR first.

**Comment by mitar** [comment]
It would be great to get this fixed soon. We have problems because of this cloud pickle issues.

I see that there are further changes made by @suquark here, to fix problems in cloud pickle which are detected by Ray CI. If I understand correctly, they are not really bugs but it is that our needs from cloud pickle is different than what default logic they have provides. So or we maintain patched version or we get them to add a switch so that we can disable things which are breaking our use case.

**Comment by robertnishihara** [comment]
@mitar, I agree it would be great to get these issues resolved soon. Maintain our own version of cloudpickle will be a nightmare, so we should stick with the official code base.

@suquark can you explain what situations cause cloudpickle to "overserialize" things? What can we do to avoid triggering those cases?

**Comment by suquark** [comment]
@robertnishihara It's really hard to give a simple example. But here's some points:

1. When restoring the global variables, in Ray we should always give serialized global variables higher priority (that is, always overriding existing global variables). The new changes in cloudpickle gives higher priority to existing global variables.
2. In Ray, do not try to infer global variables from the `__module__` attribute of a function. The new changes in cloudpickle try to make use of it when it fails to fetch global variables.

**Comment by mitar** [comment]
Are those things also something any user of Ray would have to think about?

Personally, I really do not see this pickling of much benefit to us. This is useful in scripting mode, but for production, it would just be simple to send over a full Python path of a function to call and expect it to be there on a worker available, through a regular Python importing.

**Comment by robertnishihara** [comment]
@mitar, separately I think we will provide a mode doing something like what you outlined above, where modules are available on each machine and don't need to be serialized. However, even in that case it will be hard to avoid pickle entirely, e.g., for shipping around custom serializers and things like that.

**Comment by mitar** [comment]
Even for custom serializers I would expect the code to be already there.

**Comment by mitar** [comment]
So, how can we make progress here? This is pretty important for us.

**Comment by robertnishihara** [comment]
@raulchen this problem with this PR is that it's not actually using the upstream cloudpickle. Instead @suquark applied some patches. There is some discussion on https://github.com/cloudpipe/cloudpickle/issues/214 about the best way to patch the upstream cloudpickle.

**Comment by nmatthews-asapp** [comment]
Looks like https://github.com/cloudpipe/cloudpickle/pull/240 may help here. I assume it will be in 0.7.1 of cloudpickle

**Comment by pcmoritz** [comment]
Yes, we integrated that change and some other improvements in PR #3964

**Pull request closed without merging**
