### PR TITLE
[Cherry-pick] [Core] Add retry exception allowlist for user-defined filtering of retryable application-level errors.

### PR DESCRIPTION
**Pull request by clarkzinzow**
Cherry-pick of https://github.com/ray-project/ray/pull/26449 onto 2.0.0 release branch.

### CODE REVIEW

**Comment by scv119** [comment]
hmm do we really need this for 2.0?

**Comment by clarkzinzow** [comment]
@scv119 We have a few users that have been looking for this and I've been treating this as a P0.5 for 2.0; are there concerns about this introducing instability or some other issues?

**Comment by scv119** [comment]
cc @simon-mo @iycheng  this might the cause of https://github.com/ray-project/ray/issues/27677

**Comment by simon-mo** [comment]
Yup I have verified #27677 doesn't happen in rc1. The underlying cause is this:
- Serve uses ref._on_completed(callback) to process results (and exceptions) in the background.
- In the past, the exception (asyncio.TimeoutError) can be propogated with error printed.
- This PR made it an unhandled exception.

**Comment by simon-mo** [comment]
We can easily fix this on Serve side since the use of _on_completed is a bit unconventional. But if this PR goes in 2.0, we need to make sure the corresponding Serve fix goes in as well.

**Comment by clarkzinzow** [comment]
@simon-mo I think that we're currently leaning towards not cherry-picking this in 2.0, and I think we should only merge this if we also cherry-pick the Serve fix from master (once it lands).

Also, is this change in semantics a bug? The default behavior should be preserved AFAICT, and I don't quite see how this PR could make `asyncio.TimeoutError` an unhandled exception. The default exception allowlist is "all exceptions" (pre-PR behavior), and we don't change which exceptions are handled and which are unhandled. 🤔 

https://github.com/ray-project/ray/pull/27586/files#diff-31e8159767361e4bc259b6d9883d9c0d5e5db780fcea4a52ead4ee3ee4a59a78R737-R754

**Comment by clarkzinzow** [comment]
Ohhh the issue is the new log statement! Got it. https://github.com/ray-project/ray/blob/13f43b939a43c2dc55cd0330fc0ca2cc57b4ad37/python/ray/_raylet.pyx#L751-L754

**Comment by simon-mo** [comment]
This is not the "unhandled exception" code path right? We should not break that behavior.

**Comment by clarkzinzow** [comment]
>This is not the "unhandled exception" code path right? We should not break that behavior.

No this is the new logging statement in the handled exception path, which is why you're seeing that `"Task failed with unretryable exception: TaskID(566a9d3467c6412abf2f7875f2a6fbf7b2db89b101000000)."` log statement, and is why I'm proposing that we demote that new logging statement to debug-level.

**Comment by clarkzinzow** [comment]
@simon-mo AFAICT the only change that you're seeing in Serve is that this exception is logged, but the `ref._on_completed(callback)` should still be invoked with the exception and the Serve workload should complete successfully. Is that correct?

**Comment by sihanwang41** [comment]
> @simon-mo AFAICT the only change that you're seeing in Serve is that this exception is now logged, but the `ref._on_completed(callback)` should still be invoked with the exception and the Serve workload should complete successfully. Is that correct?

Hi @clarkzinzow , yes, i have verified everything works fine but a unhandled exception printed. And yes, ref._on_completed(callback) will be invoked with expected exception.

**Comment by clarkzinzow** [comment]
@sihanwang41 Then I think that the lowest-impact fix would be demoting that log statement to debug level. Let me open a hotfix PR.

**Comment by ericl** [comment]
Closing as won't pick for 2.0.

**Pull request closed without merging**
