### PR TITLE
Fix Serve Dashboard Tests

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

https://github.com/ray-project/ray/pull/33300 made the dashboard dependent on Serve.
Causing test failures: https://buildkite.com/ray-project/oss-ci-build-branch/builds/2770#_

```
E                     File "/ray/python/ray/dashboard/utils.py", line 121, in get_all_modules
E                       importlib.import_module(name)
E                     File "/opt/miniconda/lib/python3.7/importlib/__init__.py", line 127, in import_module
E                       return _bootstrap._gcd_import(name[level:], package, level)
E                     File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
E                     File "<frozen importlib._bootstrap>", line 983, in _find_and_load
E                     File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
E                     File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
E                     File "<frozen importlib._bootstrap_external>", line 728, in exec_module
E                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
E                     File "/ray/python/ray/dashboard/modules/serve/sdk.py", line 12, in <module>
E                       from ray.serve.schema import ServeInstanceDetails
E                     File "/ray/python/ray/serve/__init__.py", line 23, in <module>
E                       raise e
E                     File "/ray/python/ray/serve/__init__.py", line 4, in <module>
E                       from ray.serve.api import (
E                     File "/ray/python/ray/serve/api.py", line 6, in <module>
E                       from fastapi import APIRouter, FastAPI
E                   ModuleNotFoundError: No module named 'fastapi'. You can run `pip install "ray[serve]"` to install all Ray Serve dependencies.
```

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zcin** [comment]
Is there a way to kick off the default install test? If not, I think we can also just merge this

**Comment by sihanwang41** [comment]
is it possible (or a problem) we just add serve dep into dashboard?

**Comment by zcin** [comment]
> is it possible (or a problem) we just add serve dep into dashboard?

I believe that requires users to install Serve and its dependencies for them to even use the Ray Dashboard.

**Review by sihanwang41 — APPROVED** [review]

**Review by shrekris-anyscale — APPROVED** [review]

**Comment by zcin** [comment]
@edoakes ping for merge

**Pull request merged**
