### PR TITLE
Add flush interval in tqdm_ray

### PR DESCRIPTION
**Pull request by raulchen**
## Why are these changes needed?

`tqdm_ray._dump_state` is expensive and may be called frequently [here](https://github.com/ray-project/ray/blob/465a1932ccd1799357d7b76d67397fb1908b0780/python/ray/data/_internal/execution/streaming_executor.py#L149). This turns out to be a bottleneck in large-scale training ingest workloads. 
Adding a flush interval to reduce the overhead. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — COMMENTED** [review]
Can you make the default flush interval 0? It doesn't seem like a safe change to make by default otherwise, since we don't have a background thread to trigger flushes on timeout.

**Comment by raulchen** [comment]
> Can you make the default flush interval 0? It doesn't seem like a safe change to make by default otherwise, since we don't have a background thread to trigger flushes on timeout.

I was concerned about this issue as well initially. But after thinking more, this seemed fine. The behavior is the same as logging libraries. Data is flushed by the next write or when closing.

**Comment by raulchen** [comment]
> > Can you make the default flush interval 0? It doesn't seem like a safe change to make by default otherwise, since we don't have a background thread to trigger flushes on timeout.
> 
> I was concerned about this issue as well initially. But after thinking more, this seemed fine. The behavior is the same as logging libraries. new logs are flushed by the next write or when closing.

@ericl does this make sense? alternatively, I think we can at least make the interval default to 1s for Data. Not sure if there will be an issue for other libraries.

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
It's worth a try, let's go back and change the default if it's a problem.

**Pull request merged**
