### PR TITLE
[docs] [overview] create LLM section and add examples: Part 1

### PR DESCRIPTION
**Pull request by angelinalg**
## Why are these changes needed?

Surface LLM/Generative AI use cases.

Request from @pcmoritz:
Can somebody put LLMs / generative AI into a separate section here https://docs.ray.io/en/latest/ray-overview/use-cases.html and also link some of the examples and latest blog posts? At the moment it is mixed together with Large Scale Workload Orchestration

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by angelinalg** [comment]
@pcmoritz Would you check that I pulled the correct items from the Large Scale Workload Orchestration section please? I also just added the minimum to the intro sentence for LLM/Gen AI. I can ask @emmyscode for a better intro in a follow up PR.

**Comment by pcmoritz** [comment]
This is great, let's merge it! As a follow up if we have time we can add an intro and possibly a graphic if it is worth the effort. If you plan to do those let me know when it is ready for cherry-picking into the 2.4 branch :)

**Review by pcmoritz — APPROVED** [review]

**Comment by zhe-thoughts** [comment]
@jjyao Do you think it's too late to pick into 2.4.0? Thanks

**Comment by jjyao** [comment]
No, we can still cherry pick.

**Comment by zhe-thoughts** [comment]
OK then I approve for picking

**Pull request merged**
