### PR TITLE
Add a Learn about Anyscale link to docs

### PR DESCRIPTION
**Pull request by sijieamoy**
Signed-off-by: sijie <sijie@anyscale.com>

## Why are these changes needed?
image

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
Can we make it into a button?

**Comment by sijieamoy** [comment]
Because the link is not visible enough? @richardliaw 

The words push the button so wide that it looks like a banner more than a button. 
image

**Comment by sijieamoy** [comment]
A button that looks less bad
image

**Review by richardliaw — APPROVED** [review]
looks good, merge and iterate

**Pull request merged**
