### PR TITLE
Small Changes to run TRPO

### PR DESCRIPTION
**Pull request by richardliaw**
Added Keras version and backend switch

### CODE REVIEW

**Comment by robertnishihara** [comment]
Nice work! Is Keras 1.0.6 actually necessary even with the `KERAS_BACKEND` flag? Also `--filter 0` should be `--filter 1`, right?

**Comment by richardliaw** [comment]
yeah! let me add to this ...

**Comment by robertnishihara** [comment]
This looks good! One last thing, what do you think about putting the `export KERAS_BACKEND=theano` in the same line as the `./run_pg.py` command (for both the original version and the Ray version) to guarantee that it gets run when the user copies/pastes the code?

**Comment by richardliaw** [comment]
What about in setup-env.sh?

**Comment by robertnishihara** [comment]
I think `export KERAS_BACKEND=theano` should be specific to this
application. setup-env.sh applies to all of Ray, and some Ray users may
want to use Keras with a tensorflow backend.

**Pull request merged**
