### PR TITLE
Return log probabilities of actions in the autoregressive action dist example for torch

### LINKED ISSUE #32696: Incorrect torch.exp in autorgressive torch example
I think this line is incorrect as a logp is returned, but the exponent is nevertheless taken. For Tensorflow this is implemented correct.

https://github.com/ray-project/ray/blob/7774cc3ebaf613eaf42067c0518667a49c26bb12/rllib/examples/models/autoregressive_action_dist.py#L118

### PR DESCRIPTION
**Pull request by MattiasDC**
In the autoregressive action distribution example, the torch implementation returned the probability of the actions, instead of the log probabilities. This PR fixes that. For Tensorflow, it was correctly implemented.

## Why are these changes needed?
It corrects the expected behavior of the autoregressive action distribution example.

## Related issue number
Closes #32696 

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [X] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [X] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by MattiasDC** [comment]
@sven1977 this has been marked as stale, could someone do a review?

**Comment by MattiasDC** [comment]
@sven1977 this has been marked as stale, could someone do a review?

**Comment by MattiasDC** [comment]
Hi @avnishn, I see you are an Rllib maintainer, can you give this a look?

**Comment by MattiasDC** [comment]
Bump

**Review by krfricke — APPROVED** [review]
Makes sense. Thanks for the fix!

**Pull request merged**
