### PR TITLE
[serve] Change serve build to use multi app by default

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

- `serve build` now outputs a multi-application config by default.
- Add `--single-app` flag to `serve build`.
- Keep `--multi-app` flag, but it doesn't do anything and prints a warning message to users, saying multi-app is default and the flag will be removed soon.
- `--single-app` and `--multi-app` cannot be specified together.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by shrekris-anyscale — APPROVED** [review]
Nice!

**Comment by edoakes** [comment]
@zcin should we leave `--multi-app` there with a warning message to avoid breaking existing CLI commands (e.g., in peoples' CI systems)?

**Comment by zcin** [comment]
> @zcin should we leave `--multi-app` there with a warning message to avoid breaking existing CLI commands (e.g., in peoples' CI systems)?

Yeah I was thinking about that too, but wasn't sure. I can add it back and let people know it is now the default.

**Review by GeneDer — APPROVED** [review]
LGTM

**Review by edoakes — APPROVED** [review]

**Pull request merged**
