### PR TITLE
Add stress test for Java worker

### PR DESCRIPTION
**Pull request by raulchen**

### CODE REVIEW

**Comment by robertnishihara** [comment]
@raulchen should we merge this as is or do you want to run it in the continuous integration?

**Comment by raulchen** [comment]
@robertnishihara yep, all functions decorated by `@Test` will be run in CI.

**Comment by raulchen** [comment]
Jenkins, retest this

**Comment by raulchen** [comment]
@robertnishihara somehow I couldn't re-run travis. but the failed jobs should be unrelated, because this PR doesn't touch any python code. It should be okay for merge now.

**Review by robertnishihara — APPROVED** [review]

**Pull request merged**
