### PR TITLE
[RLLib] Execution-Folder Type Annotations

### PR DESCRIPTION
**Pull request by michaelzhiluo**
Title^^

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by sven1977 — APPROVED** [review]
LGTM.

**Comment by ericl** [comment]
@michaelzhiluo this seems to have broken //rllib:test_distributions

**Comment by sven1977** [comment]
Weird though. All tests were green when I merged.

**Comment by michaelzhiluo** [comment]
@ericl I passed all tests. It is probably another PR.

**Pull request merged**
