### PR TITLE
Create tutorial_tensorflow_2.py

### PR DESCRIPTION
**Pull request by magedhelmy1**
## Why are these changes needed?

With the original tutorial here https://docs.ray.io/en/master/serve/tutorials/tensorflow.html . I struggled as a noob to know how to use the model saved directly. Not sure if that well help others, but atleast feel free to include it.. If accepted, I can include the updates to https://github.com/ray-project/ray/blob/master/doc/source/serve/tutorials/tensorflow.rst

## Related issue number

N/A

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] (N/A) I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] (N/A) I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by simon-mo** [comment]
Thanks for the contribution! @architkulkarni can you help shepherd this PR?

**Review by architkulkarni — CHANGES_REQUESTED** [review]
Thanks for the contribution! It looks like you're adding a section for manually testing and the model before serving it with Ray Serve, which is great.  If it helped you understand the tutorial I'm sure it'll help others.  Could you please update `tutorial_tensorflow.py` and the doc page like you suggested?  Then we'd be happy to get this merged.

**Comment by architkulkarni** [comment]
Hi @magedhelmy1, just checking in to see how things are going--please let us know if we can help in any way!

**Comment by magedhelmy1** [comment]
> Hi @magedhelmy1, just checking in to see how things are going--please let us know if we can help in any way!

My apologies for the late reply. I will do this on the weekend if that is still okay.

**Comment by architkulkarni** [comment]
Oh no problem, there's no rush! We're grateful for the contribution :)

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Pull request closed without merging**
