### PR TITLE
Draft: skip tests on windows, add delay between tests

### PR DESCRIPTION
**Pull request by mattip**
## Why are these changes needed?

Enable test_basic_2.py on windows, but skip the segfaults/hangs/flaky tests

## Related issue number
Related to #19177

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@mattip Instead of adding the sleeps in the tests, can we figure out where the race condition is coming from and fix it directly (i.e. fix ray.shutdown)? I think that would be a far superior solution since it would also make the system more robust :)

**Comment by mattip** [comment]
> I think that would be a far superior solution

Agreed

**Comment by mattip** [comment]
xref cleanups in #19430

**Comment by mattip** [comment]
Replaced by #20212

**Pull request closed without merging**
