### PR TITLE
[Doc] Update kuberay version from 0.4.0 to 0.5.0

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Updates the KubeRay version from 0.4.0 to 0.5.0 in all kuberay docs.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by shrekris-anyscale — APPROVED** [review]
Before merging, could we run these examples to make sure they still work with 0.5.0?

**Comment by architkulkarni** [comment]
@shrekris-anyscale Yeah, we're testing the docs manually.

**Comment by architkulkarni** [comment]
Doc CI failure `File "../../python/ray/train/batch_predictor.py", line ?, in default` unrelated

**Comment by architkulkarni** [comment]
@angelinalg could you please give ray-docs codeowner approval? and @wuisawesome for the cluster docs section.  (Not sure if only one of you needs to approve or both)

**Comment by architkulkarni** [comment]
Closed in favor of https://github.com/ray-project/ray/pull/34178

**Pull request closed without merging**
