### PR TITLE
[RLlib] No Preprocessors (part 2).

### PR DESCRIPTION
**Pull request by sven1977**
This PR was motivated in preparation for soon allowing individual observation components to be addressed by the trajectory view API, for example to enable frame-stacking for individual observation components within a complex observation space (Tuple|Dict). Also, soon soft-deprecating RLlib's Preprocessor API should increase transparency for the users and allow batched, model-based preprocessing of observations. Observations will arrive in the model exactly as they are returned by the env.

This is the second part of this (already merged) PR here:
https://github.com/ray-project/ray/pull/18367

- New config key "_disable_preprocessor_api" (default=False). Set this to True to disable any preprocessing of your env's observations: All obs data from the env will then arrive in the model as-is. No default Preprocessors will then be used, such as TupleFlattening/DictFlattening, etc.., not even the NoPreprocessor class.
- The main changes here are in the SimpleListCollector due to the fact that observations are now possibly nested dicts/tuples of data. Such data arriving in the collector is `dm_tree.flattened` and stored per-column in the collector: e.g.

```
obs: {a={aa=np.array((2,), float), ab=np.array((), int8)}, b=np.array((5,), float)}
stored in collector as: [np.array((2,), float), np.array((), int8)), np.array((5,), float)]
```

- A new example script was added (and is per-PR tested) that demonstrates the functionality of preprocessor_pref=None using a deeply nested obs space RandomEnv.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by yangysc** [comment]
If `preprocessor_pref` is `None`,  there are two places for torch needed to be adjusted as well.

1. policy.py
https://github.com/ray-project/ray/blob/dd096c8e73dcefce7bda9abf23182f753ce48c5f/rllib/policy/policy.py#L255-L263
Since the `obs` now is a `dict`, we cannot use `[obs]` to add the dimension.
We can change it to
    ```python
    out = self.compute_actions(
            tree.map_structure(lambda s: s[None], obs),
            state_batch,
            prev_action_batch=prev_action_batch,
            prev_reward_batch=prev_reward_batch,
            info_batch=info_batch,
            episodes=episodes,
            explore=explore,
            timestep=timestep)
    ```
1.  The `compute_actions` function in `torch_policy.py` should be adjusted as well in case `obs_batch` is a `dict`
https://github.com/ray-project/ray/blob/dd096c8e73dcefce7bda9abf23182f753ce48c5f/rllib/policy/torch_policy.py#L264

**Comment by yangysc** [comment]
Another possible problem is the `_multi_gpu_parallel_grad_calc` in `torch_policy.py`.

It seems that for dict observations and no preprocessor, the input `sample_batches` does not have the  `get_interceptor` function to transform `np.array` to `torch.Tensor`.

**Review by michaelzhiluo — APPROVED** [review]

**Comment by sven1977** [comment]
Thanks for your comments @yangysc ! These were invaluable. I added another test case covering single action calculations (and training) for all frameworks with the no-preprocessor setting and a complex observation space. Seems to be solid enough now to give this a go :)

**Comment by yangysc** [comment]
> Thanks for your comments @yangysc ! These were invaluable. I added another test case covering single action calculations (and training) for all frameworks with the no-preprocessor setting and a complex observation space. Seems to be solid enough now to give this a go :)

Very glad to help.  Also, thanks for your excellent work.

**Pull request merged**
