### PR TITLE
[ci][core] Add option for parallel ci for ray core tests

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
This is the first step to enable the parallel tests for ray core ci. To reduce the noise this test only add the option and not enable them. Parallel CI can be 40%-60% faster compared with running them one-by-one.

We'll enable them by bk jobs one-by-one.

Prototype here https://github.com/ray-project/ray/pull/25612

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
LINT is failing, and I'm working to fix that. Right now, lint will sort imports which causes a lot of issues for the reviewer. @clarng is working on the fixing.

**Comment by clarng** [comment]
> LINT is failing, and I'm working to fix that. Right now, lint will sort imports which causes a lot of issues for the reviewer. @clarng is working on the fixing.

This will help minimize the change: https://github.com/ray-project/ray/pull/25824

**Review by mwtian — APPROVED** [review]
Great if we can have parallel testing!

I wonder if there is a way to not repeat the pytest invocation logic in the all test files, e.g. would it be possible to setup these in Bazel? Anyway the change looks like a good improvement!

**Comment by iycheng** [comment]
@mwtian  that's good point. I feel we probably need to change the Bazel rule for this. Once we get that, I think we can also run multiple tests in parallel in a container.

**Pull request merged**
