### PR TITLE
[2.5.1] Cherry-picks for AIR output-related fixes

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

This picks a few fixes to the new output path into 2.5.1.

Note that the new output path is still disabled per default. Only #35977 will have an impact on the regular output as well.

Includes:

- #35770
- #35977 
- #36072 
- #36154 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
@aslonnie @can-anyscale : I think 2.5.1 is already being deployed? Could you confirm?

@krfricke @matthewdeng Separately could you confirm the urgency of getting this PR into 2.5.1 versus 2.6.0? 

Thanks

**Comment by can-anyscale** [comment]
@zhe-thoughts @krfricke: I think the change to 2.5.1 is already merged yet deployed (but can be any moment now), but the cost is high to change that at this moment

**Comment by matthewdeng** [comment]
@krfricke I suggest we exclude this from 2.5.1.

**Comment by krfricke** [comment]
OK, let's defer until 2.6.0.

**Pull request closed without merging**
