### PR TITLE
[serve] Fix bazel test sizes now that we're on buildkite

### PR DESCRIPTION
**Pull request by edoakes**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jiaodong — APPROVED** [review]

**Review by simon-mo — APPROVED** [review]
This should work? I wonder if we still need to keep some of them medium as they are still ran inside windows ci

**Comment by edoakes** [comment]
Oh good point @simon-mo let me monitor the windows build here and see if there are issues.

**Comment by chenk008** [comment]
LGTM

**Review by chenk008 — APPROVED** [review]

**Comment by edoakes** [comment]
Only `tests:test_gcs_fault_tolerance` failing in flaky build.

**Pull request merged**
