### PR TITLE
[DOC] Added a full example how to access deployments 

### PR DESCRIPTION
**Pull request by dmatrix**
Signed-off-by: Jules S.Damji <jules@anyscale.com>

## Why are these changes needed?
This example code exemplifies and augments how deployments are created, accessed, and used via two methods:
1) ServerHandle API (for use in python scripts) and 2) HTTP Requests (for use in a web application)

## Checks

- [x ] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Comment by jiaodong** [comment]
Thanks for helping on our docs ! One suggestion is to have our code snippets in docs covered by CI. One example was last week user reported our code on ray overview homepage was broken due to no coverage :/  https://github.com/ray-project/ray/pull/22228/files

I can help with adding the snippet in your docs to our CI, do you mind committing your script as a python file first, and render it inline instead ?

**Comment by dmatrix** [comment]
Let me place the file in serve/_examples and see if I can do an inline directive like others.

**Comment by jiaodong** [comment]
> @jiaodong Let me place the file in serve/doc_code/_examples and see if I can do an inline directive like others. Is there what want me to place the python script, and follow the quick_start.py example and use `# __serve_example_begin__` and `# **serve_example_end**?

Yep that's one way of doing it. In a separate PR i chatted with Max it's probably easier if we just use jupyter notebook cells with BUILD (I can help with the build or structuring code part if you need) like https://github.com/ray-project/ray/pull/22315/files

**Comment by maxpumperla** [comment]
@jiaodong @dmatrix if you have a look at the `BUILD` files and examples here https://github.com/ray-project/ray/pull/22467 you can see notebook examples for reference.

**Comment by jiaodong** [comment]
Sg, @dmatrix how about I push a commit to use notebook to this PR later and you can have a final check on the content ?

**Comment by jiaodong** [comment]
Running
`bazel test --test_output=all //doc:doc_code_create_deployment_example 
`


```
NFO: From Testing //doc:doc_code_create_deployment_example
==================== Test output for //doc:doc_code_create_deployment_example:
2022-02-24 00:42:55,058 INFO services.py:1490 -- View the Ray dashboard at http://127.0.0.1:8266
(ServeController pid=90343) 2022-02-24 00:42:57,858     INFO checkpoint_path.py:15 -- Using RayInternalKVStore for controller checkpoint and recovery.
(ServeController pid=90343) 2022-02-24 00:42:57,962     INFO http_state.py:102 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:zSeUTh:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-02-24 00:42:58,264 INFO api.py:696 -- Started Serve instance in namespace 'serve'.
2022-02-24 00:42:58,268 INFO api.py:529 -- Updating deployment 'rep-1'. component=serve deployment=rep-1
(ServeController pid=90343) 2022-02-24 00:42:58,289     INFO deployment_state.py:1099 -- Adding 2 replicas to deployment 'rep-1'. component=serve deployment=rep-1
(HTTPProxyActor pid=90347) INFO:     Started server process [90347]
2022-02-24 00:42:59,275 INFO api.py:544 -- Deployment 'rep-1' is ready at `http://127.0.0.1:8000/rep-1`. component=serve deployment=rep-1
2022-02-24 00:42:59,278 INFO api.py:529 -- Updating deployment 'rep-2'. component=serve deployment=rep-2
(ServeController pid=90343) 2022-02-24 00:42:59,352     INFO deployment_state.py:1099 -- Adding 2 replicas to deployment 'rep-2'. component=serve deployment=rep-2
2022-02-24 00:43:00,285 INFO api.py:544 -- Deployment 'rep-2' is ready at `http://127.0.0.1:8000/rep-2`. component=serve deployment=rep-2
{'rep-1': Deployment(name=rep-1,version=None,route_prefix=/rep-1), 'rep-2': Deployment(name=rep-2,version=None,route_prefix=/rep-2)}
ServerHandle API responses: ----------
handle name : rep-1
prediction  : (pid: 90348); path: /model/rep-1.pkl; data: 0.413; prediction: 0.413
--
handle name : rep-2
prediction  : (pid: 90351); path: /model/rep-2.pkl; data: 0.546; prediction: 1.169
--
handle name : rep-1
prediction  : (pid: 90356); path: /model/rep-1.pkl; data: 0.227; prediction: 0.227
--
handle name : rep-2
prediction  : (pid: 90355); path: /model/rep-2.pkl; data: 0.868; prediction: 1.491
--
HTTP responses: ----------
handle name : rep-1
prediction  : (pid: 90356); path: /model/rep-1.pkl; data: 0.186; prediction: 0.186
handle name : rep-2
prediction  : (pid: 90351); path: /model/rep-2.pkl; data: 0.516; prediction: 1.027
handle name : rep-1
prediction  : (pid: 90348); path: /model/rep-1.pkl; data: 0.158; prediction: 0.158
handle name : rep-2
prediction  : (pid: 90355); path: /model/rep-2.pkl; data: 0.439; prediction: 0.439
(ServeController pid=90343) 2022-02-24 00:43:00,411     INFO deployment_state.py:1124 -- Removing 2 replicas from deployment 'rep-1'. component=serve deployment=rep-1
(ServeController pid=90343) 2022-02-24 00:43:00,415     INFO deployment_state.py:1124 -- Removing 2 replicas from deployment 'rep-2'. component=serve deployment=rep-2
================================================================================
//doc:doc_code_create_deployment_example                        (cached) PASSED in 16.2s
```

**Comment by jiaodong** [comment]
Pushed and verified both BUILD targets used are runnable from bazel. @dmatrix please double check on the generated docs again and ping us back :)

**Comment by jiaodong** [comment]
@dmatrix can you try rebase and address CI issues on this ?

**Comment by jiaodong** [comment]
@dmatrix 
image

**Comment by dmatrix** [comment]
@jiaodong I synced with the latest master and fixed a minor typo. Hopefully, that may resolve CI issues. Not sure what the problems are with CI. If that does not work, perhaps we should sync up online and sort it out.

**Comment by maxpumperla** [comment]
@dmatrix @jiaodong why do we have `create_deployments.py` in two places?

**Review by jiaodong — APPROVED** [review]
i retired failed tests due to timeout, but lint and serve tests (that has CI for documentation) passed.

**Comment by dmatrix** [comment]
@jiaodong Thanks! I assume you going to merge it

**Pull request merged**
