### PR TITLE
ray-operator support bazel build

### PR DESCRIPTION
**Pull request by chenk008**
## Why are these changes needed?

The ray project use bazel to build . And  ray-operator  should  support using bazel to build

### CODE REVIEW

**Comment by chenk008** [comment]
cc @edoakes

**Comment by chenk008** [comment]
cc @gaocegege

**Review by gaocegege — APPROVED** [review]

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Review by edoakes — APPROVED** [review]
Amazing!

**Pull request merged**
