### PR TITLE
[serve] Add multi-app support to `serve deploy`

### PR DESCRIPTION
**Pull request by zcin**
## Why are these changes needed?

Updated `serve deploy` to accept both
- The original `ServeApplicationSchema` for deploying a single application
- The new `ServeDeploySchema` for deploying multiple applications

Details:
- `ServeApplicationSchema` and `ServeDeploySchema` have different required fields, so there is no ambiguity - one config cannot be successfully parsed as both.
- If a config fails to parse as either of them, the validation error from trying to parse as `ServeApplicationSchema` will be surfaced.
- `ServeDeploySchema` will go through `/api/serve/applications` and `ServeApplicationSchema` will go through `/api/serve/deployments`

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by edoakes — COMMENTED** [review]
@zcin can we add a test for multiple apps with different runtime_envs?

**Comment by sihanwang41** [comment]
Hi Cindy, let's add some failure case in the unit tests:

- Same app name.
- Same route_prefix.
- One application failed to deploy and the other one is good.

**Comment by zcin** [comment]
> @zcin can we add a test for multiple apps with different runtime_envs?

@edoakes Added! I added a test at the python API level instead of adding it as a cli test.


> Hi Cindy, let's add some failure case in the unit tests:
> 
> * Same app name.
> * Same route_prefix.
> * One application failed to deploy and the other one is good.

@sihanwang41 I added a unit test for one app that succeeds and one that fails (also a python API test instead of cli test). For the other two, I believe those should be Pydantic validation errors after [this PR](https://github.com/ray-project/ray/pull/32787) is merged.

**Comment by sihanwang41** [comment]
> > @zcin can we add a test for multiple apps with different runtime_envs?
> 
> @edoakes Added! I added a test at the python API level instead of adding it as a cli test.
> 
> > Hi Cindy, let's add some failure case in the unit tests:
> > 
> > * Same app name.
> > * Same route_prefix.
> > * One application failed to deploy and the other one is good.
> 
> @sihanwang41 I added a unit test for one app that succeeds and one that fails (also a python API test instead of cli test). For the other two, I believe those should be Pydantic validation errors after [this PR](https://github.com/ray-project/ray/pull/32787) is merged.

For the REST/CLI perspective, let's add those tests and assert validation errors always happening ?  :)

**Comment by zcin** [comment]
> For the REST/CLI perspective, let's add those tests and assert validation errors always happening ? :) (make sure we show the error message clearly to the caller )

Sounds good, I'll add those after https://github.com/ray-project/ray/pull/32787 is merged.

**Comment by zcin** [comment]
@sihanwang41 Added tests for conflicting app name and conflicting route prefix.

**Review by edoakes — APPROVED** [review]

**Comment by zcin** [comment]
@edoakes ready for merge?

**Pull request merged**
