### PR TITLE
[Doc][aws][autoscaler] Update AWS cluster cfg yaml to use default AMI.

### PR DESCRIPTION
**Pull request by gjoliver**
Signed-off-by: Jun Gong <jungong@anyscale.com>

## Why are these changes needed?
Update the example yamls to reflect updated default AMIs that work with newer nvidia drivers/gpus. 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [*] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — CHANGES_REQUESTED** [review]
Can we keep hardcoding the ami in `example-full.yaml` at least so it remains full? For reference the AMI should be `ami-0387d929287ab193e` 

On a related note, perhaps we could also add a comment here https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/aws/config.py#L40 stating to update the examples if we update the dictionary (you can assign me a TODO to make it a unit test)

**Comment by gjoliver** [comment]
> Can we keep hardcoding the ami in `example-full.yaml` at least so it remains full? For reference the AMI should be `ami-0387d929287ab193e`
> 
> On a related note, perhaps we could also add a comment here https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/aws/config.py#L40 stating to update the examples if we update the dictionary (you can assign me a TODO to make it a unit test)

oh, that's where these images are defined. 👌 
done. ptal.

**Review by wuisawesome — APPROVED** [review]
thanks!

**Comment by wuisawesome** [comment]
Final thing, can you update the PR description and stuff?

**Comment by wuisawesome** [comment]
nvm actually i can do it

**Comment by gjoliver** [comment]
thanks man. this is a doc only PR.
these RLlib and Tune test failures are unrelated.
merging.

**Pull request merged**
