### PR TITLE
[Java] upgrade protobuf-java

### LINKED ISSUE #23626: [Bug] Upgrade `protobuf-java`
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

From Maven page for Ray serve, it looks like the `protobuf-java` dependency has a vulnerability: https://mvnrepository.com/artifact/io.ray/ray-serve/1.11.0

### Versions / Dependencies

Java for Ray serve, Ray 1.11.0

### Reproduction script

n/a

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
To resolve a reported vulnerability: https://mvnrepository.com/artifact/io.ray/ray-serve/1.11.0

## Related issue number
Closes #23626

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jovany-wang — APPROVED** [review]

**Comment by jovany-wang** [comment]
I believe this PR is compatibility safe to merge because it changes minor version number.
Maybe @liuyang-my CC

**Comment by mwtian** [comment]
Yeah, protobuf serialization format change would definite be a major version change.

**Comment by liuyang-my** [comment]
Looks good.

**Comment by jovany-wang** [comment]
It could be merged once CI passes.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
