### PR TITLE
Adding documentation for building from current master without cloning.

### PR DESCRIPTION
**Pull request by devin-petersohn**
It might be useful for downstream projects to build from the current master without having to clone. This additional doc explains how.

### CODE REVIEW

**Comment by robertnishihara** [comment]
The documentation looks good to me.

Do you find it useful to do this? In the past I feel like I've seen `pip install` hang when trying to install from GitHub (or error messages would be suppressed if you don't have some dependency like `cmake` installed or things like that).

Maybe add a note indicating that this approach may be less reliable? If you think it's reliable enough then no need to.

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
Note that I just ran this on my mac and it worked fine (though it took a little while). However, I already have all of the relevant dependencies installed and I'm not sure about the behavior when you don't have them installed.

**Comment by devin-petersohn** [comment]
It does give you the error when it fails. I have had a couple of people try it without having the `brew` dependencies, and it gives you the failure stack. We could add a note saying that it still requires the dependencies above.

I don't think it takes any longer than building from source normally does, this is just nicer for building downstream apps.

**Comment by robertnishihara** [comment]
Ok then I think it's good as is, thanks!

**Comment by robertnishihara** [comment]
Went ahead and merged it. Since it only changes the documentation, it's probably enough for the linting to pass (the linting tries to build the documentation).

**Pull request merged**
