### PR TITLE
[Job API] Handle multiple drivers with same job submission id in GCS GetAllJobInfo endpoint

### LINKED ISSUE #32213: [Ray 2.3 Release] Common failure in a few release tests `failed to connect to all addresses; last error: UNKNOWN`
The following stacktrace appears consistently in the following tests:
* air_benchmark_xgboost_cpu_10
* lightgbm_distributed_api_test
* xgboost_distributed_api_test

BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1351#018618c9-8c0d-4102-9420-c5cd8eb29b3d

```
Traceback (most recent call last):
--
  | File "ray_release/scripts/run_release_test.py", line 168, in <module>
  | main()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
  | return self.main(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
  | rv = self.invoke(ctx)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
  | return __callback(*args, **kwargs)
  | File "ray_release/scripts/run_release_test.py", line 153, in main
  | no_terminate=no_terminate,
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/glue.py", line 404, in run_release_test
  | raise pipeline_exception
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/glue.py", line 311, in run_release_test
  | command, env=command_env, timeout=command_timeout
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/command_runner/job_runner.py", line 115, in run_command
  | full_command, full_env, working_dir=".", timeout=int(timeout)
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/job_manager.py", line 113, in run_and_wait
  | return self._wait_job(cid, timeout)
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/job_manager.py", line 92, in _wait_job
  | status = self._get_job_status_with_retry(command_id)
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/job_manager.py", line 69, in _get_job_status_with_retry
  | max_retries=3,
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/util.py", line 119, in exponential_backoff_retry
  | return f()
  | File "/tmp/release-B1APUcfhbQ/release/ray_release/job_manager.py", line 66, in <lambda>
  | lambda: job_client.get_job_status(self.job_id_pool[command_id]),
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 396, in get_job_status
  | return self.get_job_info(job_id).status
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 331, in get_job_info
  | self._raise_error(r)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 262, in _raise_error
  | f"Request failed with status code {r.status_code}: {r.text}."
  | RuntimeError: Request failed with status code 500: {"result": false, "msg": "Traceback (most recent call last):\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py\", line 95, in _handler_route\n    return await handler(bind_info.instance, req)\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py\", line 391, in get_job_info\n    job_or_submission_id,\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/utils.py\", line 209, in find_job_by_ids\n    driver_jobs, submission_job_drivers = await get_driver_jobs(gcs_aio_client)\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/utils.py\", line 154, in get_driver_jobs\n    reply = await gcs_aio_client.get_all_job_info()\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py\", line 164, in wrapper\n    return await f(self, *args, **kwargs)\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py\", line 556, in get_all_job_info\n    reply = await self._job_info_stub.GetAllJobInfo(req, timeout=timeout)\n  File \"/home/ray/anaconda3/lib/python3.7/site-packages/grpc/aio/_call.py\", line 291, in __await__\n    self._cython_call._status)\ngrpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.254.44:9031: Failed to connect to remote host: Connection refused\"\n\tdebug_error_string = \"UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.254.44:9031: Failed to connect to remote host: Connection refused {created_time:\"2023-02-03T12:04:49.142935439-08:00\", grpc_status:14}\"\n>\n", "data": {}}.
```
EDIT(archit): here's the last line pretty-printed by chatgpt for readability
```
{
    "result": false,
    "msg": "Traceback (most recent call last):
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py\", line 95, in _handler_route
    return await handler(bind_info.instance, req)
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/job_head.py\", line 391, in get_job_info
    job_or_submission_id,
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/utils.py\", line 209, in find_job_by_ids
    driver_jobs, submission_job_drivers = await get_driver_jobs(gcs_aio_client)
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/utils.py\", line 154, in get_driver_jobs
    reply = await gcs_aio_client.get_all_job_info()
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py\", line 164, in wrapper
    return await f(self, *args, **kwargs)
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/gcs_utils.py\", line 556, in get_all_job_info
    reply = await self._job_info_stub.GetAllJobInfo(req, timeout=timeout)
  File \"/home/ray/anaconda3/lib/python3.7/site-packages/grpc/aio/_call.py\", line 291, in __await__
    self._cython_call._status)
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.254.44:9031: Failed to connect to remote host: Connection refused\"
    debug_error_string = \"UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.254.44:9031: Failed to connect to remote host: Connection refused {created_time:\"2023-02-03T12:04:49.142935439-08:00\", grpc_status:14}\"
>
",
    "data": {}
}
```

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
The changes to the `GetAllJobInfo` endpoint in https://github.com/ray-project/ray/pull/31046 did not handle the possibility that multiple job table jobs (drivers) could have the same submission_id. This can actually happen, for example if there are multiple `ray.init()` calls in a Ray Job API `entrypoint` command.  The GCS would crash in this case due to failing a `RAY_CHECK` that the number of jobs equaled the number of `submission_id`s seen.

This PR updates the endpoint to handle the above possibility, and adds a unit test which fails without this PR.

## Related issue number

Closes https://github.com/ray-project/ray/issues/32213
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
The tests in the release blocking issue all pass now, whereas previously they all had the same error 
`[2023-02-03 12:04:40,254 C 172 172] (gcs_server) gcs_job_manager.cc:191:  Check failed: job_api_data_keys.size() == job_data_key_to_index.size() 
`

Those tests are
```
air_benchmark_xgboost_cpu_10
lightgbm_distributed_api_test
xgboost_distributed_api_test
```

**Comment by architkulkarni** [comment]
This PR also adds a unit test which fails on master.

**Comment by cadedaniel** [comment]
Can we kick off one of the failing release tests with this change?

**Comment by architkulkarni** [comment]
rllib `rllib:learning_tests_stateless_cartpole_r2d2` flaky on master and unrelated
Docs broken on master, unrelated. (Failure is https://buildkite.com/ray-project/oss-ci-build-pr/builds/11900#01863a07-763c-42f2-99cd-a39b90ffaebf/1824-3487 which appears to be `data/getting-started`, unrelated)

**Comment by architkulkarni** [comment]
s

> Can we kick off one of the failing release tests with this change?

@cadedaniel All three of the failing release tests with this error pass with this change. https://buildkite.com/ray-project/release-tests-pr/builds/28049#_

**Review by edoakes — APPROVED** [review]
Great that our release tests caught this

**Comment by cadedaniel** [comment]
Nice fix @architkulkarni! Can we merge or should @iycheng review?

**Comment by zhe-thoughts** [comment]
@cadedaniel I think @edoakes 's approval is sufficient here.

**Comment by cadedaniel** [comment]
Let's merge!

**Comment by architkulkarni** [comment]
(cc @gvspraveen )

**Pull request merged**
