### PR TITLE
[core worker] Disable async connections

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This fixes a minor typo/bug in #14596

The diff should be self explanatory. 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Nice catch!

**Comment by kfstorm** [comment]
This change LGTM. @WangTaoTheTonic Do we have a better way to avoid this kind of bug?

**Review by WangTaoTheTonic — APPROVED** [review]
My bad. Thanks for the catch!

**Comment by wuisawesome** [comment]
Hey @WangTaoTheTonic this seems to be causing a segfault in test_actor. Do you happen to know why?

**Comment by WangTaoTheTonic** [comment]
I ran test_actor on my laptop 5 times and see no failure. Maybe it's flakey? Could not see relationship between the failure and this change. We can re-run and see what will happen.

**Comment by wuisawesome** [comment]
Hmm it does look a little flakey so I suppose it's possible (but it rarely fails 3 times in a row). I'll rerun the job and if it passes, let's merge it I guess.

**Comment by wuisawesome** [comment]
serve:test_failure looks unrelated. merging

**Pull request merged**
