### PR TITLE
[Dashboard] Sort IDLE workers to bottom in dashboard

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

This PR sorts IDLE node workers to the bottom of the list in the machine view.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests

### CODE REVIEW

**Review by mfitton — APPROVED** [review]
Looks great.

**Comment by rkooo567** [comment]
@simon-mo Could you merge this?

**Comment by rkooo567** [comment]
@krfricke Can you merge the latest master so that it will solve the linting issues?

**Comment by rkooo567** [comment]
Also, make sure that you ran frontend lint after that. https://github.com/ray-project/ray/blob/207ab44129e1c298c2c7594aaa6ca4150a09c130/ci/travis/ci.sh#L303

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
