### PR TITLE
[Dashboard] Add environment variable flag to skip dashboard log processing

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
This PR provides a temporary workaround for https://github.com/ray-project/ray/issues/24272.  

Adds a temporary environment variable flag to skip processing the logs in the dashboard head node.  When there are lots of logs, the dashboard can become overloaded, causing it to fail other API requests like job creation and job submission.  

In the long term, this log processing will be replaced with the result of the ongoing State Observability work, so we won't need this flag.

TODO before merge:
- [x] Add a test

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Tests pass locally.  

Should this be included in the Ray docs or not, given that it's a temporary patch?

**Comment by simon-mo** [comment]
lint failed?

**Comment by simon-mo** [comment]
no let's not document it right now

**Review by simon-mo — APPROVED** [review]
LGTM thx for doing this

**Review by edoakes — APPROVED** [review]

**Pull request merged**
