### PR TITLE
[Core/RuntimeEnv] Fix runtime environment hanging issues.

### LINKED ISSUE #19514: [runtime_env] Actor tasks aren't failed correctly when missing runtime_env dependencies
Actor tasks aren't failed correctly when missing runtime_env dependencies:
```python
a = A.remote()

(raylet) [2021-10-19 09:22:43,883 E 10336 4361605] agent_manager.cc:134: Not all required Ray dependencies for the runtime_env feature were found. To install the required dependencies, please run `pip install 'ray[default]'`.
ray.get(a.f.remote())
```

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

There are several issues with the current runtime environment that hangs scheduling. This PR handles all issues at once.

This is fixing 3 things

- When jobs are started, it creates the runtime env although the empty runtime env was given. 
- When the agent is permanently dead by 5 times retrying with exponential backoff) or the minimal deps are not provided, it hangs forever.
  - We properly call callback in this case now.
-  The actor task is hanging forever if the actor is failed to be started due to the runtime env

Note that we are still raising `RayActorError` which doesn't provide the good error message. I will create an issue to propagate runtime env related errors to the driver separately and fix issues (https://github.com/ray-project/ray/issues/19824) in a separate PR so that I can minimize the change within one PR. 

## Related issue number

Closes https://github.com/ray-project/ray/issues/19514 https://github.com/ray-project/ray/issues/17558

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]
This looks good to me, thanks for the fix!

**Review by edoakes — APPROVED** [review]
This is fantastic, thanks so much for the fixes!

**Review by scv119 — APPROVED** [review]

**Comment by carsonwang** [comment]
Is there any plan to release Ray 1.8.1? It will be great to include this fix. Right now we can't make RayDP work with Ray 1.8.0 because of this issue.

**Comment by rkooo567** [comment]
Cc @scv119 @ericl maybe we should have a .1 release?

**Pull request merged**
