### PR TITLE
[gcs/ha] Enable HA flags by default

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

PR to enable all three flags for GCS HA:
- RAY_bootstrap_with_gcs=1 
- RAY_gcs_grpc_based_pubsub=1 
- RAY_gcs_storage=memory

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
@mwtian  we can use this as a tester for CI failure.

**Comment by bveeramani** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've switched our code formatter from YAPF to Black (see #21311).

To prevent issues with merging your code, here's what you'll need to do:

1. Install Black
```
pip install -I black==21.12b0
```

2. Format changed files with Black
```
curl -o format-changed.sh https://gist.githubusercontent.com/bveeramani/42ef0e9e387b755a8a735b084af976f2/raw/7631276790765d555c423b8db2b679fd957b984a/format-changed.sh
chmod +x ./format-changed.sh
./format-changed.sh
rm format-changed.sh
```

3. Commit your changes.
```
git add --all
git commit -m "Format Python code with Black"
```

4. Merge master into your branch.
```
git pull upstream master
```

5. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated `format.sh`.

**Review by mwtian — APPROVED** [review]
Finally we are turning this on!

**Comment by DmitriGekhtman** [comment]
Thanks for the heads-up on this. We're not quite ready to merge this -- K8s support needs some minor modifications.

**Comment by DmitriGekhtman** [comment]
It should actually be possible to merge this today -- need to first follow up with some folks about a minor temporary process adjustment.

**Comment by DmitriGekhtman** [comment]
@zhe-thoughts @iycheng @mwtian 

There aren't further external blockers to merging this. 
Merging left to your discretion!

**Pull request merged**
