### PR TITLE
[Doc] Update KubeRay version to 1.0.0 (#40937)

### PR DESCRIPTION
**Pull request by architkulkarni**
Cherry-pick of https://github.com/ray-project/ray/pull/40937 to the release branch. This is a docs-only change.
 
PR description copied below:
 
 ---

This PR updates all 1.0.0 release candidate versions mentioned in the KubeRay docs to 1.0.0.

As this is a docs-only change, we plan to cherry-pick this into the Ray 2.8 branch, and rebuild/publish the Ray 2.8 docs.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]

**Comment by architkulkarni** [comment]
@vitsai premerge failed, but I think it's unrelated to the PR.  I restarted premerge for now, but if it keeps failing I think we should just merge it if the failure is unrelated

**Comment by architkulkarni** [comment]
@vitsai Premerge is failing, but the reason is unrelated to this PR.  The docs build has succeeded and the original PR didn't break the master build, so I think it's safe to merge this PR.

**Comment by architkulkarni** [comment]
@vitsai @can-anyscale Is it possible to bypass premerge for this? The failure is due to 

```
#7 153.0   WARNING: Requested tune-sklearn==0.4.6 from git+https://github.com/ray-project/tune-sklearn@master (from -r /ray/ci/env/../../python/requirements/ml/tune-requirements.txt (line 20)), but installing version 0.5.0
--
  | #7 153.0 ERROR: Cannot install tune-sklearn==0.4.6 because these package versions have conflicting dependencies.
  | #7 153.0
  | #7 153.0 The conflict is caused by:
  | #7 153.0     The user requested tune-sklearn==0.4.6
  | #7 153.0     The user requested (constraint) tune-sklearn

```
and
```
  ERROR: Cannot install tune-sklearn 0.5.0 (from git+https://github.com/ray-project/tune-sklearn@master#tune-sklearn) and tune-sklearn==0.4.6 because these package versions have conflicting dependencies.
  ```
  
  This is due to an update in an different repo (`tune-sklearn`).

**Comment by can-anyscale** [comment]
Yess, do you need reviews from ray-docs team; if not I can just merge, thankkks

**Comment by architkulkarni** [comment]
@can-anyscale no we don't need any review from ray-docs, this PR was already reviewed by ray-docs when it was merged to master.  If you could merge that would be great!

**Comment by can-anyscale** [comment]
merged thankks

**Comment by architkulkarni** [comment]
Hmm, I see, the readthedocs build is actually failing with the same error:

```
ERROR: Cannot install -r doc/requirements-doc.txt (line 3) and ray[tune]==2.8.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    tune-sklearn 0.5.0 depends on ray>=2.7.1
    ray[tune] 2.8.0 depends on ray 2.8.0 (from https://files.pythonhosted.org/packages/ec/a9/45948b0cc252eef6c06c941d780042d1fffd0ba4a856febaebd5a5f8bf94/ray-2.8.0-cp310-cp310-manylinux2014_x86_64.whl (from https://pypi.org/simple/ray/))

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

So even though we merged this PR, the doc update isn't being reflected because readthedocs can't build it.  @justinvyu can you recommend any workaround for this?

**Comment by architkulkarni** [comment]
@justinvyu It looks like the last time this happened, a `tune-sklearn` version bump was reverted in the external `tune-sklearn` repo so the Ray build could go through, and then it was unreverted.  Is it feasible to do this again so the 2.8 docs can be updated, or alternatively can you recommend a way to fix this directly on the Ray 2.8 release branch?

**Pull request merged**
