### PR TITLE
[Serve] Update Serve Counter metric doc

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
Update the Serve Counter metric doc to mention the change in #43795

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by GeneDer — COMMENTED** [review]
The change LGTM, but just wondering why are we only updating the ones in the replicas? Will there be follow ups on updating all uses of counters from other components? Or was it intentionally left out for some specific reasons? 

There are many more places where Serve is using counter, just to name a few
- https://github.com/ray-project/ray/blob/9fe19b189bcd37545c19c4551828d96271dc8d96/python/ray/serve/handle.py#L169
- https://github.com/ray-project/ray/blob/9fe19b189bcd37545c19c4551828d96271dc8d96/python/ray/serve/multiplex.py#L82

**Review by GeneDer — COMMENTED** [review]
Sorry have to keep being nitpicking. Maybe those
- https://github.com/ray-project/ray/blob/6ef01ac3b781de4d00e3770cf0b0fa523a2883e8/doc/source/serve/monitoring.md?plain=1#L570
- https://github.com/ray-project/ray/blob/6ef01ac3b781de4d00e3770cf0b0fa523a2883e8/doc/source/serve/monitoring.md?plain=1#L577

**Review by GeneDer — APPROVED** [review]
LGTM!

**Review by edoakes — APPROVED** [review]
cc @alanwguo and @architkulkarni for visibility and a sanity check on the dashboard changes

**Pull request merged**
