### PR TITLE
[Java] Release actor instance reference when `Ray.exitActor()` is invoked

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

If the number of Java workers per process is set to be greater than 1, a Java worker process can hold multiple actors. If one of them calls `Ray.exitActor()`, the underlying `CoreWorker` instance and the underlying thread will exit, but the actor instance remains in `TaskExecutor.actorContextMap`, which is a memory leak bug.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ffbin — COMMENTED** [review]
@kfstorm There is windows compile error.

**Comment by kfstorm** [comment]
@ffbin fixed.

**Review by ffbin — APPROVED** [review]
LGTM

**Review by chaokunyang — APPROVED** [review]
LGTM

**Pull request merged**
