### PR TITLE
[Doc][AIR] Remove ray_lightning documentation and tests

### LINKED ISSUE #35893: [Doc] Remove stale Lightning docs and released tests
### Description

As we are migrating from ray_lightning to LightningTrainer, it becomes necessary to eliminate the old documentation to minimize any confusion for our users. Additionally, we should also remove the release tests for ray_lightning to streamline the testing process.

### Use case

_No response_

### PR DESCRIPTION
**Pull request by woshiyyya**
## Why are these changes needed?

Remove all the ray_lightning related documentation and tests. Rendered doc: https://anyscale-ray--36400.com.readthedocs.build/en/36400/

- CI tests: `python/ray/tests/ray_lightning`
- Release tests: `releases/ml_user_tests/ray-lightning`
- Removed ray-lightning in multiple requirements files
  - `doc/requirements-doc.txt`
  - `python/requirements/ml/requirements_upstream.txt`
  - `python/requirements/compat/requirements_legacy_compat.txt`
- Removed mentions of ray-lightning in our doc: 
  - `doc/source/ray-overview/eco-gallery.yml`
  - `doc/source/ray-more-libs/using-ray-with-pytorch-lightning.rst`

## Related issue number

Closes #35893 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by richardliaw — APPROVED** [review]

**Review by matthewdeng — APPROVED** [review]
<div><br/>via <a href="https://giphy.com/therokuchannel/">The Roku Channel</a> on <a href="https://giphy.com/gifs/therokuchannel-season-1-the-roku-channel-sushi-master-pjHRKW5BPhqiAcBjE3">GIPHY</a></div>

**Comment by scv119** [comment]
https://buildkite.com/ray-project/oss-ci-build-branch/builds/4571#0188df81-aabd-4dfe-b709-9c3bf64976ba

looks the failures are related

**Comment by scv119** [comment]
```


python ./ci/run/bazel_sharding/bazel_sharding.py --exclude_manual --index "${BUILDKITE_PARALLEL_JOB}" --count "${BUILDKITE_PARALLEL_JOB_COUNT}" --tag_filters=compat python/ray/tests/horovod/... python/ray/tests/lightgbm/... python/ray/tests/ml_py37_compat/... python/ray/tests/xgboost/... python/ray/tests/ray_lightning/... &&
--
  | python ./ci/run/bazel_sharding/bazel_sharding.py --exclude_manual --index "${BUILDKITE_PARALLEL_JOB}" --count "${BUILDKITE_PARALLEL_JOB_COUNT}" --tag_filters=-gpu,-needs_credentials,-hdfs python/ray/air/... &&
  | python ./ci/run/bazel_sharding/bazel_sharding.py --exclude_manual --index "${BUILDKITE_PARALLEL_JOB}" --count "${BUILDKITE_PARALLEL_JOB_COUNT}" --tag_filters=ray_air,-torch_1_11,-gpu_only,-gpu,-needs_credentials,-hdfs python/ray/train/... &&
  | python ./ci/run/bazel_sharding/bazel_sharding.py --exclude_manual --index "${BUILDKITE_PARALLEL_JOB}" --count "${BUILDKITE_PARALLEL_JOB_COUNT}" --tag_filters=ray_air python/ray/data/...;
  | } > test_shard.txt
  | + python ./ci/run/bazel_sharding/bazel_sharding.py --exclude_manual --index 0 --count 3 --tag_filters=compat python/ray/tests/horovod/... python/ray/tests/lightgbm/... python/ray/tests/ml_py37_compat/... python/ray/tests/xgboost/... python/ray/tests/ray_lightning/...
  | Loading: 0 packages loaded
  | DEBUG: /ray/bazel/ray_deps_setup.bzl:67:14: No implicit mirrors used because urls were explicitly provided
  | ERROR: no targets found beneath 'python/ray/tests/ray_lightning'
  | Loading: 2 packages loaded
  | Loading: 2 packages loaded


```

**Comment by woshiyyya** [comment]
@scv119 Looking into it

**Comment by woshiyyya** [comment]
@scv119 Seems that I haven't remove the ray_lightning dependency in this new `Ray Python 3.7 ML compatibility tests`.

I created a fix PR here: https://github.com/ray-project/ray/pull/36673

**Pull request merged**
