### PR TITLE
[runtime env] Make all plugins return a `List` of URIs

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
Followup from #24622.  This is another step towards pluggability for runtime_env.  Previously some plugin classes had `get_uri` which returned a single URI, while others had `get_uris` which returned a list.  This PR makes all plugins use `get_uris`, which simplifies the code overall.

Most of the lines in the diff just come from the new `format.sh` which sorts the imports.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by SongGuyang** [comment]
Ready to review? A lot tests failed.

**Review by SongGuyang — APPROVED** [review]
LGTM!

**Review by edoakes — APPROVED** [review]

**Comment by edoakes** [comment]
@architkulkarni a lot of test failures in CI

**Comment by architkulkarni** [comment]
“Potable-water” test_raydp_dataset flaky on master
“Mac, C++ Libraries” /python/ray/dashboard:modules/serve/tests/test_serve_head flaky on master
Lint 
`/root/go_dir/src/google.golang.org/protobuf/proto/equal.go:36:33: undefined: reflect.Pointer` was broken on master
Broken link 
`(data/creating-datasets: line  228) broken    https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.html - 404 Client Error: Not Found for url: [https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.html`](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.html%60) was broken on master and unrelated

Some of these are fixed on master but I'd rather merge this PR than wait for another round of tests and possibly other failures.

**Pull request merged**
