### PR TITLE
[Dashboard] Machine View Using New API

### PR DESCRIPTION
**Pull request by mfitton**
## Why are these changes needed?
These changes are needed to introduce some new endpoints that match the new API we are moving to and to move the Machine view over to using that API. 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [x] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by rkooo567** [comment]
After merging this PR, is our old dashboard backend not usable anymore? Or are they having the compatible APIs?

**Comment by mfitton** [comment]
@rkooo567 they will have compatible APIs. This doesn't break backwards compatibility.

**Comment by rkooo567** [comment]
@mfitton Can you resolve the merge conflict? I will review this by next Mon.

**Review by rkooo567 — APPROVED** [review]
LGTM, but I am a little worried about that this can introduce regression in the next release (because we don't test it at all). But, at the same time, I understood adding tests could be a little bit of waste of time. What do you think is the best solution in this case?

**Comment by mfitton** [comment]
@rkooo567 it may introduce regressions, you're right. I do think that adding tests at this point would be wasted effort. I'm thinking that we will never release this code under a stable release, though that may be overly optimistic.

**Comment by mfitton** [comment]
Also I need to fix conflicts.

**Comment by mfitton** [comment]
@rkooo567 this PR is getting somewhat far out of date, and I'm realizing it might be easier to transition to the Ant API in one big PR so that I don't need to re-implement their functionality all in our backend. This PR has some downsides like making the dashboard's performance worse, so I don't really want to end up having a stable release that includes this PR.

**Comment by mfitton** [comment]
Right now I'm thinking of just closing this PR and pulling the changes from this and my logical view transition branch into one.

**Pull request closed without merging**
