### PR TITLE
[Core] zero-copy serializer for pytorch

### LINKED ISSUE #4855: Pytorch's `requires_grad` attribute isn't serialized
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.3
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.5
- **Python version**:  3.7.3
- **Exact command to reproduce**:

```python
import pyarrow as pa
import torch

# Create a tensor that requires a gradient
value = torch.tensor([], requires_grad=True)

# Set up the context
context = pa.default_serialization_context()
pa.register_torch_serialization_handlers(context)

# Write
scratch_buffer = pa.allocate_buffer(32*2**20)
writer = pa.FixedSizeBufferWriter(scratch_buffer)
pa.serialize_to(value, writer, context=context)

# Read
reader = pa.BufferReader(scratch_buffer)
result = pa.deserialize_from(reader, None, context=context)

# No longer requires gradient :(
result.requires_grad
```

### Describe the problem
If you serialize and deserialize a Pytorch tensor, `requires_grad` always comes back `False`. It's a problem with Pyarrow, but while writing up an issue in their tracker I realised my Pyarrow version was `0.12.0.RAY` so I don't want to drop it on their laps first - I don't know how serious Ray's modifications to Pyarrow are.

To catch some error-message-googling: my immediate symptom was passing a `torch.nn.Module` through the Ray object store and getting a 
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
error when I tried to backprop through it. The immediate workaround is to add a custom serializer for torch modules, with 
```python
ray.register_custom_serializer(torch.nn.Module, use_pickle=True)
```

### LINKED ISSUE #12317: [Core] Zero Copy Read not working for PyTorch Tensor
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

@wuisawesome found this bug:
```python
import torch
import ray
import psutil
import numpy as np

ray.init()
def mem():
    return psutil.Process().memory_full_info().rss

def test(arr):
    ref = ray.put(arr)
    start = mem()

    one_get = [ray.get(ref)]
    delta_1 = mem()

    ten_get = [ray.get(ref) for _ in range(10)]
    delta_2 = mem()

    print(f"memory growth for: {type(arr)}, 1x get {delta_1}, 10x get {delta_2}")


pt_arr = torch.zeros(128,3,224,224)
np_arr = np.zeros((128,3,224,224))

test(pt_arr)
test(np_arr)
```

Output:
```
$  /tmp python mem.py
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2020-11-23 15:33:49,801	INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265
memory growth for: <class 'torch.Tensor'>, 1x get 426221568, 10x get 1196986368
memory growth for: <class 'numpy.ndarray'>, 1x get 1505411072, 10x get 1505435648
```
Basically you can see that np array incurs little memory growth but pytorch tensor got deserialized each time.

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

When shifted from PyArrow, we lost zero-copy serialization for torch tensors. This PR not only recovers the zero-copy serialization, it also fixes several bugs in the original serializer.

## Related issue number

Closes #4855
Closes #12317 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by suquark** [comment]
This PR should be ok. I'll add more tests later.

**Review by simon-mo — APPROVED** [review]

**Comment by sven1977** [comment]
The torch import in serialization_addons.py breaks our RLlib test (test_dependency_torch), which checks whether everything would still work, even if torch were not installed (e.g. for tf-only users).
Solution: Use `from ray.rllib.utils.framework import try_import_torch; torch, nn = try_import_torch()`.

**Comment by simon-mo** [comment]
@suquark any chance we can bring in back in?

**Comment by msaroufim** [comment]
+1 this was a really cool feature

**Pull request merged**
