### PR TITLE
[Core] Write ray address even if ray node is started with --block

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
With #26678, when a ray cluster is started, its address is written to `/tmp/ray/ray_current_cluster` so `ray.init()` can find the existing cluster and connect to it by default. However if a node is started with `ray start --block`, the file is not created so `ray.init()` will create a new cluster instead of connecting to the existing one, which is unexpected.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
I'll add tests but want to open the PR first to see if we want to include it in 2.3.1 (my vote is yes). I have seen two users encountered this issue. cc @ericl

**Comment by ericl** [comment]
This seems harmless enough to include!

**Comment by jjyao** [comment]
@ericl it's ready for review.

**Review by ericl — APPROVED** [review]

**Comment by zhe-thoughts** [comment]
+1 to cherry-pick to 2.3.1 since it's a low risk change

**Pull request merged**
