### PR TITLE
[serve] Always run router for `DeploymentHandle` in separate event loop thread

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

There is currently some logic to distinguish whether a given `DeploymentHandle` is intended to be used in a sync or an async context. However, this is imperfect and could result in broken behavior (e.g., if a user wants to use a handle in an async context _outside_ of a replica).

Additionally, there are some possible pitfalls with running the router logic within the main asyncio event loop:

- user code that blocks or overloads the loop can starve the router and cause requests to not be scheduled.
- sending handle requests is not eager, it won't happen until the next `await`, which may be confusing for users (e.g., if they make a handle call then immediately do a blocking inference operation).

This PR addresses all of these problems by _always_ running the router on its own asyncio event loop in its own thread. Interacting with the router always goes through the `concurrent.futures.Future` thread-safe interface.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by edoakes** [comment]
Running the added handle throughput benchmark w/ the change:
```
DeploymentHandle throughput (num_replicas=10, batch_size=100): 2219.45 +- 20.17 requests/s
```

vs. baseline (master):
```
DeploymentHandle throughput (num_replicas=10, batch_size=100): 2306.67 +- 36.98 requests/s
```

**Comment by edoakes** [comment]
There's an issue with `_get_or_create_router` that needs to be addressed before merging this: the logic to construct the router is now conditional on the class, but we create the router and then pass it in before updating the class. Need to think of a solution here.

**Review by GeneDer — APPROVED** [review]
LGTM!

**Comment by edoakes** [comment]
This now depends on https://github.com/ray-project/ray/pull/39832

**Pull request merged**
