### PR TITLE
[gcs] turn on grpc pubsub by default

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Turn on grpc pubsub by default.  This PR also fixed several tests which are failed before.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by WangTaoTheTonic** [comment]
Do we have any test report to show that there's or there's no regression after turning it on by default?

**Comment by mwtian** [comment]
@WangTaoTheTonic do you mean scalability tests and benchmarks? We will be working on those.

**Comment by WangTaoTheTonic** [comment]
> @WangTaoTheTonic do you mean scalability tests and benchmarks? We will be working on those.

yeah. Switching pubsub from redis to grpc will increase memory and cpu cost of gcs, in theory. Maybe we need some benchmarks with large pubsub actions(like many actors failover and restart) to see how much cost this will bring.

**Comment by iycheng** [comment]
@WangTaoTheTonic  this is just for turning the flag on and if there are things wrong, we'll revert it back. Btw, we have already had stress tests running daily.

**Comment by WangTaoTheTonic** [comment]
@iycheng could you share the stress tests and observe how gcs memory and cpu changes after turning this flag on?

**Review by mwtian — APPROVED** [review]

**Comment by iycheng** [comment]
> @iycheng could you share the stress tests and observe how gcs memory and cpu changes after turning this flag on?

Hi @WangTaoTheTonic we are measuring the metrics from the stress test right now. It's similar to the current value where you can find in the release folder. As I said, we are only turning the flags on for now and polishing this work. Some metrics haven't been covered yet which we'll do before deleting the code. Btw, please also help us test this and share some results with us.

**Comment by iycheng** [comment]
java test is flaky on master

**Comment by rkooo567** [comment]
@iycheng for those stress tests we ran with grpc pubsub on, we already have measured the memory usage. I believe it was similar.

There are workloads that can stress the pubsub layer a lot though. For example, if there are lots of logs, it can stress GCS a lot. I am not sure about the actor workload because pubsub is already using batch mechanism, and the amount of pubsub connection should be quite small, but we should still run some tests (failover tests sound good).

**Pull request merged**
