### PR TITLE
restructure how to organize 3rd party libs

### PR DESCRIPTION
**Pull request by imzhenyu**
This refactors the structure of 3rd party libs:

 - move all 3rd party libs into ```top-dir/thirdparty```
 - have all ```build_xxx.sh``` moved to ```top-dir/thirdparty/scripts```
 - have all downloaded source code and build process in ```top-dir/thirdparty/build```
 - have all libs with their installation dir in ```top-dir/thirdparty/pkg```
 - have one single ```setup.sh``` in ```top-dir/thirdparty/scripts``` for all download and build
 - have one single ```thirdparty.cmake``` in ```top-dir/thirdparty/scripts```  for all preparation work of ```find_package``` later
 - have a top level ```setup_thirdparty.sh``` for one time initialization
 - have the ```setup_thirdparty.sh``` invoked in top level ```build.sh``` when necessary

### CODE REVIEW

**Comment by imzhenyu** [comment]
@robertnishihara @pcmoritz Please take a look (seems I cannot setup reviewers for the PR).

**Comment by robertnishihara** [comment]
@imzhenyu this looks great! Can you add these changes https://github.com/imzhenyu/ray/pull/1?

@pcmoritz may have additional comments.

EDIT: Actually I was able to push it myself.

**Comment by robertnishihara** [comment]
I'm running into compilation errors on Linux.

**Comment by imzhenyu** [comment]
@robertnishihara Thx for the fix~ Since there are conflicts, what is the practice in Ray? We usually require people to rebase for that...

**Comment by robertnishihara** [comment]
@imzhenyu, ah yes, we just rebase. I'm happy to do that (it'll be quick).

**Review by robertnishihara — APPROVED** [review]

**Review by pcmoritz — APPROVED** [review]

**Comment by robertnishihara** [comment]
The tests have passed on ray-private-travis (modulo some seemingly unrelated test failures).

**Pull request merged**
