### PR TITLE
[Train][Tune] Add Horovod to ML requirements

### PR DESCRIPTION
**Pull request by bveeramani**
## Why are these changes needed?

Both Train and Tune depend on Horovod, but Horovod is not specified in any of the requirements files.
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(

### CODE REVIEW

**Comment by richardliaw** [comment]
We're installing horovod a different way i think? via source somewhere

**Comment by bveeramani** [comment]
> We're installing horovod a different way i think? via source somewhere

Do you happen to know where I can find that? If Horovod is installed via source, then the [Building Ray (Python Only)](https://docs.ray.io/en/latest/development.html#building-ray-python-only) instructions won't work.

**Comment by richardliaw** [comment]
Sorry, what are you trying to do here? The current PR adds horovod into the
testing/docker infra but not the actual Ray tune/train pip installations.
(Also we don’t want a hard dependency on horovod so doing the latter
wouldn’t make sense )

**Comment by richardliaw** [comment]
Hmm, why is it that you expect Horovod to be installed if you install ray?

Train/Tune don't strictly depend on Horovod; there's an integration but it's a soft dependency

**Comment by amogkam** [comment]
That's right @bveeramani these requirement files are not supposed to be installed for development. These are used for CI and Ray Docker images.

We don't have a canonical requirements file for development for all of Ray and its integrations. If you want to use horovod with Ray Train, you would need to manually install it yourself.

**Pull request closed without merging**
