### PR TITLE
Flush all tasks from local lineage cache after a node failure

### LINKED ISSUE #4958: Flush lineage cache after a node failure
### Describe the problem
As of #4942, the raylet where a task is submitted will flush a task to the GCS instead of the raylet where a task is executed. This means that if a node dies before it can flush a task, it's possible that no one will ever flush the task. This can lead to a memory leak in the lineage cache.

The proposed solution is to have every node flush their local lineage cache if any node fails.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

This flushes all uncommitted tasks from the local lineage cache to the GCS after a node failure. This is to guarantee that all tasks are eventually flushed.

## Related issue number

Follow-up to #4359, closes #4958.

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

**Review by robertnishihara — APPROVED** [review]
This looks good to me.

**Review by pcmoritz — APPROVED** [review]
LGTM

**Comment by pcmoritz** [comment]
There is some linting that needs to be fixed btw :)

**Comment by stephanie-wang** [comment]
> There is some linting that needs to be fixed btw :)

Thanks! Apparently `scripts/format.sh` fails silently if `clang-format` isn't found...

**Comment by robertnishihara** [comment]
Seems like linting is still an issue :(

**Pull request merged**
