### PR TITLE
[CI][Jailed] Add jailed flag for release tests

### PR DESCRIPTION
**Pull request by can-anyscale**
## Why are these changes needed?
The discussion about test policy, in particular, [jailed tests](https://docs.google.com/document/d/1hV8avu2Xl16Di3zVXyFtjuhZ8OGFDWhEt7Am319bki0/edit#heading=h.tdxb82dxifm7) seem to go well. I'm adding this flag now so we can start to jail some tests. Here is the policy of jailed tests:

- Tests are jailed if the corresponding issue tasks missed it SLA
- Jailed tests are skipped/non-blocking by default on automatic master run
- Jailed tests run/block by default on release + manually triggered runs

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- Testing Strategy
   - [X] Unit tests
   - [X] Release tests - will jailed some tests and test on top of this PR

https://buildkite.com/ray-project/release-tests-pr/builds/36193 - did not run the ray-data tests which are jailed

### CODE REVIEW

**Comment by can-anyscale** [comment]
Pending this until we all agree about test state

**Review by aslonnie — COMMENTED** [review]
could you restate what jailed test mean? specifically:

- so we will skip all jailed tests?
- does a jailed test make the build red?
- does a jailed test block release?

**Comment by jjyao** [comment]
Currently policy for unstable tests:

- They do not block releases.
- They run automatically like other tests.
- Unstable tests should eventually be converted to stable tests but currently there is no SLA for it.

I think we still need to keep these two concepts since one blocks release and one doesn't.

**Review by jjyao — APPROVED** [review]

**Comment by can-anyscale** [comment]
Sound good, thanks @jjyao. It's interesting that unstable tests do not block releases ;).

**Comment by jjyao** [comment]
Yea, ideally we should have an SLA for when an unstable test should be converted back to stable or the test should just be removed.

**Review by aslonnie — APPROVED** [review]

**Pull request merged**
