### PR TITLE
[Draft] Revert "Upgrading Redis to 6.0.10 in order to be functional on Apple …

### PR DESCRIPTION
**Pull request by ijrsvt**
…silicon (M1) (#14299)"

This reverts commit 153dcd3734719d68b0ab2c9c0d4bec1fa85eaf87.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jirkafajfr** [comment]
May I ask whats the problem with the #14299?

**Comment by ijrsvt** [comment]
Hi @jirkafajfr I'm just looking into a segfault that was introduced around when #14299 .

**Comment by ijrsvt** [comment]
This segfault still appears in this revert: 


Screen Shot 2021-03-15 at 2 29 07 PM


cc @ericl

**Comment by ijrsvt** [comment]
Closing because the segfault still appears in this revert draft.

**Pull request closed without merging**
