### PR TITLE
Revert "[Dashboard] Start the new dashboard (#9860)"

### PR DESCRIPTION
**Pull request by robertnishihara**
This reverts commit 739933e5b84291dea54c29fc6acc982a3d42a52f.

https://github.com/ray-project/ray/pull/9860 broke Windows.

### CODE REVIEW

**Comment by robertnishihara** [comment]
cc @raulchen @fyrestone

**Review by mfitton — APPROVED** [review]
Approved revert, pull breaks windows build.

**Comment by rkooo567** [comment]
@fyrestone Please feel free to reopen the PR. I will also send a slack message. The issue here was that our Windows build failed due to this change. Please create a new PR that addresses that issue! 

The error was previously
```
bazel-out/x64_windows-opt/bin/_virtual_includes/raylet_lib\ray/raylet/agent_manager.h(51): error C3646: 'agent_pid_': unknown override specifier
383
bazel-out/x64_windows-opt/bin/_virtual_includes/raylet_lib\ray/raylet/agent_manager.h(51): error C2059: syntax error: '='
384
bazel-out/x64_windows-opt/bin/_virtual_includes/raylet_lib\ray/raylet/agent_manager.h(51): error C2238: unexpected token(s) preceding ';'
```

**Comment by fyrestone** [comment]
> @fyrestone Please feel free to reopen the PR. I will also send a slack message. The issue here was that our Windows build failed due to this change. Please create a new PR that addresses that issue!
> 
> The error was previously
> 
> ```
> bazel-out/x64_windows-opt/bin/_virtual_includes/raylet_lib\ray/raylet/agent_manager.h(51): error C3646: 'agent_pid_': unknown override specifier
> 383
> bazel-out/x64_windows-opt/bin/_virtual_includes/raylet_lib\ray/raylet/agent_manager.h(51): error C2059: syntax error: '='
> 384
> bazel-out/x64_windows-opt/bin/_virtual_includes/raylet_lib\ray/raylet/agent_manager.h(51): error C2238: unexpected token(s) preceding ';'
> ```

Sorry for the break. I will fix this problem. It's wired that the type `pid_t` is used in `NodeManager::ProcessRegisterClientRequestMessage`, and compile is OK.

**Comment by fyrestone** [comment]
Please feel free to review the PR: https://github.com/ray-project/ray/pull/10131

**Comment by fyrestone** [comment]
I noticed that the `windows-msvc windows-msvc` is always `RED`, why you guys merged these PRs to master?

**Comment by rkooo567** [comment]
.Window-msvc is always red because of test failures, but your original PR broke the build itself (so it couldn’t even start)

**Comment by robertnishihara** [comment]
@fyrestone @rkooo567 the "always red" state is a big problem (which is why PRs like this get merged accidentally). I'll try to fix that this weekend.

**Pull request merged**
