### PR TITLE
[Dashboard] Include the dashboard in Windows wheels

### PR DESCRIPTION
**Pull request by pcmoritz**
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
I just tested the wheel I pushed to test wheels (e.g. the one for 3.7 is under `https://s3-us-west-2.amazonaws.com/ray-wheels/test_wheels/windows_dashboard/680fee7d019c711ce639f3e7c8d2a72f465d667e/ray-2.0.0.dev0-cp37-cp37m-win_amd64.whl`) and the dashboard is running now 🥳

**Review by simon-mo — COMMENTED** [review]
LGTM as long as CI is happy

**Review by simon-mo — APPROVED** [review]
LGTM as long as CI is happy

**Comment by kk-55** [comment]
> 
> 
> Yayyyy! I can finally see the dashboard in windows, and it's nice :) (also the experimental one works)

@carlogrisetti what did you do that it is working for you now?
I tried to install the wheel for 3.8 but I can't see the dashboard (still connection refused error).

**Comment by carlogrisetti** [comment]
Where did you get the wheel from?
Are you trying to access the dashboard on the same machine is it running from?

**Comment by kk-55** [comment]
@carlogrisetti solved
I completely removed ray and did a new install of ray with the proposed wheel 

> 
> 
> I just tested the wheel I pushed to test wheels (e.g. the one for 3.7 is under `https://s3-us-west-2.amazonaws.com/ray-wheels/test_wheels/windows_dashboard/680fee7d019c711ce639f3e7c8d2a72f465d667e/ray-2.0.0.dev0-cp37-cp37m-win_amd64.whl`) and the dashboard is running now 🥳

Thanks anyway!

**Comment by carlogrisetti** [comment]
@kk-55 Nice :)

**Comment by 19greg96** [comment]
Should this work in 1.8.0? I tried with the wheels for 3.7 and 3.8, (ray 1.8.0) but I still get connection reset. Installing the aforementioned ray-2.0.0.dev0 wheel works.

note: I use conda on windows to create virtual environments, and use pip to install packages. Dashboard directory still missing the client directory with the 1.8.0 release.

**Comment by carlogrisetti** [comment]
I had some issues (albeit different) with the prepackaged distribution. Using the latest "nightly" wheel it all works fine.
I suppose something was missing from the official stable release, but I suppose it will be present in the next one.

**Comment by 19greg96** [comment]
Great, thanks! I'm looking forward to it.

**Pull request merged**
