### PR TITLE
[GCS]Fill resource fields when re-report heartbeat after gcs restarted

### PR DESCRIPTION
**Pull request by WangTaoTheTonic**
## Why are these changes needed?

~~As extra option of https://github.com/ray-project/ray/pull/12082 and avoid reverting large piece of codes, we can just disable the light heartbeat.~~

We just fix the re-reporting issue when gcs restart in this PR.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Since we already skipped all failing tests, we can instead just troubleshoot them? I think the issue only occurs in a restart path (which is not well supported in OSS anyway)

**Review by ffbin — APPROVED** [review]
LGTM

**Comment by WangTaoTheTonic** [comment]
> Since we already skipped all failing tests, we can instead just troubleshoot them? I think the issue only occurs in a restart path (which is not well supported in OSS anyway)

Yeah. That sounds good. I'll try to fix it instead.

**Comment by WangTaoTheTonic** [comment]
tests:test_actor_failures timed out. Gonna retry.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Windows build is failing. I am 99% sure it is not related to this PR, but can you just merge the latest master just in case?

**Review by ffbin — APPROVED** [review]
LGTM

**Pull request merged**
